### ISSUE TITLE
UNMET PEER DEPENDENCY

### ISSUE THREAD

**Issue by totouraMan** [GeekyAnts/NativeBase#100]
I found this error in my console. I tried several times, until I updated my software.
Any suggestions will be appreciated.

**NODE: 4.4.7
NPM: 2.15.8
REACT-NATIVE: 0.31.0
NATIVE-BASE: 0.5.4**

`npm WARN native-base@0.5.4 requires a peer of react-native@>=0.26.0 but none was installed.
npm WARN native-base@0.5.4 requires a peer of react@>=15.0.2 but none was installed.
npm WARN native-base@0.5.4 No license field.`

**Comment by SupriyaKalghatgi** [comment]
@totouraMan I guess you did not go through system requirements.
Check [here](http://nativebase.io/docs/v0.5.2/getting-started)
