### ISSUE TITLE
PropTypes error with react 16

### ISSUE THREAD

**Issue by porfirioribeiro** [GeekyAnts/NativeBase#1001]
native-base should make use of `prop-types` package instead of React.PropTypes

react-native: 0.45.1
react: 16.0.0-alpha.13
native-base:2.1.5

With the latest alpha versions of react, they completely removed React.PropTypes,
and my code does not work

**Comment by sankhadeeproy007** [comment]
@sean-macfarlane [here](https://github.com/GeekyAnts/theme/tree/transpiled). It's in `transpiled` branch.

**Comment by sean-macfarlane** [comment]
@sankhadeeproy007 thanks! I have created a PR that fixes this [https://github.com/GeekyAnts/theme/pull/2](url)

**Comment by sankhadeeproy007** [comment]
Great! Thanks.

**Comment by porfirioribeiro** [comment]
Good work!

**Comment by brycejacobs** [comment]
Any idea when his PR will be pulled in?

**Comment by sebandres** [comment]
Excuse my ignorance but wouldn't native-base also require changes? like: [Text.js](https://github.com/GeekyAnts/NativeBase/blob/master/src/basic/Text.js) making use of React.PropTypes

**Comment by shivrajkumar** [comment]
Yes, All the components of NativeBase will need to have the changes.
Will be done in the next release

**Comment by sebandres** [comment]
I've made the changes already, should I submit a PR on top of this issue as well?

**Comment by shivrajkumar** [comment]
That would be awesome

**Comment by sebandres** [comment]
Cool @shivrajkumar! 
Will run a few more tests with the branch on my fork and submit the PR.

**Comment by brycejacobs** [comment]
I think you may be able to use the jscodeshift tool to do it quickly. 

```bash
jscodeshift -t react-codemod/transforms/React-PropTypes-to-prop-types.js /NativeBase/src
```

**Comment by sebandres** [comment]
Hey guys, apologies for the delay. Plenty of dependencies to solve!

**Comment by sebandres** [comment]
This is the status of this:
- native-base-shoutem-theme: pulled changes and released version 0.2.1 with the fix.
- react-native-drawer: pulled @sean-macfarlane changes but hasn't released a new version.
- react-native-keyboard-aware-scroll-view: has the fixes in master but needs to publish a new version- -
- shoutem/animation: waiting for [PR](https://github.com/shoutem/animation/pull/19) to be pulled with fixes.

[This Branch](https://github.com/sebandres/NativeBase/tree/upgrade-to-react-native-46-1) has a working version of NativeBase with the above 'pending changes' hardcoded on the package.json, feel free to comment if anything is not 100%!

Once all fixes are applied I'll update the versions of the packages to remove the direct reference to the repos/branches.

**Comment by sean-macfarlane** [comment]
hey @sebandres yesterday @shivrajkumar actually released version 2.3.1 of NativeBase which has the fixes for package.json to use the correct dependencies. 

To clarify the dependencies: 
-  native-base-shoutem-theme: uses 0.2.1 which has my PR 
- react-native-drawer: they pulled my PR to the master, but it doesn't look like they do releases any more, so we're stuck with just the master branch.
- react-native-keyboard-aware-scroll-view: no release yet, so still the master branch.
- shoutem/animation: NativeBase does not use this dependency anymore

**Comment by sebandres** [comment]
Darn,

Too late :(

Thanks for the heads up!

**Comment by sebandres** [comment]
For react native drawer cant we fork that and publish a react native drawer
nativebase package to keep the dependencies tighter?

**Comment by shivrajkumar** [comment]
Yes, maybe we will do this in the next release.

**Comment by akhil-geekyants** [comment]
Issue resolved. Closing the issue.
