### ISSUE TITLE
iPhone 6 plus and 7 plus layout issues

### ISSUE THREAD

**Issue by jarredszabadi** [GeekyAnts/NativeBase#1002]
## react-native, react and native-base version
```
"native-base": "^2.1.5",
"react": "^16.0.0-alpha.6",
"react-native": "^0.44.0",
```

## Actual behaviour
On the plus sized phones(6+ and 7+) the elements of a CardItem are being collapsed. I don't fully know why but when I changed the fontSize of the text in my CardItem header it will fix the issue. 

```
<CardItem style={{flex: 1, marginRight:0, paddingRight:0, paddingLeft: 0, marginLeft:0,borderBottomWidth: 1, borderBottomColor: 'rgba(217, 213, 220, .5)', paddingBottom: 5}} header>
   <View  style={{flex: 1, paddingLeft: 5}}>
    <Text style={{fontSize: 18}}>
          Sensor Details
    </Text>
    </View>
 </CardItem>
```

## Screenshot of emulator/device

With fontSize: 18 my view looks like this:

![img_0087](https://user-images.githubusercontent.com/3138299/27741699-f972766c-5d83-11e7-8092-ca877635251c.PNG)

With fontSize:17 it looks like this:

![img_0088](https://user-images.githubusercontent.com/3138299/27741702-fa9c2150-5d83-11e7-8877-be8fc1eba1b1.PNG)

## Is the bug present in both ios and android or in any one of them?

iOS only, specifically only on the plus sized phones

## Any other additional info which would help us debug the issue quicker.
Works fine on the simulator.

**Comment by shivrajkumar** [comment]
@jarredszabadi This seems to be because of lineHeight of Text in Cards. You can just add lineHeight to the Text inside Cards

**Comment by jarredszabadi** [comment]
it was an rn issue. setting assets in xcode without the proper multiples mess with the iphone 6+ and 7. closing this issue.
