### ISSUE TITLE
[Android] Floating Label Bug

### ISSUE THREAD

**Issue by ParkHeeTae1** [GeekyAnts/NativeBase#1006]
**Environment**

react-native -v: 2.0.1
node -v: v6.10.3
npm -v: 3.10.10
yarn --version (if you use Yarn): 0.24.6
Then, specify:

Target Platform (e.g. iOS, Android): Android
Development Operating System (e.g. macOS Sierra, Windows 10): macOS Sierra
Build tools (Xcode or Android Studio version, iOS or Android SDK version, if relevant): Android SDK 26.0.2

**Actual Behavior**

![1](https://user-images.githubusercontent.com/29560569/27758289-b1b4553e-5e4b-11e7-8685-0ca6be1c9446.jpg)

My problem is disappear Label, when touch input.

I think that there seems to be a problem native-base/item.js .

why paddingBottom : 12 in Android??

in item.js

<Animated.View
key="float"
style={{
position: "absolute",
left: this.props.last ? 22 : 22,
right: 0,
top: this.state.topAnim,
opacity: this.state.opacAnim,
paddingTop: Platform.OS === "ios" ? undefined : undefined,
paddingBottom: Platform.OS === "ios" ? undefined : 12
}}
>

**Reproducible Demo**

<FloatingInput
itemStyle={{ alignItems: 'flex-end' }}
label="아이디(이메일)"
autoFocus={true}
keyboardType="email-address"
onChangeText={text => this.setState({ email: text })}
returnKeyType="next"
/>

**Comment by shivrajkumar** [comment]
@ParkHeeTae1 Check the latest of NativeBase i.e 2.2.1
