### ISSUE TITLE
Title isn't center aligned on Android

### ISSUE THREAD

**Issue by ErkanSen14** [GeekyAnts/NativeBase#101]
It seems on iOS the title is aligned in the center by default, however on Android it is not.

<img width="343" alt="screen shot 2016-08-05 at 4 43 50 pm" src="https://cloud.githubusercontent.com/assets/17013914/17451465/ab80e9b6-5b2c-11e6-90ae-0d82d8e80334.png">
<img width="367" alt="screen shot 2016-08-05 at 4 44 02 pm" src="https://cloud.githubusercontent.com/assets/17013914/17451466/ab94cd00-5b2c-11e6-8e2d-5d43fe4d8d7b.png">

**Comment by sankhadeeproy007** [comment]
That is desired effect as in android, the title is aligned to the left by default.
