### ISSUE TITLE
Can't remove elevation border from Fab's component

### ISSUE THREAD

**Issue by orelkabets** [GeekyAnts/NativeBase#1014]
Hi , is there any way to remove the elevation border from the Fab's component ? 

I have an more actions menu icon which opens the Fab's component and including the following styles:

<Fab
       style={{paddingTop:80, backgroundColor:'white',elevation:2,left:5}}
       containerStyle={{top: 40,right:0, width:40}}
         .... >
</Fab>

i tried to play with the border options from: 
https://reactnatve.wordpress.com/2016/06/10/supported-css-and-flex/

also if i reduce the elevation the Fab's button are not hidden:
![image](https://user-images.githubusercontent.com/20373128/27859435-64c204c2-6181-11e7-9b68-2b9fd22f9149.png)

but nothing seems to help...

any help ?? 

![image](https://user-images.githubusercontent.com/20373128/27859179-90b1625e-6180-11e7-99a4-73584b449501.png)

**Comment by akhil-geekyants** [comment]
@orelkabets to remove elevation, you can set `shadowOffset: { height: 0 }` and `shadowRadius:0` to fab style.

```
 style={{ backgroundColor: "#5067FF", shadowOffset: { width: 0, height: 0 }, shadowRadius: 0 }}
```

**Comment by orelkabets** [comment]
thanks @akhil-geekyants  that solved my problem

**Comment by orelkabets** [comment]
thanks @akhil-geekyants  that solved my problem
