### ISSUE TITLE
Property Last of List doesn't work

### ISSUE THREAD

**Issue by EpicNem** [GeekyAnts/NativeBase#1017]
Look at my code, I generate a dynamic list and I wanted to change the style of the last Item but it doesn't work. (The list is displayed, everything works, only the prop last didn't change anything)

`<List`
          `    last={{backgroundColor: 'blue'}}`
          `    dataArray={myData}`
          `    renderRow={(item) =>`
            `        <View>`
             `            <ListItem>`
                  `                <Text>{item.text}</Text>`
              `           </ListItem>`
            `        </View>`
          `     }>`
`</List>`

ps: sorry for indentation, I don't know how to do on GitHub.

**Comment by alexkuc** [comment]
To render a block of code, use three backticks, optionally providing syntax highlight. [Example](https://help.github.com/articles/creating-and-highlighting-code-blocks/)

**Comment by shivrajkumar** [comment]
@EpicNem `last` prop is used with ListItem, not List. And it is a boolean prop to apply proper border to the last element, not for passing any style rules
