### ISSUE TITLE
Unable to run Android or IOS after upgrade

### ISSUE THREAD

**Issue by jlcrow** [GeekyAnts/NativeBase#1019]
## react-native, react and native-base version
react-native: 0.45.1
react: 16.0.0-alpha.12
native-base: 2.2.0

## Expected behaviour
App should run

## Actual behaviour
App crashes in Android

App crashes in IOS

## Steps to reproduce
Existing app on:
"native-base": "2.0.13",
 "react": "15.4.2",
 "react-native": "0.42.3

Upgrade with react-native-git-upgrade

## Screenshot of emulator/device
<img width="750" alt="screen shot 2017-07-06 at 11 41 11 am" src="https://user-images.githubusercontent.com/4369807/27927198-00d86568-6259-11e7-982c-bb928607f2d0.png">

## Is the bug present in both ios and android or in any one of them?
Both crash in different places at launch
IOS crashes in this area of the bundle:
```
Object.defineProperty(exports, "__esModule", { value: true });var _lodash = require(735     );var _lodash2 = _interopRequireDefault(_lodash);function _interopRequireDefault(obj) { // 735 = lodash
  return obj && obj.__esModule ? obj : { default: obj };
}exports.default = mapPropsToStyleNames = function mapPropsToStyleNames(styleNames, props) {
  var keys = _lodash2.default.keys(props);
  var values = _lodash2.default.values(props);

  _lodash2.default.forEach(keys, function (key, index) {
    if (values[index]) {
      styleNames.push(key);
    }
  });

  return styleNames;
};
```
Android crashes in this area of the bundle:
`
     return _react2.default.createElement(_NativeButton2.default, {
        onPress: this.props.onPress,
        style: _styles2.default.swipeoutBtnTouchable,
        underlayColor: this.props.underlayColor,
        disabled: this.props.disabled,
        style: styleSwipeoutBtn,
        textStyle: styleSwipeoutBtnText, __source: { fileName: _jsxFileName, lineNumber: 83 } }, btn.component ? _react2.default.createElement(_reactNative.View, { style: styleSwipeoutBtnComponent, __source: { fileName: _jsxFileName, lineNumber: 92 } }, btn.component) : btn.text);
    } }], [{ key: "defaultProps", get: function get() {
      return { backgroundColor: null, color: null, component: null, underlayColor: null, height: 0, key: null, onPress: null, disabled: false, text: "Click me", type: "", width: 0 };
    } }]);return SwipeoutBtn;
}(_react.Component);exports.default = SwipeoutBtn;
`
## Other info
Have tried clearing cache, watchman, node modules fresh install error still occurs
package-json
```
{
	"name": "tw_mobile",
	"version": "0.0.1",
	"private": true,
	"scripts": {
		"start": "node node_modules/react-native/local-cli/cli.js start",
		"android": "react-native run-android",
		"ios": "react-native run-ios",
		"test": "jest"
	},
	"rnpm": {
		"assets": [
			"./assets/fonts"
		]
	},
	"dependencies": {
		"lodash": "~4.11.1",
		"native-base": "2.2.0",
		"react": "16.0.0-alpha.12",
		"react-native": "0.45.1",
		"react-native-barcode-builder": "1.0.1",
		"react-native-circular-progress": "0.0.8",
		"react-native-communications": "2.2.1",
		"react-native-config": "0.3.1",
		"react-native-dismissable-numeric-keyboard": "0.0.2",
		"react-native-easy-grid": "^0.1.13",
		"react-native-image-placeholder": "^1.0.9",
		"react-native-maps": "^0.15.3",
		"react-native-parallax-scroll-view": "^0.19.0",
		"react-native-picker": "^4.0.19",
		"react-native-push-notification": "^3.0.0",
		"react-native-router-flux": "^3.41.0",
		"react-native-step-indicator": "^0.0.6",
		"react-native-swiper": "^1.5.4",
		"react-native-vector-icons": "~4.1.1",
		"react-redux": "5.0.3",
		"redux": "3.6.0",
		"redux-form": "6.7.0",
		"redux-logger": "3.0.0",
		"redux-persist": "4.5.0",
		"redux-thunk": "2.2.0",
		"uuid": "^3.1.0"
	},
	"devDependencies": {
		"eslint": "^3.5.0",
		"eslint-config-rallycoding": "3.2.0",
		"jest": "20.0.4",
		"pre-commit": "1.2.2",
		"react-test-renderer": "16.0.0-alpha.12",
		"redux-mock-store": "1.2.3"
	},
	"jest": {
		"preset": "react-native",
		"setupFiles": [
			"./jest-script/setup.js",
			"./jest-script/globalFetch.js"
		],
		"transformIgnorePatterns": [
			"node_modules/(?!(jest-))/"
		]
	}
}

```

**Comment by kmcrawford** [comment]
To fix the iOS isuue you can
` rm -fr $TMPDIR/react-*`

For the Android Issue the [SwipeoutBtn.js](https://github.com/GeekyAnts/NativeBase/blob/master/src/basic/Swipe/SwipeoutBtn.js) has 2 styles defined for it.  I am not sure why you are having issues with this and no one else is.

**Comment by jlcrow** [comment]
The cache clear doesn't work

**Comment by kmcrawford** [comment]
Try:
`rm yarn.lock && rm -rf node_modules && rm -rf $TMPDIR/react-* &&  watchman watch-del-all && npm cache clean --force && yarn`

**Comment by jlcrow** [comment]
Still no dice

**Comment by yeelone** [comment]
I also have this problem when i upgrade reactnative to 0.46.1 , it seems native-base don't work with 0.46 .

**Comment by jlcrow** [comment]
Was able to get working initing a new project and moving to 46.1 and native-base 2.2.1
