### ISSUE TITLE
Warning: You are manually calling a React.PropTypes validation function for the 

### ISSUE THREAD

**Issue by gavin-gmlab** [GeekyAnts/NativeBase#102]
I managed to get the Start Pro code running in my environment. However, I am having having a lot of warning messages regarding React.PropTypes validation function for many different calls on many different screens.

![image](https://cloud.githubusercontent.com/assets/20513400/17476935/11339370-5d95-11e6-80be-d7fefe17ad24.png)

Tried to upgrade React/React Native to the latest, but getting other errors.

**Comment by sankhadeeproy007** [comment]
You have to downgrade to React 15.1.0. Please try that and let us know.

**Comment by RocWangv** [comment]
Any solution provided?

**Comment by sankhadeeproy007** [comment]
Try with react 15.1.0

**Comment by RocWangv** [comment]
Maybe it would work with react 15.1.0 perfectly,but I don't want to downgrade my react and RN .
BTW, do  you have any plan to fix the warning with react ^15.2.1 ?
Best regards  !! @sankhadeeproy007

**Comment by sankhadeeproy007** [comment]
Yes, next version probably.

**Comment by sankhadeeproy007** [comment]
Works fine on RN 0.31 & React: 15.2.1. 
Additionally RN latest requires React: 15.2.1, si I don't think this here is an issue. Closing it. 
![screen shot 2016-08-12 at 12 34 50 pm](https://cloud.githubusercontent.com/assets/10998047/17615148/ca4ff0dc-6089-11e6-820c-66007e1639e2.png)
