### ISSUE TITLE
CheckBox issue

### ISSUE THREAD

**Issue by sumit-khajanchi** [GeekyAnts/NativeBase#1020]
Hi, Team
I am using checkbox but when I was trying to tap on checkbox label it doesn't get checked only when I tap on checkbox it's become checked. So, how can I achieve this, whenever I tap on the checkbox label my checkbox get checked?
react-native - 0.44

Thanks

**Comment by shivrajkumar** [comment]
@sumit-khajanchi Code snippet and a screenshot/gif (if possible) of what you are trying to achieve will be helpful here

**Comment by sumit-khajanchi** [comment]
Hi Shivraj,

Here is my code as mentioned in docs - 
<ListItem>
   <CheckBox  onPress={()=>this.onChecked(data)} checked={this.state.selectedAnswer ? true: false}  />
     <Body>
       <Text>Lorem ipsum</Text>
    </Body>
</ListItem>

Now, what I want that if I tap on text "lorem ipsum " then checkbox should be checked. Currently, nothing happens

Thanks

**Comment by shivrajkumar** [comment]
@sumit-khajanchi You will need to apply onPress on ListItem, instead of Checkbox

**Comment by sumit-khajanchi** [comment]
Ok Thanks

**Comment by SupriyaKalghatgi** [comment]
@sumit-khajanchi If you found this solution working, then could you please close this issue?
