### ISSUE TITLE
[Bug] Footer not display completly first and then fixed

### ISSUE THREAD

**Issue by mnlbox** [GeekyAnts/NativeBase#1023]
## react-native, react and native-base version
```
    "native-base": "^2.1.5",
    "react": "16.0.0-alpha.12",
    "react-native": "0.45.1",
```
## Expected behaviour
Footer not display completly first and then fixed. 
## Steps to reproduce (code snippet or screenshot)
This is my `/app/index.js`:
```
<SideMenu store={store}>
                <Container>
                    <AppHeader store={store} openDrawer={this.openDrawer} />
                    <Content keyboardShouldPersistTaps="always">
                        {this.renderContent()}
                    </Content>
                    <AppFooter />
                </Container>
            </SideMenu>
```

This is my `appFooter` component:
```
<Footer>
                <FooterTab>
                    <Button full>
                        <Text style={[styles.englishText, {color: "white"}]}>App Footer</Text>
                    </Button>
                </FooterTab>
            </Footer>
```

## Screenshot of emulator/device
![footerissue](https://user-images.githubusercontent.com/25859075/27992696-6e9bccc2-64af-11e7-8d68-c2f02ea0297f.gif)
## Is the bug present in both ios and android or in any one of them?
I don't know about ios but I'm in Nexus 7 Tab with Android 5.1.1

**Comment by mnlbox** [comment]
@shivrajkumar any news about this?

**Comment by akhil-geekyants** [comment]
@mnlbox tried to create a screen similar to this using the same device and package versions. But couldn't reproduce this issue. Attaching a screenshot
![footer](https://user-images.githubusercontent.com/27768184/31125446-f6efa7e8-a865-11e7-9736-5d24e966aed3.gif)

**Comment by akhil-geekyants** [comment]
closing due to no response
