### ISSUE TITLE
[BUG] List item onPress fired with a loooooong delay (after 3 or 4 second)

### ISSUE THREAD

**Issue by mnlbox** [GeekyAnts/NativeBase#1024]
## react-native, react and native-base version
```
    "native-base": "^2.1.5",
    "react": "16.0.0-alpha.12",
    "react-native": "0.45.1",
```
## Expected behaviour
List item onPress fired with a loooooong delay (after 3 or 4 second)
## Steps to reproduce (code snippet or screenshot)
This is my SideMenu code:
```
import React, { Component } from 'react';
import { Image, Text, View} from 'react-native';
import { Container, Content, List, ListItem, Drawer, Header, Title, Button, Left, Right, Body, Icon,
    Separator} from 'native-base';
import styles from '../styles/sideMenu';
import {observer} from 'mobx-react/native';
@observer
export default class SideMenu extends Component {
    constructor(props) {
        super(props);

        this.pressMenuItem = this.pressMenuItem.bind(this);
    }
    pressMenuItem(pageState) {
        this.props.store.pageState = pageState;
    }
    render () {
        const MenuComponent = (
            <Container>
                <Header>
                   ...
                </Header>
                <Content
                    style={{ flex: 1, flexDirection: 'column', backgroundColor: '#fff', top: -1 }}
                >
                    ...
                    <List>
                        <ListItem iconRight style={{marginLeft: 0}} onPress={() => {
                            console.warn("click home");
                            this.pressMenuItem("home")
                        }}>
                            <Right><Icon name="arrow-back" /></Right>
                            <Body><Text style={[styles.englishText, {textAlign: 'center'}]}>Home</Text></Body>
                            <Right><Icon name="home" /></Right>
                        </ListItem>
...
                    </List>

                </Content>
            </Container>
        );
        return (
            <Drawer
                content={MenuComponent}
                tapToClose={true}
                openDrawerOffset={0.4} // 20% gap on the right side of drawer
                closedDrawerOffset={-3}
                panCloseMask={0.90}
                panOpenMask={0.90}
                tweenHandler={(ratio) => ({
                    main: { opacity:(2-ratio)/2 }
                })}>
                { this.props.children }
            </Drawer>
        )
    }
}
```
## Screenshot of emulator/device
![menupressdelay](https://user-images.githubusercontent.com/25859075/27995433-70d733e4-64e3-11e7-8141-cad19536089c.gif)
Please see delay between when I tap on Home button in SideMenu and when you see `console.warn("click home");` output.

## Is the bug present in both ios and android or in any one of them?
I don't know about ios but I'm in Nexus 7 Tab with Android 5.1.1

**Comment by mnlbox** [comment]
Maybe related to this: #759

**Comment by mnlbox** [comment]
@sankhadeeproy007 , @SupriyaKalghatgi Are you have any suggestion?

**Comment by mnlbox** [comment]
Maybe other related issue: https://github.com/facebook/react-native/issues/2558 and #662

**Comment by mnlbox** [comment]
This is a terrible issue please help me to fix it or if it's a bug from NativeBase tell me know and add some label to it.
Thanks guys.

**Comment by shivrajkumar** [comment]
@mnlbox Have you tried this with React Native components

**Comment by mnlbox** [comment]
@shivrajkumar Can you explain more? For example with FlastList?

**Comment by SupriyaKalghatgi** [comment]
@mnlbox Please check the reply here 
[#759 comment](https://github.com/GeekyAnts/NativeBase/issues/759#issuecomment-342725652)

**Comment by akhil-geekyants** [comment]
@mnlbox FlatList with ListItem

![listitem](https://user-images.githubusercontent.com/27768184/32545406-9f3bccb8-c4a1-11e7-9869-474bd57e67a6.gif)

**Comment by akhil-geekyants** [comment]
Using FlatList solves the issue. Closing the issue.

**Comment by Bundas** [comment]
@akhil-geekyants What? It maybe solves his problem but it certainly does not solve the bug itself...

**Comment by mnlbox** [comment]
@SupriyaKalghatgi Any news?
