### ISSUE TITLE
DeckSwiper - how to use backend api data in "const cards" for dataSource in deckSwiper

### ISSUE THREAD

**Issue by sachinsinghh** [GeekyAnts/NativeBase#1025]
I am fetching data in "profileData" in componentDidMount function.I want to use that "profileData" inside "const cards" .I don't want to use static data as i have in current condition.

import React, { Component } from 'react';
import { Text, View, Image, TouchableOpacity, DrawerLayoutAndroid, Dimensions, ScrollView } from 'react-native';
import { Actions } from 'react-native-router-flux';
import { connect } from 'react-redux';
import axios from 'axios';
import { DeckSwiper, Card, CardItem, Content, Container, List, ListItem, Left, Thumbnail, Body } from 'native-base';
import { loginUser } from '../actions';

const cards = [
{
text: 'Emma Watson',
name: 'One',
image: require('./img/emma_watson.jpg'),
},
{
text: 'Scarllet Johnson',
name: 'One',
image: require('./img/johnson.jpg'),
},
{
text: 'Demi Lovato',
name: 'One',
image: require('./img/lovato.jpg'),
},
{
text: 'Megan Fox',
name: 'One',
image: require('./img/megan_fox.jpg'),
},

];

class Profiles extends Component {

constructor() {
super();
this.openDrawer = this.openDrawer.bind(this);
this.state = { id: '' };
console.log('constructor');
}

state = { profileData: [] };

componentDidMount() {
axios.post('http://192.168.3.7/DatingApp/public/api/profile', {
api_key: '12345XYDHSDKHDSZDHFJKDHFD233432'
})
.then((response) => this.setState({ profileData: response.data.user }))
.catch((error) => { console.log(error); });
}
....
......
.........
............

const mapStateToProps = state => {
  return {
    facebook_id: state.auth.facebook_id,
    name: state.auth.name,
    birthday: state.auth.birthday,
    picture: state.auth.picture
  };
};

export default connect(mapStateToProps, { loginUser })(Profiles);

**Comment by sachinsinghh** [comment]
I am fetching data in "profileData" in componentDidMount function.I want to use that "profileData" inside "const cards" .I don't want to use static data as i have in current condition.

import React, { Component } from 'react';
import { Text, View, Image, TouchableOpacity, DrawerLayoutAndroid, Dimensions, ScrollView } from 'react-native';
import { Actions } from 'react-native-router-flux';
import { connect } from 'react-redux';
import axios from 'axios';
import { DeckSwiper, Card, CardItem, Content, Container, List, ListItem, Left, Thumbnail, Body } from 'native-base';
import { loginUser } from '../actions';

const cards = [
{
text: 'Emma Watson',
name: 'One',
image: require('./img/emma_watson.jpg'),
},
{
text: 'Scarllet Johnson',
name: 'One',
image: require('./img/johnson.jpg'),
},
{
text: 'Demi Lovato',
name: 'One',
image: require('./img/lovato.jpg'),
},
{
text: 'Megan Fox',
name: 'One',
image: require('./img/megan_fox.jpg'),
},

];

class Profiles extends Component {

constructor() {
super();
this.openDrawer = this.openDrawer.bind(this);
this.state = { id: '' };
console.log('constructor');
}

state = { profileData: [] };

componentDidMount() {
axios.post('http://192.168.3.7/DatingApp/public/api/profile', {
api_key: '12345XYDHSDKHDSZDHFJKDHFD233432'
})
.then((response) => this.setState({ profileData: response.data.user }))
.catch((error) => { console.log(error); });
}
....
......
.........
............

const mapStateToProps = state => {
  return {
    facebook_id: state.auth.facebook_id,
    name: state.auth.name,
    birthday: state.auth.birthday,
    picture: state.auth.picture
  };
};

export default connect(mapStateToProps, { loginUser })(Profiles);

**Comment by shivrajkumar** [comment]
@sachinsinghh Just pass the fetched data to the dataSource prop of the DeckSwiper instead of cards array
