### ISSUE TITLE
Footer / tab bar, icons not aligned properly

### ISSUE THREAD

**Issue by pkassonss** [GeekyAnts/NativeBase#1027]
Using latest NB and RN and the footer / tab bar not providing best layout.

I have 3 tabs, and the middle takes up most space.  I can not also have a 4th tab.

Tried flex layout row and other options and just not working.
![screen shot 2017-07-10 at 11 00 16 am](https://user-images.githubusercontent.com/25250587/28024605-35594d08-655f-11e7-8ec7-5754b0c91fb8.png)

**Comment by shivrajkumar** [comment]
@pkassonss Can you post the code snippet of this.

**Comment by pkassonss** [comment]
`
    <Footer >    
        <FooterTab>
          <Button active={this.state.selectedTab==='needs'} onPress={() => this.handleTabClick('needs')}>
            <Text>Needs</Text>
              <Icon name="ios-contact-outline" />
            </Button>
        </FooterTab>

        <FooterTab>
          <Button active={this.state.selectedTab==='aboutus'} onPress={() => this.handleTabClick('aboutus')}>
            <Text>About Us</Text>
              <Icon name="ios-contact-outline" />
            </Button>
        </FooterTab>
    
        <FooterTab>
          <Button  active={this.state.selectedTab==='profile'} onPress={() => this.handleTabClick('profile')}>
            <Text>Profile</Text>
            <Icon name="ios-settings" />
          </Button>
        </FooterTab>
    </Footer >  `

**Comment by shivrajkumar** [comment]
@pkassonss This seems to work fine for both 3 or 4 Tabs

**Comment by pkassonss** [comment]
Can you post your code on how this was done ?  Thanks !

**Comment by pkassonss** [comment]
Code sample ?

**Comment by pkassonss** [comment]
Can you provide your sample code or what version of the code base you are using ?

**Comment by shivrajkumar** [comment]
@pkassonss The code used there is the code snippet provided by you.
