### ISSUE TITLE
how to use Tabs of native base ? 

### ISSUE THREAD

**Issue by rajatgupta1993** [GeekyAnts/NativeBase#103]
I used the code given in the docs . 

import React, { Component } from 'react';
import { Container, Content, Tabs } from 'native-base';

import TabOne from "./tabOne";
import TabTwo from "./tabTwo";
​
http://nativebase.io/docs/v0.5.2/components#tabs

It is showing error : Unable to resolve module ./tabOne.

**Comment by SupriyaKalghatgi** [comment]
@rajatgupta1993 That is example snippet for tabs
`tabOne` and `tabTwo` are two different `js` files that should be existing in your app

**Comment by rajatgupta1993** [comment]
@SupriyaKalghatgi  thanks . 

but how can I style it? 
as in which properties can be changed and how?

**Comment by SupriyaKalghatgi** [comment]
@rajatgupta1993 Check the [documentation](http://nativebase.io/docs/v0.5.2/customize#themeTabs) for same

**Comment by rajatgupta1993** [comment]
Hi I have tried using this , 
But it is not changing the style of tabs . 

`
									 <Content>
					                    <Tabs
					                    tabBgColor="black"
					                    tabTextColor="white">
				                        <TabOne 
				                        tabBgColor="black"
					                    tabTextColor="white"
					                    tabLabel="One" />
				                        <TabTwo tabLabel="Two" />
				                    </Tabs>
					                </Content>`


I have the tried "tabBgColor="black", tabTextColor="white" properties in <Tabs > and <TabOne> both , but result is not reflecting.

**Comment by sankhadeeproy007** [comment]
These are not props and you need to change these variables in your `theme.js` file. Please go through the docs again. Closing this as this is not an issue.

**Comment by rajatgupta1993** [comment]
where is theme.js located? 
I couldn't find it . 
and please tell me where is this documented?

**Comment by sankhadeeproy007** [comment]
[Here](http://nativebase.io/docs/v0.5.2/customize#themingNativeBaseApp)

**Comment by andreyluiz** [comment]
I think it is not very specific in the documentation how to create an actual tab to import and use it in the Tabs component. How does a Tab looks like? I can't find out where it is documented.

**Comment by ravingupta** [comment]
Unable to locate /node_modules/native-base/Components/Themes/light.js

**Comment by chibeepatag** [comment]
Is it possible to know which is the currently active tab?

**Comment by saivyas** [comment]
You can get by initialPage property            

      <Tabs initialPage=1}}>
<Tab></Tab>
<Tab></Tab>
<Tab></Tab>
                  </Tab>

**Comment by heiseish** [comment]
@chibeepatag you can get it from the onChangeTab function
