### ISSUE TITLE
BUILD FAILED : CpResource .../node_modules/native-base/Fonts/Andale\ Mono.ttf

### ISSUE THREAD

**Issue by Antoine-Mace** [GeekyAnts/NativeBase#1031]
Hi

I was previously running on version 2.1.4 of native-base, I tried to move to versions 2.2.0 (mainly to fix the toast messages bug)

However i run through a build failed issue when I try to run `react-native run-ios`

In details 
`* BUILD FAILED **

The following commands produced analyzer issues:

	Analyze /Users/XXX/Desktop/Projects/XXX/XXX/node_modules/react-native/ReactCommon/yoga/yoga/YGNodeList.c
	Analyze /Users/XXX/Desktop/Projects/XXX/XXX/node_modules/react-native/ReactCommon/yoga/yoga/Yoga.c
(2 commands with analyzer issues)

The following build commands failed:
	CpResource /Users/antionemace/Desktop/Projects/XXX/XXX/node_modules/native-base/Fonts/Andale\ Mono.ttf build/Build/Products/Debug-iphonesimulator/XXX.app/Andale\ Mono.ttf
(1 failure)

Installing build/Build/Products/Debug-iphonesimulator/XXX.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=22):
Failed to install the requested application
The bundle identifier of the application could not be determined.
Ensure that the application's Info.plist contains a value for CFBundleIdentifier.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/XXX.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist
`

Right now I'm running on

`
    "react": "16.0.0-alpha.12",
    "react-native": "0.45.1"
`

Sorry for this long post, 

Cheers for your answers :)

**Comment by sankhadeeproy007** [comment]
Check [this](https://github.com/GeekyAnts/NativeBase/issues/928).

**Comment by Antoine-Mace** [comment]
@sankhadeeproy007 thanks

**Comment by Antoine-Mace** [comment]
Just in order to close this issue the steps described worked for me [https://github.com/GeekyAnts/NativeBase/issues/928](steps)
