### ISSUE TITLE
Uppercase text in Button

### ISSUE THREAD

**Issue by anoopmm** [GeekyAnts/NativeBase#1033]
I have a button with face book icon 
`          <Button iconLeft block >
                 <Icon name='logo-facebook' />
               <Text>Login with facebook</Text>
               </Button>`
with text "Login with facebook" But it displays "LOGIN WITH FACEBOOK" .I am tried with capitalize={false} but no hope.Is there any way?
NB version:2.2.1

**Comment by stefano-DM** [comment]
did you try `uppercase={false}` instead of `capitalize`?

**Comment by shivrajkumar** [comment]
The above solution works.

**Comment by anoopmm** [comment]
Thanks @stefano-DM  :)

**Comment by isaachinman** [comment]
@stefano-DM Has the `uppercase` prop been removed?

**Comment by littletower** [comment]
@isaachinman I haven't used Nativebase in a while, but I believe `uppercase` has not been removed: https://github.com/GeekyAnts/NativeBase/blob/15f7ac040d911181b666607e3d9d68fad4a2ff7f/src/basic/Text.js#L12

**Comment by Shahzaibmalik55** [comment]
just Import Text from Native Base in your App.js
import { Text } from 'native-base';

in your constructor
constructor(props) {
 Text.defaultProps.uppercase = false;
}

instead of giving props to every Text it will set uppercase = false to all text

**Comment by brownieboy** [comment]
@Shahzaibmalik55's fix worked for me.

But an even easier solution is to import Text directly from React Native instead of from Native Base.  The "raw" version of Text doesn't display this unwanted and unexplained (any where that I could find) transformation in the first place.

```
import { Text} from "react-native";

// ... in component
<Text>Back to Info</Text>
```

Displays as "Back to Info".  Who'd have thunk it?!!!

I'm not sure why I was importing Text from Native Base in the first place.  I probably just copied and pasted some example code from somewhere and then carried on doing it that way.

**Comment by Shahzaibmalik55** [comment]
@brownieboy if you're not using native base in your project just import Text from react native and make default to uppercase = false
And importing Text from Nativebase give defalut styling to Text component such as font family
Import { Text } from "native-base"

// in IOS it shows uppercase and in android it shows capatilize its defalut styling in of native base
<Text>Back to Info</Text>

**Comment by brownieboy** [comment]
Thank you, @Shahzaibmalik55.

I found that I didn't have to set `uppercase = false` when I imported directly from "react-native".

The Text component isn't documented amongst the Nativebase Components http://docs.nativebase.io/Components.html.

**Comment by Shahzaibmalik55** [comment]
Yes @brownieboy you're right you don't have to set uppercase props if you're import from react-native

But there are many components that there is not present in the document of nativr base but you can also use Text from native-base

**Comment by Aleksandern** [comment]
theme config:
  btnUppercaseAndroidText: false,

**Comment by ermankuruoglu** [comment]
> just Import Text from Native Base in your App.js
> import { Text } from 'native-base';
> 
> in your constructor
> constructor(props) {
> Text.defaultProps.uppercase = false;
> }
> 
> instead of giving props to every Text it will set uppercase = false to all text

I use react-native-native-navigation library for navigation. I added this code line (`Text.defaultProps.uppercase = false;`) after registerScreens() function call . This also worked for me.

**Comment by MortadhaFadhlaoui** [comment]
Hello everyone when i try button without title:
`<Button>
            <Text>Hi !</Text>
          </Button>`
i got a problem say : 

> The title prop of a Button must be a string.
any solution how to disable title ?
