### ISSUE TITLE
Button is failing on null childrens

### ISSUE THREAD

**Issue by vasyas** [GeekyAnts/NativeBase#1035]
## react-native, react and native-base version
    "native-base": "^2.1.4",
    "react": "16.0.0-alpha.12",
    "react-native": "^0.45.0-rc.2",

## Expected behaviour
Button should ignore null children, as it is common in React Components

## Actual behaviour
Button render fails with error:
```
null is not an object (evaluating 'child.type')
<unknown>
Button.js:34:78
```

## Steps to reproduce (code snippet or screenshot)
```
<Button>{ null }</Button>
```

Practical case for this is conditional rendering:
```
<Button><Text>Ok</Text>{ loading && <Spinner/>}</Button>
```

## Screenshot of emulator/device
http://take.ms/mO6HB

## Is the bug present in both ios and android or in any one of them?
Yes

## Any other additional info which would help us debug the issue quicker.
No

**Comment by shivrajkumar** [comment]
Check the latest
