### ISSUE TITLE
Adding buttons to ListItem

### ISSUE THREAD

**Issue by bsiddiqui** [GeekyAnts/NativeBase#104]
I have a `ListItem` that more or less looks like this:
```jsx
<ListItem>
  <Text>Hello</Text>
   <Button onPress={() => this.props.onAdd()}>Add</Button>
   <Button onPress={() => this.props.onRemove()}>Remove</Button>
</ListItem>
```

The `ListItem` won't render with the buttons but will render correctly without them. Is there a way to effectively add clickable buttons to a `<ListItem>`?

Edit: looks like there is some logic for a `<Button>` being present so I imagine this can work.
https://github.com/GeekyAnts/NativeBase/blob/master/Components/Widgets/ListItem.js#L173

**Comment by himanshu-sahusoft** [comment]
For now, we do not support `<Button>` inside `<ListItem>` in some cases. You can wrap the children of `<ListItem>` in a `<View>` component for now. We'll have a better implementation for this in the future versions.

**Comment by bsiddiqui** [comment]
Thanks for the info
