### ISSUE TITLE
Tabs with React navigation

### ISSUE THREAD

**Issue by nonameolsson** [GeekyAnts/NativeBase#1040]
Hi! I'm trying to integrate `NativeBase` with `react-navigation`. I'm having some trouble to understand how to hook up the `TabNavigator` from `react-navigation` with `Tabs` from `NativeBase`.

Is there an example somewhere? 

Here is my code: https://gist.github.com/nonameolsson/2f2e1d3f6f51377da5f4ec110b8ad762#file-appnavigation-js-L71

**Comment by shivrajkumar** [comment]
@nonameolsson Check [this](http://docs.nativebase.io/docs/examples/navigation/StackNavigationExample.html)

**Comment by nonameolsson** [comment]
@shivrajkumar Thanks for the link! But I can't find any example of `Tabs`. There is an example with the `Footer` and `FooterTab`. That I already have got working with `react-navigation`.

What I need to understand is how `Tabs` can be implemented. The difference between `Tabs` and `FooterTab` is that `Tabs` have their content nested. Se my example below.

`FooterTab`
```javascript
export default class BottomNavigation extends React.Component {
  onPress = (navigation, route) => {
    navigation.navigate(route.routeName)
  }

  render () {
    const { navigation, routes } = this.props

    return (
      <Footer>
        <FooterTab>
          {navigationItems.map((route, index) => {
            const active = navigation.state.index === index // Check if item is active

            return (
              <Item
                key={route.label}
                label={route.label}
                icon={route.icon}
                onPress={() => this.onPress(navigation, route)}
                active={active}
              />
            )
          })}
        </FooterTab>
      </Footer>
    )
  }
}
```

This is simple, because with the `onPress` just dispatch a new navigation. 

But with `Tabs` I haven't been able to do it yet. The tab needs the content to be nested within.

`Tabs`
```javascript
import Tab1 from './tabOne';
import Tab2 from './tabTwo';
​export default class TabsExample extends Component {
  render() {
    return (
      <Container>
        <Header hasTabs />
        <Tabs initialPage={1}>
          <Tab heading="Tab1">
            <Tab1 />
          </Tab>
          <Tab heading="Tab2">
            <Tab2 />
          </Tab>
          <Tab heading="Tab3">
            <Tab3 />
          </Tab>
        </Tabs>
      </Container>
    );
  }
}
```

So, I really appreciate all help I can get to make this working!

**Comment by olivierdelomez** [comment]
Maybe the following could replace the `onPress` to dispatch navigation , I don't think it's good practice though... 

`<Tabs onChangeTab={(ref) => TriggerNavigationTab(ref)} >`
and each tab must have a `ref={}`
`<Tab ref={NavigationLabel}  >`

I don't think tabs were built with navigation in mind. Segment component might be better ?

**Comment by shivrajkumar** [comment]
Tabs and react-navigation TabNavigator together doesn't make sense. As both provide the same functionality. But using TabNavigator makes much more sense. If you want to use NativeBase Tabs for its styling. You can use it [this](https://github.com/GeekyAnts/native-base-react-navigation-stack-navigator/blob/master/src/ChatScreen/index.js) way. Use TabHeading instead of FooterTab there.

**Comment by nonameolsson** [comment]
@shivrajkumar I hear you. The reason I wanted to use NativeBase tabs with TabNavigator was to have the nice styling from NativeBase
