### ISSUE TITLE
Cannot read property '_root' of undefined Function.show Actionsheet.js:137:79

### ISSUE THREAD

**Issue by abellee** [GeekyAnts/NativeBase#1042]
react: 16.0.0-alpha.12
    react-native: 0.46.1
    native-base: 2.2.1

    ActionSheet.show(
	{
		options: [
			"相册",
			"拍一张",
			"取消"
		],
		title: "选择头像",
		cancelButtonIndex: 2
	},
	(buttonIndex) => {
		if(buttonIndex == 0){
			ImagePicker.openPicker({
			            mediaType:'photo',
			            loadingLabelText:'请稍候...',
			            width: Dimensions.get("window").width,
						height: Dimensions.get("window").width,
						cropping: true
			        }).then(image => {
			            this.setState({
			            	avatarImage: { uri: image.path }
			            });
			    	});
				}else if(buttonIndex == 1){
					ImagePicker.openCamera({
			            mediaType:'photo',
			            loadingLabelText:'请稍候...',
			            width: Dimensions.get("window").width,
						height: Dimensions.get("window").width,
						cropping: true
			        }).then(image => {
			            this.setState({
			            	avatarImage: { uri: image.path }
			            });
			        });
				}
			}
		);`

**Comment by sankhadeeproy007** [comment]
Is your topmost component wrapped inside `Root`?

**Comment by abellee** [comment]
@sankhadeeproy007 
nope, but it works in `2.1.5` and `rn 0.45.1`, so it is must wrapped inside `Root` in `2.2.1`?

**Comment by sankhadeeproy007** [comment]
Yes. [Check](http://docs.nativebase.io/Components.html#Toast)

**Comment by sankhadeeproy007** [comment]
The docs have all the possible examples. Let me know if you need help with any particular component.

**Comment by abellee** [comment]
@sankhadeeproy007
I do wonder the `List` whether has the event just like `onItemSelected`, I didn't find in the current documentation.

**Comment by gogulanareshkw** [comment]
"native-base": "^2.8.1",		
"react": "^16.4.1",
"react-native": "^0.55.4",
please help me, am getting error as cannot read property 'showActionSheet' of null

to reproduce follow these stepes:

actionsheet available in page 1, for the first actionsheet working
navigate to page 2 from page1, and then page 3 from page2 (page1 -> page2 -> page3)
then goback to page1 and click actionsheet, now getting error

![screenshot_2018-10-25-14-59-32](https://user-images.githubusercontent.com/40063274/47492947-c4397400-d86b-11e8-95ea-08cf876efe5a.png)


Thanks
