### ISSUE TITLE
DeckSwiper - swipe back function

### ISSUE THREAD

**Issue by Shingyien** [GeekyAnts/NativeBase#1043]
Hello,

Is there any way to implement swipe back function for DeckSwiper?

It seems like currently both onSwipeLeft and onSwipeRight will bring us to the next card. I would like to be able to swipe to previous card during onSwipeRight and next card during onSwipeLeft. Thanks!

**Comment by Softrabbit-de** [comment]
For me this is also an important feature? Any news?
Or as alternative https://github.com/GeekyAnts/NativeBase/issues/626

**Comment by DFelten** [comment]
Something new here? For me this is an essential feature and so I have to use an other library for a card swiper.

**Comment by nupejosh** [comment]
Are the any workarounds for this feature? Swiping left and right with the same behavior is confusing for my end users.

**Comment by davehdo** [comment]
+1

**Comment by SupriyaKalghatgi** [comment]
#626
