### ISSUE TITLE
unable to resolve module

### ISSUE THREAD

**Issue by ketankulkarni** [GeekyAnts/NativeBase#1044]
## react-native, react and native-base version
"native-base": "^2.2.1",
    "react": "16.0.0-alpha.6",
    "react-native": "0.46.0",
## Expected behaviour
able to use native base component
## Actual behaviour -
after import { Container } from 'native-base';
![native base error](https://user-images.githubusercontent.com/20577851/28163840-5e5eb6b0-67ea-11e7-8004-3bf92ee605a1.png)

## Steps that hhad been followed 
npm install native-base --save

**Comment by ajostergaard** [comment]
https://github.com/GeekyAnts/NativeBase/issues/307#issuecomment-314713406

**Comment by j2l** [comment]
Can you please update the docs:
https://docs.nativebase.io/docs/GetStarted.html

**Comment by shivrajkumar** [comment]
https://github.com/GeekyAnts/NativeBase#6-compatibility-versions
