### ISSUE TITLE
StyleSheet margin issue

### ISSUE THREAD

**Issue by KrajncJ** [GeekyAnts/NativeBase#1045]
Hi!

I am trying to use Stylesheet, but it always has a margin from bottom. I'd like to use it in my app without a bottom margin.

## react-native, react and native-base version
RN: 0.41.2
NB: 2.1.0

## Expected behaviour

I would like to achieve this.

![want](https://user-images.githubusercontent.com/16381836/28167930-aa4615a8-67dd-11e7-8bd1-dd79f97eb8c9.png)

## Actual behaviour

![screenshot_20170713-145816 1](https://user-images.githubusercontent.com/16381836/28168111-53810c18-67de-11e7-906b-8b2b3c781a6d.png)

**Comment by nazrdogan** [comment]
can you share code ?

**Comment by KrajncJ** [comment]
This is my component. 

```javascript html
<View style={{backgroundColor: 'yellow', flex: 1}}>  
      <Button transparent
            onPress={() =>
            
              ActionSheet.show(
                {
                  options: ["Option 1", "Option 2", "Option 3"],
                  cancelButtonIndex: 0,
                  destructiveButtonIndex: 1,
                  title: "Native Base StyleSheet",
                },
                buttonIndex => {
      
                  this.do(buttonIndex);
                  this.setState({ clicked: BUTTONS[buttonIndex] });
                }
              )}
          >
          <Text>Press</Text>
     </Button>
</View>


```

**Comment by nazrdogan** [comment]
Can you wrap your component with this  
`
<Container>
<Content> 
</Content>
 </Container>`

**Comment by KrajncJ** [comment]
Still the same problem.
Does wrappers in render function even affects ActionSheet display?. Because it is called with a function show() ?  I even tried rendering just a button and the same issue.

Is this the correctly meant display of ActionSheet on the second picture, or is this just the error on my side?

**Comment by dtuite** [comment]
I'm seeing something very similar. I'm using version 2.0.0 of NativeBase.

Here's a screen grab from android. The inspector shows a 25 `marginBottom` on the `<ScrollView />` inside `<Content />`. This isn't a `ScrollView` I've added, it must be part of the `Content` element.

I've tried a bunch of things to override it but don't seem to be able.

![unwanted margin highlighted in inspector](https://user-images.githubusercontent.com/562403/28243483-4f3faed4-69c3-11e7-8167-1613c7cc78d3.png)

**Comment by KrajncJ** [comment]
So any solution here?

**Comment by KrajncJ** [comment]
This is probably connected with my issue..

https://stackoverflow.com/questions/44151243/unwanted-bottom-margin-in-keyboardawarescrollview-reactnative

**Comment by dtuite** [comment]
No solution but the problem disappeared when I upgraded to `native-base@2.2.0`.

**Comment by KrajncJ** [comment]
I think that the problem is in `react native` , because the same thing happens to me even if I dont use `native-base`

**Comment by shivrajkumar** [comment]
Closing this as the issue doesn't seems to be with NativeBase. Let us know if you still have any queries
