### ISSUE TITLE
After Install React native Base error is coming

### ISSUE THREAD

**Issue by gauravverma029** [GeekyAnts/NativeBase#1047]
*I am getting error when i fresh install react native using this step
npm install -g create-react-native-app
create-react-native-app AwesomeProject
cd AwesomeProject
npm start
Install the Expo client app on your iOS or Android phone and connect to the same wireless network as your computer. Using the Expo app, scan the QR code from your terminal to open your project.
After that is was working fine.But when i install 

npm install native-base --save
npm install @expo/vector-icons --save

Then again npm install # ..*

This Error is coming.Please find screenshort
![img_0708](https://user-images.githubusercontent.com/4488516/28209191-16611e5a-68af-11e7-9abf-f2d0d77c48ae.PNG)

**Comment by gauravverma029** [comment]
I tried this given solution ...but i thing some package issue.My Package.jsom

{
  "name": "finalapp",
  "version": "0.1.0",
  "private": true,
  "devDependencies": {
    "react-native-scripts": "0.0.50",
    "jest-expo": "~18.0.0",
    "react-test-renderer": "16.0.0-alpha.12"
  },
  "main": "./node_modules/react-native-scripts/build/bin/crna-entry.js",
  "scripts": {
    "start": "react-native-scripts start",
    "eject": "react-native-scripts eject",
    "android": "react-native-scripts android",
    "ios": "react-native-scripts ios",
    "test": "node node_modules/jest/bin/jest.js --watch"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "@expo/vector-icons": "^5.0.0",
    "expo": "^18.0.3",
    "native-base": "^2.2.1",
    "react": "16.0.0-alpha.12",
    "react-native": "^0.45.1"
  }
}

**Comment by shivrajkumar** [comment]
@gauravverma029 For RN 45 use NativeBase 2.2.0
check [this](https://github.com/GeekyAnts/NativeBase#6-compatibility-versions)
