### ISSUE TITLE
After installing NativeBase shows this error on simulator unable to resolve react-native/libraries/render/shims.....

### ISSUE THREAD

**Issue by sa63** [GeekyAnts/NativeBase#1049]
<img width="366" alt="nativebase-error" src="https://user-images.githubusercontent.com/30106593/28237897-e206c262-6959-11e7-8904-4d242f38468e.png">

One mention also  react-native link command shows not found
Here are the versions that I am using.
  expo 18.0.4,
    native-base: 2.2.1,
    react 16.0.0-alpha.12,
    react-native https://github.com/expo/react-native/archive/sdk-18.0.1.tar.gz,
    react-navigation: 1.0.0-beta.11

**Comment by PanRada** [comment]
same +1

**Comment by sa63** [comment]
I found the solution. Just remove your NativeBase from your project  `npm uninstall --save native-base`   then install 2.2.0 version 
`npm install --save native-base@2.2.0`

**Comment by PanRada** [comment]
that not sound how fix problem but it's working any way -> I think that should be bug

**Comment by dtuite** [comment]
@sa63 it might be better to leave this open so the maintainers can track the bug.

**Comment by kisubs** [comment]
https://github.com/facebook/react-native/issues/14977
