### ISSUE TITLE
why its so DIFFICULT to change style in nativebase ?

### ISSUE THREAD

**Issue by yeknava** [GeekyAnts/NativeBase#1050]
## react-native, react and native-base version
RN: 46
native-base: 2+ (2.2.0)

in native base v1 we could just pass style prop to component and change its styles to our desires, btw in 2+ version the best or easiest way is eject theme and change components style in component file. but each time with each upgrade all custom styles that wrote in components file need to rewrite again cuz  we need to eject theme again.

our app is heavy customized based on native base but now its look like we need to check all lines of each component file one by one to change styles just to upgrade from native base v2.0 to v2.2 .

is there any way or any plan to make it easier ?

**Comment by sankhadeeproy007** [comment]
NativeBase 2 also takes style prop. The changes in the theme file are most likely due to variables for new components that were added with the later versions.
You can can just do a diff with the new theme file and add the new variables.

**Comment by yeknava** [comment]
@sankhadeeproy007 yes i did that with 'meld', btw i prefer there was something like native-base-updater cli to done that with git or something. or atleast easier way to customize theme.

**Comment by sankhadeeproy007** [comment]
Yes, we are currently working on a cli tool that generates a new boilerplate.
We'll probably add that feature as well. Thanks for the suggestion!
