### ISSUE TITLE
[performance] Use PureComponent instead of Component when extending StyledComponent

### ISSUE THREAD

**Issue by smmoosavi** [GeekyAnts/NativeBase#1051]
If PureComponent is used instead of Component when extending StyledComponent in `native-base-shoutem-theme`, we may experience improvements in performance.
file: node_modules/native-base-shoutem-theme/src/connectStyle.js:106

## react-native, react and native-base version
native-base@2.2.1
react@16.0.0-alpha.12
react-native@0.46.3

Note: I cannot find native-base-shoutem-theme repository and create issue here

**Comment by shivrajkumar** [comment]
@smmoosavi Using PureComponent doesn't make any difference.
You can try and send PR if you find a solution [here](https://github.com/GeekyAnts/theme)
