### ISSUE TITLE
Tab container background

### ISSUE THREAD

**Issue by anoopmm** [GeekyAnts/NativeBase#1052]
How to make tab container background to transparent?
`<Tab heading="Tab2" activeTabStyle={{backgroundColor: 'red',height:40}} tabStyle={{backgroundColor: 'transparent',height:40,borderWidth:1,borderColor:'red'}}>
              <Content padder style={{backgroundColor:'transparent'}}>
                <Text>
                  test
                </Text>
              </Content>
            </Tab>`
still there is some white color for tab container.how to make it transparent?

**Comment by shivrajkumar** [comment]
@anoopmm Tab itself here is a Content component, it is not recommended to use Content inside Tab. And you can use `style` prop in Tab to pass the desired backgroundColor

**Comment by ozexpert** [comment]
is using style in Tab broken? doesn't work.
```
<Tab style={{ backgroundColor: '#000' }}>
...
</Tab>
```

**Comment by akhil-geekyants** [comment]
@ozexpert style for `<Tab/>` is working.

Gif

![tabs](https://user-images.githubusercontent.com/27768184/32887176-ef07829e-cae8-11e7-9f93-24b6ffb8de54.gif)

**Comment by Tess-welhazi** [comment]
@akhil-geekyants What i want is to change the tab color into matching the header, not coloring the page itself

![image](https://user-images.githubusercontent.com/20952652/36471476-db055ec2-16ee-11e8-9cca-0957c65e1eef.png)

how to change to tab heading color itself? 
![image](https://user-images.githubusercontent.com/20952652/36471537-1066509e-16ef-11e8-94c8-c9eb4103acaa.png)

**Comment by ravirupareliya** [comment]
You can directly use `tabBarBackgroundColor` with <Tab>

    <Tabs tabBarBackgroundColor={'#ffffff'}
