### ISSUE TITLE
Thumbnail `square` prop not working when combined with size in wrong order

### ISSUE THREAD

**Issue by MrToph** [GeekyAnts/NativeBase#1053]
Hi,
the `square` prop of `Thumbnail` doesn't work when it is defined **before** a size property like `large`.
When you swap the order of the props it however works.

This is not a duplicate of #917 

## react-native, react and native-base version
```json
"dependencies": {
    "native-base": "^2.2.1",
    "react": "16.0.0-alpha.12",
    "react-native": "^0.46.3",
  },
```

## Expected behaviour
It should render the `Thumbnail` as a square.

## Actual behaviour
`Thumbnail` image is rendered as a circle.

## Steps to reproduce (code snippet or screenshot)
This does **NOT** render the image as a square, but it should:

```js
<Thumbnail
  square
  large
  source={{
    uri: 'http://lorempixel.com/output/fashion-q-c-640-480-3.jpg',
  }}
/>
```

Changing the order of `large` and `square` however works:
```js
<Thumbnail
  large
  square
  source={{
    uri: 'http://lorempixel.com/output/fashion-q-c-640-480-3.jpg',
  }}
/>
```

## Is the bug present in both ios and android or in any one of them?
Just tested on Android, but is probably on both.

**Comment by shivrajkumar** [comment]
Fixed in v2.3.0

**Comment by MBach** [comment]
Are you sure ? Because I'm still having the problem with v2.3.3

**Comment by akhil-geekyants** [comment]
@MBach tested in the latest version. It is working fine.
```
"native-base": "2.3.3",
"react": "16.0.0",
"react-native": "0.50.3"
```
Gif

![thumbnail](https://user-images.githubusercontent.com/27768184/32892207-77b49ade-cafb-11e7-8ae9-c3f056449a2b.gif)
