### ISSUE TITLE
[SUGGESTION] [DOCS] Please use real image for docs

### ISSUE THREAD

**Issue by mnlbox** [GeekyAnts/NativeBase#1055]
I see a lot in [docs](https://docs.nativebase.io) pages that image and example code not same. For example:

- https://docs.nativebase.io/Components.html#list-thumbnail-headref
- https://docs.nativebase.io/Components.html#inline-label-headref
- and more.

Please use real image for docs. It's a little confusing now.

Thanks for your attention 😉

**Comment by sankhadeeproy007** [comment]
Thanks for bringing it to our attention!
cc @SupriyaKalghatgi

**Comment by shivrajkumar** [comment]
Check the above referenced issue for further updates
