### ISSUE TITLE
last version of native-base is still use old prop-types package

### ISSUE THREAD

**Issue by wethil** [GeekyAnts/NativeBase#1058]
This is my package.json
`{
  "name": "l2s",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "@expo/ex-navigation": "^3.0.0",
    "babel-preset-react-native-stage-0": "^1.0.1",
    "great-circle": "^0.2.8",
    "native-base": "^2.2.1",
    "react":"^16.0.0-alpha.6",
    "react-native": "0.46.3",
    "react-native-animatable": "^1.2.2",
    "react-native-maps": "^0.15.3",
    "react-native-modalbox": "^1.4.1",
    "react-native-splash-screen": "^2.1.0",
    "react-native-vector-icons": "^4.2.0"
  },
  "devDependencies": {
    "babel-jest": "20.0.3",
    "babel-preset-react-native": "2.1.0",
    "jest": "20.0.4",
    "react-test-renderer": "16.0.0-alpha.12"
  },
  "jest": {
    "preset": "react-native"
  }
}
`

I know that PropTypes is deprecated after react 15.5. So I did run [this react-rodemod script](https://github.com/reactjs/react-codemod/blob/master/transforms/React-PropTypes-to-prop-types.js) . It got all es6 js files working with new react version. But I still get `_react2.default.PropTypes undefined is not an object` error. Because native-base@2.2.1 still has a lot of js file using deprecated `_react2.default.PropTypes`. Will be a fix for this?

>

**Comment by shivrajkumar** [comment]
#1001
