### ISSUE TITLE
Wrong the type definitions of the Card's properties

### ISSUE THREAD

**Issue by GalochkinKirov** [GeekyAnts/NativeBase#1060]
The version of Native Base is 2.2.0.

Maybe there are some errors in the props definitions in the /native-base/src/basic/Card.js:

```
Card.propTypes = {
  ...ViewPropTypes,
  style: React.PropTypes.object,
  dataArray: React.PropTypes.object,
  renderRow: React.PropTypes.object
};
```

I think it should look like this:

```
Card.propTypes = {
  ...ViewPropTypes,
  style: React.PropTypes.object,
  dataArray: React.PropTypes.array,
  renderRow: React.PropTypes.func
};
```

According to the documentation on the official page:
https://facebook.github.io/react-native/docs/listview.html

See. the props definitions.

**Comment by rizalsidikp** [comment]
is this issue still relevan ? if yes, i would love to fix it

**Comment by GalochkinKirov** [comment]
why not? of course

**Comment by shivrajkumar** [comment]
Closing this as the PR referencing this issue a=has been merged
