### ISSUE TITLE
DefaultTabBar - Change Default Color

### ISSUE THREAD

**Issue by Jeremaiha** [GeekyAnts/NativeBase#1061]
Hi everyone,
Would be very grateful if you could change the default system color in `DefaultTabBar .js` to any possible color for the programmers choice.
In `DefaultTabBar.js`, line 97, backgroundColor.

**Comment by shivrajkumar** [comment]
@Jeremaiha Refer [this](http://docs.nativebase.io/Components.html#tabs-def-headref)
There are props like tabStyle and activeTabStyle which can be used to change the default TabBar backgroundColor. Or you can also make the changes in the ejected theme for the same.
