### ISSUE TITLE
Segment Display separator missing with two buttons 

### ISSUE THREAD

**Issue by acahir** [GeekyAnts/NativeBase#1064]
## react-native, react and native-base version
react-native@0.45.1
react@16.0.0-alpha.12
native-base@2.1.4

## Expected behavior
Create a new Segment wth two segments with none active to begin. Expected two segment control with a separator between One and Two.

## Actual behavior
No separator between segments is displayed. Tracked back to default style in line 16 of Segment.js (from ejected styles):

    "NativeBase.Button": {
      alignSelf: "center",
      borderRadius: 0,
      paddingHorizontal: 20,
      height: 30,
      backgroundColor: "transparent",
      borderWidth: 1,
      borderColor: variables.segmentBorderColor,
      elevation: 0,
      ".active": {
        backgroundColor: variables.segmentActiveBackgroundColor,
        "NativeBase.Text": {
          color: variables.segmentActiveTextColor
        }
      },
      ".first": {
        borderTopLeftRadius: platform === "ios" ? 5 : undefined,
        borderBottomLeftRadius: platform === "ios" ? 5 : undefined,
        borderRightWidth: 0
      },
      ".last": {
        borderTopRightRadius: platform === "ios" ? 5 : undefined,
        borderBottomRightRadius: platform === "ios" ? 5 : undefined,
        borderLeftWidth: 0
      },

With only first and last buttons, no border separator is displayed.

## Steps to reproduce (code snippet or screenshot)

            <Segment>
              <Button first>
                <Text>One</Text>
              </Button>
              <Button last>
                <Text>Two</Text>
              </Button>
            </Segment>

## Is the bug present in both ios and android or in any one of them?

Both I believe.

## Suggested fix

If by default all segments had borderLeftWidth=0, and then .first borderLeftWidth=1, it would work in all cases. See below

    'NativeBase.Button': {
      alignSelf: 'center',
      borderRadius: 0,
      paddingHorizontal: 25,
      height: 30,
      backgroundColor: 'transparent',
      borderWidth: 1,
      borderLeftWidth: 0,
      borderColor: variables.segmentBorderColor,
      elevation: 0,
      '.active': {
        backgroundColor: variables.segmentActiveBackgroundColor,
        'NativeBase.Text': {
          color: variables.segmentActiveTextColor
        }
      },
      '.first': {
        borderTopLeftRadius: (platform=='ios') ? 5 : undefined,
        borderBottomLeftRadius: (platform=='ios') ? 5 : undefined,
        borderLeftWidth: 1
      },
      '.last': {
        borderTopRightRadius: (platform=='ios') ? 5 : undefined,
        borderBottomRightRadius: (platform=='ios') ? 5 : undefined,
      },

**Comment by shivrajkumar** [comment]
@acahir Yes, that will also work. What we have done is, we have given border to all Buttons and removed borderRight of first button and borderLeft of last button. Both does the same. But if we do it the way you described, there is no need for `last` prop. Only having `first` prop didn't seem right. So to have the constant flow with the use cases. We have done it that way.

**Comment by acahir** [comment]
What you did makes sense, but you still have a bug with only two buttons and no initial selection.

If you want to keep both `first` and `last` props, then you need to check to see if the array length is 2, and if so, keep one of the borders so you have a separator.

**Comment by shivrajkumar** [comment]
Yes, that makes sense
