### ISSUE TITLE
Segments overflow.

### ISSUE THREAD

**Issue by shikya** [GeekyAnts/NativeBase#1065]
## react-native, react and native-base version
    "react": "16.0.0-alpha.6",
    "react-native": "0.44.0",
    "native-base": "2.1.1",

## Expected behavior
Segments either should wrap around or child button's should adapt the width.

## Actual behavior
Segments overflowing the parent view.

## Steps to reproduce (code snippet or screenshot)
Follow the documentation provided http://docs.nativebase.io/Components.html#segment-outside-header-headref and add too many buttons to the UI.

## Screenshot of emulator/device
<img width="380" alt="screen shot 2017-07-18 at 11 41 55 am" src="https://user-images.githubusercontent.com/8678847/28303974-468722a8-6bb3-11e7-99b6-cad7303b0ff4.png">

## Is the bug present in both ios and android or in any one of them?
Both.

## Any other additional info which would help us debug the issue quicker.
Nope.

**Comment by sankhadeeproy007** [comment]
Usually segments are to be used when there are 2-3 buttons. For cases like yours, you're better off using Tabs/ScrollableTabs.

**Comment by shikya** [comment]
Well, I am not using as tabs. I need it to a group some buttons.
Just like how we have a behavior of radio button group.

For example pills in bootstrap.

**Comment by sankhadeeproy007** [comment]
Adding more than 3 buttons will crop off the text. Segments are intended for use with 2 or 3 buttons.
You can customize tabs to make it look like pills.

**Comment by shikya** [comment]
Ok, thank you.

**Comment by dev-pacific22** [comment]
I have the same issue with three buttons only. My button text is quite long so how to handle it now, any idea?

**Comment by pavawit** [comment]
How about make it scrollable?
Because the shape of the segment makes users know that there're other buttons.
```
<ScrollView horizontal>
  <Segment>
    <Button first>
      <Text>So long long long long longgggggggggg text</Text>
    </Button>
    <Button last>
      <Text>here</Text>
    </Button>
  </Segment>
</ScrollView>
```
