### ISSUE TITLE
Customising Item

### ISSUE THREAD

**Issue by Rolando-Barbella** [GeekyAnts/NativeBase#1066]
First time using the library, I was wondering.

Why this work?

` <Item style={{ marginBottom:10 }} regular>`

And not this one

`<Item style={style.customStyle} regular>`

I  also tried

`<Item style={{...style.customStyle}}  regular>`

Thanks

**Comment by sankhadeeproy007** [comment]
is `customStyle` using `StyleSheet.Create()` ?

**Comment by Rolando-Barbella** [comment]
Is coming from following (in the same file).

> const styles = StyleSheet.create({
>   customStyle: {
>     marginBottom:10,
>   },
> });

I solved by doing `StyleSheet.flatten(styles.customStyle)` it will be nice to use a more standard solution :)
Thank you

**Comment by shivrajkumar** [comment]
Fixed with v2.3.0
