### ISSUE TITLE
WebView inside of a Container->Content?

### ISSUE THREAD

**Issue by robputer** [GeekyAnts/NativeBase#107]
Sorry if this is a silly question, just wondering if this is possible?  I have a PDF I need to show, and I'm using a WebView to display it.  It doesn't seem to want to render within <Content>.

**Comment by sankhadeeproy007** [comment]
@robputer Do you have a screenshot of the error? Try using the webview inside a `<View />` and see if that works.

**Comment by ddobby94** [comment]
+1
Started using WebView and if I use Container-> Content it will not render, If I replace the Container and Content with the View it will render.

**Comment by sankhadeeproy007** [comment]
Related to https://github.com/facebook/react-native/issues/4773
Please specify a height for the `<WebView />` component.

**Comment by grohsfabian** [comment]
Hello,

I'm opening this since I want to add a WebView inside the Content and it is not displaying. If I set the height it will, but I want it full page.

**Comment by sankhadeeproy007** [comment]
Set the height to deviceheight

**Comment by grohsfabian** [comment]
And then it will display over the menu / footer .. so it's not good

**Comment by sankhadeeproy007** [comment]
Minus the height of header and footer. Because that is the way react native scrollview works and native-base is just a wrapper around it.

**Comment by sanketsahusoft** [comment]
@grohsfabian @sankhadeeproy007 I think setting the height using deviceHeight isn't a good idea. We can achieve the same thing using flex. Instead of <Content /> we can just place <WebView /> with { flex: 1 }

**Comment by grohsfabian** [comment]
It just doesn't work. I've tried to set it with { flex: 1 } but It won't show.

**Comment by horiuchie** [comment]
I have encountered the same problem and solved following.
```
render () {
  return (
    <Container>
      <Content contentContainerStyle={{flex: 1}}>
        <WebView source={{ uri: 'something' }} />
      </Content>
    </Container>
  );
}
```

**Comment by travismgibson** [comment]
Thank you horiuchie!
