### ISSUE TITLE
tabBarBackgroundColor is not working 

### ISSUE THREAD

**Issue by ShaileshPrajapati-BTC** [GeekyAnts/NativeBase#1071]
<Tabs 
            initialPage={0} 
            tabBarPosition='bottom' 
            tabBarUnderlineStyle={{ backgroundColor: '#004FBB'}}
            tabBarBackgroundColor="red"
          >
            <Tab heading={ <TabHeading><Icon name="md-list-box" /><Text>Care Plan</Text></TabHeading>}>
              <Text>d</Text>
            </Tab>
            <Tab heading={ <TabHeading><Icon name="md-calendar" /><Text>Appointments</Text></TabHeading>}>
              <Text>dss</Text>
            </Tab>
        </Tabs>

**Comment by devanshsadhotra** [comment]
same here !!1 even i am facing the same issue.

**Comment by ShaileshPrajapati-BTC** [comment]
i found the solution
<Tabs>
  <Tab heading={ <TabHeading style= {{backgroundColor: 'red'}}><Icon name="md-list-box" /><Text>Care Plan</Text></TabHeading>}>
    <Page1/>
  </Tab>
  <Tab heading={ <TabHeading style= {{backgroundColor: 'red'}}><Icon name="md-calendar" /><Text>Appointments</Text></TabHeading>}>
    <Page2/>
  </Tab>
</Tabs>

**Comment by devanshsadhotra** [comment]
i got the even better solution!! after referring to Native-Base documentation ! PLease refer to under mentioned tutorial

https://docs.nativebase.io/Customize.html#Customize

**Comment by shivrajkumar** [comment]
@ShaileshPrajapati-BTC @devanshsadhotra Both your solutions should work fine. But also there are `tabStyle` and `activeTabStyle` prop for this, which needs to be passed to each Tab component.

**Comment by towfiqi** [comment]
@shivrajkumar I am trying to have tab headings with transparent color, but its not working, there is always this grey color under the tabs:

```
<Tabs 
 style={styles.tabs} 
  initialPage={0} 
  onChangeTab={({ i, ref, from })=> this.tabChange(i)}
  tabBarUnderlineStyle={ {backgroundColor: '#f65857'}}
  tabBarBackgroundColor={'transparent'}
  >
                        <Tab heading={ <TabHeading style={{backgroundColor: 'transparent'}}><Text>Upcomming</Text></TabHeading>}>
                            <Text>Tabs 1</Text>
                        </Tab>
                    
                        <Tab heading={ <TabHeading style={{backgroundColor: 'transparent'}}><Text>Past</Text></TabHeading>}>
                            <Text>Tabs 2</Text>
                        </Tab>
</Tabs>
```

**Comment by towfiqi** [comment]
^^ Never Mind, Its working fine.. :)

**Comment by yerycs** [comment]
Hi @towfiqi
Tab header transparent is not working for me. If you find solution, could you please let me know?
