### ISSUE TITLE
How to make header fixed at top?

### ISSUE THREAD

**Issue by mdmush** [GeekyAnts/NativeBase#1072]
Hi GeekyAnts,

I was looking for any prop or styling that can make the header in my application fixed on top. So that whenever i scroll down, it don't go up with the content.

Thanks and regards.

**Comment by shivrajkumar** [comment]
@mdmush 
```
<Container>
   <Header>
     ....
   </Header>
   <Content>
      .....
   </Content>
</Container>
```
This syntax of NativeBase component fixes the Header to the top by default.
