### ISSUE TITLE
native-base not working with CRNA

### ISSUE THREAD

**Issue by Levitskyi** [GeekyAnts/NativeBase#1076]
package version: 
```
    "expo": "^18.0.3",
    "native-base": "^2.3.0",
    "react": "16.0.0-alpha.12",
    "react-native": "^0.45.1"
```

Steps to reproduce:
```
npm install -g create-react-native-app
create-react-native-app AwesomeProject
npm install native-base --save
npm start
```
-and then try to import something from native-base:
`import { Container } from 'native-base';`

maybe I miss something guys? :(
-------------------------------------
-------------------------------------
Unable to resolve module `react-native/Libraries/Renderer/shims/ReactNativePropRegistry` from `/Users/taraslevitskyi/projects/AwesomeProjectTest/node_modules/native-base/dist/src/Utils/computeProps.js`: Module does not exist in the module map or in these directories:
  /Users/taraslevitskyi/projects/AwesomeProjectTest/node_modules/native-base/node_modules/react-native/Libraries/Renderer/shims
,   /Users/taraslevitskyi/projects/AwesomeProjectTest/node_modules/react-native/Libraries/Renderer/shims

**Comment by shivrajkumar** [comment]
#1039
