### ISSUE TITLE
Peer dep missing: react-native@>=0.46.0, required by native-base@2.3.0

### ISSUE THREAD

**Issue by MichaelSzer** [GeekyAnts/NativeBase#1077]
When I do 'npm start' I get the following Warning: "'react-native' peer dependency missing."
Then when I did npm ls I found this: "Peer dep missing: react-native@>=0.46.0, required by native-base@2.3.0"

How can I solve this?

**Comment by shivrajkumar** [comment]
@MichaelSzer Which version of React and React Native are you on?

**Comment by productiveme** [comment]
The problem goes away for me when I roll back to version 2.2.0 of native-base

**Comment by shivrajkumar** [comment]
https://github.com/GeekyAnts/NativeBase#6-compatibility-versions
Check the compatibility
