### ISSUE TITLE
Scroll Issue

### ISSUE THREAD

**Issue by alexprice91** [GeekyAnts/NativeBase#108]
I have create a "Modal" using absolute position and zIndex. Within there I have several InputGroups.

My modal initially looks like this:
<img width="771" alt="screen shot 2016-08-11 at 8 58 50 am" src="https://cloud.githubusercontent.com/assets/4140149/17591065/013f3d34-5fa2-11e6-8680-3c5f9b63194b.png">

If I click on an Input it then looks like this:
<img width="768" alt="screen shot 2016-08-11 at 8 59 07 am" src="https://cloud.githubusercontent.com/assets/4140149/17591076/0ab8b66a-5fa2-11e6-8cf1-209288a9c934.png">

I am trying to push the content up so the input is still visible.

**Comment by sankhadeeproy007** [comment]
Hi, can you try with the latest release and check if it persists?
