### ISSUE TITLE
OnPress not working inside Col, List

### ISSUE THREAD

**Issue by googl3r** [GeekyAnts/NativeBase#1082]
Hi! 
I have a List of items and a onPress in Text but onPress is not being triggered and i don't know where the problem come from ?

here is a part of my code 
 
`<List dataArray = {this.chunk(this.state.sandwiches,2)} renderRow = {(item) => 
            <Row>
               <Col style ={this.dynamicStyle(item[0].sandwiches.color)}>                   
                    { this.state.displayImage && 
                   <View>
                            <TouchableOpacity onpress = {_ => alert('hello')}>
                        <Image source = {images[item[0]._key]} 
                                style = {this.imageDynamicTransformation(parseFloat(item[0].sandwiches.scale))} resizeMode='contain'/>                  
 </TouchableOpacity>
`

**Comment by shivrajkumar** [comment]
@googl3r It should be `onPress` not `onpress`

**Comment by googl3r** [comment]
@shivrajkumar even after changing to onPress still doesn't work...i don't know if using componentDidMount have a relation with this

**Comment by googl3r** [comment]
i don't know why this issue is closed!!

**Comment by shivrajkumar** [comment]
@googl3r The above code snippet seems to work with `onPress`.
If you still facing this issue. Please post a complete code. So that we can reproduce this error

**Comment by googl3r** [comment]
hi, i changed my code and added ListItem and its works fine now, thx
