### ISSUE TITLE
iOS: Using initialTab using a variable 

### ISSUE THREAD

**Issue by moritzschaefer** [GeekyAnts/NativeBase#1083]
Hi! Thanks for trying out NativeBase!
Due to the overwhelming requests and issues/questions we ask you to add the following details with your issue.

Please check the existing open/closed issues for a possible duplicate before creating a new issue :)

Also **DO** fill out the below form to give us a better idea about your environment and help us debug it quicker. Issues without the required details will mostly be unattended to.

## react-native, react and native-base version
native-base: 2.21
react-native: 0.46.4

## Expected behaviour

Clicking on a tab "scrolls" the TabViews to the corresponding Tab

## Actual behaviour

In Android the expected behaviour is observed. Under iOS though the TabView immeadeately changes to the View of the Tab being clicked and then, in addition, the Tab scrolls by the distant number of tabs so if I click on a tab that is two tabs to the right of the current active one (be it tab 0). It immedetely shows Tab 2 and then scrolls to Tab 4.

## Steps to reproduce (code snippet or screenshot)

The issue is provoked by using the initalTab property along with the onChangeTab property. If updating the same property in onChangeTab, as the one which is used in initialTab, the actual behaviour is observed.

    onChangeTab = ({ i }) => {
      this.setState({currentTab: i});
    }

    <Tabs initialPage={this.state.currentTab} onChangeTab={this.onChangeTab}>

## Is the bug present in both ios and android or in any one of them?
iOS only
## Any other additional info which would help us debug the issue quicker.

**Comment by dylandupreez** [comment]
Experiencing the same issue

**Comment by dylandupreez** [comment]
Managed to solve this by not setting the state variable on IOS. My code was triggering a redux action and updating the store on tab change, so the state of the application was consistent with what the tab control was displaying anyway (this may not be the case for you). It seems that the onChangeTab event fires a second time on IOS, after the tab has been selected and if you alter the initial tab it gets set to -1.

**Comment by shivrajkumar** [comment]
@moritzschaefer Let us know if you are still facing the issue

**Comment by moritzschaefer** [comment]
@shivrajkumar I workarrounded this by using separate variables for initialPage and currentPage.
@dylandupreez can you comment?

**Comment by dylandupreez** [comment]
I my case, I just let the tab control set the current page variable in state and don't update the initialPage prop (i.e. set it using a prop). I think that is pretty much exactly what you have suggested @moritzschaefer , that way I can use the state variable for the other business logic that it was needed for and it doesn't interfere with the tab control.

**Comment by moritzschaefer** [comment]
As I currently have no iOS/macOS device to test this I close this now.

**Comment by JaEdmuva** [comment]
Sorry to say this but, not having a device to test on is enough reason to close an unresolved issue? That's is very sad!! The issue is still there, the proposed solutions are just work arounds, but the issue is not really fixed. BTW I'm using v2.3.10. Please have a look at the issue again.
