### ISSUE TITLE
roboto_medium on windows?

### ISSUE THREAD

**Issue by j2l** [GeekyAnts/NativeBase#1084]
Noob question but I followed doc, copied fonts in native-base\Fonts 
![image](https://user-images.githubusercontent.com/65325/28425364-5af94aa4-6d70-11e7-80d8-588a5921da23.png)

and installed Roboto fonts on Windows but I still get error in expo XDE (and device, red screen) when connected to Android 5.1.1 device:

`fontFamily 'Roboto_medium' is not a system font and has not been loaded through Exponent.Font.loadAsync.
`

I needed to adapt async function to EC6 to please Expo XDE, so here's my async load:
```
async () => {
await Expo.Font.loadAsync({
    'Roboto': require('native-base/Fonts/Roboto.ttf'),
    'Roboto_medium': require('native-base/Fonts/Roboto_medium.ttf'),
  });
}
```

**Comment by shivrajkumar** [comment]
@j2l Try this at the root level of your app`async componentWillMount() {
    await Expo.Font.loadAsync({
      Roboto: require('native-base/Fonts/Roboto.ttf'),
      Roboto_medium: require('native-base/Fonts/Roboto_medium.ttf'),
    });
  }`

**Comment by j2l** [comment]
Thanks, but I tried that, it throws an error about missing "=>"

**Comment by shivrajkumar** [comment]
@j2l Then you can raise an issue about this in Expo github repo. As the requirement with NativeBase is to have the Font but loading custom font is something which Expo handles

**Comment by j2l** [comment]
reading https://github.com/expo/shoutem-example/blob/master/main.js 
I see async must be INSIDE the class, it was outside.
May be this is it?
