### ISSUE TITLE
Where is ''native-base/backward'?

### ISSUE THREAD

**Issue by jeremypeters** [GeekyAnts/NativeBase#1093]
I just upgraded from 0.5.15 to 2.3.0 and want to carry on using the old style for the time being. According to the docs https://docs.nativebase.io/docs/Migration.html I can import the components from 'native-base/backward', but I get the error message "Unable to resolve module 'native-base/backward'...". Is the documentation out of date?

**Comment by jeremypeters** [comment]
OK, looks like it was removed in v2.2.0. Probably a good idea to remove from the docs if it has been removed.

**Comment by sankhadeeproy007** [comment]
Yes thanks for pointing it out. Will be removed soon!
