### ISSUE TITLE
Swipable List throws error

### ISSUE THREAD

**Issue by WiseClock** [GeekyAnts/NativeBase#1096]
When followed the example given [here](https://docs.nativebase.io/Components.html#swipeable-multi-def-headref), react native throws an error.

> Error calling RCTEventEmitter.receiveEvent
> 
> Exception calling object as function: TypeError: JSON.stringify cannot serialize cyclic structures. (<unknown file>:4861)
> run
>     NativeRunnable.java
> handleCallback
>     Handler.java:739
> dispatchMessage
>     Handler.java:95
> dispatchMessage
>     MessageQueueThreadHandler.java:31
> loop
>     Looper.java:148
> run
>     MessageQueueThreadImpl.java:194
> run
>     Thread.java:818

Also mentioned in https://github.com/GeekyAnts/NativeBase/issues/883#issuecomment-316618567

## react-native, react and native-base version

> react: 16.0.0-alpha.12
> react-native: 0.46.4
> native-base: 2.3.0

## Expected behaviour

> renders the swipable listview.

## Actual behaviour

> throws an error.

## Steps to reproduce (code snippet or screenshot)

> Follow the example given in the [docs](https://docs.nativebase.io/Components.html#swipeable-multi-def-headref) and run it.

## Screenshot of emulator/device

![image](https://user-images.githubusercontent.com/1351819/28514083-99588e64-700d-11e7-8104-9559d8e4dad4.png)

## Is the bug present in both ios and android or in any one of them?

> Not sure about iOS, but happened on Android.

**Comment by shivrajkumar** [comment]
@WiseClock The example code for Swipable List seems be wrong in the docs. It will be fixed soon. For time being you can refer [this](https://github.com/GeekyAnts/NativeBase-KitchenSink/tree/master/js/components/listSwipe) for the working example

**Comment by ccfiel** [comment]
@shivrajkumar your reference is a dead link :(

**Comment by SupriyaKalghatgi** [comment]
https://github.com/GeekyAnts/NativeBase-KitchenSink/blob/master/src/screens/listSwipe/basic-list-swipe.js
