### ISSUE TITLE
how to set card item background color transparent?

### ISSUE THREAD

**Issue by bphsuan** [GeekyAnts/NativeBase#1097]
Hi,I would like to change background color of CardItem into transparent
I tried "CardItem button transparent",but it didn't work.
p.s : This is about button transparent method → [button transparent](http://nativebase.io/docs/v0.4.6/components#cardShowcase)
` 

           <Image
                source={require('../images/drawer.png')}
                style={styles.backgroundImage}>
                <Container >
                    <Content>
                        <List>
                            <ListItem>
                                    <Text>Test</Text>
                            </ListItem>
                            <Content>
                                <Card 
                                    style={{
                                        elevation: 0,//remove shadow on Android
                                        shadowOpacity: 0,//remove shadow on iOS
                                        width:278 }}>
                                    <CardItem button onPress={() => Alert.alert('hi')}  >
                                        <Icon name="plane" style={{fontSize:10}}/>
                                        <Text style={{fontSize:10,fontFamily:'monospace'}}>Register</Text>
                                        <Right>
                                        <Icon name="arrow-forward" style={{fontSize:10}} />
                                        </Right>
                                    </CardItem>
                                    <CardItem button>
                                        <Icon name="plane" style={{fontSize:10}}/>
                                        <Text style={{fontSize:10,fontFamily:'monospace'}}>Login</Text>
                                        <Right>
                                        <Icon name="arrow-forward" style={{fontSize:10}} />
                                        </Right>
                                    </CardItem>
                                    <CardItem button>
                                        <Icon name="plane" style={{fontSize:10}}/>
                                        <Text style={{fontSize:10,fontFamily:'monospace'}}>About us</Text>
                                        <Right>
                                        <Icon name="arrow-forward" style={{fontSize:10}} />
                                        </Right>
                                    </CardItem>
                                </Card>
                            </Content>
                        </List>
                    </Content>
                </Container>
             </Image>
`
the result on Android device :
![result](https://user-images.githubusercontent.com/30407039/28520333-a50793f6-70a1-11e7-8dd0-35c15ac521e8.png)
Hope someone could help me,thanks.

**Comment by shivrajkumar** [comment]
@bphsuan Apply style rule `backgroundColor: "transparent"` to CardItem.
`<CardItem button style={{ backgroundColor: "transparent" }}>`

**Comment by bphsuan** [comment]
@shivrajkumar it still doesn't work :((
the background color of card item is still white.

**Comment by shivrajkumar** [comment]
@bphsuan Did you try it for Card?

**Comment by vijaychouhan-rails** [comment]
@bphsuan 

use this
<Card style={{ backgroundColor: "transparent"  }}>
 <CardItem style={{backgroundColor: 'rgba(255, 255, 255, 0.2)'}}>
 <Text>this is transparent background</Text>
