### ISSUE TITLE
According to the sample error（custom theme）

### ISSUE THREAD

**Issue by msevensun** [GeekyAnts/NativeBase#1099]
Hi! Thanks for trying out NativeBase!
Due to the overwhelming requests and issues/questions we ask you to add the following details with your issue.

Please check the existing open/closed issues for a possible duplicate before creating a new issue :)

Also **DO** fill out the below form to give us a better idea about your environment and help us debug it quicker. Issues without the required details will mostly be unattended to.

## react-native, react and native-base version
    "native-base": "^2.2.0",
    "react": "^16.0.0-alpha.12",
    "react-native": "^0.45.1",
    "react-navigation": "^1.0.0-beta.11"
## Expected behaviour
     Can customize the theme

## Actual behaviour
    Error！
   
![image](https://user-images.githubusercontent.com/20658340/28551674-271e67aa-711c-11e7-8aa1-6dc80b0f7370.png)

## Steps to reproduce (code snippet or screenshot)
![image](https://user-images.githubusercontent.com/20658340/28551723-6a6dffb6-711c-11e7-9bca-a802d1ddfe32.png)
![image](https://user-images.githubusercontent.com/20658340/28551737-78389926-711c-11e7-859e-78ed38f1f50c.png)

## Is the bug present in both ios and android or in any one of them?
    Android
## Any other additional info which would help us debug the issue quicker.
   I am according to the official example. why is there an error. I need to know the answer.thank you！

**Comment by shivrajkumar** [comment]
@msevensun The error clearly specify that the error seems to be in line no. 36 of AppContainer
