### ISSUE TITLE
Set all ListItem's to same height

### ISSUE THREAD

**Issue by bsiddiqui** [GeekyAnts/NativeBase#110]
Is it possible to set all ListItem's to the same height? Right now the ListItem has a different height if it's plain text vs. text + badges/icon/etc.

Since the same list could have items with plain text and some with text + badges/icon/etc that can look a bit off.

**Comment by sanketsahusoft** [comment]
As a quick work around, you can write another component which returns

    <ListItem style={ { height: 50 } }>
        {this.props.children}
    </ListItem>

And use this component instead of ListItem.

**Comment by sankhadeeproy007** [comment]
Adding to @sanketsahusoft's answer, we've refrained from using a fixed height for LisItem and related components because setting a fixed height would restrict the possibilities of having different child components.
