### ISSUE TITLE
mutable item in a row

### ISSUE THREAD

**Issue by emsihyo** [GeekyAnts/NativeBase#1100]
I need mutable item in a row,but follow code doesn't work.
<List 
style={{ flexDirection: 'row', flexWrap: 'wrap' }} 
dataArray={this.state.data} 
renderRow={(rowData, sectionID, rowID, highlightRow) => { return 
<ListItem 
style={{ width: 100 }}>
<Image source={{ uri: rowData.image }} style={{ height: 100, width: 100 }}></Image>
</ListItem > }}>
</List>

**Comment by shivrajkumar** [comment]
@emsihyo NativeBase accepts just the array. YOu can use React Native ListView instead
