### ISSUE TITLE
Floating Label with Error

### ISSUE THREAD

**Issue by kelvinblade** [GeekyAnts/NativeBase#1102]
I am trying to display the red underline error with the red cross icon shown here https://docs.nativebase.io/Components.html#error-textbox-headref with the  floating Label shown here https://docs.nativebase.io/Components.html#floating-label-headref.

`<Item floatingLabel>
  <Label>Username</Label>
              <Input />
            </Item>`

How do I add the error prop "error" to Item conditionally? `<Item error>`

Thanks.

`<Item floatingLabel error>
          <Label>{field.placeholder}</Label>
          <Input
            className="form-control"
            type={field.type}
            {...input}
            disabled={disabled}
            />
            {touched ? <Icon name='close-circle' style={styles.error} /> : <Text />}
        </Item>`

I tried this but the red line is always showing and the icon is on the left side of the text

**Comment by shivrajkumar** [comment]
@kelvinblade 
```
<Item floatingLabel error>
 <Label>Username</Label>
 <Input />
 <Icon name="close" />
</Item>
```
should work.
But Icons with FloatingLabel shows only on left.
We are working on to fix it.

**Comment by kelvinblade** [comment]
@shivrajkumar 

thanks for the reply, it works but how can i only show the red line when there's an error?

**Comment by ardifirmansyah8** [comment]
is this bug fix? i need floating label with icon on right of input. I want to create password field with show / hide password masking.

**Comment by Garrett-Smith-iq** [comment]
Until this issue is closed you can put the icon on the right with style.

```
<Item style={{ flexDirection: 'row-reverse' }} >
```

**Comment by akhil-geekyants** [comment]
Made a PR #1356

**Comment by TomMahle** [comment]
Is there a good way to display error text in a floatingLabel item? 
This does not display the text at all, and was all I could find in the documentation.

        <Item error={hasError} floatingLabel={true}>
            {hasError ? <Text>{error}</Text> : <Text />}
            <Label>{label}</Label>
            <Input {...passThroughInputProps} {...passThroughProps} />
        </Item>

**Comment by chinmay-xenious** [comment]
This issue is not solved by the style={{ flexDirection: 'row-reverse' }},
Because after use this style, item left margin was swap to right.

Any more option?

**Comment by chinmay-xenious** [comment]
Also there is an icon position issue for floatingLabel Item with 'last' property.

**Comment by ettaibi** [comment]
having same issue, Icons on the right with floating label doesn't work

**Comment by SupriyaKalghatgi** [comment]
Issue fixed here
https://github.com/GeekyAnts/NativeBase/commit/d51b2f94cadd4f60d2a17445c2b9f52d6a35597a

**Comment by SupriyaKalghatgi** [comment]
Sorry for informing late, that was fixed with [2.4.3](https://github.com/GeekyAnts/NativeBase/releases/tag/v2.4.3)

Though merge notifications were visible here

**Comment by eaazumah** [comment]
Using 2.8.1 and having the same issue

**Comment by nityashagrawal** [comment]
I am trying to render a transparent button on the right with an icon wrapped in it inside an item with floating label. But, the icon isn't showing. However, if I just change it back to regular, the button is rendered. Also, if I remove the button tag and just render the icon, it is rendered in floating label as well.
