### ISSUE TITLE
custom image component

### ISSUE THREAD

**Issue by bitlab-code** [GeekyAnts/NativeBase#1103]
Hi! Thanks for NativeBase!
Is it possible to use a **custom image component** in Native Base Components (i.e. _Thumbnail_, etc..)?

i.e. use `<CachedImage />` provided by [`react-native-cached-image`](https://github.com/kfiroo/react-native-cached-image)
just like in this repo:  [`react-native-image-progress`](https://github.com/oblador/react-native-image-progress#using-a-custom-image-component)

if currently it isn’t possible… do you accept a feature request?

Tks.

**Comment by shivrajkumar** [comment]
@bitlab-code No, its not possible to use react-native-cached-image with NativeBase Thumbnail component. Still you can use any components with NativeBase components. So if you want to use your custom component you can use and apply similar styling which Thumbnail has

**Comment by bitlab-code** [comment]
@shivrajkumar thanks a lot for the quick answer, 
based on your answer and reading the doc and the source code, I'was able to customize the component.
It seem to work, but don't know if the code and the practices that i have used are correct, please can you give me a feedback about following code.

`components/Thumbnail.js`
```javascript
import React, { Component } from "react";
import { StyleSheet } from 'react-native';
import { connectStyle, StyleProvider } from 'native-base';
// import computeProps from "native-base/src/Utils/computeProps.js";
// import mapPropsToStyleNames from "native-base/src/Utils/mapPropsToStyleNames.js";
import CachedImage, { ImageCacheProvider } from 'react-native-cached-image';

class Thumbnail extends Component {
  render() {
    // connect styles to props.style defined by the theme
    const styles = this.props.style;
    return (
      <StyleProvider style={NativeBaseTheme}>
        <CachedImage ref={c => (this._root = c)} {...this.props} />
      </StyleProvider>
    );
  }
}

const NativeBaseTheme = {
  'NativeBase.Thumbnail': {
    // overrides Thumbnail style...
  }
};
const customStyles = StyleSheet.create({
  width: 180,
  height: 180,
  borderRadius: 40,
});

// connect the component to the theme
export default connectStyle('NativeBase.Thumbnail', NativeBaseTheme)(Thumbnail);
```
`screens/Home.js`
```javascript
import Thumbnail from '../components/Thumbnail';
//...
<Thumbnail large source={{ uri: 'https://www.google.it/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png' }} />
//...
```

It seem to work because the image is correctly cached by `CachedImage` but I'm not able to override Thumbnail style inside `NativeBaseTheme` const

**Comment by shivrajkumar** [comment]
Yes, the code seems fine. You can just overwrite the styles with the required
```
const NativeBaseTheme = {
  'NativeBase.Thumbnail': {
    // overrides Thumbnail style...
  }
};
```

**Comment by shivrajkumar** [comment]
Closing this for now. Let us know if you still need any help with this
