### ISSUE TITLE
Android: How to create a Picker that must be selected?  (E.g. "Select one...")

### ISSUE THREAD

**Issue by lukecwilliams** [GeekyAnts/NativeBase#1105]
## react-native, react and native-base version
react-native@0.46.4
react@16.0.0-alpha.12
native-base@^2.3.0

## Expected behaviour
Able to create a "Select one..."-style dropdown Picker for Android

## Actual behaviour
There doesn't appear to be any way to do this.  `placeholder` is only available in iOS.

This is an important design capability because in many cases, there is no default value and the designer needs to ensure the user does see the dropdown and select something.

What is the recommended way to implement this case?

We could get around this in a bit of an ugly way by just adding a "Select one..." item to the top of the list - however that doesn't work because it's impossible in Native Base to add a single Item followed by an array of Items.  (See https://github.com/GeekyAnts/NativeBase/issues/983.)

**Comment by shivrajkumar** [comment]
@lukecwilliams NativeBase picker for android is a direct implementation of react-native's picker. Since React Native Picker doesn't have this yet, there is no way of doing this as of now.

**Comment by lukecwilliams** [comment]
I see, thanks for the info.

**Comment by lloydaf** [comment]
[https://stackoverflow.com/questions/42169272/how-to-provide-picker-a-default-please-select-option](url)
Seems like a workaround for now.

**Comment by vksgautam1** [comment]
is there any way to do this ?

**Comment by lloydaf** [comment]
Sorry guys, for some reason the link doesn't seem to work. Here's how I did it.

`...
constructor(props){
        super(props);
        this.state = {
            selectedCategory: null
        }
    }

    changeCategory = (category)=>{        
        this.setState({
            selectedCategory : category
        });
    }
...
<Picker
            mode="dropdown" 
            iosHeader="Category" 
            selectedValue={this.state.selectedCategory}
            onValueChange={this.changeCategory.bind(this)}
            >
            <Picker.Item label="Select Category" value={null}/>
                    {
                        this.props.categories.map((item,index)=>{
                            return <Picker.Item key={index} label={item} value={item} />;
                        })
                    }
            </Picker>`

So the idea is to add an extra option, and set the selectedValue to the value of that option. In my case, I added a default option with a value = _null_. Hope this helps.

**Comment by gomestai** [comment]
thanks for workaround lloydaf, seems not the best solution but it works!

**Comment by akhil-geekyants** [comment]
@udarts Picker expects its children to be a `<Picker.Item/>` component. It does not accept any other values (like boolean).

**Comment by SCasarotto** [comment]
Super Duper ugly but works:

```
<Picker
  mode="dropdown"
  iosHeader="Select a vehicle"
  iosIcon={<Icon name="ios-arrow-down-outline" />}
  style={styles.vehiclePicker}
  selectedValue={vehicle}
  onValueChange={vehicle => this.setState({ vehicle })}
>
  {/*Technically this should be loaded from the server*/}
  {Platform.OS === "android"
    ? ["Select a vehicle", "Sedan", "SUV"].map((option, index) => (
        <Picker.Item
          key={`vehicle_${index}`}
          label={option}
          value={option === "Select a vehicle" ? null : option}
        />
      ))
    : ["Sedan", "SUV"].map((option, index) => (
        <Picker.Item key={`vehicle_${index}`} label={option} value={option} />
      ))}
</Picker>;

```

Seems like something that should really be addressed. Maybe with a prop like `androidDefault` or something.
