### ISSUE TITLE
How do i customize nativebase

### ISSUE THREAD

**Issue by McZieuwa** [GeekyAnts/NativeBase#1107]
Hi, I am trying nativebase out for the first time for one of my projects. I want to customize my project using the instructions given on the documentation. However, the file structure in my nativebase is different from that shown in the documentation. There is no file path like /node_modules/native-base/Components/Themes/light.js which is what the docs says we should copy. Please how do I customize my theme using your current file structure?

**Comment by shivrajkumar** [comment]
@McZieuwa run this `node node_modules/native-base/ejectTheme.js`. This will get you the whole theme of NativeBase in your local repo. And follow [this](http://docs.nativebase.io/Customize.html#Theming_NativeBase_Apps) to customize.

**Comment by McZieuwa** [comment]
Alright, thanks
