### ISSUE TITLE
Changing iconFamily

### ISSUE THREAD

**Issue by fabriciovergal** [GeekyAnts/NativeBase#111]
Hi,

I'm trying to changing **iconFamily** in the **Icon** component to load google MD icons, but with no success.
Can anyone guide me with it ? 

Thanks,
Fabricio.

**Comment by sankhadeeproy007** [comment]
Hi, did you try changing the [light.js](https://github.com/GeekyAnts/NativeBase/blob/master/Components/Themes/light.js) file. You can set the `iconFamily` variable to `MaterialIcons`

**Comment by fabriciovergal** [comment]
So, I can't use 2 font family at same time ?

**Comment by sankhadeeproy007** [comment]
2 font families from native-base? No. You can however use react-native-vector icons for multiple families.
