### ISSUE TITLE
Pass props to extend List's setScrollEnabled

### ISSUE THREAD

**Issue by WiseClock** [GeekyAnts/NativeBase#1110]
I have several Swipable Lists in a ScrollView, but every time I swipe on the List items I need to do a perfect horizontal swipe.  If by any chance the Y offset changes during my swipe, the row closes.

I noticed that when you have a single List it'll work fine because the inner SwipeRow locks the inner ListView in the setScrollEnabled method.  However, it doesn't have a prop callback so I can't extend the method by passing props.  I wish it can be added later.

In the mean time, how can I achieve my goal?  I've tried to inject the original method like this:
```
let originalMethod = obj.method;
obj.method = (params) =>
{
    originalMethod(params);
    // new stuffs here.
}
```
But I need to get the method object first, I've tried setting the ref and use `ref._root.setScrollEnabled` but that returned undefined.
Any suggestions?
Thanks!

## react-native, react and native-base version

> react: 16.0.0-alpha.12
> react-native: 0.46.4
> native-base: 2.3.0

## Steps to reproduce (code snippet or screenshot)

> Wrap several Swipable List in a ScrollView, when you semi-opened the ListItem but vertically scrolled the ScrollView a bit, the row closes.

## Is the bug present in both ios and android or in any one of them?

> in Android.  I believe you can set the `directionalLockEnabled` prop on iOS to avoid it but haven't tried yet.

**Comment by shivrajkumar** [comment]
@WiseClock Try this
```
<List scrollEnabled={this.state.scroll}
swipeGestureBegan={() => this.setState({ scroll: false })}
......
```

**Comment by WiseClock** [comment]
@shivrajkumar Thanks for the reply.
I tried `swipeGestureBegan={() => console.warn(1)}` but it doesn't show anything.
Inside the `List` component there's a `swipeGestureBegan` prop on the `SwipeRow` component:
https://github.com/GeekyAnts/NativeBase/blob/master/src/basic/List.js#L113
But it only executes the code inside, there's no way you could pass any method on the outer `List` props:
https://github.com/GeekyAnts/NativeBase/blob/master/src/basic/List.js#L59
:(

**Comment by akhil-geekyants** [comment]
@WiseClock NativeBase List will be deprecated, very soon this will be documented
So please use React Native’s FlatList in place of it. You can use ListItem for the necessary styling.
