### ISSUE TITLE
Toast  position set center is invalid

### ISSUE THREAD

**Issue by leetlin** [GeekyAnts/NativeBase#1114]
Toast position set center is invalid

## react-native, react and native-base version
"react": "16.0.0-alpha.12"
"native-base": "^2.3.1"
"react-native": "^0.46.4"
## Steps to reproduce (code snippet or screenshot)
```js
Toast.show({
      text: 'set position center',
      type: 'success',
      position: 'center',
      duration: 2000,
 });
```
## Screenshot of emulator/device
![image](https://user-images.githubusercontent.com/9165890/28725040-ba6a11c4-73ee-11e7-833c-0bd7b9af90f9.png)

**Comment by WiseClock** [comment]
Have you tried to wrap your top component in a Root?

> NativeBase Toast can be used to display quick warning or error messages. 
> 
> For Toast to work, you need to wrap your topmost component inside <Root> from native-base.
> 
> ```
> import { Root } from "native-base";
> import { StackNavigator } from "react-navigation";
> const AppNavigator = StackNavigator(
>   {
>     Page: { screen: Page },
>   }
> );
> export default () =>
>   <Root>
>     <AppNavigator />
>   </Root>;
> ```
http://docs.nativebase.io/Components.html#Toast

**Comment by sampsasaarela** [comment]
I have the same problem, and my app is wrapped to Root component. Without Root component, it will throw an error.

**Comment by shivrajkumar** [comment]
@leetlin @sampsasaarela There is no center option with position prop for Toast. Docs has been updated for the same.
If you want toast to be on center of your screen, you can just pass style to it this way
```
<Button onPress={() =>
   Toast.show({
      text: "Some Text",
      buttonText: "Okay",
      position: "bottom",
      style: { bottom: "50%" }
    })}
>
....
</Button>
```

**Comment by remoteportal** [comment]
Did you want the Toast be be vertically centered or the text INSIDE the Toast the be centered horizontally?  I'm trying to figure out horizontal.

**Comment by jaspervanbrian** [comment]
For centering the text inside:
```javascript
Toast.show({                                                                                                                                                                            
        text: "No network connection.",                                                                                                                                                     
        type: "danger",                                                                                                                                                                     
        duration: 3000,                                                                                                                                                                     
        textStyle: {                                                                                                                                                                        
            textAlign: 'center',                                                                                                                                                            
        },                                                                                                                                                                                  
})
```
