### ISSUE TITLE
UI Destroyed in LandScape mode.

### ISSUE THREAD

**Issue by santosh-btc** [GeekyAnts/NativeBase#1116]
I am using native-base.

"native-base": "2.1.4",
 "react": "16.0.0-alpha.6",
"react-native": "0.44.0"

After adding [https://github.com/zbtang/React-Native-ViewPager](url) my app UI destroyed in Landscape mode.

Please Help.

**Comment by sankhadeeproy007** [comment]
Was it working in landscape mode before you added the package?

**Comment by santosh-btc** [comment]
Yes.

**Comment by sankhadeeproy007** [comment]
Then it's a problem with the other library. Please raise an issue there.
