### ISSUE TITLE
Undefined is not an object (evaluating '_reactNative.Keyboard.addListener')

### ISSUE THREAD

**Issue by folivi** [GeekyAnts/NativeBase#112]
I get this error when I try to use  <Content>
Happens with native-base ^0.5.4
and react-native: 0.26.1

**Comment by sankhadeeproy007** [comment]
Which component is causing this error?

**Comment by folivi** [comment]
the Content component

**Comment by sankhadeeproy007** [comment]
Do you have a code sample? Something we can try? Also it is recommended that you use the later versions of react-native with native-base. If upgrading from 0.26 is not possible, please consider using older versions of native-base (0.4.*)
