### ISSUE TITLE
Website outlook/view on 15 inch screen (Mac)

### ISSUE THREAD

**Issue by LAITONEN** [GeekyAnts/NativeBase#1120]
Hello!

I believe you have some compatibility issue with your website that doesn't let it get displayed correctly on 15-inch screens (Mac, in my case). The screen attached is the regular stretched, but not maximized view from my laptop. As you can see, the main issue is happening with the phone image, I can't see the most bottom part of it.
![image](https://user-images.githubusercontent.com/23742868/28745939-59e7272c-748b-11e7-8743-e810c3299e3a.png)

**Comment by SupriyaKalghatgi** [comment]
I have opened this issue on the docs repo here: [#68](https://github.com/GeekyAnts/native-base-docs/issues/68)
Since we split the docs and the source into separate repos.

**Comment by SupriyaKalghatgi** [comment]
Fixed with latest Docs
