### ISSUE TITLE
Support react-native windows platform

### ISSUE THREAD

**Issue by tim-soft** [GeekyAnts/NativeBase#1125]
Microsoft has a tool in development allowing react-native apps to be built into Windows apps. [react-native-windows](github.com/microsoft/react-native-windows)

Messing around with this tool, I've realized that native-base only has platform stubs for ios and android (as do most react-native libs). 

Is there a way to "spoof" the platform as Android within NativeBase to allow any of my native-base apps to build for Windows?

I realize this question is a little strange but felt worth asking.

**Comment by HackedBeat** [comment]
[Correct link to react-native-windows](https://github.com/microsoft/react-native-windows)

**Comment by SupriyaKalghatgi** [comment]
.@tim-soft We dont have plan as of now to do so.
It it works on Windows Platform, then thats great news.
If not, we are sorry, but we cannot help on this.
