### ISSUE TITLE
Swipe to delete on the scrollable tab

### ISSUE THREAD

**Issue by ducle-mobytelab** [GeekyAnts/NativeBase#1126]
I have an app with 2 tabs, in each tab I implemented swipe to delete on the list view but it's not working. 
However, when I disabled the scroll of the tab, it worked.
How can I resolve my problem with both swipe and scroll between tabs?
Thank you.

**Comment by wootwoot1234** [comment]
Did you ever solve this?  I'm having the same issue.  Thanks!

**Comment by ducminh1012** [comment]
No, not yet. I currently disable the swipe between tabs to active delete function.

**Comment by akhil-geekyants** [comment]
Currently this is a limitation. When using swipe list with tabs you have to lock the tabs for row swipe to work correctly. As wrapping the swipeList inside the tab, for horizontal scroll - the parent scroll action dominates the child scroll action which leads only Tab to scroll

**Comment by itanhduy** [comment]
Hello. Any updates for this issue. I'm facing it :(
