### ISSUE TITLE
How to put BackGround color with opacity into the full screen back ground image with Native-Base?

### ISSUE THREAD

**Issue by sa63** [GeekyAnts/NativeBase#1127]
I've found lots of code examples about how to cover with the background color and add opacity into the full-screen image but don't know how to do it with Native-Base? Like in the Login screen there is a Background image. I would like to add some color to it with opacity so it will be changed like in photoshop.

**Comment by shivrajkumar** [comment]
@sa63 Try this
`
<View style={{ backgroundColor: '#CCC' }}>
  <Image source={source} style={{ opacity: 0.5 }}>
     .....
  </Image>
</View>
`

**Comment by sa63** [comment]
Thanks for the example. Must I add the code with <Content> tag or <Container> also needed inside <Image> tag?

**Comment by shivrajkumar** [comment]
@sa63 
```
<Container style={{ backgroundColor: '#CCC' }}>
  <Image source={source} style={{ opacity: 0.5 }}>
     // <Content /> and other code
  </Image>
</Container>
```

**Comment by Hayko1994** [comment]
I wrote all the same but it throws issue about enclosing tag in the line of </Container>
