### ISSUE TITLE
CheckBox not 'tapable' inside of TabViewAnimated

### ISSUE THREAD

**Issue by PatrikTes** [GeekyAnts/NativeBase#1129]
## react-native, react and native-base version
"native-base": "^2.3.1",
"react": "16.0.0-alpha.12",
"react-native": "0.46.4",
"react-native-tab-view": "latest"

## Expected behaviour
I have checkbox inside the latest react-native-tab-view
Checkbox should be redraw based on value (true||false)

## Actual behaviour
Checkbox is always in default state not redrawn. Value is changed, but the UI is always the same. When it's outside of react-native-tab-view, then it's working correctly.

## Steps to reproduce (code snippet or screenshot)
    constructor(props) {
        super(props);
        this.state = {
            checkbox1 : undefined,
            checkbox2 : undefined
        };

    };
    setAcceptAll(){

        this.setState({
            checkbox1 : !this.state.checkbox1
        });

    };

                <ListItem button onPress={()=>this.setAcceptAll()}>
                    <CheckBox checked={this.state.checkbox1}/>                    
                </ListItem>

**Comment by shivrajkumar** [comment]
@PatrikTes Check whether the onPress function is fired for any touchable component inside the react-native-tab-view

**Comment by akhil-geekyants** [comment]
Fixed in the latest version

![checkbox](https://user-images.githubusercontent.com/27768184/32365799-660b37ac-c0a1-11e7-9d85-a7d003cca833.gif)
