### ISSUE TITLE
FAB backgroundColor android

### ISSUE THREAD

**Issue by dominic3** [GeekyAnts/NativeBase#1132]
react-native: 0.46.4
react: 16.0.0-alpha.12
native-base: 2.3.1
Only affects Android

Expected Behavour:
Background color of main FAB button should match color in style prop.

Actual Behavour:
Background color of main FAB button is blue

```
                 <Fab
                    active={this.state.splitFabActive}
                    position="bottomRight"
                    style={{backgroundColor: '#000000'}}
                    onPress={() => this.setState({ splitFabActive: !this.state.splitFabActive })}
                  >
                    <Icon name={(this.state.splitFabActive?"close":"albums")} />
                    <Button style={{ backgroundColor: colors.headerBackground }} onPress={() => this._addSplit() }>
                        <Icon name="add" />
                    </Button>
                    <Button style={{ backgroundColor: '#666' }} onPress={() => this._removeSplit() }>
                        <Icon name="trash" />
                    </Button>
                  </Fab>
```

**Comment by shivenj** [comment]
is this issue fixed? i am facing the same issue in android

**Comment by mgaueca** [comment]
Same here, blue background color...is this issue fixed ?

**Comment by ssavinel** [comment]
Same thing here too. Do you have any idea when this will be fixed ?

**Comment by vitormartins1** [comment]
Same issue here. On iOS works properly. On Android the color don't change.

**Comment by pedrogarciyalopez** [comment]
Same problem, what about fix? @shivrajkumar

**Comment by williamoliveira** [comment]
He fixed it but didn't release yet
For now I required it directly from master like this `"native-base": "GeekyAnts/NativeBase",`, working fine

**Comment by philjoseph** [comment]
Hello - we hit the same bug. Do you have a plan to issue a release that will contain that fix ?

**Comment by MHaendel** [comment]
Is this going to be fixed?

**Comment by dominic3** [comment]
For me, I installed directly from Git which may not be ideal, but it includes the fix untill they issue another release:

npm install --save native-base@https://github.com/GeekyAnts/NativeBase

**Comment by TitanKing** [comment]
It does not work `npm install --save native-base@https://github.com/GeekyAnts/NativeBase` because components folder does not exist anymore. Guess I will have to drop Fab for now.

**Comment by FelipeBohnertPaetzold** [comment]
Same problem here, do you have any plans to solve?

**Comment by crossRT** [comment]
I hit the same problem also.
It would be really appreciated if any fixes can release for us. =)

**Comment by shivrajkumar** [comment]
@crossRT @FelipeBohnertPaetzold @TitanKing @dominic3 @vgabdala @MHaendel @philjoseph This has been fixed and released. Check v2.3.2
