### ISSUE TITLE
Dark, Light button colors are hardcoded instead of using variables.

### ISSUE THREAD

**Issue by elnygren** [GeekyAnts/NativeBase#1136]
All other buttons in https://github.com/GeekyAnts/NativeBase/blob/master/src/theme/components/Button.js use `variables.btnXBg` while light, dark buttons are hardcoded (#f4f4f4, #000).

Also, what's the deal with `btnPrimaryColor` (and other `btn*Color`) getters? They are not being used anywhere.

**Comment by akhil-geekyants** [comment]
Fixed in the latest version
