### ISSUE TITLE
buttonTheme structure has redundancies / is strange ?

### ISSUE THREAD

**Issue by elnygren** [GeekyAnts/NativeBase#1137]
buttonTheme contains top level key `.light` with subkeys `.bordered` and `.transparent`. However, it also contains top level keys `.bordered` and `.transparent` that bot have `.light` as a subkey. 

What's going on here?

https://github.com/GeekyAnts/NativeBase/blob/6212f9f47e4606cceae458592bcb1172dd9af8cf/src/theme/components/Button.js

**Comment by shivrajkumar** [comment]
@elnygren It's, in the case of the different order of passing the props to the component.

**Comment by elnygren** [comment]
The way I see it: `theme/components/*.js` are close to *configuration* files than application code and duplicating configuration because arguments parsing, well, is a code smell if anything.

**Comment by SupriyaKalghatgi** [comment]
Fixed with [2.3.8](https://github.com/GeekyAnts/NativeBase/releases/tag/v2.3.8)
