### ISSUE TITLE
[question] How to remove button shadow on Android?

### ISSUE THREAD

**Issue by pedrogarciyalopez** [GeekyAnts/NativeBase#1141]
Thank you!

**Comment by googl3r** [comment]
add this to the button style: 
shadowOffset: { height: 0, width: 0 },
shadowOpacity: 0,
elevation:0

it should remove button shadow on android

**Comment by GreatAuk** [comment]
> add this to the button style:
> shadowOffset: { height: 0, width: 0 },
> shadowOpacity: 0,
> elevation:0
> 
> it should remove button shadow on android

just `elevation: 0` ?
