### ISSUE TITLE
Header background not updating when theme is recalculated with a different toolbarDefaultBg color.

### ISSUE THREAD

**Issue by mini-eggs** [GeekyAnts/NativeBase#1142]
## react-native, react and native-base version
react-native: using the expo fork. https://github.com/expo/react-native/archive/sdk-19.0.0.tar.gz
react: 16.0.0-alpha.12
native-base: 2.3.0

## Expected behaviour
Header background color will change when toolbarDefaultBg is a different value when a new theme is passed to StyleProvider.

## Actual behaviour
Background color is not updated.

[Before toolbarDefaultBg update](http://i.imgur.com/yImcQKt.png)
[After toolbarDefaultBg update](http://i.imgur.com/jgY8F4L.png)

## Steps to reproduce (code snippet or screenshot)
Here's some minimal code. You can find the repo [here](https://github.com/mini-eggs/SnackChan)

```javascript
function StyleComponent({ children, themeName }) {
  const theme = Object.assign({}, Default, Custom[themeName]);
  return <StyleProvider style={GetTheme(theme)} children={children} />;
}

function mapState({ settings }) {
  return {
    themeName: settings.theme
  };
}

export default connect(mapState)(StyleComponent);
```

## Screenshot of emulator/device
Look above! :)

## Is the bug present in both ios and android or in any one of them?
I've only tried on iOS.

## Any other additional info which would help us debug the issue quicker.
No. I'm going to fork and attempt to submit a PR.

**Comment by mini-eggs** [comment]
Update from cardDefaultBg  to toolbarDefaultBg, oops!

**Comment by naviens** [comment]
Same error on Android too. 
Sample Code:
`      <Header
        backgroundColor="#00AA8D"
        androidStatusBarColor='#008975'>
        <Left>
          <Button transparent>
            <Icon name='menu' />
          </Button>
        </Left>
        <Body>
          <Title>Home</Title>
        </Body>
        <Right>
          <Button transparent >
            <Icon name='person' />
          </Button>
        </Right>
      </Header>`

Expected backgroundColor "#00AA8D"
Actual  backgroundColor "blue" (default)

**Comment by shivrajkumar** [comment]
@naviens There is no prop as `backgroundColor` for Header.

**Comment by shivrajkumar** [comment]
#910

**Comment by amalantony** [comment]
@shivrajkumar: The documentation says that `backgroundColor` is a property of header: http://docs.nativebase.io/Components.html#header-def-headref

**Comment by SupriyaKalghatgi** [comment]
@amalantony #1619

**Comment by amalantony** [comment]
@SupriyaKalghatgi thanks, it would be great if the documentation is updated to reflect the same.

**Comment by SupriyaKalghatgi** [comment]
@amalantony In my previous comment i have mentioned #1619 which has an issue opened on NB-Docs repo
