### ISSUE TITLE
tab delay property for Tabs

### ISSUE THREAD

**Issue by ketankulkarni** [GeekyAnts/NativeBase#1144]
"native-base": "^2.2.1",
    "react": "16.0.0-alpha.12",
    "react-native": "0.46.3",

Actual output - tab switching takes some amount of time for switching when other tab is selected by 
                       touching
Expected output - tab delay should be reduced

```
<Tabs initialPage={0} tabDelay={0}>
       <Tab heading="send">
       <Send/>
       </Tab>
       <Tab heading="request">
       <Request/>
       </Tab>
       <Tab heading="add">
       <Add/>
       </Tab>
     </Tabs>
```

**Comment by ketankulkarni** [comment]
got some information from https://github.com/skv-headless/react-native-scrollable-tab-view
identified property scrollWithoutAnimation  but still takes time to switch

**Comment by akhil-geekyants** [comment]
Fixed in the latest release
![tabsdelayt](https://user-images.githubusercontent.com/27768184/32362921-9f4459ea-c092-11e7-87e9-950ecd0b1e49.gif)

**Comment by w-** [comment]
this is still happening on 2.7.2

**Comment by hariantara** [comment]
@akhil-geekyants 

may you try inside TabTwo you fetch some data and render it, and then you press another tab, it will be slow and become freeze
