### ISSUE TITLE
Picker button text color

### ISSUE THREAD

**Issue by tomexa** [GeekyAnts/NativeBase#1145]
## react-native, react and native-base version
"react": "~15.4.1"
"react-native": "0.42.0"
"native-base": "2.1.0"
I used the ignite + native base boilerplate

## Expected behaviour
I wanted to change the picker button text color to white, but couldn't.
I ejected the native base theme to customize it, and modified the file Button.js:
```javascript
    '.picker': {
        paddingLeft:0,
        'NativeBase.Text': {
          fontSize: 17,
          color:'#ddd',
          '.note': {
            fontSize: 12,
            lineHeight: null,
          },
        },
      }
```
I removed the left padding from the button, and added the fontSize and color to the Text.

## Actual behaviour
Unfortunately, only the padding was removed, the text is still black

## Screenshot of emulator/device
<img width="357" alt="capture d ecran 2017-08-06 a 16 29 38" src="https://user-images.githubusercontent.com/23457258/29004225-96981d54-7ac4-11e7-95cb-0b0b7070ff5d.png">

## Is the bug present in both ios and android or in any one of them?
I only tested on iOS simulator

**Comment by tomexa** [comment]
For those wondering, I changed all '#000' references to my text color in the Button.js file, and it fixed it. I suppose the picker uses a specific type of button, 'light' or 'dark'.

**Comment by elivinsky** [comment]
`<Picker style={{ color: '#FFF' }} >`

**Comment by achubai** [comment]
@elivinsky It works but causes an error in typescript.

`Type '{ color: string; }' is not assignable to type 'StyleProp<ViewStyle>'.
  Property 'color' does not exist on type 'StyleProp<ViewStyle>'.`

**Comment by akhil-geekyants** [comment]
@achubai can you try textStyle prop of Picker
```
 <Picker
       textStyle={{ color: 'blue' }}
        ...
/>
```

**Comment by achubai** [comment]
@akhil-geekyants Unfortunately, it doesn't work properly on android. 

![download](https://user-images.githubusercontent.com/15085422/38295779-dcc1104c-37f7-11e8-8ed2-192234b759eb.png)

**Comment by SupriyaKalghatgi** [comment]
Fixed with [2.4.2](https://github.com/GeekyAnts/NativeBase/releases/tag/v2.4.2)

**Comment by bharatbiswal** [comment]
> @achubai can you try textStyle prop of Picker
> 
> ```
>  <Picker
>        textStyle={{ color: 'blue' }}
>         ...
> />
> ```

thanx @akhil-geekyants , this one working for me.

**Comment by FadiAboMsalam** [comment]
this issue still exist on android only
