### ISSUE TITLE
Allow editing 'numberOfLines' of the Title

### ISSUE THREAD

**Issue by douglasjunior** [GeekyAnts/NativeBase#1146]
In [this line](https://github.com/GeekyAnts/NativeBase/blob/a479267b89b972d7ca44cd577eeed6c69ff05eef/src/basic/Title.js#L9), just change this:

```jsx
return <Text ref={c => (this._root = c)} {...this.props} numberOfLines={1} />;
```

For this:

```jsx
return <Text ref={c => (this._root = c)} numberOfLines={1} {...this.props}  />;
```

**Comment by shivrajkumar** [comment]
@douglasjunior Added this in version 2.3.3
