### ISSUE TITLE
Android: createJSModules in react-native-vector-icons

### ISSUE THREAD

**Issue by amahrt** [GeekyAnts/NativeBase#1148]
## react-native, react and native-base version
Newest (0.47.1)
## Expected behaviour
createJSModules is not overridden
## Actual behaviour
Compilation fails due to react-native-vector-icon dependency
## Steps to reproduce (code snippet or screenshot)
Install RN 0.47.1 and the newest nativebase version
## Screenshot of emulator/device
```
:react-native-vector-icons:compileReleaseJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
~/app/node_modules/react-native-vector-icons/android/src/main/java/com/oblador/vectoricons/VectorIconsPackage.java:26: error: method does not override or implement a method from a supertype
  @Override
  ^
1 error
:react-native-vector-icons:compileReleaseJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-vector-icons:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
```
## Is the bug present in both ios and android or in any one of them?
Android
## Any other additional info which would help us debug the issue quicker.
Switch to react-native-vector-icons >=4.3.0

**Comment by mdebo** [comment]
Hi exactly the same issue for me. Any news about it? thanks

**Comment by harish-rw** [comment]
I have faced same issue. I did not found the solution. So finally I fixed this issue by commenting `@Override` in the file
`/app/node_modules/react-native-vector-icons/android/src/main/java/com/oblador/vectoricons/VectorIconsPackage.java` at line 26

**Comment by shivrajkumar** [comment]
We will update the dependency and release a new version very soon. For now, you can install the latest of vector-icons in your app.

**Comment by shivrajkumar** [comment]
`react-native-vector-icons` dependency upgraded in the latest version 2.3.3
