### ISSUE TITLE
Unable to customize my app as explained into the documentation

### ISSUE THREAD

**Issue by virgolus** [GeekyAnts/NativeBase#1150]
I've followed the documentation find at this link:
https://docs.nativebase.io/Customize.html#Customize

after ejected the theme and added < StyleProvider > to my render, the application doesn't start and I had this error in the developer tools console:
```
Warning: Failed prop type: Invalid prop `flex` of type `function` supplied to `RCTView`, expected `number`.
Bad object: {}
    in RCTView (at View.js:128)
    in View (at Container.js:17)
    in Container (at connectStyle.js:332)
    in Styled(Container) (at index.android.js:204)
    in StyleProvider (at index.android.js:203)
    in AppContainer (at index.android.js:219)
    in OnehOnedphoto (at renderApplication.js:35)
    in RCTView (at View.js:128)
    in View (at AppContainer.js:93)
    in RCTView (at View.js:128)
    in View (at AppContainer.js:92)
    in AppContainer (at renderApplication.js:34)
```
Imports:
```
import common from './native-base-theme/variables/commonColor';
import getTheme from './native-base-theme/components';
```

Main component render:
```
  render() {
    return (
      <StyleProvider style={getTheme(common)}>
        <Container>
          <MainHeader />
          <Content>
            <HomeScreen user={this.state.user} />
          </Content>
          <MainFooter onChangeScreen={this.changeScreen} />
        </Container>
      </StyleProvider>
    );
  }
}
```
## react-native, react and native-base version
```
    "native-base": "^2.2.0",
    "react": "16.0.0-alpha.12",
    "react-native": "0.45.0",
```
## Expected behaviour
My application continue to work with the platform style
## Actual behaviour
My application doesn't start
## Steps to reproduce (code snippet or screenshot)
Launch the application
## Is the bug present in both ios and android or in any one of them?
I've only one android smartphone
## Any other additional info which would help us debug the issue quicker.
I've already delete the node_modules directory and the native-base-theme directory, but the error persist

**Comment by L3V147H4N** [comment]
I also had some issues regarding old docs, some the Documentation is falling behind

**Comment by shivrajkumar** [comment]
Check the latest version.
