### ISSUE TITLE
is swipeout component removed from recent version?

### ISSUE THREAD

**Issue by manjeets12** [GeekyAnts/NativeBase#1151]
Hi! Thanks for trying out NativeBase!
Due to the overwhelming requests and issues/questions we ask you to add the following details with your issue.

Please check the existing open/closed issues for a possible duplicate before creating a new issue :)

Also **DO** fill out the below form to give us a better idea about your environment and help us debug it quicker. Issues without the required details will mostly be unattended to.

## Any other additional info which would help us debug the issue quicker.

I am looking into index folder of native-base repo but there is no Swipeout component, last month when I checked there was one.So just want to confirm is that removed from current version.And what were the possible reasons to remove?
Thanks

**Comment by shivrajkumar** [comment]
@manjeets12 Swipeout was something which we were experimenting on and it was never included to be used. We have removed it in the latest versions and added a new component SwipeList do check it out http://docs.nativebase.io/Components.html#swipeable-multi-def-headref
