### ISSUE TITLE
'Invalid tar file' from 'keyboard-aware-scroll-view', while running yarn start

### ISSUE THREAD

**Issue by fhad-getmaple** [GeekyAnts/NativeBase#1152]
Please see log below:

yarn install v0.18.1
[1/4] Resolving packages...
[2/4] Fetching packages...
error An unexpected error occurred: "https://github.com/GeekyAnts/react-native-keyboard-aware-scroll-view: invalid tar file".

**Comment by shivrajkumar** [comment]
Closing this as it seems to be working fine.
Let us know if you are still facing the issue
