### ISSUE TITLE
<Content> with style object got invalid prop

### ISSUE THREAD

**Issue by Cengkaruk** [GeekyAnts/NativeBase#1158]
## react-native, react and native-base version

"react-native": "0.42.0"
"react": "~15.4.1"
"native-base": "2.1.0"

## Expected behaviour

This style prop should be fine
`<Content style={Styles.backgroundOverlay}>`

## Actual behaviour

Got warning and style doesn't apply, but no problem when directly use style inline like this.
`<Content style={{ backgroundColor: 'rgba(0, 0, 0, 0.4)' }}>
`
## Screenshot of emulator/device

![screen shot 2017-08-10 at 9 07 45 pm](https://user-images.githubusercontent.com/629402/29246074-dfee8c38-8017-11e7-84e7-d8f7e1a4bd10.png)

## Is the bug present in both ios and android or in any one of them?

Both

## Any other additional info which would help us debug the issue quicker.

I have `<Image>` with background before the `<Content>`. This is the style object that i use.

```
backgroundOverlay: {
  backgroundColor: 'rgba(0, 0, 0, 0.4)'
}
```
And i'm using Ignite with NativeBase's boilerplate

**Comment by shivrajkumar** [comment]
@Cengkaruk Content here is actually ScollView of React Native. So its style only accepts few properties mentioned [here](http://facebook.github.io/react-native/releases/0.47/docs/scrollview.html#style). To apply backgroundColor use [contentContainerStyle](http://facebook.github.io/react-native/releases/0.47/docs/scrollview.html#contentcontainerstyle)

**Comment by Cengkaruk** [comment]
Thanks @shivrajkumar 
Btw i found another approach to solve this by using `Stylesheet.flaten()` for Stylesheet object. And its usable for directly customizing component like Text without create another props at Theme.
