### ISSUE TITLE
spinner does not show up in header

### ISSUE THREAD

**Issue by aferust** [GeekyAnts/NativeBase#116]
It seems that spinner is functional only when it is in the content component. It would be useful if it can work in header too.

**Comment by aferust** [comment]
There is a tricky solution for this. Spinner is rendered if you cover it with a title tag such as:
```
<Title>
    <View width={25} height={25}><Spinner /></View>
</Title>
```
a view with width and height props are required.

**Comment by sankhadeeproy007** [comment]
By default, the header will only support Title and Buttons. If you need custom/advanced components, they'd have to be inside your own custom component.
