### ISSUE TITLE
KeyboardAvoidingView in native base 

### ISSUE THREAD

**Issue by Bundas** [GeekyAnts/NativeBase#1163]
Is there any way to do KeyboardAvoidingView easily in native base? I am trying to implement the "View scrolling" when a keyboard is interfering an TextInput. You know what i mean

**Comment by mylvari** [comment]
IOS seems to do that by default. On android i found out that using KeyboardAvoidingView from native is needed.
```
<KeyboardAvoidingView behavior="padding" style={{ flex: 1 }}>
<Content>...</Content>
</KeyboardAvoidingView>
```

Is this however anti-pattern in native-base?

**Comment by SupriyaKalghatgi** [comment]
No thats not available with native-base

**Comment by SupriyaKalghatgi** [comment]
Closing this
Please reopen this issue if help needed

**Comment by ningacoding** [comment]
so, whats the workaround ?
if "NativeBase" is the "missing piece of React Native", why "that's not available with native-base" ?
