### ISSUE TITLE
Use more than one Icon Family

### ISSUE THREAD

**Issue by nschurmann** [GeekyAnts/NativeBase#1165]
Hi!, we need to use more than one icon family, is this supported?

**Comment by shivrajkumar** [comment]
@nschurmann One way of doing this is wrapping the Icon with StyleProvider and passing theme with different iconFamily variable. Check [this](http://docs.nativebase.io/Customize.html#theaming-nb-headref) for customization

**Comment by wootwoot1234** [comment]
@shivrajkumar is there anyway to use more than one iconFamily?  It would be great to be able to use the same icon styles but with icons from different icon families.   Maybe a iconFamily prop on the <Icon /> that overrides the iconFamily variable in the theme?

**Comment by wootwoot1234** [comment]
I wish there was a way to use other icon families within nativebase but this is what I ended up putting together to get around it:

```
import IconFA from "react-native-vector-icons/FontAwesome";
<IconFA name="balance-scale" style={{fontSize: 16}} />
```
