### ISSUE TITLE
Is have any ways to custom on Tab with Thumbnail and Text?

### ISSUE THREAD

**Issue by NemSothea** [GeekyAnts/NativeBase#1166]
<Tabs tabBarPosition="bottom" locked={true} tabBarUnderlineStyle={{backgroundColor: GREY_COLOR}}>
          <Tab  activeTextStyle= {activeTextStyle} textStyle = {textStyle} activeTabStyle = {tabStyle}
           tabStyle = {tabStyle} heading="Submission">
                <Main/>
    </Tab>
I just only custom on Text only with configuration that nativebase given..
but
I can not get it work with image and Text on Tab at the button when it's active or not?
Any suggestion?
Plz help..

**Comment by shivrajkumar** [comment]
@NemSothea You can use TabHeading to add custom heading for the Tabs
```
<Tab heading={<TabHeading><Image ..../><Text>Text</Text></TabHeading>}
```

**Comment by NemSothea** [comment]
So how can I custom style on image and text when it is active! because I try to do it but it didn't work the properties that they given..

**Comment by NemSothea** [comment]
Here is my code:

 render(){
        var directoryOne = require('../../img/directory/directoryone.png')
        var directoryTwo = require('../../img/directory/directorytwo.png')
        var avataOne = require('../../img/avatar/avataone.png')
        var avataTwo = require('../../img/avatar/avatatwo.png')
        const { tabStyle} = homeStyle;
        return (
        <Container>
            <Tabs tabBarPosition="bottom" style={{backgroundColor:GREY_COLOR}}>
                <Tab heading={<TabHeading><Thumbnail square source={directoryTwo}/><Text>Tab1</Text></TabHeading>}>
                  <Main/>
                </Tab>
                <Tab heading={<TabHeading><Thumbnail square source={avataOne}/><Text>Tab2</Text></TabHeading>}>
                  <UserInfo/>
                </Tab>
              </Tabs>
          
        </Container>
        );

**Comment by shivrajkumar** [comment]
@NemSothea Use `onChangeTab` function of Tabs to set the `page` prop to the current page and use that for active tab styling.
