### ISSUE TITLE
Input with floatingLabel does not fire onChangeText event

### ISSUE THREAD

**Issue by nileshmali** [GeekyAnts/NativeBase#1167]
Hi! Thanks for trying out NativeBase!
Due to the overwhelming requests and issues/questions we ask you to add the following details with your issue.

Please check the existing open/closed issues for a possible duplicate before creating a new issue :)

Also **DO** fill out the below form to give us a better idea about your environment and help us debug it quicker. Issues without the required details will mostly be unattended to.

## react-native, react and native-base version
`{
  "react-native": "0.47.1", 
  "react": "16.0.0-beta.5",
  "native-base": "2.3.1"
}`
## Expected behaviour
Should fire onChangeText and passthrough attributes
## Actual behaviour
Neither fires onChangeText nor honors secureTextEntry attribute
## Steps to reproduce (code snippet or screenshot)
```jsx
<Form>
  <Item floatingLabel>
    <Label>Username</Label>
    <Input 
    onChangeText={ onFieldChange }/>
  </Item>
  <Item floatingLabel last>
    <Label>Password</Label>
    <Input 
    secureTextEntry 
    onChangeText={ onFieldChange }
    />
  </Item>
</Form>
```
When we run this code rendered password input does not obscures text and does not fire onChangeText event. This was working on versions 2.2.1.
## Is the bug present in both ios and android or in any one of them?
Only tested on Android.

**Comment by shivrajkumar** [comment]
![screen shot 2017-09-11 at 4 02 23 pm](https://user-ima
ges.githubusercontent.com/17001305/30270566-a42c181e-970a-11e7-94c0-d3512acc31d2.png)
@nileshmali Seems to work just fine.
