### ISSUE TITLE
Actionsheet on galaxy S8 shows an empty bar on the bottom

### ISSUE THREAD

**Issue by nschurmann** [GeekyAnts/NativeBase#1170]
Hello!v this is happening when we use actionsheet on the S8
![screenshot_20170817-130022_1024](https://user-images.githubusercontent.com/5099344/29421706-4bdb8d10-834c-11e7-9a90-a02b978c664b.png)

This should appear on the bottom, any workaround on this??

**Comment by akhil-geekyants** [comment]
@nschurmann tried Actionsheet on Samsung Galaxy Tab S2. Couldn't see any issue. Is the issue present in any other device ?

**Comment by akhil-geekyants** [comment]
Closing this issue due to no response. If you are still facing this issue, let us know.
