### ISSUE TITLE
Text is not displayed correctly on Inputs with stackedLabel

### ISSUE THREAD

**Issue by Papipo** [GeekyAnts/NativeBase#1173]
## react-native, react and native-base version
react@16.0.0-alpha.12
react-native@0.46.4
native-base@2.3.1

## Expected behaviour
I expect text to be displayed completely

## Actual behaviour
The first character is cut

## Steps to reproduce (code snippet or screenshot)
Just try it on the Kitchen Sink app

## Screenshot of emulator/device
![screen](https://user-images.githubusercontent.com/22678/29472999-4baf7b7a-8456-11e7-8e0c-4614553dd88d.png)

## Is the bug present in both ios and android or in any one of them?
Android. I don't have an iOS device to test.

## Any other additional info which would help us debug the issue quicker.
The first char on the screenshot is a "B".
I am using floatingLabel. I think it also happens with stacked ones.

**Comment by andreimc** [comment]
I have a fix on my current master - submitted a PR

**Comment by ceefour** [comment]
I also confirm this is happening, not just with my app but with nativebase's own KitchenSink as of 31 Aug 2017. Android 7.0 on Asus Zenfone 3.

**Comment by joaozitopolo** [comment]
@andreimc there are some scheduled date for update of the native-base package at npm, with the correction?

**Comment by shivrajkumar** [comment]
Fixed in version 2.3.2
