### ISSUE TITLE
Picker cannot handle hardcode item and array together

### ISSUE THREAD

**Issue by carsonwah** [GeekyAnts/NativeBase#1176]
## react-native, react and native-base version
"react": "16.0.0-alpha.12",
"react-native": "https://github.com/expo/react-native/archive/sdk-20.0.0.tar.gz" (0.47)
"native-base": "^2.3.1"

## Fail case
```
render() {
  ...
  const pickerOptions = ['item1', 'item2', 'item3'].map((item, index) => (
    <Picker.Item label={item} value={item} key={index} />
    ));

  return (
    <Picker mode='dropdown' selectedValue={selectedValue} onValueChange={onValueChange} >
      <Picker.Item label={title} value='' />
      { pickerOptions }
    </Picker>
  )}
```

## Screenshot of emulator/device
![simulator screen shot 2017 8 20 01 19 29](https://user-images.githubusercontent.com/25053707/29488960-fb9be1a8-8547-11e7-9790-0919a3fc95f5.png)

## Is the bug present in both ios and android or in any one of them?
Haven't test android yet.

### path: native-base/dist/src/basic/Picker.ios.js line 167 (182 for native-base v2.3.0)
```
renderRow:function renderRow(child){return(
_react2.default.createElement(_ListItem.ListItem,{
selected:child.props.value===_this5.props.selectedValue, // <------here
```
* I logged the child and found that `renderRow` will be called twice and the second one will be an array, which causes error.
* If only the array provided as child, `renderRow` is called many times and each child is an item.

--------

![2017-08-20 01 41 48](https://user-images.githubusercontent.com/25053707/29489029-b26416a2-8549-11e7-9b8f-ed9da9a59973.png)

--------

Hope this can be solved soon. I will maybe move the hardcode item into the list for now.

**Comment by shivrajkumar** [comment]
#983

**Comment by Suraj-Tiwari** [comment]
Recently I've faced the same issue, I did a small tweak to get my desire result 

```
render() {
  return (
    <Picker mode='dropdown' selectedValue={selectedValue} onValueChange={onValueChange} >
      { make_list(['pass','your','desire','list']) }
    </Picker>
  )}
function make_list(list){
        d = list.map((data,i) => {
            return (
                <Picker.Item label={data} value={i}/>
            )
        })
       // i did this because no need in ios :P 
        if(Platform.OS === 'android'){
            d.unshift(<Picker.Item label="Select" />)
        }
        return d;
      //and that's how you are ready to go, because this issue isn't fixed yet (checked on 28-Dec-2017)
 }

```
