### ISSUE TITLE
Shadow is not seeing in Card in Android

### ISSUE THREAD

**Issue by lugrugzo** [GeekyAnts/NativeBase#1177]
My simple render method is:

``` jsx
<Content style={{ padding: 5 }}>
    <Card>
        <CardItem>
               <Button><Text>Button 1</Text></Button>
               <Button><Text>Button 2</Text></Button>
          </CardItem>
       </Card>
</Content>
```

It's rendering card shadow in IOS, but in Android it's not rendering anything. What can be the problem?

**Comment by shivrajkumar** [comment]
@lugrugzo shadow doesn't work for android in react-native. It works for only iOS and for android its elevation
