### ISSUE TITLE
Error after react-native link

### ISSUE THREAD

**Issue by hustlerism** [GeekyAnts/NativeBase#1178]
## Description
Hi, im having problem with the installation. I can succesfully install native-base but encountered error after running 

> react-native link

Is there a way to link it manually? 
Thanks in advance!

## react-native, react and native-base version
-react-native: 0.44.2
-react: 16.0.0-alpha.3
-native-base: ^2.2.0
## Expected behaviour
"react-native link" successfully
## Actual behaviour

> rnpm-install info Linking react-native-fbsdk android dependency
rnpm-install ERR! Something went wrong while linking. Error: ENOENT: no such file or directory, open 'D:\Desktop\Makan-app\android\app\src\main\java\android\support\graphics\drawable\animated\MainApplication.java'
Please file an issue here: https://github.com/facebook/react-native/issues

>ENOENT: no such file or directory, open 'D:\Desktop\Makan-app\android\app\src\main\java\android\support\graphics\drawable\animated\MainApplication.java'

**Comment by shivrajkumar** [comment]
@hustlerism The issue seems to be in `react-native-fbsdk` linking. Not `native-base` linking.
