### ISSUE TITLE
License

### ISSUE THREAD

**Issue by mysiar** [GeekyAnts/NativeBase#1181]
Is there any chance to publish this libary on MIT license ?

**Comment by sanketsahusoft** [comment]
May be, I would like to know about what would you like to do with this library?

**Comment by mysiar** [comment]
I'm developing now React component generator for API-Platform
https://github.com/api-platform/generate-crud
All of it is published on MIT license.
I would like to use this library and create templates to generate React Native components based on your library.

**Comment by mysiar** [comment]
@sanketsahusoft any news in license changing?

**Comment by sanketsahusoft** [comment]
Apache License V2 should work fine for your use-case.

**Comment by mysiar** [comment]
It doesn't, not worries I will not use it
