### ISSUE TITLE
Tabs overlap each other

### ISSUE THREAD

**Issue by satori-ytolstoguzov** [GeekyAnts/NativeBase#1182]
## react-native, react and native-base version
```
"react": "16.0.0-alpha.12",
"react-native": "0.46.4",
"native-base": "^2.3.1"
```
## Expected behaviour
Tabs have perfect layout without overlaps.

## Actual behaviour
Tabs overlap each other on about 0.5 of a pixel, but still visible.

## Steps to reproduce (code snippet or screenshot)
* Eject themes
* in variables make tab background transparent 
```
tabDefaultBg: 'transparent'
```
* make tab heading partially transparent: 
```
// TabHeading.js
const tabHeadingTheme = {
...
    '.scrollable': {
...
      backgroundColor: 'rgba(255, 255, 255, 0.8)'
    },
...
    }
  };

  return tabHeadingTheme;
};
```
* put something distinctive under tab bar and make tab bar overlay it.
* Switch between tabs: in some cases tabs overlap each other and you see this overlap.

## Screenshot of emulator/device
See how between second and third tab there is some kind of border, that's the overlap. It appears and disappears between different tabs depending on which tab is selected.
![tab-bar-layout-bad](https://user-images.githubusercontent.com/31261230/29592619-0bc3244c-875a-11e7-9988-069d4de3f58a.png)

## Is the bug present in both ios and android or in any one of them?
I have checked only iOS

## Any other additional info which would help us debug the issue quicker.
I noticed that it happens when positions of tabs are not integers.

**Comment by gosongs** [comment]
![image](https://user-images.githubusercontent.com/27057518/29644369-164dd5b6-88a8-11e7-8c72-abc10ad190cd.png)

Same in IOS.

**Comment by akhil-geekyants** [comment]
Issue fixed in the latest release
![taboverlap](https://user-images.githubusercontent.com/27768184/32328606-7a639baa-c000-11e7-9d2d-e67fadd40267.gif)
![taboverlap2](https://user-images.githubusercontent.com/27768184/32328617-7ef31da8-c000-11e7-9303-2a1344980564.gif)

**Comment by Ruzen1** [comment]
@akhil-geekyants Could you please mention the version , it was fixed?
