### ISSUE TITLE
Unable to resolve @expo/vector-icons/Ionicons

### ISSUE THREAD

**Issue by sinapcs** [GeekyAnts/NativeBase#1183]
Hi. First of all thank you for Native Base!
I am using Native Base about 8 month but have a problem with new version of this library. 
I installed a fresh react native app using this command : 
react-native init Project

then I used this commands to install Native Base and linked it.
npm install native-base --save
react-native link

my projects work without any problem until I import anything from native-base
```
import React, { Component } from 'react';
import {
  AppRegistry,
  StyleSheet,
  Text,
  View
} from 'react-native';
import {Button} from 'native-base';

export default class Project extends Component {
  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>
          Welcome to React Native!
        </Text>
        <Button>Hi</Button>
        <Text style={styles.instructions}>
          To get started, edit index.android.js
        </Text>
        <Text style={styles.instructions}>
          Double tap R on your keyboard to reload,{'\n'}
          Shake or press menu button for dev menu
        </Text>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});

AppRegistry.registerComponent('Project', () => Project);

```
look at this code. It's react-native hello world + a Button from native-base.
I'm getting this error : 
Unable to resolve @expo/vector-icons/Ionicons

I looked at compatibility part of native base and I noticed that it's not compatible with React 16.0.0-alpha.13! 
but problem is react-native init command installing React 16.0.0-alpha.13. I think it's good tell this issue to people in your documents and provide a way to init react-native with older version of React.

**Comment by kimkha** [comment]
Did you try `rm -rf $TMPDIR/react-native-*`?

**Comment by sinapcs** [comment]
No I installed "native-base": "^2.2.1" and problem solved. 
here is my package.json
`
{
  "name": "teeest",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "axios": "^0.16.2",
    "native-base": "^2.2.1",
    "react": "16.0.0-alpha.12",
    "react-native": "0.47.2",
    "react-native-device-info": "^0.11.0",
    "react-native-lightbox": "^0.6.0",
    "react-native-push-notification": "^3.0.1",
    "react-native-root-toast": "^1.3.0",
    "react-native-router-flux": "^4.0.0-beta.19",
    "react-redux": "^5.0.6",
    "redux": "^3.7.2"
  },
  "devDependencies": {
    "babel-jest": "20.0.3",
    "babel-preset-react-native": "3.0.1",
    "jest": "20.0.4",
    "react-test-renderer": "16.0.0-alpha.12"
  },
  "jest": {
    "preset": "react-native"
  },
  "rnpm": {
    "assets": ["./assets/fonts"]
  }
}

`

**Comment by shivrajkumar** [comment]
Follow the CRNA setup guidelines https://github.com/GeekyAnts/NativeBase#4-getting-started
