### ISSUE TITLE
disabled prop not works on <ListItem /> Component

### ISSUE THREAD

**Issue by netojose** [GeekyAnts/NativeBase#1184]
## react-native, react and native-base version
"native-base": "^2.3.1",
"react": "16.0.0-alpha.12",
"react-native": "0.47.1"

## Expected behaviour
When a `<ListItem />` Component has a `disabled` prop with **true** value, all interactions with this component should be disabled, [according with react-native official docs](http://facebook.github.io/react-native/docs/touchablewithoutfeedback.html#disabled).

## Actual behaviour
Even with disabled prop with a true value, the onPress event keep triggering.

## Steps to reproduce (code snippet or screenshot)
```
<ListItem disabled={true} onPress={() => console.log('I'm working')}>
        ...
</ListItem>
```

## Screenshot of emulator/device
N/A

## Is the bug present in both ios and android or in any one of them?
Tested only Android

## Any other additional info which would help us debug the issue quicker.
N/A

**Comment by shivrajkumar** [comment]
@netojose ListItem internally uses `TouchableHighlight` for iOS and `TouchableNativeFeedback` for android, not `TouchableWithoutFeedback`. You can create your own ListItem for TouchableWithoutFeedback with the same styling though following the customization guidelines http://docs.nativebase.io/Customize.html#custom-component-headref
