### ISSUE TITLE
Footer icons/text look bad in demo

### ISSUE THREAD

**Issue by jacobweber** [GeekyAnts/NativeBase#1186]
## react-native, react and native-base version
Using demo from https://expo.io/@geekyants/nativebasekitchensink

## Expected behaviour
Footer buttons with icons/text in demo look like a standard iOS footer.

## Actual behaviour
Footer buttons with icons/text have wrapped text, and icons that expand out of the footer.

## Steps to reproduce (code snippet or screenshot)
Launch demo using https://expo.io/@geekyants/nativebasekitchensink, go to Footer > Icon & Text Footer.

## Screenshot of emulator/device
![simulator screen shot aug 24 2017 9 26 04 am](https://user-images.githubusercontent.com/542988/29677121-feb84bf0-88ae-11e7-9821-c2430ca875dc.png)

## Is the bug present in both ios and android or in any one of them?
iOS

## Any other additional info which would help us debug the issue quicker.
Reproduced on iPhone 4S simulator, iPhone 6 device

**Comment by akhil-geekyants** [comment]
Fixed in the latest version. Attaching a screenshot.
![simulator screen shot - iphone 6 - 2017-11-02 at 17 23 34](https://user-images.githubusercontent.com/27768184/32324822-a47b9c02-bff2-11e7-8031-95a17b202d31.png)
