### ISSUE TITLE
Header buttons/text too high on iOS

### ISSUE THREAD

**Issue by jacobweber** [GeekyAnts/NativeBase#1187]
## react-native, react and native-base version
Using demo from https://expo.io/@geekyants/nativebasekitchensink

## Expected behaviour
Header in demo looks like a standard iOS header.

## Actual behaviour
Header buttons/text are raised a few pixels above where they would normally be (see comparison with Photos app below). In addition, the text is too close to the < icon, and the right/left text are too far from the edges. I swear I'm not just being pedantic; this really looks "off".

## Steps to reproduce (code snippet or screenshot)
Launch demo using https://expo.io/@geekyants/nativebasekitchensink, go to Header > Icon & Text Buttons.

## Screenshot of emulator/device
From the Expo app:
![simulator screen shot aug 24 2017 9 28 52 am](https://user-images.githubusercontent.com/542988/29677180-3031f96a-88af-11e7-9d00-682c02596fe1.png)
Here's the iOS Photos app for comparison:
![simulator screen shot aug 24 2017 9 28 12 am](https://user-images.githubusercontent.com/542988/29677186-3416be30-88af-11e7-9ba4-88583d8f7729.png)

## Is the bug present in both ios and android or in any one of them?
iOS

## Any other additional info which would help us debug the issue quicker.
Reproduced on iPhone 4S simulator, iPhone 6 device

**Comment by akhil-geekyants** [comment]
Fixed in the latest version
![simulator screen shot - iphone 6 - 2017-11-02 at 17 11 33](https://user-images.githubusercontent.com/27768184/32324304-f78df900-bff0-11e7-95b3-ed32620d8332.png)
