### ISSUE TITLE
snack expo problems

### ISSUE THREAD

**Issue by rolignu2** [GeekyAnts/NativeBase#1188]
snack.expo.io  not working with the last native-base ,  infinite loop waiting for code :S

**Comment by SupriyaKalghatgi** [comment]
@rolignu2 I tried it now, it says `installing dependencies` and then throws error

Not sure if snack expo supports NativeBase

**Comment by SupriyaKalghatgi** [comment]
@rolignu2 I contacted with the expo team
> Native base isn’t working right now, sorry.  We’re focused on making ALL npm dependencies that work in expo work in snack, so hopefully we’ll be able to get that resolved for you in the next couple of weeks

Hope this is fixed soon by expo
