### ISSUE TITLE
Header doesn't center or change color as per the documentation ? 

### ISSUE THREAD

**Issue by a-eid** [GeekyAnts/NativeBase#1190]
## react-native, react and native-base version
```
    "native-base": "^2.3.1",
    "react": "16.0.0-alpha.12",
    "react-native": "^0.47.2",
```
## Expected behaviour
Header Title should be centerd and should be colorless 
## Actual behaviour
Header is way to the left and color is blue 
## Steps to reproduce (code snippet or screenshot)
code is above , I'll be posting screenshot down blow 
## Screenshot of emulator/device
device 
## Is the bug present in both ios and android or in any one of them?
only can check on android for now 
## Any other additional info which would help us debug the issue quicker.
no 

```
      <Container>
        <Header>
        <Left/>
          <Body>
            <Title>Header </Title>
          </Body>
          <Right />
        </Header>
      </Container> 
```
also when I change color it stays the say , doesn't change . 

![](https://i.imgur.com/Bq49xda.png)

**Comment by stivaugoin** [comment]
Same problem here only on Android. Everything works fine on iOS.

**Comment by SupriyaKalghatgi** [comment]
@a-eid `Title` of the `<Header>` for Android is not aligned at center
That is because of the design guidelines for Android.

For Android, `Title` is slightly towards left, whereas for iOS it is at center

Design guidelines are not always same for iOS and Android

**Comment by SupriyaKalghatgi** [comment]
@a-eid 
> also when I change color it stays the say , doesn't change .

Please share screenshot for this, along with the changes made in `native-base-theme`

**Comment by akhil-geekyants** [comment]
@a-eid couldn't reproduce the issue. Was able to change the color of the header successfully. Attaching a gif
![headercolor](https://user-images.githubusercontent.com/27768184/32321218-6ce049de-bfe6-11e7-9d3a-fd71df502436.gif)

**Comment by a-eid** [comment]
This issue is old , I forgot to close it .

**Comment by UberMC** [comment]
Am encountering this issue with 
    "native-base": "^2.3.3",
    "react": "16.0.0",
    "react-native": "0.50.1"

Cannot set the header backgroundColor
Followed exactly as above gif.

**Comment by akhil-geekyants** [comment]
@UberMC you can also override the `<Header/>` style to change the backgroundColor. If you need to change the default header background color you can [eject the theme](http://docs.nativebase.io/Customize.html#theaming-nb-headref) and change `toolbarDefaultBg` in  `native-base-theme/variables/commonColors.js` - replace `commonColors.js` with the appropriate file based on the theme you select (`platform.js` or `material.js` or `commonColors.js`)

**Comment by joshbedo** [comment]
This still seems like it's still an issue. I'm having issues changing the background color following the GIF I don't see the same result for Android.

**Comment by akhil-geekyants** [comment]
@joshbedo tried changing the header background color. It is working fine. Attaching a gif.

Gif

![header](https://user-images.githubusercontent.com/27768184/37446679-31e4c956-2844-11e8-8b2d-2d30b4c2fb5f.gif)

**Comment by danilocecilia** [comment]
according to the documentation is saying there is a property called backgroundColor for changing its color, however, how am i supposed to know to use it wrapped on style... 

I think there should be a better documentation with more examples on 'how to dos"

**Comment by SupriyaKalghatgi** [comment]
#1619
