### ISSUE TITLE
Using ListView with RefreshControl inside Container, breaks navigation

### ISSUE THREAD

**Issue by ceefour** [GeekyAnts/NativeBase#1192]
## react-native, react and native-base version

    "native-base": "^2.3.1",
    "react": "16.0.0-alpha.12",
    "react-native": "https://github.com/expo/react-native/archive/sdk-20.0.0.tar.gz",
    "react-navigation": "^1.0.0-beta.12"

## Expected behaviour

Navigates to another page with all its content

## Actual behaviour

Navigates to another page, but only the header is changed, the content is still stuck on the page with the ListView/RefreshControl

## Steps to reproduce (code snippet or screenshot)

App with TabNavigator.

First page is:

      <Container>
        <Header>
          <Body>
            <Title>Page 1</Title>
          </Body>
        </Header>
        <View style={{flex: 1}}>
          <ListView style={{backgroundColor: 'red'}} dataSource={new ListView.DataSource({rowHasChanged: (r1, r2) => r1 !== r2})}
            renderRow={() => <View/>}
            refreshControl={<RefreshControl refreshing={true}/>}
            />
        </View>
      </Container>

Second page can be anything.

## Is the bug present in both ios and android or in any one of them?

Only tested on Android 7.0.

## Any other additional info which would help us debug the issue quicker.

If the `View` is changed to `Content`, the `RefreshControl` won't work at all (without warning). This is explained in https://github.com/GeekyAnts/NativeBase/issues/269#issuecomment-277402981 but it's still confusing because there is no warning at all. However this is not the focus of this bug report.

If set to `refreshing={true}` **during** the page mounting, then after sometime it sets refreshing=false (from state change), then behavior is broken as reported.

If set to `refreshing={false}`, then behavior is normal.

If set to `refreshing={true}` **after** the page has finished mounting, then user trigger the refreshing and then refreshing=false again, then behavior is normal.

If `Container` is changed to `View` then behavior is also normal.

My hunch is that it is a bug with `Container`, because I don't use `List` or any other native-base, except for `Header/Body/Title`.

Related to #269, #257, #348, #69.

Bug in action: Notice that both the Header Title and tab is on "Explore", but the content is still showing from the first Home tab. The Explore page should be just empty white screen.

![screenshot_20170827-205700](https://user-images.githubusercontent.com/24123/29750961-3b98b2c8-8b73-11e7-82d9-57b3b3fd6c7c.jpg)

## Workaround

`setTimeout()` (with or without timer-mixin) works wonders:

    componentDidMount() {
      // buggy:
      //this._onRefresh.bind(this);
      // buggy:
      //InteractionManager.runAfterInteractions(this._onRefresh.bind(this));
      // works:
      setTimeout(this._onRefresh.bind(this), 500);
    }

    async _onRefresh() {
      this.setState({refreshing: true})
      console.debug('Fetching posts...')
      try {
        let response = await fetch(...)
        this.setState({refreshing: false});
      } catch (error) {
        console.error('Error fetching posts', error)
        this.setState({refreshing: false})
        alert('Error: ' + error)
      }
    }

**Comment by akhil-geekyants** [comment]
@ceefour  Tried your code. Couldn't find any issue. Attaching a gif.

![refreshcontrol](https://user-images.githubusercontent.com/27768184/32595463-08d6722c-c556-11e7-820d-a06c62b0f58e.gif)

**Comment by ceefour** [comment]
I tried again with Expo 22 (previous with Expo 20), thus updated react etc. Even in native-base 2.3.1 the problem is now gone:

```
  "dependencies": {
    "@expo/samples": "^2.0.2",
    "@expo/vector-icons": "^5.2.0",
    "apollo-client": "^1.9.3",
    "color": "^2.0.0",
    "expo": "^22.0.0",
    "graphql-tag": "^2.5.0",
    "native-base": "^2.3.1",
    "react": "16.0.0-beta.5",
    "react-apollo": "^1.4.16",
    "react-native": "https://github.com/expo/react-native/archive/sdk-22.0.1.tar.gz",
    "react-navigation": "^1.0.0-beta.19"
  },
  "devDependencies": {
    "jest-expo": "^22.0.0"
  }
```

So I assumed that something in the newer dependencies has fixed this problem. Now I cannot reproduce this problem either with native-base 2.3.1 nor 2.3.3.

Thank you!
