### ISSUE TITLE
HeaderTextStyle of the Picker on iOS doesn't change.

### ISSUE THREAD

**Issue by mr-bat** [GeekyAnts/NativeBase#1193]
## Summary
I found no way to change the text style of the header and back button in iOS, while via `headerStyle` I was able to change the style of the header but I couldn't make the text style change.
## react-native, react and native-base version
react-native-cli: 2.0.1
react-native: 0.46.3
native-base: 2.2.1
## Expected behaviour:
Font Family of the header (and back button) to be changed.
## Actual behaviour:
Nothing happend!
## Steps to reproduce (code snippet or screenshot)
```
<Picker
	style={Style.picker}
	iosHeader='انتخاب کنید'
	textStyle={Style.pickerHeader}
	itemTextStyle={Style.pickerItemStyle}
	headerBackButtonText={'برگشت'}
	mode='dropdown'
	selectedValue={this.state.type}
	onValueChange={type => {
		this.setState({type})
	}}
>
```
## Screenshot of emulator/device
<img width="375" alt="screen shot 2017-08-28 at 11 17 55 am" src="https://user-images.githubusercontent.com/16259723/29762223-9a93d14e-8be2-11e7-9538-ece5396dfdc2.png">

## Is the bug present in both ios and android or in any one of them?
iOS only.

**Comment by shivrajkumar** [comment]
@mr-bat Use `headerTitleStyle` and `headerBackButtonTextStyle` props

**Comment by mr-bat** [comment]
thank you, it solved my problem.
