### ISSUE TITLE
React-Native Windows Support a Workaround

### ISSUE THREAD

**Issue by amorenew** [GeekyAnts/NativeBase#1195]
I using [React-Native Windows](https://github.com/Microsoft/react-native-windows) and I faced some Issue after running the app for windows 10.
Picker class have .android and .ios in its file name so I got a bug.
my workaround I just copied the Picker.android.js and Picker.android.js.map from
basic/
theme/components/
and just remove .android from file name to be
Picker.js and Picker.js.map 
and the app worked fine.
I hope it can help any one who supports windows

**Comment by amorenew** [comment]
Button doesn't work in windows
https://github.com/GeekyAnts/NativeBase/blob/master/dist/src/basic/Button.js
in method line 52:
Ripple is not supported in windows
I tried to fix it but I can't do it

**Comment by amorenew** [comment]
I solved Ripple problem:
I changed 
```
_reactNative.TouchableNativeFeedback
this.props.androidRippleColor?
_reactNative.TouchableNativeFeedback.Ripple(this.props.androidRippleColor):
_reactNative.TouchableNativeFeedback.Ripple(_platform2.default.androidRippleColor)},

```
to
```
_reactNative.TouchableWithoutFeedback
background: this.props.androidRippleColor
                            ? this.props.androidRippleColor
                            : _platform2.default.androidRippleColor,

```

**Comment by shivrajkumar** [comment]
#1125
