### ISSUE TITLE
Dynamic tab renders a jittering tablist

### ISSUE THREAD

**Issue by ernerock** [GeekyAnts/NativeBase#1198]
Im trying to render a <Tabs> with dynamic tabs from an API but the list "jitters".  On componentDidMount i fetch the categories and in render i change state.categories to the categories. Removing the fetch and passing the same list as a variable removes the jitter. 

![giphy](https://user-images.githubusercontent.com/6424667/29834899-320b6d58-8cbe-11e7-8e23-71d93b4b3b24.gif)

This happens occasionally and not always. I'm aware that it might be an issue with the way I change state or render list, still new to react-native. Any help is appreciated. Most times it renders correctly

![screen shot 2017-08-29 at 1 33 04 pm](https://user-images.githubusercontent.com/6424667/29835028-a3991fce-8cbe-11e7-9540-e35a9308d8a4.png)

 Code below
```
class Feed extends Component {
    constructor(props) {
        super(props);
        this.state = {
            categories: []
        };
        this.getCategories = this.getCategories.bind(this);

    }

    componentDidMount() {
        this.getCategories();
    }

    getCategories(){
        fetch(CATEGORIES_FEED)
            .then((response) => response.json())
            .then((responseJson) => {
                this.setState({categories: responseJson});
            })
            .catch((error) => {
                console.error(error);
            });
    }

    render() {

        /*Making a list of items*/
        const listItems = this.state.categories.map((item, key_) => {
            return (
                <Tab key={'category_' + key_} heading={item.name}>
                    
                </Tab>
            )
        });
        return (
            <Tabs renderTabBar={() => <ScrollableTab/>}>
                {listItems}
            </Tabs>
        );
    }
};

```
Fetch json response below:

```
[
    {
        "name": "All",
        "tid": "1",
    },
    {
        "name": "Marketing",
        "tid": "2",
    },
    {
        "name": "POV",
        "tid": "3",
    },
    {
        "name": "SEO",
        "tid": "4",
    },
    {
        "name": "Technology",
        "tid": "5",
    },
]
```

native-base: 2.3.1
react: 16.0.0-alpha.12
react-native: 0.47.1

**Comment by ernerock** [comment]
was able to solve this by wrapping the render return <Tabs> with an If condition like so:

```
                {this.state.categories.length > 0 &&
                <Tabs renderTabBar={() => <ScrollableTab/>}>
                    {listItems}
                </Tabs>
                }
```
Similarly wrapping the componentDidMount in a setTimeout even for a milisecond works as well:

```
 componentDidMount() {
      setTimeout(()=>{
        this.getCategories();
     },1);
    }
```

Probably due to a race condition.

**Comment by ansarikhurshid786** [comment]
I have similar issue. But my case is multiple tabs enabled conditionally which data coming from service(if data available). I am still facing same issue.

**Comment by ansarikhurshid786** [comment]
@ernerock please reopen this issue
