### ISSUE TITLE
how remove the bottom Separator line in ListItem

### ISSUE THREAD

**Issue by Josin22** [GeekyAnts/NativeBase#1199]

**Comment by shivrajkumar** [comment]
@Josin22 Apply `noBorder` prop on ListItem.
```
<ListItem noBorder>
```

**Comment by ShaileshPrajapati-BTC** [comment]
`<ListItem avatar key={'item'+data.id} noBorder={true}>` not working

**Comment by Josin22** [comment]
it should be <ListItem avatar key={'item'+data.id} noBorder>

**Comment by ShaileshPrajapati-BTC** [comment]
@Josin22 still not working

**Comment by Josin22** [comment]
try this : <ListItem avatar key={'item'+data.id} style={{borderWidth:0, borderColor:'transparent'}}>

**Comment by akhil-geekyants** [comment]
@ShaileshPrajapati-BTC In `<ListItem/>` add ` borderBottomWidth:0` to style for both `<Body>` and `<Right>`  
```
<ListItem avatar>
    <Body style={{ borderBottomWidth: 0 }}></Body>
    <Right style={{ borderBottomWidth: 0 }}></Right>
</ListItem>
```

**Comment by anonyzm** [comment]
Finally managed to do this!
Just set _containerStyle_ for ListItem to
`borderBottomColor: 'transparent',
borderBottomWidth: 0,`
