### ISSUE TITLE
How to specify Icon set for Android?

### ISSUE THREAD

**Issue by EllisShen** [GeekyAnts/NativeBase#12]
As title, all sample in the document is using prefix "ios" `<Icon name="ios-refresh" />`, I don't know if there's a specific requirement to use Icon on android platform.  After a brief test, the Icon shown on Android platform seems not looking good, too small. I assume that there's a different naming syntax for Android platform. Any thought?

**Comment by sankhadeeproy007** [comment]
You can use `Android` icons from Ionicions 
http://ionicons.com/
Alternatively you can also use other icon types as defined in 
https://github.com/oblador/react-native-vector-icons

**Comment by s2t2** [comment]
@EllisShen you can use material-design icons from Ionicons by specifying the `md-` prefix:

```` js
<Icon name="md-refresh"/>
````

Check http://ionicframework.com/docs/v2/ionicons/ and click on the icon you want to use to unveil a modal which tells you the name of the icon.

**Comment by mpaleo** [comment]
How can i use icons from `react-native-vector-icons/MaterialIcons` by Google ?

**Comment by iiitmahesh** [comment]
@sankhadeeproy007 @s2t2 How to add custom font icons to native base or [react native vector icons ](https://oblador.github.io/react-native-vector-icons/) icon set??
