### ISSUE TITLE
Support web using react-native-web

### ISSUE THREAD

**Issue by RangerMauve** [GeekyAnts/NativeBase#120]
[react-native-web](https://github.com/necolas/react-native-web) seems to be working on bringing the React-Native APIs to the browser. It would be really useful if this project were to work with it to provide an easy way to build UIs across all three platforms (ios/android/web)

**Comment by sankhadeeproy007** [comment]
It's something we'd look at in the near future. Let's wait for a few more upvotes.

**Comment by sankhadeeproy007** [comment]
@sanketsahusoft need your inputs regarding this.

**Comment by michaelcpuckett** [comment]
+1

**Comment by sanketsahusoft** [comment]
@sankhadeeproy007 It should just work fine if we are not using any native modules.

**Comment by sanketsahusoft** [comment]
@sankhadeeproy007 The drawer uses native module in Android which won't work. We can use the iOS implementation (which is a pure JS implementation of drawer) for RN Web. It should just work.

**Comment by RangerMauve** [comment]
@sanketsahusoft Potentially you could use platform detection using `Platform.OS === "web"` to choose which one should get used for web.

**Comment by sanketsahusoft** [comment]
@RangerMauve Thanks for the input. We're excited about this idea!

**Comment by joelchen** [comment]
This will be great!

**Comment by shishircc** [comment]
Wow, if this is possible, it would be a great feature.

**Comment by rafsoaken** [comment]
+1

**Comment by remon-georgy** [comment]
+1

**Comment by rafsoaken** [comment]
Anyway we could post a bounty here (sorry if thats against TOS, would gladly post this to the correct venue)? 
$200 if this is implemented.

**Comment by sanketsahusoft** [comment]
@rafsoaken Noted. Let me accelerate this up at our end. I will try to get an ETA next week.

If anyone else in the community wants to take it up, we would be more than happy to merge pull-requests.

**Comment by dorthwein** [comment]
Where are we on this? ;) - I'm sure the react-native-web guys would have some insight on know how to do this quickly.

**Comment by RangerMauve** [comment]
Does NativeBase have any native components, or does it just use the React Native API in JS for everything? It could be as simple as adding a "browser" field to the package.json which renames `react-native to `react-native-web`, and trying to compile that for the browser.

**Comment by himanshu-satija** [comment]
See [native-base-web](https://github.com/Chion82/native-base-web) for web support

**Comment by eilijah69** [comment]
Hello, it seems that native-base-web is pretty dead now and not compatible with native-base 2. Do you think it's still possible to implement it with this new version? Do you think about an implementation? I was sad to not be able to find it on the road map. For the most it seems pretty straight forward, only pure native component like drawer should need a fix. But basically just making it compatible for basic components could be easy and great. Playing a bit I could make it run with just a dummy Button.web.js and Picker.web.js.

**Comment by geminiyellow** [comment]
still working?
