### ISSUE TITLE
Content scrollToEnd is not a function

### ISSUE THREAD

**Issue by shivenj** [GeekyAnts/NativeBase#1200]
react-native : 0.47.2
native-base : 2.3.1

Platform:
Android

Expected behaviour:
Content should also scrollToEnd.

Actual Behaviour:
Undefined is not a function

I suppose Content replaces scrollview in native base. so all the methods which apply to scrollview should also apply to Content. but when i call scrollToEnd method on content it says Undefined is not a function. here is the code i'm using:
```
<Content ref={ref => this.content = ref}
                onContentSizeChange={(contentWidth, contentHeight)=>{        
                    this.content.scrollToEnd({animated: true});
                }}>     
                  {_.map(renderedSteps, this.renderStep)}
          </Content>
```

**Comment by shivrajkumar** [comment]
@shivenj use `this.content._root.scrollToEnd({animated: true})`
