### ISSUE TITLE
border radius not working in Tab text style 

### ISSUE THREAD

**Issue by lossen** [GeekyAnts/NativeBase#1204]
Hello!
I have a problem with tabs. I can't set border radius to tab in text style.
Here is my code:
`<pre>
<Tabs initialPage={0} tabBarUnderlineStyle={{ backgroundColor: 'transparent' }}>
                <Tab
                    heading='Tools'
                    textStyle={styles.tabHeadingSquareText}
                    activeTextStyle={styles.tabHeadingSquareTextActive}
                    tabStyle={{justifyContent:'flex-end',backgroundColor:'rgb(242, 242, 242)'}}
                    activeTabStyle={{justifyContent:'flex-end',backgroundColor:'rgb(242, 242, 242)'}}>
                    <View style={combineStyles(styles.contentBody,{paddingTop:64})}>
                       ...
                    </View>
                </Tab>
                <Tab
                    heading='Videos'
                    textStyle={styles.tabHeadingSquareText}
                    activeTextStyle={styles.tabHeadingSquareTextActive}
                    tabStyle={{justifyContent:'flex-start',backgroundColor:'rgb(242, 242, 242)'}}
                    activeTabStyle={{justifyContent:'flex-start',backgroundColor:'rgb(242, 242, 242)'}}>
                </Tab>
            </Tabs>

</pre>`
And here is my styles:
`<pre>
tabHeadingSquareText:{
    color:color6,
    shadowColor:'rgba(204, 204, 204, 0.64)',
    shadowRadius:6,
    shadowOpacity:1,
    shadowOffset:{
      width:0,
      height:2
    },
    paddingTop:10,
    paddingBottom:10,
    paddingLeft:16,
    paddingRight:16,
    borderRadius:4,
    borderWidth:1,
    borderColor:'transparent',
    fontFamily:mainFont
  },
  tabHeadingSquareTextActive:{
    color:'#fff',
    shadowColor:'rgba(204, 204, 204, 0.64)',
    shadowRadius:6,
    shadowOpacity:1,
    shadowOffset:{
      width:0,
      height:2
    },
    paddingTop:10,
    paddingBottom:10,
    paddingLeft:16,
    paddingRight:16,
    borderRadius:4,
    backgroundColor:'rgb(0, 51, 89)',
    borderWidth:1,
    borderColor:'transparent',
    fontFamily:mainFont
  },
</pre>`
and I attach a photo
![simulator screen shot 1 2017 13 07 57](https://user-images.githubusercontent.com/14949813/29958932-e3ad9fae-8f16-11e7-92d1-f1c84cca0065.png)

**Comment by shivrajkumar** [comment]
@lossen `borderRadius doesn't work on Text component. You should apply it to its container i.e, through `tabStyle and activeTabStyle`.
