### ISSUE TITLE
Cannot read property platformStyle of undefined (when trying customize theme for CheckBox attributes)

### ISSUE THREAD

**Issue by reilem** [GeekyAnts/NativeBase#1207]
## react-native, react and native-base version
react-native-cli: 2.0.1
react-native: 0.46.4
native-base: 2.2.1
## Expected behaviour
Being able to customize CheckBox attributes
## Actual behaviour
App receives error on launch
## Steps to reproduce (code snippet or screenshot)
```
import { StyleProvider, CheckBox } from 'native-base'
import checkBoxTheme from '../native-base-theme/components/CheckBox'

class TestComponent extends React.Component {
  render () {
    return (
      <StyleProvider style={checkBoxTheme()}>
        <CheckBox />
      </StyleProvider>
    )
  }
}
```
(Code snippet is simplified and will not actually work if copy-pasted, just tried to capture the essence of the issue)
## Screenshot of emulator/device
![simulator screen shot 3 sep 2017 16 03 50](https://user-images.githubusercontent.com/11155505/30003673-7df2a464-90c1-11e7-8e77-f18af30a368a.png)
## Is the bug present in both ios and android or in any one of them?
So far only tested on iOS
## Any other additional info which would help us debug the issue quicker.

I tried to follow the steps under the `Button Customize` header in the Customize docs to try and customize the color of the CheckBox component.

So after ejecting and looking around I could not find any `Themes` folder. It took me a few hours to understand that `import buttonTheme from './Themes/buttonTheme'` probably(?) was meant to be `import buttonTheme from '../native-base-theme/components/Button'`. So I assumed the equivalent would work for checkBoxThemes(). So just to try it out, I attempted to follow the docs example without making and changes yet. But when I tried it out as described in the docs (see also example code) I get an error (the one in the title). I attempted to figure out what I was doing wrong but the docs provide absolutely no help. The example provided is very bare, and doesn't even describe what the goal of the example code actually is.

For example, in the docs:
```
import buttonTheme from './Themes/buttonTheme';
​// buttonTheme is the customized theme of Button Component​
```
But no information is provided on how to create your own buttonTheme or what the content of buttonTheme is supposed to be.

Also this code snippet (from docs):
```
...
import { Container, Content, Button, Text, getTheme, StyleProvider } from 'native-base';
import customVariables from './Themes/variable';
​// getTheme is default theme of NativeBase Components
// customVariables is customized variables used in the components theme
export default class ThemeButtonExample extends Component {
  render() {
    return (
      <Container>
        <Content>
          <StyleProvider style={buttonTheme(customVariables)}>
            <Button primary>
              <Text> Primary </Text>
            </Button>
...
```
No info is given about the contents of `customVariables` or how to make your own. Also, `buttonTheme` is not imported yet somehow used.

I understand that the variables `platform/material/commonColors` contain the colors/sizes that will be used across the app. But I cannot change the variables since I do not want to change the color of each component 'permanently' but I want to change the color of a few components 'temporarily'.

Any help would be appreciated. And my apologies if I am missing something super obvious and wasting your time!

**Comment by shivrajkumar** [comment]
@reilem Try passing variable to the theme.
`
import { StyleProvider, CheckBox } from 'native-base'
import checkBoxTheme from '../native-base-theme/components/CheckBox'
import variable from '../native-base-theme/variables/platform'

class TestComponent extends React.Component {
  render () {
    return (
      <StyleProvider style={checkBoxTheme(variable)}>
        <CheckBox />
      </StyleProvider>
    )
  }
}
`

**Comment by reilem** [comment]
That does seem to be working. I have however fixed the issue by using my own checkbox component otherwise I would have to copy-paste the entire variables file and adjust the few values I wanted to change the color. This felt like a little overkill.
