### ISSUE TITLE
Support custom "Back" text in Picker

### ISSUE THREAD

**Issue by charlesLin** [GeekyAnts/NativeBase#121]
Please support custom "Back" text when Picker dialog pop up.

**Comment by sanketsahusoft** [comment]
@sankhadeeproy007 Let's discuss before you implement this

**Comment by sankhadeeproy007** [comment]
We've added custom `Header` component in 0.5.6. You can not only have your own custom back button, but the entire header is configurable. To match with your current theme.
Pass your `<Header />` component to `headerComponent` prop. Attached screenshot of example.
![screen shot 2016-08-24 at 7 38 28 pm](https://cloud.githubusercontent.com/assets/10998047/17933610/661247d4-6a32-11e6-974f-f3f1f09be990.png)
