### ISSUE TITLE
Card with header and more than a certain number of lines of text in the body, is not displayed correctly

### ISSUE THREAD

**Issue by agersoncgps** [GeekyAnts/NativeBase#1212]
```
  <Card>
            <CardItem header bordered>
              <Icon style={styles.icon} name="restaurant-menu" />
              <H3 allowFontScaling={false} style={styles.dayText}>
                Lunch
              </H3>
            </CardItem>
              <CardItem>
                <Body>
                  <Text allowFontScaling={false} style={styles.text}>
                    Thanks for taking the beta version of the CGPS App for a
                    test drive. 
                  </Text>
                </Body>
              </CardItem>
            </Card>
```
Looks good:
![screenshot 2017-09-05 21 06 39](https://user-images.githubusercontent.com/336441/30089941-1f2cb3ac-927e-11e7-9ea3-399a3edcebc2.png)

```
<Card>
            <CardItem header bordered>
              <Icon style={styles.icon} name="restaurant-menu" />
              <H3 allowFontScaling={false} style={styles.dayText}>
                Lunch
              </H3>
            </CardItem>
              <CardItem>
                <Body>
                  <Text allowFontScaling={false} style={styles.text}>
                    Thanks for taking the beta version of the CGPS App for a
                    test drive. Please note this is a pre-release "beta" version
                    of the app. There are still bugs. Use the menu icon in the
                    top left to navigate around.
                  </Text>
                </Body>
              </CardItem>
            </Card>

```
Looks bad:

![screenshot 2017-09-05 21 07 09](https://user-images.githubusercontent.com/336441/30089946-31af40bc-927e-11e7-8853-e7311dc57afe.png)

**Comment by bansalayush** [comment]
Hey @agersoncgps ,
I tried your code out and its working 
![device-2017-09-06-143219](https://user-images.githubusercontent.com/9965653/30103429-44d61ae8-9310-11e7-9100-4b1768f1acbc.png)

Please specify version of native-base , react-native

**Comment by SupriyaKalghatgi** [comment]
@agersoncgps Tried both your snippets, works fine
Tried with NativeBase 2.3.1
![simulator screen shot sep 6 2017 3 34 59 pm](https://user-images.githubusercontent.com/13464885/30106413-fe91f0e4-9318-11e7-9efd-2b037fce8983.png)

**Comment by agersoncgps** [comment]
Would it make any difference that you are on Android and I am on iOS?

**Comment by shivrajkumar** [comment]
@agersoncgps The above comments show it to be working on both iOS and android. Do check with the latest and also check the theme file, if you had ejected earlier.
