### ISSUE TITLE
 when i get into the page which has swipeRow  on android ,it has a splash screen

### ISSUE THREAD

**Issue by zcxzmzy** [GeekyAnts/NativeBase#1213]
when i get into the page which has swipeRow on android ,it has a splash screen on the right hand

**Comment by zcxzmzy** [comment]
![image](https://user-images.githubusercontent.com/19526277/30104315-d969a0be-9327-11e7-8d04-312f46a37958.png)

**Comment by SupriyaKalghatgi** [comment]
@zcxzmzy Are you talking about the Docs or NativeBase-KitchenSink?

**Comment by SupriyaKalghatgi** [comment]
Closing this due to insufficient information and inactivity

**Comment by fanzkday** [comment]
@SupriyaKalghatgi But I had the same problem.
```jsx
         <SwipeRow
            directionalDistanceChangeThreshold={10}
            swipeToOpenPercent={10}
            rightOpenValue={-75}
            disableRightSwipe={true}
            right: (
                <Button danger> // It's not visible
                  <Icon active name="trash" />
                </Button>
              )
          />
```
But, when I enter or leave this page, I can see the red "trash button" for 0.x second.

**Comment by SupriyaKalghatgi** [comment]
@fanzkday I checked it for you
I couldn't see red trash button for fraction of second

**Comment by fanzkday** [comment]
@SupriyaKalghatgi Android?

**Comment by fanzkday** [comment]
@SupriyaKalghatgi 
![bugs](https://user-images.githubusercontent.com/29252763/35090571-09fedada-fc75-11e7-9235-0ca1582b2f0f.gif)

**Comment by SupriyaKalghatgi** [comment]
@fanzkdayYou can check this in NativeBase KitchenSink from Expo
https://expo.io/@geekyants/nativebasekitchensink

**Comment by akhil-geekyants** [comment]
@fanzkday if you are using `react-navigation`, this may be due to cardStyle opacity. Try setting cardStyle opacity to 1.
```
const AppNavigator = StackNavigator(
            routes,
           {
               cardStyle: {
                   opacity: 1
                 }
           });
```
see react-navigation [docs](https://reactnavigation.org/docs/en/stack-navigator.html#stacknavigatorconfig)
