### ISSUE TITLE
Fresh install CRNA and nativebase kills jest

### ISSUE THREAD

**Issue by gregbenner** [GeekyAnts/NativeBase#1215]
I see this unresolved all over.
https://stackoverflow.com/questions/45197514/unexpected-token-import-error-crna

If you follow this guide https://docs.nativebase.io/docs/examples/MobxCounterExample.html
You cannot run `npm test`

` FAIL  ./App.test.js
  ● Test suite failed to run

    /Users/gnb/Sites/homeowner-mobile-2/node_modules/native-base-shoutem-theme/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import connectStyle from './src/connectStyle';
                                                                                             ^^^^^^
    SyntaxError: Unexpected token import`

**Comment by shivrajkumar** [comment]
#977
