### ISSUE TITLE
DeckSwiper cannot be used inside of a Content Component

### ISSUE THREAD

**Issue by w-** [GeekyAnts/NativeBase#1217]
Hi! Thanks for trying out NativeBase!
Due to the overwhelming requests and issues/questions we ask you to add the following details with your issue.

Please check the existing open/closed issues for a possible duplicate before creating a new issue :)

Also **DO** fill out the below form to give us a better idea about your environment and help us debug it quicker. Issues without the required details will mostly be unattended to.

## react-native, react and native-base version
"native-base": "^2.3.1",
"react": "16.0.0-alpha.12",
"react-native": "https://github.com/expo/react-native/archive/sdk-20.0.0.tar.gz",

also using this on expo  v20.0.0

## Expected behaviour
Using DeckSwiper inside a Content component should render components returned by renderItem prop.

## Actual behaviour
Using DeckSwiper inside of a Content component will cause items to not render. 
The component rendered by renderEmpty prop is fine.
No component returned by renderItem prop is ever visible on screen

This is similar behavior to what is observed here:
https://github.com/GeekyAnts/NativeBase/issues/369

## Steps to reproduce (code snippet or screenshot)

This does not work.
```
class DummyScreen extends React.Component{
	constructor(props){
		super(props);

		this.blah = this.blah.bind(this)
	}

	blah(item){
		return <TinderCard title='OMG IT RENDERED'></TinderCard>
	}

	render(){

		let data = [];
		data = [1,2,3,4,5];

		return (
			<Container>
				<Header>
					<Left>
						<Button transparent onPress={this.showMenu}>
							<Icon name="menu"></Icon>
						</Button>
					</Left>
					<Body>
						<Title>Tinder</Title>
					</Body>
					<Right></Right>
				</Header>

				<Content>
				<View style={{ flex: 1 }}>
					<DeckSwiper
	            			dataSource={data}
	            			renderItem={this.blah}
	            			renderEmpty={ ()=><Text>GFY</Text> } />
				</View>
				</Content>
			</Container>
		);
	}
}
```

but if we remove Content component it works

```
class DummyScreen extends React.Component{
	constructor(props){
		super(props);

		this.blah = this.blah.bind(this)
	}

	blah(item){
		return <TinderCard title='OMG IT RENDERED'></TinderCard>
	}

	render(){

		let data = [];
		data = [1,2,3,4,5];

		return (
			<Container>
				<Header>
					<Left>
						<Button transparent onPress={this.showMenu}>
							<Icon name="menu"></Icon>
						</Button>
					</Left>
					<Body>
						<Title>Tinder</Title>
					</Body>
					<Right></Right>
				</Header>


				<View style={{ flex: 1 }}>
					<DeckSwiper
	            			dataSource={data}
	            			renderItem={this.blah}
	            			renderEmpty={ ()=><Text>GFY</Text> } />
				</View>

			</Container>
		);
	}
}
```

for the record this does not work either:
```
<Content style={{ flex: 1 }}>
					<DeckSwiper
	            			dataSource={data}
	            			renderItem={this.blah}
	            			renderEmpty={ ()=><Text>GFY</Text> } />
				</Content>
```

## Screenshot of emulator/device
![image](https://user-images.githubusercontent.com/357317/30202957-7e6f9fea-94aa-11e7-9766-e659dafed649.png)

## Is the bug present in both ios and android or in any one of them?
haven't been able to test ios

**Comment by shivrajkumar** [comment]
![deck](https://user-images.githubusercontent.com/17001305/30261862-23cc1b24-96ec-11e7-8672-e6051ed98fd1.gif)
@w- Seems to be working fine with the content in the latest version 2.3.1

**Comment by w-** [comment]
@shivrajkumar  Thanks for confirming.  I am on 2.3.1
It doesn't work for me in expo.
I'm not sure what else I can do on my end.
I guess you can close this as you are unable to repro, but it's strange that it works for you and not for me.

**Comment by shivrajkumar** [comment]
@w- Have you checked whether you are able to access items in `blah` function

**Comment by w-** [comment]
Yes. I tried rendering blah independently without issue.

**Comment by dalefrancis88** [comment]
I am seeing this same issue in Android, but it works in iOS. No error or reason given

**Comment by hoekma** [comment]
I'm also having this issue with Android.  

To add to @dalefrancis88, it does render on an older iPad, but cards don't seem to want to fully "flip" and stop in the middle with two cards showing, one that is half-flipped and the one underneath that should have become the top card.  It takes a few swipes to get it to flip.

**Comment by akhil-geekyants** [comment]
adding  `flex:1` to prop `contentContainerStyle`  solves the issue.
```
<Content contentContainerStyle={{ flex: 1 }}>
````

**Comment by akhil-geekyants** [comment]
#957
