### ISSUE TITLE
update margin of ListItems in a List

### ISSUE THREAD

**Issue by garan82** [GeekyAnts/NativeBase#1219]
Hello,

I'm using
Expo 20
React Native 0.47
React 16.0.0-alpha.12
NativeBase 2.2.1

I use NativeBse List, ListItem, and Card. Basically, I have many ListItem in a List. Each ListItem includes a Card. The margin between any two consecutive ListItem is doubled, probably because it's marginBottom of the first one and the marginTop of the second. How can I update style of ListItem/Card to fix this double margins? I already set `style={{borderBottomWidth: 0}}` for ListItem.

This is my code.

`<List
    style={{margin: 0}}
    dataArray={this.state.data}
    itemDivider
    renderRow={data =>
        <ListItem style={{borderBottomWidth: 0}}>
            <Card>
                <CardItem style={{backgroundColor: "#eeeeee"}}>
                    <Body>
                        <Text style={{color : "#494949"}}>{data.name}</Text>
                    </Body>
                </CardItem>
            </Card>
        </ListItem>
    }
/>`

Thank you!!!

Edit: sorry about the formatting, not sure why the code shows up as a mess inside code tag. Here is the code https://paste.ofcode.org/huzwK9nmAbXjLxy5JFvK5w

**Comment by shivrajkumar** [comment]
@garan82 ListItem, Card and CardItems, each have some padding or margin of their own. You can just inspect the screen, check it and remove the padding/margin as per your requirement using style. Or you can eject NativeBase theme http://docs.nativebase.io/Customize.html#Customize and do your changes in the theme of those components. That way you will have the same styles for those component in your whole app.

**Comment by garan82** [comment]
I wish I could debug DOM elements but I'm plagued by this bug https://github.com/facebook/react-native/issues/6390#issuecomment-329316168 :(
