### ISSUE TITLE
How can I style a Picker with borderWidth and borderColor

### ISSUE THREAD

**Issue by charlesLin** [GeekyAnts/NativeBase#122]
A picker is like a normal Text. It would be better  like a html select tag style.
How can I style a Picker?

<Picker style={{ borderWidth:1, borderColor: 'blue'}} /> would not work.

**Comment by sankhadeeproy007** [comment]
You can now add all the styles to a picker like you would to a `<View />` component. Added in 0.5.6

**Comment by jeremypeters** [comment]
It may be worthwhile pointing out in the docs that the selected item's text can be styled using a `textStyle` prop on `Picker`.

**Comment by cseelus** [comment]
Adding a border doesn't work on Android, can anybody confirm that?

**Comment by mofesolapaul** [comment]
Confirmed
