### ISSUE TITLE
Button Icon/Text left aligned?

### ISSUE THREAD

**Issue by appjitsu** [GeekyAnts/NativeBase#1220]
- How would I go about aligning the button text and icon to the left in each button?
- Is it possible to add colored images instead of the icon?

From Sketch:
![screen shot 2017-09-10 at 12 12 27 am](https://user-images.githubusercontent.com/10903600/30246347-d02d36cc-95bc-11e7-948d-c3c0c1c99682.png)

My code:
```
<Button
  block
  rounded
  iconLeft
  style={{ height: 53, marginBottom: 10 }}
>
  <Icon name="logo-google" />
  <Text>Continue with Google</Text>
</Button>
```

![screen shot 2017-09-10 at 12 15 26 am](https://user-images.githubusercontent.com/10903600/30246355-2cfc24b2-95bd-11e7-9bce-bedb70aa043d.png)

**Comment by shivrajkumar** [comment]
@appjitsu Apply style rule `justifyContent: "flex-start"` to the Button.

**Comment by appjitsu** [comment]
Ah ok. Thanks. What do you recommend for the full images next to the text instead of using icons?

~ Jason

**Comment by shivrajkumar** [comment]
@appjitsu You can use Image itself there

**Comment by appjitsu** [comment]
@shivrajkumar Thanks!
