### ISSUE TITLE
Horizontal Form Inputs

### ISSUE THREAD

**Issue by appjitsu** [GeekyAnts/NativeBase#1224]
How would you accomplish the horizontal form inputs as pictured below? The input is a mask, basically.

![screen shot 2017-09-11 at 5 46 09 pm](https://user-images.githubusercontent.com/10903600/30300235-33c91ef0-9719-11e7-9414-be1a1ce9fdc7.png)

**Comment by shivrajkumar** [comment]
@appjitsu Try this 
```
<Form style={{ flexDirection: "row" }}>
  <Item floatingLabel style={{ flex: 1 }}>
    <Label>Month</Label>
    <Input />
  </Item>
  <Item floatingLabel style={{ flex: 1 }}>
    <Label>Pas</Label>
    <Input />
  </Item>
  <Item floatingLabel style={{ flex: 1 }}>
    <Label>Pas</Label>
    <Input />
  </Item>
  <View style={{ flex: 1 }} />
</Form>
```

**Comment by appjitsu** [comment]
Works great, thanks!

**Comment by appjitsu** [comment]
@shivrajkumar How would spread out the inputs so that they take up 100% of the width?

![screen shot 2017-09-13 at 4 20 22 pm](https://user-images.githubusercontent.com/10903600/30401380-aada0a7c-989f-11e7-9d29-cb231c7a4864.png)
