### ISSUE TITLE
[Android] Under TabBar ,  horizontal List not working

### ISSUE THREAD

**Issue by sachithamadhupa** [GeekyAnts/NativeBase#1225]
this issue only for android it's working for iOS

```
<Container>
        <Header hasTabs/>
        <Tabs>
          <Tab heading={ <TabHeading><Icon name="camera" /><Text>Camera</Text></TabHeading>}>
                            <List dataArray={ItemList} horizontal={true}
                      renderRow={(item) =>
                          < HorizontalCell  data={item} >
                      }>
                </List>
          </Tab>
          <Tab heading={ <TabHeading><Text>No Icon</Text></TabHeading>}>
            <Tab2 />
          </Tab>
          <Tab heading={ <TabHeading><Icon name="apps" /></TabHeading>}>
            <Tab3 />
          </Tab>
        </Tabs>
      </Container>
```
![screen shot 2017-09-12 at 10 58 01 am](https://user-images.githubusercontent.com/5784803/30309527-6d0e3fb6-97a9-11e7-987d-ac75efc52d30.png)

red boxes are horizontal cells when I try to move its goes to 2nd tab 
for iOS it's worked

**Comment by shivrajkumar** [comment]
@sachithamadhupa You can either lock the Tabs swipe using `locked` prop in Tabs or check with pointer-events/touches for both the scrollable contents i.e, cells and Tabs

**Comment by sachithamadhupa** [comment]
yep it's working but, it's better to fix in a good way, @shivrajkumar  k thanx for your answer

**Comment by shivrajkumar** [comment]
@sachithamadhupa Better way/the correct way would be through [pointer events](https://facebook.github.io/react-native/docs/view.html#pointerevents).

**Comment by sachithamadhupa** [comment]
yep thanks @shivrajkumar  :) 💯
