### ISSUE TITLE
StyleProvider/theme does not support hot reload

### ISSUE THREAD

**Issue by elnygren** [GeekyAnts/NativeBase#1227]
It seems that StyleProvider in `native-base-shoutem-theme` does not support hot reload:
https://github.com/GeekyAnts/NativeBase/issues/910
https://github.com/GeekyAnts/NativeBase/issues/1216
https://github.com/GeekyAnts/NativeBase/issues/772

tldr: changing theme variables has no effect after hot reload, a full reload is necessary. This might or might not be related to `react-navigation`.

This makes development with NativeBase extremely tedious because you either have to:
a) suffer and edit styles with full reloads
b) subclass everything (`Card` -> `MyCard extends Card`) and style them without using themes

What would it take to get this support? Is there some workaround? I'm going to have to drop NativeBase from my project (and recommend everyone to do the same) if there isn't a good solution to this.

Here's an example of a UI framework for React Native that *does* implement theming of components with hot reload support. https://github.com/akveo/react-native-ui-kitten and https://github.com/akveo/kittenTricks

**Comment by jariwalabhavesh** [comment]
@SupriyaKalghatgi 
Any update on this issue (solution)

**Comment by josephbuchma** [comment]
There is this thing under development, which looks very promising http://nativebase-customizer.geekydev.com/

**Comment by WilGatlin** [comment]
@elnygren  This manual clear works great: https://github.com/GeekyAnts/theme/pull/5 

But needs to be merged and has been outstanding for a while.

**Comment by Lurtroxx** [comment]
Any update to this???
