### ISSUE TITLE
Radio button not working correctly / Not switching to other radio item 

### ISSUE THREAD

**Issue by Abdul-majid-ashrafi** [GeekyAnts/NativeBase#1229]
Hi! Thanks for provide NativeBase!
I follow http://nativebase.io/docs/v0.5.13/components#radioButton to create radio button in my project.

## Expected behaviour.
I want to switch radio and Selected show

## Actual behaviour.
Render Radio with every item but not selected

## Code here:
import React, { Component } from 'react'
import firebase from 'firebase'
import { Container, Header, Content, List, ListItem, Left, Body, Right, Thumbnail, Text, Button, Icon, Radio } from 'native-base';

export class SpeciesComponent extends Component {

    constructor() {
        super()
        this.state = {
            speciesArray: [],
            pressed: true,
            value: ""
        };
    }
    componentWillMount() {
        let refRoot = firebase.database().ref('/list')
        refRoot.on("child_added", (snap) => {
            var obj = snap.val();
            obj.key = snap.key;
            this.state.speciesArray.push(obj)
            this.setState({ speciesArray: this.state.speciesArray })
        })
    }

    onCheckBoxPress(ev) {
        console.log("EV", ev)
        this.setState({ pressed: false });
        this.setState({ value: 'BODYVALUE' });
    }

    render() {
        return (
            <Container>
                <Content>
                    <List>

                        {this.state.speciesArray.map((value, index) => {
                            return (
                                <ListItem avatar style={{ margin: 5 }} key={index} >
                                    <Left>
                                        <Thumbnail source={{ uri: value.icon }} />
                                    </Left>
                                    <Body>
                                        <Text>{value.name}</Text>
                                    </Body>
                                    <Radio onPress={this.onCheckBoxPress.bind(this, value)} selected={this.state.pressed} />
                                </ListItem>
                            )
                        })}
                    </List>
                </Content>
            </Container>
        )
    }
}

**Comment by akhil-geekyants** [comment]
@Abdul-majid-ashrafi you can set some height and width to the Radio button style and also add some backgroundColor to identify the radio button area. This makes the area clickable even after the radio button is unchecked.

```
import React, { Component } from "react";
import {
  Container,
  Header,
  Content,
  List,
  ListItem,
  Left,
  Body,
  Right,
  Thumbnail,
  Text,
  Button,
  Icon,
  Radio,
} from "native-base";

export default class NHRadio extends Component {
  constructor() {
    super();
    this.state = {
      speciesArray: [
        {
          icon:
            "https://s3.amazonaws.com/media-p.slid.es/uploads/jhabdas/images/969312/react-logo-1000-transparent.png",
          name: "One",
        },
        {
          icon:
            "https://s3.amazonaws.com/media-p.slid.es/uploads/jhabdas/images/969312/react-logo-1000-transparent.png",
          name: "Two",
        },
        {
          icon:
            "https://s3.amazonaws.com/media-p.slid.es/uploads/jhabdas/images/969312/react-logo-1000-transparent.png",
          name: "Three",
        },
        {
          icon:
            "https://s3.amazonaws.com/media-p.slid.es/uploads/jhabdas/images/969312/react-logo-1000-transparent.png",
          name: "Four",
        },
        {
          icon:
            "https://s3.amazonaws.com/media-p.slid.es/uploads/jhabdas/images/969312/react-logo-1000-transparent.png",
          name: "Five",
        },
      ],
      pressed: true,
      value: "",
    };
  }

  onCheckBoxPress(ev) {
    if (this.state.value == ev) {
      this.setState({ value: {} });
      return;
    }
    this.setState({ value: ev });
  }

  render() {
    return (
      <Container>
        <Content>
          <List>
            {this.state.speciesArray.map((value, index) => {
              return (
                <ListItem avatar style={{ margin: 5 }} key={index}>
                  <Left>
                    <Thumbnail source={{ uri: value.icon }} />
                  </Left>
                  <Body>
                    <Text>{value.name}</Text>
                  </Body>
                  <Right>
                    <Radio
                      style={{
                        width: 15,
                        height: 30,
                        paddingLeft: 3,
                        backgroundColor: "lightgrey",
                      }}
                      onPress={this.onCheckBoxPress.bind(this, value)}
                      selected={this.state.value == value}
                    />
                  </Right>
                </ListItem>
              );
            })}
          </List>
        </Content>
      </Container>
    );
  }
}

```

**Comment by akhil-geekyants** [comment]
@Abdul-majid-ashrafi you can fix this by handling the onPress event on the `<ListItem/>`.

**Comment by akhil-geekyants** [comment]
Closing this due to no response
