### ISSUE TITLE
Picker inside a Navigator throw "Maximum call stack size exceeded" exception

### ISSUE THREAD

**Issue by charlesLin** [GeekyAnts/NativeBase#123]
When I use a Picker inside Navigator, it will throw Maximum call stack size exceeded" exception

sample code.

import React, { Component } from 'react';
import {
  AppRegistry,
  StyleSheet,
  Text,
  View,
  Navigator
} from 'react-native';

import { Picker } from 'native-base';

class testpicker extends Component {
  constructor(props) {
    super(props);
    this.state = {
      status: 15
    };
    this.renderScene = this.renderScene.bind(this);
  }
  renderScene(route, Navigator) {
    return (<View><Text>aaa</Text>
      <Picker style={{ width: 100, borderWidth: 1, borderColor: 'red' }} selectedValue={this.state.status}
        onValueChange={s => this.setState({ status: s }) }
        iosHeader="please select one">
        <Picker.Item label="0" value={0}/>
        <Picker.Item label="15" value={15} />
        <Picker.Item label="30" value={30} />
      </Picker>
    </View>)
  }
  render() {
    return (
      <Navigator initialRoute={{ name: 'defaultView' }}
        renderScene={this.renderScene.bind(this) }>
      </Navigator>
    );
  }
}

AppRegistry.registerComponent('testpicker', () => testpicker);

**Comment by sankhadeeproy007** [comment]
Fixed in 0.5.5

**Comment by jakobinn** [comment]
Are you sure?
I'm getting this in Native Base pickers versions 0.5.5 and also 0.5.8, only on IOS, not on android.
