### ISSUE TITLE
ActionSheet Style

### ISSUE THREAD

**Issue by anjapadu** [GeekyAnts/NativeBase#1231]
Hello, 
I was wondering if there is an option to customize the style of the actionsheet?
I was searching into the code and found that you can't customize it in the theme or by props.

Someone figured a way to do this witouth modify the sourcecode on nativebase actionsheet?
Will apreciate it alot.
Thanks

**Comment by akhil-geekyants** [comment]
@anjapadu sharing the material design guidelines for bottom sheets https://material.io/design/components/sheets-bottom.html#
Can you specify what you would like us to add to NativeBase actionsheets (android)

**Comment by nihaux** [comment]
hello any news on this feature ?  open for PR ?

**Comment by summerkiflain** [comment]
I also need dark background color for actionsheet at least on android, and light text color for action items. Please someone share if there is any other solution for it also. I am using it in an expo app.

**Comment by peleccom** [comment]
Still impossible to change the color of actionSheetContainer

**Comment by yunau** [comment]
Me too, I need to change the text color for the NativeBase ActionSheet.

**Comment by kimkong88** [comment]
howcome this did not get merged in?

**Comment by LucasBrazi06** [comment]
Actionsheet not working with Dark theme on Android:

![image](https://user-images.githubusercontent.com/25266945/88856342-9decf900-d1f4-11ea-850d-eba7fb87e90d.png)

**Comment by Aryk** [comment]
Any updates on this? It's been 3 years...

**Comment by Aryk** [comment]
For anyone who needs a solution until this gets merged:

https://github.com/beefe/react-native-actionsheet

**Comment by chaaya** [comment]
They have fixed it, but forgot to update typings for Typescript and does not mention it in their docs.
https://github.com/GeekyAnts/NativeBase/commit/75a604f78e95d50c076f02a62ea58023ca088391

You can pass a style object into the configuration.

`
ActionSheet.show({
        style: {
          backgroundColor: 'red',
        },
        options: []
  };
`
