### ISSUE TITLE
androidRippleColor change not reflecting

### ISSUE THREAD

**Issue by Hirvesh** [GeekyAnts/NativeBase#1233]
Hi,

I'm trying to change the androidRippleColor to black in the platform theme, it's not changing. It remains the original color.

 "native-base": "^2.3.2",
    "react": "16.0.0-alpha.12",
    "react-native": "0.48.3",

**Comment by tasso-evangelista** [comment]
Can you check if `androidRippleColorDark` does the job?

**Comment by akhil-geekyants** [comment]
@Hirvesh it is working in `native-base: "2.3.3"`
