### ISSUE TITLE
Have you seen any issues with layout on iPhone X?

### ISSUE THREAD

**Issue by agersoncgps** [GeekyAnts/NativeBase#1234]
"native-base": "^2.3.2",
"react-native": "0.48.3",
Code: https://pastebin.com/WFM2HtMf

![screenshot 2017-09-16 23 07 51](https://user-images.githubusercontent.com/336441/30517686-29a814ce-9b35-11e7-9343-7113a5d8e80e.png)

**Comment by KDamir** [comment]
In Card element? Try like this: <Card style={{flexWrap: null}} />

**Comment by dtuite** [comment]
I had the same problem. @KDamir's solution fixes it.

**Comment by akhil-geekyants** [comment]
`<Card style={{flexWrap: "nowrap"}} />` also solves the problem

**Comment by SupriyaKalghatgi** [comment]
Fixed with NativeBase [2.3.5](https://github.com/GeekyAnts/NativeBase/releases/tag/v2.3.5)
