### ISSUE TITLE
Feature request: Use theme to turn off uppercase buttons on Android

### ISSUE THREAD

**Issue by randomjunk** [GeekyAnts/NativeBase#1235]
NativeBase enforces uppercase on Buttons when not on iOS [here](https://github.com/GeekyAnts/NativeBase/blob/7d1be6869a4b3d0deb51e3708daf20f548caa2ad/src/basic/Button.js#L32).

Unfortunately there's no way to disable this behaviour other than by adding `<Text uppercase={false}>` every time we create a Button, which is messy and easily forgotten, or creating a wrapper component to do that, which is also easily forgotten.

I looked into disabling via the theme or via variables, but couldn't find any easy way to do that as the property isn't style.

So request is for either:
- a way to switch off the uppercase globally in variables
- a way to switch off in theme which can then be applied to certain button classes

**Comment by SupriyaKalghatgi** [comment]
Fixed with NativeBase [2.3.5](https://github.com/GeekyAnts/NativeBase/releases/tag/v2.3.5)
