### ISSUE TITLE
Strange visual artifact in segment control.

### ISSUE THREAD

**Issue by agersoncgps** [GeekyAnts/NativeBase#1236]
"native-base": "^2.3.2",
"react-native": "0.48.3",
iOS 10.3

I am not seeing this in the simulator. Only on my real iPhone 6 hardware.
![img_1620](https://user-images.githubusercontent.com/336441/30522010-739b7bd6-9b97-11e7-80bd-ad36a0d50bfd.PNG)

**Comment by akhil-geekyants** [comment]
@agersoncgps you can remove this by ejecting the theme  ([http://docs.nativebase.io/Customize.html#Customize](url)) and add `borderRightWidth:0` to `"NativeBase.Button":{}` inside `segmentTheme` in file 
`native-base-theme/components/segment.js`

**Comment by agersoncgps** [comment]
That worked. Thanks.

**Comment by bencollab** [comment]
Is this affecting everyone who uses the Segment control, or only some people? If everyone, do we need a PR to get it merged in to the default theme? If not everyone, any idea why - or for that matter, why it shows up differently on the phone vs simulator?

FYI - `borderRightWidth:0` fixed it for me also (on the device), but unfortunately in the simulator it makes the right-most segment show up without any right border (as one might expect).
