### ISSUE TITLE
CardItem misalignment when using switch on the right

### ISSUE THREAD

**Issue by kcjl519** [GeekyAnts/NativeBase#1238]
I'm trying to render a carditems with label on the left, and switch on the right, but I can't get it to line up properly. I'm using native-base@2.3.1, react-native@0.46.4

This is my code
```
        <Card>
          <CardItem>
            <Body>
              <Text>Airplane Mode 3</Text>
            </Body>
            <Right>
              <Switch value={false} />
            </Right>
          </CardItem>
        </Card>
```
This renders 

<img width="405" alt="screen shot 2017-09-19 at 12 53 19 am" src="https://user-images.githubusercontent.com/2359169/30548236-f55cd47e-9cd4-11e7-9bc7-c7187cbee376.png">

Instead of something like this

![image](https://user-images.githubusercontent.com/2359169/30548496-a66938ca-9cd5-11e7-92e5-1e930fa9777a.png)

**Comment by akhil-geekyants** [comment]
@kcjl519  can you try  this
` <Container>
          <Content>
            <Card>
              <CardItem>
                <Body>
                  <Text>Airplane Mode 3</Text>
                </Body>
                <Right>
                  <Switch value={false} />
                </Right>
              </CardItem>
            </Card>
          </Content>
        </Container>`

**Comment by cjoelrun** [comment]
Getting the same behavior

@expo/vector-icons@5.2.0
native-base@2.3.2
react-native "https://github.com/expo/react-native/archive/sdk-21.0.2.tar.gz",

```
<Container>
    <Content>
        <Card>
            <CardItem>
                <Body>
                <Text>Airplane Mode 3</Text>
                </Body>
                <Right>
                    <Icon name="ios-navigate"/>
                </Right>
            </CardItem>
        </Card>
        <Card>
            <CardItem>
                <Text>Airplane Mode 3</Text>
                <Right>
                    <Icon name="ios-navigate"/>
                </Right>
            </CardItem>
        </Card>
    </Content>
</Container>
```
<img width="390" alt="screen shot 2017-09-23 at 4 58 42 pm" src="https://user-images.githubusercontent.com/14574/30777452-7ad2e770-a080-11e7-8a58-f3e4e1b49bc3.png">

**Comment by cjoelrun** [comment]
Ok realized this is unreleased version. Working fine on native-base@2.2.1.
