### ISSUE TITLE
NativeBase Tabs View 

### ISSUE THREAD

**Issue by ignivaravinderrikhi** [GeekyAnts/NativeBase#1241]
Hi,

While using NativeBase Tabs I am populating content via API calls using onChangeTab , which works fine if I drag the view left or right. But on selecting a tab from its label the empty view is getting rendered

Following is the view on selecting tabs using dragging

![giphy](https://user-images.githubusercontent.com/20724772/30683368-d3b26f3a-9eca-11e7-9237-d4e5479e6d26.gif)

And following is the view on selecting Tabs by clicking on labels   

![bugsgiphy](https://user-images.githubusercontent.com/20724772/30683506-4dea6370-9ecb-11e7-958d-6e0df7ca58f4.gif)

## react-native, react and native-base version

"native-base": "2.3.1",
"react": "16.0.0-alpha.12",
"react-native": "0.47.0",

## Expected behaviour

Flatlist view getting rendered 

## Actual behaviour

Empty view is being rendered

**Comment by akhil-geekyants** [comment]
@ignivaravinderrikhi were you able to fix this. Tried to reproduce. But didn't see anything like above. 

![tabs2](https://user-images.githubusercontent.com/27768184/32768230-f7e58184-c93c-11e7-889c-efaa62567f55.gif)

**Comment by akhil-geekyants** [comment]
Closing this issue due to no response
