### ISSUE TITLE
What about a NativeBase cross platform (mobille and WEB)

### ISSUE THREAD

**Issue by vinils** [GeekyAnts/NativeBase#1244]
ps.: Not a bug. It´s Request feature

What about to build nativebase on top of reactxp to have cross platform **(including web)**

Bellow a sample project built on and mentioned in [reactxp issue](https://github.com/Microsoft/reactxp/issues/281)

![image](https://user-images.githubusercontent.com/14332724/30724321-855f52dc-9f13-11e7-8953-8c4bbafca7cc.png)

**Comment by miguelocarvajal** [comment]
Is this what the "web" branch is for?

Is this part of the roadmap or being looked at for a future version?

**Comment by sanketsahusoft** [comment]
The latest should work with react-native-web. We are still to document this
part.

Best,
Sanket

On Tue, Nov 7, 2017 at 7:49 AM, Miguel O. Carvajal <notifications@github.com

**Comment by miguelocarvajal** [comment]
@sanketsahusoft that’s great news! So this means it will be officially supported going forward?

Miguel

**Comment by sanketsahusoft** [comment]
Yes, we hope so!

**Comment by vinils** [comment]
would that be done with reactxp?

**Comment by micimize** [comment]
I was able to get `2.3.4` to compile after some monkey patching, but at least with `react@16.0.0-alpha.12` the examples don't render correctly or throw errors. I wasn't able to get it to compile with earlier version of react.

### Steps to compile
1. copying the following files from `.android.js` to `.web.js` extension:
```bash
native-base/dist/src/basic/Tabs/Button
native-base/dist/src/theme/components/Picker
native-base/dist/src/basic/Picker/basic/Picker
```
  
2. alias `ReactNativePropRegistry` and make `react-native` alias exclusive:
```js
{
  /* ... */
  resolve: {
    extensions: [ ".js", "jsx", ".web.js", ".web.jsx" ],
    alias: {
      'react-native$': 'react-native-web',
      'react-native/Libraries/Renderer/shims/ReactNativePropRegistry': 'react-native-web/dist/modules/ReactNativePropRegistry/index.js',
      'react-router-native': 'react-router',
    },
  },
/* ... */
}
```

**Comment by cupliz** [comment]
@micimize i got this after editing some file you mentions, do you know hot resolve it?

`/node_modules/native-base-shoutem-theme/src/StyleProvider.js
Module parse failed: Unexpected token (10:19)
You may need an appropriate loader to handle this file type.
|  */
| export default class StyleProvider extends React.Component {
|   static propTypes = {
|     children: PropTypes.element.isRequired,
|     style: PropTypes.object,`

i am planning to buy some theme in https://market.nativebase.io, just make sure it can be used in web too

**Comment by micimize** [comment]
@cupliz you need to `include` any untranspiled node modules in your babel loader, which there are a lot of with the react-native ecosystem.
```js
   /* ... */
    rules: [
      {
        test: /.jsx?$/,
        // Add every directory that needs to be compiled by Babel during the build
        include: [
          path.join(__dirname, './index.web.jsx'),
          path.resolve(__dirname, './node_modules/native-base-shoutem-theme')
        ],
        use: [  'react-hot-loader/webpack', 'babel-loader' ]
      }
    ]
 /* ... */
```
I prefer to do this explicitly per module, but you could use a regex and `include` properly transpiled modules instead

**Comment by cupliz** [comment]
@micimize could you give me your working webpack config for this case?
thanks

**Comment by micimize** [comment]
I'm currently working off of [my fork](https://github.com/micimize/NativeBase) with [this configuration](https://gist.github.com/micimize/bf64ecbb6a32c236534a3431e76b27bb). It has a few more need changes other than just the [generic components](https://github.com/GeekyAnts/NativeBase/pull/1437). I'll probably PR when I'm satisfied it's usable

**Comment by remon-georgy** [comment]
>  It has a few more needed changes other than just the generic component files

There already *multiple* PRs queued that are supposed to tackle all those issues.

**Comment by micimize** [comment]
@remon-georgy well, I've only seen the one. But if all the kinks get ironed out without me having to PR anything, even better

**Comment by SupriyaKalghatgi** [comment]
NativeBase supports web version with 2.4.1
Check docs https://docs.nativebase.io/docs/GetStarted.html
