### ISSUE TITLE
Icons not shown

### ISSUE THREAD

**Issue by aloifolia** [GeekyAnts/NativeBase#1248]
## react-native, react and native-base version
react: 16.0.0-alpha.12
react-native: 0.47
native-base: 2.3.2
## Expected behaviour
An icon should be shown when I use `<Icon name="menu">`
## Actual behaviour
A substitute icon is shown.
## Steps to reproduce (code snippet or screenshot)
![screenshot_20170925-115027](https://user-images.githubusercontent.com/1295054/30803333-85d61d44-a1e9-11e7-9d10-e8ef39ca0b81.jpg)
The full source code is
```
export default class App extends React.Component {
    render() {
        return (
            <Container>
                <Header>
                    <Left>
                        <Button transparent>
                            <Icon name="home" />
                        </Button>
                    </Left>
                    <Body>
                        <Title>Termine</Title>
                    </Body>
                </Header>
                <Content>
                    <Text>Appointments...</Text>
                </Content>
            </Container>
        );
    }
}
```
## Is the bug present in both ios and android or in any one of them?
At least on an Android device...

**Comment by akhil-geekyants** [comment]
I tried the above code on the versions specified by you. But the home icon was displaying properly. Can you check these issues #76 & #138

**Comment by shivrajkumar** [comment]
@aloifolia You need to link the icons. run `react-native link` or `react-native link react-native-vector-icons`

**Comment by waritthornnudee** [comment]
set type attribute depend on Bundled Icon Sets(list below)
Example <Icon name="flash-off" type="Entypo" />

Bundled Icon Sets
Entypo
EvilIcons
Feather
FontAwesome
Foundation
Ionicons
MaterialIcons
MaterialCommunityIcons
Octicons
Zocial
SimpleLineIcons

Nativebase use: react-native-vector-icons
See full docs here: https://github.com/oblador/react-native-vector-icons
