### ISSUE TITLE
Are there some errors in the listitem？

### ISSUE THREAD

**Issue by gooddaddy** [GeekyAnts/NativeBase#1249]
package.json:

	"dependencies": {
		"native-base": "^2.2.1",
		"react": "16.0.0-alpha.12",
		"react-native": "0.48.4",
		"react-navigation": "^1.0.0-beta.11"
	}
then screen shot:
![simulator screen shot 2017 9 25 9 58 43](https://user-images.githubusercontent.com/14076373/30813049-e7c1a3e8-a23e-11e7-9bec-1290823d1fd5.png)

when I user "react-native": "0.44.3" &"native-base": "^2.2.0" .,it work well;

**Comment by SoldierCorp** [comment]
Same issue, I thought it was only me I even wrote my issue in the slack channel but no answer yet

**Comment by binhnd-socicom** [comment]
I found the reason comes from backgroundColor of `props` in `render` function of ListItem. In version 2.2.0, its value is `undefined` but `#fff` in 2.3.2. 

Set `<ListItem style={{backgroundColor:undefined}}>` works for me :D

**Comment by mmtootmm** [comment]
Same issue and below is what I wanted for push sticking arrow-forward icon away
```HTML
<ListItem icon>
  <Body>
    <Text>{item}</Text>
  </Body>
  <Right>
    <Icon name="arrow-forward" />
  </Right>
</ListItem>
```

**Comment by akhil-geekyants** [comment]
@mmtootmm can you check with latest native base version (2.3.3). 

Gif 

![listitem](https://user-images.githubusercontent.com/27768184/33015234-05d420c0-ce10-11e7-8f7f-f34e153c020c.gif)

**Comment by minotaurrr** [comment]
Same issue with v2.3.3

**Comment by SupriyaKalghatgi** [comment]
```
<ListItem button >
    <Body>
        <Text>TextOne</Text>
    </Body>
    <Right>
        <Icon name="arrow-forward" />
    </Right>
</ListItem>
```
```
```
<ListItem button >
    <Left>
        <Text>TextOne</Text>
    </Left>
    <Right>
        <Icon name="arrow-forward" />
    </Right>
</ListItem>
```

Both these snippets give expected output
My dependencies are
```
"native-base": "2.3.3",
"react": "16.0.0",
"react-native": "0.50.0",
```

**Comment by carsonwah** [comment]
@SupriyaKalghatgi I can confirm this happens under your dependencies.

I have tried:
```
"native-base": "^2.3.3",
"react": "16.0.0",
"react-native": "0.50.4"
```

```
"expo": "^23.0.0",
"native-base": "^2.3.3",
"react": "16.0.0",
"react-native": "https://github.com/expo/react-native/archive/sdk-23.0.0.tar.gz" // ~0.50.0
```

Both brand new projects produces the issue. Please do take a look on this. Thanks.

There is a marginLeft in ListItem. I suspect that's the problem.

**Comment by SupriyaKalghatgi** [comment]
@carsonwah Sharing screenshot of simulator with your snippet can help me to find the issue

**Comment by SupriyaKalghatgi** [comment]
@carsonwah `marginLeft` has been the design for ListItem
I can help you more if you share your snippet and screenshot of simulator

**Comment by carsonwah** [comment]
Sorry for the late response. I was working on other things. Here is the screenshot.

![simulator screen shot - iphone x - 2017-12-10 at 18 32 25](https://user-images.githubusercontent.com/25053707/33804120-2a12ced6-ddd9-11e7-81cf-639ec5a6807e.png)

My code:

```javascript
import React from 'react';
import { StyleSheet, Text, View } from 'react-native';
import { Container, Header, Content, List, ListItem, Body, Right, Icon } from 'native-base';

export default class App extends React.Component {
  render() {
    return (
      <Container>
        <Header />
        <Content>
          <List>
            <ListItem onPress={()=>{}}>
              <Text>Simon Mignolet</Text>
            </ListItem>
            <ListItem>
              <Text>Nathaniel Clyne</Text>
            </ListItem>
            <ListItem>
              <Text>Dejan Lovren</Text>
            </ListItem>
          </List>
        </Content>
      </Container>
    );
  }
}
```

```
"dependencies": {
    "expo": "^23.0.0",
    "native-base": "^2.3.3",
    "react": "16.0.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-23.0.0.tar.gz"
  }
```

Can confirm this happens also on standalone app.

**Comment by SupriyaKalghatgi** [comment]
@carsonwah Can you check for this implementation in NativeBase-KitchenSink?
https://github.com/GeekyAnts/NativeBase-KitchenSink/blob/master/js/components/button/index.js

Here is the output for shared link
![simulator screen shot - iphone 7 - 2017-12-11 at 11 27 41](https://user-images.githubusercontent.com/13464885/33817627-6dd34a78-de66-11e7-93f7-a2a498c261c2.png)

**Comment by carsonwah** [comment]
@SupriyaKalghatgi I have checked both simulator (react-native run-ios) and real device (expo). Both produce normal result. 

![img_0338](https://user-images.githubusercontent.com/25053707/33878870-a1e9e540-df67-11e7-9ebb-41b83bb2820b.PNG)

Actually the result is just the same as setting `<ListItem style={{backgroundColor: 'transparent'}}>` under the buggy scenario.

---

I have also modified package.json just the same as @gooddaddy 's. And it still works fine, while my self-setup project still doesn't. I can't find any clue by now.

KitchenSink (no bug)
```json
{
	"name": "NativebaseKitchenSink",
	"version": "2.3.1",
	"private": true,
	"devDependencies": {
		"jest": "20.0.4",
		"react-test-renderer": "16.0.0-alpha.12"
	},
	"scripts": {
		"start": "react-native start",
		"android": "react-native run-android",
		"ios": "react-native run-ios",
		"test": "node node_modules/jest/bin/jest.js --watch"
	},
	"jest": {
		"preset": "react-native",
		"transformIgnorePatterns": ["node_modules/(?!react-native|native-base-shoutem-theme)"]
	},
	"dependencies": {
		"color": "~1.0.3",
		"lodash": "^4.13.1",
		"native-base": "2.2.1",
		"react": "16.0.0-alpha.12",
		"react-native": "0.48.4",
		"react-navigation": "1.0.0-beta.11"
	}
}
```

My temp project (buggy)
```json
{
	"name": "temp",
	"version": "0.0.1",
	"private": true,
	"scripts": {
		"start": "node node_modules/react-native/local-cli/cli.js start",
		"test": "jest"
	},
	"dependencies": {
		"native-base": "^2.2.1",
		"react": "16.0.0-alpha.12",
		"react-native": "0.48.4",
		"react-navigation": "^1.0.0-beta.11"
	},
	"devDependencies": {
		"babel-jest": "21.2.0",
		"babel-preset-react-native": "4.0.0",
		"jest": "21.2.1",
		"react-test-renderer": "16.0.0"
	},
	"jest": {
		"preset": "react-native"
	}
}
```

---

I think the main point is that white backgroundColor for ListItem, which shows up when it's onPress.

![simulator screen shot - iphone 6 - 2017-12-12 at 18 47 49](https://user-images.githubusercontent.com/25053707/33880558-f9f4b3be-df6c-11e7-9f70-ffa5d6a03c13.png)

![simulator screen shot - iphone 6 - 2017-12-12 at 18 55 42](https://user-images.githubusercontent.com/25053707/33880908-193c605e-df6e-11e7-9cb4-aa9ec1aab7b7.png)

---

**Comment by SupriyaKalghatgi** [comment]
@carsonwah Try excluding `^` from dependencies
Clear and install `node_modules`

**Comment by carsonwah** [comment]
@SupriyaKalghatgi Can't believe I missed this.

I can identify that it appears starting exactly from 2.3.2. It works fine up to 2.3.1. So should be the same reason as @binhnd-socicom said.

```json
"dependencies": {
		"native-base": "2.3.2",
		"react": "16.0.0-alpha.12",
		"react-native": "0.48.4",
		"react-navigation": "^1.0.0-beta.11"
	},
```

**Comment by SupriyaKalghatgi** [comment]
@carsonwah Glad to know that you found the fix

**Comment by SupriyaKalghatgi** [comment]
#1378
