### ISSUE TITLE
tabs

### ISSUE THREAD

**Issue by ronnpang1** [GeekyAnts/NativeBase#125]
In using the nativebase tabs, i seem to be a getting a wierd error similar to this one: https://github.com/skv-headless/react-native-scrollable-tab-view/issues/4
Any help on this?

**Comment by th3no0b** [comment]
I fixed this problem by giving each tab content a set width.
Something like this
`
<Tabs>
    <View tabLabel="Demo Tab" style={{width: Dimensions.get('window').width}} />
    <View tabLabel="Demo Tab 2" style={{width: Dimensions.get('window').width}} />
</Tabs>
`

**Comment by sankhadeeproy007** [comment]
Not related to `NativeBase` let's wait for the solution from 
https://github.com/skv-headless/react-native-scrollable-tab-view/issues/4
