### ISSUE TITLE
Toast not working

### ISSUE THREAD

**Issue by deadcoder0904** [GeekyAnts/NativeBase#1250]
Please improve Toast. It is not working at all with the latest version of Expo. I've seen various issues in this repo with Toast. 

I did wrap the main component with `Root` & did exactly as mentioned in the documentation. It still doesn't work. Maybe the implementation of Toast is not accurate enough. 

That's the only component which is hard to work with. Rest of the NativeBase is awesome ❤️

I've gone ahead & implemented `ToastWithAndroid` from `react-native`. Thank you for your hard work [@GeekyAnts](https://github.com/GeekyAnts).

**Comment by akhil-geekyants** [comment]
@deadcoder0904 I checked Toast with expo version 21.0.0. It was working as expected. Can you give more information about this. 
Specifying versions and use cases will be helpful.

**Comment by deadcoder0904** [comment]
Me too 😂 

Here's my package.json 

```
"dependencies": {
    "expo": "^21.0.0",
    "moment": "^2.18.1",
    "moment-immutable": "^1.0.2",
    "native-base": "^2.3.2",
    "react": "16.0.0-alpha.12",
    "react-native": "https://github.com/expo/react-native/archive/sdk-21.0.2.tar.gz",
    "react-native-easy-grid": "^0.1.15",
    "react-navigation": "^1.0.0-beta.11"
  }
```

**Comment by deadcoder0904** [comment]
Whoops I totally forgot. I'll be specifying use-case in this week or so. Bit busy. So didn't got time. Feel free to close this.

**Comment by alexrussell** [comment]
FWIW it works fine for me in Expo 21 and 22 (other than a few minor glitches I have submitted PRs for).

**Comment by deadcoder0904** [comment]
Cool enough then, I'll close this one bcz I won't be using NativeBase for a month or so. I'll open it if I still have a issue.

**Comment by brentoneill** [comment]
Still having issues with this on `2.4.3`
