### ISSUE TITLE
Error updating property 'underlineColorAndroid' of a View managed by AndroidTextInput

### ISSUE THREAD

**Issue by NULLPointerGuy** [GeekyAnts/NativeBase#1251]
`<Item style={{flex:8}}>
               <Input placeholder="Mobile Number"
                onChangeText = { (text) => this.setState({ mobileNumber: text })}
                value={this.state.mobileNumber}
                onSubmitEditing = {this.getOtp.bind(this)}
                keyboardType = 'number-pad'
                returnKeyType = 'next'
                style = {{backgroundColor:'white'}}
                /> ` same component works fine in ios but in android it seems to be throwing the above error [please find the attached screenshot](https://github.com/NULLPointerGuy/ReactPhotos/blob/master/gifs/WhatsApp%20Image%202017-09-26%20at%2011.37.42%20AM.jpeg).

I have integrated the native base as per the docs, my versions are 
RN:0.44
NativeBase:^2.1.2
expo-vector-icons:^5.2.0

**Comment by NULLPointerGuy** [comment]
@akhil-geekyants  am i missing something here? please do let me know

**Comment by akhil-geekyants** [comment]
@NULLPointerGuy I tried your code with the versions specified. It was working fine on the android device.

**Comment by akhil-geekyants** [comment]
Closing this due to no response
