### ISSUE TITLE
Custom theme using StyleProvider do not change background color of Header component

### ISSUE THREAD

**Issue by romanglom** [GeekyAnts/NativeBase#1253]
## react-native, react and native-base version
    "native-base": "^2.3.2",
    "react": "16.0.0-alpha.12",
    "react-native": "^0.47.0",
## Expected behaviour
Background color of Header component should change.

## Actual behaviour
Header is using default theme from native-base node_modules directory instead of custom theme.
The rest of the components work fine.

## Steps to reproduce (code snippet or screenshot)

```javascript
import React from 'react';
import {StyleProvider, Container, Header, Body, Title, Content} from 'native-base';

import getTheme from '../../../native-base-theme/components';
import material from '../../../native-base-theme/variables/material';

class Screen extends React.Component {
    render() {
        return (
            <StyleProvider style={getTheme(material)}>
                <Container>
                    <Header>
                        <Body>
                        <Title>Title</Title>
                        </Body>
                    </Header>
                    <Content>
                    </Content>
                </Container>
            </StyleProvider>
        )
    }
}

export default Screen;

```

## Screenshot of emulator/device

![screen shot 2017-09-27 at 01 13 31](https://user-images.githubusercontent.com/4081791/30888510-2fe04052-a321-11e7-9fb0-5ec4c989aa46.png)

## Is the bug present in both ios and android or in any one of them?
Just check in Android

## Any other additional info which would help us debug the issue quicker.
The header is using the background color of theme js located inside node_modules/native-base instead of my own thene.

**Comment by akhil-geekyants** [comment]
@romanglom here you have specified material design as your theme `<StyleProvider style={getTheme(material)}>`. So you should change the `toolbarDefaultBg` value in `native-base-theme/variables/material.js` to change the header color.

**Comment by romanglom** [comment]
@akhil-geekyants  That's exactly what I did. Other elements seems to work with the modified styles, but the Header is still using the default color.

**Comment by akhil-geekyants** [comment]
@romanglom couldn't reproduce the issue. Attaching a gif image.
![header](https://user-images.githubusercontent.com/27768184/31002520-d107ab58-a508-11e7-8e52-5468675eceaf.gif)

**Comment by romanglom** [comment]
@akhil-geekyants Thanks for trying to reproduce it. 
So I'm not sure what the problem is, but surely It's not a a bug from native-base then.

**Comment by astrocket** [comment]
same here, Header customizing does not work

**Comment by astrocket** [comment]
though it's a dirty fix, Mine works if I add either options like searchBar, rounded ...

**Comment by SamakaCD** [comment]
Seems like component will not themed if it doesn't have any properties.
