### ISSUE TITLE
Tab bar causing flickering while scrolling 

### ISSUE THREAD

**Issue by IslamTareq0012** [GeekyAnts/NativeBase#1254]
While using tab bar to switch between screens that views items to scroll , screen starts to flicker rapidly.

**Comment by suvenduchhatoi** [comment]
@IslamTareq0012 
Check for your compatibility versions between "react-native" and "native-base" and upgrade them to latest formats...The scrollable Tab bar seems to work fine if you take example from NB docs...
![screenshot 2018-12-24 at 12 44 34 pm](https://user-images.githubusercontent.com/44160581/50393106-ea02cc80-0779-11e9-81b6-3f71f60f0074.png)
And share screenshots of your code in the ISSUE_TEMPLATE format
