### ISSUE TITLE
How to remove ripples on Android?

### ISSUE THREAD

**Issue by boringer** [GeekyAnts/NativeBase#1256]
## react-native, react and native-base version

react-native: 0.48
react: 16.0.0-alpha.12
native-base: 2.3.2

## Expected behaviour

Remove ripples anywhere on Android.

## Actual behaviour

Still exist.

## Steps to reproduce (code snippet or screenshot)

Wrap my root element with `<StyleProvider style={getTheme(commonColor)}>`, change `androidRipple` in `native-base-theme/variables/commonColor.js` to `false`.

**Comment by shivrajkumar** [comment]
@boringer Fixed in version 2.3.3
