### ISSUE TITLE
Center the Button Vertically using flex

### ISSUE THREAD

**Issue by Naveen-ICARUS** [GeekyAnts/NativeBase#1258]
Hi,

How to Vertically center the Native Base Button inside View Compoent. I tried alignItems : 'center', but its not working. 

## react-native, react and native-base version

react-native: 0.47.1
react: 16.0.0-alpha.12
native-base: 2.3.1

## Expected behaviour
Center the button Vertically inside the View

## Actual behaviour

![cloud q11_20170928_182022](https://user-images.githubusercontent.com/31643287/30967543-4303433c-a47a-11e7-843b-f3afcbabdcf4.png)

## Steps to reproduce (code snippet or screenshot)

this is my code snippet

![image](https://user-images.githubusercontent.com/31643287/30967922-4253a188-a47b-11e7-98a2-e594ac92e91a.png)

## Is the bug present in both ios and android or in any one of them?
I don't know about IOS, I'm currently working on Android

Thanks in advance

**Comment by akhil-geekyants** [comment]
@Naveen-ICARUS try adding `alignSelf:'center'` to button style `networkStyle.connectionBtn:{}`
