### ISSUE TITLE
Picker background color

### ISSUE THREAD

**Issue by omgo** [GeekyAnts/NativeBase#1259]
hello, is it possible to change background color of list in Picker?

![image](https://user-images.githubusercontent.com/13779291/31005722-1966b86a-a524-11e7-9857-b00f55c03aec.png)

I need to set all background to dark, but list has white color

nativebase 2.3.1, iOS

**Comment by akhil-geekyants** [comment]
you can set the picker item color using itemStyle props of `<Picker>` and you can set the picker item text color using itemTextStyle props of `<Picker>` 
```
<Picker
  itemStyle = {{ ... }}
  itemTextStyle = {{ ... }}
  ...
>
```

**Comment by omgo** [comment]
I meant background color. How you can see at the screenshot itemStyle already has background: black. Actually there is no way how to do it, so I forked nativeBase and added that possibility
https://github.com/omgo/NativeBase/commit/77a8b8bf59c00bc01055d4adda2c24fc474f3603

**Comment by kit494way** [comment]
You can customize theme by following https://docs.nativebase.io/Customize.html#Customize .
To change background color of Picker,
1. execute `node node_modules/native-base/ejectTheme.js`
2. change native-base-theme/components/index.js
```diff
diff --git a/native-base-theme/components/index.js b/native-base-theme/components/index.js
index 25e9805..0b236a2 100644
--- a/native-base-theme/components/index.js
+++ b/native-base-theme/components/index.js
@@ -172,6 +172,9 @@ export default (variables = variable) => {
     },

     "NativeBase.PickerNB": {
+      "NativeBase.Container": {
+        backgroundColor: '#000',
+      },
       "NativeBase.Button": {
         "NativeBase.Text": {}
       }

```

**Comment by akhil-geekyants** [comment]
closing the issue due to inactivity

**Comment by appukuttan-shailesh** [comment]
The following worked for me: see https://github.com/GeekyAnts/NativeBase/issues/3110#issuecomment-641498927

**Comment by cichun** [comment]
For those who still face the problem - try using _modalStyle_ property, like this
```
<Picker
                    modalStyle={{backgroundColor:'gray'}}
                    itemStyle={{
                        backgroundColor: 'lightgray',
                        marginLeft: 0
                    }}
                    itemTextStyle={{backgroundColor: 'lightgray'}}>
....
</Picker>
```

should look like this:
![image](https://user-images.githubusercontent.com/7638234/106108383-75fd3480-6148-11eb-9d83-31d689c9a28e.png)
