### ISSUE TITLE
Icon in header causes error

### ISSUE THREAD

**Issue by PascalLeMerrer** [GeekyAnts/NativeBase#126]
In my app the following lines cause an error:
``` html
<Header>
    <Icon name="md-arrow-back"/>
   <Title>Hello</Title>
</Header>
```
It displays **undefined is no an object (evaluating 'element.props')**

When I remove one of the items in the header (either the icon or the title), it works. It's only with both of them the error occurs.

I solved this by adding a button around the Icon:

```
<Header>
        <Button>
            <Icon name="md-arrow-back" />
        <Button>
        <Title>Hello</Title>
</Header>
```

**Comment by sankhadeeproy007** [comment]
We've followed the Apple and Google guidelines for the header component. Most of the icons there were nested inside buttons so we didn't think breaking the pattern would be a good idea. If you however want your custom component, please use a <View /> inside the header and then customize it.

**Comment by PascalLeMerrer** [comment]
It did not undertand that when reading the documentation.
In the "anatomy section", you wrote:
```
<Header> 	- 	- 	Renders as Header (navbar) of your screen.
Input values: Text, Button, Icon. read more 
```
What do you mean by "input values"?

**Comment by sankhadeeproy007** [comment]
Thanks for pointing it out. That was the case for the previous versions when we had one common view for iOS and android. Will fix it ASAP.
