### ISSUE TITLE
FooterTab circle button in center

### ISSUE THREAD

**Issue by almaezafra** [GeekyAnts/NativeBase#1260]
Hi NativeBase

Is this possible to be created in FooterTab?  

![image](https://user-images.githubusercontent.com/13870208/31008111-75cd2132-a535-11e7-86ed-9b7fbd7a5ecf.png)

Thanks!

**Comment by akhil-geekyants** [comment]
@almaezafra yes. Attaching a similar screen created with NativeBase.
![home](https://user-images.githubusercontent.com/27768184/31010823-cb94d7ec-a529-11e7-881e-39e9c83b2bc2.png)

**Comment by almaezafra** [comment]
Hi thanks for the quick response. Attached is what i code based on your reply and a screenshot of the output. 
`   <Container>
        <Header />
        <Content style={{backgroundColor:'white'}}  />
        <Footer >
        <FooterTab style={{backgroundColor:'#f5f5f5'}}>
          <Button style={{}} >
            <Icon name="apps" style={{color:'darkgrey'}} />
          </Button>
          <Button >
            <Icon name="camera"  style={{color:'darkgrey'}} />
          </Button>    
          <Button onPress={this._onHomePress} style={{height: 70,width: 70,bottom: 8,borderWidth:1,borderColor:'lightgrey',borderRadius:35,backgroundColor:'#f5f5f5'}} active>
            <Icon active name="add" style={{color:'darkgrey'}}/>
          </Button>
          <Button>
            <Icon name="camera"  style={{color:'darkgrey'}} />
          </Button>
          <Button >
            <Icon name="person"  style={{color:'darkgrey'}} />
          </Button>
        </FooterTab>
      </Footer>
      </Container>`

![image](https://user-images.githubusercontent.com/13870208/31040264-a2df4696-a5b7-11e7-99ac-368f6ea633b6.png)

**Comment by almaezafra** [comment]
Ill be waiting for the fix of this thanks!

**Comment by almaezafra** [comment]
@akhil-geekyants waiting for the fix, by the way im creating it in android.

**Comment by Chaimae123** [comment]
Did you find a solution ? I am facing the same problem ! it works fine on iOS but doesn't show the whole button on android !! Thanks

**Comment by akhil-geekyants** [comment]
For Android, use absolute positioning and set elevation greater than 2 to set a circular button in the bottom center.

![screenshot_1515590439](https://user-images.githubusercontent.com/27768184/34774897-34dbbb40-f637-11e7-82a2-40f7ddc5d2c7.png)

**Comment by itcurves** [comment]
Hello,

I am still struggling with round center icon.

![image](https://user-images.githubusercontent.com/1397397/36356269-d5ce46c2-14bd-11e8-86c8-9f410ea32939.png)

this is my style:

homeicon: {
       height: 70,
        width: 70,
        bottom: 8,
        borderWidth: 2,
        borderColor: 'lightgrey',
        borderRadius: 35,
        backgroundColor: '#009bc9',
        position: 'absolute',
        left: 0,
        bottom: 0,
        right: 0,
        elevation: 8, 
    },

what I am missing or doing wrong?

**Comment by akhil-geekyants** [comment]
@itcurves for android try something similar to this.

Code

```
import React, { Component } from 'react';
import { Container, Header, Content, Footer, FooterTab, Button, Icon, Text } from 'native-base';
export default class FooterTabsExample extends Component {
  render() {
    return (
      <Container>
        <Header />
        <Content />
        <Button onPress={() => { }}
          style={{ alignSelf: 'center', position: 'absolute', elevation: 4, height: 70, width: 70, bottom: 0, borderWidth: 1, borderColor: 'lightgrey', borderRadius: 35, backgroundColor: '#f5f5f5', justifyContent: 'center' }} active>
          <Icon active name="add" style={{ color: 'darkgrey' }} />
        </Button>
        <Footer>
          <FooterTab>
            <Button>
              <Icon name="apps" />
            </Button>
            <Button>
              <Icon name="camera" />
            </Button>
            <Button style={{ flex: 0, width: 70 }}>
              <Icon active name="navigate" />
            </Button>
            <Button>
              <Icon name="camera" />
            </Button>
            <Button>
              <Icon name="person" />
            </Button>
          </FooterTab>
        </Footer>
      </Container >
    );
  }
}
```

Gif

![footerbutton](https://user-images.githubusercontent.com/27768184/36660431-1fc766fa-1afe-11e8-80bd-02587c513758.gif)

**Comment by brendonhc** [comment]
> @itcurves for android try something like this.
> 
> Code
> 
> ```
> import React, { Component } from 'react';
> import { Container, Header, Content, Footer, FooterTab, Button, Icon, Text } from 'native-base';
> export default class FooterTabsExample extends Component {
>   render() {
>     return (
>       <Container>
>         <Header />
>         <Content />
>         <Button onPress={() => { }}
>           style={{ alignSelf: 'center', position: 'absolute', elevation: 4, height: 70, width: 70, bottom: 0, borderWidth: 1, borderColor: 'lightgrey', borderRadius: 35, backgroundColor: '#f5f5f5', justifyContent: 'center' }} active>
>           <Icon active name="add" style={{ color: 'darkgrey' }} />
>         </Button>
>         <Footer>
>           <FooterTab>
>             <Button>
>               <Icon name="apps" />
>             </Button>
>             <Button>
>               <Icon name="camera" />
>             </Button>
>             <Button style={{ flex: 0, width: 70 }}>
>               <Icon active name="navigate" />
>             </Button>
>             <Button>
>               <Icon name="camera" />
>             </Button>
>             <Button>
>               <Icon name="person" />
>             </Button>
>           </FooterTab>
>         </Footer>
>       </Container >
>     );
>   }
> }
> ```
> 
> Gif
> 
> ![footerbutton](https://user-images.githubusercontent.com/27768184/36660431-1fc766fa-1afe-11e8-80bd-02587c513758.gif)

Great, it's beautiful on android! But I can't press the circle button below the footer line, below the line I always press the "navigation" button.

**Comment by melvinzoi** [comment]
<Button
                     onPress={() => this.props.navigation.navigate("Inverstment")}
                    >
                        <View style={{flex:0,alignItems:'center',justifyContent:'center',  height:50,width:50,bottom:15,borderRadius:25, backgroundColor:Colors.primary,elevation:5}}>
                            <Text style={{ fontSize: 25,color:Colors.noticeText}}>PB</Text>
                        </View>
                        <Text numberOfLines={2} ellipsizeMode='tail' style={[styles.text,{bottom:12},  this.props.navigation.state.index === 10 ? { color: Colors.primary } : { color: Colors.TextColor }]}>My Account</Text>
                    </Button>

**Comment by Mukthayar1** [comment]
Thans for help
