### ISSUE TITLE
How to use `TouchableHighlight` instead of `TouchableOpacity`?

### ISSUE THREAD

**Issue by boringer** [GeekyAnts/NativeBase#1262]
Sorry for not using issue template.

I read source code, find many components wrapped with `TouchableOpacity`, but that's not what I need at most time.

**Comment by akhil-geekyants** [comment]
@boringer you can simply wrap the component inside `<TouchableHighlight/>`.  For Buttons, add the disabled props in `<Button/>`.  You can also override the button style by [ejecting the theme](http://docs.nativebase.io/Customize.html#Customize) and changing the `btnDisabledBg` in the `native-base-theme/variables/platform/material/commonColors.js`

**Comment by boringer** [comment]
@akhil-geekyants 
But in this way, I have to style my `TouchableHighlight` and make it looks like the original `Button`.

Could Native Base provide a new prop to allow me to custom the wrapper element? Such as `<Button wrapper={TouchableHighlight}>` or something.

Or did I misunderstand something?

**Comment by boringer** [comment]
I've solved this temporarily, by inserting a full-size `View` with black background into `Button` (before children), passing `onPressIn/Out` to toggle its opacity.
