### ISSUE TITLE
Toast Not works 

### ISSUE THREAD

**Issue by jpca999** [GeekyAnts/NativeBase#1267]
![image](https://user-images.githubusercontent.com/1026325/31099558-68eebf8c-a794-11e7-8d04-197c8c084063.png)

import React from 'react';
import { Component } from 'react';
import { StyleSheet, Text, View } from 'react-native';

import { Container, Header, Content, Toast, Button, Icon } from 'native-base';

export default class App  extends Component {

 constructor(props) {
    super(props);
    this.state = {
      showToast: false
    }
  }
  render() {
    return (
      <Container>
        <Header />
        <Content padder>
          <Button onPress={()=> Toast.show({
              text: 'Wrong password!',
              position: 'bottom',
              buttonText: 'Okay'
            })}>
            <Text>Toast</Text>
          </Button>
        </Content>
      </Container>
    );
  }
}

package.json 

{
  "name": "toaster-native-library",
  "version": "0.0.0",
  "description": "Hello Expo!",
  "author": null,
  "private": true,
  "main": "node_modules/expo/AppEntry.js",
  "dependencies": {
    "expo": "^21.0.0",
    "native-base": "^2.3.2",
    "react": "16.0.0-alpha.12",
    "react-native": "https://github.com/expo/react-native/archive/sdk-21.0.2.tar.gz"
  }
}

**Comment by akhil-geekyants** [comment]
For Toast to work, you need to wrap your topmost component inside `<Root>` from native-base. You can refer [NativeBase docs](http://docs.nativebase.io/Components.html#Toast)

**Comment by akhil-geekyants** [comment]
closing the issue due to no response
