### ISSUE TITLE
Tap on icon has no effect

### ISSUE THREAD

**Issue by PascalLeMerrer** [GeekyAnts/NativeBase#127]
When I try to detect a tap on an icon nested into a button, I sometimes have to tap two or three times for the event to be taken in account:

```
<Button info>
    <Icon name="md-arrow-back" onPress={()=>this.back()} />
</Button>
```

It seems to work better when the event listener is declared at the button level:

```
<Button info onPress={()=>this.back()}>
    <Icon name="md-arrow-back" />
</Button>
```

**Comment by sankhadeeproy007** [comment]
Why would you have your onPress listener on an Icon if you already have a button?

**Comment by PascalLeMerrer** [comment]
At first, I did not have a button (just the icon), and the onPress event worked most of the time.

**Comment by sankhadeeproy007** [comment]
We've revised the anatomy a bit with the latest updates.
