### ISSUE TITLE
Card Item on Press, too fast, multiple pages

### ISSUE THREAD

**Issue by rainbowhat** [GeekyAnts/NativeBase#1271]
```
<CardItem button onPress={function_call()}>
                            <Thumbnail source={require('./img/NSP.png')} />
                            <Text>Native Starter Pro</Text>
                        </CardItem>

```
If i spam press the item, it will load multiple pages/screen (duplicates) anyway to prevent this ?

**Comment by shivrajkumar** [comment]
@rainbowhat It is not NativeBase related issue.
Check https://github.com/react-community/react-navigation/issues/271
