### ISSUE TITLE
Sortable ListView

### ISSUE THREAD

**Issue by appjitsu** [GeekyAnts/NativeBase#1275]
![screen shot 2017-10-04 at 8 06 01 am](https://user-images.githubusercontent.com/10903600/31177214-e6645d9a-a8da-11e7-9cd5-63f56150d803.png)

Is there support for a drag/drop sortable of some sort? I'd like to only enable drag/drop when the handle on the right is long-pressed.

**Comment by akhil-geekyants** [comment]
@appjitsu The feature of drag and drop is not available for `List` in NativeBase

**Comment by appjitsu** [comment]
Then I’ll recommend a feature request.

**Comment by virus2016** [comment]
+1

**Comment by SupriyaKalghatgi** [comment]
Closing this, as NativeBase wont be adding this
