### ISSUE TITLE
Nativebase and Expo accelerometer causes screen tap to lag

### ISSUE THREAD

**Issue by whattheken** [GeekyAnts/NativeBase#1277]
## react-native, react and native-base version
react 16.0.0-alpha.12
react native 0.48
native-base 2.3.2
expo 21.0.0

Also using react-navigation with redux.

## Expected behaviour
When using NativeBase with Expo's Accelerometer, expect lag-free operation on device.

## Actual behaviour
App is unresponsive to screen taps.

## Steps to reproduce (code snippet or screenshot)

Using the guide for Expo's Accelerometer here: https://docs.expo.io/versions/latest/sdk/accelerometer.html

```
<StyleProvider style={getTheme()}>
  <Container>
    <Header>
      <Left>
        <Button
          transparent
          onPress={() => this.props.navigation.navigate('DrawerOpen')}>
          <Icon name="menu" />
        </Button>
      </Left>
      <Body>
        <Title>Home</Title>
      </Body>
      <Right />
    </Header>
    <Content>
      <Text>
        NEW Accel data:
        x = { this.state.accelData.x.toFixed(3)}{', '}
        y = { this.state.accelData.y.toFixed(3)}{', '}
        z = { this.state.accelData.z.toFixed(3)}
      </Text>
    </Content>
    <Footer>
      <Button onPress={() => this.props.navigation.navigate('SecondScreen')}>
        <Text>Button</Text>
      </Button>
    </Footer>
  </Container>
</StyleProvider>
```

Adding Header and Content seem to introduce slight lag. Adding Footer introduces more lag. Adding StyleProvider makes the app mostly unresponsive to finger taps. Both the menu drawer and button in the example above are unresponsive, maybe responding once out of 10 taps. Android's back button is also unresponsive. Strangely, slide to open gesture on menu drawer still works fine. Changing the Expo Accelerometer update interval seems to have some impact, but even polling only 10 times per second causes extreme unresponsiveness when combined with NativeBase components StyleProvider, Footer, Header, and Content.

## Is the bug present in both ios and android or in any one of them?
Seems to only occur on Android.

**Comment by akhil-geekyants** [comment]
@whattheken tried your code. It was working fine for me. Attaching a gif. The buttons were responding when clicked. 
![accelerometer](https://user-images.githubusercontent.com/27768184/31445203-3ad07888-aebb-11e7-9e4d-2bea7973bc41.gif)

**Comment by whattheken** [comment]
@akhil-geekyants Strange, I still have the same issue. I tried creating a brand new expo project, added, redux, saga, and I have the same results of laggy button presses.

Here's what the code looks like for the screen:

```
import React from 'react';
import { StyleSheet, View, Dimensions } from 'react-native';
import { StyleProvider, Container, Content, Body, Header, Left, Button, Icon, Title, Right, Text, Footer } from 'native-base';
import { connect } from 'react-redux';
import PropTypes from 'prop-types';
import { Accelerometer } from 'expo';

import GenericActions from '../redux/actions/GenericActions';

class HomeScreen extends React.Component {
  static propTypes = {
  }

  static navigationOptions = {
    drawerLabel: 'Home',
  };

  constructor(props) {
    super(props);

    this.state = {
      accelerometerData: { x: 0, y: 0, z: 0 },
    };

  }

  componentDidMount() {
    this.subscription = Accelerometer.addListener((accelerometerData) => {
      this.setState({ accelerometerData });
    });
  }

  componentWillUnmount() {
    this.subscription && this.subscription.remove();
    this.subscription = null;
  }

  render() {
    return (
      <Container>
        <Header>
          <Left>
            <Button
              transparent
              onPress={() => this.props.navigation.navigate('DrawerOpen')}>
              <Icon name="menu" />
            </Button>
          </Left>
          <Body>
            <Title>Home</Title>
          </Body>
          <Right />
        </Header>
        <Content>
          <Text>
            Accel data:
            x = { this.state.accelerometerData.x.toFixed(2) }{', '}
            y = { this.state.accelerometerData.y.toFixed(2) }{', '}
            z = { this.state.accelerometerData.z.toFixed(2) }
          </Text>
        </Content>
        <Footer>
          <Button onPress={() => alert('Button Pressed')}>
            <Text>Button</Text>
          </Button>
        </Footer>
      </Container>
    );
  }
}

//const window = Dimensions.get('window');

const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
});

const mapStateToProps = (state) => {
  return {
  };
};

const mapDispatchToProps = (dispatch) => {
  return {
  };
};

export default connect(mapStateToProps, mapDispatchToProps)(HomeScreen);
```

Not sure if this has to do with the devices that I'm using. This behavior only seems to occur on Android. This has happened on a Motorola G3 running android 6, and a HTC A9 running android 7.

If I remove the native base components and use react native's view, text, and button, then there is no lag at all.
