### ISSUE TITLE
The Grid row layout does not show content properly

### ISSUE THREAD

**Issue by thechamp** [GeekyAnts/NativeBase#128]
Neither the screen has been divided in 4:1 horizontally nor the content is shown properly. See the screenshot of code and result on android simulator attached.

<img width="1055" alt="screen shot 2016-08-21 at 8 04 57 pm" src="https://cloud.githubusercontent.com/assets/2319535/17837814/d918a3d6-67da-11e6-9ffb-39f770a02f89.png">

**Comment by sankhadeeproy007** [comment]
Not related to `native-base`. Raise an issue in https://github.com/GeekyAnts/react-native-easy-grid

**Comment by sankhadeeproy007** [comment]
Keeping this open as it might have something to do with the `Content` component.

**Comment by sankhadeeproy007** [comment]
https://github.com/GeekyAnts/react-native-easy-grid/issues/8
