### ISSUE TITLE
Android back button

### ISSUE THREAD

**Issue by maartenvandillen** [GeekyAnts/NativeBase#1280]
Hi I would like to know how the Android back button is supposed to behave. I have specified a custom Header component in the static navigationOptions of my component and noticed that there is no automatic back behaviour. So I created my own buttons, rendering either the menu button or a back button in the Header.Left component. This works, but now the Android back button still needs to behave the same. Currently it just exits the app, but it needs to do a navigation.goBack call. Any thoughts on this?

**Comment by akhil-geekyants** [comment]
@maartenvandillen you can check the [Native base Kitchen sink app](https://github.com/GeekyAnts/NativeBase-KitchenSink)
