### ISSUE TITLE
Hi, i need to change tab dynamically in my app. how can i do that?

### ISSUE THREAD

**Issue by Minaghorbaani** [GeekyAnts/NativeBase#1285]
Hi! Thanks for trying out NativeBase!
Due to the overwhelming requests and issues/questions we ask you to add the following details with your issue.

Please check the existing open/closed issues for a possible duplicate before creating a new issue :)

Also **DO** fill out the below form to give us a better idea about your environment and help us debug it quicker. Issues without the required details will mostly be unattended to.

**Comment by akhil-geekyants** [comment]
@Minaghorbaani you can use `initialPage` props of the `<Tabs/>`. You can refer the [NativeBase docs for Tabs here](http://docs.nativebase.io/Components.html#tabs-def-headref)

**Comment by akhil-geekyants** [comment]
closing the issue due to no response
