### ISSUE TITLE
Multi-slider for Native Base

### ISSUE THREAD

**Issue by mjohns39** [GeekyAnts/NativeBase#1286]
Hi!  

Not sure if this has been suggested yet, but I think a multi-slider would be a good addition to this framework.  I saw that Sliders were on the Roadmap, I just thought I would throw this in as well?

I can try to code up something for a pull request if this hasn't been accounted for already? :)

**Comment by SupriyaKalghatgi** [comment]
@mjohns39 PR would be of help!

**Comment by SupriyaKalghatgi** [comment]
@mjohns39 Any updates on PR?

**Comment by SupriyaKalghatgi** [comment]
#38
