### ISSUE TITLE
Controlled hiding of Toasts

### ISSUE THREAD

**Issue by LonelyGriffin** [GeekyAnts/NativeBase#1287]
Hi guys! I want to hide all Toasts by my action or other event. 
For example:
```javascript
const toastId = Toast.show(config);
Toast.hide(toastId)

// or

Toast.hideAll();
```
Is it possible?

**Comment by akhil-geekyants** [comment]
@LonelyGriffin currently NativeBase does not support this. Will raise a feature request.

**Comment by alexrussell** [comment]
This kinda thing would be useful. FWIW the "hide all" should be as simple as adding the following code to `ToastContainer`:

```
static show() {
	this.toastInstance._root.cloaseToast();
}
```

However, the large idea of being able to have multiple toasts (and being able to refer to each) is something I'm interested in in general.

**Comment by alexrussell** [comment]
(Just seen your PR adding the hide method done exactly the way I describe. D'oh.)

**Comment by SupriyaKalghatgi** [comment]
@alexrussell @LonelyGriffin Could you please share the PR link

**Comment by SupriyaKalghatgi** [comment]
Found it
#1304

**Comment by SupriyaKalghatgi** [comment]
@LonelyGriffin Having multiple Toast popping up for a single screen, this is something inappropriate as per design guidelines / use-case 
Hence rejecting your request and PR same

**Comment by remon-georgy** [comment]
@SupriyaKalghatgi having multiple toasts simultaneously _might_ not be best UX. However, I don't see why can't we still enable hiding the single toast using `hide()` method?

Implementation provided by @LonelyGriffin is quite appropriate and in fact, it's cleaning NB Toast implementation a bit.

I'd suggest giving this PR another chance since it was closed abruptly.

**Comment by SupriyaKalghatgi** [comment]
Added with [2.7.2](https://github.com/GeekyAnts/NativeBase/releases/tag/v2.7.2)

**Comment by gianpaj** [comment]
This function should be added to the documentation. And specified how it's intended to work. Because it doesn't work as expected for me.

I also don't see tests for hiding a Toast or, for example, showing one, hiding, showing a 2nd; which is what I'm trying to do.

**Comment by SupriyaKalghatgi** [comment]
https://github.com/GeekyAnts/native-base-docs/issues/131

**Comment by suvenduchhatoi** [comment]
hide(), show() have been added to config table of Toast in latest docs versions...
