### ISSUE TITLE
Vector icons deps

### ISSUE THREAD

**Issue by alexrussell** [GeekyAnts/NativeBase#1288]
With the current latest master branch, the `package.json` file looks a bit odd.

In the [`dependencies` section](https://github.com/GeekyAnts/NativeBase/blob/master/package.json#L46) you specifically include `react-native-vector-icons@~4.1.1` and then in the [`peerDependencies` section](https://github.com/GeekyAnts/NativeBase/blob/master/package.json#L76) you require a peer of `react-native-vector-icons@~4.3.0`.

It would seem odd to have these versions mismatched and, more importantly, bundle it but also require the same package as a peer dep (albeit a different version). Maybe I just don't get peer deps properly.

**Comment by akhil-geekyants** [comment]
Fixed in the latest release (& master branch)
