### ISSUE TITLE
deckswiper flickering on IOS

### ISSUE THREAD

**Issue by flieks** [GeekyAnts/NativeBase#1289]
setup: 
react 16.0.0-alpha.12
react-native https://github.com/expo/react-native/archive/sdk-19.0.0.tar.gz
native-base ^2.3.2
testflight IOS (ios 10 & 11)

it's working fine for android but with ios i get this flickering.
look at my screencast:
https://1drv.ms/v/s!Apmrgc3Vf4c7g7Y9OIeVOstVU_kQPw

these seem related:
https://github.com/GeekyAnts/NativeBase/issues/826
https://github.com/GeekyAnts/NativeBase/issues/334
https://github.com/GeekyAnts/NativeBase/issues/866

Greetings
Felix

**Comment by SupriyaKalghatgi** [comment]
[#826](https://github.com/GeekyAnts/NativeBase/issues/826)

**Comment by flieks** [comment]
@SupriyaKalghatgi Did you find a solution or have any suggestions ?

**Comment by SupriyaKalghatgi** [comment]
@flieks Please refer #826 for updates

**Comment by flieks** [comment]
@SupriyaKalghatgi thanks but that topic 826 is still open
I'm not using any "Animated" on the deckswiper. Just using it with the basic functionality
