### ISSUE TITLE
ListView with section headers not scrolling from bottom

### ISSUE THREAD

**Issue by gazgeek** [GeekyAnts/NativeBase#1292]
Hi,

I've noticed that my sectioned List doesn't scroll when swiping up from the last row in the list (item 13 and most of item 12 in the screenshot below). When I remove the renderSectionHeader property then it works fine.

## react-native, react and native-base version
"native-base": "^2.3.2",
"react": "16.0.0-alpha.12",
"react-native": "^0.48.4"

## Expected behaviour
I'd expect the list to scroll when you swipe up to scroll down from the bottom (by touching item 13 and most of item 12 in the screenshot below)

## Actual behaviour
The list doesn't scroll when you touch from the last row or most of the second to last row

## Steps to reproduce (code snippet or screenshot)
```
import React from 'react';
import { StyleSheet, Text, View } from 'react-native';
import {ListView} from "react-native";
import {Body, List, ListItem, Separator} from "native-base";

const dataSource = new ListView.DataSource({
    rowHasChanged: (r1, r2) => r1 !== r2,
    sectionHeaderHasChanged : (s1, s2) => s1 !== s2
});

const dataBlob = {
  "List1": [{'id': '1'}, {'id': '2'}, {'id': '3'}, {'id': '3'}, {'id': '4'}, {'id': '5'}, {'id': '6'}],
  "List2": [{'id': '7'}, {'id': '8'}, {'id': '9'}, {'id': '10'}, {'id': '11'}, {'id': '12'}, {'id': '13'},
      {'id': '14'}, {'id': '15'}, {'id': '16'}, {'id': '17'}, {'id': '18'}, {'id': '19'}, {'id': '20'}, {'id': '21'}]
};

export default class App extends React.Component {
  render() {
    const listData = dataSource.cloneWithRowsAndSections(
        dataBlob,
        Object.keys(dataBlob)
    );

    return (
        <View>
            <List
                dataSource={listData}
                renderSectionHeader={(sectionData, sectionId) => <Separator bordered><Text>{sectionId}</Text></Separator>}
                renderRow={(item) =>
                    <ListItem key={item.id}>
                        <Body>
                            <Text>{`item ${item.id}`}</Text>
                        </Body>
                    </ListItem>}
                renderLeftHiddenRow={item => null}
                renderRightHiddenRow={(item) => null}
            />
        </View>
    );
  }
}
```

## Is the bug present in both ios and android or in any one of them?
both

## Screenshot of emulator/device
<img width="452" alt="screen shot 2017-10-10 at 08 59 55" src="https://user-images.githubusercontent.com/1638111/31375465-90be1ed0-ad99-11e7-8319-c8feeec2d7eb.png">

## Any other additional info which would help us debug the issue quicker.
if you comment out the line "renderSectionHeader" then the list scrolls as expected

Any ideas?

**Comment by akhil-geekyants** [comment]
@gazgeek I tried to reproduce issue with your code. But was behaving as expected. Attaching a gif 
![sectionheaderissue](https://user-images.githubusercontent.com/27768184/31434227-6447f12c-ae99-11e7-99cd-4b903618b7c0.gif)

**Comment by akhil-geekyants** [comment]
@gazgeek attaching a gif 
![section headerissue](https://user-images.githubusercontent.com/27768184/31440672-59741d74-aeae-11e7-9ad9-aa2cd387036f.gif)
we use LICEcap to create a gif

**Comment by gazgeek** [comment]
Thanks for trying to reproduce this. I've attached a gif that shows what I see. 
The problem is actually much worse in my app but I have headers, tabs and footer etc. 
I tried to create this as a minimal example of the problem.
Do you know why my iphone X simulator appears to have a top and bottom border and your doesn't?

![list](https://user-images.githubusercontent.com/1638111/31442916-d0b2ed62-ae8f-11e7-8f8c-fb06e2be3cb2.gif)

**Comment by akhil-geekyants** [comment]
@gazgeek iPhoneX is having a Safe area. Probably the touch outside this area may not be detected. See [iPhoneX developer guidelines](https://developer.apple.com/ios/human-interface-guidelines/overview/iphone-x/)

**Comment by SeuZeRicardo** [comment]
I have a problem similar to yours.

`React-Native: 0.41
React: 15.4.2
Native-Base: 2.1.3`
and testing on `Android 7,0`

And l looking for your code and it´s same "estruture" of mine.
My Last Item doesn´t show on my screen, only a little part of the item, so i put a ScrollView on my List and solved this problem.

`  render() {
    return (
      <Container style={{ backgroundColor: '#363a40' }}>        
        <CardItem style={{ backgroundColor: '#363a3f' }}>
          <View style={{ flex: 1 }}>
            <Item style={{ marginHorizontal: 0 }}>
              <Input
                placeholder="Procurar pelo nome da atração..."
                placeholderTextColor="rgb(164, 166, 170)"
                style={{ color: '#fff', height: 44, flex: 1 }}
                onChangeText={this.onSearchChange.bind(this)}
              />
            </Item>
          </View>
        </CardItem>
        {!this.props.attractions.isFetching ? (
          <ScrollView>
            <View>
              <List
                dataArray={this.state.list}
                renderRow={this._renderRow.bind(this)}
                onEndReachedThreshold={200}
                onEndReached={this._retrieveNextPage.bind(this)}
              />
            </View>
          </ScrollView>
        ) : (
          <Content showsVerticalScrollIndicator={false} style={{ marginBottom: Platform.OS === 'ios' ? -50 : -10 }}>
            <View>
              <ActivityIndicator animating={this.props.attractions.isFetching} style={{ height: 80 }} size="large" />
            </View>
          </Content>
        )}
      </Container>
    );
  }
}`

![demo1](https://user-images.githubusercontent.com/12394495/34836558-61539d7a-f6df-11e7-96d4-66b99aeec11d.gif)

**Comment by frmrgr** [comment]
@gazgeek Did you find out why this was happening and how to solve it in the end?
