### ISSUE TITLE
How to close Swipeable list row manually

### ISSUE THREAD

**Issue by manjeets12** [GeekyAnts/NativeBase#1293]
1. row is opened by swiping right or left 
2. now want to close it back by clicking on a button outside of list, how should I achieve this.
3. In react-native-swipeout , they are checking it on rowId and sectionid and provided a autoclose property for that.

-one more thing listview seems pretty slow aren't you planning to update this component with Flatlist

**Comment by akhil-geekyants** [comment]
@manjeets12 you can use 
```
rowMap[`${secId}${rowId}`].props.closeRow();`

**Comment by akhil-geekyants** [comment]
closing the issue due to no response
