### ISSUE TITLE
How to override style in NativeBase?

### ISSUE THREAD

**Issue by EllisShen** [GeekyAnts/NativeBase#13]
It may sound like a stupid question... but I didn't find a way to override style. In every code example, there's no usage of React StyleSheet. Could anyone give me a hint?

**Comment by sanketsahusoft** [comment]
With any component you can pass the style property which will be merged to the default style of that component.

For example, with <Button /> you can do

```
<Button style={ { backgroundColor: '#FF0000' } }> Click me! </Button>
```
