### ISSUE TITLE
InputGroup weird height

### ISSUE THREAD

**Issue by jreziga** [GeekyAnts/NativeBase#130]
Hello,

I'm using an InputGroup like this :
```
<InputGroup borderType="rounded" style={{height:40}}>
	<Input
		secureTextEntry={true}
		placeholder="Password"
		value={this.state.password}
		onChangeText={(password) => this.setState({password})}/>
</InputGroup>
```

I've fixed the height to 40 and here is the result : http://puu.sh/qJqRh/d5b352ae91.jpg

The rounded part doesn't extend to height 40

**Comment by sankhadeeproy007** [comment]
Hi, could you specify which version of native-base you are using? I'm using 0.5.5 and the same piece of code is working fine. 
![screen shot 2016-08-22 at 11 51 36 am](https://cloud.githubusercontent.com/assets/10998047/17845364/f5a3670a-685e-11e6-9b7e-cca77c0ee1d5.png)

**Comment by jreziga** [comment]
Can you add à background color white please

**Comment by sankhadeeproy007** [comment]
Closing this. Please check latest version.
![screen shot 2016-08-22 at 3 10 46 pm](https://cloud.githubusercontent.com/assets/10998047/17850417/b9566808-687a-11e6-8ed8-3339a5a7ce6c.png)
