### ISSUE TITLE
[ANDROID] Picker placeholder or default option 

### ISSUE THREAD

**Issue by Naveen-ICARUS** [GeekyAnts/NativeBase#1302]
## react-native, react and native-base version
react-native: 0.47.1
react: 16.0.0-alpha.12
native-base: 2.3.1

## Expected behaviour

placeHolder like "Select one"  or default one for Picker in **Android**
iosHeader not working 

## Actual behaviour

first one is selected as default

## Steps to reproduce (code snippet or screenshot)

![16-22-57](https://user-images.githubusercontent.com/31643287/31543303-1946a218-b033-11e7-8610-dddc9f5dd446.png)

## Screenshot of emulator/device

![image](https://user-images.githubusercontent.com/31643287/31543162-8ac4aa8a-b032-11e7-839a-3ad1de5edb88.png)

## Is the bug present in both ios and android or in any one of them?
may be feature required in **Android**

**Comment by akhil-geekyants** [comment]
see issue #1105

**Comment by SirPhemmiey** [comment]
This should be a bug
