### ISSUE TITLE
[BUG] Cards do not layout properly during rotation

### ISSUE THREAD

**Issue by iosdev-republicofapps** [GeekyAnts/NativeBase#1305]
Hi! Thanks for trying out NativeBase!
Due to the overwhelming requests and issues/questions we ask you to add the following details with your issue.

Please check the existing open/closed issues for a possible duplicate before creating a new issue :)

Also **DO** fill out the below form to give us a better idea about your environment and help us debug it quicker. Issues without the required details will mostly be unattended to.

## react-native, react and native-base version
react-native: 0.48.4
react: 16.0.0-alpha.12
native-base: 2.3.3

## Expected behaviour
When rotated, cards should display properly and should jam all the text on top of each other.

## Actual behaviour
Footer overwrites header and layout looks terrible

## Steps to reproduce (code snippet or screenshot)
Simple component:
```
import React from "react";
import { Image, Alert } from "react-native";
import {
  Container,
  Button,
  Text,
  Header,
  Title,
  Body,
  Card,
  CardItem,
  Left,
  Icon,
  Right
} from "native-base";

const HomeScreen = () => {
  return (
    <Container>
      <Header>
        <Body>
          <Title>Demo App</Title>
        </Body>
      </Header>

      <Card>
        <CardItem header>
          <Text>Driving is Fun</Text>
        </CardItem>
        <CardItem cardBody button onPress={() => Alert.alert("hi")}>
          <Image
            source={require("../images/burnout.jpg")}
            style={{ height: 200, width: null, flex: 1 }}
          />
        </CardItem>
        <CardItem footer>
          <Left>
            <Button transparent>
              <Icon active name="thumbs-up" />
              <Text>12 Likes</Text>
            </Button>
          </Left>
          <Body>
            <Button transparent>
              <Icon active name="chatbubbles" />
              <Text>144 Comments</Text>
            </Button>
          </Body>
          <Right>
            <Text>2h ago</Text>
          </Right>
        </CardItem>
      </Card>
    </Container>
  );
};

export default HomeScreen;
```
## Screenshot of emulator/device
![screen shot 2017-10-15 at 9 55 54 pm](https://user-images.githubusercontent.com/1666680/31595909-b3ea497a-b1f3-11e7-8385-2005e5999372.png)
![screen shot 2017-10-15 at 9 56 02 pm](https://user-images.githubusercontent.com/1666680/31595910-b3fb305a-b1f3-11e7-8f70-99c0e05e50f9.png)

## Is the bug present in both ios and android or in any one of them?
ios 11, Xcode 9, on all versions of the simulator (mostly testing on iPhone 6)

**Comment by iosdev-republicofapps** [comment]
Interesting, when I put the `Card` inside a `Content`, then the rotation works just fine.  Any idea why?  Am I not understanding something about the layout.

Here's the code when I wrap all within content:
```
import React from "react";
import { Image, Alert } from "react-native";
import {
  Container,
  Button,
  Text,
  Header,
  Title,
  Body,
  Card,
  CardItem,
  Left,
  Icon,
  Right
} from "native-base";

const HomeScreen = () => {
  return (
    <Container>
      <Header>
        <Body>
          <Title>Demo App</Title>
        </Body>
      </Header>

       <Content>
      <Card>
        <CardItem header>
          <Text>Driving is Fun</Text>
        </CardItem>
        <CardItem cardBody button onPress={() => Alert.alert("hi")}>
          <Image
            source={require("../images/burnout.jpg")}
            style={{ height: 200, width: null, flex: 1 }}
          />
        </CardItem>
        <CardItem footer>
          <Left>
            <Button transparent>
              <Icon active name="thumbs-up" />
              <Text>12 Likes</Text>
            </Button>
          </Left>
          <Body>
            <Button transparent>
              <Icon active name="chatbubbles" />
              <Text>144 Comments</Text>
            </Button>
          </Body>
          <Right>
            <Text>2h ago</Text>
          </Right>
        </CardItem>
      </Card>
      </Content>
    </Container>
  );
};

export default HomeScreen;
```

**Comment by akhil-geekyants** [comment]
@iosdev-republicofapps you can read about [NativeBase screen structure here](http://docs.nativebase.io/Components.html#anatomy-headref)

**Comment by iosdev-republicofapps** [comment]
Thanks @akhil-geekyants .  I am reading that.  :-)  I don't understand why the layout breaks when I rotate to landscape if I don't put my cards within a `Content` tag ... From the screenshot, the footer is being rendered on top of the header in landscape and that's clearly wrong ... Any ideas?

**Comment by iosdev-republicofapps** [comment]
Oh, I see this line: `Container takes mainly three components: <Header>, <Content> and <Footer>`.  Now it makes sense.  That didn't stand out in the examples.  Thanks for your help.  :-)  Closing.
