### ISSUE TITLE
How to set x , y “Back to top” after scrolling

### ISSUE THREAD

**Issue by ap050492** [GeekyAnts/NativeBase#1307]
can you please help for back to top after scrolling using Content component. i try with           resetScrollToCoords={{ x: 0, y: this.state.scrollOffsetY }}, but it's not working.

Thanks,

**Comment by akhil-geekyants** [comment]
@ap050492 if you are trying to achieve something like in this gif 
![backtotop](https://user-images.githubusercontent.com/27768184/31982267-9697a758-b975-11e7-8321-a342fb0d9a38.gif)

Code
```
  <Container>
        <Content ref={c => (this.component = c)}>
          <Text style={styles.text}>test</Text>
          <Text style={styles.text}>test</Text>
          <Text style={styles.text}>test</Text>
          ...
          ...
          ...
          ...

          <Button onPress={() => this.component._root.scrollToPosition(0, 0)}>
            <Text>Back to top</Text>
          </Button>
        </Content>
      </Container>
```

**Comment by akhil-geekyants** [comment]
Closing this due to no response
