### ISSUE TITLE
Sometimes tab views don't display until they are scrolled

### ISSUE THREAD

**Issue by andrewnoh** [GeekyAnts/NativeBase#131]
![tabs](https://cloud.githubusercontent.com/assets/13257645/17876618/c8744b3c-68a9-11e6-810e-7f7fea876dda.gif)

**Comment by sankhadeeproy007** [comment]
Hi, can you narrow down your test cases and let us know the specific code which is causing this effect?

**Comment by andrewnoh** [comment]
Looks like this might be a React Native ListView issue: https://github.com/facebook/react-native/issues/8607

**Comment by andrewnoh** [comment]
To confirm, yes this is a React Native <ListView> issue (MeteorListView is based off that). Although I don't understand it, the quick fix seems to be to put `removeClippedSubviews={false}` on the ListView/MeteorListView e.g. 

```
<ListView
    ...
     removeClippedSubviews={false}
/>
```

Native Base tabs working great! 👍

**Comment by wzf** [comment]
in my case, " removeClippedSubviews={false} " can not do well. At last i did find  [8607](https://github.com/facebook/react-native/issues/8607#issuecomment-233126000) .  Just replace RCTView with 8607.
