### ISSUE TITLE
Content and elements inside it  not getting rendered

### ISSUE THREAD

**Issue by zurez** [GeekyAnts/NativeBase#1311]
Hi! Thanks for trying out NativeBase!
Due to the overwhelming requests and issues/questions we ask you to add the following details with your issue.

Please check the existing open/closed issues for a possible duplicate before creating a new issue :)

Also **DO** fill out the below form to give us a better idea about your environment and help us debug it quicker. Issues without the required details will mostly be unattended to.

## react-native, react and native-base version
![image](https://user-images.githubusercontent.com/8244463/31707216-41071c4a-b409-11e7-8272-f45074c6b944.png)

## Expected behaviour
Input element should be rendered.
## Actual behaviour
![image](https://user-images.githubusercontent.com/8244463/31707280-684872e0-b409-11e7-9baf-23166a5e93b1.png)

## Steps to reproduce (code snippet or screenshot)
![image](https://user-images.githubusercontent.com/8244463/31707308-88b576f4-b409-11e7-93b8-4960da8c49d9.png)

## Screenshot of emulator/device
Genymotion Emulator
![image](https://user-images.githubusercontent.com/8244463/31707336-a8e12022-b409-11e7-952b-5876512a2f98.png)

## Is the bug present in both ios and android or in any one of them?
Tested on Android only

**Comment by zurez** [comment]
Update:
Running any example such as "HeaderExample" is crashing the app, without any warning/error message.

**Comment by akhil-geekyants** [comment]
@zurez Tried your code with the versions specified. Didn't see any issue. Attaching a gif
![contentelements](https://user-images.githubusercontent.com/27768184/31983572-6dbb1512-b97b-11e7-8192-01e3984a52ef.gif)

**Comment by akhil-geekyants** [comment]
Closing this due to no response
