### ISSUE TITLE
 label is cut with the top on floatingLabel Form

### ISSUE THREAD

**Issue by YulianD** [GeekyAnts/NativeBase#1312]
hello, everyone, I have the following problem, I am using the **FloatingLabel** of the **NativeBase** forms and when typed in the input the **Label is raised and cut by the top**, it is very much in the limit

## react-native, react and native-base version
    "@expo/vector-icons": "^5.2.0",
    "expo": "^21.0.0",
    "native-base": "^2.3.3",
    "react": "16.0.0-alpha.12",
    "react-native": "^0.48.4"
## Expected behaviour
![screenshot_20171018-091607](https://user-images.githubusercontent.com/11492518/31723952-f342601e-b3e5-11e7-8e86-f80304cf7b85.png)

## Actual behaviour
![screenshot_20171018-091536](https://user-images.githubusercontent.com/11492518/31723965-fd50a200-b3e5-11e7-9222-36d531f50331.png)

## Steps to reproduce (code snippet or screenshot)
![code](https://user-images.githubusercontent.com/11492518/31724131-7fc86e5c-b3e6-11e7-9b66-f7bbe8a1d427.png)

## Screenshot of emulator/device
![screenshot_20171018-092807](https://user-images.githubusercontent.com/11492518/31724203-b4622676-b3e6-11e7-8cd6-bcb817f71df3.png)

## Is the bug present in both ios and android or in any one of them?
**Android 7.0**

**Comment by akhil-geekyants** [comment]
@YulianD Tried your code with the versions specified. Didn't see any issue. Attaching a screenshot
![screenshot_1508916338](https://user-images.githubusercontent.com/27768184/31985900-33d3f2a2-b984-11e7-96a8-57cc85b42719.png)

**Comment by akhil-geekyants** [comment]
Closing the issue due to no response
