### ISSUE TITLE
When we use Form with Multiple Input's keyboard behaviour is not proper. When we click on Button it just closes keyboad but Button event ignored

### ISSUE THREAD

**Issue by srinuch1981** [GeekyAnts/NativeBase#1313]
## react-native, react and native-base version
"native-base": "^2.2.1"
"react": "16.0.0-beta.5"
"react-native": "0.49.3"

## Expected behaviour
When we have multiple Inputs ( Email, Password, First Name, Last Name) after enter email user taps the keyboad should retain or display. 

## Actual behaviour
Now we need to tap twice . On second  tap Only Keyboard appers

## Steps to reproduce (code snippet or screenshot)
<Form>

                        <Item stackedLabel>

                            <Label>{locStrings.first_name}</Label>

                            <Input
                                   ref={ input => {
                                       this.inputs['firstName'] = input;
                                   }}
                                   autoCapitalize = 'words'
                                   onChangeText={(text) => this.setState({firstName: text})}
                                   blurOnSubmit={ false }
                                   onSubmitEditing={() => {
                                       this.focusNextField('lastName');
                                   }}
                                   value={this.state.firstName}
                                   autoFocus = {true}
                                   maxLength={20}
                                   placeholder={locStrings.name_placeHolder}
                                   placeholderTextColor="gray"
                                   returnKeyType='next'/>
                        </Item>

                        <Item stackedLabel last>

                            <Label>{locStrings.last_name}</Label>

                            <Input
                                   ref={ input => {
                                       this.inputs['lastName'] = input;
                                   }}
                                   autoCapitalize = 'words'
                                   onChangeText={(text) => this.setState({lastName: text})}
                                   blurOnSubmit={ true }
                                   value={this.state.lastName}
                                   placeholder={locStrings.name_placeHolder}
                                   placeholderTextColor="gray"
                                   returnKeyType='done'
                                   maxLength={20}/>
                        </Item>
                    </Form>

## Is the bug present in both ios and android or in any one of them?
Observed in Android. The Kitchen Sink Form screens also behave same

**Comment by lucianomlima** [comment]
You need to set `keyboardShouldPersistTaps={'handled'}` in Container.

**Comment by srinuch1981** [comment]
Thanks . It's working

**Comment by SupriyaKalghatgi** [comment]
Fixed with NativeBase [2.3.4](https://github.com/GeekyAnts/NativeBase/releases/tag/v2.3.4)
