### ISSUE TITLE
ListItem renderSectionHeader background color not working on iOS

### ISSUE THREAD

**Issue by camel113** [GeekyAnts/NativeBase#1314]
I try to change the the section header backgroud color of a List but it does not work on iOS. 

## react-native, react and native-base version
```
{
	"name": "FootstatsReactNative",
	"version": "0.0.1",
	"private": true,
	"scripts": {
		"start": "node node_modules/react-native/local-cli/cli.js start",
		"test": "jest"
	},
	"dependencies": {
		"native-base": "^2.3.2",
		"react": "16.0.0-alpha.12",
		"react-native": "0.48.4",
		"react-native-i18n": "^2.0.7",
		"react-navigation": "^1.0.0-beta.13"
	},
	"devDependencies": {
		"babel-jest": "21.2.0",
		"babel-preset-react-native": "4.0.0",
		"jest": "21.2.1",
		"react-test-renderer": "16.0.0-alpha.12"
	},
	"jest": {
		"preset": "react-native"
	}
}
```

## Expected behaviour

List header backgroud should be grey => rgb(204, 206, 209)

## Actual behaviour

List header is white

## Steps to reproduce (code snippet or screenshot)

```
class MyLyst extends React.Component {

  _renderSectionHeader(sectionData, sectionID){
    return(
      <ListItem style={{ backgroundColor: 'rgb(204, 206, 209)'}}>
        <Text>Header Title</Text>
      </ListItem>
    )
  }

  render() {
    var items = ['Simon Mignolet','Nathaniel Clyne','Dejan Lovren','Mama Sakho','Emre Can'];
    return (
      <Container>
        <Content>
          <List dataArray={items}
            removeClippedSubviews={false}
            renderSectionHeader={this._renderSectionHeader.bind(this)}
            renderRow={(item) =>
              <ListItem>
                <Text>{item}</Text>
              </ListItem>
            }>
          </List>
        </Content>
      </Container>
    );
  }

}
```
## Screenshot of emulator/device
It works on Android
<img width="258" alt="screen shot 2017-10-19 at 11 08 31" src="https://user-images.githubusercontent.com/2794755/31763212-e7b0b0c4-b4bd-11e7-88f7-235ac8faa9e9.png">
It does not work on iOS
<img width="294" alt="screen shot 2017-10-19 at 11 08 18" src="https://user-images.githubusercontent.com/2794755/31763215-ea48d834-b4bd-11e7-816a-f95dcc155110.png">

## Is the bug present in both ios and android or in any one of them?

iOS

**Comment by akhil-geekyants** [comment]
Fixed in the latest version (2.3.7).

Gif

![sectionheaderbackground](https://user-images.githubusercontent.com/27768184/35219874-4bd0eb6a-ff9a-11e7-8663-79e93fe2c49e.gif)
