### ISSUE TITLE
Actionsheet and Picker are bad (Android)

### ISSUE THREAD

**Issue by hoboman313** [GeekyAnts/NativeBase#1315]
Actionsheet:
- largely unconfigurable and unstylable
- works 90% of the time, every time. https://github.com/GeekyAnts/NativeBase/issues/937 was never fixed properly which leads to random crashes.
- It just doesn't look or feel right on Android. I have not seen this type of pattern in any Google nor other apps.

Picker:
- does anyone here think that it's okay to have all that real state, but only make the tiny dropdown clickable?

**Comment by AbdallaMohamed** [comment]
The bottom sheet should slide up instead of fading in. https://material.io/guidelines/components/bottom-sheets.html

**Comment by akhil-geekyants** [comment]
@AbdallaMohamed considering this. Will be implemented in the near future.

**Comment by jobala** [comment]
@akhil-geekyants I can work on this enhancement.

**Comment by akhil-geekyants** [comment]
@jobala once completed, you can make a PR. Let us know if you need any help.

**Comment by jobala** [comment]
I can make this use, the native bottom sheet, should I do that?

**Comment by SupriyaKalghatgi** [comment]
Fixed with [2.5.0](https://github.com/GeekyAnts/NativeBase/tree/v2.5.0)

**Comment by akhil-geekyants** [comment]
- Issue #937 is fixed with native-base version 2.5.0.

- Implementation of ActionSheet on android is an implementation of the following screen 

![screen shot 2018-06-12 at 6 35 02 pm](https://user-images.githubusercontent.com/27768184/41292216-8a3ab32e-6e6f-11e8-82bc-0e3fe40b5b3f.png)

- NativeBase Picker for Android is a direct implementation of React Native Picker.

    Let us know if you would like us to add anything.

**Comment by SupriyaKalghatgi** [comment]
This issue will be closed this week in case of no response

**Comment by ardyfeb** [comment]
> Fixed with [2.5.0](https://github.com/GeekyAnts/NativeBase/tree/v2.5.0)

Let me know how make actionsheet with fade animation,  Can you give some example code ?

**Comment by rohithramachandran** [comment]
I am on version 2.13.0.. Looks like its still fading in instead of slide up... 
`ActionSheet.show()`
