### ISSUE TITLE
Button colors when using bordered causes broken buttons style

### ISSUE THREAD

**Issue by jacargentina** [GeekyAnts/NativeBase#1316]
## react-native, react and native-base version
"react-native": "^0.49.3",
"react": "16.0.0",
 "native-base": "^2.3.3",
## Expected behaviour
Display buttons just fine
## Actual behaviour
Button text color gets broken...
## Steps to reproduce (code snippet or screenshot)
For full reproduction, my app is available for cloning
https://github.com/jacargentina/iResucito.git
## Screenshot of emulator/device
Attached videos of 2 different navigation sequences.
## Is the bug present in both ios and android or in any one of them?
Both platforms; including iOS videos just for convenient, but I've checked and it's also happening on android
## Any other additional info which would help us debug the issue quicker.
All the code is on my repo.

[videos.zip](https://github.com/GeekyAnts/NativeBase/files/1403156/videos.zip)

I can't be sure this is a NativeBase bug/thing. Buttons from RN don't have background and I've tried replacing with those and they just work. But I want the look of NativeBase buttons. So that's why i'm posting my issue here.

**Comment by SupriyaKalghatgi** [comment]
@jacargentina I believe that happens only in simulator at times
I suggest you to try running your code on real device

**Comment by jacargentina** [comment]
I've discovered it no the real device; just later i've tested on the simulator for saving the demo video and posting here.

**Comment by SupriyaKalghatgi** [comment]
@jacargentina I am not clear with your statement
> I've discovered it no the real device;

Can you share screenshot from real device?

**Comment by XardoniK** [comment]
I'm not sure but I have similiar or the same problem. Screen from real device(samsung galaxy s7 edge). In emulator same effect.
react-native: 0.50.3

![screenshot_20171112-220900 copy](https://user-images.githubusercontent.com/9059223/32703492-15cc0a98-c7f7-11e7-8f01-ddaad638ea30.png)
![screenshot_20171112-221430 copy](https://user-images.githubusercontent.com/9059223/32703494-15e3176a-c7f7-11e7-97b8-81753ea28b80.png)

**Comment by akhil-geekyants** [comment]
@XardoniK Tried the following code. Couldn't see anything like above. Tested in Nexus 6, Android version -  Nougat 7.0
```
import React, { Component } from "react";
import { Container, Header, Content, Button, Text } from "native-base";
export default class ButtonThemeExample extends Component {
  render() {
    return (
      <Container>
        <Header />
        <Content>
          <Button style={{ margin: 10 }} light bordered>
            <Text> Light </Text>
          </Button>
          <Button style={{ margin: 10 }} primary bordered>
            <Text> Primary </Text>
          </Button>
          <Button style={{ margin: 10 }} success bordered>
            <Text> Success </Text>
          </Button>
          <Button style={{ margin: 10 }} info bordered>
            <Text> Info </Text>
          </Button>
          <Button style={{ margin: 10 }} warning bordered>
            <Text> Warning </Text>
          </Button>
          <Button style={{ margin: 10 }} danger bordered>
            <Text> Danger </Text>
          </Button>
          <Button style={{ margin: 10 }} dark bordered>
            <Text> Dark </Text>
          </Button>
        </Content>
      </Container>
    );
  }
}

```
Screenshot - Button with bordered prop

![screenshot_1510569254](https://user-images.githubusercontent.com/27768184/32721448-8f175638-c88c-11e7-9fd4-2bd85025b3e6.png)

Screenshot - Button without bordered prop

![screenshot_1510569736](https://user-images.githubusercontent.com/27768184/32721746-9163bb88-c88d-11e7-98fa-a28b24a6cc1f.png)

**Comment by XardoniK** [comment]
It was my bad. I imported {Text} from 'react-native' instead 'native-base'. Thank you for help. ;)

**Comment by jacargentina** [comment]
@XardoniK  that means, the problem is caused when mixing Text from RN, with Buttons from NB ?

**Comment by XardoniK** [comment]
@jacargentina yes. I had that:
![screenshot_1](https://user-images.githubusercontent.com/9059223/32741402-6efb9296-c8a6-11e7-904d-37d1deb77ac4.png)

But this is correct:
![screenshot_2](https://user-images.githubusercontent.com/9059223/32741412-7483dc3c-c8a6-11e7-9d60-b80343c7abfd.png)

**Comment by jacargentina** [comment]
So the thing is to add something on the docs stating **NativeBase buttons doesn't support mixing Text from RN as childs** ?

**Comment by SupriyaKalghatgi** [comment]
@jacargentina Thats true!
NativeBase Button inculcates NativeBase Text which has some styling applied
Whereas NativeBase Text can mixup with React Native Text in isolation

**Comment by SupriyaKalghatgi** [comment]
https://github.com/GeekyAnts/NativeBase/blob/master/src/theme/components/Button.js#L402

**Comment by carsonwah** [comment]
@SupriyaKalghatgi I am also having the same issue on `bordered` Button component.

Although I started a brand new project and did not see this happening, my current project is really suffering from this and could not find the solution.

I am suspecting that the [text color variable](https://github.com/GeekyAnts/NativeBase/blob/master/src/theme/components/Button.js#L406) got mutated somewhere inside nativebase code and didn't change back.

From `Button` [implementation](https://github.com/GeekyAnts/NativeBase/blob/master/src/basic/Button.js#L33), I saw the use of lodash merge in [computeProps.js](https://github.com/GeekyAnts/NativeBase/blob/master/src/Utils/computeProps.js#L40), which according to [lodash doc](https://lodash.com/docs/#merge), will mutate the original object. Not sure if it's buggy part as I can't understand these code well.

@SupriyaKalghatgi Could you re-investigate this issue further? Sorry for not able to set up and reproduce the issue.

---

## Situation 1:
### Screenshot:
![2018-01-16 00 23 37](https://user-images.githubusercontent.com/25053707/34952398-85315dfe-fa54-11e7-980d-f99a2b19d061.png)

### Code:
```javascript
import { Button, Text as NBText } from 'native-base';
......
        <Button bordered rounded success block>
            <NBText>{'Update Now'}</NBText>
          </Button>
          <Button bordered rounded info block>
            <NBText>{'Later'}</NBText>
          </Button>
          <Button rounded info block>
            <NBText>{'TEST'}</NBText>
          </Button>
```

*All Buttons from other pages in the app will also have this button text color, once it is mutated*

## Situation2:

If I change a little bit, it becomes:
![2018-01-16 00 35 22](https://user-images.githubusercontent.com/25053707/34952576-2dc8882a-fa55-11e7-8917-382632a72ded.png)
```javascript
        <Button rounded success block>
            <NBText>{'Update Now'}</NBText>
          </Button>
          <Button bordered rounded info block>
            <NBText>{'Later'}</NBText>
          </Button>
          <Button rounded info block>
            <NBText>{'TEST'}</NBText>
          </Button>
```

## Situation3:

Everything works fine if `bordered` props is not used at all.

**Comment by carsonwah** [comment]
The problem is not just about `bordered` Button. After some investigation, I found that my project is now "all NB buttons become white text color". It seems to be following the first button text color that appears. 

![2018-01-16 01 03 33](https://user-images.githubusercontent.com/25053707/34954102-252684d8-fa5a-11e7-809c-5bd0e2467c4c.png)

**Comment by akhil-geekyants** [comment]
@carsonwah couldn't reproduce the issue from our end. More likely it should be an issue with the app code. Can you share your code.

**Comment by harunsmrkovic** [comment]
@akhil-geekyants I am able to reproduce this exact same issue... order of Buttons (primary and light) matters...

**Comment by pqminh** [comment]
<Button
                  bordered
                  rounded

The button have been broken pixel on button border @
![Screen Shot 2019-08-12 at 2 33 53 PM](https://user-images.githubusercontent.com/13993984/62850786-410be080-bd0e-11e9-862d-2ebaf848e8fd.png)
