### ISSUE TITLE
How to remove shadow of `Tabs` on Android?

### ISSUE THREAD

**Issue by boringer** [GeekyAnts/NativeBase#1317]
## react-native, react and native-base version

React Native: 0.48.4.

React: 16.0.0-alpha.12.

Native Base: 2.3.2.

## Expected behaviour

Remove shadow under tab bar.

## Actual behaviour

Don't know how to.

## Steps to reproduce (code snippet or screenshot)

Remove code about shadows in ejected theme file (`native-base-theme/components/TabContainer.js`):

```js
const tabContainerTheme = {
    elevation: 3,
    height: styles.transformSize(104),
    flexDirection: "row",
    // shadowColor: platformStyle === "material" ? "#000" : undefined,
    // shadowOffset: platformStyle === "material"
    //  ? { width: 0, height: 2 }
    //  : undefined,
    // shadowOpacity: platformStyle === "material" ? 0.2 : undefined,
    // shadowRadius: platformStyle === "material" ? 1.2 : undefined,
    justifyContent: "space-around",
    borderBottomWidth: Platform.OS === "ios" ? variables.borderWidth : 0,
    borderColor: variables.topTabBarBorderColor
};
```

Or pass `tabStyle` to `Tabs` to override `shadowColor`, `shadowOpacity` or something.

## Is the bug present in both ios and android or in any one of them?

Android.

**Comment by akhil-geekyants** [comment]
@boringer to remove shadow set `elevation:0` in `TabContainer.js`

**Comment by akhil-geekyants** [comment]
closing this due to no response

**Comment by MarcAlx** [comment]
Another way to do what `akhil-geekyants` suggests :
```
<Tabs 
tabContainerStyle={{
  elevation:0
}}
>
```

**Comment by ApoorvTheTecHie** [comment]
@MarcAlx Thanks a lot mate, saved me a lot of head ache.. Cheers

**Comment by ruk91** [comment]
@MarcAlx  Thanks a lot

**Comment by GianReynaldi** [comment]
On IOS it's not worked

**Comment by vuongductuanktmt** [comment]
> Another way to do what `akhil-geekyants` suggests :
> 
> ```
> <Tabs 
> tabContainerStyle={{
>   elevation:0
> }}
> >
> ```

Thanks you, work for me 💯

**Comment by akashSilicon** [comment]
> Another way to do what `akhil-geekyants` suggests :
> 
> ```
> <Tabs 
> tabContainerStyle={{
>   elevation:0
> }}
> >
> ```



> Another way to do what `akhil-geekyants` suggests :
> 
> ```
> <Tabs 
> tabContainerStyle={{
>   elevation:0
> }}
> >
> ```

**Comment by akashSilicon** [comment]
> Another way to do what `akhil-geekyants` suggests :
> 
> ```
> <Tabs 
> tabContainerStyle={{
>   elevation:0
> }}
> >
> ```

Thank you very much for this solution @MarcAlx

**Comment by bharatSinghStartxlabs** [comment]
> > Another way to do what `akhil-geekyants` suggests :
> > ```
> > <Tabs 
> > tabContainerStyle={{
> >   elevation:0
> > }}
> > >
> > ```
> 
> Thank you, Work for me

AWESOME, Worked for me also

**Comment by Chill-Studio** [comment]
This works partially it removes most of the shadows but leaves a line of shadow between the tabs...

**Comment by portiz-daitan** [comment]
It worked for me by passing the same background-color as the tabContainer
`<Tabs 
tabContainerStyle={{
 backgroundColor: '#FFFFFF'
}}>
`
