### ISSUE TITLE
component disappears when set position: absolute in content component

### ISSUE THREAD

**Issue by Youjingyu** [GeekyAnts/NativeBase#1322]
## react-native, react and native-base version
react-native : 0.48.4
react : 16.0.0-alpha.12
native-base : 2.3.3
## Expected behaviour
component is visible when set ```position: absolute```
## Actual behaviour
component disappears
## Steps to reproduce (code snippet or screenshot)
my code is: 
```
<Content>
    <Button style={{ position: 'absolute' }}><Text>Click</Text></Button>
</Content>
```
the button is not visible in my android device. i think the reason is that the height of ```Content``` is 0 or ```zIndex```, so i set the ```height``` and ```zIndex```, but it is still not visible.
if i use ```Container``` to wrap ```Button```, it is visible:
```
<Container>
    <Button style={{ position: 'absolute' }}><Text>Click</Text></Button>
</Container>
```

**Comment by akhil-geekyants** [comment]
@Youjingyu you can fix this by giving a minHeight to the `<Content/>`.
Like
```
 <Content contentContainerStyle={{ minHeight: 100 }}>
       <Button style={{ position: "absolute" }}>
            <Text>Click</Text>
       </Button>
 </Content>
```

**Comment by akhil-geekyants** [comment]
Closing the issue due to no response
