### ISSUE TITLE
[ANDROID] onPress Event for Tabs

### ISSUE THREAD

**Issue by Naveen-ICARUS** [GeekyAnts/NativeBase#1325]
## react-native, react and native-base version

native-base: "^2.3.1",
react: "16.0.0-alpha.12",
react-native : "0.47.1",

## Expected behaviour

How do call a function when Native base Tab Component is clicked / pressed.

## Actual behaviour

onPress event not working in Tab component

## Steps to reproduce (code snippet or screenshot)
```
<Container>
   <Tabs style={{}} tabBarPosition="bottom" >
          <Tab style={{}} heading='Network' onPress={() => console.log("tab1")}>
          </Tab>
          <Tab style={{}} heading='Jobs' onPress={() => console.log("tab2")}>
          </Tab>
    </Tabs>
</Container>
```

## Is the bug present in both ios and android or in any one of them?

maybe a feature needed for ANDROID

**Comment by akhil-geekyants** [comment]
@Naveen-ICARUS you can use `onChangeTab` prop of `<Tabs/>` which can be used to detect a change in tab selection

**Comment by Naveen-ICARUS** [comment]
@akhil-geekyants  Thank you so much. Its what I needed.

**Comment by ngoducduy** [comment]
How can i know which tab is actived ?

**Comment by SupriyaKalghatgi** [comment]
@ngoducduy https://github.com/skv-headless/react-native-scrollable-tab-view#props

**Comment by pehagg** [comment]
Would be great if this prop would be documented in the API reference, instead of needing to search Github for an answer.

**Comment by selvesandev** [comment]
How can i disable or enable a particular tab.

**Comment by vipulkazz** [comment]
how can i change tab on another button's onPress can anyone guide me on this...?

**Comment by benhartouz** [comment]
Also i have the same question , how i can disable a specific tab ?

**Comment by ramanasak** [comment]
I want to change tabs to next and back by pressing button, how can I do that?
