### ISSUE TITLE
Header searchBar input item position.

### ISSUE THREAD

**Issue by inv2004** [GeekyAnts/NativeBase#1327]
Hello, Do you know if it possible to correct position of the input of the header-searchbar with additional Left button?

Thank you,

## react-native, react and native-base version
lastest
## Expected behaviour
Left side of input near 'back' button
## Actual behaviour
screenshot
## Steps to reproduce (code snippet or screenshot)
```
                <Header searchBar>
                    <Left>
                        <Button transparent onPress={() => this.props.navigation.navigate('Recommended')}>
                            <Icon name="arrow-back" />
                        </Button>
                    </Left>
                    <Item>
                        <Input placeholder={this.props.search} onChangeText={(x) => this.props.handleSearch(x)} />
                        <Icon name="search" />
                    </Item>
                </Header>
```
## Screenshot of emulator/device
![1](https://user-images.githubusercontent.com/4949069/31999652-121a83fa-b962-11e7-93af-a11594fa9276.png)
## Is the bug present in both ios and android or in any one of them?
android (IOS - did not check)

**Comment by akhil-geekyants** [comment]
@inv2004 you can modify the style of the components `<Left/>` or `<Item/>`  to place search near back button

**Comment by akhil-geekyants** [comment]
Closing this issue due to no response

**Comment by joshuadiezmo** [comment]
```
<Header searchBar>
                    <Left style={{flex: null}}>
                        <Button transparent onPress={() => this.props.navigation.navigate('Recommended')}>
                            <Icon name="arrow-back"/>
                        </Button>
                    </Left>
                    <Item>
                        <Input placeholder="Search User"/>
                        <Icon name="search"/>
                    </Item>
                </Header>
```
