### ISSUE TITLE
ActionSheet does not respect "cancelButtonIndex" or "destructButtonIndex"

### ISSUE THREAD

**Issue by thg303** [GeekyAnts/NativeBase#1328]
"react-native": "0.48.4",
"native-base": "^2.3.3"

There is a "cancel" and "delete" button in the documentation which should be settable by `cancelButtonIndex` and `destructButtonIndex` but none of them work in android.

I checked the `ActionSheet.js` looks like they're not implemented!

**Comment by akhil-geekyants** [comment]
@thg303 NativeBase ActionSheet is a wrapper around the React Native ActionSheetIOS component. Similar implementation has been done for Android, based on Material Design guidelines. Please share to us what you want us to add to the existing Android implementation.

**Comment by akhil-geekyants** [comment]
Closing this issue due to no response
