### ISSUE TITLE
tabBarUnderline issue when resize Tabbar height

### ISSUE THREAD

**Issue by sonnguyenit** [GeekyAnts/NativeBase#1329]
I resize the tabbar height to 25 by set style:
`activeTabStyle={{backgroundColor:"#1270BA", height: 25}} tabStyle={{backgroundColor:"#1AA9C7", height: 25}}`

and it changed, but the underline of the tabbar seems not changed follow the tabbar.
see the image [bellow.]
![tabbar](https://user-images.githubusercontent.com/13761142/32131346-1d8c12dc-bbd6-11e7-98d1-8c48225ea257.png)
How can i fix it?

**Comment by akhil-geekyants** [comment]
@sonnguyenit you can fix this by [ejecting the theme](http://docs.nativebase.io/Customize.html#Customize) and setting `height: 25` in `native-base-theme/components/TabContainer.js`

**Comment by sonnguyenit** [comment]
Thanks @akhil-geekyants 
I fixed it by add:  `<Tabs tabContainerStyle={{height: 28}} >` and seem working fine.
