### ISSUE TITLE
Input and fontFamily, fontSize etc..

### ISSUE THREAD

**Issue by jreziga** [GeekyAnts/NativeBase#133]
Hello,

I've an issue with native-base 0.5.2 on react-native 0.30.0.

I can't set a font family or a font size on an input. Can you tell me if it's me or not.

Thanks !

**Comment by sankhadeeproy007** [comment]
Please attach code examples.

**Comment by jreziga** [comment]
I was using <Button>my text</Button> instead of <Button><Text></Text></Button> my bad...
