### ISSUE TITLE
Radio button not selecting correctly

### ISSUE THREAD

**Issue by jhendrick** [GeekyAnts/NativeBase#1332]
"react-native": "0.48.2"
  "native-base": "^2.3.1"

I have the below code.  I am trying to get the radio button to change selections based on the variables below.  The first time the screen loads, it shows the correct radio button selected.  But clicking to other radio buttons does nothing.

            <List dataArray={this.props.pointsPackages} renderRow={(pointsPackages) =>
              <ListItem icon onPress={() => {this.props.toggleSelected(pointsPackages.price)}} >
                <Body>
                  <Text>{pointsPackages.description}</Text>
                </Body>
                <Right>
                  <Text>{pointsPackages.price}</Text>
                  <Radio selected={this.props.selectedPackage == pointsPackages.price} />
                </Right>
              </ListItem>
            }>

Previously, I had hard coded values like below and the radio button successfully updates when I click between them.

              <ListItem icon onPress={() => {this.toggleSelected('10 Points')}} >
                <Body>
                  <Text>10 points</Text>
                </Body>
                <Right>
                  <Radio selected={this.state.selectedPackage == '10 Points'} />
                </Right>
              </ListItem>
              <ListItem icon onPress={() => {this.toggleSelected('150 Points')}} >
                <Body>
                  <Text>150 points</Text>
                </Body>
                <Right>
                  <Radio selected={this.state.selectedPackage == '150 Points'} />
                </Right>
              </ListItem>

I'm not quite sure what I'm missing when trying to make this dynamic.  Why doesn't the radio button update correctly in the first case?

Additional code.  Passing the props in from a container class:
```
  toggleSelected(selection) {
    this.setState({'selectedPackage': selection});
  }

  render(){
    return(
      <PurchasePoints
        toggleSelected = {this.toggleSelected.bind(this)}
        selectedPackage = {this.state.selectedPackage}
        pointsPackages = {this.state.pointsPackages}/>
    );
  }
```

**Comment by akhil-geekyants** [comment]
see issue #858

**Comment by jhendrick** [comment]
Thank you this solved my problem.  Updated working code:

const packages = this.props.pointsPackages;
.....
      <List>{packages.map((pointsPackage, i) => {
              return <ListItem icon key={pointsPackage.price} onPress={() => {this.props.toggleSelected(pointsPackage.price)}}>
                <Body>
                  <Text>{pointsPackage.description}</Text>
                </Body>
                <Right>
                  <Text>{pointsPackage.price}</Text>
                  <Radio selected={this.props.selectedPackage == pointsPackage.price} />
                </Right>
              </ListItem>
            })}
