### ISSUE TITLE
Scrollable segment?

### ISSUE THREAD

**Issue by Elitebigboss90** [GeekyAnts/NativeBase#1333]
Any idea how to make a scrollable segment?
or it could be a new feature to the Native Base.

**Comment by SupriyaKalghatgi** [comment]
@Elitebigboss90 Though this is not as per iOS design principles, you can achieve it this way
```
<Header>
  <Body>
    <ScrollView horizontal={true}>
      <Segment>
```
This will scroll the segments in header
I am not sure if this is something that you are looking for

**Comment by SupriyaKalghatgi** [comment]
Closing this
Please reopen this issue if help needed
