### ISSUE TITLE
Content does not stretch to full height

### ISSUE THREAD

**Issue by gokulkulkarni1987** [GeekyAnts/NativeBase#1336]
## react-native, react and native-base version
```
"react-native": "0.48.4"
"react": "16.0.0-alpha.12"
"native-base": "2.3.3"
```
## Expected behaviour
Flatlist (horizonatl) present inside the content must stretch to full height.
## Actual behaviour
Flatlist wraps the height, without content it used to fill the whole height.
## Steps to reproduce (code snippet or screenshot)
```
<Container style={{ marginTop: 22 }}>
        <Header searchBar rounded>
          <Item>
            <Icon active name='search' />
            <Input placeholder='Search' />
          </Item>
          <Button transparent>
            <Text>Search</Text>
          </Button>
        </Header>
        <Content style={{ flex: 1 }}>
          <FlatList
            data={this.state.items}
            renderItem={this.renderRow.bind(this)}
            keyExtractor={(item) => item.row._id}
            horizontal
            removeClippedSubviews={false}
            style={{ flex: 1 }}
          />
        </Content>
</Container>
```
## Screenshot of emulator/device
![simulator screen shot - iphone 6 - 2017-10-31 at 16 23 37](https://user-images.githubusercontent.com/6063899/32221329-1d774960-be5b-11e7-8bc3-87cdc32ca256.png)

## Is the bug present in both ios and android or in any one of them?
Issue seen in Both
## Any other additional info which would help us debug the issue quicker.
I tried, 
- wrapping up Flatlist with nativebase View
- Giving `style={{ flex: 1 }} contentContainerStyle={{ flex: 1 }}` to Content.
- Tried giving flex to the items which are being displayed.
None of them is working.

**Comment by gokulkulkarni1987** [comment]
fixed it by adding,
`contentContainerStyle={{ flexGrow: 1 }}`

**Comment by SupriyaKalghatgi** [comment]
@EvHaus About `contentContainerStyle`, yes we will add this
Sorry! missed this

**Comment by hrmoller** [comment]
@SupriyaKalghatgi please do so👍

**Comment by shah-vivek** [comment]
@SupriyaKalghatgi 
The property is not present on the documentation. Is there a plan to deprecate this?

**Comment by cargallo** [comment]
Same Issue here. The solution proposed not working here...

**Comment by Abhishek12345679** [comment]
setting contentContainerStyle to {flexGrow:1}  no longer works ?
