### ISSUE TITLE
I am using picker for IOS and it is showing Maximum call stack size exceeded" exception

### ISSUE THREAD

**Issue by rajatgupta1993** [GeekyAnts/NativeBase#134]
<View>
									<Picker
									iosHeader="Select one"
									mode="dropdown"
									selectedValue={this.state.selected1}
									onValueChange={this.onValueChange.bind(this)}
									style={{flex:1}}>
									<Item label="Question" value="key0" />
									<Item label="Suggestion" value="key1"  />
									<Item label="Report a Bug" value="key2"/>
									<Item label="Other" value="key3"  />
									</Picker>
							</View>

**Comment by sankhadeeproy007** [comment]
Are you using the latest native-base version? 0.5.5?

**Comment by rajatgupta1993** [comment]
yeah updated the native base version, and it is working fine .
Thanks
