### ISSUE TITLE
How can we hide tabs header?

### ISSUE THREAD

**Issue by Symous** [GeekyAnts/NativeBase#1340]
Hi, is there any way we can hide the header of the tabs?
for example,I would like to show the header if there are more than 1 tab item so that the user can choose the tab, but it will be better to hide the header if there is only one tab item(not waste the space of the screen).Thanks!

**Comment by akhil-geekyants** [comment]
@Symous If you want to hide the ` < Header /> ` component, you can simply add a jsx condition to check the number of tabs and display the header accordingly. 
```
{
   this.state.numberOfTabs > 0 ? <Header hasTabs /> : null
}
```

**Comment by Symous** [comment]
@akhil-geekyants , hi , thanks for your reply, I might have not describe the question clearly , what I want to do is hide the "tabBar" of the Tabs instead of hiding the <Header/> component.

**Comment by Symous** [comment]
and hasTabs prop is used to remove the shadow of the header on Android and the border bottom line on iOS.

**Comment by akhil-geekyants** [comment]
@Symous if you want to hide the TabBar, you can add something similar to this
```
 <Container>
        {this.state.numberOfTabs > 0 ? (
          <Tabs>
            <Tab heading="Tab1">
              <TabOne />
            </Tab>
            <Tab heading="Tab2">
              <TabTwo />
            </Tab>
            <Tab heading="Tab3">
              <TabThree />
            </Tab>
          </Tabs>
        ) : (
          <Content>
            <TabOne />
          </Content>
        )}
      </Container>
```
hasTabs - It is advisable to use hasTabs prop with Header while using Tabs. You can refer the [docs here](http://docs.nativebase.io/Components.html#tabs-def-headref)

**Comment by Symous** [comment]
@akhil-geekyants thanks again. :D

**Comment by cgomezmendez** [comment]
Wouldn't that create two instances of the Tabone?

**Comment by cgomezmendez** [comment]
Actually I just found a better way, you can do it in the renderTabBar prop that is in tab.
something like this
<Tabs
          renderTabBar={(() => {
            if (this.state.hideTabBar) {
              return () => <View />;
            }
            return undefined;
          })()}
        >

**Comment by cgomezmendez** [comment]
Actually I just found a better way, you can do it in the renderTabBar prop that is in tab.
something like this
<Tabs
          renderTabBar={(() => {
            if (this.state.hideTabBar) {
              return () => <View />;
            }
            return undefined;
          })()}
        >

**Comment by nawaf-m** [comment]
@Symous 
Hi, this comment might be late but I hope someone finds it useful.

`<Tabs renderTabBar={false}>
  <Tab heading="Tab1">
    <Text> Tab 1</Text>
  </Tab>
  <Tab heading="Tab2">
    <Text> Tab 2</Text>
  </Tab>
  <Tab heading="Tab3">
    <Text> Tab 3</Text>
  </Tab>
</Tabs>`

**Comment by nawaf-m** [comment]
@Symous
Hi, this comment might be late but I hope someone finds it useful.

`<Tabs renderTabBar={false}>\n
  <Tab heading="Tab1">\n
    <Text> Tab 1</Text>\n
  </Tab>\n
  <Tab heading="Tab2">\n
    <Text> Tab 2</Text>\n
  </Tab>\n
  <Tab heading="Tab3">\n
    <Text> Tab 3</Text>\n
  </Tab>\n
</Tabs>`

**Comment by nawaf-m** [comment]
@Symous
Hi, this comment might be late but I hope someone finds it useful.

> <Tabs renderTabBar={false}>
  <Tab heading="Tab1">
    <Text> Tab 1</Text>
  </Tab>
  <Tab heading="Tab2">
    <Text> Tab 2</Text>
  </Tab>
  <Tab heading="Tab3">
    <Text> Tab 3</Text>
  </Tab>
</Tabs>

**Comment by harshaliitr** [comment]
Can we add animation to hide/show the tab bar? for example if the user is scrolling down in a scrollview, hide the tab bar and show it if he scrolls up.

**Comment by Manikanta-GEP** [comment]
Looking for the same.
