### ISSUE TITLE
FeatureRequest: Custom position for Toast notifications

### ISSUE THREAD

**Issue by kashishgrover** [GeekyAnts/NativeBase#1342]
Right now it seems like the only two positions available are 'top' and 'bottom'. 
<img width="718" alt="screen shot 2017-11-03 at 2 31 25 pm" src="https://user-images.githubusercontent.com/13067699/32366346-bdef7d5a-c0a3-11e7-9e43-0820f1f3ecaa.png">

**Comment by SupriyaKalghatgi** [comment]
@kashishgrover The design guidelines specifies bottom position for Toast
Though NativeBase supports bottom and top values of position

**Comment by kashishgrover** [comment]
Makes sense, but this limits the design a lot on my side. If the toast has a transparency to the dark color, it doesn't look so good along with the other elements of the app. :/

**Comment by SupriyaKalghatgi** [comment]
@kashishgrover You can customize this as per your project requirement
Check code for [Toast](https://github.com/GeekyAnts/NativeBase/blob/master/src/theme/components/Toast.js)

**Comment by kashishgrover** [comment]
Oh, alright. I will see how I can customize it once I get back to the respective components. :)

**Comment by essuraj** [comment]
changing bottomPosition of toast using marginBottom is blocking the button behind it. I can see the button but cannot click it.. any solutions? @SupriyaKalghatgi

**Comment by SupriyaKalghatgi** [comment]
I dont find any issues

![toast](https://user-images.githubusercontent.com/13464885/45609256-c0e4e880-ba74-11e8-81e4-43ca91d6d884.gif)

**Comment by hoonblizz** [comment]
Hi, it's been a while but I can't place the toast to the bottom. I mean, to the bottom 0. 
Because I'm also using this toast as keyboard avoid button, I want to avoid using position absolute. 
Also, I wonder how to remove left, right space. (tried margin, padding 0 but none of them work.)

Any help will be appreciated. 

Thank you.

**Comment by Eldavid** [comment]
> Hi, it's been a while but I can't place the toast to the bottom. I mean, to the bottom 0.
> Because I'm also using this toast as keyboard avoid button, I want to avoid using position absolute.
> Also, I wonder how to remove left, right space. (tried margin, padding 0 but none of them work.)
> 
> Any help will be appreciated.
> 
> Thank you.

I had kind of the same issue. I solved with the following style:
```
    Toast.show({
      text: e.message,
      type: 'danger',
      position: 'center',
      style: {
        borderRadius: 0,
        position: 'absolute',
        right: 0,
        left: 0,
        width: Dimensions.get('window').width,
      },
    });
```
