### ISSUE TITLE
Keyboard hides on input when using animated container

### ISSUE THREAD

**Issue by SimonVuong** [GeekyAnts/NativeBase#1344]
When using a keyboard inside an animated container with `Animated.createAnimatedComponent(Container);` the keyboard disappears after any input. For brevity, I eliminated unnecessary code, but the animated container is useful for dynamically adding padding to the container when the keyboard shows. This is useful for ensuring all no inputs get covered by the keyboard.

## react-native, react, expo, native-base version
 https://github.com/expo/react-native/archive/sdk-21.0.2.tar.gz
16.0.0-alpha.12
21.0.2
2.3.2
## Expected behavior
input persists in form
## Actual behavior
input disappears after typing a letter
## Steps to reproduce (code snippet or screenshot)
```
import React from 'react';
import { Animated } from 'react-native';
import { Container, Content, Form, Item, Text, Label, Input, Button } from 'native-base';

export default class ExampleScreen extends React.Component {

  state = { 
    phone: ''
  };

  render () {
    const AnimatedContainer = Animated.createAnimatedComponent(Container);
    
    return (
      <AnimatedContainer>
        <Content>
          <Form>
            <Item floatingLabel>
              <Label>Phone</Label>
              <Input onChangeText={(phone) => this.setState({phone})}/>
            </Item>
          </Form>
        </Content>
      </AnimatedContainer>
    )
  }
}
```

## Screenshot of emulator/device
![animatedkeyboardbug](https://user-images.githubusercontent.com/4956147/32401933-039f46e0-c0f0-11e7-9ad0-5ea09743dd15.gif)

## Is the bug present in both ios and android or in any one of them?
Anroid. Not sure about IOS.

**Comment by SupriyaKalghatgi** [comment]
@SimonVuong This is not NativeBase issue
While using any kind of `Animated` component, you need to handle the old and new values of properties whenever animation happens

**Comment by SimonVuong** [comment]
@SupriyaKalghatgi 
thanks for the tip. but could you explain how handling old and new values persists the keyboard and keeps it from disappearing? sorry if the gif was unclear. the issue isn't that the value doesn't show. it doesn't because the sample above doesn't use the value prop. the problem is that the keyboard disappears.

**Comment by SupriyaKalghatgi** [comment]
@SimonVuong You can check source code of NativeBase's floating label for handling old and new values of properties whenever animation happens

**Comment by tuomohopia** [comment]
@SimonVuong did you ever get this sorted out? I'm running to the same problem and haven't been able to figure out a solution yet.
