### ISSUE TITLE
Question: Does FCM change?

### ISSUE THREAD

**Issue by fmoessle** [GeekyAnts/NativeBase#1349]
Hi guys,

I have a question regarding the FCM-token received by the [getToken()](https://rnfirebase.io/docs/v3.1.*/messaging/reference/messaging#getToken) function.
Does the token ever change for a specific device? If yes, when does this behavior occur?

Found nothing in the docs :)

**Comment by akhil-geekyants** [comment]
Native Base is a UI Library. This issue is not related to UI.
