### ISSUE TITLE
color(...).darken(...).hex is not a function

### ISSUE THREAD

**Issue by ekimlinger** [GeekyAnts/NativeBase#1354]
## react-native, react and native-base version
Most current versions
## Actual behaviour
Error saying: color(...).darken(...).hex is not a function
## Steps to reproduce (code snippet or screenshot)
Attempt to use any one of the provided example themes provided by NativeBase
## Is the bug present in both ios and android or in any one of them?
Both
## Any other additional info which would help us debug the issue quicker.
The 'color' npm package uses a .hexString() function instead of .hex(). Not sure when this was changed.

## Fix:
Find all the .hex() functions in the variables folders and replace them with .hexString()

**Comment by fmoessle** [comment]
Same here

**Comment by SupriyaKalghatgi** [comment]
@ekimlinger @fmoessle Can you share your `package.json` here
Also try deleting `node_modules` and `yarn.lock`
Then run `yarn`

**Comment by fmoessle** [comment]
Found the problem. Npm installs a different version of the color-package then yarn. Using Npm instead of yarn solved my problem :)

**Comment by SupriyaKalghatgi** [comment]
@fmoessle Good to know that

**Comment by tmaly1980** [comment]
Weird, there's no hexString() in the most recent version of 'color', it seems to be called hex() again.
