### ISSUE TITLE
ReferenceError: Can't find variable: resolvedStyle

### ISSUE THREAD

**Issue by kishanio** [GeekyAnts/NativeBase#1359]
Hey there. I have created project using CRNA. & Later adding NativeBase as dependency. 

Versions:

"expo": "^22.0.2",
"native-base": "^2.3.3",
"react": "16.0.0-beta.5",
"react-native": "^0.49.5"

App runs just fine if i'm not using any of the NativeBase Components. As soon as i import e.g. `Content` and later use it as `<Content>SomeText</Content>`

I get following error .

![simulator screen shot - iphone 8 - 2017-11-10 at 19 38 26](https://user-images.githubusercontent.com/1800156/32664949-c64942be-c658-11e7-8f9f-004e0275ca8a.png)

**Comment by akhil-geekyants** [comment]
@kishanio Tried a sample code didn't find anything like above 

Gif

![referenceerror](https://user-images.githubusercontent.com/27768184/33017788-b10a0b72-ce19-11e7-8e73-8f6a92c4270a.gif)

**Comment by wiedld** [comment]
Problem is an updated native-base dependency.

Lock: “native-base-shoutem-theme": “0.2.1”

**Comment by AndreasKlein** [comment]
As @wiedld stated it is a problem with `native-base-shoutem-theme` In `connectStyle.js` in `getOrSetStylesInCache()`, if `(themeCache && themeCache[path.join(">")])` is not truthy, there will be a runtime exception as described above, bc indeed `var resolvedStyle` is not defined. Adding a `let` does all the magic. 

It seems like the themeCache can get into a state where that code runs and then it breaks the app. Doesn't seem like the theme is open source, so maybe it worth taking a look @akhil-geekyants 

Thanks

**Comment by akhil-geekyants** [comment]
PR (by @AaronFriel ) for this issue https://github.com/GeekyAnts/theme/pull/4

**Comment by AndreasKlein** [comment]
Excellent, we identified another issue in `Item.js`. This PR should fix it: https://github.com/GeekyAnts/NativeBase/pull/1396

**Comment by remon-georgy** [comment]
Having issues with undeclared variables here too. I confirm the PRs above tackle those issues.

Any chance those trivial fixes could be merged soon?

**Comment by SupriyaKalghatgi** [comment]
@remon-georgy Yes, this week

**Comment by midastouchprd** [comment]
Is there a version with this fixed?

**Comment by SupriyaKalghatgi** [comment]
@midastouchprd Merging it today

**Comment by anddon** [comment]
Any news on this?

**Comment by SupriyaKalghatgi** [comment]
Fixed with [2.3.6](https://github.com/GeekyAnts/NativeBase/releases/tag/v2.3.6)
