### ISSUE TITLE
State of filter not updating properly

### ISSUE THREAD

**Issue by smed** [GeekyAnts/NativeBase#136]

**Comment by smed** [comment]
Upon a button click, I am filtering the datasource for a listview inside Container/Content components. While the button click action fires properly, the state filter object does not get set properly on the first click, but all subsequent clicks set the state properly. Any thoughts?

**Comment by sankhadeeproy007** [comment]
You can try logging and see if the first click is actually registering. Not sure if it's a native-base issue.

**Comment by smed** [comment]
I've run the module outside of nativebase with no issues. Below is the console output from the initial and subsequent clicks:

pressed
set filters
{}
filtering
----------------
pressed
set filters
{ disease: 'Cancer', status: 'Unknown' }
filtering
----------------
pressed
set filters
{ disease: 'Diabetes', status: 'Valid' }
filtering

**Comment by sankhadeeproy007** [comment]
Can you try using TouchableOpacity instead of Button and see if that works.

**Comment by smed** [comment]
Same result unfortunately.

**Comment by smed** [comment]
You were correct. I needed to apply the filters on a callback from setState.
