### ISSUE TITLE
Tabs initial page load

### ISSUE THREAD

**Issue by svallen** [GeekyAnts/NativeBase#1361]
Initial tab when selected via prop is not updating the data of that tab. The tab itself highlights correctly.

## react-native, react and native-base version

"native-base": "^2.3.3",
"react": "16.0.0-beta.5",
"react-native": "https://github.com/expo/react-native/archive/sdk-22.0.2.tar.gz",

## Expected behaviour
![image](https://user-images.githubusercontent.com/6169781/32665606-e1496efa-c602-11e7-84e9-b77e0549317c.png)

## Actual behaviour

![image](https://user-images.githubusercontent.com/6169781/32665602-dcb61fa0-c602-11e7-90a3-04e7a93139e8.png)

## Steps to reproduce (code snippet or screenshot)
![image](https://user-images.githubusercontent.com/6169781/32665619-eef83e1e-c602-11e7-9865-1a4e8cbae5a0.png)

ios currently

**Comment by akhil-geekyants** [comment]
Possible duplicate. See issue #1010
