### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by smooJitter** [GeekyAnts/NativeBase#1364]
Where can I find roadmap for the next version of NativeBase?

**Comment by doertli** [comment]
and up-to-date changelogs (last entry was 9 months ago for 2.0.5, despite current version being 2.3.3).

**Comment by SupriyaKalghatgi** [comment]
@smooJitter We are in process of improving Docs
We will let you know about this

**Comment by SupriyaKalghatgi** [comment]
@doertli Agree to your statement

**Comment by smooJitter** [comment]
Thanks..  I’m just interested in knowing if we should expect new components

**Comment by SupriyaKalghatgi** [comment]
I have opened this issue on the docs repo here: [#76](https://github.com/GeekyAnts/native-base-docs/issues/76)
Since we split the docs and the source into separate repos.
