### ISSUE TITLE
Header's ZIndex cannot be set from application

### ISSUE THREAD

**Issue by wsmlby** [GeekyAnts/NativeBase#1367]

**Comment by sankhadeeproy007** [comment]
You can manually set a higher zIndex value to the header. The reason we haven't se t a high zIndex value to the header is that there might be instances when the header should hide behind a component (for example an overlay). So it's best that you set the value according to your needs.

**Comment by wsmlby** [comment]
What is the right way to set it? seems like the interface is not exposed at all. Any ideas?
