### ISSUE TITLE
rerender tabs children

### ISSUE THREAD

**Issue by niros001** [GeekyAnts/NativeBase#1368]
Hi i use RN 0.44 & NB 2.1.5
I use the tabs from the example in docs with `prerenderingSiblingsNumber` parameter:
```
<Tabs initialPage={1} prerenderingSiblingsNumber={Infinity}>
          <Tab heading="Tab1">
            <Tab1 />
          </Tab>
          <Tab heading="Tab2">
            <Tab2 />
          </Tab>
          <Tab heading="Tab3">
            <Tab3 />
          </Tab>
        </Tabs>
```
If i using that parameter so when i change tab the app rerender all the tabs, when i not using that parameter the app rerender only the current tab that i click. I want to navigate between the tabs without rerendering, that possible?
* I think in previous versions it work like that.

**Comment by akhil-geekyants** [comment]
@niros001 checked the current native-base version(2.3.3). It is working fine. If possible upgrade to the latest version. See the NativeBase compatibility [here](http://docs.nativebase.io/docs/Compatibility.html). 

Gif image

![prerender](https://user-images.githubusercontent.com/27768184/32838254-540faf94-ca36-11e7-80bc-dbe43b031019.gif)

**Comment by niros001** [comment]
but try to change tabs, what happen if you change from tab 2 to tab 3, the app rerender all the tabs again?

**Comment by niros001** [comment]
Ok i just use `PureComponent` instead `Component` on tabs children classes to prevent that behavior.

**Comment by akhil-geekyants** [comment]
Closing this issue as the issue has been solved.

**Comment by JiboStore** [comment]
Hi I have another problem regarding prerenderingSiblingsNumber, if I don't use that props, it becomes very laggy when I switch tab, but if I use prerenderingSiblingsNumber={Infinity}, my children tab will not be refreshed even after I switch to and from that tab.. any idea?
