### ISSUE TITLE
Android Picker doesn't work with stackedLabel

### ISSUE THREAD

**Issue by PaitoAnderson** [GeekyAnts/NativeBase#1369]
## react-native, react and native-base version
```
"native-base": "^2.3.3",
"react": "16.0.0",
"react-native": "0.50.3"
```

## Expected behaviour
MasterCard option should show up, and it should be clickable

## Actual behaviour
Options don't appear, isn't clickable

## Steps to reproduce (code snippet or screenshot)
```
export default class App extends Component {
  render() {
    return (
      <View style={styles.container}>
        <Content>
          <Form>
            <Item stackedLabel>
              <Label>Payment Type</Label>
              <Picker selectedValue='key0' iosHeader='Payment Type' mode='dropdown'>
                <Picker.Item label='MasterCard' value='key0' />
                <Picker.Item label='VISA' value='key1' />
              </Picker>
            </Item>
          </Form>
        </Content>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    marginTop: 20,
    flex: 1,
  }
});
```

## Screenshot of emulator/device
![screenshot_1510665422](https://user-images.githubusercontent.com/4108718/32781908-a2a41208-c914-11e7-9514-86ea9c98173e.png)
![simulator screen shot - iphone 6 - 2017-11-14 at 08 12 55](https://user-images.githubusercontent.com/4108718/32781909-a2c555c6-c914-11e7-8571-efc8495a0fb3.png)

## Is the bug present in both ios and android or in any one of them?
Just Android

## Any other additional info which would help us debug the issue quicker.
Could be related to #1173

**Comment by akhil-geekyants** [comment]
@PaitoAnderson `<Item/>` with stackedlabel is designed to work mainly with Input components. So this may not work properly.

**Comment by SupriyaKalghatgi** [comment]
Ya this is not use case with stacked input

**Comment by PaitoAnderson** [comment]
Thanks Guys! Closing.

**Comment by Moumit** [comment]
Any working example with stackedLabel or kind of?
