### ISSUE TITLE
Swipe treshold for the Tabs component

### ISSUE THREAD

**Issue by mahomahoxd** [GeekyAnts/NativeBase#1371]
Hello,

I'm happy with using the native-base elements, there is one thing I wanted to ask though. Is there a way to use the tabs in such a way with a list inside it? I have 2 tabs, in each I have a list. However on refreshing it will freeze the refreshing icon if you swipe just a tiny bit left or right (accidentally even). Isn't there a workaround or a property I can set such as some kind of a swipe threshold? Other than that everything seems great.

Thanks in advance!

**Comment by glodfinch** [comment]
I also came across this issue today. It seems to be the same as being described here #1168 
I tried applying the RefreshControl to a Content that was a parent to the Tabs component and this did work, but it scrolls the page so that the Tabs component disappears. It seems adjusting the swipe threshold would be the solution.

**Comment by mahomahoxd** [comment]
I think if you put tabs in a component such as Content, it will have that kind of behavior. I assume Tabs is a wrapper around a View, this would mean you can just put the RefreshControl thing inside the tabs (I think). I just wanted a swipe threshold as it seems a lot easier to implement that rather than a RefreshControl in each of my lists.

**Comment by glodfinch** [comment]
It's a wrapper around a ScrollView, it uses that element's horizontal scrolling under the hood. Seems it doesn't pass down the refreshControl prop however, but I edited it to do that and it seems to work fine! Here, after line 176:
https://github.com/GeekyAnts/NativeBase/blob/master/src/basic/Tabs/index.js

I added:
`refreshControl: this.props.refreshControl,`

And it passes down the prop and works perfectly from my brief testing.

**Comment by mahomahoxd** [comment]
You could make a pull request, I'd also put it in the proptypes between line 30 and 42, but thats a minor thing. I'll test that out too.

**Comment by mahomahoxd** [comment]
I've tested it as well, it seems to work fluently

**Comment by glodfinch** [comment]
Found some issues with this - closed PR, see my comment for info

**Comment by SupriyaKalghatgi** [comment]
#38
