### ISSUE TITLE
ListItem, there's a distance to the left.

### ISSUE THREAD

**Issue by pakyo-pan** [GeekyAnts/NativeBase#1372]
Hello, ListItem, there's a distance to the left. I set up backgroundColor:'#fff'for List, but when ListItem was at onPress, there was a distance on the left.

## react-native, react and native-base version
`
"native-base": "^2.3.3",
 "react": "16.0.0",
"react-native": "^0.50.3",
`
## Expected behaviour
List should be filled with full width

## Steps to reproduce (code snippet or screenshot)
![image](https://user-images.githubusercontent.com/13342613/32840646-3e00b744-ca53-11e7-88e3-b1b77fdee294.png)

## Screenshot of emulator/device
![image](https://user-images.githubusercontent.com/13342613/32840635-37cc3772-ca53-11e7-9a4b-e550ae3ec80a.png)

请求帮助

**Comment by SupriyaKalghatgi** [comment]
@pakyo-pan It would be better if you can post your query in English

**Comment by pakyo-pan** [comment]
@SupriyaKalghatgi I'm glad to hear from you. How can I solve this problem?

**Comment by akhil-geekyants** [comment]
@pakyo-pan override the ListItem style and set 

```
<ListItem style={{ marginLeft: 0, paddingLeft: 15 }}/>
```

**Comment by pakyo-pan** [comment]
@akhil-geekyants If you change it to `<ListItem style={{ marginLeft: 0, paddingLeft: 15 }}/>`, bottomBorder can't keep distance from the left.

**Comment by akhil-geekyants** [comment]
@pakyo-pan 

![listitem](https://user-images.githubusercontent.com/27768184/33006729-8221f112-cdf1-11e7-868a-1af8fe990c53.gif)

**Comment by SupriyaKalghatgi** [comment]
#1378 #1314
