### ISSUE TITLE
Is there a way to make a card take the whole screen width?

### ISSUE THREAD

**Issue by hpbl** [GeekyAnts/NativeBase#1374]
## react-native, react and native-base version
   "react-native": "0.42.0",
    "native-base": "2.1.0",
## Expected behaviour
   I'd like to make a card take the whole width of my sreen, or any other value I want.
## Actual behaviour
   Card has default width value, that I don't know how to change

Thanks ;)

**Comment by akhil-geekyants** [comment]
@hpbl just override the style of <Card/> component. The spaces are due to the default margin given to the card.

To take the whole width 
```
<Card style={{marginLeft:0,marginRight:0}}/>
```
To set a custom width
```
<Card style={{width:100}}/>
```

**Comment by hpbl** [comment]
I thought I had tried that before, but it didn't work. Guess I was mistaken, since now that I've tried what you said, it works fine. Thank you!

**Comment by anhtuank7c** [comment]
Do reject theme and edit `native-base-theme/components/Card.js`
change `marginVertical: 0`, then use ejected theme

**Comment by jerryheir** [comment]
what about how to change the card height?

**Comment by SupriyaKalghatgi** [comment]
@jerryheir Why do you want to change height of card?
Depending upon the components you wrap within `Card`, the height is set accordingly

**Comment by jerryheir** [comment]
Okay, that what I wanted to know...
