### ISSUE TITLE
Cannot install Native Base

### ISSUE THREAD

**Issue by MinhNQ90** [GeekyAnts/NativeBase#1375]
I follow as your guide run this command `npm install native-base --save`
but the cmd notice like bellow
![image](https://user-images.githubusercontent.com/33272530/32939987-e4ca2518-cbb3-11e7-943f-6bff0d5c98c6.png)
So how can it fix this issue ?

**Comment by SupriyaKalghatgi** [comment]
@MinhNQ90 Please share the complete screenshot when you run `npm install native-base --save`

**Comment by MinhNQ90** [comment]
@SupriyaKalghatgi Here it is
![image](https://user-images.githubusercontent.com/33272530/32941034-0ab99d0a-cbb7-11e7-8f4c-90fb7353a865.png)

**Comment by SupriyaKalghatgi** [comment]
@MinhNQ90 
> Please check if you have git installed in your $PATH

**Comment by MinhNQ90** [comment]
Thank you, it must install through Git

**Comment by SupriyaKalghatgi** [comment]
@MinhNQ90 Glad to know that you found the actual issue causing this
Happy NativeBase!

**Comment by YufJi** [comment]
thanks! it must install through Git commend
