### ISSUE TITLE
Support for small screen sizes

### ISSUE THREAD

**Issue by MohammadElbanna** [GeekyAnts/NativeBase#1377]
Hello, 

This is just an observation when checking the kitchen sink demo on iPhone SE running iOS 11 (I assume this will be reproducible in similar android phones with small screen sizes as well).

<img src="https://i.imgur.com/5M9tvxa.jpg" alt="first image" width="250">
<img src='https://i.imgur.com/J2SUnAC.jpg'  width="250"/>

In the first image the words for the tabs are wrapped. 
In the second image the icons are not correctly aligned:

**Comment by SupriyaKalghatgi** [comment]
With latest NativeBase, the issue is only with Footer
Rest of the components work fine on devices of smaller dimensions

**Comment by SupriyaKalghatgi** [comment]
Footer issue doesn't appear now
