### ISSUE TITLE
No support for Feather Font Icon

### ISSUE THREAD

**Issue by maxusr** [GeekyAnts/NativeBase#1379]
Hello,
thanks for your project! It's amazing! I started a couple of weeks and it's simple. The problem i have now is that your project depends on react-native-vector-icons or @expo/vector-icons but not support the Font Feather yet! Which is the same on both systems IOS and Android! I try to see and i know it is a bad way! I just modify your IconNB.js file and added lines for Feather support but it is fastidious when starting new project! do you know another way to do that?

Thanks

**Comment by shivrajkumar** [comment]
@maxusr It will be fixed in next release.
Also, you can send a PR of the fix

**Comment by SupriyaKalghatgi** [comment]
Fixed with [2.3.6](https://github.com/GeekyAnts/NativeBase/releases/tag/v2.3.6)
