### ISSUE TITLE
Icons not showing

### ISSUE THREAD

**Issue by javorosas** [GeekyAnts/NativeBase#138]
I'm getting started with NativeBase, so I copy/pasted the `InputGroup` example with `Icon`. When I run the app, I'm seeing an X where the icon is supposed to be.

<img width="361" alt="screen shot 2016-08-24 at 12 46 22 pm" src="https://cloud.githubusercontent.com/assets/2592262/17945566/440c1d60-69f9-11e6-9989-74e1ef5974a8.png">

Is there any initial setup required for the Icons that I'm missing? Here's my code:

```jsx
import React, { Component } from 'react';
import { View, Text } from 'react-native';
import { Button, InputGroup, Input, Icon } from 'native-base';

export default class SetUsername extends Component {
  render () {
    return (
      <View>
        <Text>Choose a username</Text>
        <Icon name="ios-home" style={{color: '#384850'}} />
        <InputGroup borderType="rounded" >
          <Icon name="ios-home" style={{color: '#384850'}} />
          <Input placeholder="Username" />
        </InputGroup>
        <Button type="block">Choose</Button>
      </View>
    );
  }
}
```

**Comment by SupriyaKalghatgi** [comment]
@javorosas Which version of RN and NativeBase are you using?
Also try setting up icons for android from the docs

**Comment by irekrog** [comment]
I had the same problem. I redinstalled the app and icons are shown.

My version:
React Native - 0.32
NativeBase - 0.5.7

**Comment by sankhadeeproy007** [comment]
Let's follow this thread for Icon related issues. #76

**Comment by burnquist** [comment]
I had the same problem. I reinstalled the app and icons are shown.

My version:
React Native - 0.39.2
NativeBase - 0.5.18

**Comment by mustafakucuk** [comment]
Hi, close project and start.

**Comment by veb** [comment]
To get around this I did:
`react-native link`
then:
`react-native run-android` and the icons showed up. :)

**Comment by kenmasters** [comment]
I did what @veb done and success 👍

**Comment by Rizwanilahi** [comment]
1. Simply uninstall app and reinstall it solved.

**Comment by Rizwanilahi** [comment]
## Simply uninstall app and reinstall it solved.

**Comment by durgapatra** [comment]
1st run this comment
react-native link
then:
react-native run-android and the icons showed up. now

**Comment by DiegoFelipe** [comment]
just run react-native link and then react-native run-android and it should work

**Comment by gbrum** [comment]
i did what @veb and @kenmasters do , and succes , thank you

**Comment by pareksha** [comment]
Do not run `react-native link` if you have already did it at the start of project. Else it will cause linking twice and you'll face this https://github.com/wix/react-native-camera-kit/issues/132
