### ISSUE TITLE
Form width is 0 when containing Content's "contentContainerStyle" contains "alignItems: 'center'"

### ISSUE THREAD

**Issue by kodayashi** [GeekyAnts/NativeBase#1380]
Hi! Thanks for trying out NativeBase!
Due to the overwhelming requests and issues/questions we ask you to add the following details with your issue.

Please check the existing open/closed issues for a possible duplicate before creating a new issue :)

Also **DO** fill out the below form to give us a better idea about your environment and help us debug it quicker. Issues without the required details will mostly be unattended to.

## react-native, react and native-base version
```
├── react@16.0.0
├── react-native@0.50.3
├── native-base@2.3.3
```

## Expected behaviour

When adding a Form inside of Content (regardless of justification and alignment), the form spans the width of the Content.

## Actual behaviour

Works as expected unless `alignItems: 'center'` is set as part of the Content's `contentContainerStyle`, in which case the Form (and all UI inside) has no width.

## Steps to reproduce (code snippet or screenshot)

```
        <Content
          padder
          scrollEnabled={false}
          contentContainerStyle={styles.content}>
            <Form>
              <Item>
                <Input placeholder="Username"/>
              </Item>
              <Item last>
                <Input placeholder="Password"/>
              </Item>
            </Form>
        </Content>

.
.
.

const styles = StyleSheet.create({
  content: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center'
  }
});
```

## Is the bug present in both ios and android or in any one of them?

Confirmed on iOS, unsure on Android.

## Any other additional info which would help us debug the issue quicker.

I tried all sorts of style overrides. I tried overriding `alignItems: 'center'` and putting it back to stretch in the Form, Item and Input components. I tried using variations of flex and flexDirection in the components as well.

Eventually, I just got the width from Dimensions and moved on, but it would be great if the form's width rendered properly regardless of the `alignItems` value in Content's `contentContainerStyle` property.

**Comment by akhil-geekyants** [comment]
@kodayashi `<Form/>` is behaving as expected. Try overriding `<Form/>` style and set `alignItems:'center'`. Attaching a gif

![contentcontainerstyleissue](https://user-images.githubusercontent.com/27768184/33077409-c471ab34-cef5-11e7-9074-34b357bc0927.gif)

**Comment by kodayashi** [comment]
Shoot that worked. I suppose I assumed that style would be inherited by the form -- I thought I tried that but I must've missed something. Thanks, apologies for the false positive.
