### ISSUE TITLE
CardItem layout issues only on iPhone plus devices.

### ISSUE THREAD

**Issue by AshokICreate** [GeekyAnts/NativeBase#1381]
The layout which i designed using card layout works correctly on iPhone 5, iPhone 6, iPhone 7, iPhone 7 and iPhone 6S.

But the design is completely messed up on iPhone Plus Devices.

https://github.com/GeekyAnts/NativeBase/issues/612 issues is closed with out any solutions? please reopen it.

**Comment by SupriyaKalghatgi** [comment]
@AshokICreate Issue 612 is reopened
I am closing this issue since this is duplicate one
Please check #612 for updates
