### ISSUE TITLE
How to display Icon and text

### ISSUE THREAD

**Issue by ZeroSoulEater** [GeekyAnts/NativeBase#1385]
I want to display a Icon on the Left and a Text on the Right But it always look false Like the Text is not on the same level as as the icon.
<img width="169" alt="bildschirmfoto 2017-11-21 um 23 46 52" src="https://user-images.githubusercontent.com/9642078/33100889-50102506-cf16-11e7-8b29-d17364a1ee10.png">

I Use:
```
<Text>
  <Icon ios='ios-mail-outline' android='ios-mail-outline'/>
  <Text> {this.store.user.email}</Text>
</Text>
```

**Comment by horiuchie** [comment]
FWIW, I tried using a flexbox referring to [Layout with Flexbox](https://facebook.github.io/react-native/docs/flexbox.html).

```
<View style={{ flex: 1, flexDirection: 'row', alignItems: 'center' }}>
  <Icon ios='ios-mail-outline' android='ios-mail-outline'/>
  <Text>TTTTTT@TTT.com</Text>
</View>
```
android:
![android](https://user-images.githubusercontent.com/28750080/33107090-f40eaa58-cf78-11e7-92e1-0abbbeb71323.png)

ios:
![ios](https://user-images.githubusercontent.com/28750080/33107148-40ce7b3e-cf79-11e7-8e32-865bc95e2a7b.png)

**Comment by ZeroSoulEater** [comment]
Thats cool thank you!!

**Comment by akhil-geekyants** [comment]
@ZeroSoulEater Thats happening with React Native `<Text>` also
@horiuchie 's workaround runs fine
Also that you can try wrapping `<Icon` and `<Text>` with NativeBase's `<ListItem>`
that gives proper spacing between icon and text with appropriate lineHeight

![screen shot 2017-11-22 at 3 26 27 pm](https://user-images.githubusercontent.com/27768184/33120954-934d69c2-cf99-11e7-87b2-11f04c5d9cfd.png)

**Comment by ZeroSoulEater** [comment]
@akhil-geekyants With ListItem I got this Line

<img width="171" alt="bildschirmfoto 2017-11-22 um 11 14 05" src="https://user-images.githubusercontent.com/9642078/33121905-522a479e-cf76-11e7-87e3-195d83698b01.png">

```
<ListItem icon> 
  <Left>
    <Icon name="plane" />
  </Left>
  <Body>
    <Text>Airplane Mode</Text>
  </Body>
  <Right/>
</ListItem>
``

**Comment by akhil-geekyants** [comment]
@ZeroSoulEater just set `style={{ borderBottomColor: 'transparent' }}` for `<Body/>` component and remove `<Right/>` if it don't have any children

```
<ListItem icon>
      <Left>
         <Icon name="plane" />
      </Left>
      <Body style={{ borderBottomColor: 'transparent' }}>
         <Text>Airplane Mode</Text>
      </Body>
 </ListItem>
```

**Comment by akhil-geekyants** [comment]
Closing this issue due to no response

**Comment by murrayobrien** [comment]
According to docs: [https://docs.nativebase.io/icon](url) and using native base components we can do something like this: 
`<HStack space={2}>
      <CheckIcon size="5" mt="0.5" color="emerald.500" />
      <Text color="emerald.500" fontSize="md">
        Order Placed Successfully
      </Text>
 </HStack>`
