### ISSUE TITLE
ListView error when deleting last row.

### ISSUE THREAD

**Issue by raphcadiz** [GeekyAnts/NativeBase#1386]
Hi everyone. I have a code something like this

```
<List
  dataSource={ds.cloneWithRows(this.props.sales_items)}
  renderRow={item =>
    <ListItem>
      <Text style={{color: Platform.OS === "android" ? "#777" : "#666", paddingLeft: 8}}> {item.item.product.name} - {item.item.packing.label} </Text>
    </ListItem>}
  renderLeftHiddenRow={(item, sec_id, row_id) =>
    <Button full onPress={() => this._setEditItem(item, row_id)} style={{backgroundColor: '#F05A1A'}}>
      <Icon active name="ios-create-outline" />
    </Button>}
  renderRightHiddenRow={(data, sec_id, row_id) =>
    <Button full danger onPress={() => this._deleteItem(row_id)}>
      <Icon active name="trash" />
    </Button>}
  leftOpenValue={75}
  rightOpenValue={-75}
  enableEmptySections={true}
/>
```

This is working fine the only issue is if I deleted the last item from the list then I start swiping left/right on remaining item on the list I get an error:
`null is not an object (evaluating 'this._rows[this.openCellld]._root')`
but if I delete any item (except the last item), it's working fine.

This is my delete handle:
```
_deleteItem(row_id) {
    let sales_items = this.props.sales_items
    sales_items.splice(row_id, 1)
    this.props.addSalesItem(sales_items)
    this.forceUpdate()
}
```

Any help would be very much appreciated.

**Comment by shivrajkumar** [comment]
@raphcadiz This is because you are not closing the selected/deleting row before you delete it. Swipeable list works such a way that, the open row closes only then the new row can be opened.
Change your renderRightHiddenRow to, 
`
renderRightHiddenRow={(data, sec_id, row_id) =>
    <Button full danger onPress={() => this._deleteItem(secId, rowId, rowMap)}>
      <Icon active name="trash" />
    </Button>}
`
and your delete function to
`
_deleteItem(sec_id,row_id, row_map) {
    row_map[`${sec_id}${row_id}`].props.closeRow();     // Closing the row before delete
    let sales_items = this.props.sales_items
    sales_items.splice(row_id, 1)
    this.props.addSalesItem(sales_items)
    this.forceUpdate()
}
`
