### ISSUE TITLE
When `TextInput` gets the focus, the `<Footer>` can't be topped up for ios

### ISSUE THREAD

**Issue by giantss** [GeekyAnts/NativeBase#1387]
When `TextInput` gets the focus, the `<Footer>` can't be topped up for ios,help...
![image](https://user-images.githubusercontent.com/13778798/33108017-e35def92-cf74-11e7-8991-98aa5ff5eae0.png)
![image](https://user-images.githubusercontent.com/13778798/33108041-0bab6d08-cf75-11e7-9211-31b6a9a31235.png)
@beausmith @aaray @designorant @MarceloAlves @yosmanyga

**Comment by lucianomlima** [comment]
Have same problem!

**Comment by akhil-geekyants** [comment]
Footer is designed to be fixed at bottom and not scrollable. In this case, you can move the Footer's content to `<Content/>` and fix it at the bottom.

**Comment by lucianomlima** [comment]
But when keyboard shows, the bottom is under keyboard or above keyboard?
I fix replace Content with ScrollView + KeyboardAvoidView, but is unstable for Android and iOS.

**Comment by akhil-geekyants** [comment]
@lucianomlima try something like this
```
      <Container>
        <Header />
        <Content contentContainerStyle={{ flex: 1 }} scrollEnabled={false}>
          <ScrollView>
       
          {/* Content here */}
         
          </ScrollView>
        
           {/* Footer content here */}
          
        </Content>
      </Container>
```

**Comment by lucianomlima** [comment]
@SupriyaKalghatgi why close this issue? It's not resolved yet.
@akhil-geekyants I will try.

**Comment by SupriyaKalghatgi** [comment]
@lucianomlima As explained above, Footer component is something which remains fixed at bottom of screen.
And your requirement is to have it scrollable, which is something specific to your project requirement. hence closed this after providing proper workaround
