### ISSUE TITLE
Can't install native-base!!!!!

### ISSUE THREAD

**Issue by YufJi** [GeekyAnts/NativeBase#1388]
install the lastest native-base  ERR!!

err: Refusing to download the git repo {"hostname":"github.com","protocol":"https:","repository":"https://github.com/GeekyAnts/react-native-drawer.git"} over HTTPS without a commit
hash - possible certificate error?

who can tell me why and how to solve the problem?

**Comment by YufJi** [comment]
i have know maybe native-base version is wrong , now  i use 2.2.0 , no issue!

**Comment by SupriyaKalghatgi** [comment]
Cool!
