### ISSUE TITLE
Drawer interfering with React Native modal

### ISSUE THREAD

**Issue by embpdaniel** [GeekyAnts/NativeBase#1389]
Hi, is it expected that the Drawer component will interfere/overlap with a React Native Modal? I have made a modal with a Header and a list, and I find that wherever I tap, it closes the drawer behind the modal first. When I tap again the content of the modal now react to my tap. It looks like the drawer is interfering with it and only allows me to tap on the modal elements when the drawer closes.

The button that invokes the modal is part of the drawer content, so the button and the Modal markup is within the drawer content markup. Is that ok, or should I set it up a different way?

## react-native, react and native-base version
react-native: 0.49.3
react: 16.0.0-beta.5
native-base: 2.3.3

## Expected behaviour
React Native Modal should layer over the Drawer, items and header buttons should be clickable
## Actual behaviour
React Native Modal items and header buttons cannot be pressed, as the Drawer seems to somehow interfere
## Is the bug present in both ios and android or in any one of them?
IOS, not sure about Android

**Comment by akhil-geekyants** [comment]
@embpdaniel `tapToClose` prop of Drawer can be used to control closing of the drawer on tap.

Gif

![modalwithdrawer](https://user-images.githubusercontent.com/27768184/33167480-aeaeb656-d063-11e7-9cfe-880c8aee0453.gif)

**Comment by embpdaniel** [comment]
@akhil-geekyants Thanks for the tip. I have tried it but it does not work for me as it does for you in the screenshot. If I set `tapToClose` to false, the entire modal screen is disabled and I cannot tap on any item. If I set `tapToClose` to true, my first tap anywhere on the modal closes the drawer behind the modal. After this my modal receives taps. Let me know your thoughts, thanks.

**Comment by akhil-geekyants** [comment]
Associated with react-native-drawer issue https://github.com/root-two/react-native-drawer/issues/326
