### ISSUE TITLE
How to user onPress in a Card item

### ISSUE THREAD

**Issue by bielcapanema** [GeekyAnts/NativeBase#139]
How can a use onPress prop in a CardItem?
I read about user button prop, but i din't see anything in code, can anyone show an example?

**Comment by sankhadeeproy007** [comment]
The use case is same as in a `ListItem`. Just use `button` prop to `CardItem`.

**Comment by bielcapanema** [comment]
I try but it seems to not work.. can you please show me an example?

**Comment by ALawliet** [comment]
@bielcapanema
```                        
<CardItem button onPress={() => Alert.alert('hi')}>
```
@sankhadeeproy007 where is this documented? First time hearing about `button` prop.

**Comment by SupriyaKalghatgi** [comment]
@ALawliet The latest docs for NativeBase is for v0.5.5
And the `button` prop for `CardItem` has been updated yesterday in 0.5.6 release
This will be soon documented.

**Comment by bielcapanema** [comment]
updated the package and worked for me, thanks!

**Comment by SupriyaKalghatgi** [comment]
Check the latest docs of NativeBase [0.5.9](http://nativebase.io/docs/v0.5.9/)

**Comment by tahsandewan** [comment]
> How can a use onPress prop in a CardItem?
> I read about user button prop, but i din't see anything in code, can anyone show an example?

<CardItem button onPress={function_call()}
