### ISSUE TITLE
Custom Back Buttom Picker IOS

### ISSUE THREAD

**Issue by SeuZeRicardo** [GeekyAnts/NativeBase#1393]
Hi Guys!

I was modifying a Picker Back button.

I read that I can use the **`headerBackButtonText`** property to modify the button, but when implementing I did not get the expected result, which was written **BACK**.

`
               
                      
                   <Picker
                      itemTextStyle={{ color: '#000' }}
                      textStyle={{ color: '#c7c8ca' }}
                      iosHeader="RESTRIÇÃO DE PÚBLICO"
                      headerBackButtonText="Voltar"
                      selectedValue={this.state.campoRestricaoPalco}
                      onValueChange={value => this.setState({ campoRestricaoPalco: value })}
                      style={styles.picker}
                    >
                      <Picker.Item label="Haverá controle de entrada?" value="key0" />
                      <Picker.Item label="Público" value="Público" />
                      <Picker.Item label="Privado" value="Privado" />
                      <Picker.Item label="Restrito" value="Restrito" />
                    </Picker>`

After having discovered this problem and not having implemented this functionality, I tried to modify the Header using **`headerComponent`** and ended up with the following doubt.

on the back button, what do you put on onPress?

If you want to see the code, follow below

`

                  <Picker  
                    headerComponent = { 
                      <Header>
                        <Left>
                          <Button transparent onPress={?????}>
                            <Text>Voltar</Text>
                          </Button>
                        </Left>
                        <Body>
                          <Text style={styles.pickerHeaderTitle}>RESTRIÇÃO DE PÚBLICO</Text>
                        </Body>
                        <Right />
                      </Header>
                      }
                      itemTextStyle={{ color: '#000' }}
                      textStyle={{ color: '#c7c8ca' }}
                      selectedValue={this.state.campoRestricaoPalco}
                      onValueChange={value => this.setState({ campoRestricaoPalco: value })}
                      style={styles.picker}
                    >
                      <Picker.Item label="Haverá controle de entrada?" value="key0" />
                      <Picker.Item label="Público" value="Público" />
                      <Picker.Item label="Privado" value="Privado" />
                      <Picker.Item label="Restrito" value="Restrito" />
                    </Picker>`

Any suggestions on trying to solve any of these problems.

```
React Native -> 0.41.0
Native Base -> 2.1.3
```

**Comment by akhil-geekyants** [comment]
@SeuZeRicardo tested with the latest version of native-base (2.3.3). `headerBackButtonText` was working fine. If possible update to the latest version of native-base. Before updating check the compatibility [here](http://docs.nativebase.io/docs/Compatibility.html).

![pickerheadertext](https://user-images.githubusercontent.com/27768184/33261411-b438c4c2-d388-11e7-8e20-810911277f65.gif)

The back action is provided as a parameter in renderHeader
```
<Picker
      mode="dropdown"
      selectedValue={this.state.selected1
      onValueChange={this.onValueChange.bind(this)}
      renderHeader={(backAction) => {
          return <Header>
                       <Left>
                         <Button transparent onPress={backAction}>
                           <Text>Voltar</Text>
                         </Button>
                       </Left>
                       <Body>
                         <Text>RESTRIÇÃO DE PÚBLICO</Text>
                       </Body>
                       <Right />
                    </Header>
                 }
           }
>
```

See the docs [here](http://docs.nativebase.io/Components.html#picker-def-headref)

**Comment by SeuZeRicardo** [comment]
This corrected my problem, but with Native-Base and React-Native updates just broke my layout.
Thanks for the help, but this solution is not the most viable for me and for my project.

**Comment by akhil-geekyants** [comment]
If you are facing any issues with NativeBase let us know.

**Comment by akhil-geekyants** [comment]
Closing this issue due to no response
