### ISSUE TITLE
Cannot Center Button with NativeBase

### ISSUE THREAD

**Issue by zmerchant17** [GeekyAnts/NativeBase#1394]
Hi, I am trying to center a button on the screen, but cannot do so. Here is my code:
`
<Container>
    <Content>
        <Card>
             <CardItem>
                 <Body>
                      <Button>Text</Button>
                 </Body>
             <CardItem>
        </Card>
    <Content>
</Container>
`
I have tried using justify content, alignItems and a bunch of other things, but am not able to center the button with "Text". Any help? currently, it is just on the left of the screen. I am using android.

**Comment by SupriyaKalghatgi** [comment]
@zmerchant17 `flexDirection: "row", justifyContent: "center"` with `<Body>` should do the work

**Comment by SupriyaKalghatgi** [comment]
Closing this
Please reopen this issue if help needed

**Comment by EmirGluhbegovic** [comment]
I am having issue centering button, If I have <Body> and it wraps <Text> and <Button>, all the components just stay the same, aligned to the left. If I remove the <Text> element then it sometimes works. I find I am fighting NativeBase to get basic flex functionality working. The EasyGrid also is not working as expected. I have ejected the theme so not sure if that could be causing any issues, I havny done any changes though. I simply ejected theme and chose common.

**Comment by SupriyaKalghatgi** [comment]
@EmirGluhbegovic Share your code for centering the Button with NativeBase along with output screenshot

**Comment by farkhandazeb** [comment]
SupriyaKalghatgi thank you so much it worked.

**Comment by rahamin1** [comment]
Any idea why the following doesn't center both the buttons and the text?

```
<Container style={{ backgroundColor: '#fff', paddingTop: 100, alignItems: 'center' }}>
          <Content>
              <Button style={{ margin: 10 }}>
                <Text> Short Text </Text>
              </Button>
              <Button style={{ margin: 10 }}>
                <Text> Very Long Text</Text>
              </Button>
              <View style={{ marginTop: 50 }}>
                <Text style={{ fontSize: 30 }}>
                  Welcome!
                </Text>
              </View>
          </Content>
</Container>
```

**Comment by SupriyaKalghatgi** [comment]
@rahamin1 go through solutions provided abobe

**Comment by rahamin1** [comment]
@SupriyaKalghatgi Tried before writing my comment. Failed.

**Comment by rahamin1** [comment]
Posted also in https://stackoverflow.com/questions/52207028/cannot-center-buttons-horizontally-with-nativebase

**Comment by abkios** [comment]
<Button info style = {{padding: '10%', alignSelf: 'center'}}> 
    <Text>LOGIN</Text>
    </Button> 

Use ( alignSelf: 'centre' ), I was able to move button in centre.

![screen shot 2018-11-07 at 10 37 22 am](https://user-images.githubusercontent.com/44273953/48112723-91cf4400-e279-11e8-9815-e02777fca43f.png)

**Comment by misteroak** [comment]
alignSelf: 'center' solved it for me! :)

**Comment by SeanningTatum** [comment]
Is there a way we can center it depending on the parent component? I don't think manually centering using alignSelf is a good solution. 

It works just fine with React Native's Button component.

**Comment by isair** [comment]
The issues mostly stem from Native Base's `Button` component defining `alignSelf` as `flex-start` by default.

**Comment by devmohit-live** [comment]
style = {{padding: '10%', alignSelf: 'center'}}
