### ISSUE TITLE
Question/Bug: Header shadow is going under Content

### ISSUE THREAD

**Issue by etabard** [GeekyAnts/NativeBase#1399]
## react-native, react and native-base version
React-native : 0.50.4
Native-base: 2.3.3

## Expected behaviour
The header's shadow is drawing over the content view

## Actual behaviour
The header's shadow is under the content view

## Steps to reproduce (code snippet or screenshot)
![header-shadow-bug](https://user-images.githubusercontent.com/335713/33334014-da2ee054-d468-11e7-9061-9a3ff6710922.png)

## Is the bug present in both ios and android or in any one of them?
Tested on IOS, not tested on android

## Any other additional info which would help us debug the issue quicker.
I tried zIndex on the header but it does not have any effect.

Thanks for your help !

**Comment by akhil-geekyants** [comment]
@etabard tried Native base Header component with the above versions and platform. Didn't find anything like above. Can you share the code snippet.

**Comment by etabard** [comment]
Hi,

Thanks for your reply. Here is my TestScreen with the native-base-theme/components/Header.js : https://gist.github.com/etabard/f1130c3ba06f87091a0352666b5890e4

Screen of the result : 
![test-shadow](https://user-images.githubusercontent.com/335713/33475645-710d8292-d67f-11e7-83ab-b062b12ed1de.jpg)

**Comment by akhil-geekyants** [comment]
@etabard setting zIndex to negative values in Content style made the shadow visible. 
```
<Content style={{zIndex:-3}}/>
```

**Comment by etabard** [comment]
Thanks ! I tried everything except negative zIndex :-)
