### ISSUE TITLE
Examples of event handling?

### ISSUE THREAD

**Issue by robtweed** [GeekyAnts/NativeBase#14]
I may be missing something, but I don't see, from the documentation, what events are available for the various components, eg buttons, list items etc.  Could this be added to the documentation please?  The components look great, and I'd love to use them, but don't yet see how.  Many thanks!

**Comment by sankhadeeproy007** [comment]
The `Button` component is actually a wrapper of the `TouchableOpacity` component of React Native. So you can just use the `onPress` callback function for event handling.

**Comment by bitmage** [comment]
Please add this to documentation.  Related question in https://github.com/GeekyAnts/NativeBase/issues/180.
