### ISSUE TITLE
Button with Text and Icon broken on Android

### ISSUE THREAD

**Issue by carlosgarbiatti** [GeekyAnts/NativeBase#140]
Hey, first of all, you guys have been doing a great job. Keep it on!

I have the following code: 

``` 
<Button>
     <Text>Any Text</Text>
     <Icon name="ios-arrow-back"/>
</Button>
```

It works fine on IOs but on Android I've got the following error:

![screen shot 2016-08-25 at 22 27 50](https://cloud.githubusercontent.com/assets/5911810/17965937/346dc2ee-6b13-11e6-9783-c1412013f5ec.png)

I'm using the following versions

```
    "native-base": "0.5.4",
    "react": "~15.2.1",
    "react-native": "^0.31.0",
```

Removing ".toUpperCase()" from the lines 167 and 172 of the Button.js class the problem is fixed.

Thanks!

**Comment by sankhadeeproy007** [comment]
Thanks for reporting. Fixed with 0.5.7
