### ISSUE TITLE
Android: Hamburguer menu on header is not very responsive

### ISSUE THREAD

**Issue by Germanaz0** [GeekyAnts/NativeBase#1402]
Hello, I've installed the seed using redux and typescript, what I've noticed is that when you run the seed on an android device, the hamburguer menu, on header is not very responsive.

When you click it works fine for the 90% of cases, but if you click on some edge, the ripple effect appears and wont open the side menu.

Versions:
 * react-native-cli: 2.0.1
 * react-native: 0.50.3

**Comment by SupriyaKalghatgi** [comment]
@Germanaz0 Have you installed from [ReactNativeSeed.com](https://reactnativeseed.com/)?

**Comment by Germanaz0** [comment]
@SupriyaKalghatgi Yes, I was following the steps from this link [https://reactnativeseed.com/thank-you/8824](https://reactnativeseed.com/thank-you/8824) them are listed below.

* `git clone -b RN git@github.com:GeekyAnts/react-native-boilerplate-redux-typescript.git` 
* `npm install`
* `npm build` & `npm start`
* `npm run android`

**Comment by SupriyaKalghatgi** [comment]
@Germanaz0 Probably this is not the right place for this issue
Please raise issue at [react-native-boilerplate-redux-typescript](https://github.com/GeekyAnts/react-native-boilerplate-redux-typescript)

**Comment by Germanaz0** [comment]
ok @SupriyaKalghatgi made another issue on their repository, thanks

**Comment by Germanaz0** [comment]
Btw, I have been testing in other seeds, and the problem is still the same, it happens when you long press for a bit or tap in the hamburguer menu edge.

As I said before, it does not happens always, but happens

**Comment by Germanaz0** [comment]
@SupriyaKalghatgi does it happen in other seeds ? or on native base itself ?

**Comment by SupriyaKalghatgi** [comment]
@Germanaz0 Not with NativeBase
