### ISSUE TITLE
Weird issue about button with icon right

### ISSUE THREAD

**Issue by maphongba008** [GeekyAnts/NativeBase#1408]
native-base: 2.3.3
react-native: 0.50.4

If there's 1 button, it works normal. But if there're 2 buttons with 1 iconLeft and 1 iconRight, then the UI break
![screen shot 2017-11-29 at 9 23 41 pm](https://user-images.githubusercontent.com/8359203/33379951-19426016-d54c-11e7-9fe4-33118d7a5207.png)
Here is my code: 
```
class Home extends Component {
  render() {
    return (
      <View style={styles.container}>
        <Button iconLeft success>
          <Icon name='arrow-back' />
          <Text>Back</Text>
        </Button>

        <Button iconRight success style={{marginLeft: 10}}>
          <Text>Next</Text>
          <Icon name='arrow-forward' />
        </Button>
      </View>
    )
  }
}
```

**Comment by akhil-geekyants** [comment]
@maphongba008 just simply wrap all your components in `<Container/>`. Read about NativeBase screen structure [here](http://docs.nativebase.io/Components.html#anatomy-headref)

Gif

![iconright01](https://user-images.githubusercontent.com/27768184/33472875-176ba802-d69a-11e7-8ae6-e05a04c868a9.gif)

**Comment by maphongba008** [comment]
@akhil-geekyants  thanks mate, didn't know that I must follow NativeBase structure

**Comment by SupriyaKalghatgi** [comment]
@maphongba008 Yes, thats mentioned in the Docs at very beginning section of `Components`
