### ISSUE TITLE
Icon Alignment in Header and Header Color

### ISSUE THREAD

**Issue by ahmedkassem** [GeekyAnts/NativeBase#141]
when having more than one icon in the left of the header they are not aligned the right way, as the second icon is centered behind the header`s title
this is in iOS only but fine with Android
and in iOS Header Color is not set as in Android

`            <Header>

                    <Button transparent onPress={this.open}>
                        <Icon name="ios-menu" />
                    </Button>

                    <Title>News</Title>

                    <Button transparent onPress={this.openModal2.bind(this)}>
                        <Icon name="ios-albums-outline" />
                    </Button>

                    <Button transparent  onPress={Actions.addnews}>
                        <Icon name="ios-add" />
                    </Button>

            </Header>
`

![ios](https://cloud.githubusercontent.com/assets/7607004/17975325/8bba93e4-6ae9-11e6-9873-2faf06fe6927.jpg)
![android](https://cloud.githubusercontent.com/assets/7607004/17975331/8f1d3956-6ae9-11e6-88c9-d51fa62fbd9c.jpg)

**Comment by bielcapanema** [comment]
![screen shot 2016-08-25 at 3 16 09 pm](https://cloud.githubusercontent.com/assets/14976435/17980718/f8fa7504-6ad6-11e6-89f7-0ab6fda79160.png)

**Comment by sankhadeeproy007** [comment]
Fixed in 0.5.7.
![simulator screen shot aug 26 2016 7 58 39 pm](https://cloud.githubusercontent.com/assets/10998047/18009204/da9b8ace-6bc8-11e6-9972-6f073d98dd7e.png)
