### ISSUE TITLE
Add style placeholder

### ISSUE THREAD

**Issue by tranlehaiquan** [GeekyAnts/NativeBase#1413]
Please add props to style Picker placeholder(Color). Thank you!

**Comment by pranay414** [comment]
Yes, even I need this one!
Thanks @tranlehaiquan for asking this.

**Comment by tranlehaiquan** [comment]
Thanks you 👍

**Comment by SupriyaKalghatgi** [comment]
Added customizable icon color with this

**Comment by SupriyaKalghatgi** [comment]
Fixed with NativeBase [2.3.5](https://github.com/GeekyAnts/NativeBase/releases/tag/v2.3.5)

**Comment by dhuma-shipmnts** [comment]
How to set icon in Placeholder for Android?

**Comment by dhuma1981** [comment]
How to get the same for Android? I am unable to place the icon for android picker.

**Comment by SupriyaKalghatgi** [comment]
@dhuma1981 icon, thats something default

**Comment by dhuma1981** [comment]
But when I apply backgroundColor in style it is not visible. Is there anyother way to apply background color to Picker? and also show the down-arrow Icon in android?

**Comment by SupriyaKalghatgi** [comment]
Android Picker is not much customizable, React Native does not provide this
