### ISSUE TITLE
Scrollable Tabs showing weird borders at some tabs

### ISSUE THREAD

**Issue by christianversloot** [GeekyAnts/NativeBase#1415]
Hi there,

Unfortunately could not find a solution within your current issue tracker, so opened the one following next.

## react-native, react and native-base version
    "native-base": "^2.3.3",
    "react": "16.0.0",
    "react-native": "0.50.4"

## Expected behaviour
No borders

## Actual behaviour
Borders when clicking/swiping to some tabs:

![image](https://user-images.githubusercontent.com/6450612/33521024-7a1d2b4c-d7c6-11e7-8d95-12989a13206f.png)

![image](https://user-images.githubusercontent.com/6450612/33521028-834ed8dc-d7c6-11e7-8980-e79ed3e78949.png)

## Steps to reproduce (code snippet or screenshot)

Code pretty much equal to demo code, the behaviour also occurs when running the demo code:

```
import React, { Component } from 'react';
import { ScrollableTab, Container, Content, Footer, Header, Title, Button, Left, Right, Body, Icon, Text, Tabs, Tab } from 'native-base';

export default class HeaderExample extends Component<{}> {
  render() {
    return (
      <Container>
        <Header hasTabs>
          <Left>
            <Button transparent>
              <Icon name='menu' />
            </Button>
          </Left>
          <Body>
            <Title>Actueel onweer</Title>
          </Body>
          <Right />
        </Header>
        <Tabs renderTabBar={()=> <ScrollableTab />}>
          <Tab heading="Onweerradar">
            <Text>1</Text>
          </Tab>
          <Tab heading="Liveblog">
            <Text>2</Text>
          </Tab>
          <Tab heading="Waarschuwingen">
            <Text>3</Text>
          </Tab>
          <Tab heading="Informatie">
            <Text>4</Text>
          </Tab>
        </Tabs>
      </Container>
    );
  }
}
```

## Screenshot of emulator/device
Screenshot attached above.

## Is the bug present in both ios and android or in any one of them?
Android tested, iOS not tested.

## Any other additional info which would help us debug the issue quicker.

Negative.

**Comment by christianversloot** [comment]
Any clues? @akhil-geekyants

**Comment by akhil-geekyants** [comment]
@christianversloot try setting `backgroundColor` in tabsContainerStyle of `<ScrollableTab/>` to the required color for each platform. 
Like
```
<ScrollableTab tabsContainerStyle={{ backgroundColor: platform == 'ios' ? '#F8F8F8' : '#3F51B5' }}
```

**Comment by christianversloot** [comment]
This fixes the problem, thanks 👍 😄
