### ISSUE TITLE
Add native base text component to Label component, to be able to create custom styles

### ISSUE THREAD

**Issue by karlAlnebratt** [GeekyAnts/NativeBase#1420]
Hi! Thanks for trying out NativeBase!
Due to the overwhelming requests and issues/questions we ask you to add the following details with your issue.

Please check the existing open/closed issues for a possible duplicate before creating a new issue :)

Also **DO** fill out the below form to give us a better idea about your environment and help us debug it quicker. Issues without the required details will mostly be unattended to.

## react-native, react and native-base version
"native-base": "2.3.3"
"react": "16.0.0"
"react-native": "0.50.4"

## Expected behaviour
 - To be able to att `font-family` styling to a label
## Actual behaviour
 - Native base `Label` do not use native base `Text` component. That will cause `connectStyles` to not add custom styling to the `Text` component
## Steps to reproduce (code snippet or screenshot)
 - Create a new react native project and install native base
 - Add a custom font 
 - Eject the theme
 - Add folowing to App.js
```javascript
import React, { Component } from 'react';
import PropTypes from 'prop-types'
import { Container, Header, Content, Form, Item, Input, View, Label, Button, Text, StyleProvider } from 'native-base'

import getTheme from './theme/components'
import theme from './theme/variables/theme'


export default class App extends Component {
  render() {
    return (
      <StyleProvider style={getTheme(theme)}>
        <Container>
          <Header />
          <Content padder contentContainerStyle={{ justifyContent: 'center', flex: 1 }}>
            <Form>
              <Item>
                <Label customLabel>Username</Label>
                <Input
                  keyboardType="email-address"
                  autoCorrect={false}
                  autoCapitalize="none"
                />
              </Item>
              <Item floatingLabel regular>
                <Label>Password</Label>
                <Input secureTextEntry />
              </Item>
              <Button block onPress={this.submit} >
                <Text>Login</Text>
              </Button>
            </Form>
          </Content>
        </Container>
      </StyleProvider>
    );
  }
}
```
- Add custom styling for text fontFamily to `./theme/components/Text.js`
```
...
},
".customLabel": {
  fontFamily: 'Austin-Light',
}
...
```
## Screenshot of emulator/device
The label should have a different font
![simulator screen shot - iphone 6 - 2017-12-05 at 11 43 00](https://user-images.githubusercontent.com/1122820/33603063-a0a20c32-d9b1-11e7-8dd4-a304539145c9.png)

## Is the bug present in both ios and android or in any one of them?
Both on ios and android

**Comment by akhil-geekyants** [comment]
@karlAlnebratt shouldn't we add `customLabel ` to label theme instead of `textTheme`.

**Comment by karlAlnebratt** [comment]
Yes that might be a better solution
