### ISSUE TITLE
SwipeRow not exported in TypeScript definition

### ISSUE THREAD

**Issue by SaltyDH** [GeekyAnts/NativeBase#1423]
Hi! Thanks for trying out NativeBase!
Due to the overwhelming requests and issues/questions we ask you to add the following details with your issue.

Please check the existing open/closed issues for a possible duplicate before creating a new issue :)

Also **DO** fill out the below form to give us a better idea about your environment and help us debug it quicker. Issues without the required details will mostly be unattended to.

## react-native, react and native-base version
Native-Base version: 2.3.3
## Expected behaviour
SwipeRow should be exported from index.d.ts

## Actual behaviour
SwipeRow is not currently exported

## Steps to reproduce (code snippet or screenshot)
Try and import SwipeRow into a TypeScript solution using:

Import { SwipeRow } from 'native-base';

**Comment by SaltyDH** [comment]
Thankyou!

**Comment by Tzinov15** [comment]
When will a fix for this go in? It seems like there's a big discrepancy between the docs (which seem to show `v2.2.0`), the actual code that's inside the latest for `v2.5.0`, and the proposed API (via Typescript definitions) that is in the commit above. @akhil-geekyants any updates on this? Would love to know at the very least if SwipeRow is planned on being maintained in the future so I know whether to continue building on top of it

**Comment by SupriyaKalghatgi** [comment]
Fixed with [2.3.6](https://github.com/GeekyAnts/NativeBase/releases/tag/v2.3.6)
