### ISSUE TITLE
Fab not visible or in wrong position when put inside Content

### ISSUE THREAD

**Issue by ceefour** [GeekyAnts/NativeBase#1427]
## react-native, react and native-base version

```json
{
  "main": "node_modules/expo/AppEntry.js",
  "private": true,
  "scripts": {
    "test": "node ./node_modules/jest/bin/jest.js --watch"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "@expo/samples": "2.1.1",
    "@expo/vector-icons": "^6.2.1",
    "expo": "^23.0.0",
    "firebase": "^4.6.2",
    "moment": "^2.19.3",
    "native-base": "^2.3.3",
    "react": "16.0.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-23.0.0.tar.gz",
    "react-native-datepicker": "^1.6.0",
    "react-native-keyboard-spacer": "^0.4.1",
    "react-navigation": "^1.0.0-beta.19",
    "react-redux": "^5.0.6",
    "redux": "^3.7.2",
    "redux-logger": "^3.0.6",
    "redux-thunk": "^2.2.0",
    "validate.js": "^0.12.0"
  },
  "devDependencies": {
    "jest-expo": "^23.0.0"
  }
}
```

## Expected behaviour

Fab is shown like the example.

## Actual behaviour

if Content contains only Fab: Fab is invisible

if Content contains other components: Fab is shown in the wrong position (e.g. right top when is should be bottomRight)

## Steps to reproduce (code snippet or screenshot)

```xml
<Content style={{flex: 1}}>
  <Fab position="bottomRight">
    <Icon name="add"/>
  </Fab>
</View>
```

(note: adding or removing flex=1 has no effect)

I think I'm using this wrong...

Please add a Fab demo to KitchenSink that uses Fab with Content and List (which is a typical use case, rather than an empty View like current examples)

## Screenshot of emulator/device

![screenshot_20171208-104150](https://user-images.githubusercontent.com/24123/33750172-af0ae9e2-dc04-11e7-8c0c-0901390b2f19.jpg)

## Is the bug present in both ios and android or in any one of them?

Tested in Android 7.0 only.

## Any other additional info which would help us debug the issue quicker.

Please add a Fab demo to KitchenSink that uses Fab with Content and List (which is a typical use case, rather than an empty View like current examples)

**Comment by ceefour** [comment]
"Workaround": this suggestion works: http://discuss.nativebase.io/t/how-to-use-a-fab-in-page-with-a-list/237/2

If this is the official recommendation, I suggest putting it in the KitchenSink/docs as it's a very common use case.

**Comment by SupriyaKalghatgi** [comment]
@ceefour Proper use case says, use FAB inside `Container`
I will add this to docs though

**Comment by ceefour** [comment]
@SupriyaKalghatgi , thanks, current docs / examples use Fab inside View

**Comment by oferRounds** [comment]
@SupriyaKalghatgi following this issue, I’d like to present my `FAB` over a `List` – make it always visible on the right-bottom with a fixed position, floating above the list. 

The thing is that I was only manage to present it on the end of the list; i.e., if the list is longer then a screen height, then it won’t be visible until the user scrolls to the end.

Any idea how to work around this issue?

**Comment by SupriyaKalghatgi** [comment]
@oferRounds Container, FAB, Content, List
Try wrapping in this order

**Comment by oferRounds** [comment]
Thanks @SupriyaKalghatgi!

**Comment by SupriyaKalghatgi** [comment]
I have opened this issue on the docs repo here: [#69](https://github.com/GeekyAnts/native-base-docs/issues/69)
Since we split the docs and the source into separate repos.
