### ISSUE TITLE
Native Base: How to select the next TextInput after pressing the “next” keyboard button?

### ISSUE THREAD

**Issue by ap050492** [GeekyAnts/NativeBase#1429]
Hello,

How to select the next TextInput after pressing the “next” keyboard button?i tried with below code but it's not working, please help,

//Funcation
_focusNextField(nextField) {
    this.refs[nextField].focus()    
}

// UI
<Item regular>
     <Input  value={this.state.agencyName}   
                  onSubmitEditing={() => this._focusNextField('agencyNo')}
                  returnKeyType = {"next"} 
                  ref="agencyName"
                  blurOnSubmit={false}                            
                  onChangeText={agencyName => this.setState({agencyName: agencyName})} 
                  style={{ height: 40 }} />
</Item>
<Item regular>
     <Input keyboardType="phone-pad"  
                 value={this.state.agencyFEIN} 
                 ref="agencyNo" 
                 onChangeText={agencyNo=> this.setState({agencyNo: agencyNo})} 
                 style={{ height: 40 }} />
</Item>

**Comment by akhil-geekyants** [comment]
@ap050492 replace 
```
this.refs[nextField].focus()
```
by
```
this.refs[nextField]._root.focus()
```

**Comment by ap050492** [comment]
Thanks, but now working...
when i print refs in console {console.log(this.refs)}  it's showing like below 
{}
__proto__
:
constructor
:
ƒ Object()
hasOwnProperty
:
ƒ hasOwnProperty()
isPrototypeOf
:
ƒ isPrototypeOf()
propertyIsEnumerable
:
ƒ propertyIsEnumerable()
toLocaleString
:
ƒ toLocaleString()
toString
:
ƒ toString()
valueOf
:
ƒ valueOf()
__defineGetter__
:
ƒ __defineGetter__()
__defineSetter__
:
ƒ __defineSetter__()
__lookupGetter__
:
ƒ __lookupGetter__()
__lookupSetter__
:
ƒ __lookupSetter__()
get __proto__
:
ƒ __proto__()
set __proto__
:
ƒ __proto__()

**Comment by akhil-geekyants** [comment]
@ap050492 Pasting the modified code

Code

```
import React, { Component } from 'react';
import { Container, Header, Content, Form, Item, Input, Label, List, ListItem, Button, Icon, Text } from 'native-base';
import { View, TextInput, ScrollView } from 'react-native'

export default class App extends Component {

  constructor(props) {
    super(props)
    this.state = { agencyName: '', agencyFEIN: '' }
    this._focusNextField = this._focusNextField.bind(this)
  }

  _focusNextField(nextField) {
    this.refs[nextField]._root.focus()
  }

  render() {
    return (
      <Container>
        <Content>
          <Input
            ref="agencyName"
            onSubmitEditing={() => this._focusNextField('agencyNumber')}
            returnKeyType={"next"}
            blurOnSubmit={false}
            placeholder="agency name"
            onChangeText={agencyName => this.setState({ agencyName: agencyName })}
            value={this.state.agencyName}
            style={{ height: 40 }} />

          <Input
            ref="agencyNumber"
            keyboardType="phone-pad"
            value={this.state.agencyFEIN}
            onChangeText={agencyFEIN => this.setState({ agencyFEIN: agencyFEIN })}
            onSubmitEditing={() => this._focusNextField('agencyName')}
            placeholder="phone"
            style={{ height: 40 }} />
        </Content>
      </Container>
    );
  }
}

```

Gif

![textinput](https://user-images.githubusercontent.com/27768184/33767971-36c65854-dc4a-11e7-8689-36ad2569be0c.gif)

**Comment by akhil-geekyants** [comment]
Closing this issue due to no response

**Comment by rahamin1** [comment]
@ap050492 Did you find a solution?
