### ISSUE TITLE
placeholderTextColor prop on Components/Widgets/Input.js

### ISSUE THREAD

**Issue by cavilaho** [GeekyAnts/NativeBase#143]
In the [Components/Widget/Input.js ](https://github.com/GeekyAnts/NativeBase/blob/75ef442f50675a5f10eb5e765b33faccbf2c1afa/Components/Widgets/Input.js#L38)file, the the `placeholderTextColor` prop is defined as follows:

`placeholderTextColor={ this.props.placeholderTextColor ? this.props.placeholderTextColor : this.getContextForegroundColor() ? this.getContextForegroundColor() : this.getTheme().inputColorPlaceholder } 
`

This makes that the color defined in a personal theme (in the case that you may be developing its own theme) won't ever be selected, because the property `this.getContextForegroundColor ()` is defined in [Components / Base / NativeBaseComponent.js](https://github.com/GeekyAnts/NativeBase/blob/75ef442f50675a5f10eb5e765b33faccbf2c1afa/Components/Base/NativeBaseComponent.js#L31-L33), and `foregroundColor` is defined as: 

`foregroundColor: this.props.foregroundColor? this.props.foregroundColor: this.getTheme () textColor.`

My proposal is to change the definition of palceholderTextColor to

`placeholderTextColor={ this.props.placeholderTextColor ? this.props.placeholderTextColor : this.getTheme().inputColorPlaceholder ? this.getTheme().inputColorPlaceholder : this.getContextForegroundColor() }`

**Comment by sankhadeeproy007** [comment]
I think you're using an older version of native-base. Please refer to the link you attached and check the code again. foregroundColor has been removed. It will fall back to the inputColorPlaceholder variable by default.

**Comment by cavilaho** [comment]
I installed the library by npm, but you're totally right. My bad.

Thanks.
