### ISSUE TITLE
How Swipable List use FlatList not ListView?

### ISSUE THREAD

**Issue by Jancat** [GeekyAnts/NativeBase#1430]
## react-native, react and native-base version
react-native 0.49
react 16.0.0
native-base 2.3.4

## Expected behaviour
Use Swipable List with recommended FlatList

## Actual behaviour
Now the example in the docs using Swipable List with depleted ListView

## Steps to reproduce (code snippet or screenshot)
```js
render() {
    const ds = new ListView.DataSource({ rowHasChanged: (r1, r2) => r1 !== r2 });
    return (
      <Container>
        <Header />
        <Content>
          <List
            dataSource={this.ds.cloneWithRows(this.state.listViewData)}
            renderRow={data =>
              <ListItem>
                <Text> {data} </Text>
              </ListItem>}
            renderLeftHiddenRow={data =>
              <Button full onPress={() => alert(data)}>
                <Icon active name="information-circle" />
              </Button>}
            renderRightHiddenRow={(data, secId, rowId, rowMap) =>
              <Button full danger onPress={_ => this.deleteRow(secId, rowId, rowMap)}>
                <Icon active name="trash" />
              </Button>}
            leftOpenValue={75}
            rightOpenValue={-75}
          />
        </Content>
      </Container>
    );
```

## Question
How can I use `FlatList` with Swipeable List and Swipeable Row?

**Comment by akhil-geekyants** [comment]
@Jancat Pasting a sample code
```
import React, { Component } from 'react';
import { Container, Header, Content, SwipeRow, View, Text, Icon, Button } from 'native-base';
import { FlatList } from 'react-native'

export default class App extends Component {
  constructor(props) {
    super(props)
    this.state = { data: [{ key: 1, value: 'one' }, { key: 2, value: 'two' }, { key: 3, value: 'three' }, { key: 4, value: 'four' }, { key: 5, value: 'five' }] }
  }

  removeItem(key) {
    let data = this.state.data
    data = data.filter((item) => item.key !== key)
    this.setState({ data })
  }

  render() {
    return (
      <Container>
        <Header />
        <Content scrollEnabled={false}>

          <FlatList
            data={this.state.data}
            renderItem={({ item }) => <SwipeRow
              leftOpenValue={75}
              rightOpenValue={-75}
              left={
                <Button success onPress={() => alert(item.value)} >
                  <Icon active name="add" />
                </Button>
              }
              body={
                <View>
                  <Text style={{ paddingLeft: 15 }}>{item.value}</Text>
                </View>
              }
              right={
                <Button danger onPress={() => this.removeItem(item.key)}>
                  <Icon active name="trash" />
                </Button>
              }
            />}
          />
        </Content>
      </Container>
    );
  }
}
```

Gif

![swiperow](https://user-images.githubusercontent.com/27768184/33764536-bf4a5f6e-dc3a-11e7-8a77-24e3ec327f07.gif)

**Comment by Jancat** [comment]
@akhil-geekyants Thanks, I thought about this way using `SwipeRow`.
But the default behavior such closing rows when other rows are opened will be lost.
And the press event seems to be invalid, like this:

```js
renderItem={({ item }) => (
  <TouchableHighlight onPress={() =>alert('press')}>  // don't alert
    <SwipeRow ... />
  </TouchableHighlight >
)       
```

I want to know whether there is a plan to use FlatList in Swipable List for better performance?

**Comment by akhil-geekyants** [comment]
yes, NativeBase will be using FlatList in the upcoming major release.

**Comment by Jancat** [comment]
By the way. I can't customize list item style in `SwipeRow`. 
Such as I can't modify the default `SwipeRow` `body` style below:
![image](https://user-images.githubusercontent.com/11827786/33983916-c99b58dc-e0f0-11e7-89c8-09c9981b5e67.png)

Why not give a `style` property ?

**Comment by SupriyaKalghatgi** [comment]
Fixed with [2.3.6](https://github.com/GeekyAnts/NativeBase/releases/tag/v2.3.6)

**Comment by amrit-sahoo** [comment]
Swipe row with flat list have slow animations on swiping left or right? 
My renderItem goes like this.
`<SwipeRow
        disableRightSwipe
        rightOpenValue={-100}
        style={{ padding: 0 }}
        body={
          <TouchableWithoutFeedback
            onPress={() =>
                this.props.navigation.navigate('newsfeedDetails', {
                  data: this.props.data,
                  isBookmarkRequired: false,
                })
                }
           >     
            <View style={styles.container}>
              <Image
                style={styles.imgContainer}
                source={{ uri: unescape(this.props.data.img) }}
              />
              <View style={styles.infoContainer}>
                <H3 color='primary' style={{ margin: 0 }} numberOfLines={2} text={unescape(this.props.data.title)} />
                <View style={styles.textStyle}>
                  <H4 style={styles.authorTextStyle} color='legend' numberOfLines={1} text={`by ${this.props.data.authorName}`} />
                  <H4 style={styles.publishedTextStyle} color='legend' text={moment(this.props.data.publishedAt).startOf('second').fromNow()} />
                </View>
              </View>
            </View>
          </TouchableWithoutFeedback>
        }
        right={
          <Button
            danger
            onPress={() => Alert.alert(
            'Alert',
            'Are you sure you want to remove ?',
            [
              {
                text: 'No',
                onPress: () => console.log('Cancel Pressed'), 
                style: 'cancel',
              },
              {
                text: 'Yes',
                onPress: () => {
                  const { createdAt } = this.props.data;
                  this.props.deleteBookmarkApiRequest({ createdAt });
                },
              },
            ],
            { cancelable: true },
            )}
          >
            <Text style={{ color: 'white', fontSize: 16 }}>Remove</Text>
          </Button>
        }
        />`

**Comment by gs-rbarman** [comment]
Does NativeBase 2.12.0 use FlatList for Swipable List too @akhil-geekyants ?

**Comment by iKrushYou** [comment]
@akhil-geekyants do you know if NativeBase ever switched over to `FlatList`?
