### ISSUE TITLE
How to remove ... it ???

### ISSUE THREAD

**Issue by phamdung103** [GeekyAnts/NativeBase#1433]
When I press the button. I want to remove it

![img_20171209_171458](https://user-images.githubusercontent.com/8158019/33794807-f4100020-dd05-11e7-8669-44b84a1f4f46.jpg)

## My code: 
```
    render() {
        return (
                        <Button full style={{  borderRadius: 15  }}>
                            <Icon name="facebook" style={styles.iconFB} />
                            <Text style={styles.textFB}>Login with Facebook</Text>
                        </Button>
        );
    }
```

## My dependencies: 
    "native-base": "^2.3.5",
    "react": "16.0.0",
    "react-native": "0.51.0",
    "react-native-vector-icons": "^4.4.2",
    "react-navigation": "^1.0.0-beta.21"

## My devices:
Genymotion (Google Nexus 5 - 5.1.0 API 22)
Xiaomi Redmi note 4x (7.1.0)

**Comment by SupriyaKalghatgi** [comment]
#1206
