### ISSUE TITLE
The demo  doesn't work

### ISSUE THREAD

**Issue by kk412027247** [GeekyAnts/NativeBase#1434]
### description

I flow the demo, but the code doesn't work.
The content component is missing, 
and the header component is missing in IOS , 
and the footer component is missing in android.

I very puzzle than why this happen. 
Can someone help me ?

### code
```
import React, { Component } from 'react';
import { Container, Header, Title, Content, Footer, FooterTab, Button, Left, Right, Body, Icon, Text } from 'native-base';
export default class AnatomyExample extends Component {
  render() {
    return (
      <Container>
        <Header>
          <Left>
            <Button transparent>
              <Icon name='menu' />
            </Button>
          </Left>
          <Body>
          <Title>Header</Title>
          </Body>
          <Right />
        </Header>
        <Content>
          <Text>
            This is Content Section
          </Text>
        </Content>
        <Footer>
          <FooterTab>
            <Button full>
              <Text>Footer</Text>
            </Button>
          </FooterTab>
        </Footer>
      </Container>
    );
  }
}

"native-base": "^2.3.5",
 "react": "16.0.0",
 "react-native": "0.51.0".

```

### screen

<img width="854" alt="2017-12-09" src="https://user-images.githubusercontent.com/30715186/33796835-8716433a-dd37-11e7-8ab3-7cf4223ba8a3.png">

**Comment by SupriyaKalghatgi** [comment]
@kk412027247 I dont find any issue

![simulator screen shot - iphone 7 - 2017-12-11 at 11 21 29](https://user-images.githubusercontent.com/13464885/33817406-766469d4-de65-11e7-8ec2-5315962be416.png)

dependencies
```
"expo": "23.0.1",
"native-base": "^2.3.5",
"react": "16.0.0",
"react-native": "0.50.1",
```

**Comment by SupriyaKalghatgi** [comment]
@kk412027247 You can try re-installing native-base

**Comment by kk412027247** [comment]
@SupriyaKalghatgi I didn't use the expo. I use the the native code

**Comment by akhil-geekyants** [comment]
@kk412027247 tried your code. It is working fine. 

Gif

![footer](https://user-images.githubusercontent.com/27768184/33924513-60cd5d68-dffc-11e7-8853-c72a7b4bc3c0.gif)

**Comment by kk412027247** [comment]
@akhil-geekyants 
Thank you very much.
Finally,It is working fine.
I use this code as a child component to the App, perhaps this reason did cause the bug.

<img width="1440" alt="10 55 14" src="https://user-images.githubusercontent.com/30715186/33945447-0f572ea6-e05a-11e7-9920-5810211075dc.png">
