### ISSUE TITLE
Latest version? Changelog?

### ISSUE THREAD

**Issue by kbrandwijk** [GeekyAnts/NativeBase#1439]
Homepage says latest version is 2.3.3, docs are on 2.2.0, npm says 2.3.5...

**Comment by SupriyaKalghatgi** [comment]
@kbrandwijk 
About homepage, yes we are checking it
Docs, it becomes difficult to update on every patch release. But yes, we are looking into this. Its on our list. Very soon this will be resolved

**Comment by SupriyaKalghatgi** [comment]
ChangeLog and Release Notes are up-to-date

**Comment by SupriyaKalghatgi** [comment]
I have opened this issue on the docs repo here: [#70](https://github.com/GeekyAnts/native-base-docs/issues/70)
Since we split the docs and the source into separate repos.
