### ISSUE TITLE
Thin unwanted lines bellow ListItem content (only in iOS)

### ISSUE THREAD

**Issue by mhyousefi** [GeekyAnts/NativeBase#1444]
I have a block of code that looks like this:
```
<View row reverse style={{flex: 4, height: 50}}>
  <ListItem>
    <StyledText style={{margin: 5}}>txt</StyledText>
    <Icon
      name={...}
      onPress={this._onSelectBtn1}
    />
  </ListItem>
  <ListItem>
    <StyledText style={{margin: 5}}>txt</StyledText>
    <Icon
      name={...}
      onPress={this._onSelectBtn2}
    />
  </ListItem>
</View>
```
Everything looks flawless in my Android build, but in iOS, there are weird thin lines bellow each <ListItem> content as shown in the picture bellow. This happens both in Xcode simulator as well as on a device.

<img width="209" alt="screen shot 2017-12-11 at 8 35 10 pm" src="https://user-images.githubusercontent.com/23746875/33843822-a94d7c2a-deb3-11e7-8f7c-876869c5bd1d.png">

How can I fix this??

my config:
`"react-native": "0.48.4",`
`"native-base": "2.3.3"`

**Comment by akhil-geekyants** [comment]
@mhyousefi use noBorder prop of `<ListItem/>` .
 ```
<ListItem noBorder>
```

**Comment by mhyousefi** [comment]
Thank you @akhil-geekyants 
Adding the prop `noBorder` resolved the problem for me.
