### ISSUE TITLE
Transparent Header

### ISSUE THREAD

**Issue by WoodsterId** [GeekyAnts/NativeBase#1446]
Hallo, i have one problem with header in native base, how do i make the header transparent ?
I've been looking for this problem but did not find the solution.

![screenshot from 2017-12-12 14-26-14](https://user-images.githubusercontent.com/32380621/33872351-1a72bad8-df49-11e7-9145-790c2ff77c7e.png)

and why my title can not move to center?

**Comment by akhil-geekyants** [comment]
@WoodsterId you can make the header transparent by setting the backgroundColor:'transparent' in <Header/> style prop

```
 <Header style={{ backgroundColor: 'transparent' }}>
```
or you can [eject the theme](http://docs.nativebase.io/Customize.html#Customize) and set the `toolbarDefaultBg` in `native-base-theme/variables/*.js`

Header title is positioned based on the Material design guidelines. That is why title is aligned on the left of the header.

You can override the styles of `<Body/>` and `<Right/>` components to bring the title to center.

Also if you have [ejected the theme](http://docs.nativebase.io/Customize.html#Customize) you can modify the header theme in `native-base-theme/components/Header.js`

**Comment by WoodsterId** [comment]
@akhil-geekyants awesome, thanks for your response, problem solved.
![screenshot from 2017-12-12 19-09-14](https://user-images.githubusercontent.com/32380621/33883890-262cbd34-df70-11e7-8999-375ad312d516.png)
I understand better now, thank you @akhil-geekyants

**Comment by ydv0121** [comment]
set
Header style={{elevation:0}}
its works
thank you @ChetanGodiya4

**Comment by SupriyaKalghatgi** [comment]
The `noShadow` prop of Header removes shadow from iOS Header and elevation from Android Header.

https://docs.nativebase.io/Components.html#header-no-shadow-headref
