### ISSUE TITLE
Nothing is shown inside <Content>

### ISSUE THREAD

**Issue by AleksandarAleksandrov** [GeekyAnts/NativeBase#1450]
I'm experiencing the following problem:
No mater what I set in `Content` nothing is visualized, not even a simple `<Text>` 

```js

import React, { Component } from 'react'
import { Container, Header, Body, Content, Title, Text } from 'native-base';
import LoginForm from './LoginForm'

export default class LoginPage extends Component {
    render() {
        return (
            <Container>
                <Header>
                    <Body>
                        <Title>Login</Title>
                    </Body>
                </Header>
                <Content>
                    <Text>Sample</Text>
                    <LoginForm />
                </Content>
            </Container>
        )
    }
}
``` 

```js
import React, { Component } from 'react'
import { AsyncStorage, View } from 'react-native'
import { Field, reduxForm } from 'redux-form'
import { fetchStartupData, setAuthToken } from '../../actions/startupActions'
import { Button, Text, Form } from 'native-base';

import axios from '../../axios/authAxios'
import { withRouter } from 'react-router'
import renderInput from '../form/input'

class LoginForm extends Component {

    handleSubmitLog = (values) => {
        axios().post('/users/login', jsonToFormData(values))
            .then(res => res.data)
            .then(async (authToken) => {
                await AsyncStorage.setItem('authToken', authToken)
                this.props.dispatch(setAuthToken(authToken))
                this.props.history.push('/start')
                this.props.dispatch(fetchStartupData())
            })
    }

    render() {
        return (
            <View>
                <Form>
                    <Field name="email" keyboardType="email-address" component={renderInput} />
                    <Field name="password" secureTextEntry component={renderInput} />
                    <Button block primary onPress={this.handleSubmitLog}>
                        <Text>Submit</Text>
                    </Button>
                </Form>
            </View>
        )
    }

}

export default withRouter(reduxForm({
    form: 'login' // a unique identifier for this form
})(LoginForm))
```

It just shows an empty screen:
![image](https://user-images.githubusercontent.com/9517720/33967522-78cd32a6-e06c-11e7-8001-60b19c63d702.png)

```json
  "dependencies": {
    "axios": "^0.17.1",
    "native-base": "^2.3.5",
    "react": "16.0.0",
    "react-native": "0.51.0",
    "react-redux": "^5.0.6",
    "react-router": "^4.2.0",
    "react-router-native": "^4.2.0",
    "redux": "^3.7.2",
    "redux-devtools-extension": "^2.13.2",
    "redux-form": "^7.2.0",
    "redux-thunk": "^2.2.0",
    "reselect": "^3.0.1"
  }
```

Any ideas ?

**Comment by akhil-geekyants** [comment]
@AleksandarAleksandrov tried a similar code. Were able to see the components. Can you share the code for `renderInput`

Gif

![reduxform2](https://user-images.githubusercontent.com/27768184/33981190-dbcbc268-e0d1-11e7-8cac-4aac4d891bda.gif)

**Comment by AleksandarAleksandrov** [comment]
This is the code for renderInput:

```js
import React from 'react';
import { Input, Text, Item, Icon } from 'native-base';

export default function renderInput({ input, label, type, meta: { touched, error, warning } }){
    let hasError = false;
    if (error !== undefined) {
        hasError = true;
    }
    return (
        <Item error={hasError}>
            <Icon active name={input.name === "email" ? "person" : "unlock"} />
            <Input {...input} />
            {hasError ? <Text>{error}</Text> : <Text />}
        </Item>
    )
}
```

**Comment by akhil-geekyants** [comment]
@AleksandarAleksandrov tried your code. Couldn't find any issue. Attaching a gif

Gif

![reduxform](https://user-images.githubusercontent.com/27768184/33983272-8c27792a-e0d9-11e7-8624-812424e059d4.gif)

**Comment by AleksandarAleksandrov** [comment]
Deleted node_modules and rebuild the whole application again.

Still nothing is shown.

When I remove the native-base it works!

![image](https://user-images.githubusercontent.com/9517720/33986604-c11f7cee-e0c6-11e7-8373-2f0318c7d8d2.png)

**Comment by AleksandarAleksandrov** [comment]
I will later upload the code to a git repo.

**Comment by AleksandarAleksandrov** [comment]
The code is at:

https://github.com/AleksandarAleksandrov/native-base-test-issue-1450

**Comment by SupriyaKalghatgi** [comment]
@AleksandarAleksandrov Its very strange that you are not finding the code running, whereas we are unable to replicate your issue on our side.
May be you must check with installation and cache issues
Delete node_modules, delete yarn.lock, install node_modules with nativebase 2.3.5, run `npm start -- --reset-cache`, then run your app

**Comment by Ickerday** [comment]
Can confirm the issue happening randomly regardless of what's inside <Content>. In some screens it works as expected, in some it doesn't. Maybe it has something to do with react-navigation?

**Comment by SupriyaKalghatgi** [comment]
@Ickerday I dont think so

**Comment by SupriyaKalghatgi** [comment]
@AleksandarAleksandrov Any updates?

**Comment by iiqmohamad** [comment]
I'm facing this issue on production mode. But everything ok on development.
Any clue?

**Comment by akhil-geekyants** [comment]
@iiqmohamad can you share your `package.json`.

**Comment by iiqmohamad** [comment]
@akhil-geekyants my package.json

`{
  "name": "APP",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "axios": "^0.17.1",
    "native-base": "^2.3.5",
    "react": "16.0.0",
    "react-native": "0.51.0",
    "react-navigation": "^1.0.0-beta.22",
    "react-redux": "^5.0.6",
    "redux": "^3.7.2",
    "redux-logger": "^3.0.6",
    "redux-persist": "^5.4.0",
    "redux-thunk": "^2.2.0"
  },
  "devDependencies": {
    "babel-jest": "22.0.4",
    "babel-preset-react-native": "4.0.0",
    "jest": "22.0.4",
    "react-test-renderer": "16.0.0"
  },
  "jest": {
    "preset": "react-native"
  }
}
`

**Comment by iiqmohamad** [comment]
@akhil-geekyants  yup, it's fine when I use `"native-base": "^2.3.3"` on my previouse project

**Comment by akhil-geekyants** [comment]
@iiqmohamad just created a release build apk - A simple counter example with Redux with the above packeges. Couldn't see any issue. Sharing the apk

[app-release.apk.zip](https://github.com/GeekyAnts/NativeBase/files/1630722/app-release.apk.zip)

can you just check downgrading your project to 2.3.3 and check whether the issue is present

**Comment by iiqmohamad** [comment]
Thanks @akhil-geekyants , solved by reinstalling react-native.
After `npm install react-native --save`  , react-native version changed to `"^0.51.0" `

**Comment by asaschachar** [comment]
Hi, I just ran into this issue and I believe it occurs when the `<Container>` component is wrapped in a `<View>` component. See minimally reproduce-able state showing the empty content:

https://snack.expo.io/@asametrical/native-base-content-empty

@akhil-geekyants and @AleksandarAleksandrov, I believe you all were having difficulty reproducing the error because the `LoginPage` was being rendered in a parent component that wrapped it in a `<View>` which was not being shared. Does that sound accurate?
