### ISSUE TITLE
Tabs - ScrollableTabBar - TabHeading Button Style Props

### ISSUE THREAD

**Issue by sosoban** [GeekyAnts/NativeBase#1456]
## react-native, react and native-base version
react-native 0.48.4
react 16.0.0-alpha.12
native-base 2.3.5

## Expected behaviour
ScrollableTabBar TabHeading Button element to align left and having animated underline.
<img width="348" alt="screen shot 2017-12-16 at 11 02 41 pm" src="https://user-images.githubusercontent.com/34588624/34069400-62abbbd2-e2b5-11e7-8fdd-5be0e6e0cb32.png">

## Actual behaviour
Can't style TabHeading Button element so never get the correct underline width.
<img width="343" alt="screen shot 2017-12-16 at 11 05 20 p
m" src="https://user-images.githubusercontent.com/34588624/34069413-9f16bc02-e2b5-11e7-9ae5-e4d2500a2fac.png">

## Steps to reproduce (code snippet or screenshot)
<img width="932" alt="screen shot 2017-12-16 at 11 07 27 pm" src="https://user-images.githubusercontent.com/34588624/34069425-ee7039c2-e2b5-11e7-962c-a75006b1a167.png">

## Is the bug present in both ios and android or in any one of them?
Both iOS and Android

**Comment by SupriyaKalghatgi** [comment]
@sosoban Do you need help on this?
Seems that you closed this issue

**Comment by sosoban** [comment]
@SupriyaKalghatgi, thank you for your reply. I extended the renderTab() method from the ScrollableTabBar component, added the props and it works for me, so that's all good. 

However, it might be good to add styles/props configurations for <Button> from TabBar? 

Thanks,
Shayne
