### ISSUE TITLE
Problem install native-base with npm

### ISSUE THREAD

**Issue by TranAnhDuc** [GeekyAnts/NativeBase#1457]
Hi, when trying to install native-base, I've got this problem:

> ~/development/react-native/SampleProject $ npm install native-base@2.3.1
> npm ERR! Error while executing:
> npm ERR! /usr/local/bin/git ls-remote -h -t https://github.com/GeekyAnts/react-native-keyboard-aware-scroll-view.git
> npm ERR! 
> npm ERR! fatal: unable to access 'https://github.com/GeekyAnts/react-native-keyboard-aware-scroll-view.git/': SSL certificate problem: self signed certificate in certificate chain
> npm ERR! 
> npm ERR! exited with error code: 128

The problem only occured with version 2.3 onward. I can install version 2.2 without problem.

**Comment by SupriyaKalghatgi** [comment]
@TranAnhDuc Probably `git` issue on your system

**Comment by sanketsahusoft** [comment]
@TranAnhDuc Can you try cloning with SSH?
![image](https://user-images.githubusercontent.com/1733433/34095239-b15d7580-e3f6-11e7-970f-bc0b2d8c9ec8.png)

Closing because it works for everybody else.
