### ISSUE TITLE
ReferenceError: resolvedStyle is not defined

### ISSUE THREAD

**Issue by midastouchprd** [GeekyAnts/NativeBase#1458]
## react-native, react and native-base version

"native-base": "^2.3.5",
"react": "16.0.0",
"react-native": "0.50.3",
"expo": "^23.0.6",

## Expected behaviour

Not throw Error

## Actual behaviour

ReferenceError: resolvedStyle is not defined

![screen shot 2017-12-19 at 3 33 18 am](https://user-images.githubusercontent.com/18386032/34150241-6c2e1646-e46d-11e7-9d73-92ca39cacc58.png)

## Steps to reproduce (code snippet or screenshot)

Anytime it hits the first native base component I get this

## Screenshot of emulator/device

Same as above

## Is the bug present in both ios and android or in any one of them?

I'm only using ios so I don't know 

## Any other additional info which would help us debug the issue quicker.

Created from a non ejected crna project employing the Kitchen Sink Setup from the CRNA branch

**Comment by SupriyaKalghatgi** [comment]
#1359
