### ISSUE TITLE
Error installing NativeBase

### ISSUE THREAD

**Issue by Schattenjager** [GeekyAnts/NativeBase#1459]
Hi, I'm having trouble installing NativeBase using npm when using the `npm install native-base --save` commands.

versions:
node: v6.11.1
npm: v5.6.0
react-native: v2.0.1

Expected behaviour:
Native-Base should install.

Actual behaviour:
Installation gives error saying that there is no git binary in the path.

Steps to reproduce (code snippet or screenshot):
![image](https://user-images.githubusercontent.com/116562/34160837-30380a42-e4d7-11e7-827d-89f47f63a0f9.png)

I've installed Git for Windows on the direction of another thread but it made no difference. Besides it isn't mentioned as a requirement on the NativeBase site anyway.
http://docs.nativebase.io/docs/GetStarted.html

**Comment by SupriyaKalghatgi** [comment]
@Schattenjager Try installing `react-native-vector-icons` in your project to know if it works
> Besides it isn't mentioned as a requirement on the NativeBase site anyway.
To have `git` as a mandatory requirement in docs would sound silly

**Comment by Schattenjager** [comment]
@SupriyaKalghatgi Hi, thanks for the response. I was able to successfully install react-native-vector-icons. Didn't check to see if I could install native-base after shutting down yesterday but I was now able to also install native-base. Doubt it had anything to do with react-native-vector-icons, think I might have just needed a restart yesterday.... Silly.

Anyway thanks for the help.

**Comment by SupriyaKalghatgi** [comment]
@Schattenjager Nothing related to `react-native-vector-icons`
Restart worked for it probably
