### ISSUE TITLE
Card Component

### ISSUE THREAD

**Issue by jabad3** [GeekyAnts/NativeBase#146]
I am seeing some rendering issues when using the card component alongside some styles. The demo's do not render correctly. Attaching code and pic. Any advice is much appreciated.

Some minor spacing issues present here:
<img width="1258" alt="screen shot 2016-08-26 at 9 22 08 pm" src="https://cloud.githubusercontent.com/assets/8780226/18024239/659ced8e-6bd3-11e6-8ad5-0a00b7c8fa15.png">

Some blocking issues present here. They start when 'theme' and 'style' are added
<img width="1260" alt="screen shot 2016-08-26 at 9 24 45 pm" src="https://cloud.githubusercontent.com/assets/8780226/18024271/d5e6b0c0-6bd3-11e6-937e-535b58900964.png">
Note how the text inside the card disappears. Seems to be related to styles

Update:
I added a style to the text tag. Seems to work better now. Something still feels off though, it doesnt look like the demo version.
<img width="979" alt="screen shot 2016-08-26 at 11 58 51 pm" src="https://cloud.githubusercontent.com/assets/8780226/18025014/45f3a066-6be9-11e6-8f5f-be0e79ed6a48.png">

Also, this works:
<img width="1094" alt="screen shot 2016-08-27 at 12 20 28 am" src="https://cloud.githubusercontent.com/assets/8780226/18025085/2ad141b4-6bec-11e6-9936-15dd556dad16.png">

But this doesnt:
<img width="1098" alt="screen shot 2016-08-27 at 12 22 02 am" src="https://cloud.githubusercontent.com/assets/8780226/18025091/558d107c-6bec-11e6-9d85-00397533ba3b.png">

**Comment by sankhadeeproy007** [comment]
Hi, which version of nativeBase are you using?

**Comment by jabad3** [comment]
I am using 0.5.7.
<img width="363" alt="screen shot 2016-08-30 at 8 06 45 pm" src="https://cloud.githubusercontent.com/assets/8780226/18111387/5035fe6e-6eed-11e6-8b48-b85d8e54ef36.png">

I am using the template found here:
http://startreact.com/themes/native-starter/

**Comment by kennydee** [comment]
Same problem here, any idea how to fix it ? Thanks

**Comment by SupriyaKalghatgi** [comment]
@jabad3 @kennydee NativeBase includes a theme file - `light.js` to avoid redundancy of including styles
User need to update this file according to his/her needs.
In the above case of text color in card, you need to update the `textColor` in the theme file. And then no need to add the color for text every time.
In the second case of adding different `Cards`, due to `marginTop` included between the `Cards`, the last `CardItem` is being cropped.

**Comment by sankhadeeproy007** [comment]
Hi, just use flex: 0 with the cards. That should fix your problems.
