### ISSUE TITLE
Optimistically rendering Tabs when swiping

### ISSUE THREAD

**Issue by stevenyoon** [GeekyAnts/NativeBase#1462]
Would it be possible to optimistically render the tab as we are horizontally scrolling tabs using the scrollable tab bar? I.e. when a user starts swiping the SceneComponent to either the left or the right, have the adjacent screen start to load before it gets fully swiped. This could improve the user experience by having tabs load faster (especially if you're making an async request to an api). Thanks!

## react-native, react and native-base version

react-native: ^0.49.3
react: 16.1.1
native-base: 2.2.1

**Comment by SupriyaKalghatgi** [comment]
@stevenyoon NativeBase is a UI library
So loading the adjacent screen before it is swiped, is something not related to UI

**Comment by MahmutCanKahya** [comment]
You can use "prerenderingSiblingsNumber = {1}"
