### ISSUE TITLE
Drawer container not visible

### ISSUE THREAD

**Issue by saravanannnallasamy** [GeekyAnts/NativeBase#1464]
I have used Native-Base Drawer component for side menu in my native page. But nothing is visible in that page

`  return (

        <Drawer
            ref={(ref) => { this.drawer = ref; }}
            content={<Sidebarksink navigator={this.navigator} />}
            onClose={() => this.closeDrawer()} >

        <Container>    
          <Header style={{backgroundColor:'white'}}>
            <Left>
              <Button transparent onPress={() => this.openDrawer.bind(this)}>
                <Ionicons name='ios-arrow-round-back' size={45} color='#d0964b'/>
              </Button>
            </Left>
            <Body>
              <Title style={{color:'black',width:deviceWidth/2}}>Package</Title>
            </Body>
            <Right>
              <View style={{flexDirection:'row'}}>
              </View>
          </Right>
        </Header>
        <Content>
        </Content>
        </Container>
        </Drawer>
`

## react-native, react and native-base version
    native-base :  2.0.9 ,
    react : 15.4.0 ,
    react-native :  0.38.0 
## Expected behaviour
side menu should pop out when i click menu icon.
## Actual behaviour
empty screen
## Steps to reproduce (code snippet or screenshot)
N/A
## Screenshot of emulator/device
Blank white screen
## Is the bug present in both ios and android or in any one of them?
N/A

**Comment by harikanammi** [comment]
Hi @saravanannnallasamy .......Place your code like below example. I think it's working fine.
AppHeader.js file:
```
import React, { Component } from 'react'
import { Text } from 'react-native'
import { Header, Left, Button, Icon, Right, Body, Title, Drawer } from 'native-base'
import SideBar from './SideBar'

export default class AppHeader extends Component {
  constructor(props) {
    super(props)
    this.state = {}
  }
  closeDrawer() {
    this.drawer._root.close()
  }
  openDrawer() {
    this.drawer._root.open()
  }
  render() {
    return (
      <Drawer
       ref={(ref) => { this.drawer = ref; }}
        content={<SideBar />}
        onClose={() => this.closeDrawer()}
      >
        <Header>
          <Left>
            <Button transparent onPress={() => this.openDrawer()}>
              <Icon name="menu" />
            </Button>
          </Left>
          <Body>
            <Title>SDCC Wallet</Title>
          </Body>
          <Right>
            <Button transparent>
              <Icon name="bulb" />
            </Button>
          </Right>
        </Header>
      </Drawer>
    )
  }
}
module.exports = AppHeader
```

SideBar.js File:
```
import React, { Component } from 'react';
import {
  Text,
} from 'react-native';

import styles from './styles';
import {Content} from 'native-base';

export default class SideBar extends Component {
  render() {
    return (
          <Content style={{backgroundColor:'#FFFFFF'}}>
            <Text>Drawer</Text>
          </Content>
    );
  }
}

module.exports = SideBar;
```

**Comment by saravanannnallasamy** [comment]
Hi @harikanammi , I have placed your AppHeader.js code but the AppHeader page is blank.
Is Drawer  is not supporting because of react-native/native-base versions ??????

**Comment by akhil-geekyants** [comment]
@saravanannnallasamy tried a similar code with the latest versions

Gif

![drawer](https://user-images.githubusercontent.com/27768184/34382735-f5b1804a-eb36-11e7-883b-49390de6e5ac.gif)

Code

App.js
```
import React, { Component } from 'react';
import { Drawer, Container, Header, Left, Body, Right, Button, Content, Title, View, Icon } from 'native-base'
import Sidebar from './src/components/sidebar'

export default class App extends Component {
  render() {
    return (
      <Drawer
        ref={(ref) => { this.drawer = ref; }}
        content={<Sidebar navigator={this.navigator} />}
        onClose={() => this.drawer._root.close()} >
        <Container>
          <Header style={{ backgroundColor: 'white' }}>
            <Left>
              <Button transparent onPress={() => this.drawer._root.open()}>
                <Icon name='ios-arrow-round-back' size={45} color='#d0964b' />
              </Button>
            </Left>
            <Body>
              <Title style={{ color: 'black' }}>Package</Title>
            </Body>
            <Right>
              <View style={{ flexDirection: 'row' }}>
              </View>
            </Right>
          </Header>
          <Content>
          </Content>
        </Container>
      </Drawer>
    );
  }
}

```
sidebar.js
```
import React, { Component } from 'react';
import { Content, Text } from 'native-base';

export default class Sidebar extends Component {
    render() {
        return (
            <Content style={{ backgroundColor: '#FFFFFF' }}>
                <Text style={{ margin: 20 }}>Drawer</Text>
            </Content>
        );
    }
}
```

you can refer the docs for using Drawer [here](https://docs.nativebase.io/Components.html#Drawer)

**Comment by akhil-geekyants** [comment]
Closing the issue due to no response

**Comment by DragosRotaru** [comment]
Im having the same problem... implemented the examples identically, yet when I insert the content like so: <Drawer>// STUFF HERE </Drawer>

Nothing displays.

When I take the contents out and turn drawer into a self-closing component It functions accordingly (but doesnt display the content "within" the drawer)

**Comment by akhil-geekyants** [comment]
@DragosRotaru checked the above code. It works fine for me as in gif. Can you post your code or create a test repo for us to test.

**Comment by DragosRotaru** [comment]
@akhil-geekyants apologies! I had typed an extra character within the Drawer but outside of a <Text /> Component. All Good now.
