### ISSUE TITLE
this2.props.openDrawer is not a function(Drawer)

### ISSUE THREAD

**Issue by harikanammi** [GeekyAnts/NativeBase#1469]
I am running sample drawer example. 
But i am getting error like this: this2.props.openDrawer is not a function. Please give me any suggestion. Thank you.
sideBar.js file:
```
import React, { Component } from 'react';
import {
  Text,
} from 'react-native';

import styles from './styles';
import {Content} from 'native-base';

export default class Sidebar extends Component {
  render() {
    return (
          <Content style={{backgroundColor:'#FFFFFF'}}>
            <Text>Drawer</Text>
          </Content>
    );
  }
}

module.exports = Sidebar;
```

Main.js file:
```
import React, { Component } from 'react';
import {
  AppRegistry,
  Text
} from 'react-native';

import {Drawer} from 'native-base';

import AppHeader from './appHeader';
import AppBody from './appBody';
import AppFooter from './appFooter';

import Sidebar from './sidebar';

export default class Main extends Component {
  closeDrawer = () => {
    this.drawer._root.close()
  };
  openDrawer = () => {
    this.drawer._root.open()
  };
  render() {
    return (
              <Drawer
                ref={(ref) => { this.drawer = ref; }}
                content={<Sidebar/>}
                onClose={() => this.closeDrawer()} >

                <AppHeader
                    openDrawer={this.openDrawer.bind(this)}
                />
                <AppBody/>
                </Drawer>
    );
  }
}

module.exports = Main;
```

AppHeader.js file:

```
import React, { Component } from 'react';
import {
  Text,
} from 'react-native';

import {Header,Left,Button,Icon,Right,Body,Title} from 'native-base';

export default class AppHeader extends Component {
  render() {
    return (
      <Header>
       <Left>
       <Button transparent
              onPress={()=>this.props.openDrawer()}
       >
         <Icon name='menu' />
       </Button>
       </Left>
       <Body>
         <Title>SDCC Wallet</Title>
       </Body>
       <Right>
         <Button transparent>
           <Icon name='bulb' />
         </Button>
       </Right>
     </Header>
    );
  }
}

module.exports = AppHeader;
```

Here is my screenshot:
![screen shot 2017-12-23 at 4 22 45 pm](https://user-images.githubusercontent.com/31063894/34319065-907792f0-e7fd-11e7-82be-ad4546e3bbae.png)

**Comment by akhil-geekyants** [comment]
@harikanammi instead of `this.props.openDrawer()` call `this.openDrawer()` in onPress function

Replace
```
<Button transparent
     onPress={()=>this.props.openDrawer()}
>
```
in `AppHeader.js` by
```
<Button transparent
        onPress={() => this.openDrawer()}
>
```

**Comment by akhil-geekyants** [comment]
@harikanammi tried your code. It was working fine for me. Attaching a Gif

Gif

![drawer](https://user-images.githubusercontent.com/27768184/34381273-74cde332-eb2d-11e7-8758-5365f08d4956.gif)

**Comment by akhil-geekyants** [comment]
Closing the issue due to no response

**Comment by atultiwari1996** [comment]
You should use onPress={ () =>this.props.navigation.openDrawer() instead of onPress={()=>this.props.openDrawer()} this way working for me

**Comment by PurevsurenL** [comment]
asdf

**Comment by minulmindula** [comment]
@atultiwari1996 Hi,
I am trying to access the Drawer using onPress: () => this.props.navigation.navigate.openDrawer().
I'm facing the same error..

**Comment by peternoordijk** [comment]
I got a similar error and I think my solution might help you a little. The `navigation` prop is being injected by the [React Navigation](https://reactnavigation.org/) library; or at least that's what happens in the NativeBase examples. The `openDrawer` function will only be provided if you use `createDrawerNavigator` when you define your routes (instead of `createStackNavigator` for example). See [here](https://reactnavigation.org/docs/en/drawer-based-navigation.html) an example.

**Comment by kelemenbalazs** [comment]
thanks for your answer @peternoordijk , it makes much more sense now to me, and your solution is worked!

**Comment by arnabadhikari2009** [comment]
@peternoordijk  is right but how to open a drawer from stack screen.
