### ISSUE TITLE
Nonscrollable Container

### ISSUE THREAD

**Issue by leekuo** [GeekyAnts/NativeBase#147]
I haven't seen a way to make a container non-scrollable in the docs.  Is there any way to implement this?  My main issue is that after adding tabs to a container, both the tabbed view and the parent container are both scrollable, leading to usability problems.

Thank you so much, I'm new to react native and this is the best boilerplate I've seen so far.  I'm evaluating for my project, and if it works out, would definitely buy some themes.

**Comment by ericvan76** [comment]
My workaround:
1. Parent scrollview: horizontal=true & scrollEnabled=false, which makes it non-scrollable
2. Child scrollview: width=100% (I use react-native-extended-stylesheet to set the percentage)

**Comment by L3V147H4N** [comment]
when setting Content to horizontal={true} the Tabs don't work

**Comment by gperdomor** [comment]
Same error here

**Comment by sankhadeeproy007** [comment]
![scroll](https://cloud.githubusercontent.com/assets/10998047/18993157/7a617884-873f-11e6-90d2-515ae007e072.gif)
Use `scrollEnabled={false}`
