### ISSUE TITLE
Possibility to add new types to toast.

### ISSUE THREAD

**Issue by Angelk90** [GeekyAnts/NativeBase#1471]
It would be possible to add the missing themes in the toasts, the same themes used in the buttons.
See: https://docs.nativebase.io/Components.html#button-theme-headref
Primary (default)
Success
Info
Warning
Danger
Light
Dark

Or even the possibility to insert a color manually by definition: 
example:
type={ "# 4988b2"}

**Comment by SupriyaKalghatgi** [comment]
@Angelk90 Default Toast comes with `dark`
Other types available are `success`, `warning`, `danger`

**Comment by Angelk90** [comment]
@SupriyaKalghatgi : In fact, as you say, by default.
Mine is a request to add them as features, since
NativeBase provides following color themes, as default on buttons and other components.

**Comment by SupriyaKalghatgi** [comment]
@Angelk90 I am not clear with your statement
Please explain
