### ISSUE TITLE
Error padding icon in Button (version 2.3.5)

### ISSUE THREAD

**Issue by navata** [GeekyAnts/NativeBase#1472]
I see padding icon that it display incorrect in version 2.3.5. But I work well in version 2.3.0. 
Please help me fix this issue.

![issuebutton](https://user-images.githubusercontent.com/16706514/34336349-e886021a-e988-11e7-84a3-1cafdf0c0d51.jpg)

**Comment by akhil-geekyants** [comment]
@navata can you post some code for us to test. Please see the attached Gif (Checked with native-base version 2.3.5)

Gif

![iconpadding](https://user-images.githubusercontent.com/27768184/34376529-2576ce68-eb12-11e7-9bfd-f1588367f2d4.gif)

**Comment by navata** [comment]
Thanks for @akhil-geekyants, I have fixed the issue. 
Because I import Button and Icon component from native-base but Text import form native-base.
Solution: Import Text form Native-base and add prop iconLeft and iconRight
`
//import {  Text } from 'react-native' ;  Incorrect 
import React, { Component } from 'react';
import { Container, Header, Content, Button, Text } from 'native-base';
export default class ButtonExample extends Component {
  render() {
    return (
      <Container>
        <Header />
        <Content>
          <Button iconLeft iconRight>
            <Text>Click Me! </Text>
            <Icon name='arrow-forward' />
          </Button>
        </Content>
      </Container>
    );
  }
}
` 

=> I have the question for you. Does Native base have contain all component of React-native?

**Comment by akhil-geekyants** [comment]
@navata NativeBase does not contain all the components of React Native. If you need to use ScrollView you need to import from react-native itself. You can read more about NativeBase components [here](http://docs.nativebase.io/Components.html#Components)
