### ISSUE TITLE
FooterTab circular button issue on android

### ISSUE THREAD

**Issue by Chaimae123** [GeekyAnts/NativeBase#1473]
I used the following code to create FooterTab with a centered circular button. It works fine on iOS but doesn't show the full button on android !

`<Footer>
          <FooterTab>
            <Button>
              <Icon name="apps" />
            </Button>
            <Button>
              <Icon name="camera" />
            </Button>    
            <Button onPress={this._onHomePress} style={{height: 70,width: 70,bottom: 8,borderWidth:1,borderColor:'lightgrey',borderRadius:35,backgroundColor:'#f5f5f5'}} active>
              <Icon active name="add" style={{color:'darkgrey'}}/>
            </Button>
            <Button>
              <Icon name="camera" />
            </Button>
            <Button>
              <Icon name="person" />
            </Button>
          </FooterTab>
        </Footer>`

on android
![31040264-a2df4696-a5b7-11e7-99ac-368f6ea633b6](https://user-images.githubusercontent.com/19706388/34343360-5477113c-e9c3-11e7-91e6-9ce7094f221b.png)

on iOS

![31010823-cb94d7ec-a529-11e7-881e-39e9c83b2bc2](https://user-images.githubusercontent.com/19706388/34343362-5dae45c2-e9c3-11e7-9441-fa25dc563cf1.png)

**Comment by SupriyaKalghatgi** [comment]
#1260
