### ISSUE TITLE
Render Tab issue 

### ISSUE THREAD

**Issue by arctm** [GeekyAnts/NativeBase#1474]
Hi, 
I have some issues with Tabs, it works fine when i navigate thorugh screen ( clicking on tab or swipe ). But i also have a drawer with links to this tabs, and they did not work correctly. When i click to drawer link it go to tab but seems like content of this tab did not render. Can you please help me?

## react-native, react and native-base version
    "native-base": "2.3.5",
    "react": "16.0.0",
    "react-native": "0.50.1",
## Steps to reproduce (code snippet or screenshot)
![1](https://user-images.githubusercontent.com/8043732/34351308-86783e5c-ea24-11e7-8d8e-fe693a911e85.png)
![2](https://user-images.githubusercontent.com/8043732/34351309-869930f8-ea24-11e7-9b70-8513b4bdee84.png)
## Screenshot of emulator/device
This i get when navigate by clicking on tab or by swipe 
![screenshot_1514275701](https://user-images.githubusercontent.com/8043732/34351360-de28d882-ea24-11e7-9925-d36751a21b02.png)

**And this i get when click on drawer link**
![screenshot_1514275682](https://user-images.githubusercontent.com/8043732/34351349-c0b02bf2-ea24-11e7-9a2c-40601a11ef15.png)

**Comment by SupriyaKalghatgi** [comment]
@arctm Can you check this once with NativeBase KitchenSink?

**Comment by SupriyaKalghatgi** [comment]
Blank page in case of Android
Indicator issue in case of iOS

**Comment by SupriyaKalghatgi** [comment]
#1010
