### ISSUE TITLE
Issue installing older version of native-base

### ISSUE THREAD

**Issue by ppatel890** [GeekyAnts/NativeBase#1475]
## react-native, react and native-base version
react@15.4.2
react-native@0.42.3
native-base@2.0.12
## Expected behaviour
native-base installs properly from npm
## Actual behaviour
yarn throws the error below
````
error Couldn't find match for "be7564f4611864af471a82d980ea9f7505fb6bf6" in "_c" for "https://github.com/GeekyAnts/theme".
````
## Any other additional info which would help us debug the issue quicker.
Installing this worked fine about a week ago, and now seems to be broken. Changing the native-base version seems to break a lot of existing styles, so want to avoid that.

Any help is appreciated.

**Comment by akhil-geekyants** [comment]
@ppatel890 tried installing using yarn (version 1.3.2). Didn't see any issue. Attaching a Gif.

Gif

![oldversion](https://user-images.githubusercontent.com/27768184/34379887-a390fcd6-eb23-11e7-9e28-6197bf07deee.gif)

**Comment by ppatel890** [comment]
Oops, I meant native-base@2.0.11. My fault. I was able to change the commit ref in my yarn.lock file, and it seems to work fine now.
