### ISSUE TITLE
IOS Card UI Is not working in android working fine

### ISSUE THREAD

**Issue by ShaileshPrajapati-BTC** [GeekyAnts/NativeBase#1476]
`<Card >
            <List style={{flexWrap: 'nowrap'}}>
              <ListItem avatar onPress={()=> this._openMap(data.latitude, data.longitude)}>
                <Left>
                  <Thumbnail small source={{uri: data.client_image}} />
                </Left>
                <Body style={{flex:2,paddingBottom: 22}}>
                  <Text style={{fontSize: 14}}>{data.client_name}</Text>
                  <Text note style={{fontSize: 12, color: '#b2b2b2'}}><Icon name="md-time" style={{fontSize: 12, color: '#b2b2b2'}}/> {data.time}</Text>
                </Body>
                <Right>
                  <Badge style={{ backgroundColor: status[data.status] }}>
                    <Text style={{fontSize: 13}}>{data.status}</Text>
                  </Badge>
                  {(data.extended_hours != '') ?
                    <Text note style={{fontSize: 10, marginTop: 5, color: CONFIG.theme_color}}>{data.extended_hours}</Text> : null}
                </Right>
              </ListItem>
            </List>
          </Card>`
```json
   {"native-base": "2.3.3",
    "react": "16.0.0-alpha.12",
    "react-native": "0.48.0"}
```
![simulator screen shot 27 dec 2017 2 43 30 pm](https://user-images.githubusercontent.com/19203840/34373221-da3ad18a-eb14-11e7-809e-2aa0a4b19e5e.png)

**Comment by akhil-geekyants** [comment]
@ShaileshPrajapati-BTC can you try adding style `flexWrap: 'nowrap'` to `<Card/>` component. 
```
<Card style={{flexWrap: 'nowrap'}}>
```

**Comment by ShaileshPrajapati-BTC** [comment]
@akhil-geekyants thanks it's working
