### ISSUE TITLE
new button with floating props material kind

### ISSUE THREAD

**Issue by GuillotJessica** [GeekyAnts/NativeBase#1478]
I just think  it would be relevant

**Comment by SupriyaKalghatgi** [comment]
@GuillotJessica Can you brief on this

**Comment by GuillotJessica** [comment]
[a floating action button like so](https://material.io/guidelines/components/buttons-floating-action-button.html#) like FAB but with no action predefined

**Comment by SupriyaKalghatgi** [comment]
@GuillotJessica Can you differentiate between [NativeBase FAB](https://docs.nativebase.io/Components.html#fabs-def-headref) with that of what you are expecting?

**Comment by GuillotJessica** [comment]
FAB expand  other button , I think it would be relevant to just have a button on relative position that yet do nothing

**Comment by SupriyaKalghatgi** [comment]
@GuillotJessica Have a button which does nothing? what is the use of it then

**Comment by GuillotJessica** [comment]
then you can onPress a function

**Comment by SupriyaKalghatgi** [comment]
@GuillotJessica Seems like this use case is specific and not generic
