### ISSUE TITLE
Change the inActiveColor and ActiveColor in Scrollable Tab

### ISSUE THREAD

**Issue by harikanammi** [GeekyAnts/NativeBase#1479]
I am running sample app. Here i am displaying scrollable tabs. My question is how to change the activeColor and inActiveColor in Scrollable Tabs.
Here is my code:
 ` <Tabs renderTabBar={() => <ScrollableTab style={{ backgroundColor: '#095751' }} underlineStyle={{ backgroundColor: 'black' }} />}>{description}</Tabs>`

here is my screenshot:
![screen shot 2018-01-02 at 12 32 35 pm](https://user-images.githubusercontent.com/31063894/34476698-146aaa80-efb9-11e7-8be8-ff13bd59d801.png)

**Comment by SupriyaKalghatgi** [comment]
@harikanammi NativeBase has set default colors for active and inactive tabs
You can customize them by ejecting theme and modifying as per your need

**Comment by harikanammi** [comment]
hi @SupriyaKalghatgi, thanks for your reply. But how i can change colors in Scrollable Tab component for active and inactive tabs.

**Comment by SupriyaKalghatgi** [comment]
@harikanammi By changing colors [here](https://github.com/GeekyAnts/NativeBase/blob/master/src/theme/variables/commonColor.js#L151)?

**Comment by harikanammi** [comment]
hi @SupriyaKalghatgi  how to change the active and inactive colors above you mentioned commonColor.js file.

**Comment by SupriyaKalghatgi** [comment]
@harikanammi I have mentioned the line number even
Also did you eject before doing this?
Check the docs
