### ISSUE TITLE
Change Icon Style

### ISSUE THREAD

**Issue by fbacker** [GeekyAnts/NativeBase#148]
How to change the type of icon library?

    import myTheme from '../themes/myTheme';
    <Icon name='arrows' theme={myTheme} />

The content of myTheme.js

	export default {
	    iconFamily: 'FontAwesome',
	}

This still uses the default theme library ionicons

**Comment by himanshu-sahusoft** [comment]
Fixed with this [commit](https://github.com/GeekyAnts/NativeBase/commit/e7021b94fb630a7264ab3315496b603dbf879a36)
