### ISSUE TITLE
Change check icon and text color in radio button

### ISSUE THREAD

**Issue by webdevsyd** [GeekyAnts/NativeBase#1481]
Hi Guys, does anyone tried changing the color of the icon and text when selected for the radio button? May I ask how did you do it?

**Comment by SupriyaKalghatgi** [comment]
Fixed with [2.3.6](https://github.com/GeekyAnts/NativeBase/releases/tag/v2.3.6)

**Comment by webdevsyd** [comment]
@SupriyaKalghatgi cant see the fixed for changing the color of text and icon in radio button in 2.3.6

**Comment by SupriyaKalghatgi** [comment]
@webdevsyd text color is something which comes by default with iOS and Android

**Comment by rebirthtobi** [comment]
There should be a prop to change it

**Comment by SupriyaKalghatgi** [comment]
Fixed with [2.4.4](https://github.com/GeekyAnts/NativeBase/releases/tag/v2.4.4)
