### ISSUE TITLE
Drawer does not close the sub menu properly

### ISSUE THREAD

**Issue by suleymangunduzz** [GeekyAnts/NativeBase#1483]

**Comment by akhil-geekyants** [comment]
Can you give more information on this

**Comment by akhil-geekyants** [comment]
@suleymangunduzz checked Drawer Component. It was not showing any issue. I was able to close the submenu. Attaching a Gif

Gif

![drawer](https://user-images.githubusercontent.com/27768184/34862449-769e949e-f790-11e7-80d8-26c18a894e0b.gif)

**Comment by akhil-geekyants** [comment]
Closing this issue due to no response.

**Comment by AgNm** [comment]
@akhil-geekyants can you please let me know how you created the submenus here. I tried few things but it is not working as expected.

**Comment by akhil-geekyants** [comment]
@AgNm that is an hardcoded list. Pasting code since you asked

```
import React from 'react'
import { Container, View, Text, ListItem, Left, Icon, Body, Right } from 'native-base'

export default class Sidebar extends React.Component {

    constructor(props) {
        super(props)
        this.state = { item1: false, item2: false, item3: false }
    }

    render() {

        const submenu = (<View>
            <ListItem icon >
                <Left><Icon name="person" /></Left>
                <Body><Text>Person 1</Text></Body>
            </ListItem>
            <ListItem icon >
                <Left><Icon name="person" /></Left>
                <Body><Text>Person 2</Text></Body>
            </ListItem>
            <ListItem icon>
                <Left><Icon name="person" /></Left>
                <Body><Text>Person 3</Text></Body>
            </ListItem>
        </View>)

        return (<Container style={{ backgroundColor: '#fff', paddingTop: 20 }}>
            <ListItem icon onPress={() => this.setState({ item1: !this.state.item1 })}>
                <Left><Icon name="plane" /></Left>
                <Body><Text>Item 1</Text></Body>
                <Right><Icon name="md-arrow-forward" /></Right>
            </ListItem>

            {
                this.state.item1 ? submenu : null
            }

            <ListItem icon onPress={() => this.setState({ item2: !this.state.item2 })}>
                <Left><Icon name="wifi" /></Left>
                <Body><Text>Item 2</Text></Body>
                <Right><Icon name="md-arrow-forward" /></Right>
            </ListItem>

            {
                this.state.item2 ?
                    submenu : null
            }

            <ListItem icon onPress={() => this.setState({ item3: !this.state.item3 })}>
                <Left><Icon name="bluetooth" /></Left>
                <Body><Text>Item 3</Text></Body>
                <Right><Icon name="md-arrow-forward" /></Right>
            </ListItem>

            {
                this.state.item3 ? submenu : null
            }

        </Container >)
    }
}
```

**Comment by AgNm** [comment]
@akhil-geekyants I am getting below error when clicking on any item... why is this so?

![screen shot 2018-02-12 at 3 00 30 pm](https://user-images.githubusercontent.com/11326181/36090250-a607682c-1005-11e8-82bb-3be93c46b08e.png)
![Uploading Screen Shot 2018-02-12 at 3.00.15 PM.png…]()

**Comment by AgNm** [comment]
Below is my code:

`import React, { Component }  from 'react';
import {View,TouchableOpacity,ScrollView,Alert,ImageBackground} from 'react-native';
import {Container,Thumbnail,Content,Icon,CardItem,Item,Card,Text,Header,Drawer,Button,ListItem,Left,Body,Right} from 'native-base';
import {Menus} from './common';
import {Actions} from 'react-native-router-flux';
import _ from 'lodash';
import { Fonts } from '../utils/Fonts';


  const {currentUser} = '';

  const submenu = (<View>
                <ListItem icon>
                    <Left><Icon name="person" /></Left>
                    <Body><Text>Person 1</Text></Body>
                </ListItem>
                <ListItem icon>
                    <Left><Icon name="person" /></Left>
                    <Body><Text>Person 2</Text></Body>
                </ListItem>
                <ListItem icon>
                    <Left><Icon name="person" /></Left>
                    <Body><Text>Person 3</Text></Body>
                </ListItem>
            </View>)

export class SideNavigationBar extends Component{

    constructor(props){
        super(props);
        this.state = { item1: false, item2: false, item3: false};
        alert("1 "+ this.state.item1);
        this.state = {
            children       : props.children,
            isMenuActive    : props.isMenuActive,
            onSideMenuChange   : props.onSideMenuChange
        };
    }

    render(){

        let icon = 'ios-add-outline';

        if(this.state.expanded){
            icon = 'ios-remove-outline';
        }

        return (
          <Drawer
            style={{border:0}}
            ref={(ref) => { drawer = ref; }}
            open="true"
            content={MenuComponent(currentUser)}
            >
            {this.state.children}
          </Drawer>
        );
    }
}


const MenuComponent=() => {
  return(
              <Container style={{ backgroundColor: '#fff', paddingTop: 20 }}>
                <ListItem icon onPress={() => this.setState({ item1: !this.state.item1 })}>
                    <Left><Icon name="plane" /></Left>
                    <Body><Text>Item 1</Text></Body>
                    <Right><Icon name="md-arrow-forward" /></Right>
                </ListItem>

                      {this.state.item1 ? submenu : null }

                <ListItem icon onPress={() => this.setState({ item2: !this.state.item2 })}>
                    <Left><Icon name="wifi" /></Left>
                    <Body><Text>Item 2</Text></Body>
                    <Right><Icon name="md-arrow-forward" /></Right>
                </ListItem>

                {this.state.item2 ? submenu : null }

                <ListItem icon onPress={() => this.setState({ item3: !this.state.item3 })}>
                    <Left><Icon name="bluetooth" /></Left>
                    <Body><Text>Item 3</Text></Body>
                    <Right><Icon name="md-arrow-forward" /></Right>
                </ListItem>

                {this.state.item3 ? submenu : null }
            </Container>
  )
}

const styles = {
  nameStyle : {
    paddingLeft:10,
    color:'#F1BE24',
    fontSize : 20,
    fontFamily : Fonts.TitilliumWebSemiBold
  },
  employeeCodeStyle : {
    paddingLeft:10,
    color:'#fff',
    fontSize : 15,
    fontFamily : Fonts.TitilliumWeb
  },
  companyNameStyle : {
    paddingLeft:10,
    color:'#F1BE24',
    fontSize : 15,
    fontFamily : Fonts.TitilliumWeb
  },
  menuTextStyle : {
    color:'#626B78',
    fontSize : 17,
    fontFamily : Fonts.TitilliumWebSemiBold
  }
}

const TouchableLink = {
  backgroundColor: '#ebebef'
}
`


![screen shot 2018-02-12 at 3 12 26 pm](https://user-images.githubusercontent.com/11326181/36090641-2715d4fc-1007-11e8-88e0-698a2fa4408d.png)

**Comment by akhil-geekyants** [comment]
@AgNm made MenuComponent a React Component. Passed current user as a prop and managed drawer's list state inside MenuComponent itself. 

Code
```
import React, { Component } from 'react';
import { View, TouchableOpacity, ScrollView, Alert, ImageBackground } from 'react-native';
import { Container, Thumbnail, Content, Icon, CardItem, Item, Card, Text, Header, Drawer, Button, ListItem, Left, Body, Right } from 'native-base';

const currentUser = 'test user';

const submenu = (<View>
  <ListItem icon onPress={() => alert('Person 1')}>
    <Left><Icon name="person" /></Left>
    <Body><Text>Person 1</Text></Body>
  </ListItem>
  <ListItem icon onPress={() => alert('Person 2')}>
    <Left><Icon name="person" /></Left>
    <Body><Text>Person 2</Text></Body>
  </ListItem>
  <ListItem icon onPress={() => alert('Person 3')}>
    <Left><Icon name="person" /></Left>
    <Body><Text>Person 3</Text></Body>
  </ListItem>
</View>)

export default class SideNavigationBar extends Component {
  constructor(props) {
    super(props);
    this.state = {
      drawer: false,
      children: props.children,
      isMenuActive: props.isMenuActive,
      onSideMenuChange: props.onSideMenuChange
    };
  }

  render() {
    let icon = 'ios-add-outline';
    if (this.state.expanded) {
      icon = 'ios-remove-outline';
    }

    return (
      <Drawer
        style={{ border: 0 }}
        ref={(ref) => { drawer = ref; }}
        open={this.state.drawer}
        content={<MenuComponent currentUser={currentUser} />}>
        {/* {this.state.children} */}
        <Text style={{ flex: 1, padding: 20 }} onPress={() => this.setState({ drawer: !this.state.drawer })}>Main Content</Text>
      </Drawer >
    );
  }
}

class MenuComponent extends React.Component {

  constructor(props) {
    super(props);
    this.state = { item1: false, item2: false, item3: false };
  }

  render() {
    return (
      <Container style={{ backgroundColor: '#fff', paddingTop: 20 }}>
        <ListItem icon onPress={() => this.setState({ item1: !this.state.item1 })}>
          <Left><Icon name="plane" /></Left>
          <Body><Text>Item 1</Text></Body>
          <Right><Icon name="md-arrow-forward" /></Right>
        </ListItem>

        {this.state.item1 ? submenu : null}

        <ListItem icon onPress={() => this.setState({ item2: !this.state.item2 })}>
          <Left><Icon name="wifi" /></Left>
          <Body><Text>Item 2</Text></Body>
          <Right><Icon name="md-arrow-forward" /></Right>
        </ListItem>

        {this.state.item2 ? submenu : null}

        <ListItem icon onPress={() => this.setState({ item3: !this.state.item3 })}>
          <Left><Icon name="bluetooth" /></Left>
          <Body><Text>Item 3</Text></Body>
          <Right><Icon name="md-arrow-forward" /></Right>
        </ListItem>

        {this.state.item3 ? submenu : null}
        <Text style={{ padding: 20 }}>Current user: {this.props.currentUser}</Text>
      </Container>
    )
  }
}
```

Gif

![drawer](https://user-images.githubusercontent.com/27768184/36092257-bdf3ec60-100c-11e8-89d0-49bb3ba9cded.gif)

**Comment by SupriyaKalghatgi** [comment]
2 working examples with code snippet and output shared above
