### ISSUE TITLE
Is it possible to trigger the Picker from another onPress handler?

### ISSUE THREAD

**Issue by jync** [GeekyAnts/NativeBase#1485]
We render the Picker as a field in a list. We would like to trigger the picker to open when the Row has been tapped. Is there a way to do this?

I can see that within the `Picker.ios.js` component, there is the following method:

```
  _setModalVisible(visible) {
    this.setState({ modalVisible: visible });
  }
```

Would it be possible to expose this method? Or at least a prop that we can pass in to trigger the Picker to open?

We're using native-base 2.3.5

**Comment by akhil-geekyants** [comment]
@jync you can fork NativeBase and make the required changes to achieve what you want.

**Comment by gupta-ji6** [comment]
That would greatly increase UX. If we use `Picker` with a `ListItem`, then the picker only opens when we tap on the picker rather than on the `ListItem`. We should also be able to open the picker using `ListItem`. I think that can be done using `ref` with `Picker`.

**Comment by AbanoubNassem** [comment]
@jync have you figured this issue out? because am facing the same problem and I can't access the `_setModalVisible` method!

**Comment by tanoto-the-explorer** [comment]
@AbanoubNassem  hi, have u figured this out?

**Comment by bjornbreck** [comment]
Has there been any updates to this? It seems like a very critical piece of functionality left out of core.. 😞
