### ISSUE TITLE
Version problem

### ISSUE THREAD

**Issue by goglikoo** [GeekyAnts/NativeBase#1486]
Hello , I am using native base in my project , but last days i have such problem on ios.

These are my module versions : 
    "moment": "2.17.1",
    "react": "15.4.2",
    "native-base": "2.0.12",
    "react-native": "0.41.2",
    "react-native-calendar": "0.10.0",
    "react-native-easy-grid": "0.1.7",
    "react-native-modal-dropdown": "0.4.3",
    "react-native-modalbox": "1.3.9",
    "react-native-router-flux": "3.37.0"

During transforming i have following error : 
UnableToResolveError: Unable to resolve module @shoutem/theme from /Users/userName/Desktop/laws/node_modules/native-base/dist/src/index.js: Module does not exist in the module map or in these directories:
  /Users/userName/Desktop/laws/node_modules/native-base/node_modules/@shoutem
,   /Users/userName/Desktop/laws/node_modules/@shoutem

Could you tell me how to fix this?

**Comment by SupriyaKalghatgi** [comment]
@goglikoo Try doing these

- deleting `node_nodules`
- deleting `yarn.lock`
- install `node_modules`
- clear npm cache

**Comment by goglikoo** [comment]
@SupriyaKalghatgi  I've done it already, but not fixed.

**Comment by goglikoo** [comment]
I fixed it , manually installed  @shoutem/theme
