### ISSUE TITLE
Native base link Expo does not work.

### ISSUE THREAD

**Issue by Angelk90** [GeekyAnts/NativeBase#1488]
@GeekyAnts, @akhil-geekyants :
Link: 
exp://exp.host/@
community/nativebase-kitchen-sink

**Comment by SupriyaKalghatgi** [comment]
@Angelk90 From where did you refer this?

**Comment by SupriyaKalghatgi** [comment]
@Angelk90 Refer [nativebase.io/](https://nativebase.io/)

**Comment by Angelk90** [comment]
@SupriyaKalghatgi : 
Looking on google, I find the following pages:
https://expo.io/@community/native-base
https://expo.io/@community/native-base-kitchen-sink

So there is no native-base-kitchen-sink version on Expo published by you?
Is the playstore version managed by you?

**Comment by SupriyaKalghatgi** [comment]
@Angelk90 https://expo.io/@geekyants/nativebasekitchensink
