### ISSUE TITLE
Button with Icon and text broken.

### ISSUE THREAD

**Issue by 3210jr** [GeekyAnts/NativeBase#149]
Hey, thanks again for Naive base. I see that this was fixed in 5.7 however, after an update to react 15.3.1 and react-native 0.32.0, it seems to be back.

<img width="328" alt="screen shot 2016-08-29 at 11 59 12 pm" src="https://cloud.githubusercontent.com/assets/11012023/18067263/aa3ab796-6e44-11e6-95e0-7fb79d3bdce9.png">

This issue seems related to this one: [https://github.com/GeekyAnts/NativeBase/issues/140](url)
Thanks.

**Comment by 3210jr** [comment]
In Buttons.js i edited lines 168 and 174 from 
`newChildren.push(<Text key='label' style={this.getTextStyle()}>{(Platform.OS==='ios') ? childrenArray[0] : childrenArray[0].props.children.toUpperCase()}</Text>);` 
to:
`newChildren.push(<Text key='label' style={this.getTextStyle()}>{(Platform.OS==='ios') ? childrenArray[0] : childrenArray[0]}</Text>);`

seems to work. I did this after noticing that it was like this in an earlier version. I think the problem might be compatibility with the latest release.
Leaving it open for you to close if I am right.

**Comment by sankhadeeproy007** [comment]
Hi @3210jr, do you have the exact use case which leads to this error message? It was addressed in a previous update.

**Comment by fbacker** [comment]
Getting same issue when updated my project. Hard to se origin what component in my code but guessing example

	<Button primary style={styles.buttonSpace}
	  onPress={this._onSendList.bind(this)}
	  disabled={(scan.codes.length==0)} >
	  <Icon name='ios-home' />Skicka lista</Button>

**Comment by 3210jr** [comment]
The issue is coming from passing in text along with the icon to the button component. If you remove everything and leave the icon, it should work. I'm confident it's because of the new react, so to deal with this I edited the Buttons.js file in the node modules as shown above. And it works now

**Comment by sankhadeeproy007** [comment]
There was a problem with using `<Text />` inside the `<Button />` component.
Fixed with 0.5.8

**Comment by hippycore** [comment]
I have same problem with uglify bundle version. in debug version it's works fine

**Comment by sankhadeeproy007** [comment]
What is the exact error you're getting?
