### ISSUE TITLE
Change theme Tab and Sliding effect.

### ISSUE THREAD

**Issue by Angelk90** [GeekyAnts/NativeBase#1490]
@GeekyAnts, @akhil-geekyants :

Is it possible to change the theme of the tab component, as in the image?
For example: rounded corners, and being able to do Sliding effect?
![](https://i.imgur.com/TDVJzqZ.gif)
![](https://i.imgur.com/Xit5AlB.gif)
  

What I managed to do is this:
link; https://snack.expo.io/Hy0bUp1Ez
But I can not change the height, and then I realized, you have to look at it very close, it makes a strange effect the background of the tab and the tab seem to have backgrounds of an impetuous shade, but they are different.

As you can see in the image:
![](https://i.imgur.com/6EIDWMG.jpg)
![](https://i.imgur.com/D8gASi8.jpg)

**Comment by SupriyaKalghatgi** [comment]
@Angelk90 Having rounded borders with button in footer is quite simple
Include `rounded` prop with `<Button>` in `<Footer>`

![image](https://user-images.githubusercontent.com/13464885/34661944-00fa117a-f473-11e7-9d23-8bd39ba47b8a.png)

About sliding feature, thats not available with NativeBase

**Comment by Angelk90** [comment]
@SupriyaKalghatgi : 
You could post the complete code, I do not understand.
Then I would like it not to take all the available space, I would like to resize it.

**Comment by SupriyaKalghatgi** [comment]
@Angelk90 
> Include **rounded** prop with **Button** in **Footer**

This is the code, nothing extra.
You can resize the button and footer in `theme`

**Comment by Angelk90** [comment]
@SupriyaKalghatgi : 
but I'm not using:
https://docs.nativebase.io/Components.html#footer-tabs-def-headref
but I'm using:
https://docs.nativebase.io/Components.html#tabs-def-headref


There is also written in the code.

**Comment by SupriyaKalghatgi** [comment]
@Angelk90  Ah! My mistake, i mixed this up with #1489

**Comment by Angelk90** [comment]
@SupriyaKalghatgi : In the title there is written tab, there is no written footer. ;)

**Comment by SupriyaKalghatgi** [comment]
@Angelk90 https://github.com/GeekyAnts/NativeBase/issues/1490#issuecomment-355950393

**Comment by SupriyaKalghatgi** [comment]
@Angelk90 The Tabs designed by NativeBase are as per iOS and Android design guidelines
Though you can customize them as per your need

**Comment by SupriyaKalghatgi** [comment]
Go ahead ejecting the theme and customize
