### ISSUE TITLE
Where is Progress Bar?

### ISSUE THREAD

**Issue by 1c7** [GeekyAnts/NativeBase#1491]
https://docs.nativebase.io/Components.html#Components
![image](https://user-images.githubusercontent.com/1804755/34672147-433a5f8c-f4b8-11e7-8edb-af559bf34fa7.png)

![image](https://user-images.githubusercontent.com/1804755/34672154-50959d5e-f4b8-11e7-8075-7d9c5890cfda.png)

**Comment by SupriyaKalghatgi** [comment]
@1c7 Yes! we are aware of it, we are updating Docs
Earlier NativeBase had Progress Bar, somehow its content has been left
thank you

**Comment by SupriyaKalghatgi** [comment]
https://github.com/GeekyAnts/native-base-docs/issues/72

**Comment by olee2002** [comment]
still don't see progress bar?
