### ISSUE TITLE
ActionSheet.show not working from within ActionSheet callback

### ISSUE THREAD

**Issue by hardcodet** [GeekyAnts/NativeBase#1492]
## react-native, react and native-base version

RN 0.50, Nativebase 2.3.6

## Expected behaviour

When calling ActionSheet show() from an ActionSheet callback, a new ActionSheet should be displayed.

## Actual behaviour

Nothing happens. There's also no API to programmatically close the current ActionSheet if that was necessary.

## Is the bug present in both ios and android or in any one of them?

Only tested on Android.

**Comment by akhil-geekyants** [comment]
@hardcodet  NativeBase ActionSheet is a wrapper around the React Native [ActionSheetIOS](https://facebook.github.io/react-native/docs/actionsheetios.html)  component. Similar implementation has been done for Android, based on Material Design guidelines. The [ActionSheetIOS](https://facebook.github.io/react-native/docs/actionsheetios.html) documentation does not mention anything about closing the ActionSheet programmatically. So this has not been added into NativeBase ActionSheet API.

**Comment by madcoda** [comment]
I can confirm that on IOS it works, but not working on Android.

In my use case, I need to prompt 2 ActionSheets consecutively.
In the end, I set a little bit delay with setTimeout() and it's working on both

**Comment by WickyLim** [comment]
Hey @akhil-geekyants , I am still having this issue. Here's my code snippet, and the second ActionSheet (the one with title 'Confirm Action 1?') wont show on Android. Works fine in iOS.

```
ActionSheet.show(
  {
    options: ['Action 1', 'Cancel'],
    cancelButtonIndex: 1,
    title: 'Do something'
  },
  buttonIndex => {
    if(buttonIndex==0){
      ActionSheet.show(
        {
          options: ['Confirm', 'Cancel'],
          cancelButtonIndex: 1,
          title: 'Confirm Action 1?'
        },
        buttonIndex => {
          //confirm
        }
      )
    }
  }
)
```

I have to follow @madcoda suggestion to `setTimeout()` to make it work. This is the code thats working for your reference
```
ActionSheet.show(
  {
    options: ['Action 1', 'Cancel'],
    cancelButtonIndex: 1,
    title: 'Do something'
  },
  buttonIndex => {
    if(buttonIndex==0){
      setTimeout(
        () => {
          ActionSheet.show(
            {
              options: ['Confirm', 'Cancel'],
              cancelButtonIndex: 1,
              title: 'Confirm Action 1?'
            },
            buttonIndex => {
              //confirm
            }
          )
        }, Platform.OS === 'ios' ? 0 : 100
      )
    }
  }
)
```
