### ISSUE TITLE
List Item is not rendering properly when I am trying to render them dynamically

### ISSUE THREAD

**Issue by AnubhavUjjawal** [GeekyAnts/NativeBase#1493]
#  Dynamic List doesn't look pleasant.
Here is my code:
```
    <Content>
          <Card> 
            <List
              dataArray={this.props.employees}
              renderRow={item => (
                // <ListItem icon>
                <ListItem onPress={() => this.editEmp(item)}>
                  <CardItem>
                    <Body>
                      <Text>
                        {"    "}
                        {item.name}
                      </Text>
                    </Body>
                  </CardItem>
                </ListItem>
              )}
            />
          </Card>
        </Content> 
```
Also, item looks something like this:
![image](https://user-images.githubusercontent.com/22658701/34685281-ddf6d32e-f4cd-11e7-92bc-8144bc5dca8c.png)
I am using Nokia 5 with android Nougat.
When rendered, It shows this:
![image](https://user-images.githubusercontent.com/22658701/34685396-30074856-f4ce-11e7-82bf-82986f61ae9c.png)
I think I can see a pattern of rendering lists items in an incorrect way, grouping  of an item, then two items together most of the times, which looks unpleasant to eyes.

Please help regarding this issue.

**Comment by akhil-geekyants** [comment]
@AnubhavUjjawal you can also use ReactNative [FlatList](https://facebook.github.io/react-native/docs/flatlist.html) instead of List and use it with other NativeBase components.

**Comment by AnubhavUjjawal** [comment]
Yeah, but that is a work-around. Why is that thing behaving like that?

**Comment by akhil-geekyants** [comment]
@AnubhavUjjawal we are deprecating List. Use FlatList instead. This will be documented.

**Comment by toussa** [comment]
@akhil-geekyants I'm having another issue with List while trying to stick to native-base and not use FlatList.
Thanks for your last comment, it should be more visible as soon as possible I think, for everybody.

**Comment by SupriyaKalghatgi** [comment]
@toussa What is the issue?

**Comment by toussa** [comment]
@SupriyaKalghatgi Nothing related to this issue. I didn't succeed to re render the list based on some props or state, even if the data did not change. But I didn't investigate more when I saw this comment. I'm now using FlatList with ListItem

**Comment by SupriyaKalghatgi** [comment]
#759 for docs

**Comment by SupriyaKalghatgi** [comment]
I have opened this issue on the docs repo here: [#65](https://github.com/GeekyAnts/native-base-docs/issues/65)
Since we split the docs and the source into separate repos.

**Comment by Rolilink** [comment]
I am using `FlatList` and this weird behavior is still happening to me sometimes it doesn't render the borderBottom ...

**Comment by akhil-geekyants** [comment]
@Rolilink can you post some code for us to reproduce.

**Comment by yogabbagabb** [comment]
https://nativebase.io/docs/v0.3.0/components#list does not yet mention that  List will be (or is) deprecated. fyi.
