### ISSUE TITLE
Tab some information

### ISSUE THREAD

**Issue by Angelk90** [GeekyAnts/NativeBase#1497]
- In the heading tab can the badge be used together with the text? The documentation says that it takes string or component, but if I try to insert it by mistake.
- Can the size of the tab be adapted to the text? There are tabs that have short headings and instead headings that have long titles. Is it possible to set the whole dimension instead of different and adapt to the length of the title?

**Comment by SupriyaKalghatgi** [comment]
You can add Badge similar to Icons
![simulator screen shot - iphone 7 - 2018-01-10 at 12 45 52](https://user-images.githubusercontent.com/13464885/34761084-56036a86-f608-11e7-8fe7-2a07a880f6ce.png)

Adjusting Text width with Tab, you can find that with scrollable tabs and not with Fixed tab

**Comment by Angelk90** [comment]
@SupriyaKalghatgi : 

I did this way:
```
          <Tabn heading={
            <TabHeading badge  style={{backgroundColor: "#205cb2"}}>
              <Icon2 size={24} name="theaters" color="white" /><Badge ><Text>51</Text></Badge>
          </TabHeading>} ....
```

I'm doing it wrong?
The result is android is very bad.

Could you post a code example to see where I'm wrong?

**Comment by Angelk90** [comment]
![](https://i.imgur.com/oYNaV8h.jpg)

**Comment by Angelk90** [comment]
@SupriyaKalghatgi : You could kindly publish your code to test it on android.
