### ISSUE TITLE
Change space between Input text and underline

### ISSUE THREAD

**Issue by luizcieslak** [GeekyAnts/NativeBase#1499]
Hi! I'm trying to remove the space between the text of Input and its underline. I exported the custom theme in my project, tried to change the inputLineHeight variable but no sucess.

## react-native, react and native-base version
```
"react": "16.0.0-alpha.12",
"react-native": "0.49.0",
"native-base": "2.3.5",
```
## Expected behaviour
![Image](https://imgur.com/6AijwkO.png)
## Actual behaviour
![Image](https://imgur.com/LnnnXmX.png)

## Is the bug present in both ios and android or in any one of them?
Both of them.

## Steps to reproduce the problem

```
<Item stackedLabel>
  <Label>Usuário</Label>
  <Input />
</Item>
```

**Comment by SupriyaKalghatgi** [comment]
@luizcieslak `inputHeightBase` and `inputLineHeight` should help you change the space between Input text and and its border

**Comment by muhammadarsal** [comment]
@SupriyaKalghatgi would you provide example?

**Comment by occult** [comment]
@muhammadarsal @luizcieslak Did any of you guys find a solution? Editing `inputHeightBase` and `inputLineHeight` isn't doing it for me :/

**Comment by nwmannoly** [comment]
@SupriyaKalghatgi your solution does not work - this issue should not have been closed. Does anybody have a solution?

**Comment by lakshmajim** [comment]
Same here

**Comment by Xmaxer** [comment]
For anyone still coming to this issue in 2023.

A possible workaround:

```JSX
   <Input
      _input={{
        marginBottom: -2,
      }}
      variant={'underlined'}
    />
```

Where the negative margin forces the underline border move closer, the more negative the number the closer it is to the actual input.

I wish there was a proper solution instead of this. I don't understand how this was closed without a real resolution. It should be reopened.
