### ISSUE TITLE
Error using InputGroup example

### ISSUE THREAD

**Issue by chromakey** [GeekyAnts/NativeBase#15]
Hello,
I receive the following error when using the InputGroup example from the documents:

```
undefined is not an object (evaluating 'icon.props')

getIconProps
InputGroup.js @ 97:0
```

I linked the react-native-vector-icons with both rnpm and set them up manually in XCode.  I'm brand new to react-native so I apologize in advance if this was an error on my part.  Running react-natve 0.25.1 and native-base 0.3.0.

**Comment by himanshu-sahusoft** [comment]
Hi @chromakey, it was a bug in our code. We will be releasing a patch today v0.3.1 to fix this issue.

**Comment by chromakey** [comment]
Thanks!  I appreciate the quick fix!
