### ISSUE TITLE
List / ListItem Touchability lost / returns

### ISSUE THREAD

**Issue by brianjd** [GeekyAnts/NativeBase#150]
I am having an odd issue with List (ListView).  I have a screen with a searchBar/ListView combination, where I monitor the search field for change, perform a search, and then update the dataArray.  I haven't fully isolated it yet, but sometimes after a dataArray/dataSource update, certain ListItems lack touchability (onPress not fired, no feedback).    I tried to use the inspector on the ListItems in question, and its as if nothing is there.  But when I use the inspector to view touchables, they are highlighted as if they are.    Then randomly, touchability sometimes returns.  

Any help will be appreciated, thanks.

**Comment by sankhadeeproy007** [comment]
Hi, since this issue has been here for a long time and it's not very consistent, we're closing this. Feel free to reopen this with an example (preferably) so that we have a better idea of what we're dealing with.
