### ISSUE TITLE
ListItem <body>, <right> and <left> children don't support onPress

### ISSUE THREAD

**Issue by novellizator** [GeekyAnts/NativeBase#1500]
Hi! Thanks for trying out NativeBase!
Due to the overwhelming requests and issues/questions we ask you to add the following details with your issue.

Please check the existing open/closed issues for a possible duplicate before creating a new issue :)

Also **DO** fill out the below form to give us a better idea about your environment and help us debug it quicker. Issues without the required details will mostly be unattended to.

## Expected behaviour
ListItem's `<body>, <right> and <left>` children don't support onPress event. Instead ListItem's onPress takes it all. The only way to capture an event is to use several `<Text>` elements inside the ListItem's body and every such element reacts to onPress. I cannot however then fragment it further as to make just certain parts of the Text clickable.

**Comment by akhil-geekyants** [comment]
@novellizator if you have multiple children for `<Left/>,<Body/> or <Right/>` component, you can handle the onPress by grouping them and wrapping with [TouchableOpacity](https://facebook.github.io/react-native/docs/touchableopacity.html) / [TouchableWithoutFeedback](https://facebook.github.io/react-native/docs/touchablewithoutfeedback.html) / [TouchableHighLight](https://facebook.github.io/react-native/docs/touchablehighlight.html) / [TouchableNativeFeedback](https://facebook.github.io/react-native/docs/touchablenativefeedback.html) from ReactNative

Gif

![onpress](https://user-images.githubusercontent.com/27768184/34812127-51402dfa-f6ca-11e7-816d-3af270c6bb01.gif)

**Comment by SupriyaKalghatgi** [comment]
`<Left>`, `<Body>`, `<Right`> are View components

**Comment by akhil-geekyants** [comment]
Closing this issue due to no response.
