### ISSUE TITLE
Can't Install native-base (error code 128, permission denied)

### ISSUE THREAD

**Issue by indarjoko** [GeekyAnts/NativeBase#1502]
Can anyone help me?

npm install native-base --save
npm ERR! code 128
npm ERR! Command failed: /usr/bin/git clone -q https://github.com/GeekyAnts/react-native-drawer.git /root/.npm/_cacache/tmp/git-clone-d382b195
npm ERR! fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-d382b195': Permission denied
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-01-12T03_46_58_168Z-debug.log

**Comment by SupriyaKalghatgi** [comment]
@indarjoko Probably `git` issue on your system
Try cloning with SSH

**Comment by indarjoko** [comment]
still showing permission denied issue.
what can i do now?

**Comment by SupriyaKalghatgi** [comment]
@indarjoko NativeBase has thousands of downloads and install every day
No such issues by any one
Check node and npm versions

**Comment by indarjoko** [comment]
okay.

node -v
v8.9.4
npm -v
5.6.0

should I downgrade node/npm?

**Comment by SupriyaKalghatgi** [comment]
@indarjoko Checked some google results
Many libraries facing such issue with npm 5
Try with npm 4

**Comment by indarjoko** [comment]
when I downgrade npm version to 4.
it's worked for me.
thanks a lot.
