### ISSUE TITLE
[Question] Is there a way to hide Header and Footer with slide animation when page scroll?

### ISSUE THREAD

**Issue by lucianomlima** [GeekyAnts/NativeBase#1503]
My app have a screen that is a long text reader.
I can hide Header and Footer with conditional render, but I don't know how to do with slide animation when user scrolls down.

Is there a way to do this only with NativeBase components or I need something like react-native-animatable?

**Comment by SupriyaKalghatgi** [comment]
@lucianomlima NativeBase does not provide any kind of animation support as of now

Check this repo of [Twitter clone](https://github.com/pranit123/Twitter-Clone), this might be helpful to you

**Comment by lucianomlima** [comment]
Thanks @SupriyaKalghatgi I will take a look.
