### ISSUE TITLE
Static value of floatUp() in Item component

### ISSUE THREAD

**Issue by Xvie** [GeekyAnts/NativeBase#1504]
## Expected behaviour
Possibility to change `Item` `.floatingLabel` `floatUp` value` dynamically via props with default value of `-16` (as it is now)
## Actual behaviour
Hardcoded, unable to be changed value on `floatUp` animation in `Item.floatingLabel`
## Is the bug present in both ios and android or in any one of them?
yes
## Any other additional info which would help us debug the issue quicker.
not needed

**Comment by SupriyaKalghatgi** [comment]
@Xvie Is that you want to have different values with `floatUp()` by passing props dynamically
OR
You want it to customizable with theme

**Comment by Xvie** [comment]
@SupriyaKalghatgi i think passing it through props it's much easier to implement so i think props are okay.

**Comment by SupriyaKalghatgi** [comment]
@Xvie What is the difficulty you are finding?

**Comment by SupriyaKalghatgi** [comment]
@Xvie If you look into the code of `Item`, the value for `floatUp()` is static

**Comment by Xvie** [comment]
Yea and i think it would be great if it's dynamic.

**Comment by SupriyaKalghatgi** [comment]
@Xvie We dont have plans to make it dynamic
This will remain static
