### ISSUE TITLE
[ANDROID] BUTTON bottomColor or bottomwidth vs borderBottomWidth or borderBottomColor

### ISSUE THREAD

**Issue by GuillotJessica** [GeekyAnts/NativeBase#1506]
I can't figure a way to only have one side bordered on an element,
it is all or nothing...

**Comment by akhil-geekyants** [comment]
@GuillotJessica you can use `borderBottomWidth` & `borderBottomColor` to specify the width and color of bottom border. Same way you can apply border to the other sides. Attaching a Gif

Gif

![border](https://user-images.githubusercontent.com/27768184/34873784-7f8fc420-f7bc-11e7-9755-971fd305a4df.gif)

**Comment by GuillotJessica** [comment]
I'll give it an other try, thx
