### ISSUE TITLE
Know active page of the tab

### ISSUE THREAD

**Issue by Angelk90** [GeekyAnts/NativeBase#1509]
hi, I wanted to know if there is any trick to know which page of the tabs is active?

**Comment by SupriyaKalghatgi** [comment]
@Angelk90 You can get help from https://github.com/skv-headless/react-native-scrollable-tab-view#props

**Comment by mohity777** [comment]
<Tabs onChangeTab={(g)=>{console.log(g)}}>

g.i will give u the active index
