### ISSUE TITLE
[FEATURE REQUEST] Live theme editor

### ISSUE THREAD

**Issue by josephbuchma** [GeekyAnts/NativeBase#1510]
I was looking at available UI toolkits for RN, and I'm surprised that I haven't seen an evidence of live theme editor in any of them (have I missed one ?)

The idea is following: you have an app with all available UI elements from NativeBase ui kit, you open it inside emulator, and you can click on any element and live-edit it's styles (including editing style variables that are used in different places) in pop-up that appeared. And in the end you can export file with generated styles.
At first sight I'd say that it's quite easy to implement, especially if you're maintainer of UI kit like NativeBase, but even if it's hard - I think such editor absolutely worth it.

**Comment by sankhadeeproy007** [comment]
cc @sanketsahusoft

**Comment by sanketsahusoft** [comment]
@josephbuchma @sankhadeeproy007 We are building this! It will be live by Feb 15th!

**Comment by josephbuchma** [comment]
Awesome!

**Comment by sanketsahusoft** [comment]
Subscribe to NativeBase newsletter. We will post it there. :-)

**Comment by josephbuchma** [comment]
@sanketsahusoft any updates on this ? The newsletter seems to be quiet.

**Comment by SupriyaKalghatgi** [comment]
@josephbuchma http://nativebase-customizer.geekydev.com/

**Comment by josephbuchma** [comment]
@SupriyaKalghatgi looks awesome! But it does not export correct styles, downloaded app still contains default styling.

**Comment by SupriyaKalghatgi** [comment]
@josephbuchma 
![image](https://user-images.githubusercontent.com/13464885/37148211-9a6b498c-22ef-11e8-8b83-0873a179fbb6.png)
