### ISSUE TITLE
Bug: `onScroll` on `List` not get called

### ISSUE THREAD

**Issue by oferRounds** [GeekyAnts/NativeBase#1511]
react-native, react and native-base version: `0.48.3`
native-base version: `2.3.6`

Expected behaviour: `onScroll` event should get fired

Actual behaviour: `onScroll` event does not get fired

Steps to reproduce (the following is inside `Container` and `Content`):

```
<List
      onScroll = { this._onScroll.bind(this) }
      dataArray = { this.props.lastSheet.workDays }
      renderHeader = { this._headerItem.bind(this) }
      renderRow = {( item: TimeLogModel, _sectionId: number, rowId: string ) =>
           { return (<MetaTimeEntryCell
                                data = { item }
                                rowId = { rowId }
                                onItemPress = { this._onItemPress.bind(this) } />
                              )
  } />
```

**Comment by oferRounds** [comment]
It seems that happens because the `Content`’s `onScroll` is the one that triggers. If one would set the Content’s `scrollable` to `false` then the `List`’s `onScroll` does get called. The problem is that it causes other issues...

**Comment by SupriyaKalghatgi** [comment]
@oferRounds What help do you need here

**Comment by oferRounds** [comment]
@SupriyaKalghatgi I’d like to register to the `onScroll` event, and currently it’s not working when `List` is presented inside `Content`

**Comment by oferRounds** [comment]
And in general, I believe it’s a bug, so I opened an issue...

**Comment by akhil-geekyants** [comment]
@oferRounds NativeBase`<Content>` itself is a ScrollView (you can read about `<Content/>` [here](http://docs.nativebase.io/Components.html#anatomy-headref)). So a Scrollview inside Content component behaves the same way as a ScrollView inside a ScrollView.

**Comment by oferRounds** [comment]
@akhil-geekyants thanks! 
I’m aware of that, but the question still remains: how do I get the `onScroll` event. Or the right method should be to put the list just in a `Container` (without `Content`)?

**Comment by akhil-geekyants** [comment]
@oferRounds you can use Container without Content. But then you won't get the functionalities provided with Content like Keyboard avoiding view. Other than that, it should not create any other issues.

**Comment by oferRounds** [comment]
@akhil-geekyants got you, thanks!
