### ISSUE TITLE
Picker selected text wrapping

### ISSUE THREAD

**Issue by svallen** [GeekyAnts/NativeBase#1513]
Currently using: 

 "expo": "^22.0.0",
    "native-base": "^2.3.3",
    "react": "16.0.0-beta.5",
    "react-native": "https://github.com/expo/react-native/archive/sdk-22.0.2.tar.gz",

Picker when small is wrapping the text. I tried to override the main nativebase picker component but nothing seemed to work. Any thoughts on how to force the text to be a single line and not wrap?

![screen shot 2018-01-15 at 12 19 12 pm](https://user-images.githubusercontent.com/6169781/34954404-54c9db84-f9ee-11e7-88c4-9470caf65b7e.png)

**Comment by akhil-geekyants** [comment]
@svallen can you share your code for us to test.

**Comment by svallen** [comment]
@akhil-geekyants working on getting you some sample code. will post as soon as I have a snippet in place

**Comment by svallen** [comment]
Here is the sample code.  I believe it should give you an idea.

**IMAGE**

![screen shot 2018-01-19 at 12 10 53 pm](https://user-images.githubusercontent.com/6169781/35162574-d3bc29a8-fd11-11e7-9812-aef3ed1e873b.png)

**CODE:**

'use strict';

/* --- Imports --- */
import React, { Component } from 'react';

import PropTypes from 'prop-types';

import { StyleSheet, Text, View} from 'react-native';

import { Container, Content, Header, Picker, Icon } from 'native-base';

/* --- Class methods --- */

class PickerTest extends Component {

    
constructor(props) 
{
    super(props);
	
	this.state = {

    };
	
  }
	

// RENDER PAGE   
render() {

	// RETURN ALL ABOVE VALUES TO SCROLLVIEW TO BE SHOWN
 
    return (
      	<Container style={{marginTop:50}}>
			
			<Header style={[styles.pickerHeader]}>
				
						<View style={[styles.pickerWrap]}>
							<Icon name="md-arrow-dropdown" style={[styles.pickerIcon]}/>
							<Picker
							  mode="dropdown"
							  placeholder="Select Season"
							  selectedValue={0}
							  textStyle={[styles.pickerText]}
							  itemStyle={{ backgroundColor: '#fafafa', marginLeft: 0, paddingLeft: 30 }}
							  style={[styles.picker1]}
							>
								<Picker.Item value={0} label={"Test test test test 1"} />
								<Picker.Item value={1} label={"Test test test test 2"} />
								<Picker.Item value={2} label={"Test test test test 3"} />
							</Picker>
						</View>
					        
						<View style={[styles.pickerWrap]}>
							<Icon name="md-arrow-dropdown"  style={[styles.pickerIcon]}/>
							<Picker
							  mode="dropdown"
							  placeholder="Select Type"
							  selectedValue={this.state.salarySelected}
							  textStyle={[styles.pickerText]}
							  itemStyle={{ backgroundColor: '#fafafa', marginLeft: 0, paddingLeft: 30 }}
							  style={[styles.picker1]}
							  itemTextStyle={{  }}
							>
								<Picker.Item value={0} label={"Test test test test 1"} />
								<Picker.Item value={1} label={"Test test test test 2"} />
								<Picker.Item value={2} label={"Test test test test 3"} />

							</Picker>
					   </View>
                	         
						<View style={[styles.pickerWrap]}>
							<Icon name="md-arrow-dropdown"  style={[styles.pickerIcon]}/>
							<Picker
							  mode="dropdown"
							  placeholder="Select Team"
							  selectedValue={this.state.teamSelected}
							  textStyle={[styles.pickerText]} 
							  itemStyle={{ backgroundColor: '#fafafa', marginLeft: 0, paddingLeft: 30 }}
							  style={[styles.picker1]}
							  itemTextStyle={{  }}
							>
								<Picker.Item value={0} label={"Test test test test 1"} />
								<Picker.Item value={1} label={"Test test test test 2"} />
								<Picker.Item value={2} label={"Test test test test 3"} />
							</Picker>
					   </View>
                	
						<View style={[styles.pickerWrap]}>
							<Icon name="md-arrow-dropdown"  style={[styles.pickerIcon]}/>
							<Picker
							  mode="dropdown"
							  placeholder="Select Position"
							  selectedValue={this.state.positionSelected}
							  textStyle={[styles.pickerText]}  
							  itemStyle={{ backgroundColor: '#fafafa', marginLeft: 0, paddingLeft: 30 }}
							  style={[styles.picker1]}
							  itemTextStyle={{  }}
							>
								<Picker.Item value={0} label={"Test test test test 1"} />
								<Picker.Item value={1} label={"Test test test test 2"} />
								<Picker.Item value={2} label={"Test test test test 3"} />
							</Picker>
					   </View>
                	
                	
                
			</Header>
		</Container>
    )

	
  }
}

/* --- Stylesheet --- */

const styles = 	{ 
	pickerHeader:{justifyContent:'center',flexDirection:'row',opacity:1,paddingTop:0, paddingBottom:0, height:40,backgroundColor:'#012552'},    
	
	pickerWrap:{position:'relative',flex:1,flexDirection:'column',marginRight:10}, 	picker1:{alignSelf:'stretch',height:26,backgroundColor:'#fafafa',borderRadius:2,paddingLeft:0,borderWidth:.25,borderColor:'#012552',marginTop:7},
	
  	pickerIcon:{ backgroundColor:'transparent',right:5, marginLeft: 0,flex:1,position:'absolute',top:10,zIndex:1000,color:'#012552',fontSize:20},
	
  	pickerText:{fontSize: 11,color:'#012552',paddingLeft:10},
 }


/* --- Module exports --- */

module.exports = PickerTest;

**Comment by akhil-geekyants** [comment]
@svallen this is as per the design guidelines. Picker is supposed to show both placeholder content and selected item content. 
For your use case, either you can specify the width of the Picker or reduce the number of Picker's in a single row.

**Comment by akhil-geekyants** [comment]
@svallen you can modify code in `renderButton(){}` function inside `native-base/src/basic/Picker.ios.js`. Attaching a Gif

Gif

![picker2](https://user-images.githubusercontent.com/27768184/35262953-d1d64230-003c-11e8-9536-cd0ff412efb4.gif)

**Comment by svallen** [comment]
Thanks, I will take a look and see if that works for me.  Appreciate the help.

**Comment by svallen** [comment]
Sorry to be such a pain.

I'm use Expo and when I update the code and refresh it doesn't seem to update like your's is.

It's as if the node_module code isn't updating itself on refresh.

Thoughts?

**Comment by SupriyaKalghatgi** [comment]
@svallen Is that happening with any other expo app of yours?

**Comment by akhil-geekyants** [comment]
In `node_modules/native-base/package.json`  

try changing
```
"main": "dist/src/index.js",
```
to
```
"main": "src/index.js",
```

**Comment by SupriyaKalghatgi** [comment]
@svallen In case of no response, this issue will be closed in a day or so

**Comment by svallen** [comment]
Never could get it to work. Decided to refactor how we use the pickers. Thanks for the assistance.

**Comment by Juliocbr** [comment]
Hi,

I tried the @akhil-geekyants solution but the component is not updated =(. I don't know if it is necessary to take an extra step.

**Comment by jsastriques** [comment]
same issue, please solution. thanks
