### ISSUE TITLE
Typescript declaration file missing ScrollableTab

### ISSUE THREAD

**Issue by Right2Drive** [GeekyAnts/NativeBase#1517]
## react-native, react and native-base version
`react-native`: 0.49.5
`react`: 16.0.0-beta.5
`native-base`: 2.3.6

## Expected behaviour
`import { ScrollableTab } from 'native-base';` should be valid

## Actual behaviour
`Module '"<my_dir>/node_modules/native-base/index"' has no exported member 'ScrollableTab'.`
I also do not see it in the `index.d.ts` declaration file

## Any other additional info which would help us debug the issue quicker.
I also noticed that the example in the docs [here](https://docs.nativebase.io/Components.html#tabs-scrollable-headref) is showing how to use this component in v2.2.0, however in the example it is never actually imported from anywhere? Just thought I would mention it :)

**Comment by SupriyaKalghatgi** [comment]
Fixed with [2.3.8](https://github.com/GeekyAnts/NativeBase/releases/tag/v2.3.8)
