### ISSUE TITLE
TS: update d.ts for prop style accept array

### ISSUE THREAD

**Issue by ArmandoAssuncao** [GeekyAnts/NativeBase#1520]
Hi,

I'm using this code to set two styles in prop of component: 
```
<Button
       style={[styles.one, styles.two]}
>
  foo                
 </ButtonNative>
```

But ts show this warning:
`Type 'ViewStyle[]' has no properties in common with type 'ViewStyle'`

What do you think about defining the prop `style` in `.d.ts`, like:
```
interface Button ... {
  style?: ReactNative.ViewStyle | ReactNative.ViewStyle[];
}
```

native-base: 2.3.6

**Comment by SupriyaKalghatgi** [comment]
Fixed with [2.3.8](https://github.com/GeekyAnts/NativeBase/releases/tag/v2.3.8)
