### ISSUE TITLE
Npm install

### ISSUE THREAD

**Issue by oximer** [GeekyAnts/NativeBase#1521]
Hey guys,

I noticed that you added two Github repositories as dependencies of this project and this are causing me problems.

When using GitHub as dependencies you don't specify a released build version. Actually you are cloning the master branch. Thus, you never know what is coming for your project. 

**This is an issue for security.**

In my specific scenario this situation is even worse. All the server that I use for building don't have access to internet. Those server have this restriction aiming to guarantee that we have all source code used for building.

Thus, I want to suggest this project to use a release stable version instead of a Github repositories.

**Comment by gutoglup** [comment]
In the package.json file there are two dependencies that use the github clone. If it is possible to change the repositories to a stable version of npm to correct the problem mentioned.
Also taking advantage of the following repositories have register in the npm.
 ```
"react-native-drawer": "https://github.com/GeekyAnts/react-native-drawer",
"react-native-keyboard-aware-scroll-view": "https://github.com/GeekyAnts/react-native-keyboard-aware-scroll-view"
```

**Comment by Jancat** [comment]
@SupriyaKalghatgi  Can you release a patch? I need the fix with a little emergency. Thanks !!

**Comment by SupriyaKalghatgi** [comment]
Release patch 2.3.7 with fix
