### ISSUE TITLE
Press event in a swipeable list is not received the first time when the focus is on an input text outside of the list

### ISSUE THREAD

**Issue by fabricehong** [GeekyAnts/NativeBase#1523]
I have a swippeable list containing buttons, and down below, an input box. After I press in the input box to start writing, If I click on one of the buttons in the list, nothing happens. I need to click a second time so the click event is received.

If I replace the swippeable list by a normal native base list as defined in the component doc, the event is received straight away on the first click

## Versions
"native-base": "^2.3.3"
"react": "16.0.0"
"react-native": "0.50.1"

## Expected behaviour
When I click on a button in the list, the click event is processed, even if I'm focusing in an input component below
## Actual behaviour
When I click on a button in the list, the first click even is not received. A second click will trigger the event.
## Steps to reproduce (code snippet or screenshot)

```
render() {
		let ds = new ListView.DataSource({
			rowHasChanged: (r1, r2) => {
				let result = r1 !== r2;
				return result;
			}
		});
		return (

			<View style={{flex:1}}>
				<List
					enableEmptySections
					dataSource={ds.cloneWithRows(["test"])}
					renderRow={_ => {
						return (
							<View>
								<Button onPress= {() => console.warn('event received')}><Text>A button</Text></Button>
							</View>

						);
					}}
					renderRightHiddenRow={(data : any, secId : any, rowId : any, rowMap : any) => (
						<Button
							full
							danger
							onPress={_  => {}}
						>
							<Icon active name="trash" />
						</Button>
					)}

				/>
				<Input
				placeholder="search"
				/>
			</View>
		);
	}
```

## Screenshot of emulator/device
![movie export](https://user-images.githubusercontent.com/4489934/35065350-50e62bc2-fbcd-11e7-82ee-c8720d214c95.gif)

## Is the bug present in both ios and android or in any one of them?
Present in ios + android

**Comment by akhil-geekyants** [comment]
@fabricehong checked this with SwipeList and ListItem. Both were behaving the same. Isn't the first click used to dismiss the keyboard when input is on focus.

**Comment by akhil-geekyants** [comment]
@fabricehong just add prop `keyboardShouldPersistTaps={'handled'}` to `<List/>`

Gif

![click2](https://user-images.githubusercontent.com/27768184/35214685-fefebf72-ff87-11e7-886b-b37127a82cf4.gif)

**Comment by fabricehong** [comment]
It works ! thank you very much :)
