### ISSUE TITLE
ListItem TouchableHighlight

### ISSUE THREAD

**Issue by acamenhas** [GeekyAnts/NativeBase#153]
Hi guys, thank you for this awesome project!!

One thing that i'm feeling that is important is the importance of letting the user know that he pressed a list item (because that's what react native all about).

Can you a TouchableHighlight on the top of the list item?

**Comment by sankhadeeproy007** [comment]
Hi, there is touchableOpacity wrapped around which gives noticeable enough feedback.

**Comment by acamenhas** [comment]
Hi, i've tried on android device and genymotion and i have no feedback.
Tapping or not tapping i have the same result: no highlight

**Comment by sankhadeeproy007** [comment]
There won't be any highlight, just the opacity will change on press. And that works just fine.

**Comment by acamenhas** [comment]
Didnt saw the: 'button' propery.
Works well yes.
Closed
