### ISSUE TITLE
Using FAB as a button

### ISSUE THREAD

**Issue by TheMonster1995** [GeekyAnts/NativeBase#1531]
I'm trying to use FAB as a button - to navigate to another page and NOT open any extra FABs, and for some reason, it doesn't work.

## react-native, react and native-base version
react-native: 0.50.3
react: 16.0.0
native-base: 2.3.6

## Expected behavior
Navigate to the new page

## Actual behavior
Nothing happens

## Steps to reproduce (code snippet or screenshot)
      <Container>
        <StatusBar barStyle="default" hidden={false} />
        <Header>
          <Left />
          <Body>
            <Text>
              ABC
            </Text>
          </Body>
          <Right />
        </Header>
        <StatusBar
          barStyle="light-content"
        />
        <Fab
          active={'true'}
          direction="up"
          containerStyle={{ }}
          style={{ backgroundColor: '#9f3799' }}
          position="bottomRight"
          onPress={() => navigation.navigate("Search")}
        >
          <Icon name="ios-search" />
        </Fab>
        <Content>
          <View
            style={{
              flex: 1,
              borderBottomColor: "#D9D5DC",
              borderBottomWidth: (1 / PixelRatio.getPixelSizeForLayoutSize(1)) * 2,
              flexDirection: "row",
              padding: 8,
            }}
          >
            <Left
              style={{
                flex: 1
              }}
            >
              <Thumbnail 
                source={require("../../img/inLogo.png")}
              />
            </Left>
            <Body
              style={{
                alignSelf: "flex-start",
                flexDirection: "column",
                flex: 3, 
                alignItems: "flex-start",
                justifyContent: "flex-start",
                paddingTop: 5, 
              }}
            >
              <Text
                style={{
                  color: "rgba(0, 0, 0,0.9)",
                  fontSize: 18,
                  marginBottom: 5 
                }}
              >
                John Doe
              </Text>
              <Text
                style={{
                  color: "rgba(0, 0, 0, 0.5)",
                  fontSize: 12
                }}
              >
                Last seen about a week ago
              </Text>
            </Body>
          </View>
        </Content>
      </Container>

## Is the bug present in both ios and android or in any one of them?
It appears on android. I haven't tested it on iPhone yet.

**Comment by akhil-geekyants** [comment]
@TheMonster1995 tried a sample code with react-navigation. It is working fine. Attaching a Gif.

Gif

![fab](https://user-images.githubusercontent.com/27768184/35263630-97009d4c-003f-11e8-950e-a05535bb322c.gif)

Sample Code

```
import React from 'react'
import { StackNavigator } from 'react-navigation'
import { Button } from 'react-native'
import { Container, Header, View, Icon, Fab } from 'native-base';

class MyHomeScreen extends React.Component {
  static navigationOptions = {
    title: 'Home',
  }

  render() {
    return (
      <Container>
        <View style={{ flex: 1 }}>
          <Fab
            active={true}
            direction="up"
            containerStyle={{}}
            style={{ backgroundColor: '#5067FF' }}
            position="bottomRight"
            onPress={() => this.props.navigation.navigate('Profile')}>
            <Icon name="share" />
          </Fab>
        </View>
      </Container>
    );
  }
}

class MyProfileScreen extends React.Component {
  static navigationOptions = {
    title: 'Profile',
  }

  render() {
    return (
      <Container>
        <View style={{ flex: 1 }}>
          <Fab
            active={true}
            direction="up"
            containerStyle={{}}
            style={{ backgroundColor: '#5067FF' }}
            position="bottomRight"
            onPress={() => this.props.navigation.goBack()}>
            <Icon name="share" />
          </Fab>
        </View>
      </Container>
    );
  }
}

export default ModalStack = StackNavigator({
  Home: {
    screen: MyHomeScreen,
  },
  Profile: {
    screen: MyProfileScreen,
  },
});

```

**Comment by TheMonster1995** [comment]
It's okay untill you add a Content tag. Actually, the problem is not with it not functioning. It doesn't get clicked at all once a content component is added.

Should I open another issue and close this one?

**Comment by akhil-geekyants** [comment]
@TheMonster1995 `<Content/>` component is an implementation of ScrollView. Can you try setting prop `contentContainerStyle={{ flex: 1 }}` for `<Content/>`.

![fab](https://user-images.githubusercontent.com/27768184/35375866-98dd6fa6-01ce-11e8-9df9-fbb16d875d4f.gif)

**Comment by SupriyaKalghatgi** [comment]
This to be documented [#1427](https://github.com/GeekyAnts/NativeBase/issues/1427)

**Comment by dylan-chong** [comment]
The Fab still does nothing when placed outside of content

```
import {
  Body,
  Button,
  Container,
  Content,
  Fab,
  Icon,
  Left,
  ListItem,
  Right,
  Text
} from 'native-base';
import { FlatList } from 'react-native';
import { type NavigationState } from 'react-navigation';
import React, { Component } from 'react';

import { userData } from '../services/UserService';

type Props = { navigation: NavigationState };

export class TasksScreen extends Component<Props> {
  static navigationOptions = { title: 'Tasks' };

  createTask() {
    const { navigate } = this.props.navigation;
    navigate('CreateTask');
  }

  editTask(entry) {
    const { navigate } = this.props.navigation;
    navigate('EditTask', {
      task: entry.item,
      index: entry.index,
    })
  }

  render() {
    return (
      <Container>
        <Fab
          direction="left" 
          position="bottomRight" 
          onPress={ () => this.createTask() }>
          <Icon name="add" />
        </Fab>
        <Content contentContainerStyle={{ flex: 1 }}>
          <FlatList
            data={ userData.currentUser().tasks }
            renderItem={ entry =>
              <ListItem itemDivider>
              <Left />
              <Body>
                <Text>
                  { entry.item.title }
                </Text>
              </Body>
              <Right>
                <Button transparent onPress={ () => this.editTask(entry) }>
                  <Icon active name="arrow-forward" />
              </Button>
            </Right>
              </ListItem>
            }
          />
      </Content>
      </Container>
    );
  }
}
```

**Comment by Dimon70007** [comment]
try to use usual rounded Button instead of Fab. It worked for me

**Comment by Aliar03f** [comment]
Just use FAB component after Flatlist then it will work perfectly
