### ISSUE TITLE
Floating label cut off

### ISSUE THREAD

**Issue by Gerharddc** [GeekyAnts/NativeBase#1532]
## react-native, react and native-base version

- React-Native 0.52.0

- React: 16.2.0

- Native-Base: 2.3.7

## Expected behaviour
When using an input with a floating label, the entire label should be visible when floating.
## Actual behaviour
Once the label starts floating, the top half of the label is cut off.
## Steps to reproduce (code snippet or screenshot)
Something as simple as the following basic case causes it:
```
<Form>
  <Item floatingLabel>
    <Label>Test</Label>
    <Input />
  </Item>
  <Item floatingLabel>
    <Label>Test</Label>
    <Input />
  </Item>
  ...
</Form>
```
## Screenshot of emulator/device
![screenshot_1516514113](https://user-images.githubusercontent.com/11624490/35191304-7865b8e2-fe80-11e7-8114-9a8a0df245b8.png)

## Is the bug present in both ios and android or in any one of them?
I am not able to test it on iOS at the moment.
## Any other additional info which would help us debug the issue quicker.
It used to work a while ago but I only noticed it is broken now, not sure on which version it broke.

**Comment by sarahmarciano** [comment]
+1 I have the same issue, and it happened when I've upgraded react-native to 0.52.0

**Comment by tindery** [comment]
I'm having same issue, also after upgrading to 0.52

**Comment by akhil-geekyants** [comment]
@carathorys you can add some padding to the top for `<Label/>`.

Gif

![floating label](https://user-images.githubusercontent.com/27768184/35266373-277350d2-0049-11e8-938c-2ddb6f6e85b7.gif)

**Comment by ViktorAksionov** [comment]
I found out that Label has hard coded value for `top`.
In my case I did something like this to fix it:
```
    let top = 0;
    if ( active || input.value.length > 0) {
      top = 16;
    }
```
...
```
<Label style={{top}}>{labelText}</Label>
```

**Comment by ViktorAksionov** [comment]
Looks like it's an issue with `Item` component.
If you replace `lineHeight` from 30 by 50 [here](https://github.com/GeekyAnts/NativeBase/blob/master/src/basic/Item.js#L84) then it will not cut off Label. 

Can somebody check why it has wrong value?

**Comment by SupriyaKalghatgi** [comment]
sure

**Comment by pennyandsean** [comment]
@akhil-geekyants I appreciate the tip however a fix would be better.  Want a PR?

**Comment by SupriyaKalghatgi** [comment]
@pennyandsean There is a PR for this

**Comment by SupriyaKalghatgi** [comment]
Fixed with [2.3.8](https://github.com/GeekyAnts/NativeBase/releases/tag/v2.3.8)

**Comment by raajnadar** [comment]
This will be very help for instead of hardcoding in each form.

Put a padding in the theme/components/Label.js file the path may be different for you

```
import variable from "./../variables/platform";

export default (variables = variable) => {
	const labelTheme = {
		".focused": {
			width: 0
		},
		fontSize: 17,
		paddingTop: 2 // This much is enough to fix
	};
	return labelTheme;
};
```

**Comment by akhil-geekyants** [comment]
@raajnadar checked this with native-base : 2.4.1. Couldn't see this. Posting code.
Code
```
import React, { Component } from 'react';
import { Container, Header, Content, Form, Item, Input, Label } from 'native-base';
export default class App extends Component {
  render() {
    return (
      <Container>
        <Header />
        <Content>
          <Form>
            <Item floatingLabel>
              <Label>Username</Label>
              <Input />
            </Item>
            <Item floatingLabel last>
              <Label>Password</Label>
              <Input />
            </Item>
          </Form>
        </Content>
      </Container>
    );
  }
}
```
Video

[cutoff.mp4.zip](https://github.com/GeekyAnts/NativeBase/files/1870787/cutoff.mp4.zip)

**Comment by raajnadar** [comment]
@SupriyaKalghatgi will the existing changes be overwritten after ejecting??

**Comment by ViktorAksionov** [comment]
@raajnadar 
Ejecting just doing simple copy, it's not a merging process, so yeah, you will loose your data in case if you ejected before and modified them.

**Comment by SupriyaKalghatgi** [comment]
@raajnadar Yes, if there is any update in `native-base/src/theme`, then existing changes will be overwritten on ejecting theme
This is not merge process

**Comment by NaveenJayaram94** [comment]
I also faced same issue,

Remove 
`lineHeight: 18`
from <Label> component , if you have given.
it worked for me

**Comment by SupriyaKalghatgi** [comment]
@NaveenJayaram94 You mean, modifying in ejected theme and not updating NativeBase version?

**Comment by NaveenJayaram94** [comment]
@SupriyaKalghatgi 
Native base theme works fine, doesn't need modification,
remove it from custom styles you have given to Lable or Item Component, if any.

**Comment by SupriyaKalghatgi** [comment]
@NaveenJayaram94 Yes, no need of embedding inline styles here
