### ISSUE TITLE
Problem when I'm trying to customize 

### ISSUE THREAD

**Issue by hjJunior** [GeekyAnts/NativeBase#1534]
## react-native, react and native-base version
react-native: 0.44.0
native-base: 2.1.5
## Expected behaviour
Change the variable values to change the colors of header, statusbar, and some components
## Actual behaviour
I'm Getting this error: 
`Can't find variable: Symbol`
## Steps to reproduce (code snippet or screenshot)
So, I tried to follow the docs, so... I started add the imports
`import { StyleProvider  } from 'react-base'`
`import getTheme from '../../native-base-theme/components';`
`import material from '../../native-base-theme/variables/material';`

I'm using component by class, so I have added StyleProvider Tag

    <StyleProvider style={getTheme(material)}>
        <Drawer
        ref={(ref) => { this.drawer = ref; }}
        content={<SideBar closeDrawer={this.closeDrawer} />}
        panOpenMask={.25}
        onClose={() => this.closeDrawer()} >            
            <Container>
             ...
            </Container>
    </StyleProvider>

## Screenshot of emulator/device
![screenshot_1516659445](https://user-images.githubusercontent.com/10780132/35242379-8d24be38-ffa0-11e7-8609-a7ba53b81bf7.png)

## Is the bug present in both ios and android or in any one of them?
Sorry, I can't say because, I'm working in Windows :( 
## Any other additional info which would help us debug the issue quicker.

I just have change the file `native-base-theme/variables/commonColor.js`

`brandPrimary: "#2874F0",` to:  `brandPrimary: "#ba2151",`

**Comment by akhil-geekyants** [comment]
@hjJunior can you try importing StyleProvider from native-base

change
```
import { StyleProvider } from 'react-base'
```
to 
```
import { StyleProvider } from 'native-base'
```

**Comment by hjJunior** [comment]
Thanks :) @akhil-geekyants, this works fine!!
