### ISSUE TITLE
Incorrect position of Icon with Floating label

### ISSUE THREAD

**Issue by ViktorAksionov** [GeekyAnts/NativeBase#1535]
## react-native, react and native-base version
"native-base": "^2.3.7",
"react": "16.2.0",
 "react-native": "0.52.0",
## Expected behavior
Icon should be on right side
## Actual behavior
Position of Icon always is on left side
## Steps to reproduce (code snippet or screenshot)
```
<Item floatingLabel error={error && touched}>
  <Label style={{top}}>{labelText}</Label>
  <Input
          ref={c => (this.textInput = c)}
          secureTextEntry={input.name === "password" ? true : false}
          {...input}
  />
  <Icon name='close-circle' />
</Item>
```
## Screenshot of emulator/device
![image](https://user-images.githubusercontent.com/2520890/35272621-cc735758-ffea-11e7-84ce-002516a16ea3.png)

## Is the bug present in both ios and android or in any one of them?
checked only Android

**Comment by SupriyaKalghatgi** [comment]
#1102

**Comment by navibrar** [comment]
<Item floatingLabel style={{ flexDirection: 'row-reverse' }}>
                            <Label>Password</Label>
                            <Input/>
                            <Icon name="close-circle" />
                        </Item>
