### ISSUE TITLE
performance issue

### ISSUE THREAD

**Issue by slicejunk** [GeekyAnts/NativeBase#1536]
in `customMerge` from `native-base-shoutem-theme`
there are some iteration on the properties of both objects, I guess this can be be optimized by removing the inner iteration
```
export default function customMerge(obj1, obj2) {
  const objToReturn = {};
  let property1, property2;

  if (!obj1) {
    return obj2;
  } else if (!obj2) {
    return obj1;
  }

  for (property1 in obj1) {
    if (obj2[property1] != null) {
      if (
        typeof obj1[property1] !== 'object' ||
        typeof obj2[property1] !== 'object' ||
        !obj2[property1] ||
        !obj1[property1]
      ) {
        objToReturn[property1] = obj2[property1];
      } else {
        objToReturn[property1] = customMerge(obj1[property1], obj2[property1]);
      }
    } else {
      objToReturn[property1] = obj1[property1];
    }
  }
  for (property2 in obj2) {
    if (obj1[property2] != null) {
      // already merged !
    } else {
      objToReturn[property2] = obj2[property2];
    }
  }
  return objToReturn;
}
```
in the original function, the values from `obj2` where dropped if it does not exist in `obj1`, is that wanted?

moreover it could be helpful to have some explanations about the existence of this library, why not use `shoutem-theme`

**Comment by SupriyaKalghatgi** [comment]
@slicejunk Would you go ahead initiating PR for this?

**Comment by slicejunk** [comment]
@SupriyaKalghatgi The choice of a custom version of `southem-theme` should be explained before going into this task.
What are the differences ?
and why the original version can not be used instead?

**Comment by slicejunk** [comment]
please review this PR @SupriyaKalghatgi
