### ISSUE TITLE
Text height auto not work

### ISSUE THREAD

**Issue by emirdeliz** [GeekyAnts/NativeBase#154]
Hello, peoples!

I have a problem with text height. When use:

```
import { Icon, View, Text } from 'native-base'

<View style={{flex: 1, flexDirection: 'row', alignItems: 'center'}}>
    <View style={{backgroundColor: 'powderblue'}}>
        <Icon style={ { fontSize: 12 } } name="ios-timer" />
    </View>
    <View style={{backgroundColor: 'skyblue', padding: 0}}>
        <Text style={ { fontSize: 10 }}>{ item.description }</Text>
    </View>
</View>
```
The align vertical not works.

![captura de tela 2016-08-31 as 11 21 01](https://cloud.githubusercontent.com/assets/6270495/18132412/1995d5d4-6f6d-11e6-9a07-11636484f67c.png)

I found the problem in code of Text.js

```
var type = {
	color: this.getContextForegroundColor(),
	fontSize: this.getTheme().fontSizeBase,
	lineHeight: this.getTheme().lineHeight, /* This is a problem */
	fontFamily: this.getTheme().fontFamily
}

The lineHeight fixed the height of Text

```
Existe other alternative for fix my problem?

**Comment by sankhadeeproy007** [comment]
Whenever you change fontSize in react-native, you have to adjust the lineHeight accordingly as well.

**Comment by emirdeliz** [comment]
When I use the react -native text does not exist spacing as shown in picture

**Comment by sankhadeeproy007** [comment]
That is because the lineHeight has been explicitly mentioned in native-base. So you have to set if you change the fontSize.

**Comment by emirdeliz** [comment]
Look my code now

```
<ListItem iconLeft>
    <View>
        <View style={{
            flex: 5,
            flexDirection: 'row'
        }}>
            <Icon style={{
                fontSize: 13,
                backgroundColor: '#F03'
            }} name={ 'logo-usd' } />
            <Text style={{
                fontSize: 13,
                backgroundColor: '#FF1'
            }}>Test</Text>
        </View>
    </View>
</ListItem>
```

![captura de tela 2016-09-01 as 09 13 12](https://cloud.githubusercontent.com/assets/6270495/18166937/6134cd52-7024-11e6-9488-53b01af08a64.png)

Same with fontSize not working

**Comment by sankhadeeproy007** [comment]
Please use lineHeight to adjust to your liking.

**Comment by emirdeliz** [comment]
But when content is dynamic and higher than lineHeight defined?

**Comment by emirdeliz** [comment]
This works fine!
```
<ListItem iconLeft>
   <View>
      <View style={{
          flex: 5,
          flexDirection: 'row',
          alignItems: 'center'
       }}>
            <Icon style={{
                 fontSize: 13,
                 backgroundColor: '#F03',
                 lineHeight: 15
            }} name={ 'logo-usd' } />
           <View>
              <Text style={{
                 fontSize: 13,
                 backgroundColor: '#FF1',
                 lineHeight: 15
                 }}>{ item.description }
             </Text>
         </View>
      </View>
   </View>
</ListItem>
```

![captura de tela 2016-09-01 as 09 30 12](https://cloud.githubusercontent.com/assets/6270495/18167388/b5ac376a-7026-11e6-934d-9f0db0560c68.png)

With large content

![captura de tela 2016-09-01 as 09 30 58](https://cloud.githubusercontent.com/assets/6270495/18167408/d25bf1a2-7026-11e6-86e2-96279f6ef500.png)

Thanks @sankhadeeproy007

**Comment by rahulsapkal23** [comment]
try this
{
    fontSize: 35,
    lineHeight: 35 * 0.75,
    paddingTop: 35 - (35 * 0.75), // <-- Add this
  },

**Comment by lekeCoder** [comment]
@rahulsapkal23 your last code only increase line spacing not the fontsize. What esle can l do? I need to increase text size
