### ISSUE TITLE
style depends on component order

### ISSUE THREAD

**Issue by slicejunk** [GeekyAnts/NativeBase#1540]
RN version 0.52, NB version 2.3.7

the size of the text is wrong
the second button follows the first button style, this is related to a bug in `getOrSetStylesInCache` from `native-base-shoutem-theme`

```js
      <React.Fragment>
          <Button icon={<MapIcon />} label="button large" onPress={noop} large />
          <Button icon={<MapIcon />} label="button small" onPress={noop} small />
      </React.Fragment>
```
![image](https://user-images.githubusercontent.com/5887100/35393787-48cce31c-01e6-11e8-9ccc-5f5fec31194b.png)

```js
      <React.Fragment>
          <Button icon={<MapIcon />} label="button small" onPress={noop} small />
          <Button icon={<MapIcon />} label="button large" onPress={noop} large />
      </React.Fragment>
```
![image](https://user-images.githubusercontent.com/5887100/35393757-3336f7fe-01e6-11e8-8371-50f73a98cd9b.png)

**Comment by akhil-geekyants** [comment]
@slicejunk can you try this

```
<Button iconLeft large style={{ margin: 10, backgroundColor: '#324d7a' }}>
  <Icon name='map' />
  <Text> Large</Text>
</Button>
<Button iconLeft small style={{ margin: 10, backgroundColor: '#324d7a' }}>
  <Icon name='map' style={{ fontSize: 16 }} />
  <Text> Small</Text>
</Button>
```

Gif

![button](https://user-images.githubusercontent.com/27768184/35498765-a43a3e36-04f5-11e8-89b3-7c9e93c0466f.gif)

**Comment by SupriyaKalghatgi** [comment]
```
<Content padder>
  <Button large style={{ marginBottom: 10 }}>
    <Icon name="home" />
    <Text>Large</Text>
  </Button>
  <Button style={{ marginBottom: 10 }}>
    <Icon name="home" />
    <Text>Medium</Text>
  </Button>
  <Button small>
    <Icon name="home" />
    <Text>Small</Text>
  </Button>
</Content>
```

![simulator screen shot - iphone 7 - 2018-01-29 at 16 57 10](https://user-images.githubusercontent.com/13464885/35508213-85969c16-0515-11e8-866c-596d36384493.png)

Text size is appropriate to button size

**Comment by slicejunk** [comment]
ok, I got it, the Buttons need to be embed in another Native base Component to work

```import {View} from 'react-native';```


```
<View>
  <Button large style={{ marginBottom: 10 }}>
    <Icon name="home" />
    <Text>Large</Text>
  </Button>
  <Button style={{ marginBottom: 10 }}>
    <Icon name="home" />
    <Text>Medium</Text>
  </Button>
  <Button small>
    <Icon name="home" />
    <Text>Small</Text>
  </Button>
</View>
```


=> wrong style

but


```import {View} from 'native-base';```

```
<View>
  <Button large style={{ marginBottom: 10 }}>
    <Icon name="home" />
    <Text>Large</Text>
  </Button>
  <Button style={{ marginBottom: 10 }}>
    <Icon name="home" />
    <Text>Medium</Text>
  </Button>
  <Button small>
    <Icon name="home" />
    <Text>Small</Text>
  </Button>
</View>
```

=> correct style

thanks for answering

**Comment by SupriyaKalghatgi** [comment]
I have opened this issue on the docs repo here: [#64](https://github.com/GeekyAnts/native-base-docs/issues/64)
Since we split the docs and the source into separate repos.
