### ISSUE TITLE
Using theme variables from getTheme and connectStyle

### ISSUE THREAD

**Issue by ekimlinger** [GeekyAnts/NativeBase#1543]
Question: Is it possble to have a component use the variables that are injected into:
```
<StyleProvider style={getTheme(material)}>
    <App>
</StyleProvider>
```

As far as I can tell, `connectStyle` only allows you to add variables to your theme, it does not allow access to existing ones.

For example if my app looks like so:

```
<StyleProvider style={getTheme(material)}>
    <App>
</StyleProvider>
```
I want to be able to pull out the `brandPrimary` variable from our material injected theme like so:

```
<App>
    <Text style={this.props.style.brandPrimary>
         Some Text
    </Text>
</App>

export const connectStyle('NativeBase.Theme', {})(App);
```

Anyone know if this is possible?

**Comment by dawnmist** [comment]
I am starting to suspect that the only way to do it is to stash a copy that you can access somewhere (for example in a Redux store) and then pull that copy out separately to anything in native-base.

I'd really rather that there was a way to access and pass down the variables for reuse when using connectStyle. It's not really a problem if you only use a single theme (just import the variable file wherever you need it), but if you want to support switching themes I think you'll need to save the selected theme's variables somewhere for reuse.

**Comment by benzman81** [comment]
Is there a solution to this? We followed the guide for a custom component, but now we want those styles to be overwritten by a variables.js file. Any hint or is this just not possible?

**Comment by cristianocca** [comment]
Also struggling with this. Connect should make the variables variable available. It would be a good idea to grab some ideas from react material-ui (web) library, they made an outstanding way to customize your theme while providing features to easily switch them.
