### ISSUE TITLE
Add TypeScript support for Picker props placeholderStyle

### ISSUE THREAD

**Issue by Jeowulf** [GeekyAnts/NativeBase#1544]
## react-native, react and native-base version
react native version 0.52.1, native-base Version 2.3.7
## Expected behaviour
Picker placeholderStyle prop supported by TypeScript
## Actual behaviour
Missing Type definition
## Steps to reproduce (code snippet or screenshot)
In a Project running on TS, give the Picker a prop of placeholderStyle
## Screenshot of emulator/device
![screen shot 2018-01-27 at 5 46 47 pm](https://user-images.githubusercontent.com/11777142/35477098-3019f260-038a-11e8-82cb-b8133864be4c.png)
## Is the bug present in both ios and android or in any one of them?
Only tested on ios
## Any other additional info which would help us debug the issue quicker.
Nothing more specific

**Comment by SupriyaKalghatgi** [comment]
Fixed with [2.3.8](https://github.com/GeekyAnts/NativeBase/releases/tag/v2.3.8)
