### ISSUE TITLE
Sidebar vertical swipe up

### ISSUE THREAD

**Issue by vvavepacket** [GeekyAnts/NativeBase#1545]
Right now, sidebar can be implemented sideways. We can open a sidebar by swiping from left to right like below:

[Sidebar horizontal](https://docs.nativebase.io/docs/assets/ios/components/drawer.png)

QUESTION: Is it possible to use sidebar vertically? Like facebook extensions where we can pull it upwards? I can not find vertical option to both drawer and sidebar component of Native Base.

[sidebar vertical](https://i.imgur.com/KMo6QUx.png)

**Comment by akhil-geekyants** [comment]
@vvavepacket just set `<Drawer/>` prop `side` to `bottom` 

![sidebar](https://user-images.githubusercontent.com/27768184/35505385-ffa42190-050b-11e8-8068-15bae6898816.gif)
