### ISSUE TITLE
Using multiline Input inside floating label Item is broken in iOS

### ISSUE THREAD

**Issue by minaskamel** [GeekyAnts/NativeBase#1551]
"react": "16.0.0-alpha.12"
"react-native": "0.48.1"
"native-base": "2.3.6"

## Expected behaviour
I'm trying to use an Input inside a floating label Item, and this Input should be for "description" so I need many lines for this input.
Here's the code:
`<Item floatingLabel>
                <Label>Description</Label>
                <Input
                     multiline
                     numberOfLines={4} //for Android
                />
 </Item>`

## Actual behaviour
What's happening is: the "Label" is shown below the Item separator line, instead of the normal NativeBase behavior (the label should be above). And when you start type the test is written above the separator line. 

## Screenshot of emulator/device
Screenshots from iOS:
<img width="340" alt="screen shot 2018-01-30 at 5 02 59 pm" src="https://user-images.githubusercontent.com/8933042/35550723-d8bf64b6-05df-11e8-9f3c-b0d32729b001.png">

<img width="335" alt="screen shot 2018-01-30 at 5 04 11 pm" src="https://user-images.githubusercontent.com/8933042/35550732-e5bddac6-05df-11e8-8293-297491b3802d.png">

## Is the bug present in both ios and android or in any one of them?
iOS: not working properly.
Android: It's better in Android, however if i set the numberOfLines to 4 (as in the code) there are lots of white space appearing there. 

<img width="367" alt="screen shot 2018-01-30 at 5 07 46 pm" src="https://user-images.githubusercontent.com/8933042/35550801-2c9c6278-05e0-11e8-96d7-7bd9f0d4d320.png">

<img width="356" alt="screen shot 2018-01-30 at 5 08 05 pm" src="https://user-images.githubusercontent.com/8933042/35550802-2e6fa66e-05e0-11e8-91ca-2221f760c6bd.png">

**Comment by minaskamel** [comment]
@akhil-geekyants will the fix be included in a soon release? and is there any workaround?
Thanks.

**Comment by akhil-geekyants** [comment]
@minaskamel can you try this
```
<Item floatingLabel style={{ height: 55 }}>
  <Label>Description</Label>
  <Input multiline numberOfLines={4} style={{ height: 45 }} />
</Item>
```
Gif

![multiline](https://user-images.githubusercontent.com/27768184/35906991-9203aabc-0c12-11e8-94f8-e7c8c87fd688.gif)

**Comment by minaskamel** [comment]
Thanks @akhil-geekyants , that was helpful.
The tricky part it putting the height.

**Comment by akhil-geekyants** [comment]
Closed this issue as only floating label with single line input is supported.

**Comment by NiveshShastri** [comment]
I am facing the same issue, is there any workaround for the same?
