### ISSUE TITLE
Android ripple is not triggered by child icon of Button

### ISSUE THREAD

**Issue by Culzean** [GeekyAnts/NativeBase#1552]
"native-base": "^2.3.5",
react-native-cli: 2.0.1,
react-native: 0.50.3

```
<Button borderRadius={20} >
            <Icon
              name="menu"
              style={styles.headerButton}
              onPress={() => this.toggleDrawer()}
            />
</Button>
```

Expected behaviour is for the ripple effect to appear when I click on the icon within the button, but it does not. It does appear if I click on the button but outside of the icon.

So far I have only tested this on Android so I don't know how this will behave on iOS.

**Comment by SupriyaKalghatgi** [comment]
@Culzean `onPress` should be for `Button`
