### ISSUE TITLE
In Multiple Swipable List renderRight/LeftHiddenRow rowId and secId type is string instead of integer

### ISSUE THREAD

**Issue by liamse** [GeekyAnts/NativeBase#1558]
This is not exactly an issue, but I figure out in Multiple Swipable Lists, the type of rowId and secId that pass in renderRight or renderLeftHiddenRow as parameters are string instead of Integer. As they are Id I consider they are integer but they return string.

```javascript
renderRightHiddenRow={(marker, secId, rowId, rowMap) => {
    console.log(typeof(rowId)); //"string" 
    console.log(typeof(secId)); //"string"
}
```

**Comment by akhil-geekyants** [comment]
@liamse the value of `secId` is string. This is as designed
