### ISSUE TITLE
input ref on dynamic list

### ISSUE THREAD

**Issue by texas697** [GeekyAnts/NativeBase#1559]
Hi! Thanks for trying out NativeBase!
Due to the overwhelming requests and issues/questions we ask you to add the following details with your issue.

Please check the existing open/closed issues for a possible duplicate before creating a new issue :)

Also **DO** fill out the below form to give us a better idea about your environment and help us debug it quicker. Issues without the required details will mostly be unattended to.

## react-native, react and native-base version
0.52.0
^2.3.7
## Expected behaviour
select next input on onSubmitEditing
## Actual behaviour
this.refs is null
## Is the bug present in both ios and android or in any one of them?
both
## Any other additional info which would help us debug the issue quicker.

I am trying to get the ref of the inputs but this.refs is null. I am wondering is it because I am using a dynamic list to populate the inputs? 

```
`  _focusNext (nextField) {
    this.refs[nextField]._root.focus()
  }
`
```

```
`{model.map((item, i) => (
                <CardItem key={i}>
                  <Item floatingLabel last>
                    <Label style={mainStyles.labelHeight}>{item.get('label')}</Label>
                    <Input
                      ref={item.get('id')}
                      value={item.get('value')}
                      keyboardType={item.get('keyboardType')}
                      returnKeyType={item.get('returnKeyType')}
                      onSubmitEditing={() => this._focusNext(item.get('nextId'))}
                      onChangeText={val => this._onInputChange(val, i)}
                      style={styles.input} />
                  </Item>
                </CardItem>
              ))}`

```

**Comment by SupriyaKalghatgi** [comment]
#522

**Comment by ZeroCool00** [comment]
@texas697  is this working for you..  i tried today.. its not working.. it throws error when refrencing dynamic input list. i use **getRef** props..  its not working in android, not sure about ios.

**Comment by ZeroCool00** [comment]
@SupriyaKalghatgi  any example for dynamic ref? bcz its not working in **2.7.2**
