### ISSUE TITLE
Picker does not work

### ISSUE THREAD

**Issue by henryw4k** [GeekyAnts/NativeBase#156]
![screen shot 2016-09-01 at 12 24 49 pm](https://cloud.githubusercontent.com/assets/3743891/18181247/34812740-703f-11e6-9bfb-cfcdd521c9cd.png)

I copied your example exactly from the docs. Every time I try to use picker, it throws this error: 
`Cannot read property 'props' of undefined`

**Comment by henryw4k** [comment]
`react-native@0.31.0`
` native-base@0.5.5`

**Comment by SupriyaKalghatgi** [comment]
@henryw4k I tried the same example
And it works fine for me
```
 "native-base": "^0.5.7",
    "react": "15.3.1",
    "react-native": "0.32.0"
```
![screen shot 2016-09-06 at 11 43 27 am](https://cloud.githubusercontent.com/assets/13464885/18263381/367b5dea-7427-11e6-8776-a43ef29cd54d.png)

**Comment by robputer** [comment]
I'm experiencing the same issue.

react-native@0.32.0
native-base@0.5.6

**Comment by SupriyaKalghatgi** [comment]
@henryw4k @robputer Can you try updating NativeBase to the latest and simulate?

**Comment by gor181** [comment]
Usually I would get this error when I would set `selectedValue` to one which is not included in the provided items.

**Comment by ptah23** [comment]
I'm also getting it when I set selectedValue to one not in the provided items. This is going to be a problem for dynamically created items

**Comment by gor181** [comment]
I think this should have been fixed in most recent release? 

https://github.com/GeekyAnts/NativeBase/commit/b03f0e52fa417c586b3d6cd65e2caf7d8dbe0299#diff-96cd24568168ce09474e9802b4401a30R27

This is where it was throwing now it shouldn't be the case.
However it would be a good idea to have a `defaultValue` when there are no selected items something as `Select` or similar..

**Comment by sankhadeeproy007** [comment]
Updated with 0.5.9

**Comment by jeremypeters** [comment]
I was experiencing the same issue so I updated to the latest version - the picker now appears, but it takes a second or two and I get the following console warning:

`
Warning: Call stack size exceeded when merging props, falling back to shallow merge.`

**Comment by mostafiz93** [comment]
Using Picker.Item directly can solve the issue. Don't declare `const Item = Picker.Item;​`, use this:
`<Picker.Item label="Wallet" value="key0" />`

**Comment by tarun29061990** [comment]
Facing same issue:
cannot read props of null

```
<Picker
 note
 mode="dropdown" 
 selectedValue={projectDetails.stage.display_name}
onValueChange={this.onValueChange.bind(this)}
style={{ width: '100%', color : '#5d96ff' }}
>
    {stages.map((value, key)=>{
        <Picker.Item label={value.display_name} value={value} />
    })}
</Picker>
```

"native-base": "2.8.1"
"react-native": "0.57.1"

**Comment by alexiadorneles** [comment]
@tarun29061990 So am I, found any solution?

**Comment by tarun29061990** [comment]
@alexiadorneles Do like this
```
let stages = that.stages.map((stage, id)=>{
    return <Picker.Item key={id} value={stage} label={stage.display_name} />
});
```
```
<Picker
    note
    mode="dropdown" 
    selectedValue={this.state.selectedStage}
    onValueChange={(value, index)=>{this.setState({selectedStage:value})}}
    style={{ width: '100%', color : '#5d96ff' }}
>
    {stages}
</Picker>
```

**Comment by junaidq322** [comment]
This is my code it does not seem to be working, help needed.
<Item stackedLabel>
        <Picker
          mode="dropdown"
          iosIcon={<Icon color={"#007aff"} name="arrow-down" />}
          style={{ width: undefined }}
          placeholder="Select your Category"
          selectedValue={pickerValue}
          placeholderStyle={{ color: "#007aff" }}
          placeholderIconColor="#007aff"
          onValueChange={(e) => [setPickerValue(e), setCategory(e)]}
        >
          {categories.map((c) => {
            return <Picker.Item key={c.id} label={c.name} value={c.id} />;
          })}
        </Picker>
      </Item>
