### ISSUE TITLE
Menu right header

### ISSUE THREAD

**Issue by Angelk90** [GeekyAnts/NativeBase#1561]
Hi, how can I get a menu like that.
![](https://i.imgur.com/4gqIyTk.gif)

**Comment by SupriyaKalghatgi** [comment]
@Angelk90 Thats Picker
You can check NativeBase Picker from docs https://docs.nativebase.io/Components.html#picker-def-headref

**Comment by Angelk90** [comment]
@SupriyaKalghatgi : 
It does not seem like a picker.
They seem to me two very different things.
! [] (Https://raw.githubusercontent.com/GeekyAnts/NativeBase-KitchenSink/v2.2.0/screenshots/android/picker.gif)

**Comment by oriharel** [comment]
Agree with @Angelk90 . This is not the same.
