### ISSUE TITLE
I inserted a Tabs with three Tab inside a Tabs with three Tab and does not open on Android

### ISSUE THREAD

**Issue by MatheusLima7** [GeekyAnts/NativeBase#1564]
**## react-native**

**## native-base**  => project clone NativeBase-KitchenSink

**## Expected behavior** => no bug = open Tab

**## Actual Behavior** => bug = Tab does not open on Android

**## Steps to Reproduce**

I inserted a Tabs with three Tab inside a Tabs with three Tab

**## Screenshot of the emulator / device**

**## Is the bug ios and Android or any of them?**

ANDROID

## Any additional information that will help us solve the problem more quickly.
In Emulator works normally. The problem occurs on cellphone

`          <Tabs onChangeTab={(ref) => TriggerNavigationTab(ref)}  page={this.state.firstTabValue} ref={(tabView) => { this.tabView = tabView }}  style={ style.tab }  locked={true}>
            <Tab heading="DIÁRIA" activeTabStyle={ style.tab } tabStyle={ style.tab } textStyle={ style.textStyle } activeTextStyle={ style.textStyle }>
              { (this.state.loading) ? (
                <Spinner visible={true} textContent={"Carregando..."} textStyle={{color: '#FFF'}} />
              ) : ( 
                  <View>
                    { this.buscaConteudoDiaria() }
                  </View>
              )}        
            </Tab>
            
            <Tab heading="PENDENTES" activeTabStyle={ style.tab } tabStyle={ style.tab } textStyle={ style.textStyle } activeTextStyle={ style.textStyle }>
              { this.state.loading ? (
                <Spinner visible={true} textContent={"Carregando..."} textStyle={{color: '#FFF'}} />
              ) : ( 
                <View>
                  { (this.state.results[0] == undefined ) ? (
                    <View style={style.contatos}>
                        <Text style={style.texto}>
                          Você não possui contatos pendentes
                        </Text>
                    </View>
                    ) : null }
                  <View>
                    {
                    this.state.results.map((lista, i) => (
                      <ListItem key={i} onPress={() => this.props.navigation.navigate('VerCampanhaCliente', {clienteId: lista.client.id, advertisingId: lista.current.advertising.id})}>
                        <Row>
                          <Col style={{ width: '20%' }}>
                            <Button style={style.icon}>
                              <Icon active name="person" />
                            </Button>
                          </Col>
                          <Col style={{ width: '80%' }}>
                            <Text style={style.nome}>{lista.client.name}</Text>
                            <Text style={style.texto}>{lista.current.advertising.name} {lista.current.advertising.benefit}</Text>
                            <Text style={style.texto}> { lista.current.completed ? 'TENTATIVA DE CONTATO COM SUCESSO' :  '' } </Text>
                            <Text style={style.texto}> { lista.current.optOut ? 'CLIENTE NÃO QUER MAIS RECEBER CONTATO' :  ''  } </Text>
                          </Col>
                        </Row>
                      </ListItem>
                    ))
                    }
                  </View>
                </View>  
              ) } 
            </Tab>

            <Tab heading="COMPLETA" activeTabStyle={ style.tab } tabStyle={ style.tab } textStyle={ style.textStyle } activeTextStyle={ style.textStyle }>
              { this.state.loading ? (
                <Spinner visible={true} textContent={"Carregando..."} textStyle={{color: '#FFF'}} />
              ) : ( 
                  <View>
                    <View>
                        <View style={style.select}>
                          <Text style={style.tituloRanking}>Filtre seus clientes por:</Text>
                          <View>
                            <RadioForm
                                animation={true}
                                buttonColor={'#ff3d1c'}
                                labelColor={'#000000'}
                                onPress={ this.alteraOpcoes }
                                radio_props={radio_props}
                                initial={0}
                                formHorizontal={true}
                              />
                          </View>
                        </View>
                        <Picker
                          style={{ width: 200, alignSelf: 'center', flexDirection: 'column' }}
                          headerStyle={{ backgroundColor: "#b95dd3" }}
                          headerBackButtonTextStyle={{ color: "#fff" }}
                          headerTitleStyle={{ color: "#fff" }}
                          mode="dropdown"
                          selectedValue={this.state.opcaoSelecionada}
                          onValueChange={this.onValueChange.bind(this)}
                        >
                        {
                          this.state.listaOpcoes.map((item, i) => (
                          <Item key={i} label={item.name} value={item.id} />
                            ))
                          }
                        </Picker>
                    </View>
                    {this.buscaConteudoCompleta()}
                  </View>  
              ) }   
            </Tab>
          </Tabs>`

**Comment by SupriyaKalghatgi** [comment]
@MatheusLima7 
> I inserted a Tabs with three Tab inside a Tabs with three Tab

I would like to see screenshot for this

**Comment by MatheusLima7** [comment]
It only occurs without a cell phone.

2018-02-02 10:18 GMT-02:00 Supriya Kalghatgi <notifications@github.com>:

**Comment by SupriyaKalghatgi** [comment]
@MatheusLima7 I am not clear with your response. Can you please elaborate?

**Comment by MatheusLima7** [comment]
It was code error. Disregard.

**Comment by SupriyaKalghatgi** [comment]
@MatheusLima7 Sorry to say, but am not clear with any of your comments

**Comment by SupriyaKalghatgi** [comment]
Closing this issue due to imprecise information
