### ISSUE TITLE
Button component's style prop doesn't accept color property

### ISSUE THREAD

**Issue by metagrover** [GeekyAnts/NativeBase#1568]
Thank you for the amazing work at NativeBase!

## react-native, react and native-base version
react-native - 0.49.0
native-base - 2.3.7

## Expected behaviour
`<Button>` component's `style` prop should accept `color` as a valid key. (I have a use-case where I'm trying to emulate minimal and necessary theme support with properties like primaryColor, color, without ejecting the theme from native-base)

## Actual behaviour
It seems that `<Button>` component's prop are passed to `View` in its implementation, where `color` is not a valid key in the `style` prop.

## Steps to reproduce (code snippet or screenshot)
```
<Button
    style={{
        backgroundColor: '#424242',
        color: 'yellow',
    }}
>
    Click Me
</Button>
```

## Is the bug present in both ios and android or in any one of them?
Both

**Comment by SupriyaKalghatgi** [comment]
@metagrover We are glad to know that you use NativeBase with your project

About Button, Docs says
![image](https://user-images.githubusercontent.com/13464885/35794014-f1d426f0-0a79-11e8-9493-12fee430ee18.png)

**Comment by metagrover** [comment]
oh yes, my bad! I should be changing the `Text`'s color prop. Thanks for the quick revert!
