### ISSUE TITLE
TouchableOpacity not working with Card inside

### ISSUE THREAD

**Issue by gregogalante** [GeekyAnts/NativeBase#157]
In the previous version i have a TouchableOpacity with a Card inside and it works good.

After update it stop to work and press is not working. 

If i use a text and not a card it work.

code: 

`
<TouchableOpacity key={key} onPress={() => this.goToProductRouter(product)}>
<Card style={productStyle} theme={theme}>
<CardItem style={productStyle}>
                        <Thumbnail source={{uri: `${url}${product.main_image_url}`}} />
                        <Text style={styles.categoryProductTitle}>{product.name}</Text>
                        <Text style={styles.categoryProductNote} note>{product.ingredients}</Text>
                        {productPrice}
                      </CardItem>
                    </Card>
</TouchableOpacity>
`

**Comment by sankhadeeproy007** [comment]
Try using `button` prop with CardItem.
