### ISSUE TITLE
Icons in textbox do not align properly

### ISSUE THREAD

**Issue by dphaener** [GeekyAnts/NativeBase#1572]
Hi! Thanks for trying out NativeBase!
Due to the overwhelming requests and issues/questions we ask you to add the following details with your issue.

Please check the existing open/closed issues for a possible duplicate before creating a new issue :)

Also **DO** fill out the below form to give us a better idea about your environment and help us debug it quicker. Issues without the required details will mostly be unattended to.

## react-native, react and native-base version
react-native@0.48.4
native-base@2.3.8

## Expected behaviour
Adding an icon *after* the input inside of an item should make the icon align on the right side of the input.

## Actual behaviour
The icon is aligned on the left side, regardless of the order it is rendered.

## Steps to reproduce (code snippet or screenshot)
```
<View style={styles.container}>
     <Item floatingLabel error={error && touched} style={styles.item}>
       <Label>{placeholder || label || capitalize(name)}</Label>
       <Input
          name={name}
          onChangeText={text => onChange(name, text)}
          value={value}
          keyboardType={keyboardType}
          secureTextEntry={secureTextEntry}
          {...rest}
       />
      {error && touched && <Icon active name="close-circle" />}
   </Item>
   {error && touched && <Text style={styles.errorMessage}>{error}</Text>}
</View>
```

## Screenshot of emulator/device
![simulator screen shot - iphone x - 2018-02-06 at 16 29 55](https://user-images.githubusercontent.com/5187971/35891822-03b9f2a0-0b5b-11e8-950f-fb9d4efd04b3.png)

## Is the bug present in both ios and android or in any one of them?
Confirmed in iOS, have not checked Android.

## Any other additional info which would help us debug the issue quicker.
I also attempted rendering the icon without the conditionals and observed the same behavior.

**Comment by akhil-geekyants** [comment]
Related to issue #1102 
@dphaener see this comment https://github.com/GeekyAnts/NativeBase/issues/1102#issuecomment-342271862

**Comment by inanbayram** [comment]
@dphaener  have you found a solution for that? The solution from @akhil-geekyants not working :/

**Comment by dphaener** [comment]
@inanbayram that solution worked perfectly for me. Sorry!
