### ISSUE TITLE
Transparent header

### ISSUE THREAD

**Issue by bsiddiqui** [GeekyAnts/NativeBase#158]
I have a background image in a view so I'd like the header to be transparent. Setting the backgroundColor to transparent however gets an error:
"RCTView has a shadow set but cannot calculate shadow efficiently."

Is there a better way to make the header transparent?

**Comment by bsiddiqui** [comment]
For anyone trying to figure this out I was able to add `style={{ shadowOpacity: 0 }}` to get rid of the shadow and error.

**Comment by ydv0121** [comment]
set <Header style={{elevation:0}}>..
its works
thank you @ChetanGodiya4

**Comment by SupriyaKalghatgi** [comment]
The `noShadow` prop of Header removes shadow from iOS Header and elevation from Android Header.

https://docs.nativebase.io/Components.html#header-no-shadow-headref
