### ISSUE TITLE
[Button] TouchableNativeFeedback should also be used when Platform.Version === 21  && Platform.OS !== 'ios'?

### ISSUE THREAD

**Issue by ming436534** [GeekyAnts/NativeBase#1580]
## react-native, react and native-base version
Version:
react-native: 0.52.0
react: 16.2.0
native-base: 2.3.8
Android Version: API level 21
## Expected behaviour
Button has ripple
## Actual behaviour
Button has no ripple on Press

According to android doc, ripple animation was added in API level 21, is there any reason native base only support use TouchableNativeFeedback when android API level > 21?

**Comment by SupriyaKalghatgi** [comment]
@ming436534 Yes! NativeBase supports TouchableNativeFeedback with Android API > 21

**Comment by ming436534** [comment]
I guess NativeBase should also support TouchableNativeFeedback with Android API = 21?

**Comment by SupriyaKalghatgi** [comment]
@ming436534 yes, that does
check the commit file completely

**Comment by SupriyaKalghatgi** [comment]
Fixed with [2.3.9](https://github.com/GeekyAnts/NativeBase/releases/tag/v2.3.9)
