### ISSUE TITLE
Adding BorderWidth to Button cuts off icon child

### ISSUE THREAD

**Issue by SrdjanCosicPrica** [GeekyAnts/NativeBase#1584]
## react-native, react and native-base version
react: 16.2.0
react-native : 0.52.0
native-base: 2.3.7
## Expected behaviour
![simulator screen shot - iphone 5s - 2018-02-13 at 10 45 12](https://user-images.githubusercontent.com/15933115/36143320-0f70f602-10ab-11e8-989f-4c0aae520d3d.png)

But with an orange border around the white. (See expected behaviour)
## Actual behaviour
![simulator screen shot - iphone 5s - 2018-02-13 at 10 34 35](https://user-images.githubusercontent.com/15933115/36143065-560d4c56-10aa-11e8-9054-51ccc39c4bc7.png)

## Steps to reproduce (code snippet or screenshot)
```
<Button
    style={{
            backgroundColor: 'white',
            alignSelf: 'center',
            width: 50,
            height: 50,
            borderRadius: 50,
            borderWidth: 3,
            borderColor: 'orange',
            justifyContent: 'center',
            alignItems: 'center',
        }}
>
    <Icon ios='ios-play' android='md-play'
          style={{ color: 'orange', fontSize: 36 }} />
</Button>
```
## Is the bug present in both ios and android or in any one of them?
Only Tested in IOS.
## Any other additional info which would help us debug the issue quicker.
Removing the BorderWidth will show the expected behaviour.

**EDIT**
Removing BorderRadius does not have any effect. So the fact that the button is a circle is not a problem.

**Comment by SupriyaKalghatgi** [comment]
@SrdjanCosicPrica That is because, Icon in Button has marginHorizontal
Try reducing that

**Comment by SrdjanCosicPrica** [comment]
@SupriyaKalghatgi Thanks for the response. I tested it but to no avail. However, I read the documentation on marginHorizontal for react-native and when I explicitly set 
```
marginRight: 0, marginLeft: 0
```
it worked as expected.
Closing.
