### ISSUE TITLE
Segment-Component weird rendering

### ISSUE THREAD

**Issue by fmoessle** [GeekyAnts/NativeBase#1592]
## react-native, react and native-base version
react-native: 0.52.2
react: 16.2.0
native-base: 2.3.7
## Expected behaviour
correct rendering of segment component
## Actual behaviour
segment component not rendered correctly when it has **first**-prop
## Steps to reproduce (code snippet or screenshot)

> <Header hasTabs>
          <Segment>
            <Button
              first
              onPress={() => this.setState({ activeSection: 0 })}
              active={this.state.activeSection === 0}>
              <Text>Events</Text>
            </Button>
            <Button
              onPress={() => this.setState({ activeSection: 1 })}
              active={this.state.activeSection === 1}>
              <Text>Email</Text>
            </Button>
            <Button
              last
              onPress={() => this.setState({ activeSection: 2 })}
              active={this.state.activeSection === 2}>
              <Text>SMS</Text>
            </Button>
          </Segment>
        </Header>

## Screenshot of emulator/device
![screenshot 2018-02-15 20 44 47](https://user-images.githubusercontent.com/17830282/36278005-c45b19ec-1292-11e8-8341-013cd5a14d10.png)

## Is the bug present in both ios and android or in any one of them?
only on a real ios device

**Comment by SupriyaKalghatgi** [comment]
#1400 

[facebook/react-native#11897](https://github.com/facebook/react-native/issues/11897)

[facebook/react-native#17998](https://github.com/facebook/react-native/issues/17998)
