### ISSUE TITLE
ActionSheet on Android exceeds height of screen on long list of items

### ISSUE THREAD

**Issue by a0js** [GeekyAnts/NativeBase#1595]
## react-native, react and native-base version

- react-native: 0.52.2
- react: 16.2.0
- native-base:  2.3.7

## Expected behaviour
When using ActionSheet in Android with a long list of items, the list should be scrollable and bounds of the modal should remain confined within the root container.
## Actual behaviour
The modal height exceeds the height of the container enough that the top of the title is clipped by the top of the content container.
## Steps to reproduce (code snippet or screenshot)
```javascript-jsx
<Button transparent onPress={() => ActionSheet.show(
	{
	   options: collections.map(collection => { return collection.title; }), // Has 12+ entries
	   cancelButtonIndex: 0,
	   title: 'Select Collection'
	},
	buttonIndex => {
		this.changeCollection(collections[buttonIndex]);
	}
)}>
</Button>
```
## Screenshot of emulator/device

![screen shot 2018-02-15 at 5 45 38 pm](https://user-images.githubusercontent.com/3289501/36288535-4f18886e-1278-11e8-8fbc-bec89af19696.png)

It may appear that the status bar is covering the top, but in reality the container is trimmed to the bottom of the spacebar, otherwise the top of the 'S' and 'C' would be visible under the status bar that has an alpha value on the color.

## Is the bug present in both ios and android or in any one of them?
Android only, ios uses the built in ios actionsheet.

## Any other additional info which would help us debug the issue quicker.
I already found a solution.  Adding `maxHeight: '100%'` to the TouchableOpacity view will give the expected behavior.  I will open a pull request to fix the issue.

**Comment by SupriyaKalghatgi** [comment]
Fixed with [2.3.9](https://github.com/GeekyAnts/NativeBase/releases/tag/v2.3.9)
