### ISSUE TITLE
How to add one only button aligned right in the header?

### ISSUE THREAD

**Issue by emirdeliz** [GeekyAnts/NativeBase#160]
By default first button is aligned in the left and second in right. How to add one only button aligned right in the header?

**Comment by sankhadeeproy007** [comment]
As of now, there is no proper way of doing it (sad). One "hacky" way is to add two buttons, and make the first button transparent. Something like this. 
![screen shot 2016-09-09 at 1 04 54 am](https://cloud.githubusercontent.com/assets/10998047/18363858/86d33b56-7629-11e6-865a-61ea0d25010b.png)

**Comment by yosmanyga** [comment]
Also try putting an empty `Title` and then the `Button`.
