### ISSUE TITLE
floatingLabel input doesn't "unfloat" after setting value with input blurred

### ISSUE THREAD

**Issue by rizzomichaelg** [GeekyAnts/NativeBase#1605]
## react-native, react and native-base version
react: 16.2.0, react-native: 0.53.0, native-base: 2.3.9

## Expected behaviour
When an Input within a floatingLabel Item has its value cleared programmatically, the label should "unfloat".

## Actual behaviour
The label remains floating above.

## Steps to reproduce (code snippet or screenshot)
```
import React, { Component } from 'react';
import { Container, Header, Content, Form, Item, Input, Label } from 'native-base';
export default class FloatingLabelExample extends Component {
  constructor() {
    super();
    this.state = {
      username: '',
    };
    setTimeout(() => {
      this.setState({ username: 'foo' });
      setTimeout(() => {
        this.setState({ username: '' });
      }, 2000);
    }, 5000);
  }
  render() {
    return (
      <Container>
        <Header />
        <Content>
          <Form>
            <Item floatingLabel>
              <Label>Username</Label>
              <Input value={this.state.username} />
            </Item>
          </Form>
        </Content>
      </Container>
    );
  }
}
```

## Screenshot of emulator/device
![image](https://user-images.githubusercontent.com/4391494/36355894-e66211d4-14af-11e8-81d7-5cf0f24f5b34.png)

## Is the bug present in both ios and android or in any one of them?
Present on both.

## Any other additional info which would help us debug the issue quicker.
Can be fixed by explicitly setting "isFocused: false" in Item's componentDidMount and componentWillReceiveProps.  PR coming soon.

**Comment by rizzomichaelg** [comment]
PR #1606

**Comment by SupriyaKalghatgi** [comment]
#1079

**Comment by vbansod1** [comment]
Facing the issue with the latest version. Label doesn't float back if empty text is been set on blurred input
