### ISSUE TITLE
react-web backend?

### ISSUE THREAD

**Issue by acornejo** [GeekyAnts/NativeBase#161]
Are there any plans to add a react-web (or react-native-web) backend?

This would allow folks to develop applications that run on the browser, on ios and on android using the same code base.

**Comment by sanketsahusoft** [comment]
It's on our roadmap.

Though, someone has forked NativeBase and made it work for React for Web.
https://github.com/Chion82/native-base-web

We will make some official announcements in a month or so

**Comment by acornejo** [comment]
Thanks for the prompt reply! Is the roadmap infernal or is it available somewhere? On the website all i could find was:

CLI to rename the app
Image Lightbox
ListView Swipe
Unified date picker

Also could you clarify what will be announced in 1 month? The roadmap? The fork? Or the new work for native-web? Thanks again.

**Comment by olegstepura** [comment]
Hi, guys! 

Is there any news on this issue?

**Comment by PavelPZ** [comment]
Hi,
we need the compatibility with react-native-web in order to accomplish a true cross-platform experience with React.js. Is there any news please?
