### ISSUE TITLE
Floating label get cutted

### ISSUE THREAD

**Issue by hjJunior** [GeekyAnts/NativeBase#1612]
## react-native, react and native-base version
react-native-cli: 2.0.1
react-native: 0.52.1
native-base: 2.3.7
react: 16.2.0
Windows: 10 
Android: 8.0 

I'm getting the same bug of #1006 
The floating label get cutted when is floating

## Expected behaviour
![input-floating](https://user-images.githubusercontent.com/10780132/36396267-e5d8b4ec-159b-11e8-9f19-9f7a391ee7b3.gif)

## Actual behaviour
![image](https://user-images.githubusercontent.com/10780132/36396228-b910f83e-159b-11e8-8c48-61c643e23954.png)

## Steps to reproduce (code snippet or screenshot)
            <Container>
                <Header> ...
                <Content>
                    <Form>
                        <Item floatingLabel>
                            <Label>Username</Label>
                            <Input />
                        </Item>
                        <Item floatingLabel last>
                            <Label>Password</Label>
                            <Input />
                        </Item>
                    </Form>
                </Content>
            </Container>
## Screenshot of emulator/device
![screenshot_1519073305](https://user-images.githubusercontent.com/10780132/36396464-24abf7dc-159d-11e8-80db-784343f8cd66.png)
Even without the header component
![screenshot_1519073372](https://user-images.githubusercontent.com/10780132/36396491-43a6fc40-159d-11e8-83b1-d5be0f83c581.png)

**Comment by SupriyaKalghatgi** [comment]
#1532 
Fixed with [2.3.8](https://github.com/GeekyAnts/NativeBase/releases/tag/v2.3.8)

**Comment by Aishwarya-Surana** [comment]
I am facing  the same issue with 2.3.10


![screen shot 2018-03-20 at 11 53 02 am](https://user-images.githubusercontent.com/31925389/37638922-4cdfd71a-2c35-11e8-9a48-9558d084956f.png)
