### ISSUE TITLE
Use v2.2.1 with latest react-native version(0.46). Older versions may break.

### ISSUE THREAD

**Issue by GuillotJessica** [GeekyAnts/NativeBase#1616]
Hi! Thanks for coding NativeBase!
First page says:
Use v2.2.1 with latest react-native version(0.46). Older versions may break.
This specific is quiet old perhaps issues regarding this ersion has been fixed since

**Comment by SupriyaKalghatgi** [comment]
@GuillotJessica Updated ReadMe
