### ISSUE TITLE
header background colour is not changing  in android

### ISSUE THREAD

**Issue by rizwan92** [GeekyAnts/NativeBase#1619]
"react": "16.2.0",
    "react-native": "0.53.0",
    "react-navigation": "^1.0.3"

## Expected behaviour
 `  <Header backgroundColor="#2196F3"  androidStatusBarColor="#000000">`
header colour change to this  #2196F3 colour to its by default colour in android

## Actual behaviour
when i press ctrl + s by hot loading header colour changes to this  #2196F3 colour. but when i rebuilt my app by giving command react-native run-android header colour comes to its by default  colour

## Steps to reproduce (code snippet or screenshot)
![speakup](https://user-images.githubusercontent.com/19162978/36497784-4f4139aa-1762-11e8-9f37-cf6172614fe0.png)

## Screenshot of emulator/device
![screenshot_20180221-235208](https://user-images.githubusercontent.com/19162978/36497841-79a97ef0-1762-11e8-87a5-f5d3c48c9223.png)

## Is the bug present in both ios and android or in any one of them?
i don't know about ios but in android

## Any other additional info which would help us debug the issue quicker.
i don't know

**Comment by akhil-geekyants** [comment]
@rizwan92 as a workaround, you can specify the color in style prop of header.
```
 <Header
          style={{ backgroundColor: 'red' }}
          androidStatusBarColor="red">
</Header>
```

**Comment by akhil-geekyants** [comment]
@rizwan92 `backgroundColor` prop of `<Header/>` will be removed. Use style instead. 
This will be documented.

**Comment by SupriyaKalghatgi** [comment]
https://github.com/GeekyAnts/native-base-docs/issues/81

**Comment by raajnadar** [comment]
What if I want to set the Header color in all my views??

I tried changing the value in the themes/components/Header.js file
`backgroundColor: variables.toolbarDefaultBg`

This var is declared in themes/variables/platform.js file so I changed 

`toolbarDefaultBg: platform === 'ios' ? '#F8F8F8' : '#FFFFFF',`
The above code didn't work

But as soon as I replace it with this code it works..
`backgroundColor: '#fff',`

Why is this happening??

**Comment by akhil-geekyants** [comment]
@raajnadar checked this. `toolbarDefaultBg` is working fine for me. Attaching a gif.

Gif

![headerbackground](https://user-images.githubusercontent.com/27768184/38301559-89a4bfe6-381d-11e8-809a-dacdd78dd6e8.gif)

**Comment by raajnadar** [comment]
See I am testing my app with Expo and my Xperia M android 7.1.1, whenever I try to use variables they don't work but as soon as I hard code them inside the component's JS file they work.

Tried clearing the cache did everything that is stated in the docs but nothing worked. Currently I am setting colors for Header.js file hard coded, due to the hard code the status bar color does not change as per the header color.

**Comment by akhil-geekyants** [comment]
@raajnadar can you create a test repo for us to check.

**Comment by raajnadar** [comment]
Forgot to mention I am using the exact copy of this repository https://github.com/GeekyAnts/NativeBase-KitchenSink just to get a kick start.

I am using the CRNA branch the only thing that I did is removed few dependencies. This is how my dependencies look now.

```
{
	"name": "test",
	"version": "1.0.0",
	"private": true,
	"devDependencies": {
		"jest-expo": "^26.0.0",
		"react-native-scripts": "1.11.1",
		"react-test-renderer": "16.2.0"
	},
	"main": "./node_modules/react-native-scripts/build/bin/crna-entry.js",
	"scripts": {
		"start": "react-native-scripts start",
		"eject": "react-native-scripts eject",
		"android": "react-native-scripts android",
		"ios": "react-native-scripts ios",
		"test": "node node_modules/jest/bin/jest.js"
	},
	"jest": {
		"preset": "jest-expo"
	},
	"dependencies": {
		"@expo/vector-icons": "^6.3.1",
		"expo": "^26.0.0",
		"firebase": "^4.11.0",
		"native-base": "^2.4.1",
		"prop-types": "15.6.0",
		"react": "16.3.0-alpha.1",
		"react-native": "https://github.com/expo/react-native/archive/sdk-26.0.0.tar.gz",
		"react-navigation": "^1.0.3"
	}
}
```

And I switched to expo sdk 26 just now.

**Comment by my-name-is-nheo** [comment]
> @raajnadar checked this. `toolbarDefaultBg` is working fine for me. Attaching a gif.
> 
> Gif
> 
> ![headerbackground](https://user-images.githubusercontent.com/27768184/38301559-89a4bfe6-381d-11e8-809a-dacdd78dd6e8.gif)
crazy how this doesn't work...could it be because I have headerMode off ?
