### ISSUE TITLE
Underlined Textbox with Icon renders Icon incorrectly, shows 3 dots

### ISSUE THREAD

**Issue by jjzazuet** [GeekyAnts/NativeBase#162]
Hi. Thanks for this awesome framework!

I've recently upgraded my project's dependencies and I think `InputGroup` with `Icon` is rendering incorrectly. In this screenshot, you see two `InputGroup`s and a `Button` with an `Icon`. The button with the icon renders correctly (I'm using `FontAwesome` as the theme icon family). However, the text inputs are not rendering their icons.

The Android project references the `react-native-icons` gradle subproject to copy the icons, and the `VectorIconsPackage` is referenced from `MainApplication`.

Am I missing something? These are my NPM dependencies. Thanks!

```
  "dependencies": {
    "color": "0.11.3",
    "native-base": 0.5.7",
    "react": "15.3.1",
    "react-native": "0.32.0",
    "react-native-vector-icons": "2.1.0"
  },
```

```
<InputGroup style={styles.login}>
  <Icon name="user" style={styles.whiteFont} />
  <Input placeholder="Username" style={styles.whiteFont}
    value={this.state.username}
    onChangeText={(txt) => { this.onUser(txt); }} />
</InputGroup>
...
<View style={styles.login}>
  <Button block onPress={() => { this.onLogin(); }}>
    <Icon name="lock" style={styles.whiteFont} />
  </Button>
</View>
```

![screenshot_20160906-015359](https://cloud.githubusercontent.com/assets/1002433/18263052/de22c702-73d4-11e6-859e-75b76e2c0bf2.png)

**Comment by acamenhas** [comment]
I have this problem too, but on device (tested on Android) works well.

**Comment by sankhadeeproy007** [comment]
Did you try checking with react-native-vector-icons? It might be related to that.

**Comment by jjzazuet** [comment]
@sankhadeeproy007 while it would be helpful to get feedback from the upstream project, the example code shows two different places where the `Icon` component is rendering. One works (the button), the other one doesn't (the input group), using the exact same icon definition. This tells me that there might be some unexpected behavior when the `Icon` component renders as a part of the input group.

Hope this helps. Thanks!

**Comment by sankhadeeproy007** [comment]
It is very hard to reproduce this without further details. Can you try it on a clean page with out any other dependencies?

**Comment by cellis** [comment]
Same problem, i actually filed this in react-native-vector-icons https://github.com/oblador/react-native-vector-icons/issues/294

**Comment by sankhadeeproy007** [comment]
Can you please try with different icons and check if the result is the same?

**Comment by ravigadila** [comment]
code works well in Android 6.0 device.
But in Android 7.1.1 device showing ... (dots) see attached screen
![screenshot_1484547967](https://cloud.githubusercontent.com/assets/8197942/21972937/0bf2a4c4-dbe3-11e6-8828-eccbd16bee75.png)

When i place same icon outside of input group it showing without any issue.

Using:
"react": "15.3.2"
"react-native": "0.32.0"
"native-base": "0.5.8"

**Comment by jesouhaite08** [comment]
I'm having this issue as well.

**Comment by jesouhaite08** [comment]
It renders correctly on my phone, just shows the three dots in the emulator. Strange.

**Comment by sankhadeeproy007** [comment]
Try with a lower fontSize for the icons please.

**Comment by jesouhaite08** [comment]
@sankhadeeproy007 I did try this. It just makes the three dots smaller. 

<Icon name='ios-person-outline' style={{ color: '#fff', fontSize: 10 }} />

produces the following:

<img width="247" alt="screen shot 2017-02-02 at 7 31 04 am" src="https://cloud.githubusercontent.com/assets/7729839/22549505/a6e8ca56-e919-11e6-8740-52daeb0a7f24.png">

**Comment by sankhadeeproy007** [comment]
Try out [this](https://github.com/oblador/react-native-vector-icons/issues/294#issuecomment-252786058) solution then?

**Comment by jesouhaite08** [comment]
No luck. The issue seems to be something within NativeBase's styling for InputGroup. My current code is:

    <InputGroup>
      <Icon name='ios-person-outline' style={{ color: '#fff' }} />
      <Input
        value={this.state.username}
        style={styles.loginText} 
        placeholder='Email'
        placeholderTextColor='#ffffff'
        onChangeText={(text) => this.setState({username: text})} />
    </InputGroup>

Changing the InputGroup element to View renders the icon correctly. I tried setting a width and height to InputGroup, but results were the same.
