### ISSUE TITLE
round tabbar button

### ISSUE THREAD

**Issue by itcurves** [GeekyAnts/NativeBase#1625]
Hi I already check an existing case but did not help me. also did not get any reply, that is why creating new case and referencing my comment.

https://github.com/GeekyAnts/NativeBase/issues/1260#issuecomment-366543713

Please provide me any help possible.

Thank you

**Comment by akhil-geekyants** [comment]
@itcurves see comment https://github.com/GeekyAnts/NativeBase/issues/1260#issuecomment-368426565

Closing this issue.
