### ISSUE TITLE
Input type email

### ISSUE THREAD

**Issue by vasilgramov** [GeekyAnts/NativeBase#1626]
Hei guys,
I could not find any specific property for Input to make it behave like email. Is there any?

**Comment by SupriyaKalghatgi** [comment]
@vasilgramov NativeBase provides UI elements. You can go ahead adding functionality as per your requirement

**Comment by antoinerousseau** [comment]
Tried to add `_input={{ type: "email" }}` but didn't work, how do I do that?

**Comment by antoinerousseau** [comment]
Ok found the solution, it's `keyboardType="email-address"`
