### ISSUE TITLE
First tab showing extra space if second tab has large list data

### ISSUE THREAD

**Issue by AgNm** [GeekyAnts/NativeBase#1627]
## react-native, react and native-base version

react-native-cli: 2.0.1
react-native: 0.52.2
"native-base": "^2.3.5"

## Expected behaviour

Screen should scroll only till last item in tab

## Actual behaviour

First tab showing extra space at the end if second tab has large list data, It scrolls until second tab data ends

## Steps to reproduce (code snippet or screenshot)

Add less list items in first tab & more in second tab

## Screenshot of emulator/device

![screen shot 2018-02-25 at 1 21 34 pm](https://user-images.githubusercontent.com/11326181/36639261-d6825e7a-1a2e-11e8-8984-667479c36178.png)

## Is the bug present in both ios and android or in any one of them?

Could not check on ios, I am facing issue in Android

**Comment by SupriyaKalghatgi** [comment]
@AgNm Share code snippet for this, along with GIF of the behavior

**Comment by akhil-geekyants** [comment]
Closing this issue due to no response.

**Comment by AgNm** [comment]
please refer this link : https://streamable.com/pqfm6

**Comment by SupriyaKalghatgi** [comment]
@AgNm 
![image](https://user-images.githubusercontent.com/13464885/37383062-472db79c-276c-11e8-8dc4-e9c7d235cfd0.png)

**Comment by durgesh0001** [comment]
@SupriyaKalghatgi I am able to access the link

**Comment by SupriyaKalghatgi** [comment]
I cant access it yet
