### ISSUE TITLE
How set Drawer open from right ?

### ISSUE THREAD

**Issue by Arshiamidos** [GeekyAnts/NativeBase#1628]
thnak for your greate jobs 
and my question is how change direction of  drawer and where i can find drawer props?

**Comment by tkreis** [comment]
You can find the props here: https://github.com/GeekyAnts/NativeBase/blob/master/src/basic/Drawer/index.js and here https://github.com/root-two/react-native-drawer.

**Comment by brownieboy** [comment]
There's a **side** prop that takes "left" or "right" values, e.g:
```
<Drawer
  side="right"
  ref={ref => {
    this.drawer = ref;
  }}
  content={<SideBar navigator={this.navigator} />}
  onClose={() => this.closeDrawer()}
/>
```
