### ISSUE TITLE
Error in Typescript of SwipeRow definition

### ISSUE THREAD

**Issue by tkreis** [GeekyAnts/NativeBase#1629]
It seems like the  exported Typescript definition of SwipeRow is missing the body in it's definition:
https://github.com/GeekyAnts/NativeBase/blob/master/index.d.ts#L756
https://docs.nativebase.io/Components.html#swipeable-single-def-headref

**Comment by SupriyaKalghatgi** [comment]
Fixed with NB [2.3.10](https://github.com/GeekyAnts/NativeBase/releases/tag/v2.3.10)
