### ISSUE TITLE
Is there a date calendar picker?

### ISSUE THREAD

**Issue by yaronlevi** [GeekyAnts/NativeBase#163]
In Native Starter Pro you have a calendar date picker.
Where can I find it in Native Base components?
Is there a plan to include one in Native Base components?
To be clear I am referring to a calendar in android like so:
![screen shot 2016-09-06 at 1 42 46 pm](https://cloud.githubusercontent.com/assets/5398977/18270875/ddaf8734-7437-11e6-8ec1-5cfa68309219.png)

And a matching one in iOS.

Currently there is one github project that provides such a calendar but I think the experience is not yet optimal. If you could come up with such a component it will fill a very basic need for every react native dev.

**Comment by sankhadeeproy007** [comment]
Please file new requests in this thread. The datepicker has already been mentioned. We have that in our roadmap. 
https://github.com/GeekyAnts/NativeBase/issues/38

**Comment by yaronlevi** [comment]
Thank you

**Comment by SupriyaKalghatgi** [comment]
#882
