### ISSUE TITLE
close Drawer from inside of sidebar menu (closeButton)

### ISSUE THREAD

**Issue by Arshiamidos** [GeekyAnts/NativeBase#1631]
i have X button like in my sidebarmenu and how access to call function closeDrawer of Drawer menu?
thanks

**Comment by akhil-geekyants** [comment]
@Arshiamidos you can close the drawer by passing closeDrawer function as a prop to the drawer component and call the function from inside the Drawer component.

Gif

![closedrawer](https://user-images.githubusercontent.com/27768184/36656846-204dc910-1af0-11e8-943b-b214ec1af170.gif)

**Comment by abdulmstellent** [comment]
hi, @akhil-geekyants  It's not working for me.... 
can u please fix me this issue.
here is my code:
MAIN CONTAINER:
   ```
 closeDrawer = () =>  {
        this.drawer._root.close();
    };
  openDrawer = () =>  {
      this.drawer._root.open();
  };

<Drawer
              ref={(ref) => { this.drawer = ref; }}
              content={<SideBar closeDrawer= {this.closeDrawer} />}
              openDrawerOffset={0.3}
              panCloseMask={0.3}
              onClose={() => this.closeDrawer()} >
```

SIDEBAR COMPONENT:
 ```
 <TouchableOpacity onPress = {() => this.props.closeDrawer()}>
            <Icon size={24} color="white" name="chevron-right"  />
 </TouchableOpacity>
```
Here is my screenshot
![simulator screen shot - iphone 8 - 2018-04-14 at 12 55 17](https://user-images.githubusercontent.com/37574500/38765611-17585f6a-3fe3-11e8-93d7-8f17cff115e0.png)

**Comment by SupriyaKalghatgi** [comment]
@abdulmstellent There is a working example with output provided above
Please check it accordingly
