### ISSUE TITLE
Can't use Feather icons, it got removed? Lol

### ISSUE THREAD

**Issue by xemasiv** [GeekyAnts/NativeBase#1632]
Feather is imported @ https://github.com/GeekyAnts/NativeBase/blob/master/src/basic/IconNB.js#L8

But then there isn't 

```
			case "Feather":
				this.Icon = Feather;
				break;
```

Which is supposed to be existing, as added in https://github.com/GeekyAnts/NativeBase/pull/1383

**Comment by SupriyaKalghatgi** [comment]
Fixed on `master`

**Comment by xemasiv** [comment]
@SupriyaKalghatgi thanks for the update.

The following part got missed btw (I forgot to mention it, my bad lol)

```
type: PropTypes.oneOf([
    "Feather"
])
```
