### ISSUE TITLE
fontVariant (array of enum) not supported from theme files

### ISSUE THREAD

**Issue by hugofelp** [GeekyAnts/NativeBase#1637]
## react-native, react and native-base version
RN 0.53.3
NB 2.3.9

## Expected behaviour
text is rendered with intended styles

## Actual behaviour
Application throws an exception

## Steps to reproduce (code snippet or screenshot)
Provide an array as value to fontVariant property in any theme file. Example: 

```
import variable from "./../variables/platform";

export default (variables = variable) => {
  const h1Theme = {
    color: variables.textColor,
    fontSize: variables.fontSizeH1,
    lineHeight: variables.lineHeightH1,
    fontWeight: '200',
    fontVariant: ['small-caps']
  };

  return h1Theme;
};
```

## Screenshot of emulator/device
![screen shot 2018-02-28 at 11 26 12 am](https://user-images.githubusercontent.com/73772/36759042-ff0638e6-1c7a-11e8-89da-60ddc25a6b10.png)

## Is the bug present in both ios and android or in any one of them?
Yes

## Any other additional info which would help us debug the issue quicker.
fontVariant expects an array as per documentation - https://facebook.github.io/react-native/docs/text-style-props.html#fontvariant

**Comment by SupriyaKalghatgi** [comment]
Fixed with NB [2.3.10](https://github.com/GeekyAnts/NativeBase/releases/tag/v2.3.10)
