### ISSUE TITLE
floating label overlapping value in the release mode

### ISSUE THREAD

**Issue by RyanRong** [GeekyAnts/NativeBase#1638]
Hi,

I'm using floating label on a simple input. When I pass value to this component, it's overlapping in the release mode, but  in the debug mode Work well.

<Form style={{marginTop:50}}>

                        <Item floatingLabel last>
                            <Label>请输入您的用户名／手机号</Label>
                            <Input keyboardType={"email-address"}
                                   value={this.state.username}
                                   onChangeText={(username) => this.setState({username:username})}/>
                        </Item>
                        <Item floatingLabel last>
                            <Label>请输入您的密码</Label>
                            <Input secureTextEntry={true}
                                   value={this.state.passward}
                                   onChangeText={(passward) => this.setState({passward:passward})}/>
                        </Item>
                    </Form>
```

<TouchableOpacity
                                onPress={() => this.props.navigation.navigate("Register",{returnData: this.returnData.bind(this)})}
                                style={{marginLeft:8}}>
                                <Text style={styles.text}>注册新账号</Text>
                            </TouchableOpacity>

 returnData(mobile, psw) {
        this.setState({username: mobile, passward: psw});
    }
```

![wechatimg8958](https://user-images.githubusercontent.com/11749548/36774494-422e8f9c-1c99-11e8-842d-33a639131df0.jpeg)
## react-native, react and native-base version
 "native-base": "2.3.8",
    "react-native": "0.49.3",
    "react": "16.0.0-beta.5",

**Comment by akhil-geekyants** [comment]
related to issue #627

**Comment by prionkor** [comment]
This issue is still not fixed. The related issue #627 is closed for some reason. Doesn't anyone have fix for this?

**Comment by johnshroff** [comment]
+1 same issue

**Comment by vendeesh** [comment]
+1 same issue

**Comment by indranildutta06** [comment]
+1 same issue

**Comment by FKeim** [comment]
if floating label overlapped when has a value, try to set value in the constructor when are defining this.state
