### ISSUE TITLE
After eject theme to customize my theme App run very slow.

### ISSUE THREAD

**Issue by XuanPH** [GeekyAnts/NativeBase#1639]
Hi! After eject theme to customize my theme App run very slow(debug - release). And turn on debug mode app working fine.

## Screenshot of emulator/device
<img width="600" alt="screen shot 2018-02-28 at 5 00 15 pm" src="https://user-images.githubusercontent.com/26076388/36781659-152a41ca-1ca9-11e8-9611-777ee6e44249.png">
App load all of theme and redux.

**Comment by SupriyaKalghatgi** [comment]
#1012
