### ISSUE TITLE
Unresponsive Radio Button

### ISSUE THREAD

**Issue by RachelGreenberger** [GeekyAnts/NativeBase#164]
How do you hook up the radio button to respond to the user's click? I understand that you would use 'onPress' and connect it to a function that would manipulate the selected property. However, I am finding that the radio button does not respond to onPress. How can I make it responsive? Thank you!

**Comment by sankhadeeproy007** [comment]
Hi, this has been fixed in master. Can you point your package.json to master and check if the error persists. Don't forget to reinstall native-base if you change the dependency in package.json

**Comment by RachelGreenberger** [comment]
Thank you so much, the error is gone!
