### ISSUE TITLE
Broken link after running ejectTheme.js

### ISSUE THREAD

**Issue by kale-stew** [GeekyAnts/NativeBase#1641]
## react-native and native-base Versions

`react-native: 0.49.5`
`native-base: 2.3.9`

## Expected Behaviour vs Actual Behaviour

When ejecting the native-base theme, the link inside of the terminal prompt to "check out the docs" opens to a 404.

## Steps to Reproduce

1. run `node node_modules/native-base/ejectTheme.js`
2. click on the link in your terminal
3. this opens a 404 page on docs.nativebase.io

## Screenshot of Emulator/Device

![screen shot 2018-02-28 at 6 25 49 pm](https://user-images.githubusercontent.com/30479228/36822341-d4fc9344-1cb4-11e8-8781-efde4b16eb48.png)

## Other Info

This is not an issue related to the performance of native-base, but instead the documentation.

**Comment by SupriyaKalghatgi** [comment]
Check PR #1642
