### ISSUE TITLE
Order of components affects styling

### ISSUE THREAD

**Issue by hugofelp** [GeekyAnts/NativeBase#1644]
## react-native, react and native-base version
"native-base": "^2.3.9",
"react-native": "0.53.3",

## Steps to reproduce (code snippet or screenshot)

1. run `ejectTheme` script
2. customise `Item` styles:
```
{
    ...
    ".regular": {
      "NativeBase.Input": {
        backgroundColor: 'red'
       }
    }
    ...
}
```
3. render component:
```
function SampleComponent() {
    return (
        <View>
            <Item regular>
                <Input placeholder="Email" />
            </Item>
            <Item>
                <Input placeholder="Email" />
            </Item>
        </View>
    )
}
```
3. Invert the order of the `Item`s:
```
function SampleComponent() {
    return (
        <View>
            <Item>
                <Input placeholder="Email" />
            </Item>
            <Item regular>
                <Input placeholder="Email" />
            </Item>
        </View>
    )
}
```

On the first instance both `Input`s will have a red background.
On the second instance none of the `Input`s will pick up the red background.

The expected is only the `Input` under `Item` with `regular` attribute will have a red background.

## Is the bug present in both ios and android or in any one of them?
yes

**Comment by akhil-geekyants** [comment]
@hugofelp tried the above example. Couldn't see anything like you mentioned. Can you reset the cache and try again. Attaching a gif

![itemstyling](https://user-images.githubusercontent.com/27768184/36886666-8111cf64-1e13-11e8-9b7a-e17179daead1.gif)

**Comment by hugofelp** [comment]
Hi @akhil-geekyants. Thanks for your response.
After clearing the cache and getting the same results, I started a new project from React Native Seed to try and reproduce the bug.

**It turns out I was importing `View` from `react-native` instead of importing from `native-base`.** That is the only step missing from the description above on how to reproduce.

So I guess my problem is solved, but if you agree this is a bug and want to look into it, here is the file I have at `src/boot/setup.js `:
```
import * as React from "react"
import { View } from "react-native"
import { StyleProvider, Item, Input } from "native-base"
import getTheme from "../theme/components"
import variables from "../theme/variables/platform"

export default class Setup extends React.Component<Props, State> {
  render() {
    return (
      <StyleProvider style={getTheme(variables)}>
        <View>
          <Item>
            <Input placeholder="Email" />
          </Item>
          <Item regular>
            <Input placeholder="Email" />
          </Item>
        </View>
      </StyleProvider>
    )
  }
}
```

And some screenshots:
![screen shot 2018-03-05 at 1 01 44 pm](https://user-images.githubusercontent.com/73772/36952724-79e56a40-2078-11e8-9971-fdbe251c950f.png)
![screen shot 2018-03-05 at 1 02 03 pm](https://user-images.githubusercontent.com/73772/36952725-7a3ebc62-2078-11e8-825a-04bee6cf6cac.png)

**Comment by SupriyaKalghatgi** [comment]
@hugofelp Importing` View` from NativeBase actually solves the problem
