### ISSUE TITLE
Property Thumbnail

### ISSUE THREAD

**Issue by acherkashin** [GeekyAnts/NativeBase#1647]
react-native - 0.51.0
native-base - 2.3.9

I use next code:
`<Thumbnail size={3000} square source={{ uri: avatar }} />`

![thumbnail-size](https://user-images.githubusercontent.com/9947582/36948999-a530af78-1ff3-11e8-98c3-dbc4d2aafeac.gif)

**Comment by SupriyaKalghatgi** [comment]
#1648
