### ISSUE TITLE
Property Thumbnail's size don't change image size

### ISSUE THREAD

**Issue by acherkashin** [GeekyAnts/NativeBase#1648]
react-native - 0.51.0
native-base - 2.3.9

I use next code:
`<Thumbnail size={3000} square source={{ uri: avatar }} />`

![thumbnail-size](https://user-images.githubusercontent.com/9947582/36948999-a530af78-1ff3-11e8-98c3-dbc4d2aafeac.gif)

But I can change size by style property:
`<Thumbnail square source={{ uri: avatar }} style={{width: 300, height: 300}}/>`

**Comment by SupriyaKalghatgi** [comment]
@acherkashin Check the Docs
![image](https://user-images.githubusercontent.com/13464885/36960637-e3c6be9c-206d-11e8-87c6-59e90aba469b.png)

Also `Thumbnail` example in NativeBase-KitchenSick https://github.com/GeekyAnts/NativeBase-KitchenSink/blob/master/src/screens/thumbnail/index.js

`Thumbnail` supports two of size props, `small`, `large` and the default one as medium (without any prop). Any other dimensions apart from these props, you need to wrap them in style attribute

```
style={{ height: 150, width: 150 }}
```
