### ISSUE TITLE
Error undefined is not an object (Evaluating undefined.brandPrimary)

### ISSUE THREAD

**Issue by iamlasse** [GeekyAnts/NativeBase#1649]
React Native 0.52.0
React 16.2.0
Native Base 2.3.9

Error undefined is not an object (Evaluating undefined.brandPrimary)
This worked last night and I was working on the app this morning I'm faced with this stupid red screen again and this weird error... I didn't update Native-base between today and yesterday nor did I touch the code...???

**Comment by SupriyaKalghatgi** [comment]
#1578
