### ISSUE TITLE
Bug when using iconFamily: 'FontAwesome' with CheckBox 

### ISSUE THREAD

**Issue by yaronlevi** [GeekyAnts/NativeBase#165]
I am working with FontAwesome, so inside light.js I defined:
`iconFamily: 'FontAwesome'`

The problem is when I use a checkbox component:
`<CheckBox checked={true} />`

I get an error:
![screen shot 2016-09-07 at 12 52 52 am](https://cloud.githubusercontent.com/assets/5398977/18292353/6cfc93ac-7495-11e6-871c-693ec866c1c1.png)

And I can see why this is happening, because in Checkbox.js there is:

`<Icon name={(Platform.OS === 'ios') ? 'ios-checkmark-outline' : 'md-checkmark'} style={{color:  this.props.checked ? this.getTheme().checkboxTickColor : 'transparent', lineHeight: (Platform.OS === 'ios') ? this.getTheme().checkboxSize/0.93 : this.getTheme().checkboxSize-5, marginTop: (Platform.OS==='ios') ? undefined : 1, fontSize: (Platform.OS === 'ios') ? this.getTheme().checkboxSize/0.8 : this.getTheme().checkboxSize/1.2}} />`

And **ios-checkmark-outline** is probably some icon from another theme. 
Have I missed a step when changing to FontAwesome?

**Comment by sankhadeeproy007** [comment]
No, you're right. It's a bug. Will fix it next up.

**Comment by sankhadeeproy007** [comment]
Fixed with 0.5.8
