### ISSUE TITLE
Picker in CardItem is shown but it does not change selected item

### ISSUE THREAD

**Issue by GiacomoK** [GeekyAnts/NativeBase#1651]
## react-native, react and native-base version
"react": "16.0.0-alpha.12",
"react-native": "0.47.2",
"native-base": "^2.3.3",,
## Expected behaviour
When I select "first" or "second", the value in picker should change
## Actual behaviour
The selected value is always "No type"
## Steps to reproduce (code snippet or screenshot)
    <Container>
        <Content>
            <FlatList
                data={this.state.events}
                renderItem={(item) =>
                    <Card style={{ flex: 0 }}>
                    <CardItem style={{ borderBottomColor: 'rgba(0,0,0,0.1)', borderBottomWidth: 1 }}>
                            <Left>
                                <Body>
                                    <Text>{item.item.title}</Text>
                                    <Text note>{item.item.start}</Text>
                                    <Picker
                                        iosHeader="Select one"
                                        mode="dropdown"
                                        onValueChange={this.onValueChange.bind(this, item.item)}>
                                        <Picker.Item label="No type" value="choose" />
                                        <Picker.Item label="First type" value="first" />
                                        <Picker.Item label="Second type" value="second" />
                                    </Picker>
                                    <Item stackedLabel>
                                        <Label>Sites</Label>
                                        <Input keyboardType="numeric" />
                                    </Item>
                                    <Item stackedLabel>
                                        <Label>Price</Label>
                                        <Input keyboardType="numeric" />
                                    </Item>
                                    <ListItem>
                                        <CheckBox checked={true} />
                                        <Body>
                                            <Text>Daily Stand Up</Text>
                                        </Body>
                                    </ListItem>
                                    <ListItem>
                                        <CheckBox checked={false} />
                                        <Body>
                                            <Text>Discussion with Client</Text>
                                            </Body>
                                    </ListItem>
                                </Body>
                            </Left>
                        </CardItem>
                   </Card>}
                ListFooterComponent={this.renderFooter.bind(this)}
            />
        </Content>
    </Container>
## Is the bug present in both ios and android or in any one of them?
Tried only on a Android device (not the emulator)

**Comment by SupriyaKalghatgi** [comment]
@GiacomoK Tried including [Picker from Docs](https://docs.nativebase.io/Components.html#picker-def-headref) within Card, worked as expected

**Comment by GiacomoK** [comment]
Sorry @SupriyaKalghatgi , I did not understand your answer.

**Comment by akhil-geekyants** [comment]
@GiacomoK you have to add [extraData](https://facebook.github.io/react-native/docs/flatlist.html#extradata) prop to Flatlist

Tried your code with dummy values 

Code
```
import React, { Component } from 'react';
import { Container, Header, Content, Card, CardItem, Left, Body, Picker, Item, Label, Input, ListItem, CheckBox, Text } from 'native-base';
import { FlatList } from 'react-native'

export default class App extends Component {
  constructor(props) {
    super(props)
    this.state = { events: [1, 2, 3, 4, 5], selected: "choose" }
  }

  onValueChange(value) {
    this.setState({
      selected: value
    });
  }

  render() {
    return (
      <Container>
        <Content>
          <FlatList
            data={this.state.events}
            extraData={this.state}
            renderItem={(item) =>
              <Card style={{ flex: 0 }}>
                <CardItem style={{ borderBottomColor: 'rgba(0,0,0,0.1)', borderBottomWidth: 1 }}>
                  <Left>
                    <Body>
                      <Text>Title</Text>
                      <Text note>Start</Text>
                      <Picker
                        iosHeader="Select one"
                        mode="dropdown"
                        onValueChange={this.onValueChange.bind(this)}
                        selectedValue={this.state.selected}
                      >
                        <Picker.Item label="No type" value="choose" />
                        <Picker.Item label="First type" value="first" />
                        <Picker.Item label="Second type" value="second" />
                      </Picker>
                      <Item stackedLabel>
                        <Label>Sites</Label>
                        <Input keyboardType="numeric" />
                      </Item>
                      <Item stackedLabel>
                        <Label>Price</Label>
                        <Input keyboardType="numeric" />
                      </Item>
                      <ListItem>
                        <CheckBox checked={true} />
                        <Body>
                          <Text>Daily Stand Up</Text>
                        </Body>
                      </ListItem>
                      <ListItem>
                        <CheckBox checked={false} />
                        <Body>
                          <Text>Discussion with Client</Text>
                        </Body>
                      </ListItem>
                    </Body>
                  </Left>
                </CardItem>
              </Card>}
          />
        </Content>
      </Container>
    );
  }
}
```

**Comment by GiacomoK** [comment]
@akhil-geekyants  same behaviour :(

**Comment by GiacomoK** [comment]
I think that the problem could be when I pick an item, I set a state that change array, and this probably will render FlatList again, losing values.

**Comment by akhil-geekyants** [comment]
@GiacomoK attaching video file for the above code
[device.mp4.zip](https://github.com/GeekyAnts/NativeBase/files/1787975/device.mp4.zip)

**Comment by GiacomoK** [comment]
@akhil-geekyants 
[Device.zip](https://github.com/GeekyAnts/NativeBase/files/1789324/Device.zip)

**Comment by akhil-geekyants** [comment]
@GiacomoK it is similar to what you get when you hardcode the `selectedValue={"choose"}`. Check whether the value provided to the selectedValue prop is the one selected.

**Comment by GiacomoK** [comment]
Thanks, I solved with this code:

`selectedValue={this.eventGenre(item.item)}`

on picker element.
Now I have a similar problem with CheckBox. They do not remain checked when I push them.

**Comment by akhil-geekyants** [comment]
@GiacomoK tried checkbox example. It is working fine with native-base:2.3.9

Sample code
```
import React, { Component } from 'react';
import { Container, Header, Content, ListItem, CheckBox, Text, Body } from 'native-base';
export default class App extends Component {

  state = {
    checked: 1
  }

  render() {
    return (
      <Container>
        <Header />
        <Content>
          <ListItem onPress={() => this.setState({ checked: 1 })}>
            <CheckBox checked={this.state.checked === 1} />
            <Body>
              <Text>Daily Stand Up</Text>
            </Body>
          </ListItem>
          <ListItem onPress={() => this.setState({ checked: 2 })}>
            <CheckBox checked={this.state.checked === 2} />
            <Body>
              <Text>Discussion with Client</Text>
            </Body>
          </ListItem>
        </Content>
      </Container>
    );
  }
}

```

**Comment by GiacomoK** [comment]
I have this one and it do not work:

`<CheckBox
     checked={this.eventHasGenre(item.item, t_genre.id) > -1 ? true : false}
     />`

This is the function:  
`eventHasGenre(item, genre_id) {
        console.log("eventHasGenre");
        let arEvents = this.state.events.slice();
        for (var i = 0; i < arEvents.length; i++) {
            if (arEvents[i].id == item.id) {
                if (arEvents[i].genres) {
                    return arEvents[i].genres.indexOf(genre_id);
                }
            }
        }
        return false;
    }`

Even if the function returns a value > -1, Checkbox still remains unchecked.

**Comment by akhil-geekyants** [comment]
@GiacomoK  checkbox was working fine. Checked with a similar case.

Sample Code
```
import React, { Component } from 'react';
import { Container, Header, Content, ListItem, CheckBox, Text, Body } from 'native-base';
export default class App extends Component {

  constructor(props) {
    super(props)
    this.state = { value: 1 }
    this.handleOnPress = this.handleOnPress.bind(this);
  }

  handleOnPress() {
    if (this.state.value === -1) {
      this.setState({ value: 1 })
    } else {
      this.setState({ value: -1 })
    }

  }

  eventHasGenre() {
    return this.state.value;
  }

  render() {
    return (
      <Container>
        <Header />
        <Content>
          <ListItem onPress={() => this.handleOnPress()}>
            <CheckBox checked={this.eventHasGenre() > -1 ? true : false} />
            < Body >
              <Text>Daily Stand Up</Text>
            </Body>
          </ListItem>
        </Content>
      </Container>
    );
  }
}
```
Gif

![checkbox](https://user-images.githubusercontent.com/27768184/37267771-584579b4-25e8-11e8-8e50-38fadab5e8bb.gif)
