### ISSUE TITLE
Extend selected Picker Item label

### ISSUE THREAD

**Issue by dipernaa** [GeekyAnts/NativeBase#1653]
Is there a way to parse a different label for a selected Item for a Picker? For example, my options are red, blue, and green. When I have red selected, I want the picker to display  "red color"

react: 16.2.0
react-native: 0.53.0
native-base: 2.3.8

**Comment by SupriyaKalghatgi** [comment]
@dipernaa That is not possible to do, NativeBase Picker is replacement of React Native Picker.
React Native Picker has not come across this feature

You can do this at max,
```
<Picker
       iosHeader="Select one"
       mode="dropdown"
       selectedValue={this.state.selected1}
       onValueChange={this.onValueChange.bind(this)}
       itemStyle={{ backgroundColor: 'lightgrey', marginLeft: 0, paddingLeft: 15 }}
       itemTextStyle={{ fontSize: 18, color: 'white' }}
       textStyle={{ color: "red" }}
>
```
#338

**Comment by itspauloroberto** [comment]
i dont see why this is actually closed. none of itemStyle, itemTextStyle and textStyle worked for me.

**Comment by SupriyaKalghatgi** [comment]
https://docs.nativebase.io/Components.html#picker-text-and-item-text-styles-headref

**Comment by sridix** [comment]
you can use like this for selected value from PICKER:
<Picker.Item color={(this.state.selectedId =='id') ? 'red' : 'grey' } label={'Value'} value={'id'} />
