### ISSUE TITLE
Import Issues. Can't find variable: Title

### ISSUE THREAD

**Issue by josephthweatt** [GeekyAnts/NativeBase#1654]
## react-native, react and native-base version
react-native@0.51.0
react@16.0.0
native-base@2.3.9
## Expected behaviour
Importing Header and related components from 'native-base' should give me the Header component to use in my code.
## Actual behaviour 
Header and related components are not being imported, causing the app to produce the error message `ReferenceError: Can't find variable: Title`

This is what my IDE (Webstorm) shows me
![image](https://user-images.githubusercontent.com/11358088/37007238-9642f5e2-2099-11e8-83a0-39014a3ff402.png)
## Any other additional info which would help us debug the issue quicker.
This is my first time using native-base, maybe there are extra steps required to actually use the components? Not sure, but I did check that I had native-based included in my node modules.

**Comment by SupriyaKalghatgi** [comment]
@josephthweatt Delete `node_modules`, `yarn.lock` or `package.json`
Install `node_modules`, clean build, run

**Comment by josephthweatt** [comment]
@SupriyaKalghatgi Sorry I didn't get back to your reply. The proposed solution did not work for me, but I was able to get my IDE to recognize the components and build the code by commenting out the import lines in native-base's index.
![image](https://user-images.githubusercontent.com/11358088/37248146-fbede5be-2486-11e8-9d96-738fcc894c0e.png)

However, I do not know how I can create a permanent solution for this issue. In addition the component I was trying to display (the header) only shows as a slim rectangle in the top center. This maybe a separate question, but I was wondering if the examples being shown [here](http://docs.nativebase.io/Components.html#header-def-headref) are only a part of what is necessary to implement.

**Comment by SupriyaKalghatgi** [comment]
@josephthweatt which IDE?

**Comment by SupriyaKalghatgi** [comment]
@josephthweatt Check NativeBase-KitchenSink
