### ISSUE TITLE
Heading components not show full height of text

### ISSUE THREAD

**Issue by mrphu3074** [GeekyAnts/NativeBase#166]
Hi,
When i use H1, H2, H3 component, text don't show full height

![simulator screen shot sep 7 2016 11 01 18 am](https://cloud.githubusercontent.com/assets/1584592/18299423/f3ff5010-74ea-11e6-901b-f2282a8865be.png)

I use inspector and found this
![simulator screen shot sep 7 2016 11 01 36 am](https://cloud.githubusercontent.com/assets/1584592/18299433/01948524-74eb-11e6-9795-841b73875aa1.png)

You should add `lineHeight` to style of components or other solution.

thanks

**Comment by sankhadeeproy007** [comment]
Fixed with 0.5.8
