### ISSUE TITLE
Right element not working as expected in ListItem

### ISSUE THREAD

**Issue by shrupa** [GeekyAnts/NativeBase#1660]
react-native, react and native-base version: "native-base": "^2.3.8",
Expected behaviour: <Right><Icon name="ios-arrow-forward" /></Right> in ListItem should render the icon on right section 
Actual behaviour: Renders icon next to body text
Steps to reproduce (code snippet or screenshot)
Screenshot of emulator/device
Is the bug present in both ios and android or in any one of them?: ios
Any other additional info which would help us debug the issue quicker: Broken since native-base version update
<img width="373" alt="screen shot 2018-03-06 at 1 11 53 pm" src="https://user-images.githubusercontent.com/9002584/37058656-19b894d0-2140-11e8-97c0-eb7a1cb91f6c.png">

**Comment by shrupa** [comment]
That does not work either. For some reason, the text or icon does not render on right side. Here's the actual code-
    <ListItem>
      <Text>Region{'\n'}
        <Text note>Regional</Text>
      </Text>  
      <Right><Icon name="ios-arrow-forward" /></Right>
    </ListItem>

**Comment by akhil-geekyants** [comment]
@shrupa when using `<Right/>`, put the other component inside `<Left/>` or `<Body/>`. (`<ListItem/>` expects all three components to be present)
Modified your code

Code
```
import React, { Component } from 'react';
import { Container, Header, Content, List, ListItem, Text, Right, Icon, Body } from 'native-base';
export default class ListExample extends Component {
  render() {
    return (
      <Container>
        <Header />
        <Content>
          <List>
            <ListItem icon>
              <Body>
                <Text>Region{'\n'}
                  <Text note>Regional</Text>
                </Text>
              </Body>
              <Right>
                <Icon name="ios-arrow-forward" />
              </Right>
            </ListItem>
          </List>
        </Content>
      </Container>
    );
  }
}

```
Image

![simulator screen shot - iphone 6 - 2018-03-08 at 11 09 48](https://user-images.githubusercontent.com/27768184/37135048-77aca766-22c1-11e8-9d3a-1a0204dfe530.png)
