### ISSUE TITLE
Native base edit not updated and always rendered to the original pages

### ISSUE THREAD

**Issue by burkaslarry** [GeekyAnts/NativeBase#1663]
I have used Native Flat theme for my project .

I have edited my component pages bases on NativeBase Flat Theme
But when I run react-native run-ios, it goes to the original page of FlatTheme instead of my current page 
Would you please tell me now to do ?

**Comment by SupriyaKalghatgi** [comment]
@burkaslarry Then you can drop mail to ` strapui-support@sahusoft.com` for support
Or raise issue on its git
