### ISSUE TITLE
Support multiple toast-roots

### ISSUE THREAD

**Issue by RobertHeim** [GeekyAnts/NativeBase#1666]
## react-native, react and native-base version
react-native: 0.48.4
react: 16.0.0
native-base: 2.3.1

## Expected behaviour
rendering multiple `<Root>` components each containing a `<Toast>` should all render a scheduled toast.
E.g. this is relevant when using react-native-navigation's tab-based navigation. Here each app-screen has its on context and needs to render its own `<Root>` component.

## Actual behaviour
Only the last rendered <Root> component does show the toast, but not the other Roots. E.g. using tabs this results in the last tab showing the Toast, but not the other tabs. We would like all tabs to show the current toast.

## Steps to reproduce (code snippet or screenshot)
We use a HOC wrapping all app-screens with `Root`. However, this overrides the root-ref of `Toast`.
The problem is the (singleton) static-instance of `ToastContainer`'s `toastInstance` which is overridden when rendering a new `Root` component (s. here: https://github.com/GeekyAnts/NativeBase/blob/master/src/basic/Root.js#L15:L18 )

A solution would be to use an array of toast-instances and showing the toast within all of these instances.

Our `wrapRoot` function:
```
const wrapRoot = WrappedComponent => props => (
  <Provider store={store}>
    <StyleProvider style={getTheme(commonColor(palette))}>
      <Root> // <--- does override ToastContainer.toastInstance as a side effect
        <Container>
          <WrappedComponent {...props} /> // <-- somewhere does call Toast.show({...})
        </Container>
      </Root>
    </StyleProvider>
  </Provider>
);
```

Here, each call to `wrapRoot` instantiates a new `Root` component which ultimately overrides the `Root`-ref used by `Toast`.

## Is the bug present in both ios and android or in any one of them?
yes
## Any other additional info which would help us debug the issue quicker.
s. suggestion above. This static instance is problematic: https://github.com/GeekyAnts/NativeBase/blob/master/src/basic/Root.js#L15:L18

**Comment by gits-ram** [comment]
@RobertHeim Did you manage to work around this issue? I am facing the same problem, when using Tabs app with React-Native-Navigation. 

Native-Base team, this is a valid issue. Could this be looked into please?

**Comment by RobertHeim** [comment]
@gits-ram no, we ended up using a different lib for toasts.

**Comment by leofontes** [comment]
@RobertHeim mind sharing which one?? I'm also having problems with this Toast

**Comment by RobertHeim** [comment]
@leofontes We ended up rebuilding the whole navigation using https://github.com/wix/react-native-navigation and we build a custom Toast View around their (badly documented) notification system. We create one using the Navigator:

```
// ...
navigator.showInAppNotification({
  screen: 'OurCompany.ToastView',
  passProps: {
    text: msg,
    severity,
  },
  position: 'bottom',
  autoDismissTimerSec: duration / 1000,
});
// ...
```
and within the ToastView we put a btn to dismiss it:
```
<Button transparent onPress={() => navigator.dismissInAppNotification()}>
   // ...
</Button>
```
