### ISSUE TITLE
Card not rendering all CardItems

### ISSUE THREAD

**Issue by DianaD96** [GeekyAnts/NativeBase#167]
Hi,
I am trying to make a simple card view that has a header and 3 items as the code below shows:

```
         <Card style={styles.cardnative}>
            <CardItem header>
              <Text>Location</Text>
            </CardItem>
            <CardItem>
              <Text>{this.props.placeName}</Text>
            </CardItem>
            <CardItem>
              <Text>{this.props.placeAddress}</Text>
            </CardItem>
            <CardItem>
              <Text>{this.props.placePostalCode}</Text>
            </CardItem>
          </Card>
```
My problem is that only the header and the first cardItem gets rendered and the rest are ignored. Any idea why this might happen?

![rendered] (http://i63.tinypic.com/6qcol5.png)

**Comment by sankhadeeproy007** [comment]
![screen shot 2016-09-07 at 7 37 24 pm](https://cloud.githubusercontent.com/assets/10998047/18314878/905df05a-7532-11e6-8704-f9d7c1c30612.png)
Strange! Which version are you using. Please upgrade to the latest.

**Comment by DianaD96** [comment]
Thank you for your reply!
I am using version 0.5.8. I was playing around with it and just discovered that it works perfectly fine if it's the only cardview in my view. If I'm adding others below (as seen in the image i posted) it doesn't render them properly anymore.

**Comment by sankhadeeproy007** [comment]
I don't think so. 
![screen shot 2016-09-07 at 11 34 48 pm](https://cloud.githubusercontent.com/assets/10998047/18323118/c70f6158-7553-11e6-8e80-2d2528b54f77.png)

Please check the data type of your values. It's got to be a string if you want it inside a string.
Closing this.
