### ISSUE TITLE
No "refreshControl" Typescript definitions on "Content" component

### ISSUE THREAD

**Issue by leedongwei** [GeekyAnts/NativeBase#1674]
## react-native, react and native-base version
"native-base": "2.3.9",
"react": "^16.3.0-alpha.1",
"react-native": "0.54.0",

"types/react": "16.0.40",
"types/react-native": "0.52.16",
"typescript": "2.7.2",

You'll need to add "@" in front of "types/react" and "types/react-native", Github issues is cutting them off because it thinks it's a tag/mention

## Expected behaviour
No error when compiling Typescript

## Actual behaviour
Typescript compiler will give an error
```
error TS2339: Property 'refreshing' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Content> & Readonly<{ children?: ReactNode; }> & R...'.
```

## Steps to reproduce (code snippet or screenshot)
Save this code as a `.tsx` file
```ts
import * as React from 'react';

import { RefreshControl, Text } from 'react-native';
import { Content } from 'native-base';

interface MyListProps {
  isRefreshing: boolean;
  onRefresh: { (): void };
}

const MyList: React.SFC<MyListProps> = props => (
  <Content
    refreshing={props.isRefreshing}       // Error from Typescript
    refreshControl={                      // Error from Typescript
      <RefreshControl
        refreshing={props.isRefreshing}
        onRefresh={props.onRefresh}
      />
    }
  >
    <Text>This is my list</Text>
  </Content>
);
```

## Screenshot of emulator/device
<img width="490" alt="screen shot 2018-03-10 at 9 33 37 pm" src="https://user-images.githubusercontent.com/1748388/37242840-c37797f6-24aa-11e8-814d-c1819ca538f0.png">

## Is the bug present in both ios and android or in any one of them?
The TS compiler will show a TS2339 error, however the code will compile and run without issues on iOS/Android emulator.

## Any other additional info which would help us debug the issue quicker.
None

**Comment by SupriyaKalghatgi** [comment]
Fixed with [2.4.1](https://github.com/GeekyAnts/NativeBase/releases/tag/v2.4.1)

**Comment by darron1217** [comment]
This problem exists in `2.13.14`.

![image](https://user-images.githubusercontent.com/8064923/99389712-ca9b5c80-291a-11eb-8952-d695a41e3416.png)

It's weird that `react-native-keyboard-aware-scroll-view` package is not found.
Should I install it manually?
![image](https://user-images.githubusercontent.com/8064923/99389742-d555f180-291a-11eb-96c1-c6b800d08649.png)

**Comment by darron1217** [comment]
I guess the commit below caused problem

https://github.com/GeekyAnts/NativeBase/commit/8a3fe48adc8d1d028277b23a2f59c71dfacfcc2d#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519

**Comment by darron1217** [comment]
PR already exists!
https://github.com/GeekyAnts/NativeBase/pull/3283
