### ISSUE TITLE
Tabs  locked={true} not works

### ISSUE THREAD

**Issue by waheed25** [GeekyAnts/NativeBase#1676]
Hi i am using "native-base": "^2.3.5", and "react-native": "^0.49.5", but when i am passing 
`<Tabs initialPage={0} locked={true}>`
or 
`<Tabs initialPage={0} locked}> it didn't lock tabs tabs still swipe able. `

**Comment by akhil-geekyants** [comment]
@waheed25 checked with latest version of native-base(2.3.10). It is working fine. Can you reset the cache and try again

Sample Code
```
import React, { Component } from 'react';
import { Container, Header, Content, Tab, Tabs, Text } from 'native-base';
export default class TabsExample extends Component {
    render() {
        return (
            <Container>
                <Header hasTabs />
                <Tabs initialPage={1} locked={true}>
                    <Tab heading="Tab1">
                        <Text>Tab one</Text>
                    </Tab>
                    <Tab heading="Tab2">
                        <Text>Tab two</Text>
                    </Tab>
                    <Tab heading="Tab3">
                        <Text>Tab three</Text>
                    </Tab>
                </Tabs>
            </Container>
        );
    }
}
```
Gif

![locked](https://user-images.githubusercontent.com/27768184/37276856-034b2ff0-2609-11e8-80ca-1d4215f32ba9.gif)

**Comment by akhil-geekyants** [comment]
@waheed25 Closing this issue. If you are still facing the issue let us know.

**Comment by JonathanJumper** [comment]
This is happening to me again
I also tried defining disabled the other tabs being referenced to a prop, but when the prop changes, the disable prop does not
