### ISSUE TITLE
Input does not render correctly in StackNavigator

### ISSUE THREAD

**Issue by pdupavillon** [GeekyAnts/NativeBase#1677]
Hi there,
I've a weird display of input inside navigator.
Could you help me on this please ?
Thanks

## react-native, react and native-base version
    "native-base": "^2.3.10",
    "react-native": "0.54.1",
    "react-navigation": "^1.5.1"

## Expected behaviour
Normal input rendering
## Actual behaviour
Weird border, placeholder misplaced
## Steps to reproduce (code snippet or screenshot)
```
import React, { Component } from 'react';
import { Container,Header, Content, Input, Item } from 'native-base';
import { StackNavigator } from 'react-navigation';

class Home extends Component{
  render() {
    return(
        <Item regular>
          <Input placeholder="Render Ko" />
        </Item>
    );
  }
}
const Navigator = StackNavigator({
  Home:{screen:Home}
},{headerMode:'none'})

export default class App extends Component {
  render() {
    return (
      <Container>
        <Header/>
        <Content>
          <Item regular>
            <Input placeholder="Render Ok" />
          </Item>
          <Navigator />
        </Content>
      </Container>
    );
  }
}

```
## Screenshot of emulator/device
![simulator screen shot - iphone 6 - 2018-03-11 at 14 59 21](https://user-images.githubusercontent.com/5063976/37257957-4afada9c-253e-11e8-88b6-a09ab816c607.png)
## Is the bug present in both ios and android or in any one of them?
Present on iOS, not tested on android

**Comment by SupriyaKalghatgi** [comment]
NB: 2.3.10
RN: 0.54.0

![image](https://user-images.githubusercontent.com/13464885/37268860-0fc26c00-25ee-11e8-9bfa-b760a5faa65b.png)
