### ISSUE TITLE
ref warnings on stateless styled components

### ISSUE THREAD

**Issue by ncallaway** [GeekyAnts/NativeBase#1678]
When using `connectStyles` on a stateless component, I get a ref warning:

```
Warning: Stateless function components cannot be given refs. Attempts to access this ref will fail.

Check the render method of `Styled(BackgroundImageViewComponent)`.
```

This appears to be a bug that was in shoutem-theme (https://github.com/shoutem/theme/issues/19) and has since been fixed in that library (https://github.com/shoutem/theme/pull/20).

## react-native, react and native-base version
react-native: `0.52.0`
react: `16.2.0`
native-base: `2.3.9`
native-base-shoutem-theme: `0.2.2`

## Expected behaviour
When using `connectStyles` on a stateless component, the styles are connected without a warning.

## Actual behaviour
When using `connectStyles` on a stateless component, the React warning above is provided.

## Steps to reproduce (code snippet or screenshot)

```
export const ExampleComponent = ({children}) => (
    <View {...props}>
      {children}
    </View>
);

export const Example = connectStyle('Example.Component', styles)(ExampleComponent);
```

## Screenshot of emulator/device
(You can ignore the top warning in the screenshot below, it's unrelated to the issue. Only the second warning would be present in the minimal example case above)

![unnamed](https://user-images.githubusercontent.com/427497/37258875-e78d5dc4-253b-11e8-83cd-8d3c21d7e2a6.png)

## Is the bug present in both ios and android or in any one of them?
Only tested on Android, but as it's a react related warning I would strongly expect it to occur on both devices.

## Any other additional info which would help us debug the issue quicker.
The shoutem pull request is the quickest place I would imagine to start.

**Comment by nhannah** [comment]
I am seeing the same warning with redux-form

**Comment by mordajon** [comment]
any progress with this issue?

**Comment by KowalskiP** [comment]
+1

**Comment by Eldavid** [comment]
I am getting the same error in 2.13.8

**Comment by swiety85** [comment]
Is someone working on that?
Answare is appreciated.

**Comment by JesterDunice** [comment]
Avoid it warning with HOC:
1. Returns class Component.
`import React, { Component } from 'react';
import { connectStyle } from 'native-base';

function withNativeBaseTheme(Comp, customTheme = 'variables') {
  class Wrapped extends Component {
    render() {
      return <Comp {...this.props} />;
    }
  }
  return connectStyle(customTheme)(Wrapped);
}

export default withNativeBaseTheme;

`

2. Return functional component:
`import React, { forwardRef } from 'react';
import { connectStyle } from 'native-base';

function withNativeBaseTheme(Comp, customTheme = 'variables') {
  const Wrapped = forwardRef((props, ref) => <Comp {...props} forwardedRef={ref} />)
  return connectStyle(customTheme)(Wrapped);
}

export default withNativeBaseTheme;

`

**Comment by velidan** [comment]
@JesterDunice  Could you, please, show the real example? 
I'm trying to do it in this way
`const CustomComponentStyled = withNativeBaseTheme('theme10x.CustomComponent', styles)(CustomComponent);`

but it throws an error:
**Component Style Name must be string - when connecting Component component to style.**

**Comment by JesterDunice** [comment]
Hello, Sviatoslav!

If you want to use a HOC function withNativeBaseTheme provided by me, you
need to pass as a first argument a wrapping component and as a second
argument a field name from nativebase style object(by default 'variables').

For example, const CustomComponentStyled = withNativeBaseTheme(Component).

And in the component you will to accept to style object, function
Component({ style }) {
  const { brandPrimary } = style;

  return (
   <View style={{ flex: 1, backgroundColor: brandPrimary }} />
 );
}

Best regards,
Nikita Dudin

пт, 3 апр. 2020 г. в 13:02, Sviatoslav Barbutsa <notifications@github.com>:

**Comment by velidan** [comment]
Thank you so much! Sorry for the stupid question.

**Comment by JesterDunice** [comment]
no problem)

пт, 3 апр. 2020 г. в 13:30, Sviatoslav Barbutsa <notifications@github.com>:
