### ISSUE TITLE
Don't run scroll in 'Content' component when using the android

### ISSUE THREAD

**Issue by DJONATAS** [GeekyAnts/NativeBase#1679]
Hi Guys, I’m start with ‘react-native’ and ‘native-base’.

Today, I mounted a screen with this structure:

[https://gist.github.com/DJONATAS/310b97452c6e6532cee3faa6378cfdc8](url)
![screen shot 2018-03-11 at 23 40 06](https://user-images.githubusercontent.com/124771/37263270-1a445746-2586-11e8-9940-7446d2404682.png)

It’s ok on iOS, when I write a text in the last input the screen scroll to up, BUT :disappointed: on android the screen don’t scrool to up, then the element input hide in the back the keyboard.

How I resolve this problem ?

I’m using the native-base version 2.3.9.

**Comment by DJONATAS** [comment]
Tank's I will rebuild my screen and execute new tests. I don't understand why the action don't execute in my screen. Sorry, I will resend news

**Comment by andrei0807** [comment]
Same error.
On android, input was hided by keyboard
I tried rebuild and reinstall, but same.
Please help me
