### ISSUE TITLE
CheckBox unresponsive to user actions

### ISSUE THREAD

**Issue by RachelGreenberger** [GeekyAnts/NativeBase#168]
Please can you modify the CheckBox to respond to an onPress handler? How else is it possible to make the CheckBox respond to the user's clicking? 
Thank you!

**Comment by RachelGreenberger** [comment]
Am I supposed to wrap the CheckBox in a TouchableOpacity in order to make it clickable? Or is that something that your library should be implementing?

**Comment by sankhadeeproy007** [comment]
It should be clickable now if you are using 0.5.8
https://github.com/GeekyAnts/NativeBase/blob/master/Components/Widgets/Checkbox.js#L29

**Comment by iraycd** [comment]
@sankhadeeproy007 The toggle isn't working on 0.5.8

**Comment by java99** [comment]
+1 : not working in 0.5.8
