### ISSUE TITLE
Is it possible to switch between multiple themes?

### ISSUE THREAD

**Issue by Glendonh** [GeekyAnts/NativeBase#1683]
We're building an app that needs to be able to switch to a "Night Mode" with a darker UI. Is there any way to change themes globally without restarting the app?

I'm currently trying the following:

```
<StyleProvider style={getTheme(this.props.isNightMode ? nightColor : commonColor)}>
        <RootNavigator
          navigation={addNavigationHelpers({
            dispatch: this.props.dispatch,
            state: this.props.nav,
          })}
        />
</StyleProvider>
```
This applies the correct style based on application state the first time a component is rendered, but will not change the styling when the component is re-rendered.

Is there a better way to implement what we need?

**Comment by SupriyaKalghatgi** [comment]
#910
