### ISSUE TITLE
How to hidden Spinner component.The doc do not tell me the property which could control it

### ISSUE THREAD

**Issue by Wowgreat** [GeekyAnts/NativeBase#1696]
Hi! Thanks for trying out NativeBase!
Due to the overwhelming requests and issues/questions we ask you to add the following details with your issue.

Please check the existing open/closed issues for a possible duplicate before creating a new issue :)

Also **DO** fill out the below form to give us a better idea about your environment and help us debug it quicker. Issues without the required details will mostly be unattended to.

**Comment by akhil-geekyants** [comment]
@Wowgreat Show the Spinner only when required (like when you are loading something). Put some condition for showing/hiding the Spinner.

**Comment by Wowgreat** [comment]
@akhil-geekyants Do you mean to wrap Spinner by another label, then control the label show/hiding?In fact, I use Spinner in user login page. If both account and password user provide are correct, then into another page.If not, I hope hidden Spinner and let user re-enter his/her account and password.

**Comment by SupriyaKalghatgi** [comment]
@Wowgreat You can take reference from here
https://github.com/GeekyAnts/NativeBase-KitchenSink/blob/CRNA/src/boot/setup.js

**Comment by Wowgreat** [comment]
@SupriyaKalghatgi @akhil-geekyants 
Hey, I am a Chinese. You know lots of people want to learn English in China. But they did not have the opportunity to communicate with English speakers。

   Therefore, I hope to do some to change the status quo on the Internet.If you interest it, email me. My email is suganzhang123@gmail.com
