### ISSUE TITLE
ReactNative.createElement is deprecated

### ISSUE THREAD

**Issue by janroesner** [GeekyAnts/NativeBase#17]
I had different troubles integrating NativeBase into an existing application.

1. The docs state, NativeBase would be compatible with every ReactNative release. That seems not to be the case. Everything below 0.25.1 does not come with `ReactNativePropRegistry.js`, so that claim is misleading.

2. I found nothing about setting the theme. The components that I can make work look odd and seem not to have proper styles applied (everything comes in a blue'ish color). What's necessary to activate the (one) theme?

3. Even when building a whole new and fresh app with 0.25.1, when integrating NativeBase and rendering pretty easy stuff from the docs, I get errors like `ReactNative.createElement is deprecated...`

Am I doing sth wrong here?

**Comment by sankhadeeproy007** [comment]
1. The line where we used `ReactNativePropRegistry .js`, you can replace it with 
`import StyleSheetRegistry from 'react-native/Libraries/StyleSheet/StyleSheetRegistry';` for older versiond of RN.
We are working on providing tabular data for the compatibility of NativeBase for different version of RN. We'll probably fix that with release tags as well.
2. As of now, there's only one theme, `light.js`, where you can set your default colors and other variables. Talking about bluish components and broken styles, screenshots with code snippets would help us narrow down the problem.
3.`ReactNative.createElement is deprecated...` is probably a warning and not an error. However I know it is annoying and hopefully we'll find a fix for it very soon. Feel free to send a PR if you know what is causing this.
