### ISSUE TITLE
FAB container flexDirection code

### ISSUE THREAD

**Issue by bkDJ** [GeekyAnts/NativeBase#1707]
https://github.com/GeekyAnts/NativeBase/blob/9b01cb9e2d6a0b164e3bc3a43fba54b70d58f850/src/basic/Fab.js#L157-L159

Checking the value of a string with `||` inside another string seems suspicious. Is this accomplishing what's intended? If not, I'd recommend something like
```js
flexDirection: this.props.direction
          ? this.props.direction.match(/^(?:left|right)$/) ? "row" : "column"
          : "column",
```

**Comment by SupriyaKalghatgi** [comment]
Fixed with [2.4.1](https://github.com/GeekyAnts/NativeBase/releases/tag/v2.4.1)
