### ISSUE TITLE
Toast design flaw: no on button press

### ISSUE THREAD

**Issue by NitroGhost** [GeekyAnts/NativeBase#1708]
Toast button is not optional. 

## react-native, react and native-base version
52, 16.3, 2.3.6
## Expected behaviour
Toast button should be optional and should have a on button pressed method. The button should *not* be firing the onClose method which is the only way to do something. Also, there's zero documentation on the onClose method on nativebase.io
## Actual behaviour
if you want to have something happen with the button, the only way to do this is to pass onClose, but onClose is also fired when the duration ends. What the hell. This means that if the user doesn't want to do the action provided with the toast, it'll go ahead and do it anyway. amazing.

Why should this be optional? This should be optional because the user should be in control of the toast (which is actually a snack btw, not a toast), meaning they should be allowed to ignore it.

Take for instance you have a way to delete something, but once they have been deleted, you want to give the option to undo this. If I were to do this currently with the current toast implementation and pass in onClose, once that duration ends, onClose is fired and WHOA THERE NELLY, WHY ARE YOU UNDOING MY DELETE.

## Steps to reproduce (code snippet or screenshot)
pass onClose method to the toast, first wait until the toast dismisses itself and see if your on close method fired. now make the toast appear again but this time press the button.
## Is the bug present in both ios and android or in any one of them?
of course

**Comment by akhil-geekyants** [comment]
@NitroGhost In Toast, button is optional. If you don't want button to appear, don't add buttonText.  We will be adding onClose to docs.

**Comment by NitroGhost** [comment]
the onClose method is the problem here because it's also called when the
toast dismisses itself when the duration comes to an end. it's not user
driven

**Comment by danieloprado** [comment]
@NitroGhost Take a look at the pull request. I added a reason that onClosed was called.

**Comment by NitroGhost** [comment]
@danieloprado good enough 👍

**Comment by bamaboy** [comment]
@akhil-geekyants  It seems that @danieloprado solved the problem. Any idea when his PR would be merged?

**Comment by SupriyaKalghatgi** [comment]
Released with [2.5.0](https://github.com/GeekyAnts/NativeBase/tree/v2.5.0)

**Comment by barrymichaeldoyle** [comment]
Hey there, I don't think this issue should be closed.

I'm looking at 2.6.0 and there's still no way to add an on button press function to the toast. Eg. I want to add an UNDO button to the toast and I can't implement that because if I used `onClose` that would mean that UNDO always gets called, regardless of whether or not the user clicks UNDO.

Another ncie to have feature would be the option to have 2 toast buttons (eg. UNDO and CLOSE buttons would be great, where CLOSE did the general close action and UNDO did my custom UNOD action.)

**Comment by NitroGhost** [comment]
@barrymichaeldoyle take a look at the pull request above. it has a way of knowing whether or not it was user clicked, or self dismissed. I haven't personally tried it because since raising this issue, I implemented my own snackbar that gets around all the issues I face with it

**Comment by Nerogee** [comment]
I totally agree that having custom button on Toast is a desired feature. My situation is Toast will show up if there is coming message. But I want to show the message reply screen only when use tap the Toast. Otherwise, just let it fade away.
