### ISSUE TITLE
Truncate Text in Right not working

### ISSUE THREAD

**Issue by jarrx** [GeekyAnts/NativeBase#1709]
## react-native, react and native-base version
react-native: 0.49.3
react: 16.0.0-beta.5
native-base: ^2.3.5
## Expected behaviour
I'm trying to truncate text in a Right component in a ListItem. The text should get truncated when it reaches the Body component.
## Actual behaviour
The Right component pushes on the Body component and does not get truncated until the text reaches the left most side of the screen.
## Steps to reproduce (code snippet or screenshot)
```

        <ListItem
          icon
          button
          onPress={() => {}}
        >
          <Body>
            <Text>Repeat</Text>
          </Body>
        <Right>
            <Text note numberOfLines={1}>Lorem ipsum dolor sit amet, consectetur ad</Text>
        </Right>
        </ListItem>

```
## Screenshot of emulator/device
![skarmavbild 2018-03-20 kl 18 52 50](https://user-images.githubusercontent.com/31743687/37675236-0f410ae2-2c75-11e8-9a93-b0b1ab7719b4.png)
## Is the bug present in both ios and android or in any one of them?
iOS
Android?

**Comment by akhil-geekyants** [comment]
@jarrx  can you try this
```
<ListItem icon>
  <Left>
    <Text>Repeat</Text>
  </Left>
  <Body>
    <Text note numberOfLines={1}>Lorem ipsum dolor sit amet, consectetur ad</Text>
  </Body>
  <Right>
    <Icon name="arrow-forward" />
  </Right>
</ListItem>
```
Screenshot

![screen shot 2018-03-21 at 12 56 43 pm](https://user-images.githubusercontent.com/27768184/37698189-688fd082-2d07-11e8-9d57-50b113d2193f.png)

**Comment by jarrx** [comment]
@akhil-geekyants 
It worked and after some styling I could make the list item look the same way as it did before, (right title further to the left, main title further to right etc).
A problem with this solution though is that it does not truncate subtitles as expected. It behaves the same way as it did before so I solved this by simply using the same ListItem setup as before when I have subtitles, and this setup when wanting the right title to truncate.
Thanks for the help.
