### ISSUE TITLE
nativebas radiobutton not show 

### ISSUE THREAD

**Issue by depapeep** [GeekyAnts/NativeBase#171]
Hi everyone please help me . I need to use radio buttons for my app . I follow from this web
http://nativebase.io/docs/v0.5.7/components#radioButton but it not work (develop in window 10) it not show radiobuttons but show textInput 

react native version 0.32.0 
native-base version  0.5.8

please help me and sorry for my english

**Comment by sankhadeeproy007** [comment]
Are you sure about the versions?
![screen shot 2016-09-09 at 1 02 27 am](https://cloud.githubusercontent.com/assets/10998047/18363781/220fcec8-7629-11e6-993a-2e5bbc240fee.png)
Seems to work pretty fine for me.

**Comment by depapeep** [comment]
I'm not sure but i check in node_modules/react-native/package.json  is 

 "name": "react-native",
  "version": "0.32.0",
  "description": "A framework for building native apps using React",
  "license": "BSD-3-Clause",

and node_modules/react-base/package.json  is 

"name": "native-base",
  "description": "The missing piece of React Native",
  "keywords": [
    "android",
    "ios",
    "react",
    "native",
    "react-native",
    "native-modules",
    "react-component",
    "navbar",
    "packager",
    "rnpm"
  ],
  "version": "0.5.8"

Could you tell me what your versions ? 

I forgot to say i develop in window 10 and use geniemotion to simulate android app

**Comment by sankhadeeproy007** [comment]
Can you try in another environment? We've tried that again and it works great.

**Comment by AlanVerbner** [comment]
@depapeep I'm not sure what's the cause is but we were experiencing the same problem as you. What we did (and seemed to solved the issue) was to run: 

1. `react-native link` 
2. `cd ./android/gradlew clean`
3. `react-native run-android`
4. `react-native start`

Basically, link the code and clean. I don't know if it was a link problem or just cleaning solved it.

Hope that helps!



`
