### ISSUE TITLE
Toast with long text hidden button

### ISSUE THREAD

**Issue by danieloprado** [GeekyAnts/NativeBase#1713]
## react-native, react and native-base version
react: 16.3.0-alpha.1
react-native: 0.54.2
native-base: 2.3.10

## Expected behaviour / Actual behaviour
When call a toast notification with long text the button disappears 

## Steps to reproduce (code snippet or screenshot)
```js
Toast.show({
    text: 'Não conseguimos se comunicar com o servidor',
    position: 'bottom',
    buttonText: 'Ok',
    duration: 1000
  });
```

## Screenshot of emulator/device
![image](https://user-images.githubusercontent.com/7683575/37708971-716b15ce-2ce7-11e8-90bc-a37b558e40ba.png)

![image](https://user-images.githubusercontent.com/7683575/37708961-634a0a18-2ce7-11e8-861f-4d8a4ee6354e.png)

## Is the bug present in both ios and android or in any one of them?
Both

**Comment by akhil-geekyants** [comment]
@danieloprado tried your code with same versions. It is working fine. Attaching a gif.

Gif

![toast](https://user-images.githubusercontent.com/27768184/37753250-f8da8a82-2dc1-11e8-94f7-a10497690b14.gif)

**Comment by danieloprado** [comment]
My native-base-theme's folder is outdated, I'll update it.
Thanks you @akhil-geekyants for your response so quickly!
