### ISSUE TITLE
Extra space at the top of the screen

### ISSUE THREAD

**Issue by MohamadKh75** [GeekyAnts/NativeBase#1715]
Hi! Thanks for trying out NativeBase!
Due to the overwhelming requests and issues/questions we ask you to add the following details with your issue.

Please check the existing open/closed issues for a possible duplicate before creating a new issue :)

Also **DO** fill out the below form to give us a better idea about your environment and help us debug it quicker. Issues without the required details will mostly be unattended to.

## react-native-cli
2.0.1
## react-native
0.54.0
## Expected behaviour:
Normal header, content and footer!
## Actual behaviour
Extra space at the top of the screen :neutral_face: 
## Steps to reproduce (code snippet or screenshot):
This is [DOCS example](https://docs.nativebase.io/Components.html#anatomy-headref) 
```
import React, { Component } from 'react';
import { Container, Header, Title, Content, Footer, FooterTab, Button, Left, Right, Body, Icon, Text } from 'native-base';
export default class AnatomyExample extends Component {
  render() {
    return (
      <Container>
        <Header>
          <Left>
            <Button transparent>
              <Icon name='menu' />
            </Button>
          </Left>
          <Body>
            <Title>Header</Title>
          </Body>
          <Right />
        </Header>
        <Content>
          <Text>
            This is Content Section
          </Text>
        </Content>
        <Footer>
          <FooterTab>
            <Button full>
              <Text>Footer</Text>
            </Button>
          </FooterTab>
        </Footer>
      </Container>
    );
  }
}
```
## Screenshot of emulator/device
[Screenshot](http://uupload.ir/files/ks98_photo_2018-03-22_06-31-03.jpg)
## Is the bug present in both ios and android or in any one of them?
i've got android, galaxy s7 edge, android 7.0
## Any other additional info which would help us debug the issue quicker.
Latest version of native base is installed!

**Comment by akhil-geekyants** [comment]
@MohamadKh75 Checked the example. It is working fine. If you using react-navigation, try setting the header to null.

**Comment by MohamadKh75** [comment]
@akhil-geekyants Thanks!
```
static navigationOptions = {
  header: null,
};
```

solved the problem!
