### ISSUE TITLE
Getting warnings after updated to react-native 0.54

### ISSUE THREAD

**Issue by ashokkumar88** [GeekyAnts/NativeBase#1717]
I updated the react native version to 0.54. After update i m getting multiple warning like below:

![capture](https://user-images.githubusercontent.com/11060139/37811305-5ab73896-2e7f-11e8-8a74-7e1ff6b264f2.PNG)
![capture2](https://user-images.githubusercontent.com/11060139/37811306-5aeeca0e-2e7f-11e8-8b60-ca8e2f0c986b.PNG)
![capture1](https://user-images.githubusercontent.com/11060139/37811308-5b1e8ec4-2e7f-11e8-9bc1-f43be3e41ffd.PNG)

**Comment by SupriyaKalghatgi** [comment]
#1665
