### ISSUE TITLE
collapsible or accordion component

### ISSUE THREAD

**Issue by ilkerceng** [GeekyAnts/NativeBase#1721]
Hi dear community, is it possible to create accordion or collapsible component with nativebase? I couldn't see any component in the [docs](https://docs.nativebase.io/Components.html#Components) and in [nativebase-kitchen-sink](https://github.com/GeekyAnts/NativeBase-KitchenSink)

**Comment by SupriyaKalghatgi** [comment]
@ilkerceng We will implement this soon

Subscribe on https://nativebase.io/ for updates

**Comment by ilkerceng** [comment]
I will, thank you so much @SupriyaKalghatgi

**Comment by SupriyaKalghatgi** [comment]
Available on `development`

**Comment by SupriyaKalghatgi** [comment]
Released with [2.5.0](https://github.com/GeekyAnts/NativeBase/tree/v2.5.0)

**Comment by davekedar** [comment]
Is it possible to keep the custom key for Accordion instead of "title" and "description"?

**Comment by samuelcastro** [comment]
How to create a collapsible List element?

**Comment by ilkerceng** [comment]
@samuelcastro there is an example [here](https://docs.nativebase.io/Components.html#accordion-def-headref)

**Comment by diegomachado7** [comment]
Is it possible to not collect automatically?

**Comment by theshubhagrwl** [comment]
Is this still available in the latest version? I can't find and collapsable or accordion in the docs
