### ISSUE TITLE
Problem when using native-base after android-build

### ISSUE THREAD

**Issue by roykoren111** [GeekyAnts/NativeBase#1723]
Hello,
I have a problem with my app when using native-base.
My app works well on Expo (mobile), but after making android build (with the command 'react-native run-android') I just get the red screen as described below. It means that the build succees but then I get an error.
**Notice that in app which does NOT consists any native-base component, it works well in both Expo and android build.**

## react-native, react and native-base version
react-native: 0.52.0 
react: 16.2.0
native base: 2.3.10

## Expected behaviour
Running after build on android.

## Actual behaviour
Error: The Expo SDK requires Expo to run. It appears the native Expo modules are unavailable and this code is not running on Expo. Visit https://docs.expo.io to learn more about developing an Expo project.

## Steps to reproduce (code snippet or screenshot)
import React from 'react';
import { StyleSheet, Text, View } from 'react-native';
import { Container } from 'native-base'; // HERE is the problem (if delete this line, it will work on android build)

export default class App extends React.Component {
  render() {
    return (
      <View style={styles.container}>
        <Text>Open up App.js to start working on your app!</Text>
        <Text>Changes you make will automatically reload.</Text>
        <Text>Shake your phone to open the developer menu.</Text>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});

## Screenshot of emulator/device
![screenshot_2018-03-24-11-11-59-764_com beta](https://user-images.githubusercontent.com/29411287/37867352-1eb5c2b6-2fa8-11e8-8613-ce47e2b32971.png)

## Is the bug present in both ios and android or in any one of them?
android (was not checked on ios device).

## Any other additional info which would help us debug the issue quicker.
This problem happens ONLY when importing from native-base (otherwise it works well in both expo and android-build).

**Comment by akhil-geekyants** [comment]
@roykoren111 checked this. It is working fine for me. Can you try removing the node modules, lock files  and do `npm install`. 

Read more about using `native-base` with CRNA [here](http://docs.nativebase.io/docs/GetStarted.html)

**Comment by roykoren111** [comment]
Thank you for your response, but still not working for me.

**Comment by SupriyaKalghatgi** [comment]
@roykoren111 Delete node modules and lock files and do `yarn`

**Comment by SupriyaKalghatgi** [comment]
@roykoren111 you can check NativeBase-KitchenSink which has same versions that you mentioned

**Comment by SupriyaKalghatgi** [comment]
Here is the working repo https://github.com/GeekyAnts/NativeBase-KitchenSink/tree/CRNA

**Comment by badarshahzad** [comment]
facing the same error screen mentioned by @roykoren111

**Comment by SupriyaKalghatgi** [comment]
share package.json and app.json

**Comment by badarshahzad** [comment]
`package.json`
```

{
  "name": "berlinfoods",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest",
    "eject": "react-native-scripts eject",
    "android": "react-native-scripts android",
    "ios": "react-native-scripts ios"
  },
  "dependencies": {
    "babel-preset-react-native": "^2.1.0",
    "es6-symbol": "^3.1.1",
    "expo": "^27.0.0",
    "firebase": "^5.3.1",
    "mobx": "^4.3.1",
    "mobx-react": "^5.2.3",
    "native-base": "^2.7.2",
    "prop-types": "^15.6.2",
    "react": "16.4.1",
    "react-native": "0.55.2",
    "react-native-elements": "^0.19.1",
    "react-native-keyboard-spacer": "^0.4.1",
    "react-native-phone-input": "^0.2.1",
    "react-native-radio-buttons": "^1.0.0",
    "react-native-star-rating": "^1.0.9",
    "react-navigation": "^2.9.3",
    "react-phone-number-input": "^2.2.1"
  },
  "devDependencies": {
    "babel-jest": "23.4.2",
    "babel-plugin-transform-decorators-legacy": "^1.3.5",
    "jest": "23.5.0",
    "jest-expo": "~27.0.0",
    "react-native-scripts": "1.14.0",
    "react-test-renderer": "16.3.1"
  },
  "jest": {
    "preset": "react-native"
  }
}

```
`app.json`
```
{
  "name": "berlinfoods",
  "displayName": "berlinfoods"
}

```

**Comment by SupriyaKalghatgi** [comment]
I tried Expo 27 on snack, worked fine
https://snack.expo.io/Hy2cP4xUX

**Comment by badarshahzad** [comment]
The application is working fine when I run with this `npm start`. Now I created another project in different folder and `react-native init berlinfoods` and made all changes which is required for android as mentioned [here](https://wix.github.io/react-native-navigation/v2/#/docs/Installing?id=android). I followed this [one] (https://github.com/react-community/create-react-native-app/issues/401) also and many others.

**Comment by badarshahzad** [comment]
The Welcome screen snippet code works fine but when I replace my `App.js ` with actual real code its show me the above mentioned screen.
App.js 

```
// The below sample is WOrking for applicaton
/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 *
 * @format
 * @flow
 */

import React, {Component} from 'react';
import {Platform, StyleSheet, Text, View} from 'react-native';

const instructions = Platform.select({
  ios: 'Press Cmd+R to reload,\n' + 'Cmd+D or shake for dev menu',
  android:
    'Double tap R on your keyboard to reload,\n' +
    'Shake or press menu button for dev menu',
});

type Props = {};
export default class App extends Component<Props> {
  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>Welcome dsfasd to React Native!</Text>
        <Text style={styles.instructions}>To get started, edit App.js</Text>
        <Text style={styles.instructions}>{instructions}</Text>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});
```

App.js (this is the actual I want to run)

```
import React, { Component } from "react";
import { createStackNavigator } from "react-navigation";
import { Font } from "expo";
import { StyleSheet, Text, View, KeyboardAvoidingView } from "react-native";
import { Provider,inject } from "mobx-react";
import SignUpInputScreen from "./src/screens/SignUpInputScreen";
import Splash from './src/screens/Splash'
import SignUpScreen from './src/screens/SignUpScreen'
import MainScreen from './src/screens/MainScreen'
import DishDetails from './src/screens/DishDetails'
import PlaceOrderScreen from "./src/screens/PlaceOrderScreen";
import ConfirmOrderScreen from "./src/screens/ConfirmOrderScreen";
import RatingFoodScreen from "./src/screens/RatingFoodScreen";
import CounterStore from "./src/stores/CounterStore";


const Navigation = createStackNavigator(
   {
     
     Splash: Splash,
     SignUp: SignUpScreen,
     SignUpInput: SignUpInputScreen,
     MainScreen:MainScreen,
     DishDetails:DishDetails,
     itemDetails:PlaceOrderScreen,
     ConfirmOrderScreen:ConfirmOrderScreen,
   },
 );


const counterStore = new CounterStore();

export default class App extends Component {
  constructor(props) {
    super(props);
    this.state = { loading: true };
  }

  async componentWillMount() {
    await Font.loadAsync({
      "century-gothic": require("./src/assets/fonts/CenturyGothic.ttf"),
      "century-gothic-bold": require("./src/assets/fonts/CenturyGothicBold.ttf")
    });
    this.setState({ loading: false });
  }

  render() {
    if (this.state.loading) {
      //first load the text style then to render its necessary
      return (
        <View style={styles.container}>
          <Text
            style={{
              fontSize: 36,
              alignContent: "center",
              alignItems: "center"
            }}
          >
            loading .......
          </Text>
        </View>
      );
    }
    return (
     <Provider counterStore={counterStore}>
       <Navigation/>
       {/* <MainView/> */}
     </Provider>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    flexDirection: "column"
  }
});


// Separate Screen Testing
// @inject("counterStore")
class MainView extends Component {
  render() {
    return (
      <View style={styles.container}>
      {/* <RootStack /> */}

      {/* <SignUpScreen/> */}
      {/* <SignInputScreen/> */}

      {/* Done */}
      {/* <CheckOutScreen/>  */}

      {/* Done: Rate the food */}
      {/* <RatingFoodScreen/>   */}

      {/* Done is king of contact and devlivery addres to confirm order to send you*/}
      {/* <ConfirmOrderScreen/>  */}

      {/* Done */}
      <PlaceOrderScreen/>
    </View>
    );
  }
}
```
