### ISSUE TITLE
Header buttons not vertically aligned with header title 

### ISSUE THREAD

**Issue by andidev** [GeekyAnts/NativeBase#1724]
## react-native, react and native-base version
```json
  "dependencies": {
    "native-base": "2.3.10",
    "react": "^16.3.0-alpha.1",
    "react-native": "0.54.2"
  }
```

## Expected behaviour
Buttons in header should be aligned with header title
![skarmavbild 2018-03-26 kl 00 11 46](https://user-images.githubusercontent.com/571389/37880555-ad2bea06-308a-11e8-858c-2bf779b5201b.png)

Setting icon paddingTop and marginTop to 0 seems to fix the issue:
```jsx
<Icon name='arrow-back' style={{
    paddingTop:0,
    marginTop:0,
}} />
```

## Actual behaviour
Buttons in header is not vertically aligned with header title
![skarmavbild 2018-03-26 kl 00 12 26](https://user-images.githubusercontent.com/571389/37880546-7751acb8-308a-11e8-91c4-8336819a210a.png)

## Steps to reproduce (code snippet or screenshot)
```jsx
            <Container>
                <Header>
                    <Left>
                        <Button transparent>
                            <Icon name='arrow-back' />
                        </Button>
                    </Left>
                    <Body>
                        <Title>The Title</Title>
                    </Body>
                    <Right />
                </Header>
                <Content>
                </Content>
            </Container>
```
## Is the bug present in both ios and android or in any one of them?
Only exists in ios. Android seems to look ok.

**Comment by dmitriyermolin** [comment]
Try to adjust lineHeight

**Comment by SupriyaKalghatgi** [comment]
Fixed with [2.4.2](https://github.com/GeekyAnts/NativeBase/releases/tag/v2.4.2)

**Comment by andidev** [comment]
This is by the way not fixed.

**Comment by SupriyaKalghatgi** [comment]
@andidev Refactoring Header component

**Comment by jordan-mcrae** [comment]
+1
