### ISSUE TITLE
Icomoon custom icons for IconNB 

### ISSUE THREAD

**Issue by bjartebore** [GeekyAnts/NativeBase#1732]
Hi, and thanks for a great library :)

It would be great if IconNB could use custom icons as well as all the built in icons. react-native-vector-icons has a factory method for creating icon sets from icomoon. 

## react-native, react and native-base version
react-native: 0.54.0
native-base: 2.3.9
## Expected behaviour
I would like to use the IconNB as this <IconNB name="my-cool-icon" type="Icomoon" iconFactory={createIconSetFromIcoMoon(selection)}  />
## Actual behaviour
Not implemented
## Steps to reproduce (code snippet or screenshot)
not applicable
## Screenshot of emulator/device
not applicable
## Is the bug present in both ios and android or in any one of them?
not a bug, just a feature request
## Any other additional info which would help us debug the issue quicker.
I will make a PR for this

**Comment by SupriyaKalghatgi** [comment]
@bjartebore Did you check this?

![image](https://user-images.githubusercontent.com/13464885/37951893-a8249666-31bb-11e8-91f2-7719d460f369.png)

**Comment by bjartebore** [comment]
@SupriyaKalghatgi sorry, but I fail to se the relevance, what I want is the possibility to use custom fonts generated from https://icomoon.io/

**Comment by SupriyaKalghatgi** [comment]
@bjartebore you can fork NativeBase and try adding `Icomoon`
We dont have plans to do this
