### ISSUE TITLE
Missing "src/theme/components" folder in yarn repository

### ISSUE THREAD

**Issue by phwb** [GeekyAnts/NativeBase#1735]
Hi! I don't know is it your error or yarn cache but after today update i have missing `src/theme/components` folder. On [yarnpkg.com](https://yarnpkg.com/en/package/native-base?files) in files section this directory absent too.

**Comment by SupriyaKalghatgi** [comment]
@phwb Yes, we are looking into it
Kindly follow #1734

**Comment by ReactDeveloperTwoQsoft** [comment]
Here my solution: 
    "native-base": "~2.3.0",
    "prop-types": "^15.6.1",
    "react": "16.3.0-alpha.1",
    "react-native": "0.51.0"
delete nativebase from node_module , yarn install and react-native link native-base
hard code ~ replace for ^ and reduce version => ~2.3.0
