### ISSUE TITLE
FlatList inside Content item invokes onEndReached infinite times

### ISSUE THREAD

**Issue by AndroConsis** [GeekyAnts/NativeBase#1736]
Steps to Reproduce: 
```
import {  Container,  Header,  Title,    Content,  Card,  CardItem,  Thumbnail,  Text,  Button,  Icon,  Left,  Body,  Right,  Spinner,  Badge} from 'native-base';

render() {
    return (
      <Container>
        <Header>
          <Body>
            <Title>Header</Title>
          </Body>
          <Right><Text note>{this.state.imageList.length}</Text></Right>
        </Header>
          <Content>
           {this.state.loading ? <Spinner />: 
            <FlatList
              data={this.state.imageList}
              renderItem={this._renderItem.bind(this)}
              keyExtractor={(item, index) => index.toString()}
              onEndReached={this.onEndReached.bind(this)}
              ListFooterComponent={() => { return <Spinner small/> }}
              onEndReachedThreshold={0.5}
              />
          } 
          </Content>
      </Container>
```

while rendering the above JSX, I was facing the issue that `onEndReached `was getting called again and again after an interval when setting onEndReachedThreshold greater than 0.
Ultimately I found out that problem got solved by removing `Content` tag and replacing it with `<View style={{flex: 1}}`

Please look into this.

**Comment by akhil-geekyants** [comment]
@AndroConsis See this issue https://github.com/facebook/react-native/issues/15356

**Comment by ashokkumar88** [comment]
Replace the <Content> component with <View> and write the value for `onEndReached` as below
`onEndReached = {() => this.onEndReached()}`. 
```
render() {
    return (
      <Container>
        <Header>
          <Body>
            <Title>Header</Title>
          </Body>
          <Right><Text note>{this.state.imageList.length}</Text></Right>
        </Header>
          <View style={{padding:10}}>
           {this.state.loading ? <Spinner />: 
            <FlatList
              data={this.state.imageList}
              renderItem={this._renderItem.bind(this)}
              keyExtractor={(item, index) => index.toString()}
              onEndReached={() => this.onEndReached()}
              ListFooterComponent={() => { return <Spinner small/> }}
              onEndReachedThreshold={0.5}
              />
          } 
          </View>
      </Container>
```

**Comment by ShinsukeWatanabe** [comment]
```
<Content
  style={{flex: 1}}
  contentContainerStyle={{flex: 1}} // important!
>
...
```

**Comment by ikeliec** [comment]
> 
> 
> Steps to Reproduce:
> 
> ```
> import {  Container,  Header,  Title,    Content,  Card,  CardItem,  Thumbnail,  Text,  Button,  Icon,  Left,  Body,  Right,  Spinner,  Badge} from 'native-base';
> 
> render() {
>     return (
>       <Container>
>         <Header>
>           <Body>
>             <Title>Header</Title>
>           </Body>
>           <Right><Text note>{this.state.imageList.length}</Text></Right>
>         </Header>
>           <Content>
>            {this.state.loading ? <Spinner />: 
>             <FlatList
>               data={this.state.imageList}
>               renderItem={this._renderItem.bind(this)}
>               keyExtractor={(item, index) => index.toString()}
>               onEndReached={this.onEndReached.bind(this)}
>               ListFooterComponent={() => { return <Spinner small/> }}
>               onEndReachedThreshold={0.5}
>               />
>           } 
>           </Content>
>       </Container>
> ```
> 
> while rendering the above JSX, I was facing the issue that `onEndReached `was getting called again and again after an interval when setting onEndReachedThreshold greater than 0.
> Ultimately I found out that problem got solved by removing `Content` tag and replacing it with `<View style={{flex: 1}}`
> 
> Please look into this.

This fixed mine. Thanks a bunch :)
