### ISSUE TITLE
Input appears too slow

### ISSUE THREAD

**Issue by teamhide** [GeekyAnts/NativeBase#1741]
When I load page that contains `<InputGroup> and <Input>`, It's visible is too slow.

![moveinput](https://user-images.githubusercontent.com/8403122/38162462-b2786840-351c-11e8-98e4-5d49d46ccc76.gif)

Additionally, size is not fixed and placeholder also appears slow.

How can I solve this issue?

I just used StackNavigator and native-base version is `2.3.10`

[Board.js]
```
onPress={() => this.props.navigation.navigate('BoardDetail',
{
      articleNo: 1
}
```

[BoardDetail.js]
```
import React, { Component } from 'react';
import { Container, Header, Left, Body, Right, Button, Content, Title, View, Icon, Text, Input, InputGroup } from 'native-base';
import SideBar from './SideBar';
import { StyleSheet } from 'react-native';

export default class BoardDetail extends Component {
  constructor(props) {
    super(props);
  }
  render() {
    return (
      <Container>
        <Header style={{backgroundColor: '#3D6DCC'}}>
          <Left>
            <Button
              transparent
              onPress={() => this.props.navigation.goBack()}>
              <Icon name="ios-arrow-back" style={{color: 'black'}}/>
            </Button>
          </Left>
          <Title style={{marginTop: 15}}>Comment</Title>
          <Right>
          </Right>
        </Header>
        <Content>
          <Text>123</Text>
        </Content>
        <Content>
          <InputGroup borderType='regular' >
            <Input multiline placeholder='INPUT INPUT'/>
          </InputGroup>
        </Content>
      </Container>
    );
  }
}
```

**Comment by SupriyaKalghatgi** [comment]
`InputGroup` is deprecated
Check docs https://docs.nativebase.io/Components.html#Form

**Comment by kevinvugts** [comment]
I would like to re-open this issue.

The input fields appear to be slow when typing multiple sentences in the text input.
It looks like it's removing characters and missing a few as well. 

Sometimes it's unresponsive.
What is the issue of this?
