### ISSUE TITLE
[bug] small button with icon on iOS

### ISSUE THREAD

**Issue by garan82** [GeekyAnts/NativeBase#1743]
Env: native base 2.4.1
Expo: 26.0.0
React native: 0.54
Reactjs: 16.3.0-alpha.1

Repo: create a small button with Icon on iOS
Issue: icon is cut off, button works fine on Android

**Comment by SupriyaKalghatgi** [comment]
Fixed with [2.4.2](https://github.com/GeekyAnts/NativeBase/releases/tag/v2.4.2)
