### ISSUE TITLE
Tooltips

### ISSUE THREAD

**Issue by iCueto** [GeekyAnts/NativeBase#1744]
Hey, community... I've looking for a tooltip component, and there are not a component like that!

Would be cool have a component like that. Thanks!!

[https://material.io/guidelines/components/tooltips.html#tooltips-usage](https://material.io/guidelines/components/tooltips.html)

**Comment by SupriyaKalghatgi** [comment]
#38

**Comment by waqaramjad** [comment]
i am also looking for tooltips in native base but there is no solution for that

**Comment by mdanka** [comment]
+1

**Comment by gauravsbagul** [comment]
@iCueto  @waqaramjad  you can build your own ToolTip component
by Opening Modal(transperent) and with TolTip UI with text (Tip) on exact position of onPress of any component and close the modal onPress of anywhere on screen(Modal) or setTimeOut to close the Modal.
