### ISSUE TITLE
Picker selected item label is cropped after selecting an item

### ISSUE THREAD

**Issue by alexiss03** [GeekyAnts/NativeBase#1745]
Hi, I integrated Picker in my existing application and I found this bug that whenever the user selects an item, the selected item label is always cut at the top. Not sure if I'm missing something or misused the component.

## react-native, react and native-base version
react-native:  0.52.3
native-base: 2.3.9

## Expected behaviour
Label for the selected item is not cropped

## Actual behaviour
Label for the selected item in iOS is cropped by the top

## Steps to reproduce (code snippet or screenshot)
```
<Picker style={styles.picker}
        textStyle={styles.value}
        iosHeader="List"
        mode="dropdown"
        placeholder={this.props.value}
        selectedValue={this.state.selected}
        onValueChange={this.onValueChange.bind(this)}>
    {
      this.props.itemList.map((item, key)=>(
      <Picker.Item style={styles.pickerItem} label={item} value={item} key={key} />
      ))
    }
</Picker>
```

## Screenshot of emulator/device
Pre-selecting an item
![fullsizerender 4](https://user-images.githubusercontent.com/3050502/38179160-61063906-3652-11e8-8b58-fd32d52b3537.jpg)
Selected an item
![fullsizerender 5](https://user-images.githubusercontent.com/3050502/38179161-61756baa-3652-11e8-9d24-8ed050221d7d.jpg)

## Is the bug present in both ios and android or in any one of them?
Only in iOS 

## Any other additional info which would help us debug the issue quicker.
Here's my style for the picker
```
picker: {
    ...Platform.select({
      ios: {
        marginLeft: -15,
        marginTop: -15,
        marginVertical: 5,
      },
   })
}
```

**Comment by akhil-geekyants** [comment]
@alexiss03 can you post more code( the whole card code).

**Comment by alexiss03** [comment]
@akhil-geekyants Here's the code for the card.

```
<Card style={styles.container}>
  <CardItem style={styles.content}>
    <Body>
        <Text style={styles.title}>{this.props.title}</Text>
        <Grid>
            <Col size={1}>
                <View>
                <Picker style={styles.picker}
                        textStyle={styles.value}
                        iosHeader={this.props.title}
                        mode="dropdown"
                        placeholder={this.props.value}
                        selectedValue={this.state.selected}
                        onValueChange={this.onValueChange.bind(this)}>
                    {
                      this.props.itemList.map((item, key)=>(
                      <Picker.Item label={item} value={item} key={key} />
                      ))
                    }
                </Picker>
              </View>
            </Col>
            <Col size={0.5}>
              <Image style={styles.image} source={require('root/public/images/arrow-down.png')}/>
            </Col>
        </Grid>
    </Body>
  </CardItem>
</Card>
```

**Comment by akhil-geekyants** [comment]
@alexiss03 if you are making any change to the fontSize, change the lineHeight accordingly.

**Comment by alexiss03** [comment]
@akhil-geekyants Setting the lineHeight fixes this issue. Thanks! 

Closing this now.
