### ISSUE TITLE
keyboardShouldPersistTaps missing from typings

### ISSUE THREAD

**Issue by Slessi** [GeekyAnts/NativeBase#1747]
## react-native, react and native-base version
- RN `0.54.0`
- R `16.3.0`
- NB `2.4.1`
## Expected behaviour
Typings present
## Actual behaviour
Typings not present
## Steps to reproduce (code snippet or screenshot)
```jsx
<Tabs contentProps={{ keyboardShouldPersistTaps: "handled" }}>
    {tabComponents}
</Tabs>
```

> Property 'contentProps' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Tabs> & Readonly<{ children?: ReactNode; }> & Read...'.
## Screenshot of emulator/device
n/a
## Is the bug present in both ios and android or in any one of them?
Yes
## Any other additional info which would help us debug the issue quicker.

Props added in #1410 but not added to `index.d.ts`

Can be temporarily fixed by adding below typings file to project
```ts
declare module 'native-base' {
    namespace NativeBase {
        interface Content {
            keyboardShouldPersistTaps?: string;
        }

        interface Tabs {
	    contentProps?: NativeBase.Content;
        }
    }
}
```

**Comment by SupriyaKalghatgi** [comment]
Fixed with [2.4.2](https://github.com/GeekyAnts/NativeBase/releases/tag/v2.4.2)
