### ISSUE TITLE
Input doesn't use the inputColorPlaceholder provided by the custom theme

### ISSUE THREAD

**Issue by muratakbal** [GeekyAnts/NativeBase#1750]
## react-native, react and native-base version
react-native: 0.50.3
react: 16.0.0
native-base: 2.4.1

## Expected behaviour
When a custom theme is used, the placeholder color of input should be used from the custom theme's
`inputColorPlaceholder`.

## Actual behaviour
Since the `Input` component doesn't get the variables from the theme in the context, it uses default theme's `inputColorPlaceholder `.

## Steps to reproduce (code snippet or screenshot)
see: https://github.com/GeekyAnts/NativeBase/blob/master/src/basic/Input.js#L20. It should use the theme in the context

**Comment by SupriyaKalghatgi** [comment]
Fixed with [2.4.2](https://github.com/GeekyAnts/NativeBase/releases/tag/v2.4.2)
