### ISSUE TITLE
Is not possible to change color of selected Picker Item

### ISSUE THREAD

**Issue by bgbraga** [GeekyAnts/NativeBase#1755]
I checked Picker.Item documentation and source code and apparentely there is not property to change the color of selected item.

I only found a way to change all Picker Items:

`<Picker itemTextStyle={{color: '#000000'}`

But I think is expected a way to change the selected item color.

**Comment by SupriyaKalghatgi** [comment]
#1653

**Comment by bgbraga** [comment]
I see that is not possible.

What is expected with that issue is implement that, not close.
If is not possible to pass "selected style" to Picker, another implement suggestion:

<Picker.Item label="My Item" value="My Item" textStyle={{color: '#66bdca'}}/>

The is no problem to do that. The work is just get Picker.Item style and pass to <Text>.
In that case we as Picker users will control the Picker.Item render to set the right color to right item.

@SupriyaKalghatgi I suggest to keep it open and implement that strategy. It is very simple to implement. If you accept that strategy I could do a PR.

**Comment by MedafPayDevelopers** [comment]
i want to change the selected text icon, the tick icon

**Comment by yunau** [comment]
I want to change the selected text icon, the tick icon too. Can someone help us, please?

**Comment by 3ilogics** [comment]
> I want to change the selected text icon, the tick icon too. Can someone help us, please?

its very easy just use Variable.js (you need to generate from https://nativebase.io/customizer/), After this add a class radioColor and pass the value. then your tick icon color will be change.

**Comment by sridix** [comment]
you can use like this for selected value from PICKER:
<Picker.Item color={(this.state.selectedId =='id') ? 'red' : 'grey' } label={'Value'} value={'id'} />
