### ISSUE TITLE
componentWillMount is deprecated

### ISSUE THREAD

**Issue by roboza** [GeekyAnts/NativeBase#1756]
Hi! Thanks for trying out NativeBase!
Due to the overwhelming requests and issues/questions we ask you to add the following details with your issue.

Please check the existing open/closed issues for a possible duplicate before creating a new issue :)

Also **DO** fill out the below form to give us a better idea about your environment and help us debug it quicker. Issues without the required details will mostly be unattended to.

react-native: `"react-native": "0.54.0"`
native-base: `"native-base": "2.4.1"`

I am receiving the following warning:

```
YellowBox.js:82 Warning: componentWillMount is deprecated and will be removed in the next major version. Use componentDidMount instead. As a temporary workaround, you can rename to UNSAFE_componentWillMount.

Please update the following components: View

Learn more about this warning here:
https://fb.me/react-async-component-lifecycle-hooks
```

**Comment by SupriyaKalghatgi** [comment]
#1665
