### ISSUE TITLE
Button with style prop not showing in Android 

### ISSUE THREAD

**Issue by unkownymouse** [GeekyAnts/NativeBase#1757]
I'm trying to place a button at a certain point in the screen. But the button doesn't get displayed in Android but there is no problem with iOS.

## react-native, react and native-base version
"native-base": "^2.4.1",
"react": "16.3.1",
"react-native": "0.54.4",

## Expected behaviour
The button should be rendered on Android.

## Actual behaviour
The button is not rendering on Android.

## Steps to reproduce (code snippet or screenshot)

```
<Container>
        <Header />
        <Content>
          <Button style={styles.contain}>
            <Text>Click Me! </Text>
          </Button>
        </Content>
</Container>

const styles = StyleSheet.create({
                   contain: {top: 100,}
                });

```
## Screenshot of emulator/device

<img width="493" alt="screen shot 2018-04-07 at 4 46 45 am" src="https://user-images.githubusercontent.com/32857628/38448015-df2065f8-3a1e-11e8-81d0-bbdf42fb06cc.png">

<img width="356" alt="screen shot 2018-04-07 at 4 47 38 am" src="https://user-images.githubusercontent.com/32857628/38448023-eac41b7a-3a1e-11e8-9496-4fcf277cd6fd.png">

## Is the bug present in both ios and android or in any one of them?

Bug is only present in Android.

**Comment by akhil-geekyants** [comment]
@unkownymouse not a NativeBase issue. 
Same happens with react-native `<ScrollView/>`. NativeBase `<Content/>` is an implementation of React Native `<ScrollView/>`. Pasting the test code.

Code
```
import React, { Component } from 'react';
import { ScrollView, Text } from 'react-native';
export default class App extends Component {
  render() {
    return (
      <ScrollView>
        <Text style={{ top: 100 }}>Hi there</Text>
      </ScrollView>
    );
  }
}
```

**Comment by kodayashi** [comment]
@akhil-geekyants - Is this the same issue as #1958 (logged by me)? I can't seem to apply style to Android buttons. If I do they don't render (e.g. adding your 'rounded' prop to Button).

Is there a workaround?

**Comment by SupriyaKalghatgi** [comment]
#1852
