### ISSUE TITLE
Warning componentWillReceiveProps/ componentWillUpdate is deprecated

### ISSUE THREAD

**Issue by havinhthai** [GeekyAnts/NativeBase#1758]
## Version

react-native: 0.55.0
react: 16.3.0-alpha.0
native-base: 2.4.1

## Issues
Warning componentWillReceiveProps/ componentWillUpdate is deprecated and will be removed in the next major version.

I don't know how to fix the problem, unless use react-native lower version.

**Comment by marko-hologram** [comment]
It's not a big problem, everything will still work, but those methods will probably be removed in React 17. Deprecated doesn't mean it doesn't work, it just means there is a better replacement for it. If you use them while developing your app, you can use the new lifecycle methods described in the blog post below. If they are maybe used in native-base, then it's nothing you can do until they update this repository, or if you submit a pull request fixing this "issue".

Everything is detailed here on the official React blog in [this post](https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html)

**Comment by SupriyaKalghatgi** [comment]
#1665

**Comment by pavm035** [comment]
I'm still seeing  this issue

**Comment by itsGabriel** [comment]
I'm still seeing this issue ^2
