### ISSUE TITLE
Cannot find entry file index (native-base-example-rnrf)

### ISSUE THREAD

**Issue by sinevitch** [GeekyAnts/NativeBase#1763]
# **Issue Description**
I'm trying to use the library native-base-example-rnrf
According to the documentation https://docs.nativebase.io/docs/examples/navigation/RNRFBasicExample.html

Cannot find entry file index
![image](https://user-images.githubusercontent.com/35930695/38500264-950f7972-3c12-11e8-93f2-e32504879136.png)

![image](https://user-images.githubusercontent.com/35930695/38502303-b2e5aa0c-3c17-11e8-9e31-4158869bcf06.png)

![image](https://user-images.githubusercontent.com/35930695/38502337-c51ab6cc-3c17-11e8-80e8-633deadc728f.png)

**index.ios.js**

```
/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 * @flow
 */

import React, { Component } from 'react';
import {
  AppRegistry,
} from 'react-native';
import App from './src/App.js';

export default class RnrfExample extends Component {
  render() {
    return (
      <App />
    );
  }
}

AppRegistry.registerComponent('RnrfExample', () => RnrfExample);
```

**srс/App.js**

```
import React, { Component } from 'react';
import { Router, Scene } from 'react-native-router-flux';

import PageOne from './pageOne';
import PageTwo from './pageTwo';

export default class App extends Component {
  render() {
    return (
      <Router hideNavBar= "true">
        <Scene key="root">
          <Scene key="pageOne" component={PageOne} title="PageOne" initial={true} />
          <Scene key="pageTwo" component={PageTwo} title="PageTwo" />
        </Scene>
      </Router>
    )
  }
}
```

---
### Environment
* React Native version: "0.54.0",
* Platform(s) : Xcode
* Device info : iPhone simulator
*  native-base: "^2.4.1",
*  react-native-router-flux: "^3.43.0"

**Comment by akhil-geekyants** [comment]
@sinevitch try creating an `index.js` file manually in the project root and copy the content of `index.ios..js` to it.

**Comment by SupriyaKalghatgi** [comment]
https://github.com/GeekyAnts/native-base-example-rnrf/issues/2
