### ISSUE TITLE
bug Item stackedLabel is Android

### ISSUE THREAD

**Issue by aspidvip** [GeekyAnts/NativeBase#1766]
Hello!
"react-native": "0.49.5",
"native-base": "^2.4.1",

`render() {

      return (
        <Container>
        <Content>
          <Form>
          <Item stackedLabel>
            <Label>Username</Label>
            <Input />
          </Item>
          <Item stackedLabel last>
            <Label>Password</Label>
            <Input />
          </Item>
          </Form>
        </Content>
      </Container>
      )

    }`

![bug](https://user-images.githubusercontent.com/22605655/38589717-0b491bd0-3d70-11e8-949e-fc46c5718abc.gif)

**Comment by aspidvip** [comment]
![bug1](https://user-images.githubusercontent.com/22605655/38589850-f7c39530-3d70-11e8-9c53-aa537160b562.gif)

**Comment by akhil-geekyants** [comment]
@aspidvip try setting the lineHeight same as fontSize.

Gif

![lineheight](https://user-images.githubusercontent.com/27768184/38602562-be7e14e0-3d88-11e8-9375-a31d7d895f7f.gif)

**Comment by aspidvip** [comment]
Ok thansk!!! is working

**Comment by aspidvip** [comment]
Hiding Fonts
![bug4](https://user-images.githubusercontent.com/22605655/38708139-218898ba-3ef8-11e8-942c-74c82703894c.gif)

**Comment by aspidvip** [comment]
`<Container>
          <Content>
            <Form>
            <Item stackedLabel>
              <Label>Username</Label>
              <Input style={{lineHeight: 17}} />
            </Item>
            <Item stackedLabel last>
              <Label>Password</Label>
              <Input />
            </Item>
            </Form>
          </Content>
        </Container>`
![bug5](https://user-images.githubusercontent.com/22605655/38708341-31d651fc-3ef9-11e8-92f3-5ab2d79e7561.gif)

**Comment by SupriyaKalghatgi** [comment]
Fixed with [2.4.2](https://github.com/GeekyAnts/NativeBase/releases/tag/v2.4.2)
