### ISSUE TITLE
tabStyle changing width and padding

### ISSUE THREAD

**Issue by phatnguyenbg** [GeekyAnts/NativeBase#1767]
I have many tabs in page. So, the title each tab's difference long. So, the wide of tab is similar, I'm not ability to change it.
Although, I'm using tabStyle property, changed (width and padding), but it's not effect it.
How to change the width of tab1 is difference other?
![capture](https://user-images.githubusercontent.com/29854376/38601434-c37b6bf6-3d91-11e8-9ea3-99d64b90e78e.PNG)

**Comment by akhil-geekyants** [comment]
@phatnguyenbg try changing width of both `tabStyle` and `activeTabStyle` of `<Tab/>`.

**Comment by phatnguyenbg** [comment]
I'm trying but seem it's not changed :(, 
I find out this props:
 heading={ <TabHeading><Icon name="camera" /><Text>Camera</Text></TabHeading>}
it solved my above problem, but these props below seem not great :(
![capture](https://user-images.githubusercontent.com/29854376/38849440-2f119d56-4236-11e8-96d6-29583cfa00ef.PNG)
now text title none active @@

**Comment by akhil-geekyants** [comment]
@phatnguyenbg `tabStyle`, `activeTabStyle`, `textStyle`, `activeTextStyle` are useful in the normal case where heading is just a string. If you are defining heading using `<TabHeading/>`, you have to handle the  styles based on selection.

**Comment by thanhluantl2304** [comment]
why can't i set padding for tab heading? i set padding to 1  and it was not working. Please help!
