### ISSUE TITLE
Button not working fine in android 

### ISSUE THREAD

**Issue by sudhirkumarojhaa** [GeekyAnts/NativeBase#1768]
Hi! Thanks for trying out NativeBase!
Due to the overwhelming requests and issues/questions we ask you to add the following details with your issue.

Please check the existing open/closed issues for a possible duplicate before creating a new issue :)

Also,**DO** fill out the below form to give us a better idea about your environment and help us debug it quicker. Issues without the required details will mostly be unattended to.

## react-native, react and native-base version

`  "native-base": "^2.4.1",
    "react": "16.3.1",
    "react-native": "0.55.1",`
## Expected behavior

![screen shot 2018-04-11 at 2 54 54 pm](https://user-images.githubusercontent.com/24911219/38608202-54d2505a-3d98-11e8-876e-cbc49e0342a2.png)
i.e in iOS

## Actual behavior

in android it looks like this
![screen shot 2018-04-11 at 3 01 15 pm](https://user-images.githubusercontent.com/24911219/38608539-4950bab8-3d99-11e8-9ee8-c91cd42c16db.png)

## Steps to reproduce (code snippet or screenshot)

`const ButtonNative = ({ title, icon ,onPress }) => (
  <Button rounded style={styles.roleBtn} onPress={onPress}>
    <Left>
      <Icon name={icon} style={styles.roleIcon} />
    </Left>
    <Text>{title}</Text>
    <Right />
  </Button>
);
`

> `const styles = StyleSheet.create({
  roleBtn: {
    marginVertical: 10,
    backgroundColor: "#444",
    zIndex: -1000,
    paddingVertical: 10,
    paddingHorizontal: 10,
    fontSize: 30,

  },
  roleIcon: {
    paddingLeft: 15,
    fontSize: 30,
    color: "#fff"
  }
});`

## Is the bug present in both ios and android or in any one of them?

An android device only works fine on iOS
## Any other additional info which would help us debug the issue quicker.
I tried giving left body and right to align the button full width but the text was not visible then neither the icon
![screen shot 2018-04-11 at 3 01 15 pm](https://user-images.githubusercontent.com/24911219/38608517-376210d6-3d99-11e8-9309-c93c09cbdb74.png)

also one more thing Please 

can you tell me anyway by which the header can have the title in the center in both android and ios and not only in ios? I developed the whole code in iOS simulator but now it looks very much odd in Android, also the text field for the title is very limited it shows ..... after certain width.I used the native base library because of these components only. Please help as soon as possible.

**Comment by SupriyaKalghatgi** [comment]
#1749

**Comment by sudhirkumarojhaa** [comment]
This issue is  not same , as you mentioned in the comment above the problem is with width and not height, I want to align the icon in the left corner and text in center , Please reply here

**Comment by akhil-geekyants** [comment]
@sudhirkumarojhaa use `block` props with `<Button/>`

```
 <Button rounded block>...</Button>
```

**Comment by sudhirkumarojhaa** [comment]
I did used the block props but the text is not coming in center

**Comment by akhil-geekyants** [comment]
@sudhirkumarojhaa posting code

Code
```
import React, { Component } from 'react';
import { Container, Header, Content, Button, Text, Left, Right, Icon } from 'native-base';
export default class App extends Component {
  render() {
    return (
      <Container>
        <Header />
        <Content>
          <Button rounded
            block
            style={{
              marginVertical: 10,
              marginHorizontal: 10,
              backgroundColor: "#444",
              zIndex: -1000,
              paddingVertical: 10,
              paddingHorizontal: 10,
            }}
            onPress={() => { }}>
            <Left>
              <Icon name="home" style={{
                paddingLeft: 15,
                fontSize: 30,
                color: "#fff"
              }} />
            </Left>
            <Text>Title</Text>
            <Right />
          </Button>
        </Content>
      </Container>
    );
  }
}
```
![screenshot_1523443423](https://user-images.githubusercontent.com/27768184/38612145-69f825bc-3da3-11e8-9522-86de57e57cd4.png)
![simulator screen shot - iphone 6 - 2018-04-11 at 16 13 56](https://user-images.githubusercontent.com/27768184/38612146-6a2a0316-3da3-11e8-888f-f4d76b09805e.png)

**Comment by sudhirkumarojhaa** [comment]
Thanks a lot, will check this by adding, one more issue is there the header title in Android is not coming in center. and the character limit is less it shows .... when exceeds the limit. can you help regarding this?

**Comment by akhil-geekyants** [comment]
@sudhirkumarojhaa you can do something like this for header.
```
<Header>
  <Left>
    <Button transparent>
      <Icon name='arrow-back' />
    </Button>
  </Left>
  <Body style={{ flex: 3, alignItems: 'center' }}>
    <Title>Header</Title>
  </Body>
  <Right>
    <Button transparent>
      <Icon name='more' />
    </Button>
  </Right>
</Header>
```

**Comment by SupriyaKalghatgi** [comment]
@sudhirkumarojhaa 
> header title in Android is not coming in center.

This is as per material design guidelines

**Comment by haotangio** [comment]
I had the same problem, `rounded` and `block` cannot be used together on Android (the `<Button>` will not be displayed outside of `<Content>` tag).

Any workaround?

**Comment by SupriyaKalghatgi** [comment]
#1852 
Fixed
