### ISSUE TITLE
Scrollable Tab heading label removed/invisible when clicked

### ISSUE THREAD

**Issue by techyrajeev** [GeekyAnts/NativeBase#1773]
## Issue with ScrollableTab 

Tab heading is generated dynamically for letters A to Z.
#### Versions:
react-native: 0.53.0, 
react:16.2.0,
native-base:2.4.1
#### Expected behaviour : 

clicking on scrollable tab should go to corresponding tab-view and tab should remain as it is with its label intact
### Actual behaviour : 

clicking on scrollable tab hides the tab-label and removes first tab heading label
### Before
<img width="309" alt="screen shot 2018-04-12 at 12 39 18 pm" src="https://user-images.githubusercontent.com/4118032/38661473-a06e3bf8-3e4e-11e8-9e52-4371f4b08e29.png">

### After Clicking on tab D 
<img width="301" alt="screen shot 2018-04-12 at 12 34 29 pm" src="https://user-images.githubusercontent.com/4118032/38661369-3dcb216e-3e4e-11e8-9bed-1078e91fb183.png">

## Is the bug present in both ios and android or in any one of them?
I tested only in android for now

**Comment by abhijitwani83** [comment]
I am also facing the same issue. Once I click on second tab first and second tab becomes empty.
Please help me to fix this issue.
