### ISSUE TITLE
Can NativeBase work without expo?

### ISSUE THREAD

**Issue by changtimwu** [GeekyAnts/NativeBase#1779]
Well, this is not a bug reporting.  All issue posting specs are not applicable here.

NativeBase itself doesn't depend on `expo`.  However, to use NativeBase,  all examples are starting with a small clip of loading expo fonts.  I am not sure if it is mandatory.  Could you give an example illustrating how to load font without `Expo.Font.loadAsync`?   Thank you.

**Comment by SupriyaKalghatgi** [comment]
Check Docs

**Comment by salamancajr** [comment]
Thats a bad way of handling that question. I had the same one.

**Comment by sankhadeeproy007** [comment]
@salamancajr Please check the examples [here](https://github.com/GeekyAnts/NativeBase-KitchenSink). The master branch has no dependency on Expo.

**Comment by sankhadeeproy007** [comment]
<img width="1383" alt="screen shot 2018-09-03 at 10 17 56 pm" src="https://user-images.githubusercontent.com/10998047/44996751-48d3e880-afc7-11e8-8afb-ae3460ed5eb0.png">
Also from the very first page in the official docs.
Always a good idea to read the docs 💯

**Comment by njoye** [comment]
> Well, this is not a bug reporting. All issue posting specs are not applicable here.
> 
> NativeBase itself doesn't depend on `expo`. However, to use NativeBase, all examples are starting with a small clip of loading expo fonts. I am not sure if it is mandatory. Could you give an example illustrating how to load font without `Expo.Font.loadAsync`? Thank you.

Exact same question here, I'm having problems using my App without Expo, partially because I don't know how to load the fonts without `Expo.Font.loadAsync`. +1

**Comment by tux-tn** [comment]
We are using NativeBase without expo and it's working perfectly. To use any custom font you need to tell react-native to link it to your project. Check this tutorial for more information https://medium.com/react-native-training/react-native-custom-fonts-ccc9aacf9e5e

**Comment by njoye** [comment]
Hi @tux-tn, you are right. This is _"working"_. I've downloaded the`ionicons.ttf` from [ionicons.com](https://ionicons.com/) and linking etc. works just fine. Yet my Icons have changed (without me changing their name) and I can't use the names on ionicons.com to correct that, as there are errors that the referenced Icon does not exist. 

I've been at that place before, how do I fix that problem ?

**Comment by tux-tn** [comment]
@njoye if you want to include a vector icon i suggest you to take a look at https://github.com/oblador/react-native-vector-icons there is many vector icons bundled including Ionicons and Font Awesome 5
