### ISSUE TITLE
Enable strict EsLint throughout the codebase

### ISSUE THREAD

**Issue by sanketsahusoft** [GeekyAnts/NativeBase#178]
I think we should use the EsLint Atom plugin and always fix linting errors before releasing new versions.

**Comment by aaray** [comment]
Enforcing eslint would be a great start to improving conding style consistency in the code base.

As today eslint reports 42 problems on the master branch, most of them easy to fix.

After we are done fixing the eslint errors and warnings it would also be great if we could adopt a more strict eslint rule set.  Both airbnb and standard are great at enforcing consistency and best coding practices.

**Comment by AlicanC** [comment]
> eslint reports 42 problems on the master branch

``"`npm bin`/eslint" "Components/**/*.js" "Utils/**/*.js" index.js`` reports `3996 problems (3953 errors, 43 warnings)`.

**Comment by sanketsahusoft** [comment]
We are using Prettier throughout the project, so we won't add Eslint any more.
