### ISSUE TITLE
bug] small button with icon on Android

### ISSUE THREAD

**Issue by garan82** [GeekyAnts/NativeBase#1781]
This issue https://github.com/GeekyAnts/NativeBase/issues/1743 was fixed but looks like it introduces bug on Android

Env: native base 2.4.2
Expo: 26.0.0
React native: 0.54
Reactjs: 16.3.0-alpha.1

Repo: create a small button with Icon on Android
Issue: icon is bottom aligned with the button text, which is cut off in some cases. Icon should be vertically center aligned within the button. Button looks fine on iOS

**Comment by SupriyaKalghatgi** [comment]
Fixed on `development`

**Comment by SupriyaKalghatgi** [comment]
Fixed with [2.4.3](https://github.com/GeekyAnts/NativeBase/releases/tag/v2.4.3)
