### ISSUE TITLE
Switch tintColor

### ISSUE THREAD

**Issue by gdierksmeier** [GeekyAnts/NativeBase#1782]
Hi...i would like to know how to change the color of the Switch when is inactive...

Now we have option to change a color only when active (onTintColor)

I'm using "native-base": "2.4.1" and 
"react-native": "0.52.3"
Example:
            <Field
              name="settingModeDebug"
              title={I18n.t('settingModeDebug')}
              component={FormSwitch}
              type="switch"
              validate={[]}
              icons="ios-alert-outline"
              value={true}
              onTintColor={'red'}
              thumbTintColor={'red'}
              inputGrp={{ padding: 0, margin: 0, backgroundColor: 'white' }}
            />
Thanks

**Comment by SupriyaKalghatgi** [comment]
Switch of NativeBase is direct implementation of React-Native Switch
So please check https://facebook.github.io/react-native/docs/switch.html
