### ISSUE TITLE
How to disable ripple effect on android

### ISSUE THREAD

**Issue by Risck256** [GeekyAnts/NativeBase#1783]
Hi!
It is possible to remove the androidRipple effect from all of the native-base's transparent buttons?

Thank you at all

**Comment by SupriyaKalghatgi** [comment]
https://github.com/GeekyAnts/NativeBase/blob/master/src/theme/variables/commonColor.js#L17

**Comment by NqCompiler** [comment]
I wanted to disable the ripple effect as well.
The provided link is no more available. You can use:
https://github.com/GeekyAnts/NativeBase/blob/master/src/theme/components/radio.ts

What you have to do is set the defaultProps bg property for _interactionBox to "transparent". In my case I only had overwrite the Radio Component for the pseudo prop _pressed
