### ISSUE TITLE
Component LifeCycle method only being triggered for first time?

### ISSUE THREAD

**Issue by isaaclem** [GeekyAnts/NativeBase#1798]
## Issues
Under `Tabs` component, I've bind only one specific component and distinguish them based on props. While tab active, this component are expect to re-render or sorts to get the relevant values. However, it seems that component lifecycle method only being executed first time for each and every tab. Meaning if we revisit the tab once again, none of component lifecycle method will being invoke. 

## react-native, react and native-base version
    "native-base": "^2.4.2",
    "react": "16.0.0",
    "react-native": "0.52.0",

## Expected behaviour
Component lifecycle method will be invoked everytime a tab changed.

## Actual behaviour
Component lifecycle method only being invoked for first time each tab active. Component Lifecycle method will not be invoked again if the tab is revisit.

## Steps to reproduce (code snippet or screenshot)

    <Tabs 
      initialPage={this.props.day}
      tabBarUnderlineStyle={{ backgroundColor: '#5AF158' }} 
      renderTabBar={() => <ScrollableTab />}>
      {this.renderTabHeader()}
    </Tabs>

    renderTabHeader() {
      return (
        this.props.dateArray.map((date, i) => 
          <Tab 
            key={i}
            heading={date.format('DD/MM')} 
            tabStyle={styles.tabStyling} 
            activeTabStyle={styles.activeTabStyle} 
            textStyle={styles.tabTextStyle} 
            activeTextStyle={styles.activeTabTextStyle} 
          >
            <View style={{ backgroundColor: '#EEEEEE', flex: 1 }}>
              <Content contentDate={date.format('YYYY-MM-DD')} />
            </View>
          </Tab>
        )
      );
    }

Content Component:

    class Content extends Component {
      componentWillMount() {
        console.log('Component Will Mount() ?');
        this.props.loadTransactionByDate({ date: this.props.contentDate });
      }

    componentWillUpdate(nextProps, nextState) {
      console.log('Component Will Update() ?');
    }

    render() {
      return (
        <View><Text>{this.props.contentDate}</Text></View>
      );
      }

**Comment by SupriyaKalghatgi** [comment]
https://stackoverflow.com/questions/49881731/componentwillmount-only-trigger-for-first-time

**Comment by isaaclem** [comment]
[https://media.giphy.com/media/kxtA6b7ttZrJvfP9Mk/giphy.gif](url)

Hi Akhil, I've captured a GIF to show you my situation instead.

**Comment by akhil-geekyants** [comment]
@isaaclem couldn't get anything like in gif. Can you try logging in the browser console. Attaching a gif

Gif

![lifecycle](https://user-images.githubusercontent.com/27768184/39033466-c1352102-448f-11e8-8381-517490f70f36.gif)

**Comment by isaaclem** [comment]
@akhil-geekyants I've set it up in Snack and simulated the problem. You may have a look @ https://snack.expo.io/@cclem65/moneylover

**Comment by SupriyaKalghatgi** [comment]
Somehow missed this one to check
Will respond soon

**Comment by isaaclem** [comment]
@SupriyaKalghatgi : It's ok SupriyaKalghatgi, thanks for your effort on making NB great!

**Comment by SupriyaKalghatgi** [comment]
@isaaclem 

- your code snippet: https://github.com/GeekyAnts/NativeBase/issues/1798#issuecomment-382749157

- @akhil-geekyants 's reply: https://github.com/GeekyAnts/NativeBase/issues/1798#issuecomment-382989885

we couldn't reproduce your issue with your provided code

**Comment by isaaclem** [comment]
@SupriyaKalghatgi 
I've created a snack @ https://snack.expo.io/@cclem65/moneylover with the code snippet I've provided. 
It's in MainScreen.js. Just by running it you can see the console log that those component life cycle only being triggered once

**Comment by isaaclem** [comment]
@SupriyaKalghatgi 
I've created a snack @ https://snack.expo.io/@cclem65/moneylover with the code snippet I've provided. 
It's in MainScreen.js. Just by running it you can see the console log that those component life cycle only being triggered once

**Comment by SupriyaKalghatgi** [comment]
@isaaclem We tried your code from https://github.com/GeekyAnts/NativeBase/issues/1798#issuecomment-382749157 and worked fine with output shared above

and this code is same as your code on snack

**Comment by isaaclem** [comment]
@SupriyaKalghatgi : Yes it's of course exactly the same as on snack, it's so that when you run the snack, you can see the console log. and realize that they will only be triggered for first time for each of that 4 dates.

**Comment by isaaclem** [comment]
@SupriyaKalghatgi: I've just tried to copy out the code to another snack and run it, it seems working fine. The problem can only simulated by this very specific snack https://snack.expo.io/@cclem65/moneylover . Not sure what's particularly wrong but I think you may close the issue

**Comment by SupriyaKalghatgi** [comment]
@isaaclem This is exactly what i tried to explain you
We tried your code in existing project, worked fine
We tried your code in fresh project, worked fine
If this did not work on snack, i am not sure about the reason for this.

>  I've just tried to copy out the code to another snack and run it, it seems working fine.
Totally uncommentable, we cant help with this

Let me know if any more diagnosis or help required from our side

**Comment by SupriyaKalghatgi** [comment]
We would be closing this in a day, in case of no response

**Comment by HarshitMadhav** [comment]
I am facing this same issue right now.
