### ISSUE TITLE
Add styling to touchablehighlight in ListItem

### ISSUE THREAD

**Issue by hansen94** [GeekyAnts/NativeBase#1799]
Hi,

First of all, thank you for the awesome library. 
If possible, I would like to request additional feature for ListItem. Is it possible to add custom styling to touchablehighlight in ListItem? I would like to add margin to the ListItem but the highlight underlay still covers the margin area. It would be nice to also add margin to this underlay.

Thank you.

**Comment by akhil-geekyants** [comment]
@hansen94 can you try adding `marginLeft` along with `margin` to ListItem style.

**Comment by hansen94** [comment]
I did it and the underlay still covers the margin. I am actually trying to add marginBottom. 
When i look in ListItem.js, the style props in TouchableHighlight is set to undefined. I think this is why.
Is it ok to make new props for this like highlightStyle?

**Comment by SupriyaKalghatgi** [comment]
Released with [2.5.0](https://github.com/GeekyAnts/NativeBase/tree/v2.5.0)
