### ISSUE TITLE
Input compnent is missing

### ISSUE THREAD

**Issue by webinspired** [GeekyAnts/NativeBase#18]
ran thru the demo.... it was amazing...   

everything worked perfect except that it i cant render any Inputs...  

i backed down to 0.3.0 because input would not work...

I added it to your index.js and it worked..

also using an InputGroup  without an Icon throws an 'undefined is not an object (evaluating 'Icon.props')

hope this helps
![screenshot at may 13 19-33-14](https://cloud.githubusercontent.com/assets/2215119/15264496/94794754-1941-11e6-89a8-9e64b0b2c063.png)

**Comment by sankhadeeproy007** [comment]
Hey, can you tell me the RN version you're using?

**Comment by sankhadeeproy007** [comment]
Fixed.
