### ISSUE TITLE
Font Scaling in NativeBase

### ISSUE THREAD

**Issue by AgNm** [GeekyAnts/NativeBase#1800]
I am using Nativebase throughout my application. 

If user changes the Font Size from device settings, all the fonts gets Huge/small. I don't want the font size impact on My app. How can I stop this font size scaling.

In React Native, we have ` Text.defaultProps.allowFontScaling=false;`
but it is not working for NativeBase.

Please let me know if there is any alternative. 

I am using below versions : 

```
    "native-base": "^2.3.5",
    "react": "16.3.0-rc.0",
    "react-native": "0.54.3"
```

**Comment by akhil-geekyants** [comment]
@AgNm Text.defaultProps.allowFontScaling=false; is working for NativeBase (2.4.2).

Attaching a gif

![fontscaling](https://user-images.githubusercontent.com/27768184/38936854-65ca6f62-433f-11e8-85db-7a8b1469fd4b.gif)

Let us know if you are still facing any problem
