### ISSUE TITLE
onRowOpen, onRowClose, etc... props don't exist in types

### ISSUE THREAD

**Issue by externuz** [GeekyAnts/NativeBase#1801]
Hi!

I'm using `native-base 2.4.1`

When I trying to use `<List />` props `onRowOpen, onRowClose, onRowDidOpen, onRowDidClose`, I get message from linter: `Property 'onRowDidOpen' does not exist on type 'IntrinsicAttributes' & 'IntrinsicClassAttributes<List> & ReadOnly<{ children?: ReactNode; }> & Read...'.`

**Comment by SupriyaKalghatgi** [comment]
Fixed with [2.4.3](https://github.com/GeekyAnts/NativeBase/releases/tag/v2.4.3)
