### ISSUE TITLE
InputGroup not working and lost control over input tag

### ISSUE THREAD

**Issue by ZeroCool00** [GeekyAnts/NativeBase#1805]
"dependencies": {
"native-base": "^2.4.2",
"react": "16.3.1",
"react-native": "0.55.2",
},

i m setting icon in input tag with InputGroup tag but there is no effect and also i lost control over input tag. now my email input tag's returnKeyType='next' is not working, now it takes by default "actionDone"
and in password secureTextEntry also not working. now password is also visible.

![screenshot_20180419-163939](https://user-images.githubusercontent.com/18139594/38988364-85cb0b9e-43f0-11e8-951c-c1daa1ef7dab.png)

```
<Form style={styles.inputContainer}>
            <Item floatingLabel>
              <Label>Email</Label>
              <InputGroup
                iconRight
                success={this.state.inputEmailSuccess}
                error={this.state.inputEmailError}
              >
                  <Icon name='ios-close-circle' style={{ color: '#00C497' }} />
                  <Input
                    returnKeyType='next'
                    onSubmitEditing={() => { this.password._root.focus(); }}
                    onChangeText={(value) => this.setState({ email: value })}
                    blurOnSubmit={false}
                  />
              </InputGroup>
            </Item>
            <View style={{ padding: 5 }} />
            <Item floatingLabel>
              <Label>Password</Label>
              <InputGroup
                iconRight
                success={this.state.inputPasswordSuccess}
                error={this.state.inputPasswordError}
              >
                <Icon name='ios-checkmark-circle' style={{ color: '#00C497' }} />
                <Input
                  getRef={(input) => { this.password = input; }}
                  onChangeText={(value) => this.setState({ password: value })}
                  secureTextEntry
                />
              </InputGroup>
            </Item>
          </Form>
``

**Comment by SupriyaKalghatgi** [comment]
@ZeroCool00 Why are you using `InputGroup`?
Do you find it in docs?

**Comment by ZeroCool00** [comment]
i search on google about react-native validation. and i found this concept on search result.  [this]
 (https://nativebase.io/docs/v0.5.7/components#inputGroup) and i didnt check about version. sorry i learn my lession today.. 'always check version first'.

**Comment by SupriyaKalghatgi** [comment]
@ZeroCool00 I am closing this issue

**Comment by ZeroCool00** [comment]
ok, but is there anything i can trace like this tag is not available in latest version.

**Comment by SupriyaKalghatgi** [comment]
> tag is not available in latest version

Tag is available with NativeBase repo as well as docs

**Comment by SupriyaKalghatgi** [comment]
You are using deprecated component
Check latest docs
