### ISSUE TITLE
Picker itemStyle,itemTextStyle,textStyle not working

### ISSUE THREAD

**Issue by YogarajRamesh** [GeekyAnts/NativeBase#1806]
<Picker
                                    iosHeader="Sub-Category"
                                    placeholder="Select your SIM"
                                    placeholderStyle={{ color: "#bfc6ea" }} 
                                    selectedValue={this.state.selected1}
                                    onValueChange={this.onValueChange.bind(this)}
                                    itemStyle={{ fontSize:18, color: '#d00',fontFamily:"Montserrat-Regular",backgroundColor: 'lightgrey'}}
                                    itemTextStyle={{ fontSize:18, color: '#d00',fontFamily:"Montserrat-Regular" }}
                                    textStyle={{ fontSize:16, color: '#d00',fontFamily:"Montserrat-Regular" }}
                                    >

**Comment by SupriyaKalghatgi** [comment]
@YogarajRamesh It is because of `Montserrat-Regular`
You dont have this with your project

**Comment by SupriyaKalghatgi** [comment]
@YogarajRamesh Also check docs for proper use case
https://docs.nativebase.io/Components.html#picker-text-and-item-text-styles-headref

```
itemStyle={{ fontSize:18, color: '#d00'}}
```

This is incorrect usage

**Comment by SupriyaKalghatgi** [comment]
![picker](https://user-images.githubusercontent.com/13464885/38990007-54305fb6-43f6-11e8-99fe-fddf26a39466.gif)

**Comment by YogarajRamesh** [comment]
Hi @SupriyaKalghatgi i am using android and it doesn't color and fontsize

**Comment by SupriyaKalghatgi** [comment]
@YogarajRamesh Please check docs

![image](https://user-images.githubusercontent.com/13464885/38990657-c923232e-43f8-11e8-9305-d4065a35535d.png)

Also check https://github.com/GeekyAnts/NativeBase-KitchenSink

**Comment by armouti** [comment]
I had this issue as well, I tried to use NativeBase's Picker instead of React Native's native picker because I will be able to style them but nothing, like the issue says the "itemStyle ,itemTextStyle ,and textStyle" simply don't work.
