### ISSUE TITLE
Where to change the size of Picker Item's checkmark? (With Image)

### ISSUE THREAD

**Issue by VanessaChu** [GeekyAnts/NativeBase#1808]
This is from Picker's Item list with the code:

```
                  <Picker
                    style={{ height: 30 }}
                    supportedOrientations={['portrait', 'landscape']}
                    iosHeader={'Choose Type'}
                    mode='dropdown'
                    iosIcon={<Icon darkgray style={styles.chevronRight} name='angle-right' />}
                    selectedValue={this.state.type}
                    onValueChange={(value) => { this.setState({ type: value }) }}
                    textStyle={styles.pickerText}>
                    <Picker.Item label={'Greeting'} value={'Greeting'} />
                    <Picker.Item label={'Reminder'} value={'Reminder'} />
                  </Picker>
```

How can I edit the size of the checkmark as shown in image below? It's too small/

![screen shot 2018-04-19 at 2 25 02 pm](https://user-images.githubusercontent.com/11250498/39019186-4c134c6c-43dd-11e8-87d8-fc33fec824f3.png)

**Comment by akhil-geekyants** [comment]
@VanessaChu Picker's checkmark make use of the default Radio button size. To change this you need to [eject the theme](http://docs.nativebase.io/Customize.html#theaming-nb-headref). 
You can then increase the radio button size by changing the `radioBtnSize` variable in `native-base-theme/variables/*.js`

**Comment by VanessaChu** [comment]
@akhil-geekyants That was it 😀  Thanks
