### ISSUE TITLE
CheckBox onPress not working on ios but working on android 

### ISSUE THREAD

**Issue by renztoygwapo** [GeekyAnts/NativeBase#1809]
I tried the checkbox and it will worki the onpress function in android but in ios i tried to check it and it will have an error that says.

![image](https://user-images.githubusercontent.com/4898681/39036882-7c5e6f62-44b1-11e8-9db7-a7946bd5d2e5.png)

Here is my code:
![image](https://user-images.githubusercontent.com/4898681/39036934-9d74a040-44b1-11e8-9965-f1d0b565c08e.png)
![image](https://user-images.githubusercontent.com/4898681/39036957-b06ab0a4-44b1-11e8-9ed7-390915c52ee1.png)

Any help thanks.

**Comment by akhil-geekyants** [comment]
@renztoygwapo Checkbox is working fine. The error message shows that the error is somewhere in Picker implementation. Attaching a gif

Code
```
import React, { Component } from 'react';
import { Container, Header, Content, CheckBox, View } from 'native-base';
import { Col, Row, Grid } from 'react-native-easy-grid';

export default class App extends Component {

  state = {
    shareCommission: false
  }

  _checkBoxHandler() {
    this.setState({ shareCommission: !this.state.shareCommission })
  }

  render() {
    return (
      <Container>
        <Header />
        <Content padder>
          <Grid>
            <Col style={{ width: 40 }}>
              <View>
                <CheckBox checked={this.state.shareCommission} onPress={() => this._checkBoxHandler()} />
              </View>
            </Col>
          </Grid>
        </Content>
      </Container>
    );
  }
}
```

Gif

![checkbox](https://user-images.githubusercontent.com/27768184/39040005-2862820c-44a4-11e8-9c0c-b21a896ba8df.gif)

**Comment by renztoygwapo** [comment]
actually, I am stupid the actual issue is in my picker list item. Thanks
