### ISSUE TITLE
Setting page prop on Tabs does nothing

### ISSUE THREAD

**Issue by you-fail-me** [GeekyAnts/NativeBase#181]
I want to switch active tab of `Tabs` component programatically, I'm passing a prop `page` equal to `1` to make the second tab active and it does nothing.

**Comment by NazarYablonskiy** [comment]
@sankhadeeproy007 I have the same problem.

**Comment by sankhadeeproy007** [comment]
Will be documented soon, 
`this._tabs.goToPage(tabIndex);` should do the needful. `tabIndex` is an integer denoting the Tab number.

**Comment by phixtalk** [comment]
Hello, please this._tabs.goToPage(tabindex) is not working for me.Please what am i doing wrong?

render() {
		return (
			<Container>
				<Tabs initialPage={0}>
				  <Tab heading={ <TabHeading><Text>Feed</Text></TabHeading>}>
					<Feed dpmode="1" />
				  </Tab>
				  <Tab heading={ <TabHeading><Text>Trending</Text></TabHeading>}>
					  <Content><Text onPress={() => this.tabs.goToPage(0)}>Click me</Text></Content>
				  </Tab> 
				</Tabs>
				
			</Container>
		);
	}

**Comment by phixtalk** [comment]
Hello, please this._tabs.goToPage(tabindex) is not working for me.Please what am i doing wrong?

render() {
		return (
			<Container>
				<Tabs initialPage={0}>
				  <Tab heading={ <TabHeading><Text>Feed</Text></TabHeading>}>
					<Feed dpmode="1" />
				  </Tab>
				  <Tab heading={ <TabHeading><Text>Trending</Text></TabHeading>}>
					  <Content><Text onPress={() => this.tabs.goToPage(0)}>Click me</Text></Content>
				  </Tab> 
				</Tabs>
			</Container>
		);
	}

**Comment by brickolicious** [comment]
@phixtalk 

You need to set your _tabs object in the constructor 
I have this._tabs = null and than you reference the tab component
```
<Tabs 
ref={ t=>this._tabs = t } 
renderTabBar={() => <ScrollableTab/>}>
                           --MY TABS--
</Tabs>
```

Than i have an input with an onFocus

```
   <Input
   onFocus={()=>{this._tabs.goToPage(tabsIndex)}}<---- call the ref 
   onChangeText={this.handleText}/>
```


Using refs stuff seems a bit dodgy though, but it works when you need a hack

**Comment by AamirAlam** [comment]
> @phixtalk
> 
> You need to set your _tabs object in the constructor
> I have this._tabs = null and than you reference the tab component
> 
> ```
> <Tabs 
> ref={ t=>this._tabs = t } 
> renderTabBar={() => <ScrollableTab/>}>
>                            --MY TABS--
> </Tabs>
> ```
> Than i have an input with an onFocus
> 
> ```
>    <Input
>    onFocus={()=>{this._tabs.goToPage(tabsIndex)}}<---- call the ref 
>    onChangeText={this.handleText}/>
> ```
> Using refs stuff seems a bit dodgy though, but it works when you need a hack

Work for me but the current tab was not highlited

**Comment by akbari6776** [comment]
> @phixtalk
> 
> You need to set your _tabs object in the constructor
> I have this._tabs = null and than you reference the tab component
> 
> ```
> <Tabs 
> ref={ t=>this._tabs = t } 
> renderTabBar={() => <ScrollableTab/>}>
>                            --MY TABS--
> </Tabs>
> ```
> 
> Than i have an input with an onFocus
> 
> ```
>    <Input
>    onFocus={()=>{this._tabs.goToPage(tabsIndex)}}<---- call the ref 
>    onChangeText={this.handleText}/>
> ```
> 
> Using refs stuff seems a bit dodgy though, but it works when you need a hack

is not work for me and no error

what do you mean "You need to set your _tabs object in the constructor"
