### ISSUE TITLE
[Picker for iOS] Multiple nesting ScrollViews

### ISSUE THREAD

**Issue by fcpineiro** [GeekyAnts/NativeBase#1816]
https://github.com/GeekyAnts/NativeBase/blob/c488d9219c96b57217ce070ef35d13505efd0500/src/basic/Picker.ios.js#L187

This component has a FlatList(ScrollView) inside of a Content(ScrollView) component.

Apart from being a performance improvement, this nesting may prevent this component from working properly in case some feature that uses `.scrollTo()` method is added afterwards.

Some examples may be, the ability to load the picker showing the preselected item or the ability to implement some scrollToBottom functionality (in case of big item lists).

**Comment by SupriyaKalghatgi** [comment]
Fixed with [2.4.3](https://github.com/GeekyAnts/NativeBase/releases/tag/v2.4.3)
