### ISSUE TITLE
[Question] Remove box-shadow from card

### ISSUE THREAD

**Issue by anam-hossain** [GeekyAnts/NativeBase#1819]
Is there any way to remove box-shadow from the card? Does NativeBase support flat version of card?

**Comment by akhil-geekyants** [comment]
@anam-hossain use transparent props with `<Card/>`
```
<Card transparent>...</Card>
```

**Comment by anam-hossain** [comment]
Thank you.

**Comment by SupriyaKalghatgi** [comment]
Fixed with [2.4.3](https://github.com/GeekyAnts/NativeBase/releases/tag/v2.4.3)

**Comment by khizarali621** [comment]
<Card transparent {...props}>
// code
</Card>
