### ISSUE TITLE
Margin on Top of Content if have any field

### ISSUE THREAD

**Issue by basequatro** [GeekyAnts/NativeBase#182]
I'm getting a margin on the top of content(scrollview) when we have any fields inside. Maybe its because of keyboard aware lib.

Using automaticallyAdjustContentInsets={false} on content, solved the problem. 
Shouldn't we use this for default on <Content> ?

**Comment by himanshu-sahusoft** [comment]
Please post the screenshots and some sample code to reproduce the issue.

**Comment by basequatro** [comment]
This only happens when the keyboard was opened, in my case, <Header searchBar
![screen shot 2016-09-20 at 9 35 25 am](https://cloud.githubusercontent.com/assets/2417603/18670293/9d8a593e-7f15-11e6-8f7a-7fdfd8e46d4f.png)
![screen shot 2016-09-20 at 9 34 11 am](https://cloud.githubusercontent.com/assets/2417603/18670292/9d864d9e-7f15-11e6-862b-e6d108798c69.png)
