### ISSUE TITLE
span, hasSubtitle - missing from typing (Header) 

### ISSUE THREAD

**Issue by christian150590** [GeekyAnts/NativeBase#1824]
## react-native, react and native-base version
- RN 0.55.2
- R 16.3.1
- NB 2.4.2

## Expected behaviour
Typings present
## Actual behaviour
Typings not present
## Steps to reproduce (code snippet or screenshot)

````jsx
<Header hasSubtitle={true}></Header>
````
> Property 'hasSubtitle' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Header> & Readonly<{ children?: ReactNode; }> & Re...'.

````jsx
<Header span={true} ></Header>
````
> Property 'span' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Header> & Readonly<{ children?: ReactNode; }> & Re...'.
## Screenshot of emulator/device
n/a
## Is the bug present in both ios and android or in any one of them?
Yes

**Comment by SupriyaKalghatgi** [comment]
Fixed with [2.4.3](https://github.com/GeekyAnts/NativeBase/releases/tag/v2.4.3)
