### ISSUE TITLE
floating label style is not working when isFocused=true

### ISSUE THREAD

**Issue by c3098051** [GeekyAnts/NativeBase#1826]
## react-native, react and native-base version

- react-native: 0.54.4
- react: 16.3.0-alpha.1
- native-base: 2.4.1

## Expected behaviour

```
<Item floatingLabel>
  <Label style={{fontSize: 5}}/>
</Item>
```
should refelct fontsize when `isFocused=true`

## Actual behaviour

FontSize is changed to the default value ("which is 15")

## Any other additional info which would help us debug the issue quicker.

src/basic/Item.js 

line: 77 
`let labelStyle = StyleSheet.flatten({ fontSize: 15, lineHeight: 30 }, labelProps.style);`

bugfix
`StyleSheet.flatten([{ fontSize: 15, lineHeight: 30 }, labelProps.style])`?

**Comment by akhil-geekyants** [comment]
@c3098051 this is as designed. Only fontSize and lineHeight are given a fixed value onFocus. You can still change other style values like color.

**Comment by c3098051** [comment]
@akhil-geekyants understood.. but I need to use customised fontSize for the label only when it is 
onFocus.. is there recommended way to achieve this?

**Comment by tokict** [comment]
you can overwrite this by specifying the fontSize inline on the <Label>, at least it works for me in 2.12.1
