### ISSUE TITLE
Is there a way to generate an image resource for native base icons?

### ISSUE THREAD

**Issue by liuzhen2008** [GeekyAnts/NativeBase#183]
Is there a way to generate an image resource for native base icons?

I know that react-native-vector-icon is able has a getImageResource function. Not quite sure how to access that method in native-base.

**Comment by himanshu-sahusoft** [comment]
Added getImageSource function with [this commit](https://github.com/GeekyAnts/NativeBase/commit/eb2e79afe3990295f1459fe5632832d680b5d3cc). It will be available in the next release.
