### ISSUE TITLE
labels for FABs

### ISSUE THREAD

**Issue by ctaggart** [GeekyAnts/NativeBase#1831]
It would be awesome if [FABs](https://docs.nativebase.io/Components.html#fabs-def-headref) added labels like other libraries, for example:
https://github.com/mastermoo/react-native-action-button

## react-native, react and native-base version
latest, "native-base": "^2.4.2",

## Expected behaviour
I can add a label to a FAB

**Comment by SupriyaKalghatgi** [comment]
@ctaggart Thank you for suggestion
We will keep it in our list

**Comment by ctaggart** [comment]
Cool, where is your list?

**Comment by LucasMonteiro1** [comment]
Any updates?

**Comment by fishheadcode** [comment]
I would also love that feature! :)

**Comment by ansarikhurshid786** [comment]
any update

**Comment by ansarikhurshid786** [comment]
@SupriyaKalghatgi is it available now ?

**Comment by ansarikhurshid786** [comment]
any update ?

**Comment by haseebeqx** [comment]
There is a workaround with flex direction `row reverse`. with further styling you can make it look like what you want

```js
 <Fab
      active={active}
      direction="up"
      position="bottomRight"
      containerStyle={{ flexDirection: "row-reverse" }}
      primary
    >
```

you can add Text inside button like this. But you may have to set a width 
```js
<Button
        style={ { 
    width: 130 , 
    justifyContent: 'center',
    paddingTop: 10,
    paddingBottom: 10,
    paddingRight: 20,
    paddingLeft: 10,}}
      >
<Text>Button content</Text>
<Icon name="add" />
</Button>
```

**Comment by ahteshamshah780** [comment]
Any update in this I also want to add labels to the FABs.

**Comment by okechukwu0127** [comment]
@haseebeqx  is right.
I did some adjustment to the codes and it worked out 100% fine.


`
                              <Button
                              
                                style={ { 
                                  width: this.state.FabActive?150:40 , 
                                  justifyContent: 'center',
                                  paddingTop: 10,
                                  paddingBottom: 10,
                                  paddingRight: 20,
                                  paddingLeft: 10,
                                  backgroundColor: 'rgba(52, 52, 52, 0.0)', 
                                  shadowOffset: { height: 0, width: 0 },
                                  shadowOpacity: 0,
                                  elevation:0
                              }}>

                                        <Text style={{marginRight:7}}> {this.state.FabActive?'Button content':null}</Text>
                                        
                                        <View style={{
                                          height:40,
                                          width: 46,
                                          marginRight:-20, 
                                          backgroundColor: '#3B5998',
                                          justifyContent:'center',
                                          alignContent:'center',
                                          borderRadius:28
                                        }}>
                                              <Icon  name="logo-facebook" />
                                          </View>

                              </Button>

`

Had to hide and show the content of the text depending on the Fab state.

**Comment by DrSchmurge** [comment]
> @haseebeqx is right.
> I did some adjustment to the codes and it worked out 100% fine.
> 
> `
> 
> ```
>                       <Button    
>                             style={ { 
>                               width: this.state.FabActive?150:40 , 
>                               justifyContent: 'center',
>                               paddingTop: 10,
>                               paddingBottom: 10,
>                               paddingRight: 20,
>                               paddingLeft: 10,
>                               backgroundColor: 'rgba(52, 52, 52, 0.0)', 
>                               shadowOffset: { height: 0, width: 0 },
>                               shadowOpacity: 0,
>                               elevation:0
>                           }}>
> 
>                                     <Text style={{marginRight:7}}> 
>                                           {this.state.FabActive?'Button content':null}
>                                       </Text>
>                                     
>                                     <View style={{
>                                       height:40,
>                                       width: 46,
>                                       marginRight:-20, 
>                                       backgroundColor: '#3B5998',
>                                       justifyContent:'center',
>                                       alignContent:'center',
>                                       borderRadius:28
>                                     }}>
>                                           <Icon  name="logo-facebook" />
>                                       </View>
> 
>                           </Button>
> ```
> 
> `
> 
> Had to hide and show the content of the text depending on the Fab state.

great thanks for sharing your code. Brilliant workaround!

**Comment by AlexAppiahBoateng** [comment]
You can also workaround with

          <Fab
            containerStyle={appTheme.fabContainerStyle}
            style={appTheme.fabStyle}
            position="bottomRight"
            direction="up"
            active={fabActive}
            // onPress={() => this.onRefresh()}
            onPress={() => this.setState({ fabActive: !fabActive })}
          >
            <View>
              <Text
                style={{
                  ...appTheme.headMaxi,
                  position: "absolute",
                  right: width(10),
                  color: appColors.appBlue,
                }}
              >
                New
              </Text>
              <Icon name="ios-add" style={appTheme.fabIconStyle} />
            </View>
          </Fab>

**Comment by AlexAppiahBoateng** [comment]
You can also workaround with FAB

          <Fab
            containerStyle={styles.fabContainerStyle}
            style={styles.fabStyle}
            position="bottomRight"
            direction="up"
            active={fabActive}
            // onPress={() => this.onRefresh()}
            onPress={() => this.setState({ fabActive: !fabActive })}
          >
            <View>
              <Text
                style={{
                  position: "absolute",
                  right: 50,
                  color: 'blue',
                  backgroundColor: 'white',
                  elevation: 2,
                  padding: 2
                }}
              >
                New
              </Text>
              <Icon name="ios-add" style={appTheme.fabIconStyle} />
            </View>
            {fabActive && (
              <Button style={{ backgroundColor: "#34A34F" }}>
                <Text
                  style={{
                    position: "absolute",
                    right: 50,
                    color: 'blue',
                    backgroundColor: 'white',
                    elevation: 2,
                    padding: 2
                  }}
                >
                  Invoice
                </Text>
                <Icon name="logo-whatsapp" />
              </Button>
            )}
          </Fab>

**Comment by xelahaippa** [comment]
<Fab
containerStyle={styles.fabContainerStyle}
style={styles.fabStyle}
position="bottomRight"
direction="up"
active={fabActive}
// onPress={() => this.onRefresh()}
onPress={() => this.setState({ fabActive: !fabActive })}
>
<View>
  <Text
    style={{
      position: "absolute",
      right: 50,
      color: 'blue',
      backgroundColor: 'white',
      elevation: 2,
      padding: 2
    }}
  >
    New
  </Text>
  <Icon name="ios-add" style={appTheme.fabIconStyle} />
</View>
{fabActive && (
  <Button style={{ backgroundColor: "#34A34F" }}>
    <Text
      style={{
        position: "absolute",
        right: 50,
        color: 'blue',
        backgroundColor: 'white',
        elevation: 2,
        padding: 2
      }}
    >
      Invoice
    </Text>
    <Icon name="logo-whatsapp" />
  </Button>
)}
</Fab>

**Comment by xelahaippa** [comment]
Another work around with FAB


          <Fab
          containerStyle={styles.fabContainerStyle}
          style={styles.fabStyle}
          position="bottomRight"
          direction="up"
          active={fabActive}
          // onPress={() => this.onRefresh()}
          onPress={() => this.setState({ fabActive: !fabActive })}
          >
          <View>
            <Text
              style={{
                position: "absolute",
                right: 50,
                color: 'blue',
                backgroundColor: 'white',
                elevation: 2,
                padding: 2
              }}
            >
              New
            </Text>
            <Icon name="ios-add" style={appTheme.fabIconStyle} />
          </View>
          {fabActive && (
            <Button style={{ backgroundColor: "#34A34F" }}>
              <Text
                style={{
                  position: "absolute",
                  right: 50,
                  color: 'blue',
                  backgroundColor: 'white',
                  elevation: 2,
                  padding: 2
                }}
              >
                Invoice
              </Text>
              <Icon name="logo-whatsapp" />
            </Button>
          )}
          </Fab>
