### ISSUE TITLE
Picker doesn't get styled

### ISSUE THREAD

**Issue by SirPhemmiey** [GeekyAnts/NativeBase#1832]
Hi, no matter how i style the picker, it won't style. I even had to copy and paste the same codes from the docs, still the same. What could be the problem please?
`"native-base": "^2.4.1",
    "react": "16.3.1",
    "react-native": "0.55.2",`

**Comment by SupriyaKalghatgi** [comment]
@SirPhemmiey Share your code snippet along with output

**Comment by SupriyaKalghatgi** [comment]
@SirPhemmiey We confirmed Picker use cases from Docs, with React 16.3.1, React Native 0.55.2 and latest of NativeBase, did not find any issues

Do go through docs

**Comment by SupriyaKalghatgi** [comment]
You can refer https://github.com/GeekyAnts/NativeBase-KitchenSink
