### ISSUE TITLE
testing components with enzyme

### ISSUE THREAD

**Issue by developerium** [GeekyAnts/NativeBase#1834]
Hi guys, Thanks for great work in NativeBase. My project looks like this:
react-native 0.51.0
native-base 2.3.5
emzyme 3.3.0
jest 20.0.4

I'm having difficulty using enzyme to render my components.
What I'm trying to achieve is to render a component, which has included a number of NativeBase components. I'm encountering several warnings for instance:

`Warning: <Text /> is using incorrect casing. Use PascalCase for React components, or lowercase for HTML elements.`

and

`          Warning: React does not recognize the `allowFontScaling` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `allowfontscaling` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
          in Text
          in Text (at Text.js:30)
          in Text
          in Styled(Text)
`

My guess is that enzyme was not able to determine correct environment and thinks we are in React.
any hints what should I do to fix this?

![image](https://user-images.githubusercontent.com/7695492/39240018-dc8bf58c-4897-11e8-9ca6-cb95c7a1eb4b.png)

**Comment by JungleCatSW** [comment]
did you find a solution to this ?

**Comment by kurtogath** [comment]
I solved this error adding the `dive()` method on the test as you can see in the next image. 

![zero](https://user-images.githubusercontent.com/29205148/41023345-7b642c3e-696c-11e8-9c60-66e6e0f93f93.PNG)

Then in App i got this. 

![dos](https://user-images.githubusercontent.com/29205148/41023359-847b096e-696c-11e8-8a4e-8e82103bf334.PNG)

This worked for me, hope it hepls

**Comment by SupriyaKalghatgi** [comment]
@MrTinyByte can you check this?

**Comment by pavilion** [comment]
Having the same issue. Apparently the tests run good, but that warning do appear.

**Comment by al-shivani** [comment]
I am also facing the same issue, any solution?

**Comment by Macht59** [comment]
Following solved the problem for me
```
it('has appropriate title', () => {
    const wrapper = shallow(<MyHeader title="title123" />);
    expect(wrapper.contains(<Title>title123</Title>)).toBe(true);
});
```
