### ISSUE TITLE
Multiple props missing from typings (Picker, Header, SwipeRow, Toast)

### ISSUE THREAD

**Issue by christian150590** [GeekyAnts/NativeBase#1838]
## react-native, react and native-base version
- RN 0.55.2
- R 16.3.1
- NB 2.4.2

## Expected behaviour
Typings present
## Actual behaviour
Typings not present
## Steps to reproduce (code snippet or screenshot)
````jsx
<Picker iosIcon={<Icon name="ios-arrow-down-outline" />}></Picker>
````
> Property 'iosIcon' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Header> & Readonly<{ children?: ReactNode; }> & Re...'.
````jsx
<Picker note={false}></Picker>
````
> Property 'note' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Header> & Readonly<{ children?: ReactNode; }> & Re...'.

````jsx
<Picker renderHeader={backAction =>
                        <Header>
                          <Left>
                            <Button transparent onPress={backAction}>
                              <Icon name="arrow-back"/>
                            </Button>
                          </Left>
                          <Body>
                            <Title>Your Header</Title>
                          </Body>
                          <Right />
                        </Header>}></Picker>
````
> Property 'renderHeader' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Header> & Readonly<{ children?: ReactNode; }> & Re...'.

```jsx
<SwipeRow style={{ backgroundColor: '#9370DB' }} />
```
> Property 'style' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Header> & Readonly<{ children?: ReactNode; }> & Re...'.

```jsx
<Header hasSegment={true} />
```
> Property 'hasSegment' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Header> & Readonly<{ children?: ReactNode; }> & Re...'.

```jsx
<Content padder>
          <Button
            onPress={() =>
              Toast.show({
                text: "Wrong password!",
                buttonText: "Okay",
                buttonTextStyle: { color: "#008000" },
                buttonStyle: { backgroundColor: "#5cb85c" }
              })}
          >
            <Text>Toast</Text>
          </Button>
        </Content>
```
> Property 'buttonTextStyle' and 'buttonStyle' do not exist on type
## Screenshot of emulator/device
n/a
## Is the bug present in both ios and android or in any one of them?
Yes

**Comment by SupriyaKalghatgi** [comment]
Fixed with [2.4.3](https://github.com/GeekyAnts/NativeBase/releases/tag/v2.4.3)
