### ISSUE TITLE
Support <Header /> with only one button icon on the right

### ISSUE THREAD

**Issue by wan54** [GeekyAnts/NativeBase#184]
Currently I use this workaround:

```
        <Header>
          <Button transparent>
            <Icon name='ios-search' style={{ width: 0, height: 0 }}/>
          </Button>
          <Title>Header</Title>
          <Button transparent>
            <Icon name='ios-search' />
          </Button>
        </Header>
```

Cheers.

**Comment by SupriyaKalghatgi** [comment]
@wan54 Can you share an example snippet for same?

**Comment by sankhadeeproy007** [comment]
`iconRight` prop with header should do it @SupriyaKalghatgi

**Comment by sankhadeeproy007** [comment]
![screen shot 2016-10-14 at 2 05 06 pm](https://cloud.githubusercontent.com/assets/10998047/19380982/4c3e5aa2-9217-11e6-8870-fbd5d1f72cde.png)
@SupriyaKalghatgi

**Comment by devanshsadhotra** [comment]
@sankhadeeproy007 iconRight is not working

**Comment by shivrajkumar** [comment]
@devanshsadhotra With NativeBase v2.x, the use case has changed. Check the [docs](ocs.nativebase.io) for the latest.

**Comment by devanshsadhotra** [comment]
@shivrajkumar ur link is not working

**Comment by shivrajkumar** [comment]
Ah! my bad check [this](http://docs.nativebase.io/)

**Comment by devanshsadhotra** [comment]
i have referred to this and have customized accordingly , but my icons are there at the center , no customization in theme is working !! @shivrajkumar  if u can suggest something ?

**Comment by shivrajkumar** [comment]
@devanshsadhotra Your code snippet and a screenshot of your output will be helpful here.

**Comment by devanshsadhotra** [comment]
![screenshot_1500906735](https://user-images.githubusercontent.com/15092405/28528464-5c42769a-70ab-11e7-8f40-eb913b1589e9.png)
 @shivrajkumar  i have attached the screenshot 
` <Header hasTabs style={{backgroundColor:'#32A1FE'}} >
        <Body>
        </Body>
          <Right>
            <Button transparent>
              <Icon name='search' />
            </Button>
          </Right>
          <Right>
            <Button transparent>
              <Icon name='person' />
            </Button>
          </Right>
          <Right>
            <Button transparent>
              <Icon name='notifications' />
            </Button>
          </Right>`

All i am left with is , to decrease this gap and introduce an image in <Body>. facing problem in that

**Comment by devanshsadhotra** [comment]
` <Header hasTabs style={{backgroundColor:'#32A1FE'}} >
        <Body>
        </Body>
          <Right>
            <Button transparent>
              <Icon name='search' />
            </Button>
          </Right>
          <Right>
            <Button transparent>
              <Icon name='person' />
            </Button>
          </Right>
          <Right>
            <Button transparent>
              <Icon name='notifications' />
            </Button>
          </Right>`

**Comment by devanshsadhotra** [comment]
![screenshot_1500906735](https://user-images.githubusercontent.com/15092405/28528636-e4b95eee-70ab-11e7-8166-7b44601c0c2d.png)

**Comment by shivrajkumar** [comment]
@devanshsadhotra It should be something like this
```
<Header>
     <Left> //Buttons that you need on Left </Left>
     <Body> //Buttons that you need on Center </Body>
     <Right> //Buttons that you need on Right </Right>
</Header>
```

**Comment by devanshsadhotra** [comment]
@shivrajkumar  this is exactly i have done , but the gap between <Right> buttons is way too much and i am not finding a way to decrease it

**Comment by shivrajkumar** [comment]
@devanshsadhotra You can just use flex properties for that
