### ISSUE TITLE
Statusbar content become white when open Actionsheet

### ISSUE THREAD

**Issue by ZeroCool00** [GeekyAnts/NativeBase#1840]
I using dark-content statusbar on root in app.js but when actionsheet open `statusbar content` become white on white background.

```
<Root style={styles.container}>
          <StatusBar
            backgroundColor="white"
            barStyle="dark-content"
          />
          {this.spinerRender()}
      </Root>
```

code for actionsheet
```
<TouchableOpacity
          style={{ flex: 1 }}
          onPress={() =>
            ActionSheet.show(
                {
                  options: BUTTONS,
                  cancelButtonIndex: CANCEL_INDEX,
                  title: 'Options'
                },
                buttonIndex => {
                  this.setState({ clicked: BUTTONS[buttonIndex] });
                }
              )}
        >
```
status content is not visible when actionsheet open
![screenshot_20180426-154631](https://user-images.githubusercontent.com/18139594/39300571-c7dc5226-4969-11e8-9fc0-633bde38afca.png)

**Comment by akhil-geekyants** [comment]
@ZeroCool00 related to react-native issue https://github.com/react-native-community/react-native-modal/issues/50

**Comment by ZeroCool00** [comment]
@akhil-geekyants  Finally fix it.  just need to add this [lib](https://github.com/listenzz/react-native-modal-translucent)
