### ISSUE TITLE
Attempts to access ref on any Native Base component results in crash.

### ISSUE THREAD

**Issue by RoninSTi** [GeekyAnts/NativeBase#1842]
Hi! Thanks for trying out NativeBase!
Due to the overwhelming requests and issues/questions we ask you to add the following details with your issue.

Please check the existing open/closed issues for a possible duplicate before creating a new issue :)

Also **DO** fill out the below form to give us a better idea about your environment and help us debug it quicker. Issues without the required details will mostly be unattended to.

## react-native, react and native-base version
react-native: 25.0.0
react: 16.2.0
native base: 2.4.3
## Expected behaviour
Ability to access ref shouldn't crash
## Actual behaviour
Any attempts to access the ref of a native base component results in crash
## Steps to reproduce (code snippet or screenshot)
```
<Tabs ref={t => { this._tabs = t }}>...</Tabs>
```
## Screenshot of emulator/device

No screenshot abailable, app crashes.
## Is the bug present in both ios and android or in any one of them?
Both
## Any other additional info which would help us debug the issue quicker.

I've tried with a standard react native component and can get the ref fine, any native base component fails.

**Comment by akhil-geekyants** [comment]
@RoninSTi checked this with native-base version 2.4.3.Checked ref using `<Input/>` component. Can you try upgrading react and react-native packages. If this issue still occurs, can you post a sample code for us to reproduce. Attaching a gif.

Gif

![ref](https://user-images.githubusercontent.com/27768184/39508572-af41fa54-4e00-11e8-8273-c444a164afc9.gif)
