### ISSUE TITLE
Question | Superscript support

### ISSUE THREAD

**Issue by ronilitman** [GeekyAnts/NativeBase#1846]
Hi! Thanks for a great library which makes my life a lot easier!

One small question: I could not find any good support for a replacement for HTML's **sub** and **sup** elements in react native, and I have not seen anything like this on NativeBase docs. Do you happen to have such support or plan to implement it on the future? All the solutions I have seen are hacky, which involve playing with line height and height.

Thanks in advance!

**Comment by SupriyaKalghatgi** [comment]
#38
