### ISSUE TITLE
update native base latest version

### ISSUE THREAD

**Issue by accateo** [GeekyAnts/NativeBase#1849]
Hi! 
I'm using the  2.3.1 version of native-base, but I want to upgrade it. I did:

npm install native-base@latest -g

and the command worked fine. After that I did:

node node_modules/native-base/ejectTheme.js

and also here ok. But why when I do npm outdated I always see that my current version is 2.3.1 and not 2.4.3?
Thanks

**Comment by akhil-geekyants** [comment]
@accateo This may be due to the presence of lock files. Can you try updating the package.json with the latest native-base version(2.4.3), delete the lock files(yarn.lock and package-lock.json), delete the node modules and run `yarn` or `npm install`.
