### ISSUE TITLE
Picker Item text Font family

### ISSUE THREAD

**Issue by alihesari** [GeekyAnts/NativeBase#1853]
I use `textStyle` and `itemTextStyle` to change font family in Picker text item but doesn't work.
Can anyone help me?

```
<Picker
              mode="dropdown"
              selectedValue={this.state.selectedProvince}
              onValueChange={() => { }}
              textStyle= {{
                fontFamily: 'IRANSans'
              }}
              >
              {Object.keys(this.state.provinces).map((key) => {
                return (<Picker.Item label={this.state.provinces[key]} value={key} key={key} />)
              })}
</Picker>
```

and

```
<Picker
              mode="dropdown"
              selectedValue={this.state.selectedProvince}
              onValueChange={() => { }}
              itemTextStyle= {{
                 fontFamily: 'IRANSans'
              }}
              >
              {Object.keys(this.state.provinces).map((key) => {
                return (<Picker.Item label={this.state.provinces[key]} value={key} key={key} />)
              })}
</Picker>
```

**Comment by akhil-geekyants** [comment]
@alihesari  checked this. Changing font family is working fine. Check whether the fontFamily is supported. Attaching a gif.

Gif
![fontstyle](https://user-images.githubusercontent.com/27768184/39516785-98df60ba-4e1b-11e8-9257-6200da93eff2.gif)

**Comment by alihesari** [comment]
@akhil-geekyants Hi, I'm using a Persian font named `IRANSans`. This font does not work on `Picker` and worked on other tag such `<Text>`

**Comment by akhil-geekyants** [comment]
@alihesari tried with IRANSansWeb. Attaching a gif.

Gif

![fontsupport](https://user-images.githubusercontent.com/27768184/39689906-f6d71f04-51f5-11e8-8bc9-e0d473735a25.gif)

**Comment by behzad888** [comment]
@akhil-geekyantsIt's not working on Android, I think this issue should reopen.

**Comment by alihesari** [comment]
@akhil-geekyants You are testing Font-family on `<Text>` tag, but We have this problem in the `<Picker>` and `<Picker.Item>` for Android.  😄😃 Did you know what I mean?

**Comment by alihesari** [comment]
@behzad888 Hi, Behzad I think this is a React Native problem on Android. Please read this #1885 
Also you can use this https://github.com/sohobloo/react-native-modal-dropdown
