### ISSUE TITLE
Floating Label Input text goes on second line

### ISSUE THREAD

**Issue by gibbsfromncis** [GeekyAnts/NativeBase#1854]
Hi! Thanks for trying out NativeBase!
Due to the overwhelming requests and issues/questions we ask you to add the following details with your issue.

Please check the existing open/closed issues for a possible duplicate before creating a new issue :)

Also **DO** fill out the below form to give us a better idea about your environment and help us debug it quicker. Issues without the required details will mostly be unattended to.

## react-native, react and native-base version
**react** 16.3.1
**react-native** 0.55.3
**native-base** 2.4.3
## Expected behaviour

Text should stay one line as other types of Items (fixed etc.)

## Actual behaviour

When user blur of Input text goes on two lines 

## Steps to reproduce (code snippet or screenshot)

1) Copy simple code:
```
<Form>
  <Item floatingLabel>
    <Label>Test</Label>
    <Input />
  </Item>
</Form>
```
2) Put text longer than input width

## Screenshot of emulator/device

When typing everything is OK:
<img width="327" alt="screenshot 2018-05-01 18 40 01" src="https://user-images.githubusercontent.com/35899973/39482383-24efcad4-4d6f-11e8-8923-66c15e9dc660.png">

When blur text goes on second line:
<img width="321" alt="screenshot 2018-05-01 18 40 21" src="https://user-images.githubusercontent.com/35899973/39482396-32176834-4d6f-11e8-9d01-9f9d147925e8.png">

## Is the bug present in both ios and android or in any one of them?
Tested only on iOS

**Comment by SupriyaKalghatgi** [comment]
@gibbsfromncis This is not happening with 2.7.1
Would you like to check?

**Comment by SupriyaKalghatgi** [comment]
@gibbsfromncis Closing this today in case of no response

**Comment by gibbsfromncis** [comment]
@SupriyaKalghatgi If I remember correct it works fine now. Sorry for no response I was on vacation
