### ISSUE TITLE
Tabs automatic scrolling same as issue #683

### ISSUE THREAD

**Issue by grean** [GeekyAnts/NativeBase#1858]
Hi there,

When textAlign style is on 'center' or 'right', the tab scrolls to the second.

## react-native, react and native-base version
react-native V0.55.2, react V16.3.1, native-base V2.4.3
## Expected behaviour
Not scrolling when style is textAlign center or right
## Actual behaviour
scrolling on the next tab
## Steps to reproduce (code snippet or screenshot)
Same behavior as screenshot on issue #683
## Is the bug present in both ios and android or in any one of them?
i only test android.
## Any other additional info which would help us debug the issue quicker.
When you write lots of text in the input, the tab scrolls weirdly but not entirely to the next tab.

**Comment by akhil-geekyants** [comment]
@grean checked this. Couldn't see anything like you mentioned. Attaching a gif.

Gif
![tabs](https://user-images.githubusercontent.com/27768184/39563759-144975e8-4ecf-11e8-8db4-2cadc9887810.gif)

Tested code
```
import React, { Component } from 'react';
import { Container, Header, Content, Form, Item, Input, Tabs, Tab, TabHeading, Text, Icon } from 'native-base';
export default class App extends Component {
  render() {
    return (
      <Container>
        <Header />
        <Form>
          <Item>
            <Input placeholder="Name" />
          </Item>
        </Form>
        <Tabs>
          <Tab heading="Tab one">
            <Text>Tab one</Text>
            <Form>
              <Item>
                <Input placeholder="E-mail" style={{ textAlign: "center" }} />
              </Item>
            </Form>
          </Tab>
          <Tab heading="Tab two">
            <Text>Tab two</Text>
          </Tab>
        </Tabs>
      </Container>
    );
  }
}
```

**Comment by grean** [comment]
Hi, thanks for the reply.

I tested your exemple in my context and it doesn't change nothing. It's exactly the same behavior.
I join 2 gifs with my tests
First with textAlign left with a bug when the input is fully filled, focus is lost and tab is moving a bit.
![bugtableftalign](https://user-images.githubusercontent.com/170967/39587691-6589e41c-4efa-11e8-86e8-534ac0f5721b.gif)

and an other exemple with textAlign center (or right, it's the same) We can see that when a get focus on input a can write a char but it changes the tab immediatly and then when i get the focus again it changes the tab immediatly.
![bugtabcenteralign](https://user-images.githubusercontent.com/170967/39587810-b39a8198-4efa-11e8-88d4-41030a864a42.gif)

I'm on windows 10 and i use the react native get started tutorial emulator, i join a png of its settings.
![androidemulatorinfo](https://user-images.githubusercontent.com/170967/39588153-7aa175c6-4efb-11e8-8e2d-f8d9874b5d5f.png)

**Comment by akhil-geekyants** [comment]
@grean this happens till Android api version 23. Works fine from api version 24 onwards.

**Comment by grean** [comment]
Ok i've just tested with an emulator with android 7.0 x86_64 api 24 and indeed it works fine :)
But what about users who are using devices on android 6.x and below ? do you think users get the bad behavior ?
And on the react native get started page, the RN team [preconize](https://facebook.github.io/react-native/docs/getting-started.html) :

> Android Studio installs the latest Android SDK by default. Building a React Native app with native code, however, requires the Android 6.0 (Marshmallow) SDK **in particular**. Additional Android SDKs can be installed through the SDK Manager in Android Studio.

What about this case of compatibility ?

**Comment by akhil-geekyants** [comment]
See open issue #550
