### ISSUE TITLE
CheckBox not tapable if checked bind to a state object property, work fine when bind single value

### ISSUE THREAD

**Issue by tnguyen-lh** [GeekyAnts/NativeBase#1859]
## react-native, react and native-base version
    "react-native": "0.54.2",
    "native-base": "^2.3.10",

## Expected behaviour
In summary: 
if I have 
this.state = {
      qualified: false
}
and bind checked={this.state.qualified}, it is working fine
HOWEVER if I have 
this.state = {
      registration: {qualified: false}
}
and bind checked={this.state.registration.qualified} , it is NOT working

```
this.state = {
      qualified: false
}
<CheckBox checked={this.state.qualified} onPress={() => this.setState({qualified: !this.state.qualified}) }/>
						
``` 
This is not working
```
this.state = {
      registration: {qualified: false}
}
<CheckBox checked={this.state.registration.qualified} onPress={() => this.setState({registration: {qualified: !this.state.restrigation.qualified}}) }/>
						
```

**Comment by akhil-geekyants** [comment]
@tnguyen-lh check this Stackoverflow question https://stackoverflow.com/questions/43638938/updating-an-object-with-setstate-in-react

**Comment by akhil-geekyants** [comment]
Not a NativeBase issue. 
Closing this issue.
