### ISSUE TITLE
SwipeRow Remove Separator

### ISSUE THREAD

**Issue by teddyteh** [GeekyAnts/NativeBase#1868]
How do you remove the separator below a SwipeRow? Tried adding borderBottomWidth: 0 and borderColor: 'transparent' to styles as well as adding the noBorder prop but none worked.

**Comment by akhil-geekyants** [comment]
@teddyteh setting SwipeRow style borderBottomWidth to 0 is working for me. Attaching a gif

Code
```
<SwipeRow
            style={{ borderBottomWidth: 0 }}
             ...
/>
```
Gif

![swiperow](https://user-images.githubusercontent.com/27768184/39699231-d880832c-5215-11e8-973c-b65aca088473.gif)
