### ISSUE TITLE
Gitstrap not working for paid themes

### ISSUE THREAD

**Issue by skyride99** [GeekyAnts/NativeBase#187]
This one is driving me crazy should be simple
gitstrap init <gitstrap-repo> <my-repo> 

gitstrap init FlatApp-seed myRepo

the repo is never found what is the repo?

**Comment by SupriyaKalghatgi** [comment]
@skyride99 gitstrap init <upstream-repo> <my-repo>
You considered `FlatApp-seed` to be upstream-repo and `myRepo` as origin
But you need to include the git-url for these repo and not their names.
[GitStrap CLI Tools](http://strapmobile.com/docs/react-native-flat-app-theme/v4.0.0/installation/gitstrap-cli-tools)

**Comment by himanshu-sahusoft** [comment]
Not related to NativeBase. Please contact support for any issues related to paid themes.
