### ISSUE TITLE
you closed #1815 without fixing it. 

### ISSUE THREAD

**Issue by r3wt** [GeekyAnts/NativeBase#1870]
Hi! Thanks for trying out NativeBase!
Due to the overwhelming requests and issues/questions we ask you to add the following details with your issue.

Please check the existing open/closed issues for a possible duplicate before creating a new issue :)

Also **DO** fill out the below form to give us a better idea about your environment and help us debug it quicker. Issues without the required details will mostly be unattended to.

**Comment by r3wt** [comment]
please reopen #1815

**Comment by SupriyaKalghatgi** [comment]
@r3wt #1815 was closed due to improper language

**Comment by r3wt** [comment]
improper language? the only improper language in that thread was posted 2 week ago and the message was edited to remove the improper language. you just closed that issue out of spite.

**Comment by akhil-geekyants** [comment]
@r3wt can you try this
```
export default class App extends React.Component {

  componentDidMount = () => {
    this._tab.goToPage(2);
  }

  render() {
    return <Container>
      <Tabs ref={(c) => this._tab = c}>
        <Tab heading="Tab1" >
          <Text>Tab one</Text>
        </Tab>
        <Tab heading="Tab2">
          <Text>Tab two</Text>
        </Tab>
        <Tab heading="Tab3">
          <Text>Tab three</Text>
        </Tab>
      </Tabs>
    </Container>
  }
}
```
based on issue-comment https://github.com/GeekyAnts/NativeBase/issues/1010#issuecomment-355668551

**Comment by mjugger** [comment]
@akhil-geekyants 
this causes the tab header to match the page index fed to `goToPage` method but does not actually change the tab unless you use `setTimeout` which make it similar to @hernanbruno97 solution. For now, it looks like both solutions are viable and both will produce the same results with the same side effects (i.e. you will see the tab change when viewing the component each time).

@r3wt I know using roundabout ways along with `setTimeout` to achieve base functionality is dirty, but at this point, I doubt this will be fixed any time soon.
