### ISSUE TITLE
onValueChange not triggered on input based elements for touch events when inside List

### ISSUE THREAD

**Issue by mauron85** [GeekyAnts/NativeBase#1874]
## react-native, react and native-base version
react-native-web: 0.6.1
react: 16.3.2
native-base: 2.4.3

## Expected behaviour
Elements like Switch, Input... doesn't fire onValueChange on mobile browsers and Chrome when switched to emulate touch events and when put inside `<List>`.

How to reproduce:
```
          <List>
            <ListItem itemDivider>
              <Text>iOS</Text>
            </ListItem>
            <ListItem>
              <Body>
                <Text>Test Switch</Text>
              </Body>
              <Right>
                <Switch
                  value={this.state.switch2Enabled}
                  onValueChange={this.toggleSwitch2}
                />
              </Right>
            </ListItem>
          </List>
```
Expecting `this.toggleSwitch2` to be called when Switch is toggled.

## Actual behaviour
`this.toggleSwitch2` is not called when Switch is toggled.

## Steps to reproduce (code snippet or screenshot)
1. Clone repo https://github.com/mauron85/rn-switch-glitch
2. run `yarn` or `npm install`
3. start server: `npm start`
4. In Chrome toggle touch events or use mobile browser
5. Tap on switch

## Is the bug present in both ios and android or in any one of them?
It's present in when using react-native-web, which reading announcement is officially supported by now.
## Any other additional info which would help us debug the issue quicker.
Switch and other input based elements are working fine outside List

**Comment by akhil-geekyants** [comment]
@mauron85 saw your comment here https://github.com/necolas/react-native-web/issues/932#issuecomment-387289765.
Can we close this issue.

**Comment by mauron85** [comment]
@akhil-geekyants Yes. It seems to be more or less react-native-web issue after all. Closing
