### ISSUE TITLE
How to change the width of the Toast?

### ISSUE THREAD

**Issue by rajgour** [GeekyAnts/NativeBase#1877]
Greetings,

## react-native, react and native-base version
    "native-base": "^2.4.2",
    "react": "^16.2.0",
    "react-native": "^0.52.3",

## Expected behaviour
I would like to make the Width of the toast 100% in ios 

## Actual behaviour
Width of the toast is 100% in Android whereas in ios ToastContainer is adding 20pt on each side

## Screenshot of emulator/device
![image](https://user-images.githubusercontent.com/17829755/39759859-cd69f2b6-52a1-11e8-843a-b9e4ecf144be.png)

## Is the bug present in both ios and android or in any one of them?
ios
## Any other additional info which would help us debug the issue quicker.
ToastContainer.js
getToastStyle() {
    return {
      position: "absolute",
      opacity: this.state.fadeAnim,
      width: "100%",
      elevation: 9,
      **paddingHorizontal: Platform.OS === "ios" ? 20 : 0,**
      top: this.state.position === "top" ? this.getTop() : undefined,
      bottom: this.state.position === "bottom" ? this.getTop() : undefined
    };
  }

**Comment by SupriyaKalghatgi** [comment]
@rajgour Well this is not bug!
NativeBase Toast is as per design guidelines, hence takes complete width for Android and not for iOS

You can go ahead customizing NativeBase components as per your project requirement.
To have full width Toast for iOS, you need to modify this line: https://github.com/GeekyAnts/NativeBase/blob/master/src/basic/ToastContainer.js#L29

This is will result in Toast with some borderRadius. To have Toast similar to Android, you can set borderRadius to zero here: https://github.com/GeekyAnts/NativeBase/blob/master/src/theme/components/Toast.js#L17

**Comment by rajgour** [comment]
Is there a way to customize it with variables? I don't see the ToastContainer.js in the components. Can you give me an example?

**Comment by SupriyaKalghatgi** [comment]
@rajgour 

- As I said previously,
> NativeBase Toast is as per design guidelines, hence takes complete width for Android and not for iOS

Hence no readily available variables in this case.

- 
> I don't see the ToastContainer.js in the components.

Check links shared in previous comment.

- 
> I can make changes to make it more customizable by adding props.

Yes you can fork it to have your type of component
