### ISSUE TITLE
How to invoke onPress in FooterTab in 5.8 ? 

### ISSUE THREAD

**Issue by shishircc** [GeekyAnts/NativeBase#188]
I am trying to use footer tab as below. However I am not sure how to include **onPress** for each item in tab. 

FooterTab is great. Looks good and is very useful. Is onPress possible in FooterTab ?

```
<Footer>
  <FooterTab>
    <View active>
      <Icon name="ios-home" />
      <Text>Home</Text>
    </View>
    <View>
      <Icon name="ios-planet" />
      <Text>Explore</Text>
    </View>
    <View>
      <Icon name="ios-search" />
      <Text>Search</Text>
    </View>
  </FooterTab>
</Footer>
```

**Comment by mensar** [comment]
As i code the FooterTab just like the upstair, but it didn't work.there is nothing in footer,can u
help me?

**Comment by sankhadeeproy007** [comment]
Added
