### ISSUE TITLE
@types/react-native >= 0.55.8 incompatible with native-base <= 2.4.3

### ISSUE THREAD

**Issue by Slessi** [GeekyAnts/NativeBase#1880]
https://github.com/DefinitelyTyped/DefinitelyTyped/commit/4abbfb42ff02fbdf3584f6285238d82c4ccbeb14

The above change to the `@types/react-native` package sadly breaks pretty much all RN type extensions in your types

ex:
```ts
interface Picker extends ReactNative.PickerProperties {} // Old
interface Picker extends ReactNative.PickerProps {} // New
```

## react-native, react and native-base version
@ types/react-native: `0.55.8`
native-base: `2.4.3`

Types are compatible up to `0.55.7`

**Comment by akhil-geekyants** [comment]
@Slessi tested with @ types/react-native: 0.55.12, didn't show any error/warning.
Posting Package.json

```
{
  "name": "testAppTs",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "native-base": "^2.4.4",
    "react": "16.3.1",
    "react-native": "0.55.4"
  },
  "devDependencies": {
    "@types/jest": "^22.2.3",
    "@types/react": "^16.3.14",
    "@types/react-native": "^0.55.12",
    "@types/react-test-renderer": "^16.0.1",
    "babel-jest": "22.4.3",
    "babel-preset-react-native": "4.0.0",
    "jest": "22.4.3",
    "react-native-typescript-transformer": "^1.2.5",
    "react-test-renderer": "16.3.1",
    "ts-jest": "^22.4.5",
    "typescript": "^2.8.3"
  },
  "jest": {
    "preset": "react-native",
    "moduleFileExtensions": [
      "ts",
      "tsx",
      "js"
    ],
    "transform": {
      "^.+\\.(js)$": "<rootDir>/node_modules/babel-jest",
      "\\.(ts|tsx)$": "<rootDir>/node_modules/ts-jest/preprocessor.js"
    },
    "testRegex": "(/__tests__/.*|\\.(test|spec))\\.(ts|tsx|js)$",
    "testPathIgnorePatterns": [
      "\\.snap$",
      "<rootDir>/node_modules/"
    ],
    "cacheDirectory": ".jest/cache"
  }
}
```

**Comment by Slessi** [comment]
@akhil-geekyants /shrug

Right you are... Didn't notice there was a `legacy-properties.d.ts` - my project doesn't use it for some reason

**Comment by cmrigney** [comment]
I have the same issue. @akhil-geekyants I think the reason you don't have the issue is because you have the type `"@types/react-native": "^0.55.12"` which equals react-native 0.56.X types.  0.56.X works fine. (I can't use it though because of an Expo limitation).  I bet if you changed it to resolve to `~0.55.12` instead of `^0.55.12` you will see the same issue as the OP.
