### ISSUE TITLE
Issue text overlow on Input component using redux-form with native-base

### ISSUE THREAD

**Issue by mowbell** [GeekyAnts/NativeBase#1881]
I have an issue when I try to use redux-Form Field with native base **Input** component. The input behavior is weird on iOS (simulator and devices). 
## Actual behaviour
When I test the implementation suggested on docs [ReduxForm Example](https://docs.nativebase.io/docs/examples/ReduxFormExample.html)
here suggested code :
~~~~ js
const renderInput = ({
  input, // eslint-disable-line

  // label,
  // type,
  // meta: { touched, error, warning },
  meta: { error }, // eslint-disable-line
}) => (
  // const { value } = input;
  <Item regular>
    <Input {...input} />
  </Item>
);
~~~~
here text overflow issue (input is multiline):
(Also doesn't work putting `multiline` nor `numberOfLines={1}`
## Screenshot of simulator/device
![djpzaupnuv](https://user-images.githubusercontent.com/1444992/39830856-3fd7fd66-5388-11e8-9277-b61ca4a806d1.gif)

## Expected behaviour
If I change `<Input {...input} />`  to `<Input />`
Input behavior works as expected: (text with ellipsis)
## Screenshot of simulator/device
![input working](https://user-images.githubusercontent.com/1444992/39830655-b718c2e4-5387-11e8-94a2-0c7e1e79a54e.gif)
But not redux form doesn't synchronize entered value

I had tried fix it, and I don't found a solution

On Android works better, not multiline, but without elllipsis, doesn't matter
On iOS behavior is noticeable and awful

I trying change nativebase **Input** by default **TextInput**

## react-native, react and native-base version
React-native version 0.54.4
Native-base version 2.4.3 - 2.4.1 - 2.3.7

## Steps to reproduce (code snippet or screenshot)
Follow example [Nativebase - Redux Form example](https://docs.nativebase.io/docs/examples/ReduxFormExample.html)
~~~~ js
const renderInput = ({
  input, // eslint-disable-line

  // label,
  // type,
  // meta: { touched, error, warning },
  meta: { error }, // eslint-disable-line
}) => (
  // const { value } = input;
  <Item regular>
    <Input {...input} />
  </Item>
);
~~~~

## Is the bug present in both ios and android or in any one of them?
On **IOS**

**Comment by akhil-geekyants** [comment]
@mowbell can you try setting style of `<Input/>` to
```
<Item regular>
    <Input {...input} style={{ paddingTop: 3, paddingBottom: 7 }}/>
</Item>
```

**Comment by akhil-geekyants** [comment]
Closing this issue due to no response
