### ISSUE TITLE
Adding a Picker Item 

### ISSUE THREAD

**Issue by VanessaChu** [GeekyAnts/NativeBase#1882]
**FIRST QUESTION**
Adding this line throws the error <Picker.Item label={'create a message'} value={'create'} />
Cannot read property 'value' of undefined
ExceptionsManager.js:63
Unhandled JS Exception: Cannot read property 'value' of undefined

What I want to implement is
First picker item is "Create a Message"
The rest are the messages 

                <Picker
                    style={{ height: 30 }}
                    supportedOrientations={['portrait', 'landscape']}
                    iosHeader={I18n.t('$schedule_choose_file')}
                    mode='dropdown'
                    iosIcon={<Icon darkgray style={styles.chevronRight} name='angle-right' />}
                    selectedValue={this.state.filename}
                    onValueChange={(value) => this._onMessageChange()}
                    textStyle={styles.pickerText}>
                    <Picker.Item label={'create a message'} value={'create'} />
                    {
                      messages.map((message) =>
                        <Picker.Item key={message._id} label={message.title} value={message._id} />
                      )
                    }
                  </Picker>

**SECOND QUESTION:**
How do I add an image to the Picker.Item label? 
label={ <add image here> 'create a message'}

**Comment by akhil-geekyants** [comment]
@VanessaChu you can overcome this issue by adding the `create a message` as the initial item(object) to messages array. You can also check placeHolder prop of Picker for iOS. See docs [here](http://docs.nativebase.io/Components.html#picker-placeholder-headref).

`Picker.Item`'s label is designed to accept only string value for label.  Adding an image to label is not possible as of now.

**Comment by SupriyaKalghatgi** [comment]
Adding an image to the Picker.Item label is not possible since this is not supported by React Native yet
