### ISSUE TITLE
animationEnabled = false props react-native-router-flux

### ISSUE THREAD

**Issue by NguyenPhatBG** [GeekyAnts/NativeBase#1883]
react-native-router-flux lib have animationEnabled props for change to exactly tab when user interact.
Incredible performance apps. Does NativeBase have props similar?

**Comment by akhil-geekyants** [comment]
@NguyenPhatBG you can check the default animation provided by NativeBase tabs [here in docs](http://docs.nativebase.io/Components.html#tabs-def-headref). If you wan't to disable swipe, you can set  the Tabs prop `locked={true}`

**Comment by NguyenPhatBG** [comment]
![capture](https://user-images.githubusercontent.com/33904172/39913990-e49ac1a2-552d-11e8-8d68-69766108bd20.PNG)
I had try before.This is my setting tabs, but it's not work for me!
![capture1](https://user-images.githubusercontent.com/33904172/39914116-3cf38974-552e-11e8-8791-00c009a92114.PNG)
and my tab settings!

**Comment by NguyenPhatBG** [comment]
https://github.com/GeekyAnts/NativeBase/issues/1676
I had try it before, But it's not my mean! I mean that the content while we change tab, it not pass through another content tabs, like animationEnabled = false props react-native-router-flux :)
Can you provide solution for this task !

**Comment by NguyenPhatBG** [comment]
Thanks @akhil-geekyants , It's work now! Have a great day! 👍
