### ISSUE TITLE
Persian fonts doesn't work correctly for Picker in Android

### ISSUE THREAD

**Issue by alihesari** [GeekyAnts/NativeBase#1885]
Please see those images:
In these images you can the use of IRANSansWeb and IRANSansMobile for input and Picker.
IRANSansWeb and IRANSansMobile for input work correctly, but these two fonts for Picker are not working correctly. Why?

![screen shot 1397-02-20 at 10 40 10 am](https://user-images.githubusercontent.com/8302633/39855484-5d5d3a36-5441-11e8-9e11-e06c346b70de.png)
![screen shot 1397-02-20 at 10 43 49 am](https://user-images.githubusercontent.com/8302633/39855485-5d92c0de-5441-11e8-84bb-8fd8b6303f33.png)

**Comment by akhil-geekyants** [comment]
@alihesari checked this. Can you check the gif

Gif
![test](https://user-images.githubusercontent.com/27768184/39864805-783ef07a-5468-11e8-924f-8ce514c8a3b4.gif)

**Comment by alihesari** [comment]
@akhil-geekyants You are checking this problem in IOS, but I have this problem in android!

**Comment by akhil-geekyants** [comment]
@alihesari NativeBase Picker for Android is a direct implementation of React Native Picker. React Native Picker does not allow styling text for Android. See react native Picker docs [here](https://facebook.github.io/react-native/docs/picker.html)

**Comment by akhil-geekyants** [comment]
@alihesari not sure on custom fonts. Found this link for android supported fonts https://stackoverflow.com/a/39141949/5367816

**Comment by alihesari** [comment]
@akhil-geekyants Ok, Thanks. I'll try it.

**Comment by SupriyaKalghatgi** [comment]
@alihesari Can you close this issue then?
