### ISSUE TITLE
How to detect tab change?

### ISSUE THREAD

**Issue by sabbiu** [GeekyAnts/NativeBase#1886]
As, no lifecycle method is called when tab is changed? How to detect onTabChange?

>I wnat to use this.setState of one component when tab is changed.

Tried:

        <Tabs
          initialPage={0}
          tabBarPosition="bottom"
          // onChangeTab={({ i, ref, from }) => console.log(i, ref, from)}
        >

trying onChangeTab as shown above neither outputs console.log() nor changes the tab. The app freezes when doing so.

**Comment by SupriyaKalghatgi** [comment]
@sabbiu https://github.com/skv-headless/react-native-scrollable-tab-view#props

**Comment by sabbiu** [comment]
Turns out, `console.log()` was making my app freeze. Removing that and implementing actual method is working as promised.

**Comment by r-mhjn** [comment]
hey could you please share a code snippet that could help  me implement onChangeTab

**Comment by voold** [comment]
You must not add a console.log.

I hope this is going to be corrected

```javascript
<Tabs
          tabBarUnderlineStyle={styles.tabs}
          onChangeTab={({i}) => setCurrentTab({currentTab: i})}>
          <Tab heading={'My fridge'} {...styles.tab} />
          <Tab heading={'Recipes'} {...styles.tab} />
        </Tabs>
```
