### ISSUE TITLE
Text in Segment Button not Consistent

### ISSUE THREAD

**Issue by ggpw** [GeekyAnts/NativeBase#1888]
Hi! Thanks for this awesome NativeBase!

I got this weird behaviour on text in Segment Button. It text is inconsistent, some device it display actual text, some display it text to be capital case.  

## react-native, react and native-base version
    "react": "16.3.0-alpha.1",
    "react-native": "0.54.4",
    "native-base": "^2.3.3",
## Expected behaviour
   "This Text"
## Actual behaviour
  "THIS TEXT"
## Steps to reproduce (code snippet or screenshot)
```
import {Segment, Button, Text} from "native-base";

<Segment style={segmentHeader}>
  {segmentMenus?
    segmentMenus.map((item, index)=>{
       return (
            <Button key={index} first={index===0} last={index===segmentMenus.length-1}
                  rounded style={segmentButton}
                  active={item===cardType} 
                  onPress={()=>{handleSegmentClick(item)}}>
                  <Text style={segmentTitle}>{i18n(item)}</Text>
             </Button>
        )
     })
    :null}
</Segment>
```

## Screenshot of emulator/device
![segment uppercase](https://user-images.githubusercontent.com/22366085/39906285-f182d12e-550b-11e8-92c0-c4f157fb4f51.PNG)
Segment>Button>Text(Native Base) on Emulator Android Version 4.4.2 Model Number SM-G930K

![segment normal](https://user-images.githubusercontent.com/22366085/39906437-c0255c40-550c-11e8-8548-345077c125ef.PNG)
Segment>Button>Text(Native Base) on Emulator Android Version 4.4.2 Model Number one a2001

![segment normal rn](https://user-images.githubusercontent.com/22366085/39906471-13fa59ec-550d-11e8-8aa1-f07170a55346.PNG)
Segment>Button>Text(React Native) on Emulator Android Version 4.4.2 Model Number SM-G930K

## Is the bug present in both ios and android or in any one of them?
  only tried on android device using emulator
## Any other additional info which would help us debug the issue quicker.
  Component Text that is used is from native base. If used component Text from React Native its display as it should, but the styling from native base is not worked

Once again thank you for the great work

**Comment by akhil-geekyants** [comment]
@ggpw try setting the uppercase props of NativeBase Text to false.

```
<Button><Text uppercase={false}>test</Text></Button>
```

**Comment by ggpw** [comment]
Thanks for the answer. It worked. Didn't know that props exist.
