### ISSUE TITLE
Tab cannot scroll horizontally

### ISSUE THREAD

**Issue by gordonpro** [GeekyAnts/NativeBase#189]
https://github.com/skv-headless/react-native-scrollable-tab-view
react-native-scrollable-tab-view Has a property can control scrolling on tab content to change tab.

`locked` (Bool) - disables horizontal dragging to scroll between tabs, default is false.

but in NativeBase , it is not available.

**Comment by sankhadeeproy007** [comment]
`locked={true}` isn't working?

**Comment by jesouhaite08** [comment]
I noticed rotating the screen horizontal renders tabs incorrectly. In my case I have three tabs and it shows the content of two tabs when I rotate the screen horizontal. Is this a known issue?

**Comment by sankhadeeproy007** [comment]
NativeBase doesn't have 100% support for landscape mode yet. We're working on it.

**Comment by kaielvin** [comment]
Having this issue. Have you tried starting the horizontal scrolling gesture from some content (Text for example) ?

In my case the gesture works fine when started on content, but not when started on some empty container area. Any idea why that would be ?

**Comment by SupriyaKalghatgi** [comment]
#246

**Comment by SupriyaKalghatgi** [comment]
[#246](https://github.com/GeekyAnts/NativeBase/issues/189)

**Comment by sankhadeeproy007** [comment]
Closing this as landscape mode is not high on our priority list.

**Comment by kaielvin** [comment]
wait… how is that related to landscape ?

I personally no longer need that specific feature, but it remains unsolved, and it seems like a pretty major bug to me.

**Comment by sankhadeeproy007** [comment]
Oh, I got confused. I just correlated the word horizontal to landscape. Will look into it. Since we're using scrollable-tab-views for it, we might need to upgrade to a newer version of it maybe.

**Comment by indesignlatam** [comment]
In my case the scroll horizontal scroll works, however it only does when pulling from the edges of the view not on the entire view.

**Comment by kaielvin** [comment]
Yep, same as what I experienced and described in my first comment. I am still not sure if that is the same as gorgonpro's original issue though.

**Comment by sankhadeeproy007** [comment]
Added `edgeHitWidth` prop to Tabs. Default is set to `30`. You can set it to a higher value for easier swiping.
