### ISSUE TITLE
Container component - height prop ignored.

### ISSUE THREAD

**Issue by mjstelly** [GeekyAnts/NativeBase#1892]
Hi! Thanks for trying out NativeBase!
Due to the overwhelming requests and issues/questions we ask you to add the following details with your issue.

Please check the existing open/closed issues for a possible duplicate before creating a new issue :)

Also **DO** fill out the below form to give us a better idea about your environment and help us debug it quicker. Issues without the required details will mostly be unattended to.

## react-native, react and native-base version
"react-native": "^0.55.3",
"native-base": "^2.4.3"
## Expected behaviour
Setting `height` prop in a style should size the component to the designated height in pixels.

## Actual behaviour
`height` prop has no effect. Component sized to the height of the parent container.

## Steps to reproduce (code snippet or screenshot)
```
<Container style={page}>
      <Container style={content}>
        <Label>Height prop using View</Label>
        <Container style={buttons}>
          <Image style={{ backgroundColor: 'green', height: 50, width: 50 }} />
          <Image style={{ backgroundColor: 'blue', height: 50, width: 50 }} />
        </Container>
      </Contaier>
</Container>
```

## Screenshot of emulator/device
![simulator screen shot - iphone 6 - 2018-05-12 at 15 23 37](https://user-images.githubusercontent.com/313819/39960878-ccaf1676-55f8-11e8-89f3-6ee431fbe157.png)
![simulator screen shot - iphone 6 - 2018-05-12 at 15 24 03](https://user-images.githubusercontent.com/313819/39960881-d343bc94-55f8-11e8-924b-ac2ac9ba8fc9.png)

**Comment by akhil-geekyants** [comment]
@mjstelly NativeBase Container is outermost component. Use View instead of Container, to set a specific height.
Read about NativeBase screen structure [here](http://docs.nativebase.io/Components.html#anatomy-headref)

**Comment by SupriyaKalghatgi** [comment]
@mjstelly Closing this issue, since this seems to be wrong use case
