### ISSUE TITLE
Toast and ActionSheet both cause crashes on call

### ISSUE THREAD

**Issue by AleskiWeb** [GeekyAnts/NativeBase#1895]
Hey there,

First of all, great project here. Makes prototyping very quick and basically has almost everything you need for your production application.

However there is two components that are causing me issues (and I see them logged in Firebase Crashlytics a lot) and that is the `Toast` and `ActionSheet`.

![image](https://user-images.githubusercontent.com/8318899/40004000-a64ff2a8-578c-11e8-99c8-af65648b3386.png)

Looking through the issues on this repo, every time it is brought up, it is said that you just have to add `<Root>` as your top-most component to your application. 

Whilst this does work a lot of the time, almost all of the time, there is a specific set of instructions, in a specific order that causes a `cannot call show on undefined`. This happens to both the `Toast` and `ActionSheet`

There have been work arounds suggested, and multiple issues opened and subsequently closed on this particular issue but I am not convinced any of the suggested workarounds have actually worked for very long.

`react-native 0.52.0`
`react 16.3.2` 
`native-base 2.4.3`

Is the bug present in both ios and android or in any one of them? **Both**

**I am following the documentation directly, my topmost component's first child is `<Root>` and the rest of my application is inside of that, including navigation, redux providers, etc.**

**Comment by akhil-geekyants** [comment]
@AleskiWeb can you try adding [this](https://github.com/GeekyAnts/NativeBase/issues/1121#issuecomment-388443807) to your code https://github.com/GeekyAnts/NativeBase/issues/1121#issuecomment-388443807

**Comment by akhil-geekyants** [comment]
@AleskiWeb this issue will be fixed once this PR is merged. See PR https://github.com/GeekyAnts/NativeBase/pull/1700

**Comment by AleskiWeb** [comment]
@akhil-geekyants - In his workaround, he says "main component" is where he added that. Is that the top-most level component or does he mean in the component where the Toast/ActionSheet is instantiated?

Also, thanks for the PR. Means I don't have to find/make an alternative one 👌

**Comment by akhil-geekyants** [comment]
@AleskiWeb it is safer to use it in all components where Toast/ActionSheet is used.

**Comment by AleskiWeb** [comment]
@akhil-geekyants Still getting an issue when adding that unmount workaround. When will the PR likely be merged?

**Comment by kstolte** [comment]
@akhil-geekyants I am also still getting the issue after adding the unmount workaround. I have manually altered my node_module to match the changes to your request and it has resolved my issue entirely. Do we have an ETA on #1700 being merged? I see it has been open since mid-March.

**Comment by AleskiWeb** [comment]
@kstolte I did the same 😂 - just awaiting release

**Comment by SupriyaKalghatgi** [comment]
Will be merged this week, with some new components

**Comment by SupriyaKalghatgi** [comment]
Fixed with [2.5.0](https://github.com/GeekyAnts/NativeBase/tree/v2.5.0)
