### ISSUE TITLE
Missing option iconLeft, iconRight for Icon in InputGroup

### ISSUE THREAD

**Issue by mrphu3074** [GeekyAnts/NativeBase#19]
Hi, 
NativeBase is rapid my prototype, but i have trouble with input, i can't control position of icon.
I hope we can have that options.

thanks.

**Comment by sankhadeeproy007** [comment]
We'll ship that with our next release.

**Comment by mrphu3074** [comment]
many thanks

**Comment by sankhadeeproy007** [comment]
Hi @mrphu3074 , It has been fixed and is available in development branch. Not publishing now as we're planning on adding a few more features for the next release. Pull from the development branch if you need it urgently.
Just include prop `iconRight` with the `<InputGroup/>` component for right icon. Defaults to `iconLeft`.

**Comment by mrphu3074** [comment]
@sankhadeeproy007  great !, many thanks.
