### ISSUE TITLE
Feature Request: Popup Menu

### ISSUE THREAD

**Issue by polygoal** [GeekyAnts/NativeBase#190]
![14435207_1303527736338151_7980872931161391843_o](https://cloud.githubusercontent.com/assets/21036325/18669366/f3298908-7f3a-11e6-8d84-4e4401666390.jpg)
We're missing a cross platform way of displaying popups in Navigation.

I'd like to request this as a feature in nativeBase.

Someone already wrote a component: 
https://github.com/facebook/react-native/issues/3004#issuecomment-202598006

**Comment by sankhadeeproy007** [comment]
Feature requests being tracked here #38

**Comment by zjw199011** [comment]
Hi there, I just want to ask did native base support the popup menu yet? thanks.

**Comment by xstable** [comment]
https://cmichel.io/how-to-create-a-more-popup-menu-in-react-native

**Comment by iamrommel** [comment]
I uses Actionsheet whenever there is a need for menu
