### ISSUE TITLE
footer android look weird

### ISSUE THREAD

**Issue by taeyzzz** [GeekyAnts/NativeBase#1903]
Hello

i try to make footer like this
<img width="448" alt="screen shot 2561-05-17 at 3 29 55 pm" src="https://user-images.githubusercontent.com/32537120/40166117-f8ad5e34-59e7-11e8-9490-bac81959d89d.png">

###
 this is my code
```
import {
  Button,
  Icon,
  Footer,
  FooterTab,
  ActionSheet
} from 'native-base';
```

```
<Footer style={this.getFooterStyle()}>
        <FooterTab style={styles.header}>
          <Button
            vertical
            onPress={() => this.props.navigation.navigate('HomeDashboardStack')}
          >
            <Icon name="home" style={this.getActiveStyle(0)} active={this.props.navigationState.index === 0} />
          </Button>
          <LinearGradient
            start={{x: 0.0, y: 0.25}} end={{x: 1.0, y: 1.0}}
            colors={['#32799f', '#49b8ac', '#53d6a7']}
            style={styles.linearGradient}
          >
            <TouchableOpacity
              onPress={() => this.selectImage()}
              style={styles.diagnoseBtn}
            >
              <Icon name="camera" style={{color: 'white'}}/>
            </TouchableOpacity>
          </LinearGradient>
          <Button
            vertical
            onPress={() => this.props.navigation.navigate('CaseProfileStack')}
          >
            <Icon name="people" style={this.getActiveStyle(1)} active={this.props.navigationState.index === 1} />
          </Button>
        </FooterTab>
      </Footer>
```

### this is result 
In IOS I think it's good for now 
<img width="362" alt="screen shot 2561-05-17 at 2 50 38 pm" src="https://user-images.githubusercontent.com/32537120/40165975-90baee40-59e7-11e8-8a5e-6ec5801a7781.png">

### But in Android circle camera look weird

<img width="359" alt="screen shot 2561-05-17 at 2 51 00 pm" src="https://user-images.githubusercontent.com/32537120/40166025-b5da5cb0-59e7-11e8-90ce-ca2db011a86e.png">

## react-native, react and native-base version
"native-base": "^2.4.4",
 "react": "16.2.0",
 "react-native": "0.55.4",
 "react-navigation": "^1.0.0-beta.11",

### Thank you

**Comment by akhil-geekyants** [comment]
@taeyzzz see this issue https://github.com/GeekyAnts/NativeBase/issues/1260

**Comment by taeyzzz** [comment]
@akhil-geekyants Thank you so much
