### ISSUE TITLE
Unable to change Tabs backgraound color

### ISSUE THREAD

**Issue by StudioAleph** [GeekyAnts/NativeBase#1904]
`style={{backgroundColor:"red"}}` doesn't work in tab unable to change background color
how to change tab background color ?

```
<Tabs renderTabBar={()=> <ScrollableTab />}>
          <Tab heading="Tab1">
            <Tab1 />
          </Tab>
          <Tab heading="Tab2">
            <Tab2 />
          </Tab>
          <Tab heading="Tab3">
            <Tab3 />
          </Tab>
          <Tab heading="Tab4">
            <Tab4 />
          </Tab>
          <Tab heading="Tab5">
            <Tab5 />
          </Tab>
        </Tabs>
```

**Comment by akhil-geekyants** [comment]
@StudioAleph use tabStyle and activeTabStyle of `<Tab/>`.

Usage
```
 <Tabs renderTabBar={() => <ScrollableTab />}>
          <Tab heading="Tab1" tabStyle={{ backgroundColor: "red" }} activeTabStyle={{ backgroundColor: "green" }}>
            <Text>Tab one</Text>
          </Tab>        
</Tabs>
```

**Comment by StudioAleph** [comment]
how to change text color?

**Comment by ghoshabhi** [comment]
This doesn't work if you are rendering an icon in the tab header:

```
 <Tabs>
          <Tab
            tabStyle={{ backgroundColor: "#5078F2" }}
            activeTabStyle={{ backgroundColor: "#5078F2" }}
            heading={
              <TabHeading>
                <Icon name="apps" />
              </TabHeading>
            }
          >
            <View>
              <Text>Hi there - Tab 1</Text>
            </View>
          </Tab>
          <Tab
            tabStyle={{ backgroundColor: "#5078F2" }}
            activeTabStyle={{ backgroundColor: "#5078F2" }}
            heading={
              <TabHeading>
                <Icon name="apps" />
              </TabHeading>
            }
          >
            <View>
              <Text>Hi there - Tab 2</Text>
            </View>
          </Tab>
        </Tabs>
```

**Comment by suvenduchhatoi** [comment]
@ghoshabhi #2349

**Comment by nadiahna** [comment]
@ghoshabhi you can solve with this if the color its same when active
 <Tab
            heading={
              <TabHeading style={{backgroundColor: '#ffffff'}}>
                <Icon name="apps" />
              </TabHeading>
            }
          >
            <View>
              <Text>Hi there - Tab 1</Text>
            </View>
          </Tab>

**Comment by thuynt99** [comment]
> it works for me

`<Tabs>
        <Tab
          heading="Translate"
          tabStyle={{ backgroundColor: '#1c74bb' }}
          activeTabStyle={{ backgroundColor: '#4297d3' }}
        >
          <DetailsView />
        </Tab>
        <Tab
          heading="Note"
          tabStyle={{ backgroundColor: '#1c74bb' }}
          activeTabStyle={{ backgroundColor: '#4297d3' }}
        >
          <NoteView />
        </Tab>
      </Tabs>`
