### ISSUE TITLE
types: react-native types are wrong with 16.3+ 

### ISSUE THREAD

**Issue by NitroGhost** [GeekyAnts/NativeBase#1905]
the latest version of react-native types are incompatible with the native base types. the RN types no longer have ListViewStatic, ScrollViewStatic or ViewStatic

**Comment by akhil-geekyants** [comment]
@NitroGhost see PR https://github.com/GeekyAnts/NativeBase/pull/1891

**Comment by SupriyaKalghatgi** [comment]
Fixed with [2.5.0](https://github.com/GeekyAnts/NativeBase/tree/v2.5.0)
