### ISSUE TITLE
CheckBox components doesn't have testID prop available

### ISSUE THREAD

**Issue by arnoldpaye** [GeekyAnts/NativeBase#1906]
## react-native, react and native-base version
- react-native: 2.4.5
- react: 16.3.2
- react-native: 0.55.2
## Expected behaviour
`CheckBox` component having available `testID` prop
## Actual behaviour
`CheckBox` component doesn't have `testID` prop
## Steps to reproduce (code snippet or screenshot)
I want to use `testID` prop but it is not available:

<img width="649" alt="screen shot 2018-05-18 at 11 33 20 am" src="https://user-images.githubusercontent.com/1205125/40244083-e8955fb2-5a8f-11e8-8140-d6b1bf5ee2db.png">

In the other hand , Radio component has it:

<img width="679" alt="screen shot 2018-05-18 at 11 32 54 am" src="https://user-images.githubusercontent.com/1205125/40244178-25b70a6c-5a90-11e8-96bd-db3fe4a5ffd3.png">

I expected that `CheckBox` component has this prop as `Radio`.
## Screenshot of emulator/device
n/a
## Is the bug present in both ios and android or in any one of them?
Yes
## Any other additional info which would help us debug the issue quicker.
Internally both components (`CheckBox` and `Radio`) use `TouchableOpacity` propTypes, which has `testID` prop, but as it is mentioned in #901 , the `CheckBox` interface is not extending from `ReactNative.TouchableOpacityProperties` type.

**Comment by SupriyaKalghatgi** [comment]
Released with [2.5.0](https://github.com/GeekyAnts/NativeBase/tree/v2.5.0)
