### ISSUE TITLE
Header is weird on android

### ISSUE THREAD

**Issue by thienhaole92** [GeekyAnts/NativeBase#1907]
I use NativeBase in my project when but somethings wrong with android
![screenshot_20180518-225802](https://user-images.githubusercontent.com/10322005/40245318-82955f54-5aef-11e8-88a9-1aa1cab989b3.png)

**Comment by SupriyaKalghatgi** [comment]
@thienhaole92 Tell us more about your `package.json` and code snippet of this screen

**Comment by thienhaole92** [comment]
`{
  "name": "OWAPP_RN",
  "version": "0.1.0",
  "private": true,
  "devDependencies": {
    "jest-expo": "~27.0.0",
    "react-devtools": "^3.2.1",
    "react-native-scripts": "1.14.0",
    "react-test-renderer": "16.3.1"
  },
  "main": "./node_modules/react-native-scripts/build/bin/crna-entry.js",
  "scripts": {
    "start": "react-native-scripts start",
    "eject": "react-native-scripts eject",
    "android": "react-native-scripts android",
    "ios": "react-native-scripts ios",
    "test": "jest",
    "react-devtools": "react-devtools"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "expo": "^27.0.1",
    "native-base": "^2.4.4",
    "react": "16.3.1",
    "react-native": "~0.55.2",
    "react-native-hud-view": "^1.2.2",
    "react-native-log-level": "^1.1.0",
    "react-navigation": "^2.0.1",
    "react-navigation-redux-helpers": "^1.0.7",
    "react-redux": "^5.0.7",
    "redux": "^4.0.0",
    "redux-logger": "^3.0.6",
    "redux-persist": "^5.9.1",
    "redux-thunk": "^2.2.0",
    "render-if": "^0.1.1",
    "tracer": "^0.8.15"
  }
}`

`
import React, { Component } from 'react';
import { Container, Content, Text, Card, Header, Body, Button, Title, CardItem } from 'native-base';
import { increment, decrement } from '../actions/index.js';
import {bindActionCreators} from 'redux';
import {connect} from 'react-redux';
class Counter extends Component{
  render(){
    console.log(this.props.count);
    return(
      <Container>
                <Header>
                    <Body>
                        <Title>Redux Counter</Title>
                    </Body>
                </Header>
                <Content padder>
                <Card>
                <CardItem>
                            <Text style = {{fontSize: 20, fontWeight: 'bold'}}>
                                {this.props.count}
                            </Text>
                </CardItem>
                </Card>
                        <Button dark bordered onPress= {() => this.props.increment()}>
                             <Text>Increment</Text>
                         </Button>
                         <Button dark bordered onPress= {() => this.props.decrement()}>
                              <Text>Decrement</Text>
                          </Button>
                 </Content>
            </Container>
    );
  }
}
`

**Comment by SupriyaKalghatgi** [comment]
@thienhaole92 Now that you mentioned about expo
Need `app.json` as well

**Comment by SupriyaKalghatgi** [comment]
@thienhaole92 You can also check https://github.com/GeekyAnts/NativeBase-KitchenSink/tree/CRNA for working example

**Comment by thienhaole92** [comment]
app.json
```
{
    "expo": {
        "sdkVersion": "27.0.0"
    }
}
```

**Comment by SupriyaKalghatgi** [comment]
@thienhaole92 Check the `app.json` of NativeBase-KitchenSink, link shared above
And include `androidStatusBar`

**Comment by thienhaole92** [comment]
@SupriyaKalghatgi thank you for helping my

**Comment by SupriyaKalghatgi** [comment]
@thienhaole92 were you able to fix the issue?

**Comment by SupriyaKalghatgi** [comment]
@thienhaole92 ok. closing this issue
