### ISSUE TITLE
Header Component Implementation giving error

### ISSUE THREAD

**Issue by hb2708** [GeekyAnts/NativeBase#1910]
Hello Native-Base team.

I tried to integrate the Header Component but ran into the following error

##Versions 
react-native-cli: 2.0.1
react-native: 0.54.2 ("react-native": "https://github.com/expo/react-native/archive/sdk-26.0.0.tar.gz",)
"expo": "^26.0.0",
"native-base": "^2.4.5",
"react": "16.3.0-alpha.1",
"react-navigation": "^1.5.11"

## Expected behaviour
It should show the header as expected

## Actual behaviour
It's giving the error as attached in the screen shot

## Steps to reproduce (code snippet or screenshot)
Following is the code of my simple screen
```
import React, { Component } from 'react';
import {
  View,
  Text,
  StyleSheet
} from 'react-native';

import { Icon, Button, Container, Header, Content, Left } from 'native-base';

class HomeScreen extends Component {
  render() {
    return (
      <Container>
        <Header>
          <Left>
            <Icon name='menu_icon' onPress={() => this.props.navigation.navigate('DraweOpen')} />
          </Left>
        </Header>
        <Content
        contentContainerStyle={{
          flex: 1,
          alignItems: 'center',
          justifyContent: 'center'
        }}
        >
          <Text>Home Screen</Text>
        </Content>
      </Container>
    );
  }
}

export default HomeScreen;
```
## Screenshot of emulator/device
<img width="341" alt="screen shot 2018-05-20 at 4 41 35 pm" src="https://user-images.githubusercontent.com/13498448/40277133-bf14c9ca-5c4c-11e8-8260-e85e5d0a4d1f.png">

## Is the bug present in both ios and android or in any one of them?
**YES**

## Any other additional info which would help us debug the issue quicker.
I went through the docs and used the same way as shown in Header docs
as following link
[Header Component Doc](https://docs.nativebase.io/Components.html#header-def-headref)

**Comment by akhil1988** [comment]
@hb2708 checked your code. It is working fine for me (except for the Icon name prop value warning). Attaching a gif.

![header](https://user-images.githubusercontent.com/14923943/40293106-e66af530-5cec-11e8-971e-79d3c13f6a79.gif)

**Comment by akhil-geekyants** [comment]
@hb2708 checked your code. It is working fine for me (except for the Icon name prop value warning). 
Try removing code for opening drawer from Icon's onPress prop, if it is not defined.

Attaching a gif.

![header](https://user-images.githubusercontent.com/14923943/40293106-e66af530-5cec-11e8-971e-79d3c13f6a79.gif)

**Comment by SupriyaKalghatgi** [comment]
@hb2708 I tried Header with iOS and Android, all fine

Also why `onPress` with **Icon**?

**Comment by hb2708** [comment]
Hello @akhil-geekyants @SupriyaKalghatgi 
I was following the tutorial below 
https://www.youtube.com/watch?v=bJmsmrRtMyw
and the code of native base sample app with all components.

I forgot that in the main file i have used style provide. Which was giving the error. Sorry for inconvenience.

Closing this issue for now.
