### ISSUE TITLE
The document web site is too slow in china

### ISSUE THREAD

**Issue by KloveML** [GeekyAnts/NativeBase#1914]
I am chinese.
There are many users in China using NativeBase.
But the document web site is too slow to make it difficult  for us to develop.
So I  really hope to change this feeling .
🙏 🙏 🙏

**Comment by SupriyaKalghatgi** [comment]
@KloveML Can you share GIF of loading NativeBase Docs?

**Comment by SupriyaKalghatgi** [comment]
@KloveML Any updates?

**Comment by SupriyaKalghatgi** [comment]
Closing this
