### ISSUE TITLE
CardSwiper throws error

### ISSUE THREAD

**Issue by polygoal** [GeekyAnts/NativeBase#192]
I copied the example in the docs but it's throwing this error:

![cskhjv-wgaaan5l jpg large](https://cloud.githubusercontent.com/assets/21036325/18671722/72efcfda-7f45-11e6-8775-4aa5a2957cad.jpeg)

**Comment by sankhadeeproy007** [comment]
Did you try pulling from master?

**Comment by sankhadeeproy007** [comment]
Fixed with 0.5.9

**Comment by gentle-noah** [comment]
I'm having the same issue and I locked my native-base version at 0.5.9

**Comment by gentle-noah** [comment]
@polygoal - The issue here is that the docs site shows importing `Image` in correctly.

Docs show:
```
import React, { Component, Image } from 'react';
import { Container, Content, CardSwiper, DeckSwiper, Picker, Card, CardItem, Text, Icon, Thumbnail } from 'native-base';
​```

Should be:
```
import React, { Component } from 'react';
import { Image } from 'react-native';
import { Container, Content, CardSwiper, DeckSwiper, Picker, Card, CardItem, Text, Icon, Thumbnail } from 'native-base';
​```

And then the provided example works great.

**Comment by polygoal** [comment]
It works! Thanks!!

**Comment by Randyanto** [comment]
I copy the tutorial and refer the Image to the react-native one but what I got is a blank screen >.<(in Android)

**Comment by SupriyaKalghatgi** [comment]
Check the latest docs of NativeBase [0.5.9](http://nativebase.io/docs/v0.5.9/)

**Comment by SupriyaKalghatgi** [comment]
@Randyanto Try running this snippet

https://github.com/GeekyAnts/NativeBase-KitchenSink/blob/master/js/components/deckswiper/index.js
