### ISSUE TITLE
ModalStyle on Picker component for iOS

### ISSUE THREAD

**Issue by Maren-Osnabrug** [GeekyAnts/NativeBase#1923]
Hi!
I was looking for a way to style the picker modal, and found this PR https://github.com/GeekyAnts/NativeBase/pull/335. However, using `modalStyle` on a picker has no effect. It's also not currently in the source for picker (https://github.com/GeekyAnts/NativeBase/blob/master/src/basic/Picker.ios.js).
Is there any way `modalStyle` can be made available again on the picker or is there a workaround I can use?

**Comment by SupriyaKalghatgi** [comment]
Fixed with [2.5.0](https://github.com/GeekyAnts/NativeBase/tree/v2.5.0)
