### ISSUE TITLE
CheckBox not 'tapable'

### ISSUE THREAD

**Issue by acamenhas** [GeekyAnts/NativeBase#193]
I've tested with the 0.5.8 version on android device and emulator.

                <Content>
                    <List>
                        <ListItem>
                            <CheckBox checked={true} />
                            <Text>Daily Stand Up</Text>
                        </ListItem>
                        <ListItem>
                            <CheckBox checked={false} />
                            <Text>Discussion with Client</Text>
                        </ListItem>
                    </List>
                 </Content>

**Comment by sankhadeeproy007** [comment]
![checkbox](https://cloud.githubusercontent.com/assets/10998047/18958035/d6d3ebd6-867e-11e6-8e55-91efb7d78a1a.gif)
Works fine. You sure you're using the latest?

**Comment by voidale** [comment]
@sankhadeeproy007 I think he meant when you click on the text itself it should also toggle it, is that available? looks like it's missing. I also think it should be clickable on text as well, if the checkbox was accepting a text as a children that might be nice.

**Comment by sankhadeeproy007** [comment]
@voidale You can add a prop to the `<ListItem/>` component itself. You can check the implementation in the KItchenSink app here
https://github.com/GeekyAnts/NativeBase-KitchenSink/blob/master/js/components/checkbox/index.js#L68

**Comment by gopinathshiva** [comment]
onPress missing in documentation http://nativebase.io/docs/v2.0.0/components#checkbox . Thanks for pointing it out

**Comment by PatrikTes** [comment]
Hello, I have made it exactly as in this sample. The value is correctly set, but the checkbox itself is not refreshed. It's always a.) checked or b.) unchecked, based on initial value? Any suggestions? I'm using native-base 2.3.1

**Comment by jankarres** [comment]
You are right guys, the Checkbox component have not yet a onPress event. I submitted a pull request (#1232) for this feature.

Workaround for the moment until merge and next release:

```
<View onTouchStart={() => this.setState({ terms: !this.state.terms })}>
    <CheckBox
        checked={this.state.terms}
    />
</View>
```
