### ISSUE TITLE
ScrollTabs explode on dynamic rendering

### ISSUE THREAD

**Issue by dev-aliraza** [GeekyAnts/NativeBase#1931]
I'm using native base with `react-native init` that is pure react app.

When I try to render scroll tabs dynamically via API, sometimes it explode and sometimes work absolutely fine. I build and run app first time and it works fine then I change nothing and run again and it starts exploding.

Also, I used KitchenSink to bootstrap my app

Explode screenshot:
![screenshot_2018-05-25_02-18-38](https://user-images.githubusercontent.com/9783364/40514385-63b5a80a-5fc2-11e8-907b-ec2634844769.png)

Dynamic rendering code:
```
renderTab() {
        var categories = [];
        if (this.state.categoriesData != null) { // Here state change on API call
            categories = this.state.categoriesData.map((catInfo) => {
                return (
                    <Tab heading={catInfo.name} key={catInfo.slug}>

                        <Content padder>
                            // Below is the Post list rendering on API call
                            {
                                this.state.postsData != null
                                && this.state.postsData[catInfo.slug] != null
                                && this.state.postsData[catInfo.slug].data != null 
                                && this.state.postsData[catInfo.slug].data.map((post) => {
                                    return (
                                        <Post post={post} key={post.uuid} /> // My component
                                    )
                                })
                            }
                        </Content>
                    </Tab>
                )
            });
        }
        return categories;
    }

render() {
        var tabs = this.renderTab();
        return (
          <Tabs onChangeTab={({ i, ref, from }) => console.log(i)} renderTabBar={() => <ScrollableTab tabsContainerStyle={{ backgroundColor: Platform.OS == 'ios' ? '#F8F8F8' : '#3F51B5' }} />}>
            {tabs.length > 0 && tabs}
          </Tabs>
        );
    }
```
Package.json
```
...............
"dependencies": {
    "color": "3.0.0",
    "lodash": "4.17.10",
    "moment": "2.22.1",
    "native-base": "2.4.5",
    "react": "16.3.1",
    "react-native": "0.55.4",
    "react-native-vector-icons": "4.6.0",
    "react-navigation": "2.0.2"
  },
  "devDependencies": {
    "babel-jest": "23.0.0",
    "babel-preset-react-native": "4.0.0",
    "jest": "23.0.0",
    "react-test-renderer": "16.3.1"
  },
............
```
--------------------------
No related to ticket but I just want to know that is their any way that I can decouple Categories and Posts rendering.
Current flow is: A component name X has imported Categories (as scroll tabs) and Categories has dynamic tabs and post underneath each tab. When new post renders, it render entire thing including tabs (Component X doesn't re-render because it's parent). Although react is smart but I'm uncomfortable with this thing.

**P.S:** I'm newbie in react and react-native

## Is the bug present in both ios and android or in any one of them?
I just checked on android.

**Comment by dev-aliraza** [comment]
Also, I would like to add that I test this dynamic rendering on expo.io that is CRNA and same issue occurs

**Comment by akhil-geekyants** [comment]
@dev-aliraza can you create a test repo for us to test.

**Comment by SupriyaKalghatgi** [comment]
@dev-aliraza This issue will be closed tomorrow, in case of no response

**Comment by dev-aliraza** [comment]
Hello, sorry for being unresponsive. I resolve this issue by rendering <tabs> and <tab> together. Previously I was rendering <tabs> and inside this I was rendering <tab> dynamically on a certain event.

So I pre-fetched tabs from API and render them together.

**Comment by SupriyaKalghatgi** [comment]
@dev-aliraza ok, any help needed here?

**Comment by dev-aliraza** [comment]
@SupriyaKalghatgi Everything is smooth up till now. 

_By the way awesome package. Keep up the good work!_

**Comment by SupriyaKalghatgi** [comment]
@dev-aliraza Thank you !
Stay tuned for upcoming release, you can check the Changelog from `master`
