### ISSUE TITLE
There is not plenty of space to use in Header - title

### ISSUE THREAD

**Issue by erick2014** [GeekyAnts/NativeBase#1932]
Hey guys, I have reviewed some issues related with this problem, but in all cases people are using a short text. 
I'm no able to change the width of the Title within the Body component. There is plenty of space to use, but the Body component is using a very small portion of the available width.

![image](https://user-images.githubusercontent.com/7244087/40520476-e3c89e12-5f8b-11e8-802a-32625819fc60.png)

Also in IOS: if I dont use a right button, the text gets lost:
![image](https://user-images.githubusercontent.com/7244087/40522652-8f22d362-5f97-11e8-8d1b-1ec35578e8d4.png)

## react-native, react and native-base version
```
"react-native": "0.55.1",
"native-base": "^2.4.5",
```
## Expected behaviour
To be able to use more width within the Body component, and align the text when there is not right button in IOS
## Actual behaviour
Not using plenty of space available for the title and the alignment when there is not right button gets lost
## Steps to reproduce (code snippet or screenshot)

```
const buildHomeBtn = navigation => {
  return (
    <Left>
      <Button transparent onPress={() => navigation.navigate('PatientHome')}>
        <Icon name='ios-home-outline' style={{ color: PRIMARY_DARK }} />
      </Button>
    </Left>

  )
}

const buildLeftArrowIcon = leftIconHandler => {
  console.log('leftIconHandler', leftIconHandler)
  return (
    <Left>
      <Button transparent onPress={leftIconHandler}>
        <Icon name='ios-arrow-back' style={{ color: PRIMARY_DARK }} />
      </Button>
    </Left>
  )
}

const buildRightSideIcon = navigation => {
  return (
    <Right>
      <Button transparent onPress={() => navigation.navigate('DrawerOpen')}>
        <Icon name='menu' style={{ color: PRIMARY_DARK }} />
      </Button>
    </Right>

  )
}

 <Header style={typo.bgWhite}
   androidStatusBarColor={getStatusBarColor(statusBarColor)}
   iosBarStyle='light-content'>
   {leftIconType === 'home' ? buildHomeBtn(navigation) : buildLeftArrowIcon(leftIconClickHandler)}
   <Body>
    <Title style={{ color:'blue', fontSize: 16 }}> RESUMEN DEL SERVICIO </Title>
   </Body>
    {showRightIcon ? buildRightSideIcon(navigation) : null}
</Header>
```
## Is the bug present in both ios and android or in any one of them?
both

**Comment by SupriyaKalghatgi** [comment]
@erick2014 
> Also in IOS: if I dont use a right button, the text gets lost:

If you include `Left` / `Body` / `Right`, to align your elements, then you have to wrap the rest of the elements similarly for alignment

**Comment by erick2014** [comment]
@SupriyaKalghatgi  do you mean  use Left or right within the Body?

**Comment by joshuahenson** [comment]
I believe she means that if you are using the `Left` and `Body` component, you also have to use the `Right` component but you don't have to include anything inside it. Something like this should work for you.
`{showRightIcon ? buildRightSideIcon(navigation) : <Right />}`

**Comment by erick2014** [comment]
Alright I'm going to try, thx for the explanation @joshuahenson

**Comment by SupriyaKalghatgi** [comment]
@erick2014 Did you try?

**Comment by SupriyaKalghatgi** [comment]
This issue will be closed tomorrow, in case of no response

**Comment by rosemarystanley** [comment]
Did anyone find a solution for this? I'm having the same issue. I'm using all three components `Left` / `Body` / `Right` and all of them seem to be cutting off like there's not enough room when really there is plenty of space. 

```
       <Header>
          <Left>
            <Button transparent onPress={() => this.props.navigation.navigate('Accounts')}>
              <Icon active name='ios-arrow-back' type='Ionicons' />
              <Text>Back</Text>
            </Button>
          </Left>

          <Body>
            <Title>EDIT ACCOUNTS</Title>
          </Body>

          <Right>
            <Button transparent onPress={() => this.setState({ reorder: !this.state.reorder })}>
              {(this.state.reorder ? <Icon active name='close' type='AntDesign' /> : <Icon name='ios-menu' type='Ionicons' />)}
            </Button>
          </Right>
        </Header>
```

![Screen Shot 2019-04-08 at 11 51 59 AM](https://user-images.githubusercontent.com/7914791/55738244-bf6d1480-59f4-11e9-89d2-fd997c6b3a9a.png)

**Comment by jannikbuschke** [comment]
I have the same problem

![image](https://user-images.githubusercontent.com/5894881/57795899-6442e600-7747-11e9-9fd2-10eda5fbfa34.png)

```
<Header >
  <Left>
      <Button transparent onPress={() => navigation.goBack()}>
          <Icon name='arrow-back' />
      </Button>
   </Left>
   <Body style={{ backgroundColor: "black" }}>
       <Title>{item.level3}</Title>
       <Subtitle>{item.level4}</Subtitle>
   </Body>
   <Right />
</Header>
```

I tried-and-error setting some styles on the Body and Right component , and also removed the Right component without any good results.

**Comment by kentrh** [comment]
I solved the truncated titles by putting `style={{ flex: 2 }}` on the `<Body>` tag

**Comment by Enalmada** [comment]
@SupriyaKalghatgi `style={{ flex: 2 }}` on the `<Body>` tag seems to workaround the problem.  Can GeekyAnts get a more permanent fix?
