### ISSUE TITLE
There is spaces at the left of Left

### ISSUE THREAD

**Issue by isaaclem** [GeekyAnts/NativeBase#1936]
Hi! Thanks for trying out NativeBase!
Due to the overwhelming requests and issues/questions we ask you to add the following details with your issue.

Please check the existing open/closed issues for a possible duplicate before creating a new issue :)

Also **DO** fill out the below form to give us a better idea about your environment and help us debug it quicker. Issues without the required details will mostly be unattended to.

## react-native, react and native-base version
    "native-base": "^2.4.5",
    "react": "^16.4.0",
    "react-native": "^0.55.4",
## Expected behaviour
    There is no space at the left of Left

## Actual behaviour
    There is space at the left of Left

## Steps to reproduce (code snippet or screenshot)

    <Container style={{ backgroundColor: '#123' }}>
    <Header style={{ backgroundColor: 'green', elevation: 0, borderColor: 'transparent' }}>
      <Left style={{ backgroundColor: '#111', flex: 1, alignContent: 'flex-start' }}>
        <Button large onPress={() => Actions.landingPage()}>
          <Icon name="arrow-back" style={{ color: globalStyles.appThemeColor }} />
        </Button>
      </Left>
    </Header>        
  </Container>

## Screenshot of emulator/device
![screen shot 2018-05-26 at 1 37 39 pm](https://user-images.githubusercontent.com/32945572/40573381-5867d590-60f3-11e8-8dfd-cbbc231da7f8.png)

**Comment by SupriyaKalghatgi** [comment]
https://github.com/GeekyAnts/NativeBase-KitchenSink/blob/master/src/screens/Header/2.js

https://github.com/GeekyAnts/NativeBase-KitchenSink/blob/master/screenshots/ios/header-with-icons.png

https://github.com/GeekyAnts/NativeBase-KitchenSink/blob/master/screenshots/android/header-with-icons.png

Works fine for iOS and Android as per design guidelines
