### ISSUE TITLE
[Bug] Tabs index incorrect while set Orientation programmatically

### ISSUE THREAD

**Issue by ithieund** [GeekyAnts/NativeBase#1937]
In my case, I have 4 tabs and Tab 2 (index 1) should be in landscape mode so I used the plugin react-native-orientation to do that. And after that, I saw the bug.

## react-native, react and native-base version
"native-base": "^2.4.5",
"react": "16.0.0-alpha.12",
"react-native": "0.48.4",
"react-native-orientation": "^3.1.3",

## Expected behaviour
When Tab 2 is active (landscape) -> Click Tab 3 -> Tab 3 should be active (portrait)

## Actual behaviour
Tab 4 is active (portrait)

## Steps to reproduce (code snippet or screenshot)

`<Tabs
                        locked={true}
                        onChangeTab={({i, ref, from}) => {
        console.log("Tab index changed: ", index);

        setTimeout(() => {
            if(index == 1) {
                Orientation.lockToLandscape();
            }
            else {
                Orientation.lockToPortrait();
            }
        }, 100);
    }}
                    >
                        <Tab
                            heading={<TabHeading><Text>Tab 1</Text></TabHeading>}
                        >
                            <Scene1 />
                        </Tab>
                        <Tab heading={<TabHeading><Text>Tab 2</Text></TabHeading>}>
                            <Scene2 />
                        </Tab>
                        <Tab heading={<TabHeading><Text>Tab 3</Text></TabHeading>}>
                            <Scene3 />
                        </Tab>
                        <Tab heading={<TabHeading><Text>Tab 4</Text></TabHeading>}>
                            <Scene4 />
                        </Tab>
                    </Tabs>`

## Screenshot of emulator/device
Not necessary

## Is the bug present in both ios and android or in any one of them?
Not sure. Just checked with Android. This happened in both AVD and physical devices.

## Additional info
When you click a tab that is next to the last tab, the last tab will be active
Ex:
- Case 1: 4 tabs, click tab 3 -> tab 4 will be active
- Case 2: 5 tabs, click tab 4 -> tab 4 will be active

This bug does not happend when we don't change the orientation!

**Comment by ithieund** [comment]
@SupriyaKalghatgi ,
Can you please check and fix this soon?

Thanks.

**Comment by akhil-geekyants** [comment]
@ithieund can you try adding prop  scrollWithoutAnimation={true} to Tabs

**Comment by ithieund** [comment]
@akhil-geekyants ,
It seems to work now. 
It's so strange!

Thank you very much.

**Comment by SupriyaKalghatgi** [comment]
@ithieund can you close this issue?

**Comment by akhil-geekyants** [comment]
Related issue https://github.com/skv-headless/react-native-scrollable-tab-view/issues/518

**Comment by akhil-geekyants** [comment]
Closing this issue. See this issue https://github.com/skv-headless/react-native-scrollable-tab-view/issues/518
