### ISSUE TITLE
Excess space on Android ActionSheet

### ISSUE THREAD

**Issue by joshuahenson** [GeekyAnts/NativeBase#1938]
## react-native, react and native-base version
    "native-base": "2.4.1",
    "react": "16.2.0",
    "react-native": "0.52.0"
## Expected behaviour
Hide empty space when there is no title, like on ios, or similar to the Google app
![screenshot_20180526-163959](https://user-images.githubusercontent.com/4668069/40581113-0fe2705c-6105-11e8-8b10-8490a61e9322.png)
## Actual behaviour
Extra whitespace where title goes
![screenshot_20180526-163908](https://user-images.githubusercontent.com/4668069/40581114-246632fc-6105-11e8-8ef7-4c7f1304b3c6.png)

## Steps to reproduce (code snippet or screenshot)
Remove title from ActionSheet
`              ActionSheet.show(
                {
                  options: BUTTONS,
                  cancelButtonIndex: CANCEL_INDEX,
                  destructiveButtonIndex: DESTRUCTIVE_INDEX
                },
                buttonIndex => {
                  this.setState({ clicked: BUTTONS[buttonIndex] });
                }
              )}`
## Is the bug present in both ios and android or in any one of them?
Android only

I haven't tested this but I was thinking maybe we could only show the title field if it exists.
Something along the lines of
`{this.state.title && <Text style={{ color: "#757575" }}>{this.state.title}</Text>}`

**Comment by akhil-geekyants** [comment]
@joshuahenson can you check this https://github.com/listenzz/react-native-modal-translucent

**Comment by joshuahenson** [comment]
Sorry, I don't think I was clear. I'm talking about the empty space on top of the ActionSheet that is left when you do not include an ActionSheet title. I've colored it yellow and black here.

![yellow](https://user-images.githubusercontent.com/4668069/40627337-39b6fc9e-6273-11e8-9e88-8216805e1d69.png)

My initial hope at quickly glancing at the code was that we could just conditionally not include the Text component if there was no title but I don't think that will make much difference.

**Comment by SupriyaKalghatgi** [comment]
Fixed with [2.5.0](https://github.com/GeekyAnts/NativeBase/tree/v2.5.0)

**Comment by TxusBlack** [comment]
Same error on the last version.
