### ISSUE TITLE
Text doesnt fit the image card

### ISSUE THREAD

**Issue by mlazuardy** [GeekyAnts/NativeBase#1939]
i need to resizing the text of the card to fit with the image , because the title card display like this
![screenshot from 2018-05-27 22-19-38](https://user-images.githubusercontent.com/26824873/40587674-b49dd62a-61fc-11e8-8cf1-a7e91a7dfc77.png)

my code is
```
<View>
        <List
          horizontal
          dataArray={this.state.products}
          renderRow={(product) => (
            <ListItem>
              <Card>
                  <CardItem cardBody>
                    <Image source={SamplePhoto} style={{width:200,height:200}} />
                  </CardItem>
                  <CardItem>
                    <Text>{product.nama}</Text>
                  </CardItem>
              </Card>
            </ListItem>
          )}
        />
      </View>
```
im using horizontal list view , sorry for my bad english

**Comment by gersonmontenegro** [comment]
I only thing in a calculation based on the card width, but, I don't think that is correct, in usability terms. 

Maybe, for example, if you know that the width card allows you fit 50 characters, so, you can make 2 things:
1. Cut the text at the character 47 and add ellipsis (I mean, ... )
2. Don't allow title with more of 50 characters.

I know that this is not an specific solution for your question, but maybe those ideas can help you.

**Comment by akhil-geekyants** [comment]
@mlazuardy try setting bottom CardItem width to 200 and set numberOfLines prop of Text to 1.

Sample code 

```
import React, { Component } from 'react';
import { Image } from "react-native";
import { Container, Header, Content, List, ListItem, Text, Card, CardItem } from 'native-base';
export default class App extends Component {
  render() {
    const items = ['Daniel Michael Blake Day-Lewis', 'Kiefer William Frederick Dempsey George Rufus Sutherland', 'Isabella Fiorella Elettra Giovanna Rossellini', 'Charles Philip Arthur George Mountbatten-Windsor', 'Johannes Chrysostomus Wolfgangus Theophilus Mozart'];
    return (
      <Container>
        <Header />
        <Content>
          <List dataArray={items}
            horizontal
            renderRow={(item) =>
              <ListItem>
                <Card>
                  <CardItem cardBody>
                    <Image source={{ uri: "https://nativebase.io/assets/img/front-page-icon.png" }} style={{ width: 200, height: 200 }} resizeMode="contain" />
                  </CardItem>
                  <CardItem style={{ width: 200 }}>
                    <Text numberOfLines={1}>{item}</Text>
                  </CardItem>
                </Card>
              </ListItem>
            }>
          </List>
        </Content>
      </Container>
    );
  }
}

```
Screenshot

![simulator screen shot - iphone 6 - 2018-05-28 at 11 49 22](https://user-images.githubusercontent.com/27768184/40599970-3353be42-626d-11e8-9ce7-75862e0888a8.png)

**Comment by mlazuardy** [comment]
@akhil-geekyants what is numberOfLine sir? Do You Mean if text its too long it will generate the three dot in the end of text ?

**Comment by akhil-geekyants** [comment]
@mlazuardy yes. https://facebook.github.io/react-native/docs/text.html#numberoflines

**Comment by mlazuardy** [comment]
oh i missed the card item to add the width to 200px, and even without numberOfLines its looks nicer, thanks Sir, Awesome

**Comment by SupriyaKalghatgi** [comment]
@mlazuardy Can you close this issue?
