### ISSUE TITLE
Animated.View and ListItem

### ISSUE THREAD

**Issue by jdnichollsc** [GeekyAnts/NativeBase#1942]
Hi guys,

This is a question because I can see issues using `Animated.View` into lists, what's the correct way to use animations with `ListItem`?
The touch doesn't work well:
```
<ListItem>
  <Animated.View>
  </Animated.View>
</ListItem>
```
**Result:** `The position of the items are incorrect and the touch doesn't work well`
or

```
<Animated.View>
  <ListItem>
  </ListItem>
</Animated.View>
```
**Result:** `I can't see the items`

Let me know what you think, I'm using the last version of NativeBase

Thanks in advance!

**Comment by akhil-geekyants** [comment]
@jdnichollsc checked this. Attaching a gif.

Code
```
import React from "react";
import { Animated, Easing } from "react-native";
import { ListItem, Left, Body, Right, Icon, Text } from "native-base"

export default class App extends React.Component {

  constructor() {
    super()
    this.animateItem = new Animated.Value(0)
  }

  componentDidMount() {
    Animated.timing(this.animateItem, {
      toValue: 1,
      duration: 1000,
      delay: 200,
      easing: Easing.linear
    }).start()
  }

  transformY() {
    return {
      translateY: this.animateItem.interpolate({
        inputRange: [0, 0.5, 1],
        outputRange: [700, 300, 0]
      })
    }
  }

  render() {
    return (
      <Animated.View
        style={{
          width: '100%',
          transform: [this.transformY()]
        }}>
        <ListItem
          icon>
          <Body>
            <Text>
              Text
          </Text>
          </Body>
          <Right style={{ height: '100%' }}>
            <Icon name="ios-arrow-forward" />
          </Right>
        </ListItem>
      </Animated.View>
    )
  }
}
```
Gif

![listitem](https://user-images.githubusercontent.com/27768184/40642175-e87076ea-6339-11e8-9dfb-684f1b38d53d.gif)

**Comment by jdnichollsc** [comment]
ohhh beautiful example, thanks for the help! so I don't understand what's the issue in my case :/

**Comment by SupriyaKalghatgi** [comment]
we can keep this issue open if you provide your code over snack

**Comment by jdnichollsc** [comment]
Thanks guys, let me close this issue, I need to review the theme of my app, thanks for all!
