### ISSUE TITLE
There is something like panOpenMask to increase the active area using createDrawerNavigator?

### ISSUE THREAD

**Issue by gersonmontenegro** [GeekyAnts/NativeBase#1949]
I just implemented a Sidebar menu navigation system, and it works fine, but the area to swipe the menu is too small. It is possible increase it?
## react-native, react and native-base version
0.55.2, 16.3.1, 2.4.5
## Expected behaviour
Slidebar opening sliding the menu in a long distance from the screen border, maybe 25% of it self. 
## Actual behaviour
Slidebar menu is open sliding from the very edge of the screen.

Using Drawer component, there is a prop called **panOpenMask** to do that, but I don't know something like this using createDrawerNavigator.

Thanks.

**Comment by SupriyaKalghatgi** [comment]
@gersonmontenegro `createDrawerNavigator` is with React Navigation.

Not related to NativeBase
