### ISSUE TITLE
<Button textStyle= silently fails

### ISSUE THREAD

**Issue by dsernst** [GeekyAnts/NativeBase#195]
`<Button>`'s `textStyle` attribute only accepts plain Javascript objects, and silently fails if you try to give it objects wrapped with `ReactNative.StyleSheet`.

Fails:

```jsx
class WorkingExample extends Component {
  render() {
    return (
        <Button rounded block large style={styles.button} textStyle={styles.buttonText}>click me</Button>
    );
  }
}

const styles = StyleSheet.create({
  button: {
    marginHorizontal: 38,
    marginBottom: 67,
  },
  buttonText: {
    fontSize: 12,
    fontWeight: '500',
  },
});
```

Works:

```diff
class WorkingExample extends Component {
  render() {
    return (
-        <Button rounded block large style={styles.button} textStyle={styles.buttonText}>click me</Button>
+        <Button rounded block large style={styles.button} textStyle={buttonText}>click me</Button>
    );
  }
}

+const buttonText = {
+  fontSize: 12,
+  fontWeight: '500',
+}
+
const styles = StyleSheet.create({
  button: {
    marginHorizontal: 38,
    marginBottom: 67,
  },
-  buttonText: {
-    fontSize: 12,
-    fontWeight: '500',
-  },
});
```

The docs don't mention this either.

**Comment by dsernst** [comment]
This has tripped me up twice now, and led to a stupid amount of debugging trying to hunt down what's going on. 

Possible solutions: 
- Handle both cases in the button code so it works without thinking about it: https://github.com/GeekyAnts/NativeBase/blob/master/Components/Widgets/Button.js#L110
- Throw a warning if the user tries to pass in a `StyleSheet` object for this prop.
- At the very least, update the docs to warn about this.

**Comment by sankhadeeproy007** [comment]
Thanks for notifying us. We'll figure out a fix soon.

**Comment by sankhadeeproy007** [comment]
@dsernst fixed it. Pull from master if you need urgently. Will publish soon.

**Comment by dsernst** [comment]
Nice 😄
