### ISSUE TITLE
Picker on iPhoneX not respecting Safe Area

### ISSUE THREAD

**Issue by victormartingarcia** [GeekyAnts/NativeBase#1951]
## react-native, react and native-base version

`
"react": "16.3.0-alpha.1",
"react-native": "^0.55.3",
"native-base": "^2.3.10"
`

## Expected behaviour

Picker on iOS shows a "modal" view taking the whole screen. On iPhone X it should respect the safe areas

## Actual behaviour

On iPhoneX the picker modal view does not respect Safe Areas, causing a misplacement. 

The back button is shown behind the status bar and it cannot be touched. The title is barely visible (falls behind iphone x top bezel)

<img width="587" alt="captura de pantalla 2018-05-30 a las 10 02 01" src="https://user-images.githubusercontent.com/659832/40713939-8d6bdad2-6401-11e8-9b90-0ec7c3f5b2bd.png">

## Is the bug present in both ios and android or in any one of them?

Only on iphone X (iOS)

**Comment by akhil-geekyants** [comment]
PR https://github.com/GeekyAnts/NativeBase/pull/1920

**Comment by victormartingarcia** [comment]
Cool, can't wait for PR #1920 to be merged

**Comment by SupriyaKalghatgi** [comment]
Released with [2.5.0](https://github.com/GeekyAnts/NativeBase/tree/v2.5.0)

**Comment by ironworkshop** [comment]
iPhone X is fine now, however this issue is presenting with iPhone XS Max and iPhone XR.

**Comment by UdayChintala** [comment]
Any solution or work around?
