### ISSUE TITLE
Picker Item checkmark not right aligned (Image)

### ISSUE THREAD

**Issue by VanessaChu** [GeekyAnts/NativeBase#1952]
Before I was on react native version 0.44.6, now after upgrading to react native version 0.55.4, the checkmark beside the picker item is not right aligned anymore

## react-native, react and native-base version
react-native -v 0.55.4
native-base -v 2.3.1
## Expected behaviour
Picker item checkmark should align to the right
## Actual behaviour
Picker item checkmark not aligned
## Steps to reproduce (code snippet or screenshot)
Update to latest version of react native
## Screenshot of emulator/device
<img width="349" alt="screen shot 2018-05-30 at 3 23 22 pm" src="https://user-images.githubusercontent.com/11250498/40750821-714c794e-641d-11e8-9a29-0a3117921e94.png">

**Comment by SupriyaKalghatgi** [comment]
Fixed with [2.5.0](https://github.com/GeekyAnts/NativeBase/tree/v2.5.0)
