### ISSUE TITLE
Block Buttons rendered without margins

### ISSUE THREAD

**Issue by vinnichase** [GeekyAnts/NativeBase#1956]
Hi when i copy the [example](https://docs.nativebase.io/Components.html#button-block-headref) for block buttons into my screen, it shows no margins between the buttons. It simply looks like full buttons with rounded corners.

native-base@2.4.5

**Comment by SupriyaKalghatgi** [comment]
@vinnichase Please refer this https://github.com/GeekyAnts/NativeBase-KitchenSink/blob/master/src/screens/button/block.js

**Comment by SupriyaKalghatgi** [comment]
Also that, refer NativeBase KitchenSink for demo of all components
