### ISSUE TITLE
Adding 'rounded' to Button on Android results in it not being rendered

### ISSUE THREAD

**Issue by kodayashi** [GeekyAnts/NativeBase#1958]
Hi! Thanks for trying out NativeBase!
Due to the overwhelming requests and issues/questions we ask you to add the following details with your issue.

Please check the existing open/closed issues for a possible duplicate before creating a new issue :)

Also **DO** fill out the below form to give us a better idea about your environment and help us debug it quicker. Issues without the required details will mostly be unattended to.

## react-native, react and native-base version
react-native 0.55.2
native-base 2.4.2

## Expected behaviour
I would expect that I could apply style to a button (e.g. 'rounded') and have it render in both iOS and Android.

## Actual behaviour
The custom style works fine for iOS, but the button is not rendered in Android

## Steps to reproduce (code snippet or screenshot)
Create a button with style (e.g. rounded):

        <Button
          primary
          block
          rounded
          onPress={() => console.log('Pressed')}>
          <Text>Sign up</Text>

The above Button will not render on Android.

## Is the bug present in both ios and android or in any one of them?
Only Android

## Any other additional info which would help us debug the issue quicker.
That's it! If this is expected, what's the best practice for creating buttons with style on Android?

**Comment by SupriyaKalghatgi** [comment]
#1852

**Comment by kodayashi** [comment]
Thanks @SupriyaKalghatgi - Sorry I missed that one when searching.
