### ISSUE TITLE
npm native-base 2.4.5 mismatch branch master

### ISSUE THREAD

**Issue by yandifitriyanto** [GeekyAnts/NativeBase#1959]
Hallo,

I want use native-base latest, but after install source different in branch master. this source compare different  
from cdn npm https://cdn.jsdelivr.net/npm/native-base@2.4.5/src/basic/Picker.ios.js and from github https://github.com/GeekyAnts/NativeBase/blob/master/src/basic/Picker.ios.js

Thanks.

**Comment by SupriyaKalghatgi** [comment]
@yandifitriyanto Yes, we have certain commits on branch `master`, which is not released yet
You will find it soon with npm
