### ISSUE TITLE
inputgroup borderType prop doesn't propogate when embedded inside a List

### ISSUE THREAD

**Issue by nikitph** [GeekyAnts/NativeBase#196]
try this

`<ListItem>
                                    <InputGroup borderType='rounded'>
                                        <Input placeholder='Enter dysfunctional thought here' />
                                    </InputGroup>
                                </ListItem>`

vs this

`  <InputGroup borderType='rounded'>
                                        <Input placeholder='Enter dysfunctional thought here' />
                                    </InputGroup>`

the first doesnt render the group as rounded

**Comment by sankhadeeproy007** [comment]
That is the desired behaviour. There are no custom borders when we render inputgroup in a list. We'll update the docs accordingly.
