### ISSUE TITLE
What's the difference difference between fixedLabel and inlineLabel ?

### ISSUE THREAD

**Issue by theapache64** [GeekyAnts/NativeBase#1961]

**Comment by akhil-geekyants** [comment]
@theapache64 The difference is in the maximum space the label can take. Attaching a gif. The first one is `fixedlabel` and the second one is `inlineLabel`. 

![fixed-inline-difference](https://user-images.githubusercontent.com/27768184/40959379-2a8c1838-68ba-11e8-80ed-00e06781ed89.gif)

**Comment by theapache64** [comment]
Perfect :+1:
