### ISSUE TITLE
How do i set 'backgroundColor' for all `Content` component, globally 

### ISSUE THREAD

**Issue by theapache64** [GeekyAnts/NativeBase#1963]
I want to have a global background color for all `Content`. I've searched the `material.js` file, but there's nor property like 'backgroundColor'. So how do i achieve this ?

**Comment by theapache64** [comment]
I'v created `BaseContent` class and gave 'backgroundColor'. 

```
export default class BaseContent extends Component<PropTypes> {
    render() {
        return (
            <Content {...this.props} contentContainerStyle={[
                {backgroundColor: 'white',},this.props.contentContainerStyle
            ]}>
                {this.props.children}
            </Content>
        );
    }
}
```

Is this a correct approach ? Do i have to change any part of the code ?

**Comment by SupriyaKalghatgi** [comment]
@theapache64 You can achieve it here https://github.com/GeekyAnts/NativeBase/blob/master/src/theme/components/Content.js#L6

**Comment by jerryOluranti** [comment]
> https://github.com/GeekyAnts/NativeBase/blob/master/src/theme/components/Content.js#L6

Article not found 😢
Can you please share steps here @theapache64

**Comment by theapache64** [comment]
@jerryOluranti Ooops. It's been 5 years. Sadly my memory is not that strong. Please open a new issue
