### ISSUE TITLE
placeholder color

### ISSUE THREAD

**Issue by theapache64** [GeekyAnts/NativeBase#1964]
Is it possible to have different colors on `Input` placeholder. I want `red` on standby, and `green` on float. Is it possible ?

**Comment by SupriyaKalghatgi** [comment]
@theapache64 Not possible with theme
You may have to check conditions, if `floatUp` is called then change `Label` color

**Comment by theapache64** [comment]
Ok

**Comment by theapache64** [comment]
How do i get a callback when the label floatUp. Is there any callback like this

```
<Item floatUp={()=>{
                        alert("Floated")
                    }}/>
```

**Comment by QinGuan2004** [comment]
@theapache64 you could try ```<Item isFocused={()=>alert("Floated")}/>``` not sure if it'll work

**Comment by SupriyaKalghatgi** [comment]
@theapache64 You can detect if `floatUp` is called using `ref`
Note that with `floatingLabel` use `getRef` to get reference

**Comment by julianstivenm8** [comment]
Hello, I made something like this

<Item floatingLabel  >
            <Label style={this.state.labelUp?[styles.subtitle]:[styles.normal]}>
              Nombre
            </Label>
            <Input onChangeText={name => this.setState({ name })} value={this.state.name} onFocus={()=>{this.setState({labelUp: true}); }} onBlur={()=>{(this.state.name =="")?this.setState({labelUp: false}):this.setState({labelUp: true}) }} />
          </Item>
