### ISSUE TITLE
Is there built-in RadioGroup component ? 

### ISSUE THREAD

**Issue by theapache64** [GeekyAnts/NativeBase#1965]
I've been reading the docs, came to know about `Radio` component which renders cool radio button. but I can't anything like 'RadioGroup' in the docs. Is it supported ? or am i missing something ? To manage single selection in radio, i need to write my own radio group ?

**Comment by SupriyaKalghatgi** [comment]
We dont have radio group

**Comment by SupriyaKalghatgi** [comment]
Please make use of NativeBase slack for such queries
