### ISSUE TITLE
picker doesnt work inside of a list tag

### ISSUE THREAD

**Issue by nikitph** [GeekyAnts/NativeBase#197]
self explanatory

**Comment by sankhadeeproy007** [comment]
Hi, please post a code snippet. We'll look into it.

**Comment by sankhadeeproy007** [comment]
![screen shot 2016-09-29 at 7 16 40 pm](https://cloud.githubusercontent.com/assets/10998047/18956568/7cfdcd34-8679-11e6-9c71-978f1732486a.png)
This example seems to work pretty well!

**Comment by nikitph** [comment]
hmm... i m doing the same. i think my container is inside a tabbarios...tht seems to b the issue.
