### ISSUE TITLE
Segment code doesn't have right default color scheme?

### ISSUE THREAD

**Issue by sopdock** [GeekyAnts/NativeBase#1971]
I have this basic code taken from the example:

    // imports
    import { Button, Container, Segment } from 'native-base';

    // rendering
            <Container>
                    <Segment>
                        <Button first>
                            <Text>Recent</Text>
                        </Button>
                        <Button>
                            <Text>Home</Text>
                        </Button>
                        <Button last>
                            <Text>Settings</Text>
                        </Button>
                    </Segment>
            </Container>

This results in the default blue background, but the text and border are black. Also the when selecting a segment, doesn't highlight it.

Here is a [screenshot](https://gph.is/2HtaRw4).

How can i get it to show what I see in the [official example](https://docs.nativebase.io/Components.html#segment-outside-header-headref)?

**Comment by akhil-geekyants** [comment]
@sopdock use Text from `native-base` for getting the proper styling for Text. 
```
import { Container, Segment, Button, Text } from "native-base";
```
Also use `active` props of `Button` to highlight your selected segment button.
```
<Segment>
    <Button first>
        <Text>Recent</Text>
    </Button>
    <Button active={true}>
         <Text>Home</Text>
     </Button>
     <Button last>
         <Text>Settings</Text>
      </Button>
</Segment>
```

**Comment by sopdock** [comment]
Closing this in favor of https://github.com/GeekyAnts/NativeBase/issues/1974
