### ISSUE TITLE
Header Noleft without effect

### ISSUE THREAD

**Issue by thomasphilibert** [GeekyAnts/NativeBase#1973]
Hi there ! 

It's seem that the "noLeft" prop does not work:

My Code:

```js
<Container style={styles.container}>
        <Header iosBarStyle="light-content" androidStatusBarColor={Config.HEAD_RED_COLOR} style={styles.redHeader} noLeft>
            <Left />
            <Body>
                <Text style={styles.textWhite} >My title</Text>
            </Body>
            <Right>
                <Button onPress={() => { this.props.navigation.navigate('rootAccountScreen'); }} transparent>
                    <Icon style={styles.textWhite} name="person" />
                </Button>
            </Right>
    </Header>
```

And the result : 

<img width="409" alt="capture d ecran 2018-06-07 a 16 08 29" src="https://user-images.githubusercontent.com/4984828/41106158-bd45d87e-6a6f-11e8-86d9-a082f540dfdf.png">

My configuration :
 
```json
    "native-base": "^2.4.1",
    "react": "^16.2.0",
    "react-native": "^0.52.0",
```

It is a bug or my code is not optimal ? 

Thank you,
Thomas

**Comment by SupriyaKalghatgi** [comment]
Did you eject theme after updating NativeBase version?

**Comment by SupriyaKalghatgi** [comment]
what is the version of NativeBase installed?

**Comment by SupriyaKalghatgi** [comment]
This issue will be closed in a day in case of no response

**Comment by thomasphilibert** [comment]
Hi SupriyaKalghatgi,

After upgrading my nativeBase 2.4.1 to 2.5.1 the title are on the left. You can close this issue, thank you.

**Comment by SupriyaKalghatgi** [comment]
@sagarguhe What is the issue here?
Screenshot looks fine for `noLeft`

**Comment by sagarguhe** [comment]
@SupriyaKalghatgi if you see the the code then I have icon on the left side but when I apply `noLeft` icon disappears and `Body > Title` goes to left. According to documentation Title should be centered ignoring Android guidelines?

**Comment by sagarguhe** [comment]
Sorry I misunderstood the documentation, actually I want to make header in the centre. but in Android it stays slightly left. How do I do this?

**Comment by SupriyaKalghatgi** [comment]
Then don't use `noLeft`

**Comment by sagarguhe** [comment]
if I use `noLeft` then it leaves some space for `Left` component but it still stays slightly left but on iOS it gets perfectly centred.

**Comment by sagarguhe** [comment]
if I don't use `noLeft` then it leaves some space for `Left` component but it still stays slightly left but on iOS it gets perfectly centred.

**Comment by SupriyaKalghatgi** [comment]
<Header>
 <Left />
 <Body>. . .</Body>
 <Right>. . .</Right>
</Header>

**Comment by sagarguhe** [comment]
I have icon on the left and right and in the centre title/image so I am using both `Left` and `Right` but still the `Body > Title` doesn't get centred. I think Native base works according to Android guidelines, so all the header in examples in the documentation are not perfectly centred as it is on iOS, even if you use `Left` and `Right`.

P.S.:  I have tried this code, but it doesn't work.
```
<Header>
 <Left />
 <Body>. . .</Body>
 <Right>. . .</Right>
</Header>
```

**Comment by sagarguhe** [comment]
Anyways you can close/lock this issue as this is not at all related to OP's issue.

**Comment by SupriyaKalghatgi** [comment]
I get your use case now.
Yes, NativeBase Title in Header as per Android guidelines is not centered.
You can achieve this with customization though
