### ISSUE TITLE
SwipeRow swipe functionality not working when soft keyboard is open.

### ISSUE THREAD

**Issue by dharamEnest** [GeekyAnts/NativeBase#1975]
Use list view below any TextInput field and now click on TextInput when keyboard is open try to swipe view inside SwipeRow.

**Comment by akhil-geekyants** [comment]
@dharamEnest can you post some code.

**Comment by dharamEnest** [comment]
@akhil-geekyants    Please use this code to make list view. 
Start typing in **TextInput**  and check the swipe functionality without closing the keyboard.


`

export default class TestScreen extends Component {
   
    constructor(props) {
        super(props);
        this.state = { testList: ['a', 'b', 'c', 'd', 'e'] };
    }

    render() {
        const { testList } = this.state;
        <Content>
            <TextInput
                placeholder="Mobile Phone"
                placeholderTextColor={lightGrayColor}
                underlineColorAndroid="transparent"
                keyboardType="numeric"
                maxLength={15}
                onChangeText={text => this.onTextChange(text)}
                value={contactNumber}
            />
            <List
                dataArray={testList}
                renderRow={(obj, i) => (
                    <SwipeRow
                        key={i}
                        leftOpenValue={0}
                        rightOpenValue={-125}
                        disableRightSwipe={true}
                        disableLeftSwipe={false}
                        left={
                            <Text>Left</Text>
                        }
                        body={
                            <TouchableOpacity style={{ flex: 1 }}>
                                <Text>{obj}</Text>
                            </TouchableOpacity>
                        }
                        right={
                            <Button onPress={() => { confirmAlert(); }}>
                                <Text uppercase={false}>Confirm</Text>
                            </Button>
                        }
                    />
                )}
            />
            );
</Content>
}
}



`

**Comment by akhil-geekyants** [comment]
@dharamEnest add props ` keyboardShouldPersistTaps="handled"` to `<List/>`.

**Comment by dharamEnest** [comment]
@akhil-geekyants Thanks it's working now
