### ISSUE TITLE
Picker arrow is white - how can I change the color?

### ISSUE THREAD

**Issue by VanessaChu** [GeekyAnts/NativeBase#1976]
My picker caret/arrow is white, and because my background is also white it looks like it's missing. How can I make it the default black? This is the issue on both iOS and Android

```
                  <ListItem last icon onPress={() => { }}>
                    <Body>
                      <Text>{I18n.t('$setting_owner_alarm_unattend_time')}</Text>
                    </Body>
                    <Right>
                      <Picker
                        supportedOrientations={['portrait', 'landscape']}
                        iosHeader={I18n.t('$setting_owner_picker_header')}
                        headerBackButtonText={I18n.t('$setting_owner_picker_back')}
                        mode='dropdown'
                        selectedValue={this.state.alert_interval}
                        onValueChange={(val) => { this.setState({alert_interval: parseInt(val)}) }}>
                        {
                          this.state.intervals.map(val => (
                            <Item key={val} label={I18n.t('$setting_owner_alarm_min', {n: val / 60})} value={val} />
                          ))
                        }
                      </Picker>
                    </Right>
                  </ListItem>
```

**Comment by SupriyaKalghatgi** [comment]
Picker's `iosIcon` prop defines icon
I cannot find this in your code

**Comment by SupriyaKalghatgi** [comment]
This issue will be closed in a day in case of no response

**Comment by Johncy1997** [comment]
<View style={{borderWidth:2,borderColor:'#c2c2c1',borderRadius:5}}>
                  <Picker
                  style={{
                    color:'#747474',
                    
                  }} 
                    selectedValue={this.state.subject}
                    supportedOrientations={['portrait', 'landscape']}
                    iosIcon={<IosIcon />}
                    itemStyle={{backgroundColor:'#fff'}}
                    onValueChange={(subject)=>{this.setState({subject:subject})}}>
                    <Picker.Item label="Language1" value="Language1" />
                    <Picker.Item label="English" value="English" /> 
                    <Picker.Item label="Maths" value="Maths" />
                    <Picker.Item label="Science" value="Science" /> 
                    <Picker.Item label="Social Science" value="Social Science" />
                  </Picker>
                  </View>

I tried to achieve this design:

![wanteddesign](https://user-images.githubusercontent.com/25324938/42632181-059862fe-85fa-11e8-8f98-5292285e4147.jpg)

I am getting this:

![noe](https://user-images.githubusercontent.com/25324938/42632449-d46aad6c-85fa-11e8-9ef0-c52450b099dd.jpg)

Please correct me how to change the icon style as bigger and picker should be having equal padding in 4 sides inside <View/> container

Thanks in advance

**Comment by akhil-geekyants** [comment]
@Johncy1997 NativeBase picker for android is a direct implementation of `react-native` Picker. React Native Picker for android does not support changing the icon. 

The android picker has a default height of 50. You can change the height of the picker using style props to match the padding.
```
<Picker
  style={{
    color: '#747474',
    height: Platform.OS === "android" ? 40 : 45
  }}
/>
```

**Comment by Johncy1997** [comment]
@akhil-geekyants Thanks for ur quick response.But its not changed even the height.Remained as it was before.

**Comment by akhil-geekyants** [comment]
@Johncy1997 checked this. The height is changing for me. Attaching a gif.

![picker](https://user-images.githubusercontent.com/27768184/42681929-a7c61e48-86a6-11e8-932d-2970e9b638c7.gif)

**Comment by smitthakkar1** [comment]
How can you change the color of `arrow (Icon)`on android ?

**Comment by jnicholls** [comment]
You can change the color in your styles.xml by adding this to your theme:

```
<item name="android:colorControlNormal">#FFFFFF</item>
```

There is no way to control it via react-native and thus native-base (since NB just passes straight down to RN).

**Comment by amitpadmani** [comment]
How can you change the color of arrow (Icon)on android ?

**Comment by jm90m** [comment]
@amitpadmani  If you aren't using expo then you can do what @jnicholls said above.

I use expo and I couldn't find another way so all I did was remove it... you can remove it by setting a `backgroundColor` to the `Picker` component like so - 
```

     <Picker
            style={{
              marginLeft: -8,
              marginTop: 2,
              backgroundColor: 'transparent',
            }}
            ...
          >
```

**Comment by baymax88** [comment]
Couldn't change the icon of arrow in Android?

**Comment by biancabmagalhaes** [comment]
For the ones who came later like me, i was able to change it adding `dropdownIconColor`. 
Like here: https://github.com/react-native-picker/picker/issues/334#:~:text=To%20change%20arrow%20color%20and%20ripple%20color%2C%20you%20can%20use%20the%20props%20dropdownIconColor%20and%20dropdownIconRippleColor.%20To%20change%20another%20styles%20you%20can%20use%20itemStyle%20propertie.
