### ISSUE TITLE
Error when installing native-base version 2.5.0

### ISSUE THREAD

**Issue by VilleMiekkoja** [GeekyAnts/NativeBase#1979]
I get this error when trying to install native-base version 2.5.0:

● Validation Error:

  Module <rootDir>/node_modules/react-native/jest/setup.js in the setupFiles option was not found.

  Configuration Documentation:
  https://facebook.github.io/jest/docs/configuration.html

The install command I used was: npm install native-base@2.5.0 --save --verbose

## react-native, react and native-base version
    "react": "^16.4.0",
    "react-native": "^0.48.2",
node v10.4.0
npm  v6.1.0

## Expected behaviour
Successful installation

## Actual behaviour
Unsuccessful installation

## Steps to reproduce (code snippet or screenshot)
npm install native-base@2.5.0 --save --verbose

## Any other additional info which would help us debug the issue quicker.
npm info lifecycle native-base@2.5.0~test: Failed to exec test script
npm verb stack Error: native-base@2.5.0 test: `jest`
npm verb stack Exit status 1

npm verb node v10.4.0
npm verb npm  v6.1.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! native-base@2.5.0 test: `jest`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the native-base@2.5.0 test script.

**Comment by SupriyaKalghatgi** [comment]
@VilleMiekkoja Latest is 2.5.1
Fixed this with 2.5.1
