### ISSUE TITLE
addListener is not a function

### ISSUE THREAD

**Issue by hanwenbo** [GeekyAnts/NativeBase#1980]
addListener is not a function
handleException @ ExceptionsManager.js:65
handleError @ InitializeCore.js:117
reportFatalError @ error-guard.js:44
__guard @ MessageQueue.js:233
callFunctionReturnFlushedQueue @ MessageQueue.js:102
(anonymous) @ debuggerWorker.js:72

ignite new appname --boilerplate native-base-boilerplate

## react-native, react and native-base version
react-native  0.47.2
## Expected behaviour
can use
## Actual behaviour
can not use
## Steps to reproduce (code snippet or screenshot)
![image](https://user-images.githubusercontent.com/5869741/41193339-3ecd7176-6c3d-11e8-9f38-320e563850f8.png)
emulator
ios

**Comment by SupriyaKalghatgi** [comment]
https://github.com/GeekyAnts/ignite-native-base-boilerplate/issues/19
