### ISSUE TITLE
Typo in onClose definition resulting in compilation error

### ISSUE THREAD

**Issue by idvorkin** [GeekyAnts/NativeBase#1982]
https://github.com/GeekyAnts/NativeBase/blob/f496d1b1c959fc625c14717539d1962a68175038/index.d.ts#L1123

**Comment by idvorkin** [comment]
Looks like it came from db2d48433abdcd647d5265b9494872aa74a6e5c2 @SupriyaKalghatgi

**Comment by akhil-geekyants** [comment]
PR #1990

**Comment by SupriyaKalghatgi** [comment]
Fixed with [v2.5.2](https://github.com/GeekyAnts/NativeBase/releases/tag/v2.5.2)
