### ISSUE TITLE
Scale button size?

### ISSUE THREAD

**Issue by sopdock** [GeekyAnts/NativeBase#1984]
If I have this button:

<Button bordered }>
    <Icon name="arrow-left"'/>
</Button>

Is it possible to scale the size down to 30x30 for heightxwidth?

I tried defining the `<Button bordered  style={{width: 30, height:30}}>` but then the Icon disappears.

**Comment by SupriyaKalghatgi** [comment]
Check docs for button size https://docs.nativebase.io/Components.html#button-size-headref

```
          <Button bordered small>
            <Icon name="arrow-back" />
            <Text>Button</Text>
          </Button>
```

Gives button with height and width of 30px
