### ISSUE TITLE
Header clipped on iPhoneX

### ISSUE THREAD

**Issue by idvorkin** [GeekyAnts/NativeBase#1985]
Hi! Thanks for trying out NativeBase!
Due to the overwhelming requests and issues/questions we ask you to add the following details with your issue.

Please check the existing open/closed issues for a possible duplicate before creating a new issue :)

Also **DO** fill out the below form to give us a better idea about your environment and help us debug it quicker. Issues without the required details will mostly be unattended to.

## react-native, react and native-base version

    "native-base": "^2.5.1",
    "react": "16.3.0-alpha.1",
    "react-native": "https://github.com/expo/react-native/archive/sdk-26.0.0.tar.gz",

## Expected behaviour
Header **does not** get clipped in iPhoneX notch
## Actual behaviour
Header **does** get clipped in iPhoneX notch
## Steps to reproduce (code snippet or screenshot)
```
  render() {
    return (
        <Container>
        <Header>
          <Title> Title In the Notch </Title>
        </Header>
        </Container>
    );
  }
```

## Screenshot of emulator/device
![image](https://user-images.githubusercontent.com/280981/41204966-943baf52-6ca0-11e8-854b-68d9db26ec43.png)
)
## Is the bug present in both ios and android or in any one of them?
No.

**Comment by zarir** [comment]
![header-safeareaview](https://user-images.githubusercontent.com/795240/41220247-649b39d2-6d7e-11e8-9621-5b35d23bf337.png)
Facing similar issue with NativeBase 2.5.1 and RN 0.55.4

**Comment by SupriyaKalghatgi** [comment]
@idvorkin @zarir Are you using NativeBase's `StyleProvider`?
If yes, then did you eject theme after upgrading NativeBase version?

**Comment by zarir** [comment]
@SupriyaKalghatgi No. I am not using StyleProvider or any theme. This is my code

`<Header
          noLeft
          iosBarStyle='light-content'
          androidStatusBarColor='green'
          style={{ backgroundColor: 'green' }}
        >
          <Left />
          <Body>
            <Title style={{ color: 'white' }}>{LocaleStore.home}</Title>
          </Body>
          <Right>
          <Button transparent onPress={() => this.navigate()}>
            <Icon type='Ionicons' name='person' style={{ color: 'white' }} />
          </Button>
          <Button transparent onPress={() => this.openActionSheet()}>
            <Icon type='Ionicons' name='share' style={{ color: 'white' }} />
          </Button>
          </Right>
        </Header>`

**Comment by akhil-geekyants** [comment]
@idvorkin use it like this
```
render() {
    return (
      <Container>
        <Header>
          <Left/>
          <Body>
            <Title>Header</Title>
          </Body>
          <Right />
        </Header>
      </Container>
    );
  }
```
See docs [here](http://docs.nativebase.io/Components.html#title-header-headref).

**Comment by limianwang** [comment]
I am experiencing the same issue...

```

**Comment by limianwang** [comment]
I am experiencing the same issue:

my code:
```
 return (
      <Container>
        <Header style={{
          backgroundColor: '#fff',
          borderBottomWidth: 2,
          borderBottomColor: '#ffb758'
        }}>
          <Left />
          <Body>
            <Text>Explore</Text>
          </Body>
          <Right/>
        </Header>
      </Container>
    );
```

<img width="388" alt="screen shot 2018-06-11 at 11 39 28 pm" src="https://user-images.githubusercontent.com/1587797/41274066-dc016cba-6dd0-11e8-9cec-75ceaceb01aa.png">

Anyone know why?

**Comment by limianwang** [comment]
One thing worth mentioning, on my other test app, same code works on iphone x. Version 2.4.5 works but not 2.5.1.

**Comment by idvorkin** [comment]
Thanks @akhil-geekyants !

My issue is resolved by nesting a body element in the header. 

For my learning any reason to make the body tag mandatory?

**Comment by SupriyaKalghatgi** [comment]
Fixed with [v2.5.2](https://github.com/GeekyAnts/NativeBase/releases/tag/v2.5.2)

**Comment by akhilsanker** [comment]
Hi @SupriyaKalghatgi ,

Using v2.8.2, but the issue still persist. Do you have any workaround to solve this?

Thanks

**Comment by SupriyaKalghatgi** [comment]
@akhilsanker After upgrading NativeBase, https://github.com/GeekyAnts/NativeBase/issues/1985#issuecomment-396162097
