### ISSUE TITLE
DatePicker Not found

### ISSUE THREAD

**Issue by lyseiha** [GeekyAnts/NativeBase#1986]
Module '"native-base"' has no exported member 'DatePicker'.

need help.

**Comment by SupriyaKalghatgi** [comment]
Attaching GIF of date Picker with latest Nativebase
Check NativeBase KitchenSink for example app https://github.com/GeekyAnts/NativeBase-KitchenSink

![date-picker](https://user-images.githubusercontent.com/13464885/41215679-20209b12-6d6f-11e8-93fa-a112812fd368.gif)

**Comment by lyseiha** [comment]
I use in typescript and the import statement show 
Module '"native-base"' has no exported member 'DatePicker'.

**Comment by SupriyaKalghatgi** [comment]
@lyseiha You did not mention this in your issue description

**Comment by SupriyaKalghatgi** [comment]
Accordion and Date Picker are not yet defined for typescript
Please wait for next release

**Comment by SupriyaKalghatgi** [comment]
Fixed with [v2.5.2](https://github.com/GeekyAnts/NativeBase/releases/tag/v2.5.2)
