### ISSUE TITLE
DatePicker textStyle not picked up

### ISSUE THREAD

**Issue by udarts** [GeekyAnts/NativeBase#1991]
Hi There,

I am trying to use the datepicker component, which works, but applying styling to the text (placeholder), it does get picked up, as I can see it in the debugger on my iphone, but it does not get applied.
For example if I want to remove the padding applied to the text, I added: textStyle={{padding:0}}, I see it's picked up, but not applied (placeholder still has padding 10).

Any idea on this?

**Comment by udarts** [comment]
I tried to change the file, but still not picked up. Anything I need to do after it?

**Comment by akhil-geekyants** [comment]
@udarts to check this locally, change this 
```
"main": "dist/src/index.js",
```
to
```
"main": "src/index.js",
```
in `node_modules/native-base/package.json` and restart the packager.

**Comment by udarts** [comment]
Yep that works, when is this fix available in the main product?

**Comment by SupriyaKalghatgi** [comment]
By this week

**Comment by SupriyaKalghatgi** [comment]
Fixed with [v2.5.2](https://github.com/GeekyAnts/NativeBase/releases/tag/v2.5.2)
