### ISSUE TITLE
Rogue semicolon in index.d.ts

### ISSUE THREAD

**Issue by mercerStrongArm** [GeekyAnts/NativeBase#2002]
I have a very simple issue. There is a syntax error in the native-base index file: https://github.com/GeekyAnts/NativeBase/blob/master/index.d.ts#L1123

That line has ";;" where it should have ";". This double semicolon caused a compilation error after I updated native-base. I didn't see any duplicates for this issue in the list, and the file was last updated 12 days ago.

## react-native, react and native-base version
React-native: 0.55.3
React: 16.3.1
Native-base: 2.5.1

## Expected behaviour
Running "yarn" compiles correctly, with no syntax errors in any files in the native-base node module.

## Actual behaviour
Running "yarn" to download node-modules/native-base fails with an error pointing to the syntax error at https://github.com/GeekyAnts/NativeBase/blob/master/index.d.ts#L1123.

## Steps to reproduce (code snippet or screenshot)
`rm -rf node_modules/`
`yarn`
`npm run build`

Error:
`node_modules/native-base/index.d.ts:1123:50 - error TS1131: Property or signature expected.`
`1123          onClose?: (reason: "user" | "timeout") => any;;`
                                                            ~`
## Screenshot of emulator/device
n/a

## Is the bug present in both ios and android or in any one of them?
Android

## Any other additional info which would help us debug the issue quicker.
https://github.com/GeekyAnts/NativeBase/blob/master/index.d.ts#L1123

**Comment by thanhtruong0315** [comment]
+1

**Comment by SupriyaKalghatgi** [comment]
#1982
