### ISSUE TITLE
Changing Tabs width, not the content inside

### ISSUE THREAD

**Issue by rostyys** [GeekyAnts/NativeBase#2003]
I want to customize the `Tabs` width, but not the width of the content of each tab.

![simulator screen shot - iphone x - 2018-06-12 at 13 30 34](https://user-images.githubusercontent.com/6425523/41315683-158d9106-6e45-11e8-99cd-bd6c222e40de.png)

I want the width of the `Tabs` header to not affect the width of the content inside each `Tab.`

This is my code. Currently I'm adding a `style` to `Tabs`

```
<Tabs
	style={{
		width: PixelRatio.getPixelSizeForLayoutSize(101),
	}}
	initialPage={0}
	tabBarUnderlineStyle={ styles.tabBarUnderlineStyle }
	>
        <Tab
	        heading="Phone"
	        tabStyle={ styles.tabStyle }
	        activeTabStyle={ styles.tabStyle }
	        textStyle={ styles.tabBarText }
	        activeTextStyle={ styles.tabBarText }
	        >
	        <Content>
		       
	        </Content>
	</Tab>
	<Tab
		heading="Email"
		tabStyle={ styles.tabStyle }
		activeTabStyle={ styles.tabStyle }
		textStyle={ styles.tabBarText }
		activeTextStyle={ styles.tabBarText }
		>
	        {/* <Tab2 /> */}
	</Tab>
</Tabs>
```

**Comment by akhil-geekyants** [comment]
@rostyys try using scrollable tabs http://docs.nativebase.io/Components.html#tabs-scrollable-headref.

**Comment by SupriyaKalghatgi** [comment]
@rostyys Did you try?

**Comment by rostyys** [comment]
@akhil-geekyants @SupriyaKalghatgi Yes, I tried it. In addition, I'm being forced to insert a `height` for the Tabs in order for the tab content to show up. is this normal behavior?

![scrollable](https://user-images.githubusercontent.com/6425523/41629066-50111bb2-73dc-11e8-87dc-fc9a680c4415.png)

<img width="434" alt="screen shot 2018-06-19 at 4 18 00 pm" src="https://user-images.githubusercontent.com/6425523/41629077-6041b32a-73dc-11e8-816d-7f8840177984.png">

**Comment by akhil-geekyants** [comment]
@rostyys try removing `flex:0`

Gif

![tabs](https://user-images.githubusercontent.com/27768184/41642377-ba150100-7485-11e8-96ce-9d54737bb2c8.gif)

**Comment by rostyys** [comment]
@akhil-geekyants Thank you! This fixes the `height` issue but it still doesn't solve my original issue. Is it possible to only give a `width` to the top header? I don't want the content inside each Tab to be limited to the same width because then it causes problems with seeing shadows on the TextInputs (Cuts if off on the left and right) as seen in my original photo

**Comment by SupriyaKalghatgi** [comment]
@rostyys Did you try?

**Comment by SupriyaKalghatgi** [comment]
Closing this tomorrow in case of no response

**Comment by rostyys** [comment]
@akhil-geekyants @SupriyaKalghatgi Hi! Just tried. This fixed the width of the content of each tab! 

But scrollable tabs seem to shift the tab titles to the right? How can I center them like they were before?

![shiftright](https://user-images.githubusercontent.com/6425523/41930676-99533fa4-7930-11e8-87c0-76b3f9cc7dcf.png)

**Comment by akhil-geekyants** [comment]
@rostyys  try setting the tabs container width using `tabsContainerStyle`

Gif

![tabs](https://user-images.githubusercontent.com/27768184/42020207-d267251c-7ad4-11e8-85ae-e0dd06505c60.gif)


Sample code
```
import React, { Component } from 'react';
import { Dimensions } from "react-native";
import { Container, Header, Tab, Tabs, ScrollableTab, Text } from 'native-base';
export default class App extends Component {
  render() {
    return (
      <Container>
        <Header />
        <Tabs
          renderTabBar={() =>
            <ScrollableTab style={{
              width: 300,
              marginHorizontal: Dimensions.get("window").width / 11,
              paddingTop: Dimensions.get("window").width / 35
            }}
              tabsContainerStyle={{ width: 300 }} />}>
          <Tab heading="Tab1" tabStyle={{ width: 100 }} activeTabStyle={{ width: 100 }} tab>
            <Text style={{ flex: 1, backgroundColor: "red" }}>Tab one</Text>
          </Tab>
          <Tab heading="Tab2" tabStyle={{ width: 100 }} activeTabStyle={{ width: 100 }}>
            <Text style={{ flex: 1, backgroundColor: "blue" }}>Tab two</Text>
          </Tab>
        </Tabs>
      </Container>
    );
  }
}
```
