### ISSUE TITLE
Floating label onfocus issue

### ISSUE THREAD

**Issue by ViktorAksionov** [GeekyAnts/NativeBase#2005]
After upgrade to 2.5.1 from 2.4 floating label goes up only when user typed at least 1 char, when there is a focus in input field and nothing is there floating label stack in place, but should move up.

## Expected behaviour
![image](https://user-images.githubusercontent.com/2520890/41330037-e7710f82-6e85-11e8-8a47-7723ec2d95c2.png)

## Actual behaviour
![image](https://user-images.githubusercontent.com/2520890/41329976-945e41e8-6e85-11e8-8eba-f5e0bdc0dcd5.png)

## Is the bug present in both ios and android or in any one of them?
Checked only Android

**Comment by ViktorAksionov** [comment]
![image](https://user-images.githubusercontent.com/2520890/41330756-27faacbc-6e8a-11e8-96c0-ed8d1ade4830.png)

**Comment by ZeroCool00** [comment]
same problem here

**Comment by akhil-geekyants** [comment]
@ViktorAksionov @ZeroCool00 can you try toggling the remote debugging mode.

**Comment by SupriyaKalghatgi** [comment]
#2000
