### ISSUE TITLE
stackedLabel input scrolls

### ISSUE THREAD

**Issue by theapache64** [GeekyAnts/NativeBase#2006]
![untitled](https://user-images.githubusercontent.com/9678279/41336883-2657dc14-6f0b-11e8-9e17-9958f7ce8c0d.gif)

I am using input with stackedLabel and the input scrolls when i swipedown.

### Code to reproduce 

```
import React, {Component} from 'react';
import {Container, Content, Form, Input, Item, Label} from "native-base";

export default class LabScreen extends Component {
    render() {
        return (
            <Container>
                <Content>
                    <Form>
                        <Item stackedLabel>
                            <Label>Sample label</Label>
                            <Input
                            />
                        </Item>
                    </Form>
                </Content>
            </Container>
        );
    }
}
```

**Comment by DaniloCouto** [comment]
This issue mess up content scroll pretty hard.
Sometimes the touch controller thinks it is scrolling the **input** when the user intention was to scroll the **content**, giving that feel that the application is slow.
This just happen with me. I'm going to try some workarround.

**Comment by SupriyaKalghatgi** [comment]
Fixed with [v2.5.2](https://github.com/GeekyAnts/NativeBase/releases/tag/v2.5.2)

**Comment by theapache64** [comment]
@DaniloCouto If you're working in a `ejected-theme` environment,updating just the version number won't fix this error. I had to re-eject with new version `(v2.5.2)` to fix this issue. or copy `Item` component from `node_modules` directory.

**Comment by williamliangwl** [comment]
I tested this issue with `v2.8.0` and it does fixes this issue, but not when the `secureTextEntry` is `true`
