### ISSUE TITLE
floatingLabel doesn't float on version v2.5.1 but works on v2.4.5

### ISSUE THREAD

**Issue by theapache64** [GeekyAnts/NativeBase#2009]
floatingLabel doesn't auto-float on v2.5.1 when wrapped inside another `View` and it only floats when i start typing. On v2.4.5, there's no issue like this and works perfectly fine with the same code. 

### v2.4.5
![old](https://user-images.githubusercontent.com/9678279/41347768-56666520-6f28-11e8-9be2-1001078eef4c.gif)

### v2.5.1
![new](https://user-images.githubusercontent.com/9678279/41347927-bf7e2340-6f28-11e8-9d5b-d0e62353a532.gif)

**Comment by SupriyaKalghatgi** [comment]
@theapache64 what is the difference between this and https://github.com/GeekyAnts/NativeBase/issues/2000?

**Comment by SupriyaKalghatgi** [comment]
#2000

**Comment by theapache64** [comment]
Both of the issues are based on same widget, but different.
#2000 reports the glitchy-lazy-slow floating behaviour of the `Input` with `floatingLabel`.  This issue, with the same property but doesn't float at all.
