### ISSUE TITLE
Button issue with mutable text from state on Android - undefined is not a function

### ISSUE THREAD

**Issue by java99** [GeekyAnts/NativeBase#201]
nb v0.5.8

`<Button primary onPress={this.toggleState} style={styles.buttons}> {this.state.submitButtonText} </Button>`

error in button.js (line 188)

`return <Text style={this.getTextStyle()}>{(Platform.OS==='ios') ? this.props.children : this.props.children.toUpperCase()}</Text>`

if I remove the .toUpperCase() for Android it runs fine, but with this code i get an "undefined is not a function" error. 

Thanks for your help
java99

ios version is running without issue in both cases

**Comment by sankhadeeproy007** [comment]
Can you give an example of the exact use case? Because if the children of the button isn't an array and is of type `string`, it gets handles in line 149 itself and doesn't reach till line 188 at all.

**Comment by java99** [comment]
`        <Container>
        <Content theme={theme}>
          <Image style={styles.header} source={headerImage} />
          <View style={styles.body}>
            <Avatar username={this.getUserName()} size={105}/>
            <Text style={styles.emailtext}>Username: {this.getUserName()}</Text>
            <Button primary onPress={this.toggleState} style={styles.buttons}> {this.state.submitButtonText} </Button>
            {this.state.setusername
              ?
              <View style={styles.body}>
                <TextInput
                  style={{height: 40, borderColor: 'gray', borderWidth: 1}}
                  onChangeText={(newusername) => this.setState({newusername})}
                />
                <Button danger onPress={this.cancel}> Cancel </Button>
              </View>
              : null
           }

            <View style={styles.buttonscontainer}>
            <Button primary onPress={this.showPosts} style={styles.buttons}> My Posts </Button>
            <Button success onPress={this.showRewards} style={styles.buttons}> My Rewards </Button>
            <Button danger onPress={this.signOut} style={styles.buttons}> Sign out </Button>
            </View>

          </View>
        </Content>
        </Container>`

`  toggleState() {
    var buttonText = "Submit new username";
    if (this.state.setusername) {
      Meteor.collection('users').update(Meteor.userId(), {
                  $set: {
                      'profile.name': this.state.newusername,
                  }
      });
      buttonText = "Change username";
    }

    this.setState({ setusername: !this.state.setusername, submitButtonText: buttonText});
  }

  cancel() {
      this.setState({ setusername: false, submitButtonText: "Change username" });
  }`


I know this code was not well written.. due to the persisting problem we did completely rewrite it and it did not show up again.

**Comment by linonetwo** [comment]
Same problem:
```javascript
<Button onPress={this.props.turnOff}> {`close ${this.props.id}`} </Button>
```

**Comment by sankhadeeproy007** [comment]
Can I have a screenshot of the error?

**Comment by java99** [comment]
![screenshot_20160930-221440](https://cloud.githubusercontent.com/assets/2676451/19006313/2fe69152-875f-11e6-9a93-4197935a53e7.png)

**Comment by java99** [comment]
is it fixed in 0.5.9?

**Comment by pathawee** [comment]
Button.js line 191
Should add `|| !this.props.capitalize` ?
```return <Text style={this.getTextStyle()}>{(Platform.OS==='ios' || !this.props.capitalize) ? this.props.children : this.props.children.toUpperCase()}</Text>```

**Comment by jaronoff97** [comment]
Has this been solved?

**Comment by java99** [comment]
Try latest Version. Should be fixed

Am 20.10.2016 11:46 nachm. schrieb "Jacob Aronoff" <notifications@github.com

**Comment by jaronoff97** [comment]
@java99 it hasn't been changed, i checked the code and tested on device. Check my PR #247

**Comment by java99** [comment]
So you can use my workaround in that case.

Am 25.10.2016 8:21 nachm. schrieb "Jacob Aronoff" <notifications@github.com

**Comment by jaronoff97** [comment]
@java99 the workaround is great, however, i'm about to release an app, and it's unideal to change a library that will be downloaded.

**Comment by sankhadeeproy007** [comment]
Fixed in latest.
