### ISSUE TITLE
Change letter spacing inside input

### ISSUE THREAD

**Issue by rostyys** [GeekyAnts/NativeBase#2014]
Hi! Is this possible to do?

**Comment by SupriyaKalghatgi** [comment]
Can you explain more on this

**Comment by rostyys** [comment]
@SupriyaKalghatgi Inside of a `TextInput`, is it possible to increase the spacing in between the letters?

![spacing](https://user-images.githubusercontent.com/6425523/41485975-7c8c9c68-7097-11e8-93c7-897a7a99790e.png)

**Comment by SupriyaKalghatgi** [comment]
@rostyys Yes
![image](https://user-images.githubusercontent.com/13464885/41594297-8ead49e6-73e0-11e8-9ca0-89709c254b41.png)
