### ISSUE TITLE
Toast not showing in latest react version

### ISSUE THREAD

**Issue by anbu369** [GeekyAnts/NativeBase#2015]
## react-native, react and native-base version
react-native : 0.55.4
react : 16.4.1
native-base : 2.5.2
## Expected behaviour
Show Toast
## Actual behaviour
Toast not showing and no errors showing in debugger
## Steps to reproduce (code snippet or screenshot)
`import {Button, Toast, Text} from 'native-base'`

`<Button
                          danger
                          onPress={() =>
                              Toast.show({
                                  text: "Wrong password!",
                                  buttonText: "Okay",
                                  type: "danger"
                              })}
                      >
                          <Text>Danger Toast</Text>
                      </Button>`
## Any other additional info which would help us debug the issue quicker.

I wrapped the topmost component in Root. To check that, I used ActionSheet and it is working but Toast is not.

**Comment by SupriyaKalghatgi** [comment]
Worked same on Android also 
![toast](https://user-images.githubusercontent.com/13464885/41526589-4b3dc7dc-7302-11e8-9905-b5ea7d2d38e2.gif)

**Comment by anbu369** [comment]
Thanks. The problem was with the debugger. I didnt know Toasts doesnt show when debugger is on

**Comment by MatheusNaldi** [comment]
Thanks @anbu369, I lost 2 days in this, you saved me!

**Comment by Anujmoglix** [comment]
hahaha .what the hell does debugger do ? I have already spent much time for previous file upload issue and now for this Toast too.

**Comment by uicestone** [comment]
From my testing, it show's with the debuggers on, but 'eat' the first 3000 duration.

**Comment by franciscojfs** [comment]
What do you mean @anbu369? Have you stoped the remote JS debugging?

**Comment by hariantara** [comment]
disable remote JS debugging solve problem, I don't know why it need disable  
@anbu369 thanks man, you saved me

**Comment by Tahira-SCT** [comment]
I'm facing the same issue without the debugger too. Can someone please help.

"I wrapped the topmost component in Root." 
What do you mean by this?
