### ISSUE TITLE
ListItem with Text not resizing correctly on accessibility large font sizes

### ISSUE THREAD

**Issue by kulack** [GeekyAnts/NativeBase#2017]
Hi, I couldn't find an issue like this.
First off, your native-base is amazingly good. We love having these component/API improvements. Really helps us out!

## react-native, react and native-base version
native-base 2.5.2 (tested on master also)
react-native 0.55.4 (through Expo https://github.com/expo/react-native/archive/sdk-28.0.0.tar.gz)
react 16.3.1

## Expected behaviour
I was hoping that the ListItem would resize vertically allowing the Text component to do the same in a similar fashion to the react-native only solution shown in the demo.

## Actual behaviour
Instead, as the text grows with the accessibility settings the text does not wrap and is truncated

## Steps to reproduce (code snippet or screenshot)
Running demo with toggle to compare react-native and native-base components at https://github.com/kulack/accessibility-example and https://expo.io/@kulack/accessibility-example

## Screenshot of emulator/device
The good view is the one using TouchableOpacity and the bad view is the one using ListItem/Left/Right components. 
![largertext](https://user-images.githubusercontent.com/516613/41482205-7ef184c0-709a-11e8-920e-876cb5910fcb.png)
![goodview](https://user-images.githubusercontent.com/516613/41482210-80da0e4c-709a-11e8-9fe0-8ad2f17a0866.png)
![badview](https://user-images.githubusercontent.com/516613/41482216-82b8723a-709a-11e8-96b0-b21adec53b92.png)

## Is the bug present in both ios and android or in any one of them?
I only have this problem reported by our testers on iOS device, initial testing in Android showed similar problems where the ListItem stayed small and text truncated.

## Any other additional info which would help us debug the issue quicker.
Running demo with toggle to compare react-native and native-base components at https://github.com/kulack/accessibility-example and https://expo.io/@kulack/accessibility-example

**Comment by jordan-mcrae** [comment]
+1

**Comment by akhil-geekyants** [comment]
@kulack `listItem` with `icon` prop has a fixed height. Try adding `height:null` to the styles. Can you try this
```
<ListItem
      icon
      button
      key={`page${index}`}
      onPress={() => this.doItem(item)}
      style={{height:null}}
    >
      <Left style={{height:null}}>
        <Button style={{ backgroundColor: "transparent"}} onPress={() => this.doItem(item)}>
          {item.icon()}
        </Button>
      </Left>
      <Body style={{height:null}}>
        <Text style={{marginRight: 50}}>{item.name()}</Text>
      </Body>
    </ListItem>
```

**Comment by kulack** [comment]
Very nice. This does workaround the issue. Thanks!
