### ISSUE TITLE
How to add shadows to textBox

### ISSUE THREAD

**Issue by rostyys** [GeekyAnts/NativeBase#2018]
Hello, I'm trying to add shadows to `Input`, but it's not working. It works on native `textInput`

```
<Item rounded>
   <Input
      placeholder='New Password'
      success
      style={{
          paddingLeft: 25,
          fontFamily: "SF Pro Text",
          fontSize: 13,
          color: colors.blue,
          shadowColor: colors.black10,
          shadowOffset: {
          	width: 0,
          	height: 10
          },
          shadowRadius: 32,
          shadowOpacity: 1,
      }}
   />
</Item>
```

![image-1-3 copy](https://user-images.githubusercontent.com/6425523/41493957-e9cf4364-70c1-11e8-970f-ac5576d408e3.png)

**Comment by SupriyaKalghatgi** [comment]
@rostyys Works fine with NativeBase Input
![image](https://user-images.githubusercontent.com/13464885/41594932-bcc81692-73e2-11e8-8d2d-8ed5f654bd22.png)

**Comment by SupriyaKalghatgi** [comment]
@rostyys Also that, if you are trying to set bgColor for NativeBase's rounded input, then set that on `Item` and not on `Input`
