### ISSUE TITLE
How to control `Card` padding ?

### ISSUE THREAD

**Issue by theapache64** [GeekyAnts/NativeBase#2020]
How to control the space between `CardItem` and `Card` ? The docs doesn't have any information about 
controlling the `Card` padding. ?

**Comment by SupriyaKalghatgi** [comment]
`listItemPadding` from theme does that
This variable is used commonly between List and Card

**Comment by SupriyaKalghatgi** [comment]
https://github.com/GeekyAnts/NativeBase/commit/470494ca720e553095022b149e49f245cd323654

**Comment by theapache64** [comment]
Ok. thank you for the commit.

I could also fix the issue with this
 ```
<CardItem
                            style={{
                                paddingLeft: 0,
                                paddingRight: 0,
                                paddingTop: 10,
                                paddingBottom: 10
                            }}
                        >
```

**Result**
![image](https://user-images.githubusercontent.com/9678279/41641116-cee8d3ee-7481-11e8-8fd3-9f080741d0a8.png)

**Comment by SupriyaKalghatgi** [comment]
@theapache64 Your query was
> The docs doesn't have any information about controlling the Card padding

Which means you expected some theme variable doing this
If you wanted to do this inline, then no point in questioning docs

**Comment by SupriyaKalghatgi** [comment]
You can always choose between inline style and theme variable (provided consistency) for this

**Comment by theapache64** [comment]
> The docs doesn't have any information about controlling the Card padding

How could i assume that i was expecting theme variables ? Is `docs` means `theme variable` to you ?

**Comment by SupriyaKalghatgi** [comment]
yes ofcourse
Else how can we list down the possibility of combination of inline styles for all the components

**Comment by SupriyaKalghatgi** [comment]
Fixed with [2.6.1](https://github.com/GeekyAnts/NativeBase/releases/tag/v2.6.1)

**Comment by takdol** [comment]
Hi. I'm still facing this issue for the `<CardItem>`. 

Even `paddingHorizontal` and `paddingVertical` does not work

@theapache64's workaround works though. 

Nativebase version: 2.0

**Comment by idhowardgj94** [comment]
> To make all padding to zero, I gave `padding:0` to `CardItem`, It didn't work. but this
> 
> ```
>  paddingLeft: 0,
>  paddingRight: 0,
>  paddingTop: 0,
>  paddingBottom: 0
> ```
> 
> worked.
> 
> Do you know why ?

I wonder to know why, too
