### ISSUE TITLE
Accordion icon direction

### ISSUE THREAD

**Issue by ggolda** [GeekyAnts/NativeBase#2023]
Is it possible to get icon status in custom header for Accordion? I need to draw a different set on icons based on the current status of accordion component (open/closed).

**Comment by SupriyaKalghatgi** [comment]
@ggolda Not really clear with your query
Can you give an example?
Also go through https://github.com/GeekyAnts/NativeBase-KitchenSink for examples and NativeBase Docs https://docs.nativebase.io/Components.html#Layout

**Comment by ggolda** [comment]
@SupriyaKalghatgi 
I'm talking about this accordion feature: http://docs.nativebase.io/Components.html#accordion-custom-header-content-headref

As you can see, in `renderHeader` method it provides only `title` parameter and there is no way to detect if this item is collapsed or expanded to render different icons (e.g. `arrow-up`, `arrow-down`, etc).

![image](https://user-images.githubusercontent.com/38298010/41550915-e0ed87a6-7332-11e8-92b1-934c64ec9cb1.png)

**Comment by SupriyaKalghatgi** [comment]
Fixed with [2.6.1](https://github.com/GeekyAnts/NativeBase/releases/tag/v2.6.1)
