### ISSUE TITLE
IOS 11 Header support

### ISSUE THREAD

**Issue by IbraheemAlSaady** [GeekyAnts/NativeBase#2033]
Are there currently any support for IOS 11 Header like? If not, will it be? 
Something similar to this image

![1_43k66mopfi0zbfyvmdnpoa](https://user-images.githubusercontent.com/14288490/41615793-e09ac4da-7404-11e8-9312-8b21650c2542.jpeg)

Most of IOS 11 apps has an experience similar to this one.

![28991088-f617b5e4-7940-11e7-92ca-ca14ba6b4d5d](https://user-images.githubusercontent.com/14288490/41615864-1b2a594e-7405-11e8-9c80-3780e6fc3245.gif)

Found this article [Here](https://learnui.design/blog/ios-font-size-guidelines.html), thought it might help.

**Comment by SupriyaKalghatgi** [comment]
This is something related to Animation concept
Taking this as feature request
#38

**Comment by SupriyaKalghatgi** [comment]
The 2nd screenshot (GIF) you shared describes about animation
Though the link you shared https://learnui.design/blog/ios-font-size-guidelines.html, describes change in font, alignment etc
