### ISSUE TITLE
RN 0.56 ReactNAtivePropRegistry does not exist in haste map

### ISSUE THREAD

**Issue by slootmaekersdirk** [GeekyAnts/NativeBase#2035]
Hello,

when using NB 2.5.2 with RN 0.56 I get the following error:

error: bundling failed: Error: Unable to resolve module `react-native/Libraries/Renderer/shims/ReactNativePropRegistry` from `../node_modules/native-base/dist/src/utils/computeProps.js`: Module `react-native/Libraries/Renderer/shims/ReactNativePropRegistry` does not exist in the Haste module map
React Native Packager

package.json

    "native-base": "2.5.2",
    "react": "16.3.2",
    "react-native": "0.56.0-rc.2",

any ideas on how to solve this, babel7?

**Comment by SupriyaKalghatgi** [comment]
#2028

**Comment by SupriyaKalghatgi** [comment]
@slootmaekersdirk How did you even manage to run React Native app with 0.56.0-rc.2? Irrespective of NativeBase
I get this 
![image](https://user-images.githubusercontent.com/13464885/41651245-b68ad6aa-749d-11e8-96a3-058f4d8b36fa.png)

**Comment by SupriyaKalghatgi** [comment]
https://github.com/facebook/react-native/issues/19819

**Comment by HilSny** [comment]
I am on 0.56.0-rc.3 and am still getting this error related to native base. 

![screen shot 2018-06-22 at 1 52 43 pm](https://user-images.githubusercontent.com/16581033/41794002-9803c6f6-7623-11e8-9e24-b7c571a5170b.png)

**Comment by SupriyaKalghatgi** [comment]
@HilSny Share `package.json`

**Comment by slootmaekersdirk** [comment]
You shoul use 5.0.1 for react native babel preset to compile , you use 4.0.0

Dirk

**Comment by SupriyaKalghatgi** [comment]
I have marked this duplicate
Comment on #2028
