### ISSUE TITLE
Swipeable List closerow after click

### ISSUE THREAD

**Issue by udarts** [GeekyAnts/NativeBase#2036]
Hi All,

I am wondering how to close a row after I clicked the left button (going to another screen).

I have tried using: rowMap[`${secId}${rowId}`].props.closeRow(); with an onPress

But that basically froze my app.

This is the code I use so far: 

    leftEditBtn(data, secId, rowId, rowMap) {
        return (
            <Button full 
                onPress={() => {
                    this.props.navigation.navigate('EditAnnouncement', {            
                        id: data.key,
                        title: data.title,
                        content: data.content,
                        active: data.active,
                        group: data.group_id,
                        start: data.start,
                        end: data.end,
                    })
                }}
            >
                <Icon active name="create" />
            </Button>
        );
    };

    render() {
        return (
    <List 
        dataSource={this.ds.cloneWithRows(this.state.firebaseItems)}
        renderRow={data => this.renderRow(data)}
        renderLeftHiddenRow={(data, secId, rowId, rowMap) => this.leftEditBtn(data, secId, rowId, rowMap)}
        leftOpenValue={75}
        closeOnRowBeginSwipe={true}
    />
    )}

Anyone an idea?

**Comment by SupriyaKalghatgi** [comment]
Did you go through #1611

**Comment by udarts** [comment]
Tried it and it works. I was first trying to use console.log, but that was eating up my memory, when just using the rowMap, it worked.

**Comment by BukhariMuslim** [comment]
How to close all opened swipe list without access to rowMap?
