### ISSUE TITLE
"Content" don't spread styles to your child "View"

### ISSUE THREAD

**Issue by dakiesse** [GeekyAnts/NativeBase#2038]
## react-native, react and native-base version
"native-base": "master", // 2.4.2
"react": "16.4.1",
"react-native": "0.55.4",

## Expected behaviour
Inner "View" component at "Content" component must get the same styles that and "Content"
![cdc10080ea](https://user-images.githubusercontent.com/5033716/41687117-dca53da0-74e6-11e8-8060-b25154b7e14d.png)

## Actual behaviour
Inner "View" don't have parent styles
![08834d5562](https://user-images.githubusercontent.com/5033716/41687135-e7a5eda8-74e6-11e8-8720-efcb98942805.png)

## Is the bug present in both ios and android or in any one of them?
I have tried it only with Android

## Any other additional info which would help us debug the issue quicker.
I can't display "WebView" for the reason

**Comment by SupriyaKalghatgi** [comment]
Content and View are different components
Did you try the same use case with React Native ScrollView and View?

**Comment by akhil-geekyants** [comment]
@dakiesse can you post the code that causes the Webview to hide. That may help us to provide some workaround.

**Comment by SupriyaKalghatgi** [comment]
@dakiesse We can wait for a day for your response
