### ISSUE TITLE
Card body not being rendered when text overflows

### ISSUE THREAD

**Issue by pulpdood** [GeekyAnts/NativeBase#204]
I'm following the card showcase example in the docs. I can get a couple of cards to display correctly, but if one of the texts overflows, then the cardBody isn't rendered. If there are overflows of texts on both cards it renders properly though. Please see the image below:

![Card](https://i.imgur.com/URUo41O.png)

EDIT:

Here's the same screen but with the strings contracted - it works perfectly in this case:

![Card2](https://i.imgur.com/mI9nfWY.png)

**Comment by SupriyaKalghatgi** [comment]
@pulpdood My `package.json` includes these:
"native-base": "^0.5.8",
"react": "15.3.2",
"react-native": "0.33.0"

I tried your code snippet and included 4 cards, it worked fine for me.
Small glitch on Android while rendering image, but that can be fixed by adding styles

![screen shot 2016-09-28 at 6 57 46 pm](https://cloud.githubusercontent.com/assets/13464885/18915336/4c8ca7d6-85ae-11e6-9908-f238b9555929.png)

What versions of RN and NB are you working on?

**Comment by pulpdood** [comment]
@SupriyaKalghatgi thanks for the reply! My versions were:

"native-base": "^0.5.8",
"react": "15.3.1",
"react-native": "0.33.0",

Tried updating react to 15.3.2 which didn't do anything. It only happens when the first card has long text and the second card has short text that fits. If they both have long text then it renders fine. See below:

![Long story short](https://i.imgur.com/TGS3Mnm.png)

**Comment by sankhadeeproy007** [comment]
Hi @pulpdood please use flex: 0 with card and try.

**Comment by pulpdood** [comment]
Hi @sankhadeeproy007 that has fixed the problem! Thanks! If it's not too much trouble could you maybe explain what this does? Cheers

**Comment by sankhadeeproy007** [comment]
Since you're using multiple cards, and each card by default has a flex value of 1. It tries to render content of equal height. As the content inside are of different height, it refuses to render. Setting flex to 0 allows it to flow freely.

**Comment by cavilaho** [comment]
@sankhadeeproy007 Thanks so much. Make sense! :)

**Comment by liquiddandruff** [comment]
I forgot about the nature of flex properties! I was close to filing a bug report about Cards sharing global state or something--this makes much more sense. Thanks
