### ISSUE TITLE
Can't set Header over the content with absolute positioning

### ISSUE THREAD

**Issue by qlerebours** [GeekyAnts/NativeBase#2040]
## react-native, react and native-base version
React Native: ~0.55.2
Native Base: ^2.4.5

## Expected behaviour
I expect Header to place over the Content and to be fully transparent

## Actual behaviour
If i set a `style={{ backgroundColor: 'transparent' }}`, the background will take the color of the Container background. What I'd like is to place a header over a Map which should take the full height. This is why i tried to set a `style={{ position: 'absolute', left: 0, right: 0, top: 0 }}` on Header, but it disappears.

## Steps to reproduce (code snippet or screenshot)
```
render() {
    return (
      <Container style={{position: 'relative'}}>
          <Header style={{ backgroundColor: 'transparent', zIndex: 1000, position: 'absolute', top: 0, left: 0, right: 0 }}>
            <Left>
              <Button
                transparent
                onPress={() => this.props.navigation.openDrawer()}
              >
                <Icon name="menu"/>
              </Button>
            </Left>
            <Body>
            <Title>Headers</Title>
            </Body>
            <Right/>
          </Header>
          <Content contentContainerStyle={{height: '100%', backgroundColor: 'green'}}>
            <Text>Hello World</Text>
          </Content>
      </Container>
    );
  }
```

## Screenshot of emulator/device
![Screenshot](https://user-ima
ges.githubusercontent.com/17043042/41712482-ecf70c56-754a-11e8-9f9a-ca03b00cffda.png)

## Is the bug present in both ios and android or in any one of them?
I only tried on Android

Thanks for your good work on Native Base ! :)

**Comment by SupriyaKalghatgi** [comment]
@qlerebours The screenshot that you shared, is it expected output or actual output?

**Comment by qlerebours** [comment]
This is the actual output, what is expected would be to get my header over the "Hello world" text. 
This is a simple example, in my App, the green View with text is replaced by a Map (this is why i want the header to be transparent)

**Comment by akhil-geekyants** [comment]
@qlerebours adding `style={{zIndex:-1}}` for `<Content/>` worked for me in iOS but did not work for android. 
Try placing `<Header>` inside `<Content/>`.

**Comment by qlerebours** [comment]
I didn't work, but I finally managed to do it with both your ideas and more (on android):
```
<Content>
    <Header style={{backgroundColor: 'transparent', zIndex: 10000, elevation: 0}}>
    <Map style={{flex: 1, marginTop: -56, zIndex: -1}}></Map>
</Content>
```
I don't really like the negative margin but it works at least.

Thanks for your help
