### ISSUE TITLE
TextArea full height

### ISSUE THREAD

**Issue by udarts** [GeekyAnts/NativeBase#2041]
I just have a question.
How can I make the textarea full height, so it covers the area of the screen (minus a button).
I know I can set the height: height (dimension of the screen) - height of the button.
But that doesn't work quite well, meaning, the height seems to have been set "correctly", but now when I focus the textarea, and the keyboard popsup, it pushes the whole textarea up and the cursor is out of view.

Any idea why?

**Comment by SupriyaKalghatgi** [comment]
@udarts Did you happen to try this with React Native multiline TextInput?

**Comment by akhil-geekyants** [comment]
@udarts set `enableAutomaticScroll` props of `<Content/>` component to false to prevent the keyboard response on focusing `<Textarea/>`. Attaching a gif

![textarea](https://user-images.githubusercontent.com/27768184/41833213-f90c7c72-786c-11e8-83a2-f01ce7cf2051.gif)

**Comment by SupriyaKalghatgi** [comment]
@udarts did you try?

**Comment by udarts** [comment]
Yep, that works, thanks.

**Comment by udarts** [comment]
@akhil-geekyants Yep that works, thanks.

**Comment by trydalch** [comment]
Is it possible to do this without having the top of the text area go off the screen? Have the button float above the textarea?
