### ISSUE TITLE
Pull-to-refresh flatlist nested within a Tab does not capture scroll event (Android)

### ISSUE THREAD

**Issue by Culzean** [GeekyAnts/NativeBase#2042]
Hi! Thanks for trying out NativeBase!
Due to the overwhelming requests and issues/questions we ask you to add the following details with your issue.

Please check the existing open/closed issues for a possible duplicate before creating a new issue :)

Also **DO** fill out the below form to give us a better idea about your environment and help us debug it quicker. Issues without the required details will mostly be unattended to.

## react-native, react and native-base version
react-native-cli: 2.0.1
react-native: 0.55.4
native-base: 2.5.2
## Expected behaviour

Tabs have horizontal swipes. Once a pull to re-fresh has started on my flatlist within one of these tabs, I expect there to be no swipe left or right to move the tabs until the pull event has completed and a new swipe begins.

## Actual behaviour

The pull to refresh can be completed if the swipe is completely vertical. Any deviation on the horizontal will cause the tabs to swipe and pull event be ejected without completing correctly.

## Steps to reproduce (code snippet or screenshot)

![screenshot_20180621-151155](https://user-images.githubusercontent.com/719554/41724468-8339efe8-7565-11e8-96c4-427cabd32945.png)

## Is the bug present in both ios and android or in any one of them?

I have only seen this in Android. on device with Android v7.0. Seemed fine in iOS.

**Comment by akhil-geekyants** [comment]
Related issue https://github.com/GeekyAnts/NativeBase/issues/1371

**Comment by SupriyaKalghatgi** [comment]
https://github.com/GeekyAnts/NativeBase/issues/1168#issuecomment-328489168

**Comment by SupriyaKalghatgi** [comment]
>  Any deviation on the horizontal will cause the tabs to swipe and pull event be ejected without completing correctly.

Found same behavior with FB app
