### ISSUE TITLE
Documentation has mistake connected with List component

### ISSUE THREAD

**Issue by dakiesse** [GeekyAnts/NativeBase#2043]
## react-native, react and native-base version
"native-base": "2.5.2",
"react": "16.4.1",
"react-native": "0.55.4",

## Expected behaviour
List component has to accept "dataSource" prop.
## Actual behaviour
List component doesn't handle this prop. Constructor of List component knows only about dataArray prop.

![image](https://user-images.githubusercontent.com/5033716/41725652-a746ee26-7570-11e8-8ae1-d2cb4fdebe7b.png)

**Comment by SupriyaKalghatgi** [comment]
https://github.com/GeekyAnts/native-base-docs/issues/106
