### ISSUE TITLE
How to achieve header elevation starting from 2.4.5?

### ISSUE THREAD

**Issue by pentanaveen** [GeekyAnts/NativeBase#2048]
##Versions
react-native - 0.55.4
native-base - 2.4.5 and above

##Issue
Android Specific - Header elevation worked as expected till 2.4.4 and elevation isn't being applied starting from 2.4.5.I see that for 2.4.5 `Fixed Header as per iOS and material design guidelines`.How to achieve elevation for header starting from 2.4.5.Previously it used to work with 
`<Header style={{ elevation: 2 }}></Header>`.Thank you.

**Comment by SupriyaKalghatgi** [comment]
@pentanaveen Sharing screenshots for same can help us to provide answer
Can you share screenshot with default NativeBase Header and other with `<Header style={{ elevation: 2 }}></Header>`

**Comment by akhil-geekyants** [comment]
Related to react native issue https://github.com/facebook/react-native/issues/19869
