### ISSUE TITLE
Picker wont work

### ISSUE THREAD

**Issue by yeknava** [GeekyAnts/NativeBase#205]
I just copy pasted picker example but it wont work cuz Picker.Item is empty.
its worked when i import Item from native-base instead of Picker.Item but then i got this warning message for each of my items:

"Warning: React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components). Check the render method of `PickerExample`."

testing on android, react-native 0.33

**Comment by SupriyaKalghatgi** [comment]
@yeknava Can you post the code snippet you have been trying?

**Comment by yeknava** [comment]
```javascript
import React, { Component } from 'react';
import { Container, Content, Picker } from 'native-base';

const Item = Picker.Item;​
export default class PickerExample extends Component {

    constructor(props) {
        super(props);
        this.state = {
            selectedItem: undefined,
            selected1: 'key1',
            results: {
                items: []
            }
        }
    }
    onValueChange (value: string) {
        this.setState({
            selected1 : value
        });
    }

    render() {
        return (
            <Container>
                <Content>
                    <Picker
                        iosHeader="Select one"
                        mode="dropdown"
                        selectedValue={this.state.selected1}
                        onValueChange={this.onValueChange.bind(this)}>
                        <Item label="Cats" value="key0" />
                        <Item label="Dogs" value="key1" />
                        <Item label="Birds" value="key2" />
                        <Item label="Elephants" value="key3" />
                   </Picker>
                </Content>
            </Container>
        );
    }
}
````

**Comment by SupriyaKalghatgi** [comment]
@yeknava Can you post iOS and Android screenshots for same

**Comment by yeknava** [comment]
i can but there isn't any useful information in there. that Red screen with this message:

"Did not get valid calls back from JS."

my phone runs android 6.
BTW it may be react native problem cuz Picker.Item is empty there too.

**Comment by yeknava** [comment]
Its worked.
Picker.Item is empty only when im on a Scene component in react-native-router-flux.
its works well when i put my code in a sub component.

**Comment by mauron85** [comment]
@yeknava Same problem with putting Picker into Navigator's Scene. How did you resolved it?

**Comment by yeknava** [comment]
@mauron85 just make another component and import your base component that contains Picker.

what i found is you can't use Picker in a component that is Navigator's Scene, you just need put Picker in another component (Ex. PickerContainerComponent) then import it in your Scene component.

**Comment by jmfirth** [comment]
I'm running into this problem right now with Picker and react-native-router-flux.  I tried the above multiple ways and could not make it successfully work.

**Comment by mostafiz93** [comment]
Using Picker.Item directly can solve the issue. Don't declare `const Item = Picker.Item;`​, use this:
`<Picker.Item label="Wallet" value="key0" />`

**Comment by ceefour** [comment]
I think the docs should be updated to remove this `const Item = Picker.Item;` shortcut, it's making debugging unnecessary hard and it's better to be specific anyway.

**Comment by MbF-Sathya** [comment]
@SupriyaKalghatgi in android picker i can't use search. in iOS its perfect 
![simulator screen shot - iphone 6 - 2018-03-06 at 13 07 12](https://user-images.githubusercontent.com/22494237/37019693-4bbde79c-213f-11e8-90d7-40032479c39d.png)

**Comment by akhil-geekyants** [comment]
@MbF-Sathya can you post your code
