### ISSUE TITLE
Picker Item custom content

### ISSUE THREAD

**Issue by raideltorres** [GeekyAnts/NativeBase#2054]
Hi sorry to ask this here guys since is not a bug (but it could be an enhancement ).

Basically my question is how could I set a custom content for the Picker.Item ? basically I need to add an image and a couple labels there, is this posible right now?

**Comment by akhil-geekyants** [comment]
@raideltorres  `Picker.Item` takes only label. `Picker.item` does not take custom components as of now.

**Comment by SupriyaKalghatgi** [comment]
@raideltorres Anything else we can help you here?

**Comment by akhil-geekyants** [comment]
@raideltorres NativeBase picker for android is an implementation of React Native Picker. React Native `Picker.Item` allows only two props - label and key, where type of label is a string. So the proposed enhancement is not supported by React Native on Android platform.
