### ISSUE TITLE
scrollable tab bar background color unable to change

### ISSUE THREAD

**Issue by HJ29** [GeekyAnts/NativeBase#2057]
## react-native, react and native-base version
react-native 0.55.4
react 16.0.0
native-base 2.4.4
## Expected behaviour
able to change scrollable tab's background color
## Actual behaviour
unable to change the default color #3f51b5.
## Steps to reproduce (code snippet or screenshot)
scrollable tab code
![native-base-scrollable-code-tab](https://user-images.githubusercontent.com/24311533/41910150-646385ec-797b-11e8-854f-086acfe6de70.jpg)
1. tried change material theme.
![native-base-scrollable-code](https://user-images.githubusercontent.com/24311533/41909686-4170ace6-797a-11e8-8186-aeec5f02cc37.jpg)
theme imported.
![native-base-scrollable-code-provider](https://user-images.githubusercontent.com/24311533/41909831-8d1bc658-797a-11e8-9886-645ac23e2d65.jpg)
2. tried changing tabStyle backgroundColor on tab

## Screenshot of emulator/device
here is the result, the blue color unable to change
![native-base-scrollable](https://user-images.githubusercontent.com/24311533/41909494-b9221b04-7979-11e8-930b-76435aeae915.jpg)
## Is the bug present in both ios and android or in any one of them?
only tried on android
## Any other additional info which would help us debug the issue quicker.
no

**Comment by akhil-geekyants** [comment]
@HJ29 try setting `backgroundColor` to `ScrollableTab`

like
```
<Tabs renderTabBar={() => <ScrollableTab style={{ backgroundColor: "white" }} />}>
```

**Comment by SupriyaKalghatgi** [comment]
@HJ29 Closing this in a day in case of no response

**Comment by HJ29** [comment]
@akhil-geekyants Thanks for your help! Your answer is correct and clear.

**Comment by ravirupareliya** [comment]
Or you can use `tabBarBackgroundColor` property of `<Tabs>`

    <Tabs tabBarBackgroundColor={'#ffffff'}

**Comment by egaslan** [comment]
@HJ29 you can try this code. 'ScrollableTab' and 'TabHeading ' are important.

<Tabs transparent renderTabBar={()=> <ScrollableTab style={{ backgroundColor: "#ccc" }} />}>                  
    <Tab heading={ 
        <TabHeading style={{ backgroundColor: "#ccc" }}><Icon name="home"/>
            <Text>Home</Text>
        </TabHeading>}>
       <TabOne/>
    </Tab>
</Tabs>

**Comment by anhhtz** [comment]
> @HJ29 try setting `backgroundColor` to `ScrollableTab`
> 
> like
> 
> ```
> <Tabs renderTabBar={() => <ScrollableTab style={{ backgroundColor: "white" }} />}>
> ```

You saved my life today :100:

**Comment by devanshujain95** [comment]
Set property **transparent** for Tabs component.
```
<Tabs transparent renderTabBar={() => <ScrollableTab style={{backgroundColor: 'red'}} />}>
```
Unless, background color for the tabs won't change.

Native base documentation needs to be corrected.

**Comment by harisahmedDCS** [comment]
can we do vertical  scrollable tab
