### ISSUE TITLE
Separator with long text doesn't wrap text

### ISSUE THREAD

**Issue by nbastoWM** [GeekyAnts/NativeBase#2058]
## react-native, react and native-base version
react-native 0.55.4
react 16.0.0
native-base 2.4.4

## Expected behaviour
In a <Separator> with long text inside, the text should wrap and show in multiple lines

## Actual behaviour
In a <Separator> with long text inside, the text doesn't wrap

## Code

```
 <Separator  style={{flex:1}} bordered>
      <Text style={{flex:1}}>{this.props.title.toUpperCase()}</Text>
 </Separator>
```

(I tried with and without styles)

**Comment by SupriyaKalghatgi** [comment]
@nbastoWM Did you try?

**Comment by nbastoWM** [comment]
It worked! Thank you.
