### ISSUE TITLE
Toast blocks interaction of components underneath if margin is set.

### ISSUE THREAD

**Issue by newbiemate** [GeekyAnts/NativeBase#2059]
I want to show a Toast at the bottom of the screen, but I also have buttons there. To put the Toast above the buttons, I set a `marginBottom: 50` so that the Toast will sit above the buttons.

However, when the Toast shows, **although I can see my buttons it will not let me interact with them**. I think the `marginBottom` is absorbing the clicks that are meant for the buttons.

Here is the Toast code:

            Toast.show({
                text: "Done!",
                duration: 4000,
                style: { marginBottom: 50 }
            });

How can I get the Toast to show 50 pixels above the default position for `position: bottom` and still have my buttons be interactable?

**Comment by SupriyaKalghatgi** [comment]
Toast has higher elevation, hence it remains in foreground unless it is closed. This is as per design guidelines
If you want both, Button and Toast to be interactive, then try reducing elevation of Toast

Button
![image](https://user-images.githubusercontent.com/13464885/41952406-49daf170-79ed-11e8-8308-928f2a761137.png)

Toast
![image](https://user-images.githubusercontent.com/13464885/41952415-5c4a86c2-79ed-11e8-8523-2d2569d7b96a.png)

**Comment by SupriyaKalghatgi** [comment]
@newbiemate did you try?

**Comment by SupriyaKalghatgi** [comment]
@newbiemate Closing this in a day on case of no response
