### ISSUE TITLE
Make parallax tab header 

### ISSUE THREAD

**Issue by cklinx** [GeekyAnts/NativeBase#2060]
I cant figure out how make parallex tab header with native base.

Anyone knows how do it?

I needs something like this: https://snack.expo.io/@satya164/collapsible-header-with-tabview.

Thanks in advance

**Comment by SupriyaKalghatgi** [comment]
This query is more suitable to be asked on SO or NativeBase slack

**Comment by SupriyaKalghatgi** [comment]
Not exactly what you asked, but quite similar https://github.com/pranit123/Twitter-Clone
