### ISSUE TITLE
Card Left Border is always Gray 

### ISSUE THREAD

**Issue by ntomallen** [GeekyAnts/NativeBase#2061]
## react-native, react and native-base version
React native: 0.53.4
React: 16.4.0
native-base: 2.6.0

## Expected behaviour
When setting border left color (to any custom color), the correct color will display on Android

## Actual behaviour
When setting border left color to any color and width, the border color always displays gray

## Steps to reproduce (code snippet or screenshot)
Try using the `<Card />` element with the following style:
```
  card: {
    flexDirection: 'row',
    height: cardHeight,
    width: cardWidth,
    borderRadius: cardRadius,
    alignSelf: 'center',
    marginBottom: 3,
    marginTop: 3,
    borderLeftWidth: 5,
    borderLeftColor: '#ea7e7a'
  }
```
## Screenshot of emulator/device
<img width="349" alt="gray" src="https://user-images.githubusercontent.com/6265975/41943300-e2c83924-7970-11e8-99ef-f8bdbb7b54bb.png">
(The color is always gray no matter what I set it to.)

## Is the bug present in both ios and android or in any one of them?
Bug is only present on Android, not iOS.

## Any other additional info which would help us debug the issue quicker.
I was setting the colors dynamically based on the properties given to the component, but it seems to still exist when setting it manually in styles.

**Comment by akhil-geekyants** [comment]
@ntomallen add border color to CardItem instead of Card.
Code
```
import React, { Component } from 'react';
import { StyleSheet } from "react-native";
import { Container, Header, Content, Card, CardItem, Body, Text } from 'native-base';

export default class App extends Component {
  render() {
    return (
      <Container>
        <Header />
        <Content>
          <Card style={styles.card}>
            <CardItem style={styles.cardItem}>
              <Body>
                <Text>
                  Test 
                </Text>
              </Body>
            </CardItem>
          </Card>
        </Content>
      </Container>
    );
  }
}

const styles = StyleSheet.create({
  card: {
   // flexDirection: 'row',
    height: undefined,
    width: undefined,
    // alignSelf: 'center',
    marginBottom: 3,
    marginTop: 3,
    borderRadius: 3,
  },
  cardItem: {
    borderLeftWidth: 5,
    borderLeftColor: '#ea7e7a'
  }

})

```

**Comment by ntomallen** [comment]
Thanks, that worked!
