### ISSUE TITLE
Action sheet at the top

### ISSUE THREAD

**Issue by emtiajium** [GeekyAnts/NativeBase#2063]
How to set action sheet at the top (just beneth header)? 

(I know this isn't a issue, but I don't know where to ask this.)

![action_sheet](https://user-images.githubusercontent.com/20053629/41968759-262dc54c-7a27-11e8-90ab-26cd2a630304.png)

**Comment by SupriyaKalghatgi** [comment]
@emtiajium This seems to be asked on SO or NativeBase slack
Hence closing this
