### ISSUE TITLE
Getting _react2.proptypes.oneof after creating a new project with "init", before it was working in expo. Guess its with Native base icons and i also installed proptype package. Still not working.

### ISSUE THREAD

**Issue by swaroopgs** [GeekyAnts/NativeBase#2064]
Hi! Thanks for trying out NativeBase!

Take a look at these before heading towards creating an issue
-   Check latest documentation: https://docs.nativebase.io/
-   Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
-   Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
-   For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/

Also **DO** fill out the below form to give us a better idea about your environment and help us debug it quicker. Issues without the required details will mostly be closed.

**Comment by Aruneel** [comment]
i am having the same issue. somebody help.

**Comment by SupriyaKalghatgi** [comment]
We are automatically closing this issue because it does not appear to follow as per the provided [issue template](https://github.com/GeekyAnts/NativeBase/blob/master/ISSUE_TEMPLATE.txt).

If you'd like to start a discussion, check out http://slack.nativebase.io/
