### ISSUE TITLE
Change a theme in Vue Native 

### ISSUE THREAD

**Issue by kranopodem** [GeekyAnts/NativeBase#2067]
Hello. Why are StyleProvider not taking a theme, and throwing Warning "Failed prop type: Invalid prop style of type array supplied to StyleProvider, expected object."

`<template>`
`<nb-style-provider v-bind:style="getTheme(material)">`
`<nb-container>`
`<nb-text>Contact</nb-text>`
`</nb-container>`
`</nb-style-provider>`
`</template>`
`<script>`
`import Vue from "vue-native-core";`
`import {VueNativeBase} from "native-base";`
`import getTheme from './native-base-theme/components';`
`import material from './native-base-theme/variables/material';`

`Vue.use(VueNativeBase);`
`export default {`
  `data: function() {`
   ` return {`
    `  getTheme: getTheme,`
     ` material: material,`
    `};`
  `},`
`};`
`</script>`

**Comment by gauravprwl14** [comment]
@kranopodem It's known issue and we are working on it. For time been you can create a a container wrapper with styleWrapper.js file 
```
import {
   StyleProvider
} from "native-base";
import React, {
   Component
} from "react";

import getTheme from "../../native-base-theme/components";
import variables from "../../native-base-theme/variables/commonColor";

export default class StyleWrapper extends Component {
   render() {
       return (
       <StyleProvider style={getTheme(variables)}>
       {this.props.children}
     </StyleProvider>  
   )
   }
}
```

Now You can wrapper your app.vue inside styleWrapper
```
<template>
  <style-wrapper>
    <nb-container>
        <nb-text>Contact</nb-text>
    </nb-container>
  </style-wrapper>
</template>
<script>
import StyleWrapper from './styleWrapper;'
import Vue from "vue-native-core";
import {VueNativeBase} from "native-base";
Vue.use(VueNativeBase);
export default {
components: {StyleWrapper},
data: function() {
return {
getTheme: getTheme,
material: material,
};
},
};
</script>
```

**Comment by NikolaNikushev** [comment]
> @kranopodem It's known issue and we are working on it. For time been you can create a a container wrapper with styleWrapper.js file
> 
> ```
> import {
>    StyleProvider
> } from "native-base";
> import React, {
>    Component
> } from "react";
> 
> import getTheme from "../../native-base-theme/components";
> import variables from "../../native-base-theme/variables/commonColor";
> 
> export default class StyleWrapper extends Component {
>    render() {
>        return (
>        <StyleProvider style={getTheme(variables)}>
>        {this.props.children}
>      </StyleProvider>  
>    )
>    }
> }
> ```
> 
> Now You can wrapper your app.vue with styleWrapper
> 
> ```
> <template>
>   <style-wrapper>
>     <nb-container>
>         <nb-text>Contact</nb-text>
>     </nb-container>
>   </style-wrapper>
> </template>
> <script>
> import StyleWrapper from './styleWrapper;'
> import Vue from "vue-native-core";
> import {VueNativeBase} from "native-base";
> Vue.use(VueNativeBase);
> export default {
> components: {StyleWrapper},
> };
> </script>
> ```

Thanks man! This is exactly what I was looking for! Works perfectly!

**Comment by riteshjha** [comment]
> @kranopodem It's known issue and we are working on it. For time been you can create a a container wrapper with styleWrapper.js file
> 
> ```
> import {
>    StyleProvider
> } from "native-base";
> import React, {
>    Component
> } from "react";
> 
> import getTheme from "../../native-base-theme/components";
> import variables from "../../native-base-theme/variables/commonColor";
> 
> export default class StyleWrapper extends Component {
>    render() {
>        return (
>        <StyleProvider style={getTheme(variables)}>
>        {this.props.children}
>      </StyleProvider>  
>    )
>    }
> }
> ```
> 
> Now You can wrapper your app.vue with styleWrapper
> 
> ```
> <template>
>   <style-wrapper>
>     <nb-container>
>         <nb-text>Contact</nb-text>
>     </nb-container>
>   </style-wrapper>
> </template>
> <script>
> import StyleWrapper from './styleWrapper;'
> import Vue from "vue-native-core";
> import {VueNativeBase} from "native-base";
> Vue.use(VueNativeBase);
> export default {
> components: {StyleWrapper},
> };
> </script>
> ```

Not working, gettting this error

 ERROR    Error: React.Children.only expected to receive a single React element child.
