### ISSUE TITLE
IOS11 large header feature

### ISSUE THREAD

**Issue by udarts** [GeekyAnts/NativeBase#2075]
I was wondering if you are planning to update the header to be able to use tge IOS 11 large header as well.

**Comment by SupriyaKalghatgi** [comment]
@udarts Can you try `span` with `Header` for this?
Here it is https://docs.nativebase.io/Components.html#header-span-headref

**Comment by akhil-geekyants** [comment]
@udarts can we close this issue.

**Comment by udarts** [comment]
Tried it, but that seems to only moving the title lower and doesn't have the animated (from large to small title). Or is that something that needs to be created manually?

**Comment by akhil-geekyants** [comment]
@udarts `native-base` Header currently does not have animations of its own.
