### ISSUE TITLE
How do u guys show cat-log in Atom IDE ?  #React-native

### ISSUE THREAD

**Issue by mahgolfa** [GeekyAnts/NativeBase#2076]
Hi! Thanks for trying out NativeBase!

Take a look at these before heading towards creating an issue
-   Check latest documentation: https://docs.nativebase.io/
-   Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
-   Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
-   For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/

Also **DO** fill out the below form to give us a better idea about your environment and help us debug it quicker. Issues without the required details will mostly be closed.

**Comment by SupriyaKalghatgi** [comment]
Please follow instructions mentioned in issue template
Failing which this issue will be closed
