### ISSUE TITLE
How do I change icon text styles of Picker?

### ISSUE THREAD

**Issue by wzup** [GeekyAnts/NativeBase#2077]
How do I change icon text styles of Picker?

![screen shot 2018-06-30 at 6 54 12 pm](https://user-images.githubusercontent.com/3880497/42126868-513de510-7c97-11e8-82e1-ca4e131e6e27.png)

**Comment by SupriyaKalghatgi** [comment]
Please follow instructions mentioned in issue template
Failing which this issue will be closed

**Comment by wzup** [comment]
LOL
