### ISSUE TITLE
Cannot center Icon when resizing button to a custom height/width

### ISSUE THREAD

**Issue by newbiemate** [GeekyAnts/NativeBase#2080]
The following button will not center its icon:

```
<View>
    <Button bordered info style={{alignSelf: 'flex-end', height: 24, width: 24, justifyContent: 'center'}}>
        <Icon name="info" style={{width: 24, height: 24}} />
    </Button>
</View>
```

[The result](https://imgur.com/a/5J6OiGB)

How can I center the icon inside a custom button size? And is there a way automatically scale down the Icon size to fit within the given button size? Because if I don't provide the `width` or `height` on the `Icon` element, then the icon **disappears**.

**Comment by akhil-geekyants** [comment]
@newbiemate this is due to the default height and padding given to the button. Also, Icon has some default margin. Try changing these values.

```
<View>
  <Button bordered info style={{ alignSelf: 'flex-end', paddingTop: 0, paddingBottom: 0, height: 35, width: 35, justifyContent: "center" }}>
    <Icon name="ios-information-circle" style={{ marginLeft: 0, marginRight: 0, fontSize: 24 }} />
  </Button>
</View>
```
![screen shot 2018-07-02 at 12 31 28 pm](https://user-images.githubusercontent.com/27768184/42149491-eb36c0da-7df3-11e8-9ea7-dcd2bfbdec27.png)

**Comment by akhil-geekyants** [comment]
@newbiemate did this work for you. Can we close this issue.

**Comment by newbiemate** [comment]
Yes, thank you!
