### ISSUE TITLE
Add Props in Scrollable tab in Documentation

### ISSUE THREAD

**Issue by kristinadarroch** [GeekyAnts/NativeBase#2085]
When trying to modify the <ScrollableTab> component it took forever to figure out the props (tabHeaderStyle, tabsContainerStyle, tabFontSize). In the documentation there is currently only the tabStyle, activeTabStyle, textStyle, and activeTextStyle. It would be great to add more about the properties in the docs.

**Comment by SupriyaKalghatgi** [comment]
https://github.com/GeekyAnts/native-base-docs/issues/112
