### ISSUE TITLE
Can't change icon family

### ISSUE THREAD

**Issue by oldo** [GeekyAnts/NativeBase#2088]
## node, npm, react-native, react and native-base version

node: v8.7.0
npm: 5.6.0
react-native: 0.53.0
native-base: 2.3.1

## Expected behaviour

Passing `type` as a prop into an `Icon` component should set the font family.

## Actual behaviour

`filter` is a valid part of the `Feather` family:
<img width="202" alt="screen shot 2018-07-03 at 16 07 27" src="https://user-images.githubusercontent.com/4557648/42224800-40ffdc80-7edb-11e8-811a-1b27ad239264.png">

However when I create a component like:
`<Icon type="Feather" name="filter" />`

I get:
<img width="396" alt="screen shot 2018-07-03 at 16 08 42" src="https://user-images.githubusercontent.com/4557648/42224885-77963fd2-7edb-11e8-90f1-cdacf27b9a88.png">

**Comment by oldo** [comment]
The only icon family that I can use it seems is the default `Ionicons`

**Comment by SupriyaKalghatgi** [comment]
NativeBase is on 2.6.1
You are using 2.3.1, quite old one

**Comment by SupriyaKalghatgi** [comment]
Go through release notes to use this feature of Icon

**Comment by oldo** [comment]
Ha! That fixed it. Thanks for your prompt response @SupriyaKalghatgi
