### ISSUE TITLE
How do I use different type of font icons in my react native app?

### ISSUE THREAD

**Issue by prashen** [GeekyAnts/NativeBase#209]
There is no cheatsheet of icons in NativeBase site. So it's difficult to choose icons. I have used many fontawesome icon names but it's not working.

**Comment by sankhadeeproy007** [comment]
NativeBase uses icons from [react-native-vector-icons](https://github.com/oblador/react-native-vector-icons) So all the icons available there can be used in NativeBase. You can set the default iconFamily in the variable file.

**Comment by prashen** [comment]
I am using like this:
I removed `Icon` from `import { Content, List, ListItem, Button } from 'native-base';`

and using like this:

`import Icon from 'react-native-vector-icons/FontAwesome';`

`<Icon name="facebook"  />`

It's working but tell me one thing, Is it the right way?

**Comment by sankhadeeproy007** [comment]
The ideal way is to set the variable here
http://nativebase.io/docs/v0.5.7/theme-variables
