### ISSUE TITLE
React Native Datepicker is undefined or type is invalid -- expected a string  

### ISSUE THREAD

**Issue by mrkhanakia** [GeekyAnts/NativeBase#2092]
I am trying to run an example but getting error https://docs.nativebase.io/Components.html#date-picker-def-headref

React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

When i console.log(DatePicker) in constructor then it says undefined so anyway DatePicker is not working

**Comment by SupriyaKalghatgi** [comment]
Please follow instructions mentioned in issue template
Failing which this issue will be closed

**Comment by SupriyaKalghatgi** [comment]
Also, probably you are searching for Date Picker with wrong version of NativeBase
Check release notes before using any new component / prop

**Comment by mrkhanakia** [comment]
Thanks it is working now i was using older version.
