### ISSUE TITLE
Toastr error Cannot read property '_root' of undefined

### ISSUE THREAD

**Issue by mrkhanakia** [GeekyAnts/NativeBase#2093]
I am trying to make toastr example working but getting error https://docs.nativebase.io/Components.html#toast-def-headref

![screen shot 2018-07-04 at 10 22 24 am](https://user-images.githubusercontent.com/2174170/42257449-30b4b654-7f74-11e8-835f-4165ccc62cbb.png)

<img width="375" alt="screen shot 2018-07-04 at 10 21 16 am" src="https://user-images.githubusercontent.com/2174170/42257420-0ecc642e-7f74-11e8-88c9-a62a2d2ceea7.png">

**Comment by SupriyaKalghatgi** [comment]
@mrkhanakia did you add `Root`?
![image](https://user-images.githubusercontent.com/13464885/42257721-96895d08-7f75-11e8-8a2a-e607f3a07a4d.png)

**Comment by kuldeepoza** [comment]
set
start <Root>
end </Root>
in your currunt screen

**Comment by menarayanzshrestha** [comment]
Here is the docs for using Toast :
    https://docs.nativebase.io/Components.html#toast-def-headref

import { Root } from 'native-base';
