### ISSUE TITLE
iPhoneX - Footer calculateHeight crash

### ISSUE THREAD

**Issue by victormartingarcia** [GeekyAnts/NativeBase#2095]
I'm getting a crash when using Footer on the iPhone X. 

Perhaps I am passing a quite strange **this.props.style** configuration:

<img width="283" alt="captura de pantalla 2018-07-04 a las 11 20 42" src="https://user-images.githubusercontent.com/659832/42268642-54979340-7f7c-11e8-8720-4444d0b9fc5a.png">

(Notice that this.props.style[1] is undefined)

Anyway, it's an easy fix and I'll try to send you my first PR. 

Hope it helps!

**Comment by victormartingarcia** [comment]
Please, try with these props:

`
<Footer
style={[
    {
      backgroundColor: "#232323"
    },
    {
        display: 'flex'
    }
]}>
`

**Comment by SupriyaKalghatgi** [comment]
@victormartingarcia Your reply is incomplete

**Comment by SupriyaKalghatgi** [comment]
Closing this today in case of no response
