### ISSUE TITLE
native base drawer navigation not working

### ISSUE THREAD

**Issue by The-FZ** [GeekyAnts/NativeBase#2098]
native base drawer navigation is not working. I am using react navigation. The drawer is there but not able to navigate to any screen via the sidebar(drawer).
![screenshot_2018-07-04-16-02-03-358_host exp exponent](https://user-images.githubusercontent.com/6598644/42272714-a8f708a8-7fa4-11e8-9652-c7afa383436c.png)

**Comment by SupriyaKalghatgi** [comment]
@The-FZ Sorry to inform you this, we are deprecating NativeBase Drawer, since `react`navigation` is favoured more
