### ISSUE TITLE
Documentation for Card List is incomplete

### ISSUE THREAD

**Issue by olivergeorge** [GeekyAnts/NativeBase#2105]
The example provided doesn't quite work.  Doesn't use full width (and doesn't look like the example).

I think the example is missing <Left> and/or <Body> elements.

```
<CardItem>
<Icon active name="logo-googleplus" />
<Text>Google Plus</Text>
<Right>
<Icon name="arrow-forward" />
</Right>
</CardItem>
```

**Comment by SupriyaKalghatgi** [comment]
https://github.com/GeekyAnts/native-base-docs/issues/114
