### ISSUE TITLE
Module `react-native/Libraries/Renderer/shims/ReactNativePropRegistry` does not exist in the Haste module map

### ISSUE THREAD

**Issue by kkotkkio** [GeekyAnts/NativeBase#2107]
#package.json

{
  "name": "ZzimIos",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "native-base": "^2.6.1",
    "prop-types": "^15.6.1",
    "react": "16.3.1",
    "react-native": "^0.56.0",
    "react-native-app-intro-slider": "^0.2.4",
    "react-native-awesome-alerts": "^1.0.6",
    "react-native-gifted-chat": "^0.3.0",
    "react-native-keyboard-aware-scroll-view": "^0.4.4",
    "react-native-navigation": "^2.0.2397",
    "react-native-scalable-image": "^0.2.2",
    "react-native-splash-screen": "^3.0.6",
    "react-redux": "^5.0.7",
    "recompose": "^0.26.0",
    "redux": "^3.7.2",
    "redux-devtools-extension": "^2.13.2",
    "redux-logger": "^3.0.6",
    "redux-thunk": "^2.2.0",
    "styled-components": "^3.2.5"
  },
  "devDependencies": {
    "babel-jest": "22.4.3",
    "babel-eslint": "^8.0.2",
    "babel-plugin-module-resolver": "^3.0.0",
    "eslint": "^4.11.0",
    "eslint-config-airbnb": "^16.1.0",
    "eslint-plugin-import": "^2.8.0",
    "eslint-plugin-jsx-a11y": "^6.0.2",
    "eslint-plugin-react": "^7.4.0",
    "eslint-plugin-react-native": "^3.2.1",
    "jest": "22.4.3",
    "react-test-renderer": "16.3.1",
    "react-native-debugger-open": "^0.3.17"
  },
  "jest": {
    "preset": "react-native"
  }
}

I did 'npm install' because version of react-native-navigation is updated and then I got this error.

error: bundling failed: Error: Unable to resolve module `react-native/Libraries/Renderer/shims/ReactNativePropRegistry` from `/Users/munseongsu/Desktop/_my_project/meu/ZzimIos/node_modules/native-base/dist/src/utils/computeProps.js`: Module `react-native/Libraries/Renderer/shims/ReactNativePropRegistry` does not exist in the Haste module map

I am searching now but I couldn't find any solution.
What's the problem?

**Comment by SupriyaKalghatgi** [comment]
#2028

**Comment by pranavpk** [comment]
remove  "native-base": "^2.6.1", 

from package.json 

and run 

npm install native-base --save

**Comment by Aravindsys** [comment]
Thank you vey much @pranavpk . It solved my issue
