### ISSUE TITLE
I cannot find any list of the available Icon Names

### ISSUE THREAD

**Issue by codeundercoverdev** [GeekyAnts/NativeBase#211]
Using the tutorial, I very easily created an icon:

    <Icon name='ios-mic-outline' />

I cannot find where this icon name came from or find a list of other icons in the ios-mic family.  How do I find them?

**Comment by wkw** [comment]
I'm not a familiar with this repo, but looking at the dependencies, I'd suggest you look around here https://github.com/oblador/react-native-vector-icons

**Comment by codeundercoverdev** [comment]
Thanks @wkw , but I've looked through that and can't find any referrences to icon names that start with "ios-"

**Comment by codeundercoverdev** [comment]
Ahh got it!  You have to click right on the ionicons link.

**Comment by bradlis7** [comment]
I was also having issues with this lack of documentation, but I think IonIcons is the default, but you can choose a different icon set in your NativeBase theme file.
