### ISSUE TITLE
Is there a way of having a breakline in a button text?

### ISSUE THREAD

**Issue by benjaminb10** [GeekyAnts/NativeBase#2115]
Is there a way of having a breakline in a button text?

The following code:

```
          <Button>
              <Text>
                  This should be a~{"\n"}two lines button
              </Text>
          </Button>
```
Give this result:

<img width="135" alt="screenshot_2018-07-09 15 01 31_t61pqu" src="https://user-images.githubusercontent.com/2952678/42451997-1c172524-8389-11e8-8dd1-5bf32279b97a.png">

**Comment by SupriyaKalghatgi** [comment]
This issue does not follow Issue template guidelines
