### ISSUE TITLE
[Feature-Request] give Accordion a flexible dataArray

### ISSUE THREAD

**Issue by ImBeCiliC** [GeekyAnts/NativeBase#2116]
Possibility to give custom render method of Accordion a different dataArray.
In the current code the renderHeader prop receives item.title and renderContent prop receives item.content.
It would be more flexible to add the whole array of data to a custom render. This way it would be possible to use data which was fetched via an api call and display that in the custom accordion.

The line to change is in Accordion.js line 102, 103
from: ` {this.props.renderHeader ? (
              this.props.renderHeader(this.props.item.title, this.props.expanded)`
to:  ` {this.props.renderHeader ? (
              this.props.renderHeader(this.props.item, this.props.expanded)`

and line 119, 120
from: `{this.props.renderContent ? (
              this.props.renderContent(this.props.item.content)`
to: `{this.props.renderContent ? (
              this.props.renderContent(this.props.item)`

is there a reason why it is limited to the keys title and content?

**Comment by SupriyaKalghatgi** [comment]
Added with [2.7.2](https://github.com/GeekyAnts/NativeBase/releases/tag/v2.7.2)

**Comment by fouratj** [comment]
This should ideally be reflected in the documentation for the custom header and content, as it shows the old behaviour of receiving simply the Title and Content variables.

**Comment by SupriyaKalghatgi** [comment]
Docs are on the way
