### ISSUE TITLE
Radio Button Customization

### ISSUE THREAD

**Issue by arthur-tse7** [GeekyAnts/NativeBase#212]
For some reason, when I try to change the radio button size or color, nothing changes. Do I have to pass in a theme instead ?

    <Radio selected={ this.state.selectedRadio === 'male' }
          radioColor='blue'
          radioBtnSize=10
          onPress={ this.updateButton.bind(this, 'male') }/>

**Comment by arthur-tse7** [comment]
Found the problem, was not creating theme js file.

**Comment by webdevsyd** [comment]
@arthur-tse7 how did you solve this?

**Comment by arthur-tse7** [comment]
@webdevsyd I believe I had to use themes instead of changing the radioColor and radioBtnSize directly. See here: https://docs.nativebase.io/Customize.html#Customize

**Comment by webdevsyd** [comment]
@arthur-tse7 did you eject your nativebase theme?
