### ISSUE TITLE
footertab with react-navigation and a key property to prevent multiple navigations on the same screen

### ISSUE THREAD

**Issue by jahnavi310** [GeekyAnts/NativeBase#2129]
I am using the footertab component of native-base library with the tab navigator of the react-navigation component.

I ran into the issue of when a user clicks on the same tab twice or thrice - it loads the corresponding views 3-4 times which is a terrible user experience.

    
    export default (tabNav = TabNavigator(
    {
    Home: { screen: Home },
    People: { screen: People },
    Links: { screen: Links },
     },
    {
    tabBarPosition: "bottom",
    swipeEnabled: false,
    tabBarComponent: props => {
      
      return (
        <StyleProvider style={getTheme(platform)}>
          <Footer>
            <FooterTab style={styles.color} >
              <Button 
                vertical
                active={props.navigationState.index === 0}
                onPress={() => props.navigation.navigate({routeName: 'Home', key: 'Home'})}
              >
                <Icon style={{color:'white'}} name="home" />
                <Text style={{color:'white', fontSize: 12}}>Home</Text>
              </Button>
              <Button 
                vertical
                active={props.navigationState.index === 1}
                onPress={() => props.navigation.navigate({routeName: 'People', key: 'People'})}
              >
                <Icon style={{color:'white'}} name="person" />
                <Text style={{color:'white', fontSize: 12}}>People</Text>
              </Button>
              <Button
                vertical
                active={props.navigationState.index === 2}
                onPress={() => props.navigation.navigate({routeName: 'Links', key: 'Links'})}
              >
                <Icon style={{color:'white'}} name="link" />
                <Text style={{color:'white', fontSize: 12}}>Links</Text>
              </Button>
            </FooterTab>
          </Footer>
        </StyleProvider>
      );
     }
    }

I was able to get the issue resolved by adding the key property in the  props.navigation.navigate as suggested here: [https://github.com/react-navigation/react-navigation/issues/271][1], but this slows down the navigation in the emulator. Any ideas why this might be happening? 

Essentially I changed `props.navigation.navigate('Home)` to `props.navigation.navigate({routeName: 'Home', key: 'Home'})` but the emulator started giving timeout errors.

  [1]: https://github.com/react-navigation/react-navigation/issues/271

**Comment by akhil-geekyants** [comment]
Closing this issue. Issue is not a NativeBase issue. Related to React Navigation library.
