### ISSUE TITLE
How to fix padding Button component in <Content> element ?

### ISSUE THREAD

**Issue by ar-nit** [GeekyAnts/NativeBase#213]
Hi! guy, How to fix padding between Home button and another ? (I try v0.5.8 and v0.5.9 latest).

![screenshot 66](https://cloud.githubusercontent.com/assets/11644819/19012267/a03e991a-87da-11e6-8882-e5010e24521e.png)

![screenshot 67](https://cloud.githubusercontent.com/assets/11644819/19012278/daab052a-87da-11e6-82fe-b5c94e84963f.png)

**Comment by ar-nit** [comment]
http://nativebase.io/docs/v0.5.7/components#button
![screenshot 68](https://cloud.githubusercontent.com/assets/11644819/19012308/7cc75afc-87db-11e6-9fb6-1a3c577b76f1.png)

**Comment by SupriyaKalghatgi** [comment]
@ar-nit For the purpose of demonstration, we have included extra padding between the components. This is not the case with all components. Also, this has been on our list.
NativeBase will be fixed with these issues in its upcoming sprint

**Comment by ar-nit** [comment]
Thank you for your answer @SupriyaKalghatgi. I try to add marginBottom: 10 in Button.js file and work for me.
![screenshot 72](https://cloud.githubusercontent.com/assets/11644819/19156018/a0f89796-8c0a-11e6-9e18-725a91c2cc87.png)
![screenshot 74](https://cloud.githubusercontent.com/assets/11644819/19156040/b48da60c-8c0a-11e6-8572-3474f8b9c2b4.png)

**Comment by mike-aungsan** [comment]
Just start using NativeBase. Choose this over the rest. 
Having the same issue in 2.3.1.
