### ISSUE TITLE
Ionicons font issue in 2.7.1 release

### ISSUE THREAD

**Issue by Dalamar** [GeekyAnts/NativeBase#2138]
## node, npm, react-native, react and native-base version
- node v8.11.1
- npm 5.6.0
- react 16.3.2
- react-native 0.53.0
- native-base 2.7.1
## Expected behavior
- Icons of type Ionicons renders as expected
## Actual behavior
- Questionmark renders instead of an expected icon
## Steps to reproduce should include code snippet and screenshot
- Upgrade/install NativeBase 2.7.1
- Use the following icon:
`<Icon name="ios-cart-outline"/>`
## Is the bug present in both iOS and Android or in any one of them?
- Checked only in iOS
## Any other additional info which would help us debug the issue quicker.
I blame recent fonts update because if you replace Ionicons.ttf with a font from 2.7.0 branch Ionicons icons renders OK. As only you revert font from 2.7.1 the problem shows up again.

**Comment by SupriyaKalghatgi** [comment]
yes the icon names with `*-outline` are not rendering with vector icons

**Comment by SupriyaKalghatgi** [comment]
Commits [951f154](https://github.com/GeekyAnts/NativeBase/commit/951f154d2a10d5459801ddce57addf3ee867e0ac), [f93b115](https://github.com/GeekyAnts/NativeBase/commit/f93b11530e572431ffd3148bcd65063609896e2f) fixed this

**Comment by Dalamar** [comment]
When will those commits be available in release branch?

**Comment by SupriyaKalghatgi** [comment]
Fixed with [2.7.2](https://github.com/GeekyAnts/NativeBase/releases/tag/v2.7.2)
