### ISSUE TITLE
State of support for iPhone X

### ISSUE THREAD

**Issue by neemah** [GeekyAnts/NativeBase#2139]
Hello guys, thanks for great UI lib!

Do you currently support iPhone X?

Do we need to use SafeAreaView alongside nativebase, or nativebase handle all styles itself?

Thanks in advance.

**Comment by SupriyaKalghatgi** [comment]
@neemah Please follow issue template guidelines
this doesn't report any kind of issue, hence closing

**Comment by SupriyaKalghatgi** [comment]
NativeBase supports iPhoneX

**Comment by neemah** [comment]
You are very kind, thank you!
