### ISSUE TITLE
What List is deprecated? Where is FlatList in you lib?

### ISSUE THREAD

**Issue by wzup** [GeekyAnts/NativeBase#2145]
> Note: List is deprecated. Use of List for dynamic list generation is discouraged. Use Flatlist instead.

![screen shot 2018-07-17 at 2 38 56 pm](https://user-images.githubusercontent.com/3880497/42815142-37e5c818-89cf-11e8-815a-deacd8fcdc44.png)

Is this for real? I could hardly notice that string of text.

You don't have FlatList in your lib. Bother explain what you by _Use Flatlist instead._

**Comment by SupriyaKalghatgi** [comment]
> Use FlatList instead

The string `FlatList` redirects you to https://facebook.github.io/react-native/docs/flatlist.html

**Comment by wzup** [comment]
@SupriyaKalghatgi 

`FlatList` doesn't work at ALL. It doesn't even render anything!

**Comment by SupriyaKalghatgi** [comment]
@wzup May be you are not writing it properly
Check NativeBase KitchenSink for examples https://github.com/GeekyAnts/NativeBase-KitchenSink/blob/master/src/screens/list/listitem-noIndent.js

**Comment by wzup** [comment]
> _May be you are not writing it properly_

Yep, you're right. This is the right way.

```javascript
return (
    <View style={{}}>
        <FlatList
            keyExtractor={ item => item.key }
            data={ data }
            renderItem={ this.renderItems }
        />                    
    </View>
);

renderItems( props ) {
    return (
        <ListItem key={item.key}
            button={true}
            first={props.index === 0}
            style={listItem}
            >
            <Left>
                <Text style={css.text}>{item.text}</Text>
            </Left>
            <Right style={css.right}>
                <Icon name="arrow-forward" style={css.chevron} />
            </Right>
        </ListItem>
    )
}
```

**Comment by alphashuro** [comment]
What about for non-dynamic lists? what are we supposed to use? this statement is very cryptic and barely noticeable. I think it's important to not only explain why its deprecated, but to give viable alternatives for both static and dynamic lists (although I do see that the dynamic list alternative works).

**Comment by kevin-coelho** [comment]
Bumping this - neither of the above examples work for me.

`<ListItem key={item.key} button></ListItem>` results in nothing rendering.
`<ListItem icon key={item.key}></ListItem>` works however.
