### ISSUE TITLE
First prop doesn't work for ListItem

### ISSUE THREAD

**Issue by wzup** [GeekyAnts/NativeBase#2147]
Top border is never rendered. But I set `first` prop

```javascript
        listItems = config.reduce( (all, item, idx) => {
            let li;
            all.push(
                <ListItem key={item.i18n} button={true} first={idx === 0}>  // <== first
                    <Text button>{item.i18n}</Text>
                </ListItem>
            )
            return all;
        }, []);
```

In your codebase `first` is boolean. So it is my code above. But it doesn't work. Why?
```
			note?: string;
			itemHeader?: boolean;
			first?: boolean;
			last?: boolean;
			selected?: boolean;
```

**Comment by akhil-geekyants** [comment]
@wzup this is as per design. You can refer [NativeBase Kitchen Sink](https://github.com/GeekyAnts/NativeBase-KitchenSink) examples. The screenshots in the docs are taken from NativeBase Kitchen Sink Example App.

**Comment by SupriyaKalghatgi** [comment]
About the usage of `first`, i will make it more clear in docs
https://github.com/GeekyAnts/native-base-docs/issues/118
