### ISSUE TITLE
In list of cards, the shadow grows ever longer

### ISSUE THREAD

**Issue by paour** [GeekyAnts/NativeBase#2150]
## node, npm, react-native, react and native-base version
```
    "native-base": "^2.7.1",
    "react": "16.4.1",
    "react-native": "0.56.0",
```
## Expected behaviour
In a list of cards, all cards have the same shadow thickness, unless otherwise specified
## Actual behaviour
The shadow grows for each subsequent card in a list.

![screenshot-2018-07-18_16_27_47_641](https://user-images.githubusercontent.com/90963/42928187-ebc8b4b8-8b36-11e8-8f39-b2fbb4523334.png)

## Steps to reproduce should include code snippet and screenshot

```
{_.map(props.content, c => (
  <NB.Card key={c.id} style={styles.menu}>
    <NB.CardItem cardBody button onPress={() => props.open(c)} style={styles.cardItem}>
      <NB.Text style={styles.menuText}>{c.title}</NB.Text>
    </NB.CardItem>
  </NB.Card>
  )}
```
## Is the bug present in both iOS and Android or in any one of them?

This happens in Android. I can't test on iOS on the latest version of NB because the RN 0.56 dependency causes issues with other libs (rn-firebase).

**Comment by SupriyaKalghatgi** [comment]
@paour 
> The shadow grows for each subsequent card in a list.

This can be more clear if you share GIF

**Comment by paour** [comment]
This effect does not happen only during scroll, all you need is a list of cards. I've annotated the screenshot to clarify.

**Comment by SupriyaKalghatgi** [comment]
@paour Can you check this on device?
Simulator / Emulator sometimes render these glitches

**Comment by paour** [comment]
Yes, it's the same on-device. Here, in another app on my phone.

![screenshot_20180719-155944](https://user-images.githubusercontent.com/90963/42947212-1deb0ba4-8b6d-11e8-8a7d-99d7afd264a1.png)

**Comment by SupriyaKalghatgi** [comment]
Checked this with React Native View, behaves same

```
          <View style={{elevation: 3, marginBottom: 15, borderWidth: 0.5, borderColor: '#ccc' }}><Text>Text</Text></View>
          <View style={{elevation: 3, marginBottom: 15, borderWidth: 0.5, borderColor: '#ccc' }}><Text>Text</Text></View>
          <View style={{elevation: 3, marginBottom: 15, borderWidth: 0.5, borderColor: '#ccc' }}><Text>Text</Text></View>
          <View style={{elevation: 3, marginBottom: 15, borderWidth: 0.5, borderColor: '#ccc' }}><Text>Text</Text></View>
          <View style={{elevation: 3, marginBottom: 15, borderWidth: 0.5, borderColor: '#ccc' }}><Text>Text</Text></View>
          <View style={{elevation: 3, marginBottom: 15, borderWidth: 0.5, borderColor: '#ccc' }}><Text>Text</Text></View>
          <View style={{elevation: 3, marginBottom: 15, borderWidth: 0.5, borderColor: '#ccc' }}><Text>Text</Text></View>
```

**Comment by paour** [comment]
So it's a RN bug? Sorry I didn't think to check that first!

**Comment by SupriyaKalghatgi** [comment]
yes, it is
I will link in the RN issue in a minute

**Comment by SupriyaKalghatgi** [comment]
https://github.com/facebook/react-native/issues/20501
