### ISSUE TITLE
Render wrong vector icon when type is Feather

### ISSUE THREAD

**Issue by Vergil0327** [GeekyAnts/NativeBase#2153]
Hi! Thanks for trying out NativeBase!

Take a look at these before heading towards creating an issue
-   Check latest documentation: https://docs.nativebase.io/
-   Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
-   Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
-   For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
-   For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

Also **DO** fill out the below form to give us a better idea about your environment and help us debug it quicker. Issues without the required details will mostly be closed.

## node, npm, react-native, react and native-base version
React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.4
      CPU: x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
      Memory: 29.41 MB / 8.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 9.11.1 - ~/.nvm/versions/node/v9.11.1/bin/node
      Yarn: 1.7.0 - /usr/local/bin/yarn
      npm: 5.6.0 - ~/.nvm/versions/node/v9.11.1/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
      Android SDK:
        Build Tools: 23.0.1, 26.0.1, 26.0.2, 27.0.3
        API Levels: 23, 26, 27
    IDEs:
      Android Studio: 3.0 AI-171.4443003
      Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.4.1 => 16.4.1
      react-native: 0.56.0 => 0.56.0
## Expected behaviour
```<Icon style={style} type="Feather" name="user" />``` => Supposed to render user icon
## Actual behaviour
Render another vector icon (see screenshot below)
even render the wrong icon when set name attribute to "user-plus", "user-check, or "users'
## Steps to reproduce should include code snippet and screenshot
```<Icon style={style} type="Feather" name="user-plus" />```
<img width="59" alt="2018-07-19 10 20 03" src="https://user-images.githubusercontent.com/23495551/42917836-da7de140-8b3d-11e8-9c02-83b713b8a7db.png">

## Is the bug present in both iOS and Android or in any one of them?
I only try iOS
## Any other additional info which would help us debug the issue quicker.
Before I upgrade react-natve & native-base to the latest version, it works fine.
But now, when Icon's type set to "Feather", always render the wrong vector icon

**Comment by SupriyaKalghatgi** [comment]
@Vergil0327 fixed this, rolling out today

**Comment by SupriyaKalghatgi** [comment]
Fixed with [2.7.2](https://github.com/GeekyAnts/NativeBase/releases/tag/v2.7.2)

**Comment by fabmont** [comment]
I fixed this problem by downgrading from 2.11.0 to 2.7.2 as @SupriyaKalghatgi mentioned.

**Comment by nakulgulati** [comment]
> I fixed this problem by downgrading from 2.11.0 to 2.7.2 as @SupriyaKalghatgi mentioned.

That solution indeed works but there has been quite a few releases after 2.7.2, will this also be fixed in the later releases?

**Comment by SupriyaKalghatgi** [comment]
2.7.2 you mean NativeBase?
Please check the release notes of NativeBase and check the upgrades done on react native vector icons

**Comment by nakulgulati** [comment]
@SupriyaKalghatgi I was using NativeBase 2.11.1 and the Feather icons when used with `<Icon>` component were not showing the correct icon.

**Comment by SupriyaKalghatgi** [comment]
https://github.com/GeekyAnts/NativeBase/issues/2453
