### ISSUE TITLE
Typing trigger switch tab in Tabs

### ISSUE THREAD

**Issue by XeCtvi** [GeekyAnts/NativeBase#2154]
Hi There,

Thanks for NativeBase, while I am using it an issue happened.

## Version
node -v v8.11.1
react-native ^0.51.0
react ^16.2.0
native-base ^2.5.1

## Expected behavior
While typing, type tool popup and type the texts normally

## Actual behavior
When I start to type in type tool just a word, tab1 switch to tab2 in tabs.

## Steps to reproduce should include code snippet and screenshot
![issue4](https://user-images.githubusercontent.com/10743176/42918582-fce9b148-8b40-11e8-90c2-bfc732e2f60f.gif)

## Is the bug present in both iOS and Android or in any one of them?
Andriod Genymotion Google Pixel C - 6.0.0 API 23 - 2560*1800

## Any other additional info which would help us debug the issue quicker.
- I have set `locked={true}` in tabs, so seems not triggering the swipe motion.
- Several inputs in a line as design.
- Wiring inputs with redux form.

**Comment by akhil-geekyants** [comment]
@XeCtvi See issue #550

**Comment by XeCtvi** [comment]
Hi @akhil-geekyants ,

Before I create this issue, I have alreadly noticed #550, but I still don't know how to solve this issue. Any suggestion?

Thanks.

**Comment by yowrosales** [comment]
I fixed it by using `stateAlwaysHidden|adjustPan` on AndroidManifest.xml windowSoftInputMode

**Comment by XeCtvi** [comment]
Hi @yowrosales,

It seems not work for me, am I do the thing right:
```
android:windowSoftInputMode="adjustResize"

changeTo 

android:windowSoftInputMode="stateAlwaysHidden|adjustPan"
```

Thanks.

**Comment by yowrosales** [comment]
@XeCtvi not sure if this is a fix but I have a KeyboardAvoidingView wrapping my tabs

e.g.

`<KeyboardAvoidingView behavior="padding" style={styles.tab_container}>
              <Tabs
                locked
                renderTabBar={() => <ScrollableTab style={styles.no_border} />}
                tabBarUnderlineStyle={styles.tab_underline}
              >
    ...`
