### ISSUE TITLE
2.7.2 has warnings / The warning doesn't accur 2.7.1

### ISSUE THREAD

**Issue by appaaaa** [GeekyAnts/NativeBase#2157]
I used nativebase 2.7.1 / but today I updated nativebase to 2.7.2 and It makes warnings like below..
3 warnings..

is it my fault? or just bugs in 2.7.2 version?

![screenshot_1532068912](https://user-images.githubusercontent.com/26356032/42987366-05832296-8c34-11e8-89ec-1672bc7d4aaf.png)
![screenshot_1532068934](https://user-images.githubusercontent.com/26356032/42987367-05a9ea8e-8c34-11e8-810f-953d43e48dca.png)
![screenshot_1532068941](https://user-images.githubusercontent.com/26356032/42987369-05d5337e-8c34-11e8-88ef-e0023911f7cd.png)

**Comment by EricWiener** [comment]
I'm getting these warnings as well and I'm on 2.3.5.

`Invalid props.style key `NativeBase` supplied to `View`.
Bad object: {
  "NativeBase": {
    "Label": {
      ".focused": {
        "width": 0
      },
      "fontSize": 17
    },
    "Icon": {
      "fontSize": 30,
      "color": "#000"
    },
    "IconNB": {
      "fontSize": 30,
      "color": "#000"
    },
    "Input": {
      ".multiline": {
        "height": null
      },
      "height": 50,
      "color": "#000",
      "paddingLeft": 5,
      "paddingRight": 5,
      "flex": 1,
      "fontSize": 17
    }
  },
  "borderLeftWidth": 0,
  "borderRightWidth": 0,
  "borderTopWidth": 0,
  "borderBottomWidth": 2,
  "borderColor": "#D9D5DC",
  "backgroundColor": "transparent",
  "flexDirection": "row",
  "alignItems": "center",
  "marginLeft": 2,
  "opacity": 1
}
Valid keys: [
  "display",
  "width",
  "height",
  "start",
  "end",
  "top",
  "left",
  "right",
  "bottom",
  "minWidth",
  "maxWidth",
  "minHeight",
  "maxHeight",
  "margin",
  "marginVertical",
  "marginHorizontal",
  "marginTop",
  "marginBottom",
  "marginLeft",
  "marginRight",
  "marginStart",
  "marginEnd",
  "padding",
  "paddingVertical",
  "paddingHorizontal",
  "paddingTop",
  "paddingBottom",
  "paddingLeft",
  "paddingRight",
  "paddingStart",
  "paddingEnd",
  "borderWidth",
  "borderTopWidth",
  "borderStartWidth",
  "borderEndWidth",
  "borderRightWidth",
  "borderBottomWidth",
  "borderLeftWidth",
  "position",
  "flexDirection",
  "flexWrap",
  "justifyContent",
  "alignItems",
  "alignSelf",
  "alignContent",
  "overflow",
  "flex",
  "flexGrow",
  "flexShrink",
  "flexBasis",
  "aspectRatio",
  "zIndex",
  "direction",
  "shadowColor",
  "shadowOffset",
  "shadowOpacity",
  "shadowRadius",
  "transform",
  "transformMatrix",
  "decomposedMatrix",
  "scaleX",
  "scaleY",
  "rotation",
  "translateX",
  "translateY",
  "backfaceVisibility",
  "backgroundColor",
  "borderColor",
  "borderTopColor",
  "borderRightColor",
  "borderBottomColor",
  "borderLeftColor",
  "borderStartColor",
  "borderEndColor",
  "borderRadius",
  "borderTopLeftRadius",
  "borderTopRightRadius",
  "borderTopStartRadius",
  "borderTopEndRadius",
  "borderBottomLeftRadius",
  "borderBottomRightRadius",
  "borderBottomStartRadius",
  "borderBottomEndRadius",
  "borderStyle",
  "opacity",
  "elevation"
]
    in View (at createAnimatedComponent.js:154)
    in AnimatedComponent (at TouchableOpacity.js:247)
    in TouchableOpacity (at Item.js:292)
    in Item (at connectStyle.js:384)
    in Styled(Item) (at Home.js:106)
    in RCTView (at View.js:60)
    in View (at Home.js:105)
    in RCTView (at View.js:60)
    in View (at Home.js:103)
    in Home (at SceneView.js:17)
    in SceneView (at CardStack.js:466)
    in RCTView (at View.js:60)
    in View (at createAnimatedComponent.js:154)
    in AnimatedComponent (at Card.js:12)
    in Card (at PointerEventsContainer.js:39)
    in Container (at CardStack.js:498)
    in RCTView (at View.js:60)
    in View (at CardStack.js:414)
    in RCTView (at View.js:60)
    in View (at CardStack.js:413)
    in CardStack (at CardStackTransitioner.js:67)
    in RCTView (at View.js:60)
    in View (at Transitioner.js:142)
    in Transitioner (at CardStackTransitioner.js:19)
    in CardStackTransitioner (at StackNavigator.js:41)
    in Unknown (at createNavigator.js:13)
    in Navigator (at createNavigationContainer.js:226)
    in NavigationContainer (at App.js:10)
    in RCTView (at View.js:60)
    in View (at Root.js:13)
    in Root (at connectStyle.js:384)
    in Styled(Root) (at App.js:9)
    in App (at renderApplication.js:33)
    in RCTView (at View.js:60)
    in View (at AppContainer.js:102)
    in RCTView (at View.js:60)
    in View (at AppContainer.js:122)
    in AppContainer (at renderApplication.js:32)
`

**Comment by pluschen** [comment]
Did you found any solution?
I'm getting these warnings on 2.6.1

**Comment by EricWiener** [comment]
I can't find anything yet

**Comment by k-neo** [comment]
+1 (Only 'supplied to ScrollView')

In my case I got a warning after putting the <Content> tag in component.
After re-creating the project in 2.7.1, warning disappeared.

**Comment by lorensr** [comment]
Same error.

```
    in View (at createAnimatedComponent.js:154)
    in AnimatedComponent (at TouchableOpacity.js:247)
    in TouchableOpacity (at Item.js:292)
    in Item (at connectStyle.js:384)
    in Styled(Item) (at HomeScreen.js:59)
```

My use of Item:

```
          <Form>
            <Item>
              <Input
                placeholder="Username"
                autoCapitalize="none"
                onChangeText={username => this.setState({ username })}
                value={this.state.username}
              />
            </Item>
```

**Comment by andraskende** [comment]
Somehow the "Invalid props.style key `NativeBase` supplied to `ScrollView`....  appeared today...

my project:

    react-native init app1 ; cd app1
    npm install --save redux react-redux redux-thunk moment react-navigation react-native-vector-icons native-base
    npm install
    react-native link
    react-native link react-native-vector-icons

Updated npm which fixed the issue for me..

    nvm install-latest-npm

**Comment by SupriyaKalghatgi** [comment]
```
  "dependencies": {
    "color": "1.0.3",
    "lodash": "4.13.1",
    "moment": "2.13.0",
    "native-base": "2.7.2",
    "react": "16.4.1",
    "react-native": "0.56.0",
    "react-navigation": "1.5.0"
  }
```
I tried NativeBase KitchenSink with these dependencies, no warnings

**Comment by SupriyaKalghatgi** [comment]
let me know how I can help here

**Comment by SupriyaKalghatgi** [comment]
Closing this due no response

**Comment by nixidee** [comment]
I've got the same problem. I tried to revert to 2.7.1 and got the same error. After a few tries, this is what worked on windows 10 for me:

- change version of native-base in package.json to 2.7.1
- delete node-modules folder & package-lock.json
- in windows power shell do npm install

I'm not sure what the problem was(Version, cmd or something else), i may test it later when my project is finished.

**Comment by SupriyaKalghatgi** [comment]
Its difficult to fix issue, unless its reproducible @k-neo @abonander @nixidee 
I have shared my response above
If this still happens, then try putting this on snack, and try to reproduce

**Comment by kozilla** [comment]
Have the same issue, it just popped out suddenly on one of my projects , I'm on "native-base": "^2.7.2",

**Comment by SupriyaKalghatgi** [comment]
I mentioned this in my previous comments that
> If this still happens, then try putting this on snack, and try to reproduce

**Comment by ChillkroeteTTS** [comment]
rm -r node_modules && yarn did the job for me. I was getting the "Invalid props.style key NativeBase supplied to ScrollView" warning.

**Comment by gtaylor44** [comment]
Like @SupriyaKalghatgi already mentioned, this is hard to reproduce. It's a very strange bug. 

I was getting this error on multiple components. The error is a little misleading because in one instance, the only way to clear warning was to remove button completely. 

Tried changing versions, clearing caches, node_modules and removing styles on affected components. 

Eventually fixed by deleting package-lock.json

**Comment by rianonehub** [comment]
i think this warning appears when using react-native version under 0.56.0
