### ISSUE TITLE
can not run-ios ENOENT: no such file or directory

### ISSUE THREAD

**Issue by yaakua** [GeekyAnts/NativeBase#216]
my step is under:
1. react-native init reactNativeBase
2. npm install native-base --save
3. react-native run-ios
   then got error:
   ENOENT: no such file or directory, stat '/Users/yangkui/rndemo/reactNativeBase/node_modules/react-native/packager/.1.0.1@clamp'

I can not found '.1.0.1@clamp' file or directory in '....node_modules/react-native/packager/ ' 

Node version: 6.7.0
npm list result (someone):
![image](https://cloud.githubusercontent.com/assets/1543846/19028608/9a3908ce-8970-11e6-9aa8-cf74190dd057.png)

TKS!

**Comment by SupriyaKalghatgi** [comment]
@yaakua Have you tried RN init before?
