### ISSUE TITLE
TypeScript error for 'expanded' property on renderHeader

### ISSUE THREAD

**Issue by PaulMEDITECH** [GeekyAnts/NativeBase#2160]
native-base version 6.1.0

Expected behavior
Can use 'expanded' property in renderHeader without TypeScript error.

Actual behavior
TypeScript error when using 'expanded' property in renderHeader

`
  renderHeader(item: any, expanded: boolean) {
    return (
    ...
`

`
  render() {
    let title = this.props.title;
    let content = this.props.content;
    return (
      <Accordion
        dataArray={[{title, content}]}
        renderHeader={this.renderHeader}
        ...
`
The 'renderHeader={this.renderHeader}' line produces the TypeScript error:

Types of property 'renderHeader' are incompatible.
  Type '(item: any, expanded: boolean) => Element' is not assignable to type '((item: any) => ReactElement<any>) | undefined'.
    Type '(item: any, expanded: boolean) => Element' is not assignable to type '(item: any) => ReactElement<any>'.
(JSX attribute) renderHeader: (item: any, expanded: boolean) => JSX.Element

I was able to fix it locally by making this change in index.d.ts:
Before
		interface Accordion {
			dataArray: Array<any>;
			headerStyle?: ReactNative.ViewStyle;
			contentStyle?: ReactNative.ViewStyle;
			renderHeader?: (item: any) => React.ReactElement<any>;
			renderContent?: (item: any) => React.ReactElement<any>;
                          
After
		interface Accordion {
			dataArray: Array<any>;
			headerStyle?: ReactNative.ViewStyle;
			contentStyle?: ReactNative.ViewStyle;
			**renderHeader?: (item: any, expanded: boolean) => React.ReactElement<any>;**
			renderContent?: (item: any) => React.ReactElement<any>;

**Comment by SupriyaKalghatgi** [comment]
Check commit https://github.com/GeekyAnts/NativeBase/commit/d7e69b48750a74ff8750d539f61129b12bd7b9fb
