### ISSUE TITLE
[Enhancement] Accordion Component

### ISSUE THREAD

**Issue by andresbuitront** [GeekyAnts/NativeBase#2163]
Hi! Thanks for trying out NativeBase!

Sorry by my English....
I have troubles with  Accordion Component because it only allowme put text inside them (inner of dataArray specificly )there is a way to put component inside of content part of this dataArray for example View Components or Objects 
const dataArray = [
  { title: 'title1',
    content: <View>Other Components Here!</View> },
  { title: 'Creditos', content: <View>Other Components Here!</View> },
  { title: 'Inversiones', content: <View>Other Components Here!</View> },
  { title: 'Enviar Dinero a...', content: <View>Other Components Here!</View> },
  { title: 'Pago de Servicios', content: <View>Other Components Here!</View> }
];
On this way, i can put an Accordion with elements, components, objects inside it
Thank you by the reply

**Comment by SupriyaKalghatgi** [comment]
This is not issue
its enhancement

**Comment by guiac** [comment]
Hello @andresbuitront . Were you able to do that? I need to do something like that. Could you tell me how you solved this problem? Thanks

**Comment by SupriyaKalghatgi** [comment]
#38
