### ISSUE TITLE
CheckBox Shape

### ISSUE THREAD

**Issue by josephkim583** [GeekyAnts/NativeBase#2164]
How can I make the shape of the CheckBox a Square instead of a circle. Also how do I add on styling to the checkbox? Example please?

**Comment by ZeroCool00** [comment]
@josephkim583  do you solve it?

**Comment by josephkim583** [comment]
Got it!

**Comment by arpitjain-in** [comment]
@josephkim583 How to solve this? Can you please provide me the solution on this?
