### ISSUE TITLE
Icons not working

### ISSUE THREAD

**Issue by lauffenp** [GeekyAnts/NativeBase#2165]
## node, npm, react-native, react and native-base version
node v9.5.0
npm v6.2.0
react 16.4.1
react-native 0.56.0
native-base: 2.7.2
## Expected behaviour
Icons appear:
```
export const MyIcon = () => <Icon name='home' />
export default MyIcon
```

## Actual behaviour
No icons appear:
<img width="109" alt="screen shot 2018-07-25 at 2 17 14 pm" src="https://user-images.githubusercontent.com/8912028/43200350-94fe6874-9015-11e8-8b44-ba12635b307d.png">

## Steps to reproduce should include code snippet and screenshot
```
export const MyIcon = () => <Icon name='home' />
export default MyIcon
```
## Is the bug present in both iOS and Android or in any one of them?
Android Emulator
## Any other additional info which would help us debug the issue quicker.
I'm using an Android Emulator Nexus 5X API 26 Android 8.0

**Comment by ZeroCool00** [comment]
have you done **react-native link**

**Comment by lauffenp** [comment]
thanks @ZeroCool00 ... that was it. :shame_faced:
