### ISSUE TITLE
Invariant Violation - Custom Accordion

### ISSUE THREAD

**Issue by the-transgineer** [GeekyAnts/NativeBase#2166]
I was working on my app when I noticed a page that I had used a custom accordion on would load. So I checked to see when it had changed and it hadn't. So I tried using the example custom Accordion that is shown on the docs and I am given the exact same error message

## node, npm, react-native, react and native-base version
Node: 10.4.0
NPM: 6.1.0
react-native: 0.55.4
react: 16.3.1
native-base: 2.7.2

## Expected behaviour
For the page to load

## Actual behaviour
Error involving "Objects are not valid react children"

## Steps to reproduce should include code snippet and screenshot
1. Set Up Kitchen Sink App
2. Navigate to Custom Accordion
3.
<img width="382" alt="screen shot 2018-07-25 at 10 57 37 am" src="https://user-images.githubusercontent.com/30739795/43212465-9f6d53cc-8ff9-11e8-9b1a-65699adf8cc4.png">

## Is the bug present in both iOS and Android or in any one of them?
Only Testing on iOS

**Comment by SupriyaKalghatgi** [comment]
Docs is on 2.6.0 version (updated till NativeBase 2.6.1)
and this change was made in [2.7.2](https://github.com/GeekyAnts/NativeBase/releases/tag/v2.7.2)

including use case
![image](https://user-images.githubusercontent.com/13464885/43381432-402370c0-93f2-11e8-98c9-159894dbc319.png)

**Comment by hai-ru** [comment]
I got this problem to, can you 
![screenshot from 2018-11-19 13-09-06](https://user-images.githubusercontent.com/24634668/48689294-5e3ad500-ebfc-11e8-9f93-47ab58d30cf0.png)
![screenshot from 2018-11-19 13-08-55](https://user-images.githubusercontent.com/24634668/48689295-5e3ad500-ebfc-11e8-85f6-c7f2dc10f674.png)

**Comment by hai-ru** [comment]
![image](https://user-images.githubusercontent.com/24634668/48689325-93472780-ebfc-11e8-9c68-bbd0efccc8b9.png)
i already installed latest version native base and got something error same like you 
![image](https://user-images.githubusercontent.com/24634668/48689347-b07bf600-ebfc-11e8-9938-dc7030241772.png)

**Comment by solominh** [comment]
Summary: use dataArray and expanded as parameters:
![image](https://user-images.githubusercontent.com/13938331/48824999-9aa33800-ed98-11e8-87af-276f562d8e8e.png)
![image](https://user-images.githubusercontent.com/13938331/48825008-a3940980-ed98-11e8-9840-7623557faf2a.png)
