### ISSUE TITLE
Prevent List from scrollling

### ISSUE THREAD

**Issue by the-transgineer** [GeekyAnts/NativeBase#2167]
Is there a way to prevent list from scrolling?

## node, npm, react-native, react and native-base version
Node: 10.4.0
NPM: 6.1.0
react-native: 0.55.4
react: 16.3.1
native-base: most recent

## Expected behaviour
List does not scroll
## Actual behaviour
List view is scrolling
## Steps to reproduce should include code snippet and screenshot
<img width="286" alt="screen shot 2018-07-25 at 1 01 57 pm" src="https://user-images.githubusercontent.com/30739795/43218874-5658faee-900b-11e8-9694-0f9cac986d61.png">

<img width="288" alt="screen shot 2018-07-25 at 1 03 20 pm" src="https://user-images.githubusercontent.com/30739795/43218960-9b1b2d64-900b-11e8-8b75-9b04a5d4b8ca.png">

## Is the bug present in both iOS and Android or in any one of them?
I assume both but only testing on iOS

**Comment by SupriyaKalghatgi** [comment]
Please follow the issue template guidelines
