### ISSUE TITLE
Class Drawer not found node_modules/native_base

### ISSUE THREAD

**Issue by raulcrash** [GeekyAnts/NativeBase#2168]
node v6.11.2,   npm 6.2.0,  react-native 0.55.4, react 16.4.0, native-base 2.7.2

## Expected behaviour
* import Drawer component successfully

## Actual behaviour
* Component not found ..\node_modules\native-base\src\basic\Drawer and \node_modules\native-base\index.d.ts

## Steps to reproduce should include code snippet and screenshot

On Windows running npm install and checking for \ node_modules \ native-base the Drawer component exists.

In MacOS running npm install and checking for \ node_modules \ native-base the Drawer component does not exist causing an error in the project.

I tried npm cache clean, delete temporary, npm install. Unsuccessfully

import { Drawer } from 'native-base';

**Comment by raulcrash** [comment]
Sorry, 

I saw that it was removed in this request.

https://github.com/GeekyAnts/NativeBase/pull/2100/files

**Comment by flyandi** [comment]
`native-base-legacy`
