### ISSUE TITLE
paddingbottom taking input from paddingtop in Footer for iPhone X only

### ISSUE THREAD

**Issue by hansen94** [GeekyAnts/NativeBase#2169]
Hi, I found a bug on Footer component in iPhone X where the paddingBottom is set by taking paddingTop from style. I think it should be from paddingBottom in style. You should see the bug on /src/basic/Footer.js in calculatePadder function. 

Is this an actual bug or something intended? I hope this help.

Node: v10.6.0
npm: 6.1.0
react-native: "0.56.0"
react: "16.4.1"
native-base: "^2.7.1"

**Comment by SupriyaKalghatgi** [comment]
thats intended, and works fine on iPhoneX
