### ISSUE TITLE
type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports. 

### ISSUE THREAD

**Issue by danielland85** [GeekyAnts/NativeBase#2170]
i have this error when use native-base component Drawer.
Error message:
React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

ender() {

return (

<Drawer
ref={(ref) => { this.drawer = ref; }}
content={<SideBar {...this.props}/>}
>
    <View style={styles.container}>
         <Header left='menu' openDrawer={()=>{this.drawer._root.open();}} title={'abc'}/>
         <Content>
              <View style={{flex: 3, backgroundColor:'blue'}} >
               </View>         
          </Content>
    </View>
</Drawer>
);
}

"react-native": "0.56.0",
"native-base": "^2.7.1"

**Comment by danielland85** [comment]
i found the solution by downgrade native-base@2.7.0

**Comment by SupriyaKalghatgi** [comment]
https://github.com/GeekyAnts/NativeBase/issues/2140

**Comment by SupriyaKalghatgi** [comment]
Added Drawer back with [2.8.0](https://github.com/GeekyAnts/NativeBase/releases/tag/v2.8.0)
