### ISSUE TITLE
ypeError: undefined is not an object (evaluating 'this.toastInstance._root')]

### ISSUE THREAD

**Issue by xellDart** [GeekyAnts/NativeBase#2173]
Hi, i get ypeError: undefined is not an object (evaluating 'this.toastInstance._root')]
on any toast show:

my method:
_show_toast(type) {
        Toast.show({
            text: 'Wrong password!',
            buttonText: 'Okay',
            type: type
        })
    }

**Comment by SupriyaKalghatgi** [comment]
I checked this in NativeBase KitchenSink with latest NativeBase, Toast types worked fine

Share more details, and please follow the issue template guidelines

**Comment by StevenT1** [comment]
> 你的主应用程序组件是否包含在内`<Root>`？前几天我遇到了这个问题，并为我解决了这个问题。请参阅文档：[https](https://docs.nativebase.io/Components.html#Toast)：[//docs.nativebase.io/Components.html#Toast](https://docs.nativebase.io/Components.html#Toast)

you can reference this

**Comment by forgic** [comment]
thank you very much @StevenT1

**Comment by saran-shabd** [comment]
Wrapping the component in <Root></Root> will do the trick. <Root> from 'native-base'

**Comment by saran-shabd** [comment]
Wrapping the component in `<Root>` will do the trick. `<Root>` is imported from `native-base`

**Comment by mepritam** [comment]
NativeBase Toast can be used to display quick warning or error messages. For Toast to work, you need to wrap your topmost component inside <Root> from native-base.

[Read](https://docs.nativebase.io/Components.html#toast-def-headref)

**Comment by chris-divvito** [comment]
Hi, for the record I am seeing this error with latest NativeBase with `<Root>` as my topmost element. It seems to only occur for android after users have changed to a different Activity from the main app and back (in our case, when we have done an `await PermissionsAndroid.request()`);

**Comment by askaaqib** [comment]
> Wrapping the component in `<Root>` will do the trick. `<Root>` is imported from `native-base`

It Does. Thanks @saran-shabd

**Comment by umairkhan1997** [comment]
Wrapping the component in <Root> will solve this issue. <Root> is imported from native-base

**Comment by samipshah100** [comment]
@jenni-divvito exact same case here. Did you find a work around?

**Comment by peterchijioke** [comment]
I'm having same issue here. somebody help!

**Comment by HectorRizzo** [comment]
I find this solution in Stackoverflow:
import Root from "native-base";
import Root from native base and wrap the whole container/view inside render's return function

render() {
    return (<Root>your app-return function code</Root>);}
