### ISSUE TITLE
Allow us to import a variable.js file into the Theme Customizer?

### ISSUE THREAD

**Issue by andersonaddo** [GeekyAnts/NativeBase#2174]
Hello NativeBase!
I'm wondering if you guys would please allow us to import previously made `variable.js` files into the [NativeBase Customizer](https://nativebase.io/customizer/) to edit it. At the moment, is you ever wanted to change you custom theme, you'd have to redo the whole thing in the web editor, which is quite inconvenient.

It would be much better if you allowed us to import a previous file and improve upon it.
Thanks!

**Comment by SupriyaKalghatgi** [comment]
https://github.com/GeekyAnts/NativeBase-Customizer/issues/6
