### ISSUE TITLE
Pull to refresh is not working with Tab layout

### ISSUE THREAD

**Issue by ranavc32** [GeekyAnts/NativeBase#2178]
Hi, 

I am using refreshControl from `react-native` with `native-base` Tab layout, refreshControl often hangs while pulling to refresh, Please Suggest me some fix for this, Here is the code snippet,
Here is my Tab code where I am applying the pull to refresh functionality

` <Tabs tabBarUnderlineStyle={{borderBottomWidth:1}} >
          <Tab heading={ <TabHeading >
            <Icon style={styles.TabIcon} name="random" type="FontAwesome" />
            <Text style={styles.TabText}>Random</Text>
            </TabHeading>}>
<Content
        refreshControl={
          <RefreshControl
            refreshing={this.state.refreshing}
            onRefresh={this._onRefresh}
            title="Loading..."
          />
        }
        onScroll={({ nativeEvent }) => {
          if (isCloseToBottom(nativeEvent)) {
            this.appendQuotes();
          }
        }}
        scrollEventThrottle={400}
      >
        {quoteList}
        {spinner}
      </Content>
 </Tab>
`

**Comment by SupriyaKalghatgi** [comment]
Cant find Tab code

**Comment by SupriyaKalghatgi** [comment]
I made a little change in your provided code, to demonstrate basic example of Tabs with pull to refresh. worked fine
![tabs](https://user-images.githubusercontent.com/13464885/43393220-ed89795a-9413-11e8-9c28-e401323e6176.gif)

**Comment by ranavc32** [comment]
That looks fine and same as what I am working with. But When I am placing tab having refresh Control as the first tab then I encountered this problem. So using your code will changing the Tab position will work?

**Comment by SupriyaKalghatgi** [comment]
![tabs](https://user-images.githubusercontent.com/13464885/43394205-7a641012-9417-11e8-89b6-11b21797f632.gif)
