### ISSUE TITLE
Add Tab heading Text prop allowFontScaling

### ISSUE THREAD

**Issue by jamesholcomb** [GeekyAnts/NativeBase#2179]
I would like to disable font scaling in the Tab heading text without resorting to custom tabs.

## node, npm, react-native, react and native-base version
10.6, 6.1, 2.7.2

## Expected behaviour
Tab heading text font scaling can be disabled

## Actual behaviour
Unavailable

**Comment by SupriyaKalghatgi** [comment]
You can achieve this with `<TabHeading>`

```
. . .
<Tab
  heading={
    <TabHeading>
      <Icon name="camera" />
      <Text allowFontScaling={false}>Camera</Text>
    </TabHeading>
  }
>
. . . 
```
