### ISSUE TITLE
TextArea cannot be disabled

### ISSUE THREAD

**Issue by XeCtvi** [GeekyAnts/NativeBase#2180]
Hi there, 

It seems we cannot disable the textArea for now, how do we achieve that?

Now I am using Input instead and add a property "multiline" and manually set height to it.

But I thought textArea should align to Input field right?

Thanks.

**Comment by SupriyaKalghatgi** [comment]
Added here, https://github.com/GeekyAnts/NativeBase/commit/c3d9d72318f14181a1ecab68c7cd9cd13d14529c

**Comment by XeCtvi** [comment]
Thanks for the quick response 👍

**Comment by bitlab-code** [comment]
> Added here, [c3d9d72](https://github.com/GeekyAnts/NativeBase/commit/c3d9d72318f14181a1ecab68c7cd9cd13d14529c)

this doesn't work.
```
RN 0.59.10
NativeBase 2.12.1
```
`editable` prop doesn't work.
Textarea can be disabled by `disabled={true}` (default Input prop)
```javascript
editable={this.props.disabled ? false : true}
```
@SupriyaKalghatgi what is the advantage of having two properties that do the same thing?
