### ISSUE TITLE
Cannot read property style of undefined

### ISSUE THREAD

**Issue by uppercase-army** [GeekyAnts/NativeBase#2181]
## node, npm, react-native, react and native-base version
"native-base": "2.7.2",
"react": "^16.4.1",
"react-native": "^0.56.0",

## Expected behaviour
App to load without RSOD

## Actual behaviour
RSOD:
![screenshot-2018-08-01_13 28 32 541](https://user-images.githubusercontent.com/32265535/43519228-d4cb1ca8-958e-11e8-8b6c-0ef7e56440fc.png)

## Steps to reproduce should include code snippet and screenshot
I upgraded my app to the latest version of RN as well as latest packages.
I used react-native link to link packages
I ejected the theme using the node command, so that i can use my custom theme colours.
Everything else stayed the same, code snippet:

`
  render() {
    return (
      <Root>
        <StyleProvider style={getTheme(variables)}>
          <Provider store={this.state.store}>
              <App />
          </Provider>
        </StyleProvider>
      </Root>
    );
  }`

## Is the bug present in both iOS and Android or in any one of them?
Android
## Any other additional info which would help us debug the issue quicker.
N/A

**Comment by SupriyaKalghatgi** [comment]
@uppercase-army I am unable to reproduce this
Please put this on snack and share URL here

**Comment by SupriyaKalghatgi** [comment]
@uppercase-army Any updates?
Closing this tomorrow in case of response, since this is not reproducible at out end

**Comment by uppercase-army** [comment]
@SupriyaKalghatgi I will close it for now. It's hard to reproduce since I don't know where the error is coming from. I am cloned the KitchenSink app and it's running fine. So I am going to merge my app with it.

If I experience any problem, I will reopen thanks.

**Comment by SupriyaKalghatgi** [comment]
sure
