### ISSUE TITLE
Use custom font for textStyle in Tab component

### ISSUE THREAD

**Issue by felixis-1** [GeekyAnts/NativeBase#2183]
## node, npm, react-native, react and native-base version
node: v10.5.0
react-native-cli: 2.0.1
react-native: 0.56.0
native-base: 2.7.0
## Expected behaviour
Using fontFamily: 'font' should work on tabStyle because it works elsewhere in the application as well.
## Actual behaviour
It does not work.
## Is the bug present in both iOS and Android or in any one of them?
It is a bug on both iOS and Android

**Comment by SupriyaKalghatgi** [comment]
you can achieve this with `<TabHeading>`

```
. . .
<Tab heading={
  <TabHeading>
    <Text style={{ fontFamily: 'Menlo-Italic'}}>Tab1</Text>
  </TabHeading>
}>
. . .
```

**Comment by felixis-1** [comment]
@SupriyaKalghatgi We tried this. All styles continue to take effect this way apart from fontFamily which is the problem.

**Comment by SupriyaKalghatgi** [comment]
@felixis-1 I have shared the above snippet, after trying it out

**Comment by SupriyaKalghatgi** [comment]
@felixis-1 @terreb did you go through the list of font families supported for iOS and Android?
They are not same
https://github.com/react-native-training/react-native-fonts

**Comment by SupriyaKalghatgi** [comment]
```
. . . 
<Tab heading={
  <TabHeading>
    <Text style={{ fontFamily: Platform.OS === 'ios' ? 'Menlo-Italic' : 'sans-serif-condensed' }}>Tab1</Text>
  </TabHeading>
}>
. . .
```

**Comment by terreb** [comment]
@SupriyaKalghatgi the font works perfectly with the other components and if you read my first message more attentively you will notice that it even works for unselected tabs but not for selected.

**Comment by felixis-1** [comment]
@SupriyaKalghatgi I am not using an out-of-the-box font but a custom one. And it works elsewhere. So the font installation is correct.

**Comment by SupriyaKalghatgi** [comment]
share the code along with output

**Comment by terreb** [comment]
```xml
                <Tabs initialPage={0} locked={true} onChangeTab={( { i, ref, from } ) => this._onTabChange( i )}>
                    <Tab heading={<TabHeading><Text style={{ fontSize: 12, fontFamily: platform === 'ios' ? 'Moon-Bold' : 'MoonBold' }}>Current</Text></TabHeading>}>
                        <CurrentTab />
                    </Tab>
                    <Tab heading={<TabHeading><Text style={{ fontSize: 12, fontFamily: platform === 'ios' ? 'Moon-Bold' : 'MoonBold' }}>My plans</Text></TabHeading>}>
                        <MyPlansTab/>
                    </Tab>
                    <Tab heading={<TabHeading><Text style={{ fontSize: 12, fontFamily: platform === 'ios' ? 'Moon-Bold' : 'MoonBold' }}>Marketplace</Text></TabHeading>}>
                        <MarketplaceTab/>
                    </Tab>
                </Tabs>
`

**Comment by terreb** [comment]
@SupriyaKalghatgi output? logs? what exactly, be precise?

**Comment by SupriyaKalghatgi** [comment]
screenshot of simulator or emulator

**Comment by SupriyaKalghatgi** [comment]
GIF would be better, switching between tabs

**Comment by SupriyaKalghatgi** [comment]
I get this `Unrecognized font family 'MoonBold'`

**Comment by terreb** [comment]
Here is the gif:

![ezgif-4-518e15a289](https://user-images.githubusercontent.com/6477282/43764444-c0b2071a-9a2d-11e8-9ebb-1a88a736998b.gif)

And here is the tutorial on how to add a custom font to React Native:

https://medium.com/react-native-training/react-native-custom-fonts-ccc9aacf9e5e

**Comment by SupriyaKalghatgi** [comment]
@terreb Check this on snack https://snack.expo.io/HJEuPyDHQ

**Comment by terreb** [comment]
@SupriyaKalghatgi I don't see you are using a custom font there.

**Comment by terreb** [comment]
I moved all custom styles from my real project to that test one, still cannot reproduce the issue. I assume the issue might not be directly related to native base, but other modules. Could be react native navigation for example.  

@felixis-1 don't you also use RNN in your project by any chance? 

This is the whole list of modules I'm using:

  "dependencies": {
    "color": "^3.0.0",
    "native-base": "^2.7.2",
    "react": "16.4.1",
    "react-native": "0.56.0",
    "react-native-bottomsheet": "^1.8.1",
    "react-native-code-push": "^5.4.1",
    "react-native-device-info": "^0.21.5",
    "react-native-expandable-section-list": "^1.0.7",
    "react-native-navigation": "^1.1.462",
    "react-native-progress": "^3.5.0",
    "react-native-prompt-android": "^0.3.3",
    "react-native-vector-icons": "4.5.0",
    "react-redux": "5.0.7",
    "redux": "4.0.0",
    "redux-logger": "3.0.6",
    "redux-persist": "^5.9.1",
    "redux-persist-filesystem-storage": "^1.2.0",
    "redux-thunk": "2.2.0",
    "reselect": "^3.0.1"
  },
