### ISSUE TITLE
Picker warning issue on iOS

### ISSUE THREAD

**Issue by wendycsy** [GeekyAnts/NativeBase#2185]
Hi, there is warning whenever we using picker element. 
Native Base version: "^2.7.2"

![screenshot at aug 02 10-51-44](https://user-images.githubusercontent.com/42018019/43559782-103bded6-9642-11e8-85d6-741c1fc7d034.png)

Kindly advice. Thank you.

**Comment by SupriyaKalghatgi** [comment]
Checked this on NativeBase KitchenSink with latest NativeBase, i couldn't find these waring with any type of Picker on iOS

**Comment by SupriyaKalghatgi** [comment]
Closing this tomorrow in case of no response
