### ISSUE TITLE
Left Is not working in Header for Android

### ISSUE THREAD

**Issue by grhashminxb** [GeekyAnts/NativeBase#2186]
Hello,

This is my code for displaying menu button for navigation drawer.
```
const MenuButton = props =>{
    return (
        <View>
          <Header>
            <Left>
                <Button transparent >
                    <Icon name='menu' onPress = {props.onPress}/>
                </Button>
              
            </Left>
          </Header>
        </View>
      );
}

```

On ios, its working fine but on Android, button is moved near to mid as in the screenshot. I have attached screenshot as well. Please help me.

![screenshot_1533204328](https://user-images.githubusercontent.com/29857326/43578062-1d07a58a-9667-11e8-91f3-584cc10d27b3.png)

**Comment by SupriyaKalghatgi** [comment]
@grhashminxb Closing this issue since it does not follow issue template guidelines

**Comment by SupriyaKalghatgi** [comment]
also that, if you include `<Left>` component, then you should include the other counterparts to place the Left component appropriately

```
<Header>
  <Left>
    <Button transparent >
      <Icon name='menu'/>
    </Button>
  </Left>
  <Body />
  <Right />
</Header>
```

**Comment by grhashminxb** [comment]
@SupriyaKalghatgi  I am sorry I didn't know about template but your suggestion has resolved this issue.
Thanks
