### ISSUE TITLE
Improve theme eject to support flow

### ISSUE THREAD

**Issue by jpolo** [GeekyAnts/NativeBase#2188]
When using flow, many errors are reported because of "missing annotation" in the native-base-theme-components/. 
```
export default (variables = variable) => {
                                       ^^^^Missing annotation for variable
```

A good fix would be to change the generated code to 
```
export default (variables /*: * */ = variable) => {
```
This annotation uses the flotate comment syntax and won't require a babel source processor if developers does not use flow.

Do not forget to add the `// @flow` at the beginning of the file also...

**Comment by SupriyaKalghatgi** [comment]
I tried checking flow error with [NativeBase KitchenSink](https://github.com/GeekyAnts/NativeBase-KitchenSink)
Didn't find any

![image](https://user-images.githubusercontent.com/13464885/43763592-c2faad90-9a48-11e8-8d52-24653e19891c.png)

**Comment by jpolo** [comment]
You have to add the  // @flow at the beginning of the files to enable support. Maybe my formulation was misleading : this is clearly not a bug. I am just suggesting to add support for flow types. The only error that is required to fix for that is the the "missing annotation".

**Comment by SupriyaKalghatgi** [comment]
Pushed on `master`
