### ISSUE TITLE
Disabled prop should take a boolean value

### ISSUE THREAD

**Issue by KeegsMcGeegs** [GeekyAnts/NativeBase#2189]
When using Inputs in React Native, the 'disabled' prop doesn't take boolean values. Allowing the 'disabled' prop to take boolean values will allow the 'disabled' prop to work conditionally with other Inputs. Is there a way to allow the 'disabled' feature to work conditionally (for example, if a user has the choice to select from a picker: 'single', 'living with family', or 'living with roommates'; the household size should automatically be set to 1 and the household size input should get disabled if the user selects 'single') or can the 'disabled' prop be updated to allow for boolean inputs?

**Comment by SupriyaKalghatgi** [comment]
`disabled` with Input works exactly the same

![disabled](https://user-images.githubusercontent.com/13464885/43756884-60045b6e-9a34-11e8-8c97-2e79dc5dd614.gif)
