### ISSUE TITLE
Picker selectedValue on Android not updating after redux dispatch

### ISSUE THREAD

**Issue by hoekma** [GeekyAnts/NativeBase#2190]
Using the Picker, the selectedValue of the picker does not seem to respect new values that are dispatched from redux when running on Android.   I have to navigate away from the screen and navigate back to the screen for the correct value to be shown.  

## node, npm, react-native, react and native-base version
Node --version
v8.11.3

npm version
{ npm: '5.6.0',
  ares: '1.10.1-DEV',
  cldr: '32.0',
  http_parser: '2.8.0',
  icu: '60.1',
  modules: '57',
  napi: '3',
  nghttp2: '1.32.0',
  node: '8.11.3',
  openssl: '1.0.2o',
  tz: '2017c',
  unicode: '10.0',
  uv: '1.19.1',
  v8: '6.2.414.54',
  zlib: '1.2.11' }

package.json:
  "dependencies": {
    "@expo/vector-icons": "^6.3.1",
    "expo": "^27.0.0",
    "lodash": "^4.17.10",
    "moment": "^2.22.2",
    "moment-timezone": "^0.5.17",
    "native-base": "^2.6.1",
    "react": "16.3.1",
    "react-moment": "^0.6.5",
    "react-native": "https://github.com/expo/react-native/archive/sdk-27.0.0.tar.gz",
    "react-native-easy-grid": "^0.1.15",
    "react-native-htmlview": "^0.12.0",
    "react-native-slider": "^0.11.0",
    "react-native-vector-icons": "^4.6.0",
    "react-navigation": "^2.0.0",
    "react-redux": "^5.0.7",
    "react-timer-mixin": "^0.13.3",
    "redux": "^4.0.0",
    "redux-logger": "^3.0.6",
    "redux-thunk": "^2.3.0",
    "validator": "^10.4.0",
    "xhr": "^2.5.0"
  }

## Expected behaviour
Displayed value in Picker should match the value of this.props.activeSensor.mode after redux dispatch.  

## Actual behaviour
Value does not change while still on the screen.  I have to navigate away from the screen and back to see the Picker.Item.label value that corresponds to this.props.activeSensor.mode

## Steps to reproduce should include code snippet and screenshot
                  <Content style={Styles.content}>
                        <Form style={styles.formStyle}>
                            <Item>
                                <Label>Name</Label>
                                <Input onChangeText={(text) => this.onNameChanged({ text })}    >
                                    {this.props.activeSensor.name}
                                </Input>
                            </Item>
                            <Item >
                                <Label picker style={styles.pickerCol}>Mode</Label>
                                {console.log(this.props.activeSensor.mode)}
                                <Picker
                                    iosHeader="Select one"
                                    mode="dropdown"
                                    selectedValue={this.props.activeSensor.mode}
                                    onValueChange={(picker) => this.onModeChanged(picker)}
                                    itemStyle={styles.pickerItem}
                                >
                                    <Picker.Item label="Active" value="active" />
                                    <Picker.Item label="Calibrating" value="calibrate" />
                                    <Picker.Item label="Ignore" value="ignore" />
                                </Picker>
                            </Item>
                        </Form>
                    </Content>

## Is the bug present in both iOS and Android or in any one of them?
It works as expected on iPhone.  Android is not refreshing properly

## Any other additional info which would help us debug the issue quicker.
I also tried setting a variable in refresh() such as 

`const currentMode = this.props.activeSensor.mode`

and using the variable instead of this.props.activeSensor.mode directly in the picker's selectedValue prop and that also did not work.  It seems like the displayed value is not updating until the screen loses and re-gains focus.  

The logging of this.props.activeSensor.mode immediately prior to the <Picker> logs the expected value.

**Comment by SupriyaKalghatgi** [comment]
please put this on snack, along with redux part

**Comment by hoekma** [comment]
Well, I just spent about 2 hours slicing my app down to the essentials to upload to snack. I could not duplicate the problem with the application slice.  Then tried again on my android phone with the full app and it is now working as expected.  I don't know why it was showing the above behavior before and is working properly now.  Confirmed iOS device works properly too.  If I see this again, I'll dig in again but for now it is working as expected.

**Comment by SupriyaKalghatgi** [comment]
sure

**Comment by shlokamin** [comment]
This is happening to me too, and it only started happening after switching our redux middleware from redux-promise to redux-thunk.

**Comment by suresh-jarvis** [comment]
Not working for me also

**Comment by shehzadbilal1981** [comment]
on your picker function "onValueChange" check if your list is loaded, if not loaded then don't allow to update the value.

**Comment by syedirfan33** [comment]
Same here, not working

**Comment by RamyaVaradharajan** [comment]
Same here..Any solution??

**Comment by mertlena** [comment]
Note: this is a temporary solution.

As you see, state update operation is successful. So if you create a `<Text>` component with updated state value and give it a position for overlay original `<Picker>`component, it can be work:

```jsx
           <View style={{backgroundColor:"white"}}>
              <Text>Title for Picker</Text>
              <Text style={{
                bottom: -35,
                left: 10,
                zIndex: 1
              }}>{state.selectedItemString}</Text>
              <Picker
                style={[!state.selectedItemString ? {color:"black"} : {color:"white"}]}
                mode="dropdown"
                selectedValue={state.selectedItemString}
                prompt="Prompt text for picker"
                onValueChange={(itemValue, itemIndex) => {
                    console.log(itemValue);
                }}>
                    <Picker.Item key={-1} label="Placeholder for picker" value="" />
                    {state.items.length > 0 && state.items.map((item, index) => (
                        <Picker.Item key={index} label={item.name} value={item.id} />
                    ))}
              </Picker>
        </View>
```
