### ISSUE TITLE
npm install fail

### ISSUE THREAD

**Issue by lowzhengrong** [GeekyAnts/NativeBase#2191]
![nativebase](https://user-images.githubusercontent.com/19724956/43710122-4e9a81b6-99a1-11e8-98cc-d4a64b75eeb0.png)

**Comment by SupriyaKalghatgi** [comment]
delete node_modules and try again

**Comment by lowzhengrong** [comment]
@SupriyaKalghatgi  after i delete node_modules and npm install .Then i get this error.
![screenshot_20180806-181022_testreactnative](https://user-images.githubusercontent.com/19724956/43711106-4107351e-99a4-11e8-831e-5a308a8dad80.jpg)

**Comment by SupriyaKalghatgi** [comment]
share package.json

**Comment by lowzhengrong** [comment]
@SupriyaKalghatgi 
{
  "name": "TestReactNative",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "native-base": "^2.7.2",
    "react": "16.3.1",
    "react-native": "0.55.4",
    "react-native-android-back-button": "^0.3.0",
    "react-native-scalable-image": "^0.4.0",
    "react-navigation": "^1.5.12"
  },
  "devDependencies": {
    "babel-jest": "23.0.1",
    "babel-preset-react-native": "4.0.0",
    "jest": "23.1.0",
    "react-test-renderer": "16.3.1"
  },
  "jest": {
    "preset": "react-native"
  },
  "rnpm": {
    "assets": [
      "./assets/fonts/"
    ]
  }
}

**Comment by SupriyaKalghatgi** [comment]
I have never tried react-native on windows, but try installing `prop-types`

**Comment by SupriyaKalghatgi** [comment]
Any updates?

**Comment by SupriyaKalghatgi** [comment]
Closing this today in case of no response, we have thousands of users using NativeBase with no issue. If you still face this issue, let me know
