### ISSUE TITLE
Icon crashing release build, RN 0.56, native-base 2.7.2

### ISSUE THREAD

**Issue by chrismatchett** [GeekyAnts/NativeBase#2193]
Hi,

After upgrading to RN 0.56 and nativebase 2.7.2 the release build of my app crashes with "TypeError: undefined is not an object (evaluating 'e.default').

I have pinned the error down to using Icon from nativebase. When I remove any reference to Icon all is good.

Anyone any thoughts on a fix?

Here are my package.json and .babelrc;

 "dependencies": {
    "create-react-class": "^15.6.3",
    "crypto-js": "^3.1.8",
    "install": "^0.12.1",
    "lodash": "^4.17.5",
    "mobx": "^3.4.1",
    "mobx-react": "^4.3.5",
    "moment": "^2.20.1",
    "native-base": "^2.7.2",
    "npm": "^6.2.0",
    "prop-types": "^15.6.0",
    "react": "^16.4.1",
    "react-moment": "^0.7.0",
    "react-native": "^0.56.0",
    "react-native-easy-grid": "^0.2.0"
  },
  "devDependencies": {
    "@babel/core": "7.0.0-beta.47",
    "@babel/plugin-proposal-decorators": "7.0.0-beta.47",
    "@babel/plugin-transform-runtime": "7.0.0-beta.47",
    "@babel/runtime": "7.0.0-beta.47",
    "babel-jest": "23.2.0",
    "babel-preset-react-native": "5.0.2",
    "jest": "23.3.0",
    "react-test-renderer": "16.4.1",
    "reactotron-react-native": "^2.0.0"
  },
  "jest": {
    "preset": "react-native"
  }
}

{
  "presets": ["react-native"],
  "plugins": [
    ["@babel/plugin-proposal-decorators", { "legacy": true }],
        "@babel/plugin-proposal-object-rest-spread",
        [
          "@babel/plugin-transform-runtime",
          {
            "helpers": true,
            "polyfill": false,
            "regenerator": false
          }
        ]
  ]
}

Thanks,

Chris

**Comment by shakedlokits** [comment]
+1

**Comment by SupriyaKalghatgi** [comment]
`android/settings.gradle` should have these lines

```
include ':react-native-vector-icons'
project(':react-native-vector-icons').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-vector-icons/android')
```

If not, then run `react-native link react-native-vector-icons` and try again

**Comment by SupriyaKalghatgi** [comment]
The same applies for iOS too

**Comment by chrismatchett** [comment]
I am using mobx and legacy decorators. What got react-native-vector icons working again was removing @babel/plugin-transform-runtime.

Thanks,

Chris

**Comment by karkb** [comment]
I am still getting this issue.

package.json
```
{
  "name": "DTESProject",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "mobx": "3.6.2",
    "mobx-react": "4.4.3",
    "native-base": "^2.7.2",
    "react": "^16.4.1",
    "react-native": "0.56.0",
    "react-navigation": "^2.9.3"
  },
  "devDependencies": {
    "@babel/core": "7.0.0-beta.47",
    "@babel/plugin-proposal-decorators": "7.0.0-beta.47",
    "@babel/plugin-transform-runtime": "7.0.0-beta.47",
    "@babel/runtime": "7.0.0-beta.47",
    "babel-jest": "23.4.2",
    "babel-plugin-transform-decorators-legacy": "^1.3.5",
    "babel-preset-react-native": "^5",
    "jest": "23.4.2",
    "react-test-renderer": "16.4.1"
  },
  "jest": {
    "preset": "react-native"
  }
}
```



.babelrc 

```
{
  "presets": ["react-native"],
  "plugins": ["transform-decorators-legacy"]
}
```

**Comment by SupriyaKalghatgi** [comment]
@karkb https://github.com/GeekyAnts/NativeBase/issues/2193#issuecomment-412483424
