### ISSUE TITLE
Adding Custom Element To Toast Message

### ISSUE THREAD

**Issue by Quadriphobs1** [GeekyAnts/NativeBase#2194]

**Comment by SupriyaKalghatgi** [comment]
@Quadriphobs1 I recommend you to go through this
https://material.io/design/components/snackbars.html#anatomy

![image](https://user-images.githubusercontent.com/13464885/43835489-c4f6d136-9b2f-11e8-8f56-d707deb4d88d.png)

hence we are not adding this to NativeBase

**Comment by Quadriphobs1** [comment]
I believe there should be an alert component then

**Comment by SupriyaKalghatgi** [comment]
https://facebook.github.io/react-native/docs/alert.html
