### ISSUE TITLE
Floating Label reset position when input is cleared

### ISSUE THREAD

**Issue by JonathanRufino** [GeekyAnts/NativeBase#2195]
Floating label is not behaving as expected

## Versions
node: 8.9.1
npm: 5.6.0
react-native: 0.55.4
react: 16.3.1
native-base: 2.5.1

## Expected behaviour

Floating Label should not reset position when input is cleared but is in focus

![captura de tela 2018-08-08 as 13 26 00](https://user-images.githubusercontent.com/5273493/43850553-a4f679a2-9b0e-11e8-98cc-7b20a90f1c6b.png)

## Actual behaviour

When i type and erase all content the label resets to its original position

Android
![android](https://user-images.githubusercontent.com/5273493/43851615-890e56b2-9b11-11e8-80d8-7f34ec7b3cea.gif)

iOS
![ios](https://user-images.githubusercontent.com/5273493/43851621-8b374a3e-9b11-11e8-84db-0ca70ee433fd.gif)

## Code sample

````js
import React from 'react'
import { View } from 'react-native'
import { Form, Item, Input, Label } from 'native-base'

class Example extends React.Component {
    state = {
        email: '',
    }

    render() {
        return (
            <View style={styles.container}>
                <Form style={styles.form}>
                    <Item floatingLabel last style={styles.input}>
                        <Label style={styles.label}>
                            E-MAIL
                        </Label>
                        <Input
                            value={this.state.email}
                            autoCapitalize='none'
                            keyboardType='email-address'
                            onChangeText={text => this.setState({ email: text })}
                        />
                    </Item>
                </Form>
            </View>
        )
    }
}

const styles = StyleSheet.create({
    container: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
    },
    form: {
        width: '100%',
        marginBottom: 40,
    },
    input: {
        borderColor: '#FF8000',
        marginBottom: '80rem',
    },
    label: {
        color: '#3ACFD5',
    },
})
````

## Is the bug present in both iOS and Android or in any one of them?
Both

**Comment by shiftrtech** [comment]
Hi, i am facing the same issue with;

//package.js
"native-base": "2.8.1"

I try to getRef of my inputs and later call blur() on them, no works.
