### ISSUE TITLE
LitsView bottom border doesn't appear on some items

### ISSUE THREAD

**Issue by Cassendra4** [GeekyAnts/NativeBase#2198]
Hi!

- Versions
react:16.2.0
react-native:0.55.1
native-base:2.7.2

- OS

Android (I'm not using expo)

- Expected Behavior

All items in the ListView should display the bottom border

- Actual Behavior

There are items which does not show the bottom border randomly

![screenshot_1533882230](https://user-images.githubusercontent.com/8186992/43942646-7b0b43dc-9c96-11e8-9633-51e002c508dd.png)

I need to make the UI look consistent. Hope someone could help me with this.

**Comment by SupriyaKalghatgi** [comment]
Is this screenshot from emulator?

**Comment by Cassendra4** [comment]
yes. It is

**Comment by SupriyaKalghatgi** [comment]
Check this over device, it works as expected

**Comment by Cassendra4** [comment]
I checked this on an actual device and this is how it looks,

![alcatel](https://user-images.githubusercontent.com/8186992/43943385-072d48f4-9c99-11e8-955e-204775f7b7c6.png)

**Comment by SupriyaKalghatgi** [comment]
I have put up this example on snack https://snack.expo.io/ryJW335rQ
Works fine
