### ISSUE TITLE
Footer supports no more than three items

### ISSUE THREAD

**Issue by carlosgarbiatti** [GeekyAnts/NativeBase#220]
Hi,

I'm trying to use four items in the footer and the last one gets ignored (because the children indexes are hard coded). 

```
Footer.js : 50
{ Array.isArray(this.props.children) &&
    <View style={{flex: 1,alignItems: 'center', justifyContent: 'flex-start', flexDirection: 'row'}}>
         {this.props.children[0]}
    </View>}

   { Array.isArray(this.props.children) &&
      <View style={{flex: 3, alignSelf: 'center'}}>
        {this.props.children[1]}
      </View>}

    { Array.isArray(this.props.children) &&
        <View style={{flex:1,alignItems: 'center', justifyContent: 'flex-end', flexDirection: 'row'}}>
              {this.props.children[2]}
     </View>}
```

I was wondering if this was intentional for some reason or just an edge case. 

I tried to use my own footer as well and realized that Container will only render footer if the children   match exactly the native base Footer type:

```
Container.js : 50
if(Array.isArray(this.props.children)) {
    return _.find(this.props.children, function(item) {
        if(item && item.type == Footer) {
             return true;
        }
   });
}
```

I reckon we could either allow a custom Header and Footer objects or make the footer items dynamic according to the children array. What do you guys think?

Thanks!

Carlos

**Comment by SupriyaKalghatgi** [comment]
@carlosgarbiatti Please checkout the [FooterTab](https://github.com/GeekyAnts/NativeBase-KitchenSink/blob/master/js/components/anatomy/index.js) of NativeBase in [NativeBase-KitchenSink](https://github.com/GeekyAnts/NativeBase-KitchenSink)

**Comment by pkassonss** [comment]
Sorry, I don't see it ... having same issue with just 3 tabs showing when coded for 4.
