### ISSUE TITLE
Make Item Component Agnostic of Input Component Type

### ISSUE THREAD

**Issue by joeywatts** [GeekyAnts/NativeBase#2201]
The `Item` Component doesn't support custom Input components. For example, if you make a simple wrapper around the `Input` component and try to use it in an `Item` with the `floatingLabel` prop, it won't detect your wrapped Input component and will silently create and render its own. The child that you specify is filtered out of the Item. The React team heavily encourages the composition pattern as a way of "extending" existing components.

> [React has a powerful composition model, and we recommend using composition instead of inheritance to reuse code between components.](https://reactjs.org/docs/composition-vs-inheritance.html)

I think, for this reason, NativeBase should strive to implement components that don't rely on details like specific component types. One way to implement this might [pass that Input component in as a prop](https://twitter.com/dan_abramov/status/958728081287589889).

`<Item floatingLabel input={<MyInput {...inputProps} />}></Item>`

**Comment by SupriyaKalghatgi** [comment]
Share use case that you are trying

**Comment by SupriyaKalghatgi** [comment]
@joeywatts Sorry for delayed reply, I will keep this issue open for today

**Comment by joeywatts** [comment]
One specific use case is if you want to create a "tabbable" input (i.e., one that switches focus to the next input when submitting). A generic way to implement this is to wrap the `Input` component in another component which provides this functionality, but, as-is, NativeBase will silently not render this component and just discard it. BTW, I suspect this issue is related to #2256.

**Comment by yosmanyga** [comment]
In my case I'm wrapping all components to keep my own compatibility in future. But then I'm getting troubles with Button, which relies on Text type to do some work inside.
It would be nice to have something similar like https://material-ui.com/guides/composition/
