### ISSUE TITLE
[Question] - Having Header and sharing the same background image ?

### ISSUE THREAD

**Issue by ngouass** [GeekyAnts/NativeBase#2203]
Hey guys, first thanks the package which is really helpful.
I'm trying to create this header: 
<img width="374" alt="capture d ecran 2018-08-13 a 08 30 53" src="https://user-images.githubusercontent.com/17073855/44015971-51877848-9ed3-11e8-8423-c682ddf066ef.png">
I succeed to create the header using Segment component:
<img width="298" alt="capture d ecran 2018-08-13 a 08 33 21" src="https://user-images.githubusercontent.com/17073855/44016049-af14f418-9ed3-11e8-8cbc-311f31b94620.png">

But I was expecting to get my result after encapsulating the header in a linear gradient component.
<img width="299" alt="capture d ecran 2018-08-13 a 08 38 25" src="https://user-images.githubusercontent.com/17073855/44016207-707bc6cc-9ed4-11e8-88b9-5c219d8f8c3d.png">

How should I proceed from there?
```
export default class SelectCityList extends Component {
  render() {
    return (
      <StyleProvider style={theme}>
        <Container>
          <LinearGradient colors={["#020A15", "#032655"]}>
            <Header
              hasSegment
              style={{
                height: 60,
                paddingBottom: 10,
                backgroundColor: "transparent"
              }}
            >
              <Left style={{ flex: 1 }}>
                <Button transparent>
                  <Icon name="arrow-back" />
                </Button>
              </Left>
              <Body style={{ flex: 0 }}>
                <Title style={{ fontSize: 20 }}>Select a city</Title>
              </Body>
              <Right style={{ flex: 1 }} />
            </Header>
          </LinearGradient>
          <Segment style={{ height: 60 }}>
            <Item style={searchBoxStyle}>
              <Icon name="search" style={{ color: "white" }} />
              <Input placeholder="Rechercher" />
            </Item>
          </Segment>
        </Container>
      </StyleProvider>
    );
  }
}
```

**Comment by ngouass** [comment]
I closed this issue because the problem has nothing to do with the package, it's related to how I organize my components.

**Comment by SupriyaKalghatgi** [comment]
Ok. Thank you for putting in effort knowing which package is causing you this issue
