### ISSUE TITLE
Button text color not changing

### ISSUE THREAD

**Issue by colloquet** [GeekyAnts/NativeBase#2204]
## node, npm, react-native, react and native-base version
node: 9.11.2
yarn: 1.9.2
react: 16.4.1
react-native: 0.56
native-base: 2.7.2

## Expected behaviour
Each button text has their own color

## Actual behaviour
They share the same color

## Steps to reproduce should include code snippet and screenshot
```jsx
<View>
  <Button transparent>
    <Text>Primary</Text>
  </Button>
  <Button transparent danger>
    <Text>Danger</Text>
  </Button>
</View>
```
<img width="545" alt="screen shot 2018-08-13 at 3 15 22 pm" src="https://user-images.githubusercontent.com/6201495/44017666-b7f67e7a-9f0b-11e8-8d60-f861cf7295f8.png">

## Is the bug present in both iOS and Android or in any one of them?
I have only tried it on iOS simulator

**Comment by colloquet** [comment]
Hi @SupriyaKalghatgi ,

Thanks for the prompt reply, that's weird because I have just created a new project from scratch following [this page](https://facebook.github.io/react-native/docs/getting-started) and it's still not working for me.

Can you clone [my repo](https://github.com/colloquet/native-base-test) and see if it's working for you?

**Comment by SupriyaKalghatgi** [comment]
I checked the same code across iPhone X

![image](https://user-images.githubusercontent.com/13464885/44019724-43b84d30-9efd-11e8-9c29-abb8f99efd7f.png)

**Comment by SupriyaKalghatgi** [comment]
I looked into your project. If you want to wrap these Button in `View`, then make sure it is imported from `native-base`
This gave me expected results

**Comment by colloquet** [comment]
Ah right ok so I have to use Button inside Container / Content.

Thanks for the help.
