### ISSUE TITLE
Invalid props.style key `NativeBase`

### ISSUE THREAD

**Issue by dakiesse** [GeekyAnts/NativeBase#2208]
## node, npm, react-native, react and native-base version
"native-base": "^2.7.2",
"react": "16.4.2",
"react-native": "0.56.0",

## Actual behaviour
When I am trying to use "Content" component I'm getting a error:
![image](https://user-images.githubusercontent.com/5033716/44080635-ef2f0cee-9fac-11e8-8a42-f42bc2feb784.png)
![image](https://user-images.githubusercontent.com/5033716/44080653-fb9762a6-9fac-11e8-9379-e6858aa621dd.png)

## Code
```
  render () {
    return (
      <Content/>
    )
  }
```

## Info
![f46075899d](https://user-images.githubusercontent.com/5033716/44080821-7c904184-9fad-11e8-92e8-4e01de191a35.png)

## Is the bug present in both iOS and Android or in any one of them?
I've checked only on Android.

**Comment by dakiesse** [comment]
I couldn't reproduce it via initialed project too. But, my project has the problem after updating RN and others packages. I'll try to move my project in new initialed project. If I found out something I'll let you know.

**Comment by mpcarr** [comment]
I'm also getting this error in iOS and Android. Not had chance to investigate it yet.

**Comment by akhil-geekyants** [comment]
@mpcarr can you try ChillkroeteTTS's comment https://github.com/GeekyAnts/NativeBase/issues/2157#issuecomment-413144027

**Comment by SupriyaKalghatgi** [comment]
Closing this tomorrow in case of no response

**Comment by stepri** [comment]
Didn't work for me

**Comment by mpcarr** [comment]
I removed node modules, changed to v2.7.1 in package.json, installed and warnings went away. Then upgraded back to 2.7.2. Currently no invalid prop warnings.

**Comment by nahidmbstu** [comment]
no solution worked for me ....

**Comment by DrEhsan** [comment]
same issue here, changed to v2.7.1 and still have this issue!

**Comment by rianonehub** [comment]
this issue also happened to me on v2.7.0 when using react-navigation

**Comment by joakimwennergren** [comment]
I'm having the same issue, tried to downgrade to v2.7.1 but warning won't go away.

**Comment by cmcaboy** [comment]
I am also receiving this error. On version 2.7.2

**Comment by SupriyaKalghatgi** [comment]
I cannot reproduce this issue. So whoever facing this issue, could put it on snack or github, I can then look into this

Also try try installing node_modules again by clearing lock files, cache etc

**Comment by wwarodom** [comment]
I also got this error on v2.7.2 and v2.7.1 even I tried to remove node_modules and did npm install again on v.2.7.1 already.

**Comment by DrEhsan** [comment]
this error appears on win cli thanks to react-native 0.56 :|

**Comment by dpwilhelmsen** [comment]
@SupriyaKalghatgi  - I was playing with an example react-native app and saw this warning. Here's a link to my fork where I see the issue: https://github.com/dpwilhelmsen/react-native-shop-ui. I haven't had the opportunity to narrow it down yet but hopefully it'll let you reproduce the issue.

**Comment by mognia** [comment]
still having this issue

**Comment by Aryk** [comment]
Not sure if I'm getting the same issue, but basically I have

```ts
      <Text style={editMode && {opacity: 1}}>dfdfd</Text>
```

This gives me that same error I think it's due to the "opacity" on the Text.

However, if I switch to react native Text, no error....
