### ISSUE TITLE
Swipe List Error when changing data source 

### ISSUE THREAD

**Issue by cdcordobaa** [GeekyAnts/NativeBase#2213]
Hi!, i having a problem with swipeable List i couldn't figure out how to resolve
Im using a code like this

`
list = () => {
		return (
			<List
				bounces={false}
				dataSource={this.ds.cloneWithRows(
					this.props.trackerData[this.state.category]
				)}
				renderRow={this.renderRow}
				disableRightSwipe
				renderRightHiddenRow={(data, secId, rowId, rowMap) => {...}}
				rightOpenValue={-130}
			/>
		)
	}
`

Here is an image of my View
Im using list view to render elements from an array of data, an lets say, i render 2 elements in this list, AND swipe LAST element an let it open.

![whatsapp image 2018-08-16 at 4 03 59 pm](https://user-images.githubusercontent.com/26011541/44235809-694f1680-a170-11e8-8ff9-aab52658879e.jpeg)

then if i change category in my state, it means it change the data source of the list, and the new list has fewer elements than the previous one, AND SWIPE an element lets say the FIRST ONE, im getting this error.

![whatsapp image 2018-08-16 at 4 03 59 pm 1](https://user-images.githubusercontent.com/26011541/44235815-70762480-a170-11e8-9635-23f0bc6da658.jpeg)

it happens when the index of the previous opened element, is higher than the length of the actual datalist. 
 im getting
`null is not an object (evaluating 'this._rows[this.openCellld]._root')`

i have already tried lot of things like closing the row with rowMap or obtaining reference to inner elements like openCellId, but cant find solution to this.

it does not happen when i delete an element from the list and close it with 		`rowMap[`${secId}${rowId}`].props.closeRow()`

**Comment by cdcordobaa** [comment]
an additional validation in safeCloseOpenRow in your List component should do the trick.

```
safeCloseOpenRow() {
		// if the openCellId is stale due to deleting a row this could be undefined
		if (this._rows[this.openCellId] && this._rows[this.openCellId]._root) {
			this._rows[this.openCellId]._root.closeRow()
		}
	}
```

**Comment by SupriyaKalghatgi** [comment]
Any updates on this?

**Comment by cdcordobaa** [comment]
Here is the snack recreating the bug, https://snack.expo.io/SJqclwuI7
the error is in the following image
![whatsapp image 2018-08-16 at 4 03 59 pm 2](https://user-images.githubusercontent.com/26011541/44350925-2dfd6200-a466-11e8-9881-a586125a37b5.jpeg)
however as i said, the the solution is just adding that validation, i already did. Since the method try to access to an index larger than the length of the current dataSource.

**Comment by SupriyaKalghatgi** [comment]
yes the validation fixes the issue
Any help needed here?

**Comment by sdacunha** [comment]
Hi @SupriyaKalghatgi!

I have the same issue, and forking, adding the fix above and recompiling seemed to have resolved it for me. Any chance we can get it into master and eventually an npm release?

For me, it happens on a swipe list when I delete an element.

Thanks!

**Comment by SupriyaKalghatgi** [comment]
@sdacunha Well Thanks for trying the fix and reverting
I will give it a try

**Comment by suvenduchhatoi** [comment]
@cdcordobaa  Please check with latest NB(2.11.0). It seems to be working fine without any error
![screen shot 1440-06-08 at 12 27 59 pm](https://user-images.githubusercontent.com/44160581/52692807-f4c42b80-2f8a-11e9-8532-4d370fc1f3ec.png)
![screen shot 1440-06-08 at 12 28 42 pm](https://user-images.githubusercontent.com/44160581/52692808-f4c42b80-2f8a-11e9-93b9-c984251171c6.png)
