### ISSUE TITLE
Icon doesn't appear with full size

### ISSUE THREAD

**Issue by skokon** [GeekyAnts/NativeBase#2214]
Hello, i'm trying to display icon 

`                    <Icon style = {{textAlign: 'center', fontSize: 40}} name = 'ios-contacts-outline'/>`

the problem is the icon doesn't appear with full size like this

![image](https://user-images.githubusercontent.com/35232306/44249910-bbd51500-a1fa-11e8-9a11-b4349b11bde8.png)

Any ideas?

**Comment by akhil-geekyants** [comment]
@skokon try setting the `width` to `null` for `Icon`.

Like
```
<Icon style = {{width:null, textAlign: 'center', fontSize: 40}} name = 'ios-contacts-outline'/>
```

**Comment by skokon** [comment]
thanks a lot, how i can set your answer as the correct answer?

**Comment by serdarde** [comment]
Thank you @akhil-ga ! It didn't solve my problem completely. I had to give those styles:
```
paddingTop: 4,
height: 21,
width: null,
```
This is the right solution for me, it can vary on different stacks

**Comment by serdarde** [comment]
Do not use the fontSize style for the Icon, instead use the size and boxSize props of the Icon component.
