### ISSUE TITLE
Actionsheet causes App to crash

### ISSUE THREAD

**Issue by isaaclem** [GeekyAnts/NativeBase#2215]
Following the example code from [docs](http://docs.nativebase.io/Components.html#actionsheet-def-headref), the ActionSheet will cause the App to crash. I've also created a snack to demo the problem, this happened to both iOS and Android:

https://snack.expo.io/BJJlKy4LX

**Comment by akhil-geekyants** [comment]
For ActionSheet to work, you need to wrap your topmost component inside `<Root>` from native-base. See docs [here](http://docs.nativebase.io/Components.html#actionsheet-def-headref)

Add this to your code and change the default export  
```
export default () =>
  <Root>
    <App />
  </Root>;
```

**Comment by isaaclem** [comment]
Ahh miss out the Root part, sorry about it. Thank you very much for this awesome library!
