### ISSUE TITLE
Bottom tab bar on iPhoneX

### ISSUE THREAD

**Issue by gmochid** [GeekyAnts/NativeBase#2217]
## node, npm, react-native, react and native-base version
- node: v8.6.0
- npm: 6.2.0
- native-base: "^2.7.2"
- react: "16.3.1"
- react-native: "~0.55.2"

## Expected behaviour
The tab bar on the bottom should respect the safe area on iPhoneX.

```
<Tabs
  tabBarPosition="bottom"
  tabBarUnderlineStyle={{ backgroundColor: 'white' }}>
  <Tab heading={ <TabHeading><Icon name="apps" /></TabHeading>}>
  </Tab>
  <Tab heading={ <TabHeading><Icon name="apps" /></TabHeading>}>
  </Tab>
  <Tab heading={ <TabHeading><Icon name="camera" /></TabHeading>}>
  </Tab>
</Tabs>
```

## Actual behaviour
It doesn't respect the safe area constraint on iPhoneX.

## Screenshot
![image](https://user-images.githubusercontent.com/1681647/44281326-a22ae080-a281-11e8-88ac-633b6a789b31.png)

**Comment by SupriyaKalghatgi** [comment]
You are working with the wrong Tabs for Footer
Check here in docs https://docs.nativebase.io/Components.html#footer-tabs-icon-headref

**Comment by KenrickV-Hexaware** [comment]
I am having the same issue with footer tabs. The safe area covers the footer tab text.
