### ISSUE TITLE
trasparent button did not show text when i put it in Left side of header 

### ISSUE THREAD

**Issue by Ali-CFD-Alex** [GeekyAnts/NativeBase#2218]
when i try this : 
```
<Header>
     <Left>
         <Button>
             <Text>Back</Text>
         </Button>
     </Left>
 </Header>

```
it works correctly, but when i try transparent button its not work!
```
<Header>
    <Left>
        <Button transparent>
            <Text>Back</Text>
        </Button>
    </Left>
</Header>
```

It show nothing (i can find my button when random tap but cannot see Text).
I try to set color and position or width style to text but it doesn't work.
But if use `<Right></Right>` instead of `<Left></Left>` it works correctly

**Comment by Ali-CFD-Alex** [comment]
Ops !
its work when i changed `<Text>` fontSize

**Comment by Ali-CFD-Alex** [comment]
I was watching your docs , In your docs it doesn't work too add fontSize to your `Text` 😉🤣
![image](https://user-images.githubusercontent.com/10908319/44290124-7cef9f80-a28c-11e8-9c8f-8ed8ee1e4ec8.png)

Thanks...

**Comment by SupriyaKalghatgi** [comment]
Check release notes https://github.com/GeekyAnts/NativeBase/releases/tag/v2.4.5

`Header's Left component will not render Text button for Android`
