### ISSUE TITLE
ScrollableTab have line buttom help me

### ISSUE THREAD

**Issue by AlohaIndy** [GeekyAnts/NativeBase#2221]
this code if use <ScrollableTab/> is have line buttom tabs please help. i dont want line buttom tabs
              <Tabs
                    tabBarUnderlineStyle={{
                    backgroundColor: 'white'
                }}
                    renderTabBar={() => <ScrollableTab/>}>
                    <Tab heading="All">
                        <Content
                            style={{
                            backgroundColor: "white"
                        }}>
                            <View
                                style={{
                                height: 1000,
                                backgroundColor: 'white'
                            }}></View>
                        </Content>
                    </Tab>
                    <Tab heading="Math">
                        <Content
                            style={{
                            backgroundColor: "white"
                        }}>
                            <View
                                style={{
                                height: 1000,
                                backgroundColor: 'white'
                            }}></View>
                        </Content>
                    </Tab>
                    <Tab heading="ICT"></Tab>
                    <Tab heading="Chemistry"></Tab>
                    <Tab heading="Accounting"></Tab>
                </Tabs>

**Comment by AlohaIndy** [comment]
![image](https://user-images.githubusercontent.com/32694764/44328398-a3c7f480-a48b-11e8-80ed-beec4a31b34b.png)

**Comment by SupriyaKalghatgi** [comment]
Please follow issue template guidelines
Failing which this issue will be closed
