### ISSUE TITLE
Possible to handle multiline for button with Icon and Text?

### ISSUE THREAD

**Issue by isaaclem** [GeekyAnts/NativeBase#2222]
I have a button as below

```
<Button
   iconLeft
   warning
   block
   large
   onPress={this.someFunc}
>
  <Icon name='ios-browsers' />
  <Text>{flexiTextWidth}</Text>
</Button>
```

I have the above button which working fine with fixed text, but if the content `flexiTextWidth` is very long then it will be cutted off. I'm wondering if there is any way where the button can support multi-line? I've tried to set multiline attribute at `<Text>` but doesnt seems to do anything. Wondering how we can handle the height depending on the text length?

**Comment by SupriyaKalghatgi** [comment]
Can you give me an example for where this case is used?

**Comment by SupriyaKalghatgi** [comment]
I asked you example where a button with long text (text length exceeding screen width) is used

**Comment by isaaclem** [comment]
![screen shot 2018-08-20 at 8 52 36 pm](https://user-images.githubusercontent.com/32945572/44341626-04baf100-a4bb-11e8-8bb2-fd5efce65b75.png)

```
render() {
  return(
    <Container>
      <Content padder>
        <Button
            iconLeft
            warning
            block
            large
            style={{
                marginTop: 10,
                marginBottom: 5,
                paddingRight: 10,
                justifyContent: 'space-evenly'
              }}
            onPress={this.someFunc}
          >
            <Icon style={mainButtonIconStyle} name='ios-browsers' />
            <Text style={[mainButtonTextStyle, { marginHorizontal: 20 }]}>This is a super long translated text that wished to be rendered into multiline with flexi height</Text>
          </Button>
      </Content>
    </Container>
  );
}
```

**Comment by SupriyaKalghatgi** [comment]
As per design guidelines, text in button should be precise and definitely not multiline
![image](https://user-images.githubusercontent.com/13464885/44381262-1d63ef00-a52d-11e8-914d-1af8bd1ecf17.png)

![image](https://user-images.githubusercontent.com/13464885/44381277-2bb20b00-a52d-11e8-979f-2ec9a3023394.png)

**Comment by isaaclem** [comment]
Any suggestion on how to handle the translated text with unknown text length? For now I'm manipulating the button height using manual calculation based on number of chars

**Comment by SupriyaKalghatgi** [comment]
![image](https://user-images.githubusercontent.com/13464885/44385306-a171a300-a53c-11e8-8f41-dfa1296041ae.png)
