### ISSUE TITLE
Add numberOfLines prop to Scrollable tab heading

### ISSUE THREAD

**Issue by dmitryermichev** [GeekyAnts/NativeBase#2225]
Scrollable tab heading devided into 2 lines. Is it possible to prevent this behavior? I didn't find the way to add numberOfLines prop to Text in heading.

`"native-base": "^2.7.2",`

![screenshot_2018-08-20-16-49-25-691_com clientapp](https://user-images.githubusercontent.com/14346528/44344700-fad4c600-a499-11e8-94e4-33358435fba7.png)

**Comment by SupriyaKalghatgi** [comment]
If it is Scrollable Tab, then the Text appears in single line

**Comment by SupriyaKalghatgi** [comment]
If you want Tab heading Text in single line, then use Scrollable Tab
If you want Tab heading in two lines, then use default Tab

**Comment by NguyenPhatBG** [comment]
@SupriyaKalghatgi 
How can I use numberOfLines for Tabs (4 tab for 2 lines) ?
Can you support to me ! I had try to numberOfLines FlatList but status textStyle and tabStyle is not right,
it's active when i settup them difference.

**Comment by brkrtp** [comment]
> Scrollable

They are also  Scrollable Tab and shows two line on android but ios shows one line..
<img width="275" alt="Screen Shot 2019-07-07 at 18 53 51" src="https://user-images.githubusercontent.com/18514716/60770871-94c05400-a0e8-11e9-81ee-2516f1e2f2a2.png">
