### ISSUE TITLE
style issue of <Left/> in <ListItem/>

### ISSUE THREAD

**Issue by kenphil** [GeekyAnts/NativeBase#2226]
how can i change the style of the <Left/> in <ListItem/>? 
for example: alignItems: "flex-start"....in React Native
![image](https://user-images.githubusercontent.com/17067380/44352935-2c6c8200-a4d8-11e8-9817-49ca5585a43d.png)
![image](https://user-images.githubusercontent.com/17067380/44353026-705f8700-a4d8-11e8-815c-6e04081812b9.png)

**Comment by SupriyaKalghatgi** [comment]
Fixed here with commit https://github.com/GeekyAnts/NativeBase/commit/007fabb3a3cd44a44d9553b0b78f40140aabd4bb

**Comment by SupriyaKalghatgi** [comment]
Fixed with [2.8.0](https://github.com/GeekyAnts/NativeBase/releases/tag/v2.8.0)
