### ISSUE TITLE
why cant i pass extra attributes

### ISSUE THREAD

**Issue by 1molehayo** [GeekyAnts/NativeBase#2227]
I want to be able to pass in extra attributes to the renderHeader function, for example, if I want to pass an icon type for each object in the data array, how do I do that,

`const dataArray = [
  {
    title: 'Date',
    iconType: 'Octicons',
    iconName: 'calendar',
    content: 'Lorem ipsum dolor sit amet'
  },
  {
    title: 'Cards',
    iconType: 'Octicons',
    iconName: 'credit-card',
    content: 'Lorem ipsum dolor sit amet'
  },
  {
    title: 'Account',
    iconType: 'FontAwesome',
    iconName: 'bank',
    content: 'Lorem ipsum dolor sit amet'
  }
];`

and then do this in my render function

` _renderHeader(title, expanded, iconType, iconName) {
    return (
      <View style={styles.header}>
        <View style={styles.iconBox}>
          <View style={styles.icon}>
            <Icon
              type={iconType}
              name="calendar"
              style={{ fontSize: fonts.iconSize._SMALL, color: color._PRIMARY }}
            />
          </View>
          <Text style={{ fontFamily: fonts.family._SEMI_BOLD }}> {title}</Text>
        </View>
        {expanded ? (
          <Icon
            type="Entypo"
            name="chevron-up"
            style={{ fontSize: fonts.iconSize._MEDIUM, color: color._LIGHTER_BLUE }}
          />
        ) : (
          <Icon
            type="Entypo"
            name="chevron-down"
            style={{ fontSize: fonts.iconSize._MEDIUM, color: color._LIGHTER_BLUE }}
          />
        )}
      </View>
    );
  }`

How can I achieve this?

**Comment by SupriyaKalghatgi** [comment]
#2163
