### ISSUE TITLE
Keyboard popup view auto-scroll not working for <Textarea />

### ISSUE THREAD

**Issue by AlexWroten** [GeekyAnts/NativeBase#2228]
`npm version 6.2.0`
`react-native 0.56.0`
`native-base 2.7.2`

I cannot get the soft keyboard popup to auto-align with input text position or cursor. The view doesn't autoscroll at all, and the keyboard covers the inputs.

With the following View layout:
`<Container>
  <Content padder enableAutomaticScroll>
    <Form>
      <Textarea rowSpan={5} />
      <Textarea rowSpan={5} />
      <Textarea rowSpan={5} />
      <Textarea rowSpan={5} />
    </Form>
  </Content>
</Container>`

Some screenshots of a textarea with and without the keyboard
![screen shot 2018-08-20 at 1 22 39 pm](https://user-images.githubusercontent.com/8226402/44364560-2fd22000-a47c-11e8-8fc0-c8d00558d953.png)
![screen shot 2018-08-20 at 1 22 51 pm](https://user-images.githubusercontent.com/8226402/44364561-2fd22000-a47c-11e8-846e-cfb8f5409c60.png)

It's at least present in iOS.

Any thoughts?

**Comment by AlexWroten** [comment]
@SupriyaKalghatgi I went through that whole issue, and attempting to use a ScrollView + KeyboardAvoidingView doesn't produce any better results for me.

Keep in mind, my structure *is* using the suggested NativeBase <Container> and <Content> components, so that shouldn't be a problem...

It does work properly on Android, FYI.

**Comment by SupriyaKalghatgi** [comment]
I shared #1518 to share an example where Keyboard works fine with <Input />

**Comment by mgamsjager** [comment]
Similar issue here in iOS.
The normal <Input> does trigger a scroll into focus with the keyboard visible. 
The multiLine <Input> does not.

```
<Container >
                <Content scrollEnabled>
                    <StatusBar hidden />
                    <Grid>
                        <Row style={{height: 600, backgroundColor: 'green'}}>
                            <Text>Image placeholder</Text>
                        </Row>
                        <Row >
                            <Form >
                                <Item regular>
                                    <Input  />
                                </Item>
                                <Item stackedLabel last>
                                    <Input   multiline placeholder='Type your text here'/>
                                </Item>
                            </Form>
                        </Row>
                    </Grid>
                </Content>
            </Container>
```

**Comment by SupriyaKalghatgi** [comment]
https://github.com/facebook/react-native/issues/20996

Happens to be React Native issue
