### ISSUE TITLE
invoking onPress function of CheckBox leads to crash (android&ios)

### ISSUE THREAD

**Issue by ChillkroeteTTS** [GeekyAnts/NativeBase#2230]
## node, npm, react-native, react and native-base version
react-native: 0.56.0
native-base: 2.7.2

## Expected behaviour
When clicking on the CheckBox component, the onPress function is called

## Actual behaviour
The App freezes for a few seconds and crashes afterwards. Nothing is logged.

If I remove the onPress prop I can click the checkbox without freeze but obviously nothing happens.

## Steps to reproduce should include code snippet and screenshot
Click on the checkbox

```
<ListItem style={commonStyles.flexRow} noBorder>
     <CheckBox color={theme.brandPrimary} onPress={(e) => console.log(e)} checked={false} />
     <Text style={{ marginLeft: 20 }}>Spa</Text>
</ListItem>
```

## Is the bug present in both iOS and Android or in any one of them?
both

**Comment by ChillkroeteTTS** [comment]
Not sure how to share the code from Snack, is the link enough?:
https://snack.expo.io/SkBlTFK87

I run the provided code on my device (with expo) and got an 'out of memory' error.

**Comment by SupriyaKalghatgi** [comment]
I checked snack link and tried running on Android, the app hangs as soon as its loaded

Can you simplify the code? Is this modal thing needed to check working of checkbox?

**Comment by ChillkroeteTTS** [comment]
That's unfortunate, it worked for me on my device(android) as well as appetize.io.

Here is a barebone version of the code where the issue still exists: https://snack.expo.io/BkvUejqI7

**Comment by SupriyaKalghatgi** [comment]
Check this ttps://snack.expo.io/HywZ1hqLX

`onPress={(e) => console.log(e)}` this was causing issue on Android from snack, worked fine for iOS

**Comment by SupriyaKalghatgi** [comment]
@ChillkroeteTTS Did you checked snack link that i shared?

**Comment by ChillkroeteTTS** [comment]
Hey and sry for the late reply. Correctly binding the state did indeed fix it for me, thanks. It's still a bit weird since a console.log shouldn't crash the app and it didn't just happened on snack.

**Comment by SupriyaKalghatgi** [comment]
I commented that
> onPress={(e) => console.log(e)} this was causing issue on Android from snack, worked fine for iOS

so log on snack is an issue may be

**Comment by ChillkroeteTTS** [comment]
Yes but initialy it happened on my device via adb/react-native bundler - no snack involved. However it works for me now.
