### ISSUE TITLE
Problems using Header with Native Base

### ISSUE THREAD

**Issue by gcmatheusj** [GeekyAnts/NativeBase#2231]
Current Behavior

I'm trying to create a header with a menu button using the native-base component Header, but I'm having problems,
if I use headerMode: 'none' and static navigatioOptions = {header: null} in the other screen the header looks like this:

![desktop screenshot 2018 08 20 - 15 37 10 40](https://user-images.githubusercontent.com/38117213/44363994-3b354380-a49c-11e8-94d2-3585cb4fbd80.png)

If I remove the headerMode: 'none', the screen looks like this:

![desktop screenshot 2018 08 20 - 15 43 31 28](https://user-images.githubusercontent.com/38117213/44364130-96673600-a49c-11e8-8ed8-ed21c07c6c53.png)

And I get a header on the login screen, but I do not want any header on the login screen, only on the following screens.

--- App.js
import React, { Component } from 'react'
import { StyleSheet } from 'react-native'
import { createStackNavigator } from 'react-navigation'

import LoginScreen from './src/components/login/Login'
import HomeScreen from './src/components/home/Home'

export default class App extends Component {

  render() {
    return (
      <AppStackNavigator/>
    )
  }
}

const AppStackNavigator = createStackNavigator({
  Login: LoginScreen,
  Home: HomeScreen
},
{
  headerMode: 'none'
},
  {
    navigationOptions: {
      headerStyle: {
        backgroundColor: '#00CAC9',
      },
    }
  }
)

--- Login.js
import React, { Component } from 'react'
import { StyleSheet, View, Text, TextInput, Button, Image, ScrollView, TouchableOpacity } from 'react-native'
import { createStackNavigator } from 'react-navigation'

import logo from '../../assets/consulte-aqui.png'

class LoginScreen extends Component {

    static navigationOptions = {
        header: null, 
    }

    render() {
        return (
            <ScrollView>
                <View style={styles.container}>
                    <View style={styles.logoContainer}>
                        <Image
                            style={styles.logo}
                            source={logo}
                        />
                    </View>
                    <View style={styles.formContainer}>
                        <TextInput
                            placeholder="Usuário ou Email"
                            placeholderTextColor="rgba(255,255,255,0.7)"
                            style={styles.input}
                        />
                        <TextInput
                            placeholder="Senha"
                            placeholderTextColor="rgba(255,255,255,0.7)"
                            style={styles.input}
                        />
                        <Button color='#009094' title="Entrar" onPress={() => this.props.navigation.navigate('Home')} />
                        <TouchableOpacity style={styles.button}>
                            <Text style={styles.txt_es}>ESQUECI MINHA SENHA</Text>
                        </TouchableOpacity>
                    </View>
                </View>
            </ScrollView>
        )
    }
}

--- Home.js
import React, { Component } from 'react'
import { StyleSheet, View, Text } from 'react-native'
import { createStackNavigator, createDrawerNavigator } from 'react-navigation'

import ConsultaScreen from '../consultas/Consultas'
import ExameScreen from '../exames/Exames'

class HomeScreen extends Component {
    static navigationOptions = {
        header: null,  
    }

    render(){
        return(
            <DrawerMenu></DrawerMenu>
        )
    }
}

export default createStackNavigator({
    Home: {
        screen: HomeScreen,
    },
})

const DrawerMenu = createDrawerNavigator({
    Consultas: {
        screen: ConsultaScreen,
    },
    Exames: {
        screen: ExameScreen
    },    
})

Expected Behavior

I just wanted the header with the menu button to appear correctly on the Home component screens.

![navigationdrawerimg](https://user-images.githubusercontent.com/38117213/44364697-0fb35880-a49e-11e8-9a12-a1383780c7ef.gif)

**Comment by SupriyaKalghatgi** [comment]
Please follow issue template guidelines
Failing which this issue will be closed

**Comment by gcmatheusj** [comment]
I'm going to fix it!

**Comment by SupriyaKalghatgi** [comment]
#1836 
#1907

**Comment by SupriyaKalghatgi** [comment]
@gcmatheusj You have truly messed up details with issue description
Follow issue template guidelines, to clear things

I have assumed what might be the issue and shared similar issue links above
