### ISSUE TITLE
[Question] - How to change selected style for Picker.Item 

### ISSUE THREAD

**Issue by ngouass** [GeekyAnts/NativeBase#2232]
Hey guys, I'm currently trying to change the color of the selected item for the Pick component.
I manage to make it work partially by updating selected style properties for ListItem after ejecting native-base-theme. I'm having this result: 
![capture d ecran 2018-08-22 a 07 32 25](https://user-images.githubusercontent.com/17073855/44444687-56a86780-a5de-11e8-9aac-692d5b9fe9b2.png)

I have this as selected style for ListItem:
```
const selectedStyle = {
    "NativeBase.Text": {
      color: "green",
    },
    "NativeBase.Icon": {
      color: "green",
    },
  };
```

But it's only working for the text. 
What should I do to have the right icon color set to green ?

Thanks

**Comment by SupriyaKalghatgi** [comment]
Can i know why are you customizing style for `ListItem selected`?

**Comment by ngouass** [comment]
Because I want the UI to look consistent based on the 3 colors I have choosen for my app.

**Comment by SupriyaKalghatgi** [comment]
The tick mark is radio button
so you can change radio color in theme/variables

**Comment by ngouass** [comment]
Perfect @SupriyaKalghatgi, thanks for your availability and help.

**Comment by indapublic** [comment]
@SupriyaKalghatgi Is it possible to change Radio style only for Picker item?

**Comment by bjtang28** [comment]
@SupriyaKalghatgi is there a way where I can remove the check icon? perhaps change it to a different icon?

**Comment by MedafPayDevelopers** [comment]
Can't know where to edit it, would you please help

**Comment by anastely** [comment]
I'm trying to change the modal background style, how can I do it "android"?
