### ISSUE TITLE
[Question] - Dynamic PickerItem: Is it possible to display a message if there is no item to display

### ISSUE THREAD

**Issue by ngouass** [GeekyAnts/NativeBase#2233]
Hi, I implemented a Picker with a custom header containing a search box because there is a lot items.

I would like to display a message to the user saying that no items was found matching is search. 
But when trying to display a Text, I got this:
![capture d ecran 2018-08-22 a 11 18 55](https://user-images.githubusercontent.com/17073855/44454976-363bd580-a5fd-11e8-9def-bf671e617140.png)

A PickerItem is displayed with no text and it can be selected.

**Expected Behaviour**
![capture d ecran 2018-08-22 a 11 23 37](https://user-images.githubusercontent.com/17073855/44455255-dd207180-a5fd-11e8-9400-8b2f05024b09.png)

Is that even possible ? if Yes how should I implement it ?

**Comment by SupriyaKalghatgi** [comment]
share GIF for this

**Comment by ngouass** [comment]
![issue](https://user-images.githubusercontent.com/17073855/44455887-7e5bf780-a5ff-11e8-89bc-56626bf6c765.gif)

**Code**
```
{isSearchResultEmpty ? (
                <View>
                  <Text style={styles.contentEmptyResultMessage}>
                    No city found matching your search.
                  </Text>
                </View>
              ) : (
                cities.map(city => (
                  <Picker.Item label={city.name} value={city.id} />
                ))
              )}
```

Hope this help to understand my problem.

**Comment by SupriyaKalghatgi** [comment]
```
<Picker>
.  .  .  
  {isSearchResultEmpty 
  ? (<Item label="No Matches" value="key0" />)
  : ( // render other Item)
  }
</Picker>
```
