### ISSUE TITLE
[Question] - Picker with custom header(Search input): Need two taps to select item when focus is on search input.

### ISSUE THREAD

**Issue by ngouass** [GeekyAnts/NativeBase#2234]
Hi, I'm implementing a picker with a search input in the header and I noticed that after a search I need two taps to pick an item.

## Dependencies versions
```
node: v8.0.0
npm: 4.6.1
"native-base": "2.7.2",
"react": "16.4.2",
"react-native": "0.56.0",
```

## Expected behaviour
I was expecting the item to be picked with one tap like it's done when the search box is not focus.
![expected](https://user-images.githubusercontent.com/17073855/44504223-d562da80-a69a-11e8-8e09-453ae850e6f4.gif)

## Actual Behaviour
1. First tap to hide the keyboard
2. Second one to select an item

![issue-2](https://user-images.githubusercontent.com/17073855/44469100-05709600-a627-11e8-8d5f-7bf9324adfa0.gif)

## Is the bug present in both iOS and Android or in any one of them?
I'm currently only working on iOS platform.

## Code snippet
**Segment**
```
const {selected, onValueChange, cities, searchCity, onGoingSearch} = props;

<Segment style={styles.segment}>
  <Left
    style={{
      flexShrink: 1,
      flexGrow: 1,
      flexBasis: "100%",
      paddingLeft: 10,
    }}
  >
    <Picker
      renderHeader={backAction => (
        <PickerHeader
          handleSearchInput={searchCity}
          backAction={backAction}
        />
      )}
      style={{
        backgroundColor: "rgba(216, 216, 216, 0.21)",
        borderRadius: 25,
        height: 40,
        marginBottom: 5,
      }}
      mode="dropdown"
      textStyle={{
        color: "white",
        paddingLeft: 20,
        fontSize: 16,
      }}
      placeholder="Select your city"
      placeholderStyle={{color: "white", paddingLeft: 15}}
      iosIcon={
        <Right>
          <Icon
            name="ios-arrow-down-outline"
            style={{
              color: "white",
              paddingRight: 15,
              fontSize: 20,
            }}
          />
        </Right>
      }
      selectedValue={selected}
      onValueChange={onValueChange}
    >
      {onGoingSearch && cities.length === 0 ? (
        <View>
          <Text>
            No city Matching your search.
          </Text>
        </View>
      ) : (
        cities.map(city => (
          <Picker.Item label={city.name} value={city.id} key={city.id} />
        ))
      )}
    </Picker>
  </Left>

  <Button
    transparent
    style={{
      flexShrink: computeShrinkForSearchButton(),
      flexGrow: 2,
      flexBasis: "100%",
      borderColor: "transparent",
    }}
  >
    <Text
      style={{
        color: "#7ED321",
        paddingLeft: 10,
        paddingRight: 5,
        fontWeight: "bold",
      }}
    >
      Search
    </Text>
  </Button>
</Segment>
```
**PickerHeader**
```
const PickerHeader = props => (
  <LinearGradient colors={["#020A15", "#032655"]} style={styles.LinearGradient}>
    <Header style={styles.header} hasSegment>
      <StatusBar backgroundColor="transparent" barStyle="light-content" />


      <Left style={styles.headerLeft}>
        <Button transparent onPress={props.backAction}>
          <Icon name="arrow-back" style={{color: "white", fontSize: 25}} />
        </Button>
      </Left>

      <Body style={styles.headerBody}>
        <Title style={styles.headerBodyTitle}>
          Select your city
        </Title>
      </Body>

      <Right style={styles.headerRight} />
    </Header>

    <Segment
      style={{
        backgroundColor: "transparent",
        paddingTop: 5,
        marginBottom: 10,
      }}
    >
      <Item style={styles.searchBox}>
        <Icon name="search" style={styles.searchBoxIcon} />
        <Input
          placeholder="Search"
          style={styles.searchBoxInput}
          onChangeText={props.handleSearchInput}
        />
      </Item>
    </Segment>
  </LinearGradient>
);
```
## Any other additional info which would help us debug the issue quicker.
When searching I found this issue: https://github.com/GeekyAnts/NativeBase/issues/1117
where the solution was to set: **keyboardShouldPersistTaps='handled'** to the content component.

I had a look at the picker code and it seems to not use Content to render the items:
https://github.com/GeekyAnts/NativeBase/blob/master/src/basic/Picker.ios.js#L197

So I'm wondering how I could fix that issue in my case.

**Comment by SupriyaKalghatgi** [comment]
Please follow issue guidelines
Failing which this issue will be closed

**Comment by ngouass** [comment]
Sorry for not following guidelines, I just update the issue description

**Comment by SupriyaKalghatgi** [comment]
Still cant find code snippet with issue description

**Comment by SupriyaKalghatgi** [comment]
This is not working
Take out styles, props and action

**Comment by SupriyaKalghatgi** [comment]
Better put in it on snack
It has already taken my time

**Comment by SupriyaKalghatgi** [comment]
@ngouass Can you put this on snack?

**Comment by ngouass** [comment]
@SupriyaKalghatgi Trying to do it but I facing issue. it's not able to import a library inside react-native module
https://snack.expo.io/rJKXDWh8m

**Comment by SupriyaKalghatgi** [comment]
You can skip the styles and theme part i guess

**Comment by ngouass** [comment]
Working now ! you can have a look at this link: https://snack.expo.io/Skavj-3IQ

**Comment by SupriyaKalghatgi** [comment]
The UI is completely broken
Don't get what to test here

**Comment by ngouass** [comment]
UI looks better now for test: https://snack.expo.io/rJQWlMnIX

**Comment by SupriyaKalghatgi** [comment]
Can you please run it once yourself?

**Comment by ngouass** [comment]
Done: https://snack.expo.io/Hkua8G3LQ

**Comment by SupriyaKalghatgi** [comment]
Is this what you too get?
![image](https://user-images.githubusercontent.com/13464885/44522393-03c0d400-a6f4-11e8-8166-c81242e7229c.png)

**Comment by ngouass** [comment]
You can select the platform at the bottom of page, the default is Android.
![capture d ecran 2018-08-24 a 09 27 00](https://user-images.githubusercontent.com/17073855/44571065-049f4780-a780-11e8-9430-5eb7f7110d0e.png)

I get this:
![capture d ecran 2018-08-24 a 09 32 41](https://user-images.githubusercontent.com/17073855/44571305-b2aaf180-a780-11e8-992b-99d5061eb5c7.png)

Not a perfect UI but it's enough to reproduce the issue

**Comment by SupriyaKalghatgi** [comment]
@ngouass I get this still https://github.com/GeekyAnts/NativeBase/issues/2234#issuecomment-415379431

You must have updated code and not saved before sharing it here

Please quickly provide the code snippet for me help

**Comment by SupriyaKalghatgi** [comment]
@ngouass Can you reply quickly?

**Comment by ngouass** [comment]
@SupriyaKalghatgi Sorry for the late response. I didn't make a change since the last time. 
Like I said it before I also get [#2234(comment)](https://github.com/GeekyAnts/NativeBase/issues/2234#issuecomment-415379431) if I use Android Platform but it works if I choose(configuration panel at the footer) to run it on iOS device.

**Comment by SupriyaKalghatgi** [comment]
That is not possible, expo cannot scan for iOS

**Comment by SupriyaKalghatgi** [comment]
@ngouass Can you try this use case with React Native Picker?

**Comment by ngouass** [comment]
Will do it !

**Comment by SupriyaKalghatgi** [comment]
@ngouass Did you try? updates?

**Comment by SupriyaKalghatgi** [comment]
Keeping this issue open for today

**Comment by ngouass** [comment]
@SupriyaKalghatgi I didn't have time to test it today, a lot of things in my plate. Will try to dit tomorrow.!

**Comment by SupriyaKalghatgi** [comment]
@ngouass Ok, just tomorrow

You dd'nt respond to my earlier pings

**Comment by patrick-stevenok** [comment]
@ngouass, did you somehow manage to fix this issue?
