### ISSUE TITLE
ScrollableTabs heading breaks the line

### ISSUE THREAD

**Issue by dmitryermichev** [GeekyAnts/NativeBase#2236]
This issue is for the same problem as #2225
It was closed, but problem is not fixed.

I use renderTabBar={()=> <ScrollableTab />} but line break occures in Tab heading text.

I am using code from documentation [documentation](https://docs.nativebase.io/Components.html#tabs-scrollable-headref)

```
import React, { Component } from 'react';
import { Container, Header, Tab, Tabs, ScrollableTab, Text} from 'native-base';
export default class TestTabs extends Component {
    render() {
        return (
            <Container>
                <Header hasTabs/>
                <Tabs renderTabBar={()=> <ScrollableTab />}>
                    <Tab heading="Tab1">
                        <Text>Tab1</Text>
                    </Tab>
                    <Tab heading="Tab long long name">
                        <Text>Tab2</Text>
                    </Tab>
                    <Tab heading="Tab long long long name">
                        <Text>Tab3</Text>
                    </Tab>
                    <Tab heading="Tab long long long name">
                        <Text>Tab4</Text>
                    </Tab>
                    <Tab heading="Tab long long long long name">
                        <Text>Tab5</Text>
                    </Tab>
                </Tabs>
            </Container>
        );
    }
}
```

Try to scroll to third tab and line break will occure.

native-base version - "native-base": "^2.7.2"

![screenshot_2018-08-23-11-32-30-507_com clientapp](https://user-images.githubusercontent.com/14346528/44514641-50db8080-a6c9-11e8-875a-d36180bd466f.png)

**Comment by dmitryermichev** [comment]
Problem occures when using custom theme 
[variables.js.zip](https://github.com/GeekyAnts/NativeBase/files/2313678/variables.js.zip)

**Comment by SupriyaKalghatgi** [comment]
This is with NativeBase default theme
![tabs](https://user-images.githubusercontent.com/13464885/44521060-6ebbdc00-a6ef-11e8-8366-4e502b776b0f.gif)


This is with the `variable.js` file that you shared above
![tabs-1](https://user-images.githubusercontent.com/13464885/44521074-78454400-a6ef-11e8-9c76-be1881fdee97.gif)

Worked fine in both case

**Comment by dmitryermichev** [comment]
I replaced custom theme and all tabs are ok

**Comment by SupriyaKalghatgi** [comment]
I said i tried with the theme that you shared, and it worked fine

**Comment by SupriyaKalghatgi** [comment]
How dd'nt it work for you?

**Comment by dmitryermichev** [comment]
I created another theme 
[commonColor.custom.js.zip](https://github.com/GeekyAnts/NativeBase/files/2314098/commonColor.custom.js.zip)

With old theme it doesn't work. 
Did you try with "native-base": "^2.7.2"?

**Comment by SupriyaKalghatgi** [comment]
Yes i tried with NativeBase 2.7.2
Sorry i cant test with this theme

**Comment by dmitryermichev** [comment]
I replace import external config. You can try theme file below.
[commonColor.custom.js.zip](https://github.com/GeekyAnts/NativeBase/files/2314115/commonColor.custom.js.zip)

**Comment by mohemos** [comment]
Facing the same issue, @dmitryermichev were you able to fix it ?

**Comment by FindelFof** [comment]
Hi I Have a same probleme on android device @dmitryermichev  How do you ix it?
