### ISSUE TITLE
[ts] "native base has no exported module connectStyle"

### ISSUE THREAD

**Issue by Eddie-CooRo** [GeekyAnts/NativeBase#2238]
## node, npm, react-native, react and native-base version, expo version if used
native-base@2.7.2
## Expected behaviour
Importing "connectStyle" from nativebase
## Steps to reproduce
```npm i native-base@latest```
```import {connectStyle} from 'native-base'```
## Actual behaviour
"connectStyle" HOC should get exported inside index.d.ts

**Comment by vinay0458** [comment]
temporary solution for writing jest test cases, 
ignore nativebase like this in jest
"transformIgnorePatterns": [
      "/node_modules/(?!react-native|react-clone-referenced-element|react-navigation|native-base)"
    ],

**Comment by cargallo** [comment]
Any Solution to this?

**Comment by AmalMenachery** [comment]
@SupriyaKalghatgi The Issue is still open in 2.13.12, Is the fix expected soon ?
