### ISSUE TITLE
Only <Title> in <Header> should still align left on Android

### ISSUE THREAD

**Issue by david50407** [GeekyAnts/NativeBase#224]
In Android, when there is only one `<Title>` element inside `<Header>`, it will align center as picture below:

![image](https://cloud.githubusercontent.com/assets/841969/19164642/6d8421ea-8c33-11e6-97ba-5812d3f14853.png)

But expected with aligning left to match Android styles as picture below:

![image](https://cloud.githubusercontent.com/assets/841969/19164681/90551ce2-8c33-11e6-8ac0-6b3c81d3a0d7.png)

**Comment by bgbraga** [comment]
How can I put title center after that change?
