### ISSUE TITLE
It is possible to force Android platform to use iOS theme?

### ISSUE THREAD

**Issue by gersonmontenegro** [GeekyAnts/NativeBase#2240]
Is a direct question, actually, at least for me, is not a bug o problem, but I would like to know if that is possible, and of course, how?

Thanks.

**Comment by SupriyaKalghatgi** [comment]
@gersonmontenegro You get `native-base-theme` folder when you eject NativeBase theme. 

- `native-base-theme/variables` gives you three theme files. These are more related to color customization and less on alignment props.

- `native-base-theme/components` gives you component wise customization. Here you can customize each component as per your choice

**Comment by SupriyaKalghatgi** [comment]
@gersonmontenegro I will keep this issue open for today

**Comment by gersonmontenegro** [comment]
Thanks. Actually, I've been working on it. I'll response in a while.

**Comment by gersonmontenegro** [comment]
Is ok if I modify theme/variables/platform.js like this ?
```
import color from "color";

import { Platform, Dimensions, PixelRatio } from "react-native";

const deviceHeight = Dimensions.get("window").height;
const deviceWidth = Dimensions.get("window").width;
const platform = 'ios';
```

**Comment by SupriyaKalghatgi** [comment]
No issues @gersonmontenegro you can try this way

**Comment by gersonmontenegro** [comment]
Sorry, it wasn't clear for me. I forced the _platform_ variable in platform.js, and it doesn't work. Should that works?. Thanks.

**Comment by SupriyaKalghatgi** [comment]
@gersonmontenegro Can you please be a little quick?

**Comment by gersonmontenegro** [comment]
Sorry about that.

Thanks, I injected StyleProvider based in [this example](http://docs.nativebase.io/Customize.html#theaming-nb-headref) , and, in my interface, I wrote:

`<StyleProvider style={getTheme('ios')}>`

And it's works. Thank you, very much :)

**Comment by SupriyaKalghatgi** [comment]
Nice. Closing this issue
