### ISSUE TITLE
Card in React Native

### ISSUE THREAD

**Issue by akshaykumar0291** [GeekyAnts/NativeBase#2244]
Hi, please tell me how to set the margin for the card in react native.

**Comment by SupriyaKalghatgi** [comment]
Please follow issue guidelines
Failing which this issue will be closed.

**Comment by SupriyaKalghatgi** [comment]
Closing this issue, since it does not follow issue guidelines

**Comment by akshaykumar0291** [comment]
Your wish, thankx

**Comment by SupriyaKalghatgi** [comment]
@akshaykumar0291 Check the issue guidelines
If you still need help, you can ping on NativeBase slack
