### ISSUE TITLE
Custom TabBars with only icons - do not get the backgroundColor CSS property

### ISSUE THREAD

**Issue by ghoshabhi** [GeekyAnts/NativeBase#2246]
Hi! Thanks for trying out NativeBase!

Take a look at these before heading towards creating an issue
-   Check latest documentation: https://docs.nativebase.io/
-   Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
-   Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
-   For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
-   For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

Also **DO** fill out the below form to give us a better idea about your environment and help us debug it quicker. Issues without the required details will mostly be closed.

## node, npm, react-native, react and native-base version, expo version if used
node: v8.2.1,
yarn (preferred): 1.9.2, npm: 6.2.0,
"native-base": "^2.8.0",
"react": "16.4.1",
"react-native": "0.56.0",

## Expected behavior
Trying to re-create the design of the tab bar over here: https://dribbble.com/shots/3951507-Team-Member-Profile-Projects.

As my title suggests, I originally had text only as tab content, and the `tabStyle` and `activeTabStyle` worked fine. But after I changed the code to render icons only, the styles got applied to the icon instead of the tab bar background.

What I am hoping to achieve is, that only the underline color of the tabs should change to indicate the active tab, otherwise the tab's background color shouldn't change at all!

## Actual behaviour
<img src="https://user-images.githubusercontent.com/19292575/44818967-ccdd3900-ab9f-11e8-825e-d5699aa023c6.png" width="60%" height="80%">

## Steps to reproduce should include a code snippet and screenshot. Include code snippet in preformatted mode (```code```)

https://github.com/ghoshabhi/UIChallenge_ProfilePage/blob/feature/detail-view/src/components/TabView.js#L26

## Is the bug present in both iOS and Android or in any one of them?
Tested on iOS

## Any other additional info which would help us debug the issue quicker.
Github: https://github.com/ghoshabhi/UIChallenge_ProfilePage/blob/feature/detail-view/
**Branch name: feature/detail-view**

[Source code](https://gist.github.com/andigu/dbd407baecc16ab073f3ede5e0f009f7#file-tabparallax-js-L100) from [this article on Medium](https://codeburst.io/react-native-parallax-scroll-with-tabs-721feec463c5).

**Comment by SupriyaKalghatgi** [comment]
@ghoshabhi The details you provided, are little confusing to me

You are trying to do this  https://dribbble.com/shots/3951507-Team-Member-Profile-Projects.?

OR 

As per article https://cdn-images-1.medium.com/max/800/1*ssesxI8U1846qmuOlmTF_A.gif, trying to change Tab bgcolor as it scrolls up?

Also that, I checked `feature/detail-view` branch, `TabView` file, couldn't find applying tab styles there

**Comment by ghoshabhi** [comment]
Thank you for your response. I am trying to achieve the design shown in dribble. The medium article in the process of teaching animation does achieve that ( after navbar height reduces and tab bar background and navbar background colors are same).

Regarding the styles, I think I might have reverted or not pushed those changes. I will check and update you.

Besides, do you have an example to achieve the same design but using icons only in tabbar ?

**Comment by SupriyaKalghatgi** [comment]
Here https://docs.nativebase.io/Components.html#tabs-advanced-headref

Did you check what was issue from your side?

**Comment by SupriyaKalghatgi** [comment]
@ghoshabhi Any updates?

**Comment by SupriyaKalghatgi** [comment]
Closing this today in case of no response

**Comment by ghoshabhi** [comment]
@SupriyaKalghatgi: Sorry for the delay in response. I was out traveling. So, the problem with the link you shared with the example of [Advanced Tabs](https://docs.nativebase.io/Components.html#tabs-advanced-headref) is exactly my issue.

If you notice, there's no background color on the tabs. The color only gets applied to the icons as tints. I want a different color for the icon and different background color for the tabs they are within (as per the original Dribble design).

Makes sense?
