### ISSUE TITLE
Top tabs redundantly animate scroll when changing screen width

### ISSUE THREAD

**Issue by shlokamin** [GeekyAnts/NativeBase#2249]
## node, npm, react-native, react and native-base version, expo version if used
node - v8.9.4
react-native - 0.53.3
native-base - 2.4.4

## Expected behaviour
Same active top tab will already be loaded and present with no animation 

## Actual behaviour
Tab animation scrolls to previously active tab

## Steps to reproduce 
Change a screen with scrollable top tabs to have a width of 0 (for the purpose of hiding it and presenting another screen on top of it). Change the width back to what it was, and you'll see the tab animation scrolling to the tab you were previously on. 

## Is the bug present in both iOS and Android or in any one of them?
Both

## Any other additional info which would help us debug the issue quicker.
I've done some debugging and it looks like _handleLayout in [Tabs/index.js](https://github.com/GeekyAnts/NativeBase/blob/master/src/basic/Tabs/index.js) gets called when changing the width of the screen. Because our app hides the screen with the scrollable top tabs when presenting another screen on top of it, we set the width to 0. As a result, this block executes:

    if (Math.round(width) !== Math.round(this.state.containerWidth)) {
      this.setState({ containerWidth: width });
      this.requestAnimationFrame(() => {
        this.goToPage(this.state.currentPage);
      });
    }
  

This causes the animation to repeat when it shouldn't. Would it make sense to just do an additional check to see if the screen width is set to zero (indicating that the screen is being hidden) before executing the block in the if statement above? If so, I can open up a PR and do that. 

I've attached a GIF below. You'll see that when entering the top tab with title "HEADLINE", clicking on an item, and then returning back to the top tab screen, the scrollable tab jumps to "HEADLINE" when it should just already be there. 

Note - The GIF then quickly restarts and it looks like its going back to "TOP NEWS" so ignore that. 

![out](https://user-images.githubusercontent.com/5788529/44878981-54957700-ac76-11e8-9a24-027c35927e66.gif)

**Comment by SupriyaKalghatgi** [comment]
@shlokamin As per issue guidelines, you are missing out code snippet
Make sure the code snippet reproduces the issue
Putting it in snack would be more favourable

**Comment by shlokamin** [comment]
@SupriyaKalghatgi [react-native-scrollable-tab-view ](https://github.com/happypancake/react-native-scrollable-tab-view) seems to be abandoned. I'll go ahead and open a PR anyways and see if I can find someone who can merge. 

It also looks like the version native base is using is different than what is currently on their repo. Do you folks manually copy over the required components? I don't see react-native-scrollable-tab-view anywhere in your package.json

**Comment by shlokamin** [comment]
Also, it looks like someone has already made the fix [here](https://github.com/happypancake/react-native-scrollable-tab-view/commit/2720bb3028e4c2066f8567ca0c23a6b60c672faf)

**Comment by shlokamin** [comment]
@SupriyaKalghatgi  any update on this? Would be nice to use your official repo instead of my fork. Let me know if I can help out in any way! Like I said, it looks like if you update your react-native-scrollable-tab-view dependency this should be fixed!

**Comment by brennan-pilcher** [comment]
@SupriyaKalghatgi can this issue be re-opened please? It looks like the fix is already implemented in the newer version of react-native-scrollable-tab-view, so it should be quick to update your dependencies and get it working again. Thanks!

**Comment by suvenduchhatoi** [comment]
Fixed #2572
