### ISSUE TITLE
Buttons have a grey square background

### ISSUE THREAD

**Issue by gerardo15** [GeekyAnts/NativeBase#2251]
Hey Guys, I don't know if this is normal but all the buttons that have an Icon when you press them this Square box appear I can see this behavior in all the demos and in the Premium themes. 

![image](https://user-images.githubusercontent.com/12488663/44912986-28d4c880-ad2c-11e8-96dd-42f572853404.png)

In my personal opinion makes it look weird, I spend my day looking at all my apps and the correct way is that the opacity affects the arrow itself not the whole square

**Comment by gerardo15** [comment]
I fixed by changing the React Native Base Button to TouchableOpacity.

Before

```
<Button>
    Some Text
</Button>
```

After

```
<TouchableOpacity activeOpacity={0.4}>
    Some Text
</TouchableOpacity>
```

I think for this icon buttons TouchableOpacity delivers a more clean result.

END Result 

![image](https://user-images.githubusercontent.com/12488663/44916505-355e1e80-ad36-11e8-8fe2-66a16507c927.png)


![image](https://user-images.githubusercontent.com/12488663/44916496-31320100-ad36-11e8-957a-5b761377dae7.png)

**Comment by SupriyaKalghatgi** [comment]
NativeBase uses TouchableOpacity for iOS and TouchableNativeFeedback for Android

**Comment by SupriyaKalghatgi** [comment]
Check this commit https://github.com/GeekyAnts/NativeBase/commit/4167cbfea0de651fb4a0c237d70e93e3bebdf409, to find fix. Also merged to `master`
