### ISSUE TITLE
Using nb-drawer with vue

### ISSUE THREAD

**Issue by sawyersteven** [GeekyAnts/NativeBase#2252]
Using a drawer with VueNative seems to work fine except for setting the contents prop.

For example:

```
<template>
	<nb-container>
        <nb-button transparent :onPress="() => toggleDrawer()">
            <nb-icon name="menu" />
        </nb-button>
        <nb-drawer side="right" ref="rightDrawer" :content="rightdrawer"/>
    </nb-container>
</template>


<script>
import rightdrawer from './rightDrawer';

export default {
    components: {rightdrawer },

    methods: {
        toggleDrawer(){
           this.$refs.rightDrawer._root.toggle();
        }
    }
};
</script>
```

Everything works as expected except the contents does not render. The `mounted` and `created` methods of the drawer's contents is also not called. Placing the contents inside the nb-drawer element (ie `<nb-drawer><rightdrawer/></nb-drawer>` draws the contents on the main view rather than inside the drawer.

**Comment by UsamaAltaf** [comment]
How to use this properly if anyone can help please
