### ISSUE TITLE
Property 'transparent' does not exist on type in Header Component

### ISSUE THREAD

**Issue by tyshgc** [GeekyAnts/NativeBase#2253]
Hi!

You write about 'Header Transparent' in this document, It seems like that have a problem with types.
https://docs.nativebase.io/Components.html#header-transparent-headref

#### Typescript Erorr Message
> Property 'transparent' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Header> & Readonly<{ children?: ReactNode; }> & Readonly<Header>'.

#### index.d.ts
https://github.com/GeekyAnts/NativeBase/blob/master/index.d.ts#L88-L110
```
interface Header {
    /**
     * Prop to be used with <Header> component to have Search bar onto the Header section of your screen.
     */
    searchBar?: boolean;
    /**
     * Wraps the search bar with predefined border options.
     * Default: regular
     */
    rounded?: boolean;
    style?: ReactNative.ViewStyle | Array<ReactNative.ViewStyle>;
    /**
     * It is advisable to use hasTabs prop with Header while using Tab
     */
    hasTabs?: boolean;
    noShadow?: boolean;
    hasSubtitle?: boolean;
    span?: boolean;
    androidStatusBarColor?: string;
    iosBarStyle?: ReactNative.StatusBarStyle;
    hasSegment?: boolean;
    translucent?: boolean;
}
```

And called the property `this.props.transparent` in this code, need to define types.
https://github.com/GeekyAnts/NativeBase/blob/master/src/basic/Header.js#L81

**Comment by SupriyaKalghatgi** [comment]
@tyshgc Can you check with commit https://github.com/GeekyAnts/NativeBase/commit/3f97dce37fffeae7e6f510028a89b490893e47b9
