### ISSUE TITLE
Item component with the "floatingLabel" property seems to be incompatible with styled-components

### ISSUE THREAD

**Issue by GSPanue** [GeekyAnts/NativeBase#2256]
**Expected:**
![image](https://user-images.githubusercontent.com/32800503/44947804-d1f1f080-ae0a-11e8-98cb-0df0a14c2931.png)

**Actual:**
![image](https://user-images.githubusercontent.com/32800503/44947827-2d23e300-ae0b-11e8-955b-b772dc807035.png)

**Source Code:**
```
import React from 'react';
import {Form, Item, Input, Label} from 'native-base';
import styled from 'styled-components';

const StyledLabel = styled(Label)`
    background-color: red;
`;

const StyledInput = styled(Input)`
    background-color: rgba(255, 0, 0, 0.1);
`;

export default class TextField extends React.Component {
    render() {
        return (
            <Form style={{width: '100%'}}>
                <Item floatingLabel>
                    <StyledLabel>Label</StyledLabel>
                    <StyledInput/>
                </Item>
            </Form>
        );
    }
}
```

**Package Versions:**
- native-base@2.7.2
- styled-components@3.4.5

**Notes:**
- Upgraded to native-base@2.8.0, the issue still occurs
- ``stackedLabel`` works perfectly

**Comment by SupriyaKalghatgi** [comment]
Did you try with reference?
**Note:** When using floatingLabel, use getRef to get the reference of <Input/> component

**Comment by SupriyaKalghatgi** [comment]
@GSPanue Can you respond quickly?

**Comment by SupriyaKalghatgi** [comment]
@GSPanue Any updates? Do you want to get help here?

**Comment by SupriyaKalghatgi** [comment]
I will leave this issue open for today

**Comment by teo029** [comment]
I can confirm, it doesn't work.
