### ISSUE TITLE
Red box at the bottom

### ISSUE THREAD

**Issue by t1amat9409** [GeekyAnts/NativeBase#2259]
When I use <Root></Root> on web, I get Red Box at the bottom, when I inspect using React DevTools, I shows <ActionSheetContainer> .... </ActionSheetContainer> ... Any idea?

**Comment by SupriyaKalghatgi** [comment]
Please follow issue guidelines
Failing which this issue will be closed

**Comment by SupriyaKalghatgi** [comment]
Closing this issue, since it does not satisfy issue guidelines
