### ISSUE TITLE
Picker: How to change the icon of selected item

### ISSUE THREAD

**Issue by BYElena** [GeekyAnts/NativeBase#2262]
Hi guys,

It's about picker.
Is it possible to change the color of the icon of a selected item or to change the icon itself?
![picker_selecteditem_iphone6](https://user-images.githubusercontent.com/42996641/45082315-5d180280-b0f9-11e8-81d0-5b7479eee062.png)

**Comment by SupriyaKalghatgi** [comment]
@BYElena Please read through issue template before creating one

#2232
