### ISSUE TITLE
`onSubmitEditing` of `Input` not working on Android

### ISSUE THREAD

**Issue by meetdheeraj** [GeekyAnts/NativeBase#2263]
## node, npm, react-native, react and native-base version, expo version if used
node: v8.9.4
npm: 6.4.0
react: 16.2.0
react-native: 0.53.0
native-base: 2.6.1
## Expected behaviour
After entering the text, on the press of enter key from native keyboard, it should not go to next line but trigger submit event and call function called on `onSubmitEditing`
## Actual behaviour
It introduces new line but doesn't trigger `onSubmitEditing`
## Steps to reproduce 
(```<Input onSubmitEditing={this.someFunction}
                            returnKeyType={"go"}
                            blurOnSubmit={true} />```)
## Is the bug present in both iOS and Android or in any one of them?
Just Android
## Any other additional info which would help us debug the issue quicker.
This should suffice.

##How it works in Android:
![ezgif-4-fa9634847f](https://user-images.githubusercontent.com/10056544/45083260-f0acfb80-b118-11e8-8d25-12605cd107b5.gif)

I'm expecting to submit and trigger `onSubmitEditing` on press of enter but it inserts new line.

**Comment by SupriyaKalghatgi** [comment]
Need output too, GIF

**Comment by meetdheeraj** [comment]
@SupriyaKalghatgi Have attached a gif in issue description. Thanks for the quick response.

**Comment by meetdheeraj** [comment]
> Need output too, GIF

@SupriyaKalghatgi  Have updated issue description with a gif. Thanks for the quick response.

**Comment by SupriyaKalghatgi** [comment]
I dont find issue with iOS and Android for this

**Comment by SupriyaKalghatgi** [comment]
https://snack.expo.io/r1v5sQ6vX

**Comment by meetdheeraj** [comment]
@SupriyaKalghatgi  Thanks. Actually it worked after using `returnKeyType="go"
                            blurOnSubmit={true}` as extra parameters.

**Comment by SupriyaKalghatgi** [comment]
Just this `<Input returnKeyType={"go"} />` works
