### ISSUE TITLE
input can control keyboard-type?

### ISSUE THREAD

**Issue by EoeTick** [GeekyAnts/NativeBase#2266]
## node, npm, react-native, react and native-base version, expo version if used
"native-base":"2.7.2"
 "react": "16.3.1"
"react-native": "0.55.3"
## Expected behaviour
input can control keyboard-type
## Actual behaviour
The input does not provide such a property,It would be fine if it seems like text-input of react-native.
## Steps to reproduce should include code snippet and screenshot. Include code snippet in preformatted mode (```code```)
``` <TextInput  keyboardType={"number-pad"} />```

**Comment by A-M-Alizadeh** [comment]
The props of <TextInput> are smoothly applicable to <Input>.

https://github.com/GeekyAnts/native-base-docs/blob/master/docs/components/input-group/InputGroup.md
