### ISSUE TITLE
Passing StyleSheet to Content[contentContainerStyle] crashes

### ISSUE THREAD

**Issue by david50407** [GeekyAnts/NativeBase#227]
In [< Content>](https://github.com/GeekyAnts/NativeBase/blob/master/Components/Widgets/Content.js#L38), it applied padding into user-defined `contentContainerStyle`, but when this attr is StyleSheet, will cause:

```
Attempted to assign to readonly property
```

Because [StyleSheet](https://facebook.github.io/react-native/docs/stylesheet.html) use internal cache to prevent re-generating style props, and this will make these styles readonly, it's better to use arrayed-styles instead of change style directly, like:

``` js
const contentContainerStyle = [
  this.props.contentContainerStyle || {},
  {
    padding: (this.props.padder) ? this.getTheme().contentPadding : 0,
  },
];
```

**Comment by kuzyk** [comment]
How about fix this?

**Comment by adambene** [comment]
Is this fixes?

**Comment by sankhadeeproy007** [comment]
Yes, please refer to #510
