### ISSUE TITLE
Trying to add an Image on the right of a Label. It's working fine with stackedlabel but floating label is making the image dissappear

### ISSUE THREAD

**Issue by sourabhdadapure** [GeekyAnts/NativeBase#2271]
Here's my code and screenshots

import React, { Component } from 'react';
import {View, Image} from 'react-native';

import { Label,Item, Input } from 'native-base';

export default class Splash extends Component {
    constructor(props){
        super(props);
    }

    render() {
        return (
            <View 
                style={{
                    flex:1,
                    justifyContent: 'center',
                    paddingHorizontal: 20,
                    alignItems:'center', 
                    backgroundColor:'grey'
                }}>
                <Item>
                    <Label style={{color:'black'}}>Email</Label>
                    <Input/>
                    <Image 
                        source={require('../images/email1.png')}
                        style={{
                            width:70,
                            height:35,
                            resizeMode:'contain'
                        }}/>
                </Item>
            </View>
        )
    }
}

![simulator screen shot - iphone 6 - 2018-09-13 at 06 40 21](https://user-images.githubusercontent.com/16284964/45483877-42104880-b720-11e8-8c51-a38d39c1652d.png)

But when I add floating label the image goes away
import React, { Component } from 'react';
import {View, Image} from 'react-native';

import { Label,Item, Input } from 'native-base';

export default class Splash extends Component {
    constructor(props){
        super(props);
    }

    render() {
        return (
            <View 
                style={{
                    flex:1,
                    justifyContent: 'center',
                    paddingHorizontal: 20,
                    alignItems:'center', 
                    backgroundColor:'grey'
                }}>
                <Item floatingLabel>
                    <Label style={{color:'black'}}>Email</Label>
                    <Input/>
                    <Image 
                        source={require('../images/email1.png')}
                        style={{
                            width:70,
                            height:35,
                            resizeMode:'contain'
                        }}/>
                </Item>
            </View>
        )
    }
}

![simulator screen shot - iphone 6 - 2018-09-13 at 06 40 54](https://user-images.githubusercontent.com/16284964/45483896-4e94a100-b720-11e8-9812-e61005c2fb86.png)

**Comment by SupriyaKalghatgi** [comment]
Added Thumbnail support for floatingLabel, commit https://github.com/GeekyAnts/NativeBase/commit/2e4d41483dd15e3f3e871b2c1a995c8d3a466fcb

Also available on `master`

Quick demo

![floatinglabel](https://user-images.githubusercontent.com/13464885/45670001-46cd6600-bb3f-11e8-9da9-5966be170db5.gif)
