### ISSUE TITLE
Native component won't appear

### ISSUE THREAD

**Issue by RijaAdrian** [GeekyAnts/NativeBase#2273]
node -v 9.5.0
npm -v 5.6.0
react-native-cli: 2.0.1
react-native: 0.55.4
native-base 2.8.0

Hi everyone, actually I am using native-base as a template base for my mobile app.But hsomehow all native-base component doesn't work in my environment.

Here is my simple code 
![simple](https://user-images.githubusercontent.com/17961600/45508874-b4c00900-b79e-11e8-8187-972091dbbe03.PNG)

And here is what I get
![get](https://user-images.githubusercontent.com/17961600/45508906-c99c9c80-b79e-11e8-9950-444047706153.PNG)

Strangely both Text components appear but not native-base ones, however, I imported the components and no error arose. Could anyone please tell me why or could help me find the reason?

Thank you

**Comment by SupriyaKalghatgi** [comment]
@RijaAdrian This is supposed to be incomplete code

I get error `Adjacent JSX elements must be wrapped in an enclosing tag`

**Comment by SupriyaKalghatgi** [comment]
![image](https://user-images.githubusercontent.com/13464885/45671158-5e5a1e00-bb42-11e8-8250-bb7125e81f2a.png)

This is not NativeBase

**Comment by SupriyaKalghatgi** [comment]
![image](https://user-images.githubusercontent.com/13464885/45671179-6b770d00-bb42-11e8-9701-6be696fe5f95.png)

I cannot test this code

**Comment by SupriyaKalghatgi** [comment]
You can create new issue, with complete and correct details
