### ISSUE TITLE
Placeholder inside input is not vertical aligned properly

### ISSUE THREAD

**Issue by GiacomoK** [GeekyAnts/NativeBase#2274]
Hi,  
I have an Input with a placeholder that is not vertical aligned properly.  
This is the input:

    `<Item>
         <Icon name="ios-search" />
         <Input onChangeText={(text) => this.setState({filterText: text})} placeholder={strings("main.search")} />
     </Item>`

As you see from attachment, the placeholder is not vertical aligned properlly.  

![screenshot_2018-09-14-12-15-58](https://user-images.githubusercontent.com/16156317/45546860-f1cbe000-b81e-11e8-84e2-d8993cf180bb.png)

**Comment by SupriyaKalghatgi** [comment]
Found no issue

![image](https://user-images.githubusercontent.com/13464885/45610518-cdb80b00-ba79-11e8-8cd1-00ade0c41577.png)

**Comment by GiacomoK** [comment]
Can you pls post the code of the component you used for this example?

**Comment by GiacomoK** [comment]
Can you pls post the code of the component you used for this example?
