### ISSUE TITLE
Build in Release Android error Label with floatingLabel

### ISSUE THREAD

**Issue by vauruk** [GeekyAnts/NativeBase#2276]
Hi Guys ! i have a problem.

in my code it's like this and when compiling in debug it works, but when the build release does not work, the sequencing of the images occurs and my code in sequence

In my code it's like this and when compiling in debug it works, but when the build release does not work, the sequencing of the images 1 2 happens and my code is in sequence, I verified this problem on the internet and found nothing similar if they know how to solve the path. In image 2 is hide labels.  thank you.

![image 1](https://user-images.githubusercontent.com/12579082/45590666-12299680-b914-11e8-9d99-8635d409bf6b.jpeg)
![image 2](https://user-images.githubusercontent.com/12579082/45590671-18b80e00-b914-11e8-9ff1-19ece8ad7f30.jpeg)

<img width="412" alt="captura de tela 2018-09-15 as 18 21 30" src="https://user-images.githubusercontent.com/12579082/45590676-35ecdc80-b914-11e8-9152-b3a92fa3de04.png">

Package.json
{
  "name": "newproject",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "native-base": "^2.8.0",
    "react": "16.4.1",
    "react-native": "0.56.0"
  },
  "devDependencies": {
    "babel-jest": "23.6.0",
    "babel-preset-react-native": "^5",
    "jest": "23.6.0",
    "react-test-renderer": "16.4.1"
  },
  "jest": {
    "preset": "react-native"
  }
}

**Comment by SupriyaKalghatgi** [comment]
#2264
