### ISSUE TITLE
Failing To Start Up A Native Base Project

### ISSUE THREAD

**Issue by jeromesenyonga** [GeekyAnts/NativeBase#2277]
Hello.. Hope Your All fine. I'm trying to start up a project of react native with native base but when i follow the procedures of the documentation on the native base website... but still failed.. because after finishing the procedures and try to run the app using expo from my computer to my phone i get an error that {"Error: Missing app.json. See https://docs.expo.io/ "
Couldn't start project. Please fix the errors and restart the project."} any help on this please.. or any procedures u can give for me to make the app work on expo.. thanks
![exp](https://user-images.githubusercontent.com/35918694/45597392-5ce0f800-b980-11e8-9eba-d430c43663fe.PNG)

**Comment by SupriyaKalghatgi** [comment]
@jeromesenyonga Share the project structure, I want to know the files and folders present
Also share `app.json` screenshot

**Comment by SupriyaKalghatgi** [comment]
@jeromesenyonga Any updates?

**Comment by jeromesenyonga** [comment]
Hello @SupriyaKalghatgi  this it  
![folder](https://user-images.githubusercontent.com/35918694/45617584-a2a4cb80-ba27-11e8-902e-88e7597f12f8.PNG)
![appjson](https://user-images.githubusercontent.com/35918694/45617586-a2a4cb80-ba27-11e8-8a2d-4772774e5db6.PNG)

**Comment by SupriyaKalghatgi** [comment]
Looking at your folder structure, I am not sure if this is React Native or Expo app

I would like you to go through docs https://docs.nativebase.io/docs/GetStarted.html

**Comment by SupriyaKalghatgi** [comment]
did you try creating a fresh project?
If yes, then share screenshot of folder structure, package.json, app.json

**Comment by SupriyaKalghatgi** [comment]
Expo version in package.json and SDK version in app.json should be same

**Comment by SupriyaKalghatgi** [comment]
I tried creating a new CRNA project, it had expo 27
Added NativeBase and tried https://docs.nativebase.io/Components.html#anatomy-headref
Worked fine

**Comment by SupriyaKalghatgi** [comment]
Any help needed? Can you be a little quick?

**Comment by jeromesenyonga** [comment]
Hello, @SupriyaKalghatgi Could you please if you don't mind list for me the steps you followed creating a new CRNA project and then adding in NativeBase Please In comments without directing me to links... i think there it will be more better. Thanks

**Comment by SupriyaKalghatgi** [comment]
```
npm install -g create-react-native-app
create-react-native-app my-app
cd my-app
yarn add native-base --save
npm install @expo/vector-icons --save
```

*NativeBase use some custom fonts that can be loaded using loadAsync function. Check out this expo link.*

*async componentWillMount() {
  await Expo.Font.loadAsync({
    'Roboto': require('native-base/Fonts/Roboto.ttf'),
    'Roboto_medium': require('native-base/Fonts/Roboto_medium.ttf'),
  });
}*

You can also refer NativeBase KitchenSink to know how to add these fonts https://github.com/GeekyAnts/NativeBase-KitchenSink/blob/CRNA/src/boot/setup.js

Then run the project

**Comment by jeromesenyonga** [comment]
Hello.. @SupriyaKalghatgi Thank You So much... the project now runs very well though this is the warning i'm trying to get in the terminal....
![wo](https://user-images.githubusercontent.com/35918694/45786324-cda83e80-bc24-11e8-9af6-aa98a5c1564e.PNG)
Just asking if it wont bring errors...

**Comment by SupriyaKalghatgi** [comment]
Check if you can run this snippet https://docs.nativebase.io/Components.html#anatomy-headref
And please be quick

**Comment by SupriyaKalghatgi** [comment]
I will be closing this today
