### ISSUE TITLE
Cannot override component such as Input in Item

### ISSUE THREAD

**Issue by jpolo** [GeekyAnts/NativeBase#2278]
## Expected behaviour
someProps should be present on Input component

## Actual behaviour
No props are forwarded to input

## Steps to reproduce should include code snippet and screenshot. Include code snippet in 
```jsx
function MyInput() {
  // do some stuff
  return <Input {...computedProps} />;
}

<Item>
<MyInput ...someProps />
</Item>
```

## Any other additional info which would help us debug the issue quicker.
- present in iOS and Android

**Comment by SupriyaKalghatgi** [comment]
@jpolo Can you share the same use case with React Native TextInput?

**Comment by SupriyaKalghatgi** [comment]
@jpolo Any updates?

**Comment by jpolo** [comment]
Haven't tried... I think the code in Item.js is pretty explicit :
```jsx

    let input = [];
    let inputProps = {};
    input = _.remove(childrenArray, item => {
      if (item.type === Input) {
        inputProps = item.props;
        this.inputProps = item.props;
        return item;
      }
    });
```
I see two options : use react context to register props to the parent or avoid putting heterogeneous elements in children and use one prop per type label, input, etc.
I have tested the second option in my projects and it is the best because it is simple to reproduce compared to context and it is very well typed (in flow at least don't know for ts)

**Comment by SupriyaKalghatgi** [comment]
@jpolo Please get me the same use case with React Native TextInput

**Comment by suvenduchhatoi** [comment]
@jpolo 
If what you are trying to do fails for "react-native" TextInput(as you think it will-as mentioned by you previously), then it is an issue of "react-native", and you will notice the exact behaviour if reproduced with "native-base" Input...So, Please check and move forward with the issue if it is a problem exclusive to "native-base"...

**Comment by jpolo** [comment]
@suvenduchhatoi 
It is not a React native error but more a Native Base design problem. 
I previously quoted the incriminated code in `Item.js` https://github.com/GeekyAnts/NativeBase/blob/master/src/basic/Item.js#L44

```javascript
_.remove(childrenArray, item => {
      if (item.type.displayName === "Styled(Input)") { // <=== Here is the problem it will never work on a React Native Text or any other component than a native base input
        inputProps = item.props;
        this.inputProps = item.props;
        return item;
      }
});
```

**Comment by suvenduchhatoi** [comment]
@jpolo 
As per your expected behaviour-
"someProps should be present on Input component"-
It actually accepts React-Native ```<TextInput>``` with props and also, Native-Base ```<Input>``` with props...as in the following screenshots:
![screenshot 2018-12-24 at 6 58 20 pm](https://user-images.githubusercontent.com/44160581/50400802-8eebcc80-07af-11e9-8991-4e002e4ca30a.png)
![screenshot 2018-12-24 at 6 59 11 pm](https://user-images.githubusercontent.com/44160581/50400803-8eebcc80-07af-11e9-8ac3-49d658653023.png)

**Comment by suvenduchhatoi** [comment]
Closing the issue due to no response for a while...Hope your issue has been resolved.You can reopen the issue if you still feel the issue is exclusive to "native-base"...

**Comment by jpolo** [comment]
Excuse me for the delay...

I think we can reopen the issue ;)

The full snippet of the use case would be
```javascript
import React, { Component } from 'react-native';
import { Item, Input } from 'native-base';

function MyCustomInput(props) {
  // Do some custom styling, custom validation here, etc
  
  return <Input {...props} />;// props are never received : no value
}

export default MyScreen {
  render() {
    return (
      <Item>
        <MyCustomInput value={true}  />
      </Item>
    )
  }
}
```
