### ISSUE TITLE
clear input rounded

### ISSUE THREAD

**Issue by gorge2004** [GeekyAnts/NativeBase#2279]
i want to clear input rounded but i dont know what have i to do 
`
                            <Item rounded>
                                <Input getRef={(c) =>console.log(c)} multiline={true} placeholder=' Type' onChangeText={(txt) =>{ this.setState({msg:txt}) } }/>
                            </Item>`

in console show undefined

**Comment by SupriyaKalghatgi** [comment]
This does not appear as bug report

Please read through issue guidelines, while creating one

You can refer https://stackoverflow.com/questions/45249807/clear-react-native-textinput

**Comment by gorge2004** [comment]
That is no work because I can not to get ref the <input /> component . I have used prop ref and getRef and the same result

**Comment by SupriyaKalghatgi** [comment]
https://github.com/GeekyAnts/NativeBase/issues/320

**Comment by gorge2004** [comment]
excuse me, that is working .

**Comment by SupriyaKalghatgi** [comment]
Good
