### ISSUE TITLE
Tabs Question

### ISSUE THREAD

**Issue by jesouhaite08** [GeekyAnts/NativeBase#228]
This isn't an issue, but a question. I'm not sure where to go to ask questions so please remove if inappropriate.

I implemented Tabs, but would like to modify the tab styles more than the props that are available. For example, I do not want a borderBottomWidth unless it is the active tab. 

Is this possible or do I need to implement the ScrollableTabView?

**Comment by thundenilla** [comment]
@SupriyaKalghatgi is there any way for to set height for the tab? 

`render() {
    return (
      <Container theme={myTheme}>
        <Content style={styles.bottomView}>
          <Tabs>
            {this.state.tabs.map((tab, i) => {
              return <Tab
                tabLabel={tab}
                i={i}
                key={i} />;
            })}
          </Tabs>
        </Content>
      </Container>
    );
  }
}`

**Comment by sankhadeeproy007** [comment]
This is not possible right now with the current set up of native-base. However the new rewrite should fix it.
