### ISSUE TITLE
Multiple select on Picker

### ISSUE THREAD

**Issue by isaaclem** [GeekyAnts/NativeBase#2282]
Is there any plan on supporting multiple select for Picker component?

**Comment by SupriyaKalghatgi** [comment]
https://github.com/GeekyAnts/NativeBase/issues/1813

**Comment by SupriyaKalghatgi** [comment]
https://stackoverflow.com/questions/48089683/how-to-select-multiple-values-from-picker-component-in-react-native?rq=1
