### ISSUE TITLE
tab style not working

### ISSUE THREAD

**Issue by ZeroCool00** [GeekyAnts/NativeBase#2285]
version
```
"react-native": "0.56.0",
"native-base": "^2.8.0"
```

i am applying background color but its not working

![screen shot 2018-09-19 at 6 01 14 pm](https://user-images.githubusercontent.com/18139594/45753511-bbcf9700-bc36-11e8-925a-c8c5ffe83a87.png)

you can see in image there is not red or green color as i expect.
```
<Tabs>
     <Tab
          heading={
               <TabHeading
                        activeTabStyle={{ backgroundColor: 'green' }}
                        tabStyle={{ backgroundColor: "red" }}
               >
                     <Text>Comment</Text>
               </TabHeading>}>
           <Comment comment={comments}/>
     </Tab>
      <Tab 
             heading={
                     <TabHeading 
                            activeTabStyle={{ backgroundColor: 'green' }} 
                            tabStyle={{ backgroundColor: "red" }}
                     >
                          <Text>History</Text>
                      </TabHeading>}>
                 <History comment={comments} stackUsers={this.props.stackUsers} />
       </Tab>
</Tabs>
```
this issue is in `IOS`, not sure about `android`

**Comment by SupriyaKalghatgi** [comment]
https://github.com/GeekyAnts/NativeBase/blob/master/ISSUE_TEMPLATE.txt

**Comment by ZeroCool00** [comment]
@SupriyaKalghatgi  plz reopen, i follow issue_template as you mention

**Comment by SupriyaKalghatgi** [comment]
http://nativebase.io/customizer/

**Comment by ZeroCool00** [comment]
How do i know how it use on coding side if i apply background color from sidebar. 
code not change in code editor. this link is useless without we know what is actually happening,

**Comment by SupriyaKalghatgi** [comment]
Have you tried downloading theme files from http://nativebase.io/customizer/? before making decision that its useless?

**Comment by ZeroCool00** [comment]
i dont understand what is the actual use of customizer. i meant its say download variable.js file and follow customizer docs, and use ejected theme, i meant how it relate to my issue.. i simply use tab component and tab has some styling props issue.. sorry to say but its like you are leading me in the wrong direction. i dont understand  why i need to follow this customizer step..

**Comment by SupriyaKalghatgi** [comment]
I hope now you will be clear with NativeBase Customizer
![tabs](https://user-images.githubusercontent.com/13464885/45798207-90948880-bcc6-11e8-8a28-de4cc0a99329.gif)

**Comment by SupriyaKalghatgi** [comment]
Download variable file will give you the updated theme file as per changes made by you
You can then use this downloaded theme file in your app, by following https://docs.nativebase.io/Customize.html#Customize

**Comment by SupriyaKalghatgi** [comment]
Also why haven't you checked https://docs.nativebase.io/docs/ThemeVariables.html?
This was mentioned in issue template

**Comment by ZeroCool00** [comment]
woooh.. it become to messy understand native-base now.. guess i need to limit my use of native-base for icon, input, button and checkbox component.
Thank you for your support.

**Comment by SupriyaKalghatgi** [comment]
why messy?
Its more easy due to NativeBase Customizer which acts as live editor, which tells you if and how to customize components

**Comment by SupriyaKalghatgi** [comment]
Its not mandatory to use NativeBase Customizer before you customize NativeBase components
It will help you know if its possible or not, also gives you preview of how our customization would look into your app

**Comment by ZeroCool00** [comment]
does that mean if i use tab component i need to use nativebase customizer ?

**Comment by SupriyaKalghatgi** [comment]
My last comment has already answered this before you ask

**Comment by ZeroCool00** [comment]
now your comment looks messy too.. well thank you for your time.

**Comment by SupriyaKalghatgi** [comment]
I have done my best to explain you. Well you can wait over this week, we are coming up with some tutorials about theme. To help solve issue like yours

**Comment by adrianolsk** [comment]
Hello @SupriyaKalghatgi,

I think I found what @ZeroCool00 was talking about, just faced the same issue here, I know about the themes, but I would like to change the background color of the tabs based on the screen I am in.

These are the props from tabs

```
interface Tabs {
			renderTabBar?: Function;
			tabBarPosition?: "top" | "bottom";
			edgeHitWidth?: number;
			springTension?: number;
			springFriction?: number;
			onChangeTab?: Function;
			locked?: boolean;
			initialPage?: number;
			tabBarUnderlineStyle?:ReactNative.ViewStyle | Array<ReactNative.ViewStyle>;
			tabBarBackgroundColor?:string;
			tabBarActiveTextColor?:string;
			tabBarInactiveTextColor?:string;
			tabBarTextStyle?:ReactNative.TextStyle;
			tabContainerStyle?:ReactNative.ViewStyle | Array<ReactNative.ViewStyle>;
			style?: ReactNative.ViewStyle | Array<ReactNative.ViewStyle>;
			contentProps?: ReactNative.ScrollViewProper
               }
```
so there is a option there `tabBarBackgroundColor` but it does't work, the only property I could managed to get working from this props is the `tabBarPosition` and `tabBarUnderlineStyle`

so nothing of this work:
```
tabBarBackgroundColor="red"
tabBarActiveTextColor="red"
tabBarInactiveTextColor="red"
tabBarTextStyle={{ color: "red" }}
tabContainerStyle={{ backgroundColor: "red" }}
style={{ backgroundColor: "red" }}
```

and looking at the code here: https://github.com/GeekyAnts/NativeBase/blob/master/src/basic/Tabs/index.js
```
if (this.props.tabBarBackgroundColor) {
      tabBarProps.backgroundColor = this.props.tabBarBackgroundColor;
}
```

I am going to figure this out when I got some time, do you think this is a issue? Should I open one?

**Comment by adrianolsk** [comment]
@ZeroCool00 I found a solution to my problem, gonna post here case anyone else needs, check if it solves yours.

```jsx
     <Tabs tabBarUnderlineStyle={{ backgroundColor: "yellow" }}>
          <Tab
            heading={
              <TabHeading style={{ backgroundColor: "green" }}>
                <Text>Camera</Text>
              </TabHeading>
            }
          >
            <Tab1 />
          </Tab>
          <Tab heading="Tab2">
            <Tab2 />
          </Tab>
          <Tab heading="Tab3">
            <Tab3 />
          </Tab>
        </Tabs>
```

**Comment by linux08** [comment]
This worked for me
```

<Tabs>
  <Tab
    heading="Your Projects"
    activeTabStyle={{ backgroundColor: '#201D41' }}
    tabStyle={{ backgroundColor: '#FFFFFF' }}
  >
    <Tab1 />
  </Tab>
  <Tab
    heading="Your Proposals"
    activeTabStyle={{ backgroundColor: '#201D41' }}
    tabStyle={{ backgroundColor: '#FFFFFF' }}
  >
    <Tab2 />
  </Tab>
</Tabs>
```

**Comment by andrewheekin** [comment]
@linux08's solution worked for me

**Comment by dmitryt** [comment]
@linux08 yep, that solution works, but then another problem appears, when it's impossible to disable font scaling. More details are available here https://github.com/GeekyAnts/NativeBase/issues/2179

**Comment by chirag-chopraa** [comment]
> @ZeroCool00 I found a solution to my problem, gonna post here case anyone else needs, check if it solves yours.
> 
> ```js-jsx
>      <Tabs tabBarUnderlineStyle={{ backgroundColor: "yellow" }}>
>           <Tab
>             heading={
>               <TabHeading style={{ backgroundColor: "green" }}>
>                 <Text>Camera</Text>
>               </TabHeading>
>             }
>           >
>             <Tab1 />
>           </Tab>
>           <Tab heading="Tab2">
>             <Tab2 />
>           </Tab>
>           <Tab heading="Tab3">
>             <Tab3 />
>           </Tab>
>         </Tabs>
> ```

This seriously worked for me...........
Thanks, bro :)

**Comment by siliconavengers** [comment]
My solution

```javascript
      <Tabs tabBarUnderlineStyle={{ backgroundColor: 'transparent' }}>
        <Tab
          heading="User"
          activeTextStyle={{ color: '#FFF', fontWeight: 'bold' }}
          textStyle={{ color: '#707070', fontSize: 12 }}
          tabStyle={{ backgroundColor: '#FAFAFA' }}
          activeTabStyle={{ backgroundColor: '#129378' }}
        >
          <ProfileTab />
        </Tab>
        <Tab
          heading="Payment"
          activeTextStyle={{ color: '#FFF', fontWeight: 'bold' }}
          textStyle={{ color: '#707070', fontSize: 12 }}
          tabStyle={{ backgroundColor: '#FAFAFA' }}
          activeTabStyle={{ backgroundColor: '#129378' }}
        >
          <PaymentTab />
        </Tab>
      </Tabs>
```

<img width="378" alt="Screenshot 2019-09-10 at 4 40 59 PM" src="https://user-images.githubusercontent.com/31947720/64598232-f56e5480-d3e9-11e9-9390-5611890025be.png">

**Comment by Cookizza** [comment]
I understand I can use the customiser to set the default active tab heading background. But there is no property to set the background of the active heading tab, without using a custom component. 

Tabs contain props for almost everything style wise - except the active heading background..

It would be great to be flexible on this

**Comment by habeebtheprogrammer** [comment]
i still cannot add styling to the activeTab most of the props listed in the documentation does not work at all.

**Comment by nickwang0808** [comment]
> i still cannot add styling to the activeTab most of the props listed in the documentation does not work at all.

same issue here,
