### ISSUE TITLE
How to add border width to Card ?

### ISSUE THREAD

**Issue by userbq201** [GeekyAnts/NativeBase#2286]
native-base 2.4.2

I have
```js
<Card>
  <CardItem header />
  <CardItem />
  <CardItem footer />
</Card>
```

I want add border size to card
```js
<Card style={{ borderWidth: 5 }} >
```
this work, but border always same width (about 1px)

**Comment by userbq201** [comment]
And i add border to each children (CardItem)

**Comment by SupriyaKalghatgi** [comment]
https://github.com/GeekyAnts/NativeBase/blob/master/ISSUE_TEMPLATE.txt

**Comment by ooooseaoooo** [comment]
This issue should be reopened
