### ISSUE TITLE
Floating Label not visible when building app with expo.

### ISSUE THREAD

**Issue by jblevins1991** [GeekyAnts/NativeBase#2287]
I have a very simple component that uses floatingLabels and when I use `expo start` they appear properly. When I use `expo build:android` the labels do not appear at all.

Here is more details from a forum thread. Unfortunately the solution the person proposed did not work for me I also wanted to post this issue here because using an older version is not a solution, its a workaround.

http://discuss.nativebase.io/t/nativebase-form-is-not-visible-properly-in-release-build-apk-generated-with-gradlew-assemblerelease/1142/7

**Comment by SupriyaKalghatgi** [comment]
Did you check #2264 before creating this issue?

**Comment by jblevins1991** [comment]
I did a while ago, but didn't think to check today. A new version will be available this week. Thank you for the link.
