### ISSUE TITLE
Unable to resolve Native Base

### ISSUE THREAD

**Issue by jeromesenyonga** [GeekyAnts/NativeBase#2288]
Hello.. 
When I try to run My Footer Component I get this error.. 
![heade](https://user-images.githubusercontent.com/35918694/45807556-8f3c6f00-bc78-11e8-8fa5-6d700300e0ad.PNG)
What Could Be the Problem?

**Comment by SupriyaKalghatgi** [comment]
Only Footer?

**Comment by jeromesenyonga** [comment]
Yes

**Comment by SupriyaKalghatgi** [comment]
Can you please follow issue template?
How can i assume the code?

**Comment by jeromesenyonga** [comment]
Like what are you trying to mean

**Comment by SupriyaKalghatgi** [comment]
The template which you get when you click on `New Issue` button
Please follow the instructions

**Comment by jeromesenyonga** [comment]
looked through some issues but didnt get a solution

**Comment by SupriyaKalghatgi** [comment]
This is the issue template i was talking about you to follow https://github.com/GeekyAnts/NativeBase/blob/master/ISSUE_TEMPLATE.txt

**Comment by jeromesenyonga** [comment]
This Is the code for the footer
`import React, { Component } from 'react';
import { Container, Header, Content, Footer, FooterTab, Button, Icon, Text, Badge } from 'native-base';

export default class FooterTab extends Component {
  render() {
    return (
      <Container>
        <Header />
        <Content />
        <Footer>
          <FooterTab>
            <Button badge vertical>
              <Badge><Text>2</Text></Badge>
              <Icon name="apps" />
              <Text>Home</Text>
            </Button>
            <Button vertical>
              <Icon name="camera" />
              <Text>Notifications</Text>
            </Button>
            <Button active badge vertical>
              <Badge ><Text>51</Text></Badge>
              <Icon active name="navigate" />
              <Text>Events</Text>
            </Button>
            <Button vertical>
              <Icon name="person" />
              <Text>Feeds</Text>
            </Button>
          </FooterTab>
        </Footer>
      </Container>
    );
  }
}
`

and this is the code in my app.js
`import React from 'react';
import { Root } from "native-base";
import {StackNavigator, DrawerNavigator} from "react-navigation";
import { StyleSheet, Text, View } from 'react-native';


//import Head from "./Header"
import FooterTab from "./Footer";

export default class App extends React.Component {
  render() {
    return (
      <View style={styles.container}>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});
`

**Comment by jeromesenyonga** [comment]
This is my component of the footer.js
![foo](https://user-images.githubusercontent.com/35918694/45812921-16441400-bc86-11e8-8d50-7781028e7a2d.PNG)

and this is my app.js
![app](https://user-images.githubusercontent.com/35918694/45812923-17754100-bc86-11e8-83e2-74a85bcb5c3b.PNG)

when i run yarn start i get this error
![heade](https://user-images.githubusercontent.com/35918694/45812985-3d024a80-bc86-11e8-8812-bb1550063fcf.PNG)

**Comment by SupriyaKalghatgi** [comment]
I want you to try the Anatomy snippet from docs, also mentioned in your previous issue
https://github.com/GeekyAnts/NativeBase/issues/2277#issuecomment-423029453

**Comment by jeromesenyonga** [comment]
I'm still getting the same error

**Comment by SupriyaKalghatgi** [comment]
Try this snippet https://docs.nativebase.io/Components.html#anatomy-headref and share GIF of this code and running on simulator / emulator

**Comment by jeromesenyonga** [comment]
I tried the snippet but its not running on the simulator.. because when i try to run i get the same error
![ann](https://user-images.githubusercontent.com/35918694/45813571-d847ef80-bc87-11e8-9163-157ae78ea7bd.PNG)

**Comment by SupriyaKalghatgi** [comment]
Delete node_modules, lock files, clear cache, run yarn, then run app

**Comment by SupriyaKalghatgi** [comment]
`npm run ios`

**Comment by jeromesenyonga** [comment]
this is what i get when i run the command npm run android
![and](https://user-images.githubusercontent.com/35918694/45816550-d20a4100-bc90-11e8-84da-526eeb100c6a.PNG)

**Comment by SupriyaKalghatgi** [comment]
Did you get the app working in #2277 ?

**Comment by jeromesenyonga** [comment]
Yeah

**Comment by SupriyaKalghatgi** [comment]
Then why not now?

**Comment by SupriyaKalghatgi** [comment]
*`react-native-scripts` is not recognized as an internal or external command*

This is not NativeBase issue

**Comment by jeromesenyonga** [comment]
I dont know because when i added in the footer component i kept on getting this error
![heade](https://user-images.githubusercontent.com/35918694/45816845-b5223d80-bc91-11e8-9d14-af4c2f13aac8.PNG)

**Comment by H4GEEK** [comment]
Hi first make sure you are using the fast version 
1- use npm install native-base --save
2- npm install
3-npm start
