### ISSUE TITLE
Tabs!

### ISSUE THREAD

**Issue by thundenilla** [GeekyAnts/NativeBase#229]
What are the property for tabs? since i want to change the background color of the tabs and the color of the selected tabs. btw, why cant see any of the labels? 

`<Content style={styles.bottomView}>
          <Tabs>
            <TabOne tabLabel="a"/>
            <TabTwo tabLabel='b'/>
            <TabThree tabLabel='v'/>
            <TabFour tabLabel='f'/>
            <TabFive tabLabel='s'/>
          </Tabs>
        </Content>`

 and can we change the text into icons?

**Comment by ALawliet** [comment]
To change tab colors, you need a custom theme file: http://nativebase.io/docs/v0.5.7/customize#themeTabs

**Comment by smithb1994** [comment]
Copy the theme in your `node_modules/native-base/Components/Themes/light.js` to your working directory. Import that theme into your container like this:  
  
``` Javascript  
import myTheme from './light.js';
...
<Container theme={myTheme}>
   <Header></Header>
   <Content></Content>
</Container>
```  
  
After that, go into that `light.js` file and modify tabBgColor from:  
``` Javascript  
tabBgColor: '#F8F8F8'  
```  
to  
``` Javascript  
get tabBgColor() {  
   return this.toolbarDefaultBg;  
}  
```  
This will make your tabBgColor the same as your toolbarDefaultBg color.

**Comment by SupriyaKalghatgi** [comment]
The default color of Tabs will be updated in next release
