### ISSUE TITLE
Form Floating Label Input

### ISSUE THREAD

**Issue by kgrajan12** [GeekyAnts/NativeBase#2292]
## I have gone through these following points
- []   Check latest documentation: https://docs.nativebase.io/
- []   Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- []   Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- []   Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- []   For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- []   For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

## Issue Description
While making floating label for input is not showing the label in signed apk otherwise it is working

### node, npm, react-native, react and native-base version, expo version if used
"react-native": "0.55.4",
"native-base": "^2.8.0",

### Expected behaviour in Released APK
This Layout is shown with debug apk otherwise like Actual behavior
![input-floating](https://github.com/GeekyAnts/NativeBase-KitchenSink/raw/v2.6.1/screenshots/ios/input-floating.gif)

### Actual behaviour in Released APK
![actual](https://user-images.githubusercontent.com/31614308/45938885-da92ac80-bfed-11e8-919f-067dc4bd35d9.png)

### Is the bug present in both iOS and Android or in any one of them?
It is actually present on Android I don't tried in iOS

### Any other additional info which would help us debug the issue quicker.
`<Card style={styles.Card}>
                        <Form style={styles.Form}>
                            <Item stackedLabel style={[styles.Item, { borderBottomColor: this.state.underLineColor1 }]}>
                                <Label style={[styles.Label, { color: this.state.underLineColor1 }]}>PAN*</Label>
                                <Input
                                onChangeText={(r) => this.setState({ pan: r })}
                                style={styles.Input}
                                onSubmitEditing={() => this.state.pan === '' ? this.setState({ underLineColor1: 'red' }) : null}
                                />
                            </Item>
                            <Item stackedLabel style={[styles.Item, { borderBottomColor: this.state.underLineColor2 }]}>
                                <Label style={[styles.Label, { color: this.state.underLineColor2 }]}>Mobile Number*</Label>
                                <Input
                                onChangeText={(mobileNumber) => this.setState({ mobileNumber })}
                                style={styles.Input}
                                onSubmitEditing={() => this.state.mobileNumber === '' ? this.setState({ underLineColor2: 'red' }) : null}
                                />
                            </Item>
                        </Form>
                    </Card>`

**Comment by SupriyaKalghatgi** [comment]
#2264
