### ISSUE TITLE
When Scan demo NativeBaseKithenSink with Expo ->Error

### ISSUE THREAD

**Issue by romainlouvet** [GeekyAnts/NativeBase#2296]
When I try to scan QR Code in https://nativebase.io/ with Expo -> Sorry, you are not allowed to load "NativeBaseKithenSink".

### Is the bug present in both iOS and Android or in any one of them?
iPhone X, ios 12.0

Thanks :)

**Comment by SupriyaKalghatgi** [comment]
How can you scan for iOS?

**Comment by romainlouvet** [comment]
with Apple camera scan
