### ISSUE TITLE
Add blur() and focus() functions that pass through to the native TextInput

### ISSUE THREAD

**Issue by dkadlecek** [GeekyAnts/NativeBase#2297]
This is a no-brainer, guys. Why haven't you done this earlier? It will take me 5 minutes to submit a PR for this change.

**Comment by SupriyaKalghatgi** [comment]
@dkadlecek Any difficulty with `refs` for this purpose?

**Comment by dkadlecek** [comment]
There isn’t, but why not make your code more elegant and simple?

**Comment by SupriyaKalghatgi** [comment]
Did you read https://docs.nativebase.io/Components.html#ref-components-headref ?

**Comment by dkadlecek** [comment]
Yes, I have. The problem with that documentation is that it does not include an API reference, listing all the methods and properties of the Nativebase components. One has to go to the source code, which is a pain.

Probably will just fork this and start doing these improvements myself.

**Comment by SupriyaKalghatgi** [comment]
Every component is mentioned its replacing React Native component
![image](https://user-images.githubusercontent.com/13464885/45995830-586eba80-c0b7-11e8-9f0e-85b971eec218.png)

There is a separate cheatsheet for this too https://docs.nativebase.io/docs/CheatSheet.html

Then why go to source code?

Why define these methods again at NativeBase level, when it is readily available with React Native?
And why just blur() and focus()? What about other methods of Input component and other NativeBase components? 

Why to reinvent the wheel?

**Comment by dkadlecek** [comment]
Then you should implement all methods of replaced components.

**Comment by SupriyaKalghatgi** [comment]
Probably you are not reading through completely

> Why define these methods again at NativeBase level, when it is readily available with React Native?
> Why to reinvent the wheel?

**Comment by SupriyaKalghatgi** [comment]
There are a lot of components in NativeBase which is a wrapper around React Native. 
We don't want to bloat NativeBase by imitating the same APIs again and that's the reason we expose the ref where you can access the underlying React Native component. 

So, this little change means a change in the philosophy and entire code base of NativeBase.

We have noted this request for considerations in the future.
#38

**Comment by BenWildeman** [comment]
@SupriyaKalghatgi this would make more sense to do as the getRef is not compatible with createRef which came in 16.3. doing what @dkadlecek suggested would mean that you can get rid of the getRef and then people can use ref as normal. meaning there's no deviations from React
