### ISSUE TITLE
Custom Fonts.

### ISSUE THREAD

**Issue by darkrishabh** [GeekyAnts/NativeBase#23]
Since most application try to be unique, adding a way to throw in custom font would be good.

**Comment by sankhadeeproy007** [comment]
Yes, we're thinking of adding a font variable in our theme file. Next release probably.

**Comment by sankhadeeproy007** [comment]
@darkrishabh Custom fonts would require users to manually add the `.ttf` file to xcode and copying them over to a folder in iOS and android respectively. We can put in the font-family variable but I'm afraid it won't be of much use. Waiting for suggestions.

**Comment by steida** [comment]
I believe this is the solution https://github.com/rnpm/rnpm#advanced-usage

**Comment by sankhadeeproy007** [comment]
Fixed with [v0.5.0](https://github.com/GeekyAnts/NativeBase/blob/master/package.json)
