### ISSUE TITLE
Block swiping in Deck Swiper

### ISSUE THREAD

**Issue by GHEMID-Mohamed** [GeekyAnts/NativeBase#2301]
## Issue Description

I want to block swiping in some cases, so I wonder when using `onSwipeLeft` or `onSwipeRight`, is there a way to untrigger swipe listners.
It would be better if there's these props `disableLeftSwipe` `disableRightSwipe`

Thank you

**Comment by HamadaBrest** [comment]
I find this library very interesting, I'll make you a PR soon in order to fix this.

**Comment by maxgfr** [comment]
+1

**Comment by sourabhdadapure** [comment]
@HamadaBrest 
I'm also working on similar kind of issue, let me know if I can help

Thanks!

**Comment by hanykumar** [comment]
Hi @HamadaBrest , it would be grateful, if create PR for this soon.
Thanks
