### ISSUE TITLE
Bug using FooterTab -- Clicking anywhere is executing onPress of the first button

### ISSUE THREAD

**Issue by rodrigolabs** [GeekyAnts/NativeBase#2304]
## Issue Description

I've created a simple screen using the **Icon Footer with Text** snippet following the documentation. When I click anywhere on the screen, it fires the `onPress` of te first `Button` on the `FooterTab`.

### Expected behaviour

Execute `onPress` of a FooterTab Button only when it's really clicked.

### Steps to reproduce

Create a component with only this snippet:

```jsx
<Container>
  <Content />
  <Footer>
    <FooterTab>
      <Button vertical onPress={() => alert('1')}>
        <Icon name='apps' />
        <Text>Apps</Text>
      </Button>
      <Button vertical onPress={() => alert('2')}>
        <Icon name='camera' />
        <Text>Camera</Text>
      </Button>
    </FooterTab>
  </Footer>
</Container>
```
![bug](https://user-images.githubusercontent.com/1905961/46106330-c8ac3780-c1ae-11e8-9f34-0d5555b770aa.gif)

### Is the bug present in both iOS and Android or in any one of them?

I've tested on Ipone 6.

On Iphone X, this bug is apparently not happening.

**Comment by suvenduchhatoi** [comment]
@rodrigolabs 
It seems to be a device issue...
I've tested your code both on Emulator and Simulator...They do behave as expected... But certainly I don't think it's a native-base issue

**Comment by kashmiry** [comment]
I am facing the same issue on iPhone 6 any solution to this or whats causing it?
