### ISSUE TITLE
Adding backgroundColor to ListItem style not showing touch animations.

### ISSUE THREAD

**Issue by venkatmithunk** [GeekyAnts/NativeBase#2305]
## I have gone through these following points
- [x]   Check latest documentation: https://docs.nativebase.io/
- [x]   Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x]   Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [x]   Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [x]   For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- [x]   For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

## Issue Description
I am trying to change ListItem's default backgroundColor from #808080 to #fff. But, I am not able to see touch animation if I do so.

### node, npm, react-native, react and native-base versions
node - 8.10.0
npm - 6.4.1,
react-native - 0.56.0,
react-16.4.1,
native-base-2.8.0

### Expected behaviour
ListItem onPress should show Touchable* animations.

### Actual behaviour
Not showing any touch animations if added background color

### Steps to reproduce
```
<ListItem
        noIndent
        onPress={() =>
          this.props.navigation.navigate ('Channels')}
        style={{
          backgroundColor: '#fff',
          paddingLeft: 4,
          paddingTop: 6,
          paddingBottom: 6,
          fontFamily: 'System',
        }}
      >
        <Body>
           <Text>Hi</Hi>
         </Body>
</ListItem>
```

### Is the bug present in both iOS and Android or in any one of them?
In Android, Not tested on IOS

**Comment by suvenduchhatoi** [comment]
@venkatmithunk 
Issue is not clear...
It's showing Touch animations on press...
May be you are not able to see the animations due to some other error...

**Comment by venkatmithunk** [comment]
@suvenduchhatoi Did you test by keeping the background color white?

**Comment by suvenduchhatoi** [comment]
@venkatmithunk  Yes, I have...

**Comment by SupriyaKalghatgi** [comment]
@suvenduchhatoi Share use case along with output and close this issue

**Comment by suvenduchhatoi** [comment]
```
<ListItem
              noIndent
              onPress={() => alert("ok")}
              underlayColor="#000"
              style={{
                backgroundColor: "#fff",
                paddingLeft: 4,
                paddingTop: 6,
                paddingBottom: 6,
                fontFamily: "System",
              }}
            >
              <Left>
                <Text style={{ color: "#000" }}>Simon Mignolet</Text>
              </Left>
              <Right>
                <Icon name="ios-arrow-forward" />
              </Right>
            </ListItem>
```
@venkatmithunk may be the animation is too dim for you to see... You can use property underlayColor="#000" with the color of your choice and you should be able to see the animation onPress of the ListItem

**Comment by moedeveloper** [comment]
@venkatmithun  did you manage to solve it?
