### ISSUE TITLE
Input not working in release version (Android)

### ISSUE THREAD

**Issue by jmceara** [GeekyAnts/NativeBase#2308]
## I have gone through these following points
- [X]   Check latest documentation: https://docs.nativebase.io/
- [X]   Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [X]   Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [X]   Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- []   For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- []   For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

### node, npm, react-native, react and native-base version, expo version if used
React-native: 0.57.1
React: 16.5.0
Native-base: 2.8.0

### Expected behaviour
Everything works!

### Actual behaviour
Input fields not working, but ONLY in release version. Data are coming from redux data (using persist data). But it's empty on release version (android). In debug mode, everything works as expected.

### Steps to reproduce

Sample item:
```
<ListItem>
              <Item floatingLabel>
                <Label>{translate("sensor_port", { ...i18n_opt })}</Label>
                <Input
                  keyboardType="numeric"
                  value={settings.port.toString()}
                  onChangeText={value => dispatchSetPort(value)}
                />
              </Item>
            </ListItem>
```

### Is the bug present in both iOS and Android or in any one of them?
Can't check on iOS, but it's present in Android (using SDK 26, 27)

### Any other additional info which would help us debug the issue quicker.
Ok (in debug release)
![ok](https://user-images.githubusercontent.com/3300517/46154448-8f75d500-c24b-11e8-8b95-f09d24592017.jpg)

Not OK (release version):
![not_ok](https://user-images.githubusercontent.com/3300517/46154460-9ac90080-c24b-11e8-9fce-5a8643f1f4af.jpg)

I've downgraded to 2.7.2 and everything works!

**Comment by jamesrogers10** [comment]
I'm seeing this issue on iOS, as well.

**Comment by SupriyaKalghatgi** [comment]
#2264
