### ISSUE TITLE
Icon - list of available icons

### ISSUE THREAD

**Issue by rajanlagah** [GeekyAnts/NativeBase#2310]
I have solution for this issue. (developers don't know what are available icons in nativeBase)
http://nativeiconbase.com/ 
here all available icon's images are mapped to the name of icon 
1) choose the icon from all the available icons
2) click on it (clicking will copy the link)
3) paste the link in your code

**Comment by SupriyaKalghatgi** [comment]
What about icons for other font family?

If you read docs, https://docs.nativebase.io/Components.html#icon-def-headref

It has mentioned about a repo that includes icon of various font family https://github.com/GeekyAnts/NativeBase-VectorIconApp
