### ISSUE TITLE
Drawer content color keep dark 

### ISSUE THREAD

**Issue by EasonWang01** [GeekyAnts/NativeBase#2312]
```js
import React from 'react';
import { Container, Drawer, Button, Icon, Content, Text } from 'native-base';

export default class App extends React.Component {
  static navigationOptions = {
    header: null,
  };
  closeDrawer = () => {
    this.drawer._root.close()
  };
  openDrawer = () => {
    this.drawer._root.open()
  };

  render() {
    return (
      <Drawer
        ref={(ref) => { this.drawer = ref; }}
        content={<Content style={{ backgroundColor: '#FFFFFF' }}>
          <Text>Drawer</Text>
        </Content>}>
              <Button onPress={() => this.openDrawer()} transparent>
              <Icon name='menu' />
            </Button>
      </Drawer>
    )
  }
}
```

<img width="461" alt="screen shot 2018-09-28 at 4 47 46 pm" src="https://user-images.githubusercontent.com/11001914/46199421-a0087700-c341-11e8-9dde-453d70b8ca8f.png">

Expect result: Drawer content is light and white color.

**Comment by UKbed990** [comment]
exact same issue here! any answer please...

**Comment by andreslopezdreams** [comment]
I still have the same problem, try zIndex and it does not work either, the only thing I could change is the type to displace

<Drawer type="displace" ...

Node: 8.12.0
Mac OS: Mojave
react-native: 0.57.1
native-base: ^2.8.0

**Comment by ilkka-yli** [comment]
Same issue here!

native-base: ^2.8.0,
react-native: 0.57.1

**Comment by MariaFF** [comment]
The same issue here :/
react-native: 0.57.0,
native-base: 2.8.0

**Comment by grean** [comment]
Same as well
react-native: 0.57.1,
native-base: "^2.8.1

**Comment by suishum** [comment]
Managed to fix this issue by digging into the default properties of the Drawer component, by default the Drawer component's overlay has an elevation property of 8.

The elevation prop only effects Android (which is why this problem is not present in iOS) - to change the default props you can do this:

```
import { Drawer } from 'native-base';
...
Drawer.defaultProps.styles.mainOverlay.elevation = 0;
```
