### ISSUE TITLE
Disabling Fabs android Ripple effect

### ISSUE THREAD

**Issue by aravi365** [GeekyAnts/NativeBase#2313]
## Issue Description
**Cannot disable the android ripple effect for FABs.**

###  npm, react-native, react and native-base version version  used
```
"react": "16.4.1",
"react-native": "0.56.0",
"native-base": "^2.8.0",
```
### Expected behaviour
No ripple effect or changed color of android ripple effect.

### Actual behaviour
Cannot change the FABs android ripple color.

### Steps to reproduce
Tried changing the style and containerStyle of FAB to change the androidRippleEffect.
![2](https://user-images.githubusercontent.com/15327129/46199842-b7d60000-c32d-11e8-875e-7f80d471a5fb.jpeg)

**Comment by akirchmyer** [comment]
I'm also seeing this issue. Is there a way to disable this behavior? I didn't see anything in the documentation.

**Comment by riccardonuzz** [comment]
I'm also trying to remove the ripple effect on the container of the FAB with no success. It should be applied only to the circle.

**Comment by aravi365** [comment]
No update so far! Any workarounds @SupriyaKalghatgi  or anyone

**Comment by YoonjaeYoo** [comment]
This is a workaround.

```
<Fab
    containerStyle={{ borderRadius: 28, overflow: "hidden" }}>
   // inner elements
</Fab>
```

**Comment by allan-simon** [comment]
@YoonjaeYoo  thanks for the workaround, it does the trick for me

**Comment by SupriyaKalghatgi** [comment]
@YoonjaeYoo That does not give the desired output
When Fab is toggled from active to inactive, the button shrink and retains back to usual size

**Comment by allan-simon** [comment]
@SupriyaKalghatgi  yes it's not perfect, but it's at least "pretty-enough" compared to a squarre overflowing , so it's indeed not a fix, but a "better-than-nothing workaround"

**Comment by SupriyaKalghatgi** [comment]
Fixed with commit https://github.com/GeekyAnts/NativeBase/commit/56597c45df1b75e1658b1e049d38e08dbc954e3e

**Comment by allan-simon** [comment]
@sharathprabhal  thanks a lot, can't wait for the bugfix release :)

**Comment by ZarifAhsan** [comment]
itemRippleColor="@null" doesn't seem to work but rippleColor="@null" seem to somewhat help with the issue
