### ISSUE TITLE
DatePicker chosenDate props

### ISSUE THREAD

**Issue by paegle** [GeekyAnts/NativeBase#2315]
Hi guys!

On nativebase 2.8.0, the DatePicker component don't support chosenDate prop.
So I have made a workaround to set my initial choseDate...

Maybe you put verification on componentDidUpdate like others props(defaultDate and disabled) to start state for chosenDate =D

**Comment by n-sviridenko** [comment]
In addition to this, it's impossible to make it fully controlled and having placeholderText specified at the same time:

1. if placeholderText is specified, defaultDate is ignored:
https://github.com/GeekyAnts/NativeBase/blob/master/src/basic/DatePicker.js#L28-L30

2. if it's not specified, you have "Select Date" placeholder:
https://github.com/GeekyAnts/NativeBase/blob/master/src/basic/DatePicker.js#L94-L98

**Comment by n-sviridenko** [comment]
Wrote a workaround if someone needs:
```js
import React from 'react';
import PropTypes from 'prop-types';
import isEqual from 'date-fns/is_equal';
import isDate from 'date-fns/is_date';
import { DatePicker as DatePickerBase } from 'native-base';
import { FormattedDate, FormattedMessage } from 'react-intl';
import messages from './messages';
import styles from './styles';
import xor from '../../../common/xor';

export default class DatePicker extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      key: 0,
    };
  }

  componentWillReceiveProps(nextProps) {
    const { defaultDate } = this.props;
    const { key } = this.state;
    let forceUpdate = false;
    if (isDate(defaultDate) && isDate(nextProps.defaultDate)) {
      forceUpdate = !isEqual(defaultDate, nextProps.defaultDate);
    } else if (xor(isDate(defaultDate), isDate(nextProps.defaultDate))) {
      forceUpdate = true;
    }
    if (forceUpdate) {
      // if the change was triggered by the current component
      if (this.changed) {
        this.changed = false;
      } else {
        this.setState({ key: key + 1 });
      }
    }
  }

  handleDateChange = (value) => {
    const { onDateChange } = this.props;
    this.changed = true;
    if (typeof onDateChange === 'function') {
      onDateChange(value);
    }
  };

  render() {
    const { defaultDate, ...props } = this.props;
    const { key } = this.state;
    return (
      <DatePickerBase
        {...props}
        key={key}
        modalTransparent
        defaultDate={defaultDate}
        onDateChange={this.handleDateChange}
        textStyle={styles.text}
        placeHolderTextStyle={[styles.text, styles.placeholder]}
        formatChosenDate={date => <FormattedDate value={date} month="numeric" day="numeric" year="numeric" />}
        placeHolderText={defaultDate ? undefined : <FormattedMessage {...messages.placeholder} />}
      />
    );
  }
}

DatePicker.propTypes = {
  defaultDate: PropTypes.any, // eslint-disable-line react/forbid-prop-types
  onDateChange: PropTypes.func,
};

DatePicker.defaultProps = {
  defaultDate: null,
  onDateChange: null,
};
```

**Comment by SupriyaKalghatgi** [comment]
https://github.com/GeekyAnts/NativeBase/issues/2409#issuecomment-434572936

**Comment by eniorafael** [comment]
Thank you @n-svridenko. I was struggling into this problem.

**Comment by softMaina** [comment]
I had the same issue, which I solved by upgrading native-base to `  "native-base": "2.11.0",
`

**Comment by hsiaotinghung** [comment]
> In addition to this, it's impossible to make it fully controlled and having placeholderText specified at the same time:
> 
> 1. if placeholderText is specified, defaultDate is ignored:
>    https://github.com/GeekyAnts/NativeBase/blob/master/src/basic/DatePicker.js#L28-L30
> 2. if it's not specified, you have "Select Date" placeholder:
>    https://github.com/GeekyAnts/NativeBase/blob/master/src/basic/DatePicker.js#L94-L98

I was looking everywhere for the solution for this problem. 
Removing the placehodlerText solves my problem of default date not working as expected. 
Thanks!

**Comment by yakuppdurmus** [comment]
get Component ref and **this.refs.refName.**state.choseDate to change set DatePicker text 

`  <DatePicker
          defaultDate={new Date()}
          minimumDate={new Date(2000, 1, 1)}
          maximumDate={new Date(2040, 12, 31)}
          locale={"tr"}
          timeZoneOffsetInMinutes={undefined}
          modalTransparent={false}
          animationType={"fade"}
          androidMode={"default"}
          placeHolderText={"Tarih Seç"}
          textStyle={{ color: "#fff" }}
          placeHolderTextStyle={{ }}
          onDateChange={date => this.setDate(date)}
          disabled={false}
          **ref = "tarihSec"**
          />`



`this.refs.tarihSec.state.chosenDate = new Date(your date);`

**Comment by ManiDeva6** [comment]
> get DatePicker Component ref then this.refs.refName.state.choseDate set new Date
> 
> ```
>  <DatePicker
>           defaultDate={new Date()}
>           minimumDate={new Date(2000, 1, 1)}
>           maximumDate={new Date(2040, 12, 31)}
>           locale={"tr"}
>           timeZoneOffsetInMinutes={undefined}
>           modalTransparent={false}
>           animationType={"fade"}
>           androidMode={"default"}
>           placeHolderText={"Tarih Seç"}
>           textStyle={{ color: "#fff" }}
>           placeHolderTextStyle={{ }}
>           onDateChange={date => this.setDate(date)}
>           disabled={false}
>           ref = "tarihSec"
>           />
> ```
> 
> ```
> 
> this.refs.tarihSec.state.chosenDate = new Date(your date);
> ```
Thanks for saving my entire day
