### ISSUE TITLE
List render issue

### ISSUE THREAD

**Issue by arshadd** [GeekyAnts/NativeBase#2316]
I have seen the issue is closed but I am not able to run plz help

class ProductStore {
@observable featureproducts = [];
ds = new ListView.DataSource({ rowHasChanged: (r1, r2) => r1 !== r2 });

  @computed get dataSource() {
    return this.ds.cloneWithRows(this.featureproducts.slice());
  }

@action fetchFeatureProducts() {
    var url = Config.API_BASE_URL + 'api/v1/product/featureproducts';
    return API.getFeatureProdcutService().then((resp) => {
      if (resp.status) {
        this.setFeatureProduct(resp);
      }
    }).catch((err) => {
      console.log('error',err);
    });
  }

  @action setFeatureProduct(productData) {
    this.featureproducts = productData.data.data;
  }
}
Now for the component

`@Inject( "productStore", "app", "routerActions")
@Observer
class HomePage extends Component {
componentDidMount() {
this.props.productStore.fetchFeatureProducts()

}
render() {

<List
removeClippedSubviews={false}
bounces={false}
directionalLockEnabled={false}
horizontal={true}
showsHorizontalScrollIndicator={false}
dataArray={this.props.productStore.dataSource}
renderRow={item =>
<BannerSlider
imageStyle={styles.bannerSliderImage}
onPress={() => navigation.navigate("ProductList")}
bannerImageText={item.image}
bannerImageSource={item.image}
bannerSmallText={'item.bannerSmallText'}
/>}
/>}
}`

I am using nativebase list which is using listview internally not sure why all the stuff doesn work

Also I have kept
`constructor(props) {
super(props);

const ds = new ListView.DataSource({ rowHasChanged: (r1, r2) => r1 !== r2 });
this.state = {
    DataSource: ds.cloneWithRows(this.props.productStore.featureproducts.slice())
}`
not sure where should I call this.setsate to update changes plz help

**Comment by SupriyaKalghatgi** [comment]
List is deprecated, check docs https://docs.nativebase.io/Components.html#list-def-headref
