### ISSUE TITLE
Tabs/Tab gets very slow on transitions

### ISSUE THREAD

**Issue by faustoct** [GeekyAnts/NativeBase#2317]
Got a very slow performance on Android and iOS when using Tabs with 3 Tab. Which tab contains a FlatList having Text and Images. When touch the tab it gets very slow to switch to another.. Does have any guide or best practice to implement Tabs or improve overall performance using native base?!?

I'm using the libraries

````
    "expo": "^30.0.1",
    "expokit": "1.7.1",
    "moment": "^2.22.0",
    "native-base": "^2.8.0",
    "pusher-js": "^4.2.2",
    "react": "16.3.1",
    "react-native": "https://github.com/expo/react-native/archive/sdk-30.0.0.tar.gz",
    "react-native-device-settings": "^1.2.0",
    "react-native-emoji": "^1.2.0",
    "react-native-fabric": "^0.5.1",
    "react-native-fetch-blob": "^0.10.8",
    "react-native-image-slider": "^2.0.3",
    "react-native-loading-view": "^1.0.0",
    "react-native-onesignal": "^3.1.4",
    "react-native-snap-carousel": "^3.7.2",
    "react-native-text-input-mask": "^0.8.0",
    "react-navigation": "^1.5.11"
````

The same happens with lower versions of NativeBase..

**Comment by matgsan** [comment]
Running in the same problem, if you find a solution please help me https://github.com/GeekyAnts/NativeBase/issues/2314

**Comment by SupriyaKalghatgi** [comment]
#2314
