### ISSUE TITLE
The color of the component tab is not displayed

### ISSUE THREAD

**Issue by Tuideapp** [GeekyAnts/NativeBase#232]
I installed the tab component and are not seeing the colors.

`  <Tabs >
                <Orders tabLabel='Ordenes Disponibles' navigator={this.props.navigator} route={this.props.route} />
                <MyOrders tabLabel='Mis Ordenes' navigator={this.props.navigator} route={this.props.route} />
              [</Tabs>`]

see screenshot  [https://scontent.feoh1-1.fna.fbcdn.net/t31.0-8/14612412_10210471777607819_1097690922552997809_o.jpg](url)

version nativebase v0.5.8

**Comment by kwokhou** [comment]
@Tuideapp Kind of similar issue with https://github.com/GeekyAnts/NativeBase/issues/229, try create a custom theme file.

**Comment by SupriyaKalghatgi** [comment]
@Tuideapp The default color of Tabs will be updated in next release
