### ISSUE TITLE
Warning: Require Cycle

### ISSUE THREAD

**Issue by nobady90** [GeekyAnts/NativeBase#2320]
Hi guys, this is my situation:

react-native: 0.57.1
native-base: 2.8.0

at the start of the app I am alerted to these warnings regarding cycles in DataPicker.js, DefaultTabBar.js and ScrollableTabBar.js:

![image](https://user-images.githubusercontent.com/36473359/46278558-c1967800-c566-11e8-80e9-1b3601260e2b.png)

are you already aware of it?
Thank's a lot!

**Comment by kigawas** [comment]
FYI:

```
Require cycle: node_modules/native-base/dist/src/index.js -> node_modules/native-base/dist/src/basic/DatePicker.js -> node_modules/native-base/dist/src/index.js

Require cycle: node_modules/native-base/dist/src/index.js -> node_modules/native-base/dist/src/basic/Tabs/index.js -> node_modules/native-base/dist/src/basic/Tabs/DefaultTabBar.js -> node_modules/native-base/dist/src/index.js

Require cycle: node_modules/native-base/dist/src/index.js -> node_modules/native-base/dist/src/basic/Tabs/index.js -> node_modules/native-base/dist/src/basic/Tabs/ScrollableTabBar.js -> node_modules/native-base/dist/src/index.js
```

**Comment by kigawas** [comment]
@SupriyaKalghatgi Would you please have a look on this?

**Comment by webdevsyd** [comment]
<img width="291" alt="screen shot 2018-10-06 at 5 33 08 pm" src="https://user-images.githubusercontent.com/15810023/46569863-eb4c0680-c98d-11e8-8c74-4c3d70b0a463.png">

I'm also encountering this

**Comment by nobady90** [comment]
any news Guys?

**Comment by MehdiDonk** [comment]
+1 
I have the same issue with the same three modules: DatePicker, DefaultTabBar, ScrollableTabBar.

**Comment by zzzeee** [comment]
+1

**Comment by sagarguhe** [comment]
+1

**Comment by bertacume** [comment]
+1

**Comment by thu-san** [comment]
+1

**Comment by tiagolpadua** [comment]
+1

**Comment by bingimar** [comment]
+1

**Comment by sajaddp** [comment]
?

**Comment by woraponprathuangthip** [comment]
i found it same

**Comment by stewartduffy** [comment]
No updates?

**Comment by danverde** [comment]
+1

**Comment by bartello1982** [comment]
+1

**Comment by ardyfeb** [comment]
+1

**Comment by ranneyd** [comment]
https://github.com/GeekyAnts/NativeBase/pull/2459

Everyone check this out

**Comment by diegolaciar** [comment]
+1
