### ISSUE TITLE
Is it a mistake?

### ISSUE THREAD

**Issue by omi10859** [GeekyAnts/NativeBase#2321]
![screenshot 2018-10-01 at 1 59 39 pm](https://user-images.githubusercontent.com/26123416/46277913-55c20880-c582-11e8-8bf3-abdfc74c810a.png)
that br/>  there is by mistake? 

Sorry for not following issue template. Also I'm not sure if this is the right place to report such things

**Comment by SupriyaKalghatgi** [comment]
https://github.com/GeekyAnts/native-base-docs/issues/132
