### ISSUE TITLE
TabHeading doesn't support testID

### ISSUE THREAD

**Issue by kaitlynbrown** [GeekyAnts/NativeBase#2326]
## I have gone through these following points
- [x]   Check latest documentation: https://docs.nativebase.io/
- [x]   Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x]   Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [x]   Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [x]   For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- [x]   For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

## Issue Description
When I try to use a custom `TabHeading` with a `testID` set, that `testID` is not passed through to the React Component (in fact, it looks like NativeBase just throws away the `TabHeading` provided and wraps its children in a new one for some reason)

There also doesn't seem to be any way to set a `testID` on a `Toast`.

### Expected behaviour
A `testID` I pass to `TabHeading` should be included on the React Component
### Actual behaviour
The `testID` is not included on the React Component and cannot be used to locate the tab in tests
### Steps to reproduce
- Create a screen with at least one Tab on it, and specify the `testID` for the tab's header:
```
import { Container, Header, Tabs, Tab, TabHeading, Text, Content, Body, Title } from "native-base";

export default () => (
    <Container>
      <Header hasTabs>
        <Body>
          <Title>Tab testID</Title>
        </Body>
      </Header>
      <Tabs>
        <Tab
          heading={() => (
            <TabHeading testID="TestTab">
                <Text>Test</Text>
            </TabHeading>
          )}
        >
          <Content>
            <Text>Content</Text>
          </Content>
        </Tab>
      </Tabs>
    </Container>
)
```
- Examine the TabHeading component in React Native Debugger. Note that its props does not include a `testID`
- From a calabash console, run `query("* tag:'TestTab'")`. Note that no results are returned
- Note that if you add a `testID` to another component (such as the `Container`), you will see it in the component's props in React Native Debugger, and you will be able to query for it in the Calabash console

### Is the bug present in both iOS and Android or in any one of them?
Only tested on Android, but it looks like it would happen on iOS as well

### Any other additional info which would help us debug the issue quicker.
See the `renderTab` method in `DefaultTabBar.js` and `ScrollableTabBar.js`:
```
  renderTab(
    name,
    page,
    isTabActive,
    onPressHandler,
    tabStyle,
    activeTabStyle,
    textStyle,
    activeTextStyle,
    tabHeaderStyle
  ) {
    const headerContent =
      typeof name !== "string" ? name.props.children : undefined;
    const { activeTextColor, inactiveTextColor } = this.props;
    const textColor = isTabActive ? activeTextColor : inactiveTextColor;
    const fontWeight = isTabActive ? "bold" : "normal";
    if (typeof name === "string") {
      return (
        <Button
          style={{ flex: 1 }}
          key={name}
          onPress={() => onPressHandler(page)}
        >
          <TabHeading
            style={isTabActive ? activeTabStyle : tabStyle}
            active={isTabActive}
          >
            <Text style={isTabActive ? activeTextStyle : textStyle}>
              {name}
            </Text>
          </TabHeading>
        </Button>
      );
    } else {
      return (
        <Button
          style={{ flex: 1 }}
          key={_.random(1.2, 5.2)}
          onPress={() => onPressHandler(page)}
        >
          <TabHeading style={tabHeaderStyle} active={isTabActive}>
            {headerContent}
          </TabHeading>
        </Button>
      );
    }
  },
```
As you can see, if a component is passed in, it simply takes that component's children and wraps it in a new `TabHeader`, completely ignoring the one that was passed in.

**Comment by kaitlynbrown** [comment]
I'd like to add that the `Button` component also doesn't seem to support testID

**Comment by mowbell** [comment]
I agree, for the moment I put testID on tab's heading content
```js
            <TabHeading style={styles.tabStyle}>
              <Text testID="historyTab" style={styles.tabText}>
              My History
              </Text>
            </TabHeading>
```

**Comment by SupriyaKalghatgi** [comment]
#2466
