### ISSUE TITLE
crash release build on iOS.

### ISSUE THREAD

**Issue by mosleim** [GeekyAnts/NativeBase#2327]
## I have gone through these following points
- [X]   Check latest documentation: https://docs.nativebase.io/
- [X]   Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [X]   Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [X]   Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- []   For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- []   For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

### node, npm, react-native, react and native-base version, expo version if used
```
  "dependencies": {
    "@babel/runtime": "^7.1.2",
    "native-base": "^2.8.0",
    "react": "16.5.0",
    "react-native": "0.57.1",
    "react-native-charts-wrapper": "^0.4.8",
    "react-navigation": "^2.17.0"
  }
```

### Expected behaviour
aplication not crash. same as debug build.
### Actual behaviour
mu output release crash when a page have a NativeBase componen.
### Steps to reproduce

1. init a new project
2. install native-base
3. update App.js
```
import React, { Component } from 'react';
import { Container, Button, Text } from 'native-base';
export default class GeneralExample extends Component {
  render() {
    return (
      <Container>
        <Button>
          <Text>
            Button
          </Text>
        </Button>
      </Container>
    );
  }
}

```
4. run release for iOS
5. klik the button. and aplication will be crashed.

### Is the bug present in both iOS and Android or in any one of them?
i just test on iOS.

**Comment by SupriyaKalghatgi** [comment]
@mosleim I couldn't reproduce your issue
Can you create a test repo for this?

I will keep this issue open for this week
