### ISSUE TITLE
<Item/> is broken in release builds with react-native 0.57

### ISSUE THREAD

**Issue by ajmath** [GeekyAnts/NativeBase#2328]
## I have gone through these following points
- [X]   Check latest documentation: https://docs.nativebase.io/
- [X]   Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [X]   Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [X]   Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [X]   For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- [X]   For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

### node, npm, react-native, react and native-base version, expo version if used
```
  React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: x64 Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz
      Memory: 1.65 GB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.10.0 - ~/.nvm/versions/node/v8.10.0/bin/node
      Yarn: 1.7.0 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v8.10.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.0, macOS 10.14, tvOS 12.0, watchOS 5.0
      Android SDK:
        Build Tools: 23.0.1, 25.0.2, 25.0.3, 26.0.3, 27.0.3, 28.0.0, 28.0.0, 28.0.1
        API Levels: 23, 25, 26, 27, 28
    IDEs:
      Android Studio: 3.1 AI-173.4819257
      Xcode: 10.0/10A255 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.5.0 => 16.5.0
      react-native: 0.57.1 => 0.57.1
      native-base: ^2.8.0 => 2.8.0
    npmGlobalPackages:
      create-react-native-app: 2.0.2
      react-native-cli: 2.0.1
```
### Expected behaviour
Components have the same behavior in dev and release builds
### Actual behaviour
Release builds are exhibiting various feature breaking issues that aren't present in debug builds. The following errors have been observed and reproduced when using native-base components.

* The <Input/> element does not honor secureTextEntry or onChangeText props
* The <Item/> element does not honor the floatingLabel prop
### Steps to reproduce
* Clone repository at https://github.com/ajmath/ReleaseRenderIssue
* `yarn install`
* `yarn react-native run-android` to test the dev build
* `yarn react-native run-android --variant=release` to test the release build

Screenshots are available in the readme at https://github.com/ajmath/ReleaseRenderIssue

### Is the bug present in both iOS and Android or in any one of them?
Both iOS and Android

### Any other additional info which would help us debug the issue quicker.
This issue is also being tracked in https://github.com/facebook/metro/issues/277

A similar issue was reported by slack user @blue_mask_ https://nativebase.slack.com/archives/C25STJTNK/p1537937946000100

**Comment by SupriyaKalghatgi** [comment]
#2264
