### ISSUE TITLE
Not all FontAwesome icons available

### ISSUE THREAD

**Issue by GitHubGreg** [GeekyAnts/NativeBase#2329]
Only some FontAwesome icons seem to work. 

For example, this works:
`<Icon type="FontAwesome" name="user-plus">`

This doesn't work:
`<Icon type="FontAwesome" name="user-friends">`

Is this because some FontAwesome icons are not included with native base? Is there a way to manually include them? Thanks.

**Comment by nobady90** [comment]
For information, are you trying to insert in the sidebar or on a screen?

**Comment by GitHubGreg** [comment]
On a screen

**Comment by nobady90** [comment]
Yes, I also tried "user-friends" and did not recognize the icon.
I asked you if you try on screen or on sidebar because I saw that the icons inside the sidebar are different from those that are used in the screens.
we are waiting for an answer at this point.

**Comment by SupriyaKalghatgi** [comment]
React Native Vector Icons in NativeBase is on version 4.6.0
And the icon `user-friends` is with React Native Vector Icons v5.0.0

Thats actually inappropriate query
Stay tuned on  #2290 and #2351
