### ISSUE TITLE
How to make scene FloatFromBottom?

### ISSUE THREAD

**Issue by mdmush** [GeekyAnts/NativeBase#233]
Hey,

I was using NativeBase and it is so cool but i'm not able to change configureScene for one particular route. I want to make one of my scene to pop from bottom whenever i call it.
Please reply ASAP.

Thanks.

**Comment by SupriyaKalghatgi** [comment]
@mdmush You can refer React Native [Navigator](https://facebook.github.io/react-native/docs/navigator.html#props) for transitions.
