### ISSUE TITLE
Input Error

### ISSUE THREAD

**Issue by mreorhan** [GeekyAnts/NativeBase#2330]
There have a problem.
My dependencies: 

```
"expo": "^30.0.1",
    "native-base": "^2.8.0",
    "react": "16.3.1",
    "react-native": "https://github.com/expo/react-native/archive/sdk-30.0.0.tar.gz",
```
No data is coming into the inputs. This issue occurs when I publish it as an apk. The contents of the input are changing. But when I print the data on the screen, it comes undefined.

Besides, labels does not come.

My code is like that:

```
 <Item>
              <Label style={styles.colorWhite}>usernameorEmail</Label>
              <Input style={styles.colorWhite} onChangeText={(username) => this.setState(state=>({data:{...state.data,username}}))} value={this.state.data.username}/>
            </Item>
```

**Comment by SupriyaKalghatgi** [comment]
[2.8.1](https://github.com/GeekyAnts/NativeBase/releases/tag/v2.8.1)

**Comment by mreorhan** [comment]
> [2.8.1](https://github.com/GeekyAnts/NativeBase/releases/tag/v2.8.1)

there is no problem in this version.
But the placeholder comes down to the bottom.

**Comment by SupriyaKalghatgi** [comment]
https://github.com/GeekyAnts/NativeBase/blob/master/ISSUE_TEMPLATE.txt
