### ISSUE TITLE
TextArea - Options like (Select|Copy|Paste) not translated

### ISSUE THREAD

**Issue by bemazo** [GeekyAnts/NativeBase#2334]
hi all,

I use inside my form the TextArea Element, but on our german iPhones the options like (Select|Copy|Paste) are not translated, how can I manage it?

Thanks,
Ben

**Comment by SupriyaKalghatgi** [comment]
https://github.com/GeekyAnts/NativeBase/blob/master/ISSUE_TEMPLATE.txt
