### ISSUE TITLE
Can't change text color in Action Sheet

### ISSUE THREAD

**Issue by alokrajzeta** [GeekyAnts/NativeBase#2337]
Is there a way to change the text color in ActionSheet, or the background color of ActionSheet?

This is the **options** array that I pass to the ActionSheet

`
[
{ text: 'Camera', icon: 'camera', iconColor: 'green' }, 
{ text: 'Gallery', icon: 'image', iconColor: 'violet'}, 
{text: 'Cancel', icon: 'close', iconColor: 'red'}
]
`
For my purposes I have changed the text color to white in entire app, which results in this (white text on white background)

![image](https://user-images.githubusercontent.com/28848007/46596003-c17b0880-ca8f-11e8-8d12-a9edf5b1c141.png)

I didn't find any way to either change the background color of ActionSheet, or the text color of options.

**Comment by SupriyaKalghatgi** [comment]
#1231

**Comment by SupriyaKalghatgi** [comment]
#2084
