### ISSUE TITLE
[Picker] On landscape when go to back rotate 180 deg

### ISSUE THREAD

**Issue by lmichailian** [GeekyAnts/NativeBase#2339]
## Issue Description
On ipad 2 Air 12.0
"native-base": "^2.7.0",
"react": "16.3.1",
"react-native": "~0.55.2",

### Expected behaviour

Using Picker on ipad air 2 landscape when select picker and return back the orientation direction must be the same.

### Actual behaviour

The orientation is the same but the  direction change

### Steps to reproduce

```
<Picker
    selectedValue={this.state.language}
    onValueChange={(itemValue, itemIndex) => this.setState({ language: itemValue })}>
    <Picker.Item label='Java' value='java' />
          <Picker.Item label='JavaScript' value='js' />
</Picker>
````

https://www.useloom.com/share/d9705b9703e0458db46992cb085136c0

**Comment by SupriyaKalghatgi** [comment]
@lmichailian Fixed with commit https://github.com/GeekyAnts/NativeBase/commit/613023b55a9aec8ff7c90da302b2219480f0c29b

Also available on `master`
