### ISSUE TITLE
ScrollView within Content

### ISSUE THREAD

**Issue by smithb1994** [GeekyAnts/NativeBase#234]
ScrollView doesn't work within Content because Content is a ScrollView itself. Scrolling functionality takes precedence to Content rather than the ScrollView within Content.

Proposed solution: 
- Make Content a View, rather than a ScrollView.  

Similar issue at #177

**Comment by sankhadeeproy007** [comment]
Use `scrollEnabled={false}` with `<Content>`

**Comment by smithb1994** [comment]
@sankhadeeproy007 this is not a solution. This will disable scroll for all sub views as well. What we want is the scroll to be set for the ScrollView within Content. Which isn't possible when Content is a ScrollView.

**Comment by alvelig** [comment]
@smithb1994 I replaced Tabs element with https://github.com/aksonov/react-native-tab, put it in the header and fell totally happy.

**Comment by raarts** [comment]
I think we need a ContentNoScroll component.

**Comment by raarts** [comment]
@alvelig the correct link is https://github.com/aksonov/react-native-tabs

**Comment by Nvelu048** [comment]
This worked for me
    `<Content contentContainerStyle={{flex:1}}>`

**Comment by thobiasn** [comment]
@Nvelu048 @sankhadeeproy007 What is the point of using a content element if we are disabling scrolling? Isn't this the whole point of the element in the first place?
