### ISSUE TITLE
Simplification of theming process

### ISSUE THREAD

**Issue by nakulgulati** [GeekyAnts/NativeBase#2341]
This is more of a question and feature improvement than an issue. 

While going through the the Native Base docs regarding the theming section, I noticed that the theming process isn't as easy as one would expect. 

There are use cases where a developer might want to retain all the styling Native Base provides but only modify the theme colours or margins. These use cases should ideally be as easy as to override a few variables. 

Some of the other frameworks like Ionic do precisely that [link](https://ionicframework.com/docs/theming/theming-your-app).

I would appreciate if Native Base provided their thoughts around this and in fact I would love to help implement such functionality if it sounds like a valuable add-on.

**Comment by SupriyaKalghatgi** [comment]
About the Ionic link you shared

```
$colors: (
  primary:    #488aff,
  secondary:  #32db64,
  danger:     #f53d3d,
  light:      #f4f4f4,
  dark:       #222,
  twitter: (
    base: #55acee,
    contrast: #ffffff
  )
);
```

and using this in any other theme variable, as this
```
my-component {
  background: color($colors, twitter, base);
}
```

The same is also available with NativeBase
![image](https://user-images.githubusercontent.com/13464885/47770521-bb322200-dd05-11e8-9bea-288fff2ad864.png)

And this is used across components, like
```
  get btnPrimaryBg() {
    return this.brandPrimary;
  }
```

**Comment by SupriyaKalghatgi** [comment]
Also this is discussion topic, so you can make use of NativeBase slack (#customize, #tutorials) for this purpose
