### ISSUE TITLE
<List> is rendering single data in array in partition?

### ISSUE THREAD

**Issue by manojkumawat003** [GeekyAnts/NativeBase#2343]
I have an array that has single value. I am rendering array using <List>. 
I know you have a question that i should not use array for single value. But my function is like this that array list may increase.
What happen if I have single data in array?

Example-
state = {
 emails:[]
}
here in array email,  i have only single value yet 
example : abc@gmail.com

When i render it using <List>
this show me input like this- (every alphabet in new line)
a
b
c
@ 
g
m
a
i
l
.
c
o
m

Plz give me solution how to render this in one line.

I am using React native and latest version on native base for android project

**Comment by SupriyaKalghatgi** [comment]
https://github.com/GeekyAnts/NativeBase/blob/master/ISSUE_TEMPLATE.txt

Docs: https://docs.nativebase.io/Components.html#list-def-headref
![image](https://user-images.githubusercontent.com/13464885/46669991-9529ce00-cbee-11e8-8569-5aec7a7b83d1.png)
