### ISSUE TITLE
[Checkbox] [Android] "transparent" tick / alpha values not working in React Native 0.57.2

### ISSUE THREAD

**Issue by rreina** [GeekyAnts/NativeBase#2344]
## I have gone through these following points
- [X]   Check latest documentation: https://docs.nativebase.io/
- [X]   Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x]   Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [X]   Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-

## Issue Description

Libs version:
=========
Node: 8.11.2
npm: 6.4.1
react-native: 0.57.2
react: 16.5.2
native-base: 2.8.1
I'm not using expo.

### Expected behaviour
Checkbox tick is transparent when unchecked.
<img width="409" alt="screenshot 2018-10-09 at 14 34 18" src="https://user-images.githubusercontent.com/3082477/46669976-343fcd00-cbd1-11e8-90f0-6b2c1e7fa2ec.png">

### Actual behaviour
Checkbox tick is visible. Changing NativeBase exported variables don't fix it.
<img width="377" alt="screenshot 2018-10-09 at 14 14 09" src="https://user-images.githubusercontent.com/3082477/46669965-2b4efb80-cbd1-11e8-8930-54581fe2b09b.png">

### Steps to reproduce

Add CheckBox native-base component:
`                   
 <CheckBox
      onPress={() => { return; }
      checked={this.state.isChecked}
 />
`

### Is the bug present in both iOS and Android or in any one of them?
Android only.

### Any other additional info which would help us debug the issue quicker.
Proposed fix:
Include 'textShadowRadius: 0' in 'react-native-vector-icons' style property
File: Checkbox.js line 41
`
<IconNB
    style={{
    ...
	textShadowRadius: 0
    }}
/>
`

There is an open discussion about the issue in 'react-native-vector-icons':
https://github.com/oblador/react-native-vector-icons/issues/863
This is the proposed fix for the time being.
Thanks for your time.

**Comment by rreina** [comment]
Added proposed PR #2345 
https://github.com/GeekyAnts/NativeBase/pull/2345

**Comment by murtraja** [comment]
Please can someone suggest any workarounds for this? I have to release a build and this issue is marked as must fix :)

**Comment by rreina** [comment]
You can meanwhile compile the fixed version of NativeBase 2.8.1 from our fork by adding the dependency like this in 'package.json':
    "native-base": "git+https://github.com/rreina/NativeBase.git#87da1cca83f30289baffb6a65e1f033b5b6da973",

**Comment by SupriyaKalghatgi** [comment]
Fixed with commit https://github.com/GeekyAnts/NativeBase/commit/4e4450e3927a19f4d13b5d4e70d26cf6ac997877

Also available on `master`

**Comment by OtacilioN** [comment]
Hey, Folks @rreina @SupriyaKalghatgi I think we are facing the same problem on 0.57.5, have you noticed this?

**Comment by OtacilioN** [comment]
Hey Folks, 

Now I checked that this fix is not already released, temporally I changed my package.json to import 
```    "native-base": "git+https://github.com/GeekyAnts/NativeBase.git#e96c997492d898d812243d7f19297189c75af4c0",``` 

But would be awesome to have this amazing fix released, so what do you think @SupriyaKalghatgi ? Would be great having a v2.8.2 patch with this fix.
