### ISSUE TITLE
Problem with TypeScript 3.1.1 and style properties

### ISSUE THREAD

**Issue by andreialecu** [GeekyAnts/NativeBase#2346]
There is a type error in the new TypeScript 3.1.1 with all native-base Component `style` properties:

```
Type 'RegisteredStyle<ViewStyle | TextStyle | ImageStyle>' is not assignable to type 'ViewStyle | ViewStyle[]'.
  Type 'RegisteredStyle<ViewStyle | TextStyle | ImageStyle>' is not assignable to type 'ViewStyle[]'.
    Property 'length' is missing in type 'Number & { __registeredStyleBrand: ViewStyle | TextStyle | ImageStyle; }'.
```

I think #2123 would be a potential fix for this.

Noticed this because 3.1.1 is now the default version shipping with the update to VS Code. Changing typescript back to 3.0.3 gets rid of this error.

**Comment by ScreamZ** [comment]
+1

**Comment by gonzalobustos** [comment]
I'm experiencing the same issue when trying to apply some styles to _Content_:

`
<Content contentContainerStyle={styles.content}>
`

Using this dependencies:

```
"native-base": "^2.8.1",
"react": "16.6.0-alpha.8af6728",
"react-native": "0.57.4",
"typescript": "^3.1.3"
```

**Comment by burtek** [comment]
Same here. Would be nice to have that fixed

**Comment by SupriyaKalghatgi** [comment]
#2562
