### ISSUE TITLE
Unable to use textAreaTheme after ejecting

### ISSUE THREAD

**Issue by harzkr** [GeekyAnts/NativeBase#2347]
Hi,
I was trying to customise text area component after ejecting. I put `textAlignVertical:'center'` instead of the `'top'` in the `'native-base-theme/components/Textarea.js'` and imported `'textAreaTheme'`
into the Component where I was using the `<Textarea>`. I wrapped my `<Textarea>` component like this inside `<StyleProvider>` like this :  
`<StyleProvider style={textAreaTheme()}>
  <Textarea>...</Textarea>
</StyleProvider>`

but wasn't able to see any changes, the text in the textarea remains vertically at top.

Am I missing something, I followed the example in the official docs for button theme custom application
[https://docs.nativebase.io/Customize.html#customize-button-headref](url)
Am I missing something or doing anything wrong? Could you help?

And by the way, awesome package in many aspects, love using it for almost all my react native apps!

Thanks

**Comment by SupriyaKalghatgi** [comment]
@harzkr Did you find this working?

**Comment by harzkr** [comment]
No, this was not working as of yet.
 For my use of `textarea` I have switched over to the basic package from React Native itself. It has a ,increase the lines as per content of the box, which was more suited to my usage. 

The theme method though, its not working

**Comment by suvenduchhatoi** [comment]
@harzkr 
The 'textAlignVertical' is exclusive for Android...Should work fine on Android...

**Comment by SupriyaKalghatgi** [comment]
@suvenduchhatoi Share use case along with output and close this issue

**Comment by suvenduchhatoi** [comment]
@harzkr 
In your App.js file write the following code
```
import React, { Component } from "react";
import {
  Container,
  Header,
  Content,
  Text,
  Button,
  StyleProvider,
  Card,
  CardItem,
  Body,
  Left,
  Right,
  Title,
  View,
  Button,
  Textarea,
} from "native-base";

import textAreaTheme from "./native-base-theme/components";

export default class CardThemeExample extends Component {
  render() {
    return (
      <StyleProvider style={textAreaTheme()}>
        <Textarea style={{ backgroundColor: "#979797" }} />
      </StyleProvider>
    );
  }
}
```
and inside native-base-theme/components/Textarea.js
set the property textAlignVertical: "center"

![screenshot 2018-12-19 at 4 56 36 pm](https://user-images.githubusercontent.com/44160581/50217749-9ece6f80-03af-11e9-8743-6da02ad546b8.png)

**Comment by harzkr** [comment]
Thanks @suvenduchhatoi 
I was doing the same thing, but for some reason, it was not working for iOS

You can close this issue, I
