### ISSUE TITLE
tabstyle not working when add component in heading props

### ISSUE THREAD

**Issue by abdil1234** [GeekyAnts/NativeBase#2349]
```
<Tabs tabBarPosition="bottom" tabBarUnderlineStyle={{borderBottomColor:"#f2f2f2"}}>
          <Tab 
            heading={ <TabHeading><Icon name="home" /></TabHeading>}
            tabStyle={{backgroundColor: '#f2f2f2'}}
            textStyle={{ color: 'red', fontSize: 12 }}
            >
            <Content padder>          
              <Card transparent>
                <Text>Selamat Datang </Text>
              </Card>

              <View>
                  <View style={styles.card} />
              </View>
          </Content>
          </Tab>
          <Tab             
            heading={ <TabHeading ><Icon name="camera" /></TabHeading>}
            tabStyle={{backgroundColor: '#f2f2f2'}}
            textStyle={{ color: 'red', fontSize: 12 }}
            >
            
            <Text> Tab 1</Text>
          </Tab>
          <Tab 
            heading={ <TabHeading ><Icon name="person" /></TabHeading>}
            tabStyle={{backgroundColor: '#f2f2f2'}}
            textStyle={{ color: 'red', fontSize: 12 }}
            >
            <Text> Tab 1</Text>
          </Tab>
        </Tabs>
```
![native](https://user-images.githubusercontent.com/31970269/46749464-fc737b00-ccdf-11e8-8684-f5c2a9c7d48e.PNG)

Device : Android 7.1.2

**Comment by dengue8830** [comment]
i have the same problem, i can't get the icon colored with active style, it's always white

![image](https://user-images.githubusercontent.com/5104213/51428346-6786f480-1be1-11e9-9116-0d4d8ca47ba5.png)

![image](https://user-images.githubusercontent.com/5104213/51428351-78376a80-1be1-11e9-813e-019787d147d0.png)

**Comment by dengue8830** [comment]
i fixed it in this hacky way

![image](https://user-images.githubusercontent.com/5104213/51428503-50e19d00-1be3-11e9-9d18-301d1460a648.png)

**Comment by suvenduchhatoi** [comment]
@abdil1234 , as @dengue8830 suggested using style inside 'TabHeading' should work at the moment,  ![screen shot 1440-06-02 at 5 29 00 pm](https://user-images.githubusercontent.com/44160581/52410555-a46a4b00-2afe-11e9-90dd-826793c7b496.png) but yes, we will look into this

**Comment by SupriyaKalghatgi** [comment]
Please refer Docs for tabs
https://docs.nativebase.io/Components.html#tabs-def-headref
