### ISSUE TITLE
Card and List

### ISSUE THREAD

**Issue by thundenilla** [GeekyAnts/NativeBase#235]
for the childview for both carditem and listItem, is there way to add to icon in one carditem? ei, 1 icon on the left side, and 1 more icon for drop down function on the right. ?

**Comment by thundenilla** [comment]
nevermind. found it.

**Comment by SupriyaKalghatgi** [comment]
@thundenilla This has been documented - [List Icon](http://nativebase.io/docs/v0.5.9/components#listIcon)
This is applicable for `Cards` as well
