### ISSUE TITLE
fontSize when focus Item with floatingLabel

### ISSUE THREAD

**Issue by shiftrtech** [GeekyAnts/NativeBase#2356]
## I have gone through these following points
- [x]   Check latest documentation: https://docs.nativebase.io/
- [x]   Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x]   Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [x]   Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [ x]   For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- [ x]   For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

## Issue Description

Im trying to pass the "fontSize: 12" style to <Item floatingLabel> when is focused but nothing happens

### node, npm, react-native, react and native-base version, expo version if used

node -v "10.9.0"
npm "6.4.1"
react-native: "0.57.2",
react: "16.5.0",
native-base: "2.8.1",

### Expected behaviour

Label changed FontSize when focus

### Actual behaviour

Label FontSize doesnt change

### Steps to reproduce

<Item floatingLabel style={this.stylesItem({fontSize: 12})}>

### Is the bug present in both iOS and Android or in any one of them?

Android

### Any other additional info which would help us debug the issue quicker.

none

**Comment by SupriyaKalghatgi** [comment]
https://github.com/GeekyAnts/NativeBase/issues/1964
