### ISSUE TITLE
Spinner is not showing up on device (Samsung Galaxy Note 4)

### ISSUE THREAD

**Issue by rameshkannank** [GeekyAnts/NativeBase#2357]
## Issue Description
Spinner is working fine in Android Emulator. But when I installed it on Samsung Galaxy Note 4 it does not show up.

### node, npm, react-native, react and native-base version, expo version if used
React Native Environment Info:
System:
OS: Windows 10
CPU: x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
Memory: 7.73 GB / 15.88 GB
Binaries:
Yarn: 1.9.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
npm: 5.6.0 - C:\Program Files\nodejs\npm.CMD
IDEs:
Android Studio: Version 3.1.0.0 AI-173.4907809

Device Android Version 6.0.1
Emulator Android Version: 8.1.0

+-- native-base@2.8.0
+-- react@16.5.0
`-- react-native@0.57.1

### Expected behaviour
Spinner component show show up on device.
### Actual behaviour
Spinner component shows up on emulator not on device (Samsung Galaxy Note 4)

### Steps to reproduce
Code:
**LoadingStoreScrn.js**

import React from 'react';
import * as nb from 'native-base';

export default class LoadingStoreScrn extends React.Component {
  render() {
    return (
      <nb.Container>
        <nb.Content>
        <nb.Text>Loading...</nb.Text>
        <nb.Spinner />
        </nb.Content>
      </nb.Container>
    );
  }
}

**App.js**
import React, { Component } from 'react';
import { StyleProvider, Root } from 'native-base';
import LoadingStoreScrn from './screens/LoadingStoreScrn';
import getTheme from './themes/components';
import Bmp from './themes/variables/bmp';

type Props = {};

export default class App extends Component<Props> {
  render() {
    return (
      \<StyleProvider style={getTheme(Bmp)} >
      \<Root>
      \<LoadingStoreScrn />
      \</Root>
      \</StyleProvider>
    );
  }
}

### Is the bug present in both iOS and Android or in any one of them?
Not yet tested on iOS

### Any other additional info which would help us debug the issue quicker.
None

**Comment by SupriyaKalghatgi** [comment]
In that case, can you try React Native `ActivityIndicator` on same device?

**Comment by SupriyaKalghatgi** [comment]
Closing the issue due to inactivity
You can reopen this issue anytime

**Comment by zoolyka** [comment]
Just faced a similar issue on a Galaxy Note10 with latest RN, after hours of debugging was able to figure out what caused it. If UI animations are turned off in Android accessibility settings then it wont display the spinner component at all.

![SmartSelect_20210923-174154_Accessibility](https://user-images.githubusercontent.com/4547445/134540061-dd875392-8fcb-428b-b2b6-ce17d28a7e34.jpg)
