### ISSUE TITLE
[Feature Request] Better use of Ionicons by specific platform

### ISSUE THREAD

**Issue by italomlp** [GeekyAnts/NativeBase#2361]
Hi everyone from NativeBase comunity!

I'm new in Github contributing for third party repositories, of frameworks that I use. But I want to start. So, one request that I think will be useful in NativeBase is a way for better use of Ionicons. The intuit of Ionicons is to be an "universal" icon pack for Android and iOS. So, all the icons - except for the logo icons - has the same name with system prefix (e.g. the home icon for Android: "md-home"; and for iOS: "ios-home"). But, if we want the icons for specific platforms, we have to write: `<Icon android="md-home" ios="ios-home" />`, since if we write with "name" prop, the Icon component will render the same for both platforms.

So, what I think is to addapt the Icon component of NativeBase to get only the "name" of icon without prefixes when the font choosed is Ionicons, and render properly icon. 

Eg:

Rather than write: `<Icon android="md-home" ios="ios-home" />`
Write: `<Icon name="home" />`

So the NativeBase Icon component will render properly icon, based on Ionicons, that is the default font.

And for logo icons: `<Icon name="logo-google" />`

I think it is helpful for the purposes of NativeBase. I have in mind what is to be done, but want opinions and suggestions. I'm forking the repository to work on it and submit a pull request soon as possible.

PS: I write my own component for this purposes, but I think it is useful to be present by default in NativeBase.

**Comment by italomlp** [comment]
So, I was analyzing the code of NativeBase Icon, and see that it is already implemented. It would be great if include it explicitly in the docs.

**Comment by SupriyaKalghatgi** [comment]
https://github.com/GeekyAnts/native-base-docs/issues/143

**Comment by suvenduchhatoi** [comment]
@italomlp check latest version docs... They have been updated
