### ISSUE TITLE
How to pass value as argument in _renderContent accordion

### ISSUE THREAD

**Issue by Ratnesh-K** [GeekyAnts/NativeBase#2365]
This is my code. what i want to achieve it. 

_renderContent(item,value) {      
            return (
                <View
                    style={{ flexDirection: "row", padding: 10 }}  >
                    <View>
                        <TouchableOpacity style={styles.ItemButtonStyle} activeOpacity={.5} onPress={() => { ModifyAction() }}>
                            <Text style={styles.ItemTextStyle}>Modify</Text>
                        </TouchableOpacity>
                    </View>
                    <View >
                        <TouchableOpacity style={styles.ItemButtonStyle} activeOpacity={.5} onPress={() => this.navigation.goBack()}>
                            <Text style={styles.ItemTextStyle}>Cancel</Text>
                        </TouchableOpacity>
                    </View>
                </View>
            );
        }

 <Accordion
                        dataArray={dataArray}
                        renderHeader={this._renderHeader}
                        renderContent={this._renderContent('SomeValue')}
                    />

**Comment by SupriyaKalghatgi** [comment]
As of now, Accordion takes in text type parameter only. No custom components or custom values can be passed to accordion
We have considered #2163 as enhancement to accordion component
So please stay tuned for updates

**Comment by poojapmagar** [comment]
Any update on this post is there any way how we can pass screens to accordion content part?
