### ISSUE TITLE
Checkbox icon not showing with 2.8.1

### ISSUE THREAD

**Issue by nahuelhds** [GeekyAnts/NativeBase#2368]
## I have gone through these following points
- [x]   Check latest documentation: https://docs.nativebase.io/
- [x]   Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x]   Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [x]   Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [x]   For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- [x]   For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

## Issue Description

Hi. I'm working with Expo SDK 30 and NativeBase 2.8.1

When I include a simple checkbox component it gives me a icon warning. My code is:

```
<ListItem button onPress={this.handleLegalAge}>
              <CheckBox
                checked={this.state.legalAge}
                onPress={this.handleLegalAge}
              />
</ListItem>
```

The error is the classic icon name issue: it says "Warning: Failer prop type: Invalid prop `name` of value `ios-checkmark-outline` supplied to `Icon`, expected one of [...]"

Even more, if I use an icon like
```
<Icon name="person"/>
```

It also gives a similar issue as it looks for "ios-person-outline". If I add `active` prop to that icon the component renders fine.

Anyway, my issue report is about the impossibility to use the checkbox component as I don't have access to the icon declaration.

Hope anyone can help.

Thanks in advance.

**Comment by SupriyaKalghatgi** [comment]
Fixed with commit https://github.com/GeekyAnts/NativeBase/commit/86da1649e7dd541d405aa5c64cce7d0eb61751a2

Also available on `master`

**Comment by j-ornelas** [comment]
Upgrading NativeBase fixed the issue for me.
