### ISSUE TITLE
Header with tabs showing shadow between

### ISSUE THREAD

**Issue by davidrojo** [GeekyAnts/NativeBase#2371]
## Issue Description

When adding a header with tabs, it is showing a shadow between the header and the tabs.

![header with tabs](https://user-images.githubusercontent.com/1050749/47141345-bd858c80-d2c0-11e8-9eb2-d234e6270d77.png)

### node, npm, react-native, react and native-base version, expo version if used
$ node -v
v8.10.0

$ npm ls --depth 0
testApp@0.0.1 /home/david/dev/testApp
├── @babel/runtime@7.1.2
├── babel-jest@23.6.0
├── jest@23.6.0
├── metro-react-native-babel-preset@0.48.1
├── native-base@2.8.1
├── react@16.5.0
├── react-native@0.57.1
└── react-test-renderer@16.5.0

### Expected behaviour

There should be no shadow between Header and Tabs

### Steps to reproduce
I've included a base code to test this.

```
import React, { Component } from 'react';
import {
  AppRegistry, Text, View
} from 'react-native';
import { Header, Container, Body, Title, Tabs, Tab } from 'native-base';

class App extends Component {
  render() {
    return (
      <Container>
        <Header hasTabs>
          <Body>
            <Title>
              <Text>Header title</Text>
            </Title>
          </Body>
        </Header>
        <Tabs>
          <Tab heading="Tab 1">
            <View>
              <Text>Tab 1 content</Text>
            </View>
          </Tab>
          <Tab heading="Tab 2">
            <View>
              <Text>Tab 1 content</Text>
            </View>
          </Tab>
        </Tabs>
      </Container>
    );
  }
}

AppRegistry.registerComponent('testApp', () => App);
```

### Is the bug present in both iOS and Android or in any one of them?

Only tested on Android

**Comment by Jalson1982** [comment]
Have same issue... Any help on this guys please....

**Comment by ARDcode** [comment]
@davidrojo, @Jalson1982  try <Header **style={{elevation:0}}** hasTabs> for Android or shadow to 0 for IOS

**Comment by Jalson1982** [comment]
@ARDcode i just tested on android same behaviour ... :(

**Comment by MuhDur** [comment]
got the same problem..

**Comment by ShinsukeWatanabe** [comment]
@davidrojo 
```
<Tabs
  ...
  style={Platform.OS === 'android' ? { overflow: 'hidden' } : null}
>
```

**Comment by davidrojo** [comment]
@ShinsukeWatanabe Thanks, this works fine in android

**Comment by arashrahimi46** [comment]
> @davidrojo
> 
> ```
> <Tabs
>   ...
>   style={Platform.OS === 'android' ? { overflow: 'hidden' } : null}
> >
> ```

thanks that works for me

**Comment by LuisClark** [comment]
> overflow: 'hidden'

works for me too thanks!!

**Comment by darron1217** [comment]
Those solutions are just workarounds.
I think this issue should be re-opened.

Without using <Content> right after <Header>, this issue still exists on version `2.13.14`

**Comment by darron1217** [comment]
Anyway, I found another workaround.
I think `hasTabs` attribute should increase header's `elevation`

```
      <View style={{elevation: 2}}>
        <Header />
      </View>
      <Tabs />
```
