### ISSUE TITLE
React-navigation + nativeBase error!! (can't select/copy/paste input android)

### ISSUE THREAD

**Issue by bachlongkocanh** [GeekyAnts/NativeBase#2372]
My app using nativeBase with react-navigation like diagram:
```sh
- Login
- Drawer
-- MaterialTopTab
--- Tab1
--- Tab2
-- Other Page
```
In file Tab1 use nativeBase,
```sh
<Form>
   <Item floatingLabel >
      <Label>Username</Label>
      <Input />
   </Item>
</Form>
```
Then Input can't handle `select/copy/paste`. Please check my issues. <Error only on android>
- Snack expo: https://snack.expo.io/@huutho/errornavigation
- Github: https://github.com/bachlongkocanh/ErrorNavigation

**Comment by sondoan1204** [comment]
how to fix???
