### ISSUE TITLE
Picker.Item unable to select on whitespace

### ISSUE THREAD

**Issue by isaaclem** [GeekyAnts/NativeBase#2373]
Basically there is a wide Picker and each of the item can be clickable only directly on the item itself, means that if we are clicking on the label, it can be selected but if we click on the whitespace besides the label, it wont be selected.

I've tested the same app in most of the devices but apparently this issues only happened on huawei MHA-L29.

**Comment by SupriyaKalghatgi** [comment]
In that case, can you try with React Native Picker on same device? Also share screen

**Comment by SupriyaKalghatgi** [comment]
@isaaclem Did you try?

**Comment by eyalabadi98** [comment]
I have the same issue
