### ISSUE TITLE
Input getRef is not working!

### ISSUE THREAD

**Issue by Pholenk** [GeekyAnts/NativeBase#2374]
## I have gone through these following points
- [x]   Check latest documentation: https://docs.nativebase.io/
- [x]   Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x]   Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases

## Issue Description
I already read any open and closed issue but i can't find any comment that can solved this problem. Many comments suggest to use `getRef={...}` instead of `ref={...}` but i don't event know both of them is not workin on my project.

### node, npm, react-native, react and native-base version, expo version if used
```
"react": "16.3.1",
"react-native": "0.55.3",
"native-base": "2.8.1",
"react-navigation": "2.17.0"
```

### Expected behaviour
use this._input._root.focus() in componentDidMount()

### Actual behaviour
got error of
```
... undefined is not function (evaluating: this._input._root.focus() ...
```
### Steps to reproduce
```
class SearchSuggestion extends Component{
	constructor(props){
		super(props)
		this.changeSuggestion = _.debounce(this._changeSuggestion.bind(this))
	}
	
	componentDidMount(){
		this._inputCity._root.focus()
	}

	componentWillUnmount(){
		this.props.resetSuggestion()
	}

	_changeSuggestion = text => this.props.getSuggestion(text)

	_renderSuggestions = (screenId) => {
		return(
			<FlatList
				styles={{width: width}}
				data={this.props.searchCities.suggestionCity}
				keyExtractor={(item, index) => `${item.id} - ${index}`}
				renderItem={ ({item}) => 
					<TouchableOpacity
						style={styles.suggestionItem}
						onPress={() => {
							( screenId == 'origin' ?
								this.props.setOrigin({originName: item.name, originId: item.id})
								: this.props.setDestination({destinationName: item.name, destinationId: item.id})
							)
							&& this.props.resetSuggestion() && this.props.navigation.goBack()
						}}
					>
						<Text style={styles.suggestionItemText}>{item.name}</Text>
					</TouchableOpacity>
				}
			/>
		)
	}

	render(){
		const screenId = this.props.navigation.getParam('screenId', 'origin')
		return(
			<Container>
				<Header style={styles.header} noShadow>
					<StatusBar
						backgroundColor={main}
						barStyle='light-content'
					/>
					<Left>
						<Button transparent onPress={() => this.props.navigation.goBack()}>
							<Icon name={'chevron-left'} size={30} color={'#fff'} />
						</Button>
					</Left>
					<Body>
						<Title>{screenId == 'origin' ? 'Search Origin' : 'Search Destination'}</Title>
					</Body>
				</Header>
				<Content>
					<View style={styles.form}>
						<Item regular>
							<Input
								placeholder={screenId == 'origin' ? 'Search Origin City...' : 'Search Destination City...'}
								onChangeText={text => this.changeSuggestion(text)}
								getRef={c => this._inputCity = c} // not working
								// ref={c => this._inputCity = c} // same result with getRef
							/>
						</Item>
					</View>
						{
							this._renderSuggestions(screenId)
						}
				</Content>
			</Container>
		)
	}
}
```

### Is the bug present in both iOS and Android or in any one of them?
I hope it just found on Android.

**Comment by SupriyaKalghatgi** [comment]
The example provided in https://github.com/GeekyAnts/NativeBase/issues/1793#issuecomment-382278090 works

**Comment by tmartin1** [comment]
I have run into this issue too. It looks like it only works if you use `<Item floatingLabel>`. At least, it works fine for me as long as I have `floatingLabel` in there. It doesn't work when using `fixedLabel`, `inlineLabel`, or `stackedLabel` - it doesn't even look like `getRef` gets called at all without `floatingLabel`.

The examples often shown to demonstrate this isn't an issue use floatingLabel:
https://github.com/GeekyAnts/NativeBase/issues/1803
https://github.com/GeekyAnts/NativeBase/issues/1793#issuecomment-382278090

```json
"native-base": "2.8.2",
"react": "16.3.2",
"react-native": "0.55.3",
"react-navigation": "2.7.0"
```
