### ISSUE TITLE
Unable to override picker item

### ISSUE THREAD

**Issue by indapublic** [GeekyAnts/NativeBase#2375]
I want override picker item behaviour

"native-base": "^2.4.2"

Standard example is working good
```
<Picker
    {...props}
>
    {items.map(({ label, value }) => <Picker.Item key={value} label={label} value={value} />)}
</Picker>
```

<img width="462" alt="screen shot 2018-10-19 at 00 35 11" src="https://user-images.githubusercontent.com/856260/47162315-0841eb80-d337-11e8-9c1b-8d5346a1b926.png">

If I change Picker.Item to another component 
```
{items.map(({ label, value }) => <Text>Hello</Text>)}
```
or
```
{items.map(({ label, value }) => <MyComponent {...props} />)}
```

I see

<img width="462" alt="screen shot 2018-10-19 at 00 36 07" src="https://user-images.githubusercontent.com/856260/47162378-2a3b6e00-d337-11e8-9d4e-2ad39e982e5b.png">

But if I will add props `label` to component - it works again ¯\_(ツ)_/¯  

```
{items.map(({ label, value }) => <Text label={label}>Hello</Text>)}
```

Is it possible use custom component for picker item?

**Comment by JoostSlijkoort** [comment]
I believe it is not intended to use custom Item components. Even if you add your own component, like Text, it will display the Picker.Item component. The same goes for the `react-native` Picker.

**Comment by indapublic** [comment]
So why we not use ‘items’ property?
‘’’
items: {label, value}[]
‘’’

**Comment by SupriyaKalghatgi** [comment]
@indapublic Using custom components in Picker is not intended use case
This is neither possible with React Native Picker

But if you still wish to have this feature, then you can fork NativeBase and have your necessary changes
