### ISSUE TITLE
Remove Footer Tab (Button) Touchable Opacity ?

### ISSUE THREAD

**Issue by ElangoPrince** [GeekyAnts/NativeBase#2384]
Remove footer Touchable Opacity (Buttons);
     Here i attach the image kindly help me ..
![screenshot_20181020-111220](https://user-images.githubusercontent.com/34785789/47251946-83032780-d459-11e8-9a8c-42e9168c9fc6.png)
   Ex:
    "Message -Icon Button" remove background ""gray color"

**Comment by SupriyaKalghatgi** [comment]
If you followed the issue template while creating this issue, https://github.com/GeekyAnts/NativeBase/blob/master/ISSUE_TEMPLATE.txt

It suggested you to check https://nativebase.io/customizer/
Here is the screenshot that i tried to replicate your use case
![image](https://user-images.githubusercontent.com/13464885/47359434-64678f80-d6ea-11e8-9a5e-857b494b8e0c.png)
