### ISSUE TITLE
Last CardItem text cut off in DeckSwiper component

### ISSUE THREAD

**Issue by BrianJVarley** [GeekyAnts/NativeBase#2386]
## Issue Description

Placing a Deck Swiper inside a react-native `<View>` with `flex:1` results in last CardItem text being cut off on 
certain screen sizes. 

### node, npm, react-native, react and native-base version, expo version if used
```
    "native-base": "2.0.12",
    "react": "~15.4.2",
    "react-dom": "~15.4.2",
    "react-native": "0.42.0",
    "react-native-vector-icons": "^4.0.0",

```

### Expected behaviour
Bottom card item would not be cut off as in screenshot. Or as a workaround that a ScrollVIew could be wrapped around the CardItem.

### Actual behaviour
Last `CardItem` text in the `DeckSwiper` is cut off inside View instead of resizing for given device screen size.

### Steps to reproduce
Review the following gist of the component -

https://gist.github.com/BrianJVarley/8f6a8ea5ab0fa2ca699f9546165808f2

### Is the bug present in both iOS and Android or in any one of them?
Android
### Any other additional info which would help us debug the issue quicker.

A similar issue was opened in regards to wrapping the component in a ScrollVIew but no solution given:

https://github.com/GeekyAnts/NativeBase/issues/867

*Example of CardItem cut off in view*

![cut-off-carditem](https://user-images.githubusercontent.com/6731968/47272498-9f4cb480-d57e-11e8-8c8c-0fcad4c9ba0e.png)

**Comment by Seunope** [comment]
I am experiencing this issue too, where DeckSwiper cut off some text and i can't scroll up to show the cut off text. Have you gotten a fix for it?

**Comment by hanykumar** [comment]
Hi @BrianJVarley , you can use `<ScrollView>` from `react-native` for scrolling.
```
<DeckSwiper
            dataSource={cards}
            renderItem={item =>
              <Card style={{ elevation: 3 }}>
                <CardItem>
                  <Left>
                    <Thumbnail source={item.image} style={{backgroundColor: 'red'}}/>
                    <Body>
                      <Text>{item.text}</Text>
                      <Text note>NativeBase</Text>
                    </Body>
                  </Left>
                </CardItem>
                <CardItem cardBody>
                  <Image style={{ height: 300, flex: 1, backgroundColor: 'red' }} source={{uir: item.image}} />
                </CardItem>
                <CardItem>
                  <Icon name="heart" style={{ color: '#ED4A6A' }} />
                  <ScrollView style={{height: 75}}>
                    <Text>{item.name} Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source.</Text>
                  </ScrollView>
                </CardItem>
              </Card>
            }
/>
```
![Screenshot 2020-04-16 at 12 50 04 PM](https://user-images.githubusercontent.com/15860517/79426466-d3246100-7fe0-11ea-9d5f-1c10aa7ce4a6.png)

**Comment by hanykumar** [comment]
Hi @BrianJVarley, closing this now due to inactivity. Let us know if the issue still persists.
