### ISSUE TITLE
Header not displaying properly on iPhone Xs, Xs Max, Xr

### ISSUE THREAD

**Issue by QinGuan2004** [GeekyAnts/NativeBase#2388]
## I have gone through these following points
- [x]   Check latest documentation: https://docs.nativebase.io/
- [x]   Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x]   Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [x]   Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase

## Issue Description
NodeJS 10.12.0 Current
NPM 6.4.1
react-native-cli: 2.0.1
react-native: 0.57.3

### Expected behaviour
Header covers notch gaps, and text only begins after safe area, like when run in iPhone X

### Actual behaviour
Header and Title begins at top of screen, and has normal height as when on a non iPhone X device., Thus Title is blocked out by notch 

### Steps to reproduce
```
<Header>
  <Body>
    <Title>
      Test
    </Title>
  </Body>
</Header>
```

### Is the bug present in both iOS and Android or in any one of them?
iOS only

### Any other additional info which would help us debug the issue quicker.
N/A

**Comment by SupriyaKalghatgi** [comment]
https://github.com/GeekyAnts/NativeBase/issues/2291
