### ISSUE TITLE
Slide out menu/drawer in Header

### ISSUE THREAD

**Issue by jrmcdona** [GeekyAnts/NativeBase#239]
Hi All,
Trying out your components!
This isn't an "issue" but I am wondering how you would extend the hamburger icon in the header into making a menu slider/drawer.  I am not quite advanced enough.  Do you know of any samples I could study?

Thanks

**Comment by SupriyaKalghatgi** [comment]
@jrmcdona You can check 

1. [Native Starter Kit](https://github.com/start-react/native-starter-kit), a simple starter project for [React Native](https://facebook.github.io/react-native/) + [NativeBase](http://nativebase.io/) + [Redux](https://github.com/reactjs/redux) + [React Native Navigator](https://facebook.github.io/react-native/docs/navigator.html) + [CodePush](https://github.com/Microsoft/react-native-code-push) apps on iOS and Android.

2. [NativeBase-KitchenSink](https://github.com/GeekyAnts/NativeBase-KitchenSink), an example app with all the UI components of  [NativeBase](http://nativebase.io/), extended from [Native Starter Kit](https://github.com/start-react/native-starter-kit)
