### ISSUE TITLE
Texts inside input field overlaps when using Stacked Label

### ISSUE THREAD

**Issue by sianlasaga** [GeekyAnts/NativeBase#2391]
### react-native, react and native-base version
"native-base": "^2.8.1",
"react": "16.6.0-alpha.8af6728",
"react-native": "0.57.3",
### Expected behaviour
Texts inside input box should not overlap when the text exceeds the length of textbox
### Actual behaviour
The texts inside the input box overlaps
### Steps to reproduce (code snippet or screenshot)
![image](https://user-images.githubusercontent.com/35569322/47414529-c3d5a600-d7a3-11e8-9ca7-bb9e9ed597f7.png)
![image](https://user-images.githubusercontent.com/35569322/47414551-cfc16800-d7a3-11e8-8bae-3f5ef0495d2f.png)
### Screenshot of emulator/device
![image](https://user-images.githubusercontent.com/35569322/47412733-1bbdde00-d79f-11e8-88a3-81448184f59c.png)
### Is the bug present in both ios and android or in any one of them?
Bug exists in android. I still didnt tried in ios
### Any other additional info which would help us debug the issue quicker.
This bug only occurs when using stacked label. I tried using floating label and it works fine.

**Comment by SupriyaKalghatgi** [comment]
You need to share the styles too

**Comment by sianlasaga** [comment]
@SupriyaKalghatgi sorry for that. I updated my comment. But you can base the 'value / amount' field. It doesnt use styles.

**Comment by SupriyaKalghatgi** [comment]
Don't share code snippet in screenshot
paste it here

**Comment by faizantariq1** [comment]
@sianlasaga hey did you solve the issue?
