### ISSUE TITLE
cannot read property 'showActionSheet' of null

### ISSUE THREAD

**Issue by gogulanareshkw** [GeekyAnts/NativeBase#2393]
getting error as cannot read property 'showActionSheet' of null

"native-base": "^2.8.1",		
"react": "^16.4.1",
"react-native": "^0.55.4",

follow below steps to reproduce

- if actionsheet available in page 1, for the first actionsheet is working
- navigate to page 2 from page1, and then page 3 from page2 (page1 -> page2 -> page3)
- then goback to page1 and click actionsheet, now getting error

tested in android

![screenshot_2018-10-25-14-59-32](https://user-images.githubusercontent.com/40063274/47510423-bef11f00-d895-11e8-837b-ca74f4af7358.png)

Thanks

**Comment by DB1295** [comment]
Facing the same issue on both iOS and android..

Any solution..??

**Comment by suvenduchhatoi** [comment]
@gogulanareshkw @DB1295 
Make sure to wrap the app with Root component so that the app doesn't lose actionsheet instance on closing any scene...

**Comment by gogulanareshkw** [comment]
how to wrap Root component @suvenduchhatoi , please check once with my below code

import AppStart from "../components/auth/AppStart";
import Login from "../components/auth/Login";
import HomeDrawerRouter from "./HomeDrawerRouter";
import { createStackNavigator } from "react-navigation";
HomeDrawerRouter.navigationOptions = ({ navigation }) => ({
  header: null  
});
export default (StackNav = createStackNavigator({
  AppStart: { screen: AppStart },
  Login: { screen: Login },
},
{headerMode:'none'}));

**Comment by SupriyaKalghatgi** [comment]
Here is an example from docs
https://docs.nativebase.io/Components.html#actionsheet-def-headref

**Comment by rf1804** [comment]
@SupriyaKalghatgi It happens with react-navigation v3 as StackNavigator became createStackNavigator as pointed out in

> how to wrap Root component @suvenduchhatoi , please check once with my below code
> 
> import AppStart from "../components/auth/AppStart";
> import Login from "../components/auth/Login";
> import HomeDrawerRouter from "./HomeDrawerRouter";
> import { createStackNavigator } from "react-navigation";
> HomeDrawerRouter.navigationOptions = ({ navigation }) => ({
> header: null
> });
> export default (StackNav = createStackNavigator({
> AppStart: { screen: AppStart },
> Login: { screen: Login },
> },
> {headerMode:'none'}));

@gogulanareshkw are you able to fix it??
