### ISSUE TITLE
KeyboardAvoidingView  not working in React Native 

### ISSUE THREAD

**Issue by waqaramjad** [GeekyAnts/NativeBase#2395]
i am using Nativebase and expo and my keyboard covers input field when i click on any input field , i tried all the options but still no solution work . 
i tried RN KeyboardAvoidingView ,also  react-native-keyboard-aware-scroll-view libray and many other option but my problem not solve 
here is my file : 
https://github.com/waqaramjad/Survey-App-react-Native/blob/master/components/survey%20form/form.js

**Comment by SupriyaKalghatgi** [comment]
https://github.com/GeekyAnts/NativeBase/blob/master/ISSUE_TEMPLATE.txt
