### ISSUE TITLE
Thumbnail source with HTTP protocol

### ISSUE THREAD

**Issue by markzero** [GeekyAnts/NativeBase#240]
How can we use external images for thumbnails?

For example:

`<Thumbnail source={require('http://site.com/img/flower.jpg')} />`

**Comment by sankhadeeproy007** [comment]
Does it work with  `import {Image} from 'react-native'`
<Image source={require('http://site.com/img/flower.jpg')} />?

**Comment by markzero** [comment]
It always happens to find answer after asking a question :)

I solved it like so:

`<Thumbnail source={{ uri: obj.avatar }} />`

Where obj is array of dummy data and using `map` function I created list view with list items with thumbnails. Thanks anyway!

**Comment by adnanmayo** [comment]
@markzero can you show me example ?

**Comment by markzero** [comment]
Exactly like the example above :) 
There's an object like `obj = {avatar: 'http://someurlhere.com/img/img.jpg', datetime:'...', '''}`
Just used obj.avatar...
