### ISSUE TITLE
Only 1 item is expand when other item touched (Accordion)

### ISSUE THREAD

**Issue by NguyenPhatBG** [GeekyAnts/NativeBase#2401]
I set up expanded={'none'} when componentDidMount,
but All item can be expaned, How can I expand only content 1 item, other item is close?
my code:
<Accordion
                dataArray={[item]}
                expanded={'none'}
                renderHeader={(item, expanded) => this._renderHeader(item, index, expanded)}
                renderContent={item => this._renderContent(item)}
                headerStyle={{ paddingHorizontal: 5 }}
                contentStyle={{ paddingHorizontal: 5 }}
                style={{ paddingHorizontal: 0 }}
            />

**Comment by SupriyaKalghatgi** [comment]
NativeBase Accordion toggle across the data sets that you define.
If `expanded={'none'}` and onClick of `content 1`, `content 1` expands
onClick of `content 2`, `content 1` collapse and `content 2` expands

**Comment by diegomachado7** [comment]
Is it possible to expand and maintain expand?

**Comment by IronTony** [comment]
any news about that?
