### ISSUE TITLE
Why does the Tab component have a set height? It's impossible to increase it's height.

### ISSUE THREAD

**Issue by reddeguzman** [GeekyAnts/NativeBase#2402]
Trying to add padding to Tab component but not able to. When I inspect the component there is a set `height` of `50` and that makes it impossible to adjust the height even when using padding to it. Also, I think `tabStyle` prop is being ignored.

**Comment by SupriyaKalghatgi** [comment]
https://github.com/GeekyAnts/NativeBase/blob/master/ISSUE_TEMPLATE.txt
