### ISSUE TITLE
Icon and text in the same line, depends on the icons?

### ISSUE THREAD

**Issue by nobady90** [GeekyAnts/NativeBase#2403]
> Package.json:

`    "native-base": "^2.8.0",
    "react": "16.4.1",
    "react-native": "^0.57.1",
`

Hi Guys, I have a problem with the location of the icons when they are included inside the text component.
As you can see, some icons are rendered not centered with the text:

![immagine](https://user-images.githubusercontent.com/36473359/47664646-c8cd9780-db9f-11e8-9378-ee674b37fc4b.png)

In my case the text is aligned with the lower part of the icon ...
I tried with other icons and the problem occurs depending on the icon chosen .. is it related to react-native-vector-icons? Will we need to wait for the update?

if you want you place the code but it is simply an icon inside a text component, (the left side is equal to the right side).

thanks for the support!

**Comment by SupriyaKalghatgi** [comment]
https://github.com/GeekyAnts/NativeBase/blob/master/ISSUE_TEMPLATE.txt
