### ISSUE TITLE
fontSize when 36 or 48 crops fonts

### ISSUE THREAD

**Issue by tyoc213** [GeekyAnts/NativeBase#2404]
HI there I just used https://nativebase.io/customizer/ and setting in the section of buttons the fontSIze to 36 in this case causes this behaviour testing the app with expo.io

![imagen](https://user-images.githubusercontent.com/506234/47685560-776fd900-db9c-11e8-8453-9731dee27464.png)

I need this sizes specifically 26, 26 and 48 as normal, middle and big fonts (title).

DO you know if there is a way to handle this?

**Comment by SupriyaKalghatgi** [comment]
@tyoc213 Increasing the button text fontSize will not increase the button height. The button height should also be modified as per fontSize ratio.

NativeBase Customizer https://nativebase.io/customizer/ as well as the theme files (commonColor, platform, material) do not have button height variable to customize

But you can achieve this with `native-base-theme/components/Button.js` https://github.com/GeekyAnts/NativeBase/blob/master/src/theme/components/Button.js#L383

**Comment by tyoc213** [comment]
I think that there should be a notice or something on the customizer (maybe it is a little dumb) but saying that other parameters not available in the customizer need to be set by code and probably a frequent parameters that are not available on customizer.

**Comment by tyoc213** [comment]
Is there a way to set the size of all the buttons, or shold I do it for each Button I place?

**Comment by tyoc213** [comment]
Hi there @SupriyaKalghatgi 

I stil get the crop of the text

```
<Content padder style={{ padding: 20 }}>
          <Button style={{height:120}}>
            <Text>Default Small 120</Text>
          </Button>
          <Button success height="300">
            <Text>Success Default NORMAL 300</Text>
          </Button>
          <Button large dark style={styles.mb15}>
            <Text>Dark Large</Text>
          </Button>
        </Content>
```

![image](https://user-images.githubusercontent.com/506234/47735294-e21f2400-dc31-11e8-9b97-5eaa679a1045.png)

**Comment by SupriyaKalghatgi** [comment]
@tyoc213 
> I think that there should be a notice or something on the customizer (maybe it is a little dumb) but saying that other parameters not available in the customizer need to be set by code and probably a frequent parameters that are not available on customizer.

NativeBase button as per design guidelines comes with height of `45`
Also NativeBase Button includes `small`, `large` prop to have smaller and larger button size (than default), which is again ass per design guidelines
https://docs.nativebase.io/Components.html#button-size-headref

![image](https://user-images.githubusercontent.com/13464885/47764991-e6107c00-dced-11e8-8870-009557cb8a7c.png)


But the button height you mentioned above is not as per guidelines, hence such params are not included in theme variables folder
No doubt you can have button of your desired height, in theme components folder

**Comment by SupriyaKalghatgi** [comment]
> the button height you mentioned above is not as per guidelines, hence such params are not included in theme variables folder
No doubt you can have button of your desired height, in theme components folder

> Increasing the button text fontSize will not increase the button height. The button height should also be modified as per fontSize ratio.
> you can achieve this with native-base-theme/components/Button.js https://github.com/GeekyAnts/NativeBase/blob/master/src/theme/components/Button.js#L383
