### ISSUE TITLE
Custom Toast Button rather than just text

### ISSUE THREAD

**Issue by sirajalam049** [GeekyAnts/NativeBase#2405]
## I have gone through these following points
- [x]   Check latest documentation: https://docs.nativebase.io/
- [x]   Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x]   Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [x]   Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- []   For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- [x]   For queries related to the theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

## Issue Description
I'm using Toasts, and there I want to give a custom Button. What I really want to give an Icon in the button, 

### node, npm, react-native, react and native-base version, expo version if used, Xcode version
node: v8.9.1
npm 6.4.1
react-native-cli: 2.0.1
react-native: 0.57.3

### Expected behavior
Took the <Icon /> in the place f buttonText prop of Toast component

### Actual behavior
It is throwing error **Can't find variable: React**. 

### Steps to reproduce
```
import { Toast, Icon } from 'native-base';
 export const editProfile = (userId, data) => (
    dispatch => {
        dispatch({ type: 'EDITING_PROFILE' });
        requestEditProfile(userId, data).then(
            res => {
                         dispatch(userProfileEdited(res.data)), 
                         Toast.show({position: 'bottom',
                              duration: 7000,
                              textStyle: { fontSize: 12, fontFamily: 'Raleway-SemiBold', color: 'white'},
                              type: 'success'
                              buttonText: <Icon name='ios-checkmark-circle-outline' size={16} />,
                         })
             }
            err => dispatch(userProfileEditFailed(err))
        )
    }
)
```

**Comment by SupriyaKalghatgi** [comment]
#2194
