### ISSUE TITLE
Documentation is inadequate

### ISSUE THREAD

**Issue by kaitlynbrown** [GeekyAnts/NativeBase#2410]
## I have gone through these following points
- [x]   Check latest documentation: https://docs.nativebase.io/
- [x]   Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x]   Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [x]   Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [x]   For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- [x]   For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

## Issue Description
The nativebase documentation is woefully inadequate:
- Several components are only ever mentioned in relation to other components, and do not have a list of props which they take (most notably `Item`, but also `ListItem`, `Text`, `Label`, `Left`, `Right`, possibly some others. The `Left` and `Right` components especially seem to have a lot of weird quirks that I've run into that aren't described anywhere in the documentation.
- A number of examples do not match up with the demo, and have code missing. Notably the [icon button section](https://docs.nativebase.io/Components.html#button-icon-headref), but honestly it seems to be the case in almost every single example. For example, in the icon button section, the demo shows a number of buttons with icons only, but the example code has not a single button with an icon only (are you supposed to use `iconLeft`? `iconRight`? neither?).
- It can be a pain find out what props a component takes unless you know specifically where to look. In some cases, they aren't available in the docs and you have to look at the code for the component, which is even more of a pain.
- While there is a very limited amount of documentation on customizing the theme variables, there is no documentation at all on customizing the actual component themes themselves. It's easy enough to figure out, but there seem to be a few quirks when theming nested components, and how themes are resolved when a component has multiple classes.
- There is barely any information about the `Content` component. It replaces `KeyboardAwareScrollview`. Okay. How is it different? How does it interact with the `Header` and `Footer` when the keyboard is visible? In what different ways can I make the content avoid the keyboard? What if I want the `Footer` to stay under the keyboard when it is visible? (it seems to also avoid the keyboard by default, for some reason). The documentation doesn't even say anything about the `contentContainerStyle` prop, which makes me wonder what other props are missing on this and other components.

**Comment by SupriyaKalghatgi** [comment]
https://github.com/GeekyAnts/native-base-docs/issues/146
