### ISSUE TITLE
Sidebar doesnt always react (show menu) to taps sometimes

### ISSUE THREAD

**Issue by tyoc213** [GeekyAnts/NativeBase#2411]
Just downloaded https://reactnativeseed.com/ with `flow+mobx+React Native`.

So when running the app on device, there is sometimes that tapping the menu icon highlights it (like yeah, it detects the tap), but doesn't show the menu as response to the event even if you tap multiple times.

![gifcapture](https://user-images.githubusercontent.com/506234/47811063-7066d900-dd0a-11e8-8b3a-15290d552d2a.gif)

In this capture, you can see how I tapped a lot of times to activate finally randomly the menu.

Is this "normal behaviour", or how to correct it?

**Comment by SupriyaKalghatgi** [comment]
Please reopen this issue on appropriate github repo
