### ISSUE TITLE
Header broken on iPhone XR and XS Max

### ISSUE THREAD

**Issue by Ciebiada** [GeekyAnts/NativeBase#2412]
## I have gone through these following points
- [x]   Check latest documentation: https://docs.nativebase.io/
- [x]   Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x]   Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [x]   Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- []   For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- []   For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

## Issue Description
Header component is not behaving correctly on iPhone XR and XS Max. I suppose those two phones have new resolution as compared to iPhone X for which the issue has been resolved.

Screenshot:
<img width="772" alt="screenshot 2018-11-01 at 01 17 28" src="https://user-images.githubusercontent.com/738817/47825851-9de86c80-dd74-11e8-818b-115857f76e54.png">

### Expected behaviour
I expect that it will look the same way it does for iPhone X - there will be more padding between the title and the notch

### Actual behaviour
Title is too close to the notch

**Comment by SupriyaKalghatgi** [comment]
#2291
