### ISSUE TITLE
Upgrade for react-native v0.57.4

### ISSUE THREAD

**Issue by navata** [GeekyAnts/NativeBase#2413]
Current, I have use package as below: 
 "native-base": "^2.8.1",
 "react-native": "0.57.4"
When I debug my application, it have display some warning. I think we need upgrade your package for react-native late version.
Warning error:
![screen shot 2018-11-01 at 15 53 20](https://user-images.githubusercontent.com/16706514/47842348-0116e500-ddef-11e8-9a45-b269222fbde7.png)
![screen shot 2018-11-01 at 15 52 43](https://user-images.githubusercontent.com/16706514/47842416-2572c180-ddef-11e8-89b9-5971ff94c934.png)

**Comment by SupriyaKalghatgi** [comment]
#2320
