### ISSUE TITLE
<Tab> component documentation

### ISSUE THREAD

**Issue by jaspervanbrian** [GeekyAnts/NativeBase#2417]
Hello NativeBase community!

Recently, I found myself in need to customize a single `<Tab>` component (props actually). Unfortunately, the only thing I found in the documentation is the `<Tabs>` component, no `<Tab>`. I think updating the documentation could save other beginners, just like me, from wasting hours of time. What do you think?

**Comment by SupriyaKalghatgi** [comment]
https://github.com/GeekyAnts/native-base-docs/issues/148

**Comment by jaspervanbrian** [comment]
Yeah sorry for that, forgot about the docs repo

**Comment by suvenduchhatoi** [comment]
@jaspervanbrian You can check the latest versions of Docs now... https://docs.nativebase.io
