### ISSUE TITLE
Native base drawer opacity bug

### ISSUE THREAD

**Issue by freekydesigner** [GeekyAnts/NativeBase#2418]
I get this error when using native base drawer..

![xihhd](https://user-images.githubusercontent.com/44766098/47984606-16e11e80-e0fd-11e8-9442-0b078555ef57.png)

the opacity bug error, please someone help me??

**Comment by scy0846** [comment]
Same here. Just recently showed up.

**Comment by scy0846** [comment]
Found this answer in another issue post. This fixed my error. There is a PR coming for it, but not sure when it will be merged. 

> Managed to fix this issue by digging into the default properties of the Drawer component, by default the Drawer component's overlay has an elevation property of 8.
> 
> The elevation prop only effects Android (which is why this problem is not present in iOS) - to change the default props you can do this:
> 
> ```
> import { Drawer } from 'native-base';
> ...
> Drawer.defaultProps.styles.mainOverlay.elevation = 0;
> ```
> or wait until the above PR is merged (:
