### ISSUE TITLE
Using a Badge in the Footer tab like Facebook notifications

### ISSUE THREAD

**Issue by jrmcdona** [GeekyAnts/NativeBase#242]
Hi All,
It is possible to use the Native base badge and assign it to one of the Footer tab items. Much like you see with Facebook notifications? I tried it using out of the box badge and Footer tab but they didn't seem to work together.

I assume I could make my own badge and try to get it to work.

Is this something you all were planning to add?

Thanks!

**Comment by sankhadeeproy007** [comment]
That is something in our to do list. We hope to finish by the end of this week.

**Comment by jrmcdona** [comment]
Awesome, the package looks good!  I think that is the only requirement I am missing for my project.   Nice job.

**Comment by sankhadeeproy007** [comment]
![screen shot 2016-10-20 at 4 20 13 pm](https://cloud.githubusercontent.com/assets/10998047/19556945/2434e20a-96e1-11e6-8639-01b1914e3bfd.png)
@jrmcdona Additionally you can use `badgeColor` and `textColor` props with `<Badge>` for customizing.

**Comment by jrmcdona** [comment]
Beaut!

**Comment by shishircc** [comment]
Awesome ! Just what I needed.

**Comment by shishircc** [comment]
The badge at times completely hides the icon. Maybe a slight right shift may be useful. [](url)
![simulator screen shot 24 oct 2016 5 14 21 pm](https://cloud.githubusercontent.com/assets/7352186/19644461/82dcc8b6-9a0d-11e6-8dcf-a2d58a0d12a3.png)

**Comment by sankhadeeproy007** [comment]
Okay, noted. I guess the problem isn't there with a single digit badge?

**Comment by shishircc** [comment]
For the given Icon (restaurant), even single digit hides a lot of the icon.

**Comment by shuchengc** [comment]
hi, but when I run the footertab code, it shows error message: cannot add/remove sealed array elements

**Comment by SupriyaKalghatgi** [comment]
For FooterTabs, please check for its implementation in [NativeBase-KitchenSink](https://github.com/GeekyAnts/NativeBase-KitchenSink)

**Comment by jetpack3331** [comment]
And what about normal Tab? Is there a possibility of adding <Badge> element with Text into <Tab heading={}> ?

**Comment by wmlutz** [comment]
Going to jump on @jetpack3331 's comment. Badge in the normal (top of view) Tabs looks kinda janky. Is there another issue tracking that?

**Comment by guohuihot** [comment]
How to hide default tab? react-navigation -> createBottomTabNavigator({...})
