### ISSUE TITLE
How to set style properties for all tabs and other styling queries

### ISSUE THREAD

**Issue by bonbonio** [GeekyAnts/NativeBase#2420]
Hello,

Two questions; both regarding the latest NativeBase.

1. How can I change the colour of the grey line below the Tabs component?
2. I currently set an activeTabStyle etc on every tab, is there not a way to set it once and have it applied to all Tabs?

So far this library looks great, it was the only component of worth I could find for Tabs, but the rest of it I don't use/need.

Thanks

**Comment by SupriyaKalghatgi** [comment]
https://github.com/GeekyAnts/NativeBase/issues/2119

**Comment by sanketsahusoft** [comment]
@SupriyaKalghatgi Reopening this.

**Comment by suvenduchhatoi** [comment]
@bonbonio 
Check the Customization section of Native-Base...
http://docs.nativebase.io/Customize.html#theaming-nb-headref


Your App.js is like:
```
import React, { Component } from "react";
import {
  Container,
  Header,
  Tab,
  Tabs,
  TabHeading,
  Icon,
  Text,
  Content,
  Button,
  StyleProvider,
} from "native-base";
import tabTheme from "./native-base-theme/components";
export default class TabsAdvancedExample extends Component {
  render() {
    return (
      <StyleProvider style={tabTheme()}>
        <Container>
          <Header hasTabs />
          <Tabs>
            <Tab
              heading={
                <TabHeading>
                  <Icon name="ios-camera" />
                  <Text>Camera</Text>
                </TabHeading>
              }
            >
              <Text>hhi</Text>
            </Tab>
            <Tab
              heading={
                <TabHeading>
                  <Text>No Icon</Text>
                </TabHeading>
              }
            >
              <Text>hhi</Text>
            </Tab>
            <Tab
              heading={
                <TabHeading>
                  <Icon name="ios-apps" />
                </TabHeading>
              }
            >
              <Text>hhi</Text>
            </Tab>
          </Tabs>
        </Container>
      </StyleProvider>
    );
  }
}
```
Go to native-base-theme/variables/platform in your project and make changes to style variables
// Tab
  tabDefaultBg: platform === "ios" ? "#F8F8F8" : "#3F51B5",
  topTabBarTextColor: platform === "ios" ? "#6b6b6b" : "#b3c7f9",
  topTabBarActiveTextColor: platform === "ios" ? "#007aff" : "#fff",
  topTabBarBorderColor: platform === "ios" ? "red" : "#fff",
  topTabBarActiveBorderColor: platform === "ios" ? "#007aff" : "#fff",

**Comment by SupriyaKalghatgi** [comment]
@bonbonio Did you try?

**Comment by suvenduchhatoi** [comment]
Closing the issue due to no response...Hope it got fixed
