### ISSUE TITLE
Checkbox component - Warning: Failed prop type because of missing icon

### ISSUE THREAD

**Issue by cseelus** [GeekyAnts/NativeBase#2422]
When using the Checkbox component, a `warning: Failed prop type: invalid prop type `name` of value 'ios-checkmark-outline'` is thrown with the latest version of `@oblador/react-native-vector-icons`.

Looks like the icon in question was renamed to `ios-checkmark-circle`: https://oblador.github.io/react-native-vector-icons/

When using CRNA (with Expo), the current version of `@oblador/react-native-vector-icons` (as `expo/vector-icons`) is automatically used, so I had to change the Native Base code for Checkbox manually for now.

**Comment by juanorellana13** [comment]
Mind walking me through how you changed it manually @cseelus ? Many thanks for your help and time.

**Comment by cseelus** [comment]
@juanorellana13 Go to your projects `node_modules` folder and find the `native-base` folder. In there, you need to change `ios-checkmark-outline` to `ios-checkmark` in the following files:
1. src/basic/icon/NBIcons.json:678
2. dist/src/basic/icon/NBIcons.json:678
3. src/basic/Checkbox.js:48
3. dist/src/basic/Checkbox.js:1
3. dist/src/basic/Checkbox.js.map:1

Thats what I did and it works in iOS Simulator as well as in the iOS app I built and tested via Apple Testflight.

**Comment by juanorellana13** [comment]
That did the trick @cseelus. Once again, thank you.

**Comment by SupriyaKalghatgi** [comment]
#2368

**Comment by Cookizza** [comment]
I have updated to 2.8.1 and still this issue persists.

The only difference i have is I'm using the expo  icon wrapper @expo/vectoricons 8.0.0

**Comment by zacksayenko** [comment]
Yep, this still very much the case for 2.8.1, can to manually rename from ios-checkmark-outline to ios-checkmark
