### ISSUE TITLE
Trying to add a custom class to a component breaks the component

### ISSUE THREAD

**Issue by kaitlynbrown** [GeekyAnts/NativeBase#2424]
## I have gone through these following points
- [x]   Check latest documentation: https://docs.nativebase.io/
- [x]   Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x]   Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [x]   Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [x]   For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- [x]   For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

## Issue Description
I'm trying to style a group of `full` buttons such that there is a border separating each, as well as at the top and bottom of the group. I am trying to achieve this through native-base by adding a top border to all `full` buttons, and a bottom border to any button which is `full` and `last`. I've done this by modifying the section of `native-base-theme/components/Button.js` pertaining to `full` buttons:
```
    ".full": {
      ".last": {
        borderBottomWidth: 1
      },
      justifyContent: "center",
      alignSelf: "stretch",
      borderTopWidth: 1,
      elevation: null,
      shadowColor: null,
      shadowOffset: null,
      shadowOpacity: null,
      shadowRadius: null
    },
```

I am displaying the buttons like so:
```
<Content contentContainerStyle={{ flex: 1, justifyContent: "center" }}>
      <Button light full onPress={() => navigation.push("ProfileScreen")}>
        <Left>
          <Icon name="editprofile" />
        </Left>
        <Body>
          <H3>Profile</H3>
        </Body>
        <Right>
          <NBIcon name="arrow-forward" />
        </Right>
      </Button>
      <Button light full onPress={() => navigation.push("PaymentScreen")}>
        <Left>
          <Icon name="creditcard" />
        </Left>
        <Body>
          <H3>Payment</H3>
        </Body>
        <Right>
          <NBIcon name="arrow-forward" />
        </Right>
      </Button>
      <Button
        light
        full
        last
        onPress={() => navigation.push("NotificationSettingsScreen")}
      >
        <Left>
          <Icon name="bell" />
        </Left>
        <Body>
          <H3>Notifications Settings</H3>
        </Body>
        <Right>
          <NBIcon name="arrow-forward" />
        </Right>
      </Button>
    </Content>
```

### node, npm, react-native, react and native-base version, expo version if used, xcode version
    Binaries:
      Node: 9.11.2 - /usr/bin/node
      Yarn: 1.9.4 - /usr/bin/yarn
      npm: 5.6.0 - /usr/bin/npm
      Watchman: 4.9.4 - /usr/local/bin/watchman
    SDKs:
      Android SDK:
        Build Tools: 23.0.1, 26.0.2, 26.0.3, 27.0.3, 28.0.0, 28.0.3
        API Levels: 23, 25, 26, 27, 28
    npmPackages:
      react: 16.4.1 => 16.4.1 
      react-native: ^0.57.0-rc.4 => 0.57.0-rc.4 
      native-base: ^2.8.1

### Expected behaviour
A border is added to the bottom of the a button with the `last` prop set to true

### Actual behaviour
A button with the `last` prop set to true is broken:
![image](https://user-images.githubusercontent.com/1388240/48102604-b7f4d580-e1e0-11e8-87e7-41b4d22f828d.png)

### Steps to reproduce
See above

### Is the bug present in both iOS and Android or in any one of them?
Android at least, haven't checked iOS

**Comment by suvenduchhatoi** [comment]
@kaitlynbrown 
Use independent styling as in:

".full": {
      justifyContent: "center",
      alignSelf: "stretch",
      borderRadius: 0,
    },
    ".last": {
      borderBottomWidth: 5,
      borderColor: "#979797",
    },

Not sure how to nest style of a class within another, but you can style the ".last" class independently as above, because you are passing both the 'full' and 'last' prop values to the last button, so it will inherit properties from both the classes

**Comment by suvenduchhatoi** [comment]
Closing the issue due to no response...Hope it got fixed
