### ISSUE TITLE
[Feature Request] spinner size

### ISSUE THREAD

**Issue by tkserver** [GeekyAnts/NativeBase#2427]
I would like to be able to resize the spinner via props so I can fit it into some views which are too small for the current spinner.

**Comment by SupriyaKalghatgi** [comment]
You can customize spinner size here https://github.com/GeekyAnts/NativeBase/blob/master/src/theme/components/Spinner.js#L7

Go though ejecting theme steps from documentation before proceeding https://docs.nativebase.io/Customize.html#theaming-nb-headref

**Comment by juanantoniofj** [comment]
You can also use the props size with values small or large because this prop is passed to ActivityIndicator

https://facebook.github.io/react-native/docs/activityindicator#size

**Comment by Ho3ein-Boka** [comment]
Applying this on element style could be another solution:

`transform: [{ scaleX: 1.5 }, { scaleY: 1.5 }]`

**Comment by ikeliec** [comment]
@Ho3ein-Boka Thanks buddy. This is so brilliant of you. 👍

**Comment by ikeliec** [comment]
> Applying this on element style could be another solution:
> 
> `transform: [{ scaleX: 1.5 }, { scaleY: 1.5 }]`

@Ho3ein-Boka Thanks buddy. This is so brilliant of you. 👍
