### ISSUE TITLE
Bug Icon used 

### ISSUE THREAD

**Issue by adailsonm** [GeekyAnts/NativeBase#2428]
Hello,
you are using the native 2.8.1 base, since the Icon is not working on Android. 
To mobile (USB) 
`<Icon type = "FontAwesome" name = "plus" />`

**Comment by YunyunZhai** [comment]
+1

**Comment by YunyunZhai** [comment]
how to fix?

**Comment by YunyunZhai** [comment]
> Hello,
> you are using the native 2.8.1 base, since the Icon is not working on Android.
> To mobile (USB)
> `<Icon type = "FontAwesome" name = "plus" />`

i have fix it ,it is because i forget to react-native link

**Comment by SupriyaKalghatgi** [comment]
@adailsonm As per @YunyunZhai , did you run `react-native link`?
