### ISSUE TITLE
Fab: undefined error

### ISSUE THREAD

**Issue by impguard** [GeekyAnts/NativeBase#2430]
## Issue Description

Trying to get a Fab working in a really simple setup leveraging the latest versions of Expo, Native Base, and React Native.

My very simple app has a top level App that mimics the example I'm seeing in NativeBase-kitchen sync:

```
import React from 'react'

import {
  View,
  Container,
  Header,
  Left,
  Body,
  Title,
  Button,
  Icon,
  Right,
  Content,
  Text,
  Fab,
} from 'native-base'

export default class App extends React.Component {
  constructor(props) {
    super(props)
    this.state = {
      active: 'true'
    }
  }

  render() {
    return (
      <Container>
        <Header />
        <View style={{ flex: 1 }}>
          <Fab
            active={this.state.active}
            direction="up"
            containerStyle={{ }}
            style={{ backgroundColor: '#5067FF' }}
            position="bottomRight"
            onPress={() => this.setState({ active: !this.state.active })}>
            <Icon name="share" />
            <Button style={{ backgroundColor: '#34A34F' }}>
              <Icon name="logo-whatsapp" />
            </Button>
            <Button style={{ backgroundColor: '#3B5998' }}>
              <Icon name="logo-facebook" />
            </Button>
            <Button disabled style={{ backgroundColor: '#DD5144' }}>
              <Icon name="mail" />
            </Button>
          </Fab>
        </View>
      </Container>
    )
  }
}
```

### Expected behaviour

Expect it to work, look just like a blank screen with a simple FAB.

### Actual behaviour

![image](https://user-images.githubusercontent.com/1912284/48310568-13f38d00-e546-11e8-8ea5-09f0aeddbbde.png)

### Steps to reproduce

1. Create a blank expo project using the expo CLI
2. Install native base
3. Copy paste the bare example
4. See an error

**Comment by SupriyaKalghatgi** [comment]
Follow instructions as per issue template https://github.com/GeekyAnts/NativeBase/blob/master/ISSUE_TEMPLATE.txt

Failing which this issue will be closed today
