### ISSUE TITLE
problem installing in new project of react native 

### ISSUE THREAD

**Issue by gorge2004** [GeekyAnts/NativeBase#2432]
hi , please i need your help , i am trying to installing native base in a new project of react native but i hadnt can to do it because it throws error . it has been happen from new way/version of installing react-native with expo as the documentation establishes
 here is a capture
![native base](https://user-images.githubusercontent.com/20888572/48347270-25c35600-e654-11e8-9b39-778733ff767b.png)

**Comment by moyeen52** [comment]
sudo npm cache clear --force
sudo npm i -g npm 
npm cache verify
sometimes these helps. Please let me know if you still face the issue. I tied installing a new but can't find any issue in my local.

**Comment by gorge2004** [comment]
i did that , but nothing . i didnt get solution 

![native base 2](https://user-images.githubusercontent.com/20888572/48372274-82defc00-e694-11e8-8ecb-53c6aff1c93c.png)

**Comment by moyeen52** [comment]
Seems like your git is not added to your $PATH variable. Can you add git in your environment variable? 
https://stackoverflow.com/questions/26620312/installing-git-in-path-with-github-client-for-windows  Here are some instructions.

**Comment by gorge2004** [comment]
hey , i follow the instruction https://stackoverflow.com/questions/26620312/installing-git-in-path-with-github-client-for-windows like they are specificating but  inside the **AppLocal**  directory  does not exist github folder , here capture
![applocal](https://user-images.githubusercontent.com/20888572/48386923-0e26b480-e6ca-11e8-9d65-84aec0652295.png)

**Comment by gorge2004** [comment]
Ready!!. i decided to reinstall git and fixed
