### ISSUE TITLE
Ducuments

### ISSUE THREAD

**Issue by sajaddp** [GeekyAnts/NativeBase#2436]
Hi,
When do you update the document at https://docs.nativebase.io ?

**Comment by SupriyaKalghatgi** [comment]
https://github.com/GeekyAnts/native-base-docs/issues/152

**Comment by sajaddp** [comment]
I didn't catch you.
The document on the link has not been updated since v2.6

**Comment by suvenduchhatoi** [comment]
@sajaddp You can check now.Docs upto v2.9.0 have been released...
