### ISSUE TITLE
Card/CardItem borderRadius hardcoded on theme

### ISSUE THREAD

**Issue by ganlub** [GeekyAnts/NativeBase#2437]
## I have gone through these following points
- [x]   Check latest documentation: https://docs.nativebase.io/
- [x]   Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x]   Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [x]   Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [x]   For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- [x]   For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

### node, npm, react-native, react and native-base version, expo version if used, xcode version
node: 11.1.0
npm: 6.4.1
react: 16.6.0-alpha.8af6728
native-base: 2.8.1

### Expected behaviour
When setting the theme variable `cardBorderRadius`, `CardItem` should use it too.

### Actual behaviour
`Card` gets the set radius but `CardItem` doesn't, since it's [hardcoded](https://github.com/GeekyAnts/NativeBase/blob/master/src/theme/components/CardItem.js#L189) to `2` instead of `variables.cardBorderRadius`. A work around if you haven't ejected the theme could be to set the props `first` and `last` on your `CardItem`.

### Steps to reproduce

```
<Card>
    <CardItem>
      <Body>
        <Text>Foo bar</Text>
      </Body>
    </CardItem>
  </Card>
```
Output:
![image](https://user-images.githubusercontent.com/1272617/48473158-30b6eb80-e7f8-11e8-965f-80cd569b239e.png)

### Is the bug present in both iOS and Android or in any one of them?
Present in both.

### Any other additional info which would help us debug the issue quicker.
I am only using one `CardItem` per `Card`, I wonder if my proposed solution would behave as expected in case of multiple `CardItem`, header, footer and/or image.

**Comment by suvenduchhatoi** [comment]
@ganlub 
Yes, inside cardItem.js the change is to updated soon...
borderRadius: variables.cardBorderRadius,

**Comment by ganlub** [comment]
@suvenduchhatoi Yeah, as I stated on the issue that would solve it.
