### ISSUE TITLE
Issue with Web Customizer Export variable.js

### ISSUE THREAD

**Issue by b33son** [GeekyAnts/NativeBase#2438]
Export in Web version of Customizer not exporting values. Here: https://nativebase.io/customizer/#

### Expected behaviour
Export should export color values selected in the user interface

### Actual behaviour
Selecting "Download Variable File" downloads Variable.js, but the file does not contain the colors selected in the UI. 

### Steps to reproduce
Go here: https://nativebase.io/customizer/
Customize a color variable using the color picker (ideally a unique value) (i.e. BD10E0). Take note of the value selected. 
Click download icon, then "Download Variable File"
Open Variable.js and search for the color variable. 
The value will not be found.

**Comment by suvenduchhatoi** [comment]
@b33son  
There won't be any variable named 'color' in variable.js, instead there will be variable names as 'segmentActiveTextColor' , 'segmentBorderColor', 'checkboxBgColor' ....etc...corresponding to the component you are looking to customize...

**Comment by suvenduchhatoi** [comment]
@b33son 
The hexadecimal value for the color may not appear in the downloaded file, but the corresponding RGBA notation does come, which is just the same thing, just another representation of the Hex code...
For e.g- If you change a color to '878AA4' hex value, then the downloaded file comes with value 'rgba(135,138,164,1)'....You can also see the RGB values by the side of the hex value you are supplying, during customization...

**Comment by b33son** [comment]
Ah you are right. Sorry for the confusion
