### ISSUE TITLE
iosStatusbar value ignored if using material variables

### ISSUE THREAD

**Issue by tokict** [GeekyAnts/NativeBase#2439]
## Issue Description
Whatever I put in material.js for value of iosStatusbar is ignored and light-content is applied

### node, npm, react-native, react and native-base version, expo version if used, xcode version
Rn 0.55.4
NB 2.8.1
IOS 12.1

### Expected behaviour
Change status bar according to iosStatusbar in variables file

### Actual behaviour
Status bar is always light

### Steps to reproduce
Change status bar type at param  "iosStatusbar" in variables file on iOS and notice it doesn't care

### Is the bug present in both iOS and Android or in any one of them?
iOS

### Any other additional info which would help us debug the issue quicker.
Remove hardcoding of value in file "/basic/Header.js" from 
`
 barStyle={
            this.props.iosBarStyle
              ? this.props.iosBarStyle
              : platformStyle === "material"
                ? "light-content"
                : variables.iosStatusbar
          }`

to 
`
 barStyle={
            this.props.iosBarStyle
              ? this.props.iosBarStyle
              :  variables.iosStatusbar
          }`

**Comment by suvenduchhatoi** [comment]
@tokict 
Use <Header iosBarStyle="dark-content"> in your view layout to override your styling even if you have injected 'material' theme in your project...
but it is a convention that "material" theme should use iosStatusbar ="light-content" because it has a blue-coloured background... So this is followed in
```
barStyle={ this.props.iosBarStyle ? this.props.iosBarStyle : platformStyle === "material" ? "light-content" : variables.iosStatusbar }
```

**Comment by suvenduchhatoi** [comment]
Closing the issue due to no response...Hope it got fixed
