### ISSUE TITLE
Item component with double Icon use case

### ISSUE THREAD

**Issue by jaspervanbrian** [GeekyAnts/NativeBase#2441]
## Issue Description
Hello, I have this Item component in a Form tag. I'm validating from the server- side and setting the error and Icon dynamically through redux.

For example, the email component:
```js
<Item floatingLabel error={this.props.validate_register.errors.hasOwnProperty("email")}>
    <Label>Email Address</Label>
    <Input
        autoCapitalize='none'
        onChangeText={
            (email) => {
                this.setState({ email })
             }
        }
    />
    {this.props.validate_register.errors.hasOwnProperty("email") && <Icon name="close-circle" />}
</Item>
```
Without errors:
![image](https://user-images.githubusercontent.com/24638813/48573700-05431680-e948-11e8-8a69-06347702500e.png)

With errors:
![image](https://user-images.githubusercontent.com/24638813/48573718-12f89c00-e948-11e8-9067-97c6a390ebf3.png)

Now this looks fine. But I want to do it in the `<Item>` password component also. I did this:

```js
<Item floatingLabel error={this.props.validate_register.errors.hasOwnProperty("password")}>
    <Label>Password (At least 6 chars.)</Label>
    <Input
        secureTextEntry={this.state.securePasswordEntry}
        onChangeText={
            (password) => {
                this.setState({ password })
             }
        }
    />
    {this.props.validate_register.errors.hasOwnProperty("password") && <Icon name="close-circle" />}
    <Icon active name={this.state.eye} onPress={this.toggleEye}/>
</Item>
```
Now this spawns an error:
![image](https://user-images.githubusercontent.com/24638813/48574055-222c1980-e949-11e8-8fe5-8571ad44a45d.png)

This works, but hardcoding the icon defeats a purpose of validation:
```js
    // ...
    <Icon name="close-circle" />
    <Icon active name={this.state.eye} onPress={this.toggleEye}/>
    // ...
```

Tried swapping the two lines also, no luck:
```js
    <Icon active name={this.state.eye} onPress={this.toggleEye}/>
    {this.props.validate_register.errors.hasOwnProperty("password") && <Icon name="close-circle" />}
```
### node, npm, react-native, react and native-base version, expo version if used, xcode version

Node: 10.6.0
npm: 6..4.1
"native-base": "^2.8.1",                                                                                                                                                                  
"react": "16.6.0-alpha.8af6728",                                                                                                                                                          
"react-native": "0.57.4",

### Expected behaviour
![image](https://user-images.githubusercontent.com/24638813/48574277-bf874d80-e949-11e8-8163-8d35c7983231.png)

### Actual behaviour
![image](https://user-images.githubusercontent.com/24638813/48574055-222c1980-e949-11e8-8fe5-8571ad44a45d.png)

**Comment by jaspervanbrian** [comment]
@SupriyaKalghatgi mind taking a look?

**Comment by SupriyaKalghatgi** [comment]
Didn't find any issue
![image](https://user-images.githubusercontent.com/13464885/50397510-d3b73980-0796-11e9-86b0-df9d66bbbc59.png)

**Comment by SupriyaKalghatgi** [comment]
Closing this issue due to no response
Please reopen this issue if needed

**Comment by jaspervanbrian** [comment]
Hello again, as you read at the summary, my expected behavior was with two `<Icon>`s **with error highlighting (programmatically turned)**. Have you tried that?

**Comment by jaspervanbrian** [comment]
Hey hello @SupriyaKalghatgi, any updates on this? Please
