### ISSUE TITLE
Question about broken change

### ISSUE THREAD

**Issue by userbq201** [GeekyAnts/NativeBase#2442]
react native 0.55.3
native base 2.5.2

from 14-15 november my app broken. FlatList very slow if above it has view with style or it contain onResfresh prop. Please help me.

**Comment by userbq201** [comment]
What could be the problem ? This is very critical

**Comment by userbq201** [comment]
I also published [question](https://github.com/facebook/react-native/issues/22307) in rn

**Comment by SupriyaKalghatgi** [comment]
FlatList is React Native component
So you can follow up on https://github.com/facebook/react-native/issues/22307
