### ISSUE TITLE
How can I get ListItem index of List dataArray?

### ISSUE THREAD

**Issue by JChristensen97** [GeekyAnts/NativeBase#2443]
Hi there,
I'm wanting to access the index of a <ListItem> thats being generated from <List> with dataArray.
For example:
```
<List dataArray={this.props.groceries} renderRow={(groceryListItem, index) =>
	<ListItem>	
		<Text>{index}</Text>
	</ListItem>
	}
>
</List>
```
However, this does not work. How can I access this dynamic index?
Thanks!

**Comment by SupriyaKalghatgi** [comment]
List is deprecated, use React Native's FlatList instead

**Comment by jindalashish** [comment]
you can use map function instead of dataarray to get index.

<List>
{
    this.props.groceries.map((froceryListItem,index)=>(
	<ListItem>	
		<Text>{index}</Text>
	</ListItem>
    )
}
>
</List>
