### ISSUE TITLE
"Setup with Web" error

### ISSUE THREAD

**Issue by hellobbq** [GeekyAnts/NativeBase#2448]
take this docs: https://docs.nativebase.io/docs/GetStarted.html

```
"react-native-web": "^0.9.8",
"native-base": "^2.8.1",

"@babel/plugin-proposal-class-properties": "^7.1.0",
"@babel/plugin-proposal-object-rest-spread": "^7.0.0"
```

### App.js
```js
import React, { Component } from 'react';
import {H1} from 'native-base'
import logo from './logo.svg';
import './App.css';

class App extends Component {
  render() {
    return (
      <div className="App">
        <header className="App-header">
          <img src={logo} className="App-logo" alt="logo" />
          <p>
            Edit <code>src/App.js</code> and save to reload.
          </p>
          <a
            className="App-link"
            href="https://reactjs.org"
            target="_blank"
            rel="noopener noreferrer"
          >
            <H1>Learn React</H1>
          </a>
        </header>
      </div>
    );
  }
}

export default App;

```

errors: 
```
Failed to compile
./node_modules/native-base-shoutem-theme/src/connectStyle.js
SyntaxError: path\testd\node_modules\native-base-shoutem-theme\src\connectStyle.js: Unexpected token (384:10)

  382 |         const { addedProps, style } = this.state;
  383 |         return (
> 384 |           <WrappedComponent
      |           ^
  385 |             {...this.props}
  386 |             {...addedProps}
  387 |             style={style}
```

**Comment by ArThoX** [comment]
Same issue for me.

`
"dependencies": {
    "@types/react": "^16.7.18",
    "native-base": "^2.8.0",
    "react": "^16.7.0",
    "react-art": "^16.7.0",
    "react-dom": "^16.7.0",
    "react-native": "0.57.8",
    "react-native-web": "^0.9.13",
    "react-redux": "^6.0.0"
  },
  "devDependencies": {
    "@babel/core": "^7.2.2",
    "@babel/plugin-proposal-class-properties": "^7.2.3",
    "@babel/preset-env": "^7.2.3",
    "@babel/preset-react": "^7.0.0",
    "babel-jest": "23.6.0",
    "babel-loader": "^8.0.4",
    "babel-plugin-react-native-web": "^0.9.13",
    "jest": "23.6.0",
    "metro-react-native-babel-preset": "0.51.1",
    "react-test-renderer": "16.6.3",
    "tslint": "^5.12.0",
    "typescript": "^3.2.2",
    "webpack": "^4.28.3",
    "webpack-cli": "^3.1.2",
    "webpack-dev-server": "^3.1.14"
  },
`

**Comment by ArThoX** [comment]
Hi

Indeed and as highlighted in the docs, this seems to be no other solution that to eject and edit webpack configuration to include the missing dependencies. 

https://rawgit.com/GeekyAnts/native-base-docs/v2.8.0/_book/docs/GetStarted.html

**Comment by suvenduchhatoi** [comment]
![screen shot 1440-05-03 at 4 44 49 pm](https://user-images.githubusercontent.com/44160581/50896160-39a9ef00-142e-11e9-9fcc-63cd0ed4f4e8.png)
@hellobbq @ArThoX @M144-Coder 
It seems to be an issue. We are trying to resolve it as soon as possible...

**Comment by PhfManager** [comment]
same here 👍 
Failed to compile.

./node_modules/native-base-shoutem-theme/src/StyleProvider.js
SyntaxError: C:\dev\React\ReactNative\PHF_Manager-master\node_modules\native-base-shoutem-theme\src\StyleProvider.js: Support for the experimental syntax 'classProperties' isn't currently enabled (10:20):

   8 |  */
   9 | export default class StyleProvider extends React.Component {
> 10 |   static propTypes = {
     |                    ^
  11 |     children: PropTypes.element.isRequired,
  12 |     style: PropTypes.object,
  13 |   };

Add @babel/plugin-proposal-class-properties (https://git.io/vb4SL) to the 'plugins' section of your Babel config to enable transformation.

**Comment by SupriyaKalghatgi** [comment]
Working procedure here https://github.com/GeekyAnts/NativeBase-KitchenSink/blob/web-support/README.md#to-create-new-react-app
