### ISSUE TITLE
Restrict content scroll position to scroll height

### ISSUE THREAD

**Issue by indapublic** [GeekyAnts/NativeBase#2449]
I have `Content` with many child component. My task is scroll `Content` to exact component.

```
<Content ref={ref => this.contentRef = ref}>
    <SomeComponent />
    <SomeComponent />
    <SomeComponent />
    <SomeComponent />
    ...
    <SomeComponent />
    <SomeComponent ref={ref => this.targetRef = ref} />
</Content>
```

I'm using this code.

```
scrollToCenter = () => {
    setTimeout(() => {
      if (this.contentRef && this.targetRef) {
        const UIManager = NativeModules.UIManager;
        UIManager.measureLayoutRelativeToParent(
          findNodeHandle(this.targetRef),
          (err) => {},
          (targetX, targetY) => {
            this.contentRef._root.scrollToPosition(0, targetY, true);
          }
        );
      };
    }, 0);
  }
```

If the target component is at the top of the list or in the center, it works well.
If the target component is at the very bottom I see empty area after the content below after scrolling.

<img width="245" alt="djfil" src="https://user-images.githubusercontent.com/856260/48672183-46bd0700-eb7e-11e8-915e-ddfdf2521b47.png">

How I can restrict this scrolling to content height (or what checks I should to do before scrolling).

**Comment by SupriyaKalghatgi** [comment]
NativeBase Content is a replacement for React Native ScrollView.
So you can check how ScrollView works in this case
