### ISSUE TITLE
Footer Tabs Question - How to make it work?

### ISSUE THREAD

**Issue by allanesquina** [GeekyAnts/NativeBase#245]
Hi guys, I'm a noob in RN yet, but I found this awesome project and it's saving a lot of time. 
My question is, how to make footer tabs work like tabs? The docs just show the buttons, but there's no behavior on that. How to show a view/content when I click on a button?
Should I implement it manually for each screen? Is there some example?

Thanks :+1:

**Comment by sankhadeeproy007** [comment]
Adding the behaviour is left to the user. You'll find a very basic example of switching between tabs here. 
https://github.com/GeekyAnts/NativeBase-KitchenSink/blob/master/js/components/anatomy/index.js

**Comment by allanesquina** [comment]
Thanks for the quick reply @sankhadeeproy007!
I got the idea, I'm gonna do some tests here. :+1:

**Comment by allanesquina** [comment]
Hi, FYI, I've made on that way and it works fine. :+1: 

``` 
...
renderSelectedTab () {
    switch (this.state.selectedTab) {
      case 'welcome':
        return (<Welcome />);
        break;
      case 'profile':
        return (<Profile />);
        break;
      case 'login':
        return (<Login />);
        break;
      default:
    }
  }
...
```
```
  render() {
    return (
         ...
          <Content>
            {this.renderSelectedTab()}
          </Content>
         
        <Footer >
          <FooterTab>
            <Button active={this.state.selectedTab==='profile'} 
               onPress={() => this.setState({selectedTab: 'profile'})} >
                Profile
              <Icon name="ios-apps-outline" />
            </Button>
           ...
          </FooterTab>
        </Footer>

     );
  }
}

```

**Comment by sankhadeeproy007** [comment]
Lovely!

**Comment by iMokhles** [comment]
@allanesquina example working well but it's lagging unfortunately :(

**Comment by allanesquina** [comment]
Hey @iMokhles, how's going? 
I don't know how you have structured your app, but maybe could be a good idea to extract that part to a new component, so that you can use  `shouldComponentUpdate` to avoid unnecessary re-rendering. This is just an idea, I'm not working with React Native anymore.

**Comment by hjJunior** [comment]
@iMokhles I have the same issue that you, do you have got it some way to avoid ladding, I've tried `shouldComponentUpdate` but, I don't see any better :(

**Comment by Anandks1993** [comment]
How to transfer props though footer tab ?

**Comment by nihp** [comment]
How to set footer images using react native tab navigator?

**Comment by akhil1988** [comment]
@Anandks1993 can you explain more

**Comment by Anandks1993** [comment]
@akhil1988 I just want to do it like passing props from one component to other. For eg if am in one footer tab, I want to take some details from that to another tab.

**Comment by akhil-geekyants** [comment]
@Anandks1993 if you wan't to share some value, then you can store it in the state. If you want to set some style based on selection you can do that based on that condition of selection. As this is a React Native question you can ask in stackoverflow, you can get more suggestions and answers there.

**Comment by akhil-geekyants** [comment]
@nihp you can use `<Image/>` inside `<Button/>` and set some width and height.

**Comment by Anandks1993** [comment]
@akhil-geekyants Okay sure, Thank you. 😃 🤝

**Comment by HamadaFMahdi** [comment]
if anyone wanted something better:

https://snack.expo.io/@react-navigation/tabs-with-icons

this is using the react-navigation package, it comes with swipe and animation support built in (check lines 53 and 54 and set them to true before running the simulator).



PS if you're confused on how to actually use this in a project (basically if you're new to RN) with different components, in the example they've defined the the components for each tab in the same file, in your case you'll probably want to create separate files for each tab component then import it in using:

import tabCompoenentName from './path/to/component'

**Comment by HamadaFMahdi** [comment]
you can use this instead:

https://reactnavigation.org/docs/en/tab-based-navigation.html

comes with animation and swipe built in :))

**Comment by CeamKrier** [comment]
Ahoy,

For the ones that still having trouble with the 'lagging' behavior of the tabs while transiting from one to another, the issue is originating from the creation of the new tab content instance on every tab change. 

![image](https://user-images.githubusercontent.com/18554425/66956791-b200a900-f06d-11e9-80e2-7eb0cf9b9fa0.png)

You would notice the lag even stronger if you have a large data set that is displaying a ScrollView or even with FlatList. 

So the solution can be to have multiple `<Content>` and toggling their visibility state via the style. 

![image](https://user-images.githubusercontent.com/18554425/66957478-00627780-f06f-11e9-9f14-85a69fa60a2f.png)

With this approach, you would assure that your components render only **once** and you won't suffer from that lagging behavior.

**Comment by hemalrathod** [comment]
> Hi, FYI, I've made on that way and it works fine. 👍
> 
> ```
> ...
> renderSelectedTab () {
>     switch (this.state.selectedTab) {
>       case 'welcome':
>         return (<Welcome />);
>         break;
>       case 'profile':
>         return (<Profile />);
>         break;
>       case 'login':
>         return (<Login />);
>         break;
>       default:
>     }
>   }
> ...
> ```
> 
> ```
>   render() {
>     return (
>          ...
>           <Content>
>             {this.renderSelectedTab()}
>           </Content>
> 
>         <Footer >
>           <FooterTab>
>             <Button active={this.state.selectedTab==='profile'} 
>                onPress={() => this.setState({selectedTab: 'profile'})} >
>                 Profile
>               <Icon name="ios-apps-outline" />
>             </Button>
>            ...
>           </FooterTab>
>         </Footer>
> 
>      );
>   }
> }
> ```

This has been a very useful code for me. Thanks.
