### ISSUE TITLE
Invariant Custom Accordion

### ISSUE THREAD

**Issue by hai-ru** [GeekyAnts/NativeBase#2450]
I already read doucmentation and followed it.

this doc : https://docs.nativebase.io/Components.html#accordion-custom-header-content-headref
and I've got error message
![screenshot from 2018-11-19 13-11-46](https://user-images.githubusercontent.com/24634668/48690348-ae1b9b00-ec00-11e8-863b-a648db964e61.png)
![screenshot from 2018-11-19 13-10-54](https://user-images.githubusercontent.com/24634668/48690349-ae1b9b00-ec00-11e8-94b0-46c8022c277f.png)
![screenshot from 2018-11-19 13-41-00](https://user-images.githubusercontent.com/24634668/48690373-c986a600-ec00-11e8-99a3-81f3781a5b12.png)
![image](https://user-images.githubusercontent.com/24634668/48690392-e7eca180-ec00-11e8-8e8e-50406693df2c.png)

**Comment by SupriyaKalghatgi** [comment]
Please refer example here https://github.com/GeekyAnts/NativeBase-KitchenSink/blob/master/src/screens/accordion/accordion-custom-header-content.js
