### ISSUE TITLE
Icon alignment in form item incorrect when using stackedLabel

### ISSUE THREAD

**Issue by janpieterz** [GeekyAnts/NativeBase#2451]
## I have gone through these following points
- [x]   Check latest documentation: https://docs.nativebase.io/
- [x]   Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x]   Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [x]   Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [x]   For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- [x]   For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

## Issue Description
A stackedLabel on an item causes icons to not follow the 'sorting' (left/right of input).

### node, npm, react-native, react and native-base version, expo version if used, xcode version
Node: 8.12.0
NPM: 6.4.1
React-Native: 0.57.4
React: 16.6.0-alpha.8af6728
Native Base: 2.8.1

### Expected behaviour
Icon alignment changes based on order within <Item> element.

### Actual behaviour
Icon is always aligned at front of <Item> when using stackedLabel
![img_1485](https://user-images.githubusercontent.com/383634/48760350-f93bb980-eca5-11e8-8dfa-760171cff41c.JPG)

### Steps to reproduce

Create a form with stackedLabel items and an icon on the left and right.
Code snippet can be found here: https://snack.expo.io/H1GIXBbAX

The first two are stackedLabel icons (one before, one after) and second two are floatingLabel icons, showing the difference.

### Is the bug present in both iOS and Android or in any one of them?
Confirmed on iOS on real device and Android on emulator. Presumably both.

### Any other additional info which would help us debug the issue quicker.
Other report from @eaazumah (https://github.com/GeekyAnts/NativeBase/issues/1102#issuecomment-433755226)

There have been some changes to the code recently. 
Seemingly relevant bit: https://github.com/GeekyAnts/NativeBase/blob/master/src/basic/Item.js#L337

**Comment by suvenduchhatoi** [comment]
@janpieterz 
This could be due to the difference in default stylings defined for stackedLabel and floatingLabel...
Either you can try inline styling 
```
<Item stackedLabel>
              <Label>Username</Label>
              <Icon
                name="ios-home"
                style={{
                  left: 340,
                }}
              />
              <Input />
            </Item>
```
or refer to customization section of Native-Base to define your own styling for them...

**Comment by janpieterz** [comment]
I've not changed the styling at all, so just using default (also visible in the snack as the default styles cause this). 
Just tried the suggestion (left: 340) and this works indeed. Looking at the styling there's nothing specifically for stackedlabel icons (https://github.com/GeekyAnts/NativeBase/blob/master/src/theme/components/Item.js), nor any other label with regards to order.
Any idea how to resolve this within the framework? Not sure if there's a way to style for element order (before/after Input).

**Comment by suvenduchhatoi** [comment]
@janpieterz 
You can define your custom styling for element order in Item.js after ejecting native-base-theme

**Comment by janpieterz** [comment]
@suvenduchhatoi Yeah, it's fixed in our projects, but isn't this the behavior that should work by default?

**Comment by suvenduchhatoi** [comment]
By default, we are implementing UI design patterns following some basic native guidelines and conventions for a broader range of usage...That's why customization is always open for specific purposes...Hope your issue is solved.
Closing the issue now. You can reopen if you need to...

**Comment by suvenduchhatoi** [comment]
@janpieterz  Got around your issue again... 
Yes, we are on it to fix the stackedLabel icon styling soon from the library itself...
floatingLabel works fine-you can make adjustments in your code snippet as per this sample
![screen shot 1440-05-25 at 3 39 59 pm](https://user-images.githubusercontent.com/44160581/52047768-bcc2ee80-256f-11e9-8b2e-36819d788442.png)

**Comment by hanykumar** [comment]
Hi @janpieterz , Using `Icon` with `stackedLabel` restricted to left only. We will work on it. Closing for now.
Thanks.
