### ISSUE TITLE
Support  FontAwesome5 icons

### ISSUE THREAD

**Issue by cadoman** [GeekyAnts/NativeBase#2452]
## Issue Description

The set FontAwesome5 from react-native-vector-icons is not available in NativeBase  

###  native-base version
- native-base : v2.8.1

### Expected behaviour
Renders the `pen-fancy` icon from FontAwesome5
### Actual behaviour
FontAwesome5 is not recognized : 
```
Warning: Failed prop type: Invalid prop `type` of value `FontAwesome5` supplied to `IconNB`, expected one of ["Entypo","EvilIcons","Feather","FontAwesome","Foundation","Ionicons","MaterialCommunityIcons","MaterialIcons","Octicons","SimpleLineIcons","Zocial"]
```

### Steps to reproduce
```javascript
        <Button>
            <Icon  name='pen-fancy' type="FontAwesome5" />
        </Button>
```

**Comment by SupriyaKalghatgi** [comment]
Added FontAwesome 5 icons
Available on master, commit https://github.com/GeekyAnts/NativeBase/commit/34a99bd2268d737060bd3167460f6dd9039be436

**Comment by Veikedo** [comment]
@SupriyaKalghatgi this breaks work with CRNA since @expo/vector-icons does not contain FontAwesome5.

Here is what I have now:

` Unable to resolve "@expo/vector-icons/FontAwesome5" from "node_modules\native-base\dist\src\basic\IconNB.js"`

**Comment by SupriyaKalghatgi** [comment]
@Veikedo Yes I am aware of it
You can report this to the expo team, not NativeBase issue

**Comment by SupriyaKalghatgi** [comment]
Till expo releases this fix, you can continue with previous versions

**Comment by Veikedo** [comment]
@SupriyaKalghatgi seems like they are not going to fix this.

https://github.com/expo/vector-icons/issues/58

**Comment by Veikedo** [comment]
@farisT use prev version of native-base (2.8.2 afair)

**Comment by alexandervantrijffel** [comment]
Why do you guys release a version to public that does not work at all? Its crazy...

**Comment by siradityaverma** [comment]
Anyone still facing this issue can 

1. Either downgrade to NativeBase 2.8.2 
2. To use the new version by editing the IconNB.js and IconNB.js.map in theNativeBase directory present in the node_modules folder. Remove the new commit and replace it with the old one. It removes the FontAwesome5 dependency which was the purpose of commit [34a99bd](https://github.com/GeekyAnts/NativeBase/commit/34a99bd2268d737060bd3167460f6dd9039be436?diff=split). This will help you work with Expo or CRNA projects.

By doing the second step, I haven't faced any failures. Will update if I stumble upon one.
