### ISSUE TITLE
Theme variable `androidRippleColor` is not applied to buttons unless rounded

### ISSUE THREAD

**Issue by chriswait** [GeekyAnts/NativeBase#2454]
## I have gone through these following points
- [x]   Check latest documentation: https://docs.nativebase.io/
- [x]   Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x]   Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [x]   Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [x]   For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- [x]   For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

### node, npm, react-native, react and native-base version, expo version if used, xcode version
node: `v10.11.0`
npm: `6.4.1`
react-native: `0.57.1`
native-base: `2.8.1`
expo: `31.0.5`
xcode: `10.1`

### Expected behaviour
Modifying `androidRippleColor` in `native-base-theme/variables/platform.js` affects the color used for the ripple effect in themed `<Button>` components on Android.

### Actual behaviour
Modifying has no effect unless button is rounded. If the button is _not_ rounded but _is_ transparent, the ripple color is set to be transparent and ignores `androidRippleColor` altogether.

### Steps to reproduce

1. Follow the instructions for Customize here: https://docs.nativebase.io/Customize.html#theaming-nb-headref (eject, wrap root component in `<StyleProvider>`, pass `platform` theme)
2. Modify `native-base-theme/variables/platform.js` such that androidRippleColor is changed to something obvious e.g 'red'
3. Add a `<Button>` component from NativeBase
4. Tap the button, expect to see customised ripple effect

### Is the bug present in both iOS and Android or in any one of them?
Android

### Any other additional info which would help us debug the issue quicker.
The code for Button.js reflects the behaviour I'm experiencing:

if the button is rounded:
https://github.com/GeekyAnts/NativeBase/blob/e96c997492d898d812243d7f19297189c75af4c0/src/basic/Button.js#L78

apply the ripple color:
https://github.com/GeekyAnts/NativeBase/blob/e96c997492d898d812243d7f19297189c75af4c0/src/basic/Button.js#L87

otherwise transparent:
https://github.com/GeekyAnts/NativeBase/blob/e96c997492d898d812243d7f19297189c75af4c0/src/basic/Button.js#L103

**Comment by JoaoBGusmao** [comment]
@SupriyaKalghatgi Why was this issue closed? I'm having the same problem, where I need to have a light button and cannot use androidRippleColor because it is only applied to rounded buttons. This doesn't make sense to me...
By the way, I thought about changing variables.androidRippleColor, but I can't do it, since it will change the behavior of the other buttons as well

**Comment by SupriyaKalghatgi** [comment]
@JoaoBGusmao Share code snippet along with output

**Comment by apperside** [comment]
I'm experiencing this issue as well, I solved it by setting the button as rounded and then overriding the borderRadius

```
<Button
	rounded
	bordered
	androidRippleColor="red"
	style={{ borderRadius: 5 }} //<-- override border radius with whatever value you want
	onPress={() => {}}>
	<Text>Primary</Text>
</Button>
```

**Comment by the-kenneth** [comment]
Still a bug in 2.13.8

**Comment by luiey** [comment]
Please have the ripple effect on transparent button as TouchableOpacity. It's like no interaction as it was like a text. I place the transparent button on native base header. Using TouchableOpacity will require me to overwrite the property of the text. I prefer native base button.

"native-base": "^2.13.12"
