### ISSUE TITLE
Scrollable Tabs Issue

### ISSUE THREAD

**Issue by paliwalsam** [GeekyAnts/NativeBase#2456]
Hi

http://docs.nativebase.io/Components.html#tabs-scrollable-headref

on left or right swipe , scroll not stop on next tab, it jumps on forth or fifth or last tab

In most of cases, scroll on swipe stops on last tab
![20181122_124859](https://user-images.githubusercontent.com/11517788/48887544-adc80d80-ee55-11e8-8f3a-ba5901425f4d.gif)

**Comment by suvenduchhatoi** [comment]
@paliwalsam 
Check this code. It works fine both in Ios and Android:

import React, { Component } from "react";
import { Container, Header, Tab, Tabs, ScrollableTab } from "native-base";
import Tab1 from "./tabOne";
import Tab2 from "./tabTwo";
import Tab3 from "./tabThree";
export default class TabsScrollableExample extends React.Component {
  render() {
    return (
      <Container>
        <Header hasTabs />
        <Tabs renderTabBar={() => <ScrollableTab />}>
          <Tab heading="Tab1">
            <Tab1 />
          </Tab>
          <Tab heading="Tab2">
            <Tab2 />
          </Tab>
          <Tab heading="Tab3">
            <Tab3 />
          </Tab>
        </Tabs>
      </Container>
    );
  }
}

Please go through ISSUE_TEMPLATE of GeekyAnts and post issues in the format specified in-
https://github.com/GeekyAnts/NativeBase/blob/master/ISSUE_TEMPLATE.txt

**Comment by bummiAltomatik** [comment]
is this problem solved? i have same issue about this component behaviors

**Comment by paliwalsam** [comment]
> is this problem solved? i have same issue about this component behaviors

resolve after following updates:
"react": "16.6.1"
"react-native": "0.57.7",
