### ISSUE TITLE
[Checkbox] [Android] "transparent" tick is not working - new minor release required

### ISSUE THREAD

**Issue by OtacilioN** [GeekyAnts/NativeBase#2457]
## I have gone through these following points
- [x]   Check latest documentation: https://docs.nativebase.io/
- [x]   Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x]   Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [x]   Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink

### node, npm, react-native, react and native-base version, expo version if used, xcode version
Node: v10.0.0
npm: 6.4.1
react-native: 0.57.5
react: 16.6.3
native-base: 2.8.1
I'm not using expo.

### Expected behaviour
Checkbox tick is transparent when unchecked.
![screen shot 2018-11-23 at 15 11 42](https://user-images.githubusercontent.com/10578275/48956926-65cbe800-ef34-11e8-8ce4-0408e352a1f4.png)

### Actual behaviour
Checkbox tick is visible. Changing NativeBase exported variables don't fix it.
![screen shot 2018-11-23 at 15 24 47](https://user-images.githubusercontent.com/10578275/48956933-6ebcb980-ef34-11e8-834d-7e0e2de962af.png)

### Steps to reproduce
Add CheckBox native-base component:
<CheckBox onPress={() => { return; } checked={this.state.isChecked} />

### Is the bug present in both iOS and Android or in any one of them?
Android only.

### Any other additional info which would help us debug the issue quicker.

I saw that has a related issue #2344 where this is already fixed, but this amazing fix is not released yet, so I had to work around this pointing my package.json import to: ``` "native-base": "git+https://github.com/GeekyAnts/NativeBase.git#e96c997492d898d812243d7f19297189c75af4c0",```

Since it is already fixed, is that possible release a minor patch to avoid that kind of import? ❤️

**Comment by navata** [comment]
"git+https://github.com/GeekyAnts/NativeBase.git#e96c997492d898d812243d7f19297189c75af4c0",
Have this commit merged to master ?

**Comment by OtacilioN** [comment]
Hey @navata this commit is already merged in master, but it is not already released, so I recommend you to change your package.json to point the nativeBase dependency to this fork while they not release a new version.

Change your package.json to: 

>     "native-base": "git+https://github.com/CESARBR/NativeBase.git#b81cc6d43d88388e112600153b4ad0b39e9beba2",
