### ISSUE TITLE
tabs : rotating screen bug

### ISSUE THREAD

**Issue by manukn** [GeekyAnts/NativeBase#246]
tabs renders incorrectly when rotating the screen .

**Comment by sankhadeeproy007** [comment]
Screenshots please.

**Comment by setancyber** [comment]
I face the same issue, the tabs renders incorrectly after rotating the screen from vertical to horizontal orientation and vice versa.

**Vertical Orientation**
![screenshot_2016-10-28-17-08-34](https://cloud.githubusercontent.com/assets/5510888/19803273/f6df2098-9d31-11e6-8067-e19b6e8e00b1.png)

**Horizontal Orientation**
![screenshot_2016-10-28-17-13-55](https://cloud.githubusercontent.com/assets/5510888/19803278/fcc87414-9d31-11e6-9895-64079a1ec1eb.png)

**Comment by SupriyaKalghatgi** [comment]
@manukn @setancyber Yes this is the case only with `Tabs`.

NativeBase will support this in its upcoming release.

**Comment by nico1510** [comment]
could you please let us know here in this issue as soon as it is fixed ?

**Comment by SupriyaKalghatgi** [comment]
Sure

**Comment by kirkjoan** [comment]
Do you have an update on this? I am facing same issue.
