### ISSUE TITLE
What time about release new version for fixing issue in RN 0.57 ?

### ISSUE THREAD

**Issue by navata** [GeekyAnts/NativeBase#2460]
Hi Guys,

Thanks for your package for design UI. But, I see that package have many issue in RN 0.57.
 Do you have release new version for this issue ?

Thanks.

**Comment by OtacilioN** [comment]
Would be an amazing idea, we have a lot of things already fixed and committed in master branch but unreleased.

**Comment by navata** [comment]
This commit fixed checkbox in Android. Can you talk me it merge to master ?
https://github.com/GeekyAnts/NativeBase.git#e96c997492d898d812243d7f19297189c75af4c0
