### ISSUE TITLE
StyleProvider Crashing Release Build

### ISSUE THREAD

**Issue by kailashvele** [GeekyAnts/NativeBase#2463]
## Issue Description
When using StyleProvider, the Released Signed APK of the App doesn't work on Android. While works on Emulator and in Dev Build as well but not on Release Build.

### node, npm, react-native, react and native-base version, expo version if used, xcode version
Node => 10.11.0
NPM => 6.4.1
ReactNative => 0.57.6
React => 16.6.1
NativeBase => 2.8.1

### Expected behaviour
App should work fine without any error on installing the release build on a device.

### Actual behaviour
App installs and on opening the App, it crashes giving following error: App has Stopped. or App Keeps Stopping.

### Steps to reproduce
- react-native init App
- cd App
- yarn add native-base
- react-native link
- Eject the native-base themes
- Apply StyleProvider to the App.js file
- Generate Signed APK
- Build Release
- Install app-release.apk on Android and Open the App.

### Is the bug present in both iOS and Android or in any one of them?
No IOS device to check, Currently present on Android though.

### Any other additional info which would help us debug the issue quicker.
Nothing I can suggest about as I have tried many things and then found the problem and steps to reproduce are the only steps I can provide quick tracking.

**Comment by kailashvele** [comment]
Any updates Team? Or some direction that I need to look into?

**Comment by matthewfbenjamin** [comment]
I have the same issue. I cannot say for sure that it is a `NativeBase` issue, but I think it is. The error I am getting is:
`com.facebook.react.common.JavascriptException: undefined is not an object (evaluating 'Sn[e]'),`

Here are my specs:
```
"native-base": "2.7.0",
"react": "16.4.1",
"react-native": "0.56.1",

Node: 8.12.0
NPM 6.4.1
```

**Comment by kailashvele** [comment]
Disappointed with no support or even suggestion to look into particular direction.
