### ISSUE TITLE
Lack of testID on native base component types result in Property 'testID' does not exist on type 'IntrinsicAttributes  error

### ISSUE THREAD

**Issue by vnovick** [GeekyAnts/NativeBase#2466]
## I have gone through these following points
- [X]   Check latest documentation: https://docs.nativebase.io/
- [X]   Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [X]   Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [X]   Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [X]   For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- [X]   For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

### node, npm, react-native, react and native-base version, expo version if used, xcode version
native-base@2.8.1
react-native@0.55.4
react@16.3.1
xcode 10

### Expected behaviour

testID to be declared on all Native base types

### Actual behaviour

inside index.d.ts there is no declaration of testID on any of native base types
which result in the following error when adding testID on Native base components
>Property 'testID' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Container> & Readonly<{ children?: ReactNode; }> & Readonly<Container>'.

### Steps to reproduce
In Typescript project add `testID` on `Container` component

**Comment by SupriyaKalghatgi** [comment]
Commit https://github.com/GeekyAnts/NativeBase/commit/5d6c1556799aba7549f11a274d1273b63d0e6530

**Comment by gs-rranjan** [comment]
commit: https://github.com/GeekyAnts/NativeBase/commit/5d6c1556799aba7549f11a274d1273b63d0e6530 
adds testId in native base components, but testId is supported only for IOS,  accessibilityLabel and accessible fields are also needed for working with android. 

Someone please look into this.
