### ISSUE TITLE
FAB has to be keyboard responsive

### ISSUE THREAD

**Issue by sarathvad1811** [GeekyAnts/NativeBase#2468]
!!!!NOT AN ISSUE!!!! 
## Issue Description
I know that we cannot use FAB inside a Content(ScrollView). but how can I make a FAB(which is now at the bottom right position) keyboard responsive... i.e. when keyboard it pushes itself above the keyboard and goes down to bottom right when keyboard is close

react-native: 0.53.2
react: 16.2.0
native-base: 2.3.9

### Expected behaviour
FAB has to adjust itself based on whether keyboard is open or not

### Actual behaviour
It should be keyboard responsive.

### Is the bug present in both iOS and Android or in any one of them?
Both

**Comment by suvenduchhatoi** [comment]
@sarathvad1811 
Please refer this link:-
https://medium.freecodecamp.org/how-to-make-your-react-native-app-respond-gracefully-when-the-keyboard-pops-up-7442c1535580
