### ISSUE TITLE
Tabs Border bottom not getting removed.

### ISSUE THREAD

**Issue by tarun29061990** [GeekyAnts/NativeBase#2469]
## Issue Description
So I have done all the css changes for disabling the bottom border but no success. What I am doing wrong here?

## Code
```
<Tabs tabBarUnderlineStyle={{borderBottomWidth:0, shadowColor: 'transparent', elevation: 0}}
              initialPage={0}
              renderTabBar={()=> <ScrollableTab />} 
              onChangeTab={({i, ref, from}) => this.getAllProjects(ref.key.substr(2))}
        >
					{tabsData.map((value, key)=>{
            return (
              <Tab tabStyle={{borderBottomWidth:0,backgroundColor:'#fff', width: wp("35%")}} textStyle={{"color": "#000"}} activeTabStyle={value.activeTabStyle} activeTextStyle={value.activeTextStyle} key={ value.tagName } heading={ value.name }>
                  {that.getContentOfTabs()}
              </Tab>
            );
          })}
</Tabs>
```

## Result

<img width="290" alt="screenshot 2018-11-28 at 4 32 48 pm" src="https://user-images.githubusercontent.com/1535607/49147670-49acba00-f32b-11e8-8395-948d31e7aa95.png">

## Versions

Node - 8.3.0
npm - 5.3.0
react-native-cli- 2.0.1
react-native- 0.57.1
native-base- 2.8.1
xcode- 9.4.1

**Comment by raajnadar** [comment]
This section is for tracking bugs and issue and not for asking how to questions..!

**Comment by tarun29061990** [comment]
@raajnadar  Sorry for the wrong title of the issue.

**Comment by tarun29061990** [comment]
Any updates on this??

**Comment by tarun29061990** [comment]
zIndex on tabStyle and activeTabStyle fixed the problem for me.

**Comment by rahamin1** [comment]
@tarun29061990 Can you post your code?

**Comment by CosmostakeR** [comment]
use this - tabContainerStyle={{ borderBottomWidth: 0 }}

**Comment by Abhijeet-Ashapure** [comment]
use this - tabContainerStyle={{ borderBottomWidth: 0 }}
