### ISSUE TITLE
Create a round Icon Button

### ISSUE THREAD

**Issue by cadoman** [GeekyAnts/NativeBase#2470]
Can I create a round icon Button with NativeBase such as pictured below?
![bell_ok](https://user-images.githubusercontent.com/15016365/49206962-fa5e9c00-f3b3-11e8-8c1f-7df1fb67141e.png)
I've had a few tries (see [here](https://stackoverflow.com/questions/53428343/cropped-icon-with-native-base-button) ) but without success.

**Comment by suvenduchhatoi** [comment]
@cadoman 
You are manually setting the height and width of both the Button and the Icon...So, you have to adjust the height and width of both accordingly as you want to keep your Icon inside the Rounded Button...If you want a bigger Icon, you have to give higher height and width values to Button as well...
You can go through style section of React-native docs for better understanding...as Native-Base uses it...
