### ISSUE TITLE
Switch component crashes the app

### ISSUE THREAD

**Issue by the-yadu** [GeekyAnts/NativeBase#2477]
## I have gone through these following points
- [x]   Check latest documentation: https://docs.nativebase.io/
- [x]   Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x]   Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [x]   Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [x]   For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- [x]   For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

### node, npm, react-native, react and native-base version, expo version if used, xcode version
node : v10.0.0
npm : 6.4.1
react : 16.4.2
react-native:0.56.0
### Expected behaviour

Upon using the switch component inside list component, the app should not crash

### Actual behaviour
Upon using the switch component inside list component, the app crashes without any warn info in debugger

### Is the bug present in both iOS and Android or in any one of them?
Only tested android

### Any other additional info which would help us debug the issue quicker.
I recently updated alot of libraries, This has happened after that.

**Comment by the-yadu** [comment]
<img width="349" alt="screenshot 2018-12-04 at 10 21 26 am" src="https://user-images.githubusercontent.com/7404181/49419868-cec22400-f7ae-11e8-8f7d-13a535cb4225.png">
This is the screenshot when Switch component is placed in the code and it crashes the app

**Comment by suvenduchhatoi** [comment]
Check this code snippet:
It works fine both in Android and Ios

```
import React, { Component } from "react";
import { ListItem, Switch } from "native-base";

export default class Switch extends Component {
  render() {
    return (
      <ListItem>
        <Switch value={true} />
      </ListItem>
    );
  }
}
```

Check your dependencies/libraries and their compatibility with react-native and native-base...
If the problem persists, then uninstall node_modules and run npm install, install other dependenies again and link them again with react-native

**Comment by SupriyaKalghatgi** [comment]
@the-yadu Closing this today in case of no response / code snippet

**Comment by the-yadu** [comment]
Even If I am using Switch directly from react native package.... its crashing... Did test all other points as well such as removed node_module folder, fresh npm install, npm reset cache... react native link is dangerous to do so I avoided it because few packages makes it duplicate linking and breaks the build.

**Comment by SupriyaKalghatgi** [comment]
If you are using Switch from React Native, then this is not the right place to raise this query

**Comment by suvenduchhatoi** [comment]
```
import React, { Component } from "react";
import {
  Container,
  Header,
  Content,
  List,
  ListItem,
  Text,
  Icon,
  Left,
  Body,
  Right,
  Button,
} from "native-base";
import { Switch } from "react-native";
export default class ListIconExample extends Component {
  render() {
    return (
      <Container>
        <Header />
        <Content>
          <ListItem icon>
            <Left>
              <Button style={{ backgroundColor: "#FF9501" }}>
                <Icon active name="ios-wifi" />
              </Button>
            </Left>
            <Body>
              <Text>Airplane Mode</Text>
            </Body>
            <Right>
              <Switch value={true} />
            </Right>
          </ListItem>
        </Content>
      </Container>
    );
  }
}
```
@the-yadu It is completely fine to import Switch from "react-native"...The above code runs fine both on Android and Ios...

**Comment by the-yadu** [comment]
@suvenduchhatoi and @SupriyaKalghatgi The code provided from you does not work with react native v:57.0

If you guys want you guys can close this issue. It seems to be a problem with facebook react native switch itself....

I am attaching some screenshots for reference


![Uploading Screenshot 2018-12-19 at 4.47.20 PM.png…]()
![Uploading Screenshot 2018-12-19 at 4.48.09 PM.png…]()

**Comment by suvenduchhatoi** [comment]
@the-yadu 
works with react-native:0.57.1

![screenshot 2018-12-19 at 5 16 31 pm](https://user-images.githubusercontent.com/44160581/50218420-e5bd6480-03b1-11e9-9c88-d35b8b28e44a.png)

**Comment by the-yadu** [comment]
It didnt.. I just installed v57.1 and removed node_module folder
Its crashing with an issue saying

`error: bundling failed: SyntaxError: /Users/narayan/Projects/manage_my_rides_mobile/node_modules/react-native/node_modules/react-native/Libraries/Components/Switch/Switch.js: Support for the experimental syntax 'nullishCoalescingOperator' isn't currently enabled (167:52):

  165 |         {...props}
  166 |         {...platformProps}
> 167 |         accessibilityRole={props.accessibilityRole ?? 'button'}
      |                                                    ^
  168 |         onChange={this._handleChange}
  169 |         onResponderTerminationRequest={returnsFalse}
  170 |         onStartShouldSetResponder={returnsTrue}`

**Comment by suvenduchhatoi** [comment]
Earlier, you had commented that you didn't run "react-native link" after installing packages...That is necessary...Then check it works or not...

**Comment by the-yadu** [comment]
@suvenduchhatoi 
By following the exact steps.. I got this error.
https://github.com/facebook/react-native/issues/4968


I have fallen back to v56.0
It fails to render the switch but the remaining app works fine. To continue the development I have to roll back.
