### ISSUE TITLE
Button in FooterTab always uses primary color. 

### ISSUE THREAD

**Issue by dwhiz** [GeekyAnts/NativeBase#248]
Hi, for some reason when I try to anything other than the primary color on a Button within in the FooterTab, it will not work. If I move the Button out of the tab the other colors are applied correctly? Any ideas?

**Comment by sankhadeeproy007** [comment]
Color for the text and icons you mean? Try changing the variables here
https://github.com/GeekyAnts/NativeBase/blob/master/Components/Themes/light.js#L110

**Comment by dwhiz** [comment]
@sankhadeeproy007 Thanks for the reply. I am talking about using an Button Component has a child in the FooterTab, I can't change the bg color. If I take that same Button and move it out of the FooterTab, the color is applied.

**Comment by SupriyaKalghatgi** [comment]
@dwhiz Button in FooterTab overrides certain props

https://github.com/GeekyAnts/NativeBase/blob/master/Components/Widgets/FooterTab.js#L78
