### ISSUE TITLE
Picker.item does not take integer values on Android

### ISSUE THREAD

**Issue by BoZhaoUTSC** [GeekyAnts/NativeBase#2482]
## I have gone through these following points
- [x]   Check latest documentation: https://docs.nativebase.io/
- [x]   Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x]   Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- []   Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- []   For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- []   For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

## Issue Description
App crush on Android when Picker.item takes an integer in value.
e.g. <Picker.Item label={0} value={0} />

### node, npm, react-native, react and native-base version, expo version if used, xcode version
node: v8.11.3
yarn: 1.12.3
react-native-cli: 2.0.1
react-native: 0.57.7
native-base: 2.8.0 // it also happens on 2.8.1
react: 16.6.1,
react-native": 0.57.7

### Expected behaviour
It should automatically convert label property to string or throw an error saying label property does not take integer.

### Actual behaviour
It works fine on iOS but crushing on Android.

### Steps to reproduce
```
<Form>
  <Picker
    mode="dropdown"
    iosHeader={"Header name"}
    iosIcon={<Icon name="ios-arrow-down-outline" />}
    selectedValue={this.state.selected}
    onValueChange={this.onValueChange.bind(this)}
    placeholder={"placeholder"}
  >
    <Picker.Item label={0} value={0} />
  </Picker>
</Form>
```

### Is the bug present in both iOS and Android or in any one of them?
Android only

**Comment by suvenduchhatoi** [comment]
@BoZhaoUTSC 
If you try to import Picker component from "react-native", it also behaves the same way, so it's a "react-native" issue actually...
![screenshot 2018-12-24 at 4 47 24 pm](https://user-images.githubusercontent.com/44160581/50398240-fc8dfd80-079b-11e9-90cd-e9b4744a84fe.png)

**Comment by suvenduchhatoi** [comment]
Closing the issue due to no response for a while...Hope your issue has been resolved.You can reopen the issue if you still feel the issue is exclusive to "native-base"...

**Comment by LimitingSky** [comment]
I had the same problem in my case, I had to tag several days, this was solved in the following way.
```
<Picker.Item label={`${year}`} value={year} key={year} />
```
I hope it helps you
