### ISSUE TITLE
Seems like current react native icons is breaking

### ISSUE THREAD

**Issue by vongohren** [GeekyAnts/NativeBase#2483]
## Issue Description
It seems that react native icons is facing an issue: https://github.com/oblador/react-native-vector-icons/issues/910
<img width="1109" alt="screenshot 2018-12-11 at 00 27 29" src="https://user-images.githubusercontent.com/1012055/49783948-af864200-fd2c-11e8-8f35-839a5391dfc8.png">

We need to upgrade the dependency on react native icons

### node, npm, react-native, react and native-base version, expo version if used, xcode version
Native base 2.8.1
Node 10.3.1
RN 0.57

### Expected behaviour
Be able to build the project

### Actual behaviour
Fails because of this dependency

### Steps to reproduce
Just build a fresh project with the lates nativebase

### Is the bug present in both iOS and Android or in any one of them?
Android

### Any other additional info which would help us debug the issue quicker.
Not really, just see RNvector icons link

**Comment by YangSeung-min** [comment]
same here

**Comment by vongohren** [comment]
@YangSeung-min a current solutions is to just install the react-native-vector-icons independently, get the 6.1.0 version.

Then go into your lock file,
Search for react-native-vector-icon
Delete the older version if there.
Find native base entrance with the vector-icon dependency
Update the native base dependecny version to the one installed, in this case 6.1.0
Save the lockfile
Remove JUST nodemodules
and install again.

**Comment by xstable** [comment]
In the master-branch, the new vector-icon version is still added. 
Hope @akhil-geekyants will create a 2.8.2 release very soon & fast to get this changes in 2.8.2
