### ISSUE TITLE
Unable to change the font size of form input.

### ISSUE THREAD

**Issue by akshaykumar0291** [GeekyAnts/NativeBase#2484]
Hey, I am trying to use Floating Label, in that i need to change the input font. Please help.
I have tried using "inputFontSize" but its not working.

**Comment by suvenduchhatoi** [comment]
@akshaykumar0291 
You can try changing the font size of form input using FloatingLabel as:
 <Form>
        <Item floatingLabel>
              <Label>Username</Label>
              <Input style={{ fontSize: 30 }} />
         </Item>
 </Form>
NOTE:(Always wrap floatingLabel component with <Form/>)

**Comment by akshaykumar0291** [comment]
Thank you for the quick reply. It's working.
