### ISSUE TITLE
ActionSheet crashes the app

### ISSUE THREAD

**Issue by baldarian** [GeekyAnts/NativeBase#2485]
## Issue Description
I simply use `Actionsheet.show` to open the actionsheet but it causes the app to crash. Here's the screenshot. https://imgur.com/a/tkg24we

### node, npm, react-native, react and native-base version, expo version if used, xcode version
native-base: 2.8.1,
react: "16.6.1",
react-native: "0.58.0-rc.1"

**Comment by suvenduchhatoi** [comment]
@baldarian 
For ActionSheet to work, you need to wrap your topmost component inside from native-base. 
Check if it works...or share your code snippet...

**Comment by msqar** [comment]
@suvenduchhatoi i'm wrapping my code inside a <Root> component and still doesn't work... it throws `Cannot read property _root of null` on my case.
