### ISSUE TITLE
Suggestions for better performance

### ISSUE THREAD

**Issue by anjmao** [GeekyAnts/NativeBase#2486]
Hi, 
1. there are quite few places there lambdas are used directly on component which can cause extra re-renders. 
https://github.com/GeekyAnts/NativeBase/blob/master/src/basic/Fab.js#L430
https://github.com/GeekyAnts/NativeBase/blob/master/src/basic/Footer.js#L88
https://github.com/GeekyAnts/NativeBase/blob/master/src/basic/List.js#L186

There is even es-lint rule for that.

> Lambdas are forbidden in JSX attributes due to their rendering performance impact

2. Most of the components can be extended from PureComponent instead of Component.

Cheers.

**Comment by SupriyaKalghatgi** [comment]
#38
