### ISSUE TITLE
Outline Ionicons unavailable in v4 dep 

### ISSUE THREAD

**Issue by jmatsushita** [GeekyAnts/NativeBase#2487]
## I have gone through these following points
- [x]   Check latest documentation: https://docs.nativebase.io/
- [x]   Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x]   Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [x]   Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [x]   For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- [x]   For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

### node, npm, react-native, react and native-base version, expo version if used, xcode version

node 8.7.0
npm 6.4.1
react-native 0.57.8
native-base 2.8.1
xcode 9.4.1

### Expected behaviour

`<Icon name="settings"/>` displays properly

### Actual behaviour

Displays  `?` and a warning:
```
Warning: Failed prop type: Invalid prop `name` of value `ios-settings-outline` supplied to `Icon`, expected one of [...]
```

### Steps to reproduce

`<Icon name="settings"/>`

### Is the bug present in both iOS and Android or in any one of them?

Only iOS

### Any other additional info which would help us debug the issue quicker.

react-native-vector-icons uses ionicons v4 which has a [breaking change with outline icons](https://github.com/ionic-team/ionicons/issues/550) so [this default call](https://github.com/GeekyAnts/NativeBase/blob/e594c43e79fe5c173c06d945757b0c72c9458eac/src/basic/Icon/NBIcons.json#L2428) for ios points to an icon that doesn't exist anymore.

**Comment by suvenduchhatoi** [comment]
@jmatsushita 
Use
```
<Icon name="ios-settings" />
```

**Comment by SupriyaKalghatgi** [comment]
#2461
