### ISSUE TITLE
Any plans to implement landscape mode for tabs?

### ISSUE THREAD

**Issue by jesouhaite08** [GeekyAnts/NativeBase#249]
Per the following react-native-scrollable-tab-view commit: https://github.com/skv-headless/react-native-scrollable-tab-view/commit/d8cbf1def7a6b3affd1a1cf87693b53065f1c5fe

**Comment by rodolfobarretoweb** [comment]
+1

**Comment by sankhadeeproy007** [comment]
Landscape mode is not something very high on our priority list right now.
