### ISSUE TITLE
Swipeable List Error - Cannot read property '_root' of null

### ISSUE THREAD

**Issue by sekhuat** [GeekyAnts/NativeBase#2492]
## I have gone through these following points
- [x]   Check latest documentation: https://docs.nativebase.io/
- [x]   Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x]   Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [x]   Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [x]   For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- [x]   For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

## Issue Description

When two Swipeable List use in a single Component within two Segment with a different number of items in the list, for example, the first list have 10 items and second list have 2 items. If I swipe to open the 9th item in list 1 and then I tried to swipe open the 1st item in list 2 I will get "Cannot read property '_root' of null".

After I troubleshoot and found that the issue is caused by "safeCloseOpenRow" method in List.js. It seems like `this.openCellId` is shared by the two lists, so when I swipe to open the 1st item in list 2, the module tries to "close" the open row but instead closing the 9th item in list 1, it tried to close the 9th in list 2 which is not exist therefore causing the "Cannot read property '_root' of null".

I had modified the method safeCloseOpenRow as below but adding ` if(this._rows[this.openCellId] !== null)` and it seems work fine for me.

`safeCloseOpenRow() {
    // if the openCellId is stale due to deleting a row this could be undefined
    if(this._rows[this.openCellId] !== null) {
      if (this._rows[this.openCellId]._root) {
        this._rows[this.openCellId]._root.closeRow();
      }
    }
  }`

Hope this issue can be fix in the next release.

**Comment by SupriyaKalghatgi** [comment]
@sekhuat Please add code snippet as per your description
Its difficult to assume / imagine and have my own code snippet

**Comment by SupriyaKalghatgi** [comment]
Closing this issue due to no response
Reopen this issue if needed

**Comment by sekhuat** [comment]
My issue is with Swipeable List however from your post I can see that the issue you faced is with ActionSheet, therefore, it might not the same issue.

**Comment by montaserfzy** [comment]
Yes, but the same error

**Comment by hanego** [comment]
I had the same issue. I was using redux to fee the ListView Datasource but after rechecking the docs, I closed the row manually before dispatching my action (and then update my datasource) like this:
```
removeRow(id: string, secId: string | number, rowId: string | number, rowMap: any) {
        rowMap[`${secId}${rowId}`].props.closeRow();
        this.props.myreduxaction(id)
    }
```
