### ISSUE TITLE
TypeError: Cannot read property 'value' of undefined

### ISSUE THREAD

**Issue by vauruk** [GeekyAnts/NativeBase#2494]
Hi i make update for version 2.9.0, crash in PickerNB again, the same error the issue #1918 
Thanks

**Comment by SupriyaKalghatgi** [comment]
I tried with latest NativeBase
worked fine with single Picker Item

**Comment by vauruk** [comment]
I testing again! report later. thanks

**Comment by paragbhadoria** [comment]
Hi Vauruk,
     I was facing similar issue. I was using 
`let countryListSection = <Picker.Item label='No country found' value='-1' />;`
for setting default picker items till the contents are loaded, I fixed it by making it an array;
`let countryListSection = [<Picker.Item label='No country found' value='-1' />];`
After this things worked just fine. So incase you have a similar problem statement you can look for similar updates.

Thanks
