### ISSUE TITLE
iPad Pro (12.9-inch) (3rd generation) still wrong footer

### ISSUE THREAD

**Issue by benzman81** [GeekyAnts/NativeBase#2497]
## I have gone through these following points
- [x]   Check latest documentation: https://docs.nativebase.io/
- [x]   Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x]   Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [x]   Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [x]   For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- [x]   For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

## Issue Description
"iPad Pro (12.9-inch) (3rd generation)" still doesn't use safe area for footer. iPhone XR and XS Max are working now.

### node, npm, react-native, react and native-base version, expo version if used, xcode version
node v8.11.3
npm 5.6.0
xcode 10.1
npm list --depth=0:
`├── axios@0.18.0
├── axios-retry@3.1.1
├── babel-jest@23.6.0
├── babel-plugin-transform-remove-console@6.9.4
├── buffer@5.2.1
├── fbjs@1.0.0
├── jest@23.6.0
├── lodash@4.17.11
├── metro-react-native-babel-preset@0.51.0
├── native-base@2.9.2
├── qs@6.6.0
├── react@16.6.3
├── react-native@0.57.8
├── react-native-config@0.11.7
├── react-native-device-info@0.24.3
├── react-native-easy-grid@0.2.0
├── react-native-htmlview@0.13.0
├── react-native-i18n@2.0.15
├── react-native-keychain@3.0.0
├── react-native-locale@0.0.19
├── react-native-mime-types@2.2.1
├── react-native-modal-datetime-picker@6.0.0
├── react-native-splash-screen@3.1.1
├── react-navigation@2.18.3
├── react-test-renderer@16.6.3
├── rn-fetch-blob@0.10.13
├── sax@1.2.4
└── stream@0.0.2`
### Expected behaviour
Safe area is used.

### Actual behaviour
Safe area is not used.

### Steps to reproduce
Just use FooterTabs "iPad Pro (12.9-inch) (3rd generation)".

### Is the bug present in both iOS and Android or in any one of them?
iOS

### Any other additional info which would help us debug the issue quicker.
no

**Comment by suvenduchhatoi** [comment]
@benzman81 
Seems to be working fine...
Upgrade ```native-base to 2.10.0``` and your iosVersion should be greater than 11
Check with this snippet-
```
import React, { Component } from "react";
import { AppRegistry, View, SafeAreaView } from "react-native";
import {
  Container,
  Header,
  Content,
  Footer,
  FooterTab,
  Button,
  Text,
  Left,
  Body,
  Right,
  Title,
  Icon,
} from "native-base";
export default class Blink extends Component {
  render() {
    return (
      <SafeAreaView style={{ flex: 1, backgroundColor: "#fff" }}>
        <Container>
          <Header>
            <Left>
              <Button transparent>
                <Icon name="arrow-back" />
                <Text>Back</Text>
              </Button>
            </Left>
            <Body>
              <Title>Header</Title>
            </Body>
            <Right>
              <Button transparent>
                <Text>Cancel</Text>
              </Button>
            </Right>
          </Header>
          <Content />
          <Footer>
            <FooterTab>
              <Button>
                <Text>Apps</Text>
              </Button>
              <Button>
                <Text>Camera</Text>
              </Button>
              <Button active>
                <Text>Navigate</Text>
              </Button>
              <Button>
                <Text>Contact</Text>
              </Button>
            </FooterTab>
          </Footer>
        </Container>
      </SafeAreaView>
    );
  }
}
```
![screen shot 1440-05-08 at 7 01 49 pm](https://user-images.githubusercontent.com/44160581/51115720-110b6600-182f-11e9-9141-d1154e98e82d.png)

**Comment by benzman81** [comment]
@suvenduchhatoi everything respects the safe area if you put it in a SafeAreaView. Remove it and you will see, that the iPad Pro (12.9-inch) (3rd generation) has missplaced footers. Is you start the same app without the SafeAreaView on iPhone X, XR, XS, XS Max then everthing works as expected. So there is some work needed to be done in native base.

**Comment by suvenduchhatoi** [comment]
Even without using the ```<SafeAreaView>```, iPad pro(3rd generation) behaves the same...
![screen shot 1440-05-09 at 3 48 34 pm](https://user-images.githubusercontent.com/44160581/51174279-6e5df080-18dd-11e9-99ed-8849999d3889.png)
![screen shot 1440-05-09 at 3 50 44 pm](https://user-images.githubusercontent.com/44160581/51174280-6e5df080-18dd-11e9-98d0-9ad7100b5c93.png)

**Comment by benzman81** [comment]
Here is screenshot from iPhone X, XR, XS Max and iPad Pro (12.9-inch) (3rd generation).
You see the difference in the tabs.

But I might know, why you are not seeing this. Your app is not configured for iPad. Go to Xcode and mark it as universal and start again ;-)

<img width="1433" alt="screen" src="https://user-images.githubusercontent.com/14224592/51188491-5d61af00-18de-11e9-9a60-8bb3cced7fbe.png">

**Comment by benzman81** [comment]
@suvenduchhatoi could you reproduce it with the new info?

**Comment by suvenduchhatoi** [comment]
@benzman81 Yes, you are right, but that's the purpose of using ```<safeAreaView>```
![screen shot 1440-05-22 at 9 02 23 pm](https://user-images.githubusercontent.com/44160581/51846851-6de34200-2340-11e9-929b-756c85856d49.png)
 using which you should get 
![screen shot 1440-05-22 at 8 59 33 pm](https://user-images.githubusercontent.com/44160581/51846873-76d41380-2340-11e9-8beb-61eea0d445b1.png)

**Comment by benzman81** [comment]
@suvenduchhatoi I know that a wrapper of safe view will get the result you mention, but using nativebase there is no need to do this as there is extra handling within nativebase for its components (i.e. for iPhone X or XS Max). As you can see in my screenshot the same code results in perfect view for X, XS/Max, and XR. Just the new iPad misbehaves, so it is a bug within nativebase.

**Comment by benzman81** [comment]
@suvenduchhatoi great, yeah, it seems that there will be this issue for every new device by apple. Maybe the handling of native base should assume this by default instead of checking for every new device. Than you could implement an "old" handling without respecting the safe area for "old" devices. This way all new ones will be fine. Just a suggestion ;-)

**Comment by benzman81** [comment]
Is it fixed? Can‘t see a commit with the fix. Will there be a release with the fix?

**Comment by benzman81** [comment]
@SupriyaKalghatgi Could you answer if it is fixed and when the fix is release?
