### ISSUE TITLE
Wrong mapping in Octicons icons

### ISSUE THREAD

**Issue by SynerG** [GeekyAnts/NativeBase#2500]
## Issue Description
In the Octicons icon family, the mapping between ```name -> image``` seems to be wrong, as it shows a different icon than the one referenced by the name.

For example:
```
<Icon active name="organization" type="Octicons"/>
```
Shows the `package`icon instead of the ```organization```one.
And:
```
<Icon active name="package" type="Octicons"/>
```
Shows the ```paintcan``` icon instead of the ```package``` one.

So, the mapping seems to be off by one unit, as it shows the next one in the table (according to the table in https://oblador.github.io/react-native-vector-icons/).

It is possible that the error is in the ```react-native-vector-icons``` repo instead of this one.
If this is the case, tell me and I will open the issue in that repo.

### node, npm, react-native, react and native-base version, expo version if used, xcode version
native-base 2.9.2

**Comment by SupriyaKalghatgi** [comment]
#2453

**Comment by thiyagarajan13** [comment]
This is same in IOS too! Any update? and I'm using nativebase icons.
<Icon type="Feather" name="home"/>
