### ISSUE TITLE
How to get label from Picker?

### ISSUE THREAD

**Issue by derekgould** [GeekyAnts/NativeBase#2504]
## I have gone through these following points
- [X]   Check latest documentation: https://docs.nativebase.io/
- [X]   Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [X]   Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [X]   Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [X]   For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- [X]   For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

### node, npm, react-native, react and native-base version, expo version if used, xcode version
Node: v10.14.2
React-native: react-native: 9.57.1
Expo: 2.6.14

### Expected behaviour
Trying to retrieve value AND index from a picker. 

### Actual behaviour
Value is returned, index is not.

### Steps to reproduce
Picker is loaded (from Firestore) using following function;
`snapshot.forEach(doc => {
list.push(
<Picker.Item value={doc.id} label={doc.data()["RegionName"] key={doc.id />
)
`
CODE TO DISPLAY PICKER:
`<Picker
selectedValue={this.regionID}
onValueChange={(value,index) => this.onRegionChange(value, index)}

`
CODE EXECUTED ON CHANGE:
`onRegionChanged(value, index) {
this.regionID = value;
console.log('Value: ', value)
console.log('Index: ', index)
}
`

** if I look at the console at this point, the value shows the correct value (from firestore), while the index shows as Undefined.

### Is the bug present in both iOS and Android or in any one of them?
YES

### Any other additional info which would help us debug the issue quicker.
Using Mobx and Mobx-react

**Comment by suvenduchhatoi** [comment]
@derekgould 
See "react-native" docs about Picker...
https://facebook.github.io/react-native/docs/picker#onvaluechange
Don't think your issue is related to "native-base"...

**Comment by suvenduchhatoi** [comment]
Closing the issue due to no response for a while...Hope your issue has been resolved.You can reopen the issue if you still feel the issue is exclusive to "native-base"...
