### ISSUE TITLE
Unable to resolve AntDesign in IconNB.js

### ISSUE THREAD

**Issue by ht512512** [GeekyAnts/NativeBase#2506]
## Issue Description
Unable to resolve AntDesign in IconNB.js

### node, npm, react-native, react and native-base version, expo version if used, xcode version
node v11.0.0, npm 3.10.9, expo 2.3.8, native-base 2.10.0

### Expected behaviour
Proper resolution of dependencies 

### Actual behaviour
"expo start" fails with the following unresolved dependency.

Unable to resolve "@expo/vector-icons/AntDesign" from "node_modules/native-base/dist/src/basic/IconNB.js"

### Is the bug present in both iOS and Android or in any one of them?
Tested on Android and has the bug, not tested on iOS

**Comment by gkosmo** [comment]
node v11.3.0, npm 6.4.1, expo 2.6.14, "native-base": "^2.8.2"    same problem on Android

**Comment by SupriyaKalghatgi** [comment]
https://github.com/GeekyAnts/NativeBase/issues/2452#issuecomment-448853719

**Comment by ivanarielcaceres** [comment]
Hello! I have the same problem!
I'm using native-base 2.10.0 and i did try with expo 28, 29 and 30 with no success.

**Comment by maxgfr** [comment]
I solve my problem with this comment : [comment](https://github.com/expo/vector-icons/issues/58#issuecomment-452320918)

Basically, if you use expo v32 you have to follow these instructions : https://github.com/GeekyAnts/NativeBase
and run this command : 
`npm install @expo/vector-icons@^9.0.0`

**Comment by SupriyaKalghatgi** [comment]
Please refer latest ReadMe of NativeBase, which includes proper solution

**Comment by sathwik77** [comment]
I still have this issue with all new versions of expo, native-base and expo fonts. Here's my package.json
```{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "@expo/vector-icons": "9.0.0",
    "expo": "~37.0.3",
    "expo-font": "~8.1.0",
    "native-base": "^2.13.12",
    "react": "~16.9.0",
    "react-dom": "~16.9.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz",
    "react-native-web": "~0.11.7",
    "react-navigation": "3.3.0"
  },
  "devDependencies": {
    "@babel/core": "^7.8.6",
    "babel-preset-expo": "~8.1.0"
  },
  "private": true
}
```
I tried downgrading vector-icons to 8.1.0, I tried everything I could find, but nothing worked for me. Still getting the following error:

```Unable to resolve "@expo/vector-icons/Fontisto" from "node_modules/native-base/dist/src/basic/IconNB.js" ```
