### ISSUE TITLE
Typescript missing properties

### ISSUE THREAD

**Issue by ArThoX** [GeekyAnts/NativeBase#2508]
## Issue Description

![image](https://user-images.githubusercontent.com/551029/50614411-fa851680-0ee0-11e9-9b91-f19e38ee16d9.png)

```
Type '{ children: Element; onPress: () => void; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<Button> & Readonly<{ children?: ReactNode; }> & Readonly<Button>'.
  Property 'onPress' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Button> & Readonly<{ children?: ReactNode; }> & Readonly<Button>'.
```

### Versions 
```
    "@types/react": "^16.7.18",
    "native-base": "^2.8.0",
    "react": "^16.7.0",
```

### Expected behaviour
VSCode **does not complains** AND runtime OK.

### Actual behaviour
VSCode **shows TS errors** AND runtime OK.

### Details
I found multiple issues with the same issues, fixed in a later version. However here I encounter the issue with 2.8 and latest.

Regards

**Comment by SupriyaKalghatgi** [comment]
Recently updated NativeBase with Typescript fixes. Can you install NativeBase from `master` to check if it works for you?

**Comment by b-tiwari** [comment]
I am getting the same for CardItem, 
I have `"native-base": "^2.12.0"` in package.json
 tried installing latest with `rm -rf node_modules && rm yarn.lock && yarn`

**Comment by SupriyaKalghatgi** [comment]
@ArThoX @b-tiwari Can you check from branch `master`?

**Comment by b-tiwari** [comment]
getting error when I try installing from `master` branch

![8](https://user-images.githubusercontent.com/13605214/53860678-63534280-3fa7-11e9-8fbb-7f4e69c7ae97.png)

**Comment by SupriyaKalghatgi** [comment]
@b-tiwari should work now

**Comment by b-tiwari** [comment]
@SupriyaKalghatgi , yes, its working with master branch, no TS error for onPress with CardItem

**Comment by SupriyaKalghatgi** [comment]
@b-tiwari I hope your issue is sorted out

**Comment by b-tiwari** [comment]
@SupriyaKalghatgi , yes, good for now, when are you planning to release this master branch?

**Comment by SupriyaKalghatgi** [comment]
Tomorrow

**Comment by SupriyaKalghatgi** [comment]
2.12.1 is released

**Comment by b-tiwari** [comment]
Getting TS props error for Input and Spinner elements as well, tried with both master branch and 2.12.1


![Screen Shot 2019-03-14 at 11 01 49 PM](https://user-images.githubusercontent.com/13605214/54407971-16115800-46ae-11e9-96ae-2d841762c6cd.png)

![Screen Shot 2019-03-14 at 11 06 11 PM](https://user-images.githubusercontent.com/13605214/54408013-3fca7f00-46ae-11e9-81ac-a97252985ed9.png)
