### ISSUE TITLE
DatePicker disabled prop does not update component state

### ISSUE THREAD

**Issue by elyalvarado** [GeekyAnts/NativeBase#2509]
## I have gone through these following points
- [x]   Check latest documentation: https://docs.nativebase.io/
- [x]   Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x]   Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [x]   Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [x]   For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- [x]   For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

## Issue Description
The `disabled` prop on `DatePicker` only works on component mounting, this is the property is set initially but when later changed the component remains in the previous state

### node, npm, react-native, react and native-base version, expo version if used, xcode version

node: v8.12.0
yarn: v1.12.3
react: 16.6.1
react-native: 0.57.7
native-base: v2.10.0
Xcode: v10.1

### Steps to reproduce
Run the following snippet and check that when disabled is changed to `false` the DatePicker remains disabled.

```
import React from 'react'
import { Container, Header, Content, Text, Button, DatePicker } from 'native-base'

export default class DatePickerTest extends React.Component {
  state = { disabled: true }

  toggleState = () => {
    const disabled = !this.state.disabled
    this.setState({ disabled })
  }

  render() {
    const { disabled } = this.state

    return (
      <Container>
        <Header/>
        <Content>

          <Text>
            Current State:
            <Text style={{backgroundColor: disabled ? 'red' : 'green'}}>
              { disabled ? 'disabled' : 'enabled' }
            </Text>
          </Text>

          <DatePicker
            defaultDate={new Date(2018, 4, 4)}
            minimumDate={new Date(2018, 1, 1)}
            maximumDate={new Date(2018, 12, 31)}
            locale={"en"}
            timeZoneOffsetInMinutes={undefined}
            modalTransparent={false}
            animationType={"fade"}
            androidMode={"default"}
            placeHolderText="Select date"
            textStyle={{ color: "green" }}
            placeHolderTextStyle={{ color: "#d3d3d3" }}
            disabled={disabled}
          />

          <Button block light onPress={this.toggleState} >
            <Text>Toggle enabled/disabled state</Text>
          </Button>

        </Content>
      </Container>
    )
  }
}
```

### Expected behavior
Changing the `disabled` prop should change the component state

### Is the bug present in both iOS and Android or in any one of them?
The issue is present in both platforms

**Comment by elyalvarado** [comment]
@suvenduchhatoi actually my code had a small issue which prevented it from toggling the disabled state at all:

In the `toggleState` function I was doing:
```
this.setState(disabled)
```

And it should be:
```
this.setState({ disabled })
```

It is now fixed, and still doesn't work. If you check the source code of the `DatePicker` component you'll see that its impossible for it to work at all, as the state is only set on `componentDidMount` and never changed at all in any other lifecycle method. That is why the issue is there, unless you apply PR #2510 

The constructor syntax is completely equivalent to the class level property initialization of state, however, even making that change it still doesn't work.

**Comment by suvenduchhatoi** [comment]
@elyalvarado Check this link https://www.robinwieruch.de/react-state-without-constructor/
I think you are not getting access to the 'disabled' prop because you are not using constructor...

**Comment by elyalvarado** [comment]
All right, I made the change to using a constructor prop, it made no difference and the issue is still there. I wish `expo` wasn't broken with `native-base` so I could share you an snack with it.

Please check  the source code for the `DatePicker` component and you'll clearly see that the issue is there:

The disabled state is initialized in the constructor as true:
`
  constructor(props) {
    super(props);
    this.state = {
      modalVisible: false,
      defaultDate: new Date(),
      chosenDate: undefined,
      disabled: true
    };
  }
`

And then is set from the disabled prop in `componentDidMount`
`
  componentDidMount = () => {
    this.setState({
      defaultDate: this.props.defaultDate ? this.props.defaultDate : new Date(),
      disabled: this.props.disabled ? true : false
    });
    if (!this.props.placeHolderText && this.props.defaultDate) {
      this.setState({ chosenDate: this.props.defaultDate })
    }
  };
`

But then, is never updated through the component lifecycle, that is if after the component is mounted you change the `disabled` prop, the component doesn't make use of it because in the `render` method its making use of the state, not the prop:
`
<Text
            onPress={!this.state.disabled ? this.showDatePicker.bind(this) : undefined}
            style={[
              { padding: 10, color: variables.datePickerTextColor },
              this.state.chosenDate ? this.props.textStyle : this.props.placeHolderTextStyle
            ]}
          >
`

**Comment by Johncy1997** [comment]
i am getting same issue.i tried to set disabled property from state itself..Whatever i do, the component is not changing.still it cant be fixed

**Comment by elyalvarado** [comment]
The fix is in the PR #2510

**Comment by suvenduchhatoi** [comment]
#2510 has been merged

**Comment by jhoanborges** [comment]
I'm actually facing the same issue the component is not updating after set state.
