### ISSUE TITLE
How to pass props to another scene?

### ISSUE THREAD

**Issue by mdmush** [GeekyAnts/NativeBase#251]
Hello,

Can anyone please tell me how to pass props from one screen to another screen and how to store data and pass props after login is done? [Using NativeBase]

Thanks.

**Comment by sankhadeeproy007** [comment]
You can pass props the same way as you would in a regular react-native application. There is no separate way of doing that using native-base. Native-starter-kit [here](https://github.com/start-react/native-starter-kit) uses native-base and redux for state management and passing props between routes. Please refer to the login component for a working example of the same.
