### ISSUE TITLE
ListItem bottom border messed up when thumbnail too tall

### ISSUE THREAD

**Issue by garfieldnate** [GeekyAnts/NativeBase#2513]
## I have gone through these following points
- [X]   Check latest documentation: https://docs.nativebase.io/
- [X]   Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [X]   Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [X]   Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- []   For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- []   For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

## Issue Description

If the thumbnail used in a `ListItem` component is too tall, the bottom border becomes discontinuous.

Example code:

    import { Container, Content, List, ListItem, Thumbnail, Text, Left, Body, Right, Button } from 'native-base';
    import React from 'react';

    export default class DeckPickerScreen extends React.Component {
      render() {
        return (<Container>
            <Content>
              <List>
                <ListItem thumbnail>
                  <Left>
                    <Thumbnail square source={{ uri: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Flag_of_Turkey.svg/1200px-Flag_of_Turkey.svg.png' }} />
                  </Left>
                  <Body>
                    <Text>Deck Name Here</Text>
                  </Body>
                  <Right>
                    <Text>Sample</Text>
                  </Right>
                </ListItem>
              </List>
            </Content>
          </Container>
        );
      }
    }

Screenshot:

![image](https://user-images.githubusercontent.com/778453/50739797-47b8ff00-11e5-11e9-8a56-effd80a6a26a.png)

Notice that the bottom border for the `body` and `right` sections do not match. It seems that the `right` section grows with the `left` section, but the `body` does not do so.

The fix for now is to apply a styling to the thumbnail to reduce it's height:

     style={{width: 50, height: 50}} 

Screenshot of the fix:

![image](https://user-images.githubusercontent.com/778453/50739879-55bb4f80-11e6-11e9-80e7-74ac20bb4ed4.png)

### node, npm, react-native, react and native-base version, expo version if used, xcode version

node 11.6.0, react-native 0.57.1, native-base 2.10.0, expo 2.6.14, xcode 10.1

### Is the bug present in both iOS and Android or in any one of them?

I was only able to check with iOS (simulator for SE).

**Comment by suvenduchhatoi** [comment]
@garfieldnate 
In ejected native-base-theme/components/ListItem.js  
```
".thumbnail":{
   "NativeBase.Body":{
       paddingVertical: variables.listItemPadding + 8,
   }
}
```
![screen shot 1440-05-22 at 5 09 10 pm](https://user-images.githubusercontent.com/44160581/51834157-82fba900-231f-11e9-8896-94a3be2f262b.png)

**Comment by garfieldnate** [comment]
@suvenduchhatoi 
Thank you for posting another workaround. Because my project is not ejected, I do not know how to apply the styling you posted. However, I believe that this logic belongs in native-base, not in my project. Is this incorrect?

**Comment by garfieldnate** [comment]
Was this fixed in native base? There isn't any commit linked here.

**Comment by suvenduchhatoi** [comment]
https://github.com/GeekyAnts/NativeBase/commit/b07d89edb123170e37d7ae9b5292b2dc91513a8b

**Comment by garfieldnate** [comment]
Great, thanks! GitHub did not automatically link the commit because the pound sign (#) was not used in the commit message.

**Comment by JChristensen97** [comment]
This still seems to be an issue, see here:
`".thumbnail": {
      "NativeBase.Left": {
        flex: 0
      },
      "NativeBase.Body": {
        "NativeBase.Text": {
          marginLeft: null
        },
        flex: 1,
        paddingVertical: variables.listItemPadding + 8,
        borderBottomWidth: variables.borderWidth,
        borderColor: variables.listBorderColor,
        marginLeft: variables.listItemPadding + 5,
      },...`
Even with `paddingVertical: variables.listItemPadding + 8`, my listitem border is still jagged. Same as this submitted bug.

**Comment by JChristensen97** [comment]
This still seems to be an issue, see here:
```".thumbnail": {
      "NativeBase.Left": {
        flex: 0
      },
      "NativeBase.Body": {
        "NativeBase.Text": {
          marginLeft: null
        },
        flex: 1,
        paddingVertical: variables.listItemPadding + 8,
        borderBottomWidth: variables.borderWidth,
        borderColor: variables.listBorderColor,
        marginLeft: variables.listItemPadding + 5,
      }...,
```


Even with paddingVertical: variables.listItemPadding + 8, my listitem border is still jagged. Same as this submitted bug.
