### ISSUE TITLE
Picker Shows Question Mark version 2.10.0

### ISSUE THREAD

**Issue by Shehzad10p** [GeekyAnts/NativeBase#2516]
![simulator screen shot - iphone x - 2019-01-07 at 17 18 47](https://user-images.githubusercontent.com/29776304/50767881-544e5d80-12a0-11e9-98c4-c411c59491d9.png)

This issue appears in 2.10.0 it is showing ? instead drop down symbol

**Comment by suvenduchhatoi** [comment]
@Shehzad10p  Hope your issue has been resolved...

**Comment by Shehzad10p** [comment]
Yes, thanks
