### ISSUE TITLE
DeckSwiper Not work with complex array of object

### ISSUE THREAD

**Issue by samandaryaei** [GeekyAnts/NativeBase#2518]
Hi! Thanks for trying out NativeBase

when i set dataSource to :

{
    "LessonVideoPagedItems": [
        {
            "Title": "درس تستي 4",
            "Description": "طراحی برنامه های شی گرا به خودی خود سخت است و...",
            "PaidTypeId": 2,
            "PaidTypeDesc": "پرداخت",
            "CourseId": 15,
            "PackageIds": [],
            "LikeCount": 0,
            "MediaId": "3iiiz06e1mba",
            "LessonId": 4,
            "LessonContentId": 4,
            "IsLiked": false,
            "IsPaid": true,
            "CommentsCount": 1,
            "Comments": [
                {
                    "Id": 2,
                    "Description": "test me",
                    "CreateDate": "2018-12-01T00:00:00",
                    "UserName": "mogh64",
                    "Email": "mortaza.ghahremani@gmail.com"
                }
            ]
        },
        {
            "Title": "درس تستي 3",
            "Description": "طراحی برنامه های شی گرا به خودی خود سخت است و طراحی برنامه های شی گرایی که قابل استفاده مجدد هم باشند از آن نیز سخت تر است. قابلیت استفاده مجدد برای برنامه های نوشته شده بسیار مهم است",
            "PaidTypeId": 2,
            "PaidTypeDesc": "پرداخت",
            "CourseId": 15,
            "PackageIds": [],
            "LikeCount": 0,
            "MediaId": "e47yvyjjwb6s",
            "LessonId": 3,
            "LessonContentId": 3,
            "IsLiked": false,
            "IsPaid": true,
            "CommentsCount": 2,
            "Comments": [
                {
                    "Id": 14,
                    "Description": "جالب بود",
                    "CreateDate": "2019-01-06T12:01:24.35",
                    "UserName": null,
                    "Email": null
                },
                {
                    "Id": 11,
                    "Description": "متن تستی اول",
                    "CreateDate": "2019-01-05T00:27:52.793",
                    "UserName": null,
                    "Email": "samandaryaei@yahoo.com"
                }
            ]
        },
        {
            "Title": "درس تستي 2",
            "Description": "طراحی برنامه های شی گرا به خودی خود سخت است و طراحی برنامه های شی گرایی که قابل استفاده مجدد هم باشند از آن نیز سخت تر است. قابلیت استفاده مجدد برای برنامه های نوشته شده بسیار مهم است",
            "PaidTypeId": 1,
            "PaidTypeDesc": "رایگان",
            "CourseId": 15,
            "PackageIds": [],
            "LikeCount": 2,
            "MediaId": "ope5zexrtgks",
            "LessonId": 2,
            "LessonContentId": 2,
            "IsLiked": true,
            "IsPaid": true,
            "CommentsCount": 7,
            "Comments": [
                {
                    "Id": 12,
                    "Description": "متن تستس",
                    "CreateDate": "2019-01-05T18:46:44.05",
                    "UserName": null,
                    "Email": null
                },
                {
                    "Id": 10,
                    "Description": "متن تستی چهارم",
                    "CreateDate": "2019-01-05T00:25:20.557",
                    "UserName": null,
                    "Email": "samandaryaei@yahoo.com"
                },
                {
                    "Id": 9,
                    "Description": "متن تستی سوم",
                    "CreateDate": "2019-01-05T00:24:21.557",
                    "UserName": null,
                    "Email": "samandaryaei@yahoo.com"
                }
            ]
        },
        {
            "Title": "درس تست 1",
            "Description": "در بخش قبل مطالبی در باره ی شی گرایی و مفاهیم کلی آورده شد و در این بخش به شکل خاص به الگوهای طراحی خواهیم پرداخت و در بخش های بعد به شرح یک یا دو الگو می پردازیم. ",
            "PaidTypeId": 1,
            "PaidTypeDesc": "رایگان",
            "CourseId": 15,
            "PackageIds": [],
            "LikeCount": 1,
            "MediaId": "qwgzdthdhnyp",
            "LessonId": 1,
            "LessonContentId": 1,
            "IsLiked": false,
            "IsPaid": true,
            "CommentsCount": 1,
            "Comments": [
                {
                    "Id": 13,
                    "Description": "سلام",
                    "CreateDate": "2019-01-06T12:00:58.303",
                    "UserName": null,
                    "Email": null
                }
            ]
        }
    ],
    "StatusCode": 0
}

i see exception red screen : "TypeError : cannot read property '0'  undefined " !!!!!

**Comment by suvenduchhatoi** [comment]
@samandaryaei 
Can you share the screenshot of error screen...Are you able to render DeckSwiper for simpler array Objects??

**Comment by samandaryaei** [comment]
> @samandaryaei
> Can you share the screenshot of error screen...Are you able to render DeckSwiper for simpler array Objects??

yes i can render DeckSwiper for simple array Object

![untitled](https://user-images.githubusercontent.com/20062873/50951951-38c39c80-14c4-11e9-8e8a-e26c064a2770.png)

**Comment by hanykumar** [comment]
Hi @samandaryaei , can you share minimal code reproduction on snack for the same. It will easy for us to identify the issue.
Thanks

**Comment by hanykumar** [comment]
Hi @samandaryaei, Closing this now due to inactivity. Let us know if the issue still persists.
