### ISSUE TITLE
Pull to refresh for Accordion component

### ISSUE THREAD

**Issue by devonhuangcodes** [GeekyAnts/NativeBase#2522]
Is it possible to pull to refresh for the Accordion component?

**Comment by suvenduchhatoi** [comment]
Did you mean pull-to-refresh?

**Comment by suvenduchhatoi** [comment]
Yes, just like within a ```<ScrollView>```, if you apply ```<RefreshControl>``` within ```<Accordion``` in the following manner,
```
<Accordion
        refreshControl={
          <RefreshControl
            refreshing={this.state.refreshing}
            onRefresh={this._onRefresh}
          />
        }
        dataArray={dataArray}
        expanded={0}
      />
```

**Comment by devonhuangcodes** [comment]
Thanks @suvenduchhatoi it works. Closing this issue.
