### ISSUE TITLE
How to set the StatusBar color when I have a Picker open?

### ISSUE THREAD

**Issue by egor-a-trubnikov-panov** [GeekyAnts/NativeBase#2523]
I want to change the StatusBar color when I open or close the Picker.

**Comment by suvenduchhatoi** [comment]
@egor-a-trubnikov-panov 
```
import React, { Component } from "react";
import { StatusBar, View } from "react-native";
import { Container, Header, Content, Picker, Form } from "native-base";
export default class PickerExample extends Component {
  constructor(props) {
    super(props);
    this.state = {
      selected: "key1",
      enabled: true,
    };
  }

  onValueChange(value: string) {
    this.setState({
      selected: value,
    });
  }
  render() {
    return (
      <Container>
        <Content>
          <StatusBar
            backgroundColor={this.state.enabled ? "red" : "green"}
            barStyle="light-content"
          />
          <Form>
            <Picker
              mode="dropdown"
              style={{ width: 120 }}
              selectedValue={this.state.selected}
              onValueChange={this.onValueChange.bind(this)}
              enabled={this.state.enabled}
            >
              <Picker.Item label="Wallet" value="key0" />
              <Picker.Item label="ATM Card" value="key1" />
              <Picker.Item label="Debit Card" value="key2" />
              <Picker.Item label="Credit Card" value="key3" />
              <Picker.Item label="Net Banking" value="key4" />
            </Picker>
          </Form>
        </Content>
      </Container>
    );
  }
}
```
Based on the value of ```enabled``` prop, whose value is set in the ```state``` you can change the color of ```StatusBar``` dynamically...If you set the value of ```enabled``` in the state as ```false```i.e disabling the ```Picker``` prop, your ```StatusBar``` would be set to ```green``` background...

**Comment by suvenduchhatoi** [comment]
Closing this issue due to no response for a while...You can reopen if you feel the issue is with 
```native-base```

**Comment by nyl9488** [comment]
is it working?

**Comment by realpasro09** [comment]
You can change the statusBar when you open the Picker using renderHeader property.

`renderHeader={(backAction) => {
                return <Header>
                          <StatusBar barStyle="light-content"/>
                          <Left>
                            <Button transparent onPress={backAction}>
                              <Icon name='close' />
                            </Button>
                          </Left>
                          <Body>
                            <Text>Payment Method</Text>
                          </Body>
                          <Right />
                      </Header>
                }`
