### ISSUE TITLE
Question: set left inset for <ListItem>’s divider

### ISSUE THREAD

**Issue by oferRounds** [GeekyAnts/NativeBase#2524]
Hi, I’d like to set the bottom divider, which each item has, to have some insets. Couldn’t find a way to do it

Is there a way?

**Comment by suvenduchhatoi** [comment]
@oferRounds Do you want to make something like this??
![screen shot 1440-05-09 at 6 43 44 pm](https://user-images.githubusercontent.com/44160581/51182886-a3763d00-18f5-11e9-872e-87747100b8a5.png)
If not, do provide description in ISSUE_TEMPLATE format...

**Comment by oferRounds** [comment]
Thanks!

No, please see the screenshot here – I’d like the **divider-line** to start where the text start, i.e., have a bit of left inset

![default](https://user-images.githubusercontent.com/1477963/51197585-a7588e00-18fa-11e9-8087-1ce7b7deebaf.jpeg)

**Comment by suvenduchhatoi** [comment]
@oferRounds 
![screen shot 1440-05-22 at 8 24 39 pm](https://user-images.githubusercontent.com/44160581/51844271-d62f2500-233a-11e9-80b6-97dd8e7d7457.png)

**Comment by oferRounds** [comment]
Thank you! I’ll check why it’s not showing up like that on my app
