### ISSUE TITLE
Input component does not work with Formik library

### ISSUE THREAD

**Issue by oniondomes** [GeekyAnts/NativeBase#2525]
## I have gone through these following points
- [x]   Check latest documentation: https://docs.nativebase.io/
- [x]   Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x]   Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [x]   For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- [x]   For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/
- [ ]   Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink

## Issue Description

If I use NativeBase components (`Input` to be more specific) with [Formik](https://jaredpalmer.com/formik/), It throws an error executing `onBlur` handler.

### node, npm, react-native, react and native-base version, expo version if used, xcode version

node v10.15.0, npm v6.4.1, react v16.5.0, native-base v2.10.0, expo v32.0.0, formik v1.4.2

### Expected behaviour

Well, I expect nothing to be broke.

### Actual behaviour

An error is thrown when `onBlur` event is triggered in `Input` component. The following text is displayed:

> undefined is not an object (evaluating 'e.persist')
> executeBlur at formik.cjs.development.js:L323:22

I suppose this happens because of [`Item` component not passing an event to a given handler](https://github.com/GeekyAnts/NativeBase/blob/c1930f9bfefa45290ff181f9f286f65e910caf4b/src/basic/Item.js#L198), so the library has nothing to evaluate.

This issue can easily be fixed by passing down the event object like this:

```javascript
onBlur={(e) => {
  inputProps.value
    ? this.setState({
      isFocused: true
    })
    : !this.state.text.length &&
    this.setState({ isFocused: false });
  inputProps.onBlur && inputProps.onBlur(e);
}}
```

### Steps to reproduce

This code will through the error described above:

```jsx
import { Formik } from 'formik';
import { Input, Label, Item } from 'native-base';

<Formik
  initialValues={{ email: '' }}
  onSubmit={values => console.log(values)}
>
  { props => (
    <View>
      <Item
        style={styles.input}
        floatingLabel
      >
        <Label>Email</Label>
        <Input
          onChangeText={props.handleChange('email')}
          onBlur={props.handleBlur('email')}
          value={props.values.email}
        />
      </Item>
    </View>
  )}
</Formik>
```
The result would be:

![img_2334](https://user-images.githubusercontent.com/36102898/51246125-ab3bed00-199a-11e9-8c70-14affcb27717.PNG)

### Is the bug present in both iOS and Android or in any one of them?

It is in iOS. Was not tested in Android.

**Comment by suvenduchhatoi** [comment]
@oniondomes 
Actually you should wrap floatingLabel Input within ```<Form>``` component going by docs...
Did passing event handler fix it for you?Tried your suggestion...Doesn't seem to work

**Comment by oniondomes** [comment]
@suvenduchhatoi It did. You can take a look at changes I have make in my fork here: https://github.com/oniondomes/NativeBase/commit/d4e52be3f666d2047da9f7d1c5d5705113f3f9a9

Thanks for the remark about `<Form>`  btw.

**Comment by suvenduchhatoi** [comment]
commit 4fadd8af2928c85ec8de1758537b736bd8c1da6d
