### ISSUE TITLE
DeckSwiper doesn't respect datasource changes at the renderItem level

### ISSUE THREAD

**Issue by MaciekLeks** [GeekyAnts/NativeBase#2527]
### node, npm, react-native, react and native-base version, expo version if used, xcode version
react-native
NB v2.8.1

### Expected behaviour
Active card should respect the underlying item's changes.

### Actual behaviour
For the given dataSource array (e.g. ds) if the change important to the component appears in one of the renderItem's properties (e.g. property controls an icon visibility) Deck Swiper does not show it up.

```javascript
const ds= [
  {
     property1: false,
     ...
   },
   { //active card
     property1: false, // -> true value when the state changes
     ...
   },
   ... 
];
```

### Steps to reproduce
Change the property value, which controls the visibility of some active cards element,  when the card is active.

### Is the bug present in both iOS and Android or in any one of them?
Can't test it under iOS. The issue tested in Android only.

**Comment by suvenduchhatoi** [comment]
@MaciekLeks 
seems to be a replicated issue... Let's discuss in https://github.com/GeekyAnts/NativeBase/issues/1411
