### ISSUE TITLE
Button text color.

### ISSUE THREAD

**Issue by thundenilla** [GeekyAnts/NativeBase#253]
Hey, is there any way for me to change the text color. since im trying to make the button as transparent, but im getting default black color font. i can change the icon color but not the text.  

`<Button transparent>
           <Icon name="md-people" style={{color: 'white', fontSize: 22}}/>
           <Text style={{color: 'white'}}>22</Text>
   </Button>`

**Comment by sankhadeeproy007** [comment]
Use prop textStyle with button. Refer to the [docs](http://nativebase.io/docs/v0.5.9/components#button)

**Comment by GavinThomas1192** [comment]
As of right now using textStyle, didn't work for me.
