### ISSUE TITLE
Card transparent breaks FlatList vertical scrolling?

### ISSUE THREAD

**Issue by msqar** [GeekyAnts/NativeBase#2532]
## Issue Description
I got a FlatList with Card children, and I noticed that whenever I add "transparent" to one of my Cards, the scrolling on the container will no longer work. Took me several minutes to find out why it wasn't working anymore, had to undo one change at a time until i found it.

### Expected behaviour
Scrolling shouldn't break.

### Actual behaviour
Scrolling doesn't work.

### Steps to reproduce
Create a FlatList and render Card items inside, try putting transparent inside of the card and see if it breaks scrolling.

### Is the bug present in both iOS and Android or in any one of them?
Just checked on iOS.

**Comment by suvenduchhatoi** [comment]
@msqar 
FlatList vertical scrolling is working fine when card is rendered inside it...
```
import React, { Component } from "react";
import { FlatList } from "react-native";
import {
  Container,
  Header,
  Content,
  Card,
  CardItem,
  Text,
  Body,
  View,
  ListItem,
  Separator,
} from "native-base";
export default class CardTransparentExample extends Component {
  render() {
    const statics = [
      { text: "Camera" },
      { text: "Live1" },
      { text: "Live2" },
      { text: "Live3" },
      { text: "Live4" },
      { text: "Live5" },
      { text: "Live6" },
      { text: "Live7" },
      { text: "Live8" },
      { text: "Live9" },
      { text: "Live10" },
      { text: "Live11" },
      { text: "Live12" },
      { text: "Live13" },
      { text: "Live14" },
    ];
    return (
      <Container>
        <Header />
        <Content padder>
          <FlatList
            style={{ margin: 10, backgroundColor: "#fff", flex: 1 }}
            data={statics}
            renderItem={({ item }) =>
              <View style={{ flex: 1 }}>
                <Card transparent>
                  <CardItem>
                    <Body>
                      <Text>
                        {item.text}
                      </Text>
                    </Body>
                  </CardItem>
                </Card>
                <Separator style={{ height: 1 }} />
              </View>}
          />
        </Content>
      </Container>
    );
  }
}
```
![screen shot 1440-05-23 at 8 09 19 pm](https://user-images.githubusercontent.com/44160581/51915783-ef4ed900-2401-11e9-92df-b73d196ecca6.png)

**Comment by suvenduchhatoi** [comment]
Closing the issue due to no response for a while... You can reopen if you feel the issue is with ```native-base```
