### ISSUE TITLE
Rendered tabs won't unmount and causing memory leak

### ISSUE THREAD

**Issue by el-lsan** [GeekyAnts/NativeBase#2533]
## I have gone through these following points
- [x]   Check latest documentation: https://docs.nativebase.io/
- [x]   Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x]   Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [x]   Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [x]   For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- [x]   For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

## Issue Description
Based on my testing `componentWillUnmount` does not trigger when you change the tabs and all the rendered tabs are being kept in memory and in case you have some expensive components/screen inside your tabs after few tab changes the app would get slower and slower and eventually cause crashing.

### node, npm, react-native, react and native-base version, expo version if used, xcode version
node v8.11.4, npm 5.6.0, ^react 16.7.0, react-native ^0.57.8, native-base ^2.10.0

### Expected behaviour
I know keeping them rendered might make sense in many use case but would be better to have an option to disable this behaviour and keep only the active tab rendered and unmount the rest.

### Actual behaviour
When you change the tabs, all rendered tabs are still in memory even if you set `prerenderingSiblingsNumber={0}`.

### Steps to reproduce
You can use the [Scrollable Tabs Example](http://docs.nativebase.io/Components.html#tabs-scrollable-headref), preferably with some heavy/expensive screens as each tab. Change the tabs and watch the memory usage keep increasing. You could also put a console.log inside `componentWillUnmount` for these tab's component and see it never get invoked.

### Is the bug present in both iOS and Android or in any one of them?
Yes. It happens on both iOS and Android.

**Comment by suvenduchhatoi** [comment]
Closing the issue due to no response for a while... You can reopen the issue if you feel the it is a native-base issue...
