### ISSUE TITLE
The development server returned response error code: 500

### ISSUE THREAD

**Issue by buraksakalli** [GeekyAnts/NativeBase#2536]
Hello,
I'm getting an error. Its screenshots in here;
![screenshot_3](https://user-images.githubusercontent.com/10114716/51761868-3e81ca80-20df-11e9-87e2-7f6d96b376aa.png)
![screenshot_4](https://user-images.githubusercontent.com/10114716/51761869-3f1a6100-20df-11e9-991c-72c66e93889f.png)

and also the output is:

> `The development server returned response error code: 500

URL: http://10.0.2.2:8081/index.delta?platform=android&dev=true&minify=false

Body:
{"originModulePath":"C:\\Users\\Burak\\Desktop\\AwesomeProject\\node_modules\\native-base\\dist\\src\\basic\\Tabs\\index.js","targetModuleName":"react-timer-mixin","message":"Unable to resolve module `react-timer-mixin` from `C:\\Users\\Burak\\Desktop\\AwesomeProject\\node_modules\\native-base\\dist\\src\\basic\\Tabs\\index.js`: Module `react-timer-mixin` does not exist in the Haste module map\n\nThis might be related to https://github.com/facebook/react-native/issues/4968\nTo resolve try the following:\n  1. Clear watchman watches: `watchman watch-del-all`.\n  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.\n  3. Reset Metro Bundler cache: `rm -rf /tmp/metro-bundler-cache-*` or `npm start -- --reset-cache`.\n  4. Remove haste cache: `rm -rf /tmp/haste-map-react-native-packager-*`.","errors":[{"description":"Unable to resolve module `react-timer-mixin` from `C:\\Users\\Burak\\Desktop\\AwesomeProject\\node_modules\\native-base\\dist\\src\\basic\\Tabs\\index.js`: Module `react-timer-mixin` does not exist in the Haste module map\n\nThis might be related to https://github.com/facebook/react-native/issues/4968\nTo resolve try the following:\n  1. Clear watchman watches: `watchman watch-del-all`.\n  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.\n  3. Reset Metro Bundler cache: `rm -rf /tmp/metro-bundler-cache-*` or `npm start -- --reset-cache`.\n  4. Remove haste cache: `rm -rf /tmp/haste-map-react-native-packager-*`."}],"name":"Error","stack":"Error: Unable to resolve module `react-timer-mixin` from `C:\\Users\\Burak\\Desktop\\AwesomeProject\\node_modules\\native-base\\dist\\src\\basic\\Tabs\\index.js`: Module `react-timer-mixin` does not exist in the Haste module map\n\nThis might be related to https://github.com/facebook/react-native/issues/4968\nTo resolve try the following:\n  1. Clear watchman watches: `watchman watch-del-all`.\n  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.\n  3. Reset Metro Bundler cache: `rm -rf /tmp/metro-bundler-cache-*` or `npm start -- --reset-cache`.\n  4. Remove haste cache: `rm -rf /tmp/haste-map-react-native-packager-*`.\n    at ModuleResolver.resolveDependency (C:\\Users\\Burak\\Desktop\\AwesomeProject\\node_modules\\metro\\src\\node-haste\\DependencyGraph\\ModuleResolution.js:183:15)\n    at ResolutionRequest.resolveDependency (C:\\Users\\Burak\\Desktop\\AwesomeProject\\node_modules\\metro\\src\\node-haste\\DependencyGraph\\ResolutionRequest.js:52:18)\n    at DependencyGraph.resolveDependency (C:\\Users\\Burak\\Desktop\\AwesomeProject\\node_modules\\metro\\src\\node-haste\\DependencyGraph.js:273:16)\n    at Object.resolve (C:\\Users\\Burak\\Desktop\\AwesomeProject\\node_modules\\metro\\src\\lib\\transformHelpers.js:261:42)\n    at dependencies.map.result (C:\\Users\\Burak\\Desktop\\AwesomeProject\\node_modules\\metro\\src\\DeltaBundler\\traverseDependencies.js:391:31)\n    at Array.map (<anonymous>)\n    at resolveDependencies (C:\\Users\\Burak\\Desktop\\AwesomeProject\\node_modules\\metro\\src\\DeltaBundler\\traverseDependencies.js:388:18)\n    at C:\\Users\\Burak\\Desktop\\AwesomeProject\\node_modules\\metro\\src\\DeltaBundler\\traverseDependencies.js:261:33\n    at Generator.next (<anonymous>)\n    at asyncGeneratorStep (C:\\Users\\Burak\\Desktop\\AwesomeProject\\node_modules\\metro\\src\\DeltaBundler\\traverseDependencies.js:87:24)"}
processBundleResult
    BundleDownloader.java:296
access$200
    BundleDownloader.java:37
onResponse
    BundleDownloader.java:174
execute
    RealCall.java:206
run
    NamedRunnable.java:32
runWorker
    ThreadPoolExecutor.java:1167
run
    ThreadPoolExecutor.java:641
run
    Thread.java:764
`

**Comment by bmlis** [comment]
+1, installed NativeBase on a fresh React Native setup using instructions from the guide. I've followe instruction from the error/linked issue, but to no avail.

**Comment by hoboman313** [comment]
This is basically #2534 except I installed react-timer-mixin to get around your error, which was removed in the latest RN version. Native-base does not work with the latest RN 0.58.0 and there are a lot of various breakages.

**Comment by bmlis** [comment]
Downgrading to RN 0.56.0 fixed that for me for now.

**Comment by buraksakalli** [comment]
I downgraded but there's no difference about the error. I used react 0.56.0

**Comment by VaibhavFuke** [comment]
npm install react-timer-mixin

This fixed me up.

**Comment by suvenduchhatoi** [comment]
@buraksakalli Did https://github.com/GeekyAnts/NativeBase/issues/2536#issuecomment-458082305
fix it for you

**Comment by wuno** [comment]
@buraksakalli  Why is this closed? This is a very obvious issue that many people are facing. I am even chatting with other people on the Slack org who are also facing this issue and who have been unable to solve it. If there are breaking changes to the app, would it not make sense to keep this issue open so we can get them fixed? 

I realize some people have got it working with a lower version of RN but a lot of us are not successful doing so.

**Comment by connect2jc** [comment]
I still had a this issue and its really frustrating. I tried to fix it with lot of suggestions but they all are shooting in a dark. I would also like to have this issue open until we find proper solution.

**Comment by hoboman313** [comment]
The real issue is that native-base doesn't support the latest version of RN and I logged a separate issue for that already.
The solution for this react-timer-mixin error was already given multiple times. Learn to clear the cache.

**Comment by suvenduchhatoi** [comment]
@wuno @connect2jc 
```npm install react-timer-mixin``` fixes the issue, please see if you are closing your metro instances and then clearing your cache before running it again...And you don't even need to downgrade react-native version...
![screen shot 1440-05-24 at 12 23 17 pm](https://user-images.githubusercontent.com/44160581/51963828-c32b6a80-248a-11e9-8d7f-7272e031bf88.png)

**Comment by Udbhav12** [comment]
@suvenduchhatoi Is installing `react-timer-mixin` recommended solution or just a quick fix?

According to RN 0.58 release notes mixins have been removed. Refer below link

https://github.com/facebook/react-native/issues/21581

**Comment by buraksakalli** [comment]
@connect2jc you can just solve with `npm install react-timer-mixin`. That's the solution for now.

**Comment by wuno** [comment]
@buraksakalli This was the first thing I attempted when faced with the issue. 

Would you please post your, 

```
npm --version 
node --version
```

**Comment by andresmtz98** [comment]
> @suvenduchhatoi Is installing `react-timer-mixin` recommended solution or just a quick fix?
> 
> According to RN 0.58 release notes mixins have been removed. Refer below link
> 
> [facebook/react-native#21581](https://github.com/facebook/react-native/issues/21581)

I think is not a recommended workaround but for now there is nothing to do haha. Wait for NativeBase team.

**Comment by buraksakalli** [comment]
@wuno npm: 6.5.0
node: v11.8.0

**Comment by wuno** [comment]
I was able to get it working using the same method. I am hoping the effort to fix these breaking changes is not so hard. 

Would it not make sense to just add the `react-timer-mixin` as a dependency to `native-base`?

**Comment by SupriyaKalghatgi** [comment]
Fixed with 2.11.0

**Comment by javeriazubair** [comment]
> I was able to get it working using the same method. I am hoping the effort to fix these breaking changes is not so hard.
> 
> Would it not make sense to just add the `react-timer-mixin` as a dependency to `native-base`?

how did you do it i still cant remove my error and what is this command rm -rf node_modules
 its not recognizing it any help?

**Comment by javeriazubair** [comment]
> Thanks for all the above inputs, the following helped sovle
> 
> ```shell
> rm -rf node_modules && npm install react-timer-mixin
> react-native run-ios
> ```

rm -rf node_modules how do you use it

**Comment by isaaclem** [comment]
@javeriazubair : `node_modules` is a folder at root of your project. It can be removed and installed back using `yarn install` or `npm install`. But since you're asking this question, I recommend you to get help from seniors before proceeding doing `rm -rf node_modules` because not every project has the same setup

**Comment by rishi-singh26** [comment]
> npm install react-timer-mixin
> 
> This fixed me up.

Worked for me too.

**Comment by Ralphkay** [comment]
still not working for me though

**Comment by JoeLimewire** [comment]
I'm getting this issue in 2020, I've tried `npm install react-timer-mixin` but it doesn't work and it keeps saying there is a reference error with one of the screens. A friend and I double checked the code and everything should be working.

**Comment by buraksakalli** [comment]
@JoeLimewire 

Would you write your,
```
npm --v
node --v
```
and react, react-native versions?

**Comment by JoeLimewire** [comment]
NPM --v `6.14.2`
Node -v `v13.9.0`
React: `16.9.0`
React-native: `0.61.5`

**Comment by JoeLimewire** [comment]
Okay, I've solved it on my end. I had to re-install the CLI
`npm i @react-native-community/cli`

**Comment by quoctoank4it** [comment]
I'm getting this issue in 2020, I've tried npm install react-timer-mixin but it doesn't work. Please help me!

**Comment by mdarmancse** [comment]
I'm getting this issue in 2020, I've tried npm install react-timer-mixin but it doesn't work. Please help me!

**Comment by taufik-muharrom** [comment]
reinstall yarn, `yarn install` and then `yarn start` 
its work for me.

**Comment by Hitsukihoshi** [comment]
> npm install react-timer-mixin
> 
> This fixed me up.

is it really working?

**Comment by LuwanKonnect** [comment]
npm install react-navigation --save

**Comment by safi-alt** [comment]
[
![Screenshot_2021-03-01-15-25-37-54](https://user-images.githubusercontent.com/58626565/109498607-81c87780-7ab5-11eb-8476-fffd6848c3ab.jpg)
](url)

**Comment by safi-alt** [comment]
Im facing the above-mentoioned screenshot issue. Neither the project is working on macbook nor on my windows laptop. But it is working on my friend's laptop. We are using expo and react native. We have made a general button as mainButton and using it. The error says mainButton does not exist. The path is imported correctly and none of the above mentioned fixes work. Please help. Thanks in advance
![Uploading Screenshot_2021-03-01-15-25-37-54.jpg…]()

**Comment by safi-alt** [comment]
![Screenshot_2021-03-01-15-25-37-54](https://user-images.githubusercontent.com/58626565/109499069-3367a880-7ab6-11eb-9a2b-cffc1ebed258.jpg)
Im facing the above-mentoioned screenshot issue. Neither the project is working on macbook nor on my windows laptop. But it is working on my friend's laptop. We are using expo and react native. We have made a general button as mainButton and using it. The error says mainButton does not exist. The path is imported correctly and none of the above mentioned fixes work. Please help. Thanks in advance

**Comment by NTS2k1BK** [comment]
i had an error with bottom-tabs.I tried to uninstall and install again .It worked successfully.Maybe it will help you.

**Comment by Coder404-Suyash** [comment]
how to i solve this error please help me

![Screenshot_1637667197](https://user-images.githubusercontent.com/92211439/143023143-5ade670e-77a3-43b6-9524-3b00d197ac1a.png)
![Screenshot_1637667227](https://user-images.githubusercontent.com/92211439/143023146-edc5f08e-a68c-4622-8d3d-545177c733ca.png)

**Comment by Basir-PD** [comment]
none works

**Comment by long7102** [comment]
> i had an error with bottom-tabs.I tried to uninstall and install again .It worked successfully.Maybe it will help you.

How to uninstall it

**Comment by dln88** [comment]
I got this issue by a silly mistake. I install a library and removed it right after but didn't remove the import line. Hope this help

**Comment by nc-hung** [comment]
Wrong version of node, when running the project, I also have this problem

**Comment by ali-raza50** [comment]
This error is also due to some files. In my case Body:{
  //here it shows name of a file where error is
}
so just delete that file create it again that's work for me
