### ISSUE TITLE
Can you please let me know how can i disable a row in accordion implemented using native base components

### ISSUE THREAD

**Issue by malliswarit** [GeekyAnts/NativeBase#2537]
## I have gone through these following points
- []   Check latest documentation: https://docs.nativebase.io/
- []   Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- []   Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- []   Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- []   For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- []   For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

**Comment by malliswarit** [comment]
Row 3 needs to be disabled in UI. Both header content and OnPress actions needs to be disabled.
Provide me solution please

**Comment by suvenduchhatoi** [comment]
@malliswarit Component Accordion's all elements are designed in a way to behave homogeneously... Either you can set style prop ```display:"none"```, but then you cannot see content of any Accordion element... There's no feature as such to disable only some Accordion elements...
![screen shot 1440-05-23 at 3 22 15 pm](https://user-images.githubusercontent.com/44160581/51900094-6bcdc180-23da-11e9-8d92-cc5ef843849a.png)

**Comment by malliswarit** [comment]
I have been successful to disable a particular row in accordion.
But now facing the issue to update the background colour of disabled row.

In the screenshot Row 4 is disabled. Icon functionality work as per custom props.
I want to change the background colour of only that row to grey.

![simulator screen shot - iphone x - 2019-01-29 at 16 29 45](https://user-images.githubusercontent.com/38764207/51903910-5b6e1480-23e3-11e9-928f-8b1b5e0945da.png)


Iam using custom prop --- this.state={
     DisablePanel:3
   }
to disable row 4 and it worked fine.

**Comment by suvenduchhatoi** [comment]
@malliswarit 
That's what...There's no predefined prop for it... 
Let's discuss your in next issue #2540 
Closing this issue...

**Comment by pratiksalgiya** [comment]
> I have been successful to disable a particular row in accordion.
> But now facing the issue to update the background colour of disabled row.
> 
> In the screenshot Row 4 is disabled. Icon functionality work as per custom props.
> I want to change the background colour of only that row to grey.
> 
> ![simulator screen shot - iphone x - 2019-01-29 at 16 29 45](https://user-images.githubusercontent.com/38764207/51903910-5b6e1480-23e3-11e9-928f-8b1b5e0945da.png)
> 
> Iam using custom prop --- this.state={
> DisablePanel:3
> }
> to disable row 4 and it worked fine.


> I have been successful to disable a particular row in accordion.
> But now facing the issue to update the background colour of disabled row.
> 
> In the screenshot Row 4 is disabled. Icon functionality work as per custom props.
> I want to change the background colour of only that row to grey.
> 
> ![simulator screen shot - iphone x - 2019-01-29 at 16 29 45](https://user-images.githubusercontent.com/38764207/51903910-5b6e1480-23e3-11e9-928f-8b1b5e0945da.png)
> 
> Iam using custom prop --- this.state={
> DisablePanel:3
> }
> to disable row 4 and it worked fine.

Can you share a code snippet, how you disabled a row?
