### ISSUE TITLE
Keyboard error on secureTextEntry=true

### ISSUE THREAD

**Issue by GH974** [GeekyAnts/NativeBase#2538]
## I have gone through these following points
- [x]   Check latest documentation: https://docs.nativebase.io/
- [x]   Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x]   Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [x]   Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- []   For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- []   For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

### node, npm, react-native, react and native-base version, expo version if used, xcode version
React native => 0.56.0
native-base => 2.10.0

### Expected behaviour
Show keyboard in language actual

### Actual behaviour
Keyboard change language automaticaly in another language

### Steps to reproduce

My default language is French.
On change input focus, in input secureTextEntry, keyboard change language to English.

normal input focus.
`Input contextMenuHidden={true} autoCorrect={false} onChangeText={(text) => { this.setState({pseudo:text}); }} returnKeyType={"done"} placeholder="Pseudo" />`

to bug input 
`<Input contextMenuHidden={true} autoCorrect={false} secureTextEntry={true} returnKeyType={"done"} onChangeText={(text) => { this.setState({password:text}); }} placeholder="Mot de passe" />`

### Is the bug present in both iOS and Android or in any one of them?
I tested only IOS Simulator and real device ios and not in android.

**Comment by suvenduchhatoi** [comment]
@GH974 Check this https://stackoverflow.com/questions/52701160/native-uitextfield-secure-text-entry-forces-english-us-keyboard . It seems to be an issue with react-native TextInput...
