### ISSUE TITLE
how change change text color for `Text` component

### ISSUE THREAD

**Issue by code-brewer** [GeekyAnts/NativeBase#2539]
I have eject themes, and then modify file "native-base-theme/components/Text.js" , change color attribute to `color: '#FFF000'`,  but it failed to change <Text> component's text color.

How can i do to make it take effect globally ?

**Comment by code-brewer** [comment]
I found that take effect by  wrapping with` <StyleProvider style={getTheme(customVariables)}>`
Though this is an approach, it would be nice and reasonable to make it globally take effect without introduce StyleProvider on every page.

**Comment by suvenduchhatoi** [comment]
@code-brewer 
Use ```import getTheme from "./native-base-theme/components";
import variables from "./native-base-theme/variables/platform";```, customize the variables you want in ```native-base-theme/variables/platform.js``` and wrap your code within ```<StyleProvider style={getTheme(variables)}>``` to see the reflected changes...

**Comment by code-brewer** [comment]
Thanks for your suggestion. As i have said that  wrapped component with <StyleProvider style={getTheme(variables)}> do work. But it still boring to edit every page files , and search for a  approach  that just edit ./native-base-theme/components and other file under ./native-base-theme/, then with some minimal change (maybe even without any change) to existing code to archive apllication-scope  style change.

**Comment by suvenduchhatoi** [comment]
@code-brewer 
For application level scope style change, you can pass theme a top-level Native Base component which wraps your entire app.
```
import {View} from 'native-base'; 
import darkTheme from './Themes/darkTheme'; 
import lightTheme from './Themes/lightTheme'; 
... 
<View theme={this.state.dark ? darkTheme : lightTheme}> <App /> </View>
```

**Comment by suvenduchhatoi** [comment]
https://github.com/GeekyAnts/NativeBase/blob/master/src/theme/variables/commonColor.js#L243 working fine
![screen shot 1440-06-01 at 12 16 11 pm](https://user-images.githubusercontent.com/44160581/52324941-34c66400-2a09-11e9-96c7-7a69bd5a066a.png)
![screen shot 1440-06-01 at 12 16 25 pm](https://user-images.githubusercontent.com/44160581/52324942-355efa80-2a09-11e9-8dbd-d3367d1bb06d.png)
