### ISSUE TITLE
Dynamic card items. 

### ISSUE THREAD

**Issue by thundenilla** [GeekyAnts/NativeBase#254]
Somehow if the card only have one child (carditems) the data array working perfectly fine. but if I added more than 1 child, i kept getting this 

> Adjacent JSX elements must be wrapped in enclosing tag.

which is already in CLOSE TAG.

**Comment by sankhadeeproy007** [comment]
Please attach a snippet, so that we can test it from our end.

**Comment by thundenilla** [comment]
`<Content style={{padding: 16}}>
          <Card
            dataArray={randomClient}
            renderRow={(randomClient) =>
            <CardItem header>  
              <Thumbnail style={{backgroundColor: 'red', width: 40,}}/>
              <Text>{randomClient.name}</Text>
            </CardItem>
            <CardItem button onPress={() => this.replaceRoute('service')}>
              <Text>{randomClient.address}</Text>
            </CardItem>
          }>
          </Card>
        </Content>`

**Comment by himanshu-satija** [comment]
Try this instead
```jsx
<Content style={{padding: 16}}>
  <Card dataArray={notifications}
    renderRow={(randomClient) =>
      <View>
        <CardItem header>
          <Thumbnail style={{backgroundColor: 'red', width: 40,}}/>
          <Text>{randomClient.message}</Text>
        </CardItem>
        <CardItem button onPress={() => this.replaceRoute('service')}>
          <Text>{randomClient.message}</Text>
        </CardItem>
      </View> }>
  </Card>
</Content>
```
We can't return adjacent JSX without wrapping them in a single element.
