### ISSUE TITLE
how can we change the background colour of disabled row in accordion?

### ISSUE THREAD

**Issue by malliswarit** [GeekyAnts/NativeBase#2540]
## I have gone through these following points
- []   Check latest documentation: https://docs.nativebase.io/
- []   Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- []   Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- []   Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- []   For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- []   For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

**Comment by suvenduchhatoi** [comment]
@malliswarit 
You can change backgroundColor of expanded row as in
![screen shot 1440-05-23 at 3 36 48 pm](https://user-images.githubusercontent.com/44160581/51900667-e519e400-23db-11e9-93a4-f10bc29f7e03.png)
There's no prop as ```disabled``` for Accordion Component

**Comment by malliswarit** [comment]
Can i have sample test case written for this accordion component please?

**Comment by suvenduchhatoi** [comment]
#2546
