### ISSUE TITLE
Can i have sample test case written for this accordion component please?

### ISSUE THREAD

**Issue by malliswarit** [GeekyAnts/NativeBase#2546]
## I have gone through these following points
- []   Check latest documentation: https://docs.nativebase.io/
- []   Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- []   Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- []   Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- []   For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- []   For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

**Comment by suvenduchhatoi** [comment]
@malliswarit  Please describe your issue...Is your issue related to #2540 ... Refer Nativebase Docs for Accordion sample
![screen shot 1440-05-26 at 2 43 41 pm](https://user-images.githubusercontent.com/44160581/52113712-18ed4780-2630-11e9-948e-08fd5ae0a572.png)

**Comment by malliswarit** [comment]
yes need test case for that implementation accordion. Iam not able to get it over native base git repository.

**Comment by suvenduchhatoi** [comment]
Here is the component defined- https://github.com/GeekyAnts/NativeBase/blob/master/src/basic/Accordion.js
And here is the use case-
https://docs.nativebase.io/Components.html#accordion-def-headref

**Comment by malliswarit** [comment]
I need unit testing template for accordion

**Comment by malliswarit** [comment]
I need unit testing template for accordion. Can you please send me?

**Comment by malliswarit** [comment]
Any update please?

**Comment by SupriyaKalghatgi** [comment]
@malliswarit Currently we are not available to update the missing test cases for components.
That's quite simple though. Please refer test cases for other NativeBase components here https://github.com/GeekyAnts/NativeBase/tree/master/__tests__/basic

**Comment by malliswarit** [comment]
Accordion test case seems to be not there. So i have asked.

**Comment by SupriyaKalghatgi** [comment]
@malliswarit https://github.com/GeekyAnts/NativeBase/issues/2546#issuecomment-460191263

**Comment by suvenduchhatoi** [comment]
@malliswarit https://github.com/GeekyAnts/NativeBase/blob/master/__tests__/basic/Accordion.android.js
https://github.com/GeekyAnts/NativeBase/blob/master/__tests__/basic/Accordion.ios.js
