### ISSUE TITLE
 feature request in accordion

### ISSUE THREAD

**Issue by mdmoin7** [GeekyAnts/NativeBase#2548]
I would suggest a small change in the accordion component, since even i have faced a similar issue whenever the expanded prop value was changed programmatically, the re-rendering wasn't happening. After investigating the code i could see that there's only componentDidMount hook added which only renders it once on load & does not render again on any change, i made a workaround by including the below snippet & got rid of the mount hook.
```
componentWillReceiveProps(nextProps) {
        this.setState({ selected: nextProps.expanded });
    }
```

**Comment by suvenduchhatoi** [comment]
@mdmoin7 
![screen shot 1440-05-30 at 1 10 42 pm](https://user-images.githubusercontent.com/44160581/52259119-9d4d0c80-2947-11e9-991d-b6f302738375.png)
![screen shot 1440-05-30 at 1 04 24 pm](https://user-images.githubusercontent.com/44160581/52259120-9d4d0c80-2947-11e9-9e94-598b4d515642.png)
On changing the subItems of Accordion, re-rendering is happening... On changing expanded prop, the Accordion component is re-rendered again... Actually the lifecycle method you are suggesting is UNSAFE_componentWillReceiveProps() ,but it could often lead to bugs and inconsistencies as per React Docs https://reactjs.org/docs/react-component.html#unsafe_componentwillreceiveprops

**Comment by mdmoin7** [comment]
maybe you can try exploring one use case with react-navigation included. In react-navigation componentDidMount will be called only on first load & anytime post that if you navigate didMount never gets called so there's not possibility of setState being called once again, thats the challenge there. You can refer the below link, yes willreceiveprops in now marked as unsafe but can we still use other hooks & try to achieve the same.
https://reactnavigation.org/docs/en/navigation-lifecycle.html
Just to give you an overview assuming you have 2 screens using stacknavigator, when you send the index position from screen A to B & try to use that index prop in B with accordion expanded prop it'll work the first time, but if you go back & change the index once again A will send the data to B but B expanded prop never updates because it was already mounted

**Comment by suvenduchhatoi** [comment]
Ok, you can make a PR for this along with explanation and screenshots of output. We can check...

**Comment by suvenduchhatoi** [comment]
@mdmoin7  Yes, reproduced your issue, yes the prop value is passing to the 2nd screen, but the corresponding Accordion element doesn't expand. Tried to implement your suggestion, but didn't work. Trying to fix it though... 
 ![screen shot 1440-06-07 at 8 03 35 pm](https://user-images.githubusercontent.com/44160581/52642754-a1f26180-2f01-11e9-9e59-e0f0b356d26a.png)

**Comment by mdmoin7** [comment]
i had found a workaround solution already, in that case to resolve that issue by using componentWillReceiveProps but its already marked unsafe now. But react gave a new static function getDerivedStateFromProps you can use that, i did not find time to go on to that & try it again. But you can explore it, you need to set state twice once on mount & once on change

**Comment by suvenduchhatoi** [comment]
Yes, tried to implement the above. Didn't work. Let's see

**Comment by mdmoin7** [comment]
It worked for me though, i'll try to post my solution after resolving it without using the unsafe hook. I have another issue now. I want the first component inside the content to be fixed, using absolute positioning does not help since it still scrolls through it any workarounds for the same or maybe like having multi row headers based scenario. something as below. I want that search bar to fixed along with the header, this is one use case i have another where it is below the header but not part of it but still needs to be fixed
![image](https://user-images.githubusercontent.com/45753713/52927913-ed25cd80-3362-11e9-86b2-0425a22172cf.png)

**Comment by hanykumar** [comment]
Hi @mdmoin7, can you provide minimal code reproduction for the same for easy understanding?

**Comment by mdmoin7** [comment]
Thanks for the superfast reply not using native base anymore for anything.
