### ISSUE TITLE
How to dynamically change Button enable/disable state?

### ISSUE THREAD

**Issue by msqar** [GeekyAnts/NativeBase#2549]
I see that ReactNative Button has a "disabled" property, but how can I trigger it based on a component state value?

```
<Button { this.state.buttonDisabled ? disabled : '' }>
      <Text>Label</Text>
</Button>
```

Is there a way or I should use a different approach? Like using TouchableOpacity.

**Comment by iranmarcius** [comment]
AFAIK, from react, disabled is a property. It's presence is the same as "disable={true}". So you can use

```
<Button disabled={this.state.buttonDisabled}>
...
</Button>
```

**Comment by msqar** [comment]
Ohh i feel so dumb now. Thanks @iranmarcius .

**Comment by ImBeCiliC** [comment]
The style prop `style={{backgroundColor: "#0F0"}}` overrides the disabled prop.

**Comment by msqar** [comment]
@ImBeCiliC really? o_O why?

**Comment by ImBeCiliC** [comment]
@msqar I guess the style prop overrides all Button props.

**Comment by msqar** [comment]
Still,  disabled={true | false} shouldn't override because i guess it's the same React-Native disabled prop that will make the button untouchable. Imo it has nothing to do with styling, but I could be wrong.

**Comment by ImBeCiliC** [comment]
The Button is untouchable but you override the backgroundColor so it's not visually greyed out.

**Comment by msqar** [comment]
Ah, i don't mind about that, i handle the disable styling too with something like:

`style={[ styles.button, this.state.isButtonDisabled ? styles.buttonDisabled : '' ]}`

Where for example I add some `opacity: 0.5` to it.

**Comment by ImBeCiliC** [comment]
Awesome wanted just to inform you but your commented code works fine. Doing it a similar way.

**Comment by NativLouie** [comment]
@ImBeCiliC Hi can you share the code of how you were able to accomplish this thanks

**Comment by NativLouie** [comment]
incase someone needs this,

place the follow in the render block and set disabled to` !isenabled`
```
const { email, password } = this.state;
const isEnabled = email.length > 0 && password.length > 0;
```

**Comment by Alexkin2609** [comment]
In my case, I'm creating a Login form enabling/disabling the Login Button by checking the username and password inputs, if one of those is empty, I disable it, enabling it when both inputs are not empty. This worked for me:
I created a two variables in the state (user, password) and at the end I only check when the Username or the Password TextInputs are empty, I asign them to the state and in the button I check them in the disabled property.

class Login extends Component {
  constructor(props) {
    super(props);
    this.state = {
      user: '',
      password: ''
    }
  }

render() {
    return (
      <View >
        <TextInput
        style={styles.inputs}
        value={this.state.user}
        onChangeText={(user) => this.setState({user})}
        placeholder='Username'
        underlineColorAndroid='transparent' />
        <TextInput
        style={styles.inputs}
        value={this.state.password}
        onChangeText={(password) => this.setState({password})}
        placeholder='Password'
        secureTextEntry
        underlineColorAndroid='transparent' />
        <Button
        backgroundColor='#03A9F4'
        title='Entrar'
        onPress={() => this.loginUser()}
        disabled={(this.state.user == '' || this.state.password == '') ? true : false} />
    </View>
  );
}

**Comment by Sayyamabbasi786** [comment]
what if we have multiple buttons? does it suits to create a state for each button ??
