### ISSUE TITLE
incomplete trees returned by react-test-renderer

### ISSUE THREAD

**Issue by garfieldnate** [GeekyAnts/NativeBase#2550]
## I have gone through these following points
- [X]   Check latest documentation: https://docs.nativebase.io/
- [X]   Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [X]   Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [X]   Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink (KitchenSink does not use jest)
- [X]   For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/ (https://nativebase.slack.com/archives/C2XDREYSJ/p1547992457022900)
- [N/A]   For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

## Issue Description

I'm trying to use Jest to test components I've created with native-base. However, `react-test-renderer`'s `create` method seems to return incomplete trees. Here's an example to try out:

    import React from 'react';
    import { Button, Icon, Content, Text } from 'native-base';
    import AddDeckButton from '../../Components/AddDeckButton.js';
    import renderer from 'react-test-renderer';
    ​
    it("renders icon button", () => {
     const tree = renderer
      .create(
        <Button transparent>
        <Icon
          style={{fontSize: 36}}
          name="ios-add-circle-outline" />
      </Button>
      )
      .toJSON();
     expect(tree).toMatchSnapshot();
    });

And here's the snapshot generated:

    // Jest Snapshot v1, https://goo.gl/fbAQLP
    exports[`renders icon button 1`] = `
    <View
      accessible={true}
      isTVSelectable={true}
      onResponderGrant={[Function]}
      onResponderMove={[Function]}
      onResponderRelease={[Function]}
      onResponderTerminate={[Function]}
      onResponderTerminationRequest={[Function]}
      onStartShouldSetResponder={[Function]}
      style={
        Object {
          "alignItems": "center",
          "alignSelf": "flex-start",
          "backgroundColor": "transparent",
          "borderBottomWidth": null,
          "borderColor": "#007aff",
          "borderLeftWidth": null,
          "borderRadius": 5,
          "borderRightWidth": null,
          "borderTopWidth": null,
          "borderWidth": undefined,
          "elevation": 0,
          "flexDirection": "row",
          "height": 45,
          "justifyContent": "space-between",
          "opacity": 1,
          "paddingBottom": 6,
          "paddingTop": 6,
          "shadowColor": null,
          "shadowOffset": null,
          "shadowOpacity": null,
          "shadowRadius": null,
        }
      }
    >
      <Text />
    </View>
    `;

Notice that the `Text` component is completely empty and has no styling. So we could change the icon or `fontSize` and the test would still pass because the snapshots would match!

### node, npm, react-native, react and native-base version, expo version if used, xcode version
node 11.6.0, react-native 0.57.1, native-base 2.10.0, expo 2.6.14, xcode 10.1, jest-react-native 18.0.0

### Is the bug present in both iOS and Android or in any one of them?
I was only able to check with iOS (simulator for SE).

**Comment by suvenduchhatoi** [comment]
@garfieldnate check this- complete tree is rendered 
![screen shot 1440-06-09 at 7 33 32 pm](https://user-images.githubusercontent.com/44160581/52791800-d4ca6000-308f-11e9-99a7-10831007e713.png)
![screen shot 1440-06-09 at 7 36 47 pm](https://user-images.githubusercontent.com/44160581/52791826-e449a900-308f-11e9-910c-eb2b579336db.png)

**Comment by garfieldnate** [comment]
I'm including a breaking example here. I am using Expo and I have not ejected.

[nativebase-jest.tar.gz](https://github.com/GeekyAnts/NativeBase/files/2866458/nativebase-jest.tar.gz)

Do the following:

    cd nativebase-jest
    yarn
    npm test

The test will pass. Inspect the snapshot to see the issue I mentioned in my opening comment.

**Comment by SupriyaKalghatgi** [comment]
I verified jest with Expo using React Native components and Icons from Expo/vector-icons
Behaves the same

![image](https://user-images.githubusercontent.com/13464885/53223493-8a507100-3697-11e9-9a33-1ce81b8b491a.png)

![image](https://user-images.githubusercontent.com/13464885/53223507-976d6000-3697-11e9-906c-ef1f8599a166.png)

**Comment by SupriyaKalghatgi** [comment]
Jest with React Native and NativeBase Icon

![image](https://user-images.githubusercontent.com/13464885/53223570-ca175880-3697-11e9-96c6-61cfc9e1e575.png)

![image](https://user-images.githubusercontent.com/13464885/53223588-db606500-3697-11e9-8075-a8cef1ecbd90.png)

**Comment by garfieldnate** [comment]
Hi Supriya,

Thank you for responding to this issue. I was unable to reproduce a successful test using the code that you provided.

However, I did find the problem. It is here: https://github.com/expo/vector-icons/blob/master/createIconSet.js#L39. In Expo, fonts, including icons, are loaded asynchronously in the background. If you try to render an element that uses a font before it finishes loading, then it defaults to simply rendering an empty `<Text />` with no styling. The fix is to add this to your Jest tests:

    import { Ionicons } from '@expo/vector-icons';
    beforeAll(() => {
      return Font.loadAsync(Ionicons.font);
    });

Of course, you may need to replace Ionicon with FontAwesome or whatever icon you happen to be using.

I will contact the maintainers of Expo and try to improve the documentation in that project. I honestly don't understand how fonts work in RN very well right now.

I super appreciate your responding to this ticket, but I have one important suggestion for working with contributors in the future. Please, please don't paste screenshots of code. Paste actual text code that can be copied and pasted into a reader's project. If you indent the code with 4 spaces in a comment on GitHub, it will be styled as code, with syntax highlighting and everything. It is tedious to copy code from screenshots to see if it works, and placing text content in images prevents blind developers from being able to access any help that you provide here. 

In this case it was also unclear to me whether the code you provided was meant to be used in the example project I posted here or whether you created a new project with different settings, since you did not specify which. I could not get the code you provided to work with the sample project I provided, so I assumed that you had a different project setup. If that is not the case, then there may be some other difference (OS, for example).

Thanks again for your help!

Nathan

**Comment by garfieldnate** [comment]
I opened expo/expo/issues/3566 to address this.

**Comment by SupriyaKalghatgi** [comment]
I added these test cases in the project that you shared
https://github.com/GeekyAnts/NativeBase/issues/2550#issuecomment-463753530
