### ISSUE TITLE
Fab in header

### ISSUE THREAD

**Issue by itcurves** [GeekyAnts/NativeBase#2556]
## I have gone through these following points
- [x]   Check latest documentation: https://docs.nativebase.io/
- [x]   Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x]   Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [x]   Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [x]   For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- [x]   For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

## Issue Description

I am trying to use Fab in the header but facing 2 issues:

1. place in the exact left side
2. on open it hide behind the body, I would like to show in front of the body.

how I can achieve it?

![image](https://user-images.githubusercontent.com/1397397/52295485-ebfba600-2949-11e9-978d-748b687eabc6.png)

### node, npm, react-native, react and native-base version, expo version if used, xcode version
node > 10.5
npm > 6.7
react-native > 0.58.3
native-base > 2.11

**Comment by suvenduchhatoi** [comment]
@itcurves Using FAB in Header is something not as per design guidelines. Hence NativeBase won't support this. You can go ahead and fork NB to have your version of FAB.
