### ISSUE TITLE
Thumbnail within floatingLabel Item not showing in Release/Production mode

### ISSUE THREAD

**Issue by pratomchaip** [GeekyAnts/NativeBase#2559]
## I have gone through these following points
- [x]   Check latest documentation: https://docs.nativebase.io/
- [x]   Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x]   Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [x]   Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [x]   For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- [x]   For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

### node, npm, react-native, react and native-base version, expo version if used, xcode version
native-base: 2.11.0
node: v8.11.3
react: 16.6.3
react-native: 0.58.3
xcode: 9.2

### Expected behaviour
Thumbnail image within a floatingLabel Item should show to the right of the Input element.

### Actual behaviour
Thumbnail does not appear on Release/Production build BUT appears in the Debug build

### Steps to reproduce
```
<Item floatingLabel>  
  <Label>Card Number</Label>  
  <Input />  
  <Thumbnail source={require('./images/visa_card.png')} />  
</Item>
```

### Is the bug present in both iOS and Android or in any one of them?
Tested on iOS only - not working on Release build

**Comment by suvenduchhatoi** [comment]
@pratomchaip Should be working fine in Debug mode... Yes, we are checking it for Release mode...
![screen shot 1440-06-02 at 3 22 34 pm](https://user-images.githubusercontent.com/44160581/52404723-b1337280-2aef-11e9-8402-dba7e554f5b4.png)
![screen shot 1440-06-02 at 3 04 20 pm](https://user-images.githubusercontent.com/44160581/52404724-b1cc0900-2aef-11e9-8eab-731f6824e600.png)
