### ISSUE TITLE
FooterTab returns error when using an Icon

### ISSUE THREAD

**Issue by jesouhaite08** [GeekyAnts/NativeBase#256]
I used the [docs](http://nativebase.io/docs/v0.5.9/components#footerTabs) as a base to create a FooterTab. 

I receive the following error if I add an Icon element to a button: undefined is not an object (evaluation 'child.props.children.props.name') from FooterTab.js:114 (has since changed, now [line 142](https://github.com/GeekyAnts/NativeBase/blob/master/Components/Widgets/FooterTab.js#L142)).

Below is the code I am using in my render function:

```
 <Footer>
          <FooterTab>
              <Button active={this.state.detailsTab} onPress={() => this.toggleDetailsTab()}>
                  Details
                  <Icon name='ios-home' style={globalStyles.inspectionsItemIcon} />
              </Button>
              <Button active={this.state.inspectionTab} onPress={() => this.toggleInspectionTab()}>
                  Inspection
              </Button>
              <Button active={this.state.insectsTab} onPress={() => this.toggleInsectsTab()}>
                  Insects
              </Button>
              <Button active={this.state.radonTab} onPress={() => this.toggleRadonTab()}>
                  Radon
              </Button>
          </FooterTab>
 </Footer>
```

If I remove the Icon from the first button everything works well.

Any ideas? Thanks in advance.

**Comment by sankhadeeproy007** [comment]
I'm curious to know, why would you want Icon in only a single tab? You'd rather have them in all the tabs or neither right?

**Comment by jesouhaite08** [comment]
@sankhadeeproy007 I would like to have an icon in all tabs. I just put the icon in one for the sake of this example. I had removed all of them so that I could continue working.

**Comment by monodop** [comment]
I am having this issue as well, but only if my container is wrapped in a react-native-drawer

**Comment by monodop** [comment]
Looks like this is caused by the lodash _.remove modifying your Button's children props. The above PR should fix it, or you can take a look at the PR to apply it right now as a quick fix. It worked for me, so hopefully it's the correct fix to this bug.

**Comment by sankhadeeproy007** [comment]
@jesouhaite08 silly question, but did you try putting an Icon inside all the buttons? I remember having tested it throughly. #242 even has a working example of the same.

**Comment by jesouhaite08** [comment]
@sanketsahusoft It produces the same error with an Icon inside all of the buttons.

**Comment by jesouhaite08** [comment]
@monodop Mine is only wrapped inside of a Container. Weird. Thanks for the reply.

**Comment by jesouhaite08** [comment]
Problem solved. I was importing Icon like this: 
import { Icon } from 'native-base';

Switched it to:
 import { Icon } from 'native-base';

And problem solved. Thanks, guys.
