### ISSUE TITLE
RedScreen if starting App from Xcode (react-native run ios --reset-chache works) 

### ISSUE THREAD

**Issue by xstable** [GeekyAnts/NativeBase#2560]
I have a strange Issue.

If I start Metro with: 
`react-native run ios --reset-cache`, the app working well at my USB-Connected Device.

If I start the App in Xcode, the App didn't work anymore (worked before).
Now I got this error: 

![redscreen_native-base-pathn](https://user-images.githubusercontent.com/1778068/52368431-ac6ab200-2a4e-11e9-9c22-af5036dcc5a9.png)

Trying since hours now, but didn't get it to work.

I think last I've changed before the error was upgrading babel (but not 100% sure, because in the last hours, I've tried many things to fix it).

Any suggestion, what's going wrong here?

Here my dependencies from package.json: 
```
 "dependencies": {
    "fbjs": "^0.8.17",
    "lodash": "^4.17.11",
    "lodash.isequal": "^4.5.0",
    "native-base": "https://github.com/xstable/NativeBase.git",
    "npm": "^5.8.0",
    "prop-types": "^15.6.1",
    "react": "16.4.1",
    "react-devtools": "^3.2.1",
    "react-native": "^0.56.1",
    "react-native-cacheable-image": "^2.0.0",
    "react-native-fast-image": "^5.1.2",
    "react-native-firebase": "^4.3.8",
    "react-native-grid-list": "^1.0.9",
    "react-native-image-zoom-viewer": "^2.2.23",
    "react-native-modal-dropdown": "^0.6.2",
    "react-native-render-html": "^3.9.3",
    "react-native-safe-area-view": "^0.7.0",
    "react-native-scrolling-menu": "experiment322/react-native-scrolling-menu",
    "react-native-transformable-image": "https://github.com/xstable/react-native-transformable-image.git",
    "react-native-vector-icons": "^6.1.0",
    "react-native-video": "tranvinhtruong/react-native-video",
    "react-native-video-player": "https://github.com/tranvinhtruong/react-native-video-player",
    "react-native-youtube": "^1.1.0",
    "react-navigation": "^1.5.11",
    "reactotron-react-native": "^1.14.0",
    "webpack": "^4.5.0"
  },
  "devDependencies": {
    "@babel/core": "^7.0.0",
    "@babel/preset-flow": "^7.0.0",
    "@babel/register": "^7.0.0",
    "babel-core": "^7.0.0-bridge.0",
    "babel-eslint": "^9.0.0",
    "babel-jest": "^23.4.2",
    "babel-plugin-transform-remove-console": "^6.9.2",
    "babel-preset-react-native": "^5.0.2",
    "eslint": "^5.12.1",
    "eslint-config-airbnb": "^17.1.0",
    "eslint-plugin-import": "^2.14.0",
    "eslint-plugin-jsx-a11y": "^6.1.1",
    "eslint-plugin-react": "^7.11.1",
    "eslint-plugin-react-native": "^3.2.1",
    "jest": "23.6.0",
    "react-test-renderer": "16.6.1"
  },
  "jest": {
    "preset": "react-native"
  }
```

**Comment by suvenduchhatoi** [comment]
@xstable The error shows that it is unable to find module `native-base-theme/components`, which means you had ejected theme using `node node_modules/native-base/ejectTheme.js`, but may have deleted the folder `native-base-theme`, but now you are trying to import components or variables from `native-base-theme` somewhere in your code... You should clear your cache using https://gist.github.com/jarretmoses/c2e4786fd342b3444f3bc6beff32098d , and then run 
```node node_modules/native-base/ejectTheme.js``` if you want to customize

**Comment by xstable** [comment]
@suvenduchhatoi it seems to be nothing that depends on missing or wrong packages.
It seems that it depends an Bug in react-native and the way the packager.sh is used from XCode.

https://github.com/facebook/react-native/issues/23342

**Comment by suvenduchhatoi** [comment]
Yes, probably it is a react-native error...
