### ISSUE TITLE
nativebase customizer

### ISSUE THREAD

**Issue by marketmix-matteoquintero** [GeekyAnts/NativeBase#2561]
I already have my variable.js file, what is the next step as I implement it in my project?

**Comment by suvenduchhatoi** [comment]
@marketmix-matteoquintero Once you click the 'Download Variable File' in NativeBase Customizer, you should see this-
![screen shot 1440-06-02 at 4 17 45 pm](https://user-images.githubusercontent.com/44160581/52407022-2bb2c100-2af5-11e9-9e18-7df87e7707df.png)
You need to go through Docs section https://docs.nativebase.io/Customize.html#Customize and follow the steps to implement it in your project...
