### ISSUE TITLE
Picker Android Placeholder

### ISSUE THREAD

**Issue by ForeverYouth** [GeekyAnts/NativeBase#2563]
## I have gone through these following points
- [x]   Check latest documentation: https://docs.nativebase.io/
- [x]x   Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x]   Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [x]   Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [x]   For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- [x]   For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

### Expected behaviour

Show placeholder or nothing when value if undefined.

### Actual behaviour

Showed first item from list.

### Is the bug present in both iOS and Android or in any one of them?

Only on Android. In iOS when i have no value in render empty line.

### Any other additional info which would help us debug the issue quicker.

So. My problem is that i have a list of options and Picker component. When i render Picker component and have undefined value of picker value - in title render first element of list. It's a little dissonance because user sees that value is set but in state value is undefined.

**Comment by suvenduchhatoi** [comment]
@ForeverYouth If you see th configuration Table of Picker component, it has been specified that `placeholder` prop is specific to IOS only
![screen shot 1440-06-03 at 3 55 00 pm](https://user-images.githubusercontent.com/44160581/52472776-223f5c80-2bba-11e9-84c4-345e32aeafcf.png)

**Comment by greyhands2** [comment]
My solution was to use the first picker item as my placeholder and style the color to be the same as the intended placeholder and set the value to nothing. That way when your validation function checks for empty input submission it can flag a field required message for the picker select input.
My code below:

<Picker.Item label="Office eg: VC, DSA" value="" color="#c1c1c1"/>
                <Picker.Item label="Vice Chancellor" value="key0" />
                <Picker.Item label="Principal Officer" value="key1" />
