### ISSUE TITLE
Unable to install native-base

### ISSUE THREAD

**Issue by maheshkumar2150** [GeekyAnts/NativeBase#2565]
npm ERR! path \react_native\native-base-example\node_modules\native-base\node_modules\fs-extra
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename '\react_native\native-base-example\node_modules\native-base\node_modules\fs-extra' -> '\react_native\native-base-example\node_modules\native-base\node_modules\.fs-extra.DELETE'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR! debug.log

**Comment by suvenduchhatoi** [comment]
@maheshkumar2150 
Which versions of react-native, native-base, react, npm are you using...
-For a fresh native-base installation, follow the steps-
```
react-native init AwesomeNativeBase
cd AwesomeNativeBase
npm install native-base --save
npm install
react-native link
```
If you still can't get native-base installed, please describe your issue as per ISSUE_TEMPLATE format

**Comment by maheshkumar2150** [comment]
Thanks for the help.

`rm -rf node_modules/` and then `npm install`

Worked!

Thanks. It was permission problem.
