### ISSUE TITLE
Radio Button border is actually a Icon and can't be changed.

### ISSUE THREAD

**Issue by itspauloroberto** [GeekyAnts/NativeBase#2566]
**Environviment**
node: v11.1.0
react-native: "https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz" (expo)
expo: "^32.0.0"
@expo/vector-icons: "^9.0.0"
native-base: "^2.10.0"
vscode: 1.30.2
react: "16.5.0"
redux-form: "^8.1.0"
PS: my theme is ejected.

I am using redux-form, and besides that, i created a custom component render for Radio as well:
```
export const renderRadio = ({onPress, selected, type, label, handleChange, meta: {touched, error}, ...field}) => {
  let hasError = false;
  if(error !== undefined && touched === true) hasError = true;
  
  return(
    <Item error={hasError}>
      <Radio
        color={colors.appLightBlue}
        selectedColor={colors.appLightBlue}
        selected={selected}
        onPress={onPress}
      />
      <Label>{label}</Label>
      {hasError ? <Text>{error}</Text> : <Text />}
    </Item>
  );
};
```

**The actually problem/issue and my Objective**
Well, the problem is that i dont have any way to change the **borderWidth** of the NativeBase **<Radio>** component, because it haves a Icon inside it instead of something that i can Style the Border. My goal is to change the **borderWidth** of the **Radio** NativeBase Component to match design specs as requested.

The actual behaviour/looking of the Radio rendered on screen is that one:
![NativeBase.RadioButton](https://user-images.githubusercontent.com/6789373/52513190-52095700-2bf0-11e9-9bbc-2a9171f18f84.png)

The desired behaviour/looking that is on the design specs is that one:
![Design Specs Radio Buttons](https://user-images.githubusercontent.com/6789373/52513210-6fd6bc00-2bf0-11e9-8c28-037fb3b5597e.png)

Well the only thing that is different on both images is the width of the border, but since it is a Icon i cant change it via Theme Ejecting child styling like **"NativeBase.Something":{ borderWidth: 1 }**

So i don't know what to do, maybe this is actually impossible? There is a way i can do that?

Maybe adding a new props that allow me to change the Radio's Icon or changing it to a View or something like that with Border and BorderRadius instead of using a Icon (thats weird at all) 

### Steps to reproduce
You only need to put a <Radio> component from 'native-base' on screen, and you can see the border having that width of something like 2dp  or 3 i think. As well you cannot change it.

### Is the bug present in both iOS and Android or in any one of them?
I dont know, i think it is only Android. I have not tested on IOS.

**Comment by suvenduchhatoi** [comment]
@itspauloroberto radio button had to be an Icon. And with Icon, we cannot customize border. You may change platform variable values to get your customized shape as in...
![screen shot 1440-06-07 at 2 15 23 am](https://user-images.githubusercontent.com/44160581/52592757-38c10e80-2e6d-11e9-8835-a82d0593bb8b.png)
![screen shot 1440-06-07 at 2 15 49 am](https://user-images.githubusercontent.com/44160581/52592758-38c10e80-2e6d-11e9-863c-0de88e129505.png)
![screen shot 1440-06-07 at 2 22 42 am](https://user-images.githubusercontent.com/44160581/52592760-3959a500-2e6d-11e9-8335-783a62f0fb36.png)

**Comment by itspauloroberto** [comment]
@suvenduchhatoi why it **have** to be a Icon? but nevertheless, the thing is that i cannot **change** the icon if i want some icon that have different design specs, just like changing the border, the solution you did present only changed the size of it, does not help on that border issue.

Native-Base have a lot of Icon types, i mean, sources of different icons, may providing a props that allows you to change the type and name properties of the Icon probably will do the trick and then you have a custom RadioButton.
