### ISSUE TITLE
Item component doesn't allow conditional styling.

### ISSUE THREAD

**Issue by msqar** [GeekyAnts/NativeBase#2567]
I wanted to add a styling conditional on my NativeBase `<Item>` and found out that it wasn't updating properly whenever i changed the state of the flag. I thought it was my code caching or something but it wasn't. Changed Item for a normal View, and worked as intended.

This is an example of what I did.

```
<Item style={[ styles.styleOne, this.state.isDisabled ? styles.styleForDisabled : '' ]}>
    <SomeStuff></SomeStuff>
</Item>
```

Please check if this happen to you too guys. It seemed pretty weird. Normal styling worked, but conditional didn't. 

```
   "native-base": "^2.10.0",
    "react": "16.6.3",
    "react-native": "0.57.8",
```

**Comment by suvenduchhatoi** [comment]
@msqar Check this snippet. It's working fine...
```
import React, { Component } from "react";
import { StyleSheet } from "react-native";
import {
  Container,
  Header,
  Item,
  Input,
  Icon,
  Button,
  Text
} from "native-base";
const styles = StyleSheet.create({
  styleone: {
    marginLeft: 30
  },
  bgred: {
    backgroundColor: "red"
  },
  bgyellow: {
    backgroundColor: "yellow"
  }
});

export default class SearchBarExample extends Component {
  constructor(props) {
    super(props);
    this.state = { isShowingText: true };
  }
  render() {
    return (
      <Container>
        <Header searchBar rounded>
          <Item
            style={[
              styles.styleone,
              this.state.isShowingText ? styles.bgred : styles.bgyellow
            ]}
          >
            <Icon name="ios-search" />
            <Input placeholder="Search" />
            <Icon name="ios-people" />
          </Item>
          <Button transparent>
            <Text style={styles.text}>Search</Text>
          </Button>
        </Header>
      </Container>
    );
  }
}
```
![screen shot 1440-06-06 at 6 07 41 pm](https://user-images.githubusercontent.com/44160581/52563648-13f67800-2e28-11e9-9840-b01cca37598f.png)
![screen shot 1440-06-06 at 6 07 52 pm](https://user-images.githubusercontent.com/44160581/52563649-13f67800-2e28-11e9-9bdd-bda72fbc2e4a.png)

**Comment by msqar** [comment]
Yes, that works but have you tried setting the flag to false so yellow will show up? In my case, only the first condition would be triggered, in your example would be red, and no matter what i change the value to for the flag, it would stuck in red.

**Comment by suvenduchhatoi** [comment]
But I have used exactly the similar use case as yours, and it is working

**Comment by msqar** [comment]
Okay then it might be my app, using View as replacement though. Thanks @suvenduchhatoi
