### ISSUE TITLE
RefreshControl in content

### ISSUE THREAD

**Issue by juanfe190** [GeekyAnts/NativeBase#257]
Im getting `maximum call stack size exceeded` when adding RefreshControl to any Native Base component. And in Android it freezes the app.

**Comment by sankhadeeproy007** [comment]
@himanshu-satija @sanketsahusoft  this was working before, shallow merge ignores refreshControl 😕

**Comment by sanketsahusoft** [comment]
@sankhadeeproy007 Thanks for pointing this out. We will check it tomorrow morning first thing.

@himanshu-satija Let's get this working.

**Comment by himanshu-satija** [comment]
@juanfe190 Works fine for me on both v0.5.11 and v0.5.12. Please share your code snippet that I can test.

**Comment by SupriyaKalghatgi** [comment]
@juanfe190 Working with latest release?
