### ISSUE TITLE
`ListItem` with `Left/Right` does not justify content correctly.

### ISSUE THREAD

**Issue by reitermarkus** [GeekyAnts/NativeBase#2571]
## I have gone through these following points
- [x]   Check latest documentation: https://docs.nativebase.io/
- [x]   Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x]   Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [x]   Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [ ]   For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- [x]   For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

## Issue Description

I am using the following code in a `List`:

```jsx
<ListItem>
  <Left>
    <Text>Model</Text>
  </Left>
  <Right>
    <Text>{DeviceInfo.getModel()}</Text>
  </Right>
</ListItem>
```

This produces the following output:

![bildschirmfoto 2019-02-13 um 01 08 52](https://user-images.githubusercontent.com/1309829/52676879-f3afe180-2f2b-11e9-9bd5-2c9847dba37b.png)

### node, npm, react-native, react and native-base version, expo version if used, Xcode version

```
node         11.9.0
react-native 0.58.4
native-base  2.11.0
```

### Expected behaviour

Produces the correct output, without unnecessarily wrapping multiple lines:

![bildschirmfoto 2019-02-13 um 01 13 05](https://user-images.githubusercontent.com/1309829/52677022-85b7ea00-2f2c-11e9-8370-22250b9619eb.png)

I managed to do this by setting `flex: 1` for both `Left` and `Right`:

```jsx
<ListItem>
  <Left style={{flex: 1.0}}>
    <Text>Model</Text>
  </Left>
  <Right style={{flex: 1.0}}>
    <Text>{DeviceInfo.getModel()}</Text>
  </Right>
</ListItem>
```

### Actual behaviour

Produces the output seen in the issue description.

### Steps to reproduce

See code in issue description.

### Is the bug present in both iOS and Android or in any one of them?

Both.

### Any other additional info which would help us debug the issue quicker.

I tried setting `flex: 1` everywhere in `theme/components/ListItem.js`, which also didn't work.

**Comment by suvenduchhatoi** [comment]
@reitermarkus In your ejected theme, set `flex:1` as in the screenshot
![flex 1 in eject themes fixed it](https://user-images.githubusercontent.com/44160581/52768621-045b7700-3054-11e9-82cd-5bb9e4e3fa43.png)

**Comment by reitermarkus** [comment]
@suvenduchhatoi, I was previously using 

```jsx
import { getTheme } from 'native-base'
import platform from './native-base-theme/variables/platform'
```

because I only needed custom colors.

If I actually use the ejected theme as the `getTheme` function like

```jsx
import getTheme from './native-base-theme/components'
import platform from './native-base-theme/variables/platform'
```

it works without adding `flex: 1` at all. Any idea why `getTheme` behaves differently depending on where it is imported from?

**Comment by reitermarkus** [comment]
I just tried one more thing. It works with

```jsx
import getTheme from './node_modules/native-base/src/theme/components'
```

but it doesn't work with

```jsx
import getTheme from './node_modules/native-base/dist/src/theme/components'
```

**Comment by suvenduchhatoi** [comment]
@reitermarkus It has been mentioned in the docs how to import getTheme https://docs.nativebase.io/Customize.html#theaming-nb-headref
![screen shot 1440-06-09 at 7 45 55 pm](https://user-images.githubusercontent.com/44160581/52792352-2aebd300-3091-11e9-913f-cb8f5b54a0c3.png)

While making customization, you may use native-base-theme, else if you are customizing from within node_modules, you need to set the `"main": "dist/src/index.js" to `"main": "src/index.js",`. The reason is it needs to be transpiled before running from within dist folder
