### ISSUE TITLE
Tab style reset when tab used as reusable component.

### ISSUE THREAD

**Issue by z3us94** [GeekyAnts/NativeBase#2573]
Hi everyone,

I have created small tabed form with Tab and Tabs component. It works fine with the following of documentation. But what i want to achieve is that instead defining same `tabStyle, activeTabStyle, textStyle, activeTextStyle` for each Tab that im creating, Create one component that wraps around this tab element which is defined with all the above mentioned properties. And then use that to render whatever the child content that im passing. It works without error. But the thing is the styles that im applying are not applied with this approach. Is there a workaround this ? 
I attached code snippets as well to get a better understanding of my issue.

```javascript
const TabItem = (props) => {
  return (
  <Tab `heading={props.heading}
      tabStyle={FormTabStyles.header} 
      activeTabStyle={FormTabStyles.activetabheader}
      textStyle={FormTabStyles.text}
      activeTextStyle={FormTabStyles.activetext}
      >
      {props.children}
    </Tab>
  );
}
```
```javascript
and to get the render i want i use it like below.
<Tabs tabBarUnderlineStyle={FormTabStyles.tabBarUnder}>
     <TabItem heading="Phone">
        <Text>Hello Tab Phone</Text>
     </TabItem>    
    <TabItem heading="Car">
        <Text>Hello Tab Car</Text>
     </TabItem>
 </Tabs>
```

Am i missing something or doing this the wrong way ?
Thanks in advance.

**Comment by suvenduchhatoi** [comment]
@z3us94 The docs use case is running fine as far as styling is concerned. May be you are missing something in your custom component. Refer https://docs.nativebase.io/Customize.html#custom-component-headref
![screen shot 1440-06-09 at 3 25 57 pm](https://user-images.githubusercontent.com/44160581/52778850-e9e1c780-306c-11e9-8b83-58a622ba350b.png)

**Comment by z3us94** [comment]
@suvenduchhatoi Thank you for the response.
yeah as i mentioned the default usage works fine with me too. the problem happens when i try to wrap my tab element into another component. Both custom component and the usage of it is included in the issue i mentioned in the form of code snippets.

**Comment by suvenduchhatoi** [comment]
Check the styling specified in docs for custom components . Follow the steps in your customized component https://docs.nativebase.io/Customize.html#custom-component-headref
![screen shot 1440-06-10 at 6 21 38 pm](https://user-images.githubusercontent.com/44160581/52857958-cbec9380-314e-11e9-9822-0cebfd72474f.png)
