### ISSUE TITLE
Tabs is shaking

### ISSUE THREAD

**Issue by lainguyen92** [GeekyAnts/NativeBase#2575]
> ##

 Issue Description
Tabs is shaking when changing app language
### node, npm, react-native, react and native-base version, expo version if used, xcode version
"react": "16.6.1",
"react-native": "^0.57.8",
"native-base": "^2.11.0",
### Expected behaviour
Pls fix this
### Actual behaviour
Tabs is shaking
### Steps to reproduce

Install app first time -> open app -> Change language in left menu -> Kill app -> Open app again, its happen Menu Shaking

### Is the bug present in both iOS and Android or in any one of them?
iOS only.

### Any other additional info which would help us debug the issue quicker.
Video: https://drive.google.com/file/d/1x6eNf5euCSSVEMlqh3--B_ECoig5qrjk/view?usp=sharing
> 

> 
<Tabs renderTabBar={()=> <ScrollableTab style={{ backgroundColor: 'transparent', borderBottomColor: Colors.transparent}}/>}
          tabContainerStyle={{backgroundColor: 'transparent',
          borderBottomColor: 'transparent', borderWidth: 0, elevation: 0}}
          locked
          tabBarUnderlineStyle={{ backgroundColor: Colors.bloodOrange, height: 0 }}>
          <Tab heading={I18n.t('menu.vae_live_radio', { locale: language })}
            tabStyle={styles.tabStyle}
            activeTabStyle={styles.activeTabStyle}
            textStyle={styles.textStyle}
            activeTextStyle={styles.activeTextStyle}
            style={{backgroundColor: 'transparent'}}>
            <VaeLiveRadioScreen/>
          </Tab>
          <Tab heading={I18n.t('menu.schedule', { locale: language })}
            tabStyle={styles.tabStyle}
            activeTabStyle={styles.activeTabStyle}
            textStyle={styles.textStyle}
            activeTextStyle={styles.activeTextStyle}
            style={{backgroundColor: 'transparent'}}>
            <ScheduleScreen/>
          </Tab>
          <Tab heading={I18n.t('menu.podcast', { locale: language })}
            tabStyle={styles.tabStyle}
            activeTabStyle={styles.activeTabStyle}
            textStyle={styles.textStyle}
            activeTextStyle={styles.activeTextStyle}
            style={{backgroundColor: 'transparent'}}>
            <PodcastScreen/>
          </Tab>
          <Tab heading={I18n.t('menu.blog', { locale: language })}
            tabStyle={styles.tabStyle}
            activeTabStyle={styles.activeTabStyle}
            textStyle={styles.textStyle}
            activeTextStyle={styles.activeTextStyle}
            style={{backgroundColor: 'transparent'}}>
            <BlogScreen />
          </Tab>
        </Tabs>
>

**Comment by suvenduchhatoi** [comment]
Probably the issue is with `react-native-scollable-tab-view` and native-base `Tabs` is built on top of it. Similar issue https://github.com/ptomasroos/react-native-scrollable-tab-view/issues/478 seems to be unresolved yet...
