### ISSUE TITLE
borderRadius has no color in the corner nativebase card

### ISSUE THREAD

**Issue by NguyenPhatBG** [GeekyAnts/NativeBase#2576]
![capture](https://user-images.githubusercontent.com/33904172/52762864-e853d780-304b-11e9-88bb-f16d4d0c7252.PNG)

my code:
        height: undefined,
        width: undefined,
        marginBottom: 3,
        marginTop: 3,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: '#1599C9'

**Comment by SupriyaKalghatgi** [comment]
![image](https://user-images.githubusercontent.com/13464885/53089381-717a7b00-3532-11e9-81f7-4ef65c7a25a0.png)
