### ISSUE TITLE
Jest connectStyle Error

### ISSUE THREAD

**Issue by mreorhan** [GeekyAnts/NativeBase#2579]
## I have gone through these following points
- [x]   Check latest documentation: https://docs.nativebase.io/
- [x]   Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x]   Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [x]   Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- []   For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- []   For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

## Issue Description
```
import React from 'react'
import Route from '../route'
import renderer from 'react-test-renderer'

test('renders correctly', () => {
    const tree = renderer.create(<Route />).toJSON();
    expect(tree).toMatchSnapshot();
});
```

**The app working properly in normal case. But when I started jest, it gave an error like this:**
`Test suite failed to run

    XXX\node_modules\native-base-shoutem-theme\index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import connectStyle from "./src/connectStyle";
                                                                                                    ^^^^^^^^^^^^

    SyntaxError: Unexpected identifier

      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/ScriptTransformer.js:440:17)
      at Object.<anonymous> (node_modules/native-base/src/index.js:1:1)`

### node, npm, react-native, react and native-base version, expo version if used, xcode version
     node: v10.15.1
     npm: 6.4.1
    "expo": "^31.0.4",
    "native-base": "^2.8.1",
    "react": "^16.5.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-31.0.1.tar.gz",

### Expected behaviour

Passing test processing

### Actual behaviour
Gives the error

**Comment by theharness** [comment]
Same issue. Adding 

```
"jest": {
    "preset": "react-native",
    "transformIgnorePatterns": [
      "/node_modules/(?!native-base)/"
    ]
}
```

to `package.json` solves the issue but greatly increases testing time. Haven't found a better solution.

**Comment by suvenduchhatoi** [comment]
@mreorhan 
Try this
```
"jest": {
    "preset": "react-native",
    "transformIgnorePatterns": [
      "node_modules/(?!(react-native|expo|native-base-shoutem-theme|native-base|@expo)/)"
    ]
  },
```

**Comment by anuragdwivedi29** [comment]
i am also facing the same issue 
added the following in package.json 
"jest": {
    "preset": "react-native",
    "transformIgnorePatterns": [
      "/node_modules/(?!native-base)/"
    ]
}
but the issue is still not resolved 
my setup is like this
 node:v10.16.1
npm:6.10.3
        "native-base": "^2.13.5",
        "react": "16.8.6",
        "react-native": "0.60.5",
   "react-native-testing-library": "^1.11.1",
          "react-navigation": "^4.0.0",
        "react-navigation-material-bottom-tabs": "^1.1.1",
        "react-navigation-stack": "^1.5.1",
        "react-navigation-tabs": "^2.4.0",
   Any pointers on the same will be appreciated .
PS- I am not using expo

**Comment by ZuyuLiao** [comment]
Any component using native-base component will be like this

**Comment by anuragdwivedi29** [comment]
@ZuyuLiao  sorry I didn't get you.You mean to say that we can't do unit test on native base components

**Comment by ZuyuLiao** [comment]
@anuragdwivedi29 I just found out this rule, and no solution online could resolve it.

**Comment by FDiskas** [comment]
This works for me by adding to jest config
```
transformIgnorePatterns: ['node_modules/(?!(react-native|react-native-button|native-base-.*|react-native-.*)/)'],
```

But then I landed on second error
```
 FAIL  src/App.test.tsx
  ● Console

    console.error node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11958
      The above error occurred in the <StatusBar> component:
          in StatusBar (at Header.js:97)
          in View (created by View)
          in View (at Header.js:96)
          in Header (at connectStyle.js:392)
          in Styled(Header) (created by App)
          in View (created by View)
          in View (at Container.js:12)
          in Container (at connectStyle.js:392)
          in Styled(Container) (created by App)
          in App
      
      Consider adding an error boundary to your tree to customize error handling behavior.
      Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
    console.error node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11958
      The above error occurred in the <Icon> component:
          in Icon (at IconNB.js:90)
          in IconNB (at connectStyle.js:392)
          in Styled(IconNB) (at Icon/index.js:81)
          in Icon (at connectStyle.js:392)
          in Styled(Icon) (created by App)
          in View (created by View)
          in View (at createAnimatedComponent.js:151)
          in AnimatedComponent (at TouchableOpacity.js:308)
          in TouchableOpacity (at Button.js:79)
          in Button (at connectStyle.js:392)
          in Styled(Button) (created by App)
          in View (created by View)
          in View (at Left.js:10)
          in Left (at connectStyle.js:392)
          in Styled(Left) (created by App)
          in View (created by View)
          in View (at Header.js:125)
          in View (created by View)
          in View (at Header.js:96)
          in Header (at connectStyle.js:392)
          in Styled(Header) (created by App)
          in View (created by View)
          in View (at Container.js:12)
          in Container (at connectStyle.js:392)
          in Styled(Container) (created by App)
          in App
      
      Consider adding an error boundary to your tree to customize error handling behavior.
      Visit https://fb.me/react-error-boundaries to learn more about error boundaries.

  ● renders correctly

    TypeError: Cannot read property 'default' of undefined


ReferenceError: You are trying to `import` a file after the Jest environment has been torn down.

      at Function.bezier (node_modules/react-native/Libraries/Animated/src/Easing.js:219:21)
      at ease (node_modules/react-native/Libraries/Animated/src/Easing.js:93:24)
      at TimingAnimation._easing (node_modules/react-native/Libraries/Animated/src/Easing.js:245:18)
      at TimingAnimation.onUpdate (node_modules/react-native/Libraries/Animated/src/animations/TimingAnimation.js:135:12)
/Users/vkuciauskas/Projects/github/demonas/node_modules/react-native/Libraries/Animated/src/Easing.js:220
      return _bezier(x1, y1, x2, y2);
             ^

TypeError: _bezier is not a function
    at Function.bezier (/Users/vkuciauskas/Projects/github/demonas/node_modules/react-native/Libraries/Animated/src/Easing.js:220:14)
    at ease (/Users/vkuciauskas/Projects/github/demonas/node_modules/react-native/Libraries/Animated/src/Easing.js:93:24)
    at TimingAnimation._easing (/Users/vkuciauskas/Projects/github/demonas/node_modules/react-native/Libraries/Animated/src/Easing.js:245:18)
    at TimingAnimation.onUpdate (/Users/vkuciauskas/Projects/github/demonas/node_modules/react-native/Libraries/Animated/src/animations/TimingAnimation.js:135:12)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
Test Suites: 1 failed, 1 passed, 2 total
Tests:       1 failed, 1 passed, 2 total
Snapshots:   0 total
Time:        5.664s, estimated 10s
```

**Comment by GeDiez** [comment]
i found out the solution, reading into the [doc](https://jestjs.io/docs/en/tutorial-react-native#transformignorepatterns-customization) of jest, it can be figured out by avoiding transform packages in the npm folder.

```  "jest": {
    "preset": "react-native",
    "transformIgnorePatterns": [
      "node_modules/(?!(react-[a-z, -]*|react-native|native-base-[a-z, -]*|react-native-[a-z, -]*)/)"
    ]
  }
```

notice: Im using react-native (no expo) and ignoring the native-base, react-native and react folders

**Comment by Runtime-Err** [comment]
Having the exact same error as @mreorhan 

Editing transformIgnorePatterns doesn't do the job for me. When I run my test for a component that uses native base, it says:

```
 C:\Users\Test\AndroidStudioProjects\Testproject\node_modules\native-base-shoutem-theme\index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import connectStyle, { clearThemeCache } from "./src/connectStyle";
                                                                                                    ^^^^^^^^^^^^

    SyntaxError: Unexpected identifier
```

My `jest `config in `package.json`:

```
 "jest": {
    "preset": "react-native",
    "transform": {
      "^.+\\.js$": "<rootDir>/node_modules/react-native/jest/preprocessor.js",
      "\\.(ts|tsx)$": "ts-jest"
    },
    "globals": {
      "ts-jest": {
        "tsConfig": "tsconfig.jest.json"
      }
    },
    "moduleFileExtensions": [
      "ts",
      "tsx",
      "js",
      "jsx",
      "json",
      "node"
    ],
    "transformIgnorePatterns": [
      "node_modules/(?!(react-[a-z, -]*|react-native|native-base-[a-z, -]*|react-native-[a-z, -]*)/)"
    ],
    "testRegex": "(/__tests__/.*|\\.(test|spec))\\.(ts|tsx|js)$"
  }
```
I am looking for solution since two days now :(
