### ISSUE TITLE
rightButtons now show on ios < 12

### ISSUE THREAD

**Issue by tiennguyen9988** [GeekyAnts/NativeBase#2585]
"native-base": "^2.11.0",
"react": "16.8.2",
"react-native": "0.58.4",
xcode Version 10.1 (10B61)
rightButtons working good on ios 12 but not show on ios version below.
My code:
 Navigation.mergeOptions(this.props.componentId, {
      topBar: {
        title: {
          text: "Từ điển Anh Việt"
        },
        rightButtons: {
          id: 'buttonHistoryEV', 
          icon: require('rnapp/app/Assets/Images/icon_history_white.png')
        }
      }
    });
<img width="951" alt="screen shot 2019-02-17 at 11 53 01 am" src="https://user-images.githubusercontent.com/3782474/52908550-a70d3300-32aa-11e9-9797-15f3179ca021.png">

**Comment by SupriyaKalghatgi** [comment]
Working fine
![image](https://user-images.githubusercontent.com/13464885/53089628-18f7ad80-3533-11e9-9a39-1237a273f805.png)

**Comment by tiennguyen9988** [comment]
Thank you for feedback SupriyaKalghatgi! But are you sure it working on ios 10 and below?

**Comment by SupriyaKalghatgi** [comment]
yes

**Comment by tiennguyen9988** [comment]
No way friend! I tried many times on emulator and real devices but it not working on vesions above 2.6.0. So i was downgrade to 2.6.0 then it work.
