### ISSUE TITLE
Navigation animations not showing anymore

### ISSUE THREAD

**Issue by mreorhan** [GeekyAnts/NativeBase#2586]
## I have gone through these following points
- [x]   Check latest documentation: https://docs.nativebase.io/
- [x]   Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x]   Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [x]   Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- []   For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- []   For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

## Issue Description
I upgrade the new version of native base. From: 2.8.1. Then I realize that footer navigation animation is not showing.

```
import React,{Component} from 'react';
import {View} from 'react-native';
import { Footer, FooterTab, Button, Icon,StyleProvider } from 'native-base';
import globalStyles from '../../styles/globalStyles';
import getTheme from '../../native-base-theme/components';
import material from '../../native-base-theme/variables/material';
```

```
 <StyleProvider style={getTheme(material)}>
          <View style={globalStyles.footer}>
            <Footer style={globalStyles.footerShadow}>
            <FooterTab style={globalStyles.footerBackground}>
              <Button onPress={() => navigate('Home')}>
                <Icon name="navigate" style={globalStyles.blackColor}/>
              </Button>
              <Button onPress={() => navigate('SearchLocation')}>
                <Icon active name="search"  style={globalStyles.blackColor}/>
              </Button>
              <Button onPress={() => navigate('TakePicture')}>
                <Icon active name="md-add-circle"  style={globalStyles.blackColor}/>
              </Button>
              <Button onPress={() => navigate('Bookmarks')}>
                <Icon active name="md-bookmark"  style={globalStyles.blackColor}/>
              </Button>
              <Button onPress={() => navigate('User')}>
                <Icon name="person"  style={globalStyles.blackColor}/>
              </Button>
            </FooterTab>
          </Footer>
          </View>
          </StyleProvider>
```

### node, npm, react-native, react and native-base version, expo version if used, xcode version
    "expo": "^31.0.4",
    "native-base": "^2.11.0",
    "react": "^16.5.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-31.0.1.tar.gz"
     node v10.15.1
     npm v6.4.1
### Expected behaviour
Show animations
### Is the bug present in both iOS and Android or in any one of them?
Android

**Comment by SupriyaKalghatgi** [comment]
2.5.0 had SafeArea implementation and then onwards no updates made on Footer
