### ISSUE TITLE
Invariant Violation, Style Provider after RN Upgrade to 58.4

### ISSUE THREAD

**Issue by dl-husky73** [GeekyAnts/NativeBase#2587]
I am not sure if a bug, but did React Native, & React Navigation upgrades.  When I started app I got the following error.  If I remove Style Provider all works fine.  

I researched here, followed a few suggestions.  Reinstalled NB and ejected theme again but no change.  Seems issue with theme but all worked fine yesterday.  Any ideas?

Here is the error.   
![image](https://user-images.githubusercontent.com/47721681/52921328-ef951280-32e3-11e9-9924-890cf8d1d8c0.png)

I use the StyleProvider in several areas, I am showing a new screen just about to do.   Same problem everywhere.   Here is render skeleton code.  
![image](https://user-images.githubusercontent.com/47721681/52921350-1d7a5700-32e4-11e9-99a1-ba4d5d0873c6.png)

**Comment by vtur** [comment]
I have the same error.

**Comment by ubaidchalil** [comment]
Me also same error

**Comment by suvenduchhatoi** [comment]
May be you are using `material` theme. Yes, it is an issue with `material` theme due to height of `Header` component. Similar issue has been opened
