### ISSUE TITLE
Swipable list renderLeft(Right) row badly aligned after deleting row

### ISSUE THREAD

**Issue by ghjer** [GeekyAnts/NativeBase#2589]
Hello. When I delete a row from the Swipable list the next item is not rendered correctly if the size is not the same as the deleted item:

![swipablerowissue](https://user-images.githubusercontent.com/10112015/52948327-7811c280-3379-11e9-8f07-b13a33e3539d.gif)

**Comment by SupriyaKalghatgi** [comment]
As per design guidelines, a list can have single lined / two lined /three lined etc data as its sub-elements. A single list does not have a different number of lines of data with it subelements.

Similar is the case of swipe list
Example: YouTube history page
