### ISSUE TITLE
tabLabel property of Tabs component

### ISSUE THREAD

**Issue by cirojr** [GeekyAnts/NativeBase#259]
Hi! The tabLabel property seems to make no effect to me. The place where it should appear keeps white.
Everything else works, until now in this component.
What can I check?

**Comment by himanshu-satija** [comment]
It works fine for me however I see that the color of tabLabel is white and it is not configurable. We will update the Tabs in next version.
Until then you can use [this package](https://github.com/skv-headless/react-native-scrollable-tab-view) for Tabs.

**Comment by SupriyaKalghatgi** [comment]
@cirojr Fixed with [0.5.12](https://github.com/GeekyAnts/NativeBase/releases/tag/v0.5.12)
