### ISSUE TITLE
Toast doesn't work on Redux action (thunk) with react-native-navigation

### ISSUE THREAD

**Issue by manelsanz** [GeekyAnts/NativeBase#2590]
## I have gone through these following points
- [x]   Check latest documentation: https://docs.nativebase.io/
- [x]   Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x]   Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [x]   Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [x]   For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- [x]   For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

## Issue Description

I'm using Wix React Native Navigation with Redux, and all I want is to use `Toast.show` inside a Redux Action `(redux-thunk)` . I try using `Root` on my `index.js` like this, but not work:

```
import { Root } from "native-base";
import App from "./App";

const RNRedux = () => (
  <Root>
    <Provider store={store}>
      <App />
    </Provider>
  </Root>
);

AppRegistry.registerComponent(appName, () => RNRedux);

App();
```

And my `App.js`

```

Navigation.registerComponent(
  "printerapp.AuthScreen",
  () => props => (
    <Provider store={store}>
      <AuthScreen {...props} />
    </Provider>
  ),
  () => AuthScreen
);

Navigation.registerComponent(
  "printerapp.HomeScreen",
  () => props => (
    <Provider store={store}>
      <HomeScreen {...props} />
    </Provider>
  ),
  () => HomeScreen
);

// Start app
export default () => {
     Navigation.setRoot({
      root: {
        sideMenu: {
          left: {
            component: {
              name: "printerapp.HomeScreen",
              id: "SIDE_MENU_SCREEN"
            }
          },
          center: {
            stack: {
              id: "PARENT_STACK_ID",
              options: {},
              children: [
                {
                  component: {
                    id: "AUTH_SCREEN", 
                    name: "printerapp.AuthScreen",
                    options: {
                      topBar: {
                        title: {
                          text: "Select Printer"
                        }
                      }
                    }
                  }
                }
              ]
            }
          }
        }
      }
    });
}
```

### node, npm, react-native, react and native-base version, expo version if used, xcode version
node: v11.6.0
npm: 6.5.0-next.0,
react-native: 0.57.8
native-base: 2.11.0

### Is the bug present in both iOS and Android or in any one of them?
Only tested on Android

**Comment by SupriyaKalghatgi** [comment]
@manelsanz Its difficult to reproduce such issue
It would be better if you can put this on snack or create a repo and share the link here
