### ISSUE TITLE
getRef only working for floatingLabel (not fixedLabel, inlineLabel, or stackedLabel)

### ISSUE THREAD

**Issue by tmartin1** [GeekyAnts/NativeBase#2591]
## I have gone through these following points
- [x]   Check latest documentation: https://docs.nativebase.io/
- [x]   Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x]   Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [x]   Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink

### node, npm, react-native, react and native-base version, expo version if used, xcode version
```json
"native-base": "2.8.2",
"react": "16.3.2",
"react-native": "0.55.3",
"react-navigation": "2.7.0"
```

### Expected behavior
`getRef` should be called.

### Actual behavior
`getRef` is not called.

### Steps to reproduce
```javascript
class SomeForm {
  render() {
    return (
      <Form>
        <Item fixedLabel>
          <Label>Input stuff here:</Label>
          <Input getRef={() => {
            console.log('this should be logged, but isn\'t if `floatingLabel` isn\'t `true` on <Item>');
          }}>
          </Input>
        </Item>
      </Form>
    );
  }
}
```

### Is the bug present in both iOS and Android or in any one of them?
Both iOS and Android.

### Any other additional info which would help us debug the issue quicker.
Similar ticket: https://github.com/GeekyAnts/NativeBase/issues/2374 (closed, but the issue is still present for labels that are not `floatingLabel`).

I believe the cause of this issue can be plainly seen here: https://github.com/GeekyAnts/NativeBase/blob/master/src/basic/Item.js

On lines 36 and 55 in the above file, the if block, and call to `this.inputProps.getRef` are both inside the if block that checks for `this.props.floatingLabel`. As such, the `this.inputProps.getRef` is only getting called if the item has the `floatingLabel` property, which is why it isn't working for `fixedLabel`, `inlineLabel`, or `stackedLabel`.

So I think the if statement that check for `if (this.inputProps && this.inputProps.getRef)` just needs to be moved outside of the if statement that checks for `this.props.floatingLabel`.

**Comment by SupriyaKalghatgi** [comment]
`getRef` is only for floating labels, this is documented
![image](https://user-images.githubusercontent.com/13464885/53088585-337c5780-3530-11e9-90a9-863a42f3bfc8.png)

Apart from this, all other NativeBase components support `ref`
https://docs.nativebase.io/Components.html#ref-components-headref

**Comment by tmartin1** [comment]
Hmm, I tried `getRef` because `ref` wasn't working... deleted node_modules, reinstalled and it's all working fine with `ref`. Thanks for clearing that up though.
