### ISSUE TITLE
Styling the "height" attribute of a "Header" with a string results in error on iPhone X.

### ISSUE THREAD

**Issue by mccordgh** [GeekyAnts/NativeBase#2594]
## I have gone through these following points
- [x]   Check latest documentation: https://docs.nativebase.io/
- [x]   Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x]   Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [x]   Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [x]   For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- [x]   For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

### node, npm, react-native, react and native-base version, expo version if used, xcode version
**Node:** v11.6.0
**Npm:** v6.5.0-next.0
**React-Native:** sdk-31.0.0
**React:** v16.5.0
**Native-Base:** 2.10.0
**Expo:** 32.0.0
**Xcode:** v10.1

### Expected behaviour
When I style `height` attribute, with a string, for a `<Header>`, it works as expected.

### Actual behaviour
**A `24` is being tacked on to the string and causing an error:**

Setting the `<Header>` height to `"100%"` results in the error:
```JSON value '100%24' of type NSString cannot be converted to a ABI31_0_0YGValue. Did you forget the % or pt suffix?```

Setting the `<Header>` height to `"300px"` results in the error:
```JSON value '300px24' of type NSString cannot be converted to a ABI31_0_0YGValue. Did you forget the % or pt suffix?```

Setting the `<Header>` height to `"300pt"` results in the error:
```JSON value '300pt24' of type NSString cannot be converted to a ABI31_0_0YGValue. Did you forget the % or pt suffix?```

_etc..._

### Steps to reproduce
```
import { Header } from 'native-base';

...

    render() {
        return (
            <Header style={{ height: '100%' }}>
                ...
            </Header>
        }
...
```

_The above results in this error (screenshot from iPhone X emulator)_
![screen shot 2019-02-19 at 2 44 40 pm](https://user-images.githubusercontent.com/11222008/53052966-f1321800-3454-11e9-8eae-cecb91c669fd.png)

### Is the bug present in both iOS and Android or in any one of them?
I have tested this on: 
    • **Devices**: iPhone 7,
    • **Emulators:** iPhone X, iPhone XR, Nexus 5 (Android)

It only seems to happen on iPhone X and iPhone XR.

### Any other additional info which would help us debug the issue quicker.
I realized that setting the `height` attribute of a `<Header>` with an integer will make it work correctly.

i.e.
```
<Header style={{ height: 300 }}>
  ...
</Header>
```
However, for my use cases`'100%'` and other strings are much cleaner than height calculations, etc.

**Comment by SupriyaKalghatgi** [comment]
Header replacing component is `View`
View does not take height in `%`, hence Header fails.
Instead of 100% you can make use of Dimensions to get window height

**Comment by mccordgh** [comment]
@SupriyaKalghatgi thanks!

Do you know why this only happens on iPhone X, though??

It works as expected on everything else I tested with iPhone and Android 🤔
