### ISSUE TITLE
Ripple effect doesn't respect rounded button size

### ISSUE THREAD

**Issue by buzinas** [GeekyAnts/NativeBase#2596]
## I have gone through these following points
- [x]   Check latest documentation: https://docs.nativebase.io/
- [x]   Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x]   Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [x]   Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [x]   For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- [x]   For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

## Issue Description

I saw you fixed #1207 and #1553, but the ripple effect is giant on large rounded buttons.

### node, npm, react-native, react and native-base version, expo version if used, xcode version

Node v10.15.1
React Native v0.58.5
React v16.8.2
Native Base v2.11.0
Not using expo
XCode v10.1

### Expected behaviour

The ripple should respect the button size.

### Actual behaviour

The ripple goes completely off the button (only to the top).

#### Code snippet

For the sake of this example, this component is the topmost component in my App (but the problem also happens if it's not).

```jsx
import React from 'react'
import { Container, Content, Button, Text, Separator } from 'native-base'

export default () => (
  <Container>
    <Content>
      <Button full rounded onPress={f => f}>
        <Text>Test A</Text>
      </Button>
      <Separator />
      <Button full rounded onPress={f => f}>
        <Text>Test B</Text>
      </Button>
    </Content>
  </Container>
)
```

#### Screenshot

![ripple](https://user-images.githubusercontent.com/7298695/53064289-07b48f80-34a6-11e9-9c33-62bdd8739ec1.gif)

Note: if I click the first button, the problem doesn't happen, because the ripple goes off only to the top, never to the bottom.

### Is the bug present in both iOS and Android or in any one of them?

Only Android (iOS doesn't have ripple effect).

### Any other additional info which would help us debug the issue quicker.

Nope.

**Comment by SupriyaKalghatgi** [comment]
I tested this on Android device with https://github.com/GeekyAnts/NativeBase-KitchenSink latest

Worked fine for `rounded` and `full rounded`

**Comment by andreialecu** [comment]
@SupriyaKalghatgi this problem still exists. Could be because I'm on Android 9.

See https://github.com/facebook/react-native/issues/6480

**Comment by EhsanSarshar** [comment]
not working!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!11

**Comment by ParitoshVaidya** [comment]
not working for me as well

**Comment by jenskuhrjorgensen** [comment]
@SupriyaKalghatgi This is still a bug. On Android. Maybe not on all devices. 

I've created [this snack](https://snack.expo.io/S17BwF3lL) and it works in the Appetize web Android emulator, but it doesn't work on my OnePlus 5T with Oxygen 9.0.9:

![Screenshot_20200115-133003](https://user-images.githubusercontent.com/28528363/72434420-d7e83780-379b-11ea-83f0-ff4b58a2f0bc.jpg)

**Comment by Vali06** [comment]
I have the same issue, still looking for a solution.

**Comment by lyseiha** [comment]
+1

**Comment by lyseiha** [comment]
i found the solution

`<View style={{overflow: 'hidden', borderRadius: 30}}>
<Button rounded/>
</View>
`

**Comment by jenskuhrjorgensen** [comment]
@lyseiha Thank you for your answer, but I think it is more a hack than a solution. The `<Button/>` should itself be fixed so that your hack isn't necessary.

**Comment by frontendwizard** [comment]
this is still an issue on 3.2.2. I have a round button and the ripple effect overflows the button.

**Comment by hotaryuzaki** [comment]
how to create ripple effect?
because my button doesn't have any.
i use 3.4.25 version
