### ISSUE TITLE
App props to limit the scroll jump on tabs instead of checking with layout width

### ISSUE THREAD

**Issue by devarashetty** [GeekyAnts/NativeBase#2597]
I am currently checking with `Tabs` Component.I am trying to make sure the scroll will make sure to jump to next tab instead of multiple tabs. I am attaching the a video screen where I tried to show the usage .Let me know if you guys think its worth a try and can be thought of adding the feature to tabs.

**Comment by SupriyaKalghatgi** [comment]
@devarashetty Please follow issue template

**Comment by devarashetty** [comment]
@SupriyaKalghatgi  If I have to check for a feature or request for a feature where should I comment.

**Comment by SupriyaKalghatgi** [comment]
Requesting feature you can comment on #38
