### ISSUE TITLE
Wrong "engine-off" icon

### ISSUE THREAD

**Issue by davidinhong** [GeekyAnts/NativeBase#2598]
Hi everyone, 
I've a problem with the icon, in particular with "engine-off" and "engine-off-outline" icons,  in fact i get an icon similar to a japanese character.

I've tried to execute these comands:
npm unlink native-base
npm link native-base

I've also tried to uninstall and reinstall native-base with no success...

My NativeBase versione is the v2.11.0

**Comment by SupriyaKalghatgi** [comment]
@davidinhong Please follow issue template
Also that `engine-off` or `engine-off-outline` icon doesn't exist with `IonIcon` family
