### ISSUE TITLE
Wron "Engine-off" icon on iOS

### ISSUE THREAD

**Issue by davidinhong** [GeekyAnts/NativeBase#2599]
## I have gone through these following points
- [x]   Check latest documentation: https://docs.nativebase.io/
- [x]   Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x]   Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [x]   Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [x]   For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- [x]   For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

## Issue Description
I've tried to insert the icon "engine-off" with type "MaterialCommunityIcons", but on iOS i see the wrong icons, instead on Android all is ok.

### node, npm, react-native, react and native-base version, expo version if used, xcode version
node: v10.14.2
npm: 6.4.1
react-native: 0.57.5
not using expo
native-base: 2.11.0
xcode: 10.1
### Expected behaviour
I expect to see the "engine-of"f icon visible at the [link](https://oblador.github.io/react-native-vector-icons/) on both ios and android

### Actual behaviour
I see the correct icon on android, a wrong icon on ios

### Steps to reproduce
Simply insert an icon with this code:
`<Icon name="engine-off" type="MaterialCommunityIcons" />`
this is the icon that appears:
![wrong icon](https://user-images.githubusercontent.com/35532184/53089622-5ea17f80-350d-11e9-9163-8f463fb6d6bc.PNG)

### Is the bug present in both iOS and Android or in any one of them?
The bug is present only on iOS

### Any other additional info which would help us debug the issue quicker.
No other additional info are required.

**Comment by SupriyaKalghatgi** [comment]
That is an issue with React Native Vector Icons
Refer docs https://docs.nativebase.io/Components.html#icon-def-headref

![image](https://user-images.githubusercontent.com/13464885/53091920-50695880-3539-11e9-992a-0090f776e767.png)
