### ISSUE TITLE
Q: What is the supported React-Native version?

### ISSUE THREAD

**Issue by croqaz** [GeekyAnts/NativeBase#26]
Hello, at this time, the most recent version of React-Native is 0.26.1. Native-Base doesn't work with this version.

I followed the tutorials from both RN and NB perfectly.

The hello world app works perfectly without Native-Base, but after i add any component from Native-Base, i get this error:

![screenshot_20160523-114210](https://cloud.githubusercontent.com/assets/1748317/15465122/a52be89e-20db-11e6-81d1-d24a85e36778.png)

**Comment by sankhadeeproy007** [comment]
As of now, NativeBase only supports RN upto versions 0.25

**Comment by sankhadeeproy007** [comment]
RN 0.26 supported with latest update.
