### ISSUE TITLE
Can't use scrollTo method in Content?

### ISSUE THREAD

**Issue by adulhani-systango** [GeekyAnts/NativeBase#260]
<Content ref="contentScrollView" >

I am then using this.refs.contentScrollView.scrollTo({x:0,y:0,animated:true}) to use scrollTo method of ScrollView.
Also, I have tried using scrollToPosition method of Keyboard-Aware-ScrollView which is implemented by Content, but had no success.

How to use any one of these methods?

**Comment by sankhadeeproy007** [comment]
Did you try the solution from #105 ?

**Comment by adulhani-systango** [comment]
@sankhadeeproy007 
#105 worked. Thanks.
