### ISSUE TITLE
Moderate vulnerability in dependency lodash

### ISSUE THREAD

**Issue by cedricpoon** [GeekyAnts/NativeBase#2602]
## I have gone through these following points
- [x]   Check latest documentation: https://docs.nativebase.io/
- [x]   Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x]   Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [x]   Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [ ]   For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- [ ]   For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

## Issue Description
As stated in title, a moderate vulnerability in dependency lodash.js, has been discovered.
![image](https://user-images.githubusercontent.com/13679852/53150795-50766080-35ec-11e9-8950-eaa6768232db.png)

### node, npm, react-native, react and native-base version, expo version if used, xcode version
- node: 11.4.0
- npm: 6.7.0
- react-native: ^0.58.5
- react: 16.6.3
- native-base: ^2.11.0

### Expected behaviour
No vulnerability

### Actual behaviour
Moderate vulnerability in dependency

### Steps to reproduce
```
npm install native-base
```

### Is the bug present in both iOS and Android or in any one of them?
Both

### Any other additional info which would help us debug the issue quicker.

The dependency version of lodash now in native base 2.11.0 is 4.17.10, which >= 4.17.11 will fix.

**Comment by SupriyaKalghatgi** [comment]
Fixed with commit https://github.com/GeekyAnts/NativeBase/commit/e6e794630ca6db29e1d072c02798fc1f4cb7f744
