### ISSUE TITLE
tabsContainerStyle not working for Tabs Component

### ISSUE THREAD

**Issue by lutakyn** [GeekyAnts/NativeBase#2604]
## I have gone through these following points
- []   Check latest documentation: https://docs.nativebase.io/
- []   Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- []   Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- []   Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- []   For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- []   For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

### Expected behaviour
prop tabsContainerStyle for Tabs doesn't work, the default color is still blue, it doesn't work
### Actual behaviour
The color is still blue and doesn't change
### Steps to reproduce
    import React, { Component } from "react";
     import 
      {Image,StyleSheet,Dimensions,ScrollView,TouchableOpacity,ImageBackground,TextInput,Text,}  
    from 'react-native';
     import {Accordion, Container, Header, Title, Content, Button, Card, CardItem,  Body, Left, Right,Tab,  
    Tabs, TabHeading,  View,List,Segment} from "native-base";

     export default class App extends React.Component{
     render(){
      return(
      <Tabs tabsContainerStyle={{backgroundColor:'#FFFFFF'}} tabBarActiveTextColor='red' 
       tabBarUnderlineStyle={{borderBottomWidth:4}}>
                <Tab tabStyle={{backgroundColor:'red'}} heading={ <TabHeading style= 
       {{width:60,height:30,borderRadius:10,backgroundColor:'white',margin:10}}><Text>Usage</Text> 
      </TabHeading>}>
                <View><Text>text</Text></View>
                </Tab>
                <Tab heading={ <TabHeading style= 
       {{width:60,height:30,borderRadius:10,backgroundColor:'white',margin:10}}><Text>Balance</Text> 
       </TabHeading>}>
                   <Tab1/>
                </Tab>
                <Tab heading={ <TabHeading style= 
      {{width:60,height:30,borderRadius:10,backgroundColor:'white',margin:10}}><Text>Details</Text> 
       </TabHeading>}> 
                </Tab>
                <Tab heading={ <TabHeading style= 
       {{width:60,height:30,borderRadius:10,backgroundColor:'white',margin:10}}><Text>Specials</Text> 
       </TabHeading>}>
               
                </Tab>
              </Tabs>
       );
       }
         }

### Is the bug present in both iOS and Android or in any one of them?
Yes

**Comment by lutakyn** [comment]
So how will i change the blue color of the TabBar,I don't know why you closed this issue.Issue not fixed,even if i used style of the Tab component,nothing changes

**Comment by SupriyaKalghatgi** [comment]
Check theme variables https://github.com/GeekyAnts/NativeBase/blob/master/src/theme/variables/commonColor.js#L231

**Comment by lutakyn** [comment]
tabBgColor isn't working for Tabs component

**Comment by SupriyaKalghatgi** [comment]
![image](https://user-images.githubusercontent.com/13464885/53325936-6052b500-390a-11e9-86b9-9d7b3ad7ea16.png)

**Comment by lutakyn** [comment]
// Tab
  tabDefaultBg: platform === "ios" ? "#F8F8F8" : "#000000",---check,this is black
  topTabBarTextColor: platform === "ios" ? "#6b6b6b" : "#b3c7f9",
  topTabBarActiveTextColor: platform === "ios" ? "#007aff" : "#fff",
It didn't change color,I'm using android phone,it's still blue

![pic](https://user-images.githubusercontent.com/32960420/53326572-d7258900-38dd-11e9-814d-f2c97d24d06e.png)

**Comment by SupriyaKalghatgi** [comment]
![image](https://user-images.githubusercontent.com/13464885/53327046-01426f80-390d-11e9-9cd3-270b69e6fee1.png)

![image](https://user-images.githubusercontent.com/13464885/53327023-f25bbd00-390c-11e9-8bf8-01aa46b9a486.png)

**Comment by lutakyn** [comment]
Does the Tab have to be in a header before the color can change or what,that is the only issue I'm having right now.And do I have to import  the commonColor in the file?This is strange

**Comment by SupriyaKalghatgi** [comment]
> Does the Tab have to be in a header

Refer docs https://docs.nativebase.io/Components.html#tabs-def-headref


> do I have to import the commonColor in the file

Refer docs https://docs.nativebase.io/Customize.html#Customize

Refer https://github.com/GeekyAnts/NativeBase-KitchenSink for example of all NativeBase components

**Comment by SupriyaKalghatgi** [comment]
That is why the issue template has this section

![image](https://user-images.githubusercontent.com/13464885/53327698-529f2e80-390e-11e9-91ac-83d64a3304f4.png)

**Comment by lutakyn** [comment]
I have seen the visual editor for the theme which I can use to edit the theme,after editing and downloading the variable.js file,do I have to delete the native-base package I downloaded and use the variable.js file? The documentation is a bit confusing,if you can break the explanation down too me I'll be happy

**Comment by SupriyaKalghatgi** [comment]
Thats very simple!
When you download variable file / App from NativeBase customizer, it mentions how to proceed woth this downloaded file

> Replace the content of the ejected/used theme variable file in your App with the downloaded variable file and run your App

i.e., after downloading, replace the `native-base-theme/variables/commonColor.js` file with the downloaded file.
No compulsions on replacing `commonColor`. You can replace either `commonColor` OR `platform` OR `material` file with downloaded file depending on which of these theme file you have injected in `StyleProvider`.

If you haven't ejected NativeBase theme, then go through http://docs.nativebase.io/Customize.html#theme-and-variables-headref and http://docs.nativebase.io/Customize.html#theaming-nb-headref

**Comment by lutakyn** [comment]
Ok thank you,meaning that for the variable file to work,I have to eject the native-base first

**Comment by SupriyaKalghatgi** [comment]
yes

**Comment by ajitdas123** [comment]
@SupriyaKalghatgi , So we need to replace/ change the color in `commonColor.js` after ejecting NB theme files.
Isn't it bad practice? If there is a new update and we had to eject theme files again won't it override the previous changes ??

And one thing that I want to ask, from where can I disable the ripple effect on the Tabs only? 

Thank you.

**Comment by nirbhaisingh1313** [comment]
@ajitdas123 had you found from where can I disable the ripple effect on the Tabs only?
