### ISSUE TITLE
Updating to latest version of nativebase

### ISSUE THREAD

**Issue by sam-cooper** [GeekyAnts/NativeBase#2606]
Hello,

I am new to react-native development. I was wondering how you can update the nativebase base to the latest version. Current my version of nativebase in my project is 2.7.0 and i want to update to the latest version which is 2.12.0. 

Kindly help me and provide a detailed solution. 

Thanking in advance

**Comment by SupriyaKalghatgi** [comment]
Please follow issue template. This is more of question to be asked on SO
