### ISSUE TITLE
Order of component declaration affects FAB logic?

### ISSUE THREAD

**Issue by isaaclem** [GeekyAnts/NativeBase#2607]
## I have gone through these following points
- [x]   Check latest documentation: https://docs.nativebase.io/
- [x]   Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x]   Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [x]   Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [x]   For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- [x]   For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

```
renderList = () => {
    return (
      <FlatList .../>
    );
  };

render() {
    return (
      <Container>
        {this.renderList()}
        <Fab
          direction="up"
          containerStyle={{}}
          style={{ backgroundColor: '#F37BF6' }}
          position="bottomRight"
          onPress={() => { console.log('hi');}}
        >
          <Icon name="plus" type="AntDesign" />
        </Fab>
      </Container>
    );
  }
```

Oddly enough that if `{this.renderList()}` being placed before `FAB`, `FAB` will work as expected, but if `{this.renderList()}` being placed after `FAB`, then `FAB` will not respond to any click event?

I do aware of other reported issues where they involved the component `Content` however in my case no `Content` involved, and `FAB` is showing in both version, just that it doesnt respond to click event

**Comment by SupriyaKalghatgi** [comment]
Works fine
```
<Container >
        <Header />

        {this.renderList()}
        <Fab
          active={this.state.active}
          direction="up"
          containerStyle={{}}
          style={{ backgroundColor: "#5067FF" }}
          position="bottomRight"
          onPress={() => this.setState({ active: !this.state.active })}
        >
          <IconNB name="md-share" />
          <Button style={{ backgroundColor: "#34A34F" }}>
            <IconNB name="logo-whatsapp" />
          </Button>
          <Button style={{ backgroundColor: "#3B5998" }}>
            <IconNB name="logo-facebook" />
          </Button>
          <Button disabled style={{ backgroundColor: "#DD5144" }}>
            <IconNB name="ios-mail" />
          </Button>
        </Fab>
        
        <View>
          {this.renderList()}
        </View>
      </Container>
```
