### ISSUE TITLE
tabBarTextColor in 

### ISSUE THREAD

**Issue by alanyong91** [GeekyAnts/NativeBase#2609]
I change tabBarTextColor in platform.js but it not working.

"native-base": "^2.12.0",

**Comment by SupriyaKalghatgi** [comment]
Please follow issue template

**Comment by alanyong91** [comment]
I follow doc from https://docs.nativebase.io/docs/ThemeVariables.html#Footer_Tab
I can't change tabBarTextColor in platform.js, that's why i post this issue.

**Comment by SupriyaKalghatgi** [comment]
I am talking about the template that you find while creating new issue at https://github.com/GeekyAnts/NativeBase/issues/new
