### ISSUE TITLE
Input clearButtonMode support

### ISSUE THREAD

**Issue by bradlis7** [GeekyAnts/NativeBase#261]
So, I tried to put `<TextInput>` `clearButtonMode` property on the `<Input>` and on the `<InputGroup>`, but it doesn't seem to work for me. This is a nice feature for filters and search boxes.

**Comment by sankhadeeproy007** [comment]
@himanshu-satija Might be an issue because of our new `computeProps` strategy.

**Comment by SupriyaKalghatgi** [comment]
@bradlis7 
![screen shot 2016-11-16 at 6 21 43 pm](https://cloud.githubusercontent.com/assets/13464885/20348011/9a1680a2-ac29-11e6-838c-9448a17b4982.png)
