### ISSUE TITLE
How can I use numberOfLines for Tabs ?

### ISSUE THREAD

**Issue by NguyenPhatBG** [GeekyAnts/NativeBase#2612]
How can I use numberOfLines for Tabs (4 tab for 2 lines) ?
Can you support to me ! I had try to numberOfLines FlatList but status textStyle and tabStyle is not right,
it's active when i settup them difference

**Comment by SupriyaKalghatgi** [comment]
@NguyenPhatBG You mean multiple lines for Tab heading?

**Comment by NguyenPhatBG** [comment]
![capture](https://user-images.githubusercontent.com/33904172/53485502-f4627f00-3ab8-11e9-9036-8da1692b9254.PNG)
@SupriyaKalghatgi

**Comment by SupriyaKalghatgi** [comment]
I am really not clear with your query
The screenshot you shared has single line of text

**Comment by NguyenPhatBG** [comment]
import React, { Component } from 'react';
import { FlatList } from 'react-native';
import { Container, Header, Content, Tab, Tabs } from 'native-base';
import Tab1 from './tabOne';
import Tab2 from './tabTwo';
import Tab3 from './tabThree';
export default class TabsExample extends Component {
    render() {
        return (
            <Container>
                <Header />
                <FlatList
                    data={[]}
                    renderItem={({ item }) => (
                        <Tabs>
                            <Tab heading="Tab1">
                                <Tab1 />
                            </Tab>
                            <Tab heading="Tab2">
                                <Tab2 />
                            </Tab>
                            <Tab heading="Tab3">
                                <Tab3 />
                            </Tab>
                        </Tabs>
                    )}
                    numColumns={2}
                />
            </Container>
        );
    }
}
for my example code, but Configuration(Tab,TabHeading) is wrong executed

**Comment by SupriyaKalghatgi** [comment]
Ok I get it now
But this is something not as per design guidelines, so NativeBase will not support this

**Comment by NguyenPhatBG** [comment]
export default class ExaminationResult extends React.Component<any, any> {
    constructor(props: any) {
        super(props);
        this.state = {
            currentTab: 0
        };
    }

    onChangeTab = ({ i }: any) => {
        this.setState({ currentTab: i });
    }
    render() {
        return (
            <AppContainer navigation={this.props.navigation} headerTitle="KẾT QUẢ XÉT NGHIỆM">
                <FlatList
                    data={[
                        { "key": 1, "label": "Tab1" },
                        { "key": 2, "label": "Tab2" },
                        { "key": 3, "label": "Tab3" },
                        { "key": 4, "label": "Tab4" }
                    ]}
                    renderItem={({ item }) => (
                        <Tabs
                            locked={true}
                            initialPage={this.state.currentTab}
                            onChangeTab={this.onChangeTab}
                        >
                            <Tab
                                heading={item.label}
                                textStyle={{ color: 'white', fontSize: 13 }}
                                activeTextStyle={{ color: 'tomato', fontSize: 15, fontWeight: 'bold' }}
                                tabStyle={{ backgroundColor: 'cyan' }}
                                activeTabStyle={{ backgroundColor: 'white' }}
                            >
                                <View />
                            </Tab>
                        </Tabs>
                    )}
                    numColumns={2}
                />
            </AppContainer>
        );
    }
}
Can you show me the reason it's not executed and how can i fix that. If you have a another suggest, I'm very pleasure. Thank you!

**Comment by SupriyaKalghatgi** [comment]
You can put this on SO for answers and feedback
