### ISSUE TITLE
Npm can't find a package.json file in your current directory.

### ISSUE THREAD

**Issue by obzc** [GeekyAnts/NativeBase#2614]
`npm ERR! package.json Non-registry package missing package.json: native-base@git+https://github.com/GeekyAnts/NativeBase.git#master.
npm ERR! package.json npm can't find a package.json file in your current directory.`

**Comment by SupriyaKalghatgi** [comment]
Please share your `package.json`

**Comment by obzc** [comment]
My package.json
`  "dependencies": {
    "color": "1.0.3",
    "expo": "^31.0.6",
    "expo-cli": "^2.6.14",
    "lodash": "4.17.10",
    "moment": "^2.23.0",
    "native-base": "git+https://github.com/GeekyAnts/NativeBase.git#master",
    "prop-types": "^15.6.2",
    "react": "16.8.3",
    "react-native": "0.58.0",
    "react-native-elements": "1.1.0",
    "react-native-firebase": "^5.2.0",
    "react-native-music-control": "^0.9.9",
    "react-native-slider": "^0.11.0",
    "react-native-snap-carousel": "^3.7.5",
    "react-native-sound-player": "^0.6.1",
    "react-navigation": "1.5.0",
    "react-redux": "^6.0.1",
    "redux": "^4.0.1",
    "styled-components": "^3.4.5"
  },`

**Comment by SupriyaKalghatgi** [comment]
try this `https://github.com/GeekyAnts/NativeBase.git#master`

**Comment by SupriyaKalghatgi** [comment]
@obzc did this work?
