### ISSUE TITLE
Update of Expo Client for Kitchensink App is needed

### ISSUE THREAD

**Issue by Bilal-S** [GeekyAnts/NativeBase#2615]
We cannot start the NativeBase kitchen sink Expo app because the Expo client v25 is outdated and cannot be opened. 
The current min requirement is Expo 28.

Please update the EXPO Kitchensink app:
https://expo.io/@geekyants/nativebasekitchensink

Thanks

**Comment by SupriyaKalghatgi** [comment]
https://github.com/GeekyAnts/NativeBase-KitchenSink/issues/154
