### ISSUE TITLE
how to align the text in picker to right on Android?

### ISSUE THREAD

**Issue by jiangli1984** [GeekyAnts/NativeBase#2617]
on Android ,I can not align the text in picker to right . can help me out?

<Picker
              mode="dropdown"
              iosIcon={<Icon name="ios-arrow-down-outline" />}
              style={{ width: undefined }}
              placeholder="Select your SIM"
              textStyle={{ color: "#ffd505" }} 
              itemStyle={{flex:1,justifyContent:"flex-end",alignContent:"flex-end"}} 
              itemTextStyle={{flex:1,justifyContent:"flex-end",alignContent:"flex-end"}}  
            >
              <Item label="Wallet" value="key0" />
              <Item label="ATM Card" value="key1" />
              <Item label="Debit Card" value="key2" />
              <Item label="Credit Card" value="key3" />
              <Item label="Net Banking" value="key4" />
            </Picker>

**Comment by SupriyaKalghatgi** [comment]
The example mentioned here https://docs.nativebase.io/Components.html#picker-def-headref is w.r.t. to iOS and Android. Whereas the rest of the picker examples are dedicated to iOS only
