### ISSUE TITLE
Help needed - Want to apply colors from server

### ISSUE THREAD

**Issue by trialsNow** [GeekyAnts/NativeBase#2620]
Hi

I use wix react-native-navigation V2. My requirement is to get the colors from server on start up from a JSON and then set the colors for all components in native-base? Is this doable?If so how? I did a similar set up in react-native-elements and it works well, want to do the same in native-base. How am I supposed to do this?

Here is what I did in react-native-elements "ThemeProvider". On start up user store is called to get the theme and then navigation screens registered with it.Now if I use a button from react-native-elements in a navigation screen ,the primary color is automatically picked up correctly

```
UserStore.js
  getRecentUserTheme() {
      const user = this.getUservalues()[0];
      const { theme } = user;
      const primaryColor = theme ? theme.primaryColor : '#329F9F';
      const secondaryColor = theme ? theme.secondaryColor : '#93329F';
      return {
        colors: {
          primary: primaryColor,
          secondary: secondaryColor
        },
        logo: theme.logo
      };
    }
  }))
```
```
App.js
const registerScreens = async () => {
  Screens.forEach((ScreenComponent, key) =>
    Navigation.registerComponent(
      key,
      () => props => (
        <ThemeProvider theme={theme}>
          <ScreenComponent {...props} />
        </ThemeProvider>
      ),
      () => ScreenComponent
    )
  );
};
```

With native base its confusing because I have to eject the themes but how to apply theme dynamically and wrap in navigation like above I dont know. 

Can anyone please help me at the earliest?

**Comment by SupriyaKalghatgi** [comment]
@trialsNow You share the code snippet when tried this with NativeBase
