### ISSUE TITLE
Drawer panOpenMask not working

### ISSUE THREAD

**Issue by ManiDeva6** [GeekyAnts/NativeBase#2623]
When I swipe left the drawer is not opening I'm using 
`"native-base": "^2.11.0",`
` "react-native": "0.58.4",`

My code is shown below 

`<Drawer
          side="left"
          ref={(ref) => { this.drawer = ref; }}
          acceptPan={true}
          panOpenMask={0.25}
          content={<SideBar navigator={this.navigator} />}
          openDrawerOffset={100} > 
`

**Comment by SupriyaKalghatgi** [comment]
Follow issue template
