### ISSUE TITLE
Excess bottom space in the ActionSheet 

### ISSUE THREAD

**Issue by venkatmithunk** [GeekyAnts/NativeBase#2624]
## I have gone through these following points
- [x]   Check latest documentation: https://docs.nativebase.io/
- [x]   Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x]   Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [x]   Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [x]   For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- [x]   For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

### node, npm, react-native, react and native-base version, expo version if used, xcode version
node: 10.0.0
npm: 5.6.0
react-native: 0.58.5
react: 16.6.3
native-base: 2.12.0
### Expected behaviour
No extra space after last item
### Actual behaviour
Extra space after last item
![screenshot_1551781413](https://user-images.githubusercontent.com/41567130/53798756-e1d7c200-3f5e-11e9-9dc2-2ea5a092d962.png)

### Steps to reproduce
Just adding any normal action sheet is adding extra space after last item.

### Is the bug present in both iOS and Android or in any one of them?
Android

**Comment by SupriyaKalghatgi** [comment]
Checked with NativeBase 2.12.0, no issues
![image](https://user-images.githubusercontent.com/13464885/54013072-f9e95480-419d-11e9-89c8-237df0a8eba8.png)
![image](https://user-images.githubusercontent.com/13464885/54013111-0cfc2480-419e-11e9-9232-5eebe8526e4d.png)

**Comment by venkatmithunk** [comment]
@SupriyaKalghatgi Please repeat the same case not different one. As you can see there is no title.

**Comment by SupriyaKalghatgi** [comment]
@venkatmithunk You dd'nt mention code snippet in issue description (as per issue template)

**Comment by venkatmithunk** [comment]
@SupriyaKalghatgi `  
ActionSheet.show (
      {
        options: [
          {
            text: 'Attach Photo',
            icon: 'ios-folder-open-outline',
          },
          {
            text: 'Take Photo',
            icon: 'ios-camera-outline',
          },
        ],
        title: 'Update Profile Picture',
      },
      buttonIndex => {
        if (buttonIndex === 0) {
          this.pickImage ();
        } else if (buttonIndex === 1) {
          this.openCamera ();
        }
      }
    );`

**Comment by venkatmithunk** [comment]
@SupriyaKalghatgi 
 `ActionSheet.show (`
      `{`
        `options: [`
         ` {`
            `text: 'Attach Photo',`
            `icon: 'ios-folder-open-outline',`
         ` },`
          `{`
            `text: 'Take Photo',`
           ` icon: 'ios-camera-outline',`
         ` },`
       ` ],`
        `title: 'Update Profile Picture',`
     ` },`
     ` buttonIndex => {`
       ` if (buttonIndex === 0) {`
          `this.pickImage ();`
       ` } else if (buttonIndex === 1) {`
          `this.openCamera ();`
      `  }`
     ` }`
   ` );`

**Comment by chrfreitas** [comment]
Same problem here. I'm using native-base@2.12.0

`ActionSheet.show({
            options: [
              {
                text: 'Editar',
                icon: 'create',
                action: () => {},
              },
              {
                text: 'Excluir',
                icon: 'md-trash',
                action: () => deleteAction(transaction),
              },
            ],
          })`

But just with more then 2 itens.

**Comment by venkatmithunk** [comment]
@SupriyaKalghatgi Please reopen the issue. please test for two, three, four , five items in action sheet and you will understand.

**Comment by venkatmithunk** [comment]
@SupriyaKalghatgi Any update on this?

**Comment by maulikgushani** [comment]
Any updates ?

**Comment by shubham1164** [comment]
I am also facing the same issue in native-base 2.12.0

**Comment by TxusBlack** [comment]
Same issue

**Comment by venkatmithunk** [comment]
@SupriyaKalghatgi any updates on this?

**Comment by TxusBlack** [comment]
Unfortunately not, the issue is still present 🙁

**Comment by shubham1164** [comment]
@SupriyaKalghatgi any updates on this?

**Comment by TomMahle** [comment]
I've made a pr that resolves this issue in my app. Testers would be appreciated :D

**Comment by navata** [comment]
![Screenshot_2019-06-26-11-29-03-593_com hanbiro mailapp](https://user-images.githubusercontent.com/16706514/60151139-d4905d00-9805-11e9-9582-f249cfd303c3.png)
I have same issue in version 2.12.1 but I working normal in version 2.6.1.
This issue very long time. I think we should fix and resolve it.

**Comment by TxusBlack** [comment]
> I've made a pr that resolves this issue in my app. Testers would be appreciated :D

Can you share it?

**Comment by TomMahle** [comment]
@TxusBlack I referenced this issue in the PR, so it's linked above, but sure: https://github.com/GeekyAnts/NativeBase/pull/2730

**Comment by navata** [comment]
@TomMahle you change this code from `height:this.state.items.length*80` to `height: "auto"` (or your height) in 3 file as picture. Current, I fixed this issue with this solution.
![Screen Shot 2019-06-28 at 8 09 03 AM](https://user-images.githubusercontent.com/16706514/60310294-63bf8100-997c-11e9-88b9-5849f7986cc9.png)

**Comment by TxusBlack** [comment]
> @TomMahle you change this code from `height:this.state.items.length*80` to `height: "auto"` (or your height) in 3 files as picture. Current, I fixed this issue with this solution.
> ![Screen Shot 2019-06-28 at 8 09 03 AM](https://user-images.githubusercontent.com/16706514/60310294-63bf8100-997c-11e9-88b9-5849f7986cc9.png)

Wow! I'll try! 😄

**Comment by emision** [comment]
I'll make a PR
