### ISSUE TITLE
Problem with Tabs to Details page of tab component

### ISSUE THREAD

**Issue by kameswarans** [GeekyAnts/NativeBase#2625]
I have 4 Tabs. from first Tab click to view Detail page but it is not navigate to Detail page it shows
this.props.navigation.navigate of undefined is not a function

i used this but same problem
const {navigate}= this.props.navigation

plz help to solve this

**Comment by SupriyaKalghatgi** [comment]
Follow issue template

**Comment by kameswarans** [comment]
No solution for this issue ?

**Comment by SupriyaKalghatgi** [comment]
Follow steps mentioned in issue template while you create new issue

**Comment by kameswarans** [comment]
ok
I have scrollable Tabs in my app and I want to first tab Details page is there any solution please healp me
