### ISSUE TITLE
Input placeholder is not vertically aligned when multiline is true

### ISSUE THREAD

**Issue by joeoftheforsythe** [GeekyAnts/NativeBase#2626]
## I have gone through these following points
- [x]   Check latest documentation: https://docs.nativebase.io/
- [x]   Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x]   Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [x]   Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- []   For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- []   For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

## Issue Description

When setting `multiline` to `true` on an `Input`, the placeholder text gets squished to the bottom of the `Input` line (screenshots below)

### Expected behaviour

Placeholder text should have same vertical alignment in `Input` when `multiline` is set to `true`

### Actual behaviour

Placeholder text does not have the same vertical alignment, it's squished against the bottom

### Steps to reproduce

<img width="545" alt="screen shot 2019-03-06 at 9 33 11 am" src="https://user-images.githubusercontent.com/367411/53889040-b652e700-3ff3-11e9-9cd6-464612dc4c34.png">

```
import React from 'react';
import {Button, Card, CardItem, Input, Item, Text} from 'native-base';
import Icon from 'react-native-vector-icons/MaterialIcons';

class AdditionalInfoCard extends React.Component {
  render() {
    const {handleChange, additionalInfo} = this.props;

    return (
      <Card>
        <CardItem header>
          <Text>Do you have any additional info to add?&nbsp;</Text>
          <Button iconRight transparent>
            <Icon name="info" size={20} />
          </Button>
        </CardItem>
        <CardItem>
          <Item>
            <Input
              placeholder="Enter additional info"
              value={additionalInfo}
              onChangeText={value =>
                handleChange({name: 'additionalInfo', value})
              }
            />
          </Item>
        </CardItem>
      </Card>
    );
  }
}

export default AdditionalInfoCard;
```

And with `mutiline={true}`

<img width="545" alt="screen shot 2019-03-06 at 9 33 04 am" src="https://user-images.githubusercontent.com/367411/53889236-134e9d00-3ff4-11e9-9810-f1b8d9088676.png">

```
import React from 'react';
import {Button, Card, CardItem, Input, Item, Text} from 'native-base';
import Icon from 'react-native-vector-icons/MaterialIcons';

class AdditionalInfoCard extends React.Component {
  render() {
    const {handleChange, additionalInfo} = this.props;

    return (
      <Card>
        <CardItem header>
          <Text>Do you have any additional info to add?&nbsp;</Text>
          <Button iconRight transparent>
            <Icon name="info" size={20} />
          </Button>
        </CardItem>
        <CardItem>
          <Item>
            <Input
              placeholder="Enter additional info"
              value={additionalInfo}
              multiline={true} <-- The only change
              onChangeText={value =>
                handleChange({name: 'additionalInfo', value})
              }
            />
          </Item>
        </CardItem>
      </Card>
    );
  }
}

export default AdditionalInfoCard;
```

**Comment by SupriyaKalghatgi** [comment]
@joeoftheforsythe Why not using `Textarea` of NativeBase?

**Comment by SupriyaKalghatgi** [comment]
Closing this issue due to no response
