### ISSUE TITLE
Icons completely absent - no [X]

### ISSUE THREAD

**Issue by camelial** [GeekyAnts/NativeBase#2627]
## I have gone through these following points
- [x]   Check latest documentation: https://docs.nativebase.io/
- [x]   Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x]   Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- []   Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- []   For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- [x]   For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

## Issue Description

I am using native-base for my app, and icons are completely absent (not even showing as [X] like in related issues.) 

### node, npm, react-native, react and native-base version, expo version if used, xcode version
Node: 10.15
npm: 6.8
expo: 2.10
react-native: 0.57.1
native-base: 2.12

### Expected behaviour
A menu icon should appear to the left of "Header" and to the left of "Search" in the search bar.

### Actual behaviour
There is a blank space to the left of "Header" and to the left of "Search" in the search bar (not even a [X] is showing up.)

![screenshot_20190306-161243 1](https://user-images.githubusercontent.com/31336175/53928963-339c4d00-4030-11e9-9f87-ee1299e10b97.jpg)

### Steps to reproduce

```
import React from 'react';
import {
  Platform,
  StyleSheet
} from 'react-native';
import { WebBrowser } from 'expo';
import { Container,
  Header,
  Title, 
  Content, 
  Button, 
  Left, 
  Right, 
  Body, 
  Icon, 
  Text,
  Item,
  Input,
  H3, 
  StyleProvider,
  Form, 
  Picker } from 'native-base';
import { Col, Row, Grid } from 'react-native-easy-grid';
import getTheme from '../native-base-theme/components';
import variables from '../native-base-theme/variables/variables.js';
export default class HomeScreen extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      selected: "key0",
      modalVisible: false
    };
  }
  render() {
    return (
      <StyleProvider style={getTheme(variables)}>
        <Container>
          <Header>
          <Left>
            <Button transparent>
              <Icon name="md-menu" />
            </Button>
          </Left>
          <Body>
            <Title>Header</Title>
          </Body>
          <Right />
        </Header>
          <Grid>
            <Col>
              <Row>
                <Content padder>
                  <Item rounded>
                    <Icon active name="md-search" />
                    <Input placeholder='Search'/>
                  </Item>
                </Content>
              </Row>
              <Row>
                <Col>
                  <Content>
                    <Form>
                      <Picker
                        mode="dropdown"
                        iosHeader="Find Your..."
                        iosIcon={<Icon name="arrow-down" />}
                        style={{ width: undefined }}
                        selectedValue={this.state.selected}
                        onValueChange={this.onValueChange.bind(this)}
                      >
                        <Picker.Item label="Category" value="key0" />
                        <Picker.Item label="Category2" value="key1" />
                        <Picker.Item label="Category3" value="key2" />
                        <Picker.Item label="Category4" value="key3" />
                      </Picker>
                    </Form>
                  </Content>
                </Col>
                <Col>
                  <Content>
                    <Button transparent>
                      <Text>Advanced Search</Text>
                    </Button>
                  </Content>
                </Col>
              </Row>
              <Row>
                <H3>Results</H3>
              </Row>
            </Col>
          </Grid>
        </Container>
      </StyleProvider>
    );
  }
}
```

### Is the bug present in both iOS and Android or in any one of them?
I am currently running this on Android (unable to run on iOS)

### Any other additional info which would help us debug the issue quicker.
I have tried running react-native link. When that did not work, I copied all of the .ttf files from native-base/Fonts to android/assets/fonts. I rebuilt the app many times and the icons have not been shown at all. I also followed all instructions in the react-native-vector-icons for android installation.
However, the icons in the navigation tab bar (generated automatically upon creating a new react-native project with example pages)

**Comment by SupriyaKalghatgi** [comment]
This never happened. You either get icon or get `X`
Since I am not able to reproduce this, I would recommend you to create a repo and push on github

**Comment by camelial** [comment]
Thank you I really appreciate it. I have a repo here: https://github.com/devsciples/finch
If you clone the repo, you can cd into the app/ directory and then run `npm run android` which will start the expo packager on localhost:19002. I run it on an android device (connected with USB) so I switch the mode to "tunnel" on the packager and scan the QR code on the expo app, then it builds and runs the project and should take you directly to the home screen that my screenshot is from.
The code snippet I included is from screens/HomeScreen.js - this is where I tried including the icons.

**Comment by SupriyaKalghatgi** [comment]
Your app doesn't boot up
Why do you have expo as well as Android, iOS folders?

**Comment by camelial** [comment]
It was all included when I created the project with expo.

**Comment by SupriyaKalghatgi** [comment]
Thats not possible at all.
Try to init project with Expo or React Native and share the repo here
Keeping this issue open for today
