### ISSUE TITLE
StyleProvider Error on paddingLeft & paddingRight NaN

### ISSUE THREAD

**Issue by dl-husky73** [GeekyAnts/NativeBase#2628]
I continue to have issues with StyleProvider.  Most screens works fine but a couple of my main ones are having issues.  This appears to be the same issue fixed a couple weeks ago and incorporated into the last release.   I have copied error below.  
Condition is StyleProvider with custom theme.   Any help would be great, I don't know where to turn. 

![image](https://user-images.githubusercontent.com/47721681/54001735-4c812d00-411a-11e9-8047-8539bcce93d8.png)

And the code:
return (
![image](https://user-images.githubusercontent.com/47721681/54001888-ce715600-411a-11e9-99d2-6ebf12cd212c.png)

**Comment by SupriyaKalghatgi** [comment]
> Condition is StyleProvider with custom theme
I cannot test on any custom theme, that is as per user choice
I can help if you face any issue with NativeBase theme `commonColor`, `material`, `platform`.
Do mention running on which simulator / emulator with one of NativeBase theme is causing this issue

**Comment by SupriyaKalghatgi** [comment]
> Condition is StyleProvider with custom theme

I cannot test on any custom theme, that is as per user choice
I can help if you face any issue with NativeBase theme commonColor, material, platform.
Do mention running on which simulator / emulator with one of NativeBase theme is causing this issue

**Comment by dl-husky73** [comment]
OK, I have a  question.  Is it possible the custom theme created with the NativeBase customization tool with no editing, is different than the default themes?  As I recall reading a few weeks ago, the solution to a similar issue was to make a change in actual library.  Should I abandon the customization theme option?  Is that not working?

**Comment by dl-husky73** [comment]
Also replying to your request, I am using Android phone connected via USB.

**Comment by SupriyaKalghatgi** [comment]
No issues with https://nativebase.io/customizer/

**Comment by SupriyaKalghatgi** [comment]
You can atleast share your custom theme

**Comment by SupriyaKalghatgi** [comment]
Closing this issue due to no response

**Comment by dl-husky73** [comment]
Supriya, I ran across this error again.  Same error, went thru customizer and applied to my project.  I fixed this problem by changing CardItem to:
<CardItem style={{paddingLeft: 0, paddingRight: 0}}>
Although I have to think this is a bug that the custom theme causes an error in CardItem.   I use CardItem on all my flatlists.  Want to understand if you can fix or I have to update every carditem component.  

Addressing:  #2628

**Comment by Venkat1P** [comment]
@SupriyaKalghatgi  i am able to reproduce the error and i am unable to see the changes on app after calling the getTheme in styleProvider with the downloaded theme variable.
import custom from './native-base-theme/variables/variables';
<StyleProvider style={getTheme(custom)}>
   <Container>
      <CardItem> code goes here..
 </Container>
</StyleProvider>
Please find the attached file below which is downloaded from Native customizer.

[variables.js.zip](https://github.com/GeekyAnts/NativeBase/files/4360977/variables.js.zip)
