### ISSUE TITLE
Underline color of input doesn't change

### ISSUE THREAD

**Issue by joebernard** [GeekyAnts/NativeBase#2629]
## I have gone through these following points
- [x]   Check latest documentation: https://docs.nativebase.io/
- [x]   Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x]   Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [x]   Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [x]   For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- [x]   For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

## Issue Description
I'm trying to change the success/error colors of the line that appears below an input. By default it is green/red. I have set the `success` and `error` props on `<Form/>` but don't see any change to the color.

### node, npm, react-native, react and native-base version, expo version if used, xcode version
node: 8.10.0
yarn 1.13.0
react native: 0.57.8
native-base: ^2.12.1
xcode: 10.1

### Expected behaviour

Change the `<Form>` `success` and `error` props should change the input color.

### Actual behaviour

Input error and success colors do not respect the settings.

### Is the bug present in both iOS and Android or in any one of them?
I can only test this project on iOS.

### Any other additional info which would help us debug the issue quicker.

```javascript
<Form
        success="#4998F7" // light blue
        error="#a335ee" // red
<img width="563" alt="Screenshot 2019-03-09 14 30 18" src="https://user-images.githubusercontent.com/1540653/54076284-ef9b8900-4277-11e9-860f-0e5fac8fb93c.png">
<img width="563" alt="Screenshot 2019-03-09 14 32 06" src="https://user-images.githubusercontent.com/1540653/54076294-207bbe00-4278-11e9-8f69-eef3c8a33370.png">


      >
        <Item
          success={isSubmitted && isEmailValid === true}
          error={isSubmitted && isEmailValid === false}
        >
          <Label>Email</Label>
          <Input
            ref={this.handleEmailRef}
            onChangeText={this.handleEmailChange}
            onSubmitEditing={this.handleSubmit}
          />
          {isSubmitted && isEmailValid === true && (
            <Icon name="checkmark-circle" style={styles.successIcon} />
          )}
          {isSubmitted && isEmailValid === false && (
            <Icon name="close-circle" style={styles.errorIcon} />
          )}
        </Item>
      </Form>
```
<img width="563" alt="Screenshot 2019-03-09 14 32 06" src="https://user-images.githubusercontent.com/1540653/54076309-4ef99900-4278-11e9-8222-17f6b5208395.png">

In this case I would expect the line to render in blue, not green.

**Comment by SupriyaKalghatgi** [comment]
Works fine with boolean conditions
![image](https://user-images.githubusercontent.com/13464885/54177781-78553780-44b9-11e9-992e-3966c887a8e9.png)

**Comment by joebernard** [comment]
My question is how to change the color of the underline to something other than red/green.

**Comment by SupriyaKalghatgi** [comment]
Your issue description says
> I'm trying to change the success/error colors of the line that appears below an input. By default it is green/red. I have set the success and error props on <Form/> but don't see any change to the color.

Accordingly i have answered with the snippet and output.

> In this case I would expect the line to render in blue, not green.

To do so, you can customize the color of success / error input by ejecting theme

**Comment by joebernard** [comment]
Ah, themes. That seems to be what I'm looking for. Thanks!
