### ISSUE TITLE
Can not change the fontsize of scrollable tab heading

### ISSUE THREAD

**Issue by phanbien9x** [GeekyAnts/NativeBase#2631]
```
<Tabs
    tabBarUnderlineStyle={defaultStyles.tabBarUnderline}
    renderTabBar={() => (
      <ScrollableTab
        backgroundColor="transparent"
        style={defaultStyles.tabBarContainer}
        textStyle={defaultStyles.tabBarLabel}
      />
   )}
  >
    <Tab
      tabStyle={defaultStyles.tabBarItem}
      textStyle={defaultStyles.tabBarLabel}
      activeTabStyle={defaultStyles.tabBarItem}
      activeTextStyle={[
        defaultStyles.tabBarLabel,
        defaultStyles.tabBarActiveLabel
      ]}
      heading="NOT SIGNED"
    >
      <OrderNotSigned />
    </Tab>
</Tabs>
```

My scrollable tab like this. But the fontsize not effected to the heading. It acctually work if I remove the renderTabBar. But I need the scrollable tabbar. So how to do it? Everything else work fine but just the fontsize have no effect.

![image](https://user-images.githubusercontent.com/47513285/54327725-b24f4680-463d-11e9-8e53-3e33732dbd2b.png)

**Comment by phanbien9x** [comment]
![image](https://user-images.githubusercontent.com/47513285/54327719-a82d4800-463d-11e9-9cf3-8b5c94367d8d.png)

**Comment by SupriyaKalghatgi** [comment]
I could change the fontSize of Scrollable Tabs from ejected theme
![image](https://user-images.githubusercontent.com/13464885/54413406-8d310580-471b-11e9-9d8c-2fd2336d4158.png)

**Comment by BaiMaoLi** [comment]
Sorry SupriyaKalghatgi, what is tabFontSize?
I can't find that part in documentation.
