### ISSUE TITLE
Question UI : How do to that using NativeBase ?

### ISSUE THREAD

**Issue by Steffi3rd** [GeekyAnts/NativeBase#2633]
I would like to have something like that (screenshot) : Large Header, Big Title (what is the fontSize, color) and a subtitle and Avatar (what size, position...)

How do you manage that using NativeBase ? Is there a component for that?
Or do we have to create this ourself?

It seems many people do that but I don't if they use library or Nativebase or something else.

<img width="342" alt="Capture d’écran 2019-03-15 à 21 33 25" src="https://user-images.githubusercontent.com/814410/54460518-11aa7500-476a-11e9-8075-5ff2bf9b6714.png">

**Comment by SupriyaKalghatgi** [comment]
Please read and follow issue template
Please read docs https://docs.nativebase.io/Components.html#header-span-headref
