### ISSUE TITLE
Drawer click goes to root screen when used with react-native-navigation

### ISSUE THREAD

**Issue by sumittiwari87** [GeekyAnts/NativeBase#2636]
## I have gone through these following points
- [x]   Check latest documentation: https://docs.nativebase.io/
- [x]   Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x]   Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [x]   Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [x]   For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- [x]   For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

## Issue Description
I have Login, Register page from when I am trying to go to home page where I am implementing native base drawer, but clicking on open the drawer but the page move to root screen.

### node, npm, react-native, react and native-base version, expo version if used, xcode version

    "native-base": "^2.12.1",
    "react": "16.8.3",
    "react-native": "0.59.0",
    "react-native-router-flux": "^4.0.6",

### Expected behaviour

It should stay on the same page where drawer has opened, 

### Actual behaviour
It is going to root screen when click on drawer button
### Steps to reproduce

App.js

import React, { Component } from "react";
import { connect } from "react-redux";
import { Scene, Router } from "react-native-router-flux";
import { Drawer } from 'native-base';
import PropTypes from "prop-types";
import { StatusBar } from "react-native";

import { closeDrawer } from "./actions/drawer";

import Login from "./components/rider/login/";
import Home from './components/rider/home/';
import variables from "./theme/variables/commonColor";

const RouterWithRedux = connect()(Router);

class AppNavigator extends Component<{}> {
    static propTypes = {
        drawerState: PropTypes.string
    };

    componentDidUpdate() {
        if (this.props.drawerState === "opened") {
            this.drawer._root.open();
        }

        if (this.props.drawerState === "closed") {
            this.drawer._root.close();
        }
    }
    openDrawer() {
        this.drawer._root.open();
    }

    closeDrawer() {
         if (this.props.drawerState === "opened") {
            this.props.closeDrawer();
        } 
        //this.drawer._root.close();
    }

    render() {
        // eslint-disable-line class-methods-use-thisy
        return (
            <Drawer ref={(ref) => { this.drawer = ref; }}
                content={<SideBar navigator={this.navigator} />}
                onClose={() => this.closeDrawer()}
                type="overlay"
                tapToClose
                tweenHandler={ratio => {
                    //eslint-disable-line
                    return {
                        drawer: { shadowRadius: ratio < 0.2 ? ratio * 5 * 5 : 5 },
                        main: {
                            opacity: (2 - ratio) / 2
                        }
                    };
                }}

            >
                <StatusBar
                    backgroundColor={variables.brandPrimary}
                    barStyle="light-content"
                />
                <RouterWithRedux>
                        <Scene key="root" hideNavBar>
                            <Scene key="login" component={Login} hideNavBar initial={true} />
                            <Scene key="home" component={Home} />
                        </Scene>
                </RouterWithRedux>
            </Drawer >
        );
    }
}

const bindAction = (dispatch) => {
    return {
        closeDrawer: () => dispatch(closeDrawer())
    };
};

const mapStateToProps = state => ({
    drawerState: state.drawer.drawerState
});

export default connect(
    mapStateToProps,
    bindAction
)(AppNavigator);

login.js

import React, { Component } from "react";
import { connect } from "react-redux";
import { View, Platform } from "react-native";
import { Actions } from "react-native-router-flux";
import { Content, Text, Button, Icon } from "native-base";
import { Grid, Col } from "react-native-easy-grid";

import commonColor from "../../../theme/variables/commonColor";
import styles from "./styles";

class Login extends Component {
  render() {
    return (
      <View style={{ flex: 1 }}>
        <View style={{ padding: 10, marginBottom: 60 }}>
          <Grid>
            <Col style={{ padding: 10 }}>
              <Button
                onPress={() => Actions.signIn()}
                transparent
                block
                style={styles.loginBtn}
              >
                <Text style={{ color: commonColor.brandPrimary, fontWeight: "600" }}>
                  SIGN IN
                </Text>
              </Button>
            </Col>
            <Col style={{ padding: 10 }}>
              <Button
                onPress={() => Actions.register()}
                block
                style={styles.registerBtn}
              >
                <Text style={{ fontWeight: "600", color: "#fff" }}>
                  REGISTER
                </Text>
              </Button>
            </Col>
          </Grid>
        </View>
      </View>
    );
  }
}

export default connect()(Login);

home.js 

import React, { Component } from "react";
import { connect } from "react-redux";
import { Image, View, Dimensions, Platform } from "react-native";
import {
  Header,
  Text,
  Button,
  Icon,
  Title,
  Left,
  Right,
  Body
} from "native-base";
import styles from "./styles";

import { openDrawer } from "../../../actions/drawer";
import commonColor from "../../../theme/variables/commonColor";

class Home extends Component {
  constructor(props) {
    super(props);
  }

  render() {
    return (
      <View style={styles.container}>
        <Text>Page under construuction</Text>
        <View style={styles.headerContainer}>
          <Header
            iosStatusbar="default"
            style={Platform.OS === "ios" ? styles.iosHeader : styles.aHeader}
            androidStatusBarColor={commonColor.statusBarLight}
          >
            <Left>
              <Button transparent onPress={this.props.openDrawer}>
                <Icon
                  name="ios-menu"
                  style={{ color: commonColor.brandPrimary }}
                />
              </Button>
            </Left>
            <Body>
              <Title style={{ color: commonColor.brandPrimary, marginTop: -2 }}>
                Drawer Demo App
              </Title>
            </Body>
            <Right />
          </Header>
        </View>
      </View>
    );
  }
}
function bindActions(dispatch) {
  return {
    openDrawer: () => dispatch(openDrawer())
  };
}
const mapStateToProps = state => ({
  navigation: state.cardNavigation
});

export default connect(
  mapStateToProps,
  bindActions
)(Home);

### Is the bug present in both iOS and Android or in any one of them?
I tried on Android

**Comment by SupriyaKalghatgi** [comment]
Can you please have repo on git for this?

**Comment by sumittiwari87** [comment]
Provide me your email ID I will give you access.

Thanks and Regards
*Sumit Kumar Tiwari*

**Comment by SupriyaKalghatgi** [comment]
supriya@geekyants.com

**Comment by SupriyaKalghatgi** [comment]
Closing issue due to no response
