### ISSUE TITLE
Thumbnail flickering when state is changed

### ISSUE THREAD

**Issue by benhartouz** [GeekyAnts/NativeBase#2637]
## I have gone through these following points
- [x]   Check latest documentation: https://docs.nativebase.io/
- [x]   Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x]   Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [x]   Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [x]   For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- [x]   For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

## Issue Description
I have an issue with Thumbnail component is flickering each time state is a changed.
there is a way to avoid this flickering?

### node, npm, react-native, react and native-base version, expo version if used, xcode version
```
React Native Environment Info:
    System:
      OS: macOS 10.14.2
      CPU: (4) x64 Intel(R) Core(TM) i5-5287U CPU @ 2.90GHz
      Memory: 492.05 MB / 8.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.11.4 - /usr/local/bin/node
      Yarn: 1.9.4 - /usr/local/bin/yarn
      npm: 5.6.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 23, 24, 25, 26, 27, 28
        Build Tools: 23.0.1, 25.0.0, 25.0.1, 25.0.2, 25.0.3, 26.0.0, 26.0.1, 26.0.2, 26.0.3, 27.0.0, 27.0.3, 28.0.1,28.0.3
        System Images: android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.1 AI-173.4819257
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: ^16.6.1 => 16.7.0
      react-native: 0.57 => 0.57.7
    npmGlobalPackages:
      react-native-git-upgrade: 0.2.7
      react-native-rename: 2.2.2
Node : v8.11.4
Npm  : v5.6.0
```
### Expected behaviour
Thumbnail component without flickering

### Actual behaviour
Thumbnail component flickering each time state is changed
### Steps to reproduce
```
 <Thumbnail
            source={{ uri :  picture  }} />
```
### Is the bug present in both iOS and Android or in any one of them?
Yes,

**Comment by SupriyaKalghatgi** [comment]
Need output GIF

**Comment by benhartouz** [comment]
It was my error I added a string to URL to avoid image caching.  
```
 <Thumbnail
            source={{ uri :  picture + new Date().toString().replace(/ /g, "-")  }} />
```
Thanks @SupriyaKalghatgi.
