### ISSUE TITLE
question: headers alongside react-navigation

### ISSUE THREAD

**Issue by jannikbuschke** [GeekyAnts/NativeBase#2639]
I'm using expo, react-navigation for navigation and headers and native-base for the UI controls in the content area. Is there anyone who has experience using native-base navigation controls (like Header and Drawer) while using react-navigation?
Is it straight forward to do or generally not a good idea?

**Comment by SupriyaKalghatgi** [comment]
Please follow issue template
Also that this seems some sort of discussion. NativeBase Forum, SO, NativeBase Slack is an appropriate platform for this

**Comment by gsouf** [comment]
@jannikbuschke did you find a fix?

**Comment by jannikbuschke** [comment]
@gsouf works okish together. I have run into issues (layout moved down and out of screen display about 8px or so), but was somehow able to fix everything. Its a bit annoying, as somehow all of the following parts could theoretically interfere:
 - expo (has androidstatusBar settings in appmanifest)
 - react-navigation (I use it for drawer UI component and different router logic, i.e. drawer, stack without header, switch)
- native-base (to actually render headers)
- react-native SafeAreas (for nodges)

somehow it works all together, but there was a bit trial and error necessary. Also overall the setup feels kind of weak.

**Comment by gsouf** [comment]
@jannikbuschke I got it fixed too, just disabled header in react-navigation (their doc is not very good, it was challenging by itself to find the right option). Just have to use `null` for `defaultNavigationOptions.header`.

```
const AppNavigator = createStackNavigator(
  routes,
  {
    defaultNavigationOptions: {
      header: null
    }
  }
);
```

Then for react-native-web I had to get the wrapper html element to use the following css:

```
height: 100vh;
display: flex;
```

**Comment by sorxrob** [comment]
**UPDATE for React Navigation 5.x**

If you want to use Nativebase's header with react navigation 5, you can do it like this:

```javascript
    import { NavigationContainer } from '@react-navigation/native';
    import { createStackNavigator } from '@react-navigation/stack';
    
    import {
      Header,
      Left,
      Body,
      Title,
      Button,
      Icon,
      View,
      Text
    } from 'native-base';
    
    const Stack = createStackNavigator();
    
    const Home = () => {
        return (
            <View>
                <Text>Hello World</Text>
            </View>
        )
    }
    
    const CustomHeader = ({scene, previous, navigation}) => {
      const {options} = scene.descriptor;
      const title =
        options.headerTitle !== undefined
          ? options.headerTitle
          : options.title !== undefined
          ? options.title
          : scene.route.name;
    
      return (
        <Header>
          <Left>
            {previous ? (
              <Button transparent onPress={navigation.goBack}>
                <Icon name="arrow-back" />
              </Button>
            ) : (
              undefined
            )}
          </Left>
          <Body>
            <Title>{title}</Title>
          </Body>
        </Header>
      );
    };
    
    const App = () => {
        return (
            <NavigationContainer>
                <Stack.Navigator initialRouteName="Home">
                    <Stack.Screen
                    name="Home"
                    component={Home}
                    options={{
                    header: (props) => <CustomHeader {...props} />,
                  }}
                    />
                </Stack.Navigator>
            </NavigationContainer>
        )
    }
```

More of the options here https://reactnavigation.org/docs/en/stack-navigator.html
