### ISSUE TITLE
[Question]: How to change tabs spacing

### ISSUE THREAD

**Issue by Albert0405** [GeekyAnts/NativeBase#2640]
So i have implemented the Tabs component but one thing i dont like is the spacing of each tab buttons, they are too far from each other so i wanted to make them closer a bit unfortunately i dont know how to do that (I've been trying to experiment on styling the Tabs and Tab component for hours but no luck)
![54730584_2102296193138957_3095848182559539200_n](https://user-images.githubusercontent.com/38030623/54757425-2af96880-4c25-11e9-9470-d85316c39298.jpg)

**Comment by Albert0405** [comment]
Hello??

**Comment by SupriyaKalghatgi** [comment]
As per design guidelines, Tab buttons will have width equally divided between total width of number Tabs

Example
![image](https://user-images.githubusercontent.com/13464885/54991591-4678c080-4fe3-11e9-8af5-f912a748cc1e.png)

Here in this example, the Tab heading text length is approximately equal between all tabs. Hence the gap between tabs looks quite uniform.

Here is other example, wherein Tab heading text length differs, so is the gap between tabs
![image](https://user-images.githubusercontent.com/13464885/54991843-cdc63400-4fe3-11e9-80c3-e868a53c27d5.png)


To change spacing between Tabs, you need to style them yourself by passing style to `TabHeading`
![image](https://user-images.githubusercontent.com/13464885/54992048-4af1a900-4fe4-11e9-9e1a-6e66ca587f4c.png)


tab heading text length when equal
![image](https://user-images.githubusercontent.com/13464885/54991960-14b42980-4fe4-11e9-8867-1efbc9df8585.png)

**Comment by SupriyaKalghatgi** [comment]
Closing issue due to no response
