### ISSUE TITLE
constructor side-effects are an anti-pattern with Toast in a render function

### ISSUE THREAD

**Issue by radjivF** [GeekyAnts/NativeBase#2641]
having a toast message in a render works but throw this error message

```
Warning: Cannot update during an existing state transition (such as within `render` or another component's constructor). Render methods should be a pure function of props and state; constructor side-effects are an anti-pattern, but can be moved to `componentWillMount`.
```

I have no way to add this toaster message other than adding a condition in my render function, do you guys can think about a way to not have this error message?

Cheers

**Comment by SupriyaKalghatgi** [comment]
Please follow issue template
