### ISSUE TITLE
App goes behind iPhone X notch in Landscape mode

### ISSUE THREAD

**Issue by brownieboy** [GeekyAnts/NativeBase#2642]
## I have gone through these following points
- [x]   Check latest documentation: https://docs.nativebase.io/
- [x]   Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x]   Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [x]   Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [x]   For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- [x]   For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

### node, npm, react-native, react and native-base version, expo version if used, xcodeversion
Node: v8.11.1
NPM: 5.6.0
  "dependencies": {
    "native-base": "^2.12.1",
    "react": "16.8.3",
    "react-native": "0.59.1"
  },
### Expected behaviour
Safe area should work in Portrait and Landscape modes

### Actual behaviour
Safe area only works in Portrait mode.  In Landscape mode, the app partially disappears behind the notch (see screenshots below).

### Steps to reproduce

Simple test repository here: https://github.com/brownieboy/nbiphonexheadertest

### Is the bug present in both iOS and Android or in any one of them?
iOS and then only on devices with the notch.  Tested on iPhone X Simulator.  (Don't have real hardware to test.)

### Any other additional info which would help us debug the issue quicker.
![portrait](https://user-images.githubusercontent.com/1781909/54874924-a38c3f00-4e48-11e9-97e4-e6ebf1722e9e.jpg)
![landscape](https://user-images.githubusercontent.com/1781909/54874862-c10cd900-4e47-11e9-99f5-41c23fafb06f.jpg)

If I wrap the `<Container>` in a react-native `<SafeAreaView>`, it fixes the Landscape mode issue, but it messes up the `<Header>` height in Portrait mode, see #2440.

**Comment by SupriyaKalghatgi** [comment]
Commit https://github.com/GeekyAnts/NativeBase/commit/167e2d13ebed09905c1c1eed69722bd4d255f80c

**Comment by tspike** [comment]
I encountered this issue in the context of #2947, where you can't use this fix without getting a warning about nested VirtualizedLists. My workaround is described here: https://github.com/GeekyAnts/NativeBase/issues/2947#issuecomment-603953760
