### ISSUE TITLE
Native-base component doenst work inside my component

### ISSUE THREAD

**Issue by PedroGaletti** [GeekyAnts/NativeBase#2643]
import React, { PureComponent } from 'react';
import { TouchableOpacity } from 'react-native';
import { Card as NBCard } from 'native-base';

import styles from './styles';
import { connectStyle, computeProps } from '../../utils';

class Card extends PureComponent {
  render() {
    const { style } = computeProps(this.props);
    const { children, onPress } = this.props;

    if (onPress) {
      return (
        <TouchableOpacity onPress={() => onPress()} activeOpacity={0.7}>
          <NBCard style={style} {...this.props}>
            { children }
          </NBCard>
        </TouchableOpacity>
      );
    }

    return (
      <NBCard style={style} {...this.props}>
        { children }
      </NBCard>
    )
  }
}

export default connectStyle('Portal.Card', styles, Card);

This is my component.

Above is my other component that i want to use the component Card.

import React, { Component } from 'react'
import { Text } from 'native-base';

import styles from './styles';
import { connectStyle, computeProps } from '../../utils';
import { Image, Card } from '../';

class CardImage extends Component {
  render() {
    const { style } = computeProps(this.props);
    const { source, onPress, title, subTitle } = this.props;

    return (
      <Card onPress={onPress}>
        <Image source={source} style={style} />
        <Text titleCard>{ title || '' }</Text>
        <Text subTitleCard>{ subTitle || String(new Date()) }</Text>
      </Card>
    );
  }
}

export default connectStyle('Portal.CardImage', styles, CardImage);

and here is the style of CardImage.

import { em } from '../../utils';

export default {
  flex: 1,
  borderRadius: 12,
  'Portal.Card': {
    height: 156,
    marginHorizontal: 8,
    'NativeBase.Text': {
      position: 'absolute',
      color: '#fff',
      fontFamily: 'Gibson',
      '.titleCard': {
        bottom: 33,
        fontSize: em(2),
        left: 10,
        fontFamily: 'Gibson',
      },
      '.subTitleCard': {
        bottom: 12,
        opacity: 0.75,
        fontSize: em(1.5),
        left: 12,
      },
    },
  },
};

My issue is Why the NativeBase.Text doesnt work if my component Card is connect?
The style inside 'Portal.Card' its working, but the 'NativeBase.Text' inside him doenst work, and i don't understand. 
 
Please help me!

"native-base": "^2.8.1",
"react-native": "0.57.4",

**Comment by SupriyaKalghatgi** [comment]
@PedroGaletti I cannot execute your code snippet, its incomplete
Create git repo for this

**Comment by SupriyaKalghatgi** [comment]
Closing issue due to no response
