### ISSUE TITLE
"Malformed calls from JS: field sizes are different " when useing Header

### ISSUE THREAD

**Issue by kala888** [GeekyAnts/NativeBase#2647]
```
 "react-native": "0.58.6",
"react": "16.6.3",
 "native-base": "2.12.1",
```
issue code
```
import React from 'react'
// import { StatusBar } from 'react-native'
import {Header} from 'native-base'

export default function EleHeader() {
  return (
    <Header/>
  )
}
``` 
![image](https://user-images.githubusercontent.com/1215976/55047744-c5700680-5080-11e9-8585-9e57093c18a7.png)

it works fine when we use 0.57。 After upgrade to 0.58.6, this code will cause error.
```
Invariant Violation: [659,"RCTView",71,{"backgroundColor":4294967295,"flexDirection":"row","paddingLeft":10,"paddingRight":10,"justifyContent":"center","paddingTop":42,"borderBottomWidth":0.5,"borderBottomColor":4294759270,"height":"<<NaN>>","elevation":3,"shadowColor":4278190080,"shadowOffset":{"width":0,"height":2},"shadowOpacity":0.2,"shadowRadius":1.2,"top":0,"left":0,"right":0}] is not usable as a native method argument
```

![image](https://user-images.githubusercontent.com/1215976/55047945-652d9480-5081-11e9-8011-1ef8edf16ecf.png)

![image](https://user-images.githubusercontent.com/1215976/55047924-57780f00-5081-11e9-951e-07c41eb074f7.png)

And then, i give it a height, it works,
```
import React from 'react'
// import { StatusBar } from 'react-native'
import {Header} from 'native-base'

// export default function EleHeader() {
//   return (
//     <Header/>
//   )
// }

export default function EleHeader() {
  return (
    <Header style={{height: 50}}/>
  )
}
```

**Comment by kala888** [comment]
should update the theme by manual.
https://github.com/GeekyAnts/NativeBase/issues/2581
https://github.com/GeekyAnts/NativeBase/commit/4c8a68b1886bfd1eca8d976d72726ffe6062bc94

**Comment by kala888** [comment]
should update the theme by manual.
https://github.com/GeekyAnts/NativeBase/commit/4c8a68b1886bfd1eca8d976d72726ffe6062bc94

https://github.com/GeekyAnts/NativeBase/issues/2534#issuecomment-459931809
https://github.com/GeekyAnts/NativeBase/issues/2581

**Comment by SupriyaKalghatgi** [comment]
This was fixed with 2.12.1

**Comment by cvharris** [comment]
So why is this throwing this error? It was working fine in 0.57+, do we know what changed?

**Comment by MahmoudAziz1996** [comment]
I solved it by adding error.message instead of error object 

```
.catch((error) => {
               console.log(error)
            })
```
to

```
.catch((error) => {
               console.log(error.message)
            })
```
