### ISSUE TITLE
Invariant Violation: is not usable as a native method argument

### ISSUE THREAD

**Issue by appsplanet-swapnil** [GeekyAnts/NativeBase#2649]
## Issue Description

Invariant Violation: [37,"RCTView",1,{"backgroundColor":4281646041,"flexDirection":"row","paddingLeft":10,"paddingRight":10,"justifyContent":"center","paddingTop":42,"borderBottomWidth":0.3333333333333333,"borderBottomColor":4281646041,"height":"<<NaN>>","elevation":3,"shadowColor":4278190080,"shadowOffset":{"width":0,"height":2},"shadowOpacity":0.2,"shadowRadius":1.2,"top":0,"left":0,"right":0}] is not usable as a native method argument

This error is located at:
    in RCTView (at View.js:45)
    in View (at Header.js:84)
    in RCTView (at View.js:45)
    in View (at Header.js:67)
    in Header (at connectStyle.js:384)
    in Styled(Header) (at Login.js:78)
    in RCTView (at View.js:45)
    in View (at Container.js:15)
    in Container (at connectStyle.js:384)
    in Styled(Container) (at Login.js:77)
    in Login (created by SceneView)
    in SceneView (at StackViewLayout.js:795)
    in RCTView (at View.js:45)
    in View (at createAnimatedComponent.js:153)
    in AnimatedComponent (at StackViewCard.js:69)
    in RCTView (at View.js:45)
    in View (at createAnimatedComponent.js:153)
    in AnimatedComponent (at screens.native.js:59)
    in Screen (at StackViewCard.js:57)
    in Card (at createPointerEventsContainer.js:27)
    in Container (at StackViewLayout.js:860)
    in RCTView (at View.js:45)
    in View (at screens.native.js:83)
    in ScreenContainer (at StackViewLayout.js:311)
    in RCTView (at View.js:45)
    in View (at createAnimatedComponent.js:153)
    in AnimatedComponent (at StackViewLayout.js:307)
    in Handler (at StackViewLayout.js:300)
    in StackViewLayout (at withOrientation.js:30)
    in withOrientation (at StackView.js:79)
    in RCTView (at View.js:45)
    in View (at Transitioner.js:215)
    in Transitioner (at StackView.js:22)
    in StackView (created by Navigator)
    in Navigator (at createKeyboardAwareNavigator.js:12)
    in KeyboardAwareNavigator (at createAppContainer.js:388)
    in NavigationContainer (at App.js:12)
    in StyleProvider (at App.js:11)
    in RCTView (at View.js:45)
    in View (at Root.js:13)
    in Root (at connectStyle.js:384)
    in Styled(Root) (at App.js:10)
    in App (at renderApplication.js:34)
    in RCTView (at View.js:45)
    in View (at AppContainer.js:98)
    in RCTView (at View.js:45)
    in View (at AppContainer.js:115)
    in AppContainer (at renderApplication.js:33)

### react-native, react and native-base version, xcode version
"native": "^0.3.3",
"native-base": "^2.12.1",
"react": "16.6.3",
"react-native": "^0.58.4",    
Xcode:10.1

### Actual behaviour
![image](https://user-images.githubusercontent.com/2713424/55239602-07ee3a80-525d-11e9-94f4-af1c3dadfcb5.png)

**Comment by SupriyaKalghatgi** [comment]
#2603

**Comment by appsplanet-swapnil** [comment]
@SupriyaKalghatgi 
https://github.com/GeekyAnts/NativeBase/commit/4c8a68b1886bfd1eca8d976d72726ffe6062bc94
This one is already present in code.

Still having same issue.

**Comment by appsplanet-swapnil** [comment]
> #2603 

      <Container>
        <Header >
          <Body>
            <Title style={{ alignSelf: 'center' }}>{'Login'}</Title>
          </Body>
        </Header>
      <Container>

Comment : 4c8a68b This one is already present in code.

Still having same issue.

**Comment by venkatb4u** [comment]
Any solution update on this regard?

**Comment by hesan-aminiloo** [comment]
I'm facing the same issue
Any updates?

**Comment by ronnamaeffirmo** [comment]
having the same issue. please update, thank you!

**Comment by mikedpid** [comment]
same here, "Invariant violation: [587, "RCTView",31,{"flex":1,"height":"<< NaN >>"} is not usable as a native method argument

The issue seems to come from <Panel component inside a <ListItem component

**Comment by theZulqarnain** [comment]
any update, facing the same issue...

**Comment by seunex** [comment]
Setting the Height of the Header temporarily fix the problem

`<Header noShadow hasTabs style={{elevation: 0,height: Platform.OS === 'ios' ? 90 : 50}}>`

Hope it helps
https://github.com/GeekyAnts/NativeBase/issues/2837#issuecomment-517241556

**Comment by keshakishore** [comment]
Quick fix:
https://github.com/GeekyAnts/NativeBase/issues/2889#issuecomment-530221294

**Comment by theZulqarnain** [comment]
same problem. for me, it's giving error on View and other elements also.is there any full fledge solution

**Comment by IWTBCAdeveloper** [comment]
please help I face the same issue after upgrading to SDK 34

**Comment by xgenem** [comment]
I figured the issue was that I am giving a `null` value to a styling. So look at each of your style and make sure you're not giving a `null` value.

**Comment by Benetzz** [comment]
This is happening to me on one view, setting width="100%". 
The error show:
`[403,"RCTView",51,{"width":"<<NaN>>"] is not usable as a native method argument`

Maybe something has broke with percentage values?

**Comment by xgenem** [comment]
I'm not sure if you can do it that way but perhaps you can do away with something like:
```
<Component style={{width:'100%'}}></Component>
```

**Comment by Benetzz** [comment]
@xgenem i'm using the StyleSheet, my code was this:

  ```
fieldTextStyle: {
    width: "100%",
    backgroundColor: colors.backgroundTextInput,
    height: 1,
    marginBottom: 15,
    marginLeft: 10,
  },
```

Removing the  `width: "100%"` the error disappear.

**Comment by xgenem** [comment]
> @xgenem i'm using the StyleSheet, my code was this:
> 
> ```
> fieldTextStyle: {
>   width: "100%",
>   backgroundColor: colors.backgroundTextInput,
>   height: 1,
>   marginBottom: 15,
>   marginLeft: 10,
> },
> ```
> 
> Removing the `width: "100%"` the error disappear.

I see. This shouldn't be under this repo's issues if that's the case.

**Comment by Benetzz** [comment]
> > @xgenem i'm using the StyleSheet, my code was this:
> > ```
> > fieldTextStyle: {
> >   width: "100%",
> >   backgroundColor: colors.backgroundTextInput,
> >   height: 1,
> >   marginBottom: 15,
> >   marginLeft: 10,
> > },
> > ```
> > 
> > 
> > Removing the `width: "100%"` the error disappear.
> 
> I see. This shouldn't be under this repo's issues if that's the case.

Sure. Just giving other users a suggestion to try if they encounter this issue.

**Comment by vishnu0320** [comment]
height:<<NaN>> 
it need some value initially..

**Comment by fleissigal** [comment]
I had the same problem, got `height:<<NaN>>`. The problem was that I was setting the height to a value that turned out to do division by zero. Fixed it and the problem went away. Hope it will help someone in the future

**Comment by Appoint-App** [comment]
error:
latitude: (fromLoc.latitude + toLoc.latitude) / 2,

Solution:
latitude: (Number(fromLoc.latitude) + Number(toLoc.latitude)) / 2,

If the type comes from a database as a STRING format and you are operating a calculation, JS does not understand a calculation but concatenates it. The solution is to transform it in INTEGER.

I hope I helped.

**Comment by ShiarOs** [comment]
Just remove the height of the elements inside  a FlatList or @react-native-picker/picker if you using it

**Comment by AlinaHassan** [comment]
> error: latitude: (fromLoc.latitude + toLoc.latitude) / 2,
> 
> Solution: latitude: (Number(fromLoc.latitude) + Number(toLoc.latitude)) / 2,
> 
> If the type comes from a database as a STRING format and you are operating a calculation, JS does not understand a calculation but concatenates it. The solution is to transform it in INTEGER.
> 
> I hope I helped.



> error: latitude: (fromLoc.latitude + toLoc.latitude) / 2,
> 
> Solution: latitude: (Number(fromLoc.latitude) + Number(toLoc.latitude)) / 2,
> 
> If the type comes from a database as a STRING format and you are operating a calculation, JS does not understand a calculation but concatenates it. The solution is to transform it in INTEGER.
> 
> I hope I helped.

This helped me
