### ISSUE TITLE
How to dynamically set "Success" / "Error" to inputGroup?

### ISSUE THREAD

**Issue by liuzhen2008** [GeekyAnts/NativeBase#265]
I am looking at this demo.

It says that i could just set "success" prop to inputGroup so that it indicate the data is valid.

But how do I do it dynamically? For example, I would have a function that gets invoked in the `onChangeText` of a `<input/>`

**Comment by himanshu-satija** [comment]
Passing a prop `success` is equivalent to passing `success={true}`

So if you have state variables like inputSuccess and inputError, you can do this:
```jsx
    <InputGroup 
      iconRight 
      success={this.state.inputSuccess ? true : false} 
      error={this.state.inputError ? true : false}>
      <Icon name='ios-checkmark-circle' style={{color:'#00C497'}}/>
      <Input placeholder='Textbox'/>
    </InputGroup>
```

**Comment by liuzhen2008** [comment]
Understood! thanks! Saw your SO answer too.

**Comment by adeelibr** [comment]
You should add this in the documentation as well, it will be really helpful it took me like 2 hours to figure this out.

**Comment by sankhadeeproy007** [comment]
@adeelibr This is related to how props work in React/react-native and not something which is exclusive to native-base. Hence we didn't feel the need to include it to our docs.

**Comment by adeelibr** [comment]
@sankhadeeproy007  believe me their are many newbie's out their like I am, this small piece of code will be very helpful and will make the documentation a bit more better.

**Comment by amanthegreatone** [comment]
stumbled across this after searching for a bit. Agree that it can be added to the documentation to make it simpler for newbies!

**Comment by sanketsahusoft** [comment]
Going to docs and also we are launching NativeBase 2.0 this week❗️
