### ISSUE TITLE
Flex does not work as expected between Android and iOS

### ISSUE THREAD

**Issue by german970814** [GeekyAnts/NativeBase#2650]
## I have gone through these following points
- [x]   Check latest documentation: https://docs.nativebase.io/
- [x]   Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x]   Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [x]   Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [ ]   For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- [ ]   For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

### Expected behaviour

Layout with Android and iOS have the same behaviour

### Actual behaviour

Flex for android fill all space on the x axis (width), while iOS do it in the y axis (height)

### Steps to reproduce

To explain what I'm trying to do, I need to create a tabBar, but these tabs has different width sizes. Reading some issues like #2003, the only thing that I need to do is set `flex: 0` and a fixed width to my tab, to get something like this:

<img width="603" alt="Captura de pantalla 2019-03-29 a la(s) 3 41 06 p  m" src="https://user-images.githubusercontent.com/15973868/55261507-26dad580-5239-11e9-9e2c-be4ec489a9e9.png">

So my code look like this:

    <Tab
            key="__petUpdate__tab_4"
            heading={
              <View style={{ flex: 0, width: 50, backgroundColor: 'white', width: 50, padding:0, margin: 0, alignSelf: 'center' }}>
                <Icon style={[this.state.currentTab === 3 ? Styles.tabTextActive : Styles.tabText, { fontSize: 25 }]} name="photo-camera" type="MaterialIcons" />
              </View>
            }
          >

On android it works well, but on iOS as you see, there is not happening. I've tried for a long time, but I cannot get fix it. The only thing that I saw is that on android the `flex: 1` fill the free content on width, and on iOS is over the height. See this image:

<img width="581" alt="Captura de pantalla 2019-03-29 a la(s) 3 40 12 p  m" src="https://user-images.githubusercontent.com/15973868/55261742-b97b7480-5239-11e9-8820-b3dd7dd790fa.png">

I will share my entire code:

    <Tabs tabContainerStyle={{ backgroundColor: 'blue' }} tabBarUnderlineStyle={{ backgroundColor: 'transparent' }} onChangeTab={({ i }) => { this.setState({ currentTab: i }) }}>
          <Tab
            key="__petUpdate__tab_1"
            tabStyle={Styles.tabGrey}
            textStyle={Styles.tabText}
            activeTabStyle={Styles.tabGrey}
            activeTextStyle={Styles.tabTextActive}
            heading={__('pet_update_tab_detail')}
          >
            <InformationTab pet={pet} />
          </Tab>
          <Tab
            key="__petUpdate__tab_2"
            tabStyle={Styles.tabGrey}
            textStyle={Styles.tabText}
            activeTabStyle={Styles.tabGrey}
            activeTextStyle={Styles.tabTextActive}
            heading={__('pet_update_tab_description')}
          >
            <DescriptionTab pet={pet} />
          </Tab>
          <Tab
            key="__petUpdate__tab_3"
            tabStyle={Styles.tabGrey}
            textStyle={Styles.tabText}
            activeTabStyle={Styles.tabGrey}
            activeTextStyle={Styles.tabTextActive}
            heading={__('pet_update_tab_healthy')}
          >
            <HealthTab pet={pet} />
          </Tab>
          <Tab
            key="__petUpdate__tab_4"
            heading={
              <View style={{ flex: 1, backgroundColor: 'white', flexDirection: 'column', width: 50, padding:0, margin: 0, alignSelf: 'center' }}>
                <Icon style={[this.state.currentTab === 3 ? Styles.tabTextActive : Styles.tabText, { fontSize: 25 }]} name="photo-camera" type="MaterialIcons" />
              </View>
            }
          >
            <GalleryTab pet={pet} />
          </Tab>
        </Tabs>

### Is the bug present in both iOS and Android or in any one of them?

Both of them

### Any other additional info which would help us debug the issue quicker.

If need more information, just tell me

**Comment by hanykumar** [comment]
Hi @german970814 , can you provide minimal code reproduction on snack for the same with more info like what do you want to achieve with the screenshot?
