### ISSUE TITLE
Fab buttons display huge buttons on second dsiplay

### ISSUE THREAD

**Issue by tmoore78** [GeekyAnts/NativeBase#2653]
## I have gone through these following points
- [x]   Check latest documentation: https://docs.nativebase.io/
- [x]   Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x]   Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [x]   Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- []   For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- []   For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

### Expected behaviour
Fabs display as they would on first time enter of the screen

### Actual behaviour
The buttons under fab are displayed in a very large state

### Steps to reproduce
Start on the screen with the fabs on it. Make sure you have another screen in the same navigator. Once the screen with the fabs is loaded, go to the other screen in the navigator. Then go back to the screen with the fabs. 

The first time you go to the screen with the fabs, they work perfectly. When coming back to that screen you find that they are displayed incorrectly.
![Screenshot_1554250486](https://user-images.githubusercontent.com/6580075/55444335-d5995180-556a-11e9-885c-d5de93b90244.png)

CODE for the screen with the fabs
render() {
    return (
        <Container style={styles.container}>
          <Content>
            <Text> Main content goes here</Text>
          </Content>
          <Fab
            active={this.state.activeLeft}
            direction="up"
            containerStyle={{}}
            style={{ backgroundColor: '#5067FF' }}
            position="bottomLeft"
            onPress={() => this.setState({ activeLeft: !this.state.activeLeft, activeRight: false })}>
            <Icon name="md-share" />
            <Button style={{ backgroundColor: 'red' }} onPress={this.shareEvent.bind(this)}>
              <Icon type="MaterialCommunityIcons" style={{ color: this.props.theme.white }} name="message-text" />
            </Button>
            <Button style={{ backgroundColor: '#34A34F' }}>
              <Icon name="logo-whatsapp" />
            </Button>
            <Button style={{ backgroundColor: '#3B5998' }}>
              <Icon name="logo-facebook" />
            </Button>
            <Button style={{ backgroundColor: '#00acee' }}>
              <Icon name="twitter" type="MaterialCommunityIcons" />
            </Button>
            <Button disabled style={{ backgroundColor: '#DD5144' }}>
              <Icon name="mail" />
            </Button>
          </Fab>
          <Fab
            active={this.state.activeRight}
            direction="up"
            containerStyle={{}}
            style={{ backgroundColor: '#5067FF' }}
            position="bottomRight"
            onPress={() => this.setState({ activeRight: !this.state.activeRight, activeLeft: false })}>
            <Icon name="add" />
            <Button onPress={this.addToCalendar.bind(this)}>
              <Icon type="MaterialCommunityIcons" style={{ color: this.props.theme.white }} name="calendar" />
            </Button>
            <Button style={{ backgroundColor: 'black' }} onPress={this.goToTransportation.bind(this, 'EventAddUber')}>
              <Icon type="MaterialCommunityIcons" style={{ fontSize: 30, color: 'white' }} name="uber" />
            </Button>
            <Button style={{ backgroundColor: "#ff00bf" }} onPress={this.goToTransportation.bind(this, 'EventAddLyft')}>
              <SpontaneousIcon style={{ fontSize: 20, color: 'white' }} name="lyft" />
            </Button>
            <Button style={{ backgroundColor: this.props.theme.primary_color }} onPress={this.goToConcierge.bind(this)}>
              <SpontaneousIcon style={{ fontSize: 20, color: this.props.theme.white }} name="concierge-bell" />
            </Button>
          </Fab>
        </Container>
    )
  }

}
const styles = StyleSheet.create({
  container: {
    flex: 1,
    paddingTop: Platform.OS === 'ios' ? 25 : 0
  }
});

### Is the bug present in both iOS and Android or in any one of them?
Just Android

### Any other additional info which would help us debug the issue quicker.
Create two screens in one navigator. Start on the screen with the fab in it. Go back to the other screen. Have a button in that screen that takes you back to the fab screen.

**Comment by SupriyaKalghatgi** [comment]
I tried this on iOS and Android both. Worked fine
Sharing GIF for iOS (cannot take GIF of Android device), works similarly on Android

![fab](https://user-images.githubusercontent.com/13464885/56028672-43e1cf00-5d36-11e9-95db-000a6f40c913.gif)
