### ISSUE TITLE
Input field cursor remains in the screen

### ISSUE THREAD

**Issue by akhilsanker** [GeekyAnts/NativeBase#2658]
## Issue Description
I use native base forms for my registration screen. But in samsung android tab the input field cursor remains in the screen, but it works fine in all other devices.

### node, npm, react-native, react and native-base version, expo version if used, xcode version
    "node":"8.9.1",
    "react": "16.6.3",
    "react-native": "0.57.8",
    "native-base": "^2.8.2",

### Expected behaviour
To hide the input edit cursor.
### Actual behaviour

![Screenshot_2019-04-06-17-56-59](https://user-images.githubusercontent.com/32122016/55669868-49ed3100-589a-11e9-8c25-f3f0e307eebe.png)

### Is the bug present in both iOS and Android or in any one of them?
Only in certain Android devices.

**Comment by SupriyaKalghatgi** [comment]
As per the screenshot shared above, you are saying that 2 cursors remain simultaneously on screen?

**Comment by akhilsanker** [comment]
Hi @SupriyaKalghatgi ,

Yes. The cursor remains in the app, in every screen, once it appears.

Thanks

**Comment by SupriyaKalghatgi** [comment]
I have verified this with multiple types of NativeBase input along with React Native TextInput
Behaves the same

**Comment by akhilsanker** [comment]
Hi @SupriyaKalghatgi ,

Thanks for your response. It's working in almost all devices. But in my Samsung tablet, it's working as per the screenshot, I have seen it in only one device.
Do you have any other suggestion about this?

Thank you for your time.

**Comment by SupriyaKalghatgi** [comment]
@akhilsanker My previous comment was wrt Samsung Android tab (mentioned by you in issue description)

**Comment by akhilsanker** [comment]
Hi @SupriyaKalghatgi ,

Thanks for the quick response. Please find my device specs below:
    Samsung Galaxy J Max, Android 5.1.1

Thanks

**Comment by caiopardal** [comment]
@SupriyaKalghatgi Hello! I'm having this issue in Samsung devices with Android 5.1.1 

Do you have any solutions for this?

**Comment by caiopardal** [comment]
@akhilsanker Can you help me with this issue? I'm having trouble with it :(

**Comment by akhilsanker** [comment]
Hi @caiopardal , @SupriyaKalghatgi 

Sorry to say, I have no workaround to solve this. It still there in my application. Still searching for a solution.

Thanks
