### ISSUE TITLE
behavior is not very correct on web

### ISSUE THREAD

**Issue by geminiyellow** [GeekyAnts/NativeBase#2665]
## I have gone through these following points

**ALL DONE**

## Issue Description

Open the https://github.com/GeekyAnts/NativeBase#6-nativebase-for-web from the README.md , use Chrome. and then:

**PHONE MODE**
![nb](https://user-images.githubusercontent.com/929878/55932310-2cd2ac80-5c64-11e9-9204-a082c0996a63.gif)

**WEB MODE**
![nb2](https://user-images.githubusercontent.com/929878/55932322-33f9ba80-5c64-11e9-99f9-c93b61d189b4.gif)

### Expected behaviour

> Label animates upward when input is selected and animates downward when input is erased. -- from: https://docs.nativebase.io/Components.html#inline-label-headref

### Actual behaviour

i cannot input in phone mode, and in web mode the placeholder label can block input

**Comment by SupriyaKalghatgi** [comment]
From demo
![image](https://user-images.githubusercontent.com/13464885/56030604-e00dd500-5d3a-11e9-80aa-3448bae5d04a.png)

I dont get why phone mode here

**Comment by geminiyellow** [comment]
hey @SupriyaKalghatgi , dont you see the WEB MODE?
dont you have a phone? dont you access web site from phone?
why you think i cheat you.ok, well, nothing. just close it.
