### ISSUE TITLE
Is index.d.ts still being maintained?

### ISSUE THREAD

**Issue by ecbrodie** [GeekyAnts/NativeBase#2668]
There are multiple old old PRs that update `index.d.ts`. They are awaiting attention from a NativeBase maintainer. I would like to inquire about these PRs and see what needs to be done to get them merged.

These PRs include #2664, #2663, #2622, and #1908.

I understand that core NativeBase code are just JavaScript files and this may naturally lead to the TypeScript type definitions file to receive less attention. I'm sure I don't need to explain how essential this file is for TypeScript developers using NativeBase. Without these community contributions being merged, the file becomes stale. TypeScript NativeBase projects would then need to maintain local type files to patch NativeBase's types and avoid false errors/warnings. This is not a sustainable practice.

Can someone from GeekyAnts please take a look at these PRs? Most of them are small patches, but go a long way in ensuring TypeScript quality-of-life for NativeBase. Alternatively, if maintaining `index.d.ts` is not a concern for NativeBase maintainers, then I would like to suggest that the file be moved to [DefinitelyTypes](https://github.com/DefinitelyTyped/DefinitelyTyped). This lifts the burden of maintaining the types file off of GeekyAnts and onto the shoulders of the active TypeScript community.

Thank you. CC @SupriyaKalghatgi

**Comment by SupriyaKalghatgi** [comment]
Merged

**Comment by ecbrodie** [comment]
Thanks
