### ISSUE TITLE
Image component is broken

### ISSUE THREAD

**Issue by JChristensen97** [GeekyAnts/NativeBase#2669]
Hey there,
I'm running into an issue when using Native Base Image component. I'm receiving the error: `Invariant Violation: Element type is invalid: expected a string`. My code is the following: `<Image style={{ height: 300, flex: 1 }} source={require('../assets/placeholder-swipe-img.jpg')} />`. When I replace NB Image with RN Image component, I have no issue.

**Comment by SupriyaKalghatgi** [comment]
Please follow issue template
NativeBase does not have `Image` component
