### ISSUE TITLE
<header> with Navigator's NavigationBar

### ISSUE THREAD

**Issue by tonypee** [GeekyAnts/NativeBase#267]
How can i use The NativeBase <header> component with facebook's NavigationBar ? 

I could extend Navigator.NavigatorBar and override the render to use it, should this be the approach?

**Comment by dpehrson** [comment]
I would be curious about any documentation related to how to integrate `Navigator` into native base generally, I have yet to figure out how to deal with push/pop navigation in native base at all.

**Comment by himanshu-satija** [comment]
@tonypee That should work but we have not tested it. If you have tried it, let us know.

@dpehrson NativeBase provides only UI components. It is left up to the user how they implement navigation. What we normally do is add onPress prop to Buttons inside the Header component which will call push/pop on navigator object.
