### ISSUE TITLE
Picker mode has no effect on android

### ISSUE THREAD

**Issue by AbanoubNassem** [GeekyAnts/NativeBase#2674]
## I have gone through these following points
- [x]   Check latest documentation: https://docs.nativebase.io/
- [x]   Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x]   Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [x]   Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink

## Issue Description
as the title says changing the `Picker` mode to `dialog` on Android , has no effect!

### Expected behaviour
open modal like on IOS

### Actual behaviour
it's dropdown regardless of the mode being selected!

**Comment by sankhadeeproy007** [comment]
The `Picker` component extends the react-native picker, hence no dropdown mode is supported. 
However it can be achieved as we have separate files for android and ios picker. If we remove the android file and rename the ios file to `Picker.js`, that should serve your purpose.
But that is beyond the scope if this project and I'd suggest you do it on your fork.
