### ISSUE TITLE
I still meet this warning "ListView is deprecated"

### ISSUE THREAD

**Issue by railsjack** [GeekyAnts/NativeBase#2675]
Hello, every contributor.
First off, I want to thanks to you all for contributing such a great UI framework using React Native.

Could you please fix this issue? 
Originally I believe that it was already fixed, but I found the following code in the sources of this project.
There are more codes using ListView of ReactNative.
If I misunderstood about this issue, then please kindly let me know.

https://github.com/GeekyAnts/NativeBase/blob/2bd57b74697694a15f8db2790e6da1d8aea4a428/index.d.ts#L387

**Comment by hanykumar** [comment]
Hi @railsjack , How do you produce this warning? Kindly let us know if the warning still persists?

**Comment by railsjack** [comment]
I am sorry, but I don't use native-base for now (used RN's FlastList instead).
I will let you know as soon as I start a new one with native-base.

**Comment by hanykumar** [comment]
we will appreciate your effort. Closing for now. Let us know once you face this warning.
