### ISSUE TITLE
Error when Header does not contain any button

### ISSUE THREAD

**Issue by MatthieuLemoine** [GeekyAnts/NativeBase#268]
In the [online documentation](http://nativebase.io/docs/v0.5.9/components#anatomy), the first example shows that we can use a Header with only a Title and no button : 

```javascript
<Container> 
  <Header>
    <Title>Header</Title>
  </Header>
  <Content>
    // Your main content goes here
  </Content>
</Container>
```

In `Components/Widgets/Header.js`, no check is done on the buttons array before `React.cloneElement`on `buttons[0]`. Therefore, React throws the following error : `Cannot read property 'props' of undefined`.

**Comment by himanshu-satija** [comment]
Fixed with [this commit](https://github.com/GeekyAnts/NativeBase/commit/0bf8d6ffe62aabe5938e12fad2b4c878099c3aac). Will be released with the next version.

**Comment by prithsharma** [comment]
When is this next version being released, ETA?
I see the last release was more than a month back.

**Comment by himanshu-satija** [comment]
Fixed
