### ISSUE TITLE
undefined is not an object (evaluating `this.actionsheetInstatnce._root`) 

### ISSUE THREAD

**Issue by pengyongqi** [GeekyAnts/NativeBase#2681]
Hello,I try the nativebase follow the introduction,when I try to use the actionsheet,it's throw this error,i just copy the code from example,why it dosen't work,please help me.

deps is here:

 "native-base": "^2.12.1",
 "react": "16.8.3",
 "react-native": "0.59.5"

code is here,it is same as nativebase.io actionsheet example code.

import React, { Component } from "react";
import { Container, Header, Button, Content, ActionSheet, Text } from "native-base";
const BUTTONS = ["Option 0", "Option 1", "Option 2", "Delete", "Cancel"];
const DESTRUCTIVE_INDEX = 3;
const CANCEL_INDEX = 4;
export default class ActionSheetExample extends Component {
  constructor(props) {
    super(props);
    this.state = {};
  }
  render() {
    return (
        <Container>
          <Header />
          <Content padder>
            <Button
                onPress={() =>
                    ActionSheet.show(
                        {
                          options: BUTTONS,
                          cancelButtonIndex: CANCEL_INDEX,
                          destructiveButtonIndex: DESTRUCTIVE_INDEX,
                          title: "Testing ActionSheet"
                        },
                        buttonIndex => {
                          this.setState({ clicked: BUTTONS[buttonIndex] });
                        }
                    )}
            >
              <Text>Actionsheet</Text>
            </Button>
          </Content>
        </Container>
    );
  }
}

**Comment by SupriyaKalghatgi** [comment]
Please follow issue template
That would have given you a solution for this problem

**Comment by SupriyaKalghatgi** [comment]
This is well documented. Example provided in docs and NatoveBase KitchenSink. Several repeated issues on NativeBase github too

**Comment by joaodematejr** [comment]
Almost two years later and the problem continues, even copying the documentation example has an error

![Simulator Screen Shot - iPhone 8 - 2021-01-20 at 16 43 16](https://user-images.githubusercontent.com/17418041/105226317-991f5700-5b3e-11eb-9c8f-76204a8e605f.png)
