### ISSUE TITLE
SwipeRow directionalDistanceChangeThreshold on move takes it in consideration twice.

### ISSUE THREAD

**Issue by aldoreyes** [GeekyAnts/NativeBase#2685]
## Issue Description
If you set the prop `directionalDistanceChangeThreshold` of `SwipeRow` to something noticeable like 100, the swipe row pan animation won't start until you swipe the row 200 px horizontally, this is because the `dx` variable in `handlePanResponderMove` is relative to when `handleOnMoveShouldSetPanResponder` returns true.

I.e. dx will be zero when you have already swiped 100 pixels, since `handleOnMoveShouldSetPanResponder` returned true at that distance. Then the `handlePanResponderMove` won't get past from this condition

```
if (
			absDx > this.props.directionalDistanceChangeThreshold ||
			absDy > this.props.directionalDistanceChangeThreshold
		) {
```
until you move another 100.

### node, npm, react-native, react and native-base version, expo version if used, xcode version

native-base 2.12.1

### Expected behaviour

SwipeRow animation should start when you have moved the specified distance through the prop `directionalDistanceChangeThreshold`

![expected](https://user-images.githubusercontent.com/595153/56711008-76a0a580-66ee-11e9-8ac8-a9291ddd20bd.gif)

I created this gif by removing the if condition mentioned above.

### Actual behaviour

SwipeRow animation starts when you have swiped at least twice the amount you set  in `directionalDistanceChangeThreshold`

![current](https://user-images.githubusercontent.com/595153/56711014-7d2f1d00-66ee-11e9-9fff-64396cfc5af1.gif)

You can see how it get's stuck for a moment here.

### Steps to reproduce

```
<List
            dataArray={items}
            directionalDistanceChangeThreshold={100}
            
            leftOpenValue={150}
            rightOpenValue={-150}
            stopLeftSwipe={150}
            stopRightSwipe={-150}
            renderLeftHiddenRow={this._renderLeftHiddenRow.bind(this)}
            renderRightHiddenRow={this._renderRightHiddenRow.bind(this)}
            dataSource={this.ds.cloneWithRows(items)}
            renderRow={this._renderItem.bind(this)} />
```

### Is the bug present in both iOS and Android or in any one of them?
Both

**Comment by hanykumar** [comment]
Hi @aldoreyes, can you provide minimal code reproduction in snack for the same?

**Comment by hanykumar** [comment]
Hi @aldoreyes ,  closing this now due to inactivity. Let us know if the issue still persists.
