### ISSUE TITLE
Content changing height when keyboard opens on Android

### ISSUE THREAD

**Issue by italomlp** [GeekyAnts/NativeBase#2686]
## I have gone through these following points
- [x]   Check latest documentation: https://docs.nativebase.io/
- [x]   Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x]   Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [x]   Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [x]   For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- [x]   For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

### Expected behaviour
Expected that Content with keyboard need to have equals behaviour in Android and iOS.

### Actual behaviour
Currently, on Android when the keyboard is open, the Content is changing the size of the view (maybe ScrollView). So, its children are been truncated instead of keep blank space as in initial render.

### Steps to reproduce
My code:
```
<Container>
  <SafeAreaView style={{ flex: 1 }}>
    <Content contentContainerStyle={styles.container} scrollEnabled>
      <Image style={styles.logo} source={logo} resizeMode="contain" />
      <Form style={styles.formContainer}>
        <Input
          label="Email"
          name="email"
          value={this.state.email}
          onChangeText={(email: string) => this.setState({ email })}
          autoCapitalize="none"
          keyboardType="email-address"
          returnKeyType="next"
          onSubmitEditing={() => {
            if (this.passwordInput && this.passwordInput._root) {
              this.passwordInput._root.focus();
            }
          }}
        />
        <Input
          label="Senha"
          name="password"
          autoCapitalize="none"
          autoCorrect={false}
          keyboardType={
            this.state.passwordIsHide
              ? 'default'
              : Platform.OS === 'ios'
                ? 'default'
                : 'visible-password'
          }
          getRef={(ref) => {
            this.passwordInput = ref;
          }}
          value={this.state.password}
          onChangeText={(password: string) => this.setState({ password })}
          onSubmitEditing={() => this.handleSignin(PROVIDERS.EMAIL)}
          secureTextEntry={this.state.passwordIsHide}
        >
          <Icon
            name={this.state.passwordIsHide ? 'eye' : 'eye-off'}
            onPress={this.toggleHidePassword}
          />
        </Input>
      </Form>
      <View style={styles.formActions}>
        <Button
          primary
          onPress={() => this.handleSignin(PROVIDERS.EMAIL)}
          style={styles.loginButton}
        >
          <Text>Entrar</Text>
        </Button>
      </View>
      <View style={styles.socialContainer}>
        <Text style={styles.socialText}>Ou entre usando:</Text>
        <View style={styles.socialButtons}>
          <Button primary iconLeft onPress={() => this.handleSignin(PROVIDERS.FACEBOOK)}>
            <Icon name="logo-facebook" />
            <Text>Facebook</Text>
          </Button>
          <Button primary iconLeft onPress={() => this.handleSignin(PROVIDERS.GOOGLE)}>
            <Icon name="logo-google" />
            <Text>Google</Text>
          </Button>
        </View>
      </View>
      <View style={styles.footerContainer}>
        <View style={styles.footerLine}>
          <Text>Não é cadastrado? </Text>
          <TouchableOpacity onPress={() => this.props.navigation.navigate('Signup')}>
            <Text style={styles.bold}>Criar conta.</Text>
          </TouchableOpacity>
        </View>
        <View>
          <TouchableOpacity onPress={() => this.props.navigation.navigate('LostPassword')}>
            <Text style={styles.bold}>Esqueci a senha!</Text>
          </TouchableOpacity>
        </View>
      </View>
    </Content>
  </SafeAreaView>
</Container>
```

```
const styles = StyleSheet.create({
  // ...
  container: {
    flexGrow: 1,
    flexDirection: 'column',
    justifyContent: 'space-around',
  }
});
```
My Input component is a wrapper for Native Base Item, that can has error label and name (for validation). All other props are same of Item props.

I tried with `flex: 1` instead of `flexGrow: 1` too, but this way makes more buggy (with buttons container staying over inputs)

Follow gifs for android and ios:

Android                               |  iOS
:-------------------------:|:-------------------------:
![Android](https://i.imgur.com/8RxKLs1.gif "Bug on android")  |  ![iOS](https://i.imgur.com/BOEIJZm.gif "iOS is ok")

### Is the bug present in both iOS and Android or in any one of them?
The bug is present only in Android.

### Any other additional info which would help us debug the issue quicker.
I tried to set height manually, but it's not what I've looking for, and if use that way, need to care about different heights (and camera cuts for iOS, etc).

I can't say for sure if this is really a bug and if this is a bug with Native Base Content, with RN ScrollView or with RNKeyboardAwareScroolView. Hope that someone can help.

PS: Sorry about my English. I'm from Brazil, and it's still work in progress.

**Comment by italomlp** [comment]
Someone could reproduce this issue too?

**Comment by hanykumar** [comment]
Hi @italomlp , can you provide snack for minimal reproduction for the same. It will be easy for us to handle the issue.

**Comment by hanykumar** [comment]
Hi @italomlp ,  closing this now due to inactivity. Let us know if the issue still persists.
