### ISSUE TITLE
Input placeholdertextcolor while theming

### ISSUE THREAD

**Issue by lefrankleal** [GeekyAnts/NativeBase#2687]
Hello there,

Someone know how to change the `placeholderTextColor` while theming? actually cant  find how to and also remove the `underlineTextColor`

**Comment by SupriyaKalghatgi** [comment]
Please follow issue template

**Comment by lefrankleal** [comment]
@SupriyaKalghatgi any link please?

**Comment by SupriyaKalghatgi** [comment]
https://github.com/GeekyAnts/NativeBase/issues/new
