### ISSUE TITLE
How can I use textInverseColor given in the platform.js

### ISSUE THREAD

**Issue by sirajalam049** [GeekyAnts/NativeBase#2689]
## I have gone through these following points
- []   Check latest documentation: https://docs.nativebase.io/
- []   Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- []   Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- []   Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- []   For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- []   For queries related to the theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

### 
node v10.15.1
npm v6.8.0
react-native 0.59.6
react 16.8.3
native-base 2.12.1

After setting up my theme, at some place I need to use the inverse color of the text (white). I can't see any prop like color or anything, Neither any component for this. 

Right now I have given the inline style, but I want to know how can I use that platform.js text variable

**Comment by hanykumar** [comment]
Hi @sirajalam049 , you can follow [Native Base Customize](https://docs.nativebase.io/Customize.html#Customize) for more details. 

- run `node node_modules/native-base/ejectTheme.js`
- `import inverseTextColor from "./native-base-theme/variables/platform"`
- `<Text style={{ color: inverseTextColor }}>Some text</Text>`
