### ISSUE TITLE
Pull to refresh in List component.

### ISSUE THREAD

**Issue by sagark1510** [GeekyAnts/NativeBase#269]
I have used List component and it's very handy to use. But I want to use list component for pull to refresh and infinite scrolling. 
Can you please give me some solution?

**Comment by h124551753** [comment]
i also want to pull-to-refresh list

**Comment by himanshu-satija** [comment]
Will be supporting this in the future versions

**Comment by gala132** [comment]
Which versions approximately? (So I can take a look at it then, of course I do not need a date, just an estimation, will it be weeks/months?) Thanks.

**Comment by sanketsahusoft** [comment]
@gala132 NativeBase List is just a wrapper around React Native's ListView, so the way you implement it for React Native, it should be no different.

@himanshu-satija @sankhadeeproy007 Right?

**Comment by sankhadeeproy007** [comment]
Added `RefreshControl` to `List`. Already works for `Content`
![refreshcontrol](https://cloud.githubusercontent.com/assets/10998047/21588102/58245142-d109-11e6-8d15-f27314874211.gif)

**Comment by priyesh9875** [comment]
Not working on android 6
Rows are displayed, but no refresh control
Here's my code
```

<Container>
            <Content>
                <List

                    refreshControl={
                        <RefreshControl refreshing={this.state.isRefreshing}
                            onRefresh={this.refreshList.bind(this)}
                            />
                    }

                    dataArray={this.props.contacts}
                    renderRow={(row) => <Row row={row} />}
                    >

                </List>
            </Content>
        </Container >
```

**Comment by sankhadeeproy007** [comment]
Which version of NativeBase are you using?

**Comment by priyesh9875** [comment]
"native-base": "^0.5.20",

**Comment by robtaireeo** [comment]
@priyesh9875 The List cannot go in a Content if you want pull to refresh, change Content to View (import from nativebase)

**Comment by seymores** [comment]
I found that if I use View instead of Content, the last ListItem will be clipped off but displayed if use Content instead of View.
I'm using 0.42

**Comment by srhise** [comment]
@seymores I continue to have issues with using <List> instead of <Content>. I have seen in several issues to use <View> instead of <Content> when using lists, but it breaks my layouts every time I attempt it. When I use <Content>, the page lays out perfectly. Also have heard using <List> in <Content> is a performance problem, but I haven't seen another way to get it to work and still have the header, content, footer layout style rendering work properly.

**Comment by axsann** [comment]
@seymores Add style {flex: 1} to <View>, problem solved.
`
<View style={{flex: 1}}>
<List>
...
<List>
</View>
`

**Comment by axsann** [comment]
I found a new solution!
Add refreshControl prop to "Content".
```
<Content refreshControl={ <RefreshControl ... /> }>
  <List></List>
</Content>
```

**Comment by reflog** [comment]
@axsann - thanks, works perfectly!

**Comment by ceefour** [comment]
Thanks @axsann, `<View style={{flex: 1}}>` works... But I'm still confused why this workaround is even needed in the first place. NativeBase recommends using `Content` for anatomy but then it breaks....

**Comment by cdesch** [comment]
I think this needs to be added to the docs on how to "Pull to Refresh"

**Comment by kigawas** [comment]
Thanks for sharing @axsann

**Comment by egeniegithub** [comment]
can someone share code for refreshing?

**Comment by ikeliec** [comment]
> 
> 
> can someone share code for refreshing?

Below is what I did

`<ScrollView        
        refreshControl={
          <RefreshControl
            refreshing={this.state.isRefreshing}
            onRefresh={() => {
              this.setState({isRefreshing: true}) //You need to set true so the refreshing icon can be displayed
              this.fetchFeeds()
              this.setState({isRefreshing: false}) //Hide the refreshing icon
            }}
          />
        }
      >
        <Content>
          {
            <List
              dataArray={this.state.newsList}
              keyExtractor={(item, index) => 'key'+index}
              renderRow={ item => this.renderNews(item)}
              
            />
          }                    
        </Content>
      </ScrollView>`

You can see that my List is in a Content which is inside a ScrollView. It is working perfectly.

**Comment by iam-Shashank** [comment]
@ikeliec will try this out. Though, new to RN, so a bit confusing. I basically need to display data from an API. the UI looks like this. bottom part needs to be infinite scroll.
![image](https://user-images.githubusercontent.com/34963991/69998980-969a2080-157d-11ea-9a3f-d44ce932a6b1.png)
