### ISSUE TITLE
Disable Tabs swipe to change

### ISSUE THREAD

**Issue by sarmadmakhdoom** [GeekyAnts/NativeBase#2690]
Hi

I am using Header tabs and each tab has swipeable list. But when I swipe the list item to show right or left items, instead of showing those items, tabs scroll to next tab.

Is there a way to make the tabs don't respond to swipe action and user can only change them by clicking on them rather than swiping? That will solve my swipeable list problem.

Any help would be greatly appreciated.
Thanks

**Comment by sarmadmakhdoom** [comment]
Found it, Tabs should have **locked** prop set in order to make them static.

**Comment by JxDarkAngel** [comment]
> Found it, Tabs should have **locked** prop set in order to make them static.

Thanks!!
