### ISSUE TITLE
Unable to use Font Awesome 5 Pro Icons

### ISSUE THREAD

**Issue by OrLavy** [GeekyAnts/NativeBase#2691]
## I have gone through these following points
- [V]   Check latest documentation: https://docs.nativebase.io/
- [V]   Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [V]   Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [V]   Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- []   For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- []   For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

## Issue Description
Usage of 'Font-Awesome 5 Pro' seems to be problematic.
There is seemingly no easy way to add the Pro fonts.

With the 'react-native-vector-icons' package installed and configured (with their 'fa5-upgrade'), we can see that the 'Icon' component of 'react-native-vector-icons' is configured well and can load FA5 Pro icons successfully. 

But, When trying to use the same icon name with the NativeBase 'Icon' component we get a warning message (about the using of a unsupported icon name "sign-out" for the sake of example). 

Trying to run the 'fa5-upgrade' script that is inside the 'node_modules/NativeBase' does not seem to solve this problem.

Note: After running the 'fa5-upgrade' script I ran the metro packager and 'react-native run-android' to ensure loading of any new assets.

In addition, there seems to be no option of even choosing the 'Fontawesome5 pro' font family and the props does not allow to add a property of "Solid"/"Light"/"Regular" to differentiate between the FA5 icons.

### Expected behaviour
1. Usage of FontAwesome5 Pro icons will work properly (Display pro icons) or at least will be 
easy to configure.
2. Should be able to choose the 'Fa5 pro' font family.
3. The properties for 'Solid'/'Light'/'Dark' (which exists for the 'react-native-vector-icons' Icon) should be valid props for the NativeBase 'Icon'.

### Actual behaviour
1.No icons are being displayed when using a 'pro only' icon name (e.g "sign-out").
2. Selecting 'FontAwesome 5 Pro' raises a Typescript type error.
3. Adding a 'Solid'/'Light'/'Dark'  raise an editor error.

### Steps to reproduce
Try to use a 'pro only' icon.

### Is the bug present in both iOS and Android or in any one of them?
Both

**Comment by GaetanB999** [comment]
Hello,

I have the same problem with the free version.

"native-base": "^2.12.1",
"react": "16.6.1",
"react-native": "0.57.7"

<Icon name="comment-medical" type="FontAwesome5" />

Result in :
![image](https://user-images.githubusercontent.com/38727957/57297475-f86dd700-70cf-11e9-8b05-2f592d0fd7f6.png)
