### ISSUE TITLE
Input's onChange & onChangeText not working with floatingLabel & styled-component 

### ISSUE THREAD

**Issue by nuKs** [GeekyAnts/NativeBase#2692]
## I have gone through these following points
- [x]   Check latest documentation: https://docs.nativebase.io/
- [x]   Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x]   Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [x]   Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [x]   For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- [x]   For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

### node, npm, react-native, react and native-base version, expo version if used, xcode version

```
    node@10.15.1
    yarn@1.13.0
    "react-native": "0.58.3",
    "react": "16.6.3",
    "native-base": "2.12.1",
```

### Expected behaviour

onChangeText & onChange events triggered on <Input> when used with both floatingLabel & styled-components using the `.attrs` function.

### Actual behaviour

onChangeText & onChange events aren't triggered on <Input> when used with both floatingLabel & styled-components.

- Passing the onChange* attributes using the styled-components `.attrs` function does *not* fix behavior.
- Removing floatingLabel on <Item> fixes the issue!
- Removing styled-component fixes the issue!
- (only one of the two above step is required to fix the issue, no need to do both) 

### Steps to reproduce
```
                    <Item floatingLabel>
                        <Label>numéro d'identification</Label>
                        <IdInput onChangeText={participantId => console.log('triggered?')} />
                    </Item>
```
```
const IdInput = styled(Input)
    `
        border-bottom-color: #AAA;
        border-bottom-width: 1px;
    `;
```

### Is the bug present in both iOS and Android or in any one of them?

Bug on Android Emulator (genymotion), not tested under iOS.

### Any other additional info which would help us debug the issue quicker.

This is different from previous issues. They have been effectively fixed, however do not include the use of styled-component.

**Comment by nuKs** [comment]
Ftr, setting up the border like that is useless in this case.
I actually don't need to style the input.

Also writing the bug for doc purpose in case anyone come across.

**Comment by Sivli-Embir** [comment]
Can confirm for iOS.

**Comment by grzegorzkruk** [comment]
I've found source of problem related to this issue. "Item" component, while "floatingLabel" prop is set, handles only children that are of type Label, Input, Icon, Thumbnail from native-base. Other items of childrenArray are not use to render inside renderChildren.

Look this chunk of code:
[https://github.com/GeekyAnts/NativeBase/blob/f11d9b4e9e004650d16bb9857e5f4370d0f06fbb/src/basic/Item.js#L131](url)

To solve this issue renderChildren should render other childrenArray items if are not of specified types.

**Comment by hanykumar** [comment]
Hi @nuKs , Feature `FloatingLabel` for `item` is limited. You can use Label, Input, Icon, Thumbnail  from NativeBase. Closing for now.
