### ISSUE TITLE
Warning:Failed prop type: Invalid prop 'backgroundColor' supplied to 'ScrollableTabBar': 

### ISSUE THREAD

**Issue by tiffanym19** [GeekyAnts/NativeBase#2695]
import React, { Component } from "react";
import { Animated, Dimensions, Platform, Text, TouchableOpacity, View } from "react-native";
import { Body, Header, List, ListItem as Item, ScrollableTab, Tab, TabHeading, Tabs, Title } from "native-base";
import SwiperImage from "../components/SwiperImage";

const { width: SCREEN_WIDTH } = Dimensions.get("window");
const IMAGE_HEIGHT = 250;
const HEADER_HEIGHT = Platform.OS === "ios" ? 64 : 50;
const SCROLL_HEIGHT = IMAGE_HEIGHT - HEADER_HEIGHT;
const THEME_COLOR = "#2d3436";
const FADED_THEME_COLOR = "#2d3436";

export default class ArtistDetailScreen extends Component {
  static navigationOptions = {
    header: null,
  };

  nScroll = new Animated.Value(0);
  scroll = new Animated.Value(0);
  textColor = this.scroll.interpolate({
    inputRange: [0, SCROLL_HEIGHT / 5, SCROLL_HEIGHT],
    outputRange: [THEME_COLOR, FADED_THEME_COLOR, "white"],
    extrapolate: "clamp"
  });
  tabBg = this.scroll.interpolate({
    inputRange: [0, SCROLL_HEIGHT],
    outputRange: ["white", THEME_COLOR],
    extrapolate: "clamp"
  });
  tabY = this.nScroll.interpolate({
    inputRange: [0, SCROLL_HEIGHT, SCROLL_HEIGHT + 1],
    outputRange: [0, 0, 1]
  });
  headerBg = this.scroll.interpolate({
    inputRange: [0, SCROLL_HEIGHT, SCROLL_HEIGHT + 1],
    outputRange: ["transparent", "transparent", THEME_COLOR],
    extrapolate: "clamp"
  });
  imgScale = this.nScroll.interpolate({
    inputRange: [-25, 0],
    outputRange: [1.1, 1],
    extrapolateRight: "clamp"
  });
  imgOpacity = this.nScroll.interpolate({
    inputRange: [0, SCROLL_HEIGHT],
    outputRange: [1, 0],
  });
  tabContent = (x, i) => <View style={{ height: this.state.height }}>
    <List onLayout={({ nativeEvent: { layout: { height } } }) => {
      this.heights[i] = height;
      if (this.state.activeTab === i) this.setState({ height })
    }}>
      {new Array(x).fill(null).map((_, i) => <Item key={i}><Text>Item {i}</Text></Item>)}
    </List></View>;
  heights = [500, 500];
  state = {
    activeTab: 0,
    height: 500
  };

  constructor(props) {
    super(props);
    this.nScroll.addListener(Animated.event([{ value: this.scroll }], { useNativeDriver: false }));
  }

  render() {

    return (
      <View>
        <Animated.View style={{ position: "absolute", width: "100%", backgroundColor: this.headerBg, zIndex: 1 }}>
          <Header style={{ backgroundColor: "transparent" }} hasTabs>
            <Body>
              <Title>
                <Animated.Text style={{ color: this.textColor, fontWeight: "bold" }}>
                  Hello
              </Animated.Text>
              </Title>
            </Body>
          </Header>
        </Animated.View>
        <Animated.ScrollView
          scrollEventThrottle={5}
          showsVerticalScrollIndicator={false}
          onScroll={Animated.event([{ nativeEvent: { contentOffset: { y: this.nScroll } } }], { useNativeDriver: true })}
          style={{ zIndex: 0 }}>
          <Animated.View style={{
            transform: [{ translateY: Animated.multiply(this.nScroll, 0.65) }, { scale: this.imgScale }],
            backgroundColor: THEME_COLOR
          }}>
            <Animated.View style={{ height: IMAGE_HEIGHT, width: "100%" }}>
              <SwiperImage />
            </Animated.View>
          </Animated.View>
          <Tabs
            prerenderingSiblingsNumber={3}
            onChangeTab={({ i }) => {
              this.setState({ height: this.heights[i], activeTab: i })
            }}
            renderTabBar={(props) => <Animated.View
              style={{ transform: [{ translateY: this.tabY }], zIndex: 1, width: "100%", backgroundColor: "white" }}>
              <ScrollableTab {...props}
                renderTab={(name, page, active, onPress, onLayout) => (
                  <TouchableOpacity key={page}
                    onPress={() => onPress(page)}
                    onLayout={onLayout}
                    activeOpacity={0.4}>
                    <Animated.View
                      style={{
                        flex: 1,
                        height: 100,
                        backgroundColor: this.tabBg
                      }}>
                      <TabHeading scrollable
                        style={{
                          backgroundColor: "transparent",
                          width: SCREEN_WIDTH / 3
                        }}
                        active={active}>
                        <Animated.Text style={{
                          fontWeight: active ? "bold" : "normal",
                          color: this.textColor,
                          fontSize: 14
                        }}>
                          {name}
                        </Animated.Text>
                      </TabHeading>
                    </Animated.View>
                  </TouchableOpacity>
                )}
                underlineStyle={{ backgroundColor: this.textColor }} />
            </Animated.View>
            }>
            <Tab heading="Tab 1">
              {this.tabContent(30, 0)}
            </Tab>
            <Tab heading="Tab 2">
              {this.tabContent(15, 1)}
            </Tab>
            <Tab heading="Tab 3">
              {this.tabContent(30, 0)}
            </Tab>
          </Tabs>
        </Animated.ScrollView>
      </View>
    )
  }
}
I cant trace where is the error even there is no rgba Color Format declared in the code :( Plss help

**Comment by PlabanJr** [comment]
Please follow the issue template.

**Comment by hanykumar** [comment]
Hi @tiffanym19 , please provide minimal code reproduction for the same or screenshots?

**Comment by Pankti16** [comment]
same issue here, please share if you find any solution.

**Comment by hanykumar** [comment]
Hi @tiffanym19 ,  closing this now due to inactivity. Let us know if the issue still persists.
