### ISSUE TITLE
Should we have search feature on document page?

### ISSUE THREAD

**Issue by anhkhoi** [GeekyAnts/NativeBase#2696]
I want to suggest the search feature on document page. 
https://docs.nativebase.io/

Look like the document of bootstrap framework.
https://getbootstrap.com/docs/4.3/getting-started/introduction/

I feel inconvenience and takes a lot of time when I want to find the description of a component.

**Comment by SupriyaKalghatgi** [comment]
https://github.com/GeekyAnts/native-base-docs/issues/197
