### ISSUE TITLE
custom position switch

### ISSUE THREAD

**Issue by NguyenPhatBG** [GeekyAnts/NativeBase#2697]
![Screenshot_20190511-113933](https://user-images.githubusercontent.com/33904172/57565165-a46e3580-73e2-11e9-9b19-8831e3bb5b72.png)

How I can position switch to right?
My code:
<ListItem style={{ flex: 1, justifyContent: 'space-between', alignItems: 'center' }}>
      <RNText.Text light>Face ID</RNText.Text>
          <Switch 
              value={isSwitchOn}
              onValueChange={() => { 
              this.setState({ isSwitchOn: !isSwitchOn }); 
               }} 
                style={{ backgroundColor: 'yellow' }}
           />
 </ListItem>

**Comment by hanykumar** [comment]
Hi @NguyenPhatBG, please use `<Right> <Switch {...props} />  </Right>` for better alignment of switch.

**Comment by hanykumar** [comment]
Hi @NguyenPhatBG , latest version of Native base has been released.

[Native Base 2.13.12](https://github.com/GeekyAnts/NativeBase/releases/tag/v2.13.12)
