### ISSUE TITLE
Tabs content area is sensitive to sliding

### ISSUE THREAD

**Issue by Ghost-Luu** [GeekyAnts/NativeBase#2698]
Swiping in the content area of the android Tabs is very sensitive, and I occasionally shake to the left and right when I swipe down in the content area. This problem has caused me a lot of trouble。
This is my code
`
<Tabs renderTabBar={()=> <ScrollableTab style={{ backgroundColor: Colors.black, borderBottomColor: Colors.blueBJ }} />} 
          tabBarUnderlineStyle={styles.tabs_Bar}
        >
          <Tab heading="AA" 
            activeTextStyle={styles.tabs_active_text} 
            activeTabStyle={styles.tabs_active} 
            tabStyle={styles.tabs_list}
            textStyle={styles.tabs_text}
            style={{backgroundColor: Colors.blueBJ}}
          >
            <ActivityContent activity={activity} navigation={this.props.navigation.navigate}/>
          </Tab>
          <Tab heading="BB"
            activeTextStyle={styles.tabs_active_text} 
            activeTabStyle={styles.tabs_active}
            tabStyle={styles.tabs_list}
            textStyle={styles.tabs_text}
            style={{backgroundColor: Colors.blueBJ}}
          >
            <Text>233</Text>
          </Tab>
          <Tab heading="CC" 
            activeTextStyle={styles.tabs_active_text}
            activeTabStyle={styles.tabs_active}
            tabStyle={styles.tabs_list}
            textStyle={styles.tabs_text}
            style={{backgroundColor: Colors.blueBJ}}
          >
            <Text>233</Text>
          </Tab>
          <Tab heading="WW" 
            activeTextStyle={styles.tabs_active_text}
            activeTabStyle={styles.tabs_active} 
            tabStyle={styles.tabs_list} 
            textStyle={styles.tabs_text}
            style={{backgroundColor: Colors.blueBJ}}
          >
            <Text>233</Text>
          </Tab>
          <Tab heading="FF" 
            activeTextStyle={styles.tabs_active_text}
            activeTabStyle={styles.tabs_active} 
            tabStyle={styles.tabs_list} 
            textStyle={styles.tabs_text}
            style={{backgroundColor: Colors.blueBJ}}
          >
            <Text>233</Text>
          </Tab>
          <Tab heading="DD" 
            activeTextStyle={styles.tabs_active_text}
            activeTabStyle={styles.tabs_active} 
            tabStyle={styles.tabs_list} 
            textStyle={styles.tabs_text}
            style={{backgroundColor: Colors.blueBJ}}
          >
            <Text>233</Text>
          </Tab>
          <Tab heading="QQ" 
            activeTextStyle={styles.tabs_active_text}
            activeTabStyle={styles.tabs_active} 
            tabStyle={styles.tabs_list} 
            textStyle={styles.tabs_text}
            style={{backgroundColor: Colors.blueBJ}}
          >
            <Text>233</Text>
          </Tab>
        </Tabs>
`

**Comment by Ghost-Luu** [comment]
The problem is that I've used `FlatList` in the Tabs content area, but how do I fix it?

**Comment by Ghost-Luu** [comment]
The same problem arises with SwipeRow

**Comment by Ghost-Luu** [comment]
![5月-13-2019 19-05-45](https://user-images.githubusercontent.com/19573965/57617021-4c862900-75b2-11e9-865f-61f84a1c66a2.gif)

**Comment by michaelVictoriaDev** [comment]
same issue in SwipeRow is to sensitive

**Comment by hanykumar** [comment]
Hi @Ghost-Luu , For scrolling, you need to use content which supports auto-scrolling or you need to use `ScrollView` from `react-native` manually. Closing for now. Please let us know if the issue still persists.
