### ISSUE TITLE
Cannot outline icons

### ISSUE THREAD

**Issue by danigrandem** [GeekyAnts/NativeBase#2699]
## Issue Description
outlined icons not working.

### node, npm, react-native, react and native-base version, expo version if used, xcode version
   ```
 "expo": "^32.0.0",
    "native-base": "^2.12.1",
    "react": "16.5.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz",
```
### Expected behaviour
adding -outline to an icon name the icon appears outlined

### Actual behaviour
whe i put this componet

`<Icon  name="heart-outline"   />`
or
`<Icon  name="md-heart-outline"   />`
or
`<Icon  name="ios-heart-outline"   />`

it appears a ?

### Steps to reproduce
` <StyleProvider style={getTheme(material)}>

        <CardStyled>
          <CardItem
            cardBody
            button={true}
            role="button"
            onPress={this.handleOnPress}
          >
            <ImageContainer>
              <CardImage
                source={{
                  uri: item.show_poster
                }}
                resizeMode="cover"
              />
            </ImageContainer>
            <FavouriteButtonContainer>
              <FavouriteButton>
                <Icon
                  style={{
                    textAlign: 'center'
                  }}
                  name="md-heart-outline"
                />
              </FavouriteButton>
            </FavouriteButtonContainer>
          </CardItem>
          <CardItem style={{ flex: 1 }}>
            <ColInfo>
              {notesProviders.length > 0 && (
                <NotesContainer>
                  <Notes notes={notesProviders} small />
                </NotesContainer>
              )}
            </ColInfo>
          </CardItem>
        </CardStyled>
`

**Comment by SupriyaKalghatgi** [comment]
As per NativeBase 2.12.1, here is the list of icons that work 
https://github.com/oblador/react-native-vector-icons/blob/master/glyphmaps/Ionicons.json

Also check NativeBase VectorIconApp https://github.com/GeekyAnts/NativeBase-VectorIconApp/blob/master/src/icon-list/Ionicons.js
