### ISSUE TITLE
Not working with react-native 0.26

### ISSUE THREAD

**Issue by demiro** [GeekyAnts/NativeBase#27]
I have a very simple setup, installed vector icons (work great) but when trying to load modules from native-base:
`import {Container, Header, Content, Footer, Title} from 'native-base';`

I get an error

> 
Requiring unknown module "react-native/Libraries/ReactNative/ReactNativePropRegistry".If you are sure the module is there, try restarting the packager or running "npm install"

At least for android not working

**Comment by sankhadeeproy007** [comment]
#26

**Comment by sankhadeeproy007** [comment]
RN 0.26 supported with latest update.
