### ISSUE TITLE
App gets crashed on release mode with the following error null is not an object (evaluating 's.drawer._root')

### ISSUE THREAD

**Issue by nidhinkumar06** [GeekyAnts/NativeBase#2700]
## I have gone through these following points
- [x]   Check latest documentation: https://docs.nativebase.io/
- [x]   Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x]   Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [x]   Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- []   For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- []   For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

## Issue Description
I have used native base drawer which works fine in debug mode but when i created an release apk the app gets crashed with the following error.
```
AndroidRuntime: com.facebook.react.common.JavascriptException: null is not an object (evaluating 's.drawer._root')
```
### node, npm, react-native, react and native-base version, expo version if used, xcode version
node - 10.15.1
npm - 6.4.1
react-native -0.58.6
native-base - ^2.12.0
### Expected behaviour
It should close / open the drawer
### Actual behaviour
App gets crashed in release mode
### Steps to reproduce
Created a release version of the apk with native base drawer and open and close the drawer.
### Code
```
  closeDrawer = () => {
    this.drawer._root && this.drawer._root.close();
  };
  openDrawer = () => {
    this.drawer._root && this.drawer._root.open();
  };

<Drawer
          ref={(ref) => {
            this.drawer = ref;
          }}
          type="overlay"
          side={'left'}
          openDrawerOffset={0.2}
          panOpenMask={0.2}
          tapToClose={true}
          content={
            <CityWitsSideBar
              navigator={this.navigator}
              closeDrawer={() => this.closeDrawer()}
              {...this.props}
            />
          }
          tweenHandler={(ratio) => ({
            main: { opacity: (2 - ratio) / 2 }
          })}
          onClose={() => this.closeDrawer()}
        >
```
### Is the bug present in both iOS and Android or in any one of them?
Android
### Any other additional info which would help us debug the issue quicker.
Nothing

**Comment by raguct25** [comment]
@nidhinkumar06
https://stackoverflow.com/questions/56335294/react-native-app-gets-crashed-on-release-mode-with-the-following-error-null-is-n
