### ISSUE TITLE
Picker onValueChange

### ISSUE THREAD

**Issue by eyalabadi98** [GeekyAnts/NativeBase#2703]
## I have gone through these following points
- [x]   Check latest documentation: https://docs.nativebase.io/
- [x]   Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x]   Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [x]   Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [x]   For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- [ ]   For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

## Issue Description
When using Picker, the callback prop onValueChange only returns a string, but the regular RN picker has both a key and string

Latest

### Expected behaviour

I would like to access the key used, not just the label

### Actual behaviour
I only get access to label
### Steps to reproduce
```
<Picker
                                mode="dropdown"
                                selectedValue={this.state.selectedDateLabel}
                                iosIcon={<IconNB name="arrow-down" />}
                                placeholder="Select Target"
                                defaultLabel={"-----"}
                                style={{ width: 100 }}
                                onValueChange={((text) => {

                                })}
           
                              >
                              { datesDropDown.map(value => {
                                  return (<Picker.Item key={value.key} label={value.value} value={value.value} />);
                                  }) 
                              } 
                              </Picker>
```
### Is the bug present in both iOS and Android or in any one of them?
Only checked IOS

**Comment by shripradashivakumar** [comment]
Any update on this issue?

**Comment by hanykumar** [comment]
Hi @eyalabadi98 , can you provide minimal code reproduction on snack for the same?

**Comment by hanykumar** [comment]
Hi @eyalabadi98, `onValueChange` return value and key both. Closing this now due to inactivity. Let us know if the issue still persists.
 

```
onValueChange(value, key) {
    console.log('Value: ', value);
    console.log('key: ', key);
    this.setState({
      selected: value,
    });
  }

<Picker
              note
              mode="dropdown"
              style={{width: 120}}
              selectedValue={this.state.selected}
              onValueChange={this.onValueChange.bind(this)}>
              <Picker.Item key="0" label="Wallet" value="key0" />
              <Picker.Item key="1" label="ATM Card" value="key1" />
              <Picker.Item key="2" label="Debit Card" value="key2" />
              <Picker.Item key="3" label="Credit Card" value="key3" />
              <Picker.Item key="4" label="Net Banking" value="key4" />
</Picker>
```

![Screenshot 2020-08-18 at 11 34 09 AM](https://user-images.githubusercontent.com/15860517/90476357-f73aaf00-e146-11ea-978a-26ed1c19de55.png)
