### ISSUE TITLE
Is it possible to use Animated native base component?

### ISSUE THREAD

**Issue by kaushalrajopenxcell** [GeekyAnts/NativeBase#2704]
Hello,

I am using NativeBase and want to add animation on the component like badges or icons etc.

Can I get any referent link or code to get an idea? I could not find in the documentation or an example?

**Comment by hanykumar** [comment]
Hi @kaushalrajopenxcell , there are no animated native-base components like badges and icons yet. But you can use [icons](https://icons8.com/animated-icons) for animated icons. Closing for now.

**Comment by kaushalrajopenxcell** [comment]
@hanykumar Okay. Thank you!
