### ISSUE TITLE
initialPage doesnt work in android

### ISSUE THREAD

**Issue by siddhesh-atd** [GeekyAnts/NativeBase#2705]
## Issue Description
I have 4 tabs in android and want to display the 4th tab by default if a condition sets true.

"react-native": "^0.52.0",
 "native-base": "2.3.5",

### Expected behaviour
The 4th tab should be the active tab (works this way in ios)

### Actual behaviour
Opens the page with 1st tab active

### Steps to reproduce
<Tabs
            prerenderingSiblingsNumber={4}
            initialPage={4} // works in ios

### Is the bug present in both iOS and Android or in any one of them?
Android
### Any other additional info which would help us debug the issue quicker.

@SupriyaKalghatgi - Can you look into this issue ?

**Comment by Srishti-Sharma** [comment]
To display nth tab, we need to give initialPage={n-1}

**Comment by uday5162** [comment]
initialPage={n-1} is taking to nth Tab but it's not rendering the nth tab

**Comment by uday5162** [comment]
It's rendering when i go to another tab and come back to this tab

**Comment by tinpt123** [comment]
> To display nth tab, we need to give initialPage={n-1}

it's not work :(

**Comment by Srishti-Sharma** [comment]
Please try with the latest version of [NativeBase](https://github.com/GeekyAnts/NativeBase/releases).

**Comment by hanykumar** [comment]
Hi @siddhesh-atd , we hope its working with updated NativeBase. Closing for now. Let us know if the issue still persists.
