### ISSUE TITLE
Picker on iOS ellipsize width can not set overflow #2431

### ISSUE THREAD

**Issue by pearpai** [GeekyAnts/NativeBase#2707]
<Text style={[this.props.textStyle, { width: Dimensions.get("window").width - 50 }]} note={this.props.note} numberOfLines={1} ellipsizeMode="tail"> 

width could not set overflow
can we do like this
<Text style={[ { width: Dimensions.get("window").width - 50 }, this.props.textStyle]} note={this.props.note} numberOfLines={1} ellipsizeMode="tail">

**Comment by hanykumar** [comment]
Hi @pearpai , can you provide working minimal reproduction for the same in snack?

**Comment by hanykumar** [comment]
Hi @pearpai , closing for now due to inactivity, please provide minimal code reproduction on snack for the same if the issue still persists.
