### ISSUE TITLE
Padding in percentage is generating error

### ISSUE THREAD

**Issue by Mavenic** [GeekyAnts/NativeBase#2710]
## I have gone through these following points
- []   Check latest documentation: https://docs.nativebase.io/
- []   Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- []   Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- []   Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- []   For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- []   For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

### Using padding in percentage in Content tag gives an error.
JSON value '5%0' of type NSString cannot be converted to a YGValue. Did you forget the % or pt suffix?

+[RCTConvert YGValue:]
    RCTConvert.m:549
__invoking___
-[NSInvocation invoke]
__createNSInvocationSetter_block_invoke
__49-[RCTComponentData createPropBlock:isShadowView:]_block_invoke.162
__49-[RCTComponentData propBlockForKey:isShadowView:]_block_invoke_2

### Versions Used

Node : v10.15.3
NPM : 6.4.1
react-native : 0.59
native-base : 2.12.1
xCode : 10.1

### Expected behaviour
It should accept the percentage values as it is doing for other views.

### Actual behaviour
Giving Error: JSON value '5%0' of type NSString cannot be converted to a YGValue.

### Steps to reproduce

Create a new react-native project and provide the "padding" to Content tag in percentage.
"paddingTop" alone is working fine.
```
<Content style={{padding:"5%"}}>
<Text>I am home</Text>                
</Content>
```

### Is the bug present in both iOS and Android or in any one of them?
IOS

### Any other additional info which would help us debug the issue quicker.
Removing the value in percentage or providing a number as value solves the issue.

**Comment by sankhadeeproy007** [comment]
Please use `contentContainerStyle={{padding: '30%'}}`
