### ISSUE TITLE
Any document about Container, Content, Item component?

### ISSUE THREAD

**Issue by code-brewer** [GeekyAnts/NativeBase#2713]
## I have gone through these following points
- [x]   Check latest documentation: https://docs.nativebase.io/
- [x]   Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x]   Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [x]   Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- []   For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- []   For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

### node, npm, react-native, react and native-base version, expo version if used, xcode version
  Not pertain to the development 

### Expected behaviour
  Clear document about component like Container, Content, Item component

### Actual behaviour
   NOT found it in official document

### Steps to reproduce

  NO

### Is the bug present in both iOS and Android or in any one of them?
  NO

### Any other additional info which would help us debug the issue quicker.
 NO

 **A few questions.**
1) Currently, I'm using the Input component, but not found a description on how to use. Does it comply with the usage of the React Native counterpart?   So does other components, such as View, Label, Text all apply this rule?

2) For those components that are not the counterpart of React Native, such as Item, Container, I could not find details document. If there are, please tell me the urls.

**Comment by hanykumar** [comment]
Hi @code-brewer , We are working on it. Closing for now. Let us know if the issue still persists.
- [Forms](https://docs.nativebase.io/Components.html#Form) have all info related to the use of label, Item, input.
- Container, Header, Content, Footer can be used as you can see in every example of [NativeBase Docs](https://docs.nativebase.io/Components.html#Components)
```
return (
<Container>
   <Header>
     ...
   </Header>
   <Content>
     ...
   </Content>
   <Footer>
     ...
   </Footer>
</Container>
)
```

Thanks.
