### ISSUE TITLE
'_root' cannot be accessed in typescript project of most NativeBase Components.

### ISSUE THREAD

**Issue by chj-damon** [GeekyAnts/NativeBase#2714]
## I have gone through these following points
- []   Check latest documentation: https://docs.nativebase.io/
- []   Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- []   Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- []   Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- []   For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- []   For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

## Issue Description

I read the document about ref, and it is said I can use `refs` to get access to every components, and `_root` to get access to RN components. But I cannot use it in my typescript project, because `_root` does not exist in `index.d.ts`
### Expected behaviour
I can use something like `this.button._root` in typescript project.
### Actual behaviour
ts warns me that `_root` does not exist in component, like `Drawer`

**Comment by bscaspar** [comment]
@chj-damon did you every find a way to fix this/workaround?

**Comment by suxur** [comment]
I'm having this issue as well.

**Comment by z3v0k** [comment]
idem issue

**Comment by renielDev** [comment]
I am having this issue right now. Any fix on this?

**Comment by darron1217** [comment]
If someone can explain how to solve this issue, I would create PR
