### ISSUE TITLE
Name is No Longer Optional Attribute for 'Icon' component in Typescript

### ISSUE THREAD

**Issue by wardjk87** [GeekyAnts/NativeBase#2715]
## I have gone through these following points
- [X]   Check latest documentation: https://docs.nativebase.io/
- [X]   Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [X]   Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [X]   Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- []   For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- []   For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

## Issue Description
This fix (https://github.com/GeekyAnts/NativeBase/issues/960) has been removed in current version of index.d.ts for native base 2.12.1. Name is no longer optional. According to documentation Icon can be used without name but with android and ios properties.

Following is copy of documentation example of Icon:

`import React, { Component } from 'react';
import { Container, Header, Content, Icon } from 'native-base';
export default class IconExample extends Component {
  render() {
    return (
      <Container>
        <Header />
        <Content>
          <Icon name='home' />
          <Icon ios='ios-menu' android="md-menu" style={{fontSize: 20, color: 'red'}}/>
          <Icon type="FontAwesome" name="home" />
        </Content>
      </Container>
    );
  }
}`

lines 642-653 of index.t.ts

interface Icon extends Testable { **name: string;** type?: "AntDesign" | "Entypo" | "EvilIcons" | "Feather" | "FontAwesome" | "FontAwesome5" | "Foundation" | "Ionicons" | "MaterialCommunityIcons" | "MaterialIcons" | "Octicons" | "SimpleLineIcons" | "Zocial"; // TODO position attribute of ReactNative.FlexStyle hasn't another position values without "absolute" and "relative" style?: any; onPress?: (e?: any) => any; active?: boolean; ios?: string; android?: string; color?: string; fontSize?: number; }

Example usage that triggers 'Property 'name' is missing in type...' error in Typescript:  <Icon active ios='ios-send' android='md-send />

### node, npm, react-native, react and native-base version, expo version if used, xcode version
irrelevant
### Expected behaviour
Typescript does not complain about only using ios and android properties of Icon.
### Actual behaviour
Typescript complains that attribute name is missing
### Steps to reproduce
 -use Typescript and Icon with only ios and android attributes without name defined
### Is the bug present in both iOS and Android or in any one of them?
Irrelevant

**Comment by wardjk87** [comment]
Has this been reviewed?

**Comment by hanykumar** [comment]
Hi @wardjk87 , Found no issue with `Icon` in Typescript with NativeBase v2.13.14 . Closing for now. Let us know if the issue still persists.

<img width="880" alt="Screenshot 2020-09-01 at 12 09 20 PM" src="https://user-images.githubusercontent.com/15860517/91810715-0132d680-ec4c-11ea-9a62-a4eff44ec0d1.png">
