### ISSUE TITLE
<Card/> margin only works with specified direction

### ISSUE THREAD

**Issue by evanlesmez** [GeekyAnts/NativeBase#2718]
### node, npm, react-native, react and native-base version, expo version if used, xcode version
React native version 0.57.1, react@16.6.3, native-base@2.12.1
### Expected behaviour
Card should take marginVertical, marginHorizontal, and margin as props
### Actual behaviour
Card only responds to marginBottom, marginTop, marginRight, marginLeft
### Steps to reproduce
<!--
```
<Card margin = 10 />
```

**Comment by rabidkitten** [comment]
The original poster was correct, the margin style does not get applied. You must specify the marginLeft, marginRight, etc. in order for it to work.
