### ISSUE TITLE
if borderWidth is applied to thumbnail image gets blur ? 

### ISSUE THREAD

**Issue by ppv94** [GeekyAnts/NativeBase#2719]
### Expected behaviour
used native-base Thumbnail for the 1st image in the screenshot
## Actual behaviour 
I had used react-native  image for the 2nd image in the screenshot 

applied same properties for both the images.

![Simulator Screen Shot - iPhone 8 - 2019-06-05 at 16 39 11](https://user-images.githubusercontent.com/28724702/58952192-a85a6100-87b0-11e9-95e2-3e4daeca9520.png)

**Comment by PlabanJr** [comment]
Please add proper reproduction steps, preferably a snack.

**Comment by hanykumar** [comment]
Hi @ppv94 , We have tested the same, but didn't find such issue. 
Closing this now due to inactivity. Let us know if the issue still persists
