### ISSUE TITLE
iPad Pro (12.9-inch) (3rd generation) still wrong footer altough issue closed

### ISSUE THREAD

**Issue by benzman81** [GeekyAnts/NativeBase#2721]
## I have gone through these following points
- [x]   Check latest documentation: https://docs.nativebase.io/
- [x]   Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x]   Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [x]   Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [x]   For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- [x]   For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

## Issue Description
"iPad Pro (12.9-inch) (3rd generation)" still doesn't use safe area for footer although the issue #2497 is closed. No reaction to comments at all. Thats why I open this issue using new versions of libraries.

### node, npm, react-native, react and native-base version, expo version if used, xcode version
node v11.14.0
npm 6.9.1
xcode 10.2.1
npm list --depth=0:
├── @babel/core@7.4.5
├── @babel/runtime@7.4.5
├── axios@0.19.0
├── axios-retry@3.1.2
├── babel-jest@24.8.0
├── buffer@5.2.1
├── fbjs@1.0.0
├── jest@24.8.0
├── lodash@4.17.11
├── metro-react-native-babel-preset@0.54.1
├── native-base@2.12.1
├── qs@6.7.0
├── react@16.8.3
├── react-native@0.59.8
├── react-native-config@0.11.7
├── react-native-device-info@2.0.3
├── react-native-easy-grid@0.2.1
├── react-native-gesture-handler@1.3.0
├── react-native-htmlview@0.14.0
├── react-native-i18n@2.0.15
├── react-native-image-picker@0.28.1
├── react-native-keychain@3.1.3
├── react-native-locale@0.0.19
├── react-native-mime-types@2.2.1
├── react-native-modal-datetime-picker@7.4.2
├── react-native-splash-screen@3.2.0
├── react-navigation@3.11.0
├── react-test-renderer@16.8.3
├── rn-fetch-blob@0.10.13
├── sax@1.2.4
└── stream@0.0.2

### Expected behaviour
Safe area is used.

### Actual behaviour
Safe area is not used.

### Steps to reproduce
Just use FooterTabs "iPad Pro (12.9-inch) (3rd generation)".

### Is the bug present in both iOS and Android or in any one of them?
iOS

### Any other additional info which would help us debug the issue quicker.
no

**Comment by hanykumar** [comment]
Hi @benzman81 , found no issues with latest version NativeBase v2.13.14 . Please let us know if the issue still persists.
iPad Pro (11-inch) (2nd generation) no issue
iPad Pro (12.9-inch) (4th generation) no issue

**Comment by hanykumar** [comment]
Hi @benzman81 , closing for now due to inactivity. Please let us know if the issue still persists.
