### ISSUE TITLE
Picker on Android, Styles gone!

### ISSUE THREAD

**Issue by s43** [GeekyAnts/NativeBase#2725]
Hello there,

I am facing an issue with the picker's styles, I've followed the documentations and everything goes alright, at least with iOS, but once I checked on my Android device, kaboom! styles are gone, and the app didn't even recognized em !

My guess was that I should've passed another argument to style the component on Android, but nothing like that was available on the docs, I was mistaken.

here's how it should look on Android ( which is currently OK on iOS ) :

https://imgur.com/uNaXC1I

`
<Picker
	mode='dropdown'
	iosIcon={<FontAwesome style={{
		right: 20,
		color: '#ffffff'
	}} name="angle-down" />}
	onValueChange={(text) => this._handleFilterUpdate(text, config.name)}
	placeholder={title}
	textStyle={{
		color: '#ffffff'
	}}
	selectedValue={params[config.name]}
	placeholderStyle={{ color: "#ffffff" }}					
	style={[MainStyles.FILTERS.picker]}>
	{config.options.length > 0 ? config.options : false}
</Picker>
`
the styles that should've be applied are those : 

`		picker : {
			height: 50,
			borderColor: '#ffffff',
			borderWidth: 1,
			borderRadius : 50
		},`

Thanks for correcting me if I am doing something wrong, and I do really appreciate your time reading this !

**Comment by sankhadeeproy007** [comment]
The picker extends `react-native` picker, so the styles which are not supported on the native picker won't be applicable here.
