### ISSUE TITLE
ActionSheet is not expanding in height with 1 or 2 Items in the list

### ISSUE THREAD

**Issue by ahmad6242** [GeekyAnts/NativeBase#2727]
## I have gone through these following points
- [x]   Check latest documentation: https://docs.nativebase.io/
- [x]   Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x]   Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases

###  
"@react-native-community/async-storage": "^1.3.3",
    "axios": "^0.18.0",
    "moment": "^2.24.0",
    "native-base": "^2.12.1",
    "react": "16.8.3",
    "react-native": "0.59.5",
    "react-native-animatable": "^1.3.2",
    "react-native-calendars": "^1.110.0",
    "react-native-device-info": "^2.1.2",
    "react-native-document-picker": "^2.3.0",
    "react-native-firebase": "^5.3.1",
    "react-native-fs": "^2.13.3",
    "react-native-gesture-handler": "^1.1.0",
    "react-native-image-grid": "^1.0.0",
    "react-native-loading-spinner-overlay": "^1.0.1",
    "react-native-share": "^1.1.3",
    "react-native-swiper": "^1.5.14",
    "react-native-vector-icons": "^6.4.2",
    "react-navigation": "^3.9.0",
    "react-redux": "^7.0.2",
    "redux": "^4.0.1",
    "redux-axios-middleware": "^4.0.0",
    "redux-logger": "^3.0.6",
    "redux-thunk": "^2.3.0",
    "rn-fetch-blob": "^0.10.15"

### Expected behaviour

ActionSheet to properly expand in Height even the items in the list are less than or equal to 2

### Actual behaviour

Its not expanding properly. 

![Screenshot_1560925161](https://user-images.githubusercontent.com/12858657/59741320-bb266880-927b-11e9-8eed-419f4cf0c131.png)

**Comment by TomMahle** [comment]
I've made a pr that resolves this issue in my app. Testers would be appreciated :D

**Comment by rajnishcoder** [comment]
In my case it happen only if you have single item, if you add two or more it works fine,
and the issue is still there in latest version `2.12.0`
