### ISSUE TITLE
Overide Platform Specific UI

### ISSUE THREAD

**Issue by joshua1** [GeekyAnts/NativeBase#273]
Hi ,
Is it Possible to make provision for Over riding the Platform Specific UI constraints (Design Spec), I See that most of this in the code comes after a Platform.OS Check. It should be possible for me to Build an App with Material Design Look And feel regardless of the Device it would run on, By Simply Setting a Config Value to Either ios or android. If a user doesn't have this config set, then revert to the platform specific spec. You can even have this settings on components too.

**Comment by sanketsahusoft** [comment]
@joshua1 Yes, it is very much possible. Please check the (customization of NativeBase theme)[http://nativebase.io/docs/v0.5.9/customize#themingNativeBaseApp]. You can create a copy of the theme and remove all the platform specific conditionals.
