### ISSUE TITLE
native-base expo 33 problem

### ISSUE THREAD

**Issue by bibekkakati** [GeekyAnts/NativeBase#2731]
I am facing problem after latest expo update 33.0.x 

Error is-
system is looking for node_modules/native-base/fonts in Screens folder

directory tree-

main folder...
          screens
          components
          node_modules
          other folders..

![IMG_20190623_232109](https://user-images.githubusercontent.com/34815829/59980892-86b70180-9619-11e9-82ba-70c28f13061c.jpg)

**Comment by joaopiopedreira** [comment]
Hi @bibekkakati , did you find a solution to this?

**Comment by bibekkakati** [comment]
Not yet. I tried everything. Downgrading, reinstalling stuffs. Tried on new project also. But no result.

**Comment by joaopiopedreira** [comment]
Hi @bibekkakati, my error is gone. I was importing like this:
```
Font.loadAsync({
          'Roboto': require('native-base/Fonts/Roboto.ttf'),
          'Roboto_medium': require('native-base/Fonts/Roboto_medium.ttf'),
        }),
```

but then I've moved the relevant font files to a folder inside my app and imported like thiis:
```
Font.loadAsync({
          'Roboto': require('./resources/fonts/Roboto.ttf'),
          'Roboto_medium': require('./resources/fonts/Roboto_medium.ttf'),
        }),
```

**Comment by bibekkakati** [comment]
Is it required ?
Are you using any custom fonts ?
Because I am not using any custom fonts. Everything is by default.

**Comment by joaopiopedreira** [comment]
not sure, but it fixed my error

**Comment by bibekkakati** [comment]
Ohk I'll try that now

**Comment by bibekkakati** [comment]
ENOENT: no such file or directory, scandir 'E:\ReactNative\Foblo\screens\node_modules\native-base\Fonts'
Failed building JavaScript bundle.

Is the problem with native-base or latest react native and expo. Becoz this is happening after the latest update.

**Comment by joaopiopedreira** [comment]
shouldn't it be importing from `E:\ReactNative\Foblo\screens\node_modules` instead of `E:\ReactNative\Foblo\node_modules`?

**Comment by joaopiopedreira** [comment]
tested with a fresh new sdk33 project with `native-base` added. Works well.

**Comment by bibekkakati** [comment]
yeah.. It should import like this
E:/React Native/Foblo/node_modules

I dont know why this is happening.
Is there any common issue because of which this is happening ? I might
wrote somewhere something incorrectly.

**Comment by matanume** [comment]
In my case
I reinstall expo font
`expo install expo-font`
then change Font import
`import * as Font from 'expo-font';`
then rebuild native-base 
`npm rebuild native-base`
then re ejectTheme
`node node_modules/native-base/ejectTheme.js`
and make sure to import theme from new correct path
`import getTheme from "./../native-base-theme/components";
import variables from "./../native-base-theme/variables/commonColor";`

**Comment by bibekkakati** [comment]
ohk sure I'll try this. Thank you.

BTW Are you using any custom fonts in any screen ? Or just the default
font, since I am not using any type of fonts by myself.

**Comment by sxi-uiteam** [comment]
in my case

> Font.loadAsync({
>           'Roboto': require('native-base/Fonts/Roboto.ttf'),
>           'Roboto_medium': require('native-base/Fonts/Roboto_medium.ttf'),
>         }),
> 

### works when coding in root app.js
root
  App.js  <-- Font.loadAsync here

### not work when coding child directory
root
  App.js
  src/main.js    <-- Font.loadAsync here

> ENOENT: no such file or directory, scandir 'E:\ReactNative\Foblo\screens\node_modules\native-base\Fonts'
> Failed building JavaScript bundle.

**Comment by meishier** [comment]
in my case

> Font.loadAsync({
>           'Roboto': require('native-base/Fonts/Roboto.ttf'),
>           'Roboto_medium': require('native-base/Fonts/Roboto_medium.ttf'),
>         }),
> 

### works when coding in root app.js
root
  App.js  <-- Font.loadAsync here

### not work when coding child directory
root
  App.js
  src/main.js    <-- Font.loadAsync here

> ENOENT: no such file or directory, scandir 'E:\ReactNative\Foblo\screens\node_modules\native-base\Fonts'
> Failed building JavaScript bundle.

**Comment by Azghour-Saad** [comment]
@meishier, This really helped me :smile: Thanks.

**Comment by danghuyminh** [comment]
If you put it in sub directory, you should add node_modules to the path also:

 ```Font.loadAsync({
            'Roboto': require('../node_modules/native-base/Fonts/Roboto.ttf'),
            'Roboto_medium': require('../node_modules/native-base/Fonts/Roboto_medium.ttf'),
        })```

**Comment by sguha00** [comment]
Anyone know what changed in Expo 33 that breaks loading font files from node_modules without specifying a relative path?

**Comment by kocho** [comment]
Also having issues running native base with Expo 33. 

doing a clean install and following the provided commands i keep getting 
`Unable to resolve "@expo/vector-icons/FontAwesome5Pro" from "node_modules/native-base/dist/src/basic/IconNB.js"
Failed building JavaScript bundle.`

**Comment by gurudewan** [comment]
Same issue - have tried everything above and nothing worked. Has anyone got a fix?

**Comment by thiemo--bleeken** [comment]
same issue for me

**Comment by thiemo--bleeken** [comment]
`yarn add @expo/vector-icons`

replace 
`import { Icon } from 'expo'`
to
`import * as Icon from '@expo/vector-icons'`

**Comment by michaelkoek** [comment]
Downgrading to `2.12.1` worked for me
Got it from this reference [2783](https://github.com/GeekyAnts/NativeBase/issues/2783)

**Comment by diegolaciar** [comment]
+1  
same issue,d thanks for the solution

**Comment by shivarajnaidu** [comment]
Unable to resolve "@expo/vector-icons/FontAwesome5Pro" from "node_modules/native-base/dist/src/basic/IconNB.js"
getting the same error.. :(

**Comment by bibekkakati** [comment]
I resolved the issue by creating a FontAwesomePro5 file in that path and
copied the stuffs of FontAwesome. Thats it. It works for me.

**Comment by syedjaffersathik** [comment]
> I resolved the issue by creating a FontAwesome5Pro file in that path(@expo/vector-icons) and copied the stuffs of FontAwesome. Thats it. It works for me.

Can you please explain more or provide the stuffs!!!

**Comment by pratik007kumar** [comment]
> I resolved the issue by creating a FontAwesome5Pro file in that path(@expo/vector-icons) and copied the stuffs of FontAwesome. Thats it. It works for me.

Please explain how you did?

**Comment by bibekkakati** [comment]
`Unable to resolve "@expo/vector-icons/FontAwesome5Pro" from "node_modules/native-base/dist/src/basic/IconNB.js"`

If you are facing this issue, then here is the trick to resolve this issue until expo solve it on its own.
Problem is system is searching for a FontAwesome5Pro.js  file in @expo/vector-icons  , but file is not there.

So you just do this...

1. Go to node_modules/@expo/vector-icons.
2. Open the file FontAwesome5, and copy everything from that file.
3. Create a new js file "FontAwesome5Pro" , and paste everything here.
4. Save it and done.

**Comment by pratik007kumar** [comment]
thanks its worked

**Comment by Farangi** [comment]
> 
> 
> `Unable to resolve "@expo/vector-icons/FontAwesome5Pro" from "node_modules/native-base/dist/src/basic/IconNB.js"`
> 
> If you are facing this issue, then here is the trick to resolve this issue until expo solve it on its own.
> Problem is system is searching for a FontAwesome5Pro.js file in @expo/vector-icons , but file is not there.
> 
> So you just do this...
> 
>     1. Go to node_modules/@expo/vector-icons.
> 
>     2. Open the file FontAwesome5, and copy everything from that file.
> 
>     3. Create a new js file "FontAwesome5Pro" , and paste everything here.
> 
>     4. Save it and done.
It resolved the issue but now i am getting following:
fontFamily "ionicons" is not a system font and has not been loaded through Font.loadAsync.

- If you intended to use a system font, make sure you typed the name correctly and that it is supported by your device operating system.

- If this is a custom font, be sure to load it with Font.loadAsync.

**Comment by syedjaffersathik** [comment]
If you are using expo then follow this official documentation:
https://docs.expo.io/versions/latest/guides/using-custom-fonts/#using-custom-fonts

This is my app.js and working !!!

import React from 'react';
import { StyleSheet, Text, View, AcivityIndicator } from 'react-native';
import { Font } from 'expo';


export default class App extends React.Component {
    constructor () {
        super ()
        this.state = {fontLoaded: false}
    }
    async componentDidMount() {
        await Font.loadAsync ({
                              'Roboto': require ('./assets/fonts/Roboto-Bold.ttf')
                              });
        this.setState({fontLoaded: true});
    }
    render () {
        return (
                <View style = {styles.container}>
                {
                this.state.fontLoaded ? (

                <Text style = {{fontFamily: 'Roboto', fontSize: 56 }}>
                SYED JAFFER SATHIK
                </Text>
                                         ) : null
                }
        </View>
        )
    }
}
const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
    
  },
});

**Comment by NestedLooper** [comment]
Thanks @bibekkakati
`cp node_modules/\@expo/vector-icons/FontAwesome5.js node_modules/\@expo/vector-icons/FontAwesome5Pro.js`

**Comment by umutcanbolat** [comment]
> Thanks @bibekkakati
> `cp node_modules/\@expo/vector-icons/FontAwesome5.js node_modules/\@expo/vector-icons/FontAwesome5Pro.js`

This solves the error until the next npm install. Isn't there any persistent solution?

**Comment by alexanderwanyoike** [comment]
@umutcanbolat 
This is a massive hack but I added this to `package.json` we can only wait for `@expo/vector-icons` or native-base to fix this 
```
    "postinstall": "cp ./node_modules/@expo/vector-icons/FontAwesome.js ./node_modules/@expo/vector-icons/FontAwesome5Pro.js"
```

**Comment by Sanjaya94** [comment]
> If you put it in sub directory, you should add node_modules to the path also:
> 
> ```
>            'Roboto': require('../node_modules/native-base/Fonts/Roboto.ttf'),
>            'Roboto_medium': require('../node_modules/native-base/Fonts/Roboto_medium.ttf'),
>        })```
> ```

Thank you

**Comment by SeoBG** [comment]
1. Delete the node_modules folder
2. Delete the package-lock.json
3. Run npm install
4. Run expo start -c

**Comment by malFuckingFurion** [comment]
Delete the node_modules folder
Delete the package-lock.json
Run npm install
Run expo start -c

**Comment by alejandroyunes** [comment]
> Hi @bibekkakati, my error is gone. I was importing like this:
> 
> ```
> Font.loadAsync({
>           'Roboto': require('native-base/Fonts/Roboto.ttf'),
>           'Roboto_medium': require('native-base/Fonts/Roboto_medium.ttf'),
>         }),
> ```
> 
> but then I've moved the relevant font files to a folder inside my app and imported like thiis:
> 
> ```
> Font.loadAsync({
>           'Roboto': require('./resources/fonts/Roboto.ttf'),
>           'Roboto_medium': require('./resources/fonts/Roboto_medium.ttf'),
>         }),
> ```

this fixxed my issue aswell, had to move the fonts to a src/resources/fonts and that did the trick
