### ISSUE TITLE
warning of using component Multiple Swipeable List

### ISSUE THREAD

**Issue by Greendelwold** [GeekyAnts/NativeBase#2732]
got the following warning
![image](https://user-images.githubusercontent.com/47738574/60005566-587d0480-96a1-11e9-9886-308da437a12a.png)
can i still use this or is there any alternative?

**Comment by sankhadeeproy007** [comment]
We're in the process of removing `ListView` from nativebase. You can use it for now as it won't break anything. The next release will have this fix.

**Comment by PlabanJr** [comment]
`ListView` has been removed in [v2.13.0](https://github.com/GeekyAnts/NativeBase/releases/tag/v2.13.0). So closing the issue!

**Comment by PlabanJr** [comment]
`ListView` has been removed in [v2.13.0](https://github.com/GeekyAnts/NativeBase/releases/tag/v2.13.0). So closing the issue!
