### ISSUE TITLE
Input Picker Resetting Input to First Option

### ISSUE THREAD

**Issue by aapav01** [GeekyAnts/NativeBase#2733]
**Input Picker Resetting Input to First Option,**
I Have a form in my App in which I have used 15 Picker and the First Two Picker work fine for me but when I try to change the selection of the 3rd Picker to other 11 pickers after that. They don't change their value from the first option,  It keeps resetting to the First Option of the Picker.item

[**My JS file:**](https://gist.github.com/aapav01/7f34e51ddd005c74c37c46e957d80794)

**Version Information:** 
>npm --version
6.4.1
>node --version
v10.15.3

"expo": "^33.0.0",
"expo-asset": "^5.0.0",
"expo-constants": "^5.0.0",
"expo-crypto": "~5.0.1",
"expo-font": "^5.0.0",
"expo-web-browser": "^5.0.0",
"native-base": "^2.12.1",
"react": "16.8.3",
"react-apollo": "^2.5.6",
"react-dom": "^16.8.6",
"react-native": "https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz",

**Expected behaviour**
Picker Input Should Change to Value to the Selected Value

**Actual behaviour**
Picker Input Resetting to First/Default Option
[but the state is updated to the selected but Picker is value show the first option]

**Q.** Is the bug present in both iOS and Android or in any one of them?
**Ans**: I have an Android device so, I have only tested it on the Android (REAL DEVICE using Expo App on localhost)

**Comment by sankhadeeproy007** [comment]
We're using the native picker from android as our picker component. Can you try to see if it works as expected in the Picker component from `react-native`?

**Comment by aapav01** [comment]
No, it didnt work... So you mean to say that react-native itself has this bug ??

**Comment by sankhadeeproy007** [comment]
Yes.
