### ISSUE TITLE
how to toggle picker visibility from diff component

### ISSUE THREAD

**Issue by AbanoubNassem** [GeekyAnts/NativeBase#2734]
## I have gone through these following points
- [x]   Check latest documentation: https://docs.nativebase.io/
- [x]   Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x]   Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [x]   Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink

## Issue Description
I can't toggle the `Picker` visibility through different component , say `onButtonPress`, I have tried using `ref` so I can access the `_setModalVisible` method , but I can't access it , is there anyway I can achieve this?

**Comment by sankhadeeproy007** [comment]
The functionality you mention here is not the default behaviour for pickers and hence isn't a part of this library. And since we're using the native picker for android, it won't work on android anyway.
So I'd suggest that you do the implementation yourself.
