### ISSUE TITLE
How to pass props  in tabs ?

### ISSUE THREAD

**Issue by tinpt123** [GeekyAnts/NativeBase#2735]
hello everyone,
i have a TextInput in tab1 and i want to receive that value in tab2.
What can i do ?
Thanks.

**Comment by sankhadeeproy007** [comment]
The tab content is independent of the tab headers. You can use local setstate to use the value.
Please ask such questions in stackoverflow, we only keep track of issues here.

**Comment by SahilPrabhakar7** [comment]
I passed props like this

**` <Tab 
heading="Pending" >
<Tab1
 props={this.props} />
 </Tab>`**

and  if you want to access props inside Tab1 call props like this 

**`this.props.props`**
