### ISSUE TITLE
Input Component doesn't support React useRef Hook

### ISSUE THREAD

**Issue by agilitehub** [GeekyAnts/NativeBase#2736]
### Environment:
- React Native v0.59.9
- NativBase v2.12.1
- Xcode v10.2.1 (10E1001)

### Expected behaviour
Using useRef hook from React, one can get a handle on a field to execute focus(). As per React's Docs - https://reactjs.org/docs/hooks-reference.html#useref

Example:

```javascript
import React, { useRef } from 'react'

function TextInputWithFocusButton() {
  const inputEl = useRef(null);
  const onButtonClick = () => {
    // `current` points to the mounted text input element
    inputEl.current.focus();
  };
  return (
    <>
      <input ref={inputEl} type="text" />
      <button onClick={onButtonClick}>Focus the input</button>
    </>
  );
}
```

### Actual behaviour
When attempting the above logic on a NativeBase input field, an error is returned:

> null is not an object (evaluating 'inputEl.current.focus')

### Steps to reproduce
```javascript
import React, { useRef } from 'react'
import { Form, Item, Label, Input, Button, Icon, Text } from 'native-base'
import { View } from 'react-native'

export default function TestFocus () {
  const testRef = useRef(null)

  function handleFocus () {
    testRef.current.focus()
  }

  return (
    <View >
      <Form>
        <Item floatingLabel>
          <Label>Focus Field</Label>
          <Input
            ref={testRef}
            onChangeText={handleFocus}
          />
        </Item>
        <Button success iconLeft onPress={handleFocus}>
          <Icon name='checkmark-circle-outline' />
          <Text>Test Focus</Text>
        </Button>
      </Form>
    </View>
  )
}
```

<img width="876" alt="image" src="https://user-images.githubusercontent.com/22942939/60317424-53ed7000-996f-11e9-807c-7752f7ccb228.png">

### Is the bug present in both iOS and Android or in any one of them?
Only tested with iOS but most likely with Android as well

**Comment by artykr** [comment]
As per Native Base documentation, you have to use a function for the `ref` property instead of a variable (see https://docs.nativebase.io/Components.html#ref-components-headref). But the `c` variable in that example is not compatible with `MutableRefObject<any>` type of the value returned by `useRef` hook. So, instead of `current` property, it has a `_root` property. The bottom line is if you're not using TypeScript the example in the docs should work perfectly fine:
```
let inputElement = useRef(null);

useEffect((): void => {
    inputElement._root.focus();
});

...

<Input
  ref={(input): void => {
    inputElement = input;
  }}
/>
```

So the actual request here from my perspective is to make `input` compatible with `MutableRefObject<any>`

**Comment by axeljeremy7** [comment]
For Android 10, I have to use:
```inputElement.current.focus() ```
Haven't test in iOS

**Comment by basaksilasanli** [comment]
i have the same problem. is any solution?

**Comment by jericopulvera** [comment]
I had to use React.useState() instead.

```
function SignInScreen() {
    const [passwordInputRef, setPasswordInputRef] = React.useState(null)

    return (
        <Form>
            <Item floatingLabel>
            <Label>Email</Label>
            <Input
                onSubmitEditing={() => {
                    passwordInputRef._root.focus()
                }}
            />
            </Item>
            <Item floatingLabel>
            <Label>Password</Label>
            <Input
                getRef={(c) => setPasswordInputRef(c)}
            />
            </Item>
        </Form> 
    )
}

export default SignInScreen
```

**Comment by aidankinzett** [comment]
> I had to use React.useState() instead.
> 
> ```
> function SignInScreen() {
>     const [passwordInputRef, setPasswordInputRef] = React.useState(null)
> 
>     return (
>         <Form>
>             <Item floatingLabel>
>             <Label>Email</Label>
>             <Input
>                 onSubmitEditing={() => {
>                     passwordInputRef._root.focus()
>                 }}
>             />
>             </Item>
>             <Item floatingLabel>
>             <Label>Password</Label>
>             <Input
>                 getRef={(c) => setPasswordInputRef(c)}
>             />
>             </Item>
>         </Form> 
>     )
> }
> 
> export default SignInScreen
> ```

this worked for me except I had to use `ref` instead of `getRef`

**Comment by snoop24** [comment]
> As per Native Base documentation, you have to use a function for the `ref` property instead of a variable (see https://docs.nativebase.io/Components.html#ref-components-headref). But the `c` variable in that example is not compatible with `MutableRefObject<any>` type of the value returned by `useRef` hook. So, instead of `current` property, it has a `_root` property. The bottom line is if you're not using TypeScript the example in the docs should work perfectly fine:
> 
> ```
> let inputElement = useRef(null);
> 
> useEffect((): void => {
>     inputElement._root.focus();
> });
> 
> ...
> 
> <Input
>   ref={(input): void => {
>     inputElement = input;
>   }}
> />
> ```
> 
> So the actual request here from my perspective is to make `input` compatible with `MutableRefObject<any>`

Is that working for anyone? (for me is not)

**Comment by hanykumar** [comment]
Hi @agilitehub , update to latest Native-base v2.13.14 . Let us know if the issue still persists. Closing for now.

```
const inputEl = useRef(null);

const onButtonClick = () => {
    inputEl.current._root.focus();
  };
```

```
<Item>
     <Label>Username</Label>
     <Input ref={inputEl} onChangeText={onButtonClick} />
</Item>
<Button onPress={onButtonClick}>
    <Text>Button to focus on Input</Text>
</Button>
```

**Comment by schematis** [comment]
I'm using the latest version of NativeBase and am experiencing this issue as well. I've tried various approaches using the `useRef(null)` hook and none of them work. Currently using `getRef` and setting them as variables directly.

**Comment by MuhammadJaveedNazeerTR** [comment]
Need to Import useRef from react.

**Comment by mzu** [comment]
Using `useRef()` is still not working in version `2.15.2`. I've tried the solution outlined by @hanykumar and it didn't work for me either. `current` gets never set.

**Comment by okeybond** [comment]
> Using `useRef()` is still not working in version `2.15.2`. I've tried the solution outlined by @hanykumar and it didn't work for me either. `current` gets never set.

same here too

**Comment by Satyam-code143** [comment]
@mzu  Did you get any solution for the same?

**Comment by thekingrenz23** [comment]
This should be re opened still not working

**Comment by AbdElRahmanMostafa1** [comment]
Same problem here is there any solution??

**Comment by Alex1899** [comment]
same issue here

**Comment by xgenem** [comment]
I can access `.focus()` via
```
const emailRef = useRef<IInputProps>()
// or
const emailRef = useRef<any>()

// ...
<Input ref={emailRef} />
```

However I cannot get the input's value via
```
emailRef.current.value
```

**Comment by hotaryuzaki** [comment]
in version 2 i can do this with my input
```
onSubmitEditing={() => {
  this.inputs["password"]._root.focus();
}
```

how to create same function in version 3??
