### ISSUE TITLE
Header title not centered when using left icon

### ISSUE THREAD

**Issue by NoR3s** [GeekyAnts/NativeBase#2739]
I have a small issue im using a drawer navigation where i can click and open the drawer. if i add a title. The title is not centered im using expo iphone 7 device.

```
            <Header style={{backgroundColor:'#3a455c',height:80,borderBottomColor:'#757575'}}>
                <Left>
                    <Icon name="md-menu" onPress={() =>this.props.navigation.openDrawer()} style={{color:'white'}} />
                </Left>
                <Body>
                    <Text>My title</Text>
                </Body>
```
If i remove the <Left> then its centered anyway how to fix this

![WhatsApp Image 2019-07-03 at 12 30 00(1)](https://user-images.githubusercontent.com/20150161/60584960-dec6d400-9d8e-11e9-9757-cf0b068d8366.jpeg)

**Comment by kentrh** [comment]
Maybe not completely on topic here, but for anyone else trying to get rid of truncated titles in the header, I solved it by putting `style={{ flex: 2 }}` on the `body` tag. Also all `<Left>`, `<Body>` and `Right` is required, but `<Right>` can just be left empty.
