### ISSUE TITLE
Update to react-native-vector-icons ~3.0.0

### ISSUE THREAD

**Issue by brentvatne** [GeekyAnts/NativeBase#274]
See title! :)

**Comment by sanketsahusoft** [comment]
@brentvatne Thanks for raising the issue. We are evaluating it. We are thinking of providing a uniform API on top of vector icons which maps to platform specific equivalent icons. Thoughts?

**Comment by jamesholcomb** [comment]
The way React Native Elements handles this is nice.  Use a peer dependency, specify 'type' as an optional `<Icon/>` prop.  If no type is specified, use the Theme configuration.

https://github.com/react-native-community/react-native-elements#icons--icon-buttons

**Comment by himanshu-satija** [comment]
Upgraded react-native-vector-icons to ~3.0.0. Will release with next version.
