### ISSUE TITLE
Unable to resolve module does not exist in the Haste module map when publishing with expo

### ISSUE THREAD

**Issue by matanume** [GeekyAnts/NativeBase#2741]
## Issue Description
The project work fine in dev mode when I run expo start.
When I try to publish with expo publish or expo build:[android/ios] the error occur.

### node, npm, react-native, react and native-base version, expo version if used, xcode version
node version = 8.11.3
react-native-cli: 2.0.1
react-native: 0.59.8
native-base version = 2.12.1
expo version = 33.0.7
expo-cli version = 2.21.2

### Expected behaviour
build successfully
publish to channel successfully

### Actual behaviour
Get the error
```
Unable to resolve module `src/../native-base-theme/variables/commonColor` from `/Users/myname/Desktop/ReActs/native/myproject/src/App.js`: Module `src/../native-base-theme/variables/commonColor` does not exist in the Haste module map

This might be related to https://github.com/facebook/react-native/issues/4968
To resolve try the following:
  1. Clear watchman watches: `watchman watch-del-all`.
  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
  3. Reset Metro Bundler cache: `rm -rf /tmp/metro-bundler-cache-*` or `npm start -- --reset-cache`.
  4. Remove haste cache: `rm -rf /tmp/haste-map-react-native-packager-*`.
Unable to resolve "src/../native-base-theme/variables/commonColor" from "src/App.js"
Failed building JavaScript bundle.
::ffff:127.0.0.1 - - [03/Jul/2019:13:55:07 +0000] "GET /node_modules/expo/AppEntry.bundle?dev=false&minify=true&hot=false&platform=ios HTTP/1.1" 500 - "-" "axios/0.19.0-beta.1"
Cannot read property 'status' of undefined
TypeError: Cannot read property 'status' of undefined
    at _getForPlatformAsync (/@expo/xdl@55.0.14/src/Project.js:163:70)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
```

### Is the bug present in both iOS and Android or in any one of them?
Both

### Any other additional info which would help us debug the issue quicker.
Bug is occur only in publish mode (--no-dev --minify)

**Comment by matanume** [comment]
It's about the babel.

**Comment by vrishab-cashfree** [comment]
Could you please explain it a bit more, I too am facing this issue.

**Comment by rosnaib11** [comment]
@matanume what did you do to fix?
