### ISSUE TITLE
Metro from RN 0.60.0 warns that rnpm config is deprecated and will stop working in the next release

### ISSUE THREAD

**Issue by RohanTalip** [GeekyAnts/NativeBase#2742]
This shows up when running the Metro Bundler from React Native v0.60.0:
```
warn The following packages use deprecated "rnpm" config that will stop working from next release:
  - native-base: https://github.com/GeekyAnts/NativeBase#readme
```

See https://github.com/react-native-community/cli/blob/master/docs/configuration.md#migration-guide

I see that rnpm is mentioned twice in package.json but I suspect it's not really being used.

**Comment by msqar** [comment]
Any update on this? I found the same thing after doing npm install and updating to some latest dependencies.

**Comment by jim20june1989** [comment]
I am over a react native project and have met with similar issue.

**> warn The following packages use deprecated "rnpm" config that will stop working from next release:
>   - native-base: https://github.com/GeekyAnts/NativeBase#readme
>   - react-native-google-signin: https://github.com/react-native-community/react-native-google-signin
>   - react-native-maps: https://github.com/airbnb/react-native-maps#readme
>   - react-native-video: https://github.com/react-native-community/react-native-video#readme
>**

**Comment by msqar** [comment]
@jim20june1989 yes, basically you have to check each dependency repo and see if they released a version where they don't use nrpm anymore. It sucks, i know.

**Comment by msqar** [comment]
I'm waiting on NativeBase to see if they will be releasing a hotfix soon.

**Comment by jim20june1989** [comment]
@msqar thanks.
Well then let's hope they sort this out as it's just ridiculous how things have turned after latest release by firebase and google play services. My project feels like mess now.

**Comment by sankhadeeproy007** [comment]
Here's a PR fixing the issue
https://github.com/GeekyAnts/NativeBase/pull/2749
We'll probably to test it, anybody volunteering?
@RohanTalip @jim20june1989 @msqar

**Comment by RohanTalip** [comment]
I made the same changes as PR #2749 in my node_modules/native-base/ directory.

I restarted the Metro Bundler process and no longer got the warning about the rnpm config in native-base.  I was also able to start my Vue Native app using Native Base sucessfully from Xcode.

So, it works for me 😄!

**Comment by msqar** [comment]
Agree, it works. Can we merge this PR so i can update native-base ? Thanks :)

**Comment by sankhadeeproy007** [comment]
Has been merged, the next release won't be out till the end of the coming week.
Till then, please point your package.json to the master branch.

**Comment by msqar** [comment]
@sanketsahusoft ah nvm :D i can wait 1 week. Not in a rush. Thanks again.

**Comment by rolignu2** [comment]
the next release with the fix is already ?

**Comment by dl-husky73** [comment]
Any updates on when this will be released?

**Comment by asdword** [comment]
creating a "react-native.config.js" at the root of the project

**package.json** entry:
```

{
  "rnpm": {
    "ios": {},
    "android": {},
    "assets": ["./path-to-assets"],
    "plugin": "./path-to-commands.js"
  }
}
```
becomes **react-native.config.js**
```
module.exports = {
  project: {
    ios: {},
    android: {}, // grouped into "project"
  },
  assets: ['./path-to-assets'], // stays the same
  commands: require('./path-to-commands.js'), // formerly "plugin", returns an array of commands
};
```
@asdword

**Comment by sankhadeeproy007** [comment]
Fixed in 2.13.0

**Comment by fullstact69** [comment]
I have the same issues in react-native 0.60.04.
But I can't find rnpm key in package.json.

**Comment by msqar** [comment]
@sankhadeeproy007 absolutely true! it's finally fixed. Thanks everyone for your job! :)

**Comment by adrianpfeiffer** [comment]
Hi I´m just a few months into react-native, trying to implement custom fonts into my app. It worked perfectly with rnpm but as I shouldn´t use it any more I´m not figuring out how to use cf. 
Can anyone here please write down the few steps? I´m sure I´m just missing a small part.. Thanks!
