### ISSUE TITLE
Badge with text

### ISSUE THREAD

**Issue by mateusreis** [GeekyAnts/NativeBase#275]
How can I reproduce a badge with a text like on docs page:

http://nativebase.io/docs/v0.5.9/components#badge

I want to achieve something like this:

`<Text><Badge info>2</Badge> Guitars</Text>`

Thanks,

**Comment by sospedra** [comment]
You have to think as the opposite. The Text is inside the Badge.

    <Badge primary>
       <Icon name="ios-star" style={{ fontSize: 12, color: '#fff', lineHeight: 19 }} />
       <Text>Guitard</Text>
    </Badge>

**Comment by mateusreis** [comment]
This put the text "inside" the badge. I just want the text outside. Like this:

http://imgur.com/a/SnMvq

**Comment by SupriyaKalghatgi** [comment]
@mateusreis Wrap `Badge` and `Text` in `View` and include flex

```
<View style={{ flex: 1, flexDirection: 'row' }}>
    <Badge>2</Badge>
    <Text style={{ paddingLeft: 10 }}>Default</Text>
</View>
```
