### ISSUE TITLE
i want to change picker theme by styleprovider because Style, itemStyle doesn't work 

### ISSUE THREAD

**Issue by sootood** [GeekyAnts/NativeBase#2751]
i want to change picker theme by styleprovider because Style, itemStyle doesn't work.
i ejected native-base-them and changed some item in pickerThem but picker style didn't change
please help me

**Comment by Srishti-Sharma** [comment]
Please follow the issue template and create a new issue. Also attach a reproducible code snippet _`(preferably snack)`_
