### ISSUE TITLE
Before onChangeTab method

### ISSUE THREAD

**Issue by innominat3** [GeekyAnts/NativeBase#2753]
## I have gone through these following points
- [x]   Check latest documentation: https://docs.nativebase.io/
- [x]   Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x]   Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [x]   Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [x]   For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- [x]   For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

## Issue Description
Is there any method or workaround that allows me to handle touch events BEFORE tab changes? The 'onChangeTab' method fires AFTER the view changed to the selected tab. Thanks!

**Comment by sankhadeeproy007** [comment]
We're using [this](https://github.com/ptomasroos/react-native-scrollable-tab-view) package as our base for tabs and it doesn't support the feature. 
So it'd be best fork it and implement it yourself.
