### ISSUE TITLE
iOS: text and textarea inputs dont line up correctly when the parent component uses padding

### ISSUE THREAD

**Issue by appjitsu** [GeekyAnts/NativeBase#2758]
## I have gone through these following points
- [x]   Check latest documentation: https://docs.nativebase.io/
- [x]   Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x]   Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [x]   Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [x]   For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- [x]   For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

## Issue Description
text and textarea inputs dont line up correctly when a parent component uses padding

![Screen Shot 2019-07-09 at 11 27 58 PM](https://user-images.githubusercontent.com/10903600/60940734-2626f600-a2a2-11e9-863b-cb9fad01fad7.png)

1. right side of picker is all the way to right side of the screen (tried changing the width to no avail)
2. left side of the text input is indented

### node, npm, react-native, react and native-base version, expo version if used, xcode version
```
Expo CLI 2.21.2 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
      Yarn: 1.16.0 - ~/.yarn/bin/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v10.16.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^33.0.0 => 33.0.7 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz => 0.59.8 
      react-navigation: ^3.11.0 => 3.11.0 
    npmGlobalPackages:
      expo-cli: 2.21.2
```

```
  "native-base": "^2.12.1",
```

### Expected behaviour
inputs line up correctly

### Actual behaviour
inputs dont line up correctly

### Steps to reproduce
```
  <Container style={styles.mainContainer}>
      <Form>
        <Item picker>
          <Picker
            mode="dropdown"
            iosIcon={<Icon name="arrow-down" />}
            textStyle={styles.text}
            itemTextStyle={styles.text}
            placeholderStyle={styles.text}
            placeholder="Select a Category"
          >
            <Picker.Item label="Wallet" value="key0" />
            <Picker.Item label="ATM Card" value="key1" />
            <Picker.Item label="Debit Card" value="key2" />
            <Picker.Item label="Credit Card" value="key3" />
            <Picker.Item label="Net Banking" value="key4" />
          </Picker>
        </Item>
        <Item stackedLabel>
          <Label style={styles.text}>Title</Label>
          <Input
            style={styles.text}
            autoCorrect={false}
            returnKeyType="done"
          />
        </Item>
        <Textarea
          rowSpan={10}
          bordered
          placeholder="Description"
          style={styles.text}
        />
      </Form>
    </Container>
```

```
const styles = {
  mainContainer: {
    padding: 20,
  },
  text: {
    fontFamily: 'Roboto',
    fontSize: 20,
  }
};
```

**Comment by appjitsu** [comment]
also, the textarea is ignoring styles. the text that you type in and the placeholder text should be fontSize: 20, but it remains small

```
    <Textarea
          rowSpan={10}
          bordered
          placeholder="Description"
          onChangeText={handleChange('description')}
          placeholderStyle={styles.text}
          textStyle={styles.text}
          style={styles.text}
        />
```

**Comment by hanykumar** [comment]
Hi @appjitsu , you should use `last` in `<Item stackedLabel last>...</Item>` for alignment.

![Screenshot 2020-03-17 at 10 20 35 AM](https://user-images.githubusercontent.com/15860517/76823070-fa98da00-6838-11ea-8126-57b68b77adb3.png)

If you want to style `Textarea`, just use `style`. You don't need to use `placeholderStyle` or `textStyle`.

**Comment by hanykumar** [comment]
Hi @appjitsu , closing this now due to inactivity. Let us know if the issue still persists.
