### ISSUE TITLE
CardItems border?

### ISSUE THREAD

**Issue by sospedra** [GeekyAnts/NativeBase#276]
Can I disable or change the color of the CardItems borders?
They're pretty annoying :)

For example, what if I don't want the divider between the header and the Image?

![image](https://cloud.githubusercontent.com/assets/3116899/20101693/5ee95804-a5c3-11e6-89b8-4ec91c0d82d6.png)

**Comment by sospedra** [comment]
Note: I can easly make a PR if this is not currently supported ;)

**Comment by himanshu-satija** [comment]
I know it's very late now 😅. 

You can pass the style property `borderColor: 'transparent'` with the CardItems or you can change `listBorderColor` property in your theme file if you want to apply it to all the CardItem components.
