### ISSUE TITLE
Multi Picker Component

### ISSUE THREAD

**Issue by jeremiahk** [GeekyAnts/NativeBase#2761]
##  Issue Description
Currently the picker component does not support multi select. This is a common use case. See [#1813](https://github.com/GeekyAnts/NativeBase/issues/1813) and [#2282](https://github.com/GeekyAnts/NativeBase/issues/2282). Here are my thoughts on how this should be implemented. Please let me know if there is a desire to have this done. 

### Behavior
On iOS the multipicker would look and operate very similar to the current picker except the user could select multiple values. onValueChange would not be called until the user closes the screen. 

There are a couple of options for Android. It could use a similar style as the current iOS picker. The react native picker does not allow multiple selections. So we would just launch a new screen with all options. 

There is also a library like [react-native-dialogs](https://github.com/aakashns/react-native-dialogs) to build a more Android like dialog. I believe this is not a valid option as it would break compatibility with Expo.

### Implementation
This would be a new component. It would not be a property on the current picker. A boolean property would make sense on iOS, but the Android UI for the multipicker would be drastically different than the current UI. The logic would be modeled on the current iOS picker. 

Please feel free to offer suggestions and things to think about. There may be a reason this hasn't been implemented yet.

**Comment by williamsiii** [comment]
Hello, Jeremiahk.
I very much desire to have this done) Totally agree on iOS implementation, and Android implementation should look pretty much the same

**Comment by nguyenrio18** [comment]
+1000 !!!

**Comment by thisLexic** [comment]
Any updates regarding a multi select component?
