### ISSUE TITLE
GeekyAnts forked version of react-native-keyboard-aware-scroll-view triggers ListView deprecation warning

### ISSUE THREAD

**Issue by alterx** [GeekyAnts/NativeBase#2763]
## I have gone through these following points
- [x]   Check latest documentation: https://docs.nativebase.io/
- [x]   Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x]   Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [x]   Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [x]   For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- [x]   For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

## Issue Description

There's a warning regarding the deprecation of `ListView` which the package `react-native-keyboard-aware-scroll-view` uses. Digging into the module, it looks like you're using a fork of the original lib but it's still using `ListView` (see https://github.com/GeekyAnts/react-native-keyboard-aware-scroll-view/blob/f4805f254d6cc8e3329f5fb224944401f66655db/lib/KeyboardAwareListView.js#L5)

### node, npm, react-native, react and native-base version, expo version if used, xcode version

Node: 10
react: 16.8.3
react-native: Expo 33 (https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz) 
Expo: 33.0.0
native-base: 2.8.1

### Expected behaviour
App should run without warnings.

### Actual behaviour

There's a warning regarding the deprecation of `ListView` 

```
Warning: ListView is deprecated and will be removed in a future release. See https://fb.me/nolistview for more information
- node_modules/expo/build/environment/muteWarnings.fx.js:27:24 in error
- node_modules/react-native/node_modules/fbjs/lib/warning.js:30:18 in printWarning
- node_modules/react-native/node_modules/fbjs/lib/warning.js:51:23 in <unknown>
- node_modules/react-native/Libraries/Utilities/warnOnce.js:29:10 in warnOnce
- node_modules/react-native/Libraries/react-native/react-native-implementation.js:70:6 in ListView
- node_modules/react-native-keyboard-aware-scroll-view/lib/KeyboardAwareListView.js:6:38 in <unknown>
- node_modules/metro/src/lib/polyfills/require.js:331:6 in loadModuleImplementation
- node_modules/react-native-keyboard-aware-scroll-view/index.js:5:0 in <unknown>
- node_modules/metro/src/lib/polyfills/require.js:331:6 in loadModuleImplementation
- node_modules/native-base/dist/src/basic/Content.js:1:1063 in <unknown>
- node_modules/metro/src/lib/polyfills/require.js:331:6 in loadModuleImplementation
- node_modules/native-base/dist/src/index.js:1:2715 in <unknown>
- node_modules/metro/src/lib/polyfills/require.js:331:6 in loadModuleImplementation
* src/boot/setup.js:3:0 in <unknown>
- node_modules/metro/src/lib/polyfills/require.js:331:6 in loadModuleImplementation
* App.js:2:0 in <unknown>
- node_modules/metro/src/lib/polyfills/require.js:331:6 in loadModuleImplementation
- node_modules/expo/AppEntry.js:4:0 in <unknown>
- node_modules/metro/src/lib/polyfills/require.js:331:6 in loadModuleImplementation
- node_modules/metro/src/lib/polyfills/require.js:197:45 in guardedLoadModule
* null:null in global code
```

### Steps to reproduce

This is the line that's causing the issue
https://github.com/GeekyAnts/react-native-keyboard-aware-scroll-view/blob/master/lib/KeyboardAwareListView.js#L5

### Is the bug present in both iOS and Android or in any one of them?
I have only tested it in iOS but it's probably on both.

**Comment by sankhadeeproy007** [comment]
Fixed in 2.13.0
