### ISSUE TITLE
Toast is not always showing in RN0.59.9

### ISSUE THREAD

**Issue by mjm918** [GeekyAnts/NativeBase#2764]
Toast was working fine. However, recently I upgraded to RN0.59.9 and it does not show every time. Sometimes it works fine and sometimes it does not. I am aware of that if the debugger is on, toast may not work as expected. But in release mode, it does not work perfectly also

**Comment by baragatti** [comment]
I'm having this issue too using RN 0.59.10. Sometimes it delays a lot to show and stay for waaay less than the duration before disappearing.

**Comment by JackofD** [comment]
I have been experiencing the same thing. My toast waits a while, and then flashes in and out.
Although, it works in other places. The behaviour has become very inconsistent.

**Comment by Ding-Fan** [comment]
I met the same issue, I use `Toast.show` in a `useEffect` but it delayed too long that drives me crazy...

```js
  useEffect(() => {
    console.log("Hey I'm in useEffect!");
    Toast.show({
      text: 'Wrong password!',
      buttonText: 'Okay',
      duration: 3000,
      type: 'warning',
    });
  }, [errors]);
```

**Comment by Ding-Fan** [comment]
Looks like it's because my laptop and my android phone are not at the same time. I manually adjusted the time of my android phone, the delay seems shortened...

**Comment by hanykumar** [comment]
Hi @mjm918 , please provide minimal code reproduction on snack for the same. 
Thanks

**Comment by mjm918** [comment]
I created this issue a year ago. I didn't receive any help back then so decided to stop using it. So sorry I don't have any code for this
