### ISSUE TITLE
DatePicker: Is there a way to make the user able to pick time (hour and minutes) ?

### ISSUE THREAD

**Issue by pedroomedicina** [GeekyAnts/NativeBase#2766]
## I have gone through these following points
- [x]   Check latest documentation: https://docs.nativebase.io/
- [x]   Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x]   Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [x]   Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- []   For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- []   For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

### node, npm, react-native, react and native-base version, expo version if used, xcode version
node: v12.1.0, npm: v6.9.0, react: 16.8.3, native-base: 2.12.1, expo: 2.21.1

### Expected behaviour
Isn't a real issue
### Actual behaviour
Isn't a real issue
### Steps to reproduce
Isn't a real issue

### Is the bug present in both iOS and Android or in any one of them?
Isn't a real issue
### Any other additional info which would help us debug the issue quicker.

Really sorry if this issue doesn't fit the rules, just wanted to make clear something I don't see in the docs but may exist as a feature of the datepicker component.

**Comment by VnsCode** [comment]
I haven't tried this with native-base, but there is a nice-package named `react-native-modal-datetime-picker` that I use in the prod app, and it's pretty easy to use. Link: https://github.com/mmazzarolo/react-native-modal-datetime-picker

**Comment by pedroomedicina** [comment]
Closing this, since I've followed your suggestion.
