### ISSUE TITLE
Header too tall in iphone x ? 

### ISSUE THREAD

**Issue by ansarikhurshid786** [GeekyAnts/NativeBase#2767]
I seen you same issue but no solution for tall header in iphone x. 

Without safearea my application looks weired so i need to add safearea. 

can anyone give me workaround to reduce height of header ?

**Comment by jannikbuschke** [comment]
My Header is also to tall in iPhone X using SafeArea:
![image](https://user-images.githubusercontent.com/5894881/65819953-62278280-e223-11e9-9555-d2c5142d6cab.png)

**Comment by ansarikhurshid786** [comment]
exactly i am getting same issue

**Comment by ansarikhurshid786** [comment]
Today i update latest version to ("native-base": "^2.13.12"). it has same issue.

**Comment by hanykumar** [comment]
Hi @ansarikhurshid786 , we have fixed this issue in master branch.
 same issue as #3095
