### ISSUE TITLE
Tabs border

### ISSUE THREAD

**Issue by acamenhas** [GeekyAnts/NativeBase#277]
Hi all,

I've installed the Android Kitchen Sink app and i noticed that the tabs have the same color of the header but it have a thin line/border that separates both. (on the emulator i cant see that)

Is there any way to remove that line/border?

The original component dont have it:
https://material.google.com/components/tabs.html#tabs-usage

**Comment by SupriyaKalghatgi** [comment]
@acamenhas Check implementation of [Tabs](https://github.com/GeekyAnts/NativeBase-KitchenSink/blob/master/js/components/tabs/index.js) in [NativeBase-KitchenSink](https://github.com/GeekyAnts/NativeBase-KitchenSink)

**Comment by acamenhas** [comment]
I've tested on Android and worked well !!!
Thank you!
