### ISSUE TITLE
High Vulnerability in dependancy lodash

### ISSUE THREAD

**Issue by craig95** [GeekyAnts/NativeBase#2773]
## I have gone through these following points
- [X]   Check latest documentation: https://docs.nativebase.io/
- [X]   Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [X]   Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [X]   Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [ ]   For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- [ ]   For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

## Issue Description

[High vulnerability](https://npmjs.com/advisories/1065) in dependency lodash.js, has been discovered. 

### node, npm, react-native, react and native-base version, expo version if used, xcode version

node: 10.16.0
npm: 6.9.0
react: 16.8.3
native-base: 2.12.1

### Expected behaviour
No vulnerability

### Actual behaviour
High vulnerability in dependency lodash.js.

### Steps to reproduce

`npm install native-base`

### Is the bug present in both iOS and Android or in any one of them?
Both

### Any other additional info which would help us debug the issue quicker.
The dependency version of lodash now in native base 2.12.1 is 4.17.11, which >= 4.17.12 will fix. You can also consider changing the lodash version in package.json to "^4.17.12" which will prevent this issue in the future.

**Comment by m-deacon** [comment]
Here's the related issue on lodash's github: https://github.com/lodash/lodash/issues/4348
