### ISSUE TITLE
Picker throws warning

### ISSUE THREAD

**Issue by raminious** [GeekyAnts/NativeBase#278]
Hey guys
When I use Picker in my form react-native displays this warning

![image](https://cloud.githubusercontent.com/assets/334716/20118662/96b4f296-a61a-11e6-939a-b1f5ab4f40d0.png)

I'm using your sample Picker code without any change.

RN: 0.36.0
react: 15.3.2,
native-base: 0.5.13

Also I get this warning on iOS 10.1 (simulator) and not tested on Android yet

**Comment by SupriyaKalghatgi** [comment]
@raminious Are you rendering the Picker Items dynamically?

**Comment by raminious** [comment]
@SupriyaKalghatgi Yes!

**Comment by SupriyaKalghatgi** [comment]
@raminious Passing children to picker is mandatory. If you don't pass any children initially, the `this.state.items` becomes an empty array, which should never be.

Check issue [#288](https://github.com/GeekyAnts/NativeBase/issues/288)

**Comment by StephenStrickland** [comment]
@SupriyaKalghatgi is there a way to dynamically update the <Items/> within <Picker/>? Or am I stuck because of the datasource copy in PickerNB constructor?
