### ISSUE TITLE
v2.12.2 refers to FontAwesome5Pro

### ISSUE THREAD

**Issue by bodolsog** [GeekyAnts/NativeBase#2783]
v2.12.2 imports react-native-vector-icons/FontAwesome5Pro which breaks on Expo (probably all Expo versions) where package @expo/vector-icons override react-native-vector-icons.

v2.12.1 which has no FontAwesome5Pro import (only FontAwesome5) works.

Comment in other issue: https://github.com/GeekyAnts/NativeBase/issues/2731#issuecomment-512796306_

Quick solution: downgrade to v2.12.1.

**Comment by kocho** [comment]
Great, thanx for the fix! spend two hours installing these modules :')

**Comment by sgehrig** [comment]
This seems a rather critical issue to me because it breaks Expo builds in general. Any quick fix to be expected? 

Thanks everyone involved!

**Comment by sankhadeeproy007** [comment]
Hey, it was introduced by a recent PR which adds support for FontAwesome5Pro. Can you revert back to 2.12.1 for time being till we get it fixed.

**Comment by sgehrig** [comment]
@sankhadeeproy007: Yes, that's what we've done. So it's not a blocker for us at the moment, but still a high priority issue. Thanks for your quick response - much appreciated!

**Comment by xgenem** [comment]
Ran into the same trouble. Had to downgrade to v2.12.1 
Thank you for raising this up!

**Comment by jedney0901** [comment]
Getting the same issue, I have tried the solutions but can't seem to get it to work. I was originally on 2.11.1 so I am thinking its an issue somewhere else?

Any help would be appreciated.

```Unable to resolve "@expo/vector-icons/FontAwesome5Pro" from "node_modules/native-base/dist/src/basic/IconNB.js"```

```
  "dependencies": {
    "@expo/samples": "2.1.1",
    "@expo/vector-icons": "^10.0.0",
    "@react-native-firebase/app": "^0.0.4",
    "@redux-offline/redux-offline": "^2.5.1",
    "axios": "^0.18.0",
    "expo": "^33.0.0",
    "expo-font": "^5.0.1",
    "fb-watchman": "^2.0.0",
    "fetch-mock": "^7.3.0",
    "firebase": "^5.11.1",
    "lodash": "^4.17.11",
    "native-base": "^2.12.1",
    "prop-types": "^15.7.2",
    "react": "16.8.3",
    "react-native": "https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz",
    "react-native-gesture-handler": "^1.3.0",
    "react-native-screens": "^1.0.0-alpha.23",
    "react-native-svg": "^9.5.1",
    "react-native-vector-icons": "^6.6.0",
    "react-navigation": "^3.0.9",
    "react-redux": "^6.0.0",
    "redux": "^4.0.1",
    "redux-logger": "^3.0.6",
    "redux-mock-store": "^1.5.3",
    "redux-offline-queue": "^1.0.6",
    "redux-persist": "^5.10.0",
    "redux-promise-middleware": "^5.1.1",
    "redux-thunk": "^2.3.0",
    "uuid-v4": "^0.1.0"
  },
```

**Comment by jedney0901** [comment]
@xgenem `yarn remove native-base` `yarn install native-base@2.12.1` resolved it.

**Comment by syedjaffersathik** [comment]
Yes. It's worked for me too. 
If you are mac user then
npm remove native-base 
npm install native-base@2.12.1

**Comment by jqtruong** [comment]
@jedney0901 had the same problem until i (facepalmingly) removed the caret in `package.json` for `native-base`; ie.:

```
...
...
    "native-base": "2.12.1",
...
...
```

**Comment by luanccp** [comment]
> yarn install native-base@2.12.1

Works to me. But now we have to use `yarn add native-base@2.12.1`
`install` is not used anymore.

Thank you!

**Comment by xgenem** [comment]
$npm install native-base@2.12.1
    $yarn add native-base@2.12.2

I bet this problem should be resolved by now.

**Comment by krisnadiputra** [comment]
I ve encountered the same problem. By downgrading native-base to `2.12.1`, it works on my simulator but not when I publish it to expo default channel to test it on the real device on expo client. Anyone facing the same problem?
