### ISSUE TITLE
Icon does not align properly inside an <Item stackedLabel>

### ISSUE THREAD

**Issue by PositronicBrain** [GeekyAnts/NativeBase#2784]
When using an `Icon` component with the `stackedLabel` property as in the following, the icon is not inline with the rest of the `Item` content, but it's rendered on another line:
```
<Form>
  <Item stackedLabel>
    <Label> Time </Label>
    <Input />     
    <Icon name='time' />
  </Item>
</Form>
```
Omitting `stackedLabel` or using `inplaceLabel` everything renders as expected.

**Comment by abhiburk** [comment]
any update on this ?
