### ISSUE TITLE
[Regression] Icon family from theme is ignored

### ISSUE THREAD

**Issue by elivinsky** [GeekyAnts/NativeBase#2785]
## I have gone through these following points
- [x]   Check latest documentation: https://docs.nativebase.io/
- [x]   Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x]   Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [x]   Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [ ]   For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- [x]   For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

## Issue Description
A [recent commit](https://github.com/GeekyAnts/NativeBase/commit/de81ef2fb8bd056f85e7bbc78d957f3d5ab43337#diff-3fd8713c7fac5880d02c24b431eca322R38) has introduced a regression in IconNB where the iconFamily is not being retrieved from the theme context.

I'd love to make a PR on this but I'm not keen on the inner works on this library and I'll probablly mess up.

The mentioned commit introduced the following change:

From:
https://github.com/GeekyAnts/NativeBase/blob/7472ba36903654cbc7a07c3c7547bda54d4ef40b/src/basic/IconNB.js#L27-L31

To:
https://github.com/GeekyAnts/NativeBase/blob/de81ef2fb8bd056f85e7bbc78d957f3d5ab43337/src/basic/IconNB.js#L35-L40

The `let` on line 38 prevents `iconType` from being overridden with the icon font family from the theme.

**Comment by sankhadeeproy007** [comment]
Hey, thanks for pointing it out. We'll get it fixed soon.

**Comment by dl-husky73** [comment]
I am having this same issue, wondering if I should go back to 2.12.1 for a demo Tuesday or will this be fixed?

**Comment by sankhadeeproy007** [comment]
@dl-husky73 Would be safe to switch back to 2.12.1 for now.

**Comment by sankhadeeproy007** [comment]
Fixed in 2.13.0
