### ISSUE TITLE
Style property 'top' is not supported by native animated module

### ISSUE THREAD

**Issue by tosbaha** [GeekyAnts/NativeBase#2786]
## I have gone through these following points
- [x]   Check latest documentation: https://docs.nativebase.io/
- [x]   Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x]   Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [x]   Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- []   For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- []   For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

## Issue Description
I upgraded module to 2.12.2 but now my Form crashes all the time with `Style property 'top' is not supported by native animated module` error. If Item has `floatingLabel` property it crashes.

### node, npm, react-native, react and native-base version, expo version if used, xcode version

- Node v10.16.0
- npm 6.9.0
- native base 2.12.2
- react v16.8.3
- react-native  v0.59.9

### Expected behaviour
Item floatingLabel shouldn't crash
### Actual behaviour
Item floatingLabel crashes
### Steps to reproduce
Here is the snippet directly from documentation that crashes with `Style property 'top' is not supported by native animated module`

```jsx
 <Form>
	<Item floatingLabel>
	  <Label>Username</Label>
	  <Input />
	</Item>
	<Item floatingLabel last>
	  <Label>Password</Label>
	  <Input />
	</Item>
</Form>
```

### Is the bug present in both iOS and Android or in any one of them?
I only tested Android
### Any other additional info which would help us debug the issue quicker.
None.

**Comment by JoseCarlosNS** [comment]
OMG I was JUST coming here to report this EXACT same bug! Everything for me is the same except I'm using `react-native@0.60.3` and `native-base@2.12.1`.

Also just to add insult to injury: **the `inlineLabel` property does not work and behaves like `fixedLabel`**

**Comment by harryfinn** [comment]
Am also getting this, Android only impacted (iOS is fine) RN `v0.60.4`, seems localised to `Item.js` component

**Comment by ericanthonywu** [comment]
should we downgrading to use this floating label?? will they fix this bug?

**Comment by ericanthonywu** [comment]
should we downgrading RN version to use this floating label? any other alternatives??

**Comment by Srishti-Sharma** [comment]
This PR fixes the issue #2794

**Comment by mayupat13** [comment]
same issue for me same  as @JoseCarlosNS

**Comment by LordHydra1** [comment]
Hi @Srishti-Sharma I applied your changes in my Item.js file...but I still have the same problem...there are something else to do in addition to edit and save the Item.js? How I can integrate the changes in my project without waiting your PR? There is some sort of command or script to use for build the new edited node-modules file?

**Comment by johnny32** [comment]
Same here as @LordHydra1

**Comment by harryfinn** [comment]
@LordHydra1 & @johnny32 - if you want to use the changes in the above PR, you should be able to install the package directly from GH using the following command: 

` yarn add GeekyAnts/NativeBase#srishti/Item_floatingLabel_fix` 

or the following if using NPM

`npm install GeekyAnts/NativeBase#srishti/Item_floatingLabel_fix`

**Comment by JoseCarlosNS** [comment]
Is the `inlineLabel` problem addressed too on that PR? I know this should probably be on an issue on its own, but since we're here...

**Comment by johnny32** [comment]
What I meant is that, even with the PR changes, the error still happens to me.

**Comment by uday5162** [comment]
![image](https://user-images.githubusercontent.com/20751649/61631941-51014900-aca9-11e9-8f16-3d3774de6fe3.png)

getting this error after commenting as suggested in PR for floatingLabel. I think there is some problem with top prop in Animated.View compoent

**Comment by LordHydra1** [comment]
same as @uday5162...i tryed updating my native-base package but still have the same problem....

**Comment by mubashiralisiddiqui** [comment]
same issue on IOS and android

**Comment by blankonn** [comment]
seems like reverting to ```native-base@2.12.1``` remove the warning and make the floating labels working again.
only tested on android.

**Comment by JoseCarlosNS** [comment]
@blankonn Are you sure? Because I'm using `native-base@2.12.1` with `react-native@0.60.4` and `floatingLabel` and `inlineLabel` are both not working.

**Comment by mubashiralisiddiqui** [comment]
I am using native base@2.12.1 with react-native-@0.59.9 I am working on a
project more than a month with same version but it suddenly
give this error while
I have found that the prop floating label causing this issue

**Comment by johnny32** [comment]
I'm also using native-base@2.12.1 and react-native@0.59.10, and it works for me.

**Comment by blankonn** [comment]
@JoseCarlosNS that's weird, I am using the very same react-native version as you and it is running without the error, here's my package.json [https://pastebin.com/T5JMPh34](https://pastebin.com/T5JMPh34)

**Comment by mubashiralisiddiqui** [comment]
> https://pastebin.com/T5JMPh34

you are using it on "react-native": "0.60.4", I am using 0.59

**Comment by AsthaAmeta** [comment]
I am also facing the same issue. I am on RN version 0.59. I didn't get any such error earlier, being on the same version. It happened today all of a sudden.

**Comment by tosbaha** [comment]
Crash is still happening with 2.13.0 This time it doesn't show any error but instead it waits and waits and finally crashes. Can someone please get the bottom of this?

**Comment by PlabanJr** [comment]
Please check out our latest release [v2.12.5](https://github.com/GeekyAnts/NativeBase/releases/tag/v2.13.5). 

Thank you!

**Comment by tokict** [comment]
This repo turned to a heap of bugs lately. I will be dropping it as it requires more maintenance time than it saves
