### ISSUE TITLE
Using Tabs component, strange bug where tab switch to the default tab on input change.

### ISSUE THREAD

**Issue by z3us94** [GeekyAnts/NativeBase#2788]
## I have gone through these following points
- [x]   Check latest documentation: https://docs.nativebase.io/
- [x]   Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x]   Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink

## Issue Description

node - v10.15.1
npm - v6.4.1
react-native - v0.57.5
react - v16.8.6
native-base - v2.8.1

I have a very strange issue where with native base Tabs component. where i have a design like below. 
![default](https://user-images.githubusercontent.com/17064184/61525563-4a1ed000-aa36-11e9-95a9-740a1dd8de15.png)

The default/ initial tab of these Tabs is the Email Tab. I have attached a video demonstrating the issue that im having.
And please note that this is very specific to certain cases only. Initially, we encounter this issue with a [this](https://www.gsmarena.com/tecno_camon_cm-9443.php) mobile device.
Later on when investigating this issue. I found this on an emulator. 
Emulator device is NEXUS 6p with the Android OS 6.

### Actual behaviour

![tab-switch-issue](https://user-images.githubusercontent.com/17064184/61525837-d7622480-aa36-11e9-8949-89bf1cd15d81.gif)

i believe this is happening because of the below issue that i discovered later on. _for this i removed textAlign center so that i can type on that input field._

![overflow-issue](https://user-images.githubusercontent.com/17064184/61525874-eba62180-aa36-11e9-80d0-d3266e3ec63b.gif)

### Expected behaviour

The normal behavior of the tab where and the input field.

### Steps to reproduce

I also found the cause of this issue. It was i had put `textAlign: 'center'` to the input property. to make the placeholder and the typing text center. That caused this issue. But when i removed that it worked well. 

### Is the bug present in both iOS and Android or in any one of them?
Android specific.

**Comment by hanykumar** [comment]
Hi @z3us94 , can you provide snack for the same for minimal code reproduction?

**Comment by hanykumar** [comment]
Hi @z3us94 , closing this now due to inactivity. Let us know if the issue still persists.
