### ISSUE TITLE
List not rendering and showing Invariant Violation error

### ISSUE THREAD

**Issue by rohithramachandran** [GeekyAnts/NativeBase#2792]
## I have gone through these following points
- [x]   Check latest documentation: https://docs.nativebase.io/
- [x]   Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x]   Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [x]   Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- []   For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- []   For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

## Issue Description

When adding a Listview with ListItem getting below error
`Invariant Violation: ListView has been removed from React Native. See https://fb.me/nolistview for more information or use `deprecated-react-native-listview`. 
 
### node, npm, react-native, react and native-base version, expo version if used, xcode version
node 12.6.0
npm 6.9.0
react-native 0.60.4
react 16.8.6

### Expected behaviour
Listview suppose to render

### Actual behaviour
Getting error

### Steps to reproduce

Following is the code snippet
`import {
  Content,
  Text,
  List,
  ListItem,
  Icon,
  Container,
  Left,
  Right,
  Badge,
  Body
} from "native-base";`

`<List
            dataArray={datas}
            renderRow={data =>
              <ListItem
                button
                noBorder `

### Is the bug present in both iOS and Android or in any one of them?
Yes
### Any other additional info which would help us debug the issue quicker.
Issue #1282 already checked.Its not same.

**Comment by khodarahmi** [comment]
Same breaking issue, when I use ANY of NativeBase components.

"react": "^16.8.6",
"react-native": "^0.60.4",
"native-base": "^2.12.2",

The problem was raised after an overall upgrade from:

"react": "^16.0.0-alpha.12",
"react-native": "^0.52.0",
"native-base": "^2.5.2",

**Comment by sankhadeeproy007** [comment]
Hi, thanks for reporting. This is happening because react-native has deprecated ListView and one component in native-base depends on ListView. Working on getting out fix by today.

**Comment by RajeshKumDev** [comment]
I have removed all List and ListView code from my project, but still I am getting this above error.
Here are few screenshots:
![Error-1](https://user-images.githubusercontent.com/45311174/61693409-29fc5300-ad4d-11e9-9b36-729cdbcfdae3.png)
![Error-2](https://user-images.githubusercontent.com/45311174/61693428-308aca80-ad4d-11e9-863f-a3a30efee850.png)

In my app it is showing error here (as shown in screenshot): **hamburger-button.js: 3** and at that line I have `import { Icon } from "native-base";`
So this is not directly linked to ListView, but still I am getting the same error.

Please suggest for this also. I am stuck here.

**Comment by sankhadeeproy007** [comment]
It might be related to some other package.
Can you try removing the Icon import and check if that works?

**Comment by RajeshKumDev** [comment]
@sankhadeeproy007 After removing all references of `Icon`, I am not getting the above error.

**Comment by sankhadeeproy007** [comment]
Can you check with 2.13.0?

**Comment by rohithramachandran** [comment]
It works....!!!  Thanks Brother.... @sanketsahusoft ... Thanks for the prompt support.

**Comment by joaopiopedreira** [comment]
Hey guys, great package, thanks!! 

I'm going through the hassle of replacing all my `Icon`, `List` (and God knows what more) components imported from `native-base` and that have a dependency on `react-native` `ListView`. I'm currently on `native-base@2.13.8`. Can you tell me how long are you going to take to release your next update (`ListView` free) for me to see if it's worthy to proceed my manual changes?  Many thanks!

**Comment by Prakashandrews** [comment]
<img width="374" alt="Screenshot 2020-04-12 at 8 41 21 PM" src="https://user-images.githubusercontent.com/2599266/79069098-0d021880-7cfe-11ea-800b-ea717d5d7f85.png">

I am getting above error . But it works in iOS

Below is the package info:

   "native-base": "2.12.1",
    "prop-types": "^15.6.2",
    "react": "^16.6.3",
    "react-native": "^0.58.5",

**Comment by jasim-ur** [comment]
I have no ListView component but it's still getting back the invariant violation error. And also I have no Icon or Spinner that's I import from react-native or native-base.

**Comment by wispas** [comment]
> I have no ListView component but it's still getting back the invariant violation error. And also I have no Icon or Spinner that's I import from react-native or native-base.
> ![image](https://user-images.githubusercontent.com/52109597/96351452-318be280-10dd-11eb-909b-edf0861e008c.png)

any solutions???
