### ISSUE TITLE
Invariant Violation in Header if paddingTop is zero

### ISSUE THREAD

**Issue by njt1982** [GeekyAnts/NativeBase#2798]
https://github.com/GeekyAnts/NativeBase/blob/5abaf57c3c93cf81bd0ccf5f04d92497b4230515/src/basic/Header.js#L59

When I set paddingTop to zero, this condition then falls back to padding (which, for me, is undefined). This leads to paddingTop becoming `NaN` when it tries to add `InsetValues.topInset` to `undefined`.

Temp hack: set both `paddingTop` and `padding` to `0` in the custom style. A less than ideal "solution" though ;)

**Comment by sankhadeeproy007** [comment]
Thanks for reporting, we'll take a look.

**Comment by sankhadeeproy007** [comment]
Fixed in 2.12.3
