### ISSUE TITLE
Icon and TextInput are not aligned inside InputGroup on Adnroid

### ISSUE THREAD

**Issue by raminious** [GeekyAnts/NativeBase#280]
![photo_2016-11-09_19-55-28](https://cloud.githubusercontent.com/assets/334716/20145766/93f5c962-a6b6-11e6-950d-34b8935d9650.jpg)
![photo_2016-11-09_19-55-32](https://cloud.githubusercontent.com/assets/334716/20145767/9422771e-a6b6-11e6-9504-d350b7bf1319.jpg)
![photo_2016-11-09_19-55-35](https://cloud.githubusercontent.com/assets/334716/20145768/9445c340-a6b6-11e6-8124-769f3ea0b5f5.jpg)

**Comment by SupriyaKalghatgi** [comment]
@raminious Please check the latest of NativeBase and [NativeBase-KitchenSink](https://github.com/GeekyAnts/NativeBase-KitchenSink)

**Comment by imarem** [comment]
the latest of NativeBase and NativeBase-KitchenSink, have the same problem :(

**Comment by SupriyaKalghatgi** [comment]
This will be fixed with the rewrite of NativeBase.
To be released very soon
