### ISSUE TITLE
Header onLayout not execute setState

### ISSUE THREAD

**Issue by kitfall** [GeekyAnts/NativeBase#2805]
## I have gone through these following points
- [x]   Check latest documentation: https://docs.nativebase.io/
- [x]   Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x]   Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [x]   Check examples from NativeBase KitchenSink 

## Issue Description
If I using a Header component and like to fetch the current height by onLayout the process is working well, apart that my **this.setState** is not transmitting the values to the new cycle. it seems that like setState is not executed. If I wrap around my Header with a View, this  work neither. But when I using the react-native View component and not this one from native-base import, all was working fine.
For this moment this is my workaround, but in the future, it will be nice when you can fixing this.
To catch the height variable is not an option, because the header has a variable height and I cannot use the default device config values.

In the previous version **native-base@2.12.1 this was working.** It seems that the problem was a bit more inside native-base because also other components like View has this problem.

### node, npm, react-native, react and native-base version, expo version if used, xcode version
node - v10.11.0
npm - v6.10.1
react-native - v0.59.8
react - v16.8.3
native-base - v2.12.2

### Expected behaviour
setState is transmitting the current values

### Actual behaviour
height values are correct but setState is not executing

### Steps to reproduce
`<Header style={styles.header} onLayout={this.updateContentHeight}>
        <Left><Text>Back</Text></Left>
        <Body>
          <Title>Title of the header</Title>
        </Body>
        <Right><Text>Save</Text></Right>
      </Header>`

`  updateContentHeight = ({nativeEvent}) => {
    const { layout } = nativeEvent;
    const { height } = dimension;
    this.setState({contentHeight: height - layout.height});
  };`

**Comment by hanykumar** [comment]
Hi @kitfall , please provide minimal code production for the same on snack for our easy understanding. 
Thanks

**Comment by hanykumar** [comment]
Hi @kitfall , closing for now due to inactivity. Let us know if the issue still persists on latest Native-Base v2.13.14
