### ISSUE TITLE
Can not place text on the left side with Picker Input in Form

### ISSUE THREAD

**Issue by daido1976** [GeekyAnts/NativeBase#2807]
## I have gone through these following points
- [x]   Check latest documentation: https://docs.nativebase.io/
- [x]   Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x]   Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink

## Issue Description

In the following native-base document's code, I cannot place left align Text and right align Picker Input as shown in the `Expected behaviour`.

### node, npm, react-native, react and native-base version, expo version if used, xcode version

- node - v10.15.3
- npm - v6.9.0
- react-native - v0.59.8
- expo - v33.0.7
- react - v16.8.6
- native-base - v2.12.1
- xcode - v10.2.1

### Expected behaviour

There is a text of `SIM` on the left side.

![Components_·_NativeBase](https://user-images.githubusercontent.com/35087200/61817312-35549900-ae89-11e9-880d-139546cbc204.png)

### Actual behaviour

There is not a text of `SIM`.

<img src='https://user-images.githubusercontent.com/35087200/61817449-8795ba00-ae89-11e9-85ba-3e09162ced21.png' width=270>

### Steps to reproduce

I tried as per the following native-base document.

ref. https://docs.nativebase.io/Components.html#picker-input-headref

```javascript
import React, { Component } from 'react';
import { Container, Header, Content, Form, Item, Picker } from 'native-base';
export default class PickerInputExample extends Component {
    constructor(props) {
    super(props);
    this.state = {
      selected2: undefined
    };
  }
  onValueChange2(value: string) {
    this.setState({
      selected2: value
    });
  }
  render() {
    return (
      <Container>
        <Header />
        <Content>
          <Form>
            <Item picker>
              <Picker
                mode="dropdown"
                iosIcon={<Icon name="arrow-down" />}
                style={{ width: undefined }}
                placeholder="Select your SIM"
                placeholderStyle={{ color: "#bfc6ea" }}
                placeholderIconColor="#007aff"
                selectedValue={this.state.selected2}
                onValueChange={this.onValueChange2.bind(this)}
              >
                <Picker.Item label="Wallet" value="key0" />
                <Picker.Item label="ATM Card" value="key1" />
                <Picker.Item label="Debit Card" value="key2" />
                <Picker.Item label="Credit Card" value="key3" />
                <Picker.Item label="Net Banking" value="key4" />
              </Picker>
            </Item>
          </Form>
        </Content>
      </Container>
    );
  }
}
```

### Is the bug present in both iOS and Android or in any one of them?

I tried iOS only.

**Comment by PlabanJr** [comment]
@daido1976 Please try this. This should work fine.

![Screenshot 2019-07-26 at 1 02 55 PM](https://user-images.githubusercontent.com/22071072/61934677-8ad29800-afa6-11e9-9c09-8ecad14c15a1.png)

**Comment by daido1976** [comment]
@PlabanJr 
Thanks, I will try it 👍
