### ISSUE TITLE
Picker Issue on iOS Maximum update depth exceeded

### ISSUE THREAD

**Issue by royalgiant** [GeekyAnts/NativeBase#2810]
## I have gone through these following points
- [x]   Check latest documentation: https://docs.nativebase.io/
- [x]   Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x]   Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [x]   Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [x]   For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- []   For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

### node, npm, react-native, react and native-base version, expo version if used, xcode version
package.json
```
# node v10.16.0 npm v6.9.0
{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "eject": "expo eject"
  },
  "dependencies": {
    "@expo/vector-icons": "^10.0.3",
    "axios": "^0.18.0",
    "expo": "^33.0.0",
    "expo-constants": "^5.0.1",
    "expo-facebook": "~5.0.1",
    "expo-font": "~5.0.1",
    "expo-image-picker": "~5.0.2",
    "expo-location": "~5.0.1",
    "expo-permissions": "~5.0.1",
    "expo-web-browser": "^5.0.3",
    "firebase": "^5.11.0",
    "firebase-admin": "^7.0.0",
    "moment": "^2.24.0",
    "native-base": "^2.13.0",
    "prettier": "^1.18.2",
    "react": "16.8.3",
    "react-native": "https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz",
    "react-native-axios": "^0.17.1",
    "react-native-keyboard-aware-scroll-view": "^0.8.0",
    "react-native-modal-overlay": "^1.3.1",
    "react-navigation": "^3.3.2",
    "react-redux": "^6.0.1",
    "redux": "^4.0.1",
    "redux-form": "^8.1.0",
    "redux-logger": "^3.0.6",
    "redux-saga": "^1.0.2",
    "redux-saga-firebase": "^0.15.0",
    "relative-date": "^1.1.3",
    "sentry-expo": "~1.13.0"
  },
  "devDependencies": {
    "babel-preset-expo": "^5.0.0",
    "remote-redux-devtools": "^0.5.16"
  },
  "private": true
}
```
### Expected behaviour
Picker does not throw a Maximum update depth executed error.
### Actual behaviour
Picker throws Maximum update depth executed error
### Steps to reproduce

Removing this code will not give the error, but I need to use a picker.
```
                                    <Item picker>
			              <Picker
			                mode="dropdown"
			                iosIcon={<Icon name="arrow-down" />}
			                style={{ width: undefined }}
			                placeholder="country"
			                placeholderStyle={{ color: "#bfc6ea" }}
			                placeholderIconColor="#007aff"
			                selectedValue={this.state.country}
			                onValueChange={this.onCountryChange.bind(this)}
			              >
			                <Picker.Item label="Canada" value="Canada" />
			                <Picker.Item label="United States" value="United States" />
			              </Picker>
			            </Item>
```
![Simulator Screen Shot - iPhone Xʀ - 2019-07-24 at 15 41 43](https://user-images.githubusercontent.com/845626/61828655-d6613680-ae2c-11e9-82e9-8195483c4ac7.png)

### Is the bug present in both iOS and Android or in any one of them?
iOS

**Comment by andresmtz98** [comment]
x2

**Comment by pierol** [comment]
Same problem with version 2.13.0. I made a downgrade of native-base to 2.12.1 to solve the problem

**Comment by royalgiant** [comment]
@pierol, unfortunately. The downgrade did not work for me :(

**Comment by tattivitorino** [comment]
same here!!! getting crazy with this... I need the picker.. everything was working perfect with this:
"expo": "^32.0.0",
 "native-base": "^2.12.1",
"react": "16.5.0",
 "react-native": "https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz"

Now with these configs:
"expo": "^33.0.0",
 "native-base": "^2.13.0",
"react": "16.8.3",
"react-native": "https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz",

I get the same error!

**Comment by tattivitorino** [comment]
Ps. Picker is not the only component with problems after upgrading to 2.13. The SwipeRow has a problem with the "this._panResponder" being undefined!

TypeError: TypeError: undefined is not an object (evaluating 'this._panResponder.panHandlers')

This error is located at:
    in SwipeRow (at connectStyle.js:392)

**Comment by sentry0** [comment]
Same issue with the 2.13.0 release, going back to 2.12.2 resolved the issue for me.

**Comment by jacargentina** [comment]
Trying to find the culprit, i'm  suspecting from commit 5abaf57c3c93cf81bd0ccf5f04d92497b4230515

Downgrading to 2.12.2 solved it.

Fix ASAP

**Comment by Hawods** [comment]
Seem like all controlled components has the same issue with 2.13.0 release.

**Comment by mubashiralisiddiqui** [comment]
**setState** in **componentDidUpdate** causing issue there should have been a proper code review before merging any PR 
I am also facing issue on TextInput while onChangeText fix it locally by removing setState in the node modules files but this is not a proper solution I have seen this issue also happening in other controlled components

**Comment by sankhadeeproy007** [comment]
Yes, noticed it, in the process of adding `getDerivedStateFromProps` as we speak. Should be out in an hour or two.

**Comment by sankhadeeproy007** [comment]
@mubashiralisiddiqui Can you please share the use case for issue with TextInput?
How do we reproduce it?

**Comment by ashishdigitalrooar** [comment]
Downgraded from 2.13.0 to 2.12.2  but It's not working with expo 33

**Comment by mubashiralisiddiqui** [comment]
> @mubashiralisiddiqui Can you please share the use case for issue with TextInput?
> How do we reproduce it?

simlply when you call the onChangeText method on
 <Item floating={true}>
<INPUT onChangeText={(text) => onChange(text)} />
</Item>
and when you start typing  that issue will produce


secondly, there are some other bugs I found
1)Tabs active color not working while changing the Tab
1) in Icon tab icon color not working 
3)SwipeRow not working crashing the app

these are major bugs how can we proceed development under these situations?
please fix these ASAP

**Comment by sankhadeeproy007** [comment]
Please create separate issues for the above or they might go unattended.
If it is seriously hindering your development please consider creating PR's to fix the issues :)

**Comment by sankhadeeproy007** [comment]
The picker issue has been fixed with the latest release. 
Currently figuring out a fix for the Tab text color. 
Please raise separate issues with reproducible steps.

**Comment by kaushalpar** [comment]
npm install native-base --save use this command and resolve issue (100% resolved)
