### ISSUE TITLE
Tab not working in latest release 2.13.0

### ISSUE THREAD

**Issue by ashishdigitalrooar** [GeekyAnts/NativeBase#2817]
![AwesomeScreenshot-Screenshot-1564133807-2019-07-26-15-07-65](https://user-images.githubusercontent.com/53290762/61942848-d5a8db80-afb7-11e9-9e8d-c1e892ed88cc.png)

> **In latest version Tab not working when click for change It dont work and active color also not showing.**

**Comment by ashishdigitalrooar** [comment]
I tested with 2.13.4 also

**Comment by IntelliJAbhishek** [comment]
@ashishdigitalrooar can you post snippet in https://snack.expo.io/ so that other can test

**Comment by ashishdigitalrooar** [comment]
I have created snack snippet, You can check 
https://snack.expo.io/@ashishrooar/9fe862

**Comment by sankhadeeproy007** [comment]
Fixed it here
https://snack.expo.io/rysj-DdMH
You need to remove `page={activeTabValue}` for it to work correctly.
Or change it with the onTabChange callback.

**Comment by ashishdigitalrooar** [comment]
@sankhadeeproy007  I removed page={activeTabValue}, So now working my Tabs but I had put because of validation, When there are input value not entered and current tab is first in that condition when I will submit form It will redirect on second tab. It will show error.
For redirecting on second tab what to do?
In your documentation, There is mentioned about this configuration **page**
https://docs.nativebase.io/Components.html#tabs-def-headref
Thanks
