### ISSUE TITLE
TypeError: Cannot read property 'panHandlers' of undefined

### ISSUE THREAD

**Issue by onurcskun** [GeekyAnts/NativeBase#2818]
ExceptionsManager.js:76 TypeError: TypeError: Cannot read property 'panHandlers' of undefined

This error is located at:
    in SwipeRow (at connectStyle.js:392)
    in Styled(SwipeRow) (at feedback-list-item/index.js:295)
    in FeedbackListItem (at inbox-screen/index.js:303)
    in RCTView (at View.js:45)
    in View (at inbox-screen/index.js:299)
    in StaticRenderer (at ListView.js:463)
    in RCTScrollContentView (at ScrollView.js:852)
    in RCTScrollView (at ScrollView.js:952)
    in ScrollView (at ListView.js:324)
    in ListView (at inbox-screen/index.js:555)
    in RCTView (at View.js:45)
    in View (at inbox-screen/index.js:527)
    in InboxScreenComponent (at inbox/index.js:355)
    in InboxScreen (created by Context.Consumer)
    in Connect(InboxScreen) (at Root.js:109)
    in screen (at SceneView.js:9)
    in SceneView (at createTabNavigator.js:39)
    in RCTView (at View.js:45)
    in View (at ResourceSavingScene.js:37)
    in RCTView (at View.js:45)
    in View (at ResourceSavingScene.js:26)
    in ResourceSavingScene (at createBottomTabNavigator.js:121)
    in RCTView (at View.js:45)
    in View (at screens.native.js:101)
    in ScreenContainer (at createBottomTabNavigator.js:111)
    in RCTView (at View.js:45)
    in View (at createBottomTabNavigator.js:110)
    in TabNavigationView (at createTabNavigator.js:197)
    in NavigationView (at createNavigator.js:61)
    in Navigator (at SceneView.js:9)
    in SceneView (at StackViewLayout.tsx:899)
    in RCTView (at View.js:45)
    in View (at createAnimatedComponent.js:153)
    in AnimatedComponent (at StackViewCard.tsx:93)
    in RCTView (at View.js:45)
    in View (at createAnimatedComponent.js:153)
    in AnimatedComponent (at screens.native.js:71)
    in Screen (at StackViewCard.tsx:80)
    in Card (at createPointerEventsContainer.tsx:95)
    in Container (at StackViewLayout.tsx:971)
    in RCTView (at View.js:45)
    in View (at screens.native.js:101)
    in ScreenContainer (at StackViewLayout.tsx:383)
    in RCTView (at View.js:45)
    in View (at createAnimatedComponent.js:153)
    in AnimatedComponent (at StackViewLayout.tsx:379)
    in PanGestureHandler (at StackViewLayout.tsx:372)
    in StackViewLayout (at withOrientation.js:30)
    in withOrientation (at StackView.tsx:103)
    in RCTView (at View.js:45)
    in View (at Transitioner.tsx:267)
    in Transitioner (at StackView.tsx:40)
    in StackView (at createNavigator.js:61)
    in Navigator (at createKeyboardAwareNavigator.js:12)
    in KeyboardAwareNavigator (at createAppContainer.js:429)
    in NavigationContainer (at Root.js:269)
    in AppWithConnect (created by Context.Consumer)
    in Connect(AppWithConnect) (at Root.js:409)
    in RCTView (at View.js:45)
    in View (at Root.js:407)
    in Provider (at Root.js:405)
    in Root (at App.js:70)
    in RCTView (at View.js:45)
    in View (at App.js:69)
    in RCTView (at View.js:45)
    in View (at Root.js:14)
    in Root (at connectStyle.js:392)
    in Styled(Root) (at App.js:68)
    in ErrorBoundary (at App.js:67)
    in App (at renderApplication.js:34)
    in RCTView (at View.js:45)
    in View (at AppContainer.js:98)
    in RCTView (at View.js:45)
    in View (at AppContainer.js:115)
    in AppContainer (at renderApplication.js:33)

This error is located at:
    in NavigationContainer (at Root.js:269)
    in AppWithConnect (created by Context.Consumer)
    in Connect(AppWithConnect) (at Root.js:409)
    in RCTView (at View.js:45)
    in View (at Root.js:407)
    in Provider (at Root.js:405)
    in Root (at App.js:70)
    in RCTView (at View.js:45)
    in View (at App.js:69)
    in RCTView (at View.js:45)
    in View (at Root.js:14)
    in Root (at connectStyle.js:392)
    in Styled(Root) (at App.js:68)
    in ErrorBoundary (at App.js:67)
    in App (at renderApplication.js:34)
    in RCTView (at View.js:45)
    in View (at AppContainer.js:98)
    in RCTView (at View.js:45)
    in View (at AppContainer.js:115)
    in AppContainer (at renderApplication.js:33)

![image](https://user-images.githubusercontent.com/20303109/61955158-19eda900-afc3-11e9-8c87-cd17673c1759.png)

native-base version: 2.13.4
react-native version: 0.57.1

**Comment by onurcskun** [comment]
hmm.. it has been removed.

**Comment by msqar** [comment]
Yea, throwing the same error here too. I'm using `<SwipeRow>`. Any idea?

**Comment by msqar** [comment]
Ohhh it was removed! you're right! LOL.

**Comment by hoangphuc-work** [comment]
How to fix this issue? Please, thank you..

**Comment by anniewey** [comment]
@hoangphuc-work use https://github.com/jemise111/react-native-swipe-list-view
