### ISSUE TITLE
View: wrap content

### ISSUE THREAD

**Issue by thundenilla** [GeekyAnts/NativeBase#282]
I'm pretty new with RN, is there anyway to wrap the content of the view, similar to android. In android i can just, Height: 'wrap-content'. But somehow in RN, i can't do any wrap content.

It's either I set the height of the view, or just flex, but still not wrap the view.

**Comment by himanshu-satija** [comment]
Try using [flexWrap](http://www.w3schools.com/cssref/css3_pr_flex-wrap.asp)
