### ISSUE TITLE
Conditional Style only works on initial load

### ISSUE THREAD

**Issue by gomezkitty17** [GeekyAnts/NativeBase#2822]
Hello All,

Our issue is related to this one
https://github.com/GeekyAnts/NativeBase/issues/2567
however it applies to different native base components like buttons, card, carditem, etc.
We are using this version :
  "native-base": "^2.12.1"
We even tried to use the latest one which is v2.13.4 but still conditional styling is not working.

Example

 <Button style=color={[this.state.buttonDisabled ? styles.resetPasswordButtonDisabled : styles.resetPasswordButtonEnabled,{backgroundColor: this.state.buttonDisabled ? "#fdced6" : "#F41A3E"}]} >

at initial load of the application, the style is shown properly but once the value of state changes, the styles remain unchanged.

Can you advise on how to fix the issue?

Thanks

**Comment by sankhadeeproy007** [comment]
Can you please try v2.13.4 ?

**Comment by gomezkitty17** [comment]
yeah we tried v2.13.4  as mentioned in the initial comment but same issue is occurring. Thanks

**Comment by sankhadeeproy007** [comment]
Please attach a reproducible snack example.
