### ISSUE TITLE
Tab contents becomes blank after changing tab heading

### ISSUE THREAD

**Issue by xfyre** [GeekyAnts/NativeBase#2824]
## I have gone through these following points
- [x]   Check latest documentation: https://docs.nativebase.io/
- [x]   Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x]   Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [x]   Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [x]   For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- [x]   For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

## Issue Description

NativeBase Tab contents of the current tab disappears when Tab `heading` value is changed dynamically via outer component state. The issue appears with React Native 0.59.x.

### node, npm, react-native, react and native-base version, expo version if used, xcode version
- node v12.5.0
- react-native v0.59.10
- react v16.8.3
- native-base: 2.13.0 and 2.12.0, issue is reproducible in both

### Expected behavior

When `heading` value is changed externally, Tabs component should keep the current state and re-render correctly, displaying the latest selected tab contents.

### Actual behavior

Tabs component is re-rendering with blank content. Tapping the current tab restores the content it should display.

### Steps to reproduce

Code snippet (ClojureScript, `nb/tabs` and `nb/tab` correspond to NativeBase Tabs and Tab components, respectively):

```clojure
(defn tabs-testcase []
  (let [state1-ref (r/atom 0)
        state2-ref (r/atom 0)]
    (fn []
      [nb/tabs {:locked true}
       [nb/tab {:heading (str "state1 = " @state1-ref)}
        [nb/h1 "tab1"]
        [nb/button {:on-press #(swap! state1-ref inc)} [nb/text "Update state1"]]
        ]
       [nb/tab {:heading (str "state2 = " @state2-ref)}
        [nb/h1 "tab2"]
        [nb/button {:on-press #(swap! state2-ref inc)} [nb/text "Update state2"]]
        ]
       ]
      )
    )
```

- Screenshot 1 (initial state): https://take.ms/03KKDO
- Screenshot 2 (button tapped, bug exposed): https://take.ms/bdbmx
- Screenshot 3 (current tab tapped - expected state): https://take.ms/cLQkd

### Is the bug present in both iOS and Android or in any one of them?

Issue is present on both platforms.

### Any other additional info which would help us debug the issue quicker.

The issue appeared after upgrading to React Native 0.59. Unfortunately there's no choice to downgrade because of new Google requirements effective after Aug 1.

### Workaround

The issue can be fixed by wrapping dynamic heading in `<TabHeading/>` component.

**Comment by sankhadeeproy007** [comment]
@xfyre Can you check with the latest version v2.13.4?

**Comment by xfyre** [comment]
@sankhadeeproy007 I'll try in a couple of days and update here about results. As I managed to fix my issue by directly wrapping heading contents in `<TabHeading/>` component, this is now less critical.

**Comment by luvnish19** [comment]
use property `prerenderingSiblingsNumber` and under this pass tabs count or value 1. It will look like
`prerenderingSiblingsNumber={1}`
