### ISSUE TITLE
Cannot access to row's index in renderRow of List

### ISSUE THREAD

**Issue by kenji4569** [GeekyAnts/NativeBase#2825]
This commit https://github.com/GeekyAnts/NativeBase/commit/a867e33f3565cd082cb2cf2df66636b743222afc#diff-adb80937e3be06283394efe72848a734
changes the behavior of the renderRow of List. 
Then we can no longer access to the index of each row.
It's ok to change the behavior but we should access to the index anyway.

**Comment by kenji4569** [comment]
I could manage to access index of each row by passing "renderItem" to List as follows:
```
<List dataArray={items}
        {
          ...{
            renderItem: ({item, index}) => {
              return <ListItem key={index}>{'xxx'}</ListItem>
            },
          }
        }
        />
```
But it would be better to define renderItem explicitly to the props of List.

**Comment by kenji4569** [comment]
It might be better to keep backwards compatibility for renderRow's spec, then define a renderItem method explicitly for it.

**Comment by sankhadeeproy007** [comment]
@kenji4569 Yes, that's what has been done in the above commit. We can now access the `index` from renderRow as well.

**Comment by kenji4569** [comment]
@sanketsahusoft 
I think previous renderRow's arguments are (rowData, secId, rowId), not (item, index), which would break the backwards compatibility.

**Comment by sankhadeeproy007** [comment]
Oh okay, does FlatList provide (rowData, secId, rowId)?
Care to send a PR with the fixes above?

**Comment by kenji4569** [comment]
> does FlatList provide (rowData, secId, rowId)?
I think no. Maybe we should set as follows:
```
renderItem={({ item, index }) => this.props.renderItem ? renderItem({ item, index} ) : this.props.renderRow(item, 0, index)}
```

**Comment by kenji4569** [comment]
@PlabanJr 
I think we should also fix index.d.ts for the props change.

**Comment by PlabanJr** [comment]
> @PlabanJr
> I think we should also fix index.d.ts for the props change.

It's done 👍
