### ISSUE TITLE
Poor List performance

### ISSUE THREAD

**Issue by fubar** [GeekyAnts/NativeBase#2830]
Since the upgrade to 2.13 (https://github.com/GeekyAnts/NativeBase/releases/tag/v2.13.0), the render speed, scroll performance, and tap lag of Lists have all become very poor. @sankhadeeproy007 can you provide some insights or tips? Thanks!

**Comment by sankhadeeproy007** [comment]
@fubar hi, is the performance degradation in android or ios or on both?
That's strange as we've replaced ListView with Flatlist and should have been the other way round.
Can you post a reproducible snippet which I can test?

**Comment by fubar** [comment]
I should have provided more details, my bad. iOS, React 16.6.3, React Native 0.57.8
I don't have an easily reproducible test case. This probably requires a bit more time to compare behaviour between the two versions and to isolate a test case to reproduce it.

**Comment by fubar** [comment]
I don't have time to debug this in the near future. Closing this issue for now, might reopen it later.
