### ISSUE TITLE
disabled(only for Tab) not work!

### ISSUE THREAD

**Issue by phamdoan** [GeekyAnts/NativeBase#2833]
react-native, react and native-base version
React Native: 0.56.1.
Native Base: 2.12.1.
Code
<Tab heading={<TabHeading><Text>予約</Text></TabHeading>} disabled={true}>

I can still click even though I disabled it.

**Comment by Srishti-Sharma** [comment]
Please try v2.13.4, it works fine.

**Comment by phamdoan** [comment]
> Please try v2.13.4, it works fine.

thank !

**Comment by RoniFinTech** [comment]
Tried both 2.13.4 and 2.13.8 and 'disabled' is not even a prop for 'Tab' for me... any idea why?

**Comment by annjawn** [comment]
`disabled={true}` and `disabled={false}` have the same effect on `<Tab/>` i.e. the Tab remains disabled in both cases, and I am using latest version.

**Comment by mhq96** [comment]
Try sending "undefined" in place of "false" in your condition. That did work for me!
