### ISSUE TITLE
Failed at the native-base@2.13.4 postinstall script

### ISSUE THREAD

**Issue by shubham1164** [GeekyAnts/NativeBase#2834]
## I have gone through these following points
- [x]   Check latest documentation: https://docs.nativebase.io/
- [x]   Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x]   Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [x]   Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [x]   For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- [x]   For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

### node, npm, react-native, react and native-base version, expo version if used, xcode version
npm = 6.10.2, react-native=0.59.5, react=16.8.3, Xcode: 10.3, no expo

### Expected behaviour
native-base version must be updated to 2.14.1

### Actual behaviour
unable to install native-base@2.14.1

### Steps to reproduce
migrate the native-base from 2.12.1 to 2.14.1

## Issue Description
I am using react-native 0.59 and native-base 2.12.1, I want to update the native-base to 2.13.4 ( or latest) but when I tried to update with
$npm install native-base@2.13.4
I get the error
```myusers-mac-mini:app myuser$ npm install native-base@2.13.4

> native-base@2.13.4 postinstall /Users/myuser/Documents/Workspace/ReactNative/app/app/node_modules/native-base
> node addEjectScript.js && opencollective-postinstall

┌────────────────────────────────────────────────────────────────────────────────────────────┐
│ NativeBase 2.0 has been succesfully installed!                                             │
│ Run node node_modules/native-base/ejectTheme.js to copy over theme config and variables. │
│ Head over to the docs for detailed information on how to make changes to the theme.        │
└────────────────────────────────────────────────────────────────────────────────────────────┘
sh: opencollective-postinstall: command not found
npm WARN react-native-gesture-handler@1.1.3 requires a peer of react-art@>= 16.3.2 but none is installed. You must install peer dependencies yourself.
npm WARN react-native-gesture-handler@1.1.3 requires a peer of react-dom@>= 16.3.2 but none is installed. You must install peer dependencies yourself.
npm WARN react-native-gesture-handler@1.1.3 requires a peer of react-native-web@>= 0.7 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-prettier@6.0.0 requires a peer of eslint@>=3.14.1 but none is installed. You must install peer dependencies yourself.

npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! native-base@2.13.4 postinstall: node addEjectScript.js && opencollective-postinstall
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the native-base@2.13.4 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/myuser/.npm/_logs/2019-07-31T04_36_44_052Z-debug.log````

**Comment by shubham1164** [comment]
Solved with deleting node_modules/ and $npm install

**Comment by Bidhanchandra09** [comment]
Its not working with this solution ..... deleted whole project and cloned it again but getting same error

**Comment by bilalyaqoob** [comment]
i am getting same issue

**Comment by pilleanand** [comment]
I am also getting same error
