### ISSUE TITLE
[ITEM] Floating label input with icon bug

### ISSUE THREAD

**Issue by greg-olivier** [GeekyAnts/NativeBase#2835]
## I have gone through these following points
- [x]   Check latest documentation: https://docs.nativebase.io/
- [x]   Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x]   Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [x]   Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [x]   For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/

### react-native, react and native-base version, expo version
React-Native : 0.59.8
React : 16.8.3
Expo : SDK33
Native Base : 2.13.4

### Expected behaviour
Should print Icon in input with the floating Label

### Actual behaviour
Icon missing and input bug (if you have many inputs, next one's floating label doesn't float up)

### Steps to reproduce
`<Item floatingLabel={true}>
        <Label>Input Label</Label>
        <Input/>
	    <Icon name="checkmark"/>
</Item>`

### Is the bug present in both iOS and Android or in any one of them?
Android : Yes
iOS : Yes

**Comment by sankhadeeproy007** [comment]
Please add proper reproduction steps, preferably a snack repro

**Comment by greg-olivier** [comment]
Sorry for the incompleteness of my report :) You can access here : [Snack Expo](https://snack.expo.io/@smart_futures/native-base-floating-label-issue)

**Comment by williampaulo** [comment]
The problem is missing the Component Item on line 160.
<Icon Key = {[i]} {... this.props.children [i] .props} />
A key is like an array. Remove the brackets that are fine.

**Comment by Abdo-zayed** [comment]
same issue , when i upgrade native base , i faced this issue

**Comment by smddzcy** [comment]
We had the same issue with a recent project. Downgrading native-base to 2.12.1 fixed the issue for us.

**Comment by temitope** [comment]
#2875  specifies this exctly

**Comment by iranmarcius** [comment]
> #2875 specifies this exctly

In my case the application completely hangs.

**Comment by PlabanJr** [comment]
The issue has been addressed and will be available in the next release, which is coming soon. 
Thank you!

**Comment by PlabanJr** [comment]
Please try out our latest release [v2.12.5](https://github.com/GeekyAnts/NativeBase/releases/tag/v2.13.5).

Thank you!
