### ISSUE TITLE
Header Invariant Violation by default on iOS

### ISSUE THREAD

**Issue by Sivli-Embir** [GeekyAnts/NativeBase#2837]
## I have gone through these following points
- [x]   Check latest documentation: https://docs.nativebase.io/
- [x]   Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x]   Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- []   Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- []   For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- []   For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

## Issue Description

App crashing on startup. Found the Issue was the Header. I was testing an existing app after upgrading expo and Native Base. This is limited to my iPhone X. My android emulator works fine.
```jsx
<Header>
  <Left/>
  <Body>
    <Title>[omited]</Title>
  </Body>
  <Right />
</Header>
```

### node, npm, react-native, react and native-base version, expo version if used, xcode version

* node/12.0.0
* "expo": "^34.0.1"
* "react": "16.8.3",
* "react-native": "0.59.8",
* "native-base": "2.13.4"

### Expected behaviour
No crash

### Actual behaviour
Crashses with the following error: 

```
Invariant Violation: [25,"RCTView",171,{"backgroundColor":4283326034,"flexDirection":"row","paddingLeft":10,"paddingRight":10,"justifyContent":"center","paddingTop":42,"borderBottomWidth":0.3333333333333333,"borderBottomColor":4282339765,"height":"<<NaN>>","elevation":3,"shadowColor":4278190080,"shadowOffset":{"width":0,"height":2},"shadowOpacity":0.2,"shadowRadius":1.2,"top":0,"left":0,"right":0}] is not usable as a native method argument
```

Note `"height":"<<NaN>>"`. 

### Steps to reproduce

Should crash on a clean install for iOS. 

### Is the bug present in both iOS and Android or in any one of them?
Only iOS

### Any other additional info which would help us debug the issue quicker.
Setting height, `<Header style={{height: 10}}>` or example, resolves the issue.

**Comment by Sivli-Embir** [comment]
This was similar to other issues but seemed deferent enough (hight specific) to deserve its own issue.

**Comment by Sivli-Embir** [comment]
I seem to be getting this issue as far back as "native-base": "2.10.0". (though I know I tested this on iOS with a later version). This may be a configuration issue on my side but I would not know how to check. Advice?

**Comment by timching** [comment]
I faced the same problem too, and based on https://github.com/GeekyAnts/NativeBase/issues/2603, setting the `height` of the `<Header>` works for me
```jsx
<Header style={styles.header}/>
...
...
const styles = StyleSheet.create({
    header: {
      height: Platform.OS === 'ios' ? 90 : 50,
      paddingTop: Platform.OS === 'ios' ? 40 : 0,
      paddingBottom: Platform.OS === 'ios' ? 0 : 0,
    },
});
```

And remember to set the `headerStyle` for `<Picker>` if you use it
```jsx
<Picker headerStyle={styles.header}>...</Picker>
```

Hope it helps ~

**Comment by Sivli-Embir** [comment]
Thank you @timching! That was actually very helpful. Still a bug but I have now statically added that to all my headers and can push to production now.

**Comment by PlabanJr** [comment]
@Sivli-Embir  I tried reproducing it but seems to work fine for me. Please check [this](https://snack.expo.io/@plabanjr/issue-#2837). Am I missing something obvious?

**Comment by PlabanJr** [comment]
I tried reproducing the issue but it seems to work fine for me. Please check [this](https://snack.expo.io/@plabanjr/098f6b). Please let me know if I am missing something obvious.

**Comment by PlabanJr** [comment]
@Sivli-Embir  I tried reproducing the issue but it seems to work fine for me. Please check [this](https://snack.expo.io/@plabanjr/098f6b). Please let me know if I am missing something obvious.
