### ISSUE TITLE
On Icons conditional rendering of color props is not Working

### ISSUE THREAD

**Issue by shrinkhala-navsoft** [GeekyAnts/NativeBase#2839]
constructor(props) {
    super(props);
    this.state = {
      data: null,
      status: false,
      serviceStatus: false,
      user_id: null,
      visible: false,
      iconColor: "white"
    };
  }

const myIcon =
      this.state.iconColor == "red" ? (
        <Icon
          name="heart"
          type="FontAwesome"
          style={{
            backgroundColor: "red",
            fontSize: 30
          }}
        />
      ) : (
        <Icon
          name="heart-o"
          type="FontAwesome"
          style={{
            color: "white",
            fontSize: 30
          }}
        />
      );

Above code is working Fine But It is Always Showing the Icon in White Color, If I console.log the State the iconColor props is changing correctly but same property is not reflected back in icon Color

thanks in advance.

**Comment by sankhadeeproy007** [comment]
Please follow the issue template or the issue will be closed soon.

**Comment by smigfu** [comment]
I do have that problem quite frequently with (native base) components. You can workaround this by setting a `key` and prepend the state to it, i.e. `<Icon key={"icon_" + this.state.iconColor}... />`. Somehow this force the icon to re-render properly.

**Comment by shrinkhala-navsoft** [comment]
> I do have that problem quite frequently with (native base) components. You can workaround this by setting a `key` and prepend the state to it, i.e. `<Icon key={"icon_" + this.state.iconColor}... />`. Somehow this force the icon to re-render properly.

@smigfu Thanks this is working fine.
But I didn't get the issue because Icon is changing so re-rendering was occurring only color is not changing.

**Comment by PlabanJr** [comment]
Please follow the issue template and create a new issue. 

Thank you!
