### ISSUE TITLE
Items in ListItem not aligned properly

### ISSUE THREAD

**Issue by peterkruty** [GeekyAnts/NativeBase#284]
I created minimalistic example using online examples from you:

```
renderRow(item, sectionID, rowID, highlightRow: (sectionID: number, rowID: number) => void) {
    return (
        <ListItem IconLeft IconRight >
             <Icon name="ios-mail-outline" style={{ color: '#0A69FE' }} />
             <Text>Mail</Text>
             <Badge>12</Badge>
        </ListItem>
    ) 
  }     

  render() {
    return (
        <List dataArray={[1,2,3,4]}
              renderRow={ 
                (rowData, sectionID, rowID, highlightRow) => 
                  this.renderRow(rowData, sectionID, rowID, highlightRow)
        }>
        </List>
    );
  }
```

this should render lines when icon is on left, then text and badge is on the right, but this is what I get:

<img width="281" alt="screen shot 2016-11-11 at 10 31 30" src="https://cloud.githubusercontent.com/assets/22683585/20210509/3cc1c7c8-a7fa-11e6-9648-ba3ad30d8c78.png">

Text is on second line and I can't find a way put it on the same line as icon and badge. Is it bug or why it does not look like on examples from you guys?

**Comment by SupriyaKalghatgi** [comment]
@peterkruty Could you please go through the implementation of [List Icon](https://github.com/GeekyAnts/NativeBase-KitchenSink/blob/master/js/components/list/list-icon.js) in [NativeBase-KitchenSink](https://github.com/GeekyAnts/NativeBase-KitchenSink)

![list-icon](https://cloud.githubusercontent.com/assets/13464885/20350301/61a254f2-ac34-11e6-8de7-a2066d7612d1.png)

**Comment by peterkruty** [comment]
I copied it from KitchenSink and it was not as on screenshots or in real app. 

However I figured out that when I wrap icon and text into <View> it works as I need it. Still however behaves differently to you your app when I run it.

**Comment by SupriyaKalghatgi** [comment]
@peterkruty Could you share screenshot of it?

**Comment by SupriyaKalghatgi** [comment]
@peterkruty Working fine?

**Comment by peterkruty** [comment]
Screenshot of what?

**Comment by SupriyaKalghatgi** [comment]
@peterkruty You said your app behaves differently from Kitchen sink
Could you share screenshots for same?

**Comment by SupriyaKalghatgi** [comment]
@peterkruty You are going wrong with aligning components using `iconLeft` and `iconRight`

- This is your statement of code
```
<ListItem IconLeft IconRight >
```

- WhereAs, it should be
```
<ListItem iconLeft iconRight >
```

Check the working example here
![screen shot 2016-12-26 at 7 22 47 pm](https://cloud.githubusercontent.com/assets/13464885/21482982/3f42e106-cba1-11e6-94c8-56f379c4206a.png)
