### ISSUE TITLE
native base issue

### ISSUE THREAD

**Issue by ztss0056** [GeekyAnts/NativeBase#2841]
Hello I am using 
"native-base": "^2.2.1",
"react-native": "^0.59.1",

I am getting the following error

error: bundling failed: Error: Unable to resolve module `react-native/Libraries/Renderer/shims/ReactNativePropRegistry` from `path\node_modules\native-base\dist\src\Utils\computeProps.js`: Module `react-native/Libraries/Renderer/shims/ReactNativePropRegistry` does not exist in the Haste module map

Please help me in this...
@beausmith

**Comment by ztmv0062** [comment]
I'm also facing the same issue,
Can any one please help me.

**Comment by beausmith** [comment]
Sorry, I'm unable to help as I'm not currently working in any react-native projects.

**Comment by sankhadeeproy007** [comment]
Please check with the latest version.
