### ISSUE TITLE
Feature Request: Parameter floatBack in the Label

### ISSUE THREAD

**Issue by williampaulo** [GeekyAnts/NativeBase#2843]
Hi,

In React Native I have a problem with the distance between Lebel and Input base when the Item component is floatingLabel.

I am using a standardized to make the components responsive.
```
const normalize = (size) => {

  const base_unit_height = 683;
  
  let base = Dimensions.get('window').height;

  if (Dimensions.get('window').width > Dimensions.get('window').height) {
    base = Dimensions.get('window').width;
  }

  return (size / base_unit_height) * base
};
```

When I am at a low density the above problem occurs.
e.g.:

Without parameter floatBack on a screen 480x854hdpi

![img-with-problem-device-480x854hdpi](https://user-images.githubusercontent.com/5365376/62391677-e3bca600-b53b-11e9-9ed0-74b70c7487dc.png)

The problem occurs because the top of the label animation is fixed.

By manipulating a "floatBack" property you could pass the value you would like to look like in the following image:

With parameter floatBack on a screen 480x854hdpi
![img-without-problem-device-480x854hdpi](https://user-images.githubusercontent.com/5365376/62391819-3bf3a800-b53c-11e9-9d82-f92d0f727e3c.png)

I tested on other screen density and the "floatBack" parameter works without problems.
e.g.:

Without parameter floatBack on a screen 1080x1920: 420dpi

![img-without-floatBack-device-1080x1920-420dpi](https://user-images.githubusercontent.com/5365376/62392097-f2578d00-b53c-11e9-9017-0b15044f3980.png)

With parameter floatBack on a screen 1080x1920: 420dpi
![img-with-floatBack-device-1080x1920-420dpi](https://user-images.githubusercontent.com/5365376/62392171-1fa43b00-b53d-11e9-8d66-e33f3cd7d082.png)

The Component that would need to be modified will be: Item and Label.

In Component Item:
```
...
floatBack(e) {// <== here, line 55
    Animated.timing(this.state.topAnim, {
      toValue: e || 18,// <== here, line 57
      duration: 150
    }).start();
    Animated.timing(this.state.opacAnim, {
      toValue: 1,
      duration: 150
    }).start();
  }
...
renderLabel(label, labelProps) {
  ...
  if (this.props.floatingLabel) {
      if (this.state.isFocused) {
      ...
      } else {
        newLabel.push(label);
        this.floatBack(labelProps.floatBack); // <== here, line 390
      }
  ...
```

In Component Label:
```
Label.propTypes = {
  ...Text.propTypes,
  style: PropTypes.oneOfType([
    PropTypes.object,
    PropTypes.number,
    PropTypes.array
  ]),
  floatBack: PropTypes.number, // <== here, line 21
};
```

**Comment by sankhadeeproy007** [comment]
@williampaulo Hey, that sounds like a great idea. Would really appreciate a PR with the above changes.

**Comment by sankhadeeproy007** [comment]
Has been added, will be available in the next release.
