### ISSUE TITLE
Toast hidden by keyboard

### ISSUE THREAD

**Issue by thomaslc66** [GeekyAnts/NativeBase#2844]
## I have gone through these following points
- []   Check latest documentation: https://docs.nativebase.io/
- []   Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- []   Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- []   Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- []   For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- []   For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

### node, npm, react-native, react and native-base version, expo version if used, xcode version
node: 12.4.0
npm: 6.9.0
react-native: 0.59.9
native-base: 2.13.4

### Expected behaviour

Toast should appeard on top of keyboard

### Actual behaviour

Can't see the toast as it appears behing keyboard.

### Steps to reproduce

a text input and a button, focus on the textinput this will pop-out keyboard, then press the button to show toast. The toast will not appear.

### Is the bug present in both iOS and Android or in any one of them?
Only tested for android

**Comment by PlabanJr** [comment]
![Issue #2844](https://user-images.githubusercontent.com/22071072/62451139-4b1c6500-b78b-11e9-871c-8d44b67a79b5.gif)

**Comment by maitrungduc1410** [comment]
> I tried reproducing the issue but seems to work fine at out end.
> 
> ![Issue #2844](https://user-images.githubusercontent.com/22071072/62451139-4b1c6500-b78b-11e9-871c-8d44b67a79b5.gif)

You should test it with iOS, I'm having same issue, works fine for Android, but hiding by keyboard on iOS

**Comment by PlabanJr** [comment]
> > I tried reproducing the issue but seems to work fine at out end.
> > ![Issue #2844](https://user-images.githubusercontent.com/22071072/62451139-4b1c6500-b78b-11e9-871c-8d44b67a79b5.gif)
> 
> You should test it with iOS, I'm having same issue, works fine for Android, but hiding by keyboard on iOS

Yeah,I did and the solution is pushed. It should be available in the next release.

**Comment by PlabanJr** [comment]
Please try our latest release [v2.12.5](https://github.com/GeekyAnts/NativeBase/releases/tag/v2.13.5).

**Comment by levani** [comment]
Toast is still hidden by keyboard for me on 2.13.8 on both android and ios...

**Comment by hanykumar** [comment]
Hi Team, I am ex-employee of GeekyAnts.

Native base version: 3.4.19
I am also facing same issue. 
Toast is hidden under keyboard.
Thanks

**Comment by tobobo** [comment]
I am also having this issue on IOS, Native base 3.4.21

**Comment by bryanltobing** [comment]
why is this closed?

**Comment by sainijagjit** [comment]
Still in 3.3.7

**Comment by SauravCogncise** [comment]
I am using Native base 3.4.28 it's working fine in IOS but not in android.
