### ISSUE TITLE
App crashing on iOS release build

### ISSUE THREAD

**Issue by mukherjeeraja7** [GeekyAnts/NativeBase#2845]
I am using native-base 2.12.0. My application is crashing in the log-in screen where I am using the **card** from native-base.  As it is ios release build, I am not getting any proper logs. Below are the version details-
 1. react-native - 0.59.8
 2. native-base - 2.12.0

Here is my render code block: -
    render() {
        return (
            <ViewWithSpinner
                style={styles.container}
                source={require('../../images/login_bg.png')}
                isLoading={this.props.authenticationStore.isLoading}>

                <StatusBar
                    backgroundColor={colors.black}
                    barStyle="light-content"
                />

                <Card style={styles.cardBackground}>
                    <CardItem>
                        <Body>

                            <Image
                                source={require('../../images/pwc_logo.png')}
                                style={styles.logoStyle}
                            />

                            <Item floatingLabel style={styles.floatingItem}>
                                <Label style={styles.input}>UserName</Label>
                                <Input
                                    style={styles.input}
                                    onChangeText={(name) => this.userName = name}
                                    value={this.userName} />
                            </Item>

                            <Item floatingLabel style={styles.floatingItem}>
                                <Label style={styles.input}> Password</Label>
                                <Input secureTextEntry
                                    style={styles.input}
                                    onChangeText={(pwd) => this.password = pwd}
                                    value={this.password} />
                            </Item>

                            <Button
                                full style={styles.button}
                                onPress={this.logIn}>
                                <Text uppercase={false} style={styles.buttonText}>Sign in</Text>
                            </Button>

                            <Button transparent style={styles.forgetPassowrdButton} onPress={this.showForgetPasswordDialog}>
                                <Text uppercase={false} style={styles.forgotPasswordtText}> Forgot Password ? </Text>
                            </Button>

                        </Body>
                    </CardItem>
                </Card>

                <Dialog.Container visible={this.forgetPwdDialogVisible}>
                    <Dialog.Title>Enter your user email</Dialog.Title>
                    <TextInput
                        style={{ marginLeft: 8, marginRight: 8 }}
                        underlineColorAndroid={colors.primary}
                        allowFontScaling={false}
                        textAlignVertical={'top'}
                        multiline={true}
                        editable={true}
                        autoCorrect={true}
                        autoFocus={true}
                        value={this.userEmail}
                        onChangeText={(email) => this.userEmail = email} />
                    <Dialog.Button label="Cancel" onPress={this.handleCancel} />
                    <Dialog.Button label="OK" onPress={this.handleSubmit} />
                </Dialog.Container>

            </ViewWithSpinner>
 
 ** if i am commenting out the card block, login screen is launching fine.

**Comment by VnsCode** [comment]
@mukherjeeraja7 What is that crash you are seeing? I am seeing a typo in one if your styles `forgetPassowrdButton` make sure you have same name in styles file as well

**Comment by hanykumar** [comment]
Hi @mukherjeeraja7 , closing for now due to inactivity. Please let us know if the issue still persists.
