### ISSUE TITLE
Getting warning message after upgrade to RN 0.60

### ISSUE THREAD

**Issue by deepakpm** [GeekyAnts/NativeBase#2847]
warn The following packages use deprecated "rnpm" config that will stop working from next release:
  - native-base: https://github.com/GeekyAnts/NativeBase#readme

Please notify their maintainers about it. You can find more details at https://github.com/react-native-community/cli/blob/master/docs/configuration.md#migration-guide.

Please tell me is this major issue  or we can ignore it

**Comment by sankhadeeproy007** [comment]
Warnings fixed in latest version.
