### ISSUE TITLE
Picker backgroundColor can't be changed dynamically anymore

### ISSUE THREAD

**Issue by cseelus** [GeekyAnts/NativeBase#2853]
## Issue Description

Inside a cascading Picker navigation, we change the Picker `backgroundColor` depending whether its disabled or not, from some dark gray (disabled) to white (!disabled).

After upgrading Native Base from `2.12.1` to `2.13.4` the Picker `backgroundColor` can't be changed dynamically anymore, so we had to downgrade to  `2.12.1` again.

### node, npm, react-native, react and native-base version, expo version if used, xcode version

node v12.7.0
yarn 1.17.3
react 16.8.3
native-base 2.13.4
expo 34

### Expected behaviour

Picker `backgroundColor` style prop can be changed on the fly, as with previous versions of Native Base.

### Actual behaviour

Picker `backgroundColor` style prop can't be changed anymore on the fly.

### Is the bug present in both iOS and Android or in any one of them?

We were only able to test iOS so far.

**Comment by lavender16** [comment]
I have the same issue, only return to 2.12.1 again.
At the same time, Native Base Picker generating “Unsafe legacy lifecycles” , maybe this is the real problem.
**Warning: Unsafe legacy lifecycles will not be called for components using new component APIs.**
Can fix it？

**Comment by PlabanJr** [comment]
Please attach a reproducible snack example.

**Comment by cseelus** [comment]
`2.12.2` (working on iOS): https://snack.expo.io/ry_7BJrDS

`2.13.4` (working on iOS): https://snack.expo.io/rJ1lv1SPH

Seems to be fixed in the latest version (`2.13.8`) though.
