### ISSUE TITLE
How to migrate ejected styles?

### ISSUE THREAD

**Issue by cristianoccazinsp** [GeekyAnts/NativeBase#2854]
After migrating from 2.12.1 to 2.13.4 I found a few style changes (e.g., disabled checkboxes still had the icon). After this, I had to go through every code change to find out what was changed on the platform.js file (which was ejected) and had to manually include all changes to this file (for the checkbox, it was a line containing a few new styles).

I want to believe this is not the right way to do it, and there's an easier way to handle ejected styles. Any ideas?

**Comment by iranmarcius** [comment]
I had to do it too, but I created my own variables file derived from platform.js and used <StyleProvider> to apply it.

Looks like NativeBase Customizer is out of date and the generated variables file doesn't work anymore.

**Comment by cristianoccazinsp** [comment]
So what's the proper way to handle updates? Looks like after we eject a theme, we are pretty much screwed for future updates if we are not careful.

Using a separate file will have the same issue if the theme was ejected.

Should we keep a changelog of anything that can be ejected so changes can be applied more easily?

**Comment by iranmarcius** [comment]
Once they just changed the variables spec, I don't see any big changes coming soon.

That said, I think that we have to keep track of such changes ourselves and make the necessary adaptations for now.

It took a little while ultil I realized the variables file specs changed. Had to see my buttons breaking first. But on the other hand I didn't dig enough into the documentation to see if there was some informtion about breaking changes regarding themes.
