### ISSUE TITLE
CheckBox checkmark is not show/not found

### ISSUE THREAD

**Issue by brambang** [GeekyAnts/NativeBase#2855]
## I have gone through these following points
- []   Check latest documentation: https://docs.nativebase.io/
- []   Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- []   Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- []   Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- []   For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- []   For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

## Issue Description
When we click the checkbox, the checkmark is showing X inside if box, or some device show chinese.
I face this after upgrade Expo SDK 34.0

### Expected behaviour
showing checkmark icon

### Actual behaviour
image not show/found

**Comment by brambang** [comment]
i found the problem, it is because Ionicons LoadAsync.

```
Font.loadAsync({
  ...Ionicons.font
```

i dont know why it's not work anymore, so i try change how to call required font as

```
Font.loadAsync({
  Ionicons: require('@expo/vector-icons/build/vendor/react-native-vector-icons/Fonts/Ionicons.ttf'),
```

solved

**Comment by PlabanJr** [comment]
Can you please attach a reproducible code.

**Comment by dl-husky73** [comment]
Does this font.loadAsync function need to be added if you don't use Expo?   I am having same issue without Expo in RN60.4.

**Comment by dl-husky73** [comment]
Sorry, mine was fixed by manually doing the react-native link.  I thought that wasn't necessary in RN60+ but it is with Native Base.  So all working fine now...

**Comment by PlabanJr** [comment]
@brambang Can you please try [this](https://github.com/GeekyAnts/NativeBase/issues/2855#issuecomment-520230170).

**Comment by PlabanJr** [comment]
Hope [this](https://github.com/GeekyAnts/NativeBase/issues/2855#issuecomment-520464920) solves the issue. Also check out our latest release [v2.12.5](https://github.com/GeekyAnts/NativeBase/releases/tag/v2.13.5).

Thank you!
