### ISSUE TITLE
Picker undefined is not an object: child.props.value

### ISSUE THREAD

**Issue by marcocesarato** [GeekyAnts/NativeBase#2856]
## Issue Description

 I am trying to return Picker.Item from an array but I face an error after upgrade from version 2.12.2 to 2.13.4 before works fine (with same code), this error is only on iOS in my case.

### Version

Native base: 2.13.4
React Native: 0.60.4

### Expected behaviour

Everything should render properly

### Actual behaviour

Error screen error:

`TypeError: undefined is not an object: (evaluating 'child.props.value')`

### Steps to reproduce

```jsx
<Picker>
        <Picker.Item label="Item 0" value="0" />
        {this.state.data.map((values, key) => {
            return (<Picker.Item label={values.label} value={values.value} key={key}/>);
        })}
</Picker>
```

but this for example works:

```jsx
<Picker>
        <Picker.Item label="Item 0" value="0" />
        <Picker.Item label="Item 1" value="1" />
</Picker>
```

### Any other additional info which would help us debug the issue quicker.

Related issues closed: https://github.com/GeekyAnts/NativeBase/issues/983

**Comment by marcocesarato** [comment]
At the moment i found this workaround:

```jsx
render {
    let data = this.state.data;
    data.unshift(<Picker.Item label="Item 0" value="0" />);
    return (
        <Picker>
            {data.map((values, key) => {
                return (<Picker.Item label={values.label} value={values.value} key={key}/>);
            })}
        </Picker>
    );
}
```

**Comment by PlabanJr** [comment]
Please try our latest release [v2.12.5](https://github.com/GeekyAnts/NativeBase/releases/tag/v2.13.5).

**Comment by developer-gerejaku** [comment]
Hi , you're fix it is'nt fixed yet , the picker behaviour is cant accept empty or undefined data . Make sure you pass conditional data when the data is empty just pass **empty array** .
