### ISSUE TITLE
React Hooks Update

### ISSUE THREAD

**Issue by danieloprado** [GeekyAnts/NativeBase#2857]
## I have gone through these following points
- [x]   Check latest documentation: https://docs.nativebase.io/
- [x]   Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x]   Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [x]   Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [x]   For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- [x]   For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

## Issue Description
It's is a proposal, we could migrate to use the new React Hooks Api, it's totally compatible with the current code and it can run side by side, I've created a pull request to demonstrate how simple it is and we could do it component by component with no rush. 

Reasons:
- Better Performance
- Simplify the code
- Easy Maintainability
- With the new **StyleProviderContext** will be easy to third party libs to use the theme variables.

**Comment by sankhadeeproy007** [comment]
@danieloprado That sounds like a great plan. We've been discussing the move to Hooks for a while now and the timing of your PR couldn't have been better!
Will take a look at the PR soon. Also roping in @sanketsahusoft for any inputs.

**Comment by danieloprado** [comment]
Also fix #2832

**Comment by danieloprado** [comment]
@sankhadeeproy007 Thank you! If you move on with this idea I'm glad to help you guys to update the code.

**Comment by Sampath-Lokuge** [comment]
Hi @danieloprado Is this library support React Hooks? It seems not according to the doc? e.g. https://docs.nativebase.io/Components.html#button-def-headref

**Comment by johntimothybailey** [comment]
@Sampath-Lokuge @akhil-geekyants Is this PR not being merged due to https://github.com/GeekyAnts/nativebase-v3

**Comment by TawalMc** [comment]
Hi. What about the migration to React hook of NativeBase? Want to be part of contributor if is possible.
