### ISSUE TITLE
Drawer with Item and Icon locks render

### ISSUE THREAD

**Issue by jalenhunter** [GeekyAnts/NativeBase#2859]
## I have gone through these following points
- [x]   Check latest documentation: https://docs.nativebase.io/
- [x]   Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x]   Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [x]   Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [x]   For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- [x]   For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

## Issue Description
I am trying to use a floatingLabel with an Icon in a Drawer and it locks up the rendering of all components. Using code below I get a white screen. If I remove Icon in the Drawer content it renders fine.

### node, npm, react-native, react and native-base version, expo version if used, xcode version
package.json has the following:
```
"dependencies": {
    "native-base": "^2.13.4",
    "react": "16.8.6",
    "react-native": "0.60.4"
  }
```
### Expected behaviour
Everything should render properly
### Actual behaviour
Screen is blank
### Steps to reproduce
```
import React, {useRef} from 'react'
import { Drawer, Button, Text, Content, Form, Item, Label, Input, Icon } from 'native-base'

const App = () => {
  const drawerRef = useRef()
  const closeDrawer = () => {
    drawerRef.current._root.close()
  };
  const openDrawer = () => {
    drawerRef.current._root.open()
  };
  return (
      <Drawer
          ref={drawerRef}
          content={<Content style={{backgroundColor: '#FFF'}}>
            <Form>
              <Item floatingLabel>
                <Label>Username</Label>
                <Input />
                {/*<Icon active name='home' />*/}
              </Item>
            </Form>
          </Content>}
          onClose={() => closeDrawer()}
      >
        <Button
            onPress={() => openDrawer()}
            hasText
        ><Text>Click Me!</Text><Icon active name='home' /></Button>
      </Drawer>
  );
};

export default App
```
### Is the bug present in both iOS and Android or in any one of them?
Both iOS and Android
### Any other additional info which would help us debug the issue quicker.
When I force a pause in the debugger I see animation related code in the stacktraces. This issue started in 2.12.2 as the code works fine in 2.12.1

**Comment by wesley-harding** [comment]
I'm seeing the same issue (with a very similar setup to above).

It seems to only be affecting Items with a Floating Label. Fixed, Inline, and Stacked work without issue. Floating label results in a white screen with no content rendering.

**Comment by ytimocin** [comment]
I am also seeing the same issue. Not getting a white screen, I can enter text but rendering stops completely.

Part of my code is like this:

`
<FormItem floatingLabel>
              <Label style={styles.label}>
                username
              </Label>
              <Input onChangeText={this.onChangeUsername}/>
              {
                this.state.username !== null &&
                <Icon active type="FontAwesome" name='swap'/>
              }
            </FormItem>
`

**Comment by temitope** [comment]
seeing same white screen/freeze behavior, but no explicit error, so it is a bad freeze.

as @wesley-harding pointed out, i am only seeing this when using the `floatingLabel` attribute for the parent Item component.

**Comment by temitope** [comment]
for me, the issue crept up in v2.13.4.
reverting back to 2.12.1, while less than ideal, seems to fix the issue. will traverse logs to see how far i can update before the break.

**Comment by PlabanJr** [comment]
This issue has been taken care of in our latest release [v2.12.5](https://github.com/GeekyAnts/NativeBase/releases/tag/v2.13.5). Please try it out!

Thank you for reporting!

**Comment by sajadghawami** [comment]
I am still having this issue with the latest version 2.13.X
