### ISSUE TITLE
Drawer docs not clear[docs]

### ISSUE THREAD

**Issue by mufaddalhamidofficial** [GeekyAnts/NativeBase#2862]
Docs are not properly made for Drawer-Native Base

![image](https://user-images.githubusercontent.com/49232863/62774918-da938200-bac3-11e9-9000-d5802bf0184b.png)

**Comment by PlabanJr** [comment]
Correction has been done and it will reflect in the next publish. So closing the issue!

**Comment by mufaddalhamidofficial** [comment]
@PlabanJr still not updated
