### ISSUE TITLE
Content - Use SafeAreaView from RN 60

### ISSUE THREAD

**Issue by cristianoccazinsp** [GeekyAnts/NativeBase#2863]
Replace all the manual calculations with SafeAreaView. Not only this would make the code easier, but it will also fix <Content> padding when being used without a <Header> component (which is the one that adds the top padding)

**Comment by PlabanJr** [comment]
Hello @cristianoccazinsp , thank you for your suggestion. We have removed the manual calculations and added `SafeAreaView` instead. Please check out our latest release [v.2.12.5](https://github.com/GeekyAnts/NativeBase/releases/tag/v2.13.5).

**Comment by cristianoccazinsp** [comment]
Hi @PlabanJr , would it be possible to add a setting to actually disable it? Or what would be the recommended way?

After this update, I got a few broken screens due to this change. This is mostly related when no Header is used where I want the content to use all the screen, even with safe areas, but I don't really want to fallback to using a regular View or ScrollView.

**Comment by cristianoccazinsp** [comment]
@PlabanJr  one more thing which might be a good idea to re-open this. After doing the update and removing my own SafeAreaView components, it seems like there's a small inconsistency between Android and IOS.

If you use ```<Content padder> .. </Content>```, on Android, you will get the padding between the top bar/status bar, but on IOS the padding will start from the top of the phone (and not the status bar height); hence, resulting in no padding at all on devices that have no Notch.

Should <Content> add an extra padding to account of the status bar height of IOS? This only seem to be an issue if no <Header> is used.
