### ISSUE TITLE
Ejected theme folder breaking vscode TS intellisense

### ISSUE THREAD

**Issue by saggiyogesh** [GeekyAnts/NativeBase#2864]
"react": "16.8.6",
"react-native": "0.60.4",
"native-base": "^2.13.4",
No Expo

After ejecting the theme as mentioned in this link https://docs.nativebase.io/Customize.html#theaming-nb-headref
Following code is breaking VSCode Typescript intellisense. 

```
import getTheme from '../../theme/components';

const theme = getTheme();
```

**Comment by aneesh2693** [comment]
@saggiyogesh
I also faced the same issue. Vscode intellisense just stopped working and I know the culprit is native base as itwas the last plugin i added. It  was very very frustrating.
The solution I found is that, you need to exclude the ejected native base folder 'native-base-theme' from VSCode intellisense by adding it in jsconfig.json file. Also close all the files and restart VSCode.

Example:
`{
    "compilerOptions": {
        "target": "ES6",
        "module": "commonjs",
        "baseUrl": ".",
        "paths": {
        }
    },
    "exclude": [
        "node_modules",
        "native-base-theme"
    ]
}`

You can find the method here in the  [official documentation](https://code.visualstudio.com/docs/languages/jsconfig) 

Happy Coding

**Comment by saggiyogesh** [comment]
@aneesh2693 Tried already what you've mentioned. I'm developing in TS. 
What happens after opening the file which is importing the `theme/components`, TS IntelliSense and every other VScode smart features stop working.

**Comment by aneesh2693** [comment]
@saggiyogesh Unfortunately I was facing this issue again. So the best I did right now is that define the style provider in the project's main index.js file and forget about it. Just don't open that file. My VScode and CPU is stable now.
Try this thing.

**Comment by saggiyogesh** [comment]
@aneesh2693 
Did this https://github.com/GeekyAnts/NativeBase/issues/2849#issuecomment-520047638
So now no more calculations by calling `getTheme`, as json file will get cached in require cache.

**Comment by aaronfg** [comment]
Any word on an official fix coming for this?

Having to do a separate file with theme vars that I can never open or my IDE blows up is a pretty bad solution.

**Comment by codelizrd** [comment]
Got the same problem with IntelliJ Webstorm: the typescript compiler (run through 'yarn tic') won't return and it seems it's stuck in a loop. 

Excluding the native-base-theme directory and not importing/referencing it from a compiled file makes it work again, but is not ideal...

**Comment by naxir** [comment]
Hello @saggiyogesh  .vscode/settings.json
and add this setting
"typescript.disableAutomaticTypeAcquisition": true

Your issue will be fixed 

Cheers
Happy Coding
You are the boss!

**Comment by saggiyogesh** [comment]
Cool, But now moved to other options like react-native-elements due to its small size.

**Comment by smithkre** [comment]
After I was trying to fix this problem. After I change this row my CPU went normal.

In **commonColor.js** I remove this code.
`export const PLATFORM = {
  ANDROID: 'android',
  IOS: 'ios',
  MATERIAL: 'material',
  WEB: 'web'
};`

Then replace all `PLATFORM.IOS` variable by string `'ios'`. Then `Cmd + Shift + P` to restart TS Server

<img width="249" alt="Screen Shot 2563-01-30 at 15 48 35" src="https://user-images.githubusercontent.com/5935688/73433770-fc393c00-4377-11ea-9501-ffcd12f232af.png">

It's work!

**Comment by madebyclint** [comment]
A quick fix for me was to just change the StyleProvider snippet to:

`<StyleProvider style={getTheme(material as any)}>`

Hope that helps.

**Comment by hanykumar** [comment]
Hi @saggiyogesh , please provide more information regarding the issue like, steps to reproduce and its outcome.
