### ISSUE TITLE
renderEmpty property in DeckSwiper is not defined in d.ts

### ISSUE THREAD

**Issue by extracold1209** [GeekyAnts/NativeBase#2865]
## I have gone through these following points
- [x]   Check latest documentation: https://docs.nativebase.io/
- [x]   Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x]   Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [x]   Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [x]   For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- [x]   For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

## Issue Description

renderEmpty in DeckSwiper property exists but not in index.d.ts

### node, npm, react-native, react and native-base version, expo version if used, xcode version
node : v10.15.0
npm : v6.4.1
react-native : 0.59.9
react : 16.8.3
native-base : 2.13.4

### Expected behaviour
DeckSwiper interface should be include renderEmpty property

### Actual behaviour
not included

### Is the bug present in both iOS and Android or in any one of them?
in typescript
### Any other additional info which would help us debug the issue quicker.
https://github.com/GeekyAnts/NativeBase/blob/3a6c6394b4c908cf24f4dc18a6248c94bece06ab/index.d.ts#L75-L94

**Comment by PlabanJr** [comment]
Hello @extracold1209 , thank you for your suggestion. Please check out our latest release [v.2.13.5](https://github.com/GeekyAnts/NativeBase/releases/tag/v2.13.5), `renderEmpty` and `renderButton` has been added to the `index.dts` file.
