### ISSUE TITLE
SwipeRow: TypeError: Cannot read property 'panHandlers' of undefined

### ISSUE THREAD

**Issue by batuhanoztrk** [GeekyAnts/NativeBase#2866]
![Simulator Screen Shot - iPhone X - 2019-08-11 at 18 36 48](https://user-images.githubusercontent.com/34206290/62835986-1b77cc00-bc67-11e9-88f1-580c92c093f6.png)

package.json:
`{
  "name": "ProjectYY",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "@react-native-community/geolocation": "^1.4.2",
    "mobx": "^5.13.0",
    "mobx-persist": "^0.4.1",
    "mobx-react": "^6.1.3",
    "native-base": "^2.13.4",
    "react": "16.8.6",
    "react-native": "0.60.4",
    "react-native-axios": "^0.17.1",
    "react-native-device-info": "^2.3.2",
    "react-native-geocoding": "^0.3.0",
    "react-native-gesture-handler": "^1.3.0",
    "react-native-google-places": "^3.1.2",
    "react-native-image-picker": "^1.0.2",
    "react-native-modal": "^11.3.1",
    "react-native-reanimated": "^1.2.0",
    "react-native-safe-area-view": "^0.14.7",
    "react-navigation": "^3.11.1"
  },
  "devDependencies": {
    "@babel/core": "7.5.5",
    "@babel/plugin-proposal-decorators": "^7.4.4",
    "@babel/runtime": "7.5.5",
    "@react-native-community/eslint-config": "0.0.3",
    "babel-jest": "24.8.0",
    "eslint": "^6.1.0",
    "jest": "24.8.0",
    "metro-react-native-babel-preset": "0.54.1",
    "react-test-renderer": "16.8.6"
  },
  "jest": {
    "preset": "react-native"
  }
}
`

**Comment by sayem314** [comment]
I have made a pull request #2840 few days ago that fix this. But no one cares.

**Comment by sankhadeeproy007** [comment]
@sayem314 SwipeRow has been removed from native-base v2.13.0 onwards.

**Comment by sayem314** [comment]
Was it really removed? This recent PR https://github.com/GeekyAnts/NativeBase/commit/85a52b1e0ba09d4eb45c2aaaa0916199b4e3653d broke the actual functionality.

**Comment by sankhadeeproy007** [comment]
It was removed with [this](https://github.com/GeekyAnts/NativeBase/releases/tag/v2.13.0) release.
But we decided to keep the code in there in case someone wants to fork and keep using.
The existing code will be removed in a future release.

**Comment by sankhadeeproy007** [comment]
If you can make a PR which removes the dependency on ListView, we might consider adding it back it.
