### ISSUE TITLE
Android Form Scroll

### ISSUE THREAD

**Issue by jeremiahk** [GeekyAnts/NativeBase#2870]
## I have gone through these following points
- [x]   Check latest documentation: https://docs.nativebase.io/
- [x]   Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x]   Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [x]   Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [x]   For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- [x]   For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

## Issue Description
"native-base": "^2.13.4",
"react": "16.8.6",
"react-native": "0.60.4"

### Expected behaviour
I am using the form components, Container, Form, Item and Input to build a simple form. When I set the Inputs textAlign property to right the container will no longer scroll. This only effects Android, not iOS.

If I remove the right align property everything works fine. You can see the issue in the example. 

![Example of issue](https://github.com/jeremiahk/nativeBaseScrollIssue/blob/master/Scroll%20Issue.gif?raw=true)

I did find an old issue [#290](https://github.com/GeekyAnts/NativeBase/issues/290) but there is not much info in the ticket. 

### Steps to reproduce
[Here](https://github.com/jeremiahk/nativeBaseScrollIssue) is a repo with the issue. 

### Is the bug present in both iOS and Android or in any one of them?
This is only present on Android. Not on iOS

**Comment by PlabanJr** [comment]
Hello, @jeremiahk! I was looking into the issue and found a same issue with React Native. Have you checked [this](https://github.com/facebook/react-native/issues/16206) before?

**Comment by jeremiahk** [comment]
Thanks for the link. I will take a look.

**Comment by jeremiahk** [comment]
Thanks for the link. Making the input multiline fixed the issue.
