### ISSUE TITLE
Accordion Content text is malformed

### ISSUE THREAD

**Issue by yazmnh87** [GeekyAnts/NativeBase#2874]
## I have gone through these following points
- []   Check latest documentation: https://docs.nativebase.io/
- []   Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- []   Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- []   Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- []   For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- []   For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

## Issue Description
Text is malformed in accordion; text is cut off in certain areas. 

### node, npm, react-native, react and native-base version, expo version if used, xcode version

node version- v10.15.0
npm version- 6.9.0
react-native version - 0.60.3
react version - 16.8.6
native-base version - 2.13.3
xcode version - 10.2

### Expected behaviour
Text is rendered properly without being cut off
### Actual behaviour
Text is being cutoff in certain areas only showing half the line of text, see pictures attached.
![native_base_picture](https://user-images.githubusercontent.com/25097299/63044207-f794d000-be8a-11e9-8fe8-59e37fc7640c.png)

### Steps to reproduce
Exporting content array as array of objects with properties "title" and "content" properties are type string.
- export const disclaimerData= [
    {
        title: "Disclaimer",
        content: "Clicking this box shows you agree that all information entered or collected in this app is self reported and meant for tracking, trending, and display for personal use. You understand that any information and content such as text, graphics, and images found within our Website is for general educational, entertainment, and informational purposes only. You understand that such 
- Include code snippet in preformatted mode (```code```) and not in screenshot.
- In case of lengthy code, then cut down into simple screen.
- importing array into component with accordion

import { Accordion } from "native-base";
import { disclaimerData } from "./disclaimerData";
 <Accordion dataArray={disclaimerData} expanded={2} headerStyle={{ backgroundColor: "#fff" }}
            contentStyle={{ backgroundColor: "#fff", color: "#000" }}/>

### Is the bug present in both iOS and Android or in any one of them?
Only developing in IOS at the moment.

**Comment by PlabanJr** [comment]
@yazmnh87 Can you please try `v2.13.4` and confirm the issue persists?

**Comment by yazmnh87** [comment]
> @yazmnh87 Can you please try `v2.13.4` and confirm if the issue persists?

Upgrade unfortunately did not fix the issue, this issue is on IOS only it appears.

**Comment by sankhadeeproy007** [comment]
@yazmnh87 Can you try giving the text some lineHeight style to see if this issue is fixed?

**Comment by yazmnh87** [comment]
> @yazmnh87 Can you try giving the text some lineHeight style to see if this issue is fixed?
This did in fact resolve it.  Thank you for your insight and help.  Take care.
