### ISSUE TITLE
Using Icon inside Item with floatingLabel hangs the app.

### ISSUE THREAD

**Issue by iranmarcius** [GeekyAnts/NativeBase#2875]
## I have gone through these following points
- [x]   Check latest documentation: https://docs.nativebase.io/
- [x]   Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x]   Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [x]   Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [x]   For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- [x]   For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

## Issue Description
I think I found a bug related to the use of `<Item floatingLabel>` in conjunction with `<Icon/>`

### node, npm, react-native, react and native-base version, expo version if used, xcode version
node 10.16.2
npm 6.10.3
react 16.8.3
react-native: 0.59.8
native-base 2.13.4
expo 34.0.3

### Expected behaviour
The app to be rendered.

### Actual behaviour
Rendering is hanging.

### Steps to reproduce
This is a simple application created with expo. I only changed the main app. To reproduce the problem change const 'float' to true.

```
import React from 'react';
import {Root, Container, Header, Form, Label, Item, Input, Text, Icon} from 'native-base';

const float = false;

export default function App() {

    return (
        <Root>
            <Header/>
            <Container>
                <Text>Any text</Text>
                <Item floatingLabel={float}>
                    <Label>Field label</Label>
                    <Input/>
                    <Icon type='Ionicons' name='md-eye'/>
                </Item>
            </Container>
        </Root>
    );

}

```
### Is the bug present in both iOS and Android or in any one of them?
Yes.

### Additional information
I tried to downgrade native-base to 2.13.0 but no success. The problem started after update from 2.12.1.

**Comment by temitope** [comment]
confirmed. same behavior. happens after 2.12.1

**Comment by PlabanJr** [comment]
[This](https://github.com/GeekyAnts/NativeBase/pull/2872) has been merged and is available in our latest release [v.2.13.5](https://github.com/GeekyAnts/NativeBase/releases/tag/v2.13.5). This should resolve the issue. 

Thank you for reporting!

**Comment by iranmarcius** [comment]
Just tested the new release. Problem solved. Thanks for the great work.
