### ISSUE TITLE
Update react-native-keyboard-aware-scroll-view dependency

### ISSUE THREAD

**Issue by cristianoccazinsp** [GeekyAnts/NativeBase#2879]
## I have gone through these following points
- []   Check latest documentation: https://docs.nativebase.io/
- []   Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- []   Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- []   Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- []   For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- []   For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

## Issue Description
Current version is 0.8.0. I don't think there are any important changes in 0.9.1, but the release fixes a few warnings that might become annoying while debugging with RN 60.

**Comment by sankhadeeproy007** [comment]
Fixed in 2.13.7
