### ISSUE TITLE
Picker on IOS

### ISSUE THREAD

**Issue by sagarparikh** [GeekyAnts/NativeBase#288]
I am facing one issue with NativeBase.. Basically my requirement is to load the values of the Picker within native base from the server side. So on the first Render cycle there are no children to the Picker, i get the attached error because it makes the selected item as the label on the first instance. Is there any way to get around this. Also I do not want to have a default value set want to have some placeholder text what are the options.

![screen shot 2016-11-12 at 7 45 27 pm](https://cloud.githubusercontent.com/assets/1863784/20238611/6e3d984c-a915-11e6-8e82-74657768ca3c.png)

**Comment by himanshu-satija** [comment]
You can do something like this
```jsx
render() {
  var data = [];
  return (
    <Container>
      <Header>
        <Button>
          sefesf
        </Button>
      </Header>
      <Content>
        {data.length > 0 ?
          <Picker
            iosHeader="Select one"
            mode="dropdown"
            selectedValue={this.state.selected1}
            onValueChange={this.onValueChange.bind(this)}>
            {data.map((val, index) => {
              return <Item key={index} label={val} value={val} />
            })}
          </Picker> : <Text>Placeholder text</Text>}
      </Content>
    </Container>
  );
}
```

This will render Picker conditionally based on the length of array which is populated from server side. If array is empty, you can show another component which displays your placeholder text

**Comment by chetnadaffodil** [comment]
Hi

This is my code to render items dynamically. State states is an array of states.
But it's throwing an exception. 

![screen shot 2016-12-05 at 5 27 45 pm](https://cloud.githubusercontent.com/assets/17562095/20884214/ebf6707c-bb0f-11e6-99fe-b4aeecf8b710.png)
![screen shot 2016-12-05 at 1 11 21 pm]
(https://cloud.githubusercontent.com/assets/17562095/20884234/fff0aa34-bb0f-11e6-9eca-52c75b7fdc6d.png)
