### ISSUE TITLE
Icons issue after 2.13.5

### ISSUE THREAD

**Issue by cristianoccazinsp** [GeekyAnts/NativeBase#2880]
## I have gone through these following points
- [x]   Check latest documentation: https://docs.nativebase.io/
- [x]   Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x]   Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [x]   Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [x]   For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- [x]   For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

## Issue Description

After migrating from 2.13.4, some icons stopped working randomly, or are returning the wrong icons. As seen in the captures below, the icons simply change after a re-render of the screen, but the icon name and type haven't changed at all!

### node, npm, react-native, react and native-base version, expo version if used, xcode version
"react": "16.9.0",
"react-native": "0.60.5",

### Expected behaviour
Icons should remain consistent after each re render

### Actual behaviour
Icons randomly break after a re-render

### Steps to reproduce
Simply re-render a screen with small changes to the UI but same icons.

### Is the bug present in both iOS and Android or in any one of them?
Both

### Any other additional info which would help us debug the issue quicker.
Didn't happen in 2.13.4

Captures:
First render / second render of the same screen
<img width="351" alt="Screen Shot 2019-08-16 at 13 29 24" src="https://user-images.githubusercontent.com/48869228/63183142-a3c0ed00-c02a-11e9-8d36-388a00c32f29.png">
<img width="359" alt="Screen Shot 2019-08-16 at 13 29 33" src="https://user-images.githubusercontent.com/48869228/63183145-a7ed0a80-c02a-11e9-8da3-2c62005087c8.png">

This case is odd, the two camera icons should be the same, but they are not.
<img width="371" alt="Screen Shot 2019-08-16 at 13 30 26" src="https://user-images.githubusercontent.com/48869228/63183163-b5a29000-c02a-11e9-981e-36f5c1430d75.png">
<img width="360" alt="Screen Shot 2019-08-16 at 13 29 57" src="https://user-images.githubusercontent.com/48869228/63183170-baffda80-c02a-11e9-97db-92fbee0966e1.png">

Note: I have already re-linked everything and cleaned up the build folders. Same issues still.

**Comment by cristianoccazinsp** [comment]
This 1 line change broke it all: https://github.com/GeekyAnts/NativeBase/compare/v2.13.4...v2.13.5#diff-3fd8713c7fac5880d02c24b431eca322R31

Reverting the change makes icons work again. Either use UNSAFE_componentWillUpdate (to avoid the warning), or re-think the lifecycle method being used. Whatever you do, please avoid calling setState again to trigger a re-render!

**Comment by darekg11** [comment]
I am experiencing similar issue on `v.2.13.5`

**Comment by cristianoccazinsp** [comment]
Hopefully this can be hotfixed in a new minor release, Icons are pretty much unusable in this release.

**Comment by lifenautjoe** [comment]
This is still an issue. The icons get switched up. 

![image](https://user-images.githubusercontent.com/12737509/93187674-57217700-f740-11ea-82fb-465cb91723f1.png)
