### ISSUE TITLE
Floating Input with right Icon hangs Simulator on iOS and Android

### ISSUE THREAD

**Issue by imbudhiraja** [GeekyAnts/NativeBase#2888]
## I have gone through these following points
- []   Check latest documentation: https://docs.nativebase.io/
- []   Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- []   Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- []   Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- []   For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- []   For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

## Issue Description
I'm trying to use Floating Input with right icons but it hangs the simulator on iOS as well as on Android.

react-native - v0.60.5, 
react - v16.8.6 
native-base - v2.13.4
xCode - v10.3.1
Android Studio - v3.4.1
react-native-cli - v2.0.1

### Expected behaviour
It should show icon on right.

### Actual behaviour
Simulator hangs

### Steps to reproduce
```
import React, { Component } from 'react';
import { Container, Header, Content, Item, Input, Icon } from 'native-base';

export default class SuccessInputTextboxExample extends Component {
  render() {
    return (
      <Container>
        <Header />
        <Content>
          <Item floatingLabel success>
            <Input placeholder='Textbox with Success Input' />
            <Icon name='checkmark-circle' />
          </Item>
        </Content>
      </Container>
    );
  }
}

```

Thanks

**Comment by PlabanJr** [comment]
Please try with the latest version, v2.12.5.

**Comment by Aleksandern** [comment]
@PlabanJr 
v2.13.5 doesn't have this issue. 
Thanks.
