### ISSUE TITLE
Checkbox shows black tick when not selected

### ISSUE THREAD

**Issue by imbudhiraja** [GeekyAnts/NativeBase#2891]
## I have gone through these following points
- []   Check latest documentation: https://docs.nativebase.io/
- []   Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- []   Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- []   Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- []   For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- []   For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

### node, npm, react-native, react and native-base version, expo version if used, xcode version
react-native - v0.60.5
native-base - v2.13.5

### Expected behaviour
It should show blank no tick box

### Actual behaviour
It shows black tick

### Steps to reproduce

```
<CheckBox
   style={{ borderColor: type.checked ? 'blue' : 'black' }}
  checked={false}
  color={'blue'}
  onPress={() => true}
/>               
```

### Is the bug present in both iOS and Android or in any one of them?
Yes
### Any other additional info which would help us debug the issue quicker.
[
![Simulator Screen Shot - iPhone X - 2019-08-23 at 13 03 00](https://user-images.githubusercontent.com/22340444/63576624-35d87080-c5aa-11e9-9bb6-182501c56428.png)
](url)

**Comment by imbudhiraja** [comment]
@SupriyaKalghatgi please check

**Comment by OrLavy** [comment]
I also experience the same problem

**Comment by RioFiveJack** [comment]
yep same issue, this occurs after upgrading to 2.13.x

**Comment by imbudhiraja** [comment]
@digitalalien i already have `"checkboxDefaultColor": "transparent"` in my `variable.js`.

**Comment by imbudhiraja** [comment]
yes @digitalalien i'm using style provider after ejecting the theme

**Comment by imbudhiraja** [comment]
@digitalalien yes it was overridden in `variable.js>material.js`. thanks. But this needs to be fixed in library itself.

**Comment by OrLavy** [comment]
As a temp solution, you can add a them variable named 'checkboxDefaultColor'.

Make sure it suits the ' containerBgColor' though.

There should really be a tool or at lest documentation for the changes in the theme variables between versions...

**Comment by sirajalam049** [comment]
Same solution. I just need to do it in my platform.js file.

**Comment by lpaz010** [comment]
@digitalalien Thank you for the solution. 
I solve this by adding  `"checkboxDefaultColor": "transparent"` to `variables>commonColor.js` with version `"native-base": "^2.13.12"`.

**Comment by nullmicgo** [comment]
I am using  "native-base": "2.13.8" with "checkboxDefaultColor": "transparent" inside variables>commonColor.js.

Checkbox still shows black tick when not selected.

Need some help

**Comment by unitedpalletnetwork** [comment]
I found that re-ejecting the theme fixed it for me: https://docs.nativebase.io/Customize.html#theaming-nb-headref .

**Comment by 28harishkumar** [comment]
updating `checkboxDefaultColor` didn't work for me.

I had to add `style={{ backgroundColor: "#ffffff" }}`
