### ISSUE TITLE
Ability to change CheckBox Icons

### ISSUE THREAD

**Issue by imbudhiraja** [GeekyAnts/NativeBase#2892]
## I have gone through these following points
- []   Check latest documentation: https://docs.nativebase.io/
- []   Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- []   Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- []   Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- []   For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- []   For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

## Feature Description
I need to use diff kind of check box for my application, there is no way to change checkbox icon.

Thanks

**Comment by sankhadeeproy007** [comment]
No, as of now custom icons for checkboxes are not supported.

**Comment by liaoyinglong** [comment]
@sankhadeeproy007  have a plan to implement this feature?

maybe i can contribute
