### ISSUE TITLE
Header  Android

### ISSUE THREAD

**Issue by ofancn** [GeekyAnts/NativeBase#2894]
<img width="471" alt="WX20190823-174137@2x" src="https://user-images.githubusercontent.com/38897378/63583371-74335700-c5cd-11e9-968b-667790752b9a.png">
<img width="433" alt="WX20190823-174243@2x" src="https://user-images.githubusercontent.com/38897378/63583373-74335700-c5cd-11e9-964d-3f42d413e390.png">

iOS normal

**Comment by sankhadeeproy007** [comment]
https://docs.expo.io/versions/latest/guides/configuring-statusbar/#working-with-3rd-party-libraries
