### ISSUE TITLE
[IOS] Floating label has incorrect styles when rendering an input with an initial value

### ISSUE THREAD

**Issue by aroucha-miguel** [GeekyAnts/NativeBase#2895]
## I have gone through these following points
- [X]   Check latest documentation: https://docs.nativebase.io/
- [X]   Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [X]   Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [X]   Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink

## Issue Description
When `<Input />` is initialized with a value, the floating label starts with styles associated as an empty value. Upon clicking on the input, the floating label 'flicks' to its correct styling.
It seems this is only happening on IOS, on Android it seems fine.

This seems to have started happening on version `2.12.2` and is still happening on most recent version `2.13.5`. on version `2.12.1` the floating label acts as expected

sharing a minimal example snack URL exampling the problem:
https://snack.expo.io/rkWtoq64H
(if you run the ios simulator within snack example, the bug only happens if you change `The label` to anything else after the simulator loaded the app)

### Expected behaviour
The floating label starts with correct styles

### Actual behaviour
The floating label starts with incorrect styles

### Steps to reproduce
```
import * as React from 'react';
import { StyleSheet } from 'react-native';
import {
  Item,
  Label,
  Input,
  Root,
  View,
} from 'native-base';

export default class App extends React.Component {
  render() {
    return (
      <Root>
        <View style={styles.container}>
          <Item floatingLabel>
            <Label>
              The label
            </Label>
            <Input
              value="hello"
            />
          </Item>
        </View>
      </Root>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    backgroundColor: '#ecf0f1',
    padding: 8,
  },
});
```

### Is the bug present in both iOS and Android or in any one of them?
Seems to be only happening on IOS

### Any other additional info which would help us debug the issue quicker.
--

**Comment by aroucha-miguel** [comment]
2.12.1 | 2.13.5
------------ | -------------
![native_base_floating_label_2 12 1 mov](https://user-images.githubusercontent.com/22522935/63683084-5cd4b380-c7f1-11e9-90c2-3239f2af46dc.gif) | ![native_base_floating_label_2 13 5 mov](https://user-images.githubusercontent.com/22522935/63683102-68c07580-c7f1-11e9-9fd7-b6bd2467190b.gif)

**Comment by sankhadeeproy007** [comment]
Hi, thanks for reporting. Will take a look at this one.

**Comment by aroucha-miguel** [comment]
Thanks. Also, I found this issue that seems pretty related: https://github.com/GeekyAnts/NativeBase/issues/2899

**Comment by huzaifaaak** [comment]
Getting this issue :/ Tried giving `lineHeight:0 ` to label but it doesn't fix it
