### ISSUE TITLE
<Content /> component styling issues 2.13.5

### ISSUE THREAD

**Issue by chriscraiclabs** [GeekyAnts/NativeBase#2896]
## Issue Description

When upgrading from ` "native-base": "2.13.4"` to ` "native-base": "2.13.5"` the `<Content />` component no longer take up 100% of the screen in iPhone x/xs (anything with notch). 

###  Versions
` "native-base": "2.13.5"`
`    "react": "16.9.0",`
`    "react-native": "0.60.5",`
### Expected behaviour

Map takes up fullscreen

![Screenshot 2019-08-23 at 18 15 24](https://user-images.githubusercontent.com/28810867/63610945-a4c9bf80-c5d2-11e9-8c94-675b9d250e78.png)

### Actual behaviour

![Screenshot 2019-08-23 at 18 08 10](https://user-images.githubusercontent.com/28810867/63610965-ae532780-c5d2-11e9-9e5a-2ca229955611.png)

### Example Component

```
<Content
          contentContainerStyle={styles.contentContainerStyle}
          scrollEnabled={false}
        >
          <ImageBackground style={styles.background} source={background}>
            <View style={styles.iconView}>
              <Image style={styles.icon} resizeMode="contain" source={logo} />
            </View>
            <View style={styles.mainContentView}>
                  ...
            </View>
          </ImageBackground>
        </Content>
```

Styles

```
import { StyleSheet } from 'react-native';
import { Theme } from '../../config';

export default StyleSheet.create({
  background: {
    flex: 1,
  },

  contentContainerStyle: {
    flex: 1,
  },

  iconView: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingTop: 30,
    flex: 1.2,
  },

  icon: {
    height: '100%',
  },

  mainContentView: {
    flex: 8.8,
  },
```

Thanks

**Comment by sankhadeeproy007** [comment]
Hey, this has been introduced with [this](https://github.com/GeekyAnts/NativeBase/commit/01027f79c90881bdf1866176e62346429dff4d01) commit. 
If you do intend to have the full screen available, just replace Content with ScrollView from react-native and we should be good to go.

**Comment by Aryk** [comment]
Why does "Content" stop short on the bottom? Isn't Content supposed to be a ScrollView itself. Why is there a limit there that we cannot overright with like "height: 100%" or something like that.

**Comment by ThePJMP** [comment]
> Why does "Content" stop short on the bottom? Isn't Content supposed to be a ScrollView itself. Why is there a limit there that we cannot overwrite with like "height: 100%" or something like that.

@Aryk you can use contentContainerStyle prop with a flexGrow: 1 style to solve that
