### ISSUE TITLE
Picker on IOS in landscape mode rotates to portrait after selecting item

### ISSUE THREAD

**Issue by anniekvandijk** [GeekyAnts/NativeBase#2897]
## I have gone through these following points
- [x]   Check latest documentation: https://docs.nativebase.io/
- [x]   Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x]   Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [x]   Check examples from NativeBase KitchenSink

## Issue Description
Open app in Landscape mode and go to Picker.
Click Picker, new screen with options opens.
Select an option from the Picker items in the new screen.

### node, npm, react-native, react and native-base version, expo version if used, xcode version
    "expo": "^34.0.4",
    "native-base": "^2.13.5",
    "react": "^16.8.3",
    "react-native": "^0.59.8",

### Expected behaviour
After selecting an option you return to the main screen in the orientation you were before (Landscape)

### Actual behaviour
App orientation is set to Portrait.

### Steps to reproduce
```
import React, { useState, useEffect } from 'react';
import {
  Body, Right, Left, Icon, Header, Button, Title, Picker, View
} from 'native-base';

function LanguagePicker() {
  const [language, setLanguage] = useState( 'nl');

  function handleChangeLanguage(value) {
    setLanguage(value);
  }

  return (
    <View style={{flex: 1, height: '100%', justifyContent: 'center'}}>
    <Picker
      mode="dropdown"
      iosHeader="Select language"
      iosIcon={<Icon name="arrow-down" />}
      placeholder="Select language"
      placeholderStyle={{ color: '#000' }}
      style={{ width: '100%' }}
      itemTextStyle={{ color: '#000000' }}
      selectedValue={language}
      onValueChange={value => handleChangeLanguage(value)}
    >
      <Picker.Item label="Nederlands" key="0" value="nl" />
      <Picker.Item label="English" key="1" value="en" />
    </Picker>
    </View>
  );
}

export default LanguagePicker;
```

### Is the bug present in both iOS and Android or in any one of them?
Only IOS, and only when in Landscape.

I tested this also on snack.expo (with own device, snack has only portrait mode!). Here is link to code: https://snack.expo.io/@anniekvandijk/language-dropdown

**Comment by 100phel** [comment]
I'm also having this issue.

**Comment by sankhadeeproy007** [comment]
Hi, thanks for the report. Any chance you can confirm if this existed in an earlier version of native-base as well?

**Comment by anniekvandijk** [comment]
I do not know. It's my first time I used native-base for a project i just started. Sorry...

**Comment by sankhadeeproy007** [comment]
![modal](https://user-images.githubusercontent.com/10998047/64166969-e0cc1280-ce65-11e9-8756-2505ceadcb49.gif)
Tested on react-native `60.5`. 
Are you sure it's not an expo issue?

**Comment by anniekvandijk** [comment]
Now I think you are right. Did not think of Expo for this Issue. I do not have an apple dev account yet, so I could not test this with a build. Thx for testing 😊👍. 

I will post the issue in the Expo repo.

**Comment by aav7fl** [comment]
> Now I think you are right. Did not think of Expo for this Issue. I do not have an apple dev account yet, so I could not test this with a build. Thx for testing 😊👍.
> 
> I will post the issue in the Expo repo.

Did you ever open a ticket in the Expo repo? I'm having the same issue with an Expo project of mine and haven't yet determined if it's Expo or React Native.

**Comment by hanykumar** [comment]
Hi @anniekvandijk , as we have tested it and found no issue, closing this now. Let us know if the issue still persists.
