### ISSUE TITLE
Requiring unknow module ReactNativePropRegistry

### ISSUE THREAD

**Issue by chris-gsj** [GeekyAnts/NativeBase#29]
I'ḿ trying native-base in a new react-native android project on linux, i follow the instructions and with out native-base the app works, but when i add components from native-base send me an error:

Requiring unknow module "react-native/Libraries/ReactNative/ReactNativePropRegistry".If you are sure the module is there, try restarting the packager or running "npm install".

**Comment by sankhadeeproy007** [comment]
Which version of RN are you using?
Native base supports upto 25.1 as of now.

**Comment by chris-gsj** [comment]
is the 26.1 version, so thats why ... mmm well i'm gonna try with 25.1, thank you, i hope in future versions fix it

**Comment by jgable** [comment]
Maybe update the docs then?

<img width="867" alt="screen shot 2016-05-28 at 4 16 55 pm" src="https://cloud.githubusercontent.com/assets/164497/15630431/a28a71b0-24ef-11e6-90dc-9b23d04bd3ba.png">

**Comment by sankhadeeproy007** [comment]
RN 0.26 supported with latest update.

**Comment by warka0** [comment]
Same problem on 0.27 of React Native !

**Comment by himanshu-sahusoft** [comment]
@warka0 Which version of NativeBase are you using?

**Comment by warka0** [comment]
Forget, it've downgrade to 0.26 and it's working. It seems the problem come from having 0.27 with the current version of NativeBase.

**Comment by shadowzick** [comment]
I'm on v0.33.1 and i'm getting this error.
