### ISSUE TITLE
Android Form based Scroll

### ISSUE THREAD

**Issue by sagarparikh** [GeekyAnts/NativeBase#290]
Hi All,

I am facing an issue while scrolling through Text Inputs on Android. When i am trying to scroll basically the TextInput gets focus thereby not letting page scroll freely. This only happens on Android only. Does anybody have a similar issue?

Attaching the files here to replicate the issue. 

Steps to reproduce.

1. Checkout https://github.com/GeekyAnts/NativeBase-KitchenSink
2. Copy & Replace the attached files in the **js/form** folder.
3. Run the app and select Form section from Hamburger menu.

Any help appriciated. 

[files.zip](https://github.com/GeekyAnts/NativeBase/files/587774/files.zip)

Thanks,
Sagar Parikh

**Comment by sagarparikh** [comment]
Update.. 

When i add an empty <Header> </Header> tag within the container things start to work well. Just wondering what could be the issue.


Thanks,
Sagar Parikh

**Comment by SupriyaKalghatgi** [comment]
@sagarparikh Adding `Header` did nothing.

I still cant scroll

**Comment by sagarparikh** [comment]
Yes it doesn't work.. i checked it again maybe something related to packager cache made it work that time. @SupriyaKalghatgi  Can you help with the Fix?

**Comment by sagark1510** [comment]
@sagarparikh did you find any solution?

**Comment by ahsanazwar** [comment]
Any solution scrolling????

**Comment by SupriyaKalghatgi** [comment]
@sagarparikh @sagark1510 @ahsanazwar This was fixed with React Native
Tried anytime?

**Comment by SupriyaKalghatgi** [comment]
Fixed with React Native

**Comment by sagark1510** [comment]
@SupriyaKalghatgi which version?Any commit ref?

**Comment by SupriyaKalghatgi** [comment]
I tried with these dependencies
```
"dependencies": {
    "native-base": "2.1.4",
    "react": "16.0.0-alpha.6",
    "react-native": "0.44.2"
  },
```
