### ISSUE TITLE
'keyExtractor' does not exist on type

### ISSUE THREAD

**Issue by BillyFigueroa** [GeekyAnts/NativeBase#2900]
I am getting the warning

`Type '{ dataArray: ClientListDataType[]; keyExtractor: (item: any, index: any) => any; renderRow: (client: any) => Element; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<List> & Readonly<List> & Readonly<{ children?: ReactNode; }>'.
  Property 'keyExtractor' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<List> & Readonly<List> & Readonly<{ children?: ReactNode; }>'.`

while using a react native typescript project. It seems like the List component does not know that it should inherit the keyExtractor property from VirtualizedListProps or ReactListViewProps

### node, npm, react-native, react and native-base version, expo version if used, xcode version
NativeBase: ^2.13.5
React Native (Expo): sdk-34.0.0

### Expected behaviour
I would expect that when using a list, the keyExtractor function does not cause a typescript warning

### Actual behaviour
Typescript generates the error/ warning above

The docs even mention using keyExtractor so I assume this should not be a TypeScript warning/ error 

### Steps to reproduce
I am using the List component and using keyExtractor. If I do not use it I get a react native warning that I should

```typescript
    <List
      dataArray={clients}
      keyExtractor={(item, index) => index.toString()}
      renderRow={client => (
        <ListItem avatar>
          <Left style={[styles.itemHeight]}>
           ...
          </Left>
          <Body style={[styles.itemHeight]}>
            <Text>{client.full_name}</Text>
            <Text note style={[styles.complimentColor, styles.subtitle]}>
              {client.member_plan}
            </Text>
          </Body>
          <Right style={[styles.itemHeight]}>
            <Text note>{client.join_date}</Text>
          </Right>
        </ListItem>
      )}
    />
```

**Comment by BillyFigueroa** [comment]
Is anyone taking a look at this? I d like to know if this is in some queue or if it has just been ignored

**Comment by sankhadeeproy007** [comment]
@BillyFigueroa Types issues and warnings (non-performance related) usually take a bit longer.
We'd appreciate a PR.

**Comment by BillyFigueroa** [comment]
@sankhadeeproy007 thanks, I just wanted to know if someone was looking at this. I will look into potentially fixing this my self and opening a PR. I just switched over to TypeScript and I m converting my project so I may not have the knowledge to fix this but I will look into it and see if I can

**Comment by BillyFigueroa** [comment]
@sankhadeeproy007 something seems broken with your npm scripts. Running `npm run prebublish` continues to give me babel related errors and even trying to npm install to resintall everything gives me this error

```bash
SyntaxError: flow-typed/index.js: Unexpected token, expected ; (1:8)
> 1 | declare module 'react-native' {
    |         ^
  2 |   declare module.exports: any;
  3 | }
  4 | declare module 'lodash' {
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! native-base@2.13.5 compile: `rm -rf dist/* && babel . --out-dir dist --ignore node_modules,dist --source-maps `
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the native-base@2.13.5 compile script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/figuer25/.npm/_logs/2019-09-06T18_44_23_097Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! native-base@2.13.5 transpile: `npm run compile && cp src/basic/Icon/NBIcons.json dist/src/basic/Icon`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the native-base@2.13.5 transpile script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/figuer25/.npm/_logs/2019-09-06T18_44_24_934Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! native-base@2.13.5 prepublish: `npm run transpile`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the native-base@2.13.5 prepublish script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/figuer25/.npm/_logs/2019-09-06T18_44_26_100Z-debug.log
```

**Comment by BillyFigueroa** [comment]
More from the log file

```bash
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'prepublish' ]
2 info using npm@6.4.1
3 info using node@v10.15.1
4 verbose run-script [ 'prepublish' ]
5 info lifecycle native-base@2.13.5~prepublish: native-base@2.13.5
6 verbose lifecycle native-base@2.13.5~prepublish: unsafe-perm in lifecycle true
7 verbose lifecycle native-base@2.13.5~prepublish: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/figuer25/Sites/mobile/mintgrooming_new_ts/node_modules/native-base/node_modules/.bin:/Users/figuer25/Sites/mobile/mintgrooming_new_ts/node_modules/.bin:/Users/figuer25/.rvm/gems/ruby-2.3.0/bin:/Users/figuer25/.rvm/gems/ruby-2.3.0@global/bin:/Users/figuer25/.rvm/rubies/ruby-2.3.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/Users/figuer25/.rvm/bin:/Users/figuer25/.composer/vendor/bin
8 verbose lifecycle native-base@2.13.5~prepublish: CWD: /Users/figuer25/Sites/mobile/mintgrooming_new_ts/node_modules/native-base
9 silly lifecycle native-base@2.13.5~prepublish: Args: [ '-c', 'npm run transpile' ]
10 silly lifecycle native-base@2.13.5~prepublish: Returned: code: 1  signal: null
11 info lifecycle native-base@2.13.5~prepublish: Failed to exec prepublish script
12 verbose stack Error: native-base@2.13.5 prepublish: `npm run transpile`
12 verbose stack Exit status 1
12 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
12 verbose stack     at EventEmitter.emit (events.js:189:13)
12 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
12 verbose stack     at ChildProcess.emit (events.js:189:13)
12 verbose stack     at maybeClose (internal/child_process.js:970:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
13 verbose pkgid native-base@2.13.5
14 verbose cwd /Users/figuer25/Sites/mobile/mintgrooming_new_ts/node_modules/native-base
15 verbose Darwin 17.7.0
16 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "prepublish"
17 verbose node v10.15.1
18 verbose npm  v6.4.1
19 error code ELIFECYCLE
20 error errno 1
21 error native-base@2.13.5 prepublish: `npm run transpile`
21 error Exit status 1
22 error Failed at the native-base@2.13.5 prepublish script.
22 error This is probably not a problem with npm. There is likely additional logging output above.
23 verbose exit [ 1, true ]
```

**Comment by sankhadeeproy007** [comment]
I just pushed a fix for this in master? Can you point your package.json to master and check if it works?

**Comment by BillyFigueroa** [comment]
@sankhadeeproy007 Awesome, thank you very much.

I have not needed to point a package to master before, what is the convention for this in the package.json?

**Comment by BillyFigueroa** [comment]
Hi @sankhadeeproy007 so it removed the error/ warning I was getting but I am now getting this error

![Screen Shot 2019-09-08 at 11 19 46 AM](https://user-images.githubusercontent.com/1371105/64490434-bba31f80-d22a-11e9-86ce-040be03c192f.png)



I looked at your commit and you removed renderItem

**Comment by sankhadeeproy007** [comment]
Best not to use `List` component then. The docs mention that `List` has been deprecated and suggests use of `FlatList` for dynamic lists.

**Comment by BillyFigueroa** [comment]
@sankhadeeproy007 hold up...

I am using NativeBase's List

`import { List } from 'native-base';`

I opened this issue because NativeBase's List component did not have the proper type definition. You then made a change to add the definition but removed the renderItem function. I did nothing wrong here. I am using NativeBase's List component so telling me to stop using the List item makes no sense. I am using this library to avoid having to create my own list component and NativeBase's List component is using FlatList (found in List.js)...

```js
import { connectStyle } from 'native-base-shoutem-theme';
import React, { Component } from 'react';
import { FlatList, View } from 'react-native';

import mapPropsToStyleNames from '../utils/mapPropsToStyleNames';

class List extends Component {
  render() {
    const { dataArray } = this.props;

    if (dataArray) {
      return (
        <FlatList
          ref={ref => (this._root = ref)}
          data={dataArray}
          renderItem={({ item, index }) =>
            this.props.renderItem
              ? this.props.renderItem({ item, index })
              : this.props.renderRow(item, 0, index)
          }
          {...this.props}
        />
      );
    }
    return <View ref={c => (this._root = c)} {...this.props} />;
  }
}

const StyledList = connectStyle('NativeBase.List', {}, mapPropsToStyleNames)(
  List
);

export { StyledList as List };

```

Are you a NativeBase dev? it looks like you are. You have confused me with your comment to be honest.

**Comment by sankhadeeproy007** [comment]
You do not need to create your own list component. Just replace native-base list with FlatList from react-native. 
**The List component is deprecated.**
It was added back in the time when we had ListView, but with the new FlatList, it doesn't make sense to just have a wrapper around FlatList with no added functionality.
Hence it has been deprecated.
I am just asking you to not a use a deprecated component.

**Comment by BillyFigueroa** [comment]
@sankhadeeproy007 ohhhh lol I see.

Thank you. I just switched to `FlatList` and it all looks good! thanks for the help and sorry for making you work on a deprecated component

Is there a new native base version coming? (i.e. 3.0)

**Comment by sankhadeeproy007** [comment]
Currently we're working on fixing the existing issues and just maintaining the package as it is.
Do you have something specific you need in 3.0 ? 
I'm curious to know if there are any problems with the existing version.

**Comment by BillyFigueroa** [comment]
@sankhadeeproy007 just curious. Everything else I have been using on NativeBase is working fine
