### ISSUE TITLE
Icon changes the position.

### ISSUE THREAD

**Issue by ParthShrivastav** [GeekyAnts/NativeBase#2901]
## I have gone through these following points
- [x]   Check latest documentation: https://docs.nativebase.io/
- [x]   Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x]   Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [x]   Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [x]   For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- [x]   For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

### node, npm, react-native, react and native-base version, expo version if used, xcode version
react-native-cli: 2.0.1
react-native: 0.60.5
native-base: 2.13.5
react: 16.8.6
npm: 6.9.0 
### Expected behaviour
Icon position should remain the same.
### Actual behaviour
Icon position changes when the screen appears on the complete app flow.
### Steps to reproduce

```
import React, { Component } from 'react';
import { View, Image, ImageBackground } from 'react-native';
import { Title, Label, Button, Icon, Row } from 'native-base';
import { withNavigation } from 'react-navigation';

class abc extends Component {
    render() {
        return (
            <ImageBackground 
                    <Row style={StylesNew.Containor}>
                        <Button icon block style={StylesNew.nextButton}
                            onPress={() => this.props.navigation.navigate('xyz')}>
                            <Icon name='arrow-right' type='FontAwesome5' style={StylesNew.Icon} />
                        </Button>
                    </Row>
                </View>
            </ImageBackground>
        );
    };
}
export default withNavigation(abc);

```
Styling code is as below
 ```
  Containor: {
        justifyContent: 'flex-end',
        margin: WIDTH / 9,
        flex: 1,
        alignSelf: 'flex-end'
    },
  nextButton: {
        width: HEIGHT / 12,
        height: HEIGHT / 12,
        borderRadius: HEIGHT / 24,
        backgroundColor: pinkcolor,
        alignSelf: 'flex-end',
    },
  Icon: {
        color: blackcolor,
        alignSelf: 'center',
        fontSize: WIDTH / 15
    },
```
### Is the bug present in both iOS and Android or in any one of them?
I have been working only on Android.

### Any other additional info which would help us debug the issue quicker.
![Screenshot_1566903834](https://user-images.githubusercontent.com/51599211/63767714-0304e400-c8ec-11e9-9000-693be06901e4.png)
![Screenshot_1566903664](https://user-images.githubusercontent.com/51599211/63767715-0304e400-c8ec-11e9-9644-224eb923ccfb.png)

For reference, I have added images.
1. The one having an arrow in the center is when I launch only that particular screen.
2. The other image where the arrow seems to be distorted from the center is when this screen comes in my complete app flow.

**Comment by sankhadeeproy007** [comment]
Can you inspect the Icon/Button and share the styles that are applied to the components?

**Comment by ParthShrivastav** [comment]
The issue got fixed when using the icons separately from the react-native-vector-icons library. Thus, it looks like there is some problem with using icons from the native base.

**Comment by ParthShrivastav** [comment]
I would share the styles by tomorrow.

**Comment by ParthShrivastav** [comment]
```
fontSize:27.42
color:#1f2d3d
marginLeft:16
marginRight:16
alignSelf:center
fontFamily:FontAwesome5_Solid
```
The above styling is for the icon visible in center
And below mentioned is the button component's style containing icon in it.

```
borderRadius:28.47
justifyContent:center
alignSelf:flex-end
paddingTop:6
paddingBottom:6
```
![Screenshot_1566903664](https://user-images.githubusercontent.com/51599211/64145294-cda14e80-ce35-11e9-86ee-1657f5f5d394.png)

**Comment by sankhadeeproy007** [comment]
Thanks for the details!
Can you check if manually assigning `alignSelf:center` to the 2nd case fixes this issue?

**Comment by ParthShrivastav** [comment]
No. This change makes no effect on the issue.

**Comment by hanykumar** [comment]
Hi @ParthShrivastav , Let us know if the issue still persists.
```
<Button
           icon
           block
           style={{
             width: 1000 / 12,
             height: 1000 / 12,
             borderRadius: 1000 / 24,
             backgroundColor: 'red',
           }}>
              <Icon
                name="arrow-forward"
                style={{
                  color: 'black',
                  fontSize: 1000 / 25,
                  alignSelf: 'center',
                }}
              />
</Button>
```
![Screenshot 2020-08-18 at 5 20 29 PM](https://user-images.githubusercontent.com/15860517/90509564-249f5100-e177-11ea-945c-c32940a9d595.png)

**Comment by hanykumar** [comment]
Hi @ParthShrivastav , please update to latest Native-base v.213.14 . Let us know if the issue still persists. Closing for now.
