### ISSUE TITLE
Wrong Vector Icon Resources

### ISSUE THREAD

**Issue by filippoitaliano** [GeekyAnts/NativeBase#2903]
## Issue Description
Can't display correct Icons due to **evident mismatch** between internal `react-native-vector-icons` version and **copied** "Fonts" resources. Specifically, Feather icons are periodically broken (in the current version of Native Base, they are broken).

This issue is related to #2453, #2528 and probably others but, in my opinion, the problem is not addressed in the right way.

### node, npm, react-native, react and native-base version, expo version if used, xcode version
node: 10.15.3
npm: 6.4.1
react-native: 0.60.5
react: 16.8.6
native-base: 2.13.5
expo: not used
xcode: 10.3 (10G8)

### Expected behaviour
Install and link Native Base as intended and get the correct Icons displayed.

### Actual behaviour
After normal installation I get wrong mapped icons or even not mapped icons at all.

### Steps to reproduce (ios for convenience)
1. yarn add native-base
2. react-native link native-base
3. cd ios && pod install
4. Render the Feather `clock` icon displays a cute storm icon, for example...

### Is the bug present in both iOS and Android or in any one of them?
Both platforms are affected.

### Any other additional info which would help us debug the issue quicker.
If I replace the correct `react-native-vector-icons` Fonts (now the correct version is the `6.1.0`), everythig works as expected.

Isn't more maintainable to rely directy on `react-native-vector-icons` resources instead of copy them in `native-base`? Or at least is important to replace **all** vector icons resources every time the internal `react-native-vector-icons` dependency is updated!

Thanks for your help!

**Comment by maxhis** [comment]
Same here.

**Comment by congzhou09** [comment]
I meet the same issue with react-native@0.60.5 and native-base@2.13.5 in Android. Feather icon names do not match the icons.

The "package.json" file of native-base@2.13.5 says it depends on react-native-vector-icons@6.1.0, which is installed correctly. But the *.ttf files in "android\app\src\main\assets\fonts" are not copyed from "node_modules\react-native-vector-icons\Fonts", yet from "node_modules\native-base\Fonts" in the process of linking, and *.ttf files from the two places are not the same. This is the reason.

**Hope for official repair.**

Temporary&Manual fix: 
After the process of linking, replace *.ttf files in "android\app\src\main\assets\fonts" with *.ttf files in "node_modules\react-native-vector-icons\Fonts".

**Comment by sankhadeeproy007** [comment]
Hey, thanks for reporting, will take a look at this one.

**Comment by sankhadeeproy007** [comment]
Can you check with with 2.13.6?

**Comment by congzhou09** [comment]
> 
> 
> Can you check with with 2.13.6?

Feather Icons in my project is OK after changing to 2.13.6. Thanks!

**Comment by filippoitaliano** [comment]
Ok, I've updated to 2.13.7 and the icons display correctly! I'm closing this issue. Thanks!

**Comment by ajaymarathe9** [comment]
> I meet the same issue with react-native@0.60.5 and native-base@2.13.5 in Android. Feather icon names do not match the icons.
> 
> The "package.json" file of native-base@2.13.5 says it depends on react-native-vector-icons@6.1.0, which is installed correctly. But the *.ttf files in "android\app\src\main\assets\fonts" are not copyed from "node_modules\react-native-vector-icons\Fonts", yet from "node_modules\native-base\Fonts" in the process of linking, and *.ttf files from the two places are not the same. This is the reason.
> 
> **Hope for official repair.**
> 
> Temporary&Manual fix:
> After the process of linking, replace *.ttf files in "android\app\src\main\assets\fonts" with *.ttf files in "node_modules\react-native-vector-icons\Fonts".

This solution is working <3
