### ISSUE TITLE
[Bug] btnUppercaseAndroidText true doesn't make button text uppercase

### ISSUE THREAD

**Issue by Rionardo** [GeekyAnts/NativeBase#2904]
## I have gone through these following points
- [v]   Check latest documentation: https://docs.nativebase.io/
- [v]   Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [v]   Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- []   Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- []   For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- []   For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

## Issue Description
btnUppercaseAndroidText not working as expected on Android, still working on 2.12.1 and not working on latest version 2.13.5

### node, npm, react-native, react and native-base version, expo version if used, xcode version "react": "16.8.6",
"native-base": "^2.13.5",

### Expected behaviour
button text became uppercase 
<Button>
<Text></Text>
</Button>

### Actual behaviour
button text still lowercase

### Is the bug present in both iOS and Android or in any one of them?
Android

### Any other additional info which would help us debug the issue quicker.
![image](https://user-images.githubusercontent.com/41901530/63845635-75d99200-c9b4-11e9-96ee-8e1c1aafbd4f.png)

**Comment by sankhadeeproy007** [comment]
Hey, we'll take a look at this one, for now you can just pass the text as upperCase till we fix this.

**Comment by Alex193a** [comment]
@RioFiveJack I had the opposite problem: using `btnUppercaseAndroidText: false` the button text remains in uppercase, then I realized that btnUppercaseAndroidText was renamed to **buttonUppercaseAndroidText**.
https://github.com/GeekyAnts/NativeBase/commit/6060f0461f3e606c153cb49a2bcef48d0295e65c#diff-e2d9b13af5e71dd243814626dcc96107R35

**Comment by hanykumar** [comment]
Hi @RioFiveJack , This issue has been fixed in our master branch. 

![Screenshot 2020-03-27 at 11 55 51 AM](https://user-images.githubusercontent.com/15860517/77730094-1d3fa580-7026-11ea-8fbe-8e51d974c962.png)

**Comment by hanykumar** [comment]
Hi @Rionardo , Please update Native-Base v.213.14 . Let us know if the issue still persists. Closing for now.
