### ISSUE TITLE
the text is not vertically  centre aligned when giving item property of'floating label' and border as regular for eg       <Item style={{backgroundColor: 'white'}} floatingLabel regular>

### ISSUE THREAD

**Issue by anuragversatile** [GeekyAnts/NativeBase#2911]
## I have gone through these following points
- []   Check latest documentation: https://docs.nativebase.io/
- []   Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- []   Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- []   Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- []   For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- []   For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

### node, npm, react-native, react and native-base version, expo version if used, xcode version=
react-native 0.60.5
native base 2.13.5
node 10.16.1
<img width="324" alt="EXPECTED BEHAVIOUR " src="https://user-images.githubusercontent.com/22766641/64166168-39021500-ce64-11e9-8312-e86d56b56886.png">
<img width="346" alt="GETTING BEHAVIOUR" src="https://user-images.githubusercontent.com/22766641/64166169-39021500-ce64-11e9-8a37-a414a50db899.png">
<img width="324" alt="EXPECTED BEHAVIOUR " src="https://user-images.githubusercontent.com/22766641/64166208-49b28b00-ce64-11e9-9e6d-49adc5fd72f2.png">
<img width="346" alt="GETTING BEHAVIOUR" src="https://user-images.githubusercontent.com/22766641/64166209-49b28b00-ce64-11e9-9101-7f0aac558fca.png">

xcode 10.2.1

### Steps to reproduce
<Item  floatingLabel regular>
              <Label>
                {this.state.emailText}
              </Label>

              <Input
                autoCapitalize={'none'}
                style={{borderRadius: 5}}
                accessibilityLabel={'enter email'}
                testID="emailID"
                onChangeText={e => this.handleText(e, 'email', 'email')}
  
                value={this.state.email}/>
</Item

**Comment by sankhadeeproy007** [comment]
Please attach a reproducible snack example.

**Comment by anuragversatile** [comment]
https://snack.expo.io/@adanurag/floatinglabel-issue

**Comment by anuragversatile** [comment]
> Please attach a reproducible snack example.

https://snack.expo.io/@adanurag/floatinglabel-issue

**Comment by sankhadeeproy007** [comment]
Not sure, I understand your problem properly. But for floatinglabel, the input is aligned to the bottom so that when the label floats up to the top, the input stays below and it looks symmetric.
My advice would be to only add a bottom border and it'll look better.
Any ways, it isn't a problem with the library, so closing this one.
