### ISSUE TITLE
Ripple/Highlight effect on iOS / Generic platform?

### ISSUE THREAD

**Issue by cristianoccazinsp** [GeekyAnts/NativeBase#2913]
## I have gone through these following points
- [x]   Check latest documentation: https://docs.nativebase.io/
- [x]   Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x]   Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [x]   Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [x]   For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- [x]   For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

I'm wondering if it would be possible to replace Android's ripple effect with a more generic approach that works for both iOS and Android consistently.

I've done some testing with using TouchableHighlight instead of TouchableOpacity, and it seems possible if using some logic to check for the button's background color and using color(bg).lighten(0.2).hex() for the underlayColor of the TouchableHighlight component. The final result is very similar to the opacity one, but allows you to also show some effect on buttons that use the same color as it's background (e.g., header and footer buttons). 

Although I've managed to test it, I still have inconsistency issues when the button is actually set to transparent (what would the bg/underlay color be on such case? How to calculate it generically?). This becomes more of an issue when buttons are most of the time set to transparent when used on a header/footer.

Before testing any further, I'm wondering if this is even a good idea, or there's no point in using this effect on iOS?. Truth is, the ripple effect on Android is quite bad and it breaks most of the time (e.g., when used in a footer, the ripple circle is totally messed up, although this is probably because I've tweaked the styles after ejecting.)

This is basically what I'm trying to achieve (taken from Youtube's iOS app), but it won't be possible with TouchableOpacity unless the header's background is lighter and all buttons take full width and leave no space around.
![IMG_20190903_183554_2](https://user-images.githubusercontent.com/48869228/64211122-8938a180-ce7b-11e9-9100-4c38a3e2fd8b.jpg)

**Comment by sankhadeeproy007** [comment]
The ripple effect on Android is using `TouchableNativeFeedback`.
Although replicating it on iOS might be tricky, but a similar effect can be achieved using `TouchableHighlight`.
That however is beyond the scope of this package as Cupertino design doesn't have ripple effect.
It is app specific and best left to user to implement.
Closing this.
