### ISSUE TITLE
Native base Toast Position "Top" is disturbing when keyboard is open, Only iOS

### ISSUE THREAD

**Issue by LuckyShine001** [GeekyAnts/NativeBase#2914]
## I have gone through these following points
- []   Check latest documentation: https://docs.nativebase.io/
- []   Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- []   Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- []   Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- []   For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- []   For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

### Expected behaviour
Toast position should be fixed at top
### Actual behaviour
Toast is moving with keybaord show and hide
### Steps to reproduce
Use Nativebase Toast with position top in any form.
try to open keybaord while toast is showing on the screen.

### Is the bug present in both iOS and Android or in any one of them?
iOS
### Any other additional info which would help us debug the issue quicker.
It is working fine with Position bottom

**Comment by sankhadeeproy007** [comment]
Fixed in 2.13.8
