### ISSUE TITLE
Error on native-base/fonts

### ISSUE THREAD

**Issue by RenanNeitzel** [GeekyAnts/NativeBase#2919]
#### node, npm, react-native, react and native-base version, expo version if used, xcode version

node - v12.7.0
npm - 6.10.0
react - 16.8.3
native-base - 2.13.7
expo - 3.0.10
xcode - 10.3

#### Actual behaviour

When I try run the project, my xcode return this error:

![Captura de Tela 2019-09-06 às 12 07 51](https://user-images.githubusercontent.com/41584304/64438747-07c15900-d09f-11e9-9789-efe832920256.png)

I saw in May a similar issue opened and fixed by an update.
Will this be needed again ?

#### Is the bug present in both iOS and Android or in any one of them?

Only iOS

**Comment by sankhadeeproy007** [comment]
Missed it with the last upgrade. 
Will be added back in the next version.

**Comment by lnmunhoz** [comment]
Please @sanketsahusoft, can you release a patch update for this? I am sure a lot of people will come here with the same issue.

For those with this issue, just dowload [this font file](https://github.com/GeekyAnts/NativeBase/blob/master/Fonts/rubicon-icon-font.ttf) and paste it into your `node_modules/native-base/Fonts` folder.

**Comment by sankhadeeproy007** [comment]
> Please @sanketsahusoft, can you release a patch release for this? I am sure a lot of people will come here with the same issue.
> 
> For those with this issue, just dowload [this font file](https://github.com/GeekyAnts/NativeBase/blob/master/Fonts/rubicon-icon-font.ttf) and paste it into your `node_modules/native-base/Fonts` folder.

The fix has been added to master. Please point your package.json to master till we release a new path (ETA 2 days)

**Comment by colemars** [comment]
Spam - but it is funny that this font has gone missing during upgrades twice now. Someone doesn't like it?😂

**Comment by sankhadeeproy007** [comment]
@colemars We copy the latest fonts from `react-native-vector-icons`. Must have been removed from there.

**Comment by sankhadeeproy007** [comment]
Fixed in 2.13.8
