### ISSUE TITLE
Thumbnail SVG format

### ISSUE THREAD

**Issue by thundenilla** [GeekyAnts/NativeBase#292]
Hey. Can I use svg format assets for thumbnail? or is it limited only for PNG? and why Icon's icon very limited. Was hoping to have all of material designs' icons.

**Comment by sankhadeeproy007** [comment]
You can use all the icons from `react-nativevestor-icons`. It is not just limited to Ionicons. Please go through the docs for Icon configuration. 
Thumbnail inherits all the properties of RN `Image`, so if Image has SVG support, the Thumbnail will support it too.
