### ISSUE TITLE
command react-native link not add fonts files

### ISSUE THREAD

**Issue by Juliocbr** [GeekyAnts/NativeBase#2921]
## Issue Description

Command "react-native link" does not add the fonts files to the respective ios and android folders

#### node, npm, react-native, react and native-base version, expo version if used, xcode version

native-base 2.13.7
node 10.15.0
npm 6.4.1
react 16.8.3
react-native 0.59.8

#### Is the bug present in both iOS and Android or in any one of them?

ios and android

**Comment by sankhadeeproy007** [comment]
Please use native-base versions 2.12.* for react-native older than 0.60

**Comment by Juliocbr** [comment]
@sankhadeeproy007 command "react-native link" works well until native-base v2.12.1 for react-native v0.59.8

**Comment by sankhadeeproy007** [comment]
Can you try `react-native link native-base` ? That should work for the newer versions.

**Comment by ansarikhurshid786** [comment]
> Can you try `react-native link native-base` ? That should work for the newer versions.

I tried but not working

**Comment by ansarikhurshid786** [comment]
I resolve by running : 
`react-native link react-native-vector-icons`

I am using react-native 0.59.10 and native-base : ^2.13.8
