### ISSUE TITLE
<Item stackedLabel /> breaks con position

### ISSUE THREAD

**Issue by mattiamanzati** [GeekyAnts/NativeBase#2923]
#### node, npm, react-native, react and native-base version, expo version if used, xcode version
    "expo": "^34.0.1",
    "expo-font": "^6.0.1",
    "native-base": "^2.13.7",
    "react": "16.8.3",
    "react-native": "https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz",
    "native-base": "2.13.7"

#### Expected behaviour
Icon should be placed on right side, and should support ideally multiple icons as it would without the stackedLabel prop

#### Actual behaviour
Icon is placed on left regardless of usage position relative to Input component

![image](https://user-images.githubusercontent.com/13787614/64677539-0cf41e80-d478-11e9-81b2-dbd14f79105d.png)

#### Steps to reproduce
`<Item stackedLabel={true}> <Label>Input Label</Label> <Input/> <Icon name="checkmark"/> </Item>`

[Snack](https://snack.expo.io/Hyoc7QULS)

#### Is the bug present in both iOS and Android or in any one of them?
Both Android and iOS seems to be affected

Thanks for your great library! :D

**Comment by brykov** [comment]
same problem! any news?
