### ISSUE TITLE
Jest connectStyle Error

### ISSUE THREAD

**Issue by anuragdwivedi29** [GeekyAnts/NativeBase#2926]
## I have gone through these following points

- [] Check latest documentation: https://docs.nativebase.io/
- [] Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [] Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [] Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [] For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- [] For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

## Issue Description
import Enzyme from 'enzyme';
import Adapter from 'enzyme-adapter-react-16';

Enzyme.configure({ adapter: new Adapter() });
import { shallow, mount } from 'enzyme';

import React from 'react';
import renderer from 'react-test-renderer';
import { render, fireEvent } from 'react-native-testing-library';
import LogIn from '../log-in/login';

describe('Test case for testing Login', () => {
    it('should render the Login page without crashing', () => {
        const rendered = renderer.create(<LogIn />).toJSON();
        expect(rendered).toBeTruthy();
    });
The app working properly in normal case. But when I started jest, it gave an error like this:

  ● Test suite failed to run

    /-----/----/------/-----/node_modules/native-base-shoutem-theme/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import con
nectStyle, { clearThemeCache } from "./src/connectStyle";
                                                                                                    ^^^
^^^^^^^^^

#### node, npm, react-native, react and native-base version, expo version if used, xcode version
node:v10.16.1
npm:6.10.3
"native-base": "^2.13.5",
"react": "16.8.6",
"react-native": "0.60.5",
"react-native-testing-library": "^1.11.1",
"react-navigation": "^4.0.0",
"react-navigation-material-bottom-tabs": "^1.1.1",
"react-navigation-stack": "^1.5.1",
"react-navigation-tabs": "^2.4.0",
#### Expected behaviour
test should pass
#### Actual behaviour
gives the error
#### Any other additional info which would help us debug the issue quicker.

###Important

If you want your issue to be looked at quicker, attach a snack reproducible with your issue. Makes it easier for us!

**Comment by anuragdwivedi29** [comment]
added the following in package.json as commented in issue#2579
"jest": {
"preset": "react-native",
"transformIgnorePatterns": [
"/node_modules/(?!native-base)/"
]
}
but the issue is still not resolved

**Comment by ZuyuLiao** [comment]
Same issue, add ignore pattern can not solve it

**Comment by FDiskas** [comment]
```
transformIgnorePatterns: ['node_modules/(?!(react-native|react-native-button|native-base-.*|react-native-.*)/)'],
```
solves

**Comment by Runtime-Err** [comment]
@FDiskas, I got the the exact same problem and unfortunately, your suggestion doesn't work for me. 

Here is my package.json:

```
{
  "name": "test",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint .",
    "tsc": "tsc -w"
  },
  "dependencies": {
    "@typescript-eslint/eslint-plugin": "^2.19.2",
    "@typescript-eslint/parser": "^2.19.2",
    "core-js": "^3.6.1",
    "eslint-config-prettier": "^6.10.0",
    "eslint-plugin-prettier": "^3.1.2",
    "native-base": "^2.13.8",
    "prettier": "^1.19.1",
    "react": "^16.12.0",
    "react-dom": "^16.12.0",
    "react-native": "0.61.5",
    "react-native-fs": "^2.16.2",
    "react-native-gesture-handler": "^1.5.2",
    "react-native-reanimated": "^1.4.0",
    "react-native-screens": "^1.0.0-alpha.23",
    "react-navigation": "^4.0.10",
    "react-navigation-stack": "^1.10.3",
    "react-navigation-tabs": "^2.6.2",
    "react-redux": "^7.1.3",
    "realm": "^3.6.3",
    "redux": "^4.0.5"
  },
  "devDependencies": {
    "@babel/core": "7.7.5",
    "@babel/runtime": "7.7.6",
    "@react-native-community/eslint-config": "0.0.5",
    "@testing-library/jest-native": "^3.1.0",
    "@types/jest": "^25.1.3",
    "@types/node": "^13.7.1",
    "@types/react": "^16.9.19",
    "@types/react-dom": "^16.9.5",
    "@types/react-native": "^0.61.14",
    "@types/react-redux": "^7.1.7",
    "@types/react-test-renderer": "^16.9.2",
    "babel-jest": "24.9.0",
    "chromedriver": "^79.0.0",
    "eslint": "^6.7.2",
    "jest": "^24.9.0",
    "metro-react-native-babel-preset": "0.56.3",
    "react-native-testing-library": "^1.12.0",
    "react-test-renderer": "^16.13.0",
    "source-map-loader": "^0.2.4",
    "ts-jest": "^25.2.1",
    "ts-loader": "^6.2.1",
    "typescript": "^3.7.5"
  },
  "jest": {
    "preset": "react-native",
    "transform": {
      "^.+\\.js$": "<rootDir>/node_modules/react-native/jest/preprocessor.js",
      "\\.(ts|tsx)$": "ts-jest"
    },
    "globals": {
      "ts-jest": {
        "tsConfig": "tsconfig.jest.json"
      }
    },
    "moduleFileExtensions": [
      "ts",
      "tsx",
      "js",
      "jsx",
      "json",
      "node"
    ],
    "transformIgnorePatterns": [
      "node_modules/(?!(react-native|react-native-button|native-base-.*|react-native-.*)/)"
    ],
    "testRegex": "(/__tests__/.*|\\.(test|spec))\\.(ts|tsx|js)$"
  }
}

```

**Comment by FDiskas** [comment]
Try this,

Remove `jest` settings from package.json and run
`npx ts-jest init` and then try again

**Comment by Runtime-Err** [comment]
@FDiskas , thanks a lot for your reply. Did` npx ts-jest config:init`. Now, there are tons of Typescript errors. Can I include some of above jest settings back in?

**Comment by FDiskas** [comment]
One by one :D

**Comment by Runtime-Err** [comment]
@FDiskas, in my `jest.config.js`, I have to change `preset `from `ts-jest` to `react-native`, because if not, I am getting the error "Missing initializer in const declaration". See [this ](https://stackoverflow.com/questions/57158884/syntaxerror-missing-initializer-in-const-declaration)stackoverflow post. But after I did this, the exact same error as stated above returns :(

**Comment by Runtime-Err** [comment]
I also posted the question on [Stackoverflow](https://stackoverflow.com/questions/60524323/jest-unexpected-token-export-with-react-navigation), unfortunately no answer. Maybe this helps to clarify the problem.
