### ISSUE TITLE
Open Picker Programmatically

### ISSUE THREAD

**Issue by MarkRabey** [GeekyAnts/NativeBase#2928]
I'm looking for a way to open a Picker automatically when certain conditions are met. Any suggestions? I see that Picker.ios.js has a `_setModalVisible()` method, but I am not able to access it. Any suggestions?

**Comment by moyolvera** [comment]
Did you find a way to open the picker programmatically?

**Comment by MarkRabey** [comment]
@moyolvera No I didn't. I ended up using another library. I honestly forget which one.

**Comment by hanykumar** [comment]
Hi @MarkRabey , opening picker programmatically feature is not available for now. Closing for now.

**Comment by dhamarohan** [comment]
It's possible. I'm doing this on native-base version 2.13
Create a ref to the picker dropdown.
In constructor => this.pickerRef = createRef();
Suppose ref to the dropdown => <Picker ref={this.pickerRef}  .... />
Open Picker dropdown => this.pickerRef.current._root.focus()
