### ISSUE TITLE
Problem with text color in a Picker element on Android using the StyleProvider

### ISSUE THREAD

**Issue by itjope** [GeekyAnts/NativeBase#2933]
## Issue Description
Changing text color in a `Picker` element on Android using `StyleProvider` does not work.

#### Steps to reproduce
1. Open the variables-file and set`textColor`, `inputColor`, `inputColorPlaceholder`, `defaultTextColor` to `red`.
2. Add a `Picker`

#### Is the bug present in both iOS and Android or in any one of them?
Only on Android

**Comment by hanykumar** [comment]
Hi @itjope , please explain reproduction steps more. Update Native-Base v.213.14 .
