### ISSUE TITLE
Native Base <Input> Not working properly on iOS 13 Devices. 

### ISSUE THREAD

**Issue by mohitpasiapac** [GeekyAnts/NativeBase#2936]
Hi,
We Are using Native Base with our app and when we tried it out on iOS 13 the **Input** Text Field does not work properly and we get to see cutting text on the lower part of the field instead of the basic ellipsis that should appear for long strings.
A comparative screen-shot is provided comparing it with the expected behaviour available and functioning on iOS 12.2

<img width="1440" alt="Screenshot 2019-09-23 at 3 02 19 PM" src="https://user-images.githubusercontent.com/45071136/65416548-ba224b80-de15-11e9-884b-81d2f44bfe72.png">

package.json file dependencies:

<img width="472" alt="Screenshot 2019-09-23 at 3 17 39 PM" src="https://user-images.githubusercontent.com/45071136/65416416-5ef05900-de15-11e9-8a3b-bb1129eee4b0.png">

react-native info:

<img width="837" alt="Screenshot 2019-09-23 at 3 18 52 PM" src="https://user-images.githubusercontent.com/45071136/65416470-89daad00-de15-11e9-8919-7fc55d3050df.png">

**Comment by jacargentina** [comment]
In my testing, i've found the `<Input clearButtonMode="always"/>` works fine on light but fails on dark mode; maybe it is somehow related to this issue too?

**Comment by mohitpasiapac** [comment]
@jacargentina hi for me clearButton appears on a editing, but this issue happens when the field is not in focus, As you can see in the image the second field currently is on focus and then you'll see the text distorted as this instead of being ellipsis(ed) and that too only on iOS 13 only. 

As it's the same component, it might as well be related also eagerly waiting for some response on this!.

**Comment by mohitpasiapac** [comment]
@sanketsahusoft, @SupriyaKalghatgi can we have some input from you guys on this issue?

**Comment by mohitpasiapac** [comment]
@sankhadeeproy007 sorry for bothering but some insight on this, and any solution to this would really be help-full.

Thanks in advance.

**Comment by sankhadeeproy007** [comment]
@mohitpasiapac Can you try replacing `<Input />` with the react-native textInput and see if we can reproduce this issue?

**Comment by mohitpasiapac** [comment]
Hey @sankhadeeproy007 , I tried with react-native Text-Input, And it doesn't show any issue of the kind,
 But as I'm using Item as parent to this <Input> to be able to use my custom ClearButton which was working fine and was adjusted automatically inside the item while editing but this isn't the case with **TextInput** and the extra elements are thrown out of the Item's scope and won't work until inside.
Images provided. In the first image the clear button doesn't work but after deleting characters and letting the 'x' in the scope it'll work.
<img width="405" alt="Screenshot 2019-11-04 at 12 15 28 PM" src="https://user-images.githubusercontent.com/45071136/68103473-01175c80-fefd-11e9-99dd-e5ddf17da9bc.png">
<img width="447" alt="Screenshot 2019-11-04 at 12 15 49 PM" src="https://user-images.githubusercontent.com/45071136/68103487-0aa0c480-fefd-11e9-8a9a-d6b7567789ab.png">

**Comment by mohitpasiapac** [comment]
Hey @sankhadeeproy007 , I tried with react-native Text-Input, And it doesn't show any issue of the kind,
But there are more updates I want to provide on the situation:
1. After testing further I realised that If I were to paste a really long string in the Input on any other device(<iOS 13 & android also), the same problem of the cutting text occurs, this I am seeing after the react-native update to 0.60.5.
2. Now than using react-native's text input generates different results on different platforms, **Android:** As I'm using Item as the parent to this <Input> to be able to use my custom ClearButton which was working fine and was adjusted automatically inside the item with _native-base<Input>_ while editing but this isn't the case with TextInput as the extra elements are thrown out of the Item's scope and won't work until inside.
Images provided. In the first image the clear button doesn't work but after deleting characters and letting the 'x' in the scope it'll work.
<img width="405" alt="Screenshot 2019-11-04 at 12 15 28 PM" src="https://user-images.githubusercontent.com/45071136/68110531-32028c00-ff13-11e9-88b3-fb14876ef005.png">
<img width="447" alt="Screenshot 2019-11-04 at 12 15 49 PM" src="https://user-images.githubusercontent.com/45071136/68110540-37f86d00-ff13-11e9-8136-2ea1b8425eee.png">

Now for **iOS** the **'x'** appears to be inside the item and is working but when you click it, the text is cleared but the **'x'** sticks to the start of the text input and also the icon and text alignments have changed.
Image:
<img width="403" alt="Screenshot 2019-11-04 at 12 48 08 PM" src="https://user-images.githubusercontent.com/45071136/68110970-0af88a00-ff14-11e9-9f7f-51c6e32647b8.png">

Although the particular issue of extra text is not visible with react-native textinput but it does not fullfill our required use cases either.

Appreciate your response and help with this.

**Comment by mohitpasiapac** [comment]
Hey @sankhadeeproy007  any feedback on this would be great!
??

**Comment by mohitpasiapac** [comment]
@SupriyaKalghatgi  @sanketsahusoft  can anybody help???, Support on this is appericiated!

**Comment by aeutalt** [comment]
bump

Having the same problem. Can't capture any text from <Input> component, but if I try to get the text with <TextInput> component, it works just fine.

**Comment by mohitpasiapac** [comment]
@aeutalt  It's great to know that other people are also facing issues making it a need to fix this, but even my app is in production and would love if this bug were to be resolved. and am tired of asking, I know you guys are busy and sorry but it'd really help to have you guys resolve these minor issues: @sankhadeeproy007 , @SupriyaKalghatgi ,  @sanketsahusoft

**Comment by hanykumar** [comment]
Hi @mohitpasiapac , I don't see any issue with `<input />`. Please share snack for the same for minimal reproduction if you have same issue yet.

In iOS,  iPhone 11 - 13.3
![Screenshot 2020-03-16 at 6 25 06 PM](https://user-images.githubusercontent.com/15860517/76762345-24112180-67b7-11ea-9dd9-201e0d18cb3b.png)

In Android, 
![Screenshot 2020-03-16 at 6 20 17 PM](https://user-images.githubusercontent.com/15860517/76762449-502ca280-67b7-11ea-80cf-821810d86e4a.png)

Code for the same.
![Screenshot 2020-03-16 at 6 22 36 PM](https://user-images.githubusercontent.com/15860517/76762481-60dd1880-67b7-11ea-8c67-46faeee17bd9.png)

**Comment by mohitpasiapac** [comment]
hi @hanykumar thanks for the reply, so did you paste a long text or just type?,please check with both, also remove the focus from the field to check.
as of now I'm busy with other stuff and would try to make a snack asap. sorry on that!
Also for me clearbutton mode is set to="while-editing"

**Comment by hanykumar** [comment]
Hi @mohitpasiapac , I did everything you just said. And It works fine.

**Comment by hanykumar** [comment]
Hi @mohitpasiapac , closing this now due to inactivity. Let us know if the issue still persists.
