### ISSUE TITLE
native base v2.13.8 floatingLabel don't work in production

### ISSUE THREAD

**Issue by tiendungtcu** [GeekyAnts/NativeBase#2937]
Hi,
I'm using nativebase v2.13.8 in my react native using exp app, but stuck with floatingLabel. It don't work when init value. This is what displayed when set initial value for input with floatingLabel.

![70935186_706343739866167_508624265008906240_n](https://user-images.githubusercontent.com/39891355/65433484-4bf67c80-de47-11e9-9a8d-0caa225fccf9.jpg)

Here is my sdk version:
    "expo-font": "~7.0.0",
    "formik": "^1.5.8",
    "lodash": "^4.17.15",
    "native-base": "2.13.8",
    "react": "16.8.3",
    "react-native": "https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz"
Run well in development but fail in production !

**Comment by richard24se** [comment]
Me too, doesn't work that!
