### ISSUE TITLE
native-base expo 34 issue

### ISSUE THREAD

**Issue by xain786** [GeekyAnts/NativeBase#2938]
After updating the project to SDK version 34 I am facing the following issue.
![image](https://user-images.githubusercontent.com/25928974/65482685-4a629e00-deb3-11e9-879f-1a1bb5826f50.png)

Unable to resolve "react-native-gesture-handler" from "node_modules\react-navigation-stack\src\views\StackView\StackViewLayout.js"

npm: 6.11.3
node: 10.16.3
expo sdk: 34.0.1
expo cli: 3.1.1

**Comment by tiendungtcu** [comment]
You need install react-native-gesture-handler package.
Use npm install --save react-native-gesture-handler to install the package.

**Comment by hanykumar** [comment]
Hi @xain786 , This is dependency issue with Expo project. Let us know if the issue still persists. Closing for now.
