### ISSUE TITLE
How to change active tab border bottom color of tabs.

### ISSUE THREAD

**Issue by rshaikhcornerstone** [GeekyAnts/NativeBase#2939]
## I have gone through these following points

- [] Check latest documentation: https://docs.nativebase.io/
- [] Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [] Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [] Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [] For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- [] For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

#### Any other additional info which would help us debug the issue quicker.

###Important

If you want your issue to be looked at quicker, attach a snack reproducible with your issue. Makes it easier for us!

**Comment by misterchlee7** [comment]
@rshaikhcornerstone - If you look at the docs under Tabs section (https://docs.nativebase.io/Components.html#tabs-def-headref), you will see there is a prop for `Tabs` called `tabBarUnderlineStyle`.

Here you can set `backgroundColor` styling prop to change the active tab bottom border tab color.

`<Tabs tabBarUnderlineStyle={{ backgroundColor: #fff}}`

**Comment by ansarikhurshid786** [comment]
@misterchlee7 
Thanks it is working fine

**Comment by hanykumar** [comment]
We have provided solution to your issue but did not receive any feedback from @rshaikhcornerstone. So we are closing this issue. 
Thanks.
