### ISSUE TITLE
Picker list with Search option

### ISSUE THREAD

**Issue by sagark1510** [GeekyAnts/NativeBase#294]
Hi NativeBase is great library to work with. I am using picker component and I have long list to show under picker item list, is there any option or work around to show search box and filter through it the item list.

**Comment by SupriyaKalghatgi** [comment]
@sagark1510 Hey, Glad to hear that you appreciate our work.
We dont have component which is a combination of `Picker` and `Searchbox`.
But you can customize it at your own using NB `SearchBar`

**Comment by MbF-Sathya** [comment]
Ntivebase picker is awesome. there is only thing is missing in the component is search if it is there then it will be cool
