### ISSUE TITLE
iOS 13 StatusBar change color is not working via variables

### ISSUE THREAD

**Issue by SmirnovM91** [GeekyAnts/NativeBase#2940]
## I have gone through these following points

- [x] Check latest documentation: https://docs.nativebase.io/
- [x] Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x] Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [x] Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [] For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- [x] For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

## Issue Description
iOS 13 StatusBar change color is not working via variables

#### Any other additional info which would help us debug the issue quicker.

###Important

If you want your issue to be looked at quicker, attach a snack reproducible with your issue. Makes it easier for us!

**Comment by mkrn** [comment]
For me, on iOS 13 the StatusBar has disappeared (or is white on white) and I can't quite adjust it by setting `<Header iosBarStyle="dark-content" />`
Happens with Dark Mode on and off. 
But it looks like it has nothing to do with NativeBase. React-native needs to be updated to support it:
https://github.com/facebook/react-native/issues/26369

**Comment by artshevtsov** [comment]
NativeBase overrides the color of StatusBar with the color from plarform.js or other theme applied to app and does not handle the appearance state change event(when dark or light os theme enabled) for iOS 13/ Android Q.

**Comment by hanykumar** [comment]
Hi @SmirnovM91 , you cannot set different-different colors on iOS Bar. This feature is limited for now. Closing for now. Let us know if any other issue occurs.

`<Header iosBarStyle="dark-content" />`
`<Header iosBarStyle="light-content" />`
`<Header iosBarStyle="default" />`
