### ISSUE TITLE
undefined is not object (e.endCoordinates.height )

### ISSUE THREAD

**Issue by TeslaGiga** [GeekyAnts/NativeBase#2944]
![Simulator Screen Shot - iPhone X - 2019-09-25 at 18 28 34](https://user-images.githubusercontent.com/55199866/65603045-905a5780-dfc2-11e9-9610-9b0658f9af79.png)

## I have gone through these following points

- [] Check latest documentation: https://docs.nativebase.io/
- [] Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [] Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [] Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [] For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- [] For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

## Issue Description

 react-native 0.59.3 
 native-base 2.13.5
 react 16.8.3
react-native-keyboard-aware-scroll-view 0.8.0 also tried with 0.9.1
#### Is the bug present in both iOS and Android or in any one of them?
in ios
#### Any other additional info which would help us debug the issue quicker.

###Important

If you want your issue to be looked at quicker, attach a snack reproducible with your issue. Makes it easier for us!

**Comment by hanykumar** [comment]
Hi @TeslaGiga , Please update native-base with the latest v2.13.14 .Please provide minimal code reproduction for the same. Closing for now. Let us know if the issue still persists.
