### ISSUE TITLE
Warning: Received `false` for a non-boolean attribute `uppercase`

### ISSUE THREAD

**Issue by arsamigullin** [GeekyAnts/NativeBase#2945]
Hi. Getting this warning in a web browser console

bundle.js:144396 Warning: Received `false` for a non-boolean attribute `uppercase`.

If you want to write it to the DOM, pass a string instead: uppercase="false" or uppercase={value.toString()}.

If you used to conditionally omit it with uppercase={condition && value}, pass uppercase={condition ? value : undefined} instead.
    in div (created by Text)
    in Text (at Text.js:26)
    in Text (at connectStyle.js:392)
    in Styled(Text) (at SettingsScreen.js:19)
    in div (created by View)
    in View (at Left.js:10)
    in Left (at connectStyle.js:392)
    in Styled(Left) (at SettingsScreen.js:18)
    in div (created by View)
    in View (at ListItem.js:39)
    in div (created by View)
    in View (created by TouchableHighlight)
    in TouchableHighlight (at ListItem.js:31)
    in ListItem (at connectStyle.js:392)
    in Styled(ListItem) (at SettingsScreen.js:17)
    in div (created by View)
    in View (at List.js:25)
    in List (at connectStyle.js:392)
    in Styled(List) (at SettingsScreen.js:15)
    in div (created by View)
    in View (created by ScrollView)
    in div (created by View)
    in View (created by ScrollViewBase)
    in ScrollViewBase (created by ScrollView)
    in ScrollView (at KeyboardAwareHOC.js:517)
    in KeyboardAwareScrollView (at Content.js:66)
    in Content (at connectStyle.js:392)
    in Styled(Content) (at SettingsScreen.js:14)
    in div (created by View)
    in View (at Container.js:12)
    in Container (at connectStyle.js:392)
    in Styled(Container) (at SettingsScreen.js:13)
    in SettingsScreen (at SceneView.js:9)
    in SceneView (at StackViewLayout.tsx:898)
    in div (created by View)
    in View (at StackViewLayout.tsx:897)
    in div (created by View)
    in View (at StackViewLayout.tsx:896)
    in div (created by View)
    in View (created by AnimatedComponent)
    in AnimatedComponent (at StackViewCard.tsx:106)
    in div (created by View)
    in View (created by AnimatedComponent)
    in AnimatedComponent (at screens.web.js:105)
    in Screen (at StackViewCard.tsx:93)
    in Card (at createPointerEventsContainer.tsx:95)
    in Container (at StackViewLayout.tsx:984)
    in div (created by View)
    in View (at StackViewLayout.tsx:393)
    in div (created by View)
    in View (created by AnimatedComponent)
    in AnimatedComponent (at StackViewLayout.tsx:383)
    in UnimplementedGestureHandler (at createHandler.web.js:201)
    in PanGestureHandler (at StackViewLayout.tsx:376)
    in StackViewLayout (at withOrientation.js:30)
    in withOrientation (at StackView.tsx:104)
    in div (created by View)
    in View (at Transitioner.tsx:267)
    in Transitioner (at StackView.tsx:41)
    in StackView (at createNavigator.js:80)
    in Navigator (at SceneView.js:9)
    in SceneView (at createTabNavigator.tsx:67)
    in div (created by View)
    in View (created by AnimatedComponent)
    in AnimatedComponent (at screens.web.js:105)
    in Screen (at ResourceSavingScene.tsx:20)
    in ResourceSavingScene (at createBottomTabNavigator.tsx:157)
    in div (created by View)
    in View (at createBottomTabNavigator.tsx:147)
    in div (created by View)
    in View (at createBottomTabNavigator.tsx:146)
    in TabNavigationView (at createTabNavigator.tsx:228)
    in NavigationView (at createNavigator.js:80)
    in Navigator (at SceneView.js:9)
    in SceneView (at SwitchView.js:12)
    in SwitchView (at createNavigator.js:80)
    in Navigator (created by WebApp)
    in WebApp (at App.js:27)
    in div (created by View)
    in View (at App.js:25)
    in App (at withExpoRoot.web.js:8)
    in RootErrorBoundary (at withExpoRoot.web.js:7)
    in ExpoRootComponent (at registerRootComponent.web.js:6)
    in RootComponent
    in div (created by View)
    in View (created by AppContainer)
    in div (created by View)
    in View (created by AppContainer)
    in AppContainer

**Note**: Getting this warning only in web

packages used:
    Node js v10.16.0
    "@expo/samples": "~3.0.3",
    "@expo/vector-icons": "^10.0.5",
    "@react-navigation/web": "^1.0.0-alpha.9",
    "expo": "^35.0.0",
    "expo-asset": "^7.0.0",
    "expo-constants": "7.0.0",
    "expo-font": "~7.0.0",
    "expo-web-browser": "7.0.1",
    "jwt-decode": "^2.2.0",
    "native-base": "^2.13.8",
    "react": "16.9.0",
    "react-dom": "16.8.3",
    "react-native": "0.59.8"

the full list in the package.json in the repo 

#### Expected behaviour
no such kind of warnings

#### Actual behaviour
there is a Warning: Received `false` for a non-boolean attribute `uppercase` in the web browser console 

#### Steps to reproduce
Repo with the code that reproduces this warning
https://github.com/arsamigullin/native-base-issue

**Comment by Truth1984** [comment]
same issue, use `{Text}` from `react-native` solved this problem

**Comment by jmatsushita** [comment]
This message comes from the `defaultProps` here https://github.com/GeekyAnts/NativeBase/blob/9c470822dc4912c3780cf14426cd3b6a56ef01f4/src/basic/Text.js#L44

Removing this statement gets rid of the warning on react-native-web with no apparent problems caused on the react-native side of things.

**Comment by juandav** [comment]
#3111

**Comment by hanykumar** [comment]
Hi @arsamigullin , I did not find any warning regarding uppercase neither in iOS nor in Android.
Please provide minimal code reprodutcion on snack for the same.

import { Text } from 'native-base'; 
![Screenshot 2020-04-08 at 5 11 57 PM](https://user-images.githubusercontent.com/15860517/78780354-14eb5100-79bc-11ea-8814-9e68e9e355d7.png)


![Screenshot 2020-04-08 at 5 09 14 PM](https://user-images.githubusercontent.com/15860517/78780200-d9508700-79bb-11ea-8ef2-a48e9d2dd132.png)

**Comment by velidan** [comment]
@hanykumar 
I confirm. The same issue.
![image](https://user-images.githubusercontent.com/9897782/79227531-b5cc8700-7e68-11ea-97de-e2ccf258310c.png)

**Comment by m3yevn** [comment]
If we use Text from native rn , there is no theming from NB, any solution for removing the error without using rn Text instead?

**Comment by diegolaciar** [comment]
+1 same issue 

"react-native-web": "^0.11.7",
"native-base": "2.13.8",

  Expo CLI 3.19.2 environment info:
    System:
      OS: macOS 10.15.3
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
      npm: 6.14.2 - ~/.nvm/versions/node/v12.16.1/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^37.0.0 => 37.0.6
      react: ^16.9.0 => 16.9.0
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.0.tar.gz => 0.61.4
    npmGlobalPackages:
      expo-cli: 3.17.21

**Comment by ajitdas123** [comment]
@hanykumar This issue arises when we are using native base with `react-native-web`.

**Comment by juhana** [comment]
This seems to have been fixed already: https://github.com/GeekyAnts/NativeBase/commit/ea024674188469fa9724928a6b7b7224f3cf5305 

There just hasn't been a release after the fix was merged.

**Comment by maxyharr** [comment]
Getting the same issue in web. Since this is already on master, can we just get a release?

**Comment by hanykumar** [comment]
Hi, Please update native-base with the latest v2.13.14 and let us know if the issue still persists.

**Comment by brandon-olin** [comment]
I'm having the same issue. I tried updating to v2.13.14, but that causes a whole host of other errors to pop up. Currently the only configuration I can use to get everything work together is as follows:

`  "dependencies": {
    "expo": "~39.0.2",
    "expo-font": "~8.3.0",
    "expo-status-bar": "~1.0.2",
    "firebase": "7.9.0",
    "native-base": "2.13.8",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-native": "0.45.0",
    "react-native-web": "0.11.7"
  },`

I can use NB components, but it appears that the text styling isn't being applied appropriately. So when I have a button like this:

`<Button info>
  <Text>Click Me!</Text>
</Button>`

It looks like this:
![Screenshot from 2020-10-06 09-48-50](https://user-images.githubusercontent.com/57788075/95225658-41d8bf00-07b9-11eb-91fe-af5f20ee98fe.png)

**Comment by tomvrampio** [comment]
> Hi, Please update native-base with the latest v2.13.14 and let us know if the issue still persists.

I also have this issue in web. Updating to 2.13.14 results in build error [#3231](https://github.com/GeekyAnts/NativeBase/issues/3231#issuecomment-684223710) so I can't test anything else in that release.
