### ISSUE TITLE
unable to resolve TextInputState

### ISSUE THREAD

**Issue by MarcosRenato266** [GeekyAnts/NativeBase#2948]
native-base -v . 2.13.8

already try to clean cache, watchman and etc nothing works :(

![image](https://user-images.githubusercontent.com/4360587/65709521-6313b500-e067-11e9-9caf-7670ea101592.png)

**Comment by hanykumar** [comment]
Hi @MarcosRenato266 , please provide minimal code reproduction on snack if the issue still persists. Closing for now. Please update to latest native-base v2.13.14 first.
