### ISSUE TITLE
how to focus next Input onSubmitEditing using useRef

### ISSUE THREAD

**Issue by theZulqarnain** [GeekyAnts/NativeBase#2949]
unable to focus next input when pressed enter.

```
const attNameRef = useRef(null);

<Input 
    getRef={input => {
       attNameRef= input;
    }}
   onSubmitEditing={() => {
       attNameRef._root.focus();
    }}
/>
```
>undefined is not obj

how can I use onSubmitEditing with **useRef**?

**Comment by Mohammad-Khalid23** [comment]
//use this function to focus on next field
      focusNextField = (id) => {
       this.inputs[id]._root.focus();
       }


          <Input
                keyboardType="email-address"
                name="email"
                onChangeText={(text) => this.setState({ email: text })}
                onSubmitEditing={() => {
                  this.focusNextField('password');
                }}
                returnKeyType={"next"}
                ref={input => {
                  this.inputs['email'] = input;
                }}
              />

              <Input
                name="password"
                onSubmitEditing={() => {
                  this.loginSubmit()
                }}
                returnKeyType={"done"}
                ref={input => {
                  this.inputs['password'] = input;
                }}
              />

**Comment by theZulqarnain** [comment]
@Mohammad-Khalid23 problem is that i'm using hooks so if I use ** getRef** then its not storing in `useRef` variable then I'm unable to access that variable in `focusNextField` function.sorry for late replay!

**Comment by thehappydinoa** [comment]
I think I figured it out:
```js
const passwordInput = useRef(null);

return (
<Container style={styles.container}>
      ...
      <Item rounded style={styles.input}>
        <Input
          onSubmitEditing={() => passwordInput.current._root.focus()}
          returnKeyType={'next'}
        />
      </Item>
      <Item rounded style={styles.input}>
        <Input
          ref={passwordInput}
        />
      </Item>
    ...
    </Container>
)
```

**Comment by hanykumar** [comment]
Hi @theZulqarnain , you can follow this [Link](https://github.com/GeekyAnts/NativeBase/issues/2701#issuecomment-595061731), it must work.

**Comment by thehappydinoa** [comment]
@theZulqarnain You have to use `ref.current._root` with newer version of `react-native`

**Comment by jericopulvera** [comment]
> I think I figured it out:
> 
> ```js
> const passwordInput = useRef(null);
> 
> return (
> <Container style={styles.container}>
>       ...
>       <Item rounded style={styles.input}>
>         <Input
>           onSubmitEditing={() => passwordInput.current._root.focus()}
>           returnKeyType={'next'}
>         />
>       </Item>
>       <Item rounded style={styles.input}>
>         <Input
>           ref={passwordInput}
>         />
>       </Item>
>     ...
>     </Container>
> )
> ```

this did not work on me using

expo --version
3.20.9

**Comment by samipshah100** [comment]
![image](https://user-images.githubusercontent.com/51622592/82753208-869f2300-9de1-11ea-8f3c-fb61c2168e02.png)
working for me

**Comment by hanykumar** [comment]
> > I think I figured it out:
> > ```js
> > const passwordInput = useRef(null);
> > 
> > return (
> > <Container style={styles.container}>
> >       ...
> >       <Item rounded style={styles.input}>
> >         <Input
> >           onSubmitEditing={() => passwordInput.current._root.focus()}
> >           returnKeyType={'next'}
> >         />
> >       </Item>
> >       <Item rounded style={styles.input}>
> >         <Input
> >           ref={passwordInput}
> >         />
> >       </Item>
> >     ...
> >     </Container>
> > )
> > ```
> 
> this did not work on me using
> 
> expo --version
> 3.20.9

Hi, @jericopulvera , what issue did you face using this code. Because it is working fine. Let us know the issue.

**Comment by erickh115** [comment]
> > > I think I figured it out:
> > > ```js
> > > const passwordInput = useRef(null);
> > > 
> > > return (
> > > <Container style={styles.container}>
> > >       ...
> > >       <Item rounded style={styles.input}>
> > >         <Input
> > >           onSubmitEditing={() => passwordInput.current._root.focus()}
> > >           returnKeyType={'next'}
> > >         />
> > >       </Item>
> > >       <Item rounded style={styles.input}>
> > >         <Input
> > >           ref={passwordInput}
> > >         />
> > >       </Item>
> > >     ...
> > >     </Container>
> > > )
> > > ```
> > 
> > 
> > this did not work on me using
> > expo --version
> > 3.20.9
> 
> Hi, @jericopulvera , what issue did you face using this code. Because it is working fine. Let us know the issue.

I have the same issue , .current is undefine

**Comment by quixote15** [comment]
> I think I figured it out:
> 
> ```js
> const passwordInput = useRef(null);
> 
> return (
> <Container style={styles.container}>
>       ...
>       <Item rounded style={styles.input}>
>         <Input
>           onSubmitEditing={() => passwordInput.current._root.focus()}
>           returnKeyType={'next'}
>         />
>       </Item>
>       <Item rounded style={styles.input}>
>         <Input
>           ref={passwordInput}
>         />
>       </Item>
>     ...
>     </Container>
> )
> ```

Worked like a charm !! The only solution that worked for me.

**Comment by hotaryuzaki** [comment]
how to do this in version 3??
