### ISSUE TITLE
Piker in list/forms

### ISSUE THREAD

**Issue by alejonext** [GeekyAnts/NativeBase#295]
Look, the `Piker`, is a `input`, bat is determine a `View`. Well... That's is the code..
```html
<ListItem>
	<InputGroup>
		<Picker
			inlineLabel
			iosHeader="Select number"
			label="Select number"
			mode="dropdown"
			selectedValue={this.state.num}
			onValueChange={num => this.setState({ num })}>
			<Item label='One' value={1} />
			<Item label='Two' value={2} />
			<Item label='Thre' value={3} />
		</Picker>
	</InputGroup>
</ListItem>
```
And not show the piker. Is resolve.. This in [line](https://github.com/GeekyAnts/NativeBase/blob/master/Components/Widgets/ListItem.js#L181)

```javascript
if(child && ( child.type == InputGroup || child.type == Picker ) )
```

**Comment by SupriyaKalghatgi** [comment]
@alejonext Take a look at [Form](https://github.com/GeekyAnts/NativeBase-KitchenSink/blob/master/js/components/form/index.js) of [NativeBase-KitchenSink](https://github.com/GeekyAnts/NativeBase-KitchenSink)

Similar to your use case

**Comment by Papipo** [comment]
I still don't know how to properly render a Picker with a Label. What's InputGroup? Why isn't it documented? :(
