### ISSUE TITLE
<Item> has a few bugs

### ISSUE THREAD

**Issue by cristianoccazinsp** [GeekyAnts/NativeBase#2951]
## I have gone through these following points

- [X] Check latest documentation: https://docs.nativebase.io/
- [X] Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [X] Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- X] Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [X] For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- [X] For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

#### node, npm, react-native, react and native-base version, expo version if used, xcode version
Current/Master

I've been trying to adjust the <Item> component with a floating label prop and font size changes. During the process, I've seen some bugs (and ended up creating a new Item component)

1- Do not use type.displayName. Strings are mangled during production builds and names will be not the same.
https://github.com/GeekyAnts/NativeBase/blob/master/src/basic/Item.js#L105
https://github.com/GeekyAnts/NativeBase/blob/master/src/basic/Item.js#L170
https://github.com/GeekyAnts/NativeBase/blob/master/src/basic/Item.js#L249

2- Font size (for me at least) isn't working, looks like this hardcoded 15 is the culprit: 
https://github.com/GeekyAnts/NativeBase/blob/master/src/basic/Item.js#L403

3- Overall, the animation to top/bottom really only works fine with the default library styles, any change to fonts or sizes will make it pretty much broken (too much floating to top, bottom, etc.). I'm not sure how to fix this globally and being backwards compatible, but I suggest not hardcoding the values at the Input component and neither at the related Input styles class.
Here are a few suggestions: 
- use inputFontSize and contentPadding from variables to decide how much to animate to top
- do the same for the Item['.floatingLabel'] style. It is currently very hackish with lots of magic heights, top, margins, etc, it could be much simpler.

**Comment by hanykumar** [comment]
Hi @cristianoccazinsp , please provide snack for the same. It will be easy for us to reproduce the issue.

**Comment by cristianoccazinsp** [comment]
I've tweaked quite a few styles and components in the project I'm using this library, so I'm not sure if a snack will work with the original's library code.

I can provide the code for the components and styles I've updated, but that might be too much code.  I also had some issues with the latest updates to footer/content (related to SafeAreaView and rotation) so I also had to customize those.

**Comment by hanykumar** [comment]
Hi @cristianoccazinsp , please update to latest native-base v2.13.14 . Let us know if the issue still persists?

**Comment by cristianoccazinsp** [comment]
Hello @hanykumar , thanks for the update, but we are using our own <Item> component now alongside a fork of the library to resolve other issues.

**Comment by hanykumar** [comment]
Closing for now.
Thanks
