### ISSUE TITLE
How can i toggle two different native-base drawers in same screen or same class.

### ISSUE THREAD

**Issue by ppv94** [GeekyAnts/NativeBase#2952]
## Issue Description
I want to toggle two different native-base drawers on the same screen or the same class, how can we do it. if I use drawer inside another drawer, only the main drawer is toggled.
#### Expected behaviour
I want to toggle two different drawers on the same screen.
#### Actual behaviour
only the main drawer is toggled whether main drawer or the second drawer is toggled.
#### Is the bug present in both iOS and Android or any one of them?
Both ios and android.
sample code which I tried is below there.
[sample.js.zip](https://github.com/GeekyAnts/NativeBase/files/3675534/sample.js.zip)

**Comment by hanykumar** [comment]
Hi @ppv94 , can you provide snack for minimal code reproduction for the same?

**Comment by hanykumar** [comment]
Hi @ppv94 , there can be one drawer at a time on one screen. Closing for now.
