### ISSUE TITLE
This project needs an update

### ISSUE THREAD

**Issue by onlycopy** [GeekyAnts/NativeBase#2953]
Your example in Expo is out date. Can you update your example??
![image](https://user-images.githubusercontent.com/20247951/66026333-d3687d80-e522-11e9-9cc0-ff0b4445d2b4.png)

**Comment by david-fanin** [comment]
Yes ? Please. I would like to try!

**Comment by murbanowicz** [comment]
2 months later...
![image](https://user-images.githubusercontent.com/9385106/70144518-5f6f6080-169e-11ea-8806-316d1ba95c10.png)

**Comment by hanykumar** [comment]
#3039 Duplicate
