### ISSUE TITLE
App close before toast close warning

### ISSUE THREAD

**Issue by kahwooi** [GeekyAnts/NativeBase#2955]
I am getting this warning when app reopen, because the app close while the toast is still running:

`'Warning: Can\'t perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in %s.%s', 'the componentWillUnmount method', '\n    in ToastContainer (at connectStyle.js:392)\n    in Styled(ToastContainer) (at Root.js:16)\n    in RCTView (at View.js:45)\n    in View (at Root.js:14)\n    in Root (at connectStyle.js:392)\n    in Styled(Root) (at App.js:18)\n    in Provider (at App.js:17)\n    in App (at renderApplication.js:35)\n    in RCTView (at View.js:45)\n    in View (at AppContainer.js:98)\n    in RCTView (at View.js:45)\n    in View (at AppContainer.js:115)\n    in AppContainer (at renderApplication.js:34)'`

 I have try to close it before the app close:   

```
    showToast('Confirm exit', duration, 'top');

    BackHandler.addEventListener('hardwareBackPress', () => {
       Toast.toastInstance._root.closeToast(); // add this, but still same warning 
        BackHandler.exitApp(); // exit, while toast is still open
    });
```

**Comment by keremcubuk** [comment]
I've same issue. Any solution? @kahwooi

**Comment by salihonder** [comment]
I had the same issue today. I solved it by removing <Root> wrapper.

**Comment by hanykumar** [comment]
Hi, it has been fixed. Please update to latest native-base v2.13.14 . Closing for now. Let us know if the issue still persists.
