### ISSUE TITLE
ScrollableTab lag/slow

### ISSUE THREAD

**Issue by ardynugraha** [GeekyAnts/NativeBase#2956]
Text on Tab change normally but lagging on Tab Header

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/35564421/66290743-39ca1300-e90a-11e9-863c-b7f9541dfad2.gif)

`<Tabs

    scrollWithoutAnimation={true}
    style={{ backgroundColor: '#F7F7FA' }} renderTabBar={(props) => <View
        style={{ backgroundColor: "#FFFFFF" }}>
        <ScrollableTab {...props}
            renderTab={(name, page, active, onPress, onLayout) => (
                <TouchableOpacity key={page}
                    onPress={() => onPress(page)}
                    onLayout={onLayout}
                    activeOpacity={0.4}>
                    <View
                        style={{
                            flex: 1,
                            height: 60,
                            backgroundColor: '#FFFFFF'
                        }}>
                        <TabHeading scrollable
                            style={{
                                backgroundColor: "transparent",
                                width: 150
                            }}
                            active={active}>
                            <Text style={{
                                fontWeight: active ? "normal" : "bold",
                                color: active ? Utils.primaryColor() : "#a1a1a1",
                                fontSize: active ? 15 : 13,
                                justifyContent: 'center',
                                marginTop: 15,
                            }}>
                                {name}
                            </Text>
                        </TabHeading>
                    </View>
                </TouchableOpacity>
            )}
            underlineStyle={{ backgroundColor: Utils.primaryColor(), height: 3 }} />
    </View>
    }>
    <Tab heading="Inprocess"
        style={{ backgroundColor: '#FFFFFF' }}>
        <Text>Inprocess</Text>
    </Tab>
    <Tab heading="Verification"
        style={{ backgroundColor: '#FFFFFF' }}>
        <Text>Verification</Text>
    </Tab>
    <Tab heading="Shipping"
        style={{ backgroundColor: '#FFFFFF' }}>
        <Text>Shipping</Text>
    </Tab>
    <Tab heading="Completed"
        style={{ backgroundColor: '#FFFFFF' }}>
        <Text>Completed</Text>
    </Tab>
    <Tab heading="Rejected"
        style={{ backgroundColor: '#FFFFFF' }}>
        <Text>Rejected</Text>
    </Tab>
</Tabs>`

"native-base": "^2.13.8",
"react": "16.8.6",
"react-native": "0.60.5",

**Comment by sjonchhe** [comment]
I am also facing similar lags
 "react": "16.11.0",
 "react-native": "0.62.2",
 "native-base": "^2.13.12"

**Comment by hanykumar** [comment]
Hi @ardynugraha , @sjonchhe , please update to latest native-base v2.13.14 . Let us know if the issue still persists with more details like, iOS or Android?
