### ISSUE TITLE
Scrollable tab underline position

### ISSUE THREAD

**Issue by naqash-smart-is** [GeekyAnts/NativeBase#2957]
I have a tab bar of four item. (4 tabs)

`<Tabs>
      <Tab heading="Tab1" />
      <Tab heading="Tab2" />
      <Tab heading="Tab3" />
      <Tab heading="Tab4" />
</Tabs>`

When I press the fourth tab button then the tab styling should be update with not setting its position when I press fourth tab but if you have less then four or greater then four then it works fine

![Screenshot from 2019-10-08 18-06-41](https://user-images.githubusercontent.com/56305905/66398086-94d93400-e9f6-11e9-92f3-a2f171d5995e.png)

**Comment by Mohammad-Khalid23** [comment]
Brother can you explain your problem in simple words and share you piece of code in which you are facing problem, then may be you will get the answer of your problem.

**Comment by naqash-smart-is** [comment]
> Brother can you explain your problem in simple words and share you piece of code in which you are facing problem, then may be you will get the answer of your problem.

Active tab styles are not working for 4th tab. 

How can reproduce?
Create a tab bar with four tabs and then just press the fourth tab you will see that the tab Text style changes but tab underline be will remains on its previous position

**Comment by hanykumar** [comment]
Hi @naqash-smart-is , I have test this snippet 
`<Tabs> <Tab heading="Tab1" /> <Tab heading="Tab2" /> <Tab heading="Tab3" /> <Tab heading="Tab4" /> </Tabs>`, but I did not face any problem regarding forth tab underline.  Please try again and let us know if it doesn't work. 
Native base's latest version has been released. [Native base v2.13.12](https://github.com/GeekyAnts/NativeBase/releases/tag/v2.13.12)

**Comment by Rsun24** [comment]
Same here "native-base": "^2.13.15".
The problem when you put Tabs inside Content.
