### ISSUE TITLE
Ejected customized theme causing type errors in Typescript

### ISSUE THREAD

**Issue by bscaspar** [GeekyAnts/NativeBase#2959]
## I have gone through these following points

- [x] Check latest documentation: https://docs.nativebase.io/
- [x] Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x] Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [x] Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [x] For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- [x] For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

## Issue Description
Ejecting the native base theme and extending it in the component files creates Typescript errors similar to: 
`Type '{ children: string; bold: true; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<H3> & Readonly<H3> & Readonly<{ children?: ReactNode; }>'.
      Property 'bold' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<H3> & Readonly<H3> & Readonly<{ children?: ReactNode; }>'.
`

#### node, npm, react-native, react and native-base version, expo version if used, xcode version
node: 10.15.1
nom: 6.11.3
RN: 0.59.8
react: 16.8.3
NB: ^2.13.8
expo: SDK34

#### Expected behaviour
When extending the theme, the prop types for the components are updated to reflect new custom component props.

#### Actual behaviour
The NB component prop types are not updated and therefore Typescript is not made aware of the new prop.

#### Steps to reproduce

Basic code snippet to demonstrate:
H3.js (note I added the "bold" theme item after ejecting):
```js
import variable from './../variables/platform';

export default (variables = variable) => {
  const h3Theme = {
    '.bold': { /// this was added after ejecting
      fontFamily: variables.fontFamilyBold,
    },
    color: variables.textColor,
    fontSize: variables.fontSizeH3,
    lineHeight: variables.lineHeightH3,
  };

  return h3Theme;
};

```

Component:
```js
import * as React from 'react';
import { StyleProvider, H3 } from 'native-base';
import platform from '../theme/variables/platform';

const Example = () => (
  <StyleProvider style={getTheme(platform)}>
    <H3 bold>text</H3> /// this line causes the error. No error when "bold" is removed
  </StyleProvider
)

export Example
```

Not sure I can create a snack with an ejected theme, if so let me know how and I will!

**Comment by hanykumar** [comment]
Hi @bscaspar , please update to latest native-base v2.13.14 . Closing for now. Let us know if the issue still persists.
