### ISSUE TITLE
Is it possible to style label display picker?

### ISSUE THREAD

**Issue by Thunderbird7** [GeekyAnts/NativeBase#296]
<img width="487" alt="screen shot 2559-11-16 at 15 51 18" src="https://cloud.githubusercontent.com/assets/386329/20340541/956747ea-ac14-11e6-9f13-95bcf9beeefc.png">

i use picker in list item. but picker display text can't style such as i need to set position to padding left.
who have any idea to style selected picker label ?

THANK YOU

**Comment by nobalmohan** [comment]
#338

**Comment by stefano-DM** [comment]
@Thunderbird7 @nobalmohan @ferontv
did anyone manage to style it? #338 does not work on iOS

**Comment by gouravsood** [comment]
@sanketsahusoft @Thunderbird7 do we know how to style the selected value? Appears that we can't style the picker selected value on IOS.

**Comment by kodayashi** [comment]
@sanketsahusoft - FYI this still appears to be an issue (including #338 for iOS). I can't the color for the text value set in a picker. Tried the Form's style and the Input's style (iOS).

**Comment by SupriyaKalghatgi** [comment]
#338

**Comment by kodayashi** [comment]
Hi @SupriyaKalghatgi - Yep I noticed #338 but attempts to style the Form to update the color of the text in any Items didn't work.

**Comment by SupriyaKalghatgi** [comment]
@kodayashi It becomes difficult to answer at multiple instances about same query
So please check #388 for updates

**Comment by kodayashi** [comment]
Will do @SupriyaKalghatgi thanks.

**Comment by hanykumar** [comment]
Hi @Thunderbird7, @kodayashi, @stefano-DM , latest version of Native base has been released. 

[Native Base 2.13.12](https://github.com/GeekyAnts/NativeBase/releases/tag/v2.13.12)
