### ISSUE TITLE
Deck Swiper stays static on Android

### ISSUE THREAD

**Issue by haveamission** [GeekyAnts/NativeBase#2960]
## Issue Description

I am on React Native .61, when using the deck swiper, it doesn't actually swipe on Android

#### node, npm, react-native, react and native-base version, expo version if used, xcode version

I believe Node 11. React Native .61, React 16.8, and native base latest
#### Actual behaviour

Card stays static, no movement

#### Steps to reproduce

Setup card swiper, go to page with said card swiper. Deck will not move

#### Is the bug present in both iOS and Android or in any one of them?

Only tested on Android

**Comment by carlos3g** [comment]
I'm having the same problem

**Comment by hanykumar** [comment]
Hi @haveamission , can you share link to snack for minimal code reproduction? It will be easy for us to understand the issue.

**Comment by hanykumar** [comment]
Hi @haveamission , we have update native-base with v2.13.14 . Closing for now due to inactivity. Please let us know if the issue still persists
