### ISSUE TITLE
Datepicker iOS doesn't set the date if the date is today

### ISSUE THREAD

**Issue by fmchan** [GeekyAnts/NativeBase#2961]
```
               <DatePicker
                timeZoneOffsetInMinutes={undefined}
                modalTransparent={false}
                animationType={"fade"}
                androidMode={"default"}
                onDateChange={this.setDate}
                disabled={false}
                />
```

the datepicker pops up with today selected as the default date.
if I want to choose today, i do not have to change the date.
the problem comes that datepicker thinks you do not select any date.

there is no problem on android since android has "OK" button

**Comment by nelsieborja** [comment]
I so badly need a fix for thissss

**Comment by hanykumar** [comment]
Hi @fmchan , you can use `defaultDate={new Date()}` for current date. Closing for now. Let us know if the issue still persists.

```
<DatePicker
            defaultDate={new Date()}
            ...
/>
```
