### ISSUE TITLE
button auto full width 

### ISSUE THREAD

**Issue by kin-for-test** [GeekyAnts/NativeBase#2962]
expect 
![fromweb](https://user-images.githubusercontent.com/23132046/66554522-b9ace300-eb7f-11e9-863e-1859f7dc60be.png)

but the view in android vm like 
![fromandroid](https://user-images.githubusercontent.com/23132046/66554564-cfbaa380-eb7f-11e9-8884-bb4bf8137d96.png)

code 
 

```
import React, { Component } from 'react';
import { Container, Header, Content, Button, Text } from 'native-base';
export default class ButtonThemeExample extends Component {
  render() {
    return (
      <Container>
        <Header />
        <Content>
          <Button light><Text> Light </Text></Button>
          <Button primary><Text> Primary </Text></Button>
          <Button success><Text> Success </Text></Button>
          <Button info><Text> Info </Text></Button>
          <Button warning><Text> Warning </Text></Button>
          <Button danger><Text> Danger </Text></Button>
          <Button dark><Text> Dark </Text></Button>
        </Content>
      </Container>
    );
  }
}
```

i try full={false}  but still not work

**Comment by Mohammad-Khalid23** [comment]
**full={false}** will not work, because when you pass full = {true} then it will apply full button style , other wise in default, button will get full width of the parent container because it is using flex for button style.

you have to give width to the buttons.

**Comment by kin-for-test** [comment]
OH! i see , i thought the button have a default width , because the button show  in docs is not full width

**Comment by gsouf** [comment]
I actually found the doc to be terrible, lot of actual examples do not match the result ;(

**Comment by mkamyszek** [comment]
What is the solution to get it to look like the docs?

**Comment by ahmadsyamim** [comment]
```
<Content>
<View style={{
flex:0
}}>
```

should be fine i think.

**Comment by cleybertandre** [comment]
I've solved it adding a 'alignSelf' style property on the Button:

```
<Button primary style={{alignSelf: 'flex-start'}}><Text> Primary </Text></Button>
```

**Comment by sorxrob** [comment]
> I've solved it adding a 'alignSelf' style property on the Button:
> 
> ```
> <Button primary style={{alignSelf: 'flex-start'}}><Text> Primary </Text></Button>
> ```

apply this won't let you use block and full properties

**Comment by hanykumar** [comment]
Hi @sorxrob, Button doesn't lose any styles using
`<Button primary style={{alignSelf: 'flex-start'}}><Text> Primary </Text></Button>`.
Block or full still works absolutely fine.

Hi @kin-for-test, you can definitly use the solution provided by @cleybertandre for adjusting width.

**Comment by hanykumar** [comment]
Hi @kin-for-test , we have fixed this issue. Changes are done on master branch.

latest version of Native base has been released. 
[Native Base 2.13.12](https://github.com/GeekyAnts/NativeBase/releases/tag/v2.13.12)

**Comment by kin-for-test** [comment]
@hanykumar 
thank you very much!

**Comment by jassonxian** [comment]
> @hanykumar
> thank you very much!

I've upgraded the version, but it doesn't seem to be working yet
Did you take care of that

**Comment by hanykumar** [comment]
Hi @jassonxian , this issue is not fixed in the latest version. But it will be fixed in next version. You will need to import NativeBase from master branch for its working.

**Comment by jmlavoier** [comment]
Hi @hanykumar, is this fix not merged yet?

**Comment by bigwhoop** [comment]
Still seeing this issue today as well. Last release was over 2 months ago. This seems like a rather big issue that should have received a fix by now, not? As someone that hasn't used native base and wanted to give it a go for the first time, this makes me quite hesitant to move forward. 😟

**Comment by HannaKarlson** [comment]
Had the same issue, I solved it by putting my Button inside a View with alignItems prop set. In my case what I was looking for was this

<View alignItems='center'>
<Button>Press me</Button>
</View>
