### ISSUE TITLE
Need To format the Code of the Drawer Section inside the Code Section.

### ISSUE THREAD

**Issue by mohammedSlimani** [GeekyAnts/NativeBase#2963]
I believe this is just a Formatting Issue. The code in the Drawer Section at the Components section is out of place. 
check it here 
https://docs.nativebase.io/Components.html#Drawer

**Comment by hanykumar** [comment]
Thankyou @mohammedSlimani, We will update it.

**Comment by hanykumar** [comment]
Hi @mohammedSlimani , latest version of Native base has been released. 

[Native Base 2.13.12](https://github.com/GeekyAnts/NativeBase/releases/tag/v2.13.12)
