### ISSUE TITLE
Put shadow to Accordion component

### ISSUE THREAD

**Issue by Pmz94** [GeekyAnts/NativeBase#2964]
How can I put a box-shadow to an Accordion?
I have the next code but no shadow in
```javascript
export default function Accordion() {
	return (
		<View style={{
			shadowColor: '#000',
			shadowOffset: { width: 0, height: 2, },
			shadowOpacity: 0.25,
			shadowRadius: 3.84,
			elevation: 5
		}}>
			<Accordion dataArray={array} expanded={0}/>
		</View>
	);
}
```

**Comment by hanykumar** [comment]
Hi @Pmz94 , on which platform you are working on Android or iOS?

**Comment by hanykumar** [comment]
HI @Pmz94 , closing for now due to inactivity. Please let know us know if the issue still persists with more details.
Thanks
