### ISSUE TITLE
Date Picker in Dark Mode

### ISSUE THREAD

**Issue by gabrielgc** [GeekyAnts/NativeBase#2966]
## I have gone through these following points

- [x] Check latest documentation: https://docs.nativebase.io/
- [x] Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x] Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [x] Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [x] For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- [x] For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

#### node, npm, react-native, react and native-base version, expo version if used, xcode version
node: 10.16.3
npm: 6.9.0
react-native: 0.61.1
react: 16.9.0
native-base: 2.13.8
expo: none (but snack created, see below)
xcode: 11

#### Expected behaviour
When dark mode is turned on the date picker will show all months/dates/years as it does in light mode.

#### Actual behaviour
Right now I can only see November and December for months, 17th to the 20th for dates and 2020+ for years when dark mode is turned on. The other options appear to still be part of the picker, but the associated text is not visible. 

#### Steps to reproduce
Turn on dark mode for the device
Open the date picker

Snack to reproduce the issue (as long as the device is in dark mode):
https://snack.expo.io/@kosullivan/nativebase-date-picker-dark-mode

How to enable dark mode:
https://www.howtogeek.com/440078/how-to-enable-dark-mode-on-your-iphone-and-ipad/

![image](https://user-images.githubusercontent.com/361333/66906482-b55d4b80-efff-11e9-9997-646b59301208.png)

#### Is the bug present in both iOS and Android or in any one of them?
iOS only

#### Any other additional info which would help us debug the issue quicker.
Only happens when device is in dark mode. Normal mode works fine. It seems that the selectable items are not visible, but non-selectable are. In our case the picker is only for past dates which is why only Nov/Dec are shown for 2019, but they are not selectable).

###Important

If you want your issue to be looked at quicker, attach a snack reproducible with your issue. Makes it easier for us!

**Comment by Fokus969** [comment]
<DatePicker
                  ...
                  customStyles={{
                    ...
                    datePicker:{backgroundColor: '#222'}
                  }}
              />

**Comment by BogdanTaranenko** [comment]
any progress?

**Comment by pavawit** [comment]
> ```
>             <DatePicker
>               ...
>               customStyles={{
>                 ...
>                 datePicker:{backgroundColor: '#222'}
>               }}
>           />
> ```

it doesn't work
even set theme after eject
```
  datePickerTextColor: '#ff0000',
  datePickerBg: '#00ff00',
```

**Comment by savio777** [comment]
dont work:(

**Comment by muhammadrofiq** [comment]
any update for this issue ?  or just  use  other lib ?
