### ISSUE TITLE
Can not lay a toast in the center of the screen

### ISSUE THREAD

**Issue by hh29077106** [GeekyAnts/NativeBase#2967]
If you want toast to be on center of your screen, you can just pass style to it this way
```
<Button onPress={() =>
   Toast.show({
      text: "Some Text",
      buttonText: "Okay",
      position: "bottom",
      style: { bottom: "50%" }
    })}
>
....
</Button>
```

_Originally posted by @shivrajkumar in https://github.com/GeekyAnts/NativeBase/issues/1114#issuecomment-319628729_

tried this out both on ios and android but the toast is not in the center but somewhere near the bottom

**Comment by hanykumar** [comment]
Hi @hh29077106, You can try this 
`<Button onPress={() => Toast.show({
                        text: 'Wrong password!',
                        buttonText: 'Okay',  
                        position: 'top',                      
                        style: { 
                          top: '100%'
                        }
                      })}>
                        <Text>Toast</Text>
                      </Button>
`. 
It will work.

**Comment by hanykumar** [comment]
Hi @hh29077106 , latest version of Native base has been released. 
[Native Base 2.13.12](https://github.com/GeekyAnts/NativeBase/releases/tag/v2.13.12)
