### ISSUE TITLE
Footer with Input hiding behind keyboard 

### ISSUE THREAD

**Issue by anilios** [GeekyAnts/NativeBase#2969]
## I have gone through these following points

- [] Check latest documentation: https://docs.nativebase.io/
- [] Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [] Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [] Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [] For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- [] For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

## Issue Description
App has a comment page, where all comments are shown in a List. 
In the same screen there is an Input field in Footer, as it should be in the bottom of the screen. Now everything is fine except on tap of Input field keyboard appears and hiding the input field  behind the keyboard.

#### Expected behaviour
Input field should be moved to above of the keyboard.

#### Actual behaviour
Input field hides behind the keyboard.
#### Any other additional info which would help us debug the issue quicker.

###Important

If you want your issue to be looked at quicker, attach a snack reproducible with your issue. Makes it easier for us!

**Comment by hanykumar** [comment]
The above issue is not related to any of the native base component, but an issue with keyboard-aware-scroll-view. So you can post the same in keyboard-aware-scroll-view.
You can try React Native's KeyboardAvoidingView component to handle the same.

**Comment by hanykumar** [comment]
Hi @anilios , latest version of Native base has been released.

[Native Base 2.13.12](https://github.com/GeekyAnts/NativeBase/releases/tag/v2.13.12)
