### ISSUE TITLE
Hooks version of connectStyle

### ISSUE THREAD

**Issue by zenVentzi** [GeekyAnts/NativeBase#2970]
## I have gone through these following points

- [x] Check latest documentation: https://docs.nativebase.io/
- [x] Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x] Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [x] Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [] For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- [] For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

## Question Description

Can we use connectStyle HOC somehow as a hooks version? We're updating our projects to use hooks. We had problems with the HOC version of connectStyle and are looking for a change. 

The problems are Typescript related, maybe I should create another issue for that. Once you wrap your component with connectStyle, you lose all the typescript Prop types that you have defined for the component.

**Comment by John0x** [comment]
Any news about this?

**Comment by janoist1** [comment]
+1
