### ISSUE TITLE
TypeScript: Implicit any issue

### ISSUE THREAD

**Issue by Nomeasmo** [GeekyAnts/NativeBase#2971]
## Issue Description
When compiling with a config setting of `"noImplicitAny": true,` i run into the following issue:

```
node_modules/native-base/index.d.ts:308:23 - error TS7006: Parameter 'item' implicitly has an 'any' type.
308       keyExtractor?: (item, index: number) => string;
```

#### node, npm, react-native, react and native-base version, expo version if used, xcode version
node: v10.16.3
tsc: 3.6.4
    "expo": "^35.0.0",
    "native-base": "^2.13.8",
    "react": "16.8.3",
    "react-native": "https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz",

#### Expected behaviour
Not to have the above error

I think you can achieve this either by extending the interface with that from React native FlatList or use their definition for the keyExtractor. (changes marked with *change*)

quick fix
```
keyExtractor?: (item*:any*, index: number) => string;
```
or
```
interface ReactListViewProps*<ItemT>* extends ReactNative.ScrollViewProps, React.Props<ReactNative.ListView>, Testable {
...
    keyExtractor?: (item*: ItemT*, index: number) => string;
```
or
```
interface ReactListViewProps<ItemT> extends ReactNative.ScrollViewProps, React.Props<ReactNative.*FlatListProps<ItemT>*>, Testable {

... and cleanup here: only those properties need to be defined that are special to native-base

```

#### Actual behaviour
See above

#### Steps to reproduce
run `tsc` with a `tsconfig.json` that has the setting `"noImplicitAny": true`.

#### Is the bug present in both iOS and Android or in any one of them?
n/a
#### Any other additional info which would help us debug the issue quicker.

###Important

**Comment by mattcoker** [comment]
Any updates on this or #3026?
