### ISSUE TITLE
Fix Travis CI

### ISSUE THREAD

**Issue by rsmelo92** [GeekyAnts/NativeBase#2974]
## I have gone through these following points

- [x] Check latest documentation: https://docs.nativebase.io/
- [x] Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x] Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [x] Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [x] For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- [x] For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

## Issue Description

TravisCI is failing, no pull request can be merged. It has been a long time, maybe someone could take a look

Failing message:
```
react-native: command not found
The command "react-native init AwesomeNativeBase" failed and exited with 127 during .

Your build has been stopped.
```

As seen here for example: https://travis-ci.org/GeekyAnts/NativeBase/jobs/587197188?utm_medium=notification&utm_source=github_status

related to
#2924  #2931 #2934 #2935  #2943 #2946 #2968 #2972 #2973

**Comment by sankhadeeproy007** [comment]
Fixed with https://github.com/GeekyAnts/NativeBase/pull/2992
