### ISSUE TITLE
Why is fontSize 0 for Android Header Left Icon Text ?

### ISSUE THREAD

**Issue by mmccartney** [GeekyAnts/NativeBase#2975]
I spent the last hour or so trying to figure out why my the `<Text>` label on my "back button" on Android was not showing up.  Eventually it led me to digging through the style code of `native-base` and that's where I found that it appears to be intentional!

You can observe the behavior directly on the documentation page here:
https://docs.nativebase.io/Components.html#header-icon-text-button-headref

Here is an excerpt of the code:
```
<Container>
        <Header>
          <Left>
            <Button transparent>
              <Icon name='arrow-back' />
              <Text>Back</Text>
            </Button>
          </Left>
```

If you toggle between iOS and Android, you'll see that the "Back" label disappears on Android.  I can confirm that this behavior exists when using `<Button hasText>` as well.

My question is _why?_ is this the intent?  Is this an Android convention and I shouldn't worry about it for my app?

FWIW, I tracked it down to the following code:
* https://github.com/GeekyAnts/NativeBase/blob/master/src/theme/components/Header.js#L197
* https://github.com/GeekyAnts/NativeBase/blob/master/src/theme/components/Header.js#L240
* introduced in #1897 (commit 0b47a0557bdeb367778d275bfc7a099abf109949)

Unfortunately that PR doesn't include any explanation as to why the fontSize was set to zero.

If this is a "desired behavior", I think it should be documented somewhere.  I'm willing to work on a PR for that but would first like to understand the rationale.

Thanks in advance!
Mike

## I have gone through these following points

- [x] Check latest documentation: https://docs.nativebase.io/
- [x] Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x] Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [x] Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [] For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- [x] For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

could not login to slack channel 😢 

## Issue Description

see above

#### node, npm, react-native, react and native-base version, expo version if used, xcode version

```
    "native-base": "^2.13.8",
    "react": "16.9.0",
    "react-native": "0.61.2",
```

```
info Fetching system and libraries information...
System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 360.26 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.12.0 - /usr/local/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.11.3 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.1, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
    Android SDK:
      API Levels: 22, 23, 25, 26, 27, 28
      Build Tools: 23.0.1, 25.0.0, 25.0.1, 25.0.3, 26.0.1, 26.0.2, 26.0.3, 27.0.1, 27.0.2, 27.0.3, 28.0.0, 28.0.2, 28.0.3
      System Images: android-27 | Google APIs Intel x86 Atom, android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.2 AI-181.5540.7.32.5014246
    Xcode: 11.1/11A1027 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.2 => 0.61.2 
  npmGlobalPackages:
    react-native-cli: 2.0.1
    react-native-git-upgrade: 0.2.7
```

#### Expected behaviour

consistent across platforms

#### Actual behaviour

Android does not display `<Text>`

#### Steps to reproduce

see above

#### Is the bug present in both iOS and Android or in any one of them?

Android only

#### Any other additional info which would help us debug the issue quicker.

see code references above

###Important

to reproduce, see doc link above

**Comment by hanykumar** [comment]
Hi @mmccartney , you are right and we are working on it. Well, we have fixed `transparent` `button` with `Icon` and `Text` in `Left` of `Header` in Android. You can access it from master branch.

![Screenshot 2020-03-18 at 7 13 05 PM](https://user-images.githubusercontent.com/15860517/76966814-8a7b7880-694c-11ea-8423-68212e44f2da.png)

> I guess I'd also like to figure out how to override this behavior if so desired. Creating a new theme seems overkill. I tried using `<Text style={{ fontSize: (Platform.OS === 'ios') ? 17 : 14 }}>` and it works well unless you have a `<Body/>`.
> 
> The [documentation](https://docs.nativebase.io/Components.html#header-def-headref) says that `Header` expects `Left`, `Body`, and `Right` but my experience is that only `Left` and `Right` are required and that `Body` might crowd the `Left` label.
> 
> This whole process has made me rethink my UI 🤦‍♂

**Comment by hanykumar** [comment]
Hi @mmccartney , please update to native-base v2.13.14 . Closing for now. Let us know if the issue still persists.
