### ISSUE TITLE
Item with floating label error

### ISSUE THREAD

**Issue by JaEdmuva** [GeekyAnts/NativeBase#2976]
## I have gone through these following points

- [x] Check latest documentation: https://docs.nativebase.io/
- [x] Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x] Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [x] Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [x] For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- [x] For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

## Issue Description

There are two issues actually, related to one another. 
First of all, whenever I try to use Icon inside an Item with floatingLabel to true with Icon as the first child of Item I get an exception.
Because of that I have to move Icon after Label (second child). I do not get an exception, but Icon is rendered at the right side of the Item. Which I don't want, that's why I placed Icon as first child in from the beginning.

#### node, npm, react-native, react and native-base version, expo version if used, xcode version
node: 12.22.1
npm: 6.11.3
react-native: 0.61.2
react: 16.10.2
native-base: 2.13.8

#### Expected behaviour

Icon element should render at the left side (the same order as declared in JSX)

#### Actual behaviour

When declared as first child, exception is throwed: `TypeError: Cannot read property 'props' of undefined`

When moved between Label and Input, it's rendered in the right side.

#### Steps to reproduce
```
 <Item
floatingLabel
{...someOtherProps}
>
            <Icon
              active
              name={icon}
              type="FontAwesome5"
              style={textStyle}
            />
            <Label>{value.label}</Label>
            <Input {...someProps}/>
          </Item>
```

#### Is the bug present in both iOS and Android or in any one of them?

Android (iOS not tested)

#### Any other additional info which would help us debug the issue quicker.

###Important

If you want your issue to be looked at quicker, attach a snack reproducible with your issue. Makes it easier for us!

**Comment by hanykumar** [comment]
Hi @JaEdmuva , It has been fixed. Please update to latest native-base v2.13.14 . Let us know if the issue still persists.

![Screenshot 2020-09-16 at 6 15 36 PM](https://user-images.githubusercontent.com/15860517/93339124-d5694080-f848-11ea-9dce-384325382d2b.png)
