### ISSUE TITLE
iconFamily as a prop for Icon

### ISSUE THREAD

**Issue by ksegla** [GeekyAnts/NativeBase#298]
Hi 
Thanks for the great work. Is it doable to just place iconFamily as props for Icon?
<Icon name=xx iconFamily=yy>
Sometimes, we may want Icon from different families in the same component.

**Comment by sankhadeeproy007** [comment]
That is not something we're looking at right now because you can always import another set of icons from `react-native-vector-icons` for another iconFamily.
