### ISSUE TITLE
TypeScript raises an error when using custom theme props on NativeBase components

### ISSUE THREAD

**Issue by connor-odoherty** [GeekyAnts/NativeBase#2983]
## Issue Description

My codebase uses the ejected NativeBase themes, and extends them with new properties like so:

```
export default (variables /* : * */ = variable) => {
  const contentTheme = {
    flex: 1,
    backgroundColor: "transparent",
    "NativeBase.Segment": {
      borderWidth: 0,
      backgroundColor: "transparent"
    },
   // ----------- CUSTOM THEMES BELOW -----------------
    ".brandPrimary": {
      backgroundColor: variables.brandPrimary
    },
    ".brandSurface": {
      backgroundColor: variables.brandLight
    },
    ".white": {
      backgroundColor: "#fff"
    }
  };

  return contentTheme;
};
```

When I use use the custom theme in my typescript project (by setting the custom theme on a NativeBase component, I get this error:

![Screen Shot 2019-11-05 at 10 38 34 AM](https://user-images.githubusercontent.com/10620559/68417462-521c9000-014b-11ea-9293-adea249c3cf2.png)

Is there any way for me to extend the NativeBase component types so that I can eliminate these TypeScript errors?

#### node, npm, react-native, react and native-base version, expo version if used, xcode version

NativeBase version: 2.12.1

#### Expected behaviour

NativeBase components accept custom prop names without violating TypeScript.

#### Actual behaviour

An error is produced any time a custom prop is set on a NativeBase component.

#### Steps to reproduce

1. Eject NativeBase themes
2. Extend a theme with a new prop name, as shown above
3. Use the styling prop on a NB component:

```
<Content brandPrimary style={{ borderRadius: 6 }}>
  <Children ... />
</Content>
```

4. See the TypeScript error

#### Is the bug present in both iOS and Android or in any one of them?

Present in the IDE before making it to a device

#### Additional questions:

1. Am I extending and using the ejected themes properly?
2. Is it possible for me to upgrade NativeBase while maintaining my ejected theme changes? Is there documentation surrounding best practices for maintaining ejected themes?

**Comment by connor-odoherty** [comment]
Can we get some clarity here? If my methodology is correct, this pretty much breaks NativeBase projects with TypeScript and custom ejected styles

**Comment by RioFiveJack** [comment]
#2828 https://github.com/GeekyAnts/NativeBase/issues/2828

**Comment by hanykumar** [comment]
Hi @connor-odoherty , Please follow [native Base Customize](https://docs.nativebase.io/Customize.html#Customize) for custom theme. Let us know if the issue still persists?
