### ISSUE TITLE
Invalid prop `name` of value `location-exit` supplied to `Icon`

### ISSUE THREAD

**Issue by rosnaib11** [GeekyAnts/NativeBase#2985]
I'm getting this error for both location-exit and location-enter I doubt its missing. https://materialdesignicons.com/icon/location-enter

Versions "native-base": "^2.13.8"

**Comment by hanykumar** [comment]
Hi @rosnaib11 , `<Icon name="location-exit" type="MaterialCommunityIcons" />` and `<Icon name="location-enter" type="MaterialCommunityIcons" />` are working fine. Try with the latest Native-Base v2.13.14 . Let us know if the issue still persists
