### ISSUE TITLE
Customizer crashed when you go to Tabs

### ISSUE THREAD

**Issue by SCasarotto** [GeekyAnts/NativeBase#2987]
## I have gone through these following points

- [x] Check latest documentation: https://docs.nativebase.io/
- [x] Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x] Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [x] Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [x] For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- [x] For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

## Issue Description
Title. Go here https://nativebase.io/customizer/  and click on tabs. Page crashes.

#### Expected behaviour
It not crash.
#### Actual behaviour
it crashes
#### Steps to reproduce
https://nativebase.io/customizer/
Click tabs

#### Any other additional info which would help us debug the issue quicker.

###Important

If you want your issue to be looked at quicker, attach a snack reproducible with your issue. Makes it easier for us!

**Comment by shivrajkumar** [comment]
https://nativebase.io/customizer/ is no longer being maintained
