### ISSUE TITLE
index.d.ts don't includes variables

### ISSUE THREAD

**Issue by naoto-k** [GeekyAnts/NativeBase#2989]
## I have gone through these following points

- [x] Check latest documentation: https://docs.nativebase.io/
- [x] Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x] Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [x] Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [x] For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- [x] For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

## Issue Description

index.d.ts should include variables(./theme/variables/platform)

#### Expected behaviour
Don't occur compile error.

#### Actual behaviour
Occur below compile error.
`Module '"native-base"' has no exported member 'variables'.`

#### Steps to reproduce

use typescript and include below
```
import { variables } from "native-base";
```

#### Any other additional info which would help us debug the issue quicker.

###Important

If you want your issue to be looked at quicker, attach a snack reproducible with your issue. Makes it easier for us!

P.S
Thank you for letting me use NativeBase. I enjoy NativeBase with ReactNative.

**Comment by mehmet-erim** [comment]
I can use `connectStyle`, `getTheme` with imported like this:

`import { connectStyle, getTheme } from 'native-base';`

It works but occurs this error: 
`Module '"native-base"' has no exported member 'connectStyle'.`

index.d.ts should also include `connectStyle`, `getTheme`.
May you  add this?
