### ISSUE TITLE
What is the proper way to nest many components inside a listItem?

### ISSUE THREAD

**Issue by liuzhen2008** [GeekyAnts/NativeBase#299]
I currently have a simple List structure as such. 

```
<List> 
  <ListItem key={somekey}>
     <Text> {some.text} </Text>
     <Text note> {some.otherText} </Text>
  </ListItem>
</List>
```

But it seems to me that after I added second `<Text>` the entire ListItem just decides to not render anything?

Is adding multiple components inside a list not possible/recommended? In that case how do I render a list of actionable items?

**Comment by nobalmohan** [comment]
ListItem can have multiple sibling. Error might be with your repeater.

**Comment by liuzhen2008** [comment]
@nobalmohan  What do you mean? That was my exact code =/

```
      <Container>
        <Content>
          <List>
            <ListItem>
              <Text> diablo </Text>
              <Text> dota </Text>
            </ListItem>
          </List>
        </Content>
      </Container>

```
When doing this. My list won't show anything. Is it wrong to insert to <text> into a list item?

**Comment by himanshu-satija** [comment]
Working for me with RN 0.39.2 and NativeBase 0.5.19. Please check again.

**Comment by niros001** [comment]
s
