### ISSUE TITLE
Picker items on iOS modal does not respect SafeArea when device is horizontal

### ISSUE THREAD

**Issue by david-arteaga** [GeekyAnts/NativeBase#2990]
## I have gone through these following points

- [x] Check latest documentation: https://docs.nativebase.io/
- [x] Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x] Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [x] Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [x] For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- [x] For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

#### node, npm, react-native, react and native-base version, expo version if used, xcode version
- node: v10.16.0
- npm: 6.9.0 (using yarn)
- yarn: 1.17.3
- react-native: 0.61.2
- native-base: 2.13.8
- xcode: 11.2

not using expo
#### Expected behaviour
The picker items should not be displayed beneath screen space that would be outside of a SafeAreaView.
#### Actual behaviour
<img width="964" alt="image" src="https://user-images.githubusercontent.com/7199015/68553530-37b71080-03f0-11ea-874b-6aebc8c9facd.png">

#### Steps to reproduce
```js
import { View, Picker, Container, Content, Item, Label } from 'native-base';
import React from 'react';
import { SafeAreaView } from 'react-native';

export function SomeApp() {
  return (
    <SafeAreaView style={{ flex: 1 }}>
      <View style={{ flex: 1 }}>
        <Container style={{ flex: 1 }}>
          <Content>
            <Item picker>
              <Label>{'Pick an option'}</Label>
              <Picker>
                {Array(10)
                  .fill(null)
                  .map((_, i) => (
                    <Picker.Item
                      label={'Item ' + (i + 1) + ''}
                      value={'Item ' + (i + 1)}
                      key={i}
                    />
                  ))}
              </Picker>
            </Item>
          </Content>
        </Container>
      </View>
    </SafeAreaView>
  );
}
```

#### Is the bug present in both iOS and Android or in any one of them?
Only tested on iOS because of SafeAreaView on iPhone X and forward.
#### Any other additional info which would help us debug the issue quicker.

###Important

If you want your issue to be looked at quicker, attach a snack reproducible with your issue. Makes it easier for us!
- I can't find a way to rotate the device in a snack to a horizontal position.

**Comment by hanykumar** [comment]
Hi @david-arteaga , this issue has been fixed to master branch.
