### ISSUE TITLE
Social Network Component...

### ISSUE THREAD

**Issue by steve21124** [GeekyAnts/NativeBase#3]
What step needed if I want to integrate facebook login or create facebook component for native base?

for simple header,content, footer. is easy. how about more complex layout. Is there any example of complex layout ?

**Comment by sanketsahusoft** [comment]
To answer your first question, you can just use the Facebook login for React Native. It will just work fine. Though, it's on our roadmap to provide easier integration with different Social Networks.

If you want to contribute to NativeBase and add Social Network component, you can follow the guidelines from the docs, provide a write-up on how you intend to build that, develop the component using the same pattern as other components, provide documentation and send a pull request.

To answer your second question, for complex layouts, we are going to provide grid layout like Bootstrap, and as a last resort, you can always use React Native's Flex-box implementation.
