### ISSUE TITLE
How to pass datasource to List

### ISSUE THREAD

**Issue by RezaRahmati** [GeekyAnts/NativeBase#30]
Hello

Great library, I was wondering how should I pass the data to List (since all of the examples are with static data)?

**Comment by sankhadeeproy007** [comment]
The `<List />` component is not a subset of react-native's `<ListView />`. But you can use the `.map` function to iterate through your data dource.

**Comment by sankhadeeproy007** [comment]
Added in v0.5.0. Check the [dosc](http://nativebase.io/docs/v0.5.0/components-ios#dynamicList)

**Comment by bsiddiqui** [comment]
@sanketsahusoft how does `<List>` perform vs. react-native's `<ListView>` for large amounts of dynamic data since it's just a subset of `<View>`?

**Comment by himanshu-sahusoft** [comment]
@bsiddiqui When you pass dataArray and renderRow props to `<List>`, it uses `<ListView>` internally. So the performance should be more or less same.
