### ISSUE TITLE
Can't implement Tabs

### ISSUE THREAD

**Issue by oldo** [GeekyAnts/NativeBase#300]
I'm trying to do a very basic implementation of Tabs, but am not having any luck...

I am rendering the following component:

```
import React, { Component } from 'react';
import { View } from 'react-native';
import { Container, Content, Tabs } from 'native-base';
import TabOne from './TabOne';
import TabTwo from './TabTwo';

class TabsExample extends Component {
    render() {
        return (
            <Container>
                <Content>
                    <Tabs>
                        <TabOne tabLabel='One' />
                        <TabTwo tabLabel='Two' />
                    </Tabs>
                </Content>
            </Container>
        );
    }
}

export default TabsExample;
```

And `<TabOne>` and `<TabTwo>` are both of the structure:

```
import React, { Component } from 'react';
import { Text, View } from 'react-native';

class TabOne extends Component {
  render() {
    console.log('Tab1');
    return (
      <View>
        <Text>Tab1</Text>
      </View>
    );
  }
}

export default TabOne;
```

But all I'm getting is:

<img width="376" alt="screen shot 2016-11-17 at 14 21 19" src="https://cloud.githubusercontent.com/assets/4557648/20375119/2ba3a688-acd1-11e6-95dd-cf165172f565.png">

I've tried a basic implementation using `react-native-scrollable-tab-view` and it works as expected. Any thoughts?

Thanks :-)

**Comment by SupriyaKalghatgi** [comment]
@oldo This has been fixed.

Which version of NativeBase are you using?

**Comment by oldo** [comment]
Version: 0.5.11

**Comment by SupriyaKalghatgi** [comment]
@oldo This has been fixed with NB 0.5.12

Try updating NB

**Comment by oldo** [comment]
Ok, so I've upgraded to 0.5.13 which has improved the situation. Thanks :-)

I am still however finding that the contents of both of the tabs are appearing in the first tab and nothing in the second:

<img width="375" alt="screen shot 2016-11-17 at 18 01 10" src="https://cloud.githubusercontent.com/assets/4557648/20379338/dae27228-acef-11e6-9e4e-2663a2f6e4c5.png">

**Comment by SupriyaKalghatgi** [comment]
@oldo Wrap the components of file `TabOne` and `TabTwo` to NativeBase's **Content** or **View**

**Comment by oldo** [comment]
That got it! Thanks :-)
