### ISSUE TITLE
Adding transparent prop to Button in the Left component hides the text, Android Only

### ISSUE THREAD

**Issue by AndresTIY** [GeekyAnts/NativeBase#3002]
## I have gone through these following points

- [x] Check latest documentation: https://docs.nativebase.io/
- [x] Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x] Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [x] Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [] For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- [] For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

#### Expected behaviour

Expect text to display on Android using `Button` with the `transparent` prop.

#### Actual behaviour

Text does not show in the `Button` component unless I force styles into it with:

```js
const buttonHack = {
  backgroundColor: 'transparent',
  borderColor: 'trasparent',
  shadowOffset: { height: 0, width: 0 },
  shadowOpacity: 0,
  elevation: 0,
};

```

#### Steps to reproduce

```
const HeaderProblem = ({ handleGoBack, handleSave }) => (
  <Container style={{ flex: 1 }}>
    <Header style={styles.headerStyle}>
      <Left style={{ flex: 1 }}>
        <Button onPress={handleGoBack} transparent>
          <Text style={styles.headerSideText}>Cancel</Text>
        </Button>
      </Left>
      <Body style={{ flex: 1 }} />
      <Right style={{ flex: 1 }}>
        <Button onPress={handleSave} transparent>
          <Text style={styles.headerSideText}>Save</Text>
        </Button>
      </Right>
    </Header>
  </Container>

```

Per the docs, `<Header>` is supposed to be used within a `<Container />` component. When wanting to use a touchable text, it's recommended that `Button` is given a `transparent` prop, and the text is render as a child. The odd thing is, that in my example, the button on the `Right` is displayed just fine. Only `Left` doesn't display the text child. If I remove `transparent`, then the text is shown with the button. I can add the different color text props like `success` and those work fine when not used with `transparent`. If I force the `buttonHack` style, then the text is displayed fine. I also tried moving `transparent` to before the `onPress` prop and that didn't yield any results. 

#### Is the bug present in both iOS and Android or in any one of them?
ANDROID

#### Any other additional info which would help us debug the issue quicker.

###Important

If you want your issue to be looked at quicker, attach a snack reproducible with your issue. Makes it easier for us!

**Comment by hanykumar** [comment]
Hi @AndresTIY , We have fixed this issue in Master branch.

**Comment by bob007abc** [comment]
Hi @hanykumar 
The issue can be reproduced in the lastest version 2.13.12.
So, which time are you plan to release the next version?

**Comment by hanykumar** [comment]
Hi @bob007abc , we have release latest natie-base v2.13.14 . Closing for now.
