### ISSUE TITLE
Tabs: didFocus/didBlur not called when switching tabs

### ISSUE THREAD

**Issue by LucasBrazi06** [GeekyAnts/NativeBase#3006]
## I have gone through these following points

- [X] Check latest documentation: https://docs.nativebase.io/
- [X] Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [X] Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [X] Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [] For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- [] For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

## Issue Description

I registered the methods didBlur/didFocus in the components that are displayed in the tabs control and I don't get the events when switching tabs. Eg.: I'm in tab 1 that displays screen 1 and I switch to tab 2 that displays screen 2: screen 1 doesn't get the didBlur event. I would expect it as screen 2 hides the screen 1.

#### node, npm, react-native, react and native-base version, expo version if used, xcode version
npm: v6.4.1
node: v10.15.3
react-native: v0.60.5
native-base: v2.13.5
xcode: v11.2.1 (11B500)

#### Expected behaviour
That screens embedded in tabs receives didBlur()/didFocus() events.

#### Actual behaviour
That screens embedded in tabs do not receive didBlur()/didFocus() events.

#### Steps to reproduce
Create a main component with two tabs and two screens.
In the two embedded screens that are contained the Tabs add this:
```
  public componentDidMount() {
    // Add listeners
    this.didFocus = this.props.navigation.addListener("didFocus", this.componentDidFocus.bind(this));
    this.didBlur = this.props.navigation.addListener("didBlur", this.componentDidBlur.bind(this));
  }

  public componentDidFocus() {
    console.log('componentDidFocus');
  }

  public componentDidBlur() {
    console.log('componentDidFocus');
  }
```

#### Is the bug present in both iOS and Android or in any one of them?
Both

#### Any other additional info which would help us debug the issue quicker.
Nope

**Comment by hanykumar** [comment]
Hi @LucasBrazi06 ,It has been fixed, please update to latest native-base v2.13.14 . Closing for now due to inactivity. Let us know if the issue still persists.
