### ISSUE TITLE
Input width is not responsive after device orientation change

### ISSUE THREAD

**Issue by swiety85** [GeekyAnts/NativeBase#3007]
I have a problem with styling the Item.stackedLabel component - it does not update its width after device orientation change.
As far as I can see the source of the problem is that the NativeBase components use the `variables.deviceWidth` that is initialized once and never updated e.g. on device orientation change.

https://github.com/GeekyAnts/NativeBase/blob/9c470822dc4912c3780cf14426cd3b6a56ef01f4/src/basic/Item.js#L385

I would suggest not make any calculations with the device size or make it in the theme files that it can be easily overwritten and take care about updating values on orientation change.

If you agree with me I can make the PR. I need only your approval that I didn't miss anything.

**Comment by hanykumar** [comment]
Hi @swiety85, You can refer [#3074 ](https://github.com/GeekyAnts/NativeBase/pull/3074). This issue is fixed in this PR.

**Comment by hanykumar** [comment]
Hi @swiety85 , please update to latest native-base v2.13.14 . Closing for now because it has been fixed. Let us know if the issue still persists. Thanks
