### ISSUE TITLE
Header is not adjusting the height of the Android status bar

### ISSUE THREAD

**Issue by angel-luis** [GeekyAnts/NativeBase#3010]
## I have gone through these following points

- [X] Check latest documentation: https://docs.nativebase.io/
- [X] Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [X] Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [X] Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [X] For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- [X] For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

## Issue Description
The Android status bar is over the Header component.

#### node, npm, react-native, react and native-base version, expo version if used, xcode version
node: 10.15.1
npm: 6.4.1
expo: 35.0.0
react: 16.8.3
react-native: 0.61.5
native-base: 2.13.8

#### Expected behaviour
As on iOS, the Header separated from the status bar.

#### Actual behaviour
The Header is merged with the status bar.

#### Steps to reproduce
`expo init` and NativeBase getting started steps. After that, just add the Header component inside the Container from `App.js`.

#### Is the bug present in both iOS and Android or in any one of them?
No. I attach images with the same project in both devices.

![Screenshot_2019-11-30-00-15-32-534_host exp exponent](https://user-images.githubusercontent.com/17672548/69892623-af010580-1307-11ea-8412-356f50146838.png)
![IMG_20191130_001525](https://user-images.githubusercontent.com/17672548/69892624-af010580-1307-11ea-985e-a28090188068.jpg)

**Comment by annjawn** [comment]
I am facing the same issue. Header renders correctly on iOS but in Android it's messed up.

**Comment by diaraujo13** [comment]
![Screen Shot 2020-03-17 at 14 37 04](https://user-images.githubusercontent.com/6627361/76904317-f8e10d80-685c-11ea-9a31-0eeea6abc788.png)

I face same issue. Works correctly on iOS, but not on Android

**Comment by hanykumar** [comment]
Hi @angel-luis , If you are using expo, you need to add `paddingTop: Constants.statusBarHeight` in `Container`. It is not related to `NativeBase`. 
`import Constants from 'expo-constants';`
`<Container style={{flex: 1, paddingTop: Constants.statusBarHeight}}>`

![Screenshot 2020-03-18 at 11 53 49 AM](https://user-images.githubusercontent.com/15860517/76931656-27b7bc00-690f-11ea-88a4-7b11dd3c3eed.png)

**Comment by angel-luis** [comment]
I had to apply a similar fix. Maybe including this in the Docs could help Expo users of NativeBase.

Thank you.
