### ISSUE TITLE
Toast hidden under keyboard on android

### ISSUE THREAD

**Issue by levani** [GeekyAnts/NativeBase#3011]
On android Toast component is opening below the keyboard so it's invisible until the keyboard is closed.

I checked the source and the ToastContainer only checks if the keyboard is opened or not on ios.

What's the story of this if condition?

https://github.com/GeekyAnts/NativeBase/blob/9c470822dc4912c3780cf14426cd3b6a56ef01f4/src/basic/ToastContainer.js#L61

**Comment by hanykumar** [comment]
Hi @levani , can you provide the link to snack of minimal reproduction for the same? I don't see anything like you said regarding Toast hidden under keyboard.
![Screenshot 2020-03-18 at 11 10 50 AM](https://user-images.githubusercontent.com/15860517/76930037-8f6c0800-690b-11ea-977b-cf123483df05.png)

**Comment by hanykumar** [comment]
Hi @levani , closing for now. Let us know if the issue still persists.
