### ISSUE TITLE
How to style the DatePicker? i want to change the colour and font size of the date picker and eliminate the cancel button. How to do that?

### ISSUE THREAD

**Issue by SupriyaGo** [GeekyAnts/NativeBase#3012]
## I have gone through these following points

- [] Check latest documentation: https://docs.nativebase.io/
- [] Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [] Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [] Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [] For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- [] For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

#### Any other additional info which would help us debug the issue quicker.

###Important

If you want your issue to be looked at quicker, attach a snack reproducible with your issue. Makes it easier for us!

**Comment by hanykumar** [comment]
Hi @SupriyaGo , you can use  `textStyle={{color: 'red', fontSize: 40}}` `placeHolderTextStyle={{color: 'green', fontSize: 30}}`.
```
<DatePicker
              defaultDate={new Date(2018, 4, 4)}
              minimumDate={new Date(2018, 1, 1)}
              maximumDate={new Date(2018, 12, 31)}
              locale={'en'}
              timeZoneOffsetInMinutes={undefined}
              modalTransparent={false}
              animationType={'fade'}
              androidMode={'default'}
              placeHolderText="Select date"
              textStyle={{color: 'red', fontSize: 40}}
              placeHolderTextStyle={{color: 'green', fontSize: 30}}
              onDateChange={this.setDate}
              disabled={false}
/>
<Text>Date: {this.state.chosenDate.toString().substr(4, 12)}</Text>
```
![Screenshot 2020-09-16 at 4 20 41 PM](https://user-images.githubusercontent.com/15860517/93328046-d1cdbd80-f838-11ea-865a-67e3c68e0fd8.png)

But you can't change style in main pickers
![Screenshot 2020-09-16 at 4 23 28 PM](https://user-images.githubusercontent.com/15860517/93328214-135e6880-f839-11ea-8d7f-7b0763e0a69e.png)
