### ISSUE TITLE
native base tab bar getting default line under header.

### ISSUE THREAD

**Issue by ppv94** [GeekyAnts/NativeBase#3013]
#### native-base: "^2.13.8",  react-native: "0.61.5"
I am using Native Base tabs in react-native and i am getting default line under the tab bar heading in the native base.

How can I remove the default line under the tab bar heading in the native base?
#### Expected behaviour
I don't want to show line under the tab bar header.
#### Actual behaviour
I am getting default line under the header in the tab bar.
#### screenshot
![Screen Shot 2019-12-04 at 12 27 58 PM](https://user-images.githubusercontent.com/28724702/70120017-8c694680-1691-11ea-8e21-17267f1c14b8.png)

**Comment by erikadelao13** [comment]
Same issue here!

**Comment by hanykumar** [comment]
Hi @ppv94 and @erikadelao13  latest version of Native base has been released.

[Native Base 2.13.12](https://github.com/GeekyAnts/NativeBase/releases/tag/v2.13.12)

**Comment by frossi85** [comment]
Same issue here!

**Comment by hanykumar** [comment]
Hi @frossi85 , we won't fix it in this native-base version 2.x.x. Probably we will add these new features later.
