### ISSUE TITLE
unable to use block button using variable.js

### ISSUE THREAD

**Issue by shubhamgupta536** [GeekyAnts/NativeBase#3014]
Hi,
    I downloaded variable.js online for customizing block button but when i was importing it in my project I was not able to import button in it.
I tried different scenarios and figured out that when i replaced 'btn' with 'button' everywhere in variable.js, I was able to use all the properties such as replacing 'btnPrimaryBg' with 'buttonPrimaryBg'.
Is there any one else facing same issue or its just me who got it?

I have attached my code below - 

import React, {Component} from 'react';
import { Container, Content, Text, Button, StyleProvider, Spinner, getTheme} from 'native-base';
import buttonStyle from '../../../theme/ButtonBlock';
import { styles } from "./styles";

interface IProps {}
export default class LoginScreen extends Component<IProps> {

  render () {
    return (
    < StyleProvider style={getTheme(buttonStyle)}>
      < Container>
        < Content contentContainerStyle={styles.contentStyle}>
          < Button block primary style={styles.buttonStyle} >
              < Text> Start < /Text>
            < /Button>
        < /Content>
      < /Container>
    < /StyleProvider>
    );
  }
};

Styling of content and button code - 

import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  contentStyle: {
    flex: 1,
    justifyContent: 'flex-end',
    marginBottom: 172
  },
  buttonStyle: {
    marginHorizontal: 20
  }
});

**Comment by hanykumar** [comment]
Hi @shubhamgupta536 , please follow [Native-Basse customize](https://docs.nativebase.io/Customize.html#Customize) for the same. Closing for now.
