### ISSUE TITLE
@horiuchie In that case the Content is unscrollable :(

### ISSUE THREAD

**Issue by om-mahato** [GeekyAnts/NativeBase#3019]
@horiuchie In that case the Content is unscrollable :(

webView inside a tab 

<Container>
          <Content contentContainerStyle={{ flex: 1 }}>

          <WebView ...>

          </Content>
</Container>

using this the web view gets rendered but it has fixed height. and content cannot be scrolled.

_Originally posted by @Xyzor in https://github.com/GeekyAnts/NativeBase/issues/107#issuecomment-396978747_

**Comment by hanykumar** [comment]
Hi @om-mahato , can you provide minimal code reproduction on snack for the same?
