### ISSUE TITLE
DeckSwiper - Change Card by pressing button

### ISSUE THREAD

**Issue by brunobraga95** [GeekyAnts/NativeBase#302]
Hello Guys,
DeckSwiper is working great here. The thing is that I also need to make it work (Swipe to right or left) when I click a button, just like tinder.
Does the current implementation of DeckSwiper offers this feature?

**Comment by himanshu-satija** [comment]
We have implemented this and committed to master branch. It will be released with the next version. 

You can call the function `this._deckSwiper.swipeLeft()` and `this._deckSwiper.swipeRight()` where `_deckSwiper` is the ref for DeckSwiper.

**Comment by himanshu-satija** [comment]
Released v0.5.14 which includes this feature

**Comment by brunobraga95** [comment]
Hello himanshu, I just tried it and it is working. The thing is that I had to comment all references to this.props.onSwiping, since I was getting an error saying it was undefined. How do I use this prop?

Great Job by the way!

**Comment by himanshu-satija** [comment]
Thanks for pointing it out. I have released v0.5.15 with the fix.

The prop `onSwiping` is optional. We will soon be releasing docs for this. 
It's a callback which will receive the parameter direction and will be called whenever the card is being swiped. If you start swiping left, it will be called with param `'left'`. If the swipe action is complete, it will be called with param `null`.
