### ISSUE TITLE
How to adjust the tabs bottom container in the size automatically.

### ISSUE THREAD

**Issue by ajay2c9** [GeekyAnts/NativeBase#3025]
Hi,
I'm using NativeBase in my project. I'm facing an issue with the tabs container adjustment scrolling.
Here is the scenario.
I have a screen design like the image height of 100 and after the image, I'm displaying the tabs. I have 20 tabs and 20 arrays. I placed the flat list in the tab container without scrolling option (i.e when the array is loaded in a flat list, it is not scrolled down . container size will be increased.). The tab bar bottom container size is not adjusting according to the flat list height. (i.e when flat list height is greater than the screen height tab bar container is scrolling is fine. In the next tab when the flat list height is small, the container not need to scroll. But the container is scrolling. container size needs to adjust automatically.) How to adjust the tabs bottom container size automatically.

**Comment by hanykumar** [comment]
Hi @ajay2c9 , can you just add snack for minimal reproduction for the same with the screenshots? Is that `FlatList` with Sticky Header?

**Comment by hanykumar** [comment]
Hi @ajay2c9 , closing for now due to inactivity. Let us know if the issue still persists.
