### ISSUE TITLE
How to handle SwipeRow, onRowClose function

### ISSUE THREAD

**Issue by michaelVictoriaDev** [GeekyAnts/NativeBase#3029]
How can I callback my function in specific row or rowId?

I have render data looks like this..

```
<FlatList
                data={filtered}
                onKeyExtractor={(x, i) => i.toString()}
                renderItem={(data) => {
                  return (
                    this.renderFlatListItem(data.index, data.item)
                  );
                }}
              />
```

My renderFunction looks like this...

```
renderFlatListItem(itemKey, itemObject) {
    return (

      <View key={itemKey} >
        <SwipeRow 
          rightOpenValue={-115}
          body={
            ...renderViewComponent
          }
          right={
              ...renderRightComponent
          } 
          />
      </View>

    );
  }
```

my output looks like this.
![ezgif-6-f5678c60dfc7](https://user-images.githubusercontent.com/44763288/70961692-7c079180-20bd-11ea-91a0-22145f57cb45.gif)

Expected output: when the delete function is triggered and successful the item below of the deleted item is automatically close and not automatically open.

Thanks for the advance for the help!.

**Comment by hanykumar** [comment]
Hi @michaelVictoriaDev , can you provide minimal code reproduction on snack?

**Comment by hanykumar** [comment]
Hi @michaelVictoriaDev , you can follow [react-native-swipe-list-view](https://github.com/jemise111/react-native-swipe-list-view). We have removed [Swipeable List](https://docs.nativebase.io/Components.html#swipeable-multi-def-headref) from Nativebase for now.
