### ISSUE TITLE
Unable to change default Icon family.

### ISSUE THREAD

**Issue by sachinshettigar** [GeekyAnts/NativeBase#3030]
## I have gone through these following points

- [x] Check latest documentation: https://docs.nativebase.io/
- [x] Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x] Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [x] Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [x] For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- [x] For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

## Issue Description
I'm trying to change the default fontFamily from 'Ionicons' to 'MaterialIcons' by updating variable variable files as mentioned in the document https://docs.nativebase.io/Customize.html#theme-font-headref.

However the default font is not getting updated to MaterialIcons

#### Expected behaviour
Default font family shoud  be set to MaterialIcons

#### Actual behaviour
Default font family is still  to Ionicons

#### Steps to reproduce

Eject theme and set up theme as per https://docs.nativebase.io/Customize.html#theme-and-variables-headref

set iconFamily:'MaterialIcons' in material.js variable file 

in any component use material icon as Eg:
 <Icon name="accessibility" />

#### Any other additional info which would help us debug the issue quicker.
I tried to debug and found that in the file 
https://github.com/GeekyAnts/NativeBase/blob/master/src/basic/IconNB.js
in setIcon function the context is undefined when called from constructor, so it is not able to read the theme file variable

###Important
let me know if i still need to create a snack

**Comment by sm2017** [comment]
I have same issue in react-native@0.62.2

**Comment by sm2017** [comment]
Duplicate issue https://github.com/GeekyAnts/NativeBase/issues/3061

**Comment by sm2017** [comment]
@sankhadeeproy007 @hanykumar 
Take a loot please
