### ISSUE TITLE
Adjust layout with button, when keyboard is active

### ISSUE THREAD

**Issue by RenanNeitzel** [GeekyAnts/NativeBase#3031]
## I have gone through these following points

- [ x ] Check latest documentation: https://docs.nativebase.io/
- [ x ] Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [ x ] Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [ x ] Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink

## Issue Description

On my app, I have short forms where the button stay on bottom of screen. But, when keyboard is active and input are on focus, my button need fit in near the form (inputs).
Below have the print of screen rendered:

![Image from iOS (1)](https://user-images.githubusercontent.com/41584304/71030359-036df880-20f0-11ea-8dcf-2e0c7c7f8826.png)

And below is the print screen when the input is in focus, and my button doesn't fit near the form:

![Image from iOS](https://user-images.githubusercontent.com/41584304/71030401-14b70500-20f0-11ea-8cf8-7a22c46381b4.png)

What I need: 

![Image from iOS (2)](https://user-images.githubusercontent.com/41584304/71030691-b9d1dd80-20f0-11ea-9d4c-5e37afca7514.png)

Have any prop of keyboard-aware-scroll-view, where I can make my button fit near the form ? How can I do that ?

Tks !

**Comment by hanykumar** [comment]
@RenanNeitzel The above issue is not related to any of the native base component, but an issue with `keyboard-aware-scroll-view`. So you can post the same in `keyboard-aware-scroll-view`.

**Comment by RenanNeitzel** [comment]
I couldn't adjust the button the right way because my flexbox style was forcing the button to always keep down with 'justifyContent:' space-between ''.
I solved this problem with the nativeEvent 'keyboardWillShow' and 'keyboardWillHide' method.
Thank you for your help !

**Comment by hanykumar** [comment]
Hi @RenanNeitzel , latest version of Native base has been released. 

[Native Base 2.13.12](https://github.com/GeekyAnts/NativeBase/releases/tag/v2.13.12)
