### ISSUE TITLE
Picker in IOS is not usable as a native method argument?

### ISSUE THREAD

**Issue by tuanhoang90896** [GeekyAnts/NativeBase#3034]
RN: 0.60.5
Native-base: 2.13.8
![Simulator Screen Shot - iPhone 8 Plus - 2019-12-27 at 10 36 44](https://user-images.githubusercontent.com/31724821/71499829-ec1fcf80-2894-11ea-8c29-3bbca7609956.png)
When i click picker in IOS app and show error.
How fix it?
Please help me!

**Comment by jmontoya-i-strategies** [comment]
I'm sorry man but I have the same error and nobody helps me.

**Comment by ilya-bmi** [comment]
I get the same error.
react-native 0.59.9
native-base 2.12.0

**Comment by atablash** [comment]
Same problem here with Expo 35.0.0 and native-base 2.8.2.

**Comment by hanykumar** [comment]
Hi @tuanhoang90896 , can you provide snack for minimal reproduction for the same. It will easy for us to identify this issue.

**Comment by hanykumar** [comment]
Hi @tuanhoang90896 , please update with latest native-base v2.13.14 . Let us know if the issue still persists.
