### ISSUE TITLE
cannot copy when textinput is disabled

### ISSUE THREAD

**Issue by GSingh01** [GeekyAnts/NativeBase#3036]
After disabling a textInput, i can no longer copy the text. Is there an alternative that i can try.
Any help is appreciated.

Thanks

**Comment by hanykumar** [comment]
Hi @GSingh01 , unfortunately, this is not possible in mobile apps. But you can do the same in websites by following inspect element of the web page. 
Thankyou

**Comment by hanykumar** [comment]
Hi @GSingh01 , closing for now to inactivity.
