### ISSUE TITLE
Expo QR example not working with Expo client V33.0.0

### ISSUE THREAD

**Issue by elgambet** [GeekyAnts/NativeBase#3039]
## I have gone through these following points

- Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues

Closed issue: https://github.com/GeekyAnts/NativeBase/issues/2296

## Issue Description

Expo app fails to load the example.

#### node, npm, react-native, react and native-base version, expo version if used, xcode version
Expo client version: 33.0.0
Android: Android 9
Device: moto g6 plus 

#### Expected behaviour
Load QR expo example

#### Actual behaviour
Expo QR example fails with message:
`Something went wrong. This project uses SDK v32.0.0, but this expo client requires at least v33.0.0`

#### Steps to reproduce
1) Download android latest Expo client (v33.0.0)
2) Scan QR code from [https://nativebase.io/](https://nativebase.io/) with expo

#### Is the bug present in both iOS and Android or in any one of them?
Only tested on Android

**Comment by shivrajkumar** [comment]
Fixed this, working now
