### ISSUE TITLE
Expanding Content to fill entire screen when containing a react-native-gifted-chat component

### ISSUE THREAD

**Issue by riazkarim** [GeekyAnts/NativeBase#304]
When I use the the gifted-chat component, it only fills out a third of the screen when placed in the Content section of render().

Placing it directly in the render() fills the entire screen as normal. 

More details and a screen: https://github.com/FaridSafi/react-native-gifted-chat/issues/284

Is there a way to make the Content fill the entire screen?

**Comment by SupriyaKalghatgi** [comment]
@riazkarim Wrap up the chat component in NativeBase `View`.

**Comment by riazkarim** [comment]
That did it. Thanks!
