### ISSUE TITLE
Form Floating label is not working in android

### ISSUE THREAD

**Issue by ShuKTan** [GeekyAnts/NativeBase#3040]
Hello,

While testing the floating label form component in Android 10, it is not working as expected.
I am using google pixel XL in emulator.

Type text get overlapped over label. Label doesn't get animated upwards.

**Comment by hanykumar** [comment]
Hi @ShuKTan , I don't anything like that in Android 10 Pixel. Can you just provide snack for the same?
`<Item floatingLabel>`
`              <Label>Usename</Label>`
`              <Icon name="cloud" />`
  `            <Input />`
`            </Item>`
![Screenshot 2020-03-18 at 10 05 58 AM](https://user-images.githubusercontent.com/15860517/76925680-3b0f5b00-6900-11ea-9400-60b3bb30effd.png)

**Comment by hanykumar** [comment]
Hi @ShuKTan , closing for now due to inactivity. Let us know if the issue still persists.
