### ISSUE TITLE
Native Base Picker issue Picker.Item doesn't scroll  

### ISSUE THREAD

**Issue by Bilal112** [GeekyAnts/NativeBase#3042]
## I have gone through these following points

- [] Check latest documentation: https://docs.nativebase.io/
- [] Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [] Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [] Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [] For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- [] For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

#### Any other additional info which would help us debug the issue quicker.

###Important

If you want your issue to be looked at quicker, attach a snack reproducible with your issue. Makes it easier for us!

**Comment by Bilal112** [comment]
i have a 18 picker item but it only show 10 and 8 is not showing and i can't scrool

**Comment by hanykumar** [comment]
Hi @Bilal112 , can you just provide snack for minimal reproduction for the same? Please share screenshots at least for our easy understanding of this issue.

**Comment by hanykumar** [comment]
Hi @Bilal112 , it has been fixed. Please update to latest native-base v2.13.14 . Closing for now due to inactivity.
