### ISSUE TITLE
Rounded button ripple effect on Android (OnePlus)

### ISSUE THREAD

**Issue by jenskuhrjorgensen** [GeekyAnts/NativeBase#3043]
#2836  I have gone through these following points

- [x] Check latest documentation: https://docs.nativebase.io/
- [x] Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x] Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [x] Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink --> **Doesn't work**: "[This project uses SDK v32.0.0, but this Expo client requires at least v33.0.0](https://github.com/GeekyAnts/NativeBase/issues/3039)"
- [x] For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- [x] For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

## Issue Description
The ripple effect of `rounded` `Button`'s goes beyond the button container on some Android devices:
![Screenshot_20200115-133003](https://user-images.githubusercontent.com/28528363/72434930-20ecbb80-379d-11ea-862a-ecced81ce091.jpg)

I've created [this snack](https://snack.expo.io/S17BwF3lL) and it works in the Appetize web Android emulator, but it doesn't work on my OnePlus 5T with Oxygen 9.0.9.
>

The issue has already been addressed [here](https://github.com/GeekyAnts/NativeBase/issues/2596), but has been closed. 

#### node, npm, react-native, react and native-base version, expo version if used, xcode version
"expo": "34.0.0"

#### Expected behaviour
The ripple effect goes beyond the button container.

#### Actual behaviour
The ripple effect stays within the button.

#### Steps to reproduce
See previous linked snack. The error happens with this code:
```
<Button rounded>
    <Text>Click Me!</Text>
</Button>
```

#### Is the bug present in both iOS and Android or in any one of them?
Some Android devices, so far only reproduced on OnePlus 5T.

**Comment by hanykumar** [comment]
Hi @jenskuhrjorgensen , I have tested in OnePlus 6T and pixel phone Android emulator, I didn't see anything wrong in ripple effect of rounded button.

**Comment by jenskuhrjorgensen** [comment]
@hanykumar Thanks for testing some devices.

**Comment by backmeupplz** [comment]
@hanykumar Actually, it happens on some phones with my users (e.g. on Redmi Note 7 and Honor 9 Pro). Change `androidRippleColor` to something more visible than white to see it.

**Comment by backmeupplz** [comment]
I fixed it on my end with the following hacky component:

```import React, { Component } from 'react'
import { Button as NativeBaseButton, View, NativeBase } from 'native-base'
import { Platform } from 'react-native'

export class Button extends Component<NativeBase.Button> {
  render() {
    return Platform.OS === 'android' ? (
      <View
        style={{
          overflow: 'hidden',
          width: this.props.block ? '100%' : undefined,
        }}
        removeClippedSubviews
      >
        <NativeBaseButton {...this.props} />
      </View>
    ) : (
      <NativeBaseButton {...this.props} />
    )
  }
}```

The code is not pretty and doesn't account for a few edgecases, but works for me at the moment.  I guess either `overflow` or `removeClippedSubviews` is missing on the native base button.

**Comment by Aryk** [comment]
The "rounded" tag is definitely affecting buttons on Android. For me any area outside the <Text> tag is color and styled correctly, but does not receive the onPress event. Only the actual <Text> tag will receive the onPress events.

**Comment by jenskuhrjorgensen** [comment]
@backmeupplz Thanks for your hack 👍  I hope the NativeBase team will fix this sometime soon 🤞

**Comment by backmeupplz** [comment]
It's not stale! :)) We still need this fix!!
