### ISSUE TITLE
Text strings must be rendered in a <Text> component

### ISSUE THREAD

**Issue by arunkumar413** [GeekyAnts/NativeBase#3046]
#### node, npm, react-native, react and native-base version, expo version if used, xcode version

 "@react-native-community/masked-view": "^0.1.5",
    "native-base": "^2.13.8",
    "react": "16.9.0",
    "react-native": "^0.61.5",
    "react-native-datepicker": "^1.7.2",
    "react-native-easy-grid": "^0.2.2",
    "react-native-gesture-handler": "^1.5.3",
    "react-native-onboarding-swiper": "^1.1.0",
    "react-native-paper": "^3.4.0",
    "react-native-safe-area-context": "^0.6.2",
    "react-native-vector-icons": "^6.6.0",
    "react-navigation": "^4.0.10",
    "react-navigation-stack": "^2.0.13"

#### Expected behaviour
`<Text>`  components inside the `<Button>` components should display correctly and shouldn't throw the above error

#### Actual behaviour

Throwing an error: text strings must be rendered in a `<Text>` component when the `<Text>` component is used inside a `<Button>` component. However the error doesn't occur for web view

#### Steps to reproduce
I have isolated the issue  and here is the snak link (https://snack.expo.io/Skfyu4l_U). And here is the console log of the my test rect native app: https://paste.ubuntu.com/p/GgQWCBFChz/

#### Is the bug present in both iOS and Android or in any one of them?
Both Android and iOS
#### Any other additional info which would help us debug the issue quicker.

###Important

If you want your issue to be looked at quicker, attach a snack reproducible with your issue. Makes it easier for us!

**Comment by rahsheen** [comment]
This seems similar to the conditional rendering differences between React web and React Native.

In react-native, you can't do something like `valueNotZero && <MyComponent />` because if `valueNotZero` _is_ actually `0`, react-native will try to render the text `0` and blow everything up since it's not wrapped it a `Text` component.

You're essentially doing the same thing by putting whitespace inside the `Button`. Just do `<Button />` or `<Button></Button>`

**Comment by deveshrawat** [comment]
Working Fine You need to pass something  in the  `<Button></Button>`
```
   <Button>
          <Text>Something</Text>
   </Button>
```
this thing able to render without any error.

**Comment by hanykumar** [comment]
Hi @arunkumar413 , please update to latest native-base v2.13.14 . Let us us know if the issue still persists.
