### ISSUE TITLE
Android losing side toggle button with search bar

### ISSUE THREAD

**Issue by skyride99** [GeekyAnts/NativeBase#305]
When i have the search bar, and a button in the header, on Android. The button disappears.

<img width="399" alt="screen shot 2016-11-18 at 4 39 59 pm" src="https://cloud.githubusercontent.com/assets/3801142/20423850/bfc35eb2-adad-11e6-8144-8831c742e9ca.png">

**Comment by skyride99** [comment]
on IOS it looks like this

<img width="376" alt="screen shot 2016-11-18 at 9 09 40 pm" src="https://cloud.githubusercontent.com/assets/3801142/20431144/708a08d4-add3-11e6-9036-99f7acc637df.png">

**Comment by SupriyaKalghatgi** [comment]
@skyride99 NativeBase does not support button with Searchbar for Android

**Comment by shivrajkumar** [comment]
Fixed in v2
You will need to eject the theme http://nativebase.io/docs/v2.0.0/customize#themingNativeBaseApp
and do the changes as per your requirements

**Comment by zcxzmzy** [comment]
Android losing side toggle button with search bar
