### ISSUE TITLE
How to cancel Toast subscription?

### ISSUE THREAD

**Issue by senda-dev** [GeekyAnts/NativeBase#3050]
The error:

> Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in %s.%s, the componentWillUnmount method,
    in ToastContainer (at connectStyle.js:392)
    in Styled(ToastContainer) (at Root.js:16)
    in RCTView (at Root.js:14)
    in Root (at connectStyle.js:392)
    in Styled(Root) (at App.js:57)

I've this, but it doesn't fixes the warning:
`componentWillUnmount() {
    Toast.hide();
  }`

**Comment by hanykumar** [comment]
Hi @senda-dev , can you provide snack for minimal reproduction for the same?

**Comment by senda-dev** [comment]
```
render() {

  Toast.show({
    text: myText,
    duration: 4000,
    position: "top"
  });

  return( ... );
}
```

**Comment by avy-sha** [comment]
Hey, I have a similar problem. You found any solution?

**Comment by avy-sha** [comment]
I just removed the Root HOC and it worked for me.

**Comment by mshanu** [comment]
@avy-sha can you elaborate what you mean by removed the Root HOC?
