### ISSUE TITLE
Property '_root' does not exist on type

### ISSUE THREAD

**Issue by janekolszak** [GeekyAnts/NativeBase#3053]
## Issue Description
When trying to (for example) open a Drawer TSC complains that there's no _root in the Drawer type.
It works, but it doesn't compile.

#### Expected behaviour
This should compile:
`this.drawer._root.open()`

#### Actual behaviour
tsc error: `Property '_root' does not exist on type 'Drawer'`

**Comment by z3v0k** [comment]
+1

**Comment by mehmet-erim** [comment]
Hi @janekolszak,

My component like this:
```jsx
import { Text, View, List, ListItem, Left, Button, Icon, Body, Drawer } from 'native-base';
import React, { useEffect, useRef } from 'react';

export function DrawerContent() {
  const drawerRef = useRef();

console.log(drawerRef.current._root) // it works

  return (
    <View>
      <Drawer ref={drawerRef} />
    </View>
  );
}
```

I handled the ref by using the `useRef`.

**Comment by hanykumar** [comment]
Hi @janekolszak , Please follow [here](https://github.com/GeekyAnts/NativeBase/issues/3119#issuecomment-689504841). Closing for now. Let us know if the issue persists.

**Comment by darron1217** [comment]
Same issue here.
It works well on javascript, but this error is shown when using typescript.
