### ISSUE TITLE
Typescript getTheme() no exported member

### ISSUE THREAD

**Issue by IronTony** [GeekyAnts/NativeBase#3058]
Hi all, I love Nativebase and I use it a lot.
Today I started to use Typescript, everything is well configured, but the problem is that in my App.tsx I have this warning in the getTheme() as you can see below.
I have not ejected the theme actually.

![image](https://user-images.githubusercontent.com/3645225/73594777-b6b07680-4511-11ea-921b-7773e33def92.png)

I am using:
react-native: 0.61.5
react: 16.9.0
native-base: 2.13.8

**Comment by lsmod** [comment]
running into the same issue. Any workaround ?

**Comment by RajithaKumara** [comment]
Any updates? I have the same issue.

**Comment by hanykumar** [comment]
Hi @IronTony , Please follow [NativeBase theme Customize](https://docs.nativebase.io/Customize.html#theaming-nb-headref). You can't import `getTheme` from `native-base`.
