### ISSUE TITLE
Theme variable `iconFamily` is not applied correctly

### ISSUE THREAD

**Issue by krazijames** [GeekyAnts/NativeBase#3061]
https://github.com/GeekyAnts/NativeBase/blob/ba39355c3be5ba4600dd05bdec0aee5859a863b8/src/basic/IconNB.js#L28
In `IconNB` component,  `setIcon()` is called in component's constructor.
But at that time, `this.context` seems to be `undefined` so the value of `iconFamily` is not applied except for `Ionicons` and because of this, icons are not rendered correctly.

**Comment by jknight12882** [comment]
Can confirm i am seeing the same thing

**Comment by krazijames** [comment]
1. Setup packages
```sh
react-native init AwesomeNativeBase
cd AwesomeNativeBase
yarn add native-base
react-native link
node node_modules/native-base/ejectTheme.js
```

2. Update `App.js`
```jsx
import React from 'react';
import {Icon, StyleProvider} from 'native-base';
import getTheme from './native-base-theme/components';
import variables from './native-base-theme/variables/platform';

export default function App() {
  return (
    <StyleProvider style={getTheme({...variables, iconFamily: 'FontAwesome5'})}>
      <Icon name="home" />
    </StyleProvider>
  );
}
```

3. Run app
```sh
yarn ios && yarn android
```

When I use `type` property directly (`<Icon name="home" type="FontAwesome5" />`), it works fine. But I want to use `iconFamily` to apply icon type for all of `Icon` component in whole app.

**Comment by boulgom** [comment]
Same here.
The context is not setup in the constructor 

It seems that importing the context in the constructor solves the issue 

Thats is to say replacing
`  constructor(props) {
    super(props);
    this.setIcon(props.type);
  }`

By 
`  constructor(props,context) {
    super(props,context);
    this.setIcon(props.type);
  }`

maybe it is linked to react version. I'm in 16.12.0 and react native 0.61.5

**Comment by sm2017** [comment]
I have same issue in react-native@0.62.2
