### ISSUE TITLE
Typography H3 crops the punctuation

### ISSUE THREAD

**Issue by bikerp** [GeekyAnts/NativeBase#3064]
#### Tested using the sample code from NativeBase documentation

```
import React, { Component } from 'react';
import { Container, Header, Content, H1, H2, H3, Text } from 'native-base';

export default class TypographyExample extends Component {
  render() {
    return (
      <Container>
        <Header />
        <Content>
          <H1>ĚŠČŘ</H1>
          <H2>ĚŠČŘ</H2>
          <H3>ĚŠČŘ</H3>
          <Text>Default</Text>
        </Content>
      </Container>
    );
  }
}
```

#### Bug is present in both iOS and Android
![Screenshot (6  2  2020 14_51_08)](https://user-images.githubusercontent.com/16473023/73944820-82fb9500-48f3-11ea-87ed-33d68ec8ca97.png)

**Comment by hanykumar** [comment]
Hi @bikerp , we have fixed this issue and the fix is on master. You can pull Native Base from master branch.
![Screenshot 2020-03-09 at 10 34 34 AM](https://user-images.githubusercontent.com/15860517/76188963-77a3ce00-61ff-11ea-8920-cacbca14fdfc.png)

**Comment by bikerp** [comment]
Hi @hanykumar thank for the fix

**Comment by hanykumar** [comment]
Hi @bikerp , latest version of Native base has been released. The issues should be fixed now.
[Native Base 2.13.12](https://github.com/GeekyAnts/NativeBase/releases/tag/v2.13.12)
