### ISSUE TITLE
Drawer 在Xr上无法关闭

### ISSUE THREAD

**Issue by HeMa321** [GeekyAnts/NativeBase#3065]
![企业微信截图_b7221523-4f89-46cb-b533-7f9caca5fbf5](https://user-images.githubusercontent.com/22217495/74095565-b88bc280-4b2d-11ea-8250-74f0a7d641fd.png)

onClose在iphone手机上 6s,6可以关闭,但是在xr手机上无法关闭

**Comment by hanykumar** [comment]
Hi @HeMa321 , You can follow [here](https://github.com/GeekyAnts/NativeBase/issues/3119#issuecomment-689504841) if you are facing problem in creating `Drawer`. if not, please provide minimal code reproduction on snack for the same.

**Comment by hanykumar** [comment]
Hi @HeMa321 , closing for now.
