### ISSUE TITLE
Content enableOnAndroid is not working when container has flex set to 1

### ISSUE THREAD

**Issue by lakshmajim** [GeekyAnts/NativeBase#3068]
## I have gone through these following points

- [x] Check latest documentation: https://docs.nativebase.io/
- [x] Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [] Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [x] Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [] For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- [] For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

#### node, npm, react-native, react and native-base version, expo version if used, xcode version
- node 12.13.1
- npm 6.12.1
- expo 3.11.1
- native-base ^2.13.8
- react native ~0.61.4

#### Expected behaviour
 The TextInput filed should be visible when user is trying to enter some data in text field. (keyboardAvoidView functionality should work)
 
#### Actual behaviour
The inputs fileds were hidden when the keyboard pops in.

#### Steps to reproduce
[Snack link](https://snack.expo.io/@gruminion/nativebase-kbav-issue) to reproduce the issue

#### Is the bug present in both iOS and Android or in any one of them?
I have checked only on Android
#### Any other additional info which would help us debug the issue quicker.
When i have removed `flex:1` styling from the content this is working as expected.
###Important

If you want your issue to be looked at quicker, attach a snack reproducible with your issue. Makes it easier for us!

[Snack link](https://snack.expo.io/@gruminion/nativebase-kbav-issue) to reproduce the issue

**Comment by lakshmajim** [comment]
Any update / help on the above mentioned issue ?

**Comment by hanykumar** [comment]
Hi @lakshmajim , do you want to achieve this?

![Screenshot 2020-03-10 at 4 45 38 PM](https://user-images.githubusercontent.com/15860517/76307443-d72cd700-62ee-11ea-9ecc-ab68dfdbc92a.png)

If yes, It works fine in simulator. But if not, you can try [keyboardavoidingview](https://reactnative.dev/docs/keyboardavoidingview) also to achieve this functionality.
`import {KeyboardAvoidingView} from 'react-native';`

`<KeyboardAvoidingView style={styles.container} behavior="padding" enabled>`
 ` ... your UI ...`
`</KeyboardAvoidingView>;`

**Comment by lakshmajim** [comment]
@hanykumar That's not  what I want to achieve,[The attached screen](https://user-images.githubusercontent.com/15860517/76307443-d72cd700-62ee-11ea-9ecc-ab68dfdbc92a.png) 
If we see there, the **save button** is floating over some other fields, which is not the expected behavior.

Note I have tried using **KeyboardAvoidView* with NativeBase **Content**, which is giving some unexpected results there. For now, I had re-written the entire screen with RN's *View* component which is working as expected.

FYI, I'm redescribing the things to reproduce the problem here, when I have used *Content* component
1. When we apply the following styles to container 
    ```
    const styles = StyleSheet.create({
         container: {
              flex: 1,
              paddingHorizontal: 16,
              justifyContent: 'space-between',
         },
     })
     ```



1. The elements i.e, `<Form>` and `<Button>` are aligned vertically at both the edges of the screen. This is my expected behavior here.
1. The *issue* I'm facing here is that When we are trying to edit the address field, the keyboard is covering the address field.

**Comment by hanykumar** [comment]
Hi @lakshmajim , in that case you need to scroll `<Form> ... </Form>`, so that you can click any field while showing keyboard. Try this
`<KeyboardAwareScrollView> <Form> ... </Form> </KeyboardAwareScrollView>`
 Follow [KeyboardAwareScrollView](https://github.com/APSL/react-native-keyboard-aware-scroll-view) to install.

`import { KeyboardAwareScrollView } from 'react-native-keyboard-aware-scroll-view';
`

**Comment by lakshmajim** [comment]
I don't want to incur additional libraries, as I am having this issue at one place.

**Comment by lakshmajim** [comment]
This is how I solved my issue i.e, a temporary workaround
1. Completely removed **NativeBase** *Content* and *Container* components at-least for this screen 
1. Used **ReactNative's** components
```
<KeyboardAvoidingView behavior='padding' style={styles.container}>
          <ScrollView>
                 <Form>
                    // ..... Other UI components
                 </Form>
          </ScrollView>
          <ButtonComponent />
</KeyboardAvoidingView>
```

@hanykumar Thanks for the support,
Let me know if have any other solutions to solve this in a better way (apart from using additional libraries)
