### ISSUE TITLE
Proposal

### ISSUE THREAD

**Issue by FDiskas** [GeekyAnts/NativeBase#3069]
Thanks for nice project.

I have some ideas to share

1. All project should be written in TypeScript
1. Type definitions generated automatically
1. Generate `prop-types` on the fly and for development just use simple types
1. `dist` folder should not be in the repo
1. `dist` should be compiled and published on each release
1. add some e2e tests for mobile and web versions
1. remove Flow from project.

Do you have any roadmap and suggestions also?

**Comment by sanketsahusoft** [comment]
Are you the same Vytenis who spoke to me few days ago about maintaining NativeBase?

Looping in @shivrajkumar

**Comment by FDiskas** [comment]
@sanketsahusoft yes that's me. I started a fork with typescript already

**Comment by sanketsahusoft** [comment]
I think we are going to use TypeScript with NativeBase v3.

From our internal discussion:

Plan 2-week sprint
• Top issues
• Merge PRs
• List out issues related to the architecture

Start architecting NativeBase 3.0
• Philosophy 
• Guidelines, API Design 
• styled-system
• TypeScript
• Announce End-of-Life date for NativeBase 2.0 (tentatively May 15th, 2020)

I think @shivrajkumar should speak to you. Let's do it next week.

**Comment by FDiskas** [comment]
I'm not a big fan of styled-system
https://calendar.perfplanet.com/2019/the-unseen-performance-costs-of-css-in-js-in-react-apps/
Is this a final decision?

**Comment by sanketsahusoft** [comment]
No, that's not a final decision. We can learn from styled-system.

**Comment by FDiskas** [comment]
Please - fix the tests in current version. I can't run and tests with screenshots and compare with a refactored version.

**Comment by FDiskas** [comment]
@sanketsahusoft hi, I hope you all are ok during this global crisis.
I have one question why all your components 
https://github.com/GeekyAnts/NativeBase/blob/f11d9b4e9e004650d16bb9857e5f4370d0f06fbb/src/basic/Body.js#L10
has `_root` ref? Is there something special about it? I'm refactoring all components and this looks for me like left overs.

**Comment by sanketsahusoft** [comment]
We are going to fix issues like in v3.

We are evaluating [system-ui](https://system-ui.com/) + [styled-system](https://styled-system.com/) + [styled-components](https://styled-system.com/).
