### ISSUE TITLE
[Question] ScrollableTabs and TabHeading: Align left

### ISSUE THREAD

**Issue by oferRounds** [GeekyAnts/NativeBase#3070]
## I have gone through these following points

- [x] Check latest documentation: https://docs.nativebase.io/
- [x] Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x] Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [x] Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [x] For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- [x] For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

## Issue Description

Is there a way to have have the headings to not equality distribute, and instead have 0 padding for each heading, and have them aligned to the left?

**Comment by oferRounds** [comment]
![image](https://user-images.githubusercontent.com/1477963/74633842-3f165480-516b-11ea-9b18-1b707b23beed.png)
Example: see green padding here. I’d like the padding to be very small, and have the tabs aligned to the left, if possible

**Comment by thanhluantl2304** [comment]
Same problem, can not set padding for tab heading, any updates?

**Comment by hanykumar** [comment]
Hi @oferRounds , heading width distributes equally. You can't align tabs in left only.

**Comment by oferRounds** [comment]
@hanykumar got you, thanks!
