### ISSUE TITLE
Wrong text color for light button

### ISSUE THREAD

**Issue by cruzlutor** [GeekyAnts/NativeBase#3071]
#### node, npm, react-native, react and native-base version, expo version if used, xcode version
node: 13.8.0
npm: 6.13.6
react: 16.9.0
react-native: sdk-36.0.0
expo: 36.0.0
native-base: 2.13.8

#### Expected behaviour
The text color for the light button should be darker

#### Actual behaviour
The text color for the light button is white

#### Steps to reproduce
Just rendering a light button

#### Is the bug present in both iOS and Android or in any one of them?
This is happening in both platforms

#### example
![Screen Shot 2020-02-17 at 8 55 12 PM](https://user-images.githubusercontent.com/1368971/74697171-d6a99080-51c7-11ea-90b6-5c00c1a0a589.png)

#### code repo with code example 
https://github.com/cruzlutor/error-button-sample

Related issue: https://github.com/GeekyAnts/NativeBase/issues/2204
I tried to wrap each Button in a View element, same result

thanks in advance

**Comment by hanykumar** [comment]
Hi @cruzlutor , latest version of Native base has been released. The issues should be fixed now.
[Native Base 2.13.12](https://github.com/GeekyAnts/NativeBase/releases/tag/v2.13.12)
