### ISSUE TITLE
Cannot read property '_root' of undefined react native jest

### ISSUE THREAD

**Issue by ravirupareliya** [GeekyAnts/NativeBase#3075]
## I have gone through these following points

- [x] Check latest documentation: https://docs.nativebase.io/
- [x] Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x] Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [x] Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [x] For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- [x] For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

## Issue Description

I am trying to run testcases in my project, one scenario is to mock the function and validate output. In that function I have used Toast.show(). Whenever I am trying to run that function through testcases, it gives me below error.

    Cannot read property '_root' of undefined

#### Expected behaviour
It should not give error, instead something through which we can recognise that toast has been displayed.

#### Actual behaviour
Showing error

#### Steps to reproduce
Create a function in React native component which will show Toast. Write test case to mock that class and run that function.

First.test.js

    describe("Dashboard Component", () => {
      it("should call onFunctionCall", () => {
        const wrapper = shallow(
            <Dashboard navigation={navigation} />
        ).dive().dive().dive().dive()

        const onFunctionCall = jest.spyOn(wrapper.instance(), "onFunctionCall")
        wrapper.update()
        wrapper.instance().forceUpdate()
        wrapper.instance().onFunctionCall()

        expect(onFunctionCall).toHaveBeenCalled()
      })
    })

#### Is the bug present in both iOS and Android or in any one of them?
N/A

#### Any other additional info which would help us debug the issue quicker.

###Important

If you want your issue to be looked at quicker, attach a snack reproducible with your issue. Makes it easier for us!

**Comment by FDiskas** [comment]
Could you post how content of `<Dashboard />` looks like?
