### ISSUE TITLE
can't find veriable drawer

### ISSUE THREAD

**Issue by detroit007** [GeekyAnts/NativeBase#3079]
import React, { useState, useEffect } from 'react';
import {StyleSheet, TouchableOpacity, StatusBar, Image} from 'react-native';
import { Drawer, Body, Container, Header, Left, Right, Button, Title, View } from 'native-base';
import SideBar from '../components/SideBar';
import Icon from 'react-native-vector-icons/FontAwesome';
import Color from '../constants/Color';
import AsyncStorage from '@react-native-community/async-storage';
import ApiConfig from '../server/ApiConfig';
import { useSafeArea } from 'react-native-safe-area-context';
import { set } from 'react-native-reanimated';

const DrawerScreenBox = (props) =>{

 
    const closeDrawer = () =>{
      
        drawer && drawer._root && drawer._root.close();
    };
    
    const openDrawer = () => { 
     
        drawer && drawer._root && drawer._root.open();
    };

    return(
    <Drawer refs={(ref) => { drawer = ref; refs(); }} 
 
      content={<SideBar navigation={props.navigation} />} 
      onClose={() => {closeDrawer()}} >
      <Container>
          <Header iosBarStyle='light-content' style={{backgroundColor: Color.primaryColor}}>
            <StatusBar backgroundColor='black'/>
              <Left >
                  <TouchableOpacity style={{}}>
                    <Icon name='bars' onPress={()=>openDrawer()} color='white' size={25}/>
                  </TouchableOpacity>
              </Left>

              <Body style={{alignItems:'flex-end'}}>
                    <Image style={{width: 50, height: 40}} source={require('../assets/img/logo.png')}/>
              </Body>

              <Right>

                <View style={{flexDirection: 'row', justifyContent: 'space-around' }}>

                    <TouchableOpacity 
                      onPress={()=>{props.navigation.navigate('Notify')}}
                      style={{paddingRight: 10}}
                      >

                        <Icon name='bell' color='white' size={25}/>
                    
                    </TouchableOpacity>

                    <TouchableOpacity 
                      onPress={()=>{props.navigation.navigate('SearchBar')}}
                      transparent>
                        <Icon name='search' color='white' size={25}/>
                    </TouchableOpacity>

                    </View>

              </Right>
          </Header>
          {props.children}
      </Container>
    </Drawer>
 );
}

export default DrawerScreenBox;

**Comment by ParthShrivastav** [comment]
Try Adding ref to the drawer.
You can add this to your code.
let drawer = useRef(); and don't forget it to import from react.

**Comment by hanykumar** [comment]
Hi @detroit007 , follow [here](https://github.com/GeekyAnts/NativeBase/issues/3119#issuecomment-689504841) . Closing for now. Let us know if the issue still persists.
