### ISSUE TITLE
Warning: Failed prop type: Invalid props.style key `tintColor` supplied to `Text`.

### ISSUE THREAD

**Issue by rosnaib11** [GeekyAnts/NativeBase#3080]
I can't use icon properly, it shows this error. How to rid this off?

![image](https://user-images.githubusercontent.com/26837762/75326086-f706d880-58b4-11ea-85ac-03029e55e65d.png)

**Comment by sankhadeeproy007** [comment]
Please add the reproduction steps

**Comment by schotttaylor** [comment]
I'm getting this same error whenever I try to pass an expo icon or a react-native-vector-icon in as the icon prop on a ui-kitten TabView Tab.

**Comment by hanykumar** [comment]
Hi @rosnaib11 , please update with the latest Nativebase v2.13.14 . And let us know if the issue still persists by providing minimal code reproduction with more details.
