### ISSUE TITLE
tabBarUnderline is wrong with RTL direction

### ISSUE THREAD

**Issue by ansarikhurshid786** [GeekyAnts/NativeBase#3086]
All other components working perfectly in both rtl or ltr direction. I am facing very small issue in tabs. Tab active underline is not showing properly in android only. 

anyone facing same issue.

**Comment by hanykumar** [comment]
Hi @ansarikhurshid786 , could you just provide us snack for minimal reproduction and the screenshot for the same to identify the issue.

**Comment by ansarikhurshid786** [comment]
Yes, sure.

**Comment by ansarikhurshid786** [comment]
In snack 
I18nManager.allowRTL(true);
    I18nManager.forceRTL(true);

is not working.

**Comment by hanykumar** [comment]
Hi @ansarikhurshid786 , could you provide screenshot of your actual underlined tabBar for easy understanding? If it is possible, provide code for the same also.

**Comment by ansarikhurshid786** [comment]
Code : 
```
componentDidMount() {
I18nManager.allowRTL(true);
I18nManager.forceR
![Simulator Screen Shot - iPhone X - 2020-03-11 at 13 49 43](https://user-images.githubusercontent.com/20280498/76404015-39451500-639f-11ea-924f-4af656e2e55e.png)
TL(true);
}
```
```
<Tabs initialPage={0} renderTabBar={() => <ScrollableTab />}>
                    {
                        this.state.devCodeRecs.baseDistrict || this.state.devRecs_overlayLinks.length > 0 ?
                            <Tab heading={
                                <TabHeading>
                                    <Text> {I18n.t("transObj.homePage.tabTitle.devCode")} </Text>
                                </TabHeading>
                            }>
                                <DevCodeView />
                            </Tab>
                            : null
                    }
</Tabs>
```

**Comment by ansarikhurshid786** [comment]
![Simulator Screen Shot - iPhone X - 2020-03-11 at 13 49 43](https://user-images.githubusercontent.com/20280498/76404129-6bef0d80-639f-11ea-8398-6a6c09389e03.png)

**Comment by hanykumar** [comment]
Hi @ansarikhurshid786 , please try static English Text for Tabs for verification. Because I didn't find any problem with Active underlined tabBar in Android and iOS. 

![Screenshot 2020-03-11 at 4 26 00 PM](https://user-images.githubusercontent.com/15860517/76409875-073ead80-63b5-11ea-9a25-28e725fee066.png)

**Comment by ansarikhurshid786** [comment]
I am changing language to arabic and direction of application (I18nManager.allowRTL(true);
        I18nManager.forceRTL(true);) then i am facing issue.

**Comment by ansarikhurshid786** [comment]
This problem is in both platform.

**Comment by ansarikhurshid786** [comment]
I tried to just change application direction using following code. 
```
import { I18nManager } from "react-native";

componentDidMount(){
 I18nManager.allowRTL(true);
 I18nManager.forceRTL(true);
}
```

**Comment by ansarikhurshid786** [comment]
@hanykumar hope you get my issue

**Comment by hanykumar** [comment]
Hi @ansarikhurshid786 , I get your point, but it requires snack of minimal reproduction for testing your issue. But still we will are looking into it.

**Comment by ansarikhurshid786** [comment]
See snack expo : 
https://snack.expo.io/@ansarikhurshid7869/nativebase-tabs-issue

**Comment by ansarikhurshid786** [comment]
and I need dynamic tab. can you please check it.

**Comment by hanykumar** [comment]
Hi @ansarikhurshid786 , I don't see any problem in Tab active underline in the snack link, you provided.

**Comment by ansarikhurshid786** [comment]
I have update snack expo with my case. i want dynamic tabs

**Comment by iamir4g** [comment]
> I have update snack expo with my case. i want dynamic tabs

I have the same issue can you solve this problem?

**Comment by syedamirali14** [comment]
did you fix it @ansarikhurshid786 ?
