### ISSUE TITLE
ScrollToPosition doesn't work as expected with <Content /> as a functional component

### ISSUE THREAD

**Issue by AndresTIY** [GeekyAnts/NativeBase#3087]
## I have gone through these following points

- [x] Check latest documentation: https://docs.nativebase.io/
- [x] Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x] Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [x] Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink

#### node, npm, react-native, react and native-base version, expo version if used, xcode version

react-native - 0.61.2
native-base - 2.13.8
xcode - 11.2.1

#### Expected behaviour
Expect the ScrollView / Content component to scroll to position when screen mounts

#### Actual behaviour
Component does not scroll to position UNLESS a timer is set or if the developer does a "Fast Refresh" 

#### Steps to reproduce

```js
import React, { useEffect, useRef } from 'react'
import { Text, View, StyleSheet } from 'react-native';
import { Container, Content } from 'native-base'

const App = () => {

  const ListItem = ({ text }) => (
    <View style={styles.listItemStyle}>
      <Text>
        {text}
      </Text>
    </View>
  )

  const list = ['crosstek', 'outback', 'forester', 'element', 'fit', 'civic', 'words', 'chrysler', 'cats', 'ipsum', 'config', 'mousepads', 'ben', 'its all in my head']

  const contentRef = useRef();

  const indexToScrollTo = 5

  const scrollIt = () => {
    const itemHeight = 50;
    const yValue = itemHeight * indexToScrollTo;
    contentRef.current._root.scrollToPosition(0, yValue)
  }
  
  useEffect(() => {
    scrollIt()
  },[])

  // useEffect(() => {
  //   setTimeout(() => {
  //     scrollIt()
  //   }, 500)
  // })

return (
  <Container style={styles.container}>
    <View style={styles.topView} />
    <Content ref={contentRef}>
      {list.map(item => <ListItem text={item} />)  }
    </Content>

  </Container>
  )
}

export default App
```

#### Is the bug present in both iOS and Android or in any one of them?
both

#### Any other additional info which would help us debug the issue quicker.

###Important

https://snack.expo.io/HkjbPNNSI

- When the screen first mounts, it does not scroll.
- Make any changes to the code to force a fast refresh, and then it scrolls.
- Un-comment the useEffect with the timer in it and comment the other one out and it ends up working

**Comment by ansarikhurshid786** [comment]
I am face same now. I have update react native version nativebase v2 not working
