### ISSUE TITLE
DatePicker set value

### ISSUE THREAD

**Issue by 19007361** [GeekyAnts/NativeBase#3088]
## I have gone through these following points

- [x] Check latest documentation: https://docs.nativebase.io/
- [x] Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x] Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [x] Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [x] For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- [x] For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

#### node, npm, react-native, react and native-base version, expo version if used, xcode version
native-base: 2.13.8
react-native: 0.60.6
react: 16.8.6
Latest node and npm

#### Expected behaviour
I want to be able to set the value of the DatePicker to a state variable, as in the other components including the normal Picker

#### Actual behaviour
No way to set a value

#### Any other additional info which would help us debug the issue quicker.
Would be really useful for this filter I'm busy with, one could reset the filters and it would reset the date that one selected to null. No way to do that programmatically at the moment.

**Comment by prajjawal05** [comment]
Hi @19007361 I have added a commit. This should solve your problem

**Comment by 19007361** [comment]
Thank you, I was using https://github.com/xgfe/react-native-datepicker which gave me the functionality I needed, but now I will try this one.

**Comment by dwaynelavon** [comment]
@prajjawal05 Is this gonna make it to master? I'm struggling with this issue also

**Comment by dl-husky73** [comment]
Any result here, is this in master?

**Comment by prajjawal05** [comment]
Not yet @dwaynelavon @dl-husky73 I am not sure who to tag to approve this.

**Comment by eskiesirius** [comment]
im having the same problem with this, the default value of the date picker doesn't change.. I am new to react native.. here is my code..

```
const [appointmentDate, setAppointmentDate] = React.useState(new Date())

React.useEffect(() => {		
		if (route.params) {
			const appointment = route.params.appointment
			const appointment_date = moment(appointment.appointment_date)

			setTitle('Edit Appointment')
			setAppointmentDate(appointment_date)
		}
	},[])
```

then my date picker is

```
<DatePicker
 defaultDate={appointmentDate}
 locale={"en"}
 timeZoneOffsetInMinutes={undefined}
 modalTransparent={false}
 animationType={"fade"}
 androidMode={"default"}
 textStyle={{ color: 'black' }}
 placeHolderTextStyle={{ color: 'black' }}
 placeHolderText="wew"
 onDateChange={setAppointmentDate}
 disabled={false}
 />
```

date picker will display the current date
