### ISSUE TITLE
I am trying to replicate Card OnClick functionality but having an issue

### ISSUE THREAD

**Issue by Louis345** [GeekyAnts/NativeBase#309]
I am new to Native Base as well as React-Native, and I am really thrilled about using this framework.  I am trying to replicate the example Card OnClick and I don't see how to navigate between screens. I am probably overlooking something simple. From the example listed in the docs, all I could really gather is that  there is a prop onPress making a call to a function. The example, does not illustrate the logic that should be in the function to generate the desired behavior. This leads me to believe that prior knowledge is required. Can someone kindly direct me to some literature that can help me fill in my gap of knowledge.  Or is there is a full working example I could look at to get a better idea on what is going on?

**Comment by SupriyaKalghatgi** [comment]
@Louis345 The `onPress` navigates to other screens.
So you must basically use a route to do that.
Check [Native-Starter-Kit](https://github.com/start-react/native-starter-kit) and [NativeBase-KitchenSink App](https://github.com/GeekyAnts/NativeBase-KitchenSink).
These would fill in your needs.

**Comment by Louis345** [comment]
Thank you.
