### ISSUE TITLE
ActionSheet doesn't show Cancel button in iOS

### ISSUE THREAD

**Issue by alf-ytakada** [GeekyAnts/NativeBase#3090]
## I have gone through these following points

- [x] Check latest documentation: https://docs.nativebase.io/
- [x] Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x] Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [x] Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [x] For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- [x] For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

## Issue Description

https://docs.nativebase.io/Components.html#actionsheet-def-headref

This ActionSheet example doesn't properly function with ios.
With android, it is good.

#### node, npm, react-native, react and native-base version, expo version if used, xcode version

* node
    * v12.16.1
* npm
    * 6.13.4
* react-native
    * https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz
* react
    * 16.9.0
* expo
    * 36.0.0

#### Expected behaviour

Cancel button is displayed.

#### Actual behaviour

Cancel button is not displayed.

#### Is the bug present in both iOS and Android or in any one of them?

iOS only

#### Any other additional info which would help us debug the issue quicker.

here is the example.

https://snack.expo.io/HyiEJuLr8

thanks!

**Comment by hanykumar** [comment]
Hi @alf-ytakada , There is `cancel` button on iOS below `Delete` button. This screenshot has been taken from snack code you provided.
 
<img width="317" alt="Screenshot 2020-09-14 at 3 05 22 PM" src="https://user-images.githubusercontent.com/15860517/93088080-1a5d6d80-f6b7-11ea-8627-f9ffcdaadb93.png">
