### ISSUE TITLE
MaskService.toRawValue doesnt return the correct raw value

### ISSUE THREAD

**Issue by appjitsu** [GeekyAnts/NativeBase#3101]
## I have gone through these following points

- [x] Check latest documentation: https://docs.nativebase.io/
- [x] Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x] Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [x] Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [x] For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- [x] For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

## Issue Description

toRawValue() is not returning the raw value. I tried testing with a phone number.

#### node, npm, react-native, react and native-base version, expo version if used, xcode version

node: 12.14.0
npm: 6.14.2
react-native: 0.61.4
native-base: ^2.13.8
react-native-masked-text: ^1.13.0

#### Expected behaviour

1234567890

#### Actual behaviour

(123) 456-7890

#### Steps to reproduce

MaskService.toRawValue('custom', '(123) 456-7890', {"mask": "(999) 999-9999"});

#### Is the bug present in both iOS and Android or in any one of them?

both

**Comment by hanykumar** [comment]
Hi @appjitsu , can you provide minimal code reproduction on snack?
