### ISSUE TITLE
Jest Error -   import connectStyle, { clearThemeCache } from "./src/connectStyle";     ^^^^^^      SyntaxError: Cannot use import statement outside a module 

### ISSUE THREAD

**Issue by waspfreak** [GeekyAnts/NativeBase#3105]
## I have gone through these following points

- [x] Check latest documentation: https://docs.nativebase.io/
- [x] Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x] Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [x] Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [x] For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- [x] For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

#### Try run test from my screen component
<!- 
import React from 'react';
import { Container, Content } from 'native-base';

const HomeScreen = props => {
  return (
    <Container>
      <Content>
        <Button
          style={styles.button}
          onPress={() => props.navigation.openDrawer()}
        >
          <Text>Custom Color</Text>
        </Button>
      </Content>
    </Container>
  );
};

export default HomeScreen;
->
Got this error 

I add this  in my transformIgnorePatterns:
<!- 
  transformIgnorePatterns: [
    'node_modules/(?!react-native|native-base|react-navigation|react-native-reanimated|react-navigation-redux-helpers|react-native-maps|@react-navigation/|@shoutem/theme|native-base-shoutem-theme|@shoutem/animation|@shoutem/ui|react-native-easy-grid|tcomb-form-native.*)/'
  ],
->
#### Is the bug present in both iOS and Android or in any one of them?
Yes

#### Any other additional info which would help us debug the issue quicker.

###Important

If im using React native component the tst runs ok

**Comment by Eldavid** [comment]
I have the same problem with `react-native-testing-library` testing package too.

**Comment by idhowardgj94** [comment]
facing the same problem

**Comment by rajeshwarpatlolla** [comment]
Anyone has a resolution for this?

**Comment by teja-kandula** [comment]
Came across same issue.

**Comment by arabscimitar** [comment]
Add this to your jest config

`"transformIgnorePatterns": [
      "node_modules/(?!react-native|@shoutem|react-clone-referenced-element|native-base-shoutem-theme)"
    ]`

**Comment by fredlemieux** [comment]
This solution unfortunately didn't work, are there any other solutions?  It's not great if we can't use Jest for testing NativeBase?

> Add this to your jest config
> 
> `"transformIgnorePatterns": [ "node_modules/(?!react-native|@shoutem|react-clone-referenced-element|native-base-shoutem-theme)" ]`

**Comment by monikamateeva** [comment]
I am thinking of not not using Native Base... since it does not support testing with Jest . Or at least if we had a workaround? Could not configure my project to successfully use NativeBase and Jest.

**Comment by rickyalmeidadev** [comment]
I will share my `jest.config.js`, this was enough to make it work for me:

```js
module.exports = {
  preset: 'react-native',
  setupFilesAfterEnv: ['<rootDir>/jest.setup.js'],
  transformIgnorePatterns: [
    '<rootDir>/node_modules/(?!(jest-)?react-native|native-base-shoutem-theme)'
  ]
};
```

My `jest.setup.js` does nothing but import `@testing-library/jest-native/extend-expect`.
