### ISSUE TITLE
Picker error with large list Picker.Item

### ISSUE THREAD

**Issue by tudiantuan** [GeekyAnts/NativeBase#3106]
## Issue Description
When I scrolled, the screen displayed an error: 
Attempted to transition from state `RESPONDER_INACTIVE_PRESS_IN` to `RESPONDER_ACTIVE_LONG_PRESS_IN`, which is not supported.

#### Steps to reproduce
List countries from https://gist.github.com/Keeguon/2310008.
``` 
                  <Item fixedLabel>
                    <Label>Country/region</Label>
                    <Picker
                      mode="dropdown"
                      iosHeader="Select country"
                      selectedValue={this.state.country}
                      onValueChange={this.onValueChangeCountry}
                    >
                      {countries.map(item =>
                        <Picker.Item key={item.code} label={item.name} value={item.code} />)}
                    </Picker>
                    <View style={{ width: 30 }} />
                  </Item>
```

**Comment by hanykumar** [comment]
Hi @tudiantuan , on which platform are you facing this issue, Android or iOS?

**Comment by tudiantuan** [comment]
I test on IOS

**Comment by hanykumar** [comment]
Hi @tudiantuan , can you provide minimal code reproduction for the same on snack?

**Comment by tudiantuan** [comment]
yes, it is https://snack.expo.io/@nguoilatao/c9bb16. I try scroll on Snack but i dont get error!

**Comment by tudiantuan** [comment]
<img width="269" alt="Screen Shot 2020-03-27 at 22 47 22" src="https://user-images.githubusercontent.com/39153315/77773973-ecd72600-707c-11ea-8f31-1c095b736b58.png">

**Comment by hanykumar** [comment]
Hi @tudiantuan , please update with Nativebasev2.13.14 . Let us know if the issue still persists. Found no issue on picker countries scroll.


```
constructor(props) {
    super(props);
    this.state = {};
  }

  onValueChangeCountry = (country) => {
    console.log(country);
    this.setState({ selected: country });
  };
```
```

<Item fixedLabel>
     <Label>Country</Label>
     <Picker
                  mode="dropdown"
                  selectedValue={this.state.selected}
                  placeholder="Select Country"
                  onValueChange={this.onValueChangeCountry.bind(this)}
                >
                  {countries.map((item) => (
                    <Picker.Item
                      key={item.code}
                      label={item.name}
                      value={item.code}
                    />
                  ))}
      </Picker>
</Item>
```
<img width="356" alt="Screenshot 2020-09-11 at 3 22 14 PM" src="https://user-images.githubusercontent.com/15860517/92908264-b2532100-f443-11ea-86a2-68f98bad77a3.png">

**Comment by hanykumar** [comment]
Hi @tudiantuan , closing for now. Let us know if the issue still persists.
