### ISSUE TITLE
Customisation of drawer icon in Native Base

### ISSUE THREAD

**Issue by chetnadaffodil** [GeekyAnts/NativeBase#311]
Please provide a method or some means to edit the menu/drawer icon on the left.
It's too narrow and can't change its color

![screenshot from 2016-11-21 16-41-14](https://cloud.githubusercontent.com/assets/17562095/20480648/648786dc-b009-11e6-9eda-4c0e45433cf2.png)

**Comment by SupriyaKalghatgi** [comment]
@chetnadaffodil Please follow [customization](http://nativebase.io/docs/v0.5.13/customize#themeHeader) section of NativeBase docs

**Comment by haifaGh** [comment]
Hi, can you please post the code you already used to implement native base drawer ?
