### ISSUE TITLE
Picker Background Color and Styling

### ISSUE THREAD

**Issue by judygab** [GeekyAnts/NativeBase#3110]
I can't change the background color of picker. Don't need to change item colors, just that of picker component itself before dropdown opens. Also can't set the height of it. Here is the screenshot.
<img width="366" alt="Screen Shot 2020-03-29 at 7 47 58 PM" src="https://user-images.githubusercontent.com/50160672/77864386-38610f80-71f6-11ea-9c58-d5cd5d6d1e6e.png">

`            <Picker
              mode="dropdown"
              iosIcon={<Icon name="arrow-down" />}
              placeholder="Select your language"
              placeholderStyle={{ color: "#007aff" }}
              placeholderIconColor="#007aff"
              style={{ width: undefined, height: 50, color: "#007aff"}}
              selectedValue={this.state.selected}
              onValueChange={this.onValueChange.bind(this)}
            >
              <Picker.Item label="Wallet" value="key0" />
              <Picker.Item label="ATM Card" value="key1" />
              <Picker.Item label="Debit Card" value="key2" />
              <Picker.Item label="Credit Card" value="key3" />
              <Picker.Item label="Net Banking" value="key4" />
            </Picker>`

**Comment by appukuttan-shailesh** [comment]
After a lot of searching on the Internet, and on the verge of giving up, I had some luck and one of my random trials worked for me in changing the picker background color (on Android). Putting it up here in case its useful for you or others:

```
<View style={styles.pickerItemContainer}>
    <Container style={styles.transparentContainer}>
        <Content>
            <Form>
                <Picker
                    note
                    mode="dropdown"
                    style={{ width: 160, color:'#000000' }}
                    selectedValue={gender}
                    enabled={sender !== "self"}
                    onValueChange={currentGender => setGender(currentGender)}
                >
                    <Picker.Item label={print("emptySelectOption")} value="" />
                    <Picker.Item label={print("male")} value="Male" />
                    <Picker.Item label={print("female")} value="Female" />
                    <Picker.Item label={print("other")} value="Other" />
                </Picker>
            </Form>
        </Content>
    </Container>
</View>
```

`styles.transparentContainer` specifies the background color that I require. In my case I wanted it background, so it was simply:
```
const styles = StyleSheet.create({
    transparentContainer: {
        backgroundColor: 'transparent'
    }
})
```

If you don't wish to use a stylesheet, then simply replace:
`<Container style={styles.transparentContainer}>`
with
`<Container style={{ backgroundColor: 'transparent' }}>`

I tried numerous combinations, and this is what worked for me.

Another attempt that **nearly worked** was setting the `style` on the `<Picker>` tag, e.g.
`<Picker style={{ backgroundColor: 'red' }} ...>` 

The problem with this approach is that, for some reason, the drop down arrow disappeared for me.

**Comment by hanykumar** [comment]
Hi @judygab , please update with latest NativeBase v2.13.14 . Let us know if the issue still persisits.
```
 <Picker
              mode="dropdown"
              style={{
                width: 300,
                backgroundColor: "green",
                height: 100,
              }}
              textStyle={{ color: "blue" }}
              iosIcon={<Icon name="arrow-down" />}
              selectedValue={this.state.selected}
              onValueChange={this.onValueChange.bind(this)}
            >
              <Picker.Item label="Wallet" value="key0" />
              <Picker.Item label="ATM Card" value="key1" />
              <Picker.Item label="Debit Card" value="key2" />
              <Picker.Item label="Credit Card" value="key3" />
              <Picker.Item label="Net Banking" value="key4" />
</Picker>
```
<img width="354" alt="Screenshot 2020-09-11 at 2 31 16 PM" src="https://user-images.githubusercontent.com/15860517/92898281-7ae07680-f43b-11ea-812c-055b4afb0f69.png">

**Comment by hanykumar** [comment]
Hi @judygab , closing for now. Let us know if the issue still persists.

**Comment by alessandrocapra** [comment]
Also looking for a solution to this, not working on v. 2.13.14
