### ISSUE TITLE
Module not found: Can't resolve '@expo/vector-icons/Fontisto

### ISSUE THREAD

**Issue by pawanjangle** [GeekyAnts/NativeBase#3113]
## I have gone through these following points

- [] Check latest documentation: https://docs.nativebase.io/
- [] Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [] Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [] Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [] For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- [] For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

#### Any other additional info which would help us debug the issue quicker.

###Important

If you want your issue to be looked at quicker, attach a snack reproducible with your issue. Makes it easier for us!

**Comment by joshfester** [comment]
I also get this issue when trying to use 2.13.12 with Expo 37

**Comment by thecillu** [comment]
I also get this issue when trying to use 2.13.[9-12] with Expo 37

Only the version 2.13.8 seems work

**Comment by the-codetrane** [comment]
@akhil-geekyants I found the issue and have a PR for it [here](https://github.com/GeekyAnts/NativeBase/pull/3123)

**Comment by sankhadeeproy007** [comment]
@the-codetrane Please note that this is happening because @expo/icons is using an older version of vector icons. This issue will be fixed once they upgrade the version of vector-icons.
Related thread
https://github.com/expo/vector-icons/issues/112

**Comment by juandav** [comment]
The solution to this has already been merged, all that remains is to generate a version to update and use.

https://github.com/expo/vector-icons/pull/126

**Comment by juandav** [comment]
you can use this for now.

```json
{
  "dependencies": {
    "@expo/vector-icons": "Kaushald4/vector-icons#master"
  }
}
```

**Comment by shijiezhou1** [comment]
> you can use this for now.
> 
> ```json
> {
>   "dependencies": {
>     "@expo/vector-icons": "Kaushald4/vector-icons#master"
>   }
> }
> ```

This work for me but why

**Comment by kulor** [comment]
Looks like this has been resolved since 10.1.0 (https://github.com/expo/vector-icons/pull/126#issuecomment-619719328). Run a `yarn add @expo/vector-icons` / `npm install @expo/vector-icons` to get it.

**Comment by hanykumar** [comment]
Hi @pawanjangle , please update with the latest "NativeBase": "2.13.14" and  "expo": "~38.0.8". Let us know if the issue still persists.

**Comment by hanykumar** [comment]
Hi @pawanjangle , closing for now. Let us know if the issue still persists.
