### ISSUE TITLE
change radio style and make first one checked

### ISSUE THREAD

**Issue by mhmdalii** [GeekyAnts/NativeBase#3116]
i need to change the background color and icon of radio in native base , and make first radio chechekd on first prview , how to make this ?
thankx

**Comment by hanykumar** [comment]
Hi @mhmdalii , you can refer [native-base documentation](https://docs.nativebase.io/Components.html#custom-radio-headref)


```
<Content>
          <ListItem>
            <Left>
              <Text>Daily Stand Up</Text>
            </Left>
            <Right>
              <Radio selected={false} color={"red"}
                selectedColor={"blue"}/>
            </Right>
          </ListItem>
          <ListItem>
            <Left>
              <Text>Discussion with Client</Text>
            </Left>
            <Right>
              <Radio selected={true} color={"red"}
                selectedColor={"blue"}/>
            </Right>
          </ListItem>
</Content>
```

![Screenshot 2020-04-15 at 5 10 43 PM](https://user-images.githubusercontent.com/15860517/79333393-14af0080-7f3c-11ea-86d1-890ab28bf304.png)

**Comment by hanykumar** [comment]
Hi @manuquentin , closing for now due to inactivity. Let us know if the issue still persists.
