### ISSUE TITLE
Fab and footer aren't compatible

### ISSUE THREAD

**Issue by BBenGit** [GeekyAnts/NativeBase#3120]
## I have gone through these following points

- [x] Check latest documentation: https://docs.nativebase.io/
- [x] Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x] Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [x] Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [x] For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- [x] For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

#### node, npm, react-native, react and native-base version, expo version if used, xcode version
node : v13.7.0
npm : 6.13.6
react : 16.13.1
react-native : 0.62.2
native-base : 2.13.12

#### Expected behaviour
The fab to appear above the footer.

![Screenshot 2020-04-09 at 17 48 08](https://user-images.githubusercontent.com/44926723/78914724-1df72380-7a8b-11ea-98eb-b0a9680e2cc0.png)

#### Actual behaviour
The fap appears over the footer.

![Screenshot 2020-04-09 at 17 51 23](https://user-images.githubusercontent.com/44926723/78914739-23ed0480-7a8b-11ea-97ac-a97648de0eae.png)

#### Steps to reproduce
```
<Container>
...

<Fab>
 <Icon/>
</Fab>

<Footer>
...
</Footer>
</Container>
```

#### Is the bug present in both iOS and Android or in any one of them?
Both

#### Any other additional info which would help us debug the issue quicker.

###Important

If you want your issue to be looked at quicker, attach a snack reproducible with your issue. Makes it easier for us!

**Comment by hanykumar** [comment]
Hi @BBenGit , please follow the documentation. [Native-base documentation](https://docs.nativebase.io/Components.html#fabs-def-headref)

`<Header />`
`<View style={{flex: 1}}>`
`<Fab> ... </Fab>`
`</View>`
`<Footer />`

![Screenshot 2020-04-15 at 9 52 37 AM](https://user-images.githubusercontent.com/15860517/79298480-e101b580-7efe-11ea-991b-dd349e66efb4.png)

**Comment by BBenGit** [comment]
Hi @hanykumar, thx it solved my issue.
