### ISSUE TITLE
Header glitches with react navigation 5

### ISSUE THREAD

**Issue by anam-hossain** [GeekyAnts/NativeBase#3121]
Hi guys, Nativebase header is glitching with the latest version of react-navigation (v5.3.1). I have attached a gif file to demonstrate the glitch.

![react_navigation_5_header_glitch](https://user-images.githubusercontent.com/5017268/78954965-197d4a00-7b21-11ea-8b50-be2655604cd3.gif)

I am using a native base header with a custom component. 

The code looks like the following:

```js
class HomeHeader extends React.PureComponent {
  render() {
    return (
      <StyleProvider style={getTheme(platform)}>
        <Header>
          <Left />
          <Body>
            <Title>DuaCollection</Title>
          </Body>
        </Header>
      </StyleProvider>
    );
  }
}
```
```js
function HomeStack() {
  return (
    <Stack.Navigator
      initialRouteName="Home"
      headerMode="screen"
    >
      <Stack.Screen
        name="Home"
        component={HomeSreenContainer}
        options={{ 
          header: ({ navigation }) => <HomeHeader navigation={navigation}/>
        }}
      />
      <Stack.Screen
        name="List"
        component={ListScreen}
        options={{ 
          header: ({ navigation }) => <ListHeader navigation={navigation}/>
        }}
      />
    </Stack.Navigator>
  );
}
```
```js
function TabNavigator() {
  return (
    <Tab.Navigator>
      <Tab.Screen name="HomeTab" component={HomeStack} />
    </Tab.Navigator>
  );
}
```

```js
function AppNavigator() {
  return (
    <Stack.Navigator
      initialRouteName="Main"
      mode="modal"
      headerMode="none"
      screenOptions={{
        cardStyle: { backgroundColor: 'transparent' }
      }}
    >
      <Stack.Screen
        name="Main"
        component={TabNavigator}
      />
    </Stack.Navigator>
  );
}
```

#### node, npm, react-native, react and native-base version, expo version if used, xcode version
node: v10.18.0
react-native: 0.61.5
react 16.9.0
native-base: 2.13.12
xcode 11.3

**Comment by sergchernata** [comment]
If you replace the `header` element with `view`, the error goes away. There's something wrong with `header` element but I don't know what it is yet.

**Comment by hanykumar** [comment]
HI @anam-hossain , can you provide minimal code reproduction on snack for the same?

**Comment by romonsalve** [comment]
I'm having a similar issue only in iOS when i upgrade from 2.13.8 to 2.13.12
Reverting the version resolve the problem for me. 

Im Using header in a custom component only 

`const AppHeader = ({
  left,
  body,
  right,
}) => (
  <Header
    iosBarStyle="light-content"
    style={styles.header}
  >
    <Left style={styles.left}>
      {left}
    </Left>
    <Body style={styles.body}>
      {body}
    </Body>
    <Right style={styles.right}>
      {right}
    </Right>
  </Header>
);

const styles = StyleSheet.create({
  header: {
    justifyContent: 'space-between',
    backgroundColor: Colors.primaryLayout,
    alignItems: 'center',
  },
  left: {
    flex: 0.5,
    // marginLeft: Spacing.SPACING_S,
  },
  body: {
    flex: 1,
    justifyContent: 'center',
    alignItems:'center',
  },
  right: {
    flex: 0.5,
    // marginRight: Spacing.SPACING_S,
  },
});`

**Comment by anam-hossain** [comment]
@hanykumar I am usually using React native CLI and have very little experience with Expo. So, It will be difficult for me to set up a demo with Expo.

I think @romonsalve have found the problem. Could you able to check what changes in v2.13.12?

**Comment by Aung-Myint-Thein** [comment]
Having the same issue on iOS only. I feel like the header is a bit tall. I didn't change any config of the header.

**Comment by EricBuntain** [comment]
@hanykumar I'm having a similar issue as @anam-hossain, my header kind of bounces when navigating to it.

Here is a simple expo example https://snack.expo.io/@eric_vesst/header-glitch  _Only happens with iOS._

If I use the headerLeft/headerRight that react-navigation has, there is not glitch like that.

**Comment by bhaskardabhi** [comment]
I am facing same issue. 

![](https://i.imgur.com/YsCxwTk.gif)

"react": "16.11.0",
"react-native": "0.62.2",
"react-native-gesture-handler": "~1.6.0",
"react-native-reanimated": "~1.9.0",
"react-native-router-flux": "^4.2.0",

I am sure this is because of header and happening only in iOS.

**Comment by hanykumar** [comment]
duplicate #3236

**Comment by apgsn** [comment]
FYI the same bouncy effect happens when you show/hide the `Footer` component.

**Comment by angelxmoreno** [comment]
Do we have a solution for this?

**Comment by siarheipashkevich** [comment]
Any updates?
