### ISSUE TITLE
Android issue on native base

### ISSUE THREAD

**Issue by Prakashandrews** [GeekyAnts/NativeBase#3124]
<img width="374" alt="Screenshot 2020-04-12 at 8 41 21 PM" src="https://user-images.githubusercontent.com/2599266/79069130-56526800-7cfe-11ea-9278-caa47fab086a.png">

I am getting above error when i run on android. but it works in IOS

Package info 
   "native-base": "2.12.1",
    "react": "^16.6.3",
    "react-native": "^0.58.5",

**Comment by hanykumar** [comment]
Hi @Prakashandrews , please share minimal code reproduction on snack for the same.
Thankyou

**Comment by hanykumar** [comment]
HI @Prakashandrews , closing nor now due to inactivity. Please let us know with more details if the issue still persists.
