### ISSUE TITLE
expo demo is outdated

### ISSUE THREAD

**Issue by raphaelbadia** [GeekyAnts/NativeBase#3125]
## I have gone through these following points

- [x] Check latest documentation: https://docs.nativebase.io/
- [x] Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x] Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [x] Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [x] For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- [x] For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

## Issue Description

Hello, it is not possible to see Nativebase's demo on expo, when I go to https://expo.io/@geekyants/nativebasekitchensink it says that 

>This project needs an update
>This project uses Expo SDK v32.0.0. If you want to open this project, the author will need to > update the project's SDK version.'

#### Expected behaviour
To be able to try nativebase in expo

#### Actual behaviour
![CleanShot 2020-04-15 at 09 30 13](https://user-images.githubusercontent.com/1901628/79310132-b95d1e00-7efb-11ea-9f93-7dc706c06bb1.png)

#### Steps to reproduce
go to https://expo.io/@geekyants/nativebasekitchensink

Thanks !

**Comment by zwass** [comment]
I'm not sure what it would take to get this up to date, but as a potential new user it concerns me that the demo is not working.

**Comment by lorensr** [comment]
The App Store link also doesn't work:

![image](https://user-images.githubusercontent.com/251288/94345669-9def5680-fff5-11ea-9ea4-d49ead136965.png)


![image](https://user-images.githubusercontent.com/251288/94345664-9334c180-fff5-11ea-9737-1c083b98605b.png)

**Comment by MetaMmodern** [comment]
I have the same issue. Developers, please, fix the demo.

**Comment by CarinaChenot** [comment]
I have the same problem. Another issue mentioning this: https://github.com/GeekyAnts/NativeBase/issues/3276
