### ISSUE TITLE
dosent change color of TextIput

### ISSUE THREAD

**Issue by iamir4g** [GeekyAnts/NativeBase#3128]
Hello @akhil-geekyants ,
I have this as a code snippet, but the color doesn't change
```
<Input
    returnKeyType="next"
    autoCapitalize="none"
    keyboardType="email-address"
    onChangeText={value => setFieldValue('username', value)}
    onBlur={() => setFieldTouched('username')}
    value={values.username}
    editable={!isSubmitting}
    style={{ color: '#FFF' }} />
```

i have same issue this is may code :
```
          <Item floatingLabel style={{ width: 200, height: 40, borderColor: '#507783' }} >
              <Thumbnail square source={require('../../assets/Newimage/Login/ico_user.png')} resizeMode='center' />
              <Label style={{ color: '#507783', fontSize: 12, textAlign: 'left'}}>نام کاربری</Label>
              <Input returnKeyType='next' autoCapitalize="none" onChangeText={text => setUsername(text)} style={{color: '#ffffff', textAlign: 'left', fontFamily: 'IRANSansMobile', fontSize: 12, marginLeft: 8,marginBottom:10}} />
            </Item>
``` 
_Originally posted by @snaquaye in https://github.com/GeekyAnts/NativeBase/issues/1263#issuecomment-474122519_

**Comment by hanykumar** [comment]
Hi @iamir4g , can you share minimal code reproduction on snack, if you still face same problem?  Everything is fine with the code provided by you.

![Screenshot 2020-04-20 at 4 58 58 PM](https://user-images.githubusercontent.com/15860517/79746819-3e936900-8328-11ea-9f6d-4545b4a1626b.png)

![Screenshot 2020-04-20 at 4 58 07 PM](https://user-images.githubusercontent.com/15860517/79746778-2d4a5c80-8328-11ea-9b1c-5e66569b4c3d.png)

**Comment by hanykumar** [comment]
Hi @iamir4g , closing for now. Let us know if the issue still persists.
