### ISSUE TITLE
Navigate push will get error navigate.opendrawer() is not a function

### ISSUE THREAD

**Issue by kimberly96** [GeekyAnts/NativeBase#3129]
i have 3 Screen. Login > Home > Anatomy. Home screen has a drawer. After klick save data in Anatomy, i am using `this.props.navigation.push('Anatomy') `so Home Screen will reload and give the data that i just saved.

But when i click drawer in Home screen i will getting error `TypeError_this3.props.navigation.openDrawer is not a function. In('_this3.props.navigation.openDrawer()', _this3.props.navigation.openDrawer is undefined)`

Its the same error when i am using `StackNavigator.reset.` I am using this so if i clicked back button at Home, i will not going to Login page. but it will get same error in Home Screen. Please any advice.

**Comment by hanykumar** [comment]
Hi @kimberly96 , can you provide minimal code reproduction on snack for the same?

**Comment by hanykumar** [comment]
Hi @kimberly96 , closing for now due to inactivity. Let us know if the issue still persists.
