### ISSUE TITLE
React Native Floating Label Text Input

### ISSUE THREAD

**Issue by thundenilla** [GeekyAnts/NativeBase#313]
@wcandillon  is there any of this method in nativebase? would be nice if i can implement the same behaviour like android in react native. Thanks.

**Comment by wcandillon** [comment]
@thundenilla Why are you asking me? 😅  I'm not a contributor on this project (yet ;-))

**Comment by sanketsahusoft** [comment]
@thundenilla If you can build one! We would love to embrace it. Btw, there are people working on Material Paper UI kit -- https://github.com/react-native-paper/react-native-paper

@wcandillon Good to see the "yet ;-)" in the comment :-)

**Comment by sanketsahusoft** [comment]
Added `floatingLabel` with 2.0
