### ISSUE TITLE
Cannot read property 'style' of undefined in native-base/dist/src/basic/Tabs/DefaultTabBar.js

### ISSUE THREAD

**Issue by ankurarora** [GeekyAnts/NativeBase#3130]
## I have gone through these following points

- [x] Check latest documentation: https://docs.nativebase.io/
- [x] Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x] Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [x] Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [] For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- [] For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

#### Versions 
- node 12.10.0, 
- npm 6.10.3,
- react-native 0.61.4, 
- react 16.9.0 
- native-base 2.13.8 
- expo 36.0.0

#### Expected behaviour
Should work without an error

#### Actual behaviour
Throws an error 

> Cannot read property 'style' of undefined

 in `node_modules/native-base/dist/src/basic/Tabs/DefaultTabBar.js`

#### Steps to reproduce

1. Import `<Button>` and use as per docs
2. Simply run `expo start`

![image](https://user-images.githubusercontent.com/5340725/79566680-52f01f80-80f6-11ea-9a23-6106916c9f55.png)

#### Is the bug present in both iOS and Android or in any one of them?
Yes

**Comment by hanykumar** [comment]
Hi @ankurarora , can you just provide minimal code reproduction on snack for the same?

**Comment by ankurarora** [comment]
Hi @hanykumar, I can't upload it on snack because it wouldn't let me add a dependency for `@expo/vector-icons` directly from master branch like so `"@expo/vector-icons": "https://github.com/expo/vector-icons#master"` and without it `native-base` can't use fonts. I can share code here however, if needed

**Comment by hanykumar** [comment]
Yeah sure, with the screenshot if possible.

**Comment by ankurarora** [comment]
> Yeah sure, with the screenshot if possible.

I've added to gist here https://gist.github.com/ankurarora/043ed59b5205df539dda5dcc4c098729

**Comment by hanykumar** [comment]
Hi @ankurarora , I am unable to reproduce the same error. Button is working fine as per the code provided by you. You must be using Tabs somewhere incorrectly. Please provide minimal code reproduction for the same.

**Comment by ajitdas123** [comment]
@hanykumar , I am facing the same issue. However i am trying to use nativebase with create react project along with `react-native-web`. A complete repo for the project is hosted here

[React project with nativebase](https://github.com/ajitdas123/react-native-web)

**Comment by virgil9306** [comment]
Same here. Is there any resolution?

**Comment by msaqlain** [comment]
Any solution to this?

This happens when I added react-native-web package

**Comment by ilabsllc** [comment]
Yep. Having the same issue with react-native-web pkg.

**Comment by SimonErm** [comment]
I think this should work as work around :https://github.com/necolas/react-native-web/issues/1576#issuecomment-615357971

**Comment by lordheart** [comment]
> I think this should work as work around :[necolas/react-native-web#1576 (comment)](https://github.com/necolas/react-native-web/issues/1576#issuecomment-615357971)

I don't know how to move that fix to @expo/webpack-config. Anyone know how to do it in expo?

**Comment by rickysullivan** [comment]
https://github.com/necolas/react-native-web/pull/1557#issuecomment-672355162

**Comment by stwilberth** [comment]
I could not fix the problem. help please, I don't speak English very well.

**Comment by matias91** [comment]
It seems they are already working on this issue: https://github.com/GeekyAnts/NativeBase/issues/3264#issuecomment-703404306
