### ISSUE TITLE
failed prop type invalid props.style key color supplied to pickerNB

### ISSUE THREAD

**Issue by ShuKTan** [GeekyAnts/NativeBase#3131]
I am getting below warning:
**_failed prop type invalid props.style key color supplied to pickerNB_** 

**My Code:**
```
<Item picker style={{marginLeft:15, marginRight: 15, borderBottomWidth:0}}>
   <Label style={{color: '#AFAEB3'}}>Title</Label>
   <Picker
           mode="dropdown"
            iosIcon={<Icon name="arrow-down-circle" style={{color:'#AFAEB3', marginRight: 10}} />}
            itemStyle={{color:'white'}}
            placeholder="Select your Title"
            placeholderStyle={{ color: "#AFAEB3" }}
            placeholderIconColor="#AFAEB3"
            selectedValue={this.state.personTitle}
            textStyle={{color: '#AFAEB3'}}
            
   > 
             <Picker.Item label="Mr." value="Mr. " />
             <Picker.Item label="Mrs." value="Mrs. " />
             <Picker.Item label="Ms." value="Ms. " />
   </Picker>
</Item>
```

**My Problem**
My app have black background color. I want to change the color of selected value to white. by default it is black (i guess).
above code is working as expected in iOS but not in android. In android, the select value cannot be seen as my background color is black too.

if I add  `style={{color: '#AFAEB3'}}` to < Picker >, the selected value is visible with given color in android but iOS generates `warning: failed prop type invalid props.style key color supplied to pickerNB` 

**Environment:**
react-native : "0.60.5"
react: "16.8.6"
nativebase: "^2.13.8"

**Comment by hanykumar** [comment]
Hi @ShuKTan , instead of using `style` in picker, please use `note`. `<Picker note ... ></Picker>` as per the [Native-Base Documentation](https://docs.nativebase.io/Components.html#picker-def-headref)

![Screenshot 2020-04-19 at 12 01 44 PM](https://user-images.githubusercontent.com/15860517/79681168-9ac99080-8235-11ea-9928-24f2e636d13f.png)

**Comment by ShuKTan** [comment]
Thank you @hanykumar for your quick reply. I will surly give it a try.
