### ISSUE TITLE
Tab Components

### ISSUE THREAD

**Issue by HeinXtet** [GeekyAnts/NativeBase#3132]
## I have gone through these following points

- [] Check latest documentation: https://docs.nativebase.io/
- [] Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [] Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [] Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [] For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- [] For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

#### Any other additional info which would help us debug the issue quicker.

###Important

If you want your issue to be looked at quicker, attach a snack reproducible with your issue. Makes it easier for us!

How to use tab component inside single component with his own props.? How to re - render for child component when tab is changed

**Comment by hanykumar** [comment]
Hi @HeinXtet , can you explain a little bit more?

**Comment by HeinXtet** [comment]
okay . i have dynamic tabs component , but use screen for components are same class .. when tab is changed child component is not re-rendered . example.  i have  3 tab and <ChildTabComponent props={owen props eg: index or id}/> is wrapped . when slide or pressed the tab , childtab is not re-rendered . how can re-render for that?

**Comment by HeinXtet** [comment]
`            <Tabs
              tabBarBackgroundColor={Colors.grayBackground2}
              tabBarUnderlineStyle={{backgroundColor: Colors.primaryColor}}
              renderTabBar={() => <ScrollableTab />}
              style={{backgroundColor: Colors.grayBackground2}}>
              {this.props.category!.subCategories.map((item) => (
                <Tab
                  activeTabStyle={{backgroundColor: Colors.grayBackground2}}
                  tabStyle={{backgroundColor: Colors.grayBackground2}}
                  activeTextStyle={styles.activeTabStyle}
                  heading={getLabel(item.name, localeProvider.name)}>
                  <ProductList item={item} />
                </Tab>
              ))}
            </Tabs>
`  i use like this . i just want to re-render for child component  when tab is changed

**Comment by sankhadeeproy007** [comment]
Hi, please refer to the docs here, we can use onChangeTab callback for your purpose.
https://docs.nativebase.io/Components.html#tabs-def-headref

**Comment by HeinXtet** [comment]
yes onChangeTap can handle in parent Component but child component didupdate is never call even change some prop

**Comment by hanykumar** [comment]
Hi @HeinXtet , can you provide minimal code reproduction on **snack** for the same?
