### ISSUE TITLE
Content view is not avoiding keyboard

### ISSUE THREAD

**Issue by Mavenic** [GeekyAnts/NativeBase#3133]
## I have gone through these following points

- [x] Check latest documentation: https://docs.nativebase.io/
- [x] Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x] Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [x] Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [] For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- [] For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

#### Versions
- node 10.15.3
- npm 6.14.3
- react-native 0.61.5
- react 16.9.0
- native-base 2.13.12

#### Expected behaviour
The View should be pushed above to avoid input box from being hidden when the keyboard is displayed

#### Actual behaviour
The keyboard is overlayed above Input hence hiding what is being written

#### Steps to reproduce
```
<Content>
       <Accordion
            style={[styles.b0]}
            contentContainerStyle={[styles.p20]}
            dataArray={passengers}
            expanded={0}
            animation={true}
            renderHeader={this.renderHeader}
            renderContent={this.renderContent}
            ItemSeparatorComponent={this.separatorView}
            ListHeaderComponent={this.renderNumberSelector}
            ListFooterComponent={this.contactDetailsView}
          />
</Content>
```

#### Is the bug present in both iOS and Android or in any one of them?
IOS

#### Any other additional info which would help us debug the issue quicker.
![gfiSaket](https://user-images.githubusercontent.com/1584324/79596439-31933180-80fe-11ea-8667-2ed238922166.gif)

#### Important
The Same Issue exists for footer also. The footer cannot be seen too.

**Comment by hanykumar** [comment]
Hi @Mavenic , try to resolve with this #3068.

**Comment by Mavenic** [comment]
Its already inside `Content` and I believe `Content` implements `KeyboardAvoidingView`

**Comment by hanykumar** [comment]
Hi @Mavenic , can you provide minimal code reproduction on snack for the same?

**Comment by hanykumar** [comment]
Hi @Mavenic , closing for now due to inactivity. Please let us know if the issue still persists with latest NativeBase v2.13.14.
