### ISSUE TITLE
Index of Picker is undefined 

### ISSUE THREAD

**Issue by nhuthuynh195** [GeekyAnts/NativeBase#3134]
## I have gone through these following points

- [] Check latest documentation: https://docs.nativebase.io/
- [] Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [] Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [] Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [] For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- [] For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

#### Any other additional info which would help us debug the issue quicker.

###Important

If you want your issue to be looked at quicker, attach a snack reproducible with your issue. Makes it easier for us!

**Comment by nhuthuynh195** [comment]
````
 <Picker
                    style={{paddingRight: 10}}
                    headerBackButtonTextStyle={{
                      fontFamily: 'Quicksand-Regular',
                    }}
                    headerTitleStyle={{fontFamily: 'Quicksand-Regular'}}
                    textStyle={{
                      fontFamily: 'Quicksand-Regular',
                      fontSize: 15,
                      fontWeight: 'normal',
                      paddingLeft: 10,
                    }}
                    itemTextStyle={{
                      fontFamily: 'Quicksand-Regular',
                    }}
                  
                    iosIcon={<Ionicons name="ios-arrow-down" />}
                    mode="dropdown"
                    // selectedValue={item.selectedUnit}
                    onValueChange={(value, index) =>
                      console.log('value && index', value, index)
                    }>
                    <Picker.Item key={1} label={'Value1'} value={'value1'} />
                    <Picker.Item key={2} label={'Value2'} value={'value2'} />
                   
                  </Picker>
````

**Comment by nhuthuynh195** [comment]
and result data is `value && index value2 undefined`

**Comment by nhuthuynh195** [comment]
how to fix it ???

**Comment by hanykumar** [comment]
Hi @nhuthuynh195 , we will merge #3135 in master branch soon.
Thanks

**Comment by hanykumar** [comment]
This issue has been fixed in master branch.
