### ISSUE TITLE
Received `true` for a non-boolean attribute `float`. due to floatingLabel

### ISSUE THREAD

**Issue by cybermritunjay** [GeekyAnts/NativeBase#3137]
If I add floatingLabel property in Item I get awarning in the console that Received `true` for a non-boolean attribute `float`.
Code:-
```
<Form>
        <Item floatingLabel>
          <Label>name</Label>
          <Input onChangeText={name => setName(name)}
            value={name} />
        </Item>
</Form>
```

Error:-

> Warning: Received `true` for a non-boolean attribute `float`.
> 
> If you want to write it to the DOM, pass a string instead: float="true" or float={value.toString()}.
>     in span (created by Text)
>     in Text (at Label.js:10)
>     in Label (at connectStyle.js:392)
>     in Styled(Label) (created by Item)
>     in div (created by Text)
>     in Text (at Label.js:10)
>     in Label (at connectStyle.js:392)
>     in Styled(Label) (at Item.js:346)
>     in div (created by View)
>     in View (created by AnimatedComponent)
>     in AnimatedComponent (at Item.js:334)
>     in div (created by View)
>     in View (created by TouchableOpacity)
>     in TouchableOpacity (at Item.js:434)
>     in Item (at connectStyle.js:392)
>     in Styled(Item) (at profile.js:50)
>     in div (created by View)
>     in View (at Form.js:10)
>     in Form (at connectStyle.js:392)
>     in Styled(Form) (at profile.js:49)
>     in div (created by View)
>     in View (created by ScrollView)
>     in div (created by View)
>     in View (created by ScrollViewBase)
>     in ScrollViewBase (created by ScrollView)
>     in ScrollView (at KeyboardAwareHOC.js:517)
>     in KeyboardAwareScrollView (at Content.js:37)
>     in div (created by View)
>     in View (created by SafeAreaView)
>     in SafeAreaView (at Content.js:36)
>     in Content (at connectStyle.js:392)
>     in Styled(Content) (at profile.js:47)
>     in div (created by View)
>     in View (at Container.js:12)
>     in Container (at connectStyle.js:392)
>     in Styled(Container) (at profile.js:46)
>     in Home (created by ConnectFunction)
>     in ConnectFunction (created by SceneView)
>     in StaticContainer
>     in StaticContainer (created by SceneView)
>     in EnsureSingleNavigator (created by SceneView)
>     in SceneView (created by CardContainer)
>     in div (created by View)
>     in View (created by CardContainer)
>     in div (created by View)
>     in View (created by CardContainer)
>     in div (created by View)
>     in View (created by Card)
>     in div (created by View)
>     in View (created by AnimatedComponent)
>     in AnimatedComponent (created by PanGestureHandler)
>     in PanGestureHandler (created by Card)
>     in div (created by View)
>     in View (created by AnimatedComponent)
>     in AnimatedComponent (created by Card)
>     in div (created by View)
>     in View (created by Card)
>     in Card (created by CardContainer)
>     in CardContainer (created by CardStack)
>     in div (created by View)
>     in View (created by MaybeScreen)
>     in MaybeScreen (created by CardStack)
>     in div (created by View)
>     in View (created by MaybeScreenContainer)
>     in MaybeScreenContainer (created by CardStack)
>     in CardStack (created by KeyboardManager)
>     in KeyboardManager (created by Context.Consumer)
>     in div (created by View)
>     in View (at NativeSafeAreaView.web.tsx:58)
>     in NativeSafeAreaView (at src/index.tsx:28)
>     in SafeAreaProvider (created by Context.Consumer)
>     in SafeAreaProviderCompat (created by StackView)
>     in div (created by View)
>     in View (created by StackView)
>     in StackView (created by StackNavigator)
>     in StackNavigator (at navigation.js:31)
>     in EnsureSingleNavigator (created by ForwardRef(BaseNavigationContainer))
>     in ForwardRef(BaseNavigationContainer) (created by ForwardRef(NavigationContainer))
>     in ThemeProvider (created by ForwardRef(NavigationContainer))
>     in ForwardRef(NavigationContainer) (at navigation.js:30)
>     in Navigator (at App.js:32)
>     in PersistGate (at App.js:31)
>     in Provider (at App.js:30)
>     in App (at withExpoRoot.web.js:13)
>     in RootErrorBoundary (at withExpoRoot.web.js:12)
>     in ExpoRootComponent (at registerRootComponent.web.js:6)
>     in RootComponent
>     in div (created by View)
>     in View (created by AppContainer)
>     in div (created by View)
>     in View (created by AppContainer)
>     in AppContainer

**Comment by hanykumar** [comment]
Hi @cybermritunjay , please update with the NativeBase latest v2.13.14 . Please try below code, if the error still occurs, Let us know.

```
<Form>
        <Item floatingLabel>
          <Label>name</Label>
          <Input />
        </Item>
</Form>
```

**Comment by hanykumar** [comment]
Hi @cybermritunjay , closing for now. Let us know if the issue still persists.
