### ISSUE TITLE
Unable to resolve "@shoutem/theme" from "node_modules\native-base\dist\src\index.js"

### ISSUE THREAD

**Issue by arshadmhabib** [GeekyAnts/NativeBase#3139]
Hello,
I am getting this error. I moved the theme folder into index.js folder. I also tried copying @shoutem/them folder into index.js folder. Still having issue. Any advice would be helpful!
![image](https://user-images.githubusercontent.com/47796998/80291077-55ff9700-8718-11ea-8ce1-1ee1b48381f3.png)

**Comment by hanykumar** [comment]
Hi @arshadmhabib , closing for now. Let us know if the issue still persists.
