### ISSUE TITLE
undefiend is not an  object (evaluating 'childrenArray[0].type') on Button.js 192

### ISSUE THREAD

**Issue by arabscimitar** [GeekyAnts/NativeBase#314]
Hello I have that error while rendering a button only on IOS but Android works fine

I have the latest release

**Comment by SupriyaKalghatgi** [comment]
Check with the latest of NativeBase [0.5.18](https://github.com/GeekyAnts/NativeBase/releases/tag/v0.5.18)

**Comment by vanydeasy** [comment]
Still got the same error using 0.5.18

**Comment by westcode** [comment]
I receive this error too when using the Picker component (loading items with a fetch/map).

**Comment by vanydeasy** [comment]
Resolve this error with rendering Picker only when array length > 0

**Comment by sankhadeeproy007** [comment]
#341 let's track this here

**Comment by sankhadeeproy007** [comment]
Fixed with 0.5.20
