### ISSUE TITLE
Support for the experimental syntax 'classProperties' isn't currently enabled

### ISSUE THREAD

**Issue by ajitdas123** [GeekyAnts/NativeBase#3141]
## I have gone through these following points

- [x] Check latest documentation: https://docs.nativebase.io/
- [x] Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x] Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [x] Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [x] For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- [x] For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

## Issue Description
When I am trying to use this `native-base` package along with `react-native-web` to build an application to run on android ios and web, it giving me the bellow error when trying to run on the website.

> Support for the experimental syntax 'classProperties' isn't currently enabled

 A snapshot of the error image has been attached below.

#### package.json
```
{
  "name": "react-webiste",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "axios": "^0.19.2",
    "fsevents": "^2.1.2",
     "native-base": "^2.13.12",
    "react": "^16.8.6",
    "react-dom": "^16.8.6",
    "react-native": "^0.62.1",
    "react-native-svg": "^12.1.0",
    "react-native-vector-icons": "^6.6.0",
    "react-native-web": "^0.12.2",
    "react-router-dom": "^5.1.2",
    "react-scripts": "3.0.0",
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "devDependencies": {
    "@babel/plugin-proposal-class-properties": "^7.8.3"
  }
}

```
#### babel.config.js

```
module.exports = {
    presets: ["@babel/preset-env", "@babel/preset-react"],
    plugins: ["@babel/plugin-proposal-class-properties",{"loose": true}]
};

```
#### Expected behaviour
It was expected to run smoothly without any error same as any android/ios device

#### Steps to reproduce
`index.js` of a newly created react project with build with react cli as suggested in `react-native-web`

```
import React, {Component} from 'react';
import logo from './logo.svg';
import './App.css';
import AsyncStorage from '@react-native-community/async-storage';
import {View,Text,Image} from 'react-native';
import { Button, Icon } from 'native-base';

export default class App extends Component {
    componentDidMount() {
        AsyncStorage.setItem('app', 'Testing Application').then(response => {
            console.log('Storage Response', response)
        });
    }


    render() {
        return (
                <View style={{flex:1,justifyContent:'center',alignItems:'center'}}>
                    <Image source={logo} style={{height:100,width:200}}/>
                  <Icon type="Entypo" name="cross" />
                    <Text>React native web project</Text>
                </View>
        )
    }
}

```

#### Is the bug present in both iOS and Android or in any one of them?
On Web

![nativeabase](https://user-images.githubusercontent.com/20204881/80367905-7f9bf800-88a9-11ea-955b-48a3e78f8605.jpg)

**Comment by piccinnigius** [comment]
@ajitdas123 do you fixed?

**Comment by ajitdas123** [comment]
@piccinnigius I don't know why the issue is, But I was able to get my work done by `ejecting` the app. and modifying the `webpack.config.js`.
