### ISSUE TITLE
Actionsheet theme variables are not customizable

### ISSUE THREAD

**Issue by iamnader** [GeekyAnts/NativeBase#3142]
## I have gone through these following points

- [x] Check latest documentation: https://docs.nativebase.io/
- [x] Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x] Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [x] Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [x] For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- [x] For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

## Issue Description

Hi, It looks like a few months back ActionSheet was updated to use variables.  But it looks like those are hardcoded to use package commonColor variable and if we have ejected the theme and implemented our own styles we can not override the ActionSheet variables?

See this: https://github.com/GeekyAnts/NativeBase/blob/master/src/basic/Actionsheet.js#L18 which is different than most other components.

#### Is the bug present in both iOS and Android or in any one of them?

ActionSheet customization is only relevant for Android

#### Any other additional info which would help us debug the issue quicker.

###Important

If you want your issue to be looked at quicker, attach a snack reproducible with your issue. Makes it easier for us!

**Comment by hanykumar** [comment]
Hi @iamnader , ActionSheet theme is limited for Android and iOS.

**Comment by hanykumar** [comment]
Hi @iamnader , closing for now.
