### ISSUE TITLE
Keyboard pushes content out of screen on Android

### ISSUE THREAD

**Issue by Manu206** [GeekyAnts/NativeBase#3144]
## I have gone through these following points

- [x] Check latest documentation: https://docs.nativebase.io/
- [x] Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x] Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [x] Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [x] For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- [x] For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

## Issue Description

I'm using a simple design that should center content vertically on the screen like a login page. I recognized that if I click on the input, the keyboard shows up and the content will be pushed way too far to the top and even outside of the screen. Is this normal? Maybe flex is not a good thing here? Sorry for the ugly screenshots but I wanted to keep it simple.

#### Expected behaviour

Input will be focused in the middle and not overflow to the top.

#### Actual behaviour

<img width="250" src="https://user-images.githubusercontent.com/16864103/80742320-7b771100-8b1b-11ea-943d-20454310e6d3.png">

<img width="250" alt="Bildschirmfoto 2020-04-30 um 19 49 39" src="https://user-images.githubusercontent.com/16864103/80742485-bed17f80-8b1b-11ea-945e-be0af68f75a5.png">

#### Steps to reproduce

```
class LoginScreen extends Component<Props> {
  render() {
    return (
      <Container>
        <Header transparent></Header>
        <Content contentContainerStyle={styles.container}>
          <Form>
            <Item regular style={{ width: "100%" }}>
              <Input />
            </Item>
            <Item regular>
              <Input />
            </Item>
            <Item regular>
              <Input />
            </Item>
            <Item regular>
              <Input />
            </Item>
            <Item regular>
              <Input />
            </Item>
            <Item regular>
              <Input />
            </Item>
            <Item regular>
              <Input />
            </Item>
            <Item regular>
              <Input />
            </Item>
            <Item regular>
              <Input />
            </Item>
          </Form>
        </Content>
      </Container>
    );
  }
}

export default LoginScreen;

const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "red"
  }
});
```

#### Is the bug present in both iOS and Android or in any one of them?

It is only present on Android. With iOS everything works as expected.

**Comment by hanykumar** [comment]
Hi @Manu206 , It works fine. please update the latest NativeBase v2.13.14 . Let us know if the issue still persists.

<img width="340" alt="Screenshot 2020-09-11 at 11 01 23 AM" src="https://user-images.githubusercontent.com/15860517/92867393-37c3da80-f41e-11ea-8606-b9fadb88cc4b.png">

**Comment by mmilad75** [comment]
I have the exact same problem on iOS but it works fine on Android.
"native-base": "^2.13.14"

**Comment by hanykumar** [comment]
Hi @Manu206 , closing for now due to inactivity. Let us know if the issue still persists.

**Comment by SeamusY** [comment]
@hanykumar still happens for me with native base verion "3.2.0"

**Comment by davidcort** [comment]
Same error on Android in "native-base": "^3.4.25",
