### ISSUE TITLE
Input label takes up space even with Item configs

### ISSUE THREAD

**Issue by DalerAsrorov** [GeekyAnts/NativeBase#3145]
## I have gone through these following points

- [x] Check latest documentation: https://docs.nativebase.io/
- [x] Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x] Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [x] Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [x] For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- [x] For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

## Issue Description
I added a form with inputs just like in the examples, but the label takes up space when I tap on the input instead of behaving same way as in demos.

#### Expected behaviour
Label should not take space within input if `Item` component is wrapped around both `Label` and `Input` components.

#### Actual behaviour
Label takes up space and doesn't allow the user to click on the input at the starting point.

#### Steps to reproduce
```js
    <Form>
      <Item>
        <Label>Username</Label>
        <Input />
      </Item>
      <Item>
        <Input placeholder="Password" />
      </Item>
    </Form>
```

![Screen Shot 2020-05-01 at 1 33 50 AM](https://user-images.githubusercontent.com/9118852/80784665-d88abb00-8b4b-11ea-93d4-af4b351d137f.png)

#### Is the bug present in both iOS and Android or in any one of them?
I used iOS

#### Any other additional info which would help us debug the issue quicker.

###Important

If you want your issue to be looked at quicker, attach a snack reproducible with your issue. Makes it easier for us!

**Comment by DalerAsrorov** [comment]
Quick update: This bug doesn't happen when I use `View` from `react-native-base` instead of the `Form` component... not sure why

**Comment by hanykumar** [comment]
Hi @DalerAsrorov , you can use floatingLabel or StackedLabel. Let us know if the issue still persists.
```
<Item stackedLabel>
     <Label>Username</Label>
     <Input />
</Item>
```
