### ISSUE TITLE
Tabs are not functional

### ISSUE THREAD

**Issue by harshit741** [GeekyAnts/NativeBase#3146]
I was trying to create tabs with the code given below, but when rendered I was not able to click on tabs nor the component in tab was visible.

```
 <View>
        <Appbar.Header>
          <Appbar.Action icon="home" />
          <Appbar.Content title="Home" />
        </Appbar.Header>

       <Container>
          <Tabs initialPage={0}>
            <Tab heading={<TabHeading style={styles.tabs}><Text>Current Location</Text></TabHeading>} >
              <CurrentLoc />
            </Tab>
            <Tab heading={<TabHeading style={styles.tabs}><Text>India</Text></TabHeading>} >
              <IndiaStat />
            </Tab>
          </Tabs>
       </Container>
      </View> 
```

**Comment by dianatdss** [comment]
@harshit741,  had the same issue and figured that if I render my container outside the view everything works fine

**Comment by dianatdss** [comment]
@harshit741, had the same issue. try setting your view to flex: 1. or wrap your entire component into the container, instead of a view

**Comment by harshit741** [comment]
Yeah, that worked. Thanks much.
