### ISSUE TITLE
fontFamily "Roboto_medium" is not a system font and has not been loaded through Font.loadAsync.

### ISSUE THREAD

**Issue by yuvaraghav03** [GeekyAnts/NativeBase#3147]
fontFamily "Roboto_medium" is not a system font and has not been loaded through Font.loadAsync.

- If you intended to use a system font, make sure you typed the name correctly and that it is supported by your device operating system.

- If this is a custom font, be sure to load it with Font.loadAsync.

i've gone through the documentation and i've included the same what's said in that.though i'm getting an error.

**Comment by marco-quintella** [comment]
You must load the font before starting the app in Expo.
There is an example here: https://docs.nativebase.io/docs/GetStarted.html
Just goo to **Setup with Expo**
