### ISSUE TITLE
footer is displayed above keyboard when input box gets focus on Android

### ISSUE THREAD

**Issue by knot22** [GeekyAnts/NativeBase#3149]
## I have gone through these following points

- [x] Check latest documentation: https://docs.nativebase.io/
- [x] Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x] Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [x] Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [] For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- [] For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

#### node, npm, react-native, react and native-base version, expo version if used, xcode version
node 12.13.1
npm 6.12.1
react-native 0.61.4
react 16.9.0
native-base 2.13.12
expo 36.0.2

#### Expected behaviour
When a form input field gets focus then keyboard pops up, covering footer.

#### Actual behaviour
On Android, when a form input field gets focus the keyboard pops up but the footer is displayed above keyboard.  This behaviour does not occur on iOS.

#### Steps to reproduce
Here is a picture of what the sample code below renders on iOS and Android -
[https://imgur.com/a/iSb40gf](https://imgur.com/a/iSb40gf)

Here is the code to reproduce this issue:
````
<template> 
  <root>
    <nb-container>
      <nb-header />    
      
      <nb-content>      

        <nb-form>
          <nb-item regular>
            <nb-input placeholder="Regular Textbox" />
          </nb-item>
        </nb-form>

      </nb-content>
      
      <nb-footer>
        <nb-footer-tab>
          <nb-button>
            <nb-text>Apps</nb-text>
          </nb-button>
          <nb-button>
            <nb-text>Camera</nb-text>
          </nb-button>
          <nb-button :active="true">
            <nb-text>Navigate</nb-text>
          </nb-button>
          <nb-button>
            <nb-text>Contact</nb-text>
          </nb-button>
        </nb-footer-tab>
      </nb-footer>

    </nb-container>
  </root>
</template>
````

#### Is the bug present in both iOS and Android or in any one of them?
This is only happening in Android.  The device shown in the photo is a Samsung Galaxy J3 Orbit.

#### Any other additional info which would help us debug the issue quicker.

###Important

If you want your issue to be looked at quicker, attach a snack reproducible with your issue. Makes it easier for us!

**Comment by RishabhKarnad** [comment]
@knot22 you could try this solution:

https://github.com/GeekyAnts/NativeBase/issues/787#issuecomment-299876920

If that doesn't work, you could use keyboard listeners as described here:
https://github.com/GeekyAnts/NativeBase/issues/787#issuecomment-298158992
Just use `mounted` in place of `componentWillMount` and `beforeDestroy` in place of `componentWillUnmount`

**Comment by knot22** [comment]
I decided to use the workaround approach that @yeknava posted which @RishabhKarnad pointed out above.  This particular project uses Vue Native so the code that was added looks like this -
````
<script>
import React from "react";
import { Keyboard, Platform } from "react-native";

export default {
  data() {
    return {
      showFooter: true
    }
  },
  mounted() {    
    if (Platform.OS === 'android') {
      this.keyboardDidShowListener = Keyboard.addListener('keyboardDidShow', () => this.showFooter = false);
      this.keyboardDidHideListener = Keyboard.addListener('keyboardDidHide', () => this.showFooter = true);
    }
  },
  beforeDestroy() {
    if (Platform.OS === 'android') {
      this.keyboardDidShowListener.remove();
      this.keyboardDidHideListener.remove();
    }
  }
}
</script>
````
Then a slight modification was necessary in the `<template>` to the footer component which was `<Footer v-if="showFooter" /> `.  I did not test this on the original code snippet provided for this issue but expect that `<nb-footer v-if="showFooter">` would work once the logic in `<script>` was added.

I chose to use an arrow function for the callback when adding the listener to keep the code concise - hopefully there are no pitfalls with going that route.  The Vue Native equivalent to the code that @yeknava used, which also works, is:
````
  methods: {
    _keyboardDidShow() {
      this.showFooter = false;
    },
    _keyboardDidHide() {
      this.showFooter = true;
    }
  },
  mounted() {    
    if (Platform.OS === 'android') {
		this.keyboardDidShowListener = Keyboard.addListener('keyboardDidShow', this._keyboardDidShow);
		this.keyboardDidHideListener = Keyboard.addListener('keyboardDidHide', this._keyboardDidHide);      
    }
  }
````
The workaround is not quite perfect because there is a delay in hiding the footer when the keyboard is activated.  This delay _is_ visible to the human eye.  The reason for applying it only to Android is so iOS does not have the delay of the footer reappearing when the keyboard is closed.
