### ISSUE TITLE
Fontawesome 5 Pro removed again in version 2.13.12

### ISSUE THREAD

**Issue by hariantara** [GeekyAnts/NativeBase#3152]
I have check nativebase version in 2.13.12 Fontawesome 5 Pro was removed again, but on this link look like already merged https://github.com/GeekyAnts/NativeBase/issues/2691

**Comment by davidgovea** [comment]
Looks like it was removed ~10days after addition: https://github.com/GeekyAnts/NativeBase/pull/2793

No comments, issues, explanation on that PR -- perhaps @PlabanJr can clarify?
I'm guessing it broke things for non-FA5Pro users, but more information would be nice to work toward a proper solution
