### ISSUE TITLE
Can ListItem use TouchableOpacity instead of TouchableHighlight?

### ISSUE THREAD

**Issue by Aryk** [GeekyAnts/NativeBase#3154]
I looked through the documentation and cheatsheets.

If I want ListItems to have that TouchableOpacity effect instead of TouchableHighlight, how can that be customized?

That seems it would have to switch what the ListItem is wrapped with.

Is this just something we can't customize?

**Comment by arochedy** [comment]
I think you can't customize, you can only update the ListItem component to use TouchableOpacity instead of TouchableHighlight

**Comment by hanykumar** [comment]
Hi @Aryk, yes, you cannot customize. For Android, it is `TouchableNativeFeedback` and for iOS & web, it is `TouchableHighlight` by default. 
But you can make changes manually in `node_nodules/native-base/src/basic/ListItem.js` from `TouchableHighlight` to `TouchableOpacity`.

**Comment by Aryk** [comment]
@hanykumar You can but how would I make those changes carry over into production? Or when I re-install node modules?

Really... there should be an ability to pass a way to overwrite the component with your own TouchableHighlife / TouchableNativeFeedback.

For example...if I want it to use TouchableHighlight from react-native-gesture-handler library...how can I do that without something super hacky?

**Comment by shivrajkumar** [comment]
@Aryk There isn't any way to do this in NativeBase. But to achieve this, you can just wrap a ListItem of NativeBase with TouchableOpacity, that should do the trick.

Closing this for now, let us know if you need further clarification/help on this.
