### ISSUE TITLE
"Error: React Native is not installed. Please run `npm install` in your project directory. Couldn't start project. Please fix the errors and restart the project".

### ISSUE THREAD

**Issue by ScoobyDu16** [GeekyAnts/NativeBase#3157]
## I have gone through these following points

- [x] Check latest documentation: https://docs.nativebase.io/
- [x] Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x] Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [x] Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [x] For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- [x] For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

## Issue Description
React-native is already installed on my system. Sometimes when I start my project using any of these command : "npm start", "yarn start", "expo start" this error is occurring. When I run "npm install" in my terminal the issue is resolved.

#### node, npm, react-native, react and native-base version, expo version if used, xcode version
Node : v12.16.2; npm : 6.13.0; react-native-cli: 2.0.1; expo: 37.0.0 
#### Any other additional info which would help us debug the issue quicker.
********ERROR IN THE TERMINAL********
yarn start
yarn run v1.22.4
$ expo start
Starting project at E:\Study Material\Practice\React-Native\blog
Expo DevTools is running at http://localhost:19002
Press d to open DevTools now, or shift-d to always open it automatically.
Error: React Native is not installed. Please run `npm install` in your project directory.
Couldn't start project. Please fix the errors and restart the project.
Error: Couldn't start project. Please fix the errors and restart the project.
    at startExpoServerAsync (C:\@expo\xdl@57.8.32\src\Project.ts:1948:11)
    at Object.startAsync (C:\@expo\xdl@57.8.32\src\Project.ts:2350:5)
    at action (C:\Users\pro\AppData\Roaming\npm\node_modules\expo-cli\src\commands\start.ts:163:3)
    at C:\Users\pro\AppData\Roaming\npm\node_modules\expo-cli\src\commands\start.ts:334:16
    at Command.<anonymous> (C:\Users\pro\AppData\Roaming\npm\node_modules\expo-cli\src\exp.ts:84:7)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

********PACKAGE.JSON********
{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "@react-native-community/masked-view": "0.1.6",
    "axios": "^0.19.2",
    "expo": "^37.0.0",
    "react": "16.9.0",
    "react-dom": "16.9.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz",
    "react-native-gesture-handler": "~1.6.0",
    "react-native-reanimated": "~1.7.0",
    "react-native-safe-area-context": "0.7.3",
    "react-native-screens": "~2.2.0",
    "react-native-web": "^0.11.7",
    "react-navigation": "^4.3.9",
    "react-navigation-stack": "^2.5.1"
  },
  "devDependencies": {
    "@babel/core": "^7.8.6",
    "babel-preset-expo": "^8.1.0"
  },
  "private": true
}
###Important

If you want your issue to be looked at quicker, attach a snack reproducible with your issue. Makes it easier for us!

**Comment by hanykumar** [comment]
Hi @ScoobyDu16 , please follow [react-native environment setup](https://reactnative.dev/docs/environment-setup). Closing for now. Let us know if the issue still persists.
