### ISSUE TITLE
Tab issue (scrollView.scrollTo)

### ISSUE THREAD

**Issue by phuongpt** [GeekyAnts/NativeBase#3159]
####  react-native, react and native-base version
```
"react-native": "0.61.4",
"native-base": "2.13.8",
```
#### We have tab implement like this
![native-base](https://user-images.githubusercontent.com/4443583/82626084-104bc680-9c11-11ea-9c61-538b8b74464e.gif)

#### But sometime app crashes on this screen, I guess due to tab not on the top screen at starting.
![Screen Shot 2020-05-22 at 8 49 08 AM](https://user-images.githubusercontent.com/4443583/82626141-38d3c080-9c11-11ea-87c7-9b2992bfae16.png)

**Comment by chgsantos** [comment]
It's already fixed on 2.13.9:
https://github.com/GeekyAnts/NativeBase/pull/2935

https://github.com/GeekyAnts/NativeBase/blob/081e777510591ba3d338e5282a137fdbda0c7759/src/basic/Tabs/index.js#L80

**Comment by phuongpt** [comment]
@chgsantos perfect, thanks
