### ISSUE TITLE
FontFamily in theme.js has no effect

### ISSUE THREAD

**Issue by daniel-van-niekerk** [GeekyAnts/NativeBase#316]
Hi, I followed the theme guide in the docs and I'm able to modify the settings in the light.js file. Colors and sizes etc works fine but changing the fontFamily any of the 9 provided fonts has no effect.

I restarted everything but still the issue. I'm only working on android at the moment.

`fontFamily: (Platform.OS === 'ios' ) ? 'HelveticaNeue' : 'Comic Sans MS'`

**Comment by lucianomlima** [comment]
For iOS only work for these fonts: Arial, Cochin, Courier New, Georgia and Times New Roman.

For another fonts return error `Unrecognized font family`.

**Comment by jeremypeters** [comment]
Yep, there's definitely something funky going on here. When I change the following in my theme:

    // Font
    fontFamily: (Platform.OS === 'ios' ) ? 'Georgia' : 'Georgia',
    fontSizeBase: 50,

Only the button text size in my header is changed, all the other text throughout the app is ignored, both the size and font family. I have added `theme={myTheme}` where it should be.

**Comment by SupriyaKalghatgi** [comment]
The following font families work as expected

- Andale Mono
- Arial Black
- Arial
- Comic Sans MS
- Courier New
- Georgia
- Microsoft Sans Serif
- Roboto
- Skia
- Times New Roman
- Entypo
- EvilIcons
- FontAwesome
- Ionicons
- Octicons
- Zocial

In case if the changes are not reflected, try restarting your packager

**Comment by lucianomlima** [comment]
For me restarting packager not resolve the problem.
The `react-native link` command works well copying the missing font families to platform dirs.

**Comment by SupriyaKalghatgi** [comment]
@lucianomlima Checkout the working example here - [Native Starter Kit](https://github.com/start-react/native-starter-kit)

**Comment by oakis** [comment]
Neither restarting the packager or running `react-native link` solves this for me. Font remains unchanged, so why is this closed?

**Comment by sanketsahusoft** [comment]
@oakis `react-native link` should solve it ideally. If not, go through [this article](https://medium.com/@dabit3/adding-custom-fonts-to-react-native-b266b41bff7f#.17tudl4i5)

**Comment by oakis** [comment]
@sanketsahusoft That doesn't help I'm afraid. I'm developing for Android only since I don't own a Mac. I'm on Ubuntu 16.04 if that helps. Cheers :)

Sidenote: My emulator crashed and then the font started working. I have no idea why but it seems to be working now, at least most of the times I do updates to the project.

**Comment by sanketsahusoft** [comment]
@oakis Good to know that you got the font working 👍 

Thanks!

**Comment by ckim16** [comment]
I want to use `Entypo` but it does not work as expected.

```
import Entypo from 'react-native-vector-icons/Entypo';

//and use Entypo like
<Entypo name="v-card" size={25}/>
```
but I don't see the icon, no error tho. :(

**Comment by bdavid68** [comment]
@ckim16 Please make sure you imported the font files in **android/app/src/main/assets/fonts** folder.
