### ISSUE TITLE
Unable to link react-native-vector-icons

### ISSUE THREAD

**Issue by wonderer007** [GeekyAnts/NativeBase#3161]
## Issue Description

I am following native-base docs https://docs.nativebase.io/Components.html#icon-def-headref but getting error **Unrecognized font family 'Ionicons'** for following code 

Issue is of `Icon`

```
import React, { Component } from 'react';
import { Container, Header, Content, Icon } from 'native-base';
export default class IconExample extends Component {
  render() {
    return (
      <Container>
        <Header />
        <Content>
          <Icon name='home' />
          <Icon ios='ios-menu' android="md-menu" style={{fontSize: 20, color: 'red'}}/>
          <Icon type="FontAwesome" name="home" />
        </Content>
      </Container>
    );
  }
}
```

[https://cloud.githubusercontent.com/assets/13981427/17029309/c48ee584-4f38-11e6-8e01-0df6f7dabc8f.png](url)

#### node, npm, react-native, react and native-base version, expo version if used, xcode version
```
node =>   v12.16.3
npm => 6.14.4
native-base => "^2.13.12"
```

**Comment by Grantlyk** [comment]
@wonderer007 for ionicons to work in native base you need to add `react-native-vector-icons` as a dependency to your project, do you currently have it installed?

**Comment by hanykumar** [comment]
Hi @wonderer007, This code works fine. Let us know, if you are still facing the issue.

**Comment by saini-g** [comment]
I'm still facing this issue, I started a fresh project using react native cli and got the error.
Here's exactly what I did
1. Start new project using `npx react-native init demo_app`
2. Installed native-base and react-native-vector-icons - `npm install --save native-base react-native-vector-icons`
3. In the ios directory ran `pod install`
4. Ran the app in the iOS simulator using `npm run ios`
5. Got the error

![Simulator Screen Shot - iPhone 11 - 2020-06-18 at 18 05 49](https://user-images.githubusercontent.com/50542972/85020755-6ec38080-b18e-11ea-9636-96fcc2266f12.png)

Please help.

**Comment by aldorea** [comment]
Any update?

**Comment by saini-g** [comment]
Finally got to the bottom of this, the issue was because of the font families not being available in the iOS project. Even though the libraries are auto-linked in React Native >= 0.60 the fonts are still missing and have to be manually added to the iOS project. Here's how to do that
- Go to the `info.plist` file located in `[project_root] > ios > [project_name] > info.plist`. It's an XML type file
- Add the following code. Make sure to not add it between any existing node
  ```
  <key>UIAppFonts</key>
  <array>
	<string>AntDesign.ttf</string>
	<string>Entypo.ttf</string>
	<string>EvilIcons.ttf</string>
	<string>Feather.ttf</string>
	<string>FontAwesome.ttf</string>
	<string>FontAwesome5_Brands.ttf</string>
	<string>FontAwesome5_Regular.ttf</string>
	<string>FontAwesome5_Solid.ttf</string>
	<string>Foundation.ttf</string>
	<string>Ionicons.ttf</string>
	<string>MaterialIcons.ttf</string>
	<string>MaterialCommunityIcons.ttf</string>
	<string>SimpleLineIcons.ttf</string>
	<string>Octicons.ttf</string>
	<string>Zocial.ttf</string>
	<string>Fontisto.ttf</string>
  </array>
  ```

**Comment by fosteruk** [comment]
> @wonderer007 for ionicons to work in native base you need to add `react-native-vector-icons` as a dependency to your project, do you currently have it installed?

Are you sure? That is not mentioned in the installation instructions.

**Comment by idhowardgj94** [comment]
> > @wonderer007 for ionicons to work in native base you need to add `react-native-vector-icons` as a dependency to your project, do you currently have it installed?
> 
> Are you sure? That is not mentioned in the installation instructions.

@wonderer007 's answer works for me too.
I use reac-native 0.63.2
so i don't, and i can't use react-native link, it will auto link

but still got this error, and resoved by his answer

**Comment by RobertSasak** [comment]
I find it confusing that *react-native-vector-icons* need to be installed as peer dependency. As mentioned earlier, I do not see any information in the official documentation. I also find confusing that native-base ships already with fonts folder in *node_modules*. 
<img width="780" alt="Screenshot 2020-07-31 at 18 27 51" src="https://user-images.githubusercontent.com/281281/89055978-9431d580-d35b-11ea-858a-a2c02af7ff86.png">
*Ionicons.ttf* has only 112kb and seems to be half of the size of official from *react-native-vector-icons*.

# My hypotesis is:
Native-base used to ship with fonts included. However those fonts stopped to be updated and it is expected that *react-native-vector-icons* installed as a peer dependency to overcome this issue. 

# Potential solution
1. Remove fonts from native-base
2. Add a clear note into docs regarding installing *react-native-vector-icons*
3. Add *react-native-vector-icons* as peer dependency requirement into package.json

**Comment by FadiAboMsalam** [comment]
I was in version 62.2 then i upgraded to 63.2 and now icons are not working even though they are loaded and linked 
I did not install react-native-vector-icons directly (the same way I used native base before) but now the icons are not working as expected for example      
```
  <Icon
            type="MaterialCommunityIcons"
            name="package-variant"
            style={packageFabIconStyle}
          />
```
it says it doesn't exist! even though it should

**Comment by jeveloper** [comment]
The version 12.13.13 have a peer dependency with the latest vector icon lib
 "react-native-vector-icons": "^7.0.0"

No need to duplicate it in your own project.

**Comment by hanykumar** [comment]
Hi @wonderer007 , you will need to add react-native-vector-icons manually for react-native project. Follow [here](https://github.com/oblador/react-native-vector-icons#ios). Please let us know if the issue still persists.
