### ISSUE TITLE
Documentation confusing? Am I doing something wrong?

### ISSUE THREAD

**Issue by mj-jackson** [GeekyAnts/NativeBase#3165]
Hi, I didn't really want to create an issue for this, but since the forum is non-secure I think I will go this route.

First and foremost. I really like nativeBase and want to share my experience in hopes to get it even better.

I have two major points.
1. Documentation confusing + the Screenshots next to the code snippets show something else.
I am referring to https://docs.nativebase.io/Components.html#Components
Take Buttons for example
https://docs.nativebase.io/Components.html#button-theme-headref
The way the buttons are shown in the first screenshot is not achievable for me with only nativeBase. Using the snippet shown next to the screenshot will result in full-width buttons. Even using Left or anything else will not get the buttons to be dynamic in width and align left.

I have the same problem with a lot of the snippets and screenshot shown in the docs. Just a quick not complete overview:
- Nowhere does the Content have the padder property, but is shown in most of the screenshots
- Form->Picker does have a label on the IOS Screenshot, it also is aligned right, which I had to achieve by putting in in a ListItem (not Item) and using Left for the label and Body for the picker
- Form->Picker again. Putting "picker" as a prop in the Item component (as said in the text and shown in the snippet) will result in the left padding to be taken away, yet the screenshot shows this left padding
- Form->Textarea displays an typescript error when not supplying the underline prop... a prop which does nothing and is not listed in the doc

This list is longer but I just wanted to make a point that it has been frustrating at times to use the docs just to see that I don't get what is promised.

2. Inconsistency in structure
The main problem here is that some of the components rely on some props, other components don't. My main example here is the padder prop on Content. Some components, like Card, seem to need it in order to look decent. Other components, like ListItem, look a little silly when being put inside a padder Content (also putting it in a List component doesn't help).
This basically makes mixing components a lot harder, which it shouldn't be.
Having the same base for all components that can be a child of that component would be very helpful.

**Comment by dakkafex** [comment]
the docs havent been updated since august 2019, i wouldn't hold your breath

**Comment by ybrodsky** [comment]
Is this abandoned? if so, are there any alternative that's still maintained? @dakkafex

**Comment by hanykumar** [comment]
Hi @mj-jackson , we are working on it. Thanks for your support.
