### ISSUE TITLE
activeOpacity does not work on CardItem

### ISSUE THREAD

**Issue by jhon-hst** [GeekyAnts/NativeBase#3169]
`
<Card style={{ marginBottom: 15 }}>

			<CardItem style={{ justifyContent: 'space-between' }} activeOpacity={0.5}>
				<Flag code={header.countryCode} size={64} type={'flat'} />
				<View>
					<Text>{header.country}</Text>
					<Text>{header.email}</Text>
					<Text>{header.callToAction}</Text>
				</View>
				<Image source={chevron} styles={{  width: 20, height: 20  }} height={20} width={20}/>
			</CardItem>
		</Card>
`

**Comment by hanykumar** [comment]
Hi @jhon-hst , `activeOpacity` works with `button` click. 
```
<CardItem
         button
         activeOpacity={0.2}
         >
         <Body>
             <Text>Your text here</Text>
         </Body>
</CardItem>
```
