### ISSUE TITLE
Badge Position

### ISSUE THREAD

**Issue by bemazo** [GeekyAnts/NativeBase#317]
Hi, I follow the example for the footer tabs and add a badge to one button. It's always shown on the left side. I tried to set the `alignSelf` to `flex-end` without success. The only way to move it to the right side is to set the style `right: 0`, but for that I need to set it directly into the widget code, because this is not added to the props.

How can I move the badge to the right side without to change the module code?

Thanks.

**Comment by SupriyaKalghatgi** [comment]
![footer-tabs](https://cloud.githubusercontent.com/assets/13464885/20742347/7c66566e-b6f5-11e6-8193-0b0f0a2747f4.png)
[FooterTabs](http://nativebase.io/docs/v0.5.13/components#footerTabs)
By default the Badge is on towards right

**Comment by bemazo** [comment]
yes, I saw it in the example, but what went wrong on my side? If I dont't set the right param the badge is shown on the left:

![bildschirmfoto 2016-11-30 um 08 16 01](https://cloud.githubusercontent.com/assets/5013404/20743208/52fe37a8-b6d5-11e6-84b3-7a407a3ac03b.png)

**Comment by SupriyaKalghatgi** [comment]
Did you try editing NativeBase components?
If so then try retaining its original code and simulate

**Comment by bemazo** [comment]
no yesterday I made a `rm -rf node_modules && npm install` so everything should be clean. I saw on debugging that inside the nativebase component the style value right is undefined, but nowhere defined.

Thanks for your help!

**Comment by bemazo** [comment]
sorry for the misunderstanding, the error is not left :)

**Comment by SupriyaKalghatgi** [comment]
@bemazo I hope your issue is fixed

**Comment by bemazo** [comment]
@SupriyaKalghatgi sorry no the issue is not fixed for me

**Comment by SupriyaKalghatgi** [comment]
Please reopen this issue and provide details of your issue

**Comment by bemazo** [comment]
fresh install of native base Version = 0.5.16, copy the example for the FooterTab from the docs,
but then my badge is shown on the left side even the color styling with attribute primary is not working. only if I add `right: 0` to the Badge.js under node_modules it is working:

`prepareRootProps() {

        var type = {

            backgroundColor:this.props.primary ?
                            this.getTheme().brandPrimary :
                            this.props.success ?
                            this.getTheme().brandSuccess :
                            this.props.info ?
                            this.getTheme().brandInfo :
                            this.props.warning ?
                            this.getTheme().brandWarning :
                            this.props.danger ?
                            this.getTheme().brandDanger :
                            this.getTheme().badgeBg,
            padding: (Platform.OS === 'ios') ? 3 : 0,
            paddingHorizontal: 10,
            alignSelf: 'flex-start',
            borderRadius: 13.5,
            height: 27,
            right: 0,

        }

        var defaultProps = {
            style: type
        }

        return computeProps(this.props, defaultProps);

    }` 
if I log `this.props` inside this function I see right is undefined without my added line.

**Comment by SupriyaKalghatgi** [comment]
@bemazo Thank you for details
We will look into this

**Comment by klinkov** [comment]
@bemazo it work, thank you!

**Comment by SupriyaKalghatgi** [comment]
@klinkov Did it work after adding `right: 0` to the **Badge.js** under `node_modules`?

**Comment by bemazo** [comment]
@klinkov you had the same that the badge was displayed on the left?

**Comment by klinkov** [comment]
@SupriyaKalghatgi, @bemazo  yeah, it's work

**Comment by maba1984** [comment]
Have the same problem with version 0.5.22, if i add more than 4 items or just 1.
Any suggestion what can help, i don't want to change code in the node_modules.

**Comment by nimamyscreen** [comment]
@maba1984 also have same problem with more than four items.
