### ISSUE TITLE
hide loader without close actionsheet

### ISSUE THREAD

**Issue by DaniSido** [GeekyAnts/NativeBase#3170]
Hi,

Is it possible to intercept the closing of the actionsheet?

the intent is to not make the loader more visible, but the moment I set the status to false the actionsheet is closed, do you know how I can 'hide' the oader without closing the actionsheet?

This problem occurs only with iOS

Here my code:

` 
    setIsPrintLoaderVisible(false);

    if (!isPrintLoaderVisible) {
      ActionSheet.show(
        {
          options: ["Stampa o Condividi QR", "Modifica", "Elimina", "Esci"],
          cancelButtonIndex: 4,
          destructiveButtonIndex: 3,
          title: "Scegli un'opzione"
        },
        buttonIndex => {
          if (buttonIndex == 0) {
              //code
          }
          if (buttonIndex == 1) {
              //code
          }
          if (buttonIndex == 2) {
              //code
          }
          if (buttonIndex == 3) {
            setIsPrintLoaderVisible(false);
            ActionSheet.hide();
          }
        }
      )
    }`

the return is:

`
{isPrintLoaderVisible &&
          <CustomLoader />
        }
`

Thanks so much

**Comment by hanykumar** [comment]
Hi @DaniSido , can you provide minimal code reproduction on snack with more details?

**Comment by hanykumar** [comment]
Hi @DaniSido , Keeping `ActionSheet` opened on selecting one of its menu is not possible as of now.
Thanks
