### ISSUE TITLE
FontAwesome uses different styles with same icon name

### ISSUE THREAD

**Issue by mmailhos** [GeekyAnts/NativeBase#3173]
Hello,

Is it possible to distinguish different style in the FontAwesome icon family?
As the names are the same, I don't feel it is possible to distinguish between a `solid` and a `regular` icon, such as [solid star](https://fontawesome.com/icons/star?style=solid) and [regular star](https://fontawesome.com/icons/star?style=regular).
I have tried to apply a class such as `className={['fas', 'fa-star']}`, without success.

#### node, npm, react-native, react and native-base version, expo version if used, xcode version

native-base:  2.13.12,
react: 16.11.0,
react-native: 0.62.2

#### Expected behaviour

Have a way to specify the style of the FontAwesome Icon.

#### Code
```
import {Icon} from 'native-base';
<Icon active type='FontAwesome5' name='star' />
```

**Comment by hanykumar** [comment]
Hi @mmailhos , Native Base `Icons` are limited to [react-native-vector-icons](https://github.com/oblador/react-native-vector-icons).

**Comment by mmailhos** [comment]
Thank you @hanykumar, I have decided to use FontAwesome library directly instead, to have access to those icons
