### ISSUE TITLE
How can you make a swipeable ListView without SwipeRow

### ISSUE THREAD

**Issue by chrstphmyr** [GeekyAnts/NativeBase#3174]
SwipeRow got removed from Native Base and I'm wondering how you can make a swipeable ListView that looks the same as a SwipeaRow by using react-native-swipe-list-view. I couldn't find any tutorials on how to replace the old SwipeRow with the new SwipeListView.

**Comment by ColorlessCoder** [comment]
You can checkout [SwipeRow API](https://github.com/jemise111/react-native-swipe-list-view/blob/master/docs/SwipeRow.md) if you want to integrate the SwipeRow in the FlatList.
Sample code:
```
            <FlatList
                data={itemList}
                renderItem={(item) => <SwipeRow>
                    <View style={hiddenRowStyle}>{/* hidden component*/}</View>
                    <View style={visibleRowStyle}>{/* visible component*/}</View>
                </SwipeRow>}
                keyExtractor={item => item.id}
            />
```

If you want to use SwipeListView, then there is a sample code in their [github page](https://github.com/jemise111/react-native-swipe-list-view#usage)
