### ISSUE TITLE
`@react-native-community/toolbar-android` from `node_modules/native-base/node_modules/react-native-vector-icons/lib/toolbar-android.js`: @react-native-community/toolbar-android could not be found within the project.

### ISSUE THREAD

**Issue by chayankiit** [GeekyAnts/NativeBase#3179]
System:
    OS: macOS 10.15.5
    CPU: (4) x64 Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz
    Memory: 43.27 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.16.2 - ~/.nvm/versions/node/v12.16.2/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v12.16.2/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 24, 26, 27, 28, 29
      Build Tools: 26.0.3, 28.0.3, 29.0.2, 29.0.3
      System Images: android-29 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6392135
    Xcode: 11.5/11E608c - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_222 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.2 => 0.62.2 
  npmGlobalPackages:
    *react-native*: Not Found

I am using "native-base": "^2.13.12"

![Screenshot 2020-07-07 at 04 24 39](https://user-images.githubusercontent.com/14080295/86668551-5f5a8900-c010-11ea-864e-36c1f3785293.png)

**Comment by kayzenkayzen** [comment]
Some issue!

As this issue show https://github.com/oblador/react-native-vector-icons/issues/1193

The problem was solved in 7.0.0 of react-native-vector-icons library, but native base still using version 6.6, I think native base needs to upgrade the dependency

**Comment by Jaroswaldo** [comment]
Any fix for this? I just walked in to this problem.

**Comment by jeveloper** [comment]
@akhil-geekyants Would you be so kind to let us knwo if this is an abandoned project? Thanks. Any plans to publish what's currently in the master branch?

**Comment by arnaudambro** [comment]
I think adding 
```
  "resolutions": {
    "native-base/react-native-vector-icons": "6.6.0"
  },
```

and reinstalled all packages + pods solved the problem to me

**Comment by feelthepain444** [comment]
Thanks @arnaudambro, that worked perfectly when  adding to my package.json. Was thinking of forking the code and updating the dependency myself.

**Comment by codler** [comment]
This command solved it for me
`npm install react-native-vector-icons@6.6.0 --no-save`

**Comment by jake41** [comment]
> I think adding
> 
> ```
>   "resolutions": {
>     "native-base/react-native-vector-icons": "6.6.0"
>   },
> ```
> 
> and reinstalled all packages + pods solved the problem to me

I guess this is for yarn only. npm doesnt have the resolutions feature

**Comment by codler** [comment]
I have [forked](https://github.com/codler/NativeBase) the repo to fix this issue.
```
npm i @codler/native-base
```
You will need to remove old fonts in `Copy Bundle Resources` in Xcode after install

**Comment by ashadnasim52** [comment]
Is there any fix,  I had tried adding the 
``` 
npm install react-native-vector-icons@6.6.0 --no-save
```

but it is not working

**Comment by brambang** [comment]
is there any solution for this?
why it was closed?
