### ISSUE TITLE
`<Content>` components not renders correctly on react-native 0.63.0

### ISSUE THREAD

**Issue by keima** [GeekyAnts/NativeBase#3183]
## I have gone through these following points

- [x] Check latest documentation: https://docs.nativebase.io/
- [x] Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x] Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [x] Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [x] For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- [x] For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

#### node, npm, react-native, react and native-base version, expo version if used, xcode version

node 10.18.0
npm 6.14.3
react-native 0.63.0
react 16.13.1
native-base 2.13.12
XCode 11.5

#### Expected behaviour

`<Content>` components renders correctly.

#### Actual behaviour

`<Text>Hi!</Text>` is not rendered and output error log below:

```
Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?
Check the render method of `Content`.

Warning: Functions are not valid as a React child. This may happen if you return a Component instead of <Component /> from render. Or maybe you meant to call this function rather than return it.
```

#### Steps to reproduce

```
import React, { Component } from 'react'
import { Container, Content } from 'native-base'

const Foo = () => (
  <Container>
    <Content>
      <Text>Hi!</Text>
    </Content>
  </Container>
)
```

#### Is the bug present in both iOS and Android or in any one of them?

Both.

#### Any other additional info which would help us debug the issue quicker.

###Important

If you want your issue to be looked at quicker, attach a snack reproducible with your issue. Makes it easier for us!

**Comment by cristian-rita** [comment]
This project is no longer maintained. They don't even make a build from master. Few issues are already fixed there.

**Comment by younes200** [comment]
Probleme related to change in `ScrollView` https://github.com/APSL/react-native-keyboard-aware-scroll-view/issues/429 one ce PR in react-native-keyboard-aware-scroll-view is merged this should be fixed.

**Comment by rmgpinto** [comment]
@cristian-rita do you recommend other ui lib that's properly maintained?

**Comment by codler** [comment]
I have the same issue.

**Comment by codler** [comment]
I have [forked](https://github.com/codler/NativeBase) the repo to fix this issue.
```
npm i @codler/native-base
```
You will need to remove old fonts in `Copy Bundle Resources` in Xcode after install

**Comment by younes200** [comment]
Thanks @codler.
Why removing old fonts is required ? I have issues rending font on iOS is it the case for you too ?

**Comment by codler** [comment]
You will probably get `duplicate output file error` when building ios, https://medium.com/codespace69/xcode-reactnative-ios-xcode-build-error-with-duplicate-output-file-when-install-new-library-36dfbcb5d223, but if not, then you dont need to do that.

**Comment by john-e** [comment]
Thanks @codler

**Comment by MartinMouritzen** [comment]
I guess I didn't do my homework well enough, choosing Native-Base. It does seem a bit abandoned, which makes me sad. I too would like recommendations for UI projects that are maintained.

**Comment by spdaly** [comment]
@codler Thanks for the effort. Everything worked perfectly.

@MartinMouritzen Agree.  I spent A LOT of time looking at a lot of different kits and decided on NB.  Unfortunately, this has been my experience with the RN ecosystem.  A lot of great libraries/kits/etc that have great promise but fall short.

**Comment by muyaszed** [comment]
LOL, I don't really realised this repo is kind of abandoned until I had this problem. But really it is quite a nice lib. Somebody should revive this one.

**Comment by Aung-Myint-Thein** [comment]
> I have [forked](https://github.com/codler/NativeBase) the repo to fix this issue.
> 
> ```
> npm i @codler/native-base
> ```
> 
> You will need to remove old fonts in `Copy Bundle Resources` in Xcode after install

I saw you forked rnkasv too. can I just install it but not the whole native-base? @codler

**Comment by vadympetryshyn** [comment]
> This project is no longer maintained. They don't even make a build from master. Few issues are already fixed there.

Is it really true? New pull requests no longer be merged? I've just started new project with RNB, should I find another UI Kit?

**Comment by codler** [comment]
> > I have [forked](https://github.com/codler/NativeBase) the repo to fix this issue.
> > ```
> > npm i @codler/native-base
> > ```
> > 
> > 
> > You will need to remove old fonts in `Copy Bundle Resources` in Xcode after install
> 
> I saw you forked rnkasv too. can I just install it but not the whole native-base? @codler

I only fork when needed

**Comment by jacargentina** [comment]
@hanykumar https://github.com/APSL/react-native-keyboard-aware-scroll-view/releases/tag/v0.9.2 just released!
Please update dependency and bump for new release ?

**Comment by raazatul7** [comment]
Is this issue fixed??
Please fix it asap and close it!

**Comment by madhumurugan89** [comment]
will this issue be fixed ? If not please suggest another UI library for react native

**Comment by ilya-bmi** [comment]
Please fix the issue!

**Comment by Aung-Myint-Thein** [comment]
https://github.com/APSL/react-native-keyboard-aware-scroll-view/issues/443#issuecomment-659357780

I updated the react-native-keyboard-aware-scroll-view with the command from the comment and `<Content>` is working again :D Hope this solves you guys too.

**Comment by jacargentina** [comment]
I've tried @Aung-Myint-Thein but didn't work.

Then i've tried this on my `package.json`:

```js
  "resolutions": {
    "native-base/react-native-keyboard-aware-scroll-view": "https://github.com/APSL/react-native-keyboard-aware-scroll-view#v0.9.2"
  }
```

Then `yarn install` and it works!
While i wait for a proper native-base release. Cheers!

**Comment by Aung-Myint-Thein** [comment]
> I've tried @Aung-Myint-Thein but didn't work.
> 
> Then i've tried this on my `package.json`:
> 
> ```js
>   "resolutions": {
>     "native-base/react-native-keyboard-aware-scroll-view": "https://github.com/APSL/react-native-keyboard-aware-scroll-view#v0.9.2"
>   }
> ```
> 
> Then `yarn install` and it works!�
> While i wait for a proper native-base release. Cheers!

Weird. It is not working for me after fresh npm install. I tried the resolutions method and it is still not working for me. Which React Native, Native Base versions are you using? @jacargentina ?

**Comment by jacargentina** [comment]
@Aung-Myint-Thein i'm using yarn, not npm (i dont think npm supports the `resolutions` feature; BTW i'm with rn 0.63 and latest published native-base

**Comment by yogesh1623** [comment]
Please fix the issue Asap!

**Comment by JerakRus** [comment]
@sankhadeeproy007 
is the repository really failing anymore? and will this critical issue be fixed?

**Comment by sankhadeeproy007** [comment]
Guys, is there a PR for this anywhere? 
I'll do a release quickly if I there's one.

**Comment by ankitghosh** [comment]
This has been fixed after the latest update! You guys can update the nativebase package and it will work

**Comment by sankhadeeproy007** [comment]
Thanks to @codler for their help in fixing this.

**Comment by Aung-Myint-Thein** [comment]
It is working now in my dev but my release apk is crashing upon start with 

```
Name FATAL EXCEPTION: mqt_native_modules
Reason java.lang.ClassCastException: com.facebook.react.bridge.ReadableNativeMap cannot be cast to java.lang.String
```

Is it happening the same for you guys?..

**Comment by nozbwang** [comment]
please fix it asap, thank you.
It spends me a lot of time finding my problem is caused by this lovely native-base package.  I have to roll back to older native-base  version so i can  continue my work.

**Comment by oriharel** [comment]
If this repo is not being maintained anymore, maybe [Paper](https://callstack.github.io/react-native-paper/)?

**Comment by Ar7profacex** [comment]
@codler Thank you very much, it worked perfectly, greetings from Chile

**Comment by impactcolor** [comment]
I dumped content 
<Content>
...
</Content>

To
<>
....
</>

**Comment by IamMasterWayne** [comment]
+1

**Comment by Florido14** [comment]
> please fix it asap, thank you. It spends me a lot of time finding my problem is caused by this lovely native-base package. I have to roll back to older native-base version (v2.6.1) so i can continue my work.
> 
> ![微信图片_20200810221549](https://user-images.githubusercontent.com/20251420/89792997-e04cf900-db57-11ea-83b1-fdb9708c4f6e.jpg)
I have the same issue, you can fix it?

**Comment by nozbwang** [comment]
> > please fix it asap, thank you. It spends me a lot of time finding my problem is caused by this lovely native-base package. I have to roll back to older native-base version (v2.6.1) so i can continue my work.
> > ![微信图片_20200810221549](https://user-images.githubusercontent.com/20251420/89792997-e04cf900-db57-11ea-83b1-fdb9708c4f6e.jpg)
> > I have the same issue, you can fix it?

 I fixed it by changing native-base version in my project ( for example changing to the lower version v2.6.1)。

 You can upgrade the native-base package to the lastest stable version to  find out whether the problem is fixed.
