### ISSUE TITLE
Picker Align Right Not Working

### ISSUE THREAD

**Issue by dl-husky73** [GeekyAnts/NativeBase#3188]
RN 63
NB 2.13
Android

Trying to align the picker item text to the right side with no effect. I have tried everything from documents, StackOverflow and Github issues.  There are a couple of dated references to an example but it doesn't align the picker item text on Android.  

Is there anyway to accomplish this task?

**Comment by dl-husky73** [comment]
Any response here?

**Comment by hanykumar** [comment]
Hi @dl-husky73 , is this you wanted? If not, please explain little more.
```
<View
              style={{
                alignItems: 'flex-end',
              }}>
              <Picker
                note
                mode="dropdown"
                style={{width: 120}}
                selectedValue={this.state.selected}
                onValueChange={this.onValueChange.bind(this)}>
                <Picker.Item label="Wallet" value="key0" />
                <Picker.Item label="ATM Card" value="key1" />
                <Picker.Item label="Debit Card" value="key2" />
                <Picker.Item label="Credit Card" value="key3" />
                <Picker.Item label="Net Banking" value="key4" />
              </Picker>
\</View>
```
<img width="637" alt="Screenshot 2020-09-07 at 4 22 46 PM" src="https://user-images.githubusercontent.com/15860517/92380549-ff26b700-f126-11ea-9534-d29aa0208c39.png">

**Comment by hanykumar** [comment]
Hi @dl-husky73 , closing for now due to inactivity. Please let us know if the issue still persists. You can not swap position of  `text` and `dropdown icon`.
