### ISSUE TITLE
DeckSwiper unexpectedly swipes to the opposite side

### ISSUE THREAD

**Issue by doubleh311** [GeekyAnts/NativeBase#3190]
## I have gone through these following points

- [] Check latest documentation: https://docs.nativebase.io/
- [] Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [] Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [] Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [] For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- [] For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

## Issue Description
Description:
The DeckSwiper unexpectedly swipes to the opposite side.

#### Steps to reproduce

When user swipes the card (to the Right for exp) then releases the card with a manner of finger that likely to move to the opposite site (to the Left for exp). 

#### Expected behaviour
The Card should be spring back to the balance position

#### Actual behaviour

The card will fall back to the Left 
In addition, when we use onSwipeRight and onSwipeLeft, the calculation will be incorrect. 

This issue is easier to happen on big screen mobiles and the behavior of the thumb that cannot reach as far as possible or hesitate to swipe the card.

#### Screen record:
The gif below shows the situation and we can see the side of Card Two and Card Three are swiped and the counting number increased on the action button below is counted to the other side.

![swipe-issue-2](https://user-images.githubusercontent.com/15910614/87851760-1535a980-c926-11ea-968f-de904bc0ed78.gif)

Issue happen on Kitchen Sink and version 2.13.8.

#### Code snippet
I spend a little time on the code and I think it happen in this check

`if (Math.abs(this.state.pan.x._value) > SWIPE_THRESHOLD) {
          if (velocity > 0) {
            this.props.onSwipeRight
              ? this.props.onSwipeRight(this.state.selectedItem)
              : undefined;
            this.selectNext();
          } else {
            this.props.onSwipeLeft
              ? this.props.onSwipeLeft(this.state.selectedItem)
              : undefined;
            this.selectNext();
          }
          Animated.decay(this.state.pan, {
            velocity: { x: velocity, y: vy },
            deceleration: 0.98
          }).start(this._resetState.bind(this));
        } else {
          Animated.spring(this.state.pan, {
            toValue: { x: 0, y: 0 },
            friction: 4
          }).start();
        }`

I have tried add this.state.pan.x._value to the check of velocity as below

`if (Math.abs(this.state.pan.x._value) > SWIPE_THRESHOLD) {
  if (velocity > 0 && this.state.pan.x._value >0 ) {
  ...
Animated.decay...
} else if (velocity < 0 && this.state.pan.x._value < 0 ) {
 ...
Animated.decay..
} else {
 Animated.Spring to balance
}
} else {
 Animated.Spring to balance
}`

The result in this gif and I also made some update to improve the swipe away animation
![deckSwiper-fix-improved](https://user-images.githubusercontent.com/15910614/87851665-1e724680-c925-11ea-9515-180d13e15906.gif)

I am currently change the file locally for my project and willing to create a PR.

**Comment by hanykumar** [comment]
Hi @doubleh311 , we will appreciate. Please go ahead and create PR.
