### ISSUE TITLE
Project status / future

### ISSUE THREAD

**Issue by majugurci** [GeekyAnts/NativeBase#3191]
Hi all!

First of all thank you for this wonderful free library. There is no other such a complete solution for react native.

By looking at the project activity (release versions, commits, issues) it seems that this project hasn't gotten any updates for a few months. Last release was 4 months ago and a lot has changed in react native world since then. Currently we can't upgrade to RN 0.63 version because of the issues in native base.

I have seen many comments saying this project is abandoned but could not find any official news.
I have seen some activity on V3 couple a months ago (YouTube, Twitter, this repository branches, etc.) but since then nothing.

Could you enlighten the community and tell us what are your plans for this project? Will it be maintained, further developed or sadly abandoned? Any feedback would be appreciated.

**Comment by ansarikhurshid786** [comment]
This is really great project. It is require for base setup of react native project. I am also waiting for update since few months.

**Comment by sankhadeeproy007** [comment]
Hey, we just published a new version with the latest dependency fixes.
Can you please upgrade and let us know?

**Comment by majugurci** [comment]
@sankhadeeproy007 I have updated native base and it is working correctly now. Thank you.

But can you tell us what are your further plans with this project?

**Comment by sankhadeeproy007** [comment]
@majugurci We are working on a new version of native-base with a newer API.
The plan is to gradually deprecate the current version and put our entire focus to the new API.
But we're still some way off that, so we'll continue to maintain this project till we get the newer version out.
