### ISSUE TITLE
The button level is wrong on Android

### ISSUE THREAD

**Issue by AKclown** [GeekyAnts/NativeBase#3192]
question：
 The button level is too high on Android

view：
  
android
![84260f30dcc6eec3ca92f8edd2009ad](https://user-images.githubusercontent.com/33648653/87899527-0d8c1700-ca84-11ea-898b-775e3b524ab1.jpg)

IOS
![c16c5b43378644a1296f65f1be22afb](https://user-images.githubusercontent.com/33648653/87899529-0f55da80-ca84-11ea-9935-5d3e901a645f.jpg)

**Comment by hanykumar** [comment]
Hi @AKclown , can you provide minimal code reproduction for the same with more details?

**Comment by hanykumar** [comment]
Hi @AKclown , closing for now due to inactivity. Please provide minimal code reproduction if the the issue still persists.
