### ISSUE TITLE
Icons wrong after updating to 2.13.13

### ISSUE THREAD

**Issue by jacargentina** [GeekyAnts/NativeBase#3194]
I' ve updated from 2.13.12 to 2.13.13 for use with RN 0.63

My icons are wrong!

<img width="376" alt="Captura de Pantalla 2020-07-20 a la(s) 15 38 48" src="https://user-images.githubusercontent.com/517228/87973842-82b91580-ca9f-11ea-8e07-383992ba1175.png">

I've done this already, removed all .ttf references from my Xcode project, and re-added them to reference `node_modules/react-native-vector-icons/Fonts/*.ttf`

I dont know what else to do? What is confusing is that there are Fonts in native-base itself, but in some issues like https://github.com/GeekyAnts/NativeBase/issues/425 says "NativeBase uses this for icons. Please check there for the complete list."

So i've included those Fonts from `node_modules/react-native-vector-icons/Fonts/*.ttf`

BUT, they are not working. Also, i'm not using Expo, so the README.md is not helping me.

Anybody? Cheers!

**Comment by Alaa-Ben** [comment]
Same issue: RN 0.62.2, Native Base  2.13.13 (no expo or anything else whatsoever)

**Comment by rnman** [comment]
[This comment](https://github.com/GeekyAnts/NativeBase/issues/425#issuecomment-376082933) on a different issue in the past helped me fix the icons in my app. I have no idea why a patch version of NativeBase broke icons, but I had to go in and manually check that each missing icon had a match in one of the sets that react-native-vector-icons supports, and change the name/type to fix.

**Comment by Alaa-Ben** [comment]
I'm already using type prop. Downgrading to 2.13.12 made the icons come back, so i'm probably gonna stay on it until it's fixed.

**Comment by jacargentina** [comment]
Hey all!! I've found my problem: i'm using `react-native-star-rating` package, which uses an old version for `react-native-vector-icons` and it seems there are some kind of conflict; when i uninstall `react-native-star-rating`, all works perfectly!

I will put a reference on that package to look for a solution.

Cheers!

**Comment by aldorea** [comment]
Any update?

**Comment by ansarikhurshid786** [comment]
I am getting issue in android and in ios working

**Comment by jacargentina** [comment]
@ansarikhurshid786 you should ensure to update your android fonts folder too (they are copied there, and not updated magically when upgrading native-base nor react-native-vector-icons)

I've done it like this:

```bash
rm android/app/src/main/assets/fonts/*.ttf
cp ./node_modules/react-native-vector-icons/Fonts/*.ttf android/app/src/main/assets/fonts/
```

**Comment by ansarikhurshid786** [comment]
@jacargentina Thanks i have update icon in android. Now working fine.

**Comment by jacargentina** [comment]
Everything solved, so closing this.

**Comment by IronTony** [comment]
Still not working. Anyone else have the same problem?

**Comment by ansarikhurshid786** [comment]
did you update font in android

**Comment by IronTony** [comment]
the problem is also in iOS

**Comment by ansarikhurshid786** [comment]
if you are using react-native <=0.59.10 then : 
`react-native link react-native-vector-icons`

**Comment by geekazoid-at** [comment]
> ```shell
> rm android/app/src/main/assets/fonts/*.ttf
> cp ./node_modules/react-native-vector-icons/Fonts/*.ttf android/app/src/main/assets/fonts/
> ```

Don't know why downvoted, worked for me. Had no icons in Android after upgrade, now they are back 👍
