### ISSUE TITLE
radio button doesn't work

### ISSUE THREAD

**Issue by mhmdalii** [GeekyAnts/NativeBase#3198]
i use native base version     "native-base": "^2.13.12",
radio button and check box get that in image ?
![fff](https://user-images.githubusercontent.com/33903920/88171764-31845f80-cc20-11ea-9880-18758f615a23.png)

**Comment by vsla** [comment]
Same here!
![image](https://user-images.githubusercontent.com/38630883/88809882-02736e00-d18b-11ea-9bd7-4e4a39aae5b6.png)

**Comment by Dheyson** [comment]
Same here on android, when true:
![image](https://user-images.githubusercontent.com/30505432/94855552-13e42b00-0405-11eb-8c05-93ce75b40c46.png)

when false:
![image](https://user-images.githubusercontent.com/30505432/94855565-19da0c00-0405-11eb-8723-72a1fffd6171.png)
