### ISSUE TITLE
Header buttons not working in IOS after the update of 2.13.13

### ISSUE THREAD

**Issue by YahiaBadr** [GeekyAnts/NativeBase#3199]
Any button that is shown in the header of native-base is not working in IOS after the update

**Comment by astrahov** [comment]
#3196

**Comment by hanykumar** [comment]
Hi @YahiaBadr , we just published a new version 2.13.14 with the latest dependency fixes.
Can you please upgrade and let us know?

**Comment by YahiaBadr** [comment]
I will check it

**Comment by hanykumar** [comment]
Hi @YahiaBadr , closing for now due to inactivity. Let us know if the issue still persists.
