### ISSUE TITLE
clearText of the Input on InputGroup

### ISSUE THREAD

**Issue by imarem** [GeekyAnts/NativeBase#320]
Is it possible clear text of the Input from an InputGroup?

**Comment by sankhadeeproy007** [comment]
You can use [clear()](https://facebook.github.io/react-native/docs/textinput.html#clear) function from react-native.

**Comment by alexsegura** [comment]
The `clear` method doesn't seem to be available on the NativeBase component.

I have to do this : 

```
<Input ref={(ref) => { this.input = ref }} />
```

```
this.input._root.clear();
```

Am I missing something ? I use NativeBase > 2.0

**Comment by IniZio** [comment]
@alexsegura did you do something like
```js
if (this.input != null) {
// ...
}
``` 
? I tried and the clear function works

**Comment by smitthakkar1** [comment]
Facing the same issue
