### ISSUE TITLE
CheckBox style abnormal

### ISSUE THREAD

**Issue by fujia666** [GeekyAnts/NativeBase#3201]
## I have gone through these following points

- [] CheckBox style abnormal。

## Issue Description

-v 2.13.13

**Comment by raazatul7** [comment]
Can you explain the issue?
@fujia666

**Comment by fujia666** [comment]
发自我的iPhone


------------------ Original ------------------

**Comment by RutsSantos** [comment]
I'm having a issue related to this. The checkbox is showing a hamburger icon when checked instead of the `check` icon

**Comment by santiagomartinez** [comment]
> Can you explain the issue?
> @fujia666

It is probably to this problem #3197 (I have the same problem)
