### ISSUE TITLE
expo start:web failed to compile after import native-base

### ISSUE THREAD

**Issue by yeungma** [GeekyAnts/NativeBase#3202]
## I have gone through these following points

- [x] Check latest documentation: https://docs.nativebase.io/
- [x] Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x] Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [] Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [] For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- [] For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

#### node, npm, react-native, react and native-base version, expo version if used, xcode version
****C:\myproj\pokesearch>node --version
v12.18.2

C:\myproj\pokesearch>expo --version
3.22.1

C:\myproj\pokesearch>npx react-native --version
4.10.1

C:\myproj\pokesearch>yarn list native-base
yarn list v1.22.4**
warning ..\package.json: No license field
warning Filtering by arguments is deprecated. Please use the pattern option instead.
└─ native-base@2.13.13
Done in 0.83s.**

#### Expected behaviour
In App.js,
    import {Button} from 'native-base'; 
is added in order to use the Button component.

#### Actual behaviour
expo start:web, below error comes 
web  Failed to compile.
C:/myproj/pokesearch/node_modules/@codler/react-native-keyboard-aware-scroll-view/lib/KeyboardAwareHOC.js 13:12
Module parse failed: Unexpected token (13:12)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| } from 'react-native'
| import { isIphoneX } from 'react-native-iphone-x-helper'
> import type { KeyboardAwareInterface } from './KeyboardAwareInterface'
|
| const _KAM_DEFAULT_TAB_BAR_HEIGHT: number = isIphoneX() ? 83 : 49

#### Steps to reproduce
App.js
//
import { StatusBar } from "expo-status-bar";
import { AppLoading } from "expo";
import React from "react";
import { StyleSheet, Text, View } from "react-native";
import { Button } from "native-base";

export default function App() {
  return (
    <View style={styles.container}>
      <Text>Open up App.js to start working on your app!</Text>
      <StatusBar style="auto" />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
  },
});

#### Is the bug present in both iOS and Android or in any one of them?
happen in web. not yet test in ios or android

#### Any other additional info which would help us debug the issue quicker.

###Important

If you want your issue to be looked at quicker, attach a snack reproducible with your issue. Makes it easier for us!

**Comment by patarapolw** [comment]
I downgrade many things, and upgrade one thing, in `package.json`.

```js
{
  "dependencies": {
    "native-base": "~2.11",
    "react-native-web": "~0.11"
  },
  "devDependencies": {
    "@babel/plugin-proposal-class-properties": "^7.10.4"
  },
  "resolutions": {
    "react-native-keyboard-aware-scroll-view": "^0.9.0"
  },
}
```

**Comment by robertwt7** [comment]
This also happened at ios, tested on iPad
