### ISSUE TITLE
ToastContainer has a line of Animated.timing that doesn't have useNativeDriver parameter supplied.

### ISSUE THREAD

**Issue by martintjandra** [GeekyAnts/NativeBase#3203]
There's currently one missing useNativeDriver for Animated.timing.

https://github.com/GeekyAnts/NativeBase/blob/51e42bed2bd5e6f315dc0a3173ee6bcd1ed84d32/src/basic/ToastContainer.js#L51-L54

Because of this, when someone call Toast.show, it will show yellow box warning about useNativeDriver. But the worse problem is that the Toast can't properly "clean up itself". This causes an invisible component stayed behind the disappearing Toast, blocking user interaction to be received to the component behind (such as bottom tab bar).

Before any Toast is shown, the bottom area can be tapped properly. When any Toast already shown, any subsequent tap to the bottom area (even when it looks empty) will produce yellow box warning, and all the components underneath the invisible view will not receive any user interaction like user touch, and this invisible box will persist even after navigating to other screens.

I see that a pull request has been made to fix this issue.

https://github.com/GeekyAnts/NativeBase/pull/3171

Please merge this pull request, as this is a very much needed fix.

**Comment by walterholohan** [comment]
Please merge 🙏

**Comment by Xopsy** [comment]
waiting for this merge, I had had to change my native-base node module to fix this issue. This merge would be great.

**Comment by copleykj** [comment]
#3278 fixes this issue in multiple components
