### ISSUE TITLE
Hi, does FooterTab supports lazy load? is there a difference in performance between React Navigation createBottomTabNavigator and Native-Base FooterTab?

### ISSUE THREAD

**Issue by KaizenTamashi** [GeekyAnts/NativeBase#3207]
## I have gone through these following points

- [x] Check latest documentation: https://docs.nativebase.io/
- [x] Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x] Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [x] Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [x] For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- [x] For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

## Issue Description
Hi, does `FooterTab` supports lazy load? is there a difference in performance between `React Navigation createBottomTabNavigator`  and `Native-Base FooterTab`?

#### Expected behaviour
N/A

#### Actual behaviour
N/A
#### Steps to reproduce
N/A

#### Any other additional info which would help us debug the issue quicker.

###Important

If you want your issue to be looked at quicker, attach a snack reproducible with your issue. Makes it easier for us!

**Comment by shivrajkumar** [comment]
@KaizenTamashi FooterTab doesn't support lazy loading.
And the FooterTab in native-base is just a UI component whereas the one from react navigation is a functional component with various options which also includes lazy loading
