### ISSUE TITLE
Broken types for Content component

### ISSUE THREAD

**Issue by davidgovea** [GeekyAnts/NativeBase#3209]
## I have gone through these following points

- [x] Check latest documentation: https://docs.nativebase.io/
- [x] Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x] Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [x] Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [x] For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- [x] For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

## Issue Description

PR #3185 broke the typescript definitions for the `Content` component.

@codler [changed the imported `react-native-keyboard-aware-scroll-view`](https://github.com/GeekyAnts/NativeBase/pull/3185/files#diff-73890935d8b7cec43384f2b26428017bR5) to his own fork, but did not update the version imported in the `index.d.ts` file: https://github.com/GeekyAnts/NativeBase/blob/master/index.d.ts#L4

This leads to type errors like the following: 
`Property 'bounces' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Content> & Readonly<Content> & Readonly<{ children?: ReactNode; }>'.`
unless the consuming project manually adds the upstream version of react-native-keyboard-aware-scroll-view to its dependencies as well (meaning, installing both the fork and upstream packages side-by-side).

Since the [upstream `react-native-keyboard-aware-scroll-view`]() has [fixed the issue](https://github.com/APSL/react-native-keyboard-aware-scroll-view/releases/tag/v0.9.2), **I suggest that native-base goes back to the upstream library.**

---
Since `patch-package` cannot be used to patch dependencies in `package.json`, here is a quick patchfile to fix the issue by importing the forked library in the typedef:

**patches/native-base+2.13.13.patch**
```
diff --git a/node_modules/native-base/index.d.ts b/node_modules/native-base/index.d.ts
index 73c40e9..8c0b92a 100644
--- a/node_modules/native-base/index.d.ts
+++ b/node_modules/native-base/index.d.ts
@@ -1,7 +1,7 @@
 declare module "native-base" {
 	import * as React from "react";
 	import * as ReactNative from "react-native";
-	import { KeyboardAwareScrollViewProps } from "react-native-keyboard-aware-scroll-view";
+	import { KeyboardAwareScrollViewProps } from "@codler/react-native-keyboard-aware-scroll-view";
 
 	type RnViewStyleProp = ReactNative.StyleProp<ReactNative.ViewStyle>;
 	type RnTextStyleProp = ReactNative.StyleProp<ReactNative.TextStyle>;

```

---

#### node, npm, react-native, react and native-base version, expo version if used, xcode version

```
$ node -v && npm -v && tsc -v
v12.18.2
6.14.5
Version 3.9.7
```

**Comment by willjallen** [comment]
I also ran into this issue using expo and would receive the following error

```
~/Desktop/proj/node_modules/native-base/dist/src/basic/Content.js
Module not found: Can't resolve '@codler/react-native-keyboard-aware-scroll-view' in 
~/Desktop/proj/node_modules/native-base/dist/src/basic'

```

For anyone else struggling with this, I ended up solving it by going to node_modules/native-base/dist/src/basic/Content.js
and changing
`var _reactNativeKeyboardAwareScrollView=require('@codler/react-native-keyboard-aware-scroll-view');`
to
`var _reactNativeKeyboardAwareScrollView=require('react-native-keyboard-aware-scroll-view');`

Versions
```
"react-native": "^0.63.2",
"expo": "^38.0.9",
"native-base": "^2.13.13",
"react": "^16.13.1",
```

**Comment by davidgovea** [comment]
Be aware that @willjallen's fix could fail to build for some projects, and may not work for RN 0.63, unless a newer version of `react-native-keyboard-aware-scroll-view` is pulled in by the project (at least `0.9.2`). It seems that his project is including the library indirectly in some other way.

Hoping that #3210 can be reviewed soon.
