### ISSUE TITLE
FooterTab button add text

### ISSUE THREAD

**Issue by shuchengc** [GeekyAnts/NativeBase#321]
It is fine when I only show one Icon in Button in the FooterTab . But when I add a text above the Icon, such as:
```
<FooterTab>
    <Button>
        Phone Call
        <Icon name='ios-call'/>
    </Button>
</FooterTab>
```
it shows the error, cannot add/remove sealed array elements. Anyone knows the solution

**Comment by paulsoh** [comment]
Same here..

I am getting `Unable to delete property.`

**Comment by shuchengc** [comment]
I am the fresh person for the nativebase, but I found there is a big issue of component reuse in nativebase. For example:
```
<Container>
   <Header>
    .......
  </Header>
</Container>
```
it is fine to show a header. but if I create a separated file name MyHeader.js:
```
<Header>
    .......
 </Header>
```
and I import the MyHeader file and show it, but it is not working and show nothing:
```
import MyHeader from './MyHeader'
.....
<Container>
   <MyHeader/>
</Container>
```
I believe It is a big issue to create reusable component and anyone has the same confusion.

**Comment by Deepankar01** [comment]
i  tried to use the given example in documentation [footerTabs](http://nativebase.io/docs/v0.5.13/components#footerTabs)

and it shows 
`unable to delete property`

**Comment by helloncanella** [comment]
+1

**Comment by lucianomlima** [comment]
@shuchengc when you create a new reusable component, sometimes you need to wrap in a <View> component to work correctly.

**Comment by SupriyaKalghatgi** [comment]
@shuchengc NativeBase as of now does not support Custom Components.
This has been on our list.

**Comment by SupriyaKalghatgi** [comment]
For FooterTabs, please check for its implementation in [NativeBase-KitchenSink](https://github.com/GeekyAnts/NativeBase-KitchenSink)
