### ISSUE TITLE
Ionicons not rendering the expected icon

### ISSUE THREAD

**Issue by Pixcell** [GeekyAnts/NativeBase#3213]
## I have gone through these following points

- [] Check latest documentation: https://docs.nativebase.io/
- [] Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [] Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [] Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [] For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- [] For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

#### node, npm, react-native, react and native-base version, expo version if used, xcode version
Node: v12.18.3
npm: 6.14.6
React: 16.11.0
native-base: 2.13.13
expo: 38.0.0
#### Expected behaviour

According to: https://oblador.github.io/react-native-vector-icons/

Expecting icons `ios-grid` and `people` to be those (Ionicons family)
![image](https://user-images.githubusercontent.com/4005291/89750236-36517a80-db1f-11ea-8193-0d3de3f18fd9.png)

#### Actual behaviour

Getting those instead
![image](https://user-images.githubusercontent.com/4005291/89750246-436e6980-db1f-11ea-9087-54d82893d2d1.png)

#### Steps to reproduce

```
import {Icon} from 'native-base'

<Icon name="ios-grid" type="Ionicons" />
<Icon name="people" type="Ionicons" />
```

https://snack.expo.io/@pixcell/mad-coffee

#### Any other additional info which would help us debug the issue quicker.

###Important

If you want your issue to be looked at quicker, attach a snack reproducible with your issue. Makes it easier for us!

**Comment by alfianwahid** [comment]
I faced same problem. 
NativeBase Icon uses [react-native-vector-icons](https://github.com/oblador/react-native-vector-icons)
Try update the font.

- **Android**
copy all fonts from `/yourproject/node_modules/react-native-vector-icons/Fonts` and paste to `/your-project/android/app/src/main/assets/fonts`

- IOS 
via xcode just drag and drop all font `/yourproject/node_modules/react-native-vector-icons/Fonts` to "Resources"

![image](https://user-images.githubusercontent.com/2808896/89937231-000b1c80-dc3f-11ea-89c8-260a23b78dbf.png)

**Comment by jjleng** [comment]
Verified @alfianwahid's solution. It worked. The problems were caused by the out of dated font files provided by NativeBase. You can also install my patched version `yarn add "git+https://github.com/jjleng/NativeBase.git#v2.13.13"` and then `npx react-native link`.

**Comment by Pixcell** [comment]
Thanks heaps for the help !
It is my first project using React-Native and Native-Base. I am really enjoying it so far. However, I am using a build managed by expo.
Where do I need to put my Fonts for this to work ?

It uses a hook to load some resources before the app start
```
import * as Font from 'expo-font'
import * as SplashScreen from 'expo-splash-screen'
import * as React from 'react'

export default function useCachedResources () {
  const [isLoadingComplete, setLoadingComplete] = React.useState(false)

  // Load any resources or data that we need prior to rendering the app
  React.useEffect(() => {
    async function loadResourcesAndDataAsync () {
      try {
        SplashScreen.preventAutoHideAsync()

        // Load fonts
        await Font.loadAsync({
          // ...Ionicons.font,
          Ionicons: require('native-base/Fonts/Ionicons.ttf'),
          Roboto: require('native-base/Fonts/Roboto.ttf'),
          Roboto_medium: require('native-base/Fonts/Roboto_medium.ttf')
        })
      } catch (e) {
        // We might want to provide this error information to an error reporting service
        console.warn(e)
      } finally {
        setLoadingComplete(true)
        SplashScreen.hideAsync()
      }
    }

    loadResourcesAndDataAsync()
  }, [])

  return isLoadingComplete
}
```

I tried adding the `Ionicons` bit in there, but it didn't work as expected.

Any help is greatly appreciated

**Comment by tudiantuan** [comment]
> I faced same problem.
> NativeBase Icon uses [react-native-vector-icons](https://github.com/oblador/react-native-vector-icons)
> Try update the font.
> 
> * **Android**
>   copy all fonts from `/yourproject/node_modules/react-native-vector-icons/Fonts` and paste to `/your-project/android/app/src/main/assets/fonts`
> * **IOS**
>   via xcode just drag and drop all font `/yourproject/node_modules/react-native-vector-icons/Fonts` to "Resources"
> 
> ![image](https://user-images.githubusercontent.com/2808896/89937231-000b1c80-dc3f-11ea-89c8-260a23b78dbf.png)

I do it but not working, what do I need to do next?

**Comment by TheRusskiy** [comment]
Not fixed
