### ISSUE TITLE
Tabs , Error while updating 'nativeBackgroundAndroid'

### ISSUE THREAD

**Issue by sm2017** [GeekyAnts/NativeBase#3214]
## I have gone through these following points

- [x] Check latest documentation: https://docs.nativebase.io/
- [x] Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x] Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [x] Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [x] For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- [x] For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

#### node, npm, react-native, react and native-base version, expo version if used, xcode version

```
System:
    OS: Windows 10 10.0.18363
    CPU: (4) x64 Intel(R) Core(TM) i3-8100 CPU @ 3.60GHz
    Memory: 2.05 GB / 11.85 GB
  Binaries:
    Node: 10.15.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 23, 26, 27, 28, 29
      Build Tools: 23.0.1, 27.0.3, 28.0.3, 29.0.2
      System Images: android-19 | Google APIs ARM EABI v7a, android-19 | Google APIs Intel x86 Atom, android-21 | ARM EABI v7a, android-21 | Google APIs Intel x86 Atom, android-22 | Google APIs Intel x86 Atom, android-28 | Intel x86
 Atom_64, android-28 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: Version  4.0.0.0 AI-193.6911.18.40.6626763
  Languages:
    Java: 1.8.0_221 - C:\Program Files\Java\jdk1.8.0_221\bin\javac.EXE
    Python: 2.7.16 - C:\Python27\python.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.2 => 0.63.2
  npmGlobalPackages:
    *react-native*: Not Found

```

#### Expected behaviour
`Tabs` component must work an android kitkat

#### Actual behaviour
`Tabs` component has Error while updating 'nativeBackgroundAndroid'

#### Steps to reproduce

```js
import React, { Component } from 'react';
import { Container, Content, Tabs } from 'native-base';

import TabOne from './tabOne';
import TabTwo from './tabTwo';
​
export default class TabsExample extends Component {
    render() {
        return (
            <Container>
                <Content>
                    <Tabs>
                        <TabOne tabLabel='One' />
                        <TabTwo tabLabel='Two' />
                    </Tabs>
                </Content>
            </Container>
        );
    }
}
```
![image](https://user-images.githubusercontent.com/19644997/89786143-b6341080-db30-11ea-8fa8-f8098478adc4.png)

#### Is the bug present in both iOS and Android or in any one of them?
I tested in android kitkat but I think it occured on api<21

#### Any other additional info which would help us debug the issue quicker.

###Important

If you want your issue to be looked at quicker, attach a snack reproducible with your issue. Makes it easier for us!

**Comment by sm2017** [comment]
@sankhadeeproy007 @SupriyaKalghatgi @akhil-geekyants take a look please

**Comment by hanykumar** [comment]
Hi @sm2017 , Is it working on latest Android version? If not, please follow [NativeBase Docs](https://docs.nativebase.io/Components.html#tabs-def-headref). You are not using `Tab` as shown in the code provided by you. 
Let us know if the issue still persists. 

```
import React, { Component } from 'react';
import { Container, Header, Content, Tab, Tabs } from 'native-base';

export default class TabsExample extends Component {
  render() {
    return (
      <Container>
        <Header hasTabs />
        <Tabs>
          <Tab heading="Tab1">
            ...
          </Tab>
          <Tab heading="Tab2">
          ...
          </Tab>
          <Tab heading="Tab3">
            ...
          </Tab>
        </Tabs>
      </Container>
    );
  }
}


```

**Comment by hanykumar** [comment]
Hi @sm2017 , closing for now due to inactivity. Let us know if the issue still persists.

**Comment by umairshaikh6405** [comment]
Error while updating property 'nativeBackgroundAndroid' of a view managed by: RCTView

I've reproduced the issue. Android versions between 4.1 and 4.4 are crashing
