### ISSUE TITLE
Issues in placeholder and cursor tint color

### ISSUE THREAD

**Issue by krishnmobilehub** [GeekyAnts/NativeBase#3215]
Hello,
I am using this library and getting below issues in Android device. 
1. I cannot change cursor tint color in textfield. I want to change it.
2. When I want to add prefix text in textfield on that field placeholder is overlapping.

Can you please help me to sort out this thing? Thanks 

![Image 1](https://user-images.githubusercontent.com/56722459/89803680-c8be4200-db50-11ea-8c13-39e2de61db4e.jpg)

![Image 5](https://user-images.githubusercontent.com/56722459/89804072-4d10c500-db51-11ea-8045-9e9cb6979f9a.jpg)

**Comment by hanykumar** [comment]
Hi @krishnmobilehub , can you provide minimal code reproduction for your second point?
- You can use `selectionColor="red"`
- 

```
<Item>
        <Input
          placeholder="Enter Name"
          placeholderTextColor="pink"
          selectionColor="red"
          value="XYZ"
        />
</Item>
```
with `value="XYZ"`
<img width="357" alt="Screenshot 2020-09-02 at 4 38 59 PM" src="https://user-images.githubusercontent.com/15860517/91974024-d2475e00-ed3a-11ea-887f-c3e00e50575f.png">

without `value="XYZ"`
<img width="357" alt="Screenshot 2020-09-02 at 4 40 01 PM" src="https://user-images.githubusercontent.com/15860517/91974139-f9059480-ed3a-11ea-9c48-70a6bb448354.png">

**Comment by hanykumar** [comment]
Hi @krishnmobilehub , closing for now due to inactivity. Let us know if the issue still persists.

**Comment by DaniSido** [comment]
Hi @hanykumar,
neither of them works for me, in fact I get the following error:

`Failed prop type: Invalid prop `placeholderTextColor` supplied to `ForwardRef(TextInput)``

Can someone help me?
Thank you very much
