### ISSUE TITLE
Appropriate Loaders Issue

### ISSUE THREAD

**Issue by ebrahim3108** [GeekyAnts/NativeBase#3219]
## I have gone through these following points

- [x] Check latest documentation: https://docs.nativebase.io/
- [x] Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x] Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [x] Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [x] For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- [x] For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

## Issue Description
Hi Team,
I'm trying to import a Button from the native-base library. When I compile my app I get an error 
"(My app Directory)/node_modules/@codler/react-native-keyboard-aware-scroll-view/lib/KeyboardAwareHOC.js 13:12
Module parse failed: Unexpected token (13:12)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders"

#### Steps to reproduce
All I did is installed native-base in expo and added a line "import {Button} from native-base" and it gives an error. 

#### Below is my code snippet 
const { ScreenContainer } = require("react-native-screens");

import React from "react";
import { StyleSheet, View, Text} from "react-native";
import { Button } from "native-base";
import OTPTextView from "react-native-otp-textinput";

export function otpverification({ navigation }) {
  return (
    <View style={Style.Container}>
      <Text>Verification</Text>
      <Text>
        Please check your message for a six-digit security code and enter it
        below
      </Text>
      <OTPTextView
        handleTextChange={(e) => {}}
        containerStyle={Style.textInputContainer}
        textInputStyle={Style.roundedTextInput}
        inputCount={5}
        inputCellLength={2}
      />
      <Text>Didn't get a code? &nbsp;</Text>
      <TouchableOpacity>
        <Text style={{ color: "#1DA1F2" }}>Send again</Text>
      </TouchableOpacity>
      <Button primary><Text></Text></Button>
    </View>
  );
}

const Style = StyleSheet.create({
  textInputContainer: {
    marginBottom: 20,
  },
  roundedTextInput: {
    borderRadius: 10,
    borderWidth: 4,
  },
  Container: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
});
export default otpverification;

#### Is the bug present in both iOS and Android or in any one of them? - Both

###Important

![Error](https://user-images.githubusercontent.com/69892719/90606859-09d3e780-e21e-11ea-9d93-c438c70e8693.png)

**Comment by zeptonaut** [comment]
Also running into this issue trying to import `native-base` into my project.

**Comment by hanykumar** [comment]
Hi @ebrahim3108 , We are unable to reproduce this issue. Please provide minimal code reproduction on snack for the same with more details.  

![Screenshot 2020-09-02 at 3 54 21 PM](https://user-images.githubusercontent.com/15860517/91969970-98735900-ed34-11ea-8b2d-0082810cf4a5.png)

**Comment by dylanarmstrong** [comment]
To duplicate:
1. Download zip from https://snack.expo.io/o4hwq7pSc
2. npm i
3. npm run start
4. open in web browser

Note: It does not happen on the snack website.
