### ISSUE TITLE
Remove ToastContainer listeners when unmounting the component

### ISSUE THREAD

**Issue by GabrielePrestifilippo** [GeekyAnts/NativeBase#3220]
## Issue Description

The `ToastContainer` adds two listeners on mounting and never removes them. See https://github.com/GeekyAnts/NativeBase/blob/47643385e1b7224387fb7fd70451746fc70accaa/src/basic/ToastContainer.js#L61

#### Expected behaviour
This is wrong behavior and they should be removed as

```
  componentWillUnmount() {
    Keyboard.removeListener('keyboardDidShow', this.keyboardDidShow);
    Keyboard.removeListener('keyboardDidHide', this.keyboardDidHide);
  }
```
#### Actual behaviour
A warning might appear

**Comment by damii** [comment]
Need to add this on next release

  componentWillUnmount() {
    Keyboard.removeListener('keyboardDidShow', this.keyboardDidShow);
    Keyboard.removeListener('keyboardDidHide', this.keyboardDidHide);
  }

**Comment by hanykumar** [comment]
Hi @GabrielePrestifilippo , Thanks for your support.
