### ISSUE TITLE
[ENHANCEMENT?]Tabs: How to go back to first tab when you right swipe on the last tab

### ISSUE THREAD

**Issue by coderscode2** [GeekyAnts/NativeBase#3222]
Hi, 
I am not facing any bugs or issues. I have a requirement of circular tab scrolls. I mean, when you swipe the last tab to see the next, since there would no next tab for last, it should go to the first tab. Similarly, when you swipe on the first tab to see previous tab, it should go to the last tab. Like a carousel fashion. Please suggest. Thanks in advance.

**Comment by vedgenerac** [comment]
Deck Swiper is one option I think
