### ISSUE TITLE
Doesn't work with RN 0.63.x

### ISSUE THREAD

**Issue by itryapitsin2** [GeekyAnts/NativeBase#3225]
## I have gone through these following points

- [x] Check latest documentation: https://docs.nativebase.io/
- [x] Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x] Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [x] Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [] For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- [] For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

## Issue Description
The library doesn't work with the latest version of RN.

#### node, npm, react-native, react and native-base version, expo version if used, xcode version
node -v
v12.13.0

npm -v
6.12.0

react-native
0.63.2

react
16.13.1

native-base
2.13.14

expo
38.0.9

#### Expected behaviour
Should work

#### Actual behaviour
Throw errors

#### Steps to reproduce
Use a native-base component with the RN > 0.63
index.js
```index.js
import { registerRootComponent } from 'expo';

import { AppRegistry, YellowBox } from 'react-native';
import { name as appName } from './app.json';
import App from './src/App';

YellowBox.ignoreWarnings(['Remote debugger']);

AppRegistry.registerComponent(appName, () => App);
registerRootComponent(App);
```

App.js
```app.js
import React from 'react';
import { Container, Content } from "native-base";

export default function App() {
  return (
    <Container>
      <Content/>
    </Container>
  );
}
```
See the errors in console
![image](https://user-images.githubusercontent.com/24933570/90979994-44f95200-e561-11ea-8224-b1efa504e57c.png)

#### Is the bug present in both iOS and Android or in any one of them?
Checked on an Android emulator and device

#### Any other additional info which would help us debug the issue quicker.
Works fine with RN ~0.62

### Important
Broken after migration RN ~0.62 to 0.63.2

**Comment by hanykumar** [comment]
Hi @itryapitsin2 , closing for now due to inactivity. Let us know if the issue still persists.
