### ISSUE TITLE
Checkbox and radio button presentation not working

### ISSUE THREAD

**Issue by sjonchhe** [GeekyAnts/NativeBase#3226]
## Issue Description
I am having problem with checkbox and radio button of native base. In checkbox, instead of check(tick) icon hyphen icon shows whereas for radio buttons shuffle icon shows up instead of cicle radiobutton. Has anybody faced similar issues?? It was all good until last week. I dont know what has happened now. I have tried reinstalling vector icons,native base.But nothing worked.

#### node, npm, react-native, react and native-base version, expo version if used, xcode version
React native version 0.62.2
Native base version 2.13.14
Platform : android

#### Expected behaviour
Show checkbox and radio button with theier normal presentaion ie check mark icon in checkbox and radio(cicle) button icon in radio button

#### Actual behaviour
Hyphen icon in checkbox and share icon radio button

#### Steps to reproduce
Simply use checkbox and radiobutton from native base library.
![IMG_20200821_125012](https://user-images.githubusercontent.com/17291050/91003069-0494e500-e5f0-11ea-9e25-238bc373d023.jpg)
![IMG_20200821_125024](https://user-images.githubusercontent.com/17291050/91003072-05c61200-e5f0-11ea-9186-11b9597635b5.jpg)

#### Is the bug present in both iOS and Android or in any one of them?
I have only tested in android so far.

#### Any other additional info which would help us debug the issue quicker.
It was working all fine 2weeks back.

**Comment by wachixx** [comment]
having the same issue. any solutions?

**Comment by wachixx** [comment]
copying all fonts from ../node_modules/react-native-vector-icons/Fonts  to ../android/app/src/main/assets/fonts fixed this for me

**Comment by hanykumar** [comment]
Hi @sjonchhe and @wachixx , you must be missing icons. Checkbox and Radio button is working fine.
Please follow https://github.com/oblador/react-native-vector-icons#android. Let us know if the issue still persists, with more details.

**Comment by mhmdalii** [comment]
any solution here ?

**Comment by mhmdalii** [comment]
> copying all fonts from ../node_modules/react-native-vector-icons/Fonts to ../android/app/src/main/assets/fonts fixed this for me

not working with me :(

**Comment by sjonchhe** [comment]
> copying all fonts from ../node_modules/react-native-vector-icons/Fonts to ../android/app/src/main/assets/fonts fixed this for me

this solved it finally

**Comment by wouterds** [comment]
Same issue on iOS, latest version of `native-base` & `react-native.

![Screenshot 2020-12-04 at 00 35 41](https://user-images.githubusercontent.com/1210628/101101351-a4d3b000-35c8-11eb-82f3-43ca3383df4e.jpg)

**Comment by wouterds** [comment]
From a first quick glance it looks like it's because of the 7.1 upgrade on `react-native-vector-icons`. If you paste the 7.0.0 fonts in the fonts folder of `native-base` it's fine. So this package should hard lock on 7.0.0 instead of ^7.0.0.

**Comment by hotaryuzaki** [comment]
i have same problem.
- i already tried copy /node_modules/react-native-vector-icons/Fonts to /android/app/src/main/assets/fonts
- i already tried copy /node_modules/react-native-vector-icons/Fonts to /node_modules/native-base/Fonts

nothing is work.
my problem is same, checkbox showing hyphen.

native-base: 2.15.2
expo-icons: 10.0.0

**Comment by hotaryuzaki** [comment]
> i have same problem.
> 
> * i already tried copy /node_modules/react-native-vector-icons/Fonts to /android/app/src/main/assets/fonts
> * i already tried copy /node_modules/react-native-vector-icons/Fonts to /node_modules/native-base/Fonts
> 
> nothing is work.
> my problem is same, checkbox showing hyphen.
> 
> native-base: 2.15.2
> expo-icons: 10.0.0

i solved the problem, i cannot explain why.
but wtat i do is change ionicons path:

```
Font.loadAsync({
      // NATIVE BASE DEPENDECIES
      // ...Ionicons.font,
      // Ionicons: require('@expo/vector-icons/build/vendor/react-native-vector-icons/Fonts/Ionicons.ttf'),
      Ionicons: require('native-base/Fonts/Ionicons.ttf'),
```

which I comment ("//") doesn't work, even if I check the font is there in expo/vector-icons folder

**Comment by clluiz** [comment]
I'm still having this problem. Any new solution?

**Comment by jaspalprajapati11** [comment]
Hi, I am facing the same problem. I tried copying all the fonts from  /node_modules/react-native-vector-icons/Fonts to /android/app/src/main/assets/fonts but it still doesn't work. 

Any solutions??
