### ISSUE TITLE
Change color of StatusBar

### ISSUE THREAD

**Issue by Deepankar01** [GeekyAnts/NativeBase#323]
Is there any way i can change the color of `StatusBar` in NativeBase

i wrote this and nothing changed 

```
<Header style={styles.header}>
                    <Container style={{flexDirection: 'row',}}>
                        <StatusBar
                            backgroundColor="blue"
                            barStyle="light-content"
                        />
                        <Navigator
                            initialRoute={{statusBarHidden: false}}
                            renderScene={(route, navigator) =>
                                <Container>
                                    <StatusBar hidden={route.statusBarHidden}/>
                                </Container>
                            }
                        />
                        <Image style={styles.headerIcon} source={images.Logo}>
                        </Image>

                    </Container>
                </Header>
```

**Comment by sankhadeeproy007** [comment]
'StatusBar' should ideally wrap the component in the topmost level.

**Comment by mmmoli** [comment]
Is there an example of this somewhere? Want to see some code.

**Comment by yossijacob** [comment]
Agree, not sure where am i supposed to put the StatusBar. if i put inside of content it works but only until the app returning from background. an example will be much appreciated.
In the react native docs they put it alongside the navigator but this does not work with native base.

from the react native docs

```
<View>
   <StatusBar
     backgroundColor="blue"
     barStyle="light-content"
   />
   <Navigator
     initialRoute={{statusBarHidden: true}}
     renderScene={(route, navigator) =>
       <View>
         <StatusBar hidden={route.statusBarHidden} />
         ...
       </View>
     }
   />
 </View>
```

**Comment by HyperSimon** [comment]
Is this problem solved? Is there any example? Why is this issue closed?

**Comment by PhiSpindler** [comment]
You could use the StatusBarManager as work-around.

```
import {NativeModules, processColor } from 'react-native';
const { StatusBarManager } = NativeModules;

export default class DiscoverScreen extends Component {
  componentDidMount() {
    StatusBarManager.setColor(processColor('#ff0000'), false);
  }
  render() {
    return ( ... );
  }
}
```

**Comment by jasonnathan** [comment]
@PhiSpindler `setColor` is not a function

**Comment by PhiSpindler** [comment]
oh ok, my bad - I only tested it on android, there it worked

**Comment by nacmonad** [comment]
Hey!  found a neat way to do this entirely with native-base components:

<Header androidStatusBarColor="#2c3e50" style={{display:'none'}}/>

**Comment by nacmonad** [comment]
Hey!  found a neat workaround/hack that you can implement inside any <Container>  component.  the statusbar is a prop of the Header component, but when you want to change statusbar and not show the header, simply : 
`<Header androidStatusBarColor="#2c3e50" style={{display:'none'}}/>`

**Comment by jacobo360** [comment]
Finally @nacmonad!!! Thanks!!

**Comment by prayasht** [comment]
Checking out the `Header` component [source](https://github.com/GeekyAnts/NativeBase/blob/master/src/basic/Header.js) it looks like it takes a `iosBarStyle` prop for iOS and `androidStatusBarColor ` for Android.

This works for me in iOS:
```javascript
<Header iosBarStyle="light-content"> </Header>
```

Hope that helps!

**Comment by Amin52J** [comment]
You can also simply import `StatusBar` from "react-native" module and put it inside the NativeBase `Header` component:

    import {StatusBar} from 'react-native';
    import {Container, Content, Header, Body, Title} from 'native-base';
    .
    .
    .
    export default class App extends React.Component {
      render() {
        return (
          <Container>
            <Header style={{backgroundColor:'#000'}}>
              <StatusBar barStyle="light-content"/>
              <Body>
                <Title style={{color:'#FFF'}}>My App</Title>
              </Body>
            </Header>
            <Content>
              //content of your app goes here
            </Content>
          </Container>
        );
      }
    }

**Comment by Minaghorbaani** [comment]
hi , how can i make my statusbar background gradient ?

**Comment by Abhishekgarg727** [comment]
Just put it as top element in Content, and make sure to` import {StatusBar} from 'react-native'`

 ```
 render() {
        return (
            <Container style={styles.Container}>

                <Content style={styles.Content}>
                    <View>
                        <StatusBar
                            backgroundColor="#ff1c1c"
                            barStyle="light-content"
                        />
                    </View>
                </Content>
          </Container>
        );
     }

             
```

**Comment by msmahesh91** [comment]
thank you so much @nacmonad

**Comment by shimatai** [comment]
> @PhiSpindler `setColor` is not a function

It works only in Android.

**Comment by harikrishna1213** [comment]
> Hey! found a neat workaround/hack that you can implement inside any native-base `<Container>` component. the statusbar is a prop of the Header component, but when you want to change statusbar and not show the header, simply :
> `<Header androidStatusBarColor="#2c3e50" style={{display:'none'}}/>`
it's working....!!! great !!!!

**Comment by ashwithags** [comment]
<Header iosBarStyle="light-content"> </Header> 

this changed the text color to white. but the background color remain unchanged

**Comment by kajeevan025** [comment]
<Header
        iosBarStyle="light-content"
        androidStatusBarColor="#2c3e50"
        style={{ backgroundColor: "#212B36" }}
      >
</Header>

This can be helpfull

**Comment by thanhluantl2304** [comment]
> You can also simply import `StatusBar` from "react-native" module and put it inside the NativeBase `Header` component:
> 
> ```
> import {StatusBar} from 'react-native';
> import {Container, Content, Header, Body, Title} from 'native-base';
> .
> .
> .
> export default class App extends React.Component {
>   render() {
>     return (
>       <Container>
>         <Header style={{backgroundColor:'#000'}}>
>           <StatusBar barStyle="light-content"/>
>           <Body>
>             <Title style={{color:'#FFF'}}>My App</Title>
>           </Body>
>         </Header>
>         <Content>
>           //content of your app goes here
>         </Content>
>       </Container>
>     );
>   }
> }
> ```

Perfect! I tested and run successfully! :D

**Comment by brownieboy** [comment]
I must have tried the solutions on every one of these comments, but none of them worked for me.  All I'm trying to do is get light coloured text for the status bar on iOS.  (I already get light text by default on Android).

Is it tied to some particular version of NativeBase or React Native?  I'm on React Native 0.59.1 and NativeBase 2.12.1.   I'm not using Expo.

**Comment by truongthanh1303** [comment]
> I must have tried the solutions on every one of these comments, but none of them worked for me. All I'm trying to do is get light coloured text for the status bar on iOS. (I already get light text by default on Android).
> 
> Is it tied to some particular version of NativeBase or React Native? I'm on React Native 0.59.1 and NativeBase 2.12.1. I'm not using Expo.
> 
> **Update**
> It's working for me now.
> 
> I upgraded to RN 0.61 and putting `<StatusBar barStyle="light-content"/>` inside the `<Header>` component did the trick.

Hi @brownieboy , I got the same issue with React Native 0.59.9, native-base 2.13.8. Do you have any ideas without upgrade the RN version?
Thanks,

**Comment by brownieboy** [comment]
> Hi @brownieboy , I got the same issue with React Native 0.59.9, native-base 2.13.8. Do you have any ideas without upgrade the RN version?

Sorry, no.

The RN 0.61 upgrade also fixed a lot of other problems that I was having, so it was well worth the effort.

**Comment by Rajan-Savaliya-spt** [comment]
import {StatusBar} from 'react-native';
import {Container, Content, Header, Body, Title} from 'native-base';
.
.
.
export default class App extends React.Component {
  render() {
    return (
      <Container>
        <Header style={{backgroundColor:'#000'}}>
          <StatusBar barStyle="light-content"/>
          <Body>
            <Title style={{color:'#FFF'}}>My App</Title>
          </Body>
        </Header>
        <Content>
          //content of your app goes here
        </Content>
      </Container>
    );
  }
}

this is work for me

**Comment by zoobibackups** [comment]
> Hey! found a neat workaround/hack that you can implement inside any native-base `<Container>` component. the statusbar is a prop of the Header component, but when you want to change statusbar and not show the header, simply :
> `<Header androidStatusBarColor="#2c3e50" style={{display:'none'}}/>`

thank. it worked for me. I was searching for the solution in react native for the last 2 weeks.
