### ISSUE TITLE
Native base error with postInstall

### ISSUE THREAD

**Issue by Bidhanchandra09** [GeekyAnts/NativeBase#3232]
[4/7] ⡀ native-base
error /home/user/CodeNative/Mobile%20App/node_modules/native-base: Command failed.
Exit code: 127
Command: node addEjectScript.js && opencollective-postinstall
Arguments: 
Directory: /home/user/CodeNative/Mobile%20App/node_modules/native-base
Output:
┌────────────────────────────────────────────────────────────────────────────────────────────┐
│ NativeBase 2.0 has been succesfully installed!                                             │
│ Run `node node_modules/native-base/ejectTheme.js` to copy over theme config and variables. │

**Comment by hanykumar** [comment]
Hi @Bidhanchandra09 , can you explain more with steps to reproduce?

**Comment by hanykumar** [comment]
Hi @Bidhanchandra09 , closing for now due to inactivity. Let us know in details if the issue still persists.

**Comment by arzazahrian** [comment]
hi @hanykumar i have the same issue the console is showing this.

error /Users/muarzazahrian/Documents/work/PFP/coe/PLAI/plai:rollout:dev/pruforce_app_id/node_modules/native-base: Command failed.
Exit code: 127
Command: node addEjectScript.js && opencollective-postinstall
Arguments: 
Directory: /Users/muarzazahrian/Documents/work/PFP/coe/PLAI/plai:rollout:dev/pruforce_app_id/node_modules/native-base
Output:
┌────────────────────────────────────────────────────────────────────────────────────────────┐
│ NativeBase 2.0 has been succesfully installed!                                             │
│ Run `node node_modules/native-base/ejectTheme.js` to copy over theme config and variables. │

im doing the yarn on my console. 

- node v20.15.1
- "react-native": "0.72.10",
