### ISSUE TITLE
iOS page flickers when different headers for the different page

### ISSUE THREAD

**Issue by bhaskardabhi** [GeekyAnts/NativeBase#3236]
My page bounces when i have different headers per page.

## I have gone through these following points

- [x] Check latest documentation: https://docs.nativebase.io/
- [x] Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x] Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [] Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [] For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- [] For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

## Issue Description

My scene bounces when i have different headers per scene. I have attached GIF below:

![](https://i.imgur.com/YsCxwTk.gif)

#### node, npm, react-native, react and native-base version, expo version if used, xcode version

"native-base": "^2.13.12",
"react": "16.11.0",
"react-native": "0.62.2",
"react-native-gesture-handler": "~1.6.0",
"react-native-reanimated": "~1.9.0",
"react-native-router-flux": "^4.2.0",

#### Steps to reproduce

Code like below:

App.js

```
    <Router>
        <Stack key="root">
            <Scene openDrawer={this.openDrawer} initial navBar={HomeHeader} key="home" component={Home} />}
            <Scene openDrawer={this.openDrawer} navBar={Header} key="profile" component={User} />
            <Scene openDrawer={this.openDrawer} navBar={Header} path="/support" key="support" component={Support} />
        </Stack>
    </Router>

```
HomeHeader:

```
    <HeaderBase>
    
                <Left>
                    <Button onPress={() => Actions.pop()} transparent>
                        <Icon name='arrow-back' />
                    </Button>
                </Left>
                <Body>
                    <Title onPress={() => Actions.support()}>HeaderBase</Title>
                </Body>
                <Right>
                    <Button transparent>
                        <Icon name='menu' />
                    </Button>
                </Right>
            </HeaderBase>
```

Header:

```
            <Left>
                    <Button onPress={() => Actions.pop()} transparent>
                        <Icon name='arrow-back' />
                    </Button>
                </Left>
                <Body>
                    <Title onPress={() => Actions.support()}>HeaderBase</Title>
                </Body>
                <Right>
                    <Button transparent>
                        <Icon name='menu' />
                    </Button>
                </Right>
            </HeaderBase>

```

If I change `<Scene openDrawer={this.openDrawer} initial navBar={HomeHeader} key="home" component={Home} />}` to `<Scene openDrawer={this.openDrawer} initial navBar={Header} key="home" component={Home} />}` (make header same for all scene) works.

Try to navigate between different scene and you will face the issue.

#### Is the bug present in both iOS and Android or in any one of them?

Only on iOS

**Comment by hanykumar** [comment]
Hi @bhaskardabhi , can you provide minimal code reproduction on snack?

**Comment by bhaskardabhi** [comment]
Sorry for late reply. I will provide the minimal code for the reproduction soon.
