### ISSUE TITLE
Tab with sliderbox images issue

### ISSUE THREAD

**Issue by MedElba** [GeekyAnts/NativeBase#3238]
## I have gone through these following points

- [x] Check latest documentation: https://docs.nativebase.io/
- [x] Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x] Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [x] Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [x] For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- [x] For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

## Issue Description

Hi, I'm using the tab component with, as child, an image sliderbox ( react-native-image-slider-box ). the problem  is that i can't slide horizontally the images because it switches tabs instead of images. 

Thanks!!!

#### react-native, react and native-base version
"react-native": "0.63.2",
"native-base": "2.13.14"
"react": "16.13.1"
"react-native-image-slider-box": "1.0.12"

#### Expected behaviour

If I touch the sliderbox it should slide images and not tabs. 

#### Actual behaviour

If I swipe on sliderbox, it doesn't slide images, but tabs instead.

#### Steps to reproduce

```
import React from 'react';
import {Tab, Tabs, Container} from 'native-base';
import {SliderBox} from 'react-native-image-slider-box';

export default function MyPage(props) {
  return (
    <Container>
      <Tabs>
        <Tab heading="Tab1">
          <Text>TabOne</Text>
        </Tab>
        <Tab heading="Tab2">
          <SliderBox
            images={props.image}
            sliderBoxHeight={350}
          />
        </Tab>
      </Tabs>
    </Container>
  );
}
```

#### Is the bug present in both iOS and Android or in any one of them?

I tried only on android.

#### Any other additional info which would help us debug the issue quicker.

I'm already using the sliderbox librarry in the project and I don't have other issues.

**Comment by hanykumar** [comment]
Hi @MedElba , you can lock Tabs from sliding. You can change tabs by clicking on Tab headings. Let us know if the issue still persists.

**Comment by MedElba** [comment]
Hi @hanykumar ! I don't want to lock tabs because I need the sliding approach, I need the rich to slide the images of the box, and if it is the last image and I try to slide to the right, then it should slide to the next tab, if it's the first Image and I try to slide to the left it should slide to the previous tab. Is it clear what I said? I tried on iOS and it works, the problem is only on Android.

Thanks!!

**Comment by gomezmark** [comment]
Im having same issues.
Im using this one https://github.com/archriss/react-native-snap-carousel

And I don't want to lock the tabs.

Thanks

**Comment by pmella16** [comment]
@gomezmark hi, you managed to solve this ?? @MedElba

**Comment by gomezmark** [comment]
@pmella16  sadly no, I locked the tab on every touch on the slider.

**Comment by MedElba** [comment]
Hi guys! Sorry for delay, I solved switching to this tab component that automatically handles this "touch priority"! https://github.com/satya164/react-native-tab-view
