### ISSUE TITLE
Tabs fail: JSON value '(1,1,1, ...)' of type NSMutableArray cannot be converted to BOOL 

### ISSUE THREAD

**Issue by iqorlobanov** [GeekyAnts/NativeBase#3239]
Hi everyone.
I'm trying to use Animated.View in Tabs renderTabBar param and getting this error

![Simulator Screen Shot - iPhone 11 - 2020-09-11 at 12 40 34](https://user-images.githubusercontent.com/3371179/92895688-c63f5880-f42c-11ea-83ad-2c68dde04d8f.png)

and this is my code

<img width="714" alt="Screen Shot 2020-09-11 at 12 40 56" src="https://user-images.githubusercontent.com/3371179/92895735-d2c3b100-f42c-11ea-8c03-4a575f840db2.png">

"react-native": "0.63.2"
"native-base": "^2.13.8"

Everything is working on "react-native": "0.61.5"

**Comment by hanykumar** [comment]
Hi @iqorlobanov , can you provide minimal code reproduction on snack for the same?

**Comment by ptdede** [comment]
I also experience this.

This is rendered perfectly okay
```js
<Tabs
  renderTabBar={props => (props && <ScrollableTab />)}
>
  <Tab heading="Tab 1">
    <View>
      <Text>Tab 1</Text>
    </View>
  </Tab>
  <Tab heading="Tab 2">
    <View>
      <Text>Tab 2</Text>
    </View>
  </Tab>
</Tabs>
```

I found out that if you're using a root view inside `renderTabBar`, you'll get some error.
Also, by passing `{...props}` to `ScrollableTab` is causing the error if you're using `<Animated.View>`.
example:

```js
<Tabs
  renderTabBar={props => (props && 
      <Animated.View>
        <ScrollableTab { ...props } />
      </Animated.View>
    )
  }
>
  <Tab heading="Tab 1">
    <View>
      <Text>Tab 1</Text>
    </View>
  </Tab>
  <Tab heading="Tab 2">
    <View>
      <Text>Tab 2</Text>
    </View>
  </Tab>
</Tabs>
```

**Comment by mj-iosdev** [comment]
I was facing the same issue with Animated.View

I wrapped it in `<> </> ` and it fixed the issue for me.

![Screenshot 2020-09-28 at 5 39 26 PM](https://user-images.githubusercontent.com/19156236/94430670-e8b5cd80-01b1-11eb-8470-ed8f728e3a34.png)

**Comment by iqorlobanov** [comment]
> @iqorlobanov
> 
> I was facing the same issue with Animated.View
> 
> I wrapped it in `<> </> ` and it fixed the issue for me.
> 
> ![Screenshot 2020-09-28 at 5 39 26 PM](https://user-images.githubusercontent.com/19156236/94430670-e8b5cd80-01b1-11eb-8470-ed8f728e3a34.png)

Thanks! It works :)
