### ISSUE TITLE
Picker in Android dropdown mode opens when it's already scrolled to the bottom

### ISSUE THREAD

**Issue by GuyDev1** [GeekyAnts/NativeBase#3249]
Hey,

This is relevant only for Android as IOS doesn't have an option to show a dropdown picker.

When I open a large list using NativeBase's picker in dropdown mode, the list is automatically scrolled
to the bottom, whereas I would expect it to open scrolled all the way to the top.

Is there anything to do regarding this issue?

Thanks

**Comment by shivrajkumar** [comment]
Picker in native-base is an implementation of RN picker, so it behaves as provided in RN
