### ISSUE TITLE
Full Height buttons

### ISSUE THREAD

**Issue by andreyluiz** [GeekyAnts/NativeBase#325]
Hey guys.

I have the following structure:

```
<Grid>
  <Row size={50}>
    <Col>
      <Image .../>
    </Col>
  </Row>
  <Row size={50}>
    <Col>
      <Row size={50}>
        <Col size={50}>
          <Button large .../>
        </Col>
        <Col size={50}>
          <Button large .../>
        </Col>
      </Row>
      <Row size={50}>
        <Col size={50}>
          <Button large .../>
        </Col>
        <Col size={50}>
          <Button large .../>
        </Col>
      </Row>
    </Col>
  </Row>
</Grid>
```

The grid structure is pretty straightforward, but I have an issue with the buttons. I need them to get the entire height of the closer Row. 

What seems to happen is that the Row fits to the Button height. I need the parent Rows to take the full screen height and the buttons to follow the same behavior.

![app](https://cloud.githubusercontent.com/assets/1965897/20653237/69b277c4-b4f1-11e6-9a48-01567bd3902e.png)

In the example image I need the buttons to fill the entire marked space.

Is there any way to do that?

Thank you.

**Comment by sankhadeeproy007** [comment]
Can you please try using style `flex: 1` with the rows and buttons and check?

**Comment by andreyluiz** [comment]
Nope. `flex: 1` does nothing. Another tip?

**Comment by andreyluiz** [comment]
Fixed. I was able to do by using the default Views and setting the flex-box sizes according to my grid structure.
