### ISSUE TITLE
Uncaught TypeError: Cannot read property 'style' of undefined。这个是什么问题

### ISSUE THREAD

**Issue by fewoy** [GeekyAnts/NativeBase#3252]
![image](https://user-images.githubusercontent.com/14038970/93544895-ae6a5600-f991-11ea-997d-dec358afad6a.png)
![image](https://user-images.githubusercontent.com/14038970/93544914-b924eb00-f991-11ea-85e6-1387e67ad05e.png)

**Comment by hanykumar** [comment]
HI @fewoy , please provide minimal code reproduction with more details like 
- which platform iOS, android or web
- versions

**Comment by idanavr** [comment]
I also get the same error but in another file.
The error happends only on web, on android it works normally.
```
"react-native": "0.62.2",
"expo": "38.0.9",
"native-base": "2.13.14",
```
![image](https://user-images.githubusercontent.com/28144178/94129630-453c8400-fe64-11ea-86a7-e7cc6293d6e0.png)

Do you know what should I do to fix it?

**Comment by saravanatm** [comment]
Getting this error in web
