### ISSUE TITLE
Long text in picker not wrapping to next line in android and the selected text doesn't wrap in either android/ios 

### ISSUE THREAD

**Issue by Aayushi1301** [GeekyAnts/NativeBase#3256]
## I have gone through these following points

- [x] Check latest documentation: https://docs.nativebase.io/
- [x] Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x] Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [] Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [] For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- [] For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

## Issue Description

I am using Picker from React https://docs.nativebase.io/Components.html#picker-def-headref but I have long text in the list which gets truncated on both ios and android after selection whereas on the picker it gets truncated on android. I have tried flexWrap, flexShrink but they don't help. I have latest react native and native base versions.

#### Expected behaviour
Text should wrap to new line in case of lengthy text

#### Actual behaviour
Text gets truncated

#### Steps to reproduce
I created a simple Picker with two picker options from documentation:
import React, { Component } from "react";
import { Container, Header, Content, Picker, Form } from "native-base";

export default class PickerExample extends Component {
  constructor(props) {
    super(props);
    this.state = {
      selected: "key1"
    };
  }
  onValueChange(value: string) {
    this.setState({
      selected: value
    });
  }
  render() {
    return (
      <Container>
        <Header />
        <Content>
          <Form>
            <Picker
              note
              mode="dropdown"
              selectedValue={this.state.selected}
              onValueChange={this.onValueChange.bind(this)}
            >
              <Picker.Item label="Wallet" value="key0" />
              <Picker.Item label="LongTextLongTextLongTextLongTextLongTextLongTextLongTextLongTextLongTextLongTextLongTextLongTextLongText" value="key1" />
            </Picker>
          </Form>
        </Content>
      </Container>
    );
  }
}

Screenshots:-
Picker on ios(Text gets wrapped to next line as expected)
![image](https://user-images.githubusercontent.com/39982141/93759441-cfe46f80-fc27-11ea-894c-cd5256d87fe8.png)

Selected value on ios(Text gets truncated)
![image](https://user-images.githubusercontent.com/39982141/93759586-1934bf00-fc28-11ea-9d02-71ddab573bbf.png)

Picker on android(Text gets truncated)
![image](https://user-images.githubusercontent.com/39982141/93760283-53529080-fc29-11ea-88fe-b24c3b9b3704.png)

Selected value on android(Text gets truncated)
![image](https://user-images.githubusercontent.com/39982141/93760265-4b92ec00-fc29-11ea-8488-241f21312d17.png)

#### Is the bug present in both iOS and Android or in any one of them?
both

**Comment by hanykumar** [comment]
Hi @Aayushi1301 , Text is supposed to be truncated on both iOS and android after selection whereas on the picker it gets truncated on android because its Native behavior is inherited from 'react-native'.
