### ISSUE TITLE
Close ActionSheet on click off on iOS

### ISSUE THREAD

**Issue by Aryk** [GeekyAnts/NativeBase#3259]
I'm trying to have it so that when I click off an ActionSheet, it will close.

I was able to get it working on Android only with `cancelButtonIndex: -1`, but on iOS it does not work.

Is there a way to do it? Can't seem to find it in the documentation.

Native Base: 2.13.8

**Comment by hanykumar** [comment]
Hi @Aryk , Please update to latest Native-Base v2.13.14 and let us know if the issue still persists.

**Comment by skrcode** [comment]
@Aryk Did you get this to work? I had the same problem and upgrading to 2.13.14 did not help.

**Comment by Aryk** [comment]
@skrcode  - 2.13.14 fixes it for me, but it completely screwed up my headers as already documented here (https://github.com/GeekyAnts/NativeBase/issues/3095), so I have to wait until that is fixed.

**Comment by hanykumar** [comment]
Hi @Aryk , can you provide minimal code reproduction with more description?
