### ISSUE TITLE
Dependency of react-native-easy-grid not updated

### ISSUE THREAD

**Issue by tzyhhaur** [GeekyAnts/NativeBase#326]
The dependency states react-native-easy-grid@0.1.5, thus will have the ReactNativePropRegistry issue.

Should be updated to the latest 0.1.7

**Comment by tzyhhaur** [comment]
#327

**Comment by ujwal-setlur** [comment]
Yes, please update the dependency to 0.1.7 I am currently doing it manually, but it breaks the workflow of npm install. Can you please update and upload a new package?

**Comment by ujwal-setlur** [comment]
My workaround is to install react-native-easy-grid first to get the latest, then native-base and then delete the react-native-easy-grid (0.1.5) under node_modules/native-base/node_modules.

But this is less than ideal :-)

**Comment by SupriyaKalghatgi** [comment]
Fixed with latest release [0.5.18](https://github.com/GeekyAnts/NativeBase/releases/tag/v0.5.18)
