### ISSUE TITLE
Radio - unselected state not rendering 

### ISSUE THREAD

**Issue by myousufq** [GeekyAnts/NativeBase#3260]
## Issue Description

Some reason unselected state of Radio is not rendering in Android after selecting new item. 

"react-native": "^0.63.2",
"native-base": "^2.13.14",

#### Actual behaviour
![Screenshot_20200925-125544](https://user-images.githubusercontent.com/163169/94215265-2f949080-ff30-11ea-8daf-626698fd49ff.jpg)

**Comment by myousufq** [comment]
Line 63 `this.props.color` in Radio.js is undefined causing for this issue.

**Comment by R4DIC4L** [comment]
Would have been better to default the color to black so that missing rendering icon doesn't happen. But good to know that the color property should be set.
