### ISSUE TITLE
Input component with maxLength value set to Number.MAX_VALUE

### ISSUE THREAD

**Issue by IrmantasVaracinskas** [GeekyAnts/NativeBase#3263]
## I have gone through these following points

- [x] Check latest documentation: https://docs.nativebase.io/
- [x] Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x] Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [x] Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [x] For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- [x] For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

#### node, npm, react-native, react and native-base version, expo version if used, xcode version
node v12.18.1
npm 6.14.5
react-native 0.63
react 16.13.1
native-base current master branch
xcode 12
#### Expected behaviour
cannot input any text
#### Actual behaviour
can input text
#### Steps to reproduce
In iOS simulator create <Input> component with maxLength set to Number.MAX_VALUE. Funny thing is that it's working correctly with real device.  
Currently working around this problem by setting maxLength to Number.MAX_SAFE_INTEGER

#### Is the bug present in both iOS and Android or in any one of them?
iOS

**Comment by hanykumar** [comment]
Hi @IrmantasVaracinskas , this is a native behavior of `TextInput` from `'react-native'.` so `Input` inherits props from `TextInput` .
