### ISSUE TITLE
Dark mode theme for Android and iOS

### ISSUE THREAD

**Issue by Aryk** [GeekyAnts/NativeBase#3265]
Is there a dark mode theme for Android and iOS already in NativeBase?

I'm on 2.13.8 but I could move up to 2.13.14 if needed.

I have not seen in the documentation or in the library itself and kind of "Dark Mode" themes that we can link to.

Or is it only for RC 3?

**Comment by hanykumar** [comment]
Hi @Aryk , as of now there is no dark mode theme available for Android or iOS in NativeBase.
