### ISSUE TITLE
Textarea Typescript fields should be optional

### ISSUE THREAD

**Issue by Aryk** [GeekyAnts/NativeBase#3268]
I wrote a comment on this merge:

https://github.com/GeekyAnts/NativeBase/pull/2756

I'm using 2.13.8 (2.13.14 also has this issue). For `Textarea`, type definitions are currently:

```ts
		interface Textarea extends ReactNative.TextInputProps, Testable {
			rowSpan: number;
			bordered: boolean;
			underline: boolean;
			/**
             * Disables inputting data.
             */
			disabled?: boolean;
		}
```

But should be:

```ts
		interface Textarea extends ReactNative.TextInputProps, Testable {
			rowSpan?: number;
			bordered?: boolean;
			underline?: boolean;
			/**
             * Disables inputting data.
             */
			disabled?: boolean;
		}
```

They should not be **required** to be entered...am I right?

**Comment by ARKEOLOGIST** [comment]
I'm not sure about rowspan, but I don't think bordered and underline are necessary.

**Comment by Aryk** [comment]
Thanks for making the PR, pretty sure rowspan is not required as my app is performing fine with it.

**Comment by ARKEOLOGIST** [comment]
You mean without it?
