### ISSUE TITLE
Toast prevent from pressing button event if it's hidden

### ISSUE THREAD

**Issue by MarcHbb** [GeekyAnts/NativeBase#3271]
I have button positionned at the bottom, and when show the toast, and then hide it, I can't press on the Button.
With element inspector I found that event if Toast is hidden, it's still one the screen. I tried to set an elevation for the button higher than the toast, not working 

Any ideas ?

Tried on snack, there's no problem, but on IOS simulator, it's not working 

https://snack.expo.io/@simbasnack/nativebase?&preview=true&platform=ios&iframeId=fr2udn44xn&theme=light

**Comment by hanykumar** [comment]
Hi, @MarcHbb , we found no such issue. We are able to press `Button` whether `Toast` is visible or not on iOS simulator as well. Can you explain more and provide few more details like version?

<img width="890" alt="Screenshot 2020-10-12 at 10 21 56 AM" src="https://user-images.githubusercontent.com/15860517/95706645-ff115e00-0c74-11eb-87db-90ccc765f310.png">

**Comment by crava-logico-srl** [comment]
It's happening to me as well.
The Toast disappears, but it stills cover the area where it used to be.

**Comment by shivrajkumar** [comment]
@crava-logico-srl Can you share a code snippet that causes the issue for you. As we couldn't reproduce this from the earlier expo code.
