### ISSUE TITLE
Error: currentlyFocusedField is deprecated 

### ISSUE THREAD

**Issue by fengyouchao** [GeekyAnts/NativeBase#3273]
ReactNative version: 0.63.2
Expo version: 39.0.0
NativeBase version: 2.13.14
Test Platform: iOS 

 When an `Input` in `Content` component **gets focus** and the **keyboard pops up**, an error message will appear: `currentlyFocusedField is deprecated and will be removed in a future release. Use currentlyFocusedInput`

I think it should be caused by `@codler/react-native-keyboard-aware-scroll-view`

https://github.com/GeekyAnts/NativeBase/blob/0315c117959bf19eae0f7c2a85e7faafa982f6e9/src/basic/Content.js#L5

**Comment by djimenezlegend** [comment]
![Screen Shot 2020-10-14 at 11 48 38](https://user-images.githubusercontent.com/60449824/96005807-3584df80-0e13-11eb-875e-18675c09a567.png)


Same error, on `<Input></Input>`

**Comment by mbeech** [comment]
I've just created a PR to fix this in NativeBase, in the meantime if you add
`"@codler/react-native-keyboard-aware-scroll-view": "1.0.1",` in your own package.json it'll override the NB version that includes this fix

**Comment by Macht59** [comment]
Any update on this?

**Comment by tudiantuan** [comment]
> I've just created a PR to fix this in NativeBase, in the meantime if you add
> `"@codler/react-native-keyboard-aware-scroll-view": "1.0.1",` in your own package.json it'll override the NB version that includes this fix
I yarn add @codler/react-native-keyboard-aware-scroll-view@1.0.1 but android is crash  when screen use Input

**Comment by devplaceaccount** [comment]
Any update on this?

**Comment by pierol** [comment]
Same problem here:
ReactNative version: 0.63.2
Expo version: 39.0.0
NativeBase version: 2.13.15
Test Platform: iOS


`
.....
import {
  Container,
  Form,
  Item,
  Input,
  Button,
  Icon
} from 'native-base';
....



<Input
                placeholder="Utente"
                autoCorrect={false}
                autoCapitalize="none"
                onChangeText={this.onUsernameChange.bind(this)}
                value={this.props.username}
              />`

The error:

currentlyFocusedField is deprecated and will be removed in a future release. Use currentlyFocusedInput

**Comment by shivrajkumar** [comment]
Fixed in the latest verion
