### ISSUE TITLE
 Support for the experimental syntax 'jsx' isn't currently enabled

### ISSUE THREAD

**Issue by piccinnigius** [GeekyAnts/NativeBase#3275]
## I have gone through these following points

- [x] Check latest documentation: https://docs.nativebase.io/
- [x] Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x] Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [x] Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [] For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- [] For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

## Issue Description

i followed the web configuration, is working on android but can't compile on react native web.
I got this error:
yarn run react-app-rewired start
```
./node_modules/native-base/src/basic/Accordion.js
SyntaxError: D:\dev\jumple\testnative2\node_modules\native-base\src\basic\Accordion.js: Support for the experimental syntax 'jsx' isn't currently enabled (34:7):

  32 | 
  33 |     return (
> 34 |       <View
     |       ^
  35 |         style={[
  36 |           // eslint-disable-next-line no-use-before-define   
  37 |           styles.defaultHeader,

Add @babel/plugin-transform-react-jsx (https://git.io/vb4yd) to the 
'plugins' section of your Babel config to enable transformation.   
```

then i added " '@babel/plugin-transform-react-jsx'" to my config-overrides but doesn't work.

#### node, npm, react-native, react and native-base version, expo version if used, xcode version
node --version v14.13.1
npm --version 6.14.8
yarn -v 1.22.0
react: 16.13.1
react-native: 0.63.3
native-base: last github (30 mins ago)

#### Steps to reproduce
follow the react native (not expo)  + web tutorial

#### Is the bug present in both iOS and Android or in any one of them?
android: no
web: yes
ios: not tested
#### Any other additional info which would help us debug the issue quicker.

###Important

If you want your issue to be looked at quicker, attach a snack reproducible with your issue. Makes it easier for us!
config-overrides.js
```js
const path = require( 'path' );
const {
  override,
  addWebpackAlias,
  babelInclude,
  addBabelPlugins
} = require( 'customize-cra' );

module.exports = override(
  addWebpackAlias( {
    'react-native/Libraries/Renderer/shims/ReactNativePropRegistry': 'react-native-web/dist/modules/ReactNativePropRegistry',
    'react-native': 'react-native-web'
  } ),
  addBabelPlugins(
    '@babel/plugin-proposal-class-properties',
    '@babel/plugin-transform-react-jsx'
  ),
  babelInclude( [
    path.resolve( 'src' ),
    path.resolve( 'node_modules/native-base-shoutem-theme' ),
    path.resolve( 'node_modules/react-navigation' ),
    path.resolve( 'node_modules/react-native-easy-grid' ),
    path.resolve( 'node_modules/react-native-drawer' ),
    path.resolve( 'node_modules/react-native-safe-area-view' ),
    path.resolve( 'node_modules/react-native-vector-icons' ),
    path.resolve( 'node_modules/react-native-keyboard-aware-scroll-view' ),
    path.resolve( 'node_modules/react-native-web' ),
    path.resolve( 'node_modules/react-native-tab-view' ),
    path.resolve( 'node_modules/static-container' ),
    path.resolve( 'node_modules/@codler/react-native-keyboard-aware-scroll-view' )
  ] )
);
```

```json
{
  "name": "testnative2",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "web": "react-app-rewired start",
    "dev_menu": "adb shell input keyevent 82",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "@react-native-community/masked-view": "^0.1.10",
    "@react-navigation/native": "^5.7.6",
    "@react-navigation/stack": "^5.9.3",
    "native-base": "https://github.com/fdkitlui/NativeBase.git",
    "proxy-polyfill": "^0.3.2",
    "react": "16.13.1",
    "react-dom": "^16.13.1",
    "react-native": "0.63.3",
    "react-native-gesture-handler": "^1.8.0",
    "react-native-reanimated": "^1.13.1",
    "react-native-safe-area-context": "^3.1.8",
    "react-native-screens": "^2.11.0",
    "react-native-web": "^0.14.0",
    "recoil": "https://github.com/facebookexperimental/Recoil.git#nightly"
  },
  "devDependencies": {
    "@babel/core": "^7.8.4",
    "@babel/plugin-proposal-class-properties": "^7.10.4",
    "@babel/plugin-transform-react-jsx": "^7.10.4",
    "@babel/runtime": "^7.8.4",
    "@react-native-community/eslint-config": "^1.1.0",
    "customize-cra": "^1.0.0",
    "eslint": "^6.5.1",
    "metro-react-native-babel-preset": "^0.59.0",
    "react-app-rewired": "^2.1.6",
    "react-scripts": "^3.4.3",
    "react-test-renderer": "16.13.1"
  },
  "jest": {
    "preset": "react-native"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}


```

thanks so much in advance

**Comment by piccinnigius** [comment]
replacing `addBabelPlugins` with `addExternalBabelPlugins` i have a new error: 
```

./node_modules/native-base/src/basic/Actionsheet.js
Attempted import error: 'ActionSheetIOS' is not exported from 'react-native'.
```

**Comment by Azrideus** [comment]
your current config file wont work at all,  because you are not using the customized config
replace 
` "start": "react-native start",`
with 
` "start": "react-app-rewired start",`

**Comment by danilrafiqi** [comment]
any update ?

**Comment by execptionerror** [comment]
[[Already Solved] SyntaxError: Support for the experimental syntax ‘jsx’ isn’t currently enabled](https://exerror.com/syntaxerror-support-for-the-experimental-syntax-jsx-isnt-currently-enabled/)
