### ISSUE TITLE
Unknown named module: 'react/lib/ReactNativePropRegistry'

### ISSUE THREAD

**Issue by justfede** [GeekyAnts/NativeBase#328]
Hey guys!

Im getting this error with the following example: http://nativebase.io/docs/v0.5.13/components#anatomy

My package.json:

  "dependencies": {
    "native-base": "^0.5.16",
    "react": "15.4.1",
    "react-native": "0.38.0"
  },

**Comment by uniquarkD** [comment]
https://github.com/GeekyAnts/NativeBase/issues/307

**Comment by RocWangv** [comment]
Also happened in 
   ` "react": "15.3.2",`
   ` "react-native": "0.37.0"`

**Comment by cyuxlif** [comment]
same problem

**Comment by RocWangv** [comment]
fixed by change 
`import ReactNativePropRegistry from 'react-native/Libraries/Renderer/src/renderers/native/ReactNativePropRegistry';`
to
`import { ReactNativePropRegistry } from 'react-native';`
in node_modules/react-native-easy-grid/Utils/computeProps.js

**Comment by smhatre59** [comment]
As @RocWangv pointed out correctly replacing the following code in react-native-easy-grid module fixed the issue for me:
// var ReactNativePropRegistry = require('react/lib/ReactNativePropRegistry');
import { ReactNativePropRegistry } from 'react-native';

**Comment by SupriyaKalghatgi** [comment]
Fixed with latest release [0.5.18](https://github.com/GeekyAnts/NativeBase/releases/tag/v0.5.18)

**Comment by mauron85** [comment]
This fix seems not working with react-native 0.35
```
  "dependencies": {
    "native-base": "^0.5.18",
    "react": "^15.3.1",
    "react-native": "^0.35.0",
    "react-native-maps": "^0.11.0",
    "react-native-mauron85-background-geolocation": "^0.2.0-alpha.5"
  }
```

**Comment by 20matan** [comment]
netiher with
"depenencies": {
    "native-base": "^0.5.18",
    "react": "15.3.1",
    "react-native": "^0.34.1"
}

**Comment by mauron85** [comment]
But it really works with:

```
  "dependencies": {
    "native-base": "^0.5.18",
    "react": "^15.4.1",
    "react-native": "^0.38.0",
    "react-native-maps": "^0.11.0",
    "react-native-mauron85-background-geolocation": "^0.2.0-alpha.5"
  }
```

**Comment by SupriyaKalghatgi** [comment]
@mauron85 @20matan  If you want to work with RN < 0.38 then you should go for NB < 0.5.16
For RN >= 0.38, NB 0.5.18 is compatible
