### ISSUE TITLE
Blank screen displayed when clicked on the datepicker for iOS 14

### ISSUE THREAD

**Issue by bhaskardabhi** [GeekyAnts/NativeBase#3281]
## I have gone through these following points

- [*] Check latest documentation: https://docs.nativebase.io/
- [*] Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [] Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [] Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [] For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- [] For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

## Issue Description

In project we are using Nativebase datepicker, It works fine on Android. In iOS, when clicked on Datepicker then it goes blank and it looks weird. I am not able to scroll the date or month or year.

Please check the attached screenshot:

![alt text](https://i.imgur.com/FG24yCC.png)

#### node, npm, react-native, react and native-base version, expo version if used, xcode version
node: v12.9.0
npm: 6.10.2
react-native-cli: 2.0.1
react-native: 0.62.2
native-base: "^2.13.12"
react: "16.11.0"

#### Is the bug present in both iOS and Android or in any one of them?

Only iOS

**Comment by keremoge** [comment]
Hi, can u look up to this issue;

**Comment by keremoge** [comment]
Can you look up to this issue; https://github.com/facebook/react-native/issues/30067

**Comment by muhammadrofiq** [comment]
you can solve this by adding this code, above your AppDelegate -> didFinishLaunchingWithOptions function

`
if (@available(iOS 14, *)) {
  UIDatePicker *picker = [UIDatePicker appearance];
  picker.preferredDatePickerStyle = UIDatePickerStyleWheels;
}
`

**Comment by abdymm** [comment]
@bhaskardabh you can add this on infoplist to force Light theme 
```
<key>UIUserInterfaceStyle</key>
	<string>Light</string>
```

**Comment by ajithes111** [comment]
+1

**Comment by atroudi** [comment]
+1
