### ISSUE TITLE
[TypeScript] Content does not has proper props. Types imported from "react-native-keyboard-aware-scroll-view" rather than "@codler/react-native-keyboard-aware-scroll-view"

### ISSUE THREAD

**Issue by hinsxd** [GeekyAnts/NativeBase#3282]
## I have gone through these following points

- [x] Check latest documentation: https://docs.nativebase.io/
- [x] Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x] Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [x] Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [x] For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- [x] For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

## Issue Description
`<Content>` component only has limited types. For example, 
```tsx
<Content
  style={styles.content}
  ref={contentRef}
  onScroll={() => { // IDE saids 'onScroll' does not exist
    Alert.alert('scrolled'); // But this is called
  }}
>
...
</Content>
```

After investigation, the corresponding type declaration is 
```ts
interface Content extends Testable, KeyboardAwareScrollViewProps {}
```
where 
```ts
import { KeyboardAwareScrollViewProps } from "react-native-keyboard-aware-scroll-view";
```

However, it shows in packages.json
```json
"dependencies": {
    "@codler/react-native-keyboard-aware-scroll-view": "1.0.0",
}
```

#### node, npm, react-native, react and native-base version, expo version if used, xcode version
node: v14.9.0
yarn 1.22.5
react: 16.13.1
nativebase: 2.13.14
expo: 3.28.1
xcode: 11.6
#### Expected behaviour
Although not documented, `<Content>` should inherit all `KeyboardAwareScrollViewProps` from `"@codler/react-native-keyboard-aware-scroll-view"`
#### Actual behaviour
It has the following props only
![スクリーンショット 2020-10-24 午前3 49 52](https://user-images.githubusercontent.com/8574962/97047760-02c5ae80-15ac-11eb-8ea0-0577b0a78165.png)

#### Is the bug present in both iOS and Android or in any one of them?
IDE with Typescipt

**Comment by darron1217** [comment]
Any updates on this issue?
I hope the PR to be merged soon
