### ISSUE TITLE
Native base Footer Tab Button click not working

### ISSUE THREAD

**Issue by monicse09ku** [GeekyAnts/NativeBase#3285]
`react-native: 0.63.3`
`native-base: 2.13.14`

I am using react-native 0.63.3 and native base 2.13.14. Footer Tab Button onPress is not working. Previously I solved it by downgrading to 2.13.8. But after upgrading my react-native version, it stopped working. Then I have tried 2.13.14. How can I solve this.

N.B. yarn was used to install everything.

    <Footer style={pagestyles.footerStyle}>
        <FooterTab  style={{ backgroundColor: GLOBAL.TERTIARY_COLOR }}>
            <Button vertical onPress={() => Actions.home()}>
                <Icon name="home" style={pagestyles.footerIcon}/>
                <Text style={pagestyles.bottomText}>{I18n.t("footer.home")}</Text>
            </Button>
            <Button vertical onPress={() => alert('working')}>
                <Icon name="home" style={pagestyles.footerIcon}/>
                <Text style={pagestyles.bottomText}>{I18n.t("footer.home")}</Text>
            </Button>
        </FooterTab>
    </Footer>`

**Comment by cyrus25** [comment]
Hi @monicse09ku  , can you provide snack for minimal reproduction for the same?

**Comment by monicse09ku** [comment]
hello @cyrus25 , thanks for your reply, I faced that issue then and had to solve it using custom buttons and design, a lot of other people also faced the same issue then, using mentioned versions. Sorry cant provide snack now.
