### ISSUE TITLE
How to center a card inside of container?

### ISSUE THREAD

**Issue by Deboracgs** [GeekyAnts/NativeBase#3291]
## I have gone through these following points

- [x] Check latest documentation: https://docs.nativebase.io/
- [x] Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [] Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [] Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [] For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- [] For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

## Issue Description

When I put justify-content: center or align-items: center, the card background is lost

![Screenshot_1605550617](https://user-images.githubusercontent.com/12396210/99291616-01e50d00-2838-11eb-9d83-aff7960f0504.png)

```
const styles = StyleSheet.create({
  contentContainer: {
    //justifyContent: 'center', 
    //flex: 1,
    paddingHorizontal: "20%"
  },
  title: {
    fontWeight: "bold",
    marginBottom: 8
  },
  subtitle: {
    marginBottom: 8
  }
})
```

```

    <Container>
      <Header title="Setup" />
      <Content style={styles.container} contentContainerStyle={styles.contentContainer}>
     

        <Card>
<Row>
  <Col>
    <Text style={styles.title}>PIN</Text>
    <Text style={styles.subtitle}>Do you want to login with a PIN?</Text>
    <Row>
      <Col>
        <Button text="YES" onPress={() => setDoWantToUsePin(true)} />
      </Col>
      <Col>
        <Button typeStyle="white" text="NO"  onPress={() => setDoWantToUsePin(false)}  />
      </Col>
    </Row>
  </Col>
  <Col>
  </Col>
</Row>
</Card>
      </Content>
    </Container>
```

**Comment by henrineken** [comment]
This gonna work

```
  **contentContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },**
```
