### ISSUE TITLE
Disable prop for button doesn't change color

### ISSUE THREAD

**Issue by zaid0077** [GeekyAnts/NativeBase#3296]
I want to use the disable prop in my button component. It works fine, it change the color to grey. But when i add background color to the button, the disable prop works but it doesn't change the color to grey.  

                    {/* <Button style={styles.mainBtn}>
                        <Text style={styles.btnText}>Submit</Text>
                    </Button> */}
// styles
    mainBtn: {
        backgroundColor: '#0C1248',
        borderRadius: 20
    },
    btnText: {
        color: 'white',
        fontSize: 18,
    },

**Comment by shivrajkumar** [comment]
@zaid0077 That's how it is supposed to work. If you specify a background color, it will take that as the background color in priority.
If you want the button to be grey when disabled and applied color when not disabled, then you can pass the background color conditionally.
Let us know if you need further help with this.

**Comment by jimbo23** [comment]
facing the same issue

**Comment by gomo** [comment]
@jimbo23 

Use `isDisabled` instead of `disable` props. And,  Put the string directly under the `Button` without using `Text`. 

```jsx
<Button isDisabled={!email || !password} >Sign In</Button>
```

**Comment by MrVico** [comment]
None of you address the original issue which is that having the button disabled overrides the custom background color if we pass one to the button.

i.e. We set the button's background color to red, if the button is disabled we still expect the background color to be red but it's not the case anymore.

**Comment by jingcheng16** [comment]
Have same issue here. `_disabled` props doesn't work

**Comment by yushanwebdev** [comment]
same issue here

**Comment by Irfanwani** [comment]
@jingcheng16 did you found any solution?

> Have same issue here. `_disabled` props doesn't work

**Comment by jingcheng16** [comment]
> @jingcheng16 did you found any solution?
> 
> > Have same issue here. `_disabled` props doesn't work

@Irfanwani Yes I solved it. Try `isDisabled`, let me know if it works.

**Comment by Irfanwani** [comment]
@jingcheng16 you are right, buttons are dimmed a bit when disabled which is pretty nice but I just wanted some more customisations. Anyway, going with the default behavior now.
