### ISSUE TITLE
NativeBase project is dead?

### ISSUE THREAD

**Issue by alexandrtovmach** [GeekyAnts/NativeBase#3297]
Hello community!
I'm worrying about the current state of the project and would like to ask maintainers for their opinion. I'm faced with two issues that already solved with PRs two months ago, but still not released. Feels like nobody cares about it (it happens in open source), and I would like to know:
1. Who is responsible for making new releases?
2. Why nobody chats with the community to provide some estimates or updates? 
3. What is the current status of development of this project, any plans/roadmaps?

Related: #3250, #3230
CC: @akhil-geekyants @sankhadeeproy007 @SupriyaKalghatgi @shivrajkumar

**Comment by sankhadeeproy007** [comment]
Hey, @AleksandarDev apologies for the delay.
The team is working on a newer version of NativeBase, it is based on styled-system and will have a ChakraUI like API.
Regarding the plans for the current version, we're mostly depending on community support/PR's for the issues as we do not have devs working actively on the project.
We will try to be more regular with our releases in the future. Thanks for your patience.

**Comment by alexandrtovmach** [comment]
Thanks for answering @sankhadeeproy007
>we're mostly depending on community support/PR's for the issues

Totally makes sense, but as I mentioned "community" did PRs, that's already merged to `master` but still not release to NPM. Community haven't enough rights to do that, and we need some help from maintainers. For sure setting up CI/CD with autodeploy and autorelease will be much better.

**Comment by alexandrtovmach** [comment]
BTW: you used wrong mention :upside_down_face:

**Comment by sankhadeeproy007** [comment]
Yes, we're setting up a system as we speak.
Expect quicker releases in the future @alexandrtovmach 😄

**Comment by sanketsahu** [comment]
Hey, sorry for being quiet here. We are bringing in @cyrus25 and @shivrajkumar to maintain the v2.x and another team is making some great progress for the v3.0 alpha release.

**Comment by hmolotsi** [comment]
@sankhadeeproy007 and @sanketsahu Do you have an estimate on when the PRs referenced will be merged?

**Comment by shivrajkumar** [comment]
@hmolotsi #3230 has been already merged and just released today.
And we are looking into #3250

**Comment by hmolotsi** [comment]
Thanks @shivrajkumar - What about #3218 ?

**Comment by MohammadAzimi** [comment]
@hmolotsi I think this one also has a high priority to merge and release; because we just can't run the project on `web`. https://github.com/GeekyAnts/NativeBase/pull/3280
