### ISSUE TITLE
Style label for <Input>

### ISSUE THREAD

**Issue by oldo** [GeekyAnts/NativeBase#330]
Hi there,
I'd like to style the label for the `<Input>` component so that the labels are all justified to the left. By default they are all justified: center.

<img width="487" alt="screen shot 2016-11-29 at 19 39 16" src="https://cloud.githubusercontent.com/assets/4557648/20702395/beb8de72-b66b-11e6-8cf7-c873b531bb59.png">

I'm sure it must be easy but I'm not sure how to do this... Any suggestions?
Thanks :-)

**Comment by SupriyaKalghatgi** [comment]
@oldo This has been onto the development.
To be released soon with the rewrite of NativeBase

**Comment by oldo** [comment]
Thanks @SupriyaKalghatgi 
Is there an estimate on when it might be released?

**Comment by SupriyaKalghatgi** [comment]
@oldo I can say may be in a week

**Comment by trevor-coleman** [comment]
Will this also allow us to style the label and placeholder separately?

Currently changing `inputColorPlaceholder` also changes the colour of the label text.

**Comment by sankhadeeproy007** [comment]
@oldo you can now add `inlineLabelAlign` for this. Accepted values are `flex-start`, `center` and `flex-end`. Defaults to `center`.
![screen shot 2016-12-28 at 5 43 28 pm](https://cloud.githubusercontent.com/assets/10998047/21521697/649309f6-cd25-11e6-910b-216bcc1ffca5.png)

**Comment by oldo** [comment]
Excellent! Thank you :-)
