### ISSUE TITLE
Update @codler/react-native-keyboard-aware-scroll-view to version 1.0.1

### ISSUE THREAD

**Issue by edinpuzic** [GeekyAnts/NativeBase#3303]
When the keyboard is open console is throwing out an error `currentlyFocusedField is deprecated and will be removed in a future release. Use currentlyFocusedInput`

Native Base is using 1.0.0 version for `@codler/react-native-keyboard-aware-scroll-view` To resolve this issue it needs to update to the 1.0.1 version.
```
└─┬ native-base@2.13.15
  └── @codler/react-native-keyboard-aware-scroll-view@1.0.0
```

I create PR for this issue #https://github.com/GeekyAnts/NativeBase/pull/3305

**Comment by shivrajkumar** [comment]
PR for this has been merged and release in v2.15.0
