### ISSUE TITLE
RNCAndroidDialogPicker" was not found in the UIManager after upgrade to nativebase 2.13.15

### ISSUE THREAD

**Issue by alfianwahid** [GeekyAnts/NativeBase#3307]
## I have gone through these following points

- [x] Check latest documentation: https://docs.nativebase.io/
- [x] Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x] Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [] Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [] For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- [] For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

#### node, npm, react-native, react and native-base version, expo version if used, xcode version

"node":"v12.14.1",
"npm":"6.14.9"
"native-base": "^2.13.15",
"react": "16.13.1",
"react-native": "0.63.3",

#### Steps to reproduce
- Upgrade to latest nativebase 2.13.15
- `watchman watch-del-all`
- `gradlew clean`
- `react-native start --reset-cache`
- `react-native run-android`

#### Is the bug present in both iOS and Android or in any one of them?
only tested in Android, don't know in IOS.

#### Any other additional info which would help us debug the issue quicker.
![image](https://user-images.githubusercontent.com/2808896/102010075-3a600400-3d6e-11eb-8314-2b9d041fa5e8.png)

**Comment by fredrickabayie** [comment]
Try the below:

- [ ] `yarn add @react-native-community/picker`

- [ ] `cd android && ./gradlew clean && cd ..`

- [ ] `react-native run-android`

This worked for me.

**Comment by alfianwahid** [comment]
> Try the below:
> 
> * [x]  `yarn add @react-native-community/picker`
> * [x]  `cd android && ./gradlew clean && cd ..`
> * [x]  `react-native run-android`
> 
> This worked for me.

ok it's worked, 

but `@react-native-community/picker` has been deprecated, and moved to `@react-native-picker/picker`

**Comment by fredrickabayie** [comment]
It seems native-base latest release 2.13.15 included the deprecated dependency. Maybe changing that to `@react-native-picker/picker` might fix the issue.

<img width="864" alt="Screenshot 2020-12-14 at 15 52 55" src="https://user-images.githubusercontent.com/9385800/102102685-05ae8400-3e24-11eb-9edc-96fb4e985b56.png">

**Comment by humbertocruz** [comment]
It's not working with Expo, I guess this lib is using some native code and it's broke Expo Apps. My package was "native-base":"^2.13.0" and with this "^" yarn install 2.15

**Comment by raphacmartin** [comment]
It seems to be solved here: https://github.com/GeekyAnts/NativeBase/commit/0552d3f2fff15ba50dad357c32dfc212a5002ea2

Installing the latest 2.15 version updated the picker repository

**Comment by GSolari79** [comment]
Still facing this issue. Does anyone come up with a solution?

**Comment by Birhanu2050** [comment]
Linking react-native picker like this solve my issues. 
sudo react-native link  @react-native-picker/picker

**Comment by JamesC159** [comment]
I am having this issue on RN 0.66.2. important @react-native-picker/picker does not solve this issuee

**Comment by joix97b** [comment]
In my case I am using "react-native-picker-select": "^8.0.4" and it was not working until I added "@react-native-picker/picker": "^2.2.1" also by 'yarn add ..."

**Comment by pranay202** [comment]
@joix97b I have tried what you have said, but still its not working for me!

**Comment by rveruna** [comment]
I had the same error. I used 
`cd ios && rm -rf Podfile.lock ./Pods && cd ..`
and 
`cd ios && pod install && cd ..`
to clean up ios and 
`cd android && ./gradlew clean && cd ..`
to clean up android. 

this way android worked fine and ios only gave me the wheel with items, but when you clicked on any item, nothing happened. I am not sure why there is functionality missing on ios or is im missing something.

Then I spoted comment from @joix97b (thanks)

> In my case I am using "react-native-picker-select": "^8.0.4" and it was not working until I added "@react-native-picker/picker": "^2.2.1" also by 'yarn add ..."

Therefore, on top of `yarn add @react-native-picker/picker` I also added the react-native-picker-select with `yarn add  react-native-picker-select` and now both android and ios work fine 

![image](https://user-images.githubusercontent.com/15161568/185923466-9402899f-d3fc-496e-9251-b13c09d80880.png)

![image](https://user-images.githubusercontent.com/15161568/185921437-0c5ccce1-eb68-4ca4-bebf-1246a8636d2f.png)

```import * as React from 'react'; 
import Picker from 'react-native-picker-select';

const CreatePost: React.FC = () => {
  return (
    <Picker
      onValueChange={(value) => console.log(value)}
      items={[
        { label: 'Football', value: 'football' },
        { label: 'Baseball', value: 'baseball' },
        { label: 'Hockey', value: 'hockey' },
      ]}
    />
  );
};

export default CreatePost;```

**Comment by ShaunKo** [comment]
Same issue here. I am using React-native 0.70.5, expo 47 bare workflow. Solved this problem by adding command below.
`yarn add @react-native-picker/picker` 
iOS : `cd ios && pod install`
android: `Sync project with Gradle Files`

**Comment by wesvh** [comment]
@ShaunKo , i have the same env, with React-native 0.70.5 and expo 47

My project is on android ...

You can make more explicit how to do this?

**Comment by ShaunKoooo** [comment]
@wesvh Hi. In my case. First, I do `yarn add @react-native-picker/picker` in your project root. Second, in your Android Studio press the 'Sync Project with Gradle File' button. Second step will update the Android Studio project model to match the contents of the Gradle build file. Rerun the project. All good !! Hope this work for you.

**Comment by sky2030** [comment]
it's not solved even by adding this package @react-native-picker/picker
