### ISSUE TITLE
Customizing FooterTab

### ISSUE THREAD

**Issue by josephsanglee** [GeekyAnts/NativeBase#331]
Can't seem to get customize the FooterTab properties?
`
<Footer>
  <FooterTab
    tabActiveBgColor="#4fb5f9"
    tabBarActiveTextColor="#2d83bc"
    tabBarTextColor="#6b6b6b"
  >
    <Button>
      Inventory
      <Icon name="ios-list-box-outline" />
    </Button>
    <Button>
      Survey
      <Icon name="ios-camera-outline" />
    </Button>
    <Button>
      Chat
      <Icon name="ios-chatboxes-outline" />
    </Button>
  </FooterTab>
</Footer>
`

**Comment by SupriyaKalghatgi** [comment]
@josephsanglee Did you check for it in the docs?
[Customize FooterTabs](http://nativebase.io/docs/v0.5.13/customize#themeFooterTabs)
