### ISSUE TITLE
Cannot find module 'react-native-keyboard-aware-scroll-view' or its corresponding type declarations.

### ISSUE THREAD

**Issue by v0lna** [GeekyAnts/NativeBase#3315]
Inside file "index.d.ts" import of `import { KeyboardAwareScrollViewProps } from "react-native-keyboard-aware-scroll-view";`
dependency typescript throw error **Cannot find module 'react-native-keyboard-aware-scroll-view' or its corresponding type declarations.ts(2307)**
When i try to change it to `	import { KeyboardAwareScrollViewProps } from "@codler/react-native-keyboard-aware-scroll-view";` everything seems like ok

**Comment by toscanoGithub** [comment]
October 2021 stiil have the same issue !!!
How do you fixed this issue?
