### ISSUE TITLE
Can't customize FooterTab

### ISSUE THREAD

**Issue by josephsanglee** [GeekyAnts/NativeBase#332]
Can't seem to customize the FooterTab properties.

```<Footer>
  <FooterTab
    tabActiveBgColor="#4fb5f9"
    tabBarActiveTextColor="#2d83bc"
    tabBarTextColor="#6b6b6b"
  >
    <Button>
      Inventory
      <Icon name="ios-list-box-outline" />
    </Button>
    <Button>
      Survey
      <Icon name="ios-camera-outline" />
    </Button>
    <Button>
      Chat
      <Icon name="ios-chatboxes-outline" />
    </Button>
  </FooterTab>
```

**Comment by josephsanglee** [comment]
`<Footer>
  <FooterTab
    tabActiveBgColor="#4fb5f9"
    tabBarActiveTextColor="#2d83bc"
    tabBarTextColor="#6b6b6b"
  >
    <Button onPress={() => this.setState({ content: 'inventory', title: 'Inventory' })}>
      Inventory
      <Icon name="ios-list-box-outline" />
    </Button>
    <Button onPress={() => this.goToSurvey()}>
      Survey
      <Icon name="ios-camera-outline" />
    </Button>
    <Button onPress={() => this.setState({ content: 'chat', title: 'Chat' })}>
      Chat
      <Icon name="ios-chatboxes-outline" />
    </Button>
  </FooterTab>
</Footer>`

**Comment by SupriyaKalghatgi** [comment]
@josephsanglee Seems like you dd'nt go through docs before customizing
You can go through procedure to [set up](http://nativebase.io/docs/v0.5.13/customize) your theme file.
Check this to customize [Customize FooterTabs](http://nativebase.io/docs/v0.5.13/customize#themeFooterTabs)

**Comment by josephsanglee** [comment]
Besides customization, even with the default settings, the active tab doesn't seem to be changing text/background color?

**Comment by SupriyaKalghatgi** [comment]
@josephsanglee This is the default FooterTabs of NativeBase
![anatomy](https://cloud.githubusercontent.com/assets/13464885/20785238/28726eb4-b7c5-11e6-8985-49b4e1e5c4e3.png)

You can find this in [NativeBase-KitchenSink](https://github.com/GeekyAnts/NativeBase-KitchenSink)

**Comment by DaniloMeritocracy** [comment]
@SupriyaKalghatgi is there a way to customize the background color of the whole bar? For example, in android is blue, but all my app is red, so...

**Comment by SupriyaKalghatgi** [comment]
@DaniloMeritocracy Nope, no such feature as of now.

You can anyway add this to [discussion](https://github.com/GeekyAnts/NativeBase/issues/38)

**Comment by SupriyaKalghatgi** [comment]
@DaniloMeritocracy Check into `light.js` file for [FooterTab](https://github.com/GeekyAnts/NativeBase/blob/master/Components/Themes/light.js#L107)
