### ISSUE TITLE
NativeBase - issue with Android StatusBar color/transprancy with Header component, icons on Android

### ISSUE THREAD

**Issue by b-tiwari** [GeekyAnts/NativeBase#3323]
## I have gone through these following points

- [x] Check latest documentation: https://docs.nativebase.io/
- [x] Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x] Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [x] Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [ ] For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/ - 
- [ ] For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/ - N/A

## Issue Description

Starting on another RN project (with `RN init` command, not with EXPO), this time planning to try NativeBase as UI library. 
I tried [this example from NB's documents for Header-> Transparent](https://docs.nativebase.io/Components.html#header-transparent-headref). In its documentation, Android screenshot is as below, in this the Android's StatusBar seem to be somehow getting same color as app container.

![NativeBase-header-transparent-example](https://user-images.githubusercontent.com/13605214/102852661-56098100-43e4-11eb-8c6c-5290a82cbf27.png)

#### node, npm, react-native, react and native-base version, expo version if used, xcode version
```
    "native-base": "^2.15.0",
    "react": "16.13.1",
    "react-native": "0.63.4"
```

![libVerions](https://user-images.githubusercontent.com/13605214/102852511-0aef6e00-43e4-11eb-91d6-de361cac7468.png)

### Expected behaviour
Expecting to see the app behavior same as in the example from NB's docs.

### Actual behaviour
The app is working as expected for iOS.

- However on Android, not getting the same expected results for status bar. Unlike the docs example screenshot, the status-bar on Android is not going transparent or the same color as App/Header background color for me.

- Icons also not working in Android

![NB-Android-Issues](https://user-images.githubusercontent.com/13605214/102852818-ada7ec80-43e4-11eb-9f27-0f84c4d03114.png)

#### Steps to reproduce
Below is my App component code (only component I have so far)

```
import React from 'react';
import { Button, Container, Header, Title, Content, Icon, Left, Right, Text, Body } from "native-base";
import { React$Node } from './../TypesAndInterfaces/AppTypes';

/**
 * @name App
 * @description App Component function
 */
const App: () => React$Node = () => {

  return (
    <Container style={{ backgroundColor: '#9FA8DA' }}>
      <Header transparent>
        <Left>
          <Button transparent>
            <Icon name="arrow-back" />
          </Button>
        </Left>
        <Body>
          <Title>Transparent</Title>
        </Body>
        <Right>
          <Button transparent>
            <Text>Cancel</Text>
          </Button>
        </Right>
      </Header>
      <Content padder>
        <Text>
          Header with transparent prop
        </Text>
      </Content>
    </Container>
  );
};

export default App;

```

### Is the bug present in both iOS and Android or in any one of them?
Only Android

### Any other additional info which would help us debug the issue quicker.
Also, tried setting Statusbar's color to the app's color through code, but that didn't work as well:

```
...
...
const App: () => React$Node = () => {

  React.useEffect(() => {
    if (Platform.OS === 'android') {
      StatusBar.setBackgroundColor('#9FA8DA');
    }
  }, []);

  return (
    <Container style={{ backgroundColor: '#9FA8DA' }}>
      <Header transparent>

...
...
```

**Comment by b-tiwari** [comment]
I further tried removing the Header from the App component ( with the code to set StatusBar color in `useEffect`), and with no Header component, the StatusBar color works as expected

![AppWithNoHeader](https://user-images.githubusercontent.com/13605214/102855653-aaaffa80-43ea-11eb-8ff3-f7307b9a2162.png)


and below is behavior when not setting StatusBar background color via code, this is also working as expected I believe

![AppWithNoHeader-2](https://user-images.githubusercontent.com/13605214/102855764-d7fca880-43ea-11eb-82cb-657c49bfac51.png)

So, the issue seem to happen when <Header> component is added to app

**Comment by myungkyum-kim** [comment]
I have same issue, too, thanks for reporting

**Comment by b-tiwari** [comment]
sorry for late reply, got pulled into another issue
thanks @myungkyum-kim , you were right, it was some issue with 'react-native-vector-icons',

did `yarn add 'react-native-vector-icons'` (won't have to do `yarn link` as I am using RN@0.63)
this however didn't resolve the icons issue right away, had to follow the first two steps of [this fix suggested here](https://stackoverflow.com/a/57311262)

that fixed the issue on Android, but then the icons broke on iOS :-)

`pod install` and then below code finally fixed icons on iOS as well

```
import MaterialIcons from 'react-native-vector-icons/MaterialIcons';
MaterialIcons.loadFont();
```

![IconsLoading](https://user-images.githubusercontent.com/13605214/103097164-02f22280-45cc-11eb-9178-26bd4b099f0b.png)
