### ISSUE TITLE
native-base Icon showing as a different language Symbols

### ISSUE THREAD

**Issue by nick22985** [GeekyAnts/NativeBase#3327]
Native Base Icon not working properly. 

```
 <Drawer.Screen name="My Account" component={MyAccount} options={{drawerIcon: ({focused, color, size}) => (<Icon name="people" style={{fontSize: size, color: color}}/>),}} />
 ```
![Screenshot_20201224-185438_CookingApp](https://user-images.githubusercontent.com/43774713/103090026-9a428e80-463b-11eb-8058-f4c9819c1ec0.jpg)

**Comment by cyrus25** [comment]
Hi @nick22985, please refer [here](https://github.com/oblador/react-native-vector-icons/issues/1294), as this is a vector icon issue.
