### ISSUE TITLE
RenderRow not working in examples (render empty rows)

### ISSUE THREAD

**Issue by kirkryan** [GeekyAnts/NativeBase#3338]
## I have gone through these following points

- [x] Check latest documentation: https://docs.nativebase.io/
- [x] Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x] Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [x] Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [x] For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- [x] For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

## Issue Description
When following the example tutorial (https://github.com/GeekyAnts/native-base-docs/blob/master/docs/components/card/DynamicCard.md)  for the Card and CardItem components, using renderRow results in blank rows being rendered. Rendering the exact same card manually embedded without renderRow results in the cards showing correctly

If I embed the CardItem without RenderRow function (to ensure correct formatting):

Code without RenderRow:
```
return (
    <Container>
      <Header />
      <Content>
        <Card dataArray={items}>
          <CardItem button>
            <Icon active name="logo-facebook" />
            <Text>Hello!</Text>
            <Right>
              <Icon name="arrow-forward" style={{color: '#999'}} />
            </Right>
          </CardItem>
        </Card>
      </Content>
    </Container>
  );
};
```

Simulator:
![image](https://user-images.githubusercontent.com/18603029/103455856-a340f900-4ce8-11eb-8097-bc3d4d431c99.png)

However, when using renderRow and using the same card template:

Code using renderRow:
...
```
const items = [
    {
      iconName: 'logo-googleplus',
      text: 'Google Plus',
    },
    {
      iconName: 'logo-facebook',
      text: 'Facebook',
    },
    {
      iconName: 'logo-twitter',
      text: 'Twitter',
    },
    {
      iconName: 'logo-reddit',
      text: 'Reddit',
    },
    {
      iconName: 'logo-linkedin',
      text: 'LinkedIn',
    },
  ];
...
return (
    <Container>
      <Header />
      <Content>
        <Card
          dataArray={items}
          renderRow={(item) => (
            <CardItem button>
              <Icon active name={item.iconName} />
              <Text>{item.text}</Text>
              <Right>
                <Icon name="arrow-forward" style={{color: '#999'}} />
              </Right>
            </CardItem>
          )}
        />
      </Content>
    </Container>
  );
};
```

Simulator:
![image](https://user-images.githubusercontent.com/18603029/103455899-fca92800-4ce8-11eb-9783-cf6adce2a216.png)

#### node, npm, react-native, react and native-base version, expo version if used, xcode version
node: 15.5.0
react-native: 0.63.4
native-base: 2.15.0

#### Expected behaviour
The card will display for all items specified in the array

#### Actual behaviour
The cards are being rendered, but are blank. The icon is showing in the <Right> component though

#### Steps to reproduce

See above

#### Is the bug present in both iOS and Android or in any one of them?

Confirmed in iOS 14.3

#### Any other additional info which would help us debug the issue quicker.

###Important

If you want your issue to be looked at quicker, attach a snack reproducible with your issue. Makes it easier for us!

**Comment by jatinggrwl** [comment]
replace 
`item. iconName and item,text with item.item, iconName and item.item.text`
