### ISSUE TITLE
Tabs header background transparent not working.

### ISSUE THREAD

**Issue by yerycs** [GeekyAnts/NativeBase#3348]
Tabs header background color transparent is not working.
It shows background grey even I set as transparent.

```
<Tabs style={{backgroundColor: 'transparent'}}>
  <Tab>
    heading={
      <TabHeading style={{ backgroundColor: colors.transparent }} tabStyle={{ backgroundColor: colors.transparent }}>
        <Text>Sector </Text>
      </TabHeading>
    }
  </Tab>
</Tabs>
```
I cannot find solution in document and existing issues.

**Comment by danielmoreno510** [comment]
<Tabs tabContainerStyle={{ backgroundColor: 'transparent' }}>
  <Tab  heading={<TabHeading style={{ backgroundColor: 'transparent' }}><Text>Sector</Text></TabHeading>}>
  </Tab>
</Tabs>
