### ISSUE TITLE
 Invalid prop tabStyle

### ISSUE THREAD

**Issue by ReactNativ** [GeekyAnts/NativeBase#3358]
Warning: Failed prop type: Invalid prop `tabStyle` of type `array` supplied to `DefaultTabBar`, expected `object`.
    in DefaultTabBar (at connectStyle.js:392)
    in Styled(DefaultTabBar) (at Tabs/index.js:131)

**Comment by darron1217** [comment]
I'm experiencing same issue after upgrading from `2.13.14` to `2.15.2`(latest)

**Comment by adamsea** [comment]
Same issue here -- upgraded from `2.13.14` -> `2.15.2`. I tried fixing the prop as follows:
```
-                        tabStyle={[
-                            tabStyles.tabStyle,
-                            tabStyles.leftBorderStyle,
-                            page !== 1 && tabStyles.rightBorderStyle
-                        ]}
+                        tabStyle={{
+                            ...tabStyles.tabStyle,
+                            ...tabStyles.leftBorderStyle,
+                            ...(page !== 1 && tabStyles.rightBorderStyle)
+                        }}
```

But still get the warning

**Comment by HeyShinner** [comment]
version `2.13.14` still has this warning

**Comment by ikismail** [comment]
> I'm experiencing same issue after upgrading from `2.13.14` to `2.15.2`(latest)

+1

**Comment by nabilarifdaaa** [comment]
any update for this issue?

**Comment by GSolari79** [comment]
Me too, any update on this one?

**Comment by Rubench0** [comment]
greetings, I have the same problem, any solution?

**Comment by nmarchais** [comment]
Same here...
Do you need more details to solve the issue?

**Comment by Cookizza** [comment]
Same issue here..

**Comment by darron1217** [comment]
I'm using `2.13.14` currently because every updates are unstable.
Maintainers seems busy with preparing v3 so I decided to stay at current version...

**Comment by mike-zarandona** [comment]
The culprit seems to be the fact that `props` are being spread onto the `<DefaultTabBar {...props} />` in `native-base/src/basic/Tabs/index.js:131`.

**Comment by canberkardic** [comment]
Same here

**Comment by Mwild2** [comment]
Following. v2.15.2

**Comment by Robsonpca01** [comment]
Experiencing the same here.

**Comment by dmsouza** [comment]
Same here

**Comment by mohity777** [comment]
Same

**Comment by yu-ichiro** [comment]
I think I found the problem.


at [src/basic/Tabs/DefaultTabBar.js:25](https://github.com/GeekyAnts/NativeBase/blob/02f5b23e19b3db594e5b5828f336fdac32cfb1fc/src/basic/Tabs/DefaultTabBar.js#L25), 
tabStyle's type is set like

```javascript
    tabStyle: PropTypes.shape({
      style: PropTypes.any,
    }),
```

but actually its always passed as arrays, ([src/basic/Tabs/index.js:298](https://github.com/GeekyAnts/NativeBase/blob/02f5b23e19b3db594e5b5828f336fdac32cfb1fc/src/basic/Tabs/index.js#L298))

and index-accessed in DefaultTabBar too ([src/basic/Tabs/DefaultTabBar.js](https://github.com/GeekyAnts/NativeBase/blob/02f5b23e19b3db594e5b5828f336fdac32cfb1fc/src/basic/Tabs/DefaultTabBar.js#L168))

so I think the PropType definition is wrong, but I couldn't just monkey-patch the propTypes static attribute of DefaultTabBar (it still gave errors), so I worked around it by defining a custom `renderTabBar` function that hooks and replaces `tabStyle` with an Array that doesn't look like one and putting it in Tabs 

```jsx
import { Tab, Tabs, DefaultTabBar } from "native-base";

const renderTabBar = (props) => {
  props.tabStyle = Object.create(props.tabStyle);
  return <DefaultTabBar {...props} />;
};

const SomeFC = () => (
/* ... */
    <Tabs renderTabBar={renderTabBar}>
        <Tab tabStyle={{ /* ... */ }}>
            /* ... */
        </Tab>
        <Tab tabStyle={{ /* ... */ }}>
            /* ... */
        </Tab>        
    </Tabs>
/* ... */
)
```

for typescript users (like me)

```tsx
declare module "native-base" {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  export class DefaultTabBar extends React.Component<any, any> {}
}

import { Tab, Tabs, DefaultTabBar } from "native-base";

// eslint-disable-next-line @typescript-eslint/no-explicit-any
const renderTabBar = (props: any) => {
  props.tabStyle = Object.create(props.tabStyle);
  // eslint-disable-next-line @typescript-eslint/ban-ts-comment
  // @ts-ignore
  return <DefaultTabBar {...props} />;
};

const SomeFC = () => (
/* ... */
    <Tabs renderTabBar={renderTabBar}>
        <Tab tabStyle={{ /* ... */ }}>
            /* ... */
        </Tab>
        <Tab tabStyle={{ /* ... */ }}>
            /* ... */
        </Tab>        
    </Tabs>
/* ... */
)
```

**Comment by viet-nv** [comment]
Amazing, good job @yu-ichiro !!!

**Comment by khoabuidev** [comment]
Perfect @yu-ichiro, many thanks!

**Comment by sammiepls** [comment]
@yu-ichiro it worked! But when I try to pass in a style prop, then I'll get the same warning. I have to hard-code the style to remove the tabs' border (https://stackoverflow.com/questions/51466904/how-to-remove-the-border-of-native-base-tabs) and doing that seems to negate the workaround. 

```
const renderTabBar = (props) => {
      props.tabStyle = Object.create(props.tabStyle);
      props.style = Object.create({ borderBottomWidth: 0 });
  return <ScrollableTab {...props}  />
};
```

Will remove the bottom border, but gives the earlier `tabStyle` warning and this warning:

> Warning: Failed prop type: Invalid prop `style` of type `array` supplied to `ScrollableTabBar`, expected `object`.

**Comment by yu-ichiro** [comment]
@sammiepls 
Hi, please don't use me/github as stackoverflow. I could give you hints like

1. The component you're using in the `renderTabBar` (remember, its render-"TabBar" function and not render-"Tab" function) is not a derived class of TabBar (DefaultTabBar) so that might be the problem

2. Did you try the other answers in the question you linked? fixing it through tabContainerStyle seems more legitimate than trying to use a different component for Tab to me

but this is not how things work here, and I won't answer any specific setup questions like this here at github. Please use question answer websites like above.

**Comment by sammiepls** [comment]
I'm sorry @yu-ichiro, apologies. I have tried the answers in the link, it solve one of the issues but not the prop type warning. I will take your advice and post to SO.

**Comment by timotismjntk** [comment]
yes, it worked thanks @yu-ichiro

**Comment by mechanizzed** [comment]
Thanks @yu-ichiro

**Comment by ELiHimself** [comment]
Had same problem, thank you @yu-ichiro

**Comment by monikamateeva** [comment]
I had the same issue.
I am using native-base version 2.15.2. 
The solution by @yu-ichiro worked for me. Thank you!

**Comment by prawee** [comment]
version 2.15.2 still has this warning

**Comment by aaratishah** [comment]
you saved me @yu-ichiro Thanks a lot.

**Comment by Ruzen1** [comment]
@sammiepls 

Hey Sammie, 

Sorry for sudden mention. I am facing the same problem.
Have you solved it and would you mind sharing if solved please?
