### ISSUE TITLE
Cannot find module 'react/lib/ReactNativePropRegistry

### ISSUE THREAD

**Issue by thundenilla** [GeekyAnts/NativeBase#336]
I've been trying for the past 2 days with this. 

1. I update my react, reactnative, nativebase to latest version.
Error that i got is ::: RTCWebsocket (android) and cannot found react-native/..../nativebase/button.js(ios)

2. I revert back my version changes to what originally they are
` "native-base": "0.5.13",
    "react": "15.3.2",
    "react-native": "0.32.0",`
but i'm getting error of Cannot find module ..../ReactNativePropRegistry.

3. I did most of the recommended solutions in the git. Someone PLEASEE HELP!

**Comment by sankhadeeproy007** [comment]
Could you try creating a new project with react-native init and then do a fresh install of native-base?

**Comment by thundenilla** [comment]
so basically start my project from scratch? @sankhadeeproy007

**Comment by SupriyaKalghatgi** [comment]
@thundenilla `ReactNativePropRegistry` issue has been fixed and works both on iOS and Android
To make sure we are on same page, please follow these steps to upgrade
In your `package.json`
  ```
    "native-base": "0.5.18",
    "react": "15.4.1",
    "react-native": "0.38.0",
```
- Delete `node_modules`, `android`, `ios`
- `npm install`
- `react-native upgrade`
- `react-native android`
- `react-native link`

**Comment by thundenilla** [comment]
@SupriyaKalghatgi so basically i did what you listed above, now im getting another error (TypeError: undefined is not a function(evaluating 'RCTWebSocketModule.connect(url..........)

**Comment by SupriyaKalghatgi** [comment]
@thundenilla Are you on Xcode 8?

**Comment by thundenilla** [comment]
yup 8 @SupriyaKalghatgi

**Comment by SupriyaKalghatgi** [comment]
Please check [this](https://github.com/facebook/react-native/issues/8584#issuecomment-236366222)

**Comment by dorthwein** [comment]
I'll add that this issue is also faced when trying to integrate with react-native-web.  See issue #120.  

Any way we can move away from referencing this directly etc...?

**Comment by dorthwein** [comment]
I've got a solution for this if we just extract the ReactNative PropRegistry and put it in your Utils folder it will prevent this from happening again down the line etc... and also allows this to work with react-native-web.

Is this something y'all would be ok with?   We also would need to do the same thing with your react-native-easy-grid

**Comment by SupriyaKalghatgi** [comment]
@thundenilla Is NativeBase up and running for you?

**Comment by SupriyaKalghatgi** [comment]
@dorthwein Yes we are looking for long-term solution to this

**Comment by thundenilla** [comment]
@SupriyaKalghatgi yeah its working now. but something else pop up. but its fine, must be something related to my genymotion.

**Comment by SupriyaKalghatgi** [comment]
@thundenilla Sounds good!
Could you please close the issue, if it has been solved

**Comment by DaniloMeritocracy** [comment]
@SupriyaKalghatgi can you check this out? https://github.com/GeekyAnts/NativeBase-KitchenSink/issues/11

It's related to this. Thank you!

**Comment by SeonaeShin** [comment]
@SupriyaKalghatgi  finally "react-native": "0.38.0" works! thanks.
