### ISSUE TITLE
Badge without text not work in FooterTab

### ISSUE THREAD

**Issue by klinkov** [GeekyAnts/NativeBase#337]
Hi

This code work well
`<Button transparent onPress={() => alert('Messages')}>
                            <Badge>2</Badge>
                            Messages
                            <Icon name={Platform.OS === 'ios' ? 'ios-chatboxes' : 'md-chatboxes'}/>
</Button>`

but this code display nothing

`<Button transparent onPress={() => alert('Messages')}>
                            <Badge>2</Badge>
                            <Icon name={Platform.OS === 'ios' ? 'ios-chatboxes' : 'md-chatboxes'}/>
</Button>`

"native-base": "0.5.18",
"react": "15.4.1",
"react-native": "0.38.0",

**Comment by sankhadeeproy007** [comment]
Will be fixed with next update. Use from master if required urgently.
