### ISSUE TITLE
NativeBase components does not work with Animated API anymore

### ISSUE THREAD

**Issue by hsjoberg** [GeekyAnts/NativeBase#3372]
## Issue Description

Since 2.15.0 and above, NativeBase components cannot be animated with the react-native [`Animated`](https://reactnative.dev/docs/next/animated) API anymore.

#### Expected behaviour

Animations created by the [`Animated`](https://reactnative.dev/docs/next/animated) API should work as normal.

#### Actual behaviour

Animation never starts. No visual effect occurs.

#### Steps to reproduce

Consider the following example:

```JSX
import React, { useEffect, useRef } from 'react';
import { Animated } from 'react-native';
import { Text } from "native-base";
const AnimatedText = Animated.createAnimatedComponent(Text);

const App = () => {
  const fadeAnim = useRef(new Animated.Value(0)).current;

  useEffect(() => {
    Animated.timing(fadeAnim, {
      toValue: 1,
      duration: 5000,
      useNativeDriver: false,
    }).start();
  }, []);

  return (
    <AnimatedText style={{
      marginTop: 100,
      opacity: fadeAnim,
    }}
    >
      Test
    </AnimatedText>
  );
};

export default App;
```

The text should fade in, but it does not on >= 2.15.0.
The last working version is 2.13.15.

#### Is the bug present in both iOS and Android or in any one of them?

The issue is present in iOS, Android and web builds.

#### Any other additional info which would help us debug the issue quicker.

I made some research and tracked down this commit as the one causing the regression: cd6dd9ce541b6e34178270c91613de108bb0a66e

**Comment by henrineken** [comment]
You need to import the Text component from just one lib

**Comment by hsjoberg** [comment]
@henrineken My bad, the example code had an error. The issue is still real though.

**Comment by davwheat** [comment]
What happens if it's wrapped in a `<Animated.View>` instead?
