### ISSUE TITLE
Tabs titles overlap each other.

### ISSUE THREAD

**Issue by evacao1225** [GeekyAnts/NativeBase#3376]
## I have gone through these following points

- [] Check latest documentation: https://docs.nativebase.io/
- [] Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [] Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [] Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [] For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- [] For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

#### node, npm, react-native, react and native-base version, expo version if used, xcode version
React-native: 0.59.9
native-base: 2.15.0
xcode: 11.6
npm: 6.14.7
node: v14.8.0
#### Expected behaviour
No overlap
#### Actual behaviour
<img width="341" alt="image" src="https://user-images.githubusercontent.com/18162948/104673639-18ff8880-571d-11eb-8b55-ee2403d43966.png">

#### Steps to reproduce

```
// render Tabs
// tabs is an array received from API response the first time, then they will be cached locally for next use.
// this issue only occurs when reading tabs from API response.

let { tabs=[] } = this.props;

let Tabs = tabs.map(tab => {
  return (
    <Tab heading={tab.name}>
       <MyView />
    </Tab>
  );
});

return (
  <Container>
    <Tabs
         renderTabBar={
            () =>
             <ScrollableTab />
          }
          onChangeTab={this.handleTabChange}
     >
          {Tabs}
    </Tabs>
  </Container>
);
```

#### Is the bug present in both iOS and Android or in any one of them?
In iOS: 
Tab titles overlap each other and keep refreshing.

In Android:
Tab titles overlap each other.

#### Any other additional info which would help us debug the issue quicker.
Only when ```tabs``` are returned from API call, this issue occurs. Then ```tabs``` will be cached, then next time, this issue is gone. 
(```tabs``` can't be hardcoded in my case, and they have to be fetched from API response.)

###Important

If you want your issue to be looked at quicker, attach a snack reproducible with your issue. Makes it easier for us!

**Comment by evacao1225** [comment]
If anything else needs to provide, just let me know.

**Comment by Ruzen1** [comment]
I am having the same problem. Native base team help us
