### ISSUE TITLE
Toast button not working on stand alone app

### ISSUE THREAD

**Issue by pROFESOR11** [GeekyAnts/NativeBase#3393]
## I have gone through these following points

- [x] Check latest documentation: https://docs.nativebase.io/
- [x] Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x] Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [x] Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [x] For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- [x] For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

## Issue Description

I've read documentation, change logs, other issues and found out that this issue has been addressed before and fixed in a previous release (https://github.com/GeekyAnts/NativeBase/pull/3200 @ https://github.com/GeekyAnts/NativeBase/releases/tag/v2.13.14). I actually use a more recent version, but still experience the same problem when I build the app.

#### node, npm, react-native, react and native-base version, expo version if used, xcode version
```
"expo": "^39.0.0",
"native-base": "2.15.2",
"react": "16.13.1"
```
#### Expected behaviour
User should be able to press toast button, and toast onClose method should be triggered with `reason === "user"`.

#### Actual behaviour
User can not press toast button, and toast onClose method always is triggered with `reason === "timeout` after the specified duration ends.

#### Steps to reproduce

```
Toast.show({
  text: "Share your work",
  type: "success",
  duration: 5000,
  style: { marginTop: 78 },
  position: "top",
  buttonText: "Share",
  buttonTextStyle: { fontWeight: "bold" },
  buttonStyle: { alignSelf: "center" },
  onClose: (reason) => {
    if (reason === "user" || reason === "functionCall") {
      shareWork({
        title: workTitle,
        url: workUrl,
      });
    }
  },
});
```

#### Is the bug present in both iOS and Android or in any one of them?
I have tried only on iOS, as the app will be for iOS users.

#### Any other additional info which would help us debug the issue quicker.
The toast button is fully functional when is used in the Expo Client. However it doesn't work in the build. Swipe functionality works fine in both.

**Comment by Aryk** [comment]
Im experiencing the same thing...except it intermittently works on Expo and standalone iOS.

**Comment by mbernardes19** [comment]
Had the same problem and unfortunately had to do the same thing as @Aryk . I'm using version 2.15.2 and tried to fork it to see what could be happening but no luck. Once I have more time maybe I'll analyze it more deeply.
