### ISSUE TITLE
Is there a way to scroll to bottom automatically when showing a List component?

### ISSUE THREAD

**Issue by benjaminb10** [GeekyAnts/NativeBase#340]
It's possible for ListView react-native component. But since List is a native-base component, how can I scroll to bottom a List component automatically when showing up?

**Comment by 3210jr** [comment]
+ 1

going through the same problem...

@benjaminb10 do you have a solution?

**Comment by benjaminb10** [comment]
I did'nt manage but I've used react native scrollview component instead.

**Comment by sanketsahusoft** [comment]
You can get a ref to the RN's ListView component and then use the provided scroll API.
