### ISSUE TITLE
Custom SVG throws error in Android devices

### ISSUE THREAD

**Issue by hariharank6** [GeekyAnts/NativeBase#3408]
## I have gone through these following points

- [x] Check latest documentation: https://docs.nativebase.io/
- [x] Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x] Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [x] Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [x] For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- [x] For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

## Issue Description
SVG with elements like <rect>,<circle>,<g> breaks the app in android devices.

I'm using https://snack.expo.io/@hariharank/icon-example-(custom) this method to create icons.

Refer attached screenshot and files of repro:
![Screenshot_1612158619](https://user-images.githubusercontent.com/69412921/106420959-c5fa3500-6481-11eb-86bb-96aac60a5f4e.png)

[dashboard.zip](https://github.com/GeekyAnts/NativeBase/files/5902161/dashboard.zip)

#### node, npm, react-native, react and native-base version, expo version if used, xcode version
expo v40
nativebase v19 (v3 alpha)

#### Expected behaviour
SVG should render correctly on Android devices.

#### Actual behaviour
Throws error on Android devices if svg contains any elements other than <path>.

#### Steps to reproduce
Use the attached svgs to create icon in UI

#### Is the bug present in both iOS and Android or in any one of them?
Android

#### Any other additional info which would help us debug the issue quicker.
Issue doesn't occur with SVG that has only path elements inside it.

If you want your issue to be looked at quicker, attach a snack reproducible with your issue. Makes it easier for us!

I tried to create a snack, but it is not working for native devices. Even the nativebase example snacks also fail for me

**Comment by Ajamuar** [comment]
@hariharank6 we believe this is fixed in the latest version. Please try it there and re-open the issue if the problem still persists.
