### ISSUE TITLE
Drawer doc is broken

### ISSUE THREAD

**Issue by ngocdaothanh** [GeekyAnts/NativeBase#3429]
Doc:
https://docs.nativebase.io/Components.html#Drawer

See attached image:

<img width="798" alt="Screen Shot 2021-02-04 at 2 39 04 am" src="https://user-images.githubusercontent.com/10095/106770770-62932180-6692-11eb-92cd-4384b9484549.png">

**Comment by beatrizavanzi** [comment]
I'm also needing this doc.
