### ISSUE TITLE
Support for Styled-Components

### ISSUE THREAD

**Issue by juangl** [GeekyAnts/NativeBase#343]
I wonder if there is support for styled-components or there are plans to support it.

I'd be amazing to use themeProvider with NativeBase!

**Comment by juangl** [comment]
thank you for response! When can I found development branch?

**Comment by swaroopa94** [comment]
@himanshu-satija Hi Did you add support of styled compoennt for nativebase 

native-base version  : 2.3.1
When I use 

```
const NavbarRightView = styled.Segment`
  flex:0.2;
`
```
It is throwing error

**Comment by rkhayat** [comment]
@swaroopa94 try this
```
const NavbarRightView = styled(Segment)`
  flex:0.2;
`
```
