### ISSUE TITLE
RNCAndroidDropdownPicker was not found in the UIManager

### ISSUE THREAD

**Issue by ansarikhurshid786** [GeekyAnts/NativeBase#3435]
Hi
Thanks contributor for a best library for react native. 

In latest version i am getting following error in android platform: 
`RNCAndroidDropdownPicker was not found in the UIManager`

node: 10.15.0
react-native: 0.63.4
nativebase: 2.15.2

#### Expected behaviour
PIcker shoult also working in android platform. 

#### Actual behaviour
Getting following error in Android: 
`RNCAndroidDropdownPicker was not found in the UIManager`

#### Steps to reproduce
Code snipped: 
 ```
<Item picker>                 
                               <Picker
                                    mode="dropdown"
                                    iosIcon={<Icon name="arrow-down" />}
                                    selectedValue={this.state.domain}
                                    onValueChange={(text) => { this.onValueChangeUpdateState("domain", text); }}
                                    placeholder="Select Domain"
                                    iosHeader="Select Domain"
                                >
                                    <Picker.Item label="Select Domain" value="" />
                                    <Picker.Item label="DMT" value="dmt" />
                                </Picker>
 </Item>
``

**Comment by AndrewN93** [comment]
I found in source code that picker depends from @react-native-picker/picker package, so i just installed it with ```npm install @react-native-picker/picker --save``` and this fixed error.

https://github.com/GeekyAnts/NativeBase/blob/02f5b23e19b3db594e5b5828f336fdac32cfb1fc/src/basic/Picker.js#L5

**Comment by jonnycraze** [comment]
I'm getting this same issue, installing @react-native-picker/picker did not resolve the issue for me.

**Comment by mohity777** [comment]
installing  @react-native-picker/picker resolved the issue in my case

**Comment by Aladeusi** [comment]
import { Picker } from '@react-native-picker/picker' and npm install @react-native-picker/picker --save
the above works

**Comment by isotopeee** [comment]
Just in case anyone has a similar case to mine. I'm using `expo@35.0.0`, I needed to downgrade to `native-base` <= `2.13.14` to resolve the issue. Based on https://blog.expo.io/expo-sdk-38-is-now-available-ab6cd30ca2ee, because of the addition of `@react-native-community/picker` package in Expo 38, the `<Picker>` component was adjusted. 

The issue was caused by import change on `native-base` >= `2.13.15`:

https://github.com/GeekyAnts/NativeBase/blob/6db05d7e32234369bc9ef1c00ae81c725cf790ac/src/basic/Picker.js#L5

Before the import was:

https://github.com/GeekyAnts/NativeBase/blob/47643385e1b7224387fb7fd70451746fc70accaa/src/basic/Picker.js#L5

**Comment by heruujoko** [comment]
I got a similar issue, but only downgrading to native-base <= 2.13.14 seems to resolve it.

**Comment by ThangLeQuoc** [comment]
Installing the `@react-native-picker/picker` does not resolve in my case.

**Comment by lorenzosfarra** [comment]
Not sure if this is somehow an accepted way to proceed (old style, maybe...so I think it's not a resolution to the bug but a possible workaround), but I have manually edited `settings.gradle` and `app/build.gradle` together with a line added to `MainApplication.java` in order to make it work.

The first step was to install the package:
`npm install @react-native-picker/picker --save`

**`settings.gradle`**

Added
`implementation project(path: ':@react-native-community-picker')`

to the `dependencies` section.


**`app/build.gradle`**

Added
`implementation project(path: ':@react-native-community-picker')`

to the `dependencies` section.

**`settings.gradle`**

Added
```
+include ':@react-native-community-picker'
+project(':@react-native-community-picker').projectDir = new File(rootProject.projectDir,       '../node_modules/@react-native-community/picker/android')
```

**`MainApplication.java`**
```
+import `com.reactnativecommunity.picker.RNCPickerPackage;`
// ...
@Override
                protected List<ReactPackage> getPackages() {
                    // [...]
                    return Arrays.<ReactPackage>asList(
                           // [..]
                           new new RNCPickerPackage()
                    );
               }
```

This is **not** a solution, but I wanted to add some steps that made the module work soon (very urgent for me).

**Comment by gabrielhpugliese** [comment]
The solution from @lorenzosfarra does not work for me:

```
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Could not resolve project :@react-native-community-picker.
     Required by:
         project :app
      > Unable to find a matching configuration of project :@react-native-community-picker:
          - None of the consumable configurations have attributes.
 ```

**Comment by lorenzosfarra** [comment]
@gabrielhpugliese sorry, there was a mistake in my comment.
`npm install @react-native-community/picker --save`
instead of
`npm install @react-native-picker/picker --save`

already correct my comment. Hopefully this will fix your error, too.

**Comment by ansarikhurshid786** [comment]
@lorenzosfarra after installing @react-native-community/picker, i am getting following error: 

`Invariant Violation: Tried to register two views with the same name RNCAndroidDropdownPicker`

**Comment by lorenzosfarra** [comment]
It _can be_ because you now have both @react-native-community/picker and @react-native-picker/picker, you should remove `@react-native-picker/picker`.
If it's already removed, can you please show how do you import the picker in your JS code?

**Comment by ansarikhurshid786** [comment]
i also tried to remove @react-native-picker/picker package still get same error

**Comment by gabrielhpugliese** [comment]
I could only solve it by downgrading native-base@2.13.14

**Comment by ansarikhurshid786** [comment]
I have install @react-native-picker/picker and now it is working fine.

**Comment by ansarikhurshid786** [comment]
@gabrielhpugliese you are right. previously i was using native-base@2.13.14. now i install @react-native-picker/picker which resolved issue.

**Comment by gabrielhpugliese** [comment]
I am not sure if this should be closed. Isn't it still an issue because something about the dependencies is off?

**Comment by wendysychan** [comment]
Agreed, hope will fix in next version.

**Comment by mernxl** [comment]
Hello, just installing `@react-native-picker/picker@^1.9.7` fixes the issue for me. That version matches that used by native-base. Its also imperative to keep importing from native-base as it applies the predefined styles to the picker component.

I think this issue has to do with auto-linking of the `@react-native-picker/picker` package. When its a dependency of native-base alone, somehow its not linked, but when directly depended upon by your app, its linked properly. 

Hope it helps you 🚀 Happy Coding...

**Comment by shivamjjha** [comment]
It is a problem with `linking/installing right package by default`. In `package-lock.json`, I can see that `@react-native-picker/picker` version `"^1.9.7"` is required:

```
"native-base": {
      "version": "2.15.2",
      "resolved": "https://registry.npmjs.org/native-base/-/native-base-2.15.2.tgz",
      "integrity": "sha512-Oa42UOlOVgzA6oNc5ai86r3DFom9Wj5JuJ3ShsHmEkqhnqWw7TBKpuIDNV8Zt9NmycH5xMdMcgxliob6jniZjw==",
      "requires": {
        "@codler/react-native-keyboard-aware-scroll-view": "1.0.1",
        "@react-native-community/datetimepicker": "^3.0.2",
        "@react-native-picker/picker": "^1.9.7",
         .....
```

But only version `"1.15.0"` is installed:

```
    "@react-native-picker/picker": {
      "version": "1.15.0",
      "resolved": "https://registry.npmjs.org/@react-native-picker/picker/-/picker-1.15.0.tgz",
      "integrity": "sha512-TYdhavldt3ami860fVgYv2mf0d1u5YhMQ6kTw+soX/a1rYbpRCRjdz01sEQXwCW8oL7/lzHakOFnwqCo6JazDw=="
    },


```

After manually installing using `npm i --save @react-native-picker/picker`, the problem got fixed.

**Comment by hotaryuzaki** [comment]
> Hello, just installing `@react-native-picker/picker@^1.9.7` fixes the issue for me.
> 
> ```shell
> yarn add @react-native-picker/picker@^1.9.7
> ```
> 
> That version matches that used by native-base. Its also imperative to keep importing from native-base as it applies the predefined styles to the picker component.
> 
> ```ts
> import { Picker } from 'native-base'; // use this as it will apply the predefined styles from native-base
> ```
> 
> I think this issue has to do with auto-linking of the `@react-native-picker/picker` package. When its a dependency of native-base alone, somehow its not linked, but when directly depended upon by your app, its linked properly.
> 
> Hope it helps you  Happy Coding...

i think this is true.
that is why we have to install again react-native-picker into our dependencies.

but if we want to make both of them use the latest version, reinstall native-base so it would install latest version of react-native-picker. Then install react-native-picker.
for me, now both of them using react-native-picker 1.15.0
and the error solved too.

thanks to @mernxl

**Comment by chaudev** [comment]
Use `npm install @react-native-community/picker --save` instead of all other options!! It worked for me

**Comment by ajhoel43** [comment]
> > Hello, just installing `@react-native-picker/picker@^1.9.7` fixes the issue for me.
> > ```shell
> > yarn add @react-native-picker/picker@^1.9.7
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > That version matches that used by native-base. Its also imperative to keep importing from native-base as it applies the predefined styles to the picker component.
> > ```ts
> > import { Picker } from 'native-base'; // use this as it will apply the predefined styles from native-base
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I think this issue has to do with auto-linking of the `@react-native-picker/picker` package. When its a dependency of native-base alone, somehow its not linked, but when directly depended upon by your app, its linked properly.
> > Hope it helps you  Happy Coding...
> 
> i think this is true.
> that is why we have to install again react-native-picker into our dependencies.
> 
> but if we want to make both of them use the latest version, reinstall native-base so it would install latest version of react-native-picker. Then install react-native-picker.
> for me, now both of them using react-native-picker 1.15.0
> and the error solved too.
> 
> thanks to @mernxl

thanks @mernxl & @hotaryuzaki , installing react-native-picker@1.15.0 solved my problem

I'm using:

- native-base: 2.15.2
- react-native: 0.60.4

**Comment by batosain** [comment]
After install @react-native-picker/picker, we must build application again. '@' packages must require building after install. This worked for me.

**Comment by rajeevverma076** [comment]
> Not sure if this is somehow an accepted way to proceed (old style, maybe...so I think it's not a resolution to the bug but a possible workaround), but I have manually edited `settings.gradle` and `app/build.gradle` together with a line added to `MainApplication.java` in order to make it work.
> 
> The first step was to install the package:
> `npm install @react-native-community/picker --save`
> 
> **`app/build.gradle`**
> 
> Added
> `implementation project(path: ':@react-native-community-picker')`
> 
> to the `dependencies` section.
> 
> **`settings.gradle`**
> 
> Added
> 
> ```
> +include ':@react-native-community-picker'
> +project(':@react-native-community-picker').projectDir = new File(rootProject.projectDir,       '../node_modules/@react-native-community/picker/android')
> ```
> 
> **`MainApplication.java`**
> 
> ```
> +import `com.reactnativecommunity.picker.RNCPickerPackage;`
> // ...
> @Override
>                 protected List<ReactPackage> getPackages() {
>                     // [...]
>                     return Arrays.<ReactPackage>asList(
>                            // [..]
>                            new RNCPickerPackage()
>                     );
>                }
> ```
> 
> This is **not** a solution, but I wanted to add some steps that made the module work soon (very urgent for me).

This solution working but we need to get a solution for @react-native-picker/picker because @react-native-community-picker This package has been deprecated. Can you please provide me a solution for this issue?
