### ISSUE TITLE
DatePicker issue : Component Exception

### ISSUE THREAD

**Issue by DimpyLadva** [GeekyAnts/NativeBase#3438]
Issue: 

A date or time should be specified as 'value'
![Screenshot_1612548030](https://user-images.githubusercontent.com/10396936/107071215-65b11d80-680a-11eb-90fc-5c1931972d7f.png)

"native-base": "^2.15.2",

**Comment by purplegamba** [comment]
This looks the same as:  https://github.com/GeekyAnts/NativeBase/issues/3381

**Comment by timothydillan** [comment]
Hi! Not sure if double posts are allowed, but you can refer [here](https://github.com/GeekyAnts/NativeBase/issues/3381#issuecomment-791300821) for the fix.
