### ISSUE TITLE
Unable to resolve module

### ISSUE THREAD

**Issue by gperdomor** [GeekyAnts/NativeBase#344]
![screen shot 2016-12-05 at 11 26 57 pm](https://cloud.githubusercontent.com/assets/371939/20910820/b6e86fe2-bb42-11e6-91e4-ba2725c593a2.png)

**Comment by SupriyaKalghatgi** [comment]
@gperdomor Could you please mention what version of React, RN, NB and Easy-Grid *(if you have)* are you using?

**Comment by gperdomor** [comment]
RN 0.37, but after upgrade to 0.39 is solved
