### ISSUE TITLE
[Feature Request] Handle click on Title in Header

### ISSUE THREAD

**Issue by gperdomor** [GeekyAnts/NativeBase#346]
Hi, i tried to handle click on Title header but if i wrap the Title component inside a TouchableFeedback or similar, the title is not rendered.

I tried also changing the Title to a Button but is rendered on the right

**Comment by sankhadeeproy007** [comment]
Works with RN 0.39.2 and native-base 0.5.19
![title](https://cloud.githubusercontent.com/assets/10998047/21520904/32073d60-cd1e-11e6-9f59-41330401494a.gif)
