### ISSUE TITLE
Issue with Dynamic Card

### ISSUE THREAD

**Issue by deep-coder** [GeekyAnts/NativeBase#347]
If the Dynamic Content increased beyond the iOS/Android Screen height only the last item is getting displayed and rest of the content are displayed as blank.
<img width="923" alt="screen shot 2016-12-07 at 12 01 22 pm" src="https://cloud.githubusercontent.com/assets/10391116/20957299/fa32b0d6-bc74-11e6-9dfe-dde389432f5f.png">

`let themes = [
  {
    name: '1',
  },
  {
    name: '2',
  },
  {
    name: '3',
  },
  {
    name: '4',
  },
  {
    name: '5',
  },
  {
    name: '6',
  },
  {
    name: '7',
  },
  {
    name: '8',
  },
  {
    name: '9',
  },
  {
    name: '10',
  },
  {
    name: '11',
  },
  {
    name: '12',
  },
  {
    name: '13',
  },
  {
    name: '14',
  },
  {
    name: '15',
  },
];
export default class FooterTabsExample extends Component {
  constructor() {
    super();
  }

  render() {

    return (
      <Container>
        <Content>
          <Card dataArray={themes}
                renderRow={(theme) =>
                  <CardItem>
                    <Text>{theme.name}</Text>
                  </CardItem>
                }>
          </Card>
        </Content>
      </Container>
    );
  }
}`

**Comment by smhatre59** [comment]
The issue occurs when number of cardItems reaches more than 10.
Here is the screenshot when loop/no of items is less than 10:
for(var i=0;i<10;i++){
	questionanswers.push({
		question:"This is some question",
		answer:"This is some answer",
		hint:"This is some hint"
	})
}


![nativebaseissue3](https://cloud.githubusercontent.com/assets/13968787/21082240/80101622-bffd-11e6-9cf7-872f40c45ea1.jpg)
And once the loop/no of items is in more than 10:
for(var i=0;i<11;i++){
	questionanswers.push({
		question:"This is some question",
		answer:"This is some answer",
		hint:"This is some hint"
	})
}
![nativebaseissue4](https://cloud.githubusercontent.com/assets/13968787/21082251/bbca402a-bffd-11e6-9a04-0cb792a79840.jpg)

**Comment by deep-coder** [comment]
Find one workaround for this. If we import '<Text>' from 'react-native' and not from 'native-base' then it is working fine.

**Comment by SupriyaKalghatgi** [comment]
@deep-coder 
-  NativeBase's Card renders dynamically, even when its content goes beyond the iOS/Android Screen height.
-  Importing **Text** from RN and not from NB has got nothing to do with Dynamic Card, since NB's `Text` extends RN's `Text`.

I tried experimenting with your code snippet, it works as expected

![screen shot 2016-12-26 at 7 40 27 pm](https://cloud.githubusercontent.com/assets/13464885/21483169/efd754e6-cba3-11e6-99b7-4cf5ec76aa1e.png)

**Comment by kenleezle** [comment]
Be sure to use the key attribute of the CardItem. Underneath it uses a ListView and dynamically rendered ListViewItems need keys.

**Comment by haifaGh** [comment]
@kenleezle  hey i'm having the same problem: as i have a list that i need to extract from firebase database and then display them in cards. But,I keep getting this error "undefined is not an object evaluating (this.props.title.title)" ALTHOUGH, it works perfectly fine if i displayed them in listView. So, do you have any idea or you can maybe post your code, it might be helpful
