### ISSUE TITLE
Why do buttons overlap other elements indefinitely?

### ISSUE THREAD

**Issue by Rc85** [GeekyAnts/NativeBase#3479]
Elements with position absolute and a high zIndex always appear behind the button no matter where I put the element (before or after). Adjusting the zIndex doesn't bring it over the button.

Looking at the source code, there isn't anything that indicates the button should overlap other elements.

Here is a demo, this is on Android

https://snack.expo.io/trgIzinmU

**Comment by jiasweelaw** [comment]
I also having same issue. Button always overlay on top of any other element
