### ISSUE TITLE
RefreshControl on NativeBase Descendants

### ISSUE THREAD

**Issue by steve-gray** [GeekyAnts/NativeBase#348]
This appears to be a different issue to #257. When using a component that implements the drag-down refreshing pattern on any component that is presented as a descendant of a NativeBase control, it seems that the refreshing of the component is completely blocked.  If I place the components outside the Container/Content regions - drag-down refreshes work as expected.

Unlike the other issues, no errors or warnings are raised of any kind.

**Comment by robertzhouxh** [comment]
i also met the issue too

**Comment by h124551753** [comment]
so do i

**Comment by robertzhouxh** [comment]
<Content
            refreshControl={
              <RefreshControl
                    style={{backgroundColor: '#E0FFFF'}}
                    refreshing={this.props.devices.isLoading}
                    onRefresh={this._onRefresh}
                    tintColor="#ff0000"
                    title="Loading..."
                    titleColor="#00ff00"
                    colors={['#ff0000', '#00ff00', '#0000ff']}
                    progressBackgroundColor="#ffff00"
              />}
        >
        { this._renderTabContent() }
        </Content>
        { this._renderFooterTabs() }
      </Container>
    );

put into Content instead of ListView or ScrollView can resolve the issue.

**Comment by steve-gray** [comment]
I've found that doing this leads to an odd situation where if the children include TouchableOpacities 50% of the time you get no triggering of the refresh, but also 50% of the time generally dragging down won't show the refresher either. Nesting Content/container seems to be problematic this way.

**Comment by SupriyaKalghatgi** [comment]
@steve-gray  By placing the components inside the `Container`, drag-down refreshes work as expected.
@robertzhouxh @h124551753 **ScrollView** is the replacing component for NativeBase's `Content`. Also that `ListView` uses `ScrollView` internally, so wrapping it in another ScrollView is not necessary.

```
<Container>
  <Header>
    <Button transparent>
      <Icon name="ios-arrow-back" />
    </Button>

    <Title>Refresh Control</Title>

    <Button transparent onPress={this.props.openDrawer}>
      <Icon name="ios-menu" />
    </Button>
  </Header>

  <View>
    <ListView
      refreshControl={this._refreshControl()}
      dataSource={this.state.dataSource}
      renderRow={(theme) => this._renderListView(theme)}>
    </ListView>
  </View>
</Container>
```

**Comment by sankhadeeproy007** [comment]
Added `RefreshControl` to `List`. Already works for `Content`
![refreshcontrol](https://cloud.githubusercontent.com/assets/10998047/21588102/58245142-d109-11e6-8d15-f27314874211.gif)

**Comment by li-zhenyu** [comment]
Met the same issue, it cost me two hours !!
Finally solved the problem after saw this.
Not ListView but Content ? This issue made me crazy !!

**Comment by francescjimenez** [comment]
But it doesn't work if the list fills all the items on scroll

**Comment by ceefour** [comment]
@SupriyaKalghatgi https://github.com/GeekyAnts/NativeBase/issues/348#issuecomment-269209129 will break navigation if refreshing=true from the start (bug #1192)

**Comment by crystalcase** [comment]
Maybe I am missing something, but I still have the same problem @steve-gray mentioned. It is like 50% chance of pull to scroll or to refresh. I am using <Content> with refreshControll as a root component in a tabNavigation. If I scroll down and try to scroll up, the refreshControll is triggered. Is there a solution I am missing out?
