### ISSUE TITLE
[Drawer] On Android, ratio can be NaN or Infinity, causing exception

### ISSUE THREAD

**Issue by ngocdaothanh** [GeekyAnts/NativeBase#3483]
native-base: 2.15.2

Drawer source code:
https://github.com/GeekyAnts/NativeBase/blob/de81ef2fb8bd056f85e7bbc78d957f3d5ab43337/src/basic/Drawer/index.js

```js
  tweenHandler: ratio => ({
    mainOverlay: { opacity: ratio / 2 }
  })
```

On Android (iOS is OK), ratio can be `NaN` or `Infinity`, causing exception:

```
[Invariant Violation: [3,"RCTView",{"opacity":"<<NaN>>"}] is not usable as a native method argument] 

[Invariant Violation: [3,"RCTView",{"opacity":"<<Infinity>>"}] is not usable as a native method argument] 
```

Fix:

```js
  tweenHandler: (ratio: number) => {
    const ratioNumber = isFinite(ratio) ? ratio : 0
    return {mainOverlay: {opacity: ratioNumber / 2}}
  }
```

-----

The example of Drawer should be updated to use React Hook `useState` and `open` property of `react-native-drawer`:
https://docs.nativebase.io/Components.html#Drawer

-----

https://github.com/root-two/react-native-drawer hasn't been updated for a long time. And its README says:

```
For production applications we generally recommend using either React Native Side Menu or React Navigation as applicable
```

So probably native-base should switch to those libraries?

**Comment by gtaylor44** [comment]
I'm seeing something similar with Drawer component.

![image](https://user-images.githubusercontent.com/11572604/120661491-7d9e6280-c4c7-11eb-9c57-8a7f74acb71a.png)
