### ISSUE TITLE
Header Component not displaying correctly in iPhone12 Simulator

### ISSUE THREAD

**Issue by ShuKTan** [GeekyAnts/NativeBase#3488]
Hi,
I am using native base 2.13.8 for my react native app.

I have used **header** component for my app and is fine in iPhone 11 series (as desired design) but in iPhone 12 series header is not displaying correctly. 
Header component height is the main issue in iPhone 12 series
left and right components tap is also not working correctly.

I am using simulators for ios app

**Comment by telltokichu** [comment]
facing same issue

**Comment by IMG-Enrique** [comment]
Any update on this?

**Comment by FelipeWikky** [comment]
I'm also having the same problem.
I use version 2.12.1
