### ISSUE TITLE
nativebase.github.io NativeBase 3.0 examples broken

### ISSUE THREAD

**Issue by beepsoft** [GeekyAnts/NativeBase#3489]
Hi,

I'm really thrilled about the upcoming 3.0 release, thank you for your efforts GeekyAnts!

I'm trying to evaluate NativeBase 3.0 and reading the docs at https://nativebase.github.io/

It seems that none of the examples work.

Also the main https://nativebase.io/ site advertises the latest version as `Currently v3.0.0-next.25` but  https://nativebase.io/ seems to be at `v3.0.0-next.21`

Can you please make the examples work?  Or what is the status of nativebase.github.io and should I expect the examples to work as of now?

Thanks!

**Comment by theankurkedia** [comment]
Hi @beepsoft ,

We have moved the Nativebase v3 docs to http://alpha.nativebase.io/. As already mentioned, it is still in alpha and there might be frequent breaking changes in the API until the beta release.

**Comment by beepsoft** [comment]
Oh, great, thanks I didn't know about  http://alpha.nativebase.io/ .
