### ISSUE TITLE
Typescript and NBFactory errors in 3.0.0-next.27

### ISSUE THREAD

**Issue by beepsoft** [GeekyAnts/NativeBase#3491]
I know this is alpha software but I couldn't find an appropriate channel (discord, etc.) where these issues like what is the state of some components or features of v3. etc. can be discussed.

Anyways, I created a snack demonstrating 2 problems I met while using `3.0.0-next.27`.

https://snack.expo.io/@beep/nativebase-ts-problems

1. Any component wrapped with `NBFactory` fails when used inside a `NavigationContainer`. It doesn't happen in the snack online, but happens when the project is downloaded and run locally in iOS simulator or on the web:
```Error: Couldn't find a navigation context. Have you wrapped your app with 'NavigationContainer'? See https://reactnavigation.org/docs/getting-started for setup instructions.```

2. Many of the NativeBase components have typescript errors like these (see the red underlines in the snack):
```Type '{ children: string; }' is missing the following properties from type 'Pick<any, "hitSlop" | "onLayout" | "onPress" | "style" | "testID" | "hasTVPreferredFocus" | "tvParallaxProperties" | "accessible" | "accessibilityActions" | "accessibilityLabel" | ... 218 more ... | "endIcon">': hitSlop, onLayout, onPress, style, and 224 more.```

Are you guys aware of these problems? Or am I doing something wrong here? (I did my trials according to the descriptions in https://alpha.nativebase.io/docs/nativebase)

Thanks!

**Comment by theankurkedia** [comment]
Hi @beepsoft, fixed both of these issues in the latest release `3.0.0-next.30`. Closing this one. If you still face component typing issues any component, please create an issue with the component list.

**Comment by beepsoft** [comment]
Thanks @theankurkedia for the quick response, I'll check it!

**Comment by beepsoft** [comment]
The typing are now OK! 🎉  But the NBFactory vs NavigationContext error still persists.

**Comment by theankurkedia** [comment]
Let me check it and get back to you on this.

**Comment by theankurkedia** [comment]
@beepsoft , NavigationContext error has been fixed in the [commit](https://github.com/GeekyAnts/NativeBase/commit/d3c6b78cde2aad789b8d2b7b84a1174ae818dbd1). It will work in the next version.

**Comment by HeAtNet** [comment]
I also tried to use NBFactory, but does not work.
If I use this component inside of a NavigationContainer, I get this error:
`Error: Couldn't find a navigation context. Have you wrapped your app with 'NavigationContainer'? See https://reactnavigation.org/docs/getting-started for setup instructions.`

In the NBFactory component's parameter I tried multiple different objects, not only the TouchableOpacity, but neither seems to work.

**Comment by theankurkedia** [comment]
@HeAtNet Check read the last comment.

**Comment by theankurkedia** [comment]
@HeAtNet Please check the last comment

**Comment by beepsoft** [comment]
@theankurkedia, I can confirm, it works now using the latest commit like this
```
 "native-base": "git://github.com/GeekyAnts/NativeBase.git#d3c6b78cde2aad789b8d2b7b84a1174ae818dbd1"
```
Thank you very much for the quick fix, I really appreciate it! 👏
