### ISSUE TITLE
alpha.nativebase.io/docs/select examples are broken

### ISSUE THREAD

**Issue by beepsoft** [GeekyAnts/NativeBase#3496]
All examples are broken on this page: https://alpha.nativebase.io/docs/select

In the Basic and Native examples this is wrong:

```
React.useState < string > '';
```

In the Styled one this line

```
React.useState<string>('js');
```

plus a `)` is missing before SelectComponent's closing `}`

**Comment by theankurkedia** [comment]
Hi @beepsoft , it is fixed now. Please check it.

**Comment by beepsoft** [comment]
Thanks, it is working now!
