### ISSUE TITLE
alpha.nativebase.io/docs/modal examples don't work on iOS

### ISSUE THREAD

**Issue by beepsoft** [GeekyAnts/NativeBase#3497]
Examples at http://alpha.nativebase.io/docs/modal seem to work on web, but don't work or look bad on iOS

For example, this is the `Modal Sizes` example:

![IMG_3523](https://user-images.githubusercontent.com/1926265/109119209-aa164600-7744-11eb-9b9c-cf49ed29c6f0.PNG)

**Comment by ricardopacheco** [comment]
Weird, i tested it according to comment and, everything worked.

**Comment by beepsoft** [comment]
I reported it more than a month ago, now they do seem to work on iOS. 🎉

**Comment by intergalacticspacehighway** [comment]
@beepsoft since you reported it's working, I am closing this issue. Feel free to open another if the issue persists!
