### ISSUE TITLE
ListItem itemDivider 

### ISSUE THREAD

**Issue by jamesholcomb** [GeekyAnts/NativeBase#350]
![itemdivider](https://cloud.githubusercontent.com/assets/362729/21037609/e2709b22-bd94-11e6-95ac-78ee686f3664.png)

The upper left corner is missing a part of the divider line.

````
<ListItem itemDivider>
  <Grid>
    <Col size={12}>
      <Icon name="md-people" />
    </Col>
    <Col size={88}>
      <Text>Confirmed</Text>
    </Col>
  </Grid>
</ListItem>
````

**Comment by nobalmohan** [comment]
Please add the styling if any. Can't reproduce this !

**Comment by jamesholcomb** [comment]
Run the native base sample app (List => List Divider).  The second and third section headers exhibit the same behavior.

**Comment by sanketsahusoft** [comment]
@jamesholcomb That's the way it is designed. You might need to fork that component and use your own for now.

**Comment by jamesholcomb** [comment]
This needs to be addressed in the core component as it is supported by ListView.   See https://facebook.github.io/react-native/docs/listview.html#renderseparator

> If provided, a renderable component to be rendered as the separator below each row but not the last row if there is a section header below.
