### ISSUE TITLE
Button.isDisabled doesn't work  on iOS in 3.0.0-next.31

### ISSUE THREAD

**Issue by beepsoft** [GeekyAnts/NativeBase#3500]
`isDisabled` setting is not respected on iOS (it works on web):

https://snack.expo.io/@beep/button-isdisabled-buf-on-ios-300-next31

**Comment by intergalacticspacehighway** [comment]
@beepsoft Thanks for reporting. This seems to be fixed in latest v3.0.0. Closing this issue, feel free to open another if the issue persists. [Updated your example with new version](https://snack.expo.io/@nishanbende/2eb075)
