### ISSUE TITLE
DeckSwiper - undefined is not an object (evaluation "item.title")

### ISSUE THREAD

**Issue by brunobraga95** [GeekyAnts/NativeBase#352]
Hello guys,

I was using deckSwiper two weeks ago and it was working fine (NB 0.5.14). Today I ran my app again and I ran into a few problems: 
`Requiring unknown module: 'react-native/Libraries/Renderer/src/renderers/native/ReactNativePropRegistry'`

I fixed this problem by replacing `import ReactNativePropRegistry from 'react-native/Libraries/Renderer/src/renderers/native/ReactNativePropRegistry';`
by:
`import ReactNativePropRegistry from 'react\lib\ReactNativePropRegistry';`
in:
node_modules\react-native-easy-grid\Utils\computeProps.js

and also updated NB to 0.5.18, along with
react: 15.4.0
RN: 0.38.0

After all that, I ran my app and my deckSwiper component was not not working anymore. Instead it was returning only the top of the card (Very weird problem). Then I checked the documentation and I saw that DeckSwiper code example changed a lot. 
After trying to run the DeckSwiper example provided in the documentation  I got the following error:

 **undefined is not an object (evaluation "item.title")**

Anyone knows why deckSwiper stopped working in the first place, and why the sample code on native base documentation will not work?
thanks

**Comment by sandeepskak** [comment]
@brunobraga95 I had the same issue, the example code on the documentation has a few errors.
Here's the corrected snippet:
`<DeckSwiper
  dataSource={cards}
  renderItem={item =>
      <Card style={{ elevation: 3 }}>
          <CardItem>
              <Thumbnail source={item.image} />
              <Text>{item.text}</Text>
              <Text note>NativeBase</Text>
          </CardItem>
          <CardItem>
              <Image style={{ resizeMode: 'cover', width: null }} source={item.image} />
          </CardItem>
          <CardItem>
              <Icon name="ios-heart" style={{ color: '#ED4A6A' }} />
              <Text>{item.name}</Text>
          </CardItem>
      </Card>
  }>
</DeckSwiper>`
Hope this helps.

**Comment by sanketsahusoft** [comment]
@SupriyaKalghatgi Example by @sandeepskak needs to be updated in the docs as well.
