### ISSUE TITLE
v3 roadmap

### ISSUE THREAD

**Issue by bitlab-code** [GeekyAnts/NativeBase#3539]
Hi,
can you share a roadmap for v3? (possibly with ETA)
Just to help community to decide if wait v3 for the next project
Thank you very much!

**Comment by richagain** [comment]
+1

**Comment by richagain** [comment]
+2

**Comment by richagain** [comment]
+3

**Comment by bitlab-code** [comment]
ETA and roadmap are useful for the reasons mentioned above, anyway... @richagain  I think it's useless respond with +1, in this way you will just send a lot of emails to me 😀

**Comment by gauravguha** [comment]
We are still deciding on the core architecture. It is going to be a mobile-first accessible component for react native and web which will help you to build your design system for all the platforms. Expect a beta preview in 2-3 weeks from now.

**Comment by hlaporthein** [comment]
Hi @gauravguha , when would v3 be stable? I am thinking to start using v3 in my next mobile project coming days.

**Comment by jsonxr** [comment]
Do you have an update on a beta preview ETA?

**Comment by Ajamuar** [comment]
We are working on a roadmap and we will inform you as soon as that is done.

**Comment by AshwiniKumar007** [comment]
Thanks for your patience. We have finally planned our roadmap for NativeBase v3. You can check out the roadmap [here](https://nativebase.io/roadmap)
