### ISSUE TITLE
while installing package 

### ISSUE THREAD

**Issue by SainathPatil001** [GeekyAnts/NativeBase#3541]
npm WARN ERESOLVE overriding peer dependency
npm WARN Found: react@17.0.1
npm WARN node_modules/react
npm WARN   peer react@"17.0.1" from react-native@0.64.0
npm WARN   node_modules/react-native
npm WARN     peer react-native@">=0.64.0-rc.0 || 0.0.0-*" from @react-native-community/cli@5.0.1-alpha.1
npm WARN     node_modules/@react-native-community/cli
npm WARN     4 more (the root project, native-base, ...)
npm WARN   6 more (react-shallow-renderer, react-test-renderer, ...)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer react@"16.13.1" from react-native-windows@0.63.24
npm WARN node_modules/react-native-windows
npm WARN   peer react-native-windows@">=0.62" from @react-native-community/datetimepicker@3.2.0
npm WARN   node_modules/@react-native-community/datetimepicker
npm WARN ERESOLVE overriding peer dependency
npm WARN Found: react-native@0.64.0
npm WARN node_modules/react-native
npm WARN   peer react-native@">=0.64.0-rc.0 || 0.0.0-*" from @react-native-community/cli@5.0.1-alpha.1
npm WARN   node_modules/@react-native-community/cli
npm WARN     @react-native-community/cli@"^5.0.1-alpha.0" from react-native@0.64.0
npm WARN   4 more (the root project, native-base, ...)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer react-native@"^0.63.0-0" from react-native-windows@0.63.24
npm WARN node_modules/react-native-windows
npm WARN   peer react-native-windows@">=0.62" from @react-native-community/datetimepicker@3.2.0
npm WARN   node_modules/@react-native-community/datetimepicker
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! Found: react@17.0.1
npm ERR! node_modules/react
npm ERR!   peer react@"17.0.1" from react-native@0.64.0
npm ERR!   node_modules/react-native
npm ERR!     peer react-native@">=0.64.0-rc.0 || 0.0.0-*" from @react-native-community/cli@5.0.1-alpha.1
npm ERR!     node_modules/@react-native-community/cli
npm ERR!       @react-native-community/cli@"^5.0.1-alpha.0" from react-native@0.64.0
npm ERR!     react-native@"0.64.0" from the root project
npm ERR!     3 more (native-base, ...)
npm ERR!   peer react@"^16.0.0 || ^17.0.0" from react-shallow-renderer@16.14.1
npm ERR!     react-shallow-renderer@"^16.13.1" from react-test-renderer@17.0.1
npm ERR!     node_modules/react-test-renderer
npm ERR!       dev react-test-renderer@"17.0.1" from the root project
npm ERR!   5 more (react-test-renderer, use-subscription, ...)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.0" from @react-native-picker/picker@1.9.12
npm ERR! node_modules/native-base/node_modules/@react-native-picker/picker
npm ERR!   @react-native-picker/picker@"^1.9.7" from native-base@2.15.2
npm ERR!   node_modules/native-base
npm ERR!     native-base@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\Sainath\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Sainath\AppData\Local\npm-cache\_logs\2021-03-14T08_12_04_809Z-debug.log

**Comment by patricktan98** [comment]
@shivrajkumar Can you help check what's going on?
I cant even install old version NativeBase

**Comment by cyrus25** [comment]
@SainathPatil001 @patricktan98 I am able to install the native-base package with the latest react-native version.
<img width="687" alt="Screenshot 1942-12-28 at 5 41 53 PM" src="https://user-images.githubusercontent.com/38385549/111778376-92ad2180-88da-11eb-9341-6dc34d28661f.png">
