### ISSUE TITLE
Using fab example. Fab button shifts on first click

### ISSUE THREAD

**Issue by chirag93** [GeekyAnts/NativeBase#355]
I'm using the exact same example for fab button. 

1. The fab button goes out of screen. But when I add marginTop it positions properly.

2. But when I click on the same fab second time it changes it position with more marginTop value and then it animates.  (It changes the position in the first click only)

Eg code running:
`render() {
        return (
            <Container>
                <Content>
                    <Fab
                        active='true'
                        direction="right"
                        containerStyle={{ marginLeft: 10,marginTop:40 }}
                        style={{ backgroundColor: '#5067FF' }}
                        position="topLeft"
                        onPress={() => this.setState({ active: !this.state.active })}
                    >
                        <Icon name="md-share" />
                        <Button style={{ backgroundColor: '#34A34F' }}>
                            <Icon name="logo-whatsapp" />
                        </Button>
                        <Button style={{ backgroundColor: '#3B5998' }}>
                            <Icon name="logo-facebook" />
                        </Button>
                        <Button disabled style={{ backgroundColor: '#DD5144' }}>
                            <Icon name="ios-mail" />
                        </Button>
                    </Fab>
                </Content>
            </Container>
        );
    }`

**Comment by sankhadeeproy007** [comment]
Hi, can you attach a gif showing the issue?
