### ISSUE TITLE
Buttons are not showing correctly on Android

### ISSUE THREAD

**Issue by MaganAnkur** [GeekyAnts/NativeBase#3559]
I am using block buttons one with colour and one with transparent background.

**on Android transparent button is showing some grey background.

Also the text is showing in caps on Android only.**

![Screen Shot 2021-03-19 at 11 55 01 PM](https://user-images.githubusercontent.com/42070594/111858380-d883dd00-890e-11eb-85ea-932f940f3f6b.png)

      <NativeButton
                testID={testID}
                small={isSmall}
                disabled={isDisabled}
                block={isFullLength}
                rounded
                style={[
                    tailwind(`justify-center ${buttonStyle[isVariant](isPressed)} ${buttonClasses}`),
                    {
                        ...buttonStyles,
                        ...shadowStyle,
                        ...floatingStyle,
                    },
                ]}
                onPress={onPress}
                onPressIn={onPressIn}
                onPressOut={onPressOut}
                activeOpacity={1}>
                <NativeText
                    style={[
                        tailwind(`${textStyle[isVariant](isPressed)} font-extrabold   ${textClasses}`),
                        {
                            ...textStyles,
                            fontFamily: 'Poppins-SemiBold',
                            textAlignVertical: 'center',
                            textAlign: 'center',
                            ...smallButtonStyle,
                        },
                    ]}>
                    {children}
                </NativeText>
                {icon}
            </NativeButton>
        </Content>

**Comment by MaganAnkur** [comment]
Any help would be really appreciated..

**Comment by shivrajkumar** [comment]
@MaganAnkur Can you let us know the version of NativeBase you are using?

**Comment by MaganAnkur** [comment]
> @MaganAnkur Can you let us know the version of NativeBase you are using?

2.13.14
