### ISSUE TITLE
[Feature] RTL support

### ISSUE THREAD

**Issue by cyclops24** [GeekyAnts/NativeBase#356]
Hi,
First thanks for your awesome components pack.
I have two question:

1. Is native base support RTL (for example through a theme variable or any config or options)?

2. Is native base now ready for production?

**Comment by cyclops24** [comment]
guys, are you here?

**Comment by sanketsahusoft** [comment]
@cyclops24 To answer your questions:

1. We don't have RTL support yet (but it's on the roadmap)
2. It's production ready. It has been used by many companies. You can check the apps of  StrapMobile.com, they all use NativeBase.

**Comment by cyclops24** [comment]
Thanks @sanketsahusoft,
1. Are you have a roadmap list anywhere for this awesome project? (for example Thrello or here in Github)?
2. Unfortunately StrapMobile.com is unreachable and site isn't up. 😩

**Comment by ar7casper** [comment]
@sanketsahusoft Is there an updated on the RTL issue? (couldn't find in the repo)

**Comment by sanketsahusoft** [comment]
@ar7casper Not yet! We are considering this.

**Comment by eyadfarra** [comment]
@sanketsahusoft any update on the RTL ?

**Comment by HosseinRashno** [comment]
Do you support RTL now?

**Comment by r-anjirabi** [comment]
two years later and this is still missing!
This feature still in plan ?
