### ISSUE TITLE
Cannot resize ICON component

### ISSUE THREAD

**Issue by flemux** [GeekyAnts/NativeBase#3574]
## I have gone through these following points

- [x] Check latest documentation: https://docs.nativebase.io/
- [x] Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x] Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [x] Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [x] For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- [x] For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

## Issue Description
Unable to change the size of an Icon.  This uses the react-native-vector-icons library which has a size prop.  This doesn't.   Changing the width and height in the **styles** don't work.  Nor do **fontSize** or **iconFontSize** does not make a difference.  Height and width will just change the container.

#### node, npm, react-native, react and native-base version, expo version if used, xcode version

` "dependencies": {
    "@react-native-community/masked-view": "^0.1.10",
    "@react-navigation/bottom-tabs": "^5.11.8",
    "@react-navigation/drawer": "^5.12.4",
    "@react-navigation/native": "^5.9.3",
    "@react-navigation/stack": "^5.14.3",
    "native-base": "^2.15.2",
    "react": "16.13.1",
    "react-native": "0.63.2",
    "react-native-gesture-handler": "^1.10.3",
    "react-native-reanimated": "^2.0.0",
    "react-native-safe-area-context": "^3.2.0",
    "react-native-screens": "^2.18.1",
    "react-native-splash-screen": "^3.2.0",
    "styled-components": "^5.2.1"
  },
  "devDependencies": {
    "@babel/core": "^7.8.4",
    "@babel/preset-typescript": "^7.13.0",
    "@babel/runtime": "^7.8.4",
    "@react-native-community/eslint-config": "^1.1.0",
    "@types/jest": "^26.0.21",
    "@types/react-native": "^0.63.2",
    "@types/react-test-renderer": "^16.9.2",
    "@types/styled-components-react-native": "^5.1.1",
    "@types/webpack-env": "^1.16.0",
    "@typescript-eslint/eslint-plugin": "^4.18.0",
    "@typescript-eslint/parser": "^2.27.0",
    "babel-eslint": "^10.1.0",
    "babel-jest": "^25.1.0",
    "detox": "^18.7.1",
    "eslint": "^6.5.1",
    "eslint-config-airbnb": "^18.2.1",
    "eslint-config-airbnb-typescript": "^12.3.1",
    "eslint-config-prettier": "^8.1.0",
    "eslint-plugin-import": "^2.22.1",
    "eslint-plugin-jsx-a11y": "^6.4.1",
    "eslint-plugin-prettier": "^3.3.1",
    "eslint-plugin-react": "^7.22.0",
    "eslint-plugin-react-native": "^3.10.0",
    "husky": "^5.1.3",
    "jest": "^25.1.0",
    "jest-circus": "^26.6.3",
    "lint-staged": "^10.5.4",
    "metro-react-native-babel-preset": "^0.59.0",
    "prettier": "^2.2.1",
    "react-test-renderer": "16.13.1",
    "typescript": "^3.8.3"
  },`

#### Expected behaviour
Either, changing the width and height of the Icon makes the Icon bigger/smaller.

#### Actual behaviour
Either crops the icon, or makes the container bigger, not changing the size.  fontSize, and size props do not do anything either.

#### Steps to reproduce
<Icon fontSize={270} type={type} name={name} style={{width: 100, height: 100}} size={100} />;

#### Is the bug present in both iOS and Android or in any one of them?
only tested on iOS.

#### Any other additional info which would help us debug the issue quicker.

###Important

If you want your issue to be looked at quicker, attach a snack reproducible with your issue. Makes it easier for us!

I will try to do this.

**Comment by SkyLundy** [comment]
Experiencing a similar problem with icon container vs icon sizing that may be related to this issue. My use case is using it in a Button but it also occurs when using an Icon without any other components. I'm attempting to style the Button globally in an extendedTheme configuration object but the Icon container is sized, not the icon itself.

[https://snack.expo.io/@renovasky/nativebase-icon-sizing-bug](Snack)

NativeBase v3.0.3
Expo v41.0.1
Node v15.14.0
React v16.13.1
React Native v41.0.0
