### ISSUE TITLE
Icon - list of available icons

### ISSUE THREAD

**Issue by crobinson42** [GeekyAnts/NativeBase#358]
What is the easiest way to see the list of available icons to be used? The docs aren't very clear on that detail, http://nativebase.io/docs/v0.5.13/components#icon

**Comment by nobalmohan** [comment]
List of bundled icons in NativeBase https://github.com/oblador/react-native-vector-icons#bundled-icon-sets

**Comment by samthui** [comment]
Dont know why pp dislike @nobalmohan 's answer, that link helps. It leads to this: https://oblador.github.io/react-native-vector-icons/

**Comment by ptaking** [comment]
@samthui There are multiple icons with the same name. How can I select a particular one?

**Comment by SupriyaKalghatgi** [comment]
https://github.com/GeekyAnts/native-base-docs/blob/docs/updateTillTag2.3.10/docs/components/Icon.md

@samthui
