### ISSUE TITLE
Picker and Picker.Item does not have testID property 

### ISSUE THREAD

**Issue by cichun** [GeekyAnts/NativeBase#3587]
## I have gone through these following points

- [x] Check latest documentation: https://docs.nativebase.io/
- [x] Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x] Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [x] Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [x] For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- [x] For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

#### node, npm, react-native, react and native-base version, expo version if used, xcode version

```
  Expo CLI 4.3.2 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.16.0 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.11 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
      Android SDK:
        API Levels: 29
        Build Tools: 29.0.2
        System Images: android-27 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.6010548
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmGlobalPackages:
      expo-cli: 4.3.2
    Expo Workflow: managed
```
#### Expected behaviour
Picker and Picker.Item components should be found by its testID property in E2E tests (detox).
#### Actual behaviour
Picker and Picker.Item could not be found using testID like
`await expect(element(by.id('tidPicker'))).toBeVisible();`
![image](https://user-images.githubusercontent.com/7638234/112485681-7cd8aa00-8d7b-11eb-8284-0a11f7fab892.png)
but this code runs OK for other native-base components like Header/Content/H3/...
#### Steps to reproduce

```
    render() {
        return (
            <Container testID={'tidContainer'}>
                <Header testID={'tidHeader'}/>
                <Content testID={'tidContent'}>
                    <H3 testID='welcome' style={styles.welcomeStyle}>
                        Sample project in React Native to try out Detox E2E tests,
                        using native-base framework
                    </H3>

                    <Form testID={'tidForm'}>
                        <Picker
                            testID={'tidPicker'}
                            style={styles.pickerStyle}
                            itemStyle={styles.itemStyle}
                            mode="dropdown"
                            selectedValue={this.state.pickerSelectedKey}
                            onValueChange={this.onPickerChange}
                            iosIcon={
                                <Icon name="chevron-down-outline"
                                      style={{color: 'rgba(255,255,255,0.8)', lineHeight: 20}}/>
                            }
                        >
                            <Picker.Item label="Wallet" value="key0" testID={'tidPickerItem0'}/>
                            <Picker.Item label="ATM Card" value="key1" testID={'tidPickerItem1'}/>
                            <Picker.Item label="Debit Card" value="key2" testID={'tidPickerItem2'}/>
                            <Picker.Item label="Credit Card" value="key3" testID={'tidPickerItem3'}/>
                            <Picker.Item label="Net Banking" value="key4" testID={'tidPickerItem4'}/>
                        </Picker>
                    </Form>
                </Content>
            </Container>
        );

    }
```
every native-base components are accessible in E2E tests by its testID property

I've prepared sample project showing the issue: 
https://github.com/cichun/expo-detox-test.git  ( switch branch to native-base-tests )

`git clone --branch native-base-tests https://github.com/cichun/expo-detox-test.git `

#### Is the bug present in both iOS and Android or in any one of them?
iOS
#### Any other additional info which would help us debug the issue quicker.

###Important

If you want your issue to be looked at quicker, attach a snack reproducible with your issue. Makes it easier for us!

**Comment by aikewoody** [comment]
Also having the same problem, would be very appreciated if the maintainers look into this!
