### ISSUE TITLE
Support success / error / iconRight for forms

### ISSUE THREAD

**Issue by wochinge** [GeekyAnts/NativeBase#359]
Hi,

as shown in the documentation (http://nativebase.io/docs/v0.5.13/components#successInputTextbox) you can show the validation result of a InputTextbox using the properties success and error or with icons on the right side.

But this great way to indicate errors is not possibe, when using forms.
Would be nice if forms also support this feature, as their input is usually validated somehow.

**Comment by sanketsahusoft** [comment]
It needs to be handled outside NativeBase. At the moment, NativeBase is meant for UI components only and the logic needs to be implemented in your code.

**Comment by wochinge** [comment]
I think you misunderstood me. What I am missing, is the option to have a success / error property (which render the bottomborder accordingly) for forms as well as an icon on the right side of a form input. From my point of view, this is UI related.

**Comment by sankhadeeproy007** [comment]
```{(this.state.success) &&<Icon name='ios-checkmark-circle' />}```
This should work for you.

**Comment by SupriyaKalghatgi** [comment]
@wochinge The success / error prop changes the border color of textbox
And not icons or anything else related to textbox
You can add your custom code in case if you wish to have some enhanced features.

**Comment by wochinge** [comment]
Thanks for your help 👍

**Comment by Norfeldt** [comment]
I can't make it work.. seems like it doesn't re-render..
