### ISSUE TITLE
Picker not showing inside a Card component

### ISSUE THREAD

**Issue by titanve** [GeekyAnts/NativeBase#3597]
## I have gone through these following points

- [] Check latest documentation: https://docs.nativebase.io/
- [] Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [] Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [] Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [] For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- [] For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

#### node, npm, react-native, react and native-base version, expo version if used, xcode version
node: v12.21.0
npm: 6.14.11
react-native: 0.64.0
native-base: 2.15.2
expo: ^40.0.1
Xcode 12.4 Build version 12D4e

#### Expected behaviour
To show the `<Picker />` inside the `<Card />` item
#### Actual behaviour
Not showing the `<Picker />` inside the `<Card />` item
#### Steps to reproduce
![image](https://user-images.githubusercontent.com/4803351/113064572-e510fc80-917c-11eb-9568-456ce9c9679c.png)
![image](https://user-images.githubusercontent.com/4803351/113064613-f6f29f80-917c-11eb-842a-f98256477190.png)

#### Any other additional info which would help us debug the issue quicker.

###Important

If you want your issue to be looked at quicker, attach a snack reproducible with your issue. Makes it easier for us!

**Comment by cyrus25** [comment]
Hi @titanve , couldn't reproduce the above issues. Can you provide a snack link for minimal reproduction for the same?

**Comment by jacargentina** [comment]
@titanve i've had a similar issue; discovered that giving `height` style with some value, it is fixed on my case.

<img width="632" alt="Captura de Pantalla 2021-05-25 a la(s) 11 36 13" src="https://user-images.githubusercontent.com/517228/119516797-6df77f00-bd4d-11eb-83c3-ff9ab8f938a0.png">
