### ISSUE TITLE
How to use images on Footer instead of Icons / Button with Icons?

### ISSUE THREAD

**Issue by maotora** [GeekyAnts/NativeBase#360]
Hi,

I need to use images on my `Footer` component.

It can be anything (as how i tried with failures) not nessessary a `<Footer />` component but anything that can stay on the footer and look awesome.

I have my custom images already i tried your **trello** solution but Image gets ugly and colorless.

I need to accomplish something like this...
![footer](https://cloud.githubusercontent.com/assets/5174884/21202091/7f370450-c25e-11e6-8a24-19cc96fc254a.png)

I hope this is not a stupid issue but i'm desperately in need of something like that.

Thank you.

**Comment by sanketsahusoft** [comment]
@maotora This is on our list. Let me add an enhancement label to the thread.

**Comment by maotora** [comment]
@sanketsahusoft thank you :) 

Quick question, when is the next version coming up again?

**Comment by sanketsahusoft** [comment]
@maotora May be 2 weeks from now :-)

**Comment by maotora** [comment]
Awesome!

Can't wait!! 👍
