### ISSUE TITLE
alpha version 36 

### ISSUE THREAD

**Issue by Tjajeer** [GeekyAnts/NativeBase#3609]
## I have gone through these following points
- [] After adding nativebase v3 into my project, its giving this error

## Issue Description

`Tried to register two views with the same name RNCSafeAreaProvider`, i m checking on IOS simulator and Iphone, but works fine on web`

This are the package versions , i have used

#### node, npm, react-native, react and native-base version, expo version if used, xcode version
node v14.16.0
npm 6.14.11

  "expo": "~40.0.0",
  "expo-status-bar": "~1.0.3",
  "native-base": "^3.0.0-next.36",
  "react": "16.13.1",
"react-native": "https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz",

**Comment by Ajamuar** [comment]
@Tjajeer Can you please try the latest version of native-base? You can report if you face similar issues there.
