### ISSUE TITLE
Error when trying to use Floating Action Button

### ISSUE THREAD

**Issue by Deevent** [GeekyAnts/NativeBase#361]
Whenever I try to use FABs in my code, I get the following error : 

![simulator screen shot 16 dec 2016 a 14 36 06](https://cloud.githubusercontent.com/assets/16573898/21264556/3260a6b4-c39d-11e6-98ff-80337d3c2156.png)

I use the same code than in the example.

`
        render() {
            return (
                <Container>
                    <Content>
                        <Fab
                            active={this.state.active}
                            direction="right"
                            containerStyle={{ marginLeft: 10 }}
                            style={{ backgroundColor: '#5067FF' }}
                            position="topLeft"
                            onPress={() => this.setState({ active: !this.state.active })}
                        >
                            <Icon name="md-share" />
                            <Button style={{ backgroundColor: '#34A34F' }}>
                                <Icon name="logo-whatsapp" />
                            </Button>
                            <Button style={{ backgroundColor: '#3B5998' }}>
                                <Icon name="logo-facebook" />
                            </Button>
                            <Button disabled style={{ backgroundColor: '#DD5144' }}>
                                <Icon name="ios-mail" />
                            </Button>
                        </Fab>
                    </Content>
                </Container>
            );
        }
`

**Comment by sankhadeeproy007** [comment]
Please try to provide some more details regarding versions, because we can't reproduce it from our end.
