### ISSUE TITLE
RN 0.63 with v3.0.0-next36 and @expo/vector-icons

### ISSUE THREAD

**Issue by ricardopacheco** [GeekyAnts/NativeBase#3619]
@expo/vector-icons is really need for RN apps? I can understading expo apps ... but react native, not.

How to use native base 3 without @expo/vector-icons dependency?

**Comment by rajnish-actolap** [comment]
+1

**Comment by rajnish76** [comment]
+1

**Comment by gev** [comment]
+2
I Suggest react-native-vector-icons instead

**Comment by jahead** [comment]
@gauravguha or someone could update us on this? - if it's possible to just use RNVI

It seems that @expo/vector-icons is just a shim for react-native-vector-icons. 
We try to not include anything from expo, as their packages usually need to pull in a number of dependencies that only really make sense if you are using expo. 

This doesn't seem to be the case with this library, it's a shim AFAICT is just to make RNVIs web compact and pull in a direct copy of RNVI to make it stable. 

Any possibility that there could be alternative option?

**Comment by jahead** [comment]
I take that back. 
it still pulls in unimodules which wants to own the module loading process and pulls in a bunch of expo packages 

I now get a warning for lot setting up unimodules in my project.

**Comment by Valdomar** [comment]
+1

Actually i'm not using Icon from native-base and i'm using RNVI, but it's so bad that expo/vector-icons is mandatory...

**Comment by jahead** [comment]
You'll probably find if you're using the select/radio you're using the icon. 

It's unfortunate they didn't stay with RNVIs and have the ability to optionally  load expo icons. 

Expo icons is compact for RNVIs anyway. 

The good news is it's open source and it's only two line change to change it back ^^

**Comment by LadislavBohm** [comment]
I created gist for patch-package in the meantime if anyone is interested.

https://gist.github.com/LadislavBohm/d2154dd48d06f4a1ccee01932326914e

**Comment by jahead** [comment]
Oh that's really neat +1. I forked. But this is so much better!

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by intergalacticspacehighway** [comment]
We have removed expo vector icons dependency in the new release. :D 
You can use them using `as` prop in the Icon component. [Check out this example](http://docs.nativebase.io/icon#basic)
