### ISSUE TITLE
NativeBase 5.2 don't have FABs

### ISSUE THREAD

**Issue by Norfeldt** [GeekyAnts/NativeBase#363]
In the [5.2 documentation]( http://nativebase.io/docs/v0.5.2/components) there is no FAB components. 

Will they be discarded in the newer versions (I'm currently using ^5.18)?

**Comment by himanshu-satija** [comment]
FAB was added in v0.5.13 and 0.5.2 is an older version. We won't be discarding FAB component.

**Comment by Norfeldt** [comment]
Okay, didn't knew that 😊 thank you for answering my question.

The numbering reminds me of how MS Word do its section numbers..
