### ISSUE TITLE
v3 update react 17 and react-native v0.64

### ISSUE THREAD

**Issue by jahead** [GeekyAnts/NativeBase#3657]
## I have gone through these following points

- [x] Check latest documentation: https://docs.nativebase.io/
- [x] Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x] Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [x] Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [x] For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- [x] For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

## Issue Description
Hey  guys,

I know it's even not out in beta yet, from trying it out, I saw that the RN and react versions a bit behind. 
I'm sure you all are working on it, just wanted an issue tracking it. 

``` 
warning " > native-base@3.0.0-next.36" has incorrect peer dependency "react-native@0.62.2".
warning " > native-base@3.0.0-next.36" has unmet peer dependency "react-native-svg@^12.1.0"
```

Are you all accepting PRs for v3 yet?

**Comment by intergalacticspacehighway** [comment]
@jahead Thanks for reporting, this has been fixed in v3.0.0 so closing it. 
Also we have done the beta release. :D [Check it out](https://docs.nativebase.io/)
