### ISSUE TITLE
Can't install correctly

### ISSUE THREAD

**Issue by jsantana90** [GeekyAnts/NativeBase#367]
I am using react-native [ExponentJS](https://getexponent.com/)

After I add the npm package: npm install native-base --save

and do:
import { Button } from 'native-base';

I get
<img width="355" alt="screen shot 2016-12-20 at 6 08 59 pm" src="https://cloud.githubusercontent.com/assets/9933887/21369876/74dae960-c6df-11e6-9ba5-78918b60bf9b.png">

`Requiring unknown module "react-native/Libraries/Renderer/src/renderers/native/ReactNativePropRegistry"`

**Comment by ranjeev75** [comment]
With Exponent use `npm i native-base@0.5.15 --save`  You will also need to add babel-preset-exponent in your .babelrc if you are using an older version of Exponent. [UI-Toolkits](https://blog.getexponent.com/using-react-native-ui-toolkits-with-exponent-3993434caf66#.io89cyyih)

**Comment by jsantana90** [comment]
I see, thanks!
