### ISSUE TITLE
Error with styled-components  native-base v3 

### ISSUE THREAD

**Issue by bettimms** [GeekyAnts/NativeBase#3674]
Hi,
Im trying to use latest version of native base with latest version of react-native but im getting the error showing the the screenshots. Apparently somewhere in native-base components something missing. I tried to install components on my side but i get other styled-components dependency errors. Any suggestion?! I didn't see anywhere that i've to install styled-components as dependency of native-base though?!

```
"dependencies": {
    "native-base": "^3.0.0-next.36",
    "react": "17.0.1",
    "react-native": "0.64.0"
  },
```

<img width="651" alt="Screen Shot 2021-05-04 at 3 10 33 PM" src="https://user-images.githubusercontent.com/9863453/116995138-f9936800-acd9-11eb-9e68-328deb3992db.png">
<img width="374" alt="Screen Shot 2021-05-04 at 3 08 57 PM" src="https://user-images.githubusercontent.com/9863453/116995158-0021df80-acda-11eb-89e8-6f0d584c95da.png">

**Comment by bettimms** [comment]
Solved! I had to install all `peerDependencies`

```
"peerDependencies": {
    "@expo/vector-icons": "^12.0.2",
    "@react-native-picker/picker": "^1.9.11",
    "react": "16.11.0",
    "react-dom": "*",
    "react-native": "0.62.2",
    "react-native-safe-area-context": "^3.1.9",
    "react-native-svg": "^12.1.0",
    "styled-components": "^5.2.1",
    "styled-system": "^5.1.5"
  },
```
 from https://github.com/GeekyAnts/NativeBase/blob/v3.0.0-next.36/package.json

**Comment by minh-dai** [comment]
it's not work :(((

**Comment by minh-dai** [comment]
@sanketsahu 
NativeBase v3 is compatible with 0.63 and above. :))))

**Comment by Janki11-pixel** [comment]
Try wrapping your component in a SafeAreaProvider tag

import { SafeAreaProvider } from 'react-native-safe-area-context';

export default App = () => {

  return (
    <SafeAreaProvider>
      <MainNavigation />
    </SafeAreaProvider>
  );
}
