### ISSUE TITLE
v3 Toast and Snackbar prevent touch when present

### ISSUE THREAD

**Issue by LadislavBohm** [GeekyAnts/NativeBase#3678]
## I have gone through these following points

- [x] Check latest documentation: https://docs.nativebase.io/
- [x] Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [] Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [x] Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [] For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- [x] For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

#### node, npm, react-native, react and native-base version, expo version if used, xcode version
RN 64 (Hermes enabled)
NativeBase: ^3.0.0-next.36

#### Expected behaviour
Displaying Toast or Snackbar should not prevent user to manipulate with the rest of the UI.

#### Actual behaviour
When Toast or Snackbar are present they prevent from using rest of the UI. They behave like a modal with no visible overlay.

#### Steps to reproduce

```

<Button  onPress={() =>  toast({position: 'bottom', title: 'TEST TOAST MESSAGE', duration: 5000})}>
   TEST
</Button>

```
#### Is the bug present in both iOS and Android or in any one of them?
Both for me

#### Any other additional info which would help us debug the issue quicker.
From the source code it looks like they are using Overlay internally and a Wrapper.tsx component that has always a fullscreen transparent view applied to it.

**Comment by DavideCrapa** [comment]
same problem

**Comment by intergalacticspacehighway** [comment]
@DavideCrapa @LadislavBohm Thanks for reporting. This has been resolved in new version. Let me know If you're still facing any issue.
