### ISSUE TITLE
Typings are missing from published package

### ISSUE THREAD

**Issue by davwheat** [GeekyAnts/NativeBase#3686]
## I have gone through these following points

- [x] Check latest documentation: https://docs.nativebase.io/
- [x] Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x] Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [ ] Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [ ] For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- [ ] For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

## Issue Description

I'm using the v3 alpha, and the `package.json` does have a `types` and `typings` entry, but the `types` points to a non-existent file, which breaks the typings.

The `typings` entry doesn't seem to be used, at least in VS Code.

Changing `types` to be the `lib/index.d.ts` file fixes the typings in VSCode.

**Comment by intergalacticspacehighway** [comment]
@davwheat Thanks for reporting, this has been fixed in 3.0.0
