### ISSUE TITLE
Bug: Button Component with rounded prop throws an Error

### ISSUE THREAD

**Issue by rahul-mahato** [GeekyAnts/NativeBase#3692]
<img src="https://user-images.githubusercontent.com/52028898/118394246-255f0800-b661-11eb-9396-b1a8355d7b0d.png" width="350px"/>

## Issue Description
Using the prop rounded,roundedTopLeft, roundedTopRight , roundedBottomLeft, roundedBottomRight, etc , throws and error 

```
import {Box, Button} from 'native-base';

const SomeComponent = () => {
  return (
    <Box>
      <Button marginY={10} rounded>
        Test
      </Button>
    </Box>
  );
};

export default SomeComponent;
```

#### Versions : 
npm : 7.13.0
node: v15.3.0
react-native-cli: 2.0.1
react-native: 0.64.1
xed: 12.5

#### Expected behaviour
To have a button with rounded borders, ie. with some border radius.

#### Actual behaviour
Throws error `Invalid prop 'borderRadius' of type 'string' supplied to 'StyleSheet generated', expected 'number'`

#### Steps to reproduce
- create a project using `react-native init projectname`.
- install nativebase using `yarn add nativebase@next`.
- install all the peer dependencies.
- Create any component which uses `Button` component from `native-base`.
- Add a prop `rounded` to the `Button` component.

**Comment by jacargentina** [comment]
In v3, it is variant=“pill”

**Comment by zuhairnaqi** [comment]
I think rounded buttons are removed in version 3.
