### ISSUE TITLE
Picker.item unexpected character error ?

### ISSUE THREAD

**Issue by ddpdev** [GeekyAnts/NativeBase#370]
NativeBase Picker example not working..

exactly copy example...

but error occur when i run

const Item = Picker.Item;​ <-- 

[Message]  unexpected character ...

how to solve it ?
and i don't know how to make sub component 
(anyone help me... pickerContainer source want.. m.m)

i use 
react 15.4.1
 "native-base": "^0.5.18",
 "react-native": "^0.39.2", ...
"react-native-router-flux": "^3.36.0",
macOS XCode 8.1

thanks NativeBase~

**Comment by SupriyaKalghatgi** [comment]
@ddpdev Seems like there is a space after `const Item = Picker.Item;​`
Exclude it and that would work

**Comment by ddpdev** [comment]
thanks @SupriyaKalghatgi ^^;
