### ISSUE TITLE
Error in Accordion

### ISSUE THREAD

**Issue by dodiwknd** [GeekyAnts/NativeBase#3705]
I get an error like this in the component accordion .. has someone found this?

![image](https://user-images.githubusercontent.com/82150448/119122368-a3a01d80-ba58-11eb-8ac9-425957d752ea.png)

**Comment by AndersonHqds** [comment]
You can pass the prop expanded. 

```
<Accordion 
  expanded={[]} // if you don't want any section expanded
/>
```

and 

```
<Accordion
  expanded={[0]} // You can pass the index, if you want some section expanded
/>
```
