### ISSUE TITLE
Extracting Tab into a reusable component loses style

### ISSUE THREAD

**Issue by TeyimPila** [GeekyAnts/NativeBase#3706]
## I have gone through these following points

- [x] Check latest documentation: https://docs.nativebase.io/
- [x] Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x] Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [x] Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [x] For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- [x] For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

## Issue Description

I have a native base Tabs with many tabs in it. These tabs have identical styles as follows. My goal is to extract them into a reusable component but when I create the component and use it, I lose all the styles.

```Javascript

 <Tabs>
          <Tab
            heading="Tab A"
            style={{ backgroundColor: Colors.backgroundFaded, ...Gutters.smallPadding }}
            tabStyle={{ backgroundColor: Colors.backgroundFaded }}
            activeTabStyle={{ backgroundColor: Colors.backgroundFaded }}
            activeTextStyle={{ color: Colors.primary }}
          >
            <Text style={[Fonts.h2]}>tab a</Text>
          </Tab>
          <Tab
            heading="Tab B"
            style={{ backgroundColor: Colors.backgroundFaded, ...Gutters.smallPadding }}
            tabStyle={{ backgroundColor: Colors.backgroundFaded }}
            activeTabStyle={{ backgroundColor: Colors.backgroundFaded }}
            activeTextStyle={{ color: Colors.primary }}
          >
            <Text style={[Fonts.h2]}>tab b</Text>
          </Tab>
          <Tab
            heading="Tab C"
            style={{ backgroundColor: Colors.backgroundFaded, ...Gutters.smallPadding }}
            tabStyle={{ backgroundColor: Colors.backgroundFaded }}
            activeTabStyle={{ backgroundColor: Colors.backgroundFaded }}
            activeTextStyle={{ color: Colors.primary }}
          >
            <Text style={[Fonts.h2]}>Tab c</Text>
          </Tab>
          <Tab
            heading="Tab D"
            style={{ backgroundColor: Colors.backgroundFaded, ...Gutters.smallPadding }}
            tabStyle={{ borderTopRightRadius: 10, backgroundColor: Colors.backgroundFaded }}
            activeTabStyle={{ borderTopRightRadius: 10, backgroundColor: Colors.backgroundFaded }}
            activeTextStyle={{ color: Colors.primary }}
          >
            <Text style={[Fonts.h2]}>tab d</Text>
       
          </Tab>
        </Tabs>
```

My goal is to create a component like the following and just reuse it. When I do this, I lose all my styling 

```JavaScript

const TabItem = ({ heading, children }) => {
  const { Colors, Gutters } = useTheme();
  return (
    <Tab
      heading={heading}
      style={{ backgroundColor: Colors.backgroundFaded, ...Gutters.smallPadding }} // This styles the content of a tab
      tabStyle={{ borderTopLeftRadius: 10, backgroundColor: Colors.backgroundFaded, borderWidth: 1}}
      activeTabStyle={{ borderTopLeftRadius: 10, backgroundColor: Colors.backgroundFaded }}
      activeTextStyle={{ color: Colors.primary }}
    >
      {children}
    </Tab>
  );
};

TabItem.propTypes = {
  children: PropTypes.node.isRequired,
  heading: PropTypes.string.isRequired,
};

export default TabItem;
```

#### node, npm, react-native, react and native-base version, expo version if used, xcode version
- Node 14.15.4
- npm 7.6.3
-  "native-base": "^2.15.2"
- "react": "^17.0.2",
- "react-native": "^0.64.0",

#### Expected behaviour

- When I extract Tab into a component and style the component, I should retain the styles when I reuse that component

#### Actual behaviour
- Styles revert to default styles

#### Steps to reproduce

- Create a Tab component and style is
- Import the component and render it in Tabs

#### Is the bug present in both iOS and Android or in any one of them?
- Currently tested in iOS

#### Any other additional info which would help us debug the issue quicker.
- None

###Important

If you want your issue to be looked at quicker, attach a snack reproducible with your issue. Makes it easier for us!

**Comment by Fanrong-qu** [comment]
i have the same problem, probably it is the problem of pagerView
