### ISSUE TITLE
Can't install nativebase on my react native app

### ISSUE THREAD

**Issue by NexCodeJimM** [GeekyAnts/NativeBase#3714]
Hello, I'm trying to install native base on my react app by it's showing me this error every time I tried running 'npm install native-base --save'

`npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! Found: react@16.13.1
npm ERR! node_modules/react
npm ERR!   peer react@"^16.0" from @gregfrench/react-native-wheel-picker@1.2.14
npm ERR!   node_modules/@gregfrench/react-native-wheel-picker
npm ERR!   peer react@"^16.8.0" from @koale/useworker@3.4.0
npm ERR!   node_modules/@koale/useworker
npm ERR!     @koale/useworker@"^3.2.1" from expo-camera@11.0.3
npm ERR!     node_modules/expo-camera
npm ERR!       expo-camera@"~11.0.2" from the root project
npm ERR!   7 more (@react-native-mapbox-gl/maps, ...)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"17.0.1" from react-native-windows@0.64.9
npm ERR! node_modules/native-base/node_modules/react-native-windows
npm ERR!   peer react-native-windows@">=0.62" from @react-native-community/datetimepicker@3.5.0
npm ERR!   node_modules/native-base/node_modules/@react-native-community/datetimepicker
npm ERR!     @react-native-community/datetimepicker@"^3.0.2" from native-base@2.15.2
npm ERR!     node_modules/native-base
npm ERR!       native-base@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/jim/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:`

I hope someone know a fix :/

**Comment by jonhickman5** [comment]
Native Base appears to be having significant issues across the board with new react native apps.

**Comment by rhyek** [comment]
Any workarounds? Completely new project and I can't even get past the getting started part for native-base.
