### ISSUE TITLE
Fab disappears when in `bottomRight` or `bottomLeft` position (iPhone 6S)

### ISSUE THREAD

**Issue by trevor-coleman** [GeekyAnts/NativeBase#372]
Works fine in `topLeft` and `topRight` but can't get it to work in bottom positions.

It's a blank screen with just the FAB on it for now.

```<Container theme={dunbarTheme}>
    <Content>
      <Fab
         active={this.state.active}
         direction="left"
         style={{ backgroundColor: '#5067FF' }}
         position="bottomRight"
         containerStyle={{paddingBottom: 20, paddingRight: 20}}
         onPress={() => this.setState({ active: !this.state.active })}
       >
         <Icon name="rocket" />
      <Button style={{ backgroundColor: '#34A34F' }}>
         <Icon name="rocket" />
      </Button>
      <Button style={{ backgroundColor: '#3B5998' }}>
         <Icon name="rocket" />
      </Button>
      <Button disabled style={{ backgroundColor: '#DD5144' }}>
         <Icon name="rocket" />
      </Button>
    </Fab>
  </Content>
</Container>

**Comment by trevor-coleman** [comment]
Ends up looking like this: 

![image](https://cloud.githubusercontent.com/assets/22041394/21435671/104a4bb0-c849-11e6-8967-28bf79a988c3.png)

**Comment by Ruchika1989** [comment]
same problem with me

**Comment by sankhadeeproy007** [comment]
Versions please? I can get it to work with the exact same source.
![fab](https://cloud.githubusercontent.com/assets/10998047/21519663/1b35d046-cd15-11e6-9630-2f809892244f.gif)

**Comment by kapone89** [comment]
Same problem. Version 0.5.22. Why there is a FAB on the top in examples? It used to be on the bottom. Is it because it doesn't work? 😄

**Comment by sankhadeeproy007** [comment]
Please use `Fab` outside `Content` and not inside it. That'll probably fix it.

**Comment by Colmea** [comment]
Thanks, moving Fab outside Content resolve my issue. Please update doc (which shows an example with a FAB **inside** a Content)

**Comment by sankhadeeproy007** [comment]
cc @SupriyaKalghatgi

**Comment by w-** [comment]
In the current version docs (v19.0.0) it still isn't clear that FAB should sit outside the `<Content />` component.

I had to trawl through the issues and luckily stumbled across this. I think @Colmea 's suggestion would be beneficial to those not fully familiar with this component.
