### ISSUE TITLE
[Request] Typescript - Add ability to extend exported primitive with custom properties

### ISSUE THREAD

**Issue by FrederickEngelhardt** [GeekyAnts/NativeBase#3725]
## I have gone through these following points

- [x] Check latest documentation: https://docs.nativebase.io/
- [x] Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x] Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [x] Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [x] For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- [x] For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

## Issue Description
Adding additional properties to nativebase components will result in a prop type error from typescript.

Example adding '.bold' in the ejected `theme/component/Test.js` will error when using it in a react component. 

Example:`<Text bold>Test</Text>` will error saying bold is not an intrinsic property of Text.

## Request
Add ability to autogenerate types during eject or directly off the ejected directory. These types would override the NativeBase.d.ts files.

Has anyone gone down this route? It would require parsing through all exported primitives and then generating extended types for those primitives.

**Comment by Ajamuar** [comment]
We have taken note of this issue and we'll be working to fix this ASAP.

**Comment by himanshu-satija** [comment]
@FrederickEngelhardt I'm assuming this issue is for NativeBase v2.x. If that's the case, we're sorry but we won't be able to work on this as we are actively focusing on v3 now.

If someone is willing to work on this, we are open to PRs.
