### ISSUE TITLE
Picker.Item doesn't exist in the TypeScript definition

### ISSUE THREAD

**Issue by Flavien** [GeekyAnts/NativeBase#373]
The TypeScript compiler can't find Picker.Item, resulting in compile time error, even though the value apparently exists.

**Comment by himanshu-satija** [comment]
I have never worked with TypeScript. Maybe @wcandillon can help us out with a PR.

**Comment by wcandillon** [comment]
@Flavien @himanshu-satija I fixed it in #380

**Comment by himanshu-satija** [comment]
Thanks!
