### ISSUE TITLE
Toast not working in Native Base alpha 3.0.0-next40

### ISSUE THREAD

**Issue by mrezzaaa** [GeekyAnts/NativeBase#3738]
## I have gone through these following points

- [X] Check latest documentation: https://docs.nativebase.io/
- [X] Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [] Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [X] Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [] For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- [] For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

## Issue Description

I have already read the docs and example but got error message 
`Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.`

#### node, npm, react-native, react and native-base version, expo version if used, xcode version
react-native-cli: 2.0.1
react-native: 0.64.2
react: 17.0.1
#### Expected behaviour
Toast working like Nativebase 2.0
#### Actual behaviour
Toast not working 
#### Any other additional info which would help us debug the issue quicker.

###Important

If you want your issue to be looked at quicker, attach a snack reproducible with your issue. Makes it easier for us!

**Comment by intergalacticspacehighway** [comment]
@mrezzaaa The error states that you're using `useToast` hook outside of a React component. useToast can only be called in a functional component as it's a hook. Check out this example https://snack.expo.io/@nishanbende/toast-example. 
Let me know if you're still facing the issue.

**Comment by Ajamuar** [comment]
Since there has been no further activity, we are closing this issue. Please re-open it if it still doesn't work.
