### ISSUE TITLE
How is Input used to make multiline textboxes? 

### ISSUE THREAD

**Issue by jcollum** [GeekyAnts/NativeBase#376]
I'm looking for a multiline text input control. [TextArea](https://github.com/GeekyAnts/NativeBase/blob/master/Components/Widgets/Textarea.js) seems to be the right way to go but there are no docs for it. I can't figure out how to get input to do multiline either. 

```
  <InputGroup borderType='regular'>
                        <Textarea rowSpan={10} style={{
                            width: 200
                        }} placeholder='Type your text here'/>
                    </InputGroup>

```

```
InputGroup borderType='regular'>
                        <Input style={{
                            width: 200,
                            height: 300
                        }} placeholder='Type your text here'/>
                    </InputGroup>
```

Neither of those are really doing what I'm looking for.

**Comment by shivrajkumar** [comment]
just <Textarea rowSpan={10} style={{
                            width: 200
                        }} placeholder='Type your text here'/>
works

**Comment by shivrajkumar** [comment]
just <Textarea rowSpan={10} style={{ width: 200 }} placeholder='Type your text here'/> works

**Comment by jcollum** [comment]
Looks like `multiline` is the trick: 

```
  <InputGroup borderType='regular'>
                        <Input style={{
                            width: 200, height: 200
                        }}  multiline={true} placeholder='Type your text here'/>
                    </InputGroup>
```

I see `Textarea` in the source code but don't see it in the docs. Is it deprecated?

**Comment by sankhadeeproy007** [comment]
Not exactly deprecated, but since we can achieve the same results with `multiline`, we're not sure if `TextArea` will be very useful.
