### ISSUE TITLE
Are Platform Props available to all components?

### ISSUE THREAD

**Issue by beepsoft** [GeekyAnts/NativeBase#3762]
I'm using NativeBase 3.0.2 with Typescript.

I just learned about the platform specific properties `_ios, _android, _web`, which are super useful. I tried to use them on some NB components and it seems that they actually work on eg. both `View` and `Button` (the settings on these properties get applied), however TS typing is missing for `View` and my IDE is showing red wiggly lines: 

![image](https://user-images.githubusercontent.com/1926265/123540882-80e0e300-d741-11eb-9318-e0c7ea91eb74.png)

So, are these platform specific properties are intended to be available on all NB components? And if so is it just a TS typing bug for now?

**Comment by MD-REHMAN** [comment]
Thanks @beepsoft for reporting the issue, we'll fix it in the upcoming patch. And you're right **Platforms Props** are supported in all NativeBase components.

**Comment by Ajamuar** [comment]
This has been fixed in [v3.0.3](https://www.npmjs.com/package/native-base/v/3.0.3). You can try it out and if it still causes the problem, you can re-open this issue.
