### ISSUE TITLE
Actionsheet is not working in nativebase:3.0.2

### ISSUE THREAD

**Issue by govind1530** [GeekyAnts/NativeBase#3763]
**Describe the bug**
                             using action sheet example provided in doc when i click on onOpen  its through error.

**Expected behaviour** 
                           action sheet should open.

**Screenshots**
                            https://ibb.co/sJ8VWC3

**Platform**
                                   System:
                                      OS: Windows 10 10.0.10240
                                      CPU: (8) x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
                                      Memory: 2.76 GB / 7.91 GB
                                    Binaries:
                                      Node: 14.17.0 - C:\Program Files\nodejs\node.EXE
                                      Yarn: Not Found
                                      npm: 6.14.13 - C:\Program Files\nodejs\npm.CMD
                                      Watchman: Not Found
                                    SDKs:
                                      Android SDK:
                                        API Levels: 29, 30
                                        Build Tools: 29.0.2, 30.0.3
                                        System Images: android-30 | Google APIs Intel x86 Atom
                                        Android NDK: Not Found
                                      Windows SDK: Not Found
                                    IDEs:
                                      Android Studio: Version  4.2.0.0 AI-202.7660.26.42.7351085
                                      Visual Studio: Not Found
                                    Languages:
                                      Java: Not Found
                                    npmPackages:
                                      @react-native-community/cli: Not Found
                                      react: 17.0.1 => 17.0.1
                                      react-native: 0.64.2 => 0.64.2
                                      react-native-windows: Not Found
                                    npmGlobalPackages:
                                      *react-native*: Not Found

**Comment by intergalacticspacehighway** [comment]
@govind1530 can you post your code here? Seems it's like an import issue. Also, can you check out this [example](https://snack.expo.io/@nishanbende/actionsheetexample) and confirm with your code?

**Comment by govind1530** [comment]
yes, i am using example code.

**Comment by intergalacticspacehighway** [comment]
@govind1530 since it's working on snack player, I think there must be some installation or an import issue. I'll need more information to debug it. Are other components working apart from ActionSheet?

**Comment by Ajamuar** [comment]
Due to inactivity, I am closing this issue. If you still have any problem, feel free to reopen this issue.
