### ISSUE TITLE
Using <Root> from 2.13.8 to 3.0.2

### ISSUE THREAD

**Issue by md56n** [GeekyAnts/NativeBase#3768]
**Describe the bug**
I am updating as project from 2.13.8 to 3.0.2 and <Root> isn't working properly. I keep getting the error "JSX element type 'Root' does not have any construct or call signatures." Did NativeBase move away from Root?

**To Reproduce**
render() {
    return this.state.appReady ? (
      Root
        StatusBarListenerProvider
          Provider store={this.props.store}
            NativeBaseProvider theme={this.props.theme}
              Features 
            NativeBaseProvider
          Provider
        StatusBarListenerProvider
      Root
    ) : (
      AppLoading 
    );
  }

**Expected behaviour**
Render my app

**Platform**
 - any
 - Version 3.0.2

**Additional information**
I am unable to build my project. Any help is appreciated

**Comment by intergalacticspacehighway** [comment]
@md56n NativeBase v3 doesn't have a `Root` component. You just need to wrap the app with [NativeBaseProvider](https://docs.nativebase.io/setup-provider). Since you're migrating, you can join our [discord server](https://discord.com/invite/TSgCw2UPmb) to for quick communication. :)

**Comment by intergalacticspacehighway** [comment]
Closing this issue. Feel free to open a new one in case the above solution doesn't work! :)
