### ISSUE TITLE
SubURL Missing

### ISSUE THREAD

**Issue by sumittulsyan** [GeekyAnts/NativeBase#3769]
**KitchenSink Web**
**Expected**- It must show sub URL too, once one enters into any component.
**Actual**- It is not displayed.

<img width="1440" alt="Screenshot 2021-06-23 at 11 46 28 AM" src="https://user-images.githubusercontent.com/48272902/123761984-f5ea1f00-d8df-11eb-9644-0ddde08f9b22.png">

**Platform** 

- Chrome
- Firefox
- Safari
-  Brave

 **Priority**
- Medium

**Comment by Ajamuar** [comment]
Please report KitchenSink issues in the [kitchensink repo](https://github.com/nativebase/kitchen-sink/).

**Comment by sumittulsyan** [comment]
Sure
