### ISSUE TITLE
Box With Linear gradient example produces warning.

### ISSUE THREAD

**Issue by btrewern** [GeekyAnts/NativeBase#3774]
If you recreate the
**Box** -> **With Linear gradient** - https://docs.nativebase.io/box/#with-linear-gradient
with the current version of NativeBase (3.0.3) you get the following warning:

"Node of type rule not supported as an inline style"

This is on the
Android Emulator running Android 11
or Note 9 running Expo Go 2.19.6

**Comment by rayan1810** [comment]
This issue should be resolved with next release, fix merged in PR - https://github.com/GeekyAnts/NativeBase/pull/3777
