### ISSUE TITLE
Add color prop typescript definition in `Select`

### ISSUE THREAD

**Issue by intergalacticspacehighway** [GeekyAnts/NativeBase#3775]
**Describe the bug**
Using color prop we can change the color of the currently selected. See the below screenshot. Color props works but ts shows it as an error.

<img width="1212" alt="Screenshot 2021-06-30 at 12 56 17 PM" src="https://user-images.githubusercontent.com/23293248/123919453-9143c880-d9a2-11eb-8e49-9094ee3f3065.png">

**Expected behaviour**
TS should suggest color prop.

**Comment by rayan1810** [comment]
This issue has be resolved and will be fixed with the next Release.
