### ISSUE TITLE
3.0.3 / styled-components/native could not be found within the project or in these directories

### ISSUE THREAD

**Issue by naka98** [GeekyAnts/NativeBase#3778]
** Before reporting this bug, please...**
1. Check the latest documentation: https://docs.nativebase.io/
2. Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
3. Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
4. Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
5. For discussion purpose make use of NativeBase discord: https://discord.gg/TSgCw2UPmb

**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

**CodeSandBox/Snack link**
It would be easier for us to debug if you can reproduce the error in a codesandbox link or a snack link. You can use the [codesandbox template](https://codesandbox.io/s/native-base-v3-template-mq6ox)/[snack template](https://snack.expo.io/@mdrehman/nativebase-template).

**Screenshots**

**Platform**

**Additional information**
1. Add any other context about the problem here.
2. Is the bug present in both iOS and Android or in any one of them?
3. If you want your issue to be looked at quicker, please attach a snack reproducible with your issue. Makes it easier for us!

**Comment by Ajamuar** [comment]
@naka98 it would be easier for us to debug if you can add a screenshot and steps for reproduction.

**Comment by naka98** [comment]
node_modules
  ../node_modules

If you are sure the module exists, try these steps:
 1. Clear watchman watches: watchman watch-del-all
 2. Delete node_modules and run yarn install
 3. Reset Metro's cache: yarn start --reset-cache
 4. Remove the cache: rm -rf /tmp/metro-*
  1 | import React from 'react';
> 2 | import styled from 'styled-components/native';
    |                     ^
  3 | import Box from '../../primitives/Box';
  4 | import { useThemeProps } from '../../../hooks';
  5 | import type { ITagProps } from './types';.
Error: Unable to resolve module styled-components/native from /Volumes/Seagate/project/KISSOFT/ReactNative/POLESTAT_RN_project/new/EMSMobileRN/node_modules/native-base/src/components/composites/Tag/index.tsx: styled-components/native could not be found within the project or in these directories:
  node_modules
  ../node_modules

If you are sure the module exists, try these steps:
 1. Clear watchman watches: watchman watch-del-all
 2. Delete node_modules and run yarn install
 3. Reset Metro's cache: yarn start --reset-cache
 4. Remove the cache: rm -rf /tmp/metro-*
  1 | import React from 'react';
> 2 | import styled from 'styled-components/native';
    |                     ^
  3 | import Box from '../../primitives/Box';
  4 | import { useThemeProps } from '../../../hooks';
  5 | import type { ITagProps } from './types';
    at ModuleResolver.resolveDependency (/Volumes/Seagate/project/KISSOFT/ReactNative/POLESTAT_RN_project/new/EMSMobileRN/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:234:15)
    at DependencyGraph.resolveDependency (/Volumes/Seagate/project/KISSOFT/ReactNative/POLESTAT_RN_project/new/EMSMobileRN/node_modules/metro/src/node-haste/DependencyGraph.js:413:43)
    at Object.resolve (/Volumes/Seagate/project/KISSOFT/ReactNative/POLESTAT_RN_project/new/EMSMobileRN/node_modules/metro/src/lib/transformHelpers.js:317:42)
    at resolve (/Volumes/Seagate/project/KISSOFT/ReactNative/POLESTAT_RN_project/new/EMSMobileRN/node_modules/metro/src/DeltaBundler/traverseDependencies.js:629:33)
    at /Volumes/Seagate/project/KISSOFT/ReactNative/POLESTAT_RN_project/new/EMSMobileRN/node_modules/metro/src/DeltaBundler/traverseDependencies.js:645:26
    at Array.reduce (<anonymous>)
    at resolveDependencies (/Volumes/Seagate/project/KISSOFT/ReactNative/POLESTAT_RN_project/new/EMSMobileRN/node_modules/metro/src/DeltaBundler/traverseDependencies.js:644:33)
    at /Volumes/Seagate/project/KISSOFT/ReactNative/POLESTAT_RN_project/new/EMSMobileRN/node_modules/metro/src/DeltaBundler/traverseDependencies.js:329:33
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Volumes/Seagate/project/KISSOFT/ReactNative/POLESTAT_RN_project/new/EMSMobileRN/node_modules/metro/src/DeltaBundler/traverseDependencies.js:137:24)
info Run CLI with --verbose flag for more details.
Command PhaseScriptExecution failed with a nonzero exit code

**Comment by intergalacticspacehighway** [comment]
@naka98 can you verify you followed the install peer dependency step from the installation guide?

https://docs.nativebase.io/install-rn#install-dependencies

**Comment by minh-dai** [comment]
Error: Cannot create styled-component for component: undefined.

**Comment by ju5td0m7m1nd** [comment]
Get into the same issue @minh-dai mentioned.

With the dependencies

```javascript
info Direct dependencies
├─ native-base@3.0.3
├─ react-native-safe-area-context@3.2.0
├─ react-native-svg@12.1.1
├─ styled-components@5.3.0
└─ styled-system@5.1.5
```

**Comment by intergalacticspacehighway** [comment]
@ju5td0m7m1nd @minh-dai Can someone share a minimum reproducible demo with a repo? Would help us debug further!
I tried but unable to reproduce in my system.

**Comment by ju5td0m7m1nd** [comment]
@intergalacticspacehighway 

I think I found the issue, `Pressable` is introduced in `react-native > 0.63` (Ref: https://github.com/facebook/react-native/releases/tag/v0.63.0)
And it will be imported as `undefined` for `react-native < 0.63`, which will cause `styled-components` throw undefined error

**Comment by intergalacticspacehighway** [comment]
Oh right, yes. NativeBase v3 is compatible with 0.63 and above.  
https://github.com/GeekyAnts/NativeBase/#10-compatible-versions
