### ISSUE TITLE
Add an option to suppress warning of colors not being accessible

### ISSUE THREAD

**Issue by Ajamuar** [GeekyAnts/NativeBase#3785]
** Before reporting this bug, please...**
1. Check the latest documentation: https://docs.nativebase.io/
2. Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
3. Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
4. Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
5. For discussion purpose make use of NativeBase discord: https://discord.gg/TSgCw2UPmb

**Describe the bug**
We are getting an error suggesting our color scheme is not up to the prescribed contrast ratio. We want to suppress this warning.

**To Reproduce**
Steps to reproduce the behaviour:
Use any color combination that is not up to the prescribed color contrast.

**Screenshots**
![image](https://user-images.githubusercontent.com/48080578/124114024-b95a2700-da89-11eb-8520-e7d95c8855c8.png)

**Comment by rayan1810** [comment]
Fix for this released in v3.0.7, closing this issue.
