### ISSUE TITLE
use Toast in redux-saga 

### ISSUE THREAD

**Issue by Shik1997** [GeekyAnts/NativeBase#3793]
My team use  redux-saga,and I have some  request in saga function,and when i get response ,i need  a toast  to give  user a fadeback.In native base 2.0, this is feasible，but 3.0 has changed to hooks , hooks can't work in redux-saga .

**Comment by sanketsahu** [comment]
Hey @Shik1997, we are having an internal discussion. We will expose a standalone toast in the next release. Possibly in the next 2 days. Thanks for reporting this.

**Comment by msamirma** [comment]
@sanketsahu any news about this ?

**Comment by intergalacticspacehighway** [comment]
@msamirma we'll be adding this in the 3.0.8 release.

**Comment by kuls14** [comment]
Any expected timeline for the 3.0.8 release date @intergalacticspacehighway,  I'm having this same issue.

**Comment by intergalacticspacehighway** [comment]
@Shik1997 @kuls14 @msamirma This has been released in 3.1.0. You can check out the standalone toast example here. https://docs.nativebase.io/toast#standalone-toast
