### ISSUE TITLE
error at 'Fab' demo at demo site

### ISSUE THREAD

**Issue by shootermv** [GeekyAnts/NativeBase#3794]
![image](https://user-images.githubusercontent.com/1336862/124431864-9ecdc980-dd79-11eb-96c7-42078e747a2e.png)

**Describe the bug**
Error at demo site .

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'https://docs.nativebase.io/FAB#basic'
2. you will see error instead of demo component

**Comment by intergalacticspacehighway** [comment]
Thanks for reporting. It has been fixed in the new version :)
https://docs.nativebase.io/FAB#basic
