### ISSUE TITLE
Responsive SSR support

### ISSUE THREAD

**Issue by petrbela** [GeekyAnts/NativeBase#3801]
First of all, great improvements in the v3 of the library!

One thing that I think is still missing from "full" web support is handling responsiveness for server-side rendering. The server obviously doesn't know what size the device is going to have, which means it has to render a size-neutral output, otherwise reconciliation on the client wouldn't match. There are generally two ways to approach this:

1. Skip responsive components on the server, just return `null`, do the same on the first client render, and only after `useEffect` runs, update state that would cause an actual render of the component with the responsiveness in mind. (This is, for example, what https://github.com/nandorojo/dripsy#for-ssr-apps-nextjs-gatsby-etc does.)

2. A better, although a more complicated approach is to render the responsive styles as media queries. Since the rendered output is device-size agnostic, it can be pre-rendered on the server, and the browser automatically picks whatever applies to it. The downside, if the component tree needs to be different for different device sizes (e.g. render different content and/or very different layout between mobile and desktop), is that you can't easily do a conditional rendering of components based on device size; rather you have to render everything and then use `display: none` in media queries to hide the sizes you don't want. This library https://github.com/kasinskas/react-native-media-query helps to collect media queries and render them on web while also handling the React Native side.

I understand if you decide to go with the first approach but I'd at least like to open a discussion about supporting media-query-based responsiveness and see how complicated it would be.

**Comment by sanketsahu** [comment]
Thank you for sharing your ideas around the "full" web support. We have noted both the points and we will give some thoughts and update this thread. We are actively working on making the web more stable.

**Comment by kisg** [comment]
I was thinking about this issue for some time and I think that the best approach would be to support both options. As usual, there is no silver bullet and each approach has its own advantages and valid use cases:
- The media query based approach is great for "normal" websites where NativeBase is used with e.g. Gatsby or NextJS.
- For more complex, app-like experience simply resorting to client side rendering for responsive layouts is probably a good tradeoff.

My use case for NativeBase would be a potential new frontend for Frappe (frappeframework.com) and ERPNext (erpnext.com) which is based on Frappe. My requirements are to use a single set of components that can be used with React Native on Android and iOS (both mobile and tablet layouts), and also on the web: both in a client side rendered single page app and also server rendered "regular" web pages.

The goal would be to use a single frontend technology regardless of the platform to quickly build business apps with Frappe / ERPNext.

**Comment by redbar0n** [comment]
I’ve dived into this a bit, and wrote this up that may help with some insights: 

https://github.com/nandorojo/dripsy/discussions/109#discussioncomment-848718

Overview summary of current strategies for users:

https://dev.to/redbar0n/how-to-combine-react-native-web-responsivity-nextjs-ssr-to-get-seo-a4g

**Comment by grumpyshiba** [comment]
[react-native-media-query](https://github.com/kasinskas/react-native-media-query ) is awesome. It might be built-in feature for nativebase.

So the solution is quite simple: we always render an element even regardless of it's a desktop or mobile layout but control styling using media queries on web and media queries evaluation (aka `useMediaQuery`) in mobile app.

It can be redone by nativebase app devs just using styled-components global styles definition in their factory component.

**Comment by redbar0n** [comment]
also check out how https://tamagui.dev/ solves it. It's the only cross-platform UI kit that currently has it solved, to my knowledge.

**Comment by redbar0n** [comment]
> So the solution is quite simple: we always render an element regardless of it's a desktop or mobile layout but control styling using media queries on web

Yes, that's also the rationale I've laid out here: https://github.com/yocontra/react-responsive/issues/162#issuecomment-996224622

The alternative would be to use something like [Fresnel](https://github.com/artsy/fresnel), to render the markup conditionally, but that seems way too complex for what it's worth (shaving off a few kb of HTML, instead of going [mobile first](https://dev.to/redbar0n/how-to-combine-react-native-web-responsivity-nextjs-ssr-to-get-seo-a4g), or simply having different urls, which would be more in line with the web as well, as per the aforementioned rationale).

**Comment by grumpyshiba** [comment]
@redbar0n Nah I guess real mobile-first isn't quite possible (in real-world projects, not in some MVP).
Since you can't detect viewport size on the server-side, nothing else but media queries on the web will work properly.
In that case, we render **both** desktop and mobile experiences on the web.
It leads to some duplication though (like in every single responsive layout on the web) but it wouldn't "blink" the way content blinks when it's hydrated differently.

**Comment by sanketsahu** [comment]
Responsive SSR is our priority for this week. We hope to fix it soon!

**Comment by vidhi499** [comment]
@petrbela We fixed the above in the latest release of native-base(3.3.3). We are now implementing the styles using media query, this will also solve the flicker issue caused by forced re render. You can. checkout the implementation here.

**Comment by redbar0n** [comment]
Awesome! I would include such an important update in a release message, if I were you. It didn't seem to be mentioned at all in the [3.3.3 release](https://github.com/GeekyAnts/NativeBase/releases/tag/v3.3.3).
