### ISSUE TITLE
how to horizontally scrollable header tab and switch tab by swipe tab content in v3

### ISSUE THREAD

**Issue by samuelzega** [GeekyAnts/NativeBase#3809]
**Still not found a way to make tab header scrollable**
can somebody please help me how to
- make the header tab scrollable
- switch tab by swipe tab content

**Here is the code i try**

`
import React from 'react';
import {Tabs} from 'native-base';
import {Text, View, ScrollView} from 'react-native';
export default function TabComponent() {
  return (
    <Tabs isManual={false} colorScheme="haha">

      <Tabs.Bar style={{borderBottomColor: 'transparent'}}>
        <Tabs.Tab>one</Tabs.Tab>
        <Tabs.Tab>two</Tabs.Tab>
        <Tabs.Tab>three</Tabs.Tab>
        <Tabs.Tab>four</Tabs.Tab>
        <Tabs.Tab>five</Tabs.Tab>
        <Tabs.Tab>eight</Tabs.Tab>
        <Tabs.Tab>nine</Tabs.Tab>
        <Tabs.Tab>ten</Tabs.Tab>
      </Tabs.Bar>

      <Tabs.Views>
        <Tabs.View>one</Tabs.View>
        <Tabs.View>two</Tabs.View>
        <Tabs.View>three</Tabs.View>
        <Tabs.View>four</Tabs.View>
        <Tabs.View>five</Tabs.View>
        <Tabs.View>eight</Tabs.View>
        <Tabs.View>nine</Tabs.View>
        <Tabs.View>ten</Tabs.View>
      </Tabs.Views>
    </Tabs>
  );
}
`

**Screenshots**

![Screen Shot 2021-07-07 at 17 15 50](https://user-images.githubusercontent.com/56619279/124742630-1ac93c80-df47-11eb-8609-790087b30bcb.png)

**Comment by intergalacticspacehighway** [comment]
@samuelzega Thanks for reporting the issue. 
Tab is currently under development. It's still exported, but not recommended to use. You can use React Native tab view in the meantime. Check out this recipe.
https://docs.nativebase.io/buildingTabView

We'll cover most of the cases you mentioned when it's officially released. Closing this issue for now.
