### ISSUE TITLE
[Request]: Possible Support For the Sx Prop

### ISSUE THREAD

**Issue by cmaycumber** [GeekyAnts/NativeBase#3813]
It seems like a lot of the inspiration from v3 came from chakra-ui and styled-system. It really does look great. 

Our team really enjoys using the `sx` prop because it groups styles in a relatively readable manner vs. the prop based style approach. 

Chakra and Theme UI currently support this approach. Do you think there'd be any consideration in supporting the `sx` prop in NativeBase?

**Comment by surajahmed** [comment]
@cmaycumber We're considering adding `sx` prop in NativeBase. This will help the user to pass any valid CSS to the element.  

However, we can pass any valid react style attribute in `_android`, `_ios` or `_web` props.
```
<Box
 _web={{
    style: { backgroudColor: "red"}
   }}
   _ios={{
    style: { backgroudColor: "blue"}
   }}
>
  Hello!
</Box>
```
Hope to add `sx` prop soon, thank you!

**Comment by kylegwalsh** [comment]
Does the `closed as completed` status mean that this feature was included in the latest version? Or was it simply marked as stale?

I still feel like this would be valuable from an organization standpoint (all styles live in the `sx` prop). Obviously, it's all personal preference, but it seems pretty standard in other libraries.
