### ISSUE TITLE
Hovered state does not work properly

### ISSUE THREAD

**Issue by cmaycumber** [GeekyAnts/NativeBase#3814]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to https://docs.nativebase.io/pressable#accessing-events-hover-focus-and-pressed
2. Hover over web preview
4. Notice the pressable does not register the hover 

**Expected behaviour**
Hover is applied to pressable components e.i Button, Pressable, etc. 

**CodeSandBox/Snack link**
Does not work here as referenced in documentation: https://docs.nativebase.io/pressable#accessing-events-hover-focus-and-pressed

**Platform**
 - OS: [MacOS]
 - Browser [Chrome]

**Additional information**
1. Seems like this is also affecting the `_hover` prop

**Comment by intergalacticspacehighway** [comment]
@cmaycumber Can you confirm if your react-native-web's version is 15+? Hover support on Pressable  was added in react-native-web 0.15. 
On expo snack it won't work as it's using react-native-web 0.13 and there's no way to customise it.

**Comment by cmaycumber** [comment]
Gotcha, currently I'm using v14 where hovered support does seem to be added: https://github.com/necolas/react-native-web/releases/tag/0.14.0.  

I was able to reproduce it on a test page on my app where the normal react-native pressable does work with hovered and the isHovered from `native-base` doesn't seem to work. 

Would a code sandbox help?

**Comment by intergalacticspacehighway** [comment]
Oh I see. Actually we're depending upon onHoverIn/onHoverOut for hover states which were added in 0.15.6 version. 
https://github.com/necolas/react-native-web/releases?after=0.15.6

Is it possible for you to upgrade react native web? Doesn't seem to be much breaking changes

**Comment by cmaycumber** [comment]
Yeah, I think upgrading should be fine. Let me see if I can do that real quick. 

Thanks for the quick response!

**Comment by cmaycumber** [comment]
That works! Thanks for the help much appreciated.
