### ISSUE TITLE
Best practices for animated transitions across Pressable states?

### ISSUE THREAD

**Issue by cmaycumber** [GeekyAnts/NativeBase#3816]
Are there any best practices for animating transitions from base  -> hover -> press for button state? 

I assume atm this requires a custom button component but was wondering if there might be another way to animate the transitions between different states.

**Comment by makkarMeenu** [comment]
We currently don't have that. You can make a custom wrapper for animation for your usecase.
As of now, you can pass pseudo props for hover, pressed states.
