### ISSUE TITLE
Disable FAB on a specific screens or show one screen only

### ISSUE THREAD

**Issue by entervalhalla** [GeekyAnts/NativeBase#3817]
Added a FAB on a screen in my React Native project, the FAB appears on every screen. How can I show the FAB on only one screen and not the others. The documentation is unclear on how to achieve this.

**Comment by intergalacticspacehighway** [comment]
@entervalhalla can you mount and unmount FAB when the screen is focused and unfocused respectively? 
If you're using React Navigation there's a way to know whether a screen is focused. Let me know If this works for you.
https://reactnavigation.org/docs/use-is-focused/

**Comment by intergalacticspacehighway** [comment]
Something like this
```
const isFocused = useIsFocused();

return isFocused ? <Fab /> : null
```

**Comment by intergalacticspacehighway** [comment]
We've added a prop `renderInPortal` which can be set to `false` to handle the position manually. 
This provides a workaround to control the position and mounting/unmounting FAB on a screen.
https://docs.nativebase.io/FAB#props

**Comment by DevHamzaShahid** [comment]
> We've added a prop `renderInPortal` which can be set to `false` to handle the position manually. This provides a workaround to control the position and mounting/unmounting FAB on a screen. https://docs.nativebase.io/FAB#props

thanks
