### ISSUE TITLE
[New Feature Request] Skeleton loading

### ISSUE THREAD

**Issue by deaa1111** [GeekyAnts/NativeBase#3824]
**Describe the solution you'd like**
adding skeleton component will be nice thank you for great gob.

**Comment by sanketsahu** [comment]
@vidhi499 Is this merged and released?

**Comment by vidhi499** [comment]
A PR has been created by the team for the skeleton component and it should be part of the next minor release.

**Comment by makkarMeenu** [comment]
Skeleton has been released in 3.3.0-rc.0 release.
