### ISSUE TITLE
FAB Button is hidden below the react-native-navigation nav bar on Android

### ISSUE THREAD

**Issue by bartdelange** [GeekyAnts/NativeBase#3826]
**Describe the bug**
The FAB button is hidden under the navigation element (which is a HStack in this case). Normal buttons are visible when given a absolute position and placed above the navigation component

**To Reproduce**
See https://github.com/bartdelange/FabBug for a minimal reproduction environment

**Expected behaviour**
The FAB button should be completely visible on both Android and iOS 14.5

**Screenshots**
Left the Pixel XL with android API 29 and right the iPhone 12 Pro Max with iOS
<img width="891" alt="Screenshot 2021-07-13 at 15 23 50" src="https://user-images.githubusercontent.com/32978882/125460873-3188aa27-2eb1-4e04-9cd5-1789c04e119f.png">

**Platform**
 - NativeBase version: 3.0.3
 - Device: Iphone 12 Pro Max and Google Pixel XL 
 - OS: iOS 14.5 and Android API 29:5554
 - React Native version: 0.64.2
 - node:  16.1.0
 - npm: 7.13.0

**Additional information**
1. Add any other context about the problem here.
2. Is the bug present in both iOS and Android or in any one of them?
3. If you want your issue to be looked at quicker, please attach a snack reproducible with your issue. Makes it easier for us!

**Comment by intergalacticspacehighway** [comment]
@bartdelange Issue on android is due to the elevation property. Elevation is behaving like zIndex. The BottomBar has shadow which is adding elevation of 9 on it. However, adding elevation to FAB should ideally solve it but it won't because the [absolutely positioned wrapper](https://github.com/GeekyAnts/NativeBase/blob/master/src/components/composites/Fab/Fab.tsx#L12) itself doesn't have an elevation. I hope it makes sense. We'll look how we can fix this. In the meantime, you can use below solution.

```
import React from 'react';
import {
  Button,
  extendTheme,
  Icon,
  NativeBaseProvider,
  StatusBar,
  theme,
} from 'native-base';
import 'react-native-gesture-handler';
import {NavigationContainer} from '@react-navigation/native';
import {createBottomTabNavigator} from '@react-navigation/bottom-tabs';
import Ionicons from 'react-native-vector-icons/Ionicons';
import BottomTabs from './layout/BottomTabs';
// Screens
import One from './screens/One';
import Two from './screens/Two';
import Three from './screens/Three';

const Tab = createBottomTabNavigator();

const App = () => {
  const newTheme = extendTheme({
    colors: {
      primary: theme.colors.emerald,
      secondary: theme.colors.rose,
    },
  });

  return (
    <NativeBaseProvider theme={newTheme}>
      <NavigationContainer>
        <Button
          colorScheme="secondary"
          right={8}
          rounded="full"
          height={16}
          width={16}
          position="absolute"
          bottom={30}
          shadow={9}
          style={{elevation: 11}}
          startIcon={
            <Icon as={<Ionicons name="add" />} color="white" size="30px" />
          }
        />
        <StatusBar translucent={true} barStyle={'dark-content'} />
        <Tab.Navigator
          detachInactiveScreens
          initialRouteName="one"
          lazy
          tabBar={props => <BottomTabs {...props} />}>
          <Tab.Screen
            options={{
              tabBarIcon: ({color, size}) => (
                <Icon
                  mb={1}
                  as={<Ionicons name="add-outline" />}
                  color={color}
                  size={size}
                />
              ),
            }}
            name="one"
            component={One}
          />
          <Tab.Screen
            options={{
              tabBarIcon: ({color, size}) => (
                <Icon
                  mb={1}
                  as={<Ionicons name="checkmark-done-outline" />}
                  color={color}
                  size={size}
                />
              ),
            }}
            name="two"
            component={Two}
          />
          <Tab.Screen
            options={{
              tabBarIcon: ({color, size}) => (
                <Icon
                  mb={1}
                  as={<Ionicons name="trash-bin-outline" />}
                  color={color}
                  size={size}
                />
              ),
            }}
            name="three"
            component={Three}
          />
        </Tab.Navigator>
      </NavigationContainer>
    </NativeBaseProvider>
  );
};

export default App;

```

**Comment by intergalacticspacehighway** [comment]
We've added a prop `renderInPortal` which can be set to false to handle the position manually.
This provides a workaround to control the position/elevation of FAB on a screen.
https://docs.nativebase.io/FAB#props
