### ISSUE TITLE
Button linearGradient

### ISSUE THREAD

**Issue by musetraine** [GeekyAnts/NativeBase#3827]
How do I add a gradient to a button? There is implements from the box but there is no possibility to add a gradient button?

**Comment by intergalacticspacehighway** [comment]
@musetraine The library that we're supporting expo-linear-gradient or react-native-linear-gradient both allow passing gradient to View which is used by Box in our case. We'll see how we can make it work for Buttons. Until then, you can do something like below. We'll update in the docs. Button uses HStack internally to support Icons and HStack is built using Box. So, the below code should do the trick. It's not clean to be honest, but works :D
Whatever props you'd pass to Button just pass to _stack. (Apart from position or margins)
```
import React from "react"
import { Box, Center, NativeBaseProvider, Button } from "native-base"

export const Example = () => {
  return (
    <Button
      py={0}
      _stack={{
        p: 12,
         bg:{
          linearGradient: {
          colors: ["lightBlue.300", "violet.800"],
          start: [0, 0],
          end: [1, 0],
          },
        }
      }}
      rounded="lg"
      _text={{
        fontSize: "md",
        fontWeight: "bold",
        color: "white",
      }}
    >
      This is a Box with Linear Gradient
    </Button>
  )
}

const config = {
  dependencies: {
    'linear-gradient': require('expo-linear-gradient').LinearGradient
  }
}

export default () => {
  return (
    <NativeBaseProvider config={config}>
      <Center flex={1}>
        <Example />
      </Center>
    </NativeBaseProvider>
  )
}
```

**Comment by musetraine** [comment]
> @musetraine The library that we're supporting expo-linear-gradient or react-native-linear-gradient both allow passing gradient to View which is used by Box in our case. We'll see how we can make it work for Buttons. Until then, you can do something like below. We'll update in the docs. Button uses HStack internally to support Icons and HStack is built using Box. So, the below code should do the trick. It's not clean to be honest, but works :D
> Whatever props you'd pass to Button just pass to _stack. (Apart from position or margins)
> 
> ```
> import React from "react"
> import { Box, Center, NativeBaseProvider, Button } from "native-base"
> 
> export const Example = () => {
>   return (
>     <Button
>       py={0}
>       _stack={{
>         p: 12,
>          bg:{
>           linearGradient: {
>           colors: ["lightBlue.300", "violet.800"],
>           start: [0, 0],
>           end: [1, 0],
>           },
>         }
>       }}
>       rounded="lg"
>       _text={{
>         fontSize: "md",
>         fontWeight: "bold",
>         color: "white",
>       }}
>     >
>       This is a Box with Linear Gradient
>     </Button>
>   )
> }
> 
> const config = {
>   dependencies: {
>     'linear-gradient': require('expo-linear-gradient').LinearGradient
>   }
> }
> 
> export default () => {
>   return (
>     <NativeBaseProvider config={config}>
>       <Center flex={1}>
>         <Example />
>       </Center>
>     </NativeBaseProvider>
>   )
> }
> ```

And one more question, how to style the _pressed and _disabled for this?

**Comment by intergalacticspacehighway** [comment]
Currently, _stack props can't be passed in _pressed and _disabled. We might add it in future versions. For now, you can use a workaround like below. (Similarly for disabled state)

```
import React from "react"
import { Box, Center, NativeBaseProvider, Button } from "native-base"

export const Example = () => {
  const [pressed, setPressed] = React.useState(false);
  
  return (
    <Button
      py={0}
      _stack={{
        p: 12,
         bg:{
          linearGradient: {
          colors: pressed ? ["lightBlue.400", "violet.900"] : ["lightBlue.300", "violet.800"],
          start: [0, 0],
          end: [1, 0],
          },
        }
      }}

      onPressIn={()=>setPressed(true)}
      onPressOut={()=>setPressed(false)}

      rounded="lg"
      _text={{
        fontSize: "md",
        fontWeight: "bold",
        color: "white",
      }}
    >
      This is a Box with Linear Gradient
    </Button>
  )
}

const config = {
  dependencies: {
    'linear-gradient': require('expo-linear-gradient').LinearGradient
  }
}

export default () => {
  return (
    <NativeBaseProvider config={config}>
      <Center flex={1}>
        <Example />
      </Center>
    </NativeBaseProvider>
  )
}
```
