### ISSUE TITLE
Docs about how to upgrade from 2.x.x to 3.x.x

### ISSUE THREAD

**Issue by mbernardes19** [GeekyAnts/NativeBase#3828]
Sorry if there's already any doc about it, but as far as I could search, I couldn't find any.

I'm considering upgrading from 2.15.2 to the latest 3.0.3 in a project, but I'm not sure what were the breaking changes between these major versions, so I'd like to know it to be sure of how much effort I'd need to invest in that upgrade.

**Comment by intergalacticspacehighway** [comment]
@mbernardes19 We have a [migration guide here](https://docs.nativebase.io/migration/Guide).
v3 is a complete rewrite of v2 and it also changes the philosophy from being platform specific to platform agnostic. 
You'll have to rewrite significant amount of code If you're considering migration.

**Comment by melvinchng** [comment]
@intergalacticspacehighway Do you have any information on upgrading v2.x to v3.x for Vue Native? Is Native Base v3.x still supporting Vue Native?

**Comment by realtril** [comment]
@jakemwood have you found new migration guide?

**Comment by intergalacticspacehighway** [comment]
@jakemwood @realtril you can find it here. https://docs.nativebase.io/migration/action-sheet

**Comment by realtril** [comment]
@intergalacticspacehighway seems to be stuff I am looking for. Thank you!

**Comment by realtril** [comment]
@intergalacticspacehighway do you know, can i use    ` const { isOpen, onOpen, onClose } = useDisclose();` in a class
 component?

**Comment by makkarMeenu** [comment]
> @intergalacticspacehighway Do you have any information on upgrading v2.x to v3.x for Vue Native? Is Native Base v3.x still supporting Vue Native?

No, v3.x doesn't support Vue Native.

**Comment by danielb-magnadint** [comment]
> @jakemwood @realtril you can find it here. https://docs.nativebase.io/migration/migration-guide-three For component migration - https://docs.nativebase.io/migration/action-sheet

doesnt exists anymore

**Comment by karocksjoelee** [comment]
Links are not working anymore

**Comment by afXIII** [comment]
here's the new link: https://docs.nativebase.io/migration/v3
