### ISSUE TITLE
Removing FooterTab Button background color

### ISSUE THREAD

**Issue by mrpatiwi** [GeekyAnts/NativeBase#383]
There is no documentation about how to remove the background color of a `active={true} button inside a `FooterTab`.

![image](https://cloud.githubusercontent.com/assets/7570744/21472205/a146a130-caac-11e6-8fb7-1af5ca7cf698.png)

> I would like to remove the blue background color of the button.

Also `rounded={false}` doesn't remote the round edges.

**Comment by SupriyaKalghatgi** [comment]
@mrpatiwi 
Check this

![screen shot 2016-12-26 at 7 56 57 pm](https://cloud.githubusercontent.com/assets/13464885/21483287/84eb55c2-cba5-11e6-897e-a24084036848.png)


This has been documented here [Theme FooterTab](http://nativebase.io/docs/v0.5.13/customize#themeFooterTabs)

**Comment by SupriyaKalghatgi** [comment]
@mrpatiwi Well the `Button` props doesn't go with FooterTab.
To be fixed soon.

**Comment by sankhadeeproy007** [comment]
Please make your changes to the theme file here
https://github.com/GeekyAnts/NativeBase/blob/master/Components/Themes/light.js#L114
To be released with next update. Use from master if urgent.
