### ISSUE TITLE
Avatar with conditional badge does not work

### ISSUE THREAD

**Issue by t1gor** [GeekyAnts/NativeBase#3836]
**Describe the bug**
Rendering <Avatar> component with conditional children results in errors.

**To Reproduce**
```tsx
<Avatar source={{uri: 'http://placehold.it/32x32'}}>
	{username.substr(0, 2).toUpperCase()}
	{isOnline && <Avatar.Badge bg="success.500" />}
</Avatar>
```

**Expected behaviour**
Badge should be rendered only when condition is evaluated as `true`.

**CodeSandBox/Snack link**
[![Edit priceless-banzai-viwtb](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/priceless-banzai-viwtb?fontsize=14&hidenavigation=1&theme=dark)

**Screenshots**
![simulator_screenshot_9DFDDD6F-5835-4112-9794-CD04538B9E8C](https://user-images.githubusercontent.com/1280013/125779015-fbdbe3b0-f724-4b8d-a462-66a46220528d.png)

**Platform**
 - NativeBase version: 3.0.3
 - Device: iPhone12 Pro Max (emulator)
 - OS: iOS
 - Expo sdk version: 40.0.1
 - node: 12.13.0
 - yarn: 1.22.10

**Additional information**
Error: `TypeError: Cannot read property 'type' of null`

**Comment by t1gor** [comment]
For someone facing the same issue, a quick-fix would be to use an array of children:

```tsx
// prepare children
const avatarContent: React.ReactChild[] = [
	username.substr(0, 2).toUpperCase(),
];

if (channelVM.isOnline) {
	avatarContent.push(<Avatar.Badge bg="success.500" />);
}

// and then in rendering:
<Avatar source={{uri: 'http://placehold.it/32x32'}}>
	{avatarContent}
</Avatar>
```

**Comment by cyrus25** [comment]
@t1gor This issue has been fixed.
