### ISSUE TITLE
InputGroup and Input does not render label when inside composite component

### ISSUE THREAD

**Issue by esbenp** [GeekyAnts/NativeBase#384]
I am trying to make a composite component that consists of a `InputGroup` and an `Input` but I am getting really strange results. I am new to react native, so unsure on how to debug this effectively. Basically If a create component like this.

It will not render the label when used. But if I render the `InputGroup` and `Input` components directly it will render correctly.

```
import { InputGroup, Input } from 'native-base'

const Test = props => (
  <InputGroup>
    <Input inlineLabel label="Some label" placeholder="What the devil" />
  </InputGroup>
)

export default class NativeBaseTest extends Component {
  render() {
    return (
      <Container>
        <Content>
          <List>
            <ListItem>
              <Test />
            </ListItem>
            <ListItem>
              <InputGroup>
                <Input inlineLabel label="Some label" placeholder="What the devil" />
              </InputGroup>
            </ListItem>
          </List>
        </Content>
      </Container>
    );
  }
}
```

<img width="369" alt="screen shot 2016-12-25 at 21 42 47" src="https://cloud.githubusercontent.com/assets/934819/21472839/28a04c2e-caeb-11e6-8d49-07f5e4ba3bbd.png">

I have created a repo for the code above here https://github.com/esbenp/native-base-test/commit/14560926318b0b22f10c0da1e63688ea1543e391

**Comment by esbenp** [comment]
Already seems I found the reason. `inlineLabel` only works for `Input`s that are the 2nd-level descendant of a ListItem (check this line https://github.com/GeekyAnts/NativeBase/blob/1bf4710496c338faeda71eda2fc8c89ff401d19c/Components/Widgets/ListItem.js#L343)

So when doing a composite component like `Test` the `Input` will be a 3rd-level descendant and therefore `inlineComponentPresent` will be `false`.

**Comment by sankhadeeproy007** [comment]
Thanks for pointing out. This is something we're considering looking into in our next releases.
