### ISSUE TITLE
Bold/Italics don't work in V3.0.4

### ISSUE THREAD

**Issue by sohcah** [GeekyAnts/NativeBase#3840]
**Describe the bug**
Bold and Italics properties don't work on <Text> and <Heading> elements following upgrade from `3.0.3` to `3.0.4`

**To Reproduce**
View the text in the Snack link below.

**Expected behaviour**
Text "Bold" should be in bold, and text "Italics" should be in italics. Works correctly using 3.0.3, but fails on 3.0.4.

**CodeSandBox/Snack link**
https://snack.expo.io/GJLNRZm6L

**Screenshots**
V3.0.3
![Screenshot 2021-07-15 at 14 59 53](https://user-images.githubusercontent.com/51970078/125800696-ead439ef-862b-4b18-842a-9a4226687b0e.png)

V3.0.4
![Screenshot 2021-07-15 at 14 59 24](https://user-images.githubusercontent.com/51970078/125800625-949a7787-3acc-43b1-bfcd-454af0620677.png)

**Platform**
 - NativeBase version 3.0.4
 - Device: 2020 MacBook Air (M1)
 - OS: MacOS 11.4
 - Browser: Vivaldi (Chromium Based)
 - Browser version: 4.0.2312.38 (Stable channel) (arm64)
 - React Native version: 0.63
 - Expo SDK version: 42
 - node: ??
 - yarn or npm: ??

**Additional information**
Also reproducible on Chrome on Windows

**Comment by intergalacticspacehighway** [comment]
@sohcah We just pushed 3.0.5 with the fix. Thanks for reporting!
