### ISSUE TITLE
[Input + Modal, mobile] Unexpected behavior when typing characters in some languages

### ISSUE THREAD

**Issue by tell-y** [GeekyAnts/NativeBase#3847]
## About the bug
When I type Japanese characters at the Input component is in the Modal component, the keyboard behavior is unexpected. It does not work the feature to convert Hiragana into Kanji characters.
You can see what happens here. It seems like the enter key is pressed after you type one word.
https://user-images.githubusercontent.com/6883692/126018766-2d8da995-f863-46a1-8e45-713627644eb2.mov

My expected behavior is like the first part of the video.

## Snack link
https://snack.expo.io/qyy3f4YYr

**Platform**
 - NativeBase version: 3.0.6
 - Device: iPhone8
 - OS: iOS14.6
 - Expo sdk version: 42.0.1

## Additional information
- I observe it in Chinese too. Not only Japanese.

**Comment by madhav23bansal** [comment]
Hi @tell-y, we are working on the fix. For now, the workaround for this problem can be moving the input component outside your main component.
```
import React from "react";
import { Input, Center, NativeBaseProvider, Modal, Button } from "native-base";
export const Example = () => {
  const [open, setOpen] = React.useState(false);
  const [text, setText] = React.useState("");
  return (
    <>
      <Input
        p={2}
        placeholder="Native Base"
        value={text}
        onChangeText={(value) => setText(value)}
      />
      <Button onPress={() => setOpen(true)}>open modal</Button>
      <Modal isOpen={open} onClose={() => setOpen(false)}>
        <Modal.Content maxWidth="400px">
          <Modal.Body>
            <InputComponent></InputComponent>
          </Modal.Body>
        </Modal.Content>
      </Modal>
    </>
  );
};

const  InputComponent = () => {
  const [text2, setText2] = React.useState("");
  return (
    <Input
      p={2}
      placeholder="Native Base"
      value={text2}
      onChangeText={(value) => setText2(value)}
    />
  );
};

export default () => {
  return (
    <NativeBaseProvider>
      <Center flex={1}>
        <Example />
      </Center>
    </NativeBaseProvider>
  );
};
```
