### ISSUE TITLE
Checkbox styles

### ISSUE THREAD

**Issue by musetraine** [GeekyAnts/NativeBase#3848]
Hi, could someone tell me how to change the color of the checkmark in Checkbox?

**Comment by intergalacticspacehighway** [comment]
You can do it like this
```
  <Checkbox value="test" 
      _checkbox={{
        _checked:{
          bg:"black",
          borderColor: "black"
        }
      }}
    />
```
For more configurations, checkout the default theme of checkbox https://github.com/GeekyAnts/NativeBase/blob/development/src/theme/components/checkbox.ts

**Comment by musetraine** [comment]
> You can do it like this
> 
> ```
>   <Checkbox value="test" 
>       _checkbox={{
>         _checked:{
>           bg:"black",
>           borderColor: "black"
>         }
>       }}
>     />
> ```
> 
> For more configurations, checkout the default theme of checkbox https://github.com/GeekyAnts/NativeBase/blob/development/src/theme/components/checkbox.ts

You solution don't change color of checkmark =(
I need to make the color of the checkmark black, I could not even imagine that it was so difficult

**Comment by intergalacticspacehighway** [comment]
@musetraine Please check this out and let me know If it works
https://snack.expo.io/msALTSZcx

**Comment by intergalacticspacehighway** [comment]
To change the checkmark
```
<Checkbox value="test"
      _icon={{color: "black"}}
/>
```
