### ISSUE TITLE
How do you combine styles in v3

### ISSUE THREAD

**Issue by hankduan** [GeekyAnts/NativeBase#3853]
traditionally, you can combine style objects as array: 
```
const style1 = { color: 'white', fontSize: 10}
const style2 = { marginLeft: 2}
const combinedStyle = [style1, style2]
```
How do you do this in v3?

**Comment by intergalacticspacehighway** [comment]
@hankduan You can combine and pass styles like above in NativeBase components. <Box style={[style1, style2]} />. 
The only downside is that it won't pick theme token values. 

Is there any use-case where you need an array and can't use something like below?
`<Box color="white" fontSize={10} ml={2} />`

You can also just spread them as objects. e.g.

const style1 = { color: 'white', fontSize: 10}
const style2 = { marginLeft: 2}

const style = {...style1, ...style2} 
`<Box {...style} />`

**Comment by hankduan** [comment]
I see, thank you for that!
