### ISSUE TITLE
Partial migration

### ISSUE THREAD

**Issue by hankduan** [GeekyAnts/NativeBase#3855]
Given that the change is so large between v2 and v3, it's not feasible to migrate in one go for larger projects.

What do you think about providing the possibility to have coexisting v2 and v3 libraries, to allow users to migrate from v2->v3 in a piecemeal manner?

**Comment by makkarMeenu** [comment]
@hankduan You can follow https://discord.com/channels/785491682719301643/829984794523598848/846459378496569424
regarding this. There is a workaround that somebody shared regarding the same.
