### ISSUE TITLE
[Question] Are custom style classes supported in v3?

### ISSUE THREAD

**Issue by cristianoccazinsp** [GeekyAnts/NativeBase#3863]
Currently using v2 with an ejected theme and many customizations (custom class/attributes).  Is this something still supported in v3? How does one do it?

**Comment by intergalacticspacehighway** [comment]
@cristianoccazinsp You can use extendTheme to change a component's or default theme's styles
https://docs.nativebase.io/customizingTheme
https://docs.nativebase.io/customizingComponents
