### ISSUE TITLE
Add a style prop to Toast in version 3 as available in version 2

### ISSUE THREAD

**Issue by Jaybee4real** [GeekyAnts/NativeBase#3865]
Text overflows if content is more than 5 words

It would be really nice to have a style prop to the custom provided/default native base toast instead of having to create a custom toast everytime i want something to be displayed nicely if the text overflows as in picture (see picture)

<img width="435" alt="Screenshot 2021-07-22 at 09 20 28" src="https://user-images.githubusercontent.com/51276685/126610596-835cf30a-3339-49c1-8279-33b1f3fa8850.png">

**Comment by intergalacticspacehighway** [comment]
Thanks for reporting!
@amars29 I think you made a PR. Is this the same issue?

**Comment by amars29** [comment]
@intergalacticspacehighway yes, it will get resolved in our next release.

**Comment by amars29** [comment]
we don't need style prop to use styles here. You can directly apply them as key/value pair, along with title and description.

Example:
 ```
<Button
        onPress={() =>
          toast.show({
            title: 'Hello world',
            placement: 'top-right',
            backgroundColor: 'pink.400',
          })
        }
      >
        Top right
</Button>
```

**Comment by intergalacticspacehighway** [comment]
@Jaybee4real Closing this issue for now. If the above solution doesn't work, let us know.
