### ISSUE TITLE
Pointer cursor outside of modal and menu

### ISSUE THREAD

**Issue by treyshedrick** [GeekyAnts/NativeBase#3868]
![Screen Shot 2021-07-22 at 12 30 55 PM](https://user-images.githubusercontent.com/35882658/126684680-2ebec79c-5fa2-4733-b443-003e4e2a6931.png)

**Describe the bug**
Pointer cursor shows when hovering outside of modal (Seem to be for any overlay component)

**To Reproduce**
Steps to reproduce the behaviour:
1. Create react app with NativeBase template
2. Add a basic dropdown menu
3. See if pointer is shown outside of modal

**Expected behaviour**
A default cursor is usually shown unless its a button, link, or specified

**Platform**
 - NativeBase version 3.0.6
 - Device: Macbook Pro 2018
 - OS: MacOs Big Sur 11.3.1
 - Browser Chrome
 - Browser version 91.0.4472.164 (Official Build) (x86_64)
 - React Native Web version 0.16.5
 - node 12.20.0
 - npm 6.14.8

**Comment by makkarMeenu** [comment]
This has been resolved in NativeBase 3.2.2 .
