### ISSUE TITLE
Styles are not exposed

### ISSUE THREAD

**Issue by alexpanov** [GeekyAnts/NativeBase#387]
Hi,

Thanks for such a great component library!
I was wondering if there has been made a decision to _not_ to expose styles of components externally.

There is a use case for exposed styles in my opinion. 
I am using a custom date picker component together with NativeBase. The date picker supports styling, but unfortunately the only way to style it's input to appear exactly as NativeBase's `<Input />` is to replicate the styling logic myself.

I am aware that a Date Picker component is in the Roadmap, but the point I'm making is sort of general.

The question is, if it is not against the philosophy behind NativeBase, is it possible to expose the styles and if so, how does one do it properly?

Many thanks!

**Comment by himanshu-satija** [comment]
Thanks for bringing this use case into our notice. 

For now, you can just check the native-base code for the internal components' styles. For input, you can check it in Components/Widgets/Input.js

What do you suggest for exposing those styles? Should we provide a function for that?

**Comment by alexpanov** [comment]
@himanshu-satija 
I am not exactly sure. Maybe a static method on each of the components. There is `getInitialStyle` already.
My other option would be a separate module for styles specifically.
Unfortunately, I am not familiar with the underpinnings of NativeBase enough to propose a mature solution.
From the perspective of the user, I'd be happy with anything that would allow me to compute styles (optionally) based on a theme.

**Comment by sanketsahusoft** [comment]
@alexpanov Not sure how much value it will add. Because the styling is very much specific to each component.

The best what you can do for now is check the source of the desired component and copy to your component. For Input, you can check Input.js and copy the styling.

In the next major version, we are going to have an easier contextual styling, much like Bootstrap SCSS.
