### ISSUE TITLE
[Input] Input(Left | Right)Element displayed on focus or invalid state

### ISSUE THREAD

**Issue by mlecoq** [GeekyAnts/NativeBase#3874]
**Describe the bug**
According to the doc, `_invalid`, `_focus` ... props takes IInputProps as params.

My use case is to have a right icon (a cross mark) when Input is invalid, I wanted to use `_invalid` props

**To Reproduce**
Steps to reproduce the behaviour:

Use the following component:

``` 
    <Input
                  size="md"
                  placeholder="Email address"
                  keyboardType="email-address"
                  onBlur={onBlur}
                  onChangeText={onChange}
                  value={value}
                  autoCapitalize="none"
                  _invalid={{
                    InputLeftElement: <Icon as={<MaterialIcons name="error" />} size="md" m={2} color="red" />,
                  }}
                />
```

**Expected behaviour**
The input left element is displayed when input is invalid

**Screenshots**

**Platform**
 - NativeBase version: 3.0.6
 - Device: iPhone 12 mini
 - OS: iOS 14.6
 - React Native version: 0.63.2
 - Expo sdk version: 42
 - node: 14.16.1
 - yarn: 1.22.4

**Additional information**
1. Add any other context about the problem here. 
2. Is the bug present in both iOS and Android or in any one of them? both android and iOS
3. If you want your issue to be looked at quicker, please attach a snack reproducible with your issue. Makes it easier for us!

**Comment by Viraj-10** [comment]
This Issue is resolved in NativeBase version v3.3.0.
