### ISSUE TITLE
FooterTab Icons display problem

### ISSUE THREAD

**Issue by krouw** [GeekyAnts/NativeBase#388]
I am using FooterTab for android and I have the following problem with the icons when they are not accompanied by any label

![Error](https://s-media-cache-ak0.pinimg.com/236x/e0/fb/72/e0fb726214305314054849d892b2f641.jpg)

I found a solution modifying FooterTab.js on line 141

![code](https://s-media-cache-ak0.pinimg.com/564x/fc/f7/c0/fcf7c0fe0da66d58f0fc37f946f0ccab.jpg)
![solution](https://s-media-cache-ak0.pinimg.com/564x/e3/68/83/e36883d80189d27d2f8ac9d1ab530667.jpg)

fontSize: 28
height: 35
paddingTop: 3
paddingLeft:3

Has anyone had the same problem or used another solution?

**Comment by sankhadeeproy007** [comment]
Yes, we noticed the cropping too. Will fix it with the next update.
