### ISSUE TITLE
SimpleGrid documentation

### ISSUE THREAD

**Issue by btrewern** [GeekyAnts/NativeBase#3881]
As of the current version NativeBase 3.0.6.

1. There does not seem to be a link to the SimpleGrid in the documentation menu.
2. In the docs https://docs.nativebase.io/simpleGrid it states that **spacing** is a property of SimpleGrid but it seems it should be **space**.

**Comment by soullivaneuh** [comment]
Also, the expo sample are currently not working on the documentation page.

**Comment by makkarMeenu** [comment]
SimpleGrid is not in a stable state. So we decided to remove it from the documentation. 
We will add it soon in consecutive versions.
