### ISSUE TITLE
Error when deleting a digit from PinInput

### ISSUE THREAD

**Issue by nathanwkwong** [GeekyAnts/NativeBase#3887]
I have a simple PinInput component from native-base which I can input digit with it. An error occur when I try to delete a digit from it. And the error is shown in below.

my simple PinInput component: 

    const TestScreenTwo = () => {
        return (
            <PinInput inputSize="md">
                <PinInput.Field />
                <PinInput.Field />
                <PinInput.Field />
                <PinInput.Field />
            </PinInput>
        );
    };

<img width="188" alt="qemu-system-x86_64_07p-271839" src="https://user-images.githubusercontent.com/55337066/127140835-c4f0993b-bafa-4f62-ae12-a01c7a8f1155.png">

<img width="188" alt="qemu-system-x86_64_073-271827" src="https://user-images.githubusercontent.com/55337066/127139203-babafef9-4848-405d-8f9e-0c8b6901c275.png">

Environment: 
- platform: Andriod( on both real and virtual devices) with API 29
- npm with node: v14.16.1
- package: 
        "native-base": "^3.0.6",
        "react": "17.0.1",
        "react-native": "0.64.2",

**Comment by derrysukrie** [comment]
i had the same issue, is there any update?

**Comment by makkarMeenu** [comment]
Sorry for the trouble but Accordion is not released and supported right now. It's on the roadmap and will be supported in future release. The components present in the sidebar in the docs are the only ones that are released till now.
