### ISSUE TITLE
Issue with i18n text in buttons

### ISSUE THREAD

**Issue by gust42** [GeekyAnts/NativeBase#3888]
When wrapping text in a fragment in a button you get error:
Error: Text strings must be rendered within a <Text> component.

```
<Button>
  <>
    Text
  </>
</Button>
``` 
The real world issue with this is when when using declarative i18n components like react-intl they wrap the text in an fragment and the issue above triggers

```
<Button>
  <FormattedMessage {...beforeFirstPulseMessages.startButton} />
</Button>
```

To solve this you have to do like v2 and wrap in in a Text and then you have to style the text element for every button
```
<Button>
  <Text color="buttonTextColor">
    <FormattedMessage {...beforeFirstPulseMessages.startButton} />
  </Text>
</Button>
```

My guess is that a lot of real world apps are gonna have this issue

Let me know if i can be of any more help

**Comment by intergalacticspacehighway** [comment]
@gust42 can you verify if this is fixed in 3.0.7? We've added support for Fragment children for text.
https://github.com/GeekyAnts/NativeBase/releases/tag/v3.0.7

**Comment by gust42** [comment]
Sorry for slow response, was on vaccation, will check this later!

**Comment by gust42** [comment]
Still not working with react intl, they must be wrapping the text somehow when used in react native compared to web,

This here is the source file if someone wanna look
https://github.com/formatjs/formatjs/blob/main/packages/react-intl/src/components/message.tsx

**Comment by surajahmed** [comment]
@gust42 Wrapping of text with a fragment is working now. But this didn't solve the react-intl issue. We're looking into this.
Thanks for reporting!
