### ISSUE TITLE
How to use font-awesome icons or other type of icons that are included?

### ISSUE THREAD

**Issue by jsantana90** [GeekyAnts/NativeBase#389]
I'm having trouble using all of the icons included.

I can only use ionicons or octicons, but if I try to use, for example, [cutlery](http://fontawesome.io/icon/cutlery/) then a `?` symbol appears instead.

**Comment by sankhadeeproy007** [comment]
Change your theme file to set `FontAwesome` as the default Icon font-family.
![screen shot 2016-12-28 at 12 31 54 pm](https://cloud.githubusercontent.com/assets/10998047/21515919/af56c116-ccf9-11e6-9a2f-7b21a1e1af82.png)
Please keep in mind to import the theme file and use it as shown in the screenshot.

**Comment by OogieBoogieInJSON** [comment]
Which was the reason of not setting the icon family using a property on the ```Icon``` component ?

**Comment by godoakbrutal** [comment]
@sankhadeeproy007 
If I don't want to change at the `mainThemeFile`. So how to change iconFamily at `<Icon />` component ?

**Comment by OogieBoogieInJSON** [comment]
@godoakbrutal At this point it's not possible but there is an open merge request about this here: #1319

**Comment by waritthornnudee** [comment]
`<Icon name="flash-off" type="MaterialIcons" />`

type depend on Bundled Icon Sets

Bundled Icon Sets
Entypo
EvilIcons
Feather
FontAwesome
Foundation
Ionicons
MaterialIcons
MaterialCommunityIcons
Octicons
Zocial
SimpleLineIcons
