### ISSUE TITLE
Keyboard doesn't work on NumberInput

### ISSUE THREAD

**Issue by arndeash** [GeekyAnts/NativeBase#3894]
NativeBases Number inputs default behavior on web is to allow the keyboard up arrow and down arrow to adjust the value. It is not possible in NativeBase. Examples from other UI libs where this is working as intended: 

https://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_input_type_number
https://chakra-ui.com/docs/form/number-input

NativeBase example where this is not working:
https://docs.nativebase.io/numberInput#numberinputfield

**Comment by arndeash** [comment]
Dig a bit into this and would be solved by adding type="numeric" to the input type. Don't have time to do a PR today, but maybe I'll do it some time in the future.

**Comment by makkarMeenu** [comment]
Sorry for the trouble but NumberInput is not released and supported right now. It's on the roadmap and will be supported in future release. The components present in the sidebar in the docs are the only ones that are released till now.
