### ISSUE TITLE
Upgrading to latest version gives syntax error

### ISSUE THREAD

**Issue by Ruzen1** [GeekyAnts/NativeBase#3895]
** Before reporting this bug, please...**
1. Check the latest documentation: https://docs.nativebase.io/
2. Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
3. Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
4. Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
5. For discussion purpose make use of NativeBase discord: https://discord.gg/TSgCw2UPmb

**Describe the bug**
The real bug was that the tabs overlapped each other. I came to know it will be solved by updating the library.
So , I updated the library and found a different error now.

**To Reproduce**
Steps to reproduce the behaviour:
As soon as the app opens, it shows the error in the screenshot attached.

**Expected behaviour**
It should work smooth and the tabs should not overlap each other.

**Screenshots**
![rn_image_picker_lib_temp_cb60e959-abac-405b-a131-ba4ef506eb33](https://user-images.githubusercontent.com/25242058/127265292-1bb86b67-0de7-4ffa-b0c6-c32124dbc835.png)

**Platform**
 - NativeBase version : Before it was 2.13.8, now it is 3.0.6 
 - Device: Android shows overlapped tabs whereas, iOS continuosly moves the tabs vigorously
 - React Native version [e.g. 0.64] 0.61.3
 - node [e.g. 14.16.1]  12.6.0

**Comment by rayan1810** [comment]
@Ruzen1 you need to update to version - 2.15.2 instead of 3.0.6 . Please downgrade to version 2.15.2 . v3 doesn't support Tabs right now.

**Comment by Ruzen1** [comment]
@rayan1810 Thank you very much. Now I see.
