### ISSUE TITLE
Enable style prop array values

### ISSUE THREAD

**Issue by steida** [GeekyAnts/NativeBase#39]
Array doesn't work on Button.

```jsx
<Button style={[styles.base, styles.background]} />
```

**Comment by sankhadeeproy007** [comment]
We never tested the styles with an array. Can you tell us which of the two style classes is working?

**Comment by sanketsahusoft** [comment]
@steida We are going to fix that in the next release.
@sankhadeeproy007 Ideally, the prototype of the style property of all the NativeBase component should be exactly like the one provided by React Native.

**Comment by sankhadeeproy007** [comment]
@steida We've pushed the updates to master. Just check and let us know if that's working sowe can close this issue.

**Comment by steida** [comment]
LGTM

**Comment by iamraphson** [comment]
@sankhadeeproy007 this is not working on V2.1.0
