### ISSUE TITLE
After fab button activates, it doesn't let me press anything behind it

### ISSUE THREAD

**Issue by jsantana90** [GeekyAnts/NativeBase#390]
Having trouble with fab button.

## react-native, react and native-base version
React-native: "0.37.0",
"react": "~15.3.2",
"native-base": "0.5.15"

## Expected behaviour
When fab buttons are deactivated, it should let me press stuff behind it.

## Actual behaviour
When fab buttons are deactivated, it doesn't let me press anything behind or even scroll where the buttons once where when active.

## Steps to reproduce (code snippet or screenshot)
Add the sample from [here](http://nativebase.io/docs/v0.5.13/components#fab)

I added a border too see the effect:
`containerStyle={{ borderWidth: 1, borderColor: 'black' }}`

![nativefaverror](https://cloud.githubusercontent.com/assets/9933887/21526324/b7fffb8e-ccf9-11e6-98b1-79a66de48c01.gif)

**Edit**
Happens randomly, you have to try more than once to get the bug sometimes.

## Is the bug present in both ios and android or in any one of them?
The bug is currently present in iOS simulator (haven't tested in physical iphone) and physical android device (note 5).

**Comment by sankhadeeproy007** [comment]
Thanks for pointing it out. It has been fixed with the above commit. Use from master till we release a new update.
