### ISSUE TITLE
Preventing Duplicate Toast

### ISSUE THREAD

**Issue by Shik1997** [GeekyAnts/NativeBase#3902]
When i set placement  'top' ,Preventing Duplicate Toast  not work .but when i set placement 'bottom' is worked.
and why  can't set placement 'center',is there some problem ?

**Comment by intergalacticspacehighway** [comment]
@Shik1997 Can you check out this example I created using top placement. It prevents duplicate. 
Also, can you share a reproducible demo of the issue on snack player? 
https://snack.expo.dev/@nishanbende/toast-top-prevent-duplicate

AFAIK, placement center is not very common for toasts, so there's no center option available. Let me know the usecase. Also, you can pass top and make it center aligned if needed. 

```

toast.show({
  id,
  placement: "top",
  top: 100,
  title: "Hey! You can't create a duplicate toast",
});
    
```

**Comment by Shik1997** [comment]
> @Shik1997 Can you check out this example I created using top placement. It prevents duplicate.
> Also, can you share a reproducible demo of the issue on snack player?
> https://snack.expo.dev/@nishanbende/toast-top-prevent-duplicate
> 
> AFAIK, placement center is not very common for toasts, so there's no center option available. Let me know the usecase. Also, you can pass top and make it center aligned if needed.
> 
> ```
> 
> toast.show({
>   id,
>   placement: "top",
>   top: 100,
>   title: "Hey! You can't create a duplicate toast",
> });
>     
> ```

I found this problem in our bare React Native app,not on snack expo.I compared your demo code with mine,There is only one difference，i have  {duration: 2000 }  in options.

**Comment by chinomnsoawazie** [comment]
This issue still persits!
