### ISSUE TITLE
Testing with RNNative Testing Library

### ISSUE THREAD

**Issue by adoniscoder** [GeekyAnts/NativeBase#3907]
Hi, I'm trying to test my components that is wrapped insider `NativeBaseProvider` but the problem is that the result of the Provider's render is just an empty `RNCSafeAreaProvider`

I have a custom render wrapper to wrap all my components inside the Provider:

<img width="788" alt="Screen Shot 2021-07-31 at 11 05 19 AM" src="https://user-images.githubusercontent.com/13381026/127731150-2f6560a7-2da3-403e-9697-8e6ae9478d98.png">

and my test :

<img width="789" alt="Screen Shot 2021-07-31 at 11 05 37 AM" src="https://user-images.githubusercontent.com/13381026/127731153-84866177-76a5-4c5d-b8a3-38b075107ac5.png">

but the result is :

<img width="1131" alt="Screen Shot 2021-07-31 at 11 06 30 AM" src="https://user-images.githubusercontent.com/13381026/127731178-a2b70a97-35be-4c6f-89ce-6941008452cb.png">

**Platform**
 - NativeBase version 3.0.6
 - React Native version 0.64.1

**Comment by adoniscoder** [comment]
Seems like I had to pass the `initialWindowMetrics` prop to the `NativeBaseProvider` in order it to render its children properly.

**Comment by leoparis89** [comment]
Adding `initialWindowMetrics` as follows fixed the problem 


```
    <NativeBaseProvider
      initialWindowMetrics={{
        frame: {
          width: 320,
          height: 640,
          x: 0,
          y: 0,
        },
        insets: {
          left: 0,
          right: 0,
          bottom: 0,
          top: 0,
        },
      }}
    >
      <Box flex={1} bg="#fff" alignItems="center" justifyContent="center">
        <Text>Open up App.js to start working on your app!</Text>
      </Box>
    </NativeBaseProvider> 
```
