### ISSUE TITLE
Floating Label Input

### ISSUE THREAD

**Issue by abhiburk** [GeekyAnts/NativeBase#3908]
Well I am looking for Floating Label Input field.
I could not found it in the 3.x native base docs but was available in the previous version i.e 2.x.
If it is available in the current version please let me know where I can find

Thanks

**Comment by rayan1810** [comment]
Hey, @abhiburk it's on our roadmap, as of now we don't have a Floating Lable Input.

**Comment by georgii-ivanov** [comment]
Please do :-)

**Comment by Djauron** [comment]
There is some new ? @rayan1810 😄

**Comment by surajahmed** [comment]
We've added it to our list. However, we're not including it in a coming release. Hope to add this feature soon.

**Comment by johnf** [comment]
@surajahmed Can this be reopened?
I'm using path-package to basically bring https://github.com/GeekyAnts/NativeBase/pull/3592/files back in.
I'm simplifying it as I want it all the time, not animated in on focus.

Let me know if you want me to create a PR for it
