### ISSUE TITLE
ListItem List with note pulls text to the right - why?

### ISSUE THREAD

**Issue by stueynet** [GeekyAnts/NativeBase#391]
See this screenshot. The docs show that the note text should appear below the text but when implemented it floats it to the right.

http://d.pr/i/JmtG

**Comment by sankhadeeproy007** [comment]
That is the case for `Thumbnail`. Without thumbnail, it's configured to align to the right. We went through the design guidelines of both android and ios and there weren't any examples which reflected your use. Ofcourse we might have skipped something. To achieve this, you can add a thumbnail with 0 opacity and add some negative left margin.

**Comment by sankhadeeproy007** [comment]
Let me know if that works out for you.

**Comment by stueynet** [comment]
Ah ok. Yeah thats a bit awkward for sure since we don't always have a local image for a thumbnail. Sometimes the thumbnail needs to be Text based (for example Initials). So this forces the ListItem to use an image based thumbnail.

**Comment by sankhadeeproy007** [comment]
Yes, that is not the best possible solution I know. But it's very hard for us to keep up with requirements of projects of advanced complexities. We're planning on releasing a newer version with more customizability. Till then you can create a fork and make the required changes to NativeBase.
