### ISSUE TITLE
How to use icons dynamically

### ISSUE THREAD

**Issue by manufunk** [GeekyAnts/NativeBase#3910]
How can I use dynamic icons in v3?
In my database I have 2 values `iconType` which holds something like 'Ionicons' or 'MaterialIcons' and `iconName` which holds the name if the icon.

This is how I did it in v2.
```
 <Icon
        name={props.iconName}
        type={props.iconType}
/>
```

Is there any way to also define the `as` property inside v3 icon with dynamic string values containing the icon type?

**Comment by intergalacticspacehighway** [comment]
Hi @manufunk In v3, you can do something like this. It's a bit verbose but we decided to decouple vector or expo icons in v3. We might add a more simple way so that above syntax is possible. In the meantime, you can do below.

```
const getComponent = (iconType, iconName) => {
  switch(iconType) {
    case "MaterialIcons":
      return <MaterialIcons name={iconName} />
    case "Ionicons": 
      return <Ionicons  name={iconName} />
    default:
      return <MaterialIcons  name={iconName} />
    }
  }
  
export const Example = ({iconName, iconType}) => {
  const iconComponent = getComponent(iconName, iconType);
  return (   
      <Icon as={iconComponent} />
  )
}

```

**Comment by manufunk** [comment]
Thank you for the hint. I thought maybe there is a nicer solution for this because it could be any type of icon which is a very long list. But I guess for now I will follow your suggestion until there is a more dynamic way. Should I create a feature request for it to have it in the backlog?

**Comment by makkarMeenu** [comment]
A solution similar to above solution works in v3 now. Check third party icons documentation [here](https://docs.nativebase.io/icon#integration-with-third-party-icons)
