### ISSUE TITLE
TextArea shifts cursor to center of Input on focus

### ISSUE THREAD

**Issue by intergalacticspacehighway** [GeekyAnts/NativeBase#3914]
Reproducible demo - https://snack.expo.dev/@arturs_osp/example?

Steps:
- Open above example in android
- Focus on the TextArea input.
- Cursor jumps to center

https://user-images.githubusercontent.com/23293248/127818995-7d1c9bdf-342f-46d0-b6cf-86383cb699d5.mp4

**Comment by rayan1810** [comment]
You can refer this => https://snack.expo.dev/@rayan117/textarea-text-vertical-top, passing `textAlignVertical` as a prop works as expected. Passing it in style reproduces the above issue though.
