### ISSUE TITLE
Error after import components in React Native Base

### ISSUE THREAD

**Issue by tranquang7979** [GeekyAnts/NativeBase#392]
## react-native, react and native-base version
    "native-base": "^0.5.20",
    "react": "15.4.1",
    "react-native": "0.39.2"

## Expected behaviour
I tried to ran source at http://nativebase.io/docs/v0.5.13/components#anatomy 

## Actual behaviour
I run app and get error (red screen)

## Steps to reproduce (code snippet or screenshot)
I'm using Mac to develop my app. 
After I finish the installation follow http://nativebase.io/docs/v0.5.13/getting-started
I tried to imported source at http://nativebase.io/docs/v0.5.13/components#anatomy 
I run app and get error (red screen)

## Screenshot of emulator/device
![simulator screen shot dec 29 2016 11 00 13 pm](https://cloud.githubusercontent.com/assets/2139635/21547783/cc301bf8-ce1a-11e6-8154-a544c784fb1c.png)

## Is the bug present in both ios and android or in any one of them?
I just tried on the Mac OS

## Sample here 
http://www.alogiatot.com/AwesomeNativeBase.zip

**Comment by sankhadeeproy007** [comment]
Please try to remove all whitespace in and around line 16  of your code. It is possible that some stray characters got copied with the example in the docs. If possible try typing out the code. Should fix it.

**Comment by tranquang7979** [comment]
Solved. Thank you so much!
