### ISSUE TITLE
FlatList Showing Error Bugs

### ISSUE THREAD

**Issue by gakinson** [GeekyAnts/NativeBase#3924]
** Before reporting this bug, please...**
1. Check the latest documentation: https://docs.nativebase.io/
2. Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
3. Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
4. Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
5. For discussion purpose make use of NativeBase discord: https://discord.gg/TSgCw2UPmb

**Describe the bug**
When using a FlatList (nativebase), I am setting the stickyHeaderIndices to [0] to make the header component stick to the top and I get an error saying:

`
Render Error
number 0 is not iterable
`

If I change the param to [[0]], then it works, but I get a typescript error saying that [[0]] is not number[].

**To Reproduce**
Steps to reproduce the behaviour:
See sandbox link to recreate code

**Expected behaviour**
FlatList works as documented, no typescript errors

**CodeSandBox/Snack link**

https://codesandbox.io/s/flatlist-bug-ddcbc?file=/src/components/Example.tsx

**Screenshots**
![Screen Shot 2021-08-03 at 9 00 27 AM](https://user-images.githubusercontent.com/3464973/128048029-56704fb2-abac-4d2d-8f65-82c1393e66d3.png)

**Platform**
 - NativeBase version 3.0.6
 - Device: Simulator IPhone 12
 - OS: 14.5
 - React Native version 0.64.1
 - Expo sdk version [e.g. 41]
 - node v12.22.1
 - yarn or npm: npm 7.16.0

**Additional information**
Only being tested on IOS (not android)

**Comment by kytosai** [comment]
Mee too, i cannot use prop **stickyHeaderIndices** with FlatList in native-base, I must use FlatList of react-native alter

**Comment by makkarMeenu** [comment]
This is fixed now in newer version of NativeBase, please re-open if you still face the same.
