### ISSUE TITLE
Expo Tabs (Typescript) + Native Base Template

### ISSUE THREAD

**Issue by Psycarlo** [GeekyAnts/NativeBase#3925]
**Motivation**
Expo Tabs Template (Typescript) is a very used template to get started with react native. Native Base is on of the most used UI frameworks for react native. Why don't combine these two together? This template could make it easier for people to get started with expo and native base.

**Feature Description**
Create a Native Base template based on expo tabs template (typescript):
- Easy to customize light and dark themes (or maybe more);
- Toggle between light and dark theme (system and/or user preference);
- Refactor/Remove expo tabs template code.

**Comment by surajahmed** [comment]
@Psycarlo We'll update our documentation with this template. Thank you!
