### ISSUE TITLE
useSystemColorMode doesn't work

### ISSUE THREAD

**Issue by intergalacticspacehighway** [GeekyAnts/NativeBase#3927]
Docs mention a prop called [useSystemColorMode](https://docs.nativebase.io/color-mode#default-color-mode).

When this prop is `true`, NativeBase colorMode should be set based on the user's system color mode preference. 

To achieve this, we can use [useColorScheme](https://reactnative.dev/docs/usecolorscheme) hook from react native. If the `useSystemColorMode` is `true`, we need to initialize the default color mode to value returned from `useColorScheme`

**Comment by Psycarlo** [comment]
**Very important feature!**

**Comment by intergalacticspacehighway** [comment]
@Psycarlo This has been released in 3.1.0
