### ISSUE TITLE
AlertDialog properties not found and crash

### ISSUE THREAD

**Issue by ugar0ff** [GeekyAnts/NativeBase#3934]
Not all of AlertDialog properties are found:
![Снимок экрана от 2021-08-05 22-26-10](https://user-images.githubusercontent.com/14922730/128409516-08396691-063b-4547-89ea-95421ba3959d.png)
![Снимок экрана от 2021-08-05 22-26-22](https://user-images.githubusercontent.com/14922730/128409524-4ba58315-19da-4b62-91db-2b45367bc698.png)

_Type '{ children: Element; leastDestructiveRef: MutableRefObject<undefined>; isOpen: boolean; onClose: () => void; isCentered: true; }' is not assignable to type 'IntrinsicAttributes & IAlertDialogProps & { ref?: any; }'.
  Property 'isCentered' does not exist on type 'IntrinsicAttributes & IAlertDialogProps & { ref?: any; }'.ts(2322)_

Me imports:
`import { Pressable, AlertDialog, Text } from 'native-base';`

Also I have a crash after close AlertDialog and moving by stack:
![Снимок экрана от 2021-08-05 22-31-07](https://user-images.githubusercontent.com/14922730/128409872-494955bd-c514-4ce5-84e2-80d5294c9731.png)
but maybe it is same problem.

Android_Pixel_4_API_30
"native-base": "3.0.7",
"react-native": "0.64.2",
node v14.15.4
yarn v1.22.10

**Comment by ugar0ff** [comment]
Steps to reproduce crash:
1. Go to N screen in stack (react-navigation)
2. Open AlertDialog 
3. Go back 
4. Return to N screen

**Comment by surajahmed** [comment]
@ugar0ff  @kytosai This issue has been resolved in version `3.3.0` or later. Thanks for reporting.
