### ISSUE TITLE
NPM 7 install and build issues

### ISSUE THREAD

**Issue by gyandeeps** [GeekyAnts/NativeBase#3938]
**Describe the bug**

`"native-base": "^3.0.7"`

When i install react-native using `npm 7.20.3` via nodejs 16 (latest) than the install is successful but when i try to run the code I get the following error:

```sh
/<path>/node_modules/native-base/lib/commonjs/components/composites/Menu/useMenu.js
Module not found: Can't resolve '@react-aria/focus' in '/<path>/node_modules/native-base/lib/commonjs/components/composites/Menu'
```

The error happens because menu component [here](https://github.com/GeekyAnts/NativeBase/blob/8db2ead80127450a60de81c6863f0703bda3168a/src/components/composites/Menu/useMenu.tsx#L1) uses `@react-aria/focus` which is not present inside dependencies. I think it should be present inside dependencies if its used directly regardless of npm version.

Now this thing works using `npm 6.x` series just because how it de-dupes dependencies.

Based on this it might be an issues in npm 7.x just how its not smartly dedupes deps but i think the modules should list all their dependencies and not rely on transitive dependencies.

**Comment by intergalacticspacehighway** [comment]
@gyandeeps Thanks for reporting and debuggin this issue :). We'll fix it in the next patch release

**Comment by gyandeeps** [comment]
I have not collected all the data but it seems there are couple of other modules as well which are not listed in deps but are consumed directly. Best way to test is ti use the latest nodejs version of 16.x series.

**Comment by gyandeeps** [comment]
I tried the latest version but now i guess https://github.com/GeekyAnts/react-native-aria its packages have issues in them.

Example error:
```sh
Failed to compile.
/Users/<path>/node_modules/native-base/node_modules/@react-native-aria/overlays/lib/module/useOverlay.web.js
Module not found: Can't resolve '@react-aria/interactions' in '/Users/<path>/node_modules/native-base/node_modules/@react-native-aria/overlays/lib/module'
```

I guess once we fix this issue than we will see the next one.

**Comment by surajahmed** [comment]
@gyandeeps We're looking into this. Thank you!
