### ISSUE TITLE
ActionSheet with input being Covered by keyboard

### ISSUE THREAD

**Issue by nathanwkwong** [GeekyAnts/NativeBase#3939]
On IOS, I have an opened ActionSheet and a text input inside. When I try to click the input, a keyboard is shown, then the ActionSheet is covered behind the keyboard. 

Is it a bug? Or do I need to manually program to push the ActionSheet up according to the height of the keyboard?

I tried to wrap the ActionSheet by KeyboardAvoidingView with different props but the problem is still there. Thanks for answering. 

An example showing the issue:
https://snack.expo.dev/@nathanwkwong/2fd6a5

![before-pressing-input-on-actionsheet](https://user-images.githubusercontent.com/55337066/128804544-b515101f-ffd1-4bc3-8dc3-ca080c42a919.png)
 Activesheet is opened with an text input inside
![after-pressing-input--on-actionsheet](https://user-images.githubusercontent.com/55337066/128804543-cdaeff39-a352-465b-b4bf-6ac861887d5c.png)
 Activesheet is covered by the pop out keyboard after clicking on the text input

Environment:
  - platform: IOS 14 ( on both real and virtual devices) 
  - npm with node: v14.16.1
  - package:
  - "native-base": "^3.07",
  - "react": "17.0.1",
  - "react-native": "0.64.2",

**Comment by intergalacticspacehighway** [comment]
@nathanwkwong We'll implement a fix in later versions. In the meantime, can you use this workaround? 
I've updated your snack code with a solution. I have tested it on iOS and Android. Let me know if it works or you face any issues 🙂 
https://snack.expo.dev/@nishanbende/keyboard-avoid-hook

**Comment by nathanwkwong** [comment]
@intergalacticspacehighway This workaround is great and solved my problem. Thank you.

**Comment by nathanwkwong** [comment]
There is still a problem when using the hook solution above. 

Suppose there are two inputs (one or none input is fine) and a button(to open the Actionsheet) on a screen, I press the two inputs one by one and trigger the keyboard open, then I click the button to open the Actionsheet, the hook failed to measure the keyboard event and the Actionsheet is covered by the keyboard.

An example to show the problem developing upon the keyboard-avoid-hook:
https://snack.expo.dev/@nathanwkwong/keyboard-avoid-hook

![Screenshot 2021-08-11 at 10 18 13 AM](https://user-images.githubusercontent.com/55337066/128961367-5ae34f3b-562b-452a-b548-220b776629a6.png)

Click of the second input before clicking the button to open the Actionsheet

![Screenshot 2021-08-11 at 10 18 50 AM](https://user-images.githubusercontent.com/55337066/128961363-b6b97a46-a32f-4b14-90f8-aa09918742da.png)

The ActionSheet is being covered again

I think the problem is related to the keyboard event triggered and mixed between the inputs inside and outside of the Actionsheet. I don't have any workaround so far, is there any solution? Thanks.

**Comment by eburns1148** [comment]
This also seems to be a problem when using the Modal on iOS with the avoidKeyboard prop. I have 2 or more inputs and when the focus changes to another input, the modal drops down as if the keyboard was "hidden".

Packages:
```
"expo": "~42.0.1",
"native-base": "^3.0.7",
"react": "16.13.1",
"react-dom": "16.13.1",
"react-native": "https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz",
```

**Comment by intergalacticspacehighway** [comment]
@nathanwkwong  I noticed in the above solution the callback is behaving in a weird way. I'll take a deeper look. In the meantime, can you try this out?

https://snack.expo.dev/@nishanbende/keyboard-avoid-hook---fixed

@eburns1148 can you not use avoidKeyboard prop and use the above hook solution to set the bottom or padding of <Modal.Content/> component?

**Comment by nathanwkwong** [comment]
@intergalacticspacehighway Thanks for the update. I integrated and tested your fixed hook into my current project. It works fine on my Android, iOS stimulator (14.2) and iOS iPhone 7 (13.2).

**Comment by eburns1148** [comment]
@intergalacticspacehighway  I was able to test out your fix. It seems to be working great with marginBottom. With bottom or padding, it didn't look well.

Thanks!

**Comment by mikekreeki** [comment]
Does anyone have a modification of the workaround above that is using a smooth animation instead of jump and is willing to share?

**Comment by makkarMeenu** [comment]
@mikekreeki I have added animation in @intergalacticspacehighway's code .
 You can try https://snack.expo.dev/@meenu1/28ff38 out.

**Comment by param-finder** [comment]
I'm facing the same issue even now. The actionsheets with inputs hide behind the keyboards when opened.

**Comment by HagTheDon** [comment]
> @nathanwkwong I noticed in the above solution the callback is behaving in a weird way. I'll take a deeper look. In the meantime, can you try this out?
> 
> https://snack.expo.dev/@nishanbende/keyboard-avoid-hook---fixed
> 
> @eburns1148 can you not use avoidKeyboard prop and use the above hook solution to set the bottom or padding of <Modal.Content/> component?

Worked for me, thanks @nathanwkwong 
 
Incase you need test data details;
- React Native: v 0.68
- Native Base: 3.4.8
- IOS: Physical Device - Iphone 8

Thanks, let me know if you need any more debug info. When can this be added to the NativeBase update?

**Comment by brunolcarlos** [comment]
Create a function with

```
const useKeyboardBottomInset = () => {
  const [bottom, setBottom] = React.useState(0);
  const subscriptions = React.useRef([]);

  React.useEffect(() => {
    subscriptions.current = [
      Keyboard.addListener("keyboardDidHide", (e) => setBottom(0)),
      Keyboard.addListener("keyboardDidShow", (e) => {
        if (Platform.OS === "android") {
          setBottom(e.endCoordinates.height);
        } else {
          setBottom(
            Math.max(e.startCoordinates.height, e.endCoordinates.height)
          );
        }
      }),
    ];

    return () => {
      subscriptions.current.forEach((subscription) => {
        subscription.remove();
      });
    };
  }, [setBottom, subscriptions]);

  return bottom;
};
```

After call this inside of the function where is your Actionsheet

` const bottomInset = useKeyboardBottomInset();`

And then put the 

```
<Actionsheet
        style={{ backgroundColor: "rgba(0,0,0,0)" }}
        isOpen={isOpen}
        onClose={onClose}
      >
        <Actionsheet.Content
          bottom={bottomInset} // here #######################
          bg={"#151D29"}
          style={{ backgroundColor: "#151D29", height: 380 }}
        >
          <UsersChat post={item_} />
        </Actionsheet.Content>
      </Actionsheet>
```

**Comment by pkreipke** [comment]
I get that this workaround works but has this been fixed in any version of NB?

**Comment by pkreipke** [comment]
And a note: this workaround mostly succeeds for NB modals covered up by the keyboard as well:

```
  <Modal isOpen={isOpen} avoidKeyboard={false} animationPreset="slide">
    <Modal.Content bottom={bottomInset > 0 ? 105 : 0}
    ...
    </Modal.Content>
  </Modal>

```

Except that the offset needs to be calculated using the current Y position of the modal, not just the height of the keyboard. The offset is usually much less than the keyboard height.

I didn't do that in the example above, I just hard coded a value after trial and error. The non-zero value from the hook is just the signal that keyboard is open and to apply an offset.

**Comment by aozfen** [comment]
When we add more than one input and switch from an input with focus to a different input, the bottomInset returns as 0 and the keyboard remains open. This problem is only valid for IOS, it works fine on Android version

**Comment by NilsBaumgartner1994** [comment]
> const useKeyboardBottomInset = () => {
>   const [bottom, setBottom] = React.useState(0);
>   const subscriptions = React.useRef([]);
> 
>   React.useEffect(() => {
>     subscriptions.current = [
>       Keyboard.addListener("keyboardDidHide", (e) => setBottom(0)),
>       Keyboard.addListener("keyboardDidShow", (e) => {
>         if (Platform.OS === "android") {
>           setBottom(e.endCoordinates.height);
>         } else {
>           setBottom(
>             Math.max(e.startCoordinates.height, e.endCoordinates.height)
>           );
>         }
>       }),
>     ];
> 
>     return () => {
>       subscriptions.current.forEach((subscription) => {
>         subscription.remove();
>       });
>     };
>   }, [setBottom, subscriptions]);
> 
>   return bottom;
> };

Works like a charm. A bit dissapointed, that Scrollview and AvoidKeyboardView did not work as intendet.

**Comment by NilsBaumgartner1994** [comment]
My modified workaround:

````
    const bottomInset = useKeyboardBottomInset();
    const [height, setHeight] = React.useState(0);
...


      <SafeAreaView>
          <Actionsheet isOpen={isOpen} onClose={handleClose} onLayout={(event) => {
            const height = event?.nativeEvent?.layout?.height;
            if(height){
              setHeight(height);
            }
          }} _backdrop={{
            opacity: opacity,
          }}>
            <Actionsheet.Content bottom={bottomInset} height={bottomInset > 0 ? height-bottomInset : undefined} >
              <View key={"ActionSheetHeader"} style={{flexDirection: "row", justifyContent: "space-between", alignItems: "center"}}>
                <Text>{props?.title}</Text>
              </View>
              {renderDescription()}
              <ScrollView style={{width: "100%", backgroundColor: "orange"}}>
                {renderContent()}
              </ScrollView>
            </Actionsheet.Content>
          </Actionsheet>
      </SafeAreaView>
```

**Comment by gma692002** [comment]
@intergalacticspacehighway i tried using your workaround https://snack.expo.dev/@nishanbende/keyboard-avoid-hook
but still it didn't work for me this is my expo https://snack.expo.dev/@murshid69/keyboard_hide kindly let me know about the fix :)

**Comment by marcelino-borges** [comment]
The workarounds here didn't work for me as well =/

**Comment by VigneshVaidyanathan** [comment]
Using this below onchange function works for me from the work around.

```
    const onKeyboardChange = (e: any): void => {
      setBottom(e.endCoordinates.height);
    };
```

**Comment by 0xPasho** [comment]
> Create a function with
> 
> ```
> const useKeyboardBottomInset = () => {
>   const [bottom, setBottom] = React.useState(0);
>   const subscriptions = React.useRef([]);
> 
>   React.useEffect(() => {
>     subscriptions.current = [
>       Keyboard.addListener("keyboardDidHide", (e) => setBottom(0)),
>       Keyboard.addListener("keyboardDidShow", (e) => {
>         if (Platform.OS === "android") {
>           setBottom(e.endCoordinates.height);
>         } else {
>           setBottom(
>             Math.max(e.startCoordinates.height, e.endCoordinates.height)
>           );
>         }
>       }),
>     ];
> 
>     return () => {
>       subscriptions.current.forEach((subscription) => {
>         subscription.remove();
>       });
>     };
>   }, [setBottom, subscriptions]);
> 
>   return bottom;
> };
> ```
> 
> After call this inside of the function where is your Actionsheet
> 
> ` const bottomInset = useKeyboardBottomInset();`
> 
> And then put the bottom={bottomInset} on your Actionsheet.Content
> 
> ```
> <Actionsheet
>         style={{ backgroundColor: "rgba(0,0,0,0)" }}
>         isOpen={isOpen}
>         onClose={onClose}
>       >
>         <Actionsheet.Content
>           bottom={bottomInset} // here #######################
>           bg={"#151D29"}
>           style={{ backgroundColor: "#151D29", height: 380 }}
>         >
>           <UsersChat post={item_} />
>         </Actionsheet.Content>
>       </Actionsheet>
> ```

This code makes the keyboard work correctly, if you are using typescript and want it to be fully typed you can use this code:
```typescript
import React from 'react';
import {
  EmitterSubscription,
  Keyboard,
  KeyboardEvent,
  Platform
} from 'react-native';

const useKeyboardBottomInset = () => {
  const [bottom, setBottom] = React.useState(0);
  const subscriptions = React.useRef<EmitterSubscription[]>([]);

  React.useEffect(() => {
    subscriptions.current = [
      Keyboard.addListener('keyboardDidHide', (e) => setBottom(0)),
      Keyboard.addListener('keyboardDidShow', (e: KeyboardEvent) => {
        if (Platform.OS === 'android') {
          setBottom(e.endCoordinates.height);
        } else {
          setBottom(
            Math.max(e.startCoordinates?.height || 0, e.endCoordinates.height)
          );
        }
      })
    ];

    return () => {
      subscriptions.current.forEach((subscription) => {
        subscription.remove();
      });
    };
  }, [setBottom, subscriptions]);

  return bottom;
};

export default useKeyboardBottomInset;

```

**Comment by FezVrasta** [comment]
Could someone explain to me why the `useKeyboardBottomInset` exported by native-base is not working on Android but the one posted above does?
