### ISSUE TITLE
input placeholder text styling

### ISSUE THREAD

**Issue by acornejo** [GeekyAnts/NativeBase#394]
Tested on version of nativebase available on the playstore (1.0 built on Oct 14, 2016)

The input placeholder text styling is exactly the same as the input value text styling, this makes the placeholder and the value text indistinguishable (very poor UX/UI).

Both iOS and Android widgets use different styles on placeholder and values on input. The most common styling change is that placeholder text opacity is decreased when the input is focused.

**Comment by sankhadeeproy007** [comment]
You can add your placeholder color by using the `placeholderTextColor` prop.

**Comment by TsuryKnox** [comment]
Is 'placeholderTextColor' included in the docs? I can't find it.

**Comment by kukuandroid** [comment]
http://facebook.github.io/react-native/docs/textinput.html @TsuryKnox

**Comment by jaxatto** [comment]
For future people viewing this:

"inputColorPlaceholder" is included in the variables for native base themes now. Took me a few moments to find it. :)
