### ISSUE TITLE
Wrong Hello World code in documentation in v3.0.7

### ISSUE THREAD

**Issue by GregoryWullimann** [GeekyAnts/NativeBase#3941]
I'm trying Native Base for the first time, and by following the set up with Expo in v3.0.7 the Hello World code snippet produce an error.

Link: https://docs.nativebase.io/install-expo#run-the-hello-world-example

Error:

`Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
`

Code snippet in `App.js`
```
import React from 'react';
import { NativeBaseProvider, Box } from 'native-base';

function App() {
  return (
    <NativeBaseProvider>
      <Box>Hello world</Box>
    </NativeBaseProvider>
  );
}
```

By using the code snippet from Setup NativeBase Provider (https://docs.nativebase.io/setup-provider) the App works in the correct way.

Correct code:
```
import React from 'react';
import { NativeBaseProvider, Text, Box } from 'native-base';

export default function App() {
  return (
    <NativeBaseProvider>
      <Box flex={1} bg="#fff" alignItems="center" justifyContent="center">
        <Text>Open up App.js to start working on your app!</Text>
      </Box>
    </NativeBaseProvider>
  );
}
```

**Platform**
 - NativeBase version 3.0.7

**Comment by rayan1810** [comment]
Ok we haven't exported the App in the first example that must be causing this issue, thanks for reporting this @GregoryWullimann , we will try to update the Docs as soon as possible.
