### ISSUE TITLE
V3 & Above Installation Error

### ISSUE THREAD

**Issue by Csierram96** [GeekyAnts/NativeBase#3943]
After creating a new project with react-native-cli. 

npm install native-base
npm ERR! Found: react@17.0.1
npm ERR! node_modules/react
npm ERR!   react@"17.0.1" from the root project
npm ERR!   peer react@"*" from native-base@3.0.0
npm ERR!   node_modules/native-base
npm ERR!     native-base@"3.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"17.0.2" from react-dom@17.0.2
npm ERR! node_modules/react-dom
npm ERR!   peer react-dom@"*" from native-base@3.0.0
npm ERR!   node_modules/native-base
npm ERR!     native-base@"3.0.0" from the root project

**Comment by samijnih** [comment]
same issue

**Comment by intergalacticspacehighway** [comment]
@Csierram96 @samijnih can you install using --force flag `npm install --force`. This seems to be happening in recent npm version as there's React 16.8 peer dependency in one of the dependencies. I'll take a look. Thanks for reporting the issue!

**Comment by samijnih** [comment]
> @Csierram96 @samijnih can you install using --force flag `npm install --force`. This seems to be happening in recent npm version as there's React 16.8 peer dependency in one of the dependencies. I'll take a look. Thanks for reporting the issue!

Hey, I did try. But I've got 502 and an exception. That was not successful at all! :/

**Comment by Csierram96** [comment]
I managed to solve it using Yarn, with yarn you dont have any problems because of the peer dependencies. Hope that helps you.
