### ISSUE TITLE
Does the popover/menu component support interaction with elements on outside clicks on web? 

### ISSUE THREAD

**Issue by cmaycumber** [GeekyAnts/NativeBase#3945]
It seems like the popover/menu component currently acts like a modal. Is it possible to add functionality for users to interact with content outside the menu when the menu is open?

This is the current behavior of `react-native-popper` by @intergalacticspacehighway. I'm currently implementing the functionality in a custom  `Menu` component but it would be nice if that were supported out of the box.

**Comment by intergalacticspacehighway** [comment]
@cmaycumber Currently, the outside interactions are prevented as a transparent backdrop component is added. We'll add the mentioned feature in Menu/Popover components in the future.

**Comment by grean** [comment]
When the popover is controlled by the "isOpen" prop, we can't dismiss the popover anymore by cliking outside of it.
To achieve that you have to implement the onClose prop with your setIsOpen state callback.
