### ISSUE TITLE
Allow toast usage for Typescript class components

### ISSUE THREAD

**Issue by nmehlei** [GeekyAnts/NativeBase#3949]
**Is your feature request related to a problem? Please describe.**
I'm not sure if this counts as a feature request or a regression bug, but during migration of a react native project from NativeBase v2 to v3 I noticed that Toasts can now only be shown with the useToast hook.

When implementing components as Typescript-based class components, hooks can - to my knowledge - not be used, as trying to use a hook from a class component throws an `Invalid hook call` error. Therefore, the migration from NativeBase v2 to v3 would require a rewriting of all components to no longer be class based if both class components and Toasts are to be used. 

**Describe the solution you'd like**
Allow usage of toasts even for class components.

**Describe alternatives you've considered**
The alternative would be to exclude class components from being supported by NativeBase v3 and communicate it accordingly.

**Additional context**
I don't have the deepest knowledge base for React Native (yet), so I might not be aware of other alternatives.

**Comment by intergalacticspacehighway** [comment]
@nmehlei Thanks for the feature request. You should be able to call toast without using useToast hook, once this gets merged. We'll be releasing it in next releases

**Comment by intergalacticspacehighway** [comment]
@nmehlei  This has been released in 3.1.0. You can checkout the standalone toast example here. https://docs.nativebase.io/toast#standalone-toast
