### ISSUE TITLE
ZStack margins don't work in ios with justifyContent and alignItems

### ISSUE THREAD

**Issue by stacey-gammon** [GeekyAnts/NativeBase#3961]
**Describe the bug**

Items within a ZStack on ios don't abide by margin properties.

**To Reproduce**
Steps to reproduce the behaviour:

```
import React from "react"
import { ZStack, Box, Center, NativeBaseProvider } from "native-base"
export const Example = () => {
  return (
    <ZStack alignItems="center" justifyContent="center">
      <Box bg="primary.400" size={64} rounded="lg" />
      <Box bg="secondary.400" size={48} ml={20} rounded="lg" shadow={8} />
      <Box bg="emerald.400" size={32} rounded="lg" shadow={8} />
    </ZStack>
  )
}

export default () => {
  return (
    <NativeBaseProvider>
      <Center flex={1}>
        <Example />
      </Center>
    </NativeBaseProvider>
  )
}
```

The result, on ios, will be:

<img width="326" alt="Screen Shot 2021-08-16 at 7 24 22 PM" src="https://user-images.githubusercontent.com/16563603/129641260-0d4e485d-2d25-4ce9-a43e-c6e4907b0097.png">

While the web rendering will be:

<img width="324" alt="Screen Shot 2021-08-16 at 7 24 27 PM" src="https://user-images.githubusercontent.com/16563603/129641273-4a582372-d3c1-49e1-a59f-4e1f38650db0.png">

**Expected behaviour**
I expected the box to look like the web version.

**Comment by makkarMeenu** [comment]
@stacey-gammon ZStack's internal code is written in such a way that it's children are absolutely placed. 

Cause of the issue: Absolute placement  has different behaviour on native and web.

Workaround:  Use `left` , `right`, `top` , `bottom` props instead wherever absolute positioning is used .
