### ISSUE TITLE
Actionsheet too tall when app is multi-windowed

### ISSUE THREAD

**Issue by gretchelin** [GeekyAnts/NativeBase#3966]
**Describe the bug**
Actionsheet height does not resized when app is being multi-windowed, making content inside it out of view at the top and the actionsheet itself cannot be closed as drag icon is out of view.

**To Reproduce**
Steps to reproduce the behaviour:
1. Add actionsheet component anywhere.
2. Open the actionsheet in normal window (correct)
3. Set app to multi-window view
4. The actionsheet height will stay as if the app is still normal/full sized. Reopening the actionsheet also won't make the height adjust correctly.

**Expected behaviour**
Height should adjust accordingly when app is multi-windowed

**CodeSandBox/Snack link**
Here's a snack that demonstrate this problem (tested on real android device)
 [snack template](https://snack.expo.dev/@gretchelin/example).

**Screenshots**
![Screenshot_20210818-141519](https://user-images.githubusercontent.com/53071794/129854606-ac19c1e2-5635-43a8-9b99-d998a04203cf.png)

![Screenshot_20210818-141155](https://user-images.githubusercontent.com/53071794/129854369-2baaa949-c2c7-4eeb-9b4a-4b23df691cd9.png)

**Platform**
 - NativeBase version 3.0.1
 - Device: Android
 - OS: Android 10
 - React Native version 0.64

**Comment by makkarMeenu** [comment]
Can you please try in the latest version of NativeBase? We were unable to reproduce this.
Please re-open this if this still exists.
