### ISSUE TITLE
Border style 'dashed' prop is not working in android

### ISSUE THREAD

**Issue by Abhineetk47** [GeekyAnts/NativeBase#3968]
** Before reporting this bug, please...**
1. Check the latest documentation: https://docs.nativebase.io/
2. Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
3. Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
4. Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
5. For discussion purpose make use of NativeBase discord: https://discord.gg/TSgCw2UPmb

**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

**CodeSandBox/Snack link**
It would be easier for us to debug if you can reproduce the error in a codesandbox link or a snack link. You can use the [codesandbox template](https://codesandbox.io/s/native-base-v3-template-mq6ox)/[snack template](https://snack.expo.io/@mdrehman/nativebase-template).

**Screenshots**

**Platform**
 - NativeBase version [e.g. 3.0.1]
 - Browser version [e.g. 22]
 - React Native version [e.g. 0.64]
 - Expo sdk version [e.g. 41]
 - node [e.g. 14.16.1]
 - yarn or npm [e.g. 6.1]

**Additional information**
1. Add any other context about the problem here.
2. Is the bug present in both iOS and Android or in any one of them?
3. If you want your issue to be looked at quicker, please attach a snack reproducible with your issue. Makes it easier for us!
![Screenshot 2021-08-18 at 6 56 53 PM](https://user-images.githubusercontent.com/57386914/129906436-e80f9ad9-a1a5-4f5e-8121-934543609d43.png)
![Screenshot 2021-08-18 at 6 57 23 PM](https://user-images.githubusercontent.com/57386914/129906521-7ef89a68-af52-41ca-970b-9be465ec5396.png)

**Comment by intergalacticspacehighway** [comment]
@Abhineetk47 Thanks for reporting the issue. This seems to be an issue in React Native. https://github.com/facebook/react-native/issues/17251.
Also, this PR aims to fix it. https://github.com/facebook/react-native/commit/cb0e1d603aa4439a4d4804ad2987e4cb1f9bbf90

Until it's released you can add borderRadius={1} with `dashed` style as a workaround.

<img width="695" alt="Screenshot 2021-08-19 at 6 02 29 PM" src="https://user-images.githubusercontent.com/23293248/130068832-130e53aa-5e58-4426-88e3-a153973f1e1e.png">

**Comment by Abhineetk47** [comment]
@intergalacticspacehighway This hack works well in the IOS but in Android, this hack also doesn't help.

**Comment by intergalacticspacehighway** [comment]
Oh okay, I just tried it in the Android emulator and it worked. Might be failing for a specific version. Can you check in an emulator or share the device spec you using for testing?

**Comment by makkarMeenu** [comment]
Since this is inactive for a long time, closing this for now,

**Comment by xgenem** [comment]
```borderStyle='dashed'```

Still doesn't work. native-base@3.4.5
