### ISSUE TITLE
Toast message cuts offs description or title on iOS

### ISSUE THREAD

**Issue by tylern206** [GeekyAnts/NativeBase#3973]
Steps to reproduce the behaviour:
1. Press button to display toast
2. View toast

**Expected behaviour**
Text message should wrapped text and not truncate it.
**CodeSandBox/Snack link**
[Snack Link](https://snack.expo.dev/@tylern06/nativebase-toast) 

**Screenshots**

**Platform**
 - NativeBase version [3.0.7]
 - Device: [iPhoneX]
 - OS: [iOS]
 - React Native version [0.63]
 - Expo sdk version [41]
 - node [e.g. 14.16.1]

2. Is the bug present in both iOS and Android or in any one of them?
It is present only on iOS
3. If you want your issue to be looked at quicker, please attach a snack reproducible with your issue. Makes it easier for us!
[](https://snack.expo.dev/@tylern06/nativebase-toast )

**Comment by ankit-tailor** [comment]
Hi @tylern206 , This issue has been resolved in version 3.3.0. Thanks for reporting.
