### ISSUE TITLE
Chevron Icons breaking with size property

### ISSUE THREAD

**Issue by bjornbreck** [GeekyAnts/NativeBase#3974]
**Describe the bug**
All chevron icons do not seem to size correctly when a size property is added to the icon, rather padding is added around the icon.

**To Reproduce**
Steps to reproduce the behaviour:
1. Add a chevron icon to any screen or component with the size property.
2. `<CheckCircleIcon  size="xl" />` `<CheckCircleIcon  size="xs" />`
2. You'll see that if it's sized up that there's padding added. If it's sized down the icon is cut off

**Expected behaviour**
The chevrons should size accordingly like the rest of the icons.

**CodeSandBox/Snack link**
Paste either of those icons into the examples in the kitchensink on https://docs.nativebase.io/icon#examples and you can see this issue.

**Screenshots**
<img width="1545" alt="Screen Shot 2021-08-18 at 4 30 20 PM" src="https://user-images.githubusercontent.com/3058749/129980710-d58b9c66-3c18-423b-85ed-fa8866153629.png">

**Platform**
 - NativeBase version [e.g. 3.0.1]

**Additional information**
This bug seems to be across all platforms.

**Comment by bjornbreck** [comment]
@makkarMeenu any updates on this?

**Comment by surajahmed** [comment]
@bjornbreck Thanks for reporting! We've added it to our list. We'll try to push this fix by the next release.

**Comment by surajahmed** [comment]
@bjornbreck My bad! We've already fixed this in version `3.2.2` or later.
