### ISSUE TITLE
Pass variant prop through Checkbox.Group and Radio.Group

### ISSUE THREAD

**Issue by cmaycumber** [GeekyAnts/NativeBase#3980]
**Is your feature request related to a problem? Please describe.**
I don't like to have to define the variant across all the sub-components in a group 

**Describe the solution you'd like**
Pass the variant prop down through the Group components

**Describe alternatives you've considered**
Define the variant for each item in the group.

**Comment by surajahmed** [comment]
@cmaycumber Thanks for reporting! We've added this feature request to our list.

**Comment by surajahmed** [comment]
Hi @cmaycumber, you can use `_radio` or `_checkbox` prop to group component to modify props of sub-components now. 
This feature is included in version `3.3.6`.
Hope this will fix your issue.
Closing this issue. If you face any problem regarding this, feel free to reopen. Thanks.
