### ISSUE TITLE
TypeError: Cannot read property 'onPress' of undefined

### ISSUE THREAD

**Issue by pablohpsilva** [GeekyAnts/NativeBase#3983]
**Describe the bug**
I'm running the project using NextJS (created following the tutorial you guys have on your site).
Whenever I try to use the `toggleColorMode` function from `useColorMode` hook, I get an `onPress` error.

**To Reproduce**

```
import { useColorMode, Tooltip, Switch, Text } from "native-base";

const ColorModeSwitch = () => {
  const { colorMode, toggleColorMode } = useColorMode();

  return (
    <Tooltip
      label={colorMode === "dark" ? "Enable light mode" : "Enable dark mode"}
      placement="bottom right"
      openDelay={300}
      closeOnClick={false}
    >
      <Text>Label A</Text>
      <Switch
        onToggle={toggleColorMode}
      />
      <Text>Label B</Text>
    </Tooltip>
  );
};

export default ColorModeSwitch;
```

Then I see the error:
```
Server Error
TypeError: Cannot read property 'onPress' of undefined
```

**Expected behaviour**
To work... It shouldn’t care about the method, since it is a function.

**Platform**

node: v16.5.0
npm: v7.20.0
yarn: v1.22.10
"native-base": "^3.0.7",
"next": "latest",
"react": "^17.0.2",
"react-dom": "^17.0.2",
"react-native-safe-area-context": "^3.3.0",
"react-native-svg": "^12.1.1",
"react-native-web": "^0.17.1",
"styled-components": "^5.3.0",
"styled-system": "^5.1.5"

**Comment by rayan1810** [comment]
Ok I found the bug it's an issue with the Tooltip component, this will be fixed in the next patch release. Thanks for reporting the bug @pablohpsilva.

**Comment by makkarMeenu** [comment]
This is fixed now :)
