### ISSUE TITLE
Support for Rem?

### ISSUE THREAD

**Issue by LefanTan** [GeekyAnts/NativeBase#3985]
Thanks for filing an issue 😄!

Please search open/closed issues before submitting. Someone
might have asked the same thing before 😉!

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
In React, we're able to use rem which is great when it comes to scaling your application to work in different screen sizes. 

**Describe alternatives you've considered**
I've tried using percentages but for some reason it doesn't work concisely on different screen sizes.

**Additional context**

**Comment by makkarMeenu** [comment]
You can always use rem in web but not on native. Native doesn't support rem unit. 
For this, the syntax would be `_web = {{ p : "5rem" }}`
