### ISSUE TITLE
@react-stately missing at first use

### ISSUE THREAD

**Issue by hemalrathod** [GeekyAnts/NativeBase#3999]
I installed new nativebase version 3 with instructions as stated there in get started. When using first time on expo, I am getting following errors while building.

Android Bundling failed 6910ms
Unable to resolve module **@react-stately/checkbox** from C:\HEMAL\TinyTrader\DEVELOPMENT\TradeCentralMini\TradeCentralMiniAppUpdated\node_modules\native-base\src\components\primitives\Checkbox\CheckboxGroup.tsx: @react-stately/checkbox 
could not be found within the project.

If you are sure the module exists, try these steps:
 1. Clear watchman watches: watchman watch-del-all
 2. Delete node_modules and run yarn install
 3. Reset Metro's cache: yarn start --reset-cache
 4. Remove the cache: rm -rf /tmp/metro-*
  1 | import React, { createContext, memo, forwardRef } from 'react';
> 2 | import { useCheckboxGroupState } from '@react-stately/checkbox';
    |                                        ^
  3 | import { useCheckboxGroup } from '@react-native-aria/checkbox';
  4 | import { useFormControlContext } from '../../composites/FormControl';
  5 | import type { ICheckboxGroupProps, ICheckboxContext } from './types';

Could not understand why this is happening.

**Comment by hemalrathod** [comment]
> Thanks. This is an issue with pnpm too. I guess its a hoisting issue.

Thank you @vjpr for the reply. How should I solve it for the time being?

**Comment by MohammedBENHADINE** [comment]
same issue , any workaround for this ?
I tried to downgrade native base version to match compatibility versions table but no success.

**Comment by vjpr** [comment]
If you use pnpm modify your `pnpmfile.js`:

```
  if (pkg.name === 'native-base') {
    pkg.dependencies = {
      ...pkg.dependencies,
      '@react-stately/collections': '*',
      '@react-stately/tabs': '*',
      '@react-stately/checkbox': '*',
      '@react-stately/toggle': '*',
      '@react-stately/slider': '*',
    }
  }
```

Yarn has same thing.

**Comment by MohammedBENHADINE** [comment]
Adding that + '@react-aria/ssr' solved the issue

**Comment by hemalrathod** [comment]
> If you use pnpm modify your `pnpmfile.js`:
> 
> ```
>   if (pkg.name === 'native-base') {
>     pkg.dependencies = {
>       ...pkg.dependencies,
>       '@react-stately/collections': '*',
>       '@react-stately/tabs': '*',
>       '@react-stately/checkbox': '*',
>       '@react-stately/toggle': '*',
>       '@react-stately/slider': '*',
>     }
>   }
> ```
> 
> Yarn has a similar thing.

I am using `npm `for the installation. How should I do it with this? @MohammedBENHADINE

**Comment by hemalrathod** [comment]
> Adding that + '@react-aria/ssr' solved the issue

Where should I edit/add this while using `npm` with `expo`?

**Comment by MohammedBENHADINE** [comment]
@hemalrathod it seems that we should add those dependencies manually , so i did it the hard way (even it seems not accurate but it did the trick) . I ve just added the pkgs with npm like th following : 
`npm install @react-stately/collections @react-stately/tabs @react-stately/checkbox @react-stately/toggle @react-stately/slider @react-aria/ssr`
**Disclaimer** : i'm just starting with RN so maybe the above isn't the good way...

**Comment by hemalrathod** [comment]
> @hemalrathod it seems that we should add those dependencies manually , so i did it the hard way (even it seems not accurate but it did the trick) . I ve just added the pkgs with npm like th following :
> `npm install @react-stately/collections @react-stately/tabs @react-stately/checkbox @react-stately/toggle @react-stately/slider @react-aria/ssr`
> **Disclaimer** : i'm just starting with RN so maybe the above isn't the good way...

One solution I found, is not to use `npm`

I used `yarn` and all problems with `stately` solved. I think problem is with `npm` package manager dependencies configuration.
