### ISSUE TITLE
Enhancement: Better compatibility with Jest test framework

### ISSUE THREAD

**Issue by dikarel** [GeekyAnts/NativeBase#400]
This library is [incompatible](https://github.com/GeekyAnts/NativeBase/issues/396) with React Native's [default test framework](https://facebook.github.io/jest) out of the box. The workaround requires the developer to tweak an obscure [configuration value](https://facebook.github.io/jest/docs/configuration.html#transformignorepatterns-array-string).

I'd like to propose either of the following enhancements to make first-time usage painless:

1. Transpile ES6 `import` statements into CommonJS-style `require` statements before publishing the package
2. Add an easily-accessible FAQ/guide for setting up tests with the Jest framework

The first is a common operation already done by other NPM packages; the second should be trivial to implement.

PR #403 is an attempt at (1)

**Comment by sankhadeeproy007** [comment]
Thanks! Added to 0.5.21
