### ISSUE TITLE
How to open or focus the NativeBase Select component

### ISSUE THREAD

**Issue by josephsintum** [GeekyAnts/NativeBase#4002]
## NativeBase Version
"native-base": "^3.1.0",
Bare "react-native": "0.64.2",

## Issue Description

How can I trigger an onPress or open a [Select Component](https://docs.nativebase.io/select)
I want open or focus the select component from a function.
It doesn't have an isOpen state I can access.
I tried using the getting the ref and calling the onPress function

```js
return (
      <Select
       wrappedRef={selectRef => console.log(selectRef)}
        selectedValue={language}
        onValueChange={(itemValue) => setLanguage(itemValue)}
      >
        <Select.Item label="JavaScript" value="js" />
        <Select.Item label="TypeScript" value="ts" />
     </Select>
)
```
but I get this object which doesn't have the onPress function

```json
{
  "_children": [...],
  "_internalFiberInstanceHandleDEV": {
    "_debugHookTypes": null,
    "_debugID": 16533,
   ...
  },
  "_nativeTag": 865,
  "viewConfig": {
    "Commands": {},
    "bubblingEventTypes": {...},
    "directEventTypes": {...},
 ...
  }
}
```

**Comment by jaferi512** [comment]
Me Also Facing Same Issues Like that Please try to resolve this query

**Comment by mkhalifa013** [comment]
bump for this thread. Also experiencing this issue.

It looks like the components build in the library are not build with inversion of control in mind.
The select component is using an internal Pressable which is hooked to an internal state called [open, setOpen]. 

This makes hooking into this programmatically impossible. 

To the makers: could you please gives us an api to open selects, inputs etc programmatically?

**Comment by Beyazatli** [comment]
I have same issue, any solve?

**Comment by ankit-tailor** [comment]
Hi Everyone, We don't have support to open select programmatically but We might add it in the future versions. Thanks for your suggestions. Closing the issue for now. Feel free to open it if you have any queries.
