### ISSUE TITLE
Additional style property for Box inside of SimpleGrid component

### ISSUE THREAD

**Issue by kylegwalsh** [GeekyAnts/NativeBase#4003]
**Is your feature request related to a problem? Please describe.**
I am unable to use the SimpleGrid in several scenarios because I cannot completely control it's style.

There is an inner Box being used to wrap the "col" component inside of the SimpleGrid, but it does not accept any props as styles. For my use case, I'm trying to "flex: 1" this box so that the children in each row expand to fill the entirety of the SimpleGrid's width (rather than just fitting the width of the children).

```
  {row.map((col: any) => {
    return (
      <Box {...DEBUG_STYLES.cols} key={col.key}>
        {col}
      </Box>
    );
  })}
```

**Describe the solution you'd like**
It would be helpful if we were given more control over the SimpleGrid component's styles.  This could be accomplished by passing down a _gridItem style or something similar for this wrapper. 

**Describe alternatives you've considered**
I have considered using a series of VStacks + HStacks to achieve the desired behavior, but at that point, I will just be duplicating the SimpleGrid and tweaking it slightly.

**Comment by pierroo** [comment]
I am trying to accomplish the same thing: having children expend to fill the full width for each lines.
Did you manage to find a solution? would you mind sharing it if you did? :)

**Comment by kylegwalsh** [comment]
@pierroo I actually don't recall exactly where we were trying to use this so I can't find the code, but I'm pretty sure we took the approach of nesting the VStack and HStack's similar to how the SimpleGrid works behind the scenes. Not as convenient, but it gets the job done for now.

**Comment by pierroo** [comment]
Thank you for answering @kylegwalsh , I will look into this solution as well then, until NativeBase gives us this option natively :)

**Comment by surajahmed** [comment]
@kylegwalsh SimpleGrid component is currently on hold. We're going to add full support for that soon.
