### ISSUE TITLE
Input Variants do not work with Pseudo props

### ISSUE THREAD

**Issue by Psycarlo** [GeekyAnts/NativeBase#4016]
**Describe the bug**
Input variants do not work with pseudo props

**To Reproduce**
`<Input variant="filled" _focus={{ variant: 'outline' }} />`

**Expected behaviour**
When focused, the input should change from filled to outline

**Platform**

- NativeBase version: ^3.1.0
- Device: iPhone12

**Comment by Psycarlo** [comment]
A work around is to use bgColor='transparent'

`_focus={{ bgColor: 'transparent' }}`

**Comment by Psycarlo** [comment]
Others also seem not work with pseudo props

**Comment by vidhi499** [comment]
@Psycarlo This issue has been fixed in the latest release.
