### ISSUE TITLE
Can't click on InputRightElement when focus

### ISSUE THREAD

**Issue by Psycarlo** [GeekyAnts/NativeBase#4017]
**Describe the bug**
When I try to click the InputRightElement inside the Input, the Input dismisses.

**To Reproduce**
`<Input
                variant="filled"
                _focus={{ bgColor: 'transparent' }}
                type={showPassword ? 'text' : 'password'}
                InputRightElement={
                  showPassword ? (
                    <Icon
                      as={<Ionicons name="eye-off-outline" />}
                      size="5"
                      mr={3}
                      onPress={handleShowPasswordClick}
                    />
                  ) : (
                    <Icon
                      as={<Ionicons name="eye-outline" />}
                      size="5"
                      mr={3}
                      onPress={handleShowPasswordClick}
                    />
                  )
                }
                isRequired
              />`

**Expected behaviour**
You would be able to click on the InputRightElement : Icon without the input stop being on focus.

**Platform**

- NativeBase version: 3.0.1

**Comment by Psycarlo** [comment]
Was a scrollView messing things up.

**Comment by Livan-pro** [comment]
This can be fixed with `keyboardShouldPersistTaps="handled"` on `ScrollView`.
Details: https://reactnative.dev/docs/scrollview#keyboardshouldpersisttaps.
