### ISSUE TITLE
NPM package info page shows error message instead of readme contents

### ISSUE THREAD

**Issue by dikarel** [GeekyAnts/NativeBase#402]
## react-native, react and native-base version

native-base version **0.5.20**

## Expected behaviour

When I go to the [NPM package info page](https://www.npmjs.com/package/native-base), I should see readme contents from README.md.

I proposed a fix with the following PR: https://github.com/GeekyAnts/NativeBase/pull/401

## Actual behaviour

It shows "ERROR: No README data found!" instead.

## Steps to reproduce (code snippet or screenshot)

Go to https://www.npmjs.com/package/native-base

![screen shot 2017-01-04 at 2 13 59 am](https://cloud.githubusercontent.com/assets/15131271/21619793/ddac7edc-d223-11e6-9bf5-36b8bf8b3aef.png)

**Comment by sankhadeeproy007** [comment]
Thanks! Fixed with 0.5.21
