### ISSUE TITLE
Android. Left and right border color does not apply and stay black.

### ISSUE THREAD

**Issue by abramovks** [GeekyAnts/NativeBase#4030]
Hello.
Android
Left and right border color does not apply and stay black.
If use borderColor, then no one border change color.
<Box
    borderTopColor={'#e9e9e9'}
    borderLeftColor={'#e9e9e9'}
    borderRightColor={'#e9e9e9'}
    borderBottomColor={'#e9e9e9'}
    border={3}
    p={1}
    rounded={round} 
>
In the IOS  the problem does not exist.

<img width="360" alt="problem" src="https://user-images.githubusercontent.com/4946997/133180742-79552f6f-a154-411a-a67d-eab6fc432bf4.png">

**Comment by MD-REHMAN** [comment]
I am unable to reproduce the above case. But certainly, the border has an existing issue on android which you can see over [here](https://github.com/facebook/react-native/issues/12403). 

If you're still having any concerns, please share a minimal snack describing the issue. And I'll try to provide you a better solution.
