### ISSUE TITLE
Slow Performance of Checkbox group when Number of checkboxes is big

### ISSUE THREAD

**Issue by arunim2405** [GeekyAnts/NativeBase#4035]
**Describe the bug**
Very Slow Performance of Checkbox group when Number of checkboxes is big (>~50)
**To Reproduce**
Steps to reproduce the behaviour:

Create a checkbox group with >~50 different checkbox values

**Expected behaviour**

**CodeSandBox/Snack link**
https://codesandbox.io/s/laughing-keldysh-ur72n?file=/src/components/Example.tsx

**Platform**
iOS and Android Both

**Comment by Ajamuar** [comment]
Hi @arunim2405, sorry for the late response. 

We are working on fixing the overall performance of the system. It might take a bit of time but we are hoping that it won't affect the application this is being used in too much. We have made some improvements here and there, and we also have a few more experiments planned regarding this. We will keep you posted.

**Comment by tungduonghgg123** [comment]
it is really slow for the whole component containing the Checkbox group.

**Comment by arunim2405** [comment]
@tungduonghgg123 try to render the checkboxes in a flat list instead of a scroll view, I saw a slight improvement this way
