### ISSUE TITLE
Title in Header not response to taps.

### ISSUE THREAD

**Issue by niros001** [GeekyAnts/NativeBase#404]
I use react-native v-0.39.0 and native-base v-0.5.9.
When i press on title in android everything is fine, But in ios it's do nothing.
```
<Header>
<Title onPress={()=>alert('Show me please!')}>
title
</Title>
</Header>
```
How can i solve this issue?

**Comment by sankhadeeproy007** [comment]
Works in latest NativeBase #346.

**Comment by niros001** [comment]
It's work if the header have only title, But if you add 1 Button or more with title only the buttons work and title not!
