### ISSUE TITLE
header navbar button icon spacing

### ISSUE THREAD

**Issue by mybigman** [GeekyAnts/NativeBase#405]
Hi Guys,

How can i shift the icon over to the right edge of the button in the navbar, otherwise the icon sits to far off the screen edge and is not symmetrical?

Also the icon is clipped top and bottom as well, how to resolve?

```javascript
<Container>
  <Header iconRight style={{ paddingRight: 0 }}>
    <Title>My Title</Title>
    <Button>
    <Icon name="ios-information-circle" />
    </Button>
  </Header>
```

![image](https://cloud.githubusercontent.com/assets/1289916/21632185/d5bda0a6-d297-11e6-9c83-32fcca6aa75b.png)

Many thanks.

NB v0.5.19

**Comment by sankhadeeproy007** [comment]
Just add a negative margin to the button and decrease the font size of the icon. Should work.
