### ISSUE TITLE
Title and Buttons in Header BUG!

### ISSUE THREAD

**Issue by niros001** [GeekyAnts/NativeBase#406]
I use react-native v-0.39.2 and native-base v-0.5.20

Title onPress work if the header have only title, But if you add 1 Button or more with title - only the buttons work and title not!

**Comment by mutale** [comment]
+1

**Comment by fhad-getmaple** [comment]
+1

**Comment by niros001** [comment]
I update to v 2.0.6 and this issue solved, Thanks!
