### ISSUE TITLE
Components try to update state after unmounting

### ISSUE THREAD

**Issue by kevinwcyu** [GeekyAnts/NativeBase#4063]
** Before reporting this bug, please...**

1. Check the latest documentation: https://docs.nativebase.io/
2. Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
3. Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
4. Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
5. For discussion purpose make use of NativeBase discord: https://discord.gg/TSgCw2UPmb

**Describe the bug**
When Native Base components are unmounted, they still try to update state. There is a warning message:

```
index.js:1 Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
```

**To Reproduce**
Steps to reproduce the behaviour:

1. Clone https://github.com/kevinwcyu/native-base-unmount
1. `cd native-base-unmount`
1. `yarn install`
1. `yarn start`
1. Go to http://localhost:19002/ (this should open automatically)
1. Click `Run in web browser` (this should open http://localhost:19006/ in a new tab)
1. Open the console in devtools
1. Resize the window width from largest to smallest size
1. There should be a warning in the console.

**Expected behaviour**
There shouldn't be a warning.

1. Comment out line 10 in `screens/TabOneScreen.tsx` and uncomment lines 11-15. This uses `View` and `Text` from `react-native` instead of the `Text` component in `native-base`.
1. Resize the window width from largest to smallest size
1. There isn't a warning in the console.

**CodeSandBox/Snack link**
It would be easier for us to debug if you can reproduce the error in a codesandbox link or a snack link. You can use the [codesandbox template](https://codesandbox.io/s/native-base-v3-template-mq6ox)/[snack template](https://snack.expo.io/@mdrehman/nativebase-template).

**Screenshots**

**Platform**

- NativeBase version 3.1.0
- Device: MacBook Air M1
- OS: macOS 11.5.2
- Browser: Brave and Firefox
- Browser version: Brave Version 1.29.80 Chromium: 93.0.4577.63 (Official Build) (arm64). Firefox 92.0.
- React Native version:  0.63.4
- Expo sdk version: 42
- node 16.8.0
- yarn 1.22.11

**Additional information**

I used `expo init` with the tabs template to generate the reproduction https://github.com/kevinwcyu/native-base-unmount. I only edited `navigation/index.tsx` to use the `useBreakpointValue` hook to switch between navigators depending on the screen size. I used just a `Text` component `TabOneScreen.tsx` as a minimal reproduction of the issue.

I'm seeing this with other Native Base components. In my actual codebase I'm seeing it with `IconButton`, `VStack`, `Heading`, etc.

I tried another UI library (UI-Kitten), and just pure `react-native` components, and they don't have the same issue.

**Comment by surajahmed** [comment]
@kevinwcyu Can you please try the latest version `3.4.3`? We've fixed a lot of issues and warnings.

**Comment by kevinwcyu** [comment]
Hi @surajahmed, Thanks for the update.

I'm no longer using NativeBase and I think I deleted my repro branch in my original issue. I don't have time to try to recreate it unfortunately.

Sorry, I'm not able to test out the latest version to see if this fixed it. I'm fine with closing off this issue if you'd like to do that.

**Comment by surajahmed** [comment]
@kevinwcyu Thanks for your reply. Closing this issue for now. Please feel free to reopnen.
