### ISSUE TITLE
H3 cuts off bottom part of letter 'g'

### ISSUE THREAD

**Issue by mweitzel2005** [GeekyAnts/NativeBase#409]
Hi there,

I've started a new react-native project today and thought I would give *NativeBase* a spin. Unfortunately the first tag to be included in the `Content` section was an `H3` tag which cuts off some text at the bottom.

## react-native, react and native-base version
* "native-base": "^0.5.20",
* "react": "~15.4.0-rc.4",
* "react-native": "0.40.0"

## Expected behaviour
Including a `H3` tag inside a `Content` tag should render the included text correctly.

## Actual behaviour
Some text (e.g. the lower part of the letter `g`) gets cut off.

## Steps to reproduce (code snippet or screenshot)
```
<Container>
  <Content>
    <H3>
      logical
    </H3>
  </Content>
</Container>
```

#### No padding:
![nopadding](https://cloud.githubusercontent.com/assets/584796/21683811/a9056cb6-d363-11e6-9b52-d4716af883ce.PNG)

#### Padding of 5:
![padding5](https://cloud.githubusercontent.com/assets/584796/21683821/b67410a0-d363-11e6-92bd-e01af20c4542.PNG)

## Is the bug present in both ios and android or in any one of them?
Haven't tried `iOS` on account of using a Windows machine, only seen it on `Android` so far.

## Any other additional info which would help us debug the issue quicker.
 Adding `padding` or `margin` does not change that, `H1` and `H2` tags display correctly.

*Thanks for all your work and help!*

**Comment by sankhadeeproy007** [comment]
Change the lineHeight of H3?

**Comment by sankhadeeproy007** [comment]
@mweitzel2005 Any updates here?

**Comment by phannam1412** [comment]
same problem

**Comment by akhil-geekyants** [comment]
@phannam1412 checked this. Working fine for me. Attaching a gif.

Gif

![h3](https://user-images.githubusercontent.com/27768184/41335175-87b7b750-6f05-11e8-891f-59cb25d31d9e.gif)

**Comment by phannam1412** [comment]
thank @akhil-geekyants, actually I have problem when there are multiple H3, not the single H3, but no worries, the better way is to wrap H3 for convenient style customization
`
import {H3 as NBH3} from 'native-base';

export class H3 extends Component {
    constructor(props) {
        super(props);
    }
    render() {
        return <NBH3 style={this.props.style,{lineHeight: 24}} {...this.props} />
    }
}
`
