### ISSUE TITLE
Toast broken in version 3.2.0

### ISSUE THREAD

**Issue by muazazhar** [GeekyAnts/NativeBase#4094]
If used 'status' property in toast, it gives error 
` Error: `NativeBaseConfigProvider` must be used within `NativeBaseConfigProvider` `

Steps to reproduce:
use latest version(3.2.0) 
it can be checked [here](https://docs.nativebase.io/toast#status) .

**Comment by intergalacticspacehighway** [comment]
@muazazhar Thanks for reporting. Toast is broken in docs but works locally. We're looking into the docs issue.

**Comment by intergalacticspacehighway** [comment]
@muazazhar This has been resolved in new deployment https://docs.nativebase.io/toast. Thanks for reporting :)

**Comment by muazazhar** [comment]
Nope, Still giving error.
![image](https://user-images.githubusercontent.com/49091541/135204976-fae97dcd-fc30-4868-b590-45e7ac1124c2.png)

**Comment by intergalacticspacehighway** [comment]
@qlereboursBS it has been fixed in the 3.2.1, also updated the docs. https://docs.nativebase.io/toast

**Comment by dijaltom** [comment]
Error: `useTheme` must be used within `NativeBaseConfigProvider`
This error is located at:
    in Text
    in RCTView (at View.js:32)
    in View (at Home.js:18)
    in Home (at Store.js:437)
    in Wrapped (created by SceneView)
    in SceneView (created by CardContainer)
    in RCTView (at View.js:32)
    in View (created by CardContainer)
    in RCTView (at View.js:32)
    in View (created by CardContainer)
    in RCTView (at View.js:32)
    in View
    in CardSheet (created by Card)
    in RCTView (at View.js:32)
    in View (at createAnimatedComponent.js:242)
    in AnimatedComponent (at createAnimatedComponent.js:295)
    in AnimatedComponentWrapper (created by PanGestureHandler)
    in PanGestureHandler (created by PanGestureHandler)
    in PanGestureHandler (created by Card)
    in RCTView (at View.js:32)
    in View (at createAnimatedComponent.js:242)
    in AnimatedComponent (at createAnimatedComponent.js:295)
    in AnimatedComponentWrapper (created by Card)
    in RCTView (at View.js:32)
    in View (created by Card)
    in Card (created by CardContainer)
    in CardContainer (created by CardStack)
    in MaybeFreeze (at src/index.native.tsx:229)
    in RNSScreen (at createAnimatedComponent.js:242)
    in AnimatedComponent (at createAnimatedComponent.js:295)
    in AnimatedComponentWrapper (at src/index.native.tsx:208)
    in Screen (created by MaybeScreen)
    in MaybeScreen (created by CardStack)
    in RNSScreenContainer (at src/index.native.tsx:277)
    in ScreenContainer (created by MaybeScreenContainer)
    in MaybeScreenContainer (created by CardStack)
    in CardStack
    in KeyboardManager (created by SafeAreaInsetsContext)
    in RNCSafeAreaProvider (at SafeAreaContext.tsx:76)
    in SafeAreaProvider (created by SafeAreaInsetsContext)
    in SafeAreaProviderCompat (created by StackView)
    in GestureHandlerRootView (at GestureHandlerRootView.android.tsx:26)
    in GestureHandlerRootView (created by StackView)
    in StackView (created by StackView)
    in StackView
    in Unknown (created by Navigator)
    in Navigator (created by NavigationContainer)
    in NavigationContainer (at Router.js:101)
    in App (at Router.js:127)
    in Router (at App.js:9)
    in App (at renderApplication.js:50)
    in RCTView (at View.js:32)
    in View (at AppContainer.js:92)
    in RCTView (at View.js:32)
    in View (at AppContainer.js:119)
    in AppContainer (at renderApplication.js:43)

**Comment by intergalacticspacehighway** [comment]
@dijaltom can you share your code snippet or snack player? `useToast` should be used in a child of NativeBaseProvider or look at the standalone Toast API. https://docs.nativebase.io/toast#standalone-toast
