### ISSUE TITLE
react-native 0.27.2 invalid peer dependency

### ISSUE THREAD

**Issue by chromakey** [GeekyAnts/NativeBase#41]
> npm ERR! peerinvalid The package react-native@0.27.2 does not satisfy its siblings' peerDependencies requirements!
> npm ERR! peerinvalid Peer native-base@0.4.6 wants react-native@0.26.0 - 0.27.1

Figure you guys will update shortly.  Thanks for a great library.

**Comment by sankhadeeproy007** [comment]
We'll fix it in the next update. Can you tell us if the package is working fine in RN 0.27.2 apart from the `npm install` error?

**Comment by chromakey** [comment]
I'm only using the Button component from native-base, but it seems to be working fine on RN 0.27.2 apart from the npm install error.

**Comment by sankhadeeproy007** [comment]
Great! Closing this for now. Reopen please if there are further issues.
