### ISSUE TITLE
Documentation site drawer navigation is broken on Expo Snack

### ISSUE THREAD

**Issue by Ajulibe** [GeekyAnts/NativeBase#4102]
Display Preview for the drawer tab navigation is throwing a _"Minified React error "_.

**To Reproduce**
1. Go to https://docs.nativebase.io/building-drawer-navigation.
2. Wait for the simulator to load.

**Expected behaviour**
The simulator should display an interactive preview of what the drawer tab looks like.

**Screenshots**
<img width="845" alt="Screenshot 2021-09-22 at 10 01 22" src="https://user-images.githubusercontent.com/48919324/134314678-8f4936cc-8da2-42ea-a830-cf89360911c4.png">

**Comment by makkarMeenu** [comment]
It's fixed now.
