### ISSUE TITLE
Click on backdrop of Actionsheet is not working Native Base 3.2

### ISSUE THREAD

**Issue by jonra1993** [GeekyAnts/NativeBase#4104]
** Before reporting this bug, please...**

**Describe the bug**
After press backdrop, Actionsheet does not disappear. I tested documentation examples and on iOS and Android devices. The only way to close Actionsheet is by dragging it down.

**To Reproduce**
Steps to reproduce the behaviour:

1. Press Actionsheet button
2. Click backdrop

**Expected behavior**
I was expecting to close the Actionsheet after pressing the backdrop.

**CodeSandBox/Snack link**
https://snack.expo.dev/K-weARrke

**Screenshots**
![image](https://user-images.githubusercontent.com/23468720/134388562-3b0e582e-5928-40a4-9e30-fdc65d757e36.png)

**Platform**

- NativeBase version 3.2
- Device: web, ios, android
- OS: iOS12
- Browser Chrome
- React Native version 0.64
- node 14.16.1

**Comment by intergalacticspacehighway** [comment]
@jonra1993 Thanks for reporting :) This will be fixed in the next release.
