### ISSUE TITLE
Adding placeholder for Picker component

### ISSUE THREAD

**Issue by berdof** [GeekyAnts/NativeBase#411]
It would be really great if we could add a placeholder for picker. Looked through the docs and seems like this option is missing.

**Comment by sankhadeeproy007** [comment]
yes, this is something which we will fix in a future version.

**Comment by megazoll** [comment]
@sankhadeeproy007 placeholder works only on iOS. Do you have plan to add placeholder for android?

**Comment by sankhadeeproy007** [comment]
We are using react-native's android. So unless react-native adds it, very unlikely.

**Comment by femiveys** [comment]
Do we have a view yet on when this will be implemented?
