### ISSUE TITLE
Color mode(light, dark) doesn't change immediately, using StorageManager

### ISSUE THREAD

**Issue by Amitkahlon** [GeekyAnts/NativeBase#4110]
**Describe the bug**
Color mode doesn't update immediately when changing, using AsyncStorage and StorageManager(same as the example)

**To Reproduce**
I used the example in the docs: [persisting-the-color-mode](https://docs.nativebase.io/color-mode#persisting-the-color-mode)
this is my code: 

```
import type { ColorMode, StorageManager } from 'native-base';
import AsyncStorage from '@react-native-async-storage/async-storage';

export const colorModeManager: StorageManager = {
  get: async () => {
    try {
      let val = await AsyncStorage.getItem('@color-mode');
      return val === 'dark' ? 'dark' : 'light';
    } catch (e) {
      return 'light';
    }
  },
  set: async (value: ColorMode) => {
    try {
      await AsyncStorage.setItem('@color-mode', value);
    } catch (e) {
      console.log(e);
    }
  },
};
```
```
// App.js
 <Provider store={store}>
      <NativeBaseProvider theme={theme} colorModeManager={colorModeManager} >
        <RootNavigator />
      </NativeBaseProvider>
    </Provider>
```

```
// the button the changes the mode.
<Button
        onPress={async () => {
          const theme = await colorModeManager.get();
          let mode: ColorMode = theme === "light" ? 'dark': 'light'
          await colorModeManager.set(mode);
          console.log(mode);
        }}
      >
        ChangeTheme
      </Button>
```

**Expected behaviour**
I expected that when I use the StorageManager to handle the colorModeManager(to manage color mode, dark or light)
it will change automatically, instead, it doesn't change until I refresh the app.

**Screenshots**
video to showcase the problem:
https://youtu.be/KZH75PylVeg

**Platform**
- latest native-base
- android studio
- "@react-native-async-storage/async-storage": "~1.15.0",
- "@react-navigation/native": "^6.0.2",
- "@react-navigation/native-stack": "^6.1.0",
- "@react-navigation/stack": "^6.0.7"
- "react-redux": "^7.2.5",
- "redux": "^4.1.1",

**Additional information**
Maybe Im doing it wrong? I suppose to update the color mode somewhere? 
the example make it seems for me that the colorModeManager handles the update.

**Comment by intergalacticspacehighway** [comment]
@Amitkahlon Modify change code with the below snippet. The Color mode manager is to get the initial color mode and storing the changed color mode (It's handled internally, you can just interact with the useColorMode hook). Check this out for more detail: https://docs.nativebase.io/next/use-color-mode
```
// the button the changes the mode.
function Test() {
  const colorMode = useColorMode();
return <Button onPress={colorMode.toggleColorMode}>
        ChangeTheme
      </Button>
}

```
Let us know if you have any doubts.

**Comment by Amitkahlon** [comment]
Thank you very much, I saw this hook doc but I probably thought you need to use the asyncStorage.
