### ISSUE TITLE
themeTools getColor should accept OpaqueColorValue

### ISSUE THREAD

**Issue by trajano** [GeekyAnts/NativeBase#4119]
**Describe the bug**

expo-vectorIcons uses `string | OpaqueColorValue` or simply `ColorValue` which uses `OpaqueColorValue` but getColor requires a string.

**Comment by vidhi499** [comment]
@trajano  We will fix this in further release, for now theme tools provide tranparentize util which can be used to provide opacity. Let us know if you have any more doubts.

**Comment by trajano** [comment]
It's more for improving type safety by making things consistent with React Native types and removing the use of `any` (which I don't think you used in this context).

**Comment by MD-REHMAN** [comment]
@trajano we have introduced a way to use the alpha value on any theme color by simply appending `:alpha.10` or some number from the [theme](https://docs.nativebase.io/default-theme#opacity) within NativeBase.
_NOTE: These colors are not part of the theme instead we're adding alpha values on existing theme tokens._

So if it's a valid NativeBase color, getColor will give you its respective **rgba** value
