### ISSUE TITLE
onEndReached on Dynamic List

### ISSUE THREAD

**Issue by shukerullah** [GeekyAnts/NativeBase#412]
How to use onEndReached on dynamic List? I think ListView common props are missing such as renderFooter and onEndReachedThreshold .

**Comment by sankhadeeproy007** [comment]
List component is a wrapper around RN ListView. So all the props should get passed to ListView. Please attach a code snippet of what you're trying to do. That will be helpful.

**Comment by shukerullah** [comment]
I replaced List with ListView and it worked.
