### ISSUE TITLE
Spinner size property crash the app

### ISSUE THREAD

**Issue by tylim88** [GeekyAnts/NativeBase#4131]
**Describe the bug**
Spinner size property accepts only "sm","lg","small" and "large", the app will close if you use any other value stated in doc

this is the case for android emulator and android device, it just quit the app without any error log

the size in snack is also incorrect

![image](https://user-images.githubusercontent.com/5227509/134918058-e178b1e3-8510-49dc-8b31-7db7bbb34927.png)

**To Reproduce**
Steps to reproduce the behaviour:

1.expo init my-app --template expo-template-native-base-typescript
2. paste this code in App.tsx (only minor modification compare to original code)
```
import React from "react";
import {
  Text,
  Link,
  HStack,
  Center,
  Heading,
  Switch,
  useColorMode,
  NativeBaseProvider,
  extendTheme,
  VStack,
  Code,Spinner
} from "native-base";
import NativeBaseIcon from "./components/NativeBaseIcon";

// Define the config
const config = {
  useSystemColorMode: false,
  initialColorMode: "dark",
};

// extend the theme
export const theme = extendTheme({ config });

export default function App() {
 
	return (
    <NativeBaseProvider>
      <Center
        _dark={{ bg: "blueGray.900" }}
        _light={{ bg: "blueGray.50" }}
        px={4}
        flex={1}
      >
        <VStack space={5} alignItems="center">
          <Spinner size="lg"/>
          <NativeBaseIcon />
          <Heading size="lg">Welcome to NativeBase</Heading>
          <HStack space={2} alignItems="center">
            <Text >Edit</Text>
            <Code>App.tsx</Code>
            <Text>and save to reload.</Text>
          </HStack>
          <Link href="https://docs.nativebase.io" isExternal>
            <Text color="primary.500" underline fontSize={"xl"}>
              Learn NativeBase
            </Text>
          </Link>
          <ToggleDarkMode />
        </VStack>
      </Center>
    </NativeBaseProvider>
  )
}

// Color Switch Component
function ToggleDarkMode() {
  const { colorMode, toggleColorMode } = useColorMode();
  return (
    <HStack space={2} alignItems="center">
      <Text>Dark</Text>
      <Switch
        isChecked={colorMode === "light" ? true : false}
        onToggle={toggleColorMode}
        aria-label={
          colorMode === "light" ? "switch to dark mode" : "switch to light mode"
        }
      />
      <Text>Light</Text>
    </HStack>
  );
}

```
**Expected behaviour**
We should be able to use the size stated in doc
![image](https://user-images.githubusercontent.com/5227509/134918474-30479fdd-d0f6-4e46-813f-3276d8d9e73b.png)

**Platform**
NativeBase version： 3.2
Device: Pixel XL(emulator), redmi note 10 pro(device, apk)
OS: Android 11
React Native version: 0.63.2
Expo sdk version: 42.0
node: 14.17.6
yarn: 1.22.5

**Comment by makkarMeenu** [comment]
This has been resolved and Spinner component only accepts size as "sm", "lg","small" or "large". It also accepts other props as React Native's ActivityIndicator mentioned in documentation.
