### ISSUE TITLE
Add some description what a ButtonGroup is

### ISSUE THREAD

**Issue by trajano** [GeekyAnts/NativeBase#4136]
**Is your feature request related to a problem? Please describe.**

Looking at https://docs.nativebase.io/button#import and the example at https://docs.nativebase.io/button#buttongroup it does not really explain what it is used for.

**Describe the solution you'd like**

It looks the buttons act like a radio button, but the example does not look like a radio button.  It also makes it a bit confusing that the colors are different and does not show the state of the button group

**Describe alternatives you've considered**

**Additional context**

**Comment by amars29** [comment]
Button group is for grouping buttons and share properties such as size, colorScheme to all the buttons within it. We haven’t thought about using it in radio buttons, radio has RadioGroup but it doesn’t function same as Button group as of now.

**Comment by trajano** [comment]
Please indicate that in the documentation.  Since it's lacking that clarity.
