### ISSUE TITLE
Add `ref` to `<Input />` so that you can call `focus()`, 'blur()`, 'clear()` methods

### ISSUE THREAD

**Issue by therunbuddy** [GeekyAnts/NativeBase#4140]
**Is your feature request related to a problem? Please describe.**
At the moment there is no way to programmatically call the `focus()`, 'blur()`, 'clear()` methods on `<Input />`

**Describe the solution you'd like**
Expose the ref on `<Input />` so that the above methods can be called

**Comment by kdgyimah** [comment]
@therunbuddy 
Currently `ref` is being passed as a second parameter.
See: https://github.com/GeekyAnts/NativeBase/blob/master/src/components/primitives/Input/Input.tsx


So you can pass your ref as a second parameter, as it is not currently deconstructed via props and it should work

**Comment by makkarMeenu** [comment]
Unable to reproduce this issue in NativeBase 3.2.2. If you are still facing this issue, please re-open it with proper snack.

**Comment by hotaryuzaki** [comment]
is there any solution for this issue?
