### ISSUE TITLE
rounded is not documented in Box

### ISSUE THREAD

**Issue by trajano** [GeekyAnts/NativeBase#4145]
https://docs.nativebase.io/box uses `rounded` in the example but it does not appear to be documented anywhere as to what the values allowed are.

It appears to be pulling it from `radii` based on the source code.

**Comment by rayan1810** [comment]
Thanks for reporting this @trajano, we will add the props here https://docs.nativebase.io/utility-props#borders-radius with the next Docs update or release.

**Comment by Viraj-10** [comment]
Thanks for Reporting this bug Rounded is now included in docs under utility-props.
