### ISSUE TITLE
How to change the <picker> selected value fontSize

### ISSUE THREAD

**Issue by AymanJitan** [GeekyAnts/NativeBase#415]
I have the picker set up like this
```
          <Picker
              iosHeader="Select Country"
              mode="dropdown"
              selectedValue={this.state.selected}
              onValueChange={this.onValueChange.bind(this)}
          >
              <Item label="中文 (China)" value="key0" />
              <Item label="United States" value="key1" />
              <Item label="Canada" value="key2" />
              <Item label="Germany" value="key3" />
              ...
          </Picker>
```
and I want to adjust the selected value font size.
I tried adding `style={{fontSize: 12}}` to the picker tag, but that didn't work.

**Comment by sankhadeeproy007** [comment]
You have to use prop `textStyle` for that. 
```
textStyle={{fontSize: 12}}
```

**Comment by nimamyscreen** [comment]
You mean something like this ? but it's not working for me
```
<Picker style={styles.picker}
                            iosHeader="Select one"
                            mode="dropdown"
                            textStyle={{fontSize: 12,color:'yellow'}}
                            selectedValue={this.state.tourDuration}
                            onValueChange={this.onValueChange.bind(this)}>
                        <Picker.Item label="One hour" value="1"/>
                        <Picker.Item label="Two hours" value="2"/>
                        <Picker.Item label="Three hours" value="3"/>
                        <Picker.Item label="Four hours" value="4"/>
                        <Picker.Item label="Five hours" value="5"/>
                    </Picker>

picker: {
        color: '#616161',
        borderRadius: 14,
        borderWidth: 1,
        backgroundColor: '#e2e2e2',
        borderBottomWidth: 1 / PixelRatio.get(),
        borderTopWidth: 1 / PixelRatio.get(),
        borderColor: '#484848',
        width: 110,
        height:40,
        marginRight:16
    },
```

**Comment by YKSing** [comment]
It dose not work on Android

**Comment by crest-ccruz** [comment]
Doesn't work on Android for me either.  Any workaround?

**Comment by cstd** [comment]
not work on Android

**Comment by rolandfromrobin** [comment]
textStyle prop has no effect on Android here either

**Comment by shivrajkumar** [comment]
@rolandfromrobin Those props are available only for iOS. Check https://facebook.github.io/react-native/docs/picker.html for Android props

**Comment by rolandfromrobin** [comment]
@shivrajkumar I see, thank you. Do you know of any workaround to style the selectedValue text in Android picker?

**Comment by shivrajkumar** [comment]
@rolandfromrobin You can style the items conditionally on selection.

**Comment by singhalok641** [comment]
I am not able to change the picker text size for my app. What is the right way to do it?

**Comment by Ashutosh21Nigam** [comment]
how i set the font size for <Picker.Item> tag

**Comment by akhil-geekyants** [comment]
@Ashutosh21Nigam NativeBase Picker for android is an implementation of ReactNative Picker. You can check here https://facebook.github.io/react-native/docs/picker.html

**Comment by vinicius-cleves** [comment]
I`ve tried Friendly-Robot`s solution on Android but the touchable region doesn`t scale together with the field.

**Comment by reabbotted** [comment]
@Friendly-Robot  It worked OK for me. I had some extra padding because of it, so I applied a negative margin to fix that. But it's the best solution I've seen.

**Comment by rafael96** [comment]
@Friendly-Robot  It worked OK for me. Thanks a lot.

**Comment by l1br3** [comment]
@Friendly-Robot I upvote, this is genius solution

**Comment by gtiongco95** [comment]
Still on iOS I can't set the font size through the textStyle prop.. Anyone found a solution for this?

**Comment by mdeveloper20** [comment]
Still have problem on Android. textStyle doesn't work at all.

**Comment by wadeem** [comment]
When picker item font size will get supported?

**Comment by evansque** [comment]
@sankhadeeproy007 the problem still persists, why did you close the issue?

**Comment by sootood** [comment]
i have same problem

**Comment by kamlesh1000** [comment]
Still have this issue.

**Comment by approached** [comment]
Same issue, @sankhadeeproy007 can you reopen this issues please.

**Comment by libasoles** [comment]
Tried Friendly-Robot suggestion. Like this:

```
<Picker
      selectedValue={"dummy"}
      style={{ height: 100, transform: [{ scaleX: 1.2 }, { scaleY: 1.2 }] }}
      onValueChange={noAction}
      textStyle={{ fontSize: 60 }}
    >
      <Picker.Item label={texts.myLibrary.boughtBooks} value={"dummy"} />
</Picker>
```

But it has two problems. Typescript complains about the `transform` attribute not being valid/expected.

And the scale... well, you should also change the scale origin, like `transformOrigin: "top left"`... and it's not working for me anyway.

**Comment by SeanCannon** [comment]
The prop you are looking for is `itemStyle` and you need to add it to the `Picker` component, _not_ the `Picker.Item` component. Therefore, `Picker` will likely get both `style` _and_ `itemStyle` in your file.

**Comment by berk9595** [comment]
Here is my fix for Android
         <View
          style={{
            paddingLeft: 16,
            paddingRight: 16,
            marginTop: 16,
            marginBottom: 12,
          }}>
          <View
            style={{
              flexDirection: 'row',
              alignItems: 'center',
              backgroundColor: '#ececec',
              borderRadius: 8,
              padding: 16,
            }}>
            <View
              style={{
                width: '100%',
                borderBottomWidth: 1,
                borderColor: '#e76e3c',
                flexDirection: 'row',
                flex: 1,
                position: 'relative',
                alignItems: 'center',
                height: 32,
              }}>
              <Icon name="ios-pin" size={18} color="#e76e3c" />
              <Picker
                selectedValue={this.state.district}
                style={{
                  width: '100%',
                  paddingBottom: 0,
                  backgroundColor: 'transparent',

                  paddingLeft: 0,
                  fontFamily: 'Montserrat-Regular',
                  transform: [{scaleX: 0.77}, {scaleY: 0.77}],
                  left: -25,
                  position: 'absolute',
                }}
                onValueChange={(itemValue, itemIndex) =>
                  this.setState({district: itemValue})
                }>
                {get(this.props, 'allRegions.allRegions[0].district', [])
                  .sort()
                  .map((reg, index) => (
                    <Picker.Item
                      color="#929292"
                      label={reg}
                      value={reg}
                      key={index}
                    />
                  ))}
              </Picker>
            </View>
          </View>
        </View>

and result was like this :
![image](https://user-images.githubusercontent.com/25593430/71545882-aac91600-29a1-11ea-9f3e-b57693db9fb7.png)

**Comment by jlguida** [comment]
None of the work arounds allow for actual font styling for Android. @berk9595 solutions works great for font size, but not for font weight and many other styling properties. Best solution to have proper control over styling of your dropdown is to change to a new library. Here is a list of some of the best alternatives: https://openbase.io/categories/js/best-react-native-dropdown-libraries

**Comment by qasim483** [comment]
I got it working like this:
`<Picker.Item style={{fontSize:10}} label="All Types" value="all" />`
Set the fontSize to Picker.Item instead of Picker.

**Comment by Salmankhan033** [comment]
**Normal**
```
  {drinksArr.map((val, index) => (
 <Picker.Item
                style={{
                  fontSize: 30,
                  backgroundColor: Colors.Black,
                }}
                fontFamily="font_family"
                color={Colors.Gold}
                label={val.title}
                value={val.title}
                key={index}
              />
```
       **For  selected value:**     
              

 ```{drinksArr.map((val, index) => (
 <Picker.Item
                style={val=="selectedValue"? style.styleOne: styles.stylesOther}
                fontFamily={val=="selectedValue"? "FontFamilyOne": "FontFamilyOther}
                color={Colors.Gold}
                label={val.title}
                value={val.title}
                key={index}
              />
```
