### ISSUE TITLE
There's no `xxs`

### ISSUE THREAD

**Issue by trajano** [GeekyAnts/NativeBase#4154]
The `xxs` size was removed in 3.2.x and replaced with `2xs` but the documentation still refers to `xxs` in the samples https://docs.nativebase.io/default-theme#typography

**Comment by trajano** [comment]
It's missing in the upgrade guide https://docs.nativebase.io/migration/migration-guide-three-point-two

**Comment by makkarMeenu** [comment]
Fixed in NativeBase  documentation.
