### ISSUE TITLE
Please expose Overlay component

### ISSUE THREAD

**Issue by georgii-ivanov** [GeekyAnts/NativeBase#4155]
Just export Overlay component from primitives.
I can prepare a PR for you or you can do it for yourself.

I wanted to implement my own Drawer but I need overlay for that.
Hook isn't really what I want to use for that.

On top of that also please make Menu placement static (so I can use it without trigger element)

**Comment by Viraj-10** [comment]
Hi @georgii-ivanov, Thanks for the suggestion. We will look into it.
