### ISSUE TITLE
useBreakpointResolvedProps should take in any props not just IProp

### ISSUE THREAD

**Issue by trajano** [GeekyAnts/NativeBase#4157]
useBreakpointResolvedProps should be able to take in any prop object because the code for resolveValueWithBreakpoint will fallback to the original value if needed.

**Comment by Viraj-10** [comment]
Hi @trajano, Can you please provide usecase for this request ?

**Comment by trajano** [comment]
It's been a while, but if I recall correctly it's because the type restriction for `useBreakpointResolvedProps` requries either an array or an object, but resolveValueWithBreakpoint which it uses allowed for a simple object and use that as the fallback.  This way the API is consistent.
