### ISSUE TITLE
Expose PresenseTransition animation options for Popover and other animated components

### ISSUE THREAD

**Issue by georgii-ivanov** [GeekyAnts/NativeBase#4158]
Popover is currently animated but no animation props to turn off the animation.

One of the problems with that it's animated improperly (scale animation scales always from the bottom to the top but in my case I need from top to the bottom).

Also, maybe it makes sense to provide option for optimization and customization.

**Comment by Viraj-10** [comment]
Hi @georgii-ivanov , Thanks for suggestion. We will look into it.
