### ISSUE TITLE
Is it possible fro Deck Swiper to swipe when a function call?

### ISSUE THREAD

**Issue by radvc** [GeekyAnts/NativeBase#416]
Hi, I currently working right now in a project with the use of Deck Swiper from native base, is it possible if we press a button the card will swipe?

**Comment by sankhadeeproy007** [comment]
@himanshu-satija Please help him out with the use case here.

**Comment by himanshu-satija** [comment]
@radvc Yes, you can do that by calling `swipeRight` and `swipeLeft` function on the ref of DeckSwiper

```jsx
this.deckSwiper.swipeRight();
...
<DeckSwiper ref={(ds) => {this.deckSwiper = ds;}}>
...
```

**Comment by radvc** [comment]
@himanshu-satija thanks! Its working. @sankhadeeproy007 thanks also
