### ISSUE TITLE
Factory ignores defaults for explicit properties

### ISSUE THREAD

**Issue by CarlosHdez** [GeekyAnts/NativeBase#4164]
**Describe the bug**
A component with `Factory` and a custom theme will ignore defaultProps or baseStyle from the theme if the user passes a custom prop.

**To Reproduce**
Steps to reproduce the behaviour:

1. Create a base Factory as the one in the docs.
2. Add a theme with default props and/or baseStyle that sets a prop like background color.
3. Also make the factory wrapped theme take the background as prop
4. Pass it to the wrapped component 

**Expected behaviour**
When not passing the prop to the wrapped component it takes it but if none is provided it should go back to the theme ones.

**CodeSandBox/Snack link**
https://snack.expo.dev/8YsvmTxk6

**Platform**

- NativeBase version 3.2.0
- Device: Macbook Pro
- OS: Big Sur
- Browser Chrome
- Browser version 93.0.4577.82
- React Native version [e.g. 0.64]
- Expo sdk version 41.0.1
- node 12.22.6
- npm 6.14.15

**Comment by makkarMeenu** [comment]
Resolved in NativeBase 3.2.2. Let us know if you face any issue.
