### ISSUE TITLE
[typescript] tintColor type does not exist on Image but working

### ISSUE THREAD

**Issue by tylim88** [GeekyAnts/NativeBase#4165]
![image](https://user-images.githubusercontent.com/5227509/135932149-398933b2-1388-41b7-9ad4-1e5a1c288a26.png)

![image](https://user-images.githubusercontent.com/5227509/135932858-d1619192-2cd6-4a33-be54-48f46f9cb204.png)

https://snack.expo.dev/@acidcoder/tintcolor-type

**Comment by makkarMeenu** [comment]
Resolved in NativeBase 3.2.2. Let us know if you face any issue.
