### ISSUE TITLE
How to Call Function onOpen of Select Component??

### ISSUE THREAD

**Issue by jaferi512** [GeekyAnts/NativeBase#4166]
**Environment Setup:**
RN: 0.65
Native Base: 3.1.0

**Feature Required:**
I want to Call a Function When we Click the Select Component to Open it because I want to fill the select.items by getting values from my restful api. I've not found something like that to detect the onOpen or something like that. Is there anything like that available then let me know otherwise try to implement this feature in your Select Component because this feature is needed by most of the developers to complete their Features in the complex projects.
**My Code Looks Like That:**
          <Select
            selectedValue={field.value}
            width={'95%'}
            dropdownIcon={
              <Icon2 style={{marginRight: 8}} name="down" size={15} />
            }
            placeholder={field.name}
            onValueChange={itemValue => field.onChange(itemValue)}
            _selectedItem={{
              bg: 'white',
              _text: {color: 'black'},
              endIcon: <Icon2 name="check" size={20} />,
            }}>
            {combo &&
              combo.map(function (ok, i) {
                return <Select.Item key={i} label={ok.name} value={ok.id} />;
              })}
          </Select>
I'll wait for your Response because I really need this feature to implement my ERP Solution using Mobile Applications. 
Thanks in Advance.

**Comment by surajahmed** [comment]
@jaferi512 Support for `onOpen` and `onClose` props have been added to `Select` component in version `3.3.0`.
