### ISSUE TITLE
extendTheme Button _text does not accept fontSize prop

### ISSUE THREAD

**Issue by dlombardi** [GeekyAnts/NativeBase#4167]
**Describe the bug**
I'm unable to get fontSize to apply to the Text within a button from baseStyle in the extendTheme functionality.  fontSize does work when passing it through the _text prop on the Button itself in JSX. I tried applying fontWeight and that seems to work.

**To Reproduce**
Steps to reproduce the behaviour:

Use extendTheme in your project and try to modify the baseStyle of the native base Button element to include the prop _text and within that prop include `fontSize: '200px` (or whatever value) and see that the fontSize is not applied.

**Expected behaviour**
fontSize when supplied to a variant or base style of a Button _text property should apply to the text within the Button

**CodeSandBox/Snack link**
It would be easier for us to debug if you can reproduce the error in a codesandbox link or a snack link. You can use the [codesandbox template](https://codesandbox.io/s/native-base-v3-template-mq6ox)/[snack template](https://snack.expo.io/@mdrehman/nativebase-template).

**Screenshots**

Example of code that does not work:
![Screen_Shot_2021-10-05_at_9 57 55_AM](https://user-images.githubusercontent.com/6826175/136061348-c988cba4-7744-4135-89be-bc078aebcd13.png)

**Platform**

- NativeBase version [e.g. 3.0.6]
- React Native version 0.64
- Expo sdk version 42
- node 14.16.1
- yarn or npm  6.1

**Additional information**

I'm using Expo

**Comment by Brysonmk1984** [comment]
Having a similar issue both with access text and and with extending the theme on different components.  I also can't seem to extend Toast at all. 

`  components: {
    Button: {
      // baseStyle on buttons doesn't seem to work!
      baseStyle: {
        rounded: "md",
        bg: "base.water",
        // Doesn't work!
        // _text: {
        //   color: 'base.primary',
        // },
        marginLeft: 2,
        marginRight: 2,
        _disabled: {
          opacity: 1,
          backgroundColor: "primary.600",
          // Doesn't work!
          // _text: {
          //   color : 'fire.500'
          // }
        },Toast: {
        baseStyle: {
          width: "100%",
          flex: 1,
          margin: 0,
        },
        variants: {
          test: {
            backgroundColor: "black",
            _text: {
              color: "base.white",
            },
          },
        },
      },
      },`

**Comment by MD-REHMAN** [comment]
Thanks, @dlombardi for reporting the issue. We'll the current way to update the `fontSize` of Button using extendTheme will [this](https://snack.expo.dev/@md-rehman/update-button-fontsize-using-extendtheme). As `fontSIze` declared in size. So it should be overwritten from there.

And we're planning to update the docs to better explain the whole customization and theming of components.

**Comment by MD-REHMAN** [comment]
In the meantime, if you're still wondering how the customization works, check out [the blog](https://md-rehman.hashnode.dev/customising-components-in-nativebase) I have written.

**Comment by maxcan** [comment]
Still happening on 3.4.9

**Comment by dlombardi** [comment]
This is still happening

**Comment by oviedo97fer** [comment]
Still happening dec 22..

**Comment by FrenchMajesty** [comment]
Can confirm still an issue March 2023. I am on version 3.4.28.

The `_text {}` styling values I set in the theme for the Button component don't get applied

**Comment by varelycode** [comment]
I am still getting the same issue

**Comment by Simoon-F** [comment]
`"native-base": "^3.4.28"` .
There are also such problems in this version.
