### ISSUE TITLE
Can't set <Picker> Header title using iosHeader attr

### ISSUE THREAD

**Issue by AymanJitan** [GeekyAnts/NativeBase#417]
Picker's header title seems to be hardcoded.

https://github.com/GeekyAnts/NativeBase/blob/master/Components/Widgets/Picker.ios.js#L96

**Comment by sankhadeeproy007** [comment]
You can use the `renderHeader` prop to have your own customized header for Picker.

**Comment by AymanJitan** [comment]
@sankhadeeproy007  That doesn't work, `renderHeader` prop doesn't seem to replace the header.

here's my code.

```
              <Picker
                  renderHeader ={()=>{
                    return (
                      <Header >
                        <Title>Select Country</Title>
                      </Header>
                    )
                  }}
                  mode="dropdown"
                  ...
```
Can you provide a sample code that is working ?

**Comment by AymanJitan** [comment]
`headerComponent` not `renderHeader`
