### ISSUE TITLE
/node_modules/native-base/Fonts/rubicon-icon-font.ttf: No such file or directory

### ISSUE THREAD

**Issue by jonra1993** [GeekyAnts/NativeBase#4170]
**Describe the bug**
When I try to compile my react native project on iOS devices I have a problem related to Fonts.

**To Reproduce**
Steps to reproduce the behaviour:

1. Run project on Xcode

**Expected behaviour**
No error appears

**Platform**

- NativeBase version 3.2.0
- Device: Iphone 13
- OS: iOS11
- React Native version 0.66
- Xcode: 13.0

**Screenshots**
This is the error message on Xcode

![image](https://user-images.githubusercontent.com/23468720/136430492-f96242e9-f4d1-4cce-bfdf-6a890e9e2079.png)

**Comment by jonra1993** [comment]
Hello, @rafaelmaeuer thanks for the information. I followed those steps and it worked correctly. I create a folder Fonts on /node_module/native-base and I added these fonts https://github.com/jonra1993/sonarqube-react-webapp/tree/main/src/assets/Fonts

**Comment by rickgonzalez** [comment]
Is someone going to merge this back into a release or remove the dependency? I would hate to have to copy that stuff in every time I update.

**Comment by devWaleed** [comment]
bump
