### ISSUE TITLE
property _hover not working

### ISSUE THREAD

**Issue by evilripper** [GeekyAnts/NativeBase#4175]
I try in my project, but it doesn't working in the documentation too! 
In the version 3.1.0 is ok in 3.2 no!

https://docs.nativebase.io/pseudo-props-101

The button never become red!

```
import React from 'react';
import { Button, NativeBaseProvider, Center } from 'native-base';
function Component() {
  return (
      // Here you can see _hover will be overrided by _pressed
      <Button _hover={{ bg: 'red.500' }} _pressed={{ bg: 'green.500' }}>
        Press and Hover here
      </Button>
  );
}
export default function () {
  return (
    <NativeBaseProvider>
      <Center flex={1}>
        <Component />
      </Center>
    </NativeBaseProvider>
  );}
```

**Comment by intergalacticspacehighway** [comment]
@evilripper Can you check your react-native-web version and make sure it's above 0.15?
It doesn't work in documentation as Snack player uses 0.13 version which doesn't support hover callbacks on Pressable.
