### ISSUE TITLE
TS error at lib/typescript/theme/base/types.d.ts

### ISSUE THREAD

**Issue by arieloO** [GeekyAnts/NativeBase#4189]
** Before reporting this bug, please...**

- [x] Check the latest documentation: https://docs.nativebase.io/
- [x] Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
- [x] Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
- [x] Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [ ] For discussion purpose make use of NativeBase discord: https://discord.gg/TSgCw2UPmb

**Describe the bug**

typescript check fails at "lib/typescript/theme/base/types.d.ts"

**To Reproduce**

1. Install expo typescript & native-base
2. run tsc (typescript check)
3. See error : 
```
node_modules/native-base/lib/typescript/theme/base/types.d.ts:1:83 - error TS1005: '?' expected.

1 declare type Join<K, P> = K extends string | number ? P extends string | number ? `${K}${'' extends P ? '' : '.'}${P}` : never : never;
                                                                                    ~~~

node_modules/native-base/lib/typescript/theme/base/types.d.ts:1:93 - error TS1005: '}' expected.

1 declare type Join<K, P> = K extends string | number ? P extends string | number ? `${K}${'' extends P ? '' : '.'}${P}` : never : never;
                                                                                              ~~~~~~~

node_modules/native-base/lib/typescript/theme/base/types.d.ts:1:113 - error TS1128: Declaration or statement expected.

1 declare type Join<K, P> = K extends string | number ? P extends string | number ? `${K}${'' extends P ? '' : '.'}${P}` : never : never;
                                                                                                                  ~

node_modules/native-base/lib/typescript/theme/base/types.d.ts:1:115 - error TS1005: ';' expected.

1 declare type Join<K, P> = K extends string | number ? P extends string | number ? `${K}${'' extends P ? '' : '.'}${P}` : never : never;
                                                                                                                    ~

node_modules/native-base/lib/typescript/theme/base/types.d.ts:6:1 - error TS1160: Unterminated template literal.

6
```

3. fails even with the following tsconfig.json : ```
{
    "compilerOptions": {
        ...
        "skipLibCheck": true
    }
    "exclude": ["node_modules/native-base/lib/typescript/theme/base/types.d.ts",]
}
```

**Platform**

- NativeBase version [e.g. 3.2.1]
- Expo sdk version [e.g. 42.0.1]
- node [e.g. 14.16.1]
- yarn or npm [e.g. ^6.1]

**Comment by intergalacticspacehighway** [comment]
@arieloO can you upgrade typescript version to >= 4.2 and let us know if the error still persists?

**Comment by arieloO** [comment]
Just updated : It's all good !
thanks !
