### ISSUE TITLE
Vite cannot resolve module exports

### ISSUE THREAD

**Issue by leoafarias** [GeekyAnts/NativeBase#4196]
**Describe the bug**
When creating an app using Vite as the build tool. I get the following error when running it.

```[vite] Internal server error: Failed to resolve entry for package "native-base". The package may have incorrect main/module/exports specified in its package.json: Failed to resolve entry for package "native-base". The package may have incorrect main/module/exports specified in its package.json.```

I went ahead and checked the modules path and seems to be pointing to `"module": "dist/bundle.web.js"` which does not exist. 

**To Reproduce**
Steps to reproduce the behaviour:

1. `yarn create vite my-react-app --template react-ts`
2. Import native-base component and use on App.tsx

**Expected behaviour**
Vite should be able to locate the native-base module and build properly.

**Platform**

- NativeBase version 3.2.1
- MacOS 11.6

**Comment by Fanna1119** [comment]
I am running into the same issue with another library, On another issue it stated it might have something to do with webpack configs that was used to build the library

**Comment by surajahmed** [comment]
@leoafarias Thanks for reporting! Vitejs doesn't support react-native projects. However, we can build web app with `react-native-web` and Vite. We have to look into this. Hope to find this fix soon.

**Comment by MohamedLamineAllal** [comment]
For the one stumbling with this here a solution that works:

```
export default defineConfig({
  optimizeDeps: {
    esbuildOptions: {
      resolveExtensions: ['.web.js', '.js', '.ts', '.web.ts', '.tsx', '.jsx'],
    },
  },
  plugins: [react()],
  resolve: {
    alias: {
      'react-native': 'react-native-web',
    },
  },
});
```

The main problem is the `.web.js` extension isn't resolved by default.
Add and it works.
Remove it and it stops working.


Credit to https://github.com/vitejs/vite/discussions/8195#discussioncomment-3054164
