### ISSUE TITLE
Switch custom color for disable state

### ISSUE THREAD

**Issue by ugar0ff** [GeekyAnts/NativeBase#4198]
Good Day!
Can you add properties disabled Switch color, f.e. `offTrackDisabledColor, onTrackDisabledColor, onThumbDisabledColor, offThumbDisabledColor` like `offTrackColor, onTrackColor, onThumbColor, offThumbColor`?

**Comment by MD-REHMAN** [comment]
This issue has a dependency on [this](https://github.com/necolas/react-native-web/pull/2164) PR on React-Native-Web. We're waiting for the PR to get merged.

**Comment by sanketsahu** [comment]
@MD-REHMAN Can we use that PR version of React Native Web in a project?
