### ISSUE TITLE
Implmenting Searchbar on the Tool bar

### ISSUE THREAD

**Issue by jojonarte** [GeekyAnts/NativeBase#42]
Do we have some guide on implementing this common functionality? It seems to not yet be added on the current version? Or am I wrong? Please let me know,.

**Comment by sankhadeeproy007** [comment]
Toolbar search is on our to do list. Will ship it with our next release.

**Comment by jojonarte** [comment]
That would be awesome :)

**Comment by sankhadeeproy007** [comment]
Added in v0.5.0
