### ISSUE TITLE
[Question] Set backgroun color in main theme

### ISSUE THREAD

**Issue by gperdomor** [GeekyAnts/NativeBase#420]
Hi

Is possible set the background color in main theme.js instead doing it in every component?

**Comment by sankhadeeproy007** [comment]
There is no `backgroundColor` at the moment in NatveBase.

**Comment by sanketsahusoft** [comment]
@sankhadeeproy007 That's a good though. If platform guidelines allow it. AFAIK, Android Material has a dark version. So, may be we can check that.
