### ISSUE TITLE
Not so good at all !!

### ISSUE THREAD

**Issue by joy-mollick** [GeekyAnts/NativeBase#4200]
I thought it first very easy and nice one . But I found it not enough good and did not have good documentation also. I mean to say you have to learn it by wasting so much time over this.  You had better use stylesheet from react-native. That is easy. It is good for nothing package, sometimes even press and other functions will not work . It is better to leave this package.

**Comment by georgii-ivanov** [comment]
In my opinion, it's not bad at all. It's fresh, universal.
Well, maybe it's not as well optimized as we would like to see... But better than v2.

Lack of documentation - yes. Also removed AppBar, Drawer, DatePicker - yes. Very slow development...
I wish they will speed up and spend more time in the development of this framework and optimization.

**Comment by trajano** [comment]
@joy-mollick do you have any other suggestions? I tried a few and this was the most sane one at the moment bugs and all.  At least to get me over the hurdle of getting an app out before I strip most of the components out.

I already planned from the get go that the only way to ensure that there's reduced vendor lock in is to wrap almost every single component with your own and manage the use

e.g.
```
export { Box } from 'native-base';
```

or something crazy like this which adds i18n to the text component without getting the developers to useLocalization themselves.

```
import { Text as NBText, ITextProps as NBTextProps} from `native-base`;

export TextProps = NBTextProps | (Omit<NBTextProps, 'children'> & { t: string }) // add localization
export function Text({t, props}: TextProps) : JSX.Element {
   const { i18n } = useLocalization();
   if (t) {
     return <NBText {...props}>{i18n(t)}</NBText>
   } else {
    return <NBText {...props} />
   }
}
```

**Comment by trajano** [comment]
> And your notes are too opinionated. I like spacing/sizes (and base 4px size) it's easy to get used to it...

This is mostly an opinion issue.  Which technically shouldn't be here, it should really be in a forum.

**Comment by hemadriDasari1990** [comment]
I’m having same problem. The library is quite big and surely a great library but it’s not quite matured yet. Breakpoints doesn’t work in web. Document doesn’t have enough examples and the components doesn’t support additional props like material UI. Their examples are very poorly written and uses external libraries to create a layout and the code isn’t clean. Small things aren’t working and wasting lot of time but yet no resolution. This is my experience so far. Library is good but it’s a bad headache on head.

**Comment by kenchoong** [comment]
@hemadriDasari1990 https://github.com/GeekyAnts/NativeBase/issues/3997#issuecomment-954605433 here is the solution
