### ISSUE TITLE
Add a message to src/util/createContext.ts about multiple copies of native-base

### ISSUE THREAD

**Issue by trajano** [GeekyAnts/NativeBase#4201]
If there are multiple copies of `native-base` just like multiple copies of React the context resolution will fail.  The error message doesn't indicate what could be the problem as noted in https://github.com/GeekyAnts/NativeBase/issues/4094

After doing some checks and reading through the source the culprit was two copies of the native-base on node_modules.

**Comment by intergalacticspacehighway** [comment]
@trajano can you try 3.2.1 and verify if that fixes it?
