### ISSUE TITLE
Border prop is not passed into Flex as expected

### ISSUE THREAD

**Issue by airen29** [GeekyAnts/NativeBase#4208]
**Describe the bug**
Regarding documentation, Flex inherit Box props and utilities. Border is mossing in properties so it's "not a valid style property"

Properties regarding border that Flex got:
```"borderBottomColor",
  "borderBottomEndRadius",
  "borderBottomLeftRadius",
  "borderBottomRightRadius",
  "borderBottomStartRadius",
  "borderBottomWidth",
  "borderColor",
  "borderEndColor",
  "borderEndWidth",
  "borderLeftColor",
  "borderLeftWidth",
  "borderRadius",
  "borderRightColor",
  "borderRightWidth",
  "borderStartColor",
  "borderStartWidth",
  "borderStyle",
  "borderTopColor",
  "borderTopEndRadius",
  "borderTopLeftRadius",
  "borderTopRightRadius",
  "borderTopStartRadius",
  "borderTopWidth",
  "borderWidth"
```

**To Reproduce**
```
  <Flex border={1}>
    <Text>Flex should have border but it's missing prop</Text>
  </Flex>
```

**Expected behaviour**
Flex will have border property

**Platform**

- NativeBase version [3.2.1-rc.1]
- Device: [iPhone11, Web, Android]
- OS: [iOS/Web/Android]

- React Native version [0.64]
- Expo sdk version [42.0.0]
- node [16.11.0]
- yarn [1.22.15]

**Additional information**

1. Is the bug present in both iOS and Android or in any one of them?
Yes

**Comment by intergalacticspacehighway** [comment]
@airen29 Thanks for reporting. Docs need to be updated, already raised a PR. Can you try using borderWidth/borderColor?
Earlier, we had border prop, but it was not working with tokenized shorthands as `border: 1px solid green.500` and might have added an overhead of additional parsing to support shorthand syntax. 

<img width="242" alt="Screenshot 2021-10-18 at 3 07 36 PM" src="https://user-images.githubusercontent.com/23293248/137706742-80d5dc45-d211-4180-8c14-f27d53cf49d8.png">

**Comment by MD-REHMAN** [comment]
Closing the issue, as it has been fixed.
