### ISSUE TITLE
Properties set in _hover does not override other properties.

### ISSUE THREAD

**Issue by etiennelacoursiere** [GeekyAnts/NativeBase#4210]
**Describe the bug**
Property does not get overrided by the same property set in `_hover` using a Factory

I created a component using the Factory function and was trying to make some styling using `_hover`. 
It work great except it doesn't override values that are already set.

**To Reproduce**
Open the snack and then hover the Choice component

**Expected behaviour**
The border color should be `primary.500` when hovered. Instead it stays `gray.100`

**CodeSandBox/Snack link**
https://codesandbox.io/s/peaceful-taussig-5s1cz?file=/src/components/Choice.tsx

**Platform**

- NativeBase version: 3.2.1
- OS: MacOS BigSur
- Browser: Chrome
- Browser version: Version 94.0.4606.81 (Official Build) (x86_64)
- Expo sdk version https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz
- node 16.3.0
- yarn 1.22.11

**Comment by surajahmed** [comment]
@etiennelacoursiere Thanks for reporting this issue! We've kept it on high priority.
