### ISSUE TITLE
borderColor not accepting theme color value like "red.500" 

### ISSUE THREAD

**Issue by vamshi9666** [GeekyAnts/NativeBase#4211]
**Describe the bug**
borderColor to any component is not accepting color values from theme like "red.500" or "primary.500". Only direct color strings (ex: "#ffffff") are being accepted currently, which is not expected. 

**To Reproduce**
Steps to reproduce the behaviour:

1. Create a demo app 
2. install native-base
3. render `<HStack borderBottomWidth={1} borderBottomColor="red.500" > </HStack/>

**Expected behaviour**

HStack should be rendered with border on bottom.  

**CodeSandBox/Snack link**
It would be easier for us to debug if you can reproduce the error in a codesandbox link or a snack link. You can use the [codesandbox template](https://codesandbox.io/s/native-base-v3-template-mq6ox)/[snack template](https://snack.expo.io/@mdrehman/nativebase-template).

**Screenshots**
![simulator_screenshot_76419A11-9828-4664-99EB-818015259F0D](https://user-images.githubusercontent.com/28837336/137590016-847d473f-de22-4e70-b27c-d69a384682e3.png)

**Platform**
ios 

- NativeBase version [e.g. 3.0.1]
- Browser version [e.g. 22]
- React Native version [e.g. 0.64]
- Expo sdk version [e.g. 41]
- node [e.g. 14.16.1]
- yarn or npm [e.g. 6.1]

**Additional information**

1. Add any other context about the problem here.
2. Is the bug present in both iOS and Android or in any one of them?
3. If you want your issue to be looked at quicker, please attach a snack reproducible with your issue. Makes it easier for us!

**Comment by intergalacticspacehighway** [comment]
@vamshi9666 can you try this template and reproduce the issue here?
https://snack.expo.dev/@nishanbende/hstack-border-color
