### ISSUE TITLE
Card borderColor not coloring bottom of card

### ISSUE THREAD

**Issue by Sorgrum** [GeekyAnts/NativeBase#422]
"react": "^15.3.2",
"react-native": "~0.37.0",
"native-base":"0.5.15"

### Actual Behavior
![<Card style={{borderColor: 'red', }}>](https://cloud.githubusercontent.com/assets/3497076/21810226/f7fd3214-d718-11e6-8e6a-6d94e275cae0.png)

### Expected Behavior
Everything from the above picture but with the border going around the bottom as well

### Steps to reproduce (code snippet or screenshot)
```
                <Container tabLabel='Invites'>
                    <Content style={{padding: 8}} >
                        <Card style={{borderColor: 'red', }}>
                            <CardItem >
                                <Text>NativeBase</Text>
                                <Text note>April 15, 2016</Text>
                            </CardItem>

                            <CardItem cardBody>
                                <Text>
                                    //Your text here
                                </Text>
                                <Button transparent textStyle={{color: '#87838B'}}>
                                    <Icon name="logo-github" />
                                    <Text>1,926 stars</Text>
                                </Button>
                            </CardItem>
                       </Card>
                    <Container>
```
### Is the bug present in both ios and android or in any one of them?
Yes, both

The reason I want to pass the border color through the props is because I want to have the border be a different color depending on whether the card is "active" or not

**Comment by sankhadeeproy007** [comment]
Please use from master till the time we release a newer version.

**Comment by Sorgrum** [comment]
I just copied the Card component from the node_modules folder into my components folder, applied the fix manually and am using that.

**Comment by simakwm** [comment]
Was it fixed in current master?

**Comment by soleilgl** [comment]
use transparent to remove the shadow

**Comment by SupriyaKalghatgi** [comment]
@simakwm Try with NativeBase 2.3.6
