### ISSUE TITLE
Documentation: Drawer Natigation Example Error

### ISSUE THREAD

**Issue by alejolp** [GeekyAnts/NativeBase#4221]
**Describe the bug**

From the Documentation, the example Drawer Natigation displays an error on the website itself:

https://docs.nativebase.io/building-drawer-navigation

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to https://docs.nativebase.io/building-drawer-navigation
2. Click on Example
3. Scroll down to Example

**Expected behaviour**

To see the example.

**Screenshots**

**Platform**

- NativeBase version: Last

**Comment by rayan1810** [comment]
This issue is related to https://github.com/GeekyAnts/nativebase-docs closing it here and creating the issue on nativebase-docs Repo. Please follow this https://github.com/GeekyAnts/nativebase-docs/issues/132.
