### ISSUE TITLE
Button disabled prop doesn't change color on 3.21.0

### ISSUE THREAD

**Issue by macolko** [GeekyAnts/NativeBase#4231]
**Describe the bug**
When applying the `disabled` prop to the `<Button>` component, it disables the button `onPress` functionality but does not change the button color.

```
<Button disabled={true} width="100%" onPress={onStartPress}>
    Start
</Button>
```

The prop works on 3.1.0.

**Platform**

- NativeBase 3.2.1
- Device: Android/iPhone
- React Native 6.1.0
- node 14.15.4
- yarn 1.22.10

**Comment by arryanggaputra** [comment]
@Akashdeep-Patra  regarding this issue, can we set particular color if button `isDisabled` via `extendTheme` ? in the latest version, it's only possible to change the background color
```
          _disabled: {
            bg: '#ddd',
            fontColor:'red'
          },
  ```

**Comment by Akashdeep-Patra** [comment]
@arryanggaputra  well practically it is possible but you still need to check which color name is the isDisabled prop is targetting and then extend that color name, I don't think they support absolute values just like that, but yeah you can check this out.

**Comment by ENT108** [comment]
Button `baseStyle` is not taking `_disabled` props like `bg`. I am unable to style disabled button bg via `themeExtend`.
