### ISSUE TITLE
Input loses some extended component theme when using InputRightElement

### ISSUE THREAD

**Issue by bilmaijer** [GeekyAnts/NativeBase#4234]
Hi!
I want to add shadow to Input component by extending the default theme:
By default it works as expected, however, when I add InputRightElement, the shadow does not work anymore

**To Reproduce**
**Extend theme:**
```
const Input = {
  baseStyle: {
    borderRadius: 'xl',
    shadow: 3,
    bg: 'white',
  },
};

export default extendTheme({
  components: {
    Input,
  },
});
```

**Input with InputRightElement:**
```
import React from 'react';
import { IInputProps, Input as NBInput, Text } from 'native-base';

const Input: React.FC<IInputProps> = ({ isRequired, ...props }) => {
  return (
    <NBInput
      mx="3"
      my="2"
      placeholder="Input"
      w={{
        base: '75%',
        md: '25%',
      }}
      InputRightElement={isRequired ? <Text>REQUIRED</Text> : undefined}
      isRequired={isRequired}
      {...props}
    />
  );
};

export default Input;
```

**Usage**
```
<View style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}>
      <Text>Profile</Text>
      <Input />
      <Input isRequired />
    </View>
```

**Expected behaviour**
Both Inputs should have a shadow

**Screenshots**
![IMG_6D9919D46EF3-1](https://user-images.githubusercontent.com/7389069/138602653-c515325c-f43c-43d3-8e17-787bb8b355a2.jpeg)

**Platform**

- NativeBase version [3.2.1]
- Device: [iPhone Xr]
- OS: [14.7.1]
- React Native version [0.66.0]
- node [v12.14.1]
- npm [6.13.4]

**Comment by makkarMeenu** [comment]
This has been resolved in NativeBase 3.2.2 . Please let us know if you face any issue.
