### ISSUE TITLE
[Avatar] Passing local path to image doesn't load the image

### ISSUE THREAD

**Issue by DanailH** [GeekyAnts/NativeBase#4242]
**Describe the bug**
If you pass a path to image (for example if you want to preview before uploading) the image doesn't render.
```tsx
<Avatar
    source={{
      uri: 'file:///PATH_TO_IMAGE',
    }}
  />
```

**Expected behaviour**
I should be able to see a preview of the image when using a local path, same as the `<Image />` component.

**Comment by Viraj-10** [comment]
Hi @DanailH, solution for the issue is provided and it's working. Closing this bug due to inactivity. You can reopen the issue if required.
