### ISSUE TITLE
Add a `hidden` prop on `Hidden` component

### ISSUE THREAD

**Issue by likeSo** [GeekyAnts/NativeBase#4243]
Thanks for filing an issue 😄!

Please search open/closed issues before submitting. Someone
might have asked the same thing before 😉!

**Is your feature request related to a problem? Please describe.**
I want to hide some elements according to my business logic

**Describe the solution you'd like**
Add a `hidden: boolean` prop to `IHiddenProps`, which directly controls the component visibility 

**Describe alternatives you've considered**

**Additional context**

For now, the `Hidden` component can only hide its children by platform, color mode, or size.
```ts
export interface IHiddenProps {
  /**
   * The from prop takes breakpoint from which the wrapped component is hidden.
   */
  from?: LiteralUnion<'base' | 'sm' | 'md' | 'lg' | 'xl'>;
  /**
   * The till prop takes breakpoint till which the wrapped component is hidden.
   */
  till?: LiteralUnion<'base' | 'sm' | 'md' | 'lg' | 'xl'>;
  /**
   * The only prop takes array of breakpoints on which the wrapped component is hidden.
   * It hides the component starting from that breakpoint to the next breakpoint.
   */
  only?:
    | LiteralUnion<'base' | 'sm' | 'md' | 'lg' | 'xl'>
    | Array<LiteralUnion<'base' | 'sm' | 'md' | 'lg' | 'xl'>>;
  /**
   * The colormode takes the mode on which the wrapped component must be hidden.
   */
  colorMode?: 'light' | 'dark';
  /**
   * The platform takes the platform as string or array for the multiple on which the wrapped component must be hidden.
   */
  platform?:
    | LiteralUnion<'ios' | 'android' | 'web'>
    | Array<LiteralUnion<'ios' | 'android' | 'web'>>;
  /**
   *
   */
  children: React.ReactElement | null;
}
`

**Comment by likeSo** [comment]
Thank you! 
The `&&` operator is simple and practical.
But when it has a lot of children:
```tsx
{
    visible && <Box>
        <Text></Text>
        <Text></Text>
        <Text></Text>
    </Box>
}
```
As we can see, it is not good for debugging and readers. 
It is easy but great to do this!

**Comment by rayan1810** [comment]
Thanks for the suggestion and points we'll keep this in our list and will discuss it and if the team comes to a consensus we will surely add this, closing the issue for now, please feel free to reopen if you have anything further to add.
