### ISSUE TITLE
Invalid DOM prop from MenuItem

### ISSUE THREAD

**Issue by CarlosHdez** [GeekyAnts/NativeBase#4253]
** Before reporting this bug, please...**

1. Check the latest documentation: https://docs.nativebase.io/
2. Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
3. Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
4. Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
5. For discussion purpose make use of NativeBase discord: https://discord.gg/TSgCw2UPmb

**Describe the bug**
Using `MenuItem` shows an error on console ` React does not recognize the "data-nativebaseMenuItem" prop on a DOM element` 
Most likely from https://github.com/GeekyAnts/NativeBase/blob/aae9b8f90cc86459f84bbfeeae52a74b7154f970/src/components/composites/Menu/useMenu.tsx#L58

**To Reproduce**
Steps to reproduce the behaviour:
1. Implement a Menu with some MenuItem
2. Open the devTools
3. Interact with the menu

**Expected behaviour**
There's no error reported on the devTools

**CodeSandBox/Snack link**

**Screenshots**

![Screen Shot 2021-10-29 at 13 06 04](https://user-images.githubusercontent.com/5401623/139482037-78b57ed1-044d-4ae4-93b4-cc8757246f4a.png)

**Platform**

- NativeBase version 3.2.1
- Device: [MacBook Pro]
- OS: [MacOS BigSur]
- Browser [Chrome]
- Browser version [95.0.4638.54]
- React Native version [0.63.1]
- Expo sdk version [41.0.1]
- node [12.22.6]
- npm [6.14.15]

**Additional information**

**Comment by intergalacticspacehighway** [comment]
@CarlosHdez can you share the code-snippet that you're using?

**Comment by CarlosHdez** [comment]
I'm using the same code as in the `Menu` example in the docs
```
return (
             <NativeBaseProvider>
                 <Menu
                         w="190"
                         trigger={(triggerProps) => {
                                 return (
                                         <Pressable accessibilityLabel="More options menu" {...triggerProps}>
                                                 <HamburgerIcon />
                                         </Pressable>
                                 )
                         }}
                 >
                         <Menu.Item>Arial</Menu.Item>
                         <Menu.Item>Nunito Sans</Menu.Item>
                         <Menu.Item>Roboto</Menu.Item>
                         <Menu.Item>Poppins</Menu.Item>
                         <Menu.Item>SF Pro</Menu.Item>
                         <Menu.Item>Helvetica</Menu.Item>
                         <Menu.Item isDisabled>Sofia</Menu.Item>
                         <Menu.Item>Cookie</Menu.Item>
                 </Menu>
         </NativeBaseProvider>
       )
```

**Comment by MD-REHMAN** [comment]
I was unable to reproduce the issue, @CarlosHdez  can you please share which version you were using and does the issue still persists in the latest version.
And if it still does, please share a snack.
