### ISSUE TITLE
Typescript error in Picker Native base

### ISSUE THREAD

**Issue by MuflahNasir** [GeekyAnts/NativeBase#4255]
In native base version 2.12.1 I am getting error on missing properties `selectedValue` & `onValueChange` in Picker. 

Expo CLI 4.10.0 environment info:
    System:
      OS: macOS 11.5.2
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.16.0 - /usr/local/bin/node
      Yarn: 1.22.15 - ~/.yarn/bin/yarn
      npm: 7.11.2 - /usr/local/bin/npm
      Watchman: 2021.06.07.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.0. - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 15.0, DriverKit 20.4, macOS 11.3, tvOS 15.0, watchOS 8.0
    IDEs:
      Xcode: 13.0/13A233 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~40.0.0 => 40.0.1 
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2 
      react-native-web: ^0.15.5 => 0.15.7 
    npmGlobalPackages:
      expo-cli: 4.10.0
    Expo Workflow: managed

**Comment by vid553** [comment]
@MuflahNasir did you solve this issue?
I'm having the same problem...
```
"react": "17.0.2",
"react-native": "0.67.4",
"native-base": "2.15.2",
"typescript": "4.6.3"
```
