### ISSUE TITLE
Rendering FormControl.ErrorMessage without a child is still rendering the component.

### ISSUE THREAD

**Issue by MD-REHMAN** [GeekyAnts/NativeBase#4261]
**Describe the bug**
Rendering FormControl.ErrorMessage without a child is still rendering the component.

**To Reproduce**
Try rendering FormControl.ErrorMessage without any child.

**Expected behaviour**
The component should not render

**Platform**
- NativeBase version [e.g. 3.2.1]

**Comment by makkarMeenu** [comment]
This has been fixed in NativeBase 3.2.2.
