### ISSUE TITLE
Button isLoading disappears

### ISSUE THREAD

**Issue by pierroo** [GeekyAnts/NativeBase#4265]
**Describe the bug**
When isLoading = true on a Button component, the spinner appears but the button disappears entirely, it becomes variant unstyled somehow. The spinner and text are visible, but background color, border etc all disappears.

**To Reproduce**
Just add isLoading props to Button component

**Expected behaviour**
The button losing a bit of opacity on isLoading, usual behavior.

**Screenshots**
![image](https://user-images.githubusercontent.com/17619412/139910787-7580ffa0-e0e1-4b99-a745-500a4b1ffe35.png)

![image](https://user-images.githubusercontent.com/17619412/139910685-e89f5e0b-2e44-402f-a80d-031ea69d8c57.png)

**Platform**

- NativeBase version 3.2.0
- Device: Android & iOS
- OS: All
- React Native version 0.66

**Comment by rayan1810** [comment]
@pierroo Hey thanks for reporting this, it's on us we have a small issue in the Button's theme we are changing the backgroundColor to `warmGray.50` when the Button is in `Loading state`, you can as a workaround pass `_loading={{bg:"color of your choice"}}` for now, we will fix this in next release.

**Comment by Easy-Ez** [comment]
@rayan1810  may i change all button theme  by   [Customising Components ](https://docs.nativebase.io/3.0.6/customizingComponents)  ? thx!
```
          Button: {
            defaultPorps: {
              _loading: {bg: '#f00'},
            },
          },
```
 I tried , but it seems not working

**Comment by ankit-tailor** [comment]
Hi @pierroo , This issue has been resolved in version 3.3.0. Thanks for reporting.

**Comment by ksi9302** [comment]
Hi I'm using NativeBase 3.3.4, The issue still persists.

**Comment by newme616** [comment]
yes I have the same issue

**Comment by freddygarcia** [comment]
I was experiencing this issue in 3.3.11 but updated to 3.4.1 and is working fine now.
