### ISSUE TITLE
Input inside select does not respect wrapper width 

### ISSUE THREAD

**Issue by CarlosHdez** [GeekyAnts/NativeBase#4266]
**Describe the bug**
On web, when reducing the width of a `Select` component, the `Input` inside it wont adapt causing the chevron not to be visible.
This happens only when making the width smaller, when making it larger it does remain floating to the right

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to https://snack.expo.dev/nVx2-7dYO
2. Change the width property on the `Select` to anything lower than 170

**Expected behaviour**
The down pointing arrow should remain visible

**Screenshots**
<img width="169" alt="Screen Shot 2021-11-02 at 16 50 41" src="https://user-images.githubusercontent.com/5401623/139962903-423b24e3-e297-4fd5-9073-50cb13123628.png">

**Platform**

- NativeBase version 3. 2.1
- Device: MacBookPro
- OS: [BigSierra]
- Browser [Chrome]
- Browser version [95]
- React Native version [0.64]
- Expo sdk version [41]
- node [12.22.6]
- npm [6.14.16]

**Additional information**
The issue seems to be only present on Web

**Comment by Viraj-10** [comment]
This issue is fixed in NativeBase@v3.3.0.

**Comment by CarlosHdez** [comment]
I thinks some time at version 3.3.6 this got broken again, if you check the original snack, it works by changing the `native-base` version to `3.3.x` until 3.3.5, on patch 6 it add a scroll bar
