### ISSUE TITLE
Is it possible to close popover from inside the popover? 

### ISSUE THREAD

**Issue by nicholascm** [GeekyAnts/NativeBase#4269]
i am triggering a popover from a button, and inside the popover are a few buttons. Upon clicking one of these buttons, I want the popover to disappear. I haven't found a clear way to manage this in the docs. Closing via tap outside the popover or using the "Popover.CloseButton" works fine, but I need to use my own button. 

Thanks!

**Comment by milkyway044** [comment]
"Popover.CloseButton" works fine on web and ios, but does not work on android. Check the [example](https://docs.nativebase.io/popover#basic ) by running on android…

And also there is no way to **close the window with the cancel button** in the footer inside the popover.

**Comment by intergalacticspacehighway** [comment]
@nicholascm to can use popover's `isOpen` prop (controlled state) to do that. [Check this out](https://snack.expo.dev/iJBwJye5w) 
@milkyway044 this looks like a bug with `Popover.CloseButton` on android.
