### ISSUE TITLE
securityTextEntry not working

### ISSUE THREAD

**Issue by thundenilla** [GeekyAnts/NativeBase#427]
Hi. 

`    "native-base": "0.5.18",
    "react": "15.4.1",
    "react-native": "0.38.0",`

I implement the TextInput for my login screen, and implement the securityTextEntry={true}, but it seems not working. its still showing the words. 

Hi! Thanks for trying out NativeBase!
Due to the overwhelming requests and issues/questions we ask you to add the following details with your issue. im only testing on Android.

**Comment by sankhadeeproy007** [comment]
It's `secureTextEntry` and not `securityTextEntry`
