### ISSUE TITLE
Potential issue in 3.2.2-rc.3

### ISSUE THREAD

**Issue by bilmaijer** [GeekyAnts/NativeBase#4271]
Just wanted to test out your new RC. I'm getting some new errors. Shouldn't it be
`baseStyle?: ((props: any) => StyledProps) | StyledProps;`
here:
https://github.com/GeekyAnts/NativeBase/blob/4b934a662366ba98a7b53b169c1fd59a18571fae/src/theme/index.ts#L8

**Comment by intergalacticspacehighway** [comment]
Thanks for catching it!
