### ISSUE TITLE
Menu.OptionGroup event onChange not work

### ISSUE THREAD

**Issue by dcboy** [GeekyAnts/NativeBase#4276]
** Before reporting this bug, please...**

1. Check the latest documentation: https://docs.nativebase.io/
2. Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
3. Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
4. Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
5. For discussion purpose make use of NativeBase discord: https://discord.gg/TSgCw2UPmb

**Describe the bug**

```
<Menu
                    closeOnSelect={false}
                    w="120"
                    trigger={triggerProps => {
                      return (
                        <Pressable
                          accessibilityLabel="More options menu"
                          {...triggerProps}>
                          <HamburgerIcon size="6" color="white" />
                        </Pressable>
                      );
                    }}>
                    <Menu.OptionGroup
                      defaultValue={1}
                      title="Speed"
                      onChange={(val: any) => {
                       console.log(`onChange:${val}`);  // not trigger
                      }}
                      type="radio">
                      <Menu.ItemOption value={1}>1x</Menu.ItemOption>
                      <Menu.ItemOption value={0.5}>0.5x</Menu.ItemOption>
                      <Menu.ItemOption value={0.25}>0.25x</Menu.ItemOption>
                    </Menu.OptionGroup>
                  </Menu>
```

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

**CodeSandBox/Snack link**
It would be easier for us to debug if you can reproduce the error in a codesandbox link or a snack link. You can use the [codesandbox template](https://codesandbox.io/s/native-base-v3-template-mq6ox)/[snack template](https://snack.expo.io/@mdrehman/nativebase-template).

**Screenshots**

**Platform**

- NativeBase version 3.2.1
- Device: android
- OS: 9.1
- Browser version [e.g. 22]
- React Native version: 0.66.1
- Expo sdk version [e.g. 41]
- node [e.g. 14.16.1]
- yarn or npm [e.g. 6.1]

**Additional information**

1. Add any other context about the problem here.
2. Is the bug present in both iOS and Android or in any one of them?
3. If you want your issue to be looked at quicker, please attach a snack reproducible with your issue. Makes it easier for us!

**Comment by dcboy** [comment]
`
import React, { forwardRef, memo } from 'react';
import MenuGroup from './MenuGroup';
import type { IMenuOptionGroupProps, IMenuOptionContextProps } from './types';
import { useHasResponsiveProps } from '../../../hooks/useHasResponsiveProps';

export const MenuOptionContext = React.createContext<IMenuOptionContextProps>({
  values: [],
  onChange: (_val) => {},
  type: 'checkbox',
});

const MenuOptionGroup = (
  { type, defaultValue, value, onChange, ...props }: IMenuOptionGroupProps,
  ref?: any
) => {
  const internalDefaultValue = defaultValue
    ? Array.isArray(defaultValue)
      ? defaultValue
      : [defaultValue]
    : [];

  const [internalValues, setValues] = React.useState<Array<string | number>>(
    internalDefaultValue
  );
  _onChange = (newValue: string | number) => {
    if (type === 'checkbox') {
      const newValues = [...internalValues];
      if (internalValues.includes(newValue)) {
        newValues.splice(newValues.indexOf(newValue), 1);
        setValues(newValues);
      } else {
        newValues.push(newValue);
        setValues(newValues);
      }
    } else if (type === 'radio') {
      setValues([newValue]);
    }
    onChange && onChange(newValue); // fixed here
  };
  //TODO: refactor for responsive prop
  if (useHasResponsiveProps(props)) {
    return null;
  }
  return (
    <MenuOptionContext.Provider
      value={{
        values: !value
          ? internalValues
          : Array.isArray(value)
          ? value
          : [value],
        onChange:_onChange, // fixed here
        type,
      }}
    >
      <MenuGroup {...props} ref={ref} />
    </MenuOptionContext.Provider>
  );
};

export default memo(forwardRef(MenuOptionGroup));

`

**Comment by cyrus25** [comment]
@dcboy This issue has been fixed.
