### ISSUE TITLE
Button onPress Event not working with Typescript and React

### ISSUE THREAD

**Issue by shubham-ghuge** [GeekyAnts/NativeBase#4284]
**Describe the bug**
I am working on a project (web) with nativebase, react and typescript. And I've tried using onPress event as mentioned in the docs but it's throwing error.

**To Reproduce**
Steps to reproduce the behaviour:

1. Import Button from native-base
2. add onpress on Button component.

**Screenshots**
<img width="1097" alt="Screenshot 2021-11-08 at 5 25 55 PM" src="https://user-images.githubusercontent.com/48974345/140739055-7870cdb5-9885-4429-bfa6-ac457cb01df7.png">

**Comment by intergalacticspacehighway** [comment]
@shubham-ghuge Thanks for reporting. You'll need to install react-native typings to fix it. Run `yarn add @types/react-native -D` in the project. We'll update the docs for the same :)

**Comment by shubham-ghuge** [comment]
@intergalacticspacehighway Thanks man, It solved the onPress issue.
