### ISSUE TITLE
Migration to the last r.c. from 2.15.2 question: how the block of code with ```Root``` has to be migrated properly?

### ISSUE THREAD

**Issue by realtril** [GeekyAnts/NativeBase#4287]
Don't see a ```Root``` in new migration guides, but I can't use it.
This is what I got using ```NativeBaseProvider```instead of ```Root``` that I had before.

So what would be the proper way for migration?

This is what I had in 2.15.2.

```
import { NativeBaseProvider, Root } from 'native-base';

  render() {
    const { themeState, loading } = this.state;
    if (loading) return null;
    return (
      <Provider store={ Store }>
        <AppearanceProvider>
          <SafeAreaProvider>
            <Root>
              <ThemeContext.Provider value={ themeState }>
                <Navigation />
                <FingerprintModal />
              </ThemeContext.Provider>
            </Root>
          </SafeAreaProvider>
        </AppearanceProvider>
      </Provider>
```

**Comment by hotaryuzaki** [comment]
same question, there is no migration guide.
i think the docs and changelog release is really terrible, i cannot find anywhere which mention about Root tag was remove or deprecated. cmiiw
