### ISSUE TITLE
Last CardItem should have borderBottomWidth of 0

### ISSUE THREAD

**Issue by Sorgrum** [GeekyAnts/NativeBase#429]
## react-native, react and native-base version
"react": "^15.3.2",
"react-native": "~0.37.0",
"native-base":"0.5.15"

## Expected behaviour
![image](https://cloud.githubusercontent.com/assets/3497076/21938392/2d8a46fc-d989-11e6-9144-4e55339cba45.png)

## Actual behaviour
![image](https://cloud.githubusercontent.com/assets/3497076/21938412/403ab386-d989-11e6-95f3-9ac93fd3f321.png)

## Steps to reproduce (code snippet or screenshot)
                        <Card style={{borderColor: 'red', }}>
                            <CardItem >
                                <Text>NativeBase</Text>
                                <Text note>April 15, 2016</Text>
                            </CardItem>

                            <CardItem cardBody>
                                <Text>
                                    //Your text here
                                </Text>
                                <Button transparent textStyle={{color: '#87838B'}}>
                                    <Text>1,926 stars</Text>
                                </Button>
                            </CardItem>
                       </Card>

## Screenshot of emulator/device
Same as actual behavior: ![image](https://cloud.githubusercontent.com/assets/3497076/21938412/403ab386-d989-11e6-95f3-9ac93fd3f321.png)

## Is the bug present in both ios and android or in any one of them?
Both

## Any other additional info which would help us debug the issue quicker.
When you change the border color of a Card, if it has CardItem's, the border from the last CardItem cuts off the Card's border.
                        <Card style={{borderColor: 'red', }}>
                            <CardItem >
                                <Text>NativeBase</Text>
                                <Text note>April 15, 2016</Text>
                            </CardItem>

                            <CardItem style={{borderBottomWidth: 0}} cardBody>
                                <Text>
                                    //Your text here
                                </Text>
                                <Button transparent textStyle={{color: '#87838B'}}>
                                    <Text>1,926 stars</Text>
                                </Button>
                            </CardItem>
                       </Card>

**Comment by shivrajkumar** [comment]
fixed in 2.1.3
