### ISSUE TITLE
v3.2.2 has type error

### ISSUE THREAD

**Issue by mononoke-choi** [GeekyAnts/NativeBase#4298]
**Describe the bug**
after upgrading to v3.2.2, i couldn't build next web using native-base.
please support export type when we have 'isolatedModules" flag in typescript project

**To Reproduce**

1. Go to [next.js project](https://docs.nativebase.io/install-next)
2. clone repository and upgrade native-base version from 3.2.1 to 3.2.2
3. insert some code to reproduce type error in index.tsx file
 `import { IBoxProps } from 'native-base/src/components/primitives/Box/types';`
4. build and then you could see 'Type error: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'. error message

**Expected behaviour**
like v3.2.1, i wanna build using predefined type

**Screenshots**
![image](https://user-images.githubusercontent.com/44839313/141642048-8749858a-53bd-4499-b61d-0c09c5548a3d.png)

**Platform**
- NativeBase version [3.2.2]
- Browser [chrome]

**Comment by mononoke-choi** [comment]
@surajahmed It seems to be reproduced another type issue.. :(
![image](https://user-images.githubusercontent.com/44839313/150158417-9a8daedb-e4f5-4f19-8956-665759c2edca.png)

**Comment by mononoke-choi** [comment]
> @mononoke-choi Thanks for reporting! This issue has been fixed in version `3.3.0`.

@surajahmed   It seems to be reproduced another type issue.. :(
![image](https://user-images.githubusercontent.com/44839313/150158417-9a8daedb-e4f5-4f19-8956-665759c2edca.png)

**Comment by surajahmed** [comment]
@mononoke-choi Thanks for reporting! `next build` is crashing in version `3.3.2`,  we're working on it. Hope to push a new version with these fixes soon.

**Comment by surajahmed** [comment]
@mononoke-choi `next build` issue is fixed in version `3.3.3`. 
Let us know if you still face any issues with the build.

**Comment by mononoke-choi** [comment]
![image](https://user-images.githubusercontent.com/44839313/150470350-fb3f7b6c-1b63-40c2-8f9c-fab78d667df6.png)
![image](https://user-images.githubusercontent.com/44839313/150470464-95c54a52-7055-42a0-8406-ba1bace59a90.png)
i still have same problems :( ... in both version 3.3.3 and 3.3.3-rc.6

**Comment by mononoke-choi** [comment]
![image](https://user-images.githubusercontent.com/44839313/158960411-84e73968-19bc-44a5-b014-2056cde1673f.png)

i've been using v3.2.1 since this issue happened
could you let me know how can i fix this?

**Comment by Viraj-10** [comment]
This issue has been fixed in `v3.4.8`.
