### ISSUE TITLE
App does not look the same even with v3CompatibleTheme

### ISSUE THREAD

**Issue by arunim2405** [GeekyAnts/NativeBase#4299]
I tried to update the app from v3.10 and 3.2.2 and also added v3CompatibleTheme to my extendTheme but the app does not look the same at all, the padding is not correct, the font is smaller and border radius seems to not work at all. Attatching some screenshots for reference. Dividers are not visible even though I haven't used the size prop anywhere

![image](https://user-images.githubusercontent.com/47343112/141644693-29a8f80a-ca42-46a1-975e-6e920f631fd6.png)
![image](https://user-images.githubusercontent.com/47343112/141644705-63b6c8ce-9ca1-4545-a9fb-01c3f81da640.png)

![image](https://user-images.githubusercontent.com/47343112/141644716-79e3254c-0d21-4d5d-92d5-0fc43a12e152.png)
![image](https://user-images.githubusercontent.com/47343112/141644729-a901ef28-6d0c-4cb8-b8ae-3cac6347b18d.png)

**Comment by surajahmed** [comment]
@arunim2405 We've made a few theme value changes from version `3.1.*` to `3.2.*` or later due to design inconsistency. 
You might need to make few changes even after using `v3CompatibleTheme`. If you are still facing a lot of problems, please let us know.

**Comment by arunim2405** [comment]
Can we mention this in the docs as well? Instead of fixing the designs I spent hours on figuring out why v3compatibletheme was not working for me.

**Comment by surajahmed** [comment]
@arunim2405 I realize this is disappointing. We'll update the docs with this information. Thank you 👍
