### ISSUE TITLE
Right and Left icons in TextInput

### ISSUE THREAD

**Issue by amanthegreatone** [GeekyAnts/NativeBase#430]
Hi,

I want to know how to get both right and left icons in a text input. Case in point, mobile number text input to have a mobile icon on the left and the validated icons (success / error ) on the right.

Right now I am wrapping the InputGroup with right icon (success / error) and mobile icon (left) inside a view and displaying them inline.

**Comment by shivrajkumar** [comment]
v2.x should solve the issue for you.
