### ISSUE TITLE
3.2.2 Theme.fonts are all undefined.

### ISSUE THREAD

**Issue by trajano** [GeekyAnts/NativeBase#4300]
https://docs.nativebase.io/customizing-fonts says

  fonts: {
    heading: 'Roboto',
    body: 'Roboto',
    mono: 'Roboto',
  },

but

https://github.com/GeekyAnts/NativeBase/blob/9660e606194c19ae9e8af267b15ab604c3e5b302/src/theme/base/typography.ts#L112-L116

claims they should be `undefined`.

**Comment by MD-REHMAN** [comment]
Thanks, @trajano for reporting the issue.

So, with the [customizing-fonts](https://docs.nativebase.io/customizing-fonts ) example we're showing how the user can set `Roboto` font, it'll be more clear go through the above lines. The best place to check the default theme is https://docs.nativebase.io/default-theme, And [here](https://docs.nativebase.io/default-theme#typography) you'll find your answer.

And by default, we're keeping fonts `undefined` so the application can pick the device's/system's default font.

**Comment by trajano** [comment]
@MD-REHMAN  try your example with TypeScript and you should see that it's going to fail due to the type since the theme is defined using the "lazy approach" (which I sometimes do myself) of just letting TypeScript make up based on the value.
