### ISSUE TITLE
How to add FlatList in Modal.Body

### ISSUE THREAD

**Issue by MNevin** [GeekyAnts/NativeBase#4304]
code :
```
<Modal.Body>
      <FlatList
        scrollEnabled={false}
        data={Array(100).fill('item')}
        renderItem={(item) => {
          return <Text>{item}</Text>;
        }}
      />
</Modal.Body>
```
get this warning: 
VirtualizedLists should never be nested inside plain ScrollViews with the same orientation because it can break windowing and other functionality - use another VirtualizedList-backed container instead.

**Comment by maqeelqureshi** [comment]
Have you found the solution of this issue?

I am facing the same on V 3.3.5.
