### ISSUE TITLE
Next.js - Warning: Prop `className` did not match. Server:

### ISSUE THREAD

**Issue by raivieiraadriano92** [GeekyAnts/NativeBase#4305]
I'm following the documentation steps to get started with next.js, but when I run the project on the browser I get this error:

---Warning: Prop `className` did not match. Server:---

I tried a few things to fix this like installing `babel-plugin-styled-components` but it is not working.

Does anyone have the same problem?
Any solutions to fix that?

Steps to reproduce the behaviour:

1. Start a new Next.js project:   `yarn create next-app -e https://github.com/GeekyAnts/nativebase-templates/tree/master/nextjs-with-native-base-typescript`
2. Run `yarn dev`
3. open the browser console

**Screenshots**
![image](https://user-images.githubusercontent.com/14861463/141776684-f6031985-459e-4914-8f5b-2aa85e48b320.png)

**Comment by AngelLoredoAlvarez** [comment]
Does anyone found the solution for this?

**Comment by raivieiraadriano92** [comment]
> Does anyone found the solution for this?

Hi @AngelLoredoAlvarez  , I think I found the solution but forgot to post it here.
Try removing `reactStrictMode: true` from next.config.js.
Let me know if this worked for you :)

**Comment by AngelLoredoAlvarez** [comment]
> > Does anyone found the solution for this?
> 
> Hi @AngelLoredoAlvarez , I think I found the solution but forgot to post it here. Try removing `reactStrictMode: true` from next.config.js. Let me know if this worked for you :)

Hi @raivieiraadriano92, thanks for your response, unfortunately, it didn't work for me, I am still diggin in my code to see if I can find the problem

**Comment by surajahmed** [comment]
@raivieiraadriano92 Thanks for reporting this issue. We're working on Nextjs SSR fixes, it is a work in progress #4479

Hope it will get fixed after this merge.
