### ISSUE TITLE
Why not export `IModalProps` from native-base, I want to import it from `native-base`

### ISSUE THREAD

**Issue by Youngtao1999** [GeekyAnts/NativeBase#4310]
I can't import `IModalProps` from `native-base` when I want to use it

I found it in `native-base/lib/typescript/components/composites/Modal`, But I don't want to import it like `import { IModalProps } from 'native-base/lib/typescript/components/composites/Modal';`, That's stupid.

pls export it.

**Comment by Viraj-10** [comment]
This issue is fixed in nativeBase version 3.3.0.
