### ISSUE TITLE
Seems like Components based on Transition not working well with SSR

### ISSUE THREAD

**Issue by loveholly** [GeekyAnts/NativeBase#4312]
**Describe the bug**

I found that `Dialog`, `ActionSheet` doesn't work well with SSR, since I checked the html document content from my server configured with SSR. However, `Text` works.

**Expected behaviour**

I think those components built on `Transition` should render directly on SSR

- NativeBase version [3.2.1]
- Browser [Chrome]
- React Native version [https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz]
- React Native web version [0.13.12]
- Expo sdk version [42.0.1]
- next version [9.4.4]
- yarn [1.22.11]

**Comment by surajahmed** [comment]
@loveholly Thanks for reporting this issue. We're working on SSR fixes, it is a work in progress https://github.com/GeekyAnts/NativeBase/pull/4479

Hope it will get fixed after this merge.

**Comment by surajahmed** [comment]
@loveholly Can you please try the latest release version `3.3.6`? Let us know if the issue persists.
