### ISSUE TITLE
Facing overlapping issues in floating Inputs

### ISSUE THREAD

**Issue by loveheenavasu** [GeekyAnts/NativeBase#4322]
**Platform**

IOS

- NativeBase version : 2.15.0
- Device: Iphone 7 or later
- OS: IOS
- React Native version: 0.63.4
- node 15

Facing overlapping issues in floating Inputs

![File (1)](https://user-images.githubusercontent.com/55981820/142386993-2bdd1a46-685d-4c14-a03e-a044b012df75.jpg)

**Comment by ankit-tailor** [comment]
Hi @loveheenavasu , Can you please provide snack /  codesandbox link?
