### ISSUE TITLE
Mixed media queries do not work correctly

### ISSUE THREAD

**Issue by CarlosHdez** [GeekyAnts/NativeBase#4323]
**Describe the bug**
When using a mediaQuery with two rules, it only takes one as it's value

**To Reproduce**

1. Go to https://snack.expo.dev/NExwAUpe7
2. Open the example in a separate window
3. Change the height of the window

**Expected behaviour**
The image is only visible on the expected heights of the viewport (from 280 to 480) but it only hides below 280 and with heights larger than 480 the media query stays true and the image visible.

**CodeSandBox/Snack link**
https://snack.expo.dev/NExwAUpe7

**Screenshots**

**Platform**

- NativeBase version [e.g. 3.0.1]
- Device: [Web]
- Browser [Chrome]
- React Native version [e.g. 0.64]
- Expo sdk version [e.g. 43]
- node [e.g. 14.16.1]
- yarn or npm [e.g. 6.1]

**Comment by ankit-tailor** [comment]
Hi @CarlosHdez This issue has been resolved in version 3.3.0. Thanks for reporting.
