### ISSUE TITLE
FontWeight applied to Text component not working when extend theme with fontConfig

### ISSUE THREAD

**Issue by loveholly** [GeekyAnts/NativeBase#4324]
**Describe the bug**

`FontWeight` not setting to Text's stylesheet when extending theme with `fontConfig`. However, it works fine with `v3.0.3`

**Expected behaviour**

`fontWeight` should work well when it is applied to `Text` component like `v3.0.3` did.

**CodeSandBox/Snack link**

Checkout out the [example](https://codesandbox.io/s/modest-worker-yr0qm) here.

**Screenshots**

![image](https://user-images.githubusercontent.com/5133856/142610437-9fa70216-24ff-4ee5-8a5d-cac0e82e9e67.png)

**Platform**

- NativeBase version [v3.2.1]

**Comment by MD-REHMAN** [comment]
Fixing the name of the font from `Robot` -> `Roboto`, fixed it. As `Robot` isn't a valid font.
![Screenshot 2021-11-19 at 7 05 50 PM](https://user-images.githubusercontent.com/25659255/142631568-784fed77-aa40-4d30-b827-f36a2b437977.png)

**Comment by loveholly** [comment]
em...This is what I saw on my side:
![image](https://user-images.githubusercontent.com/5133856/142635778-d03bfe3c-15f3-43c7-8bbe-fe130c296d5a.png)

**Comment by loveholly** [comment]
Also, I think the font name is misspelled though, the `font-weight` won't be influenced, am I wrong on this point?

**Comment by Viraj-10** [comment]
Hi @loveholly, Please check following codesandbox [link](https://codesandbox.io/s/determined-jasper-n9i61?file=/src/App.tsx).
