### ISSUE TITLE
How can I do styled components using NativeBase?

### ISSUE THREAD

**Issue by AshwiniKumar007** [GeekyAnts/NativeBase#4328]
How can I do styled-components using NativeBase? How can I extend the styles of a NativeBase component without doing it through the theme? My use-case is that I want to extend the style of the Text component but on only one screen.

**Comment by MD-REHMAN** [comment]
@AshwiniKumar007 you can make custom variants for Text as I showed in [this snack](https://snack.expo.dev/@md-rehman/adding-variants-to-text). And you can use this variant in your specific scenario.

**Comment by AshwiniKumar007** [comment]
Thanks for the help
