### ISSUE TITLE
Top Tabs Bar Border Bottom Color on Active Tab is the same color as the text Color

### ISSUE THREAD

**Issue by mihirk** [GeekyAnts/NativeBase#433]
The selected(active) tab's underline color right now is controlled by the theme variable `tabTextColor`. Would be great to have a separate theme variable like `tabBorderColor ` or `tabUnderlineColor` to control the bottom border color on the active tab.

This is how the code looks like right now: File -  DefaultTabBar.js
```
var tabUnderlineStyle = {
      position: 'absolute',
      width: deviceWidth / numberOfTabs,
      height: 4,
      backgroundColor: this.getTheme().tabTextColor,
      bottom: 0,
    };

```

Would you be fine with me submitting a PR for it?

**Comment by sankhadeeproy007** [comment]
Yeah, would be great!

**Comment by mihirk** [comment]
@sankhadeeproy007 Implemented it and sent a PR.
https://github.com/GeekyAnts/NativeBase/pull/443

**Comment by sankhadeeproy007** [comment]
Thanks! will take a look into it soon.
