### ISSUE TITLE
Pressable isFocused prop not working android

### ISSUE THREAD

**Issue by BaLaLaLs** [GeekyAnts/NativeBase#4332]
nativebase version: 3.2.1

I think the option of Expo preview web in the document is OK, but Expo Android isfocused doesn't work
![6ll94-dwhb7](https://user-images.githubusercontent.com/23353559/142834615-ef3e30c1-0a1f-492c-a27a-cb9d639d09f9.gif)

**Comment by makkarMeenu** [comment]
On native devices , only `Input` component  has `focused` state but no other component. 
Native devices has `pressed` state.
