### ISSUE TITLE
Can we get a feature for creating initial of any name in Avatar?

### ISSUE THREAD

**Issue by AshwiniKumar007** [GeekyAnts/NativeBase#4333]
How about Avatar component supporting feature for creating initial of any Name.Ex:- if name is Ashwini Kumar and no image is provided so it will generate initial "AK"

**Comment by Ajamuar** [comment]
We can consider adding this feature. But it might take time. If you want, feel free to send a PR.

**Comment by ankit-tailor** [comment]
Hi @AshwiniKumar007 , This feature has been added in version 3.3.0
