### ISSUE TITLE
How can i dismiss keyboard on tap, especially the ios numberpad.

### ISSUE THREAD

**Issue by AshwiniKumar007** [GeekyAnts/NativeBase#4335]

**Comment by jalexandremoreira** [comment]
something along these lines will probably help you:
https://docs.expo.dev/versions/latest/react-native/keyboardavoidingview/

**Comment by AshwiniKumar007** [comment]
I tried 

<TouchableWithoutFeedback onPress={ () => Keyboard.dismiss() }> {rest of the code} </TouchableWithoutFeedback>

**Comment by MD-REHMAN** [comment]
You're stepping in the right direction, just wrap the main `View` with `TouchableWithoutFeedback` and call `Keyboard.dismiss()` it onPress. This should dismiss the Keyboard.

You can read more about this [here](https://stackoverflow.com/questions/29685421/hide-keyboard-in-react-native)
