### ISSUE TITLE
How can I customize the style for IconButton _pressed?  I tried the following but it doesn't work. 

### ISSUE THREAD

**Issue by AshwiniKumar007** [GeekyAnts/NativeBase#4336]
`components: {
    IconButton: {
      baseStyle: {
        _pressed: {
          bg: "red.100:alpha.20",
        },
      },
    },
  }`

**Comment by MD-REHMAN** [comment]
The reason the above code is not working is that the `_pressed` style has been declared in variants style. Do check out [styling doc](https://docs.nativebase.io/icon-button#styling) and [default IconButton style](https://github.com/GeekyAnts/NativeBase/blob/master/src/theme/components/icon-button.ts).

I am also sharing a [snack](https://snack.expo.dev/@md-rehman/updating-iconbutton-variant-style) to better explain how you can extend the theme.

And @AshwiniKumar007 do share simple snack or code sandbox example, it helps a lot. Thanks.
