### ISSUE TITLE
ts-ignore is not working.

### ISSUE THREAD

**Issue by shunki-github** [GeekyAnts/NativeBase#4338]
Currently I am using "native-base@3.2.2" with "React native".

The bug is identical to the one talked about [here](https://github.com/GeekyAnts/NativeBase/issues/4239).
The bug is the same as talked about here, i.e. ts-ignore is not working.

Please help me.

**Comment by Ajamuar** [comment]
Can you share an example of this bug somewhere? The way to reproduce can also help us identify and fix this bug.
