### ISSUE TITLE
Make Storybook more developer friendly by removing dependencies

### ISSUE THREAD

**Issue by 404-html** [GeekyAnts/NativeBase#4341]
**Is your feature request related to a problem? Please describe.**
In order to see how Native Base works in some custom app [existing storybook](https://github.com/GeekyAnts/NativeBase/tree/master/example/storybook) can be imported into it. The problem is that it holds dependencies that doesn't have to be added into the target project, like `formik`, `@expo/vector-icons` and few more. [Example](https://github.com/GeekyAnts/NativeBase/blob/master/example/storybook/stories/components/composites/IconButton/Basic.tsx#L3).

**Describe the solution you'd like**
Change Storybook stories to be pure Native Base, remove custom dependencies. 

**Describe alternatives you've considered**
Looks like `@expo/vector-icons` is used the most. SVG icons could be used instead.

**Comment by Ajamuar** [comment]
Some examples are trying to showcase the ability to integrate with these packages. Removing this might create a new problem of showcasing it somewhere. Can you individually remove the components causing the issue for your use case?
