### ISSUE TITLE
Image source not updated with dark/light mode

### ISSUE THREAD

**Issue by pierroo** [GeekyAnts/NativeBase#4342]
**Describe the bug**
With React Native, I am trying to use "useColorModeValue" to change the path of an image, without success.
For example:
`const image = mode(list_images[name], list_images[`${name}_dark`])` only displays the day mode image; although they both exist and displays well separately.

so my question is: how can we toggle from an image to another based on the color mode?

**Platform**

- NativeBase version : 3.2.2
- Device: all
- React Native version 0.66

**Comment by 404-html** [comment]
This might be related to https://github.com/GeekyAnts/NativeBase/issues/4268
A workaround is to change `key` attribute on the `Image` to force re-render.

**Comment by pierroo** [comment]
> This might be related to #4268 A workaround is to change `key` attribute on the `Image` to force re-render.

This was exactly the issue, thank you so much!
I've spent way too much time trying to fix this. :)

**Comment by makkarMeenu** [comment]
We will use #4268 for further discusssions.
