### ISSUE TITLE
InputGroup renders single child two times

### ISSUE THREAD

**Issue by ocarreterom** [GeekyAnts/NativeBase#4347]
**Describe the bug**
`InputGroup` renders single child two times.

**To Reproduce**
```js
<InputGroup>
  <Input /> {/*  renders two times */}
</InputGroup>
```

**Expected behaviour**
Render only one time.

**CodeSandBox/Snack link**
https://codesandbox.io/s/hardcore-mclaren-4f5ww?file=/src/App.js

**Platform**

- NativeBase version: 3.2.2, 3.3.0-rc

**Comment by ankit-tailor** [comment]
Hi @ocarreterom , This issue has been resolved in version 3.3.0. Thanks for reporting.
