### ISSUE TITLE
Set activeOpacity in Button

### ISSUE THREAD

**Issue by kuoliangkwong** [GeekyAnts/NativeBase#435]
This is not a bug. Would like to request a feature as depicted in title. 

In React Native, it has activeOpacity in TouchableOpacity. I noticed this value is coded to 0.5 in NativeBase Button. Is it possible to add the option so we can set as well?

**Comment by shivrajkumar** [comment]
Added in v2

**Comment by YassineGherbi** [comment]
Has this been removed in V3?
