### ISSUE TITLE
Allow web "type" attribute to be pass to <Input> component

### ISSUE THREAD

**Issue by tlenclos** [GeekyAnts/NativeBase#4353]
It seems that the "type" props on the <Input> component is only use for secure text entry and not passed to the native input component.

https://github.com/GeekyAnts/NativeBase/blob/master/src/components/primitives/Input/InputBase.tsx#L102

**Describe alternatives you've considered**
A custom component input for my forms.

**Additional context**
I wanted to have a type="date" on my input like so but keep the theme of native base

![image](https://user-images.githubusercontent.com/686101/143561160-f761dcae-1682-4e76-90ff-8391aa7e620d.png)

**Comment by Ajamuar** [comment]
@tlenclos Currently expo does not have a web version of DatePicker. We are considering doing a PR for the same. We are also considering adding a DatePicker in NativeBase. In the meanwhile, using web-specific conditional code might help. We will try and create an example snack for the same. You can also look into some community examples in the meanwhile.
