### ISSUE TITLE
Auto Nested Styling

### ISSUE THREAD

**Issue by NilsBaumgartner1994** [GeekyAnts/NativeBase#4359]
**Is your feature request related to a problem? Please describe.**
It would be nice to have automaticly styling of a Box within a Box, so that you can see the nested styling.

**Describe the solution you'd like**
A component or a pseudo prop, which handles the taking of the theme palette.

**Describe alternatives you've considered**
Here is a small component, which is not so good i fear in things of performance.

```
import React, {FunctionComponent} from 'react';
import {Box, useColorModeValue} from "native-base";
import {IBoxProps} from "native-base/lib/typescript/components/primitives/Box/types";

export interface AppState {
	_shadeLevel?: number
}
export const MyThemedBox: FunctionComponent<AppState & IBoxProps> = (props) => {

	let level = props._shadeLevel || 0;

	const maxLevel = 9;
	const minLevel = 0;
	level = Math.min(maxLevel, Math.max(minLevel, level))

	function getShadeByLevel(level){
		if(level===0) return 50;
		return level*100;
	}

	let themeLevel = useColorModeValue(level, maxLevel-level)
	let _myThemeShade = getShadeByLevel(themeLevel);

	const childrenWithProps = React.Children.map(props.children, child => {
		// Checking isValidElement is the safe way and avoids a typescript
		// error too.
		if (React.isValidElement(child)) {
			return React.cloneElement(child, { _shadeLevel: level+1 });
		}
		return child;
	});

	return(
		<Box
			 _light={{
				 bg: 'coolGray.'+_myThemeShade,
			 }}
			 _dark={{
				 bg: 'blueGray.'+_myThemeShade,
			 }}
			 {...props}
		>
			{childrenWithProps}
		</Box>
	)

}
```

**Comment by Ajamuar** [comment]
@NilsBaumgartner1994 Can you please provide some use-case and examples of the same?

**Comment by NilsBaumgartner1994** [comment]
It allows to give automaticly nested shading. Its pretty common and i wondered, that its not implemented.
You dont have to worry about displaying a nested view for the user.

<img width="247" alt="Bildschirmfoto 2021-12-01 um 10 55 32" src="https://user-images.githubusercontent.com/33295329/144212666-4ccdb269-fa15-4d7e-958a-e47b47319f73.png">

**Comment by surajahmed** [comment]
@NilsBaumgartner1994 This might cause some performance issues. We're keeping it open till we have a better solution for this.
