### ISSUE TITLE
[Request Component] Add Flip card component

### ISSUE THREAD

**Issue by congnguyen91** [GeekyAnts/NativeBase#436]
Could you add a FlipCard component. We can touch the card and it flip (default Front Face) ?

Thanks.

**Comment by congnguyen91** [comment]
This is my fork repository
https://github.com/congnguyen91/react-native-flip-card

**Comment by sanketsahusoft** [comment]
@congnguyen91 That's an amazing library and I really appreciate your effort into this. But we are strictly following platform guidelines and we couldn't find a match of this component in Apple's iOS and Google's Material guidelines.
