### ISSUE TITLE
Allow overriding underlying native component

### ISSUE THREAD

**Issue by AndrewIngram** [GeekyAnts/NativeBase#4362]
I'm using `react-native-text-input-mask`, which provides a native component that's ultimately a wrapper around React Native's TextInput (with a few additional props, and a different `onChangeText` signature). I want to use it with NativeBase, as well as all my theme config, but I'm finding that i'm having to reimplement the majority of the `Input` component, including a whole bunch of private APIs that aren't exposed.

I'd be interested in a mechanism that lets us override the underlying native component, something like:

```js
<Input baseComponent={TextInputMask} /* other props */ />

**Comment by Viraj-10** [comment]
Hi @AndrewIngram, Thanks for reporting the issue. We will look into it.
