### ISSUE TITLE
Autocompletion not showing in some components

### ISSUE THREAD

**Issue by arryanggaputra** [GeekyAnts/NativeBase#4370]
I have created a custom theme for the native base

```ts
type CustomThemeType = typeof MyCustomTheme;

declare module "native-base" {
  interface ICustomTheme extends CustomThemeType {}
}

```

The autocompletion works for background in Button, color in Text, but in some other components, the autocompletion is not worked. An example in the `Box` component, when I use the `bg` property the autocompletion does not show my custom theme. Is there any way that I need to adjust regarding this issue? 

## autocompletion works for bg

![image](https://user-images.githubusercontent.com/4743772/144523343-6da44e14-35d7-47f1-aca2-b2491d876c31.png)

## autocompletion not works for color
![image](https://user-images.githubusercontent.com/4743772/144523370-c0e9aead-5d5c-40f2-ade8-1c6c85f8242a.png)

**Comment by surajahmed** [comment]
@arryanggaputra Thanks for reporting! We've fixed this issue in version `3.3.2`.
