### ISSUE TITLE
Custom Theme Type Warning 

### ISSUE THREAD

**Issue by haibert** [GeekyAnts/NativeBase#4375]
**Describe the bug**
I don't believe this is necessarily a bug, it might be just a lack of my knowledge when it comes to TypeScript but I’m creating a custom theme object for NativeBase and inside of it I am adding some extra properties like “bgColor”. Later when accessing these properties through useTheme() the code works, but I get a type warning saying "Property 'bgColor' does not exist on type 'ITheme'" Is there a way to silence this warning? In reality the property exists and my code works absolutely fine.. its only a type warning that is an issue and i'm not sure if there is a way to silence it? 

**To Reproduce**
snack: https://snack.expo.dev/@haibert/typescript-nativebase

**Expected behavior**
For there to be no warning since i'm using the ICustomTheme theme type

**CodeSandBox/Snack link**
It would be easier for us to debug if you can reproduce the error in a codesandbox link or a snack link. You can use the ICustomTheme

**Platform**

- NativeBase version [e.g. 3.0.1]
- Device: [e.g. iPhone12]
- OS: [e.g. iOS15]
- React Native version [e.g. 0.63.3]
- Expo sdk version [e.g. 43]
- node [e.g. 16.16.1]
- yarn or npm [e.g. 6.1]

**Additional information**

**Comment by MD-REHMAN** [comment]
Hi @haibert, one of the main reasons why typing is not showing up for the customized theme is because you have not declared the updated theme. To do that you can simply go through [this](https://docs.nativebase.io/typescript) page.

**Comment by haibert** [comment]
Hi @MD-REHMAN 
I appriciate your response. I just think it would be very useful if you guys allowed the user to add some custom things maybe under a custom:{} object where we can put what ever we need in that wont give a type warning.

**Comment by rayan1810** [comment]
Hey @haibert, as @MD-REHMAN already mentioned If you want to have types for the custom themes you can follow [this](https://docs.nativebase.io/typescript). What you are asking for, I don't think is something NativeBase is aligned with right now,  I'm closing this issue in the meanwhile, please feel free to reopen if you have any other queries.
