### ISSUE TITLE
Fixing overflow value in the input component in theme

### ISSUE THREAD

**Issue by vytch** [GeekyAnts/NativeBase#4378]
** Before reporting this bug, please...**

1. Check the latest documentation: https://docs.nativebase.io/
2. Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
3. Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
4. Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
5. For discussion purpose make use of NativeBase discord: https://discord.gg/TSgCw2UPmb

**Describe the bug**
When installing the latest RC branch, we had a problem with the value of the overflow:
https://github.com/GeekyAnts/NativeBase/blob/98ddc36b83c40148a6a18d54eda7fe03a1136a41/src/theme/components/input.ts#L34

We had to switch it to scroll for the time being so we could start using the RC branch.

Can we release a new RC with that value fixed?

**To Reproduce**
Steps to reproduce the behaviour:

1. Install the latest of master
2. Run the server
3. The issue should show up.

**Comment by Viraj-10** [comment]
Hi @vytch, Thanks for reporting a issue. We have made changes and they are merged into master.
[https://github.com/GeekyAnts/NativeBase/blob/9d1618ed0844addfb4042d6a85a219ca93e27083/src/theme/components/input.ts#L34](url)
