### ISSUE TITLE
iosHeader props bug [ Picker ]

### ISSUE THREAD

**Issue by Clowning** [GeekyAnts/NativeBase#438]
Hey ! 

I'm using the lastest version of NativeBase and when i set a iosHeader on Picker component, nothing append ! There is always "Pick one" :/ ! Do you have an idea?

Thank you!

**Comment by shivrajkumar** [comment]
Seems to work with the latest version(v2.0.x)

**Comment by shivrajkumar** [comment]
Closing the issue due to inactivity. Do let me know if the above doesn't solve the issue.
