### ISSUE TITLE
How to access this.getTheme() in our own components?

### ISSUE THREAD

**Issue by ooicl** [GeekyAnts/NativeBase#439]
Hi!

I'm trying to make my own component while using Native Base. 
How can I make my component looks like Native Base component?
How can I access this.getTheme() in my own component? 
So that I can match the colour and font sizes etc... 

Thanks for any guidance provided.

**Comment by shivrajkumar** [comment]
With v2 you can just eject the theme and customize the components, and can also import the theme variables to create your own components
http://nativebase.io/docs/v2.0.0/customize#

**Comment by AshCoolman** [comment]
@shivrajkumar I'm a bit confused if the list is an ordered list of steps, or a list of optional steps :)

Do I have to run `ejectTheme.js` to:

> Pass the variable i.e platform/material/commonColors.js as the parameter of theme function, which is passed as a value to style prop of component <StyleProvider>

**Comment by shivrajkumar** [comment]
Closing the issue due to inactivity.
