### ISSUE TITLE
[En]When input uses InputRightElement, the focused style does not take effect .[中文]input 在使用InputRightElement时，聚焦的样式不生效 

### ISSUE THREAD

**Issue by asmallxx** [GeekyAnts/NativeBase#4391]
当前版本是3.2.2:
我在使用Input组件时，如果我想变化聚焦时的边框颜色，我添加了代码：
（The current version is 3.2.2:When I was using the Input component, if I wanted to change the color of the border when focusing, I added the code:）

   _focus={{
          style: {
            borderColor: 'red',
          },
        }}

完整的如下所示：（The complete one is as follows：）

      <Input
        placeholder="Search People & Places"
        bg="#fff"
        width="100%"
        borderRadius="4"
        py="3"
        px="1"
        fontSize="14"
        _focus={{
          style: {
            borderColor: 'red',
          },
        }}
      />

目前效果是：（The current effect is:）
https://static.dingtalk.com/media/lADPJxf-vGk_bBfM080FBA_1284_211.jpg_720x720g.jpg?renderWidth=1284&renderHeight=211&renderOrientation=1&isLocal=0&bizType=im

但是，当我添加了"InputLeftElement"和"InputRightElement"时，聚焦的样式就不生效了，问题代码如下所示：（However, when I added "InputLeftElement" and "InputRightElement", the focused style did not take effect. The problem code is as follows:）

      <Input
        placeholder="Search People & Places"
        bg="#fff"
        width="100%"
        borderRadius="4"
        py="3"
        px="1"
        fontSize="14"
        _focus={{
          style: {
            borderColor: 'red',
          },
        }}
        InputLeftElement={
          <Icon
            m="2"
            ml="3"
            size="6"
            color="gray.400"
            as={<MaterialIcons name="search" />}
          />
        }
        InputRightElement={
          <Icon
            m="2"
            mr="3"
            size="6"
            color="gray.400"
            as={<MaterialIcons name="mic" />}
          />
        }
      />

效果是：（The effect is:）
https://static.dingtalk.com/media/lADPJv8gRefR7BrMtM0FBA_1284_180.jpg_720x720g.jpg?renderWidth=1284&renderHeight=180&renderOrientation=1&isLocal=0&bizType=im

此前我参考过这个问题：#4234，但升级后版本并没有得到解决。（I have referred to this question before: #4234, but the version has not been resolved after the upgrade.）

麻烦你们看一下哦~（Please take a look~）

**Comment by sejr1996** [comment]
I have the same problem.
The native base version is 3.2.2

**Comment by amars29** [comment]
@asmallxx  When you are using InputLeftElement (or InputRightElement or both), then both Input & InputLeftElement (or InputRightElement or both) will be sibling components wrapped by a Box component. Whatever styles you are giving will go the the Input Element and not to the parent i.e. Box. 

Solution:
Instead of using styles, you can use utilty props as shown below:
```
 _focus={{
        borderColor: 'red.500',
      }}
```

**Comment by surajahmed** [comment]
Closing this issue, please feel free to reopen if the issue persists. Thanks.
