### ISSUE TITLE
Iconbutton isDisabled not doing anything

### ISSUE THREAD

**Issue by 1nefootstep** [GeekyAnts/NativeBase#4397]
**Describe the bug**
Adding isDisabled={true} to IconButton doesn't disable the button.

**CodeSandBox/Snack link**
Snack: [link](https://snack.expo.dev/@onefootstep/2e0b9c).
In this snack, even though isDisabled={true}, the button can still be pressed and the onPress callback still triggers.

**Platform**

- NativeBase version: 3.2.2

**Comment by joeljose350** [comment]
It looks like IconButton does not have a prop called isDisabled. Here's a [link](https://github.com/GeekyAnts/NativeBase/blob/master/src/components/composites/IconButton/index.tsx) to its definition.

**Comment by cruzlutor** [comment]
It doesn't but it should, I see how it could be useful for disabling icon buttons

**Comment by trymbill** [comment]
It's got `isDisabled` as one of its prop in the documentation: https://docs.nativebase.io/icon-button#props ... so either that should be fixed or the same functionality from the `<Button />` component should be implemented. I vote for the latter.

**Comment by Viraj-10** [comment]
Hi @1nefootstep , Thanks for reporting the issue.
I will look into it.

**Comment by Viraj-10** [comment]
Hi @1nefootstep, This issue is resolved in our latest version of NativeBase 3.3.2.
