### ISSUE TITLE
Pressable doesn't have onPress prop in Typescript definition

### ISSUE THREAD

**Issue by Looooong** [GeekyAnts/NativeBase#4398]
Passing in `onPress` does work. But it's annoying because of Typescript Intellisense error.

**Comment by amars29** [comment]
@Looooong Please check if your project contains "@types/react-native" as dev-dependency. Adding it will resolve the issue.

**Comment by Looooong** [comment]
I have `@types/react-native` as dependency but I used the version that doesn't match with my current `react-native` version. Sorry for the trouble.
