### ISSUE TITLE
NativeBase on NPM comments out Spinner & ProgressBar

### ISSUE THREAD

**Issue by zzimbler** [GeekyAnts/NativeBase#44]
Seems to be commented out in the current master branch as well, but is pretty annoying if you are sharing a code base with multiple people and node_modules are not committed to git (which they shouldn't be).

<img width="582" alt="screen shot 2016-06-16 at 5 00 44 pm" src="https://cloud.githubusercontent.com/assets/538636/16135923/e634bada-33e3-11e6-80a4-750548da9fa1.png">

**Comment by sankhadeeproy007** [comment]
We couldn't get the `ProgressBarAndroid` path to work. So had to comment it out. You can have a go at it  by uncommenting it but it'll error out in Android.

**Comment by zzimbler** [comment]
is it the same issue with the spinner?

**Comment by sankhadeeproy007** [comment]
Yes, Spinner component too. More details here https://facebook.github.io/react-native/docs/progressbarandroid.html

**Comment by sankhadeeproy007** [comment]
Spinner added in [v0.5.0](https://github.com/GeekyAnts/NativeBase/blob/master/Components/Widgets/Spinner.js)

**Comment by zzimbler** [comment]
I just pulled 0.5.0 into my repo to test out and I'm seeing the following for the spinnner 
<img width="378" alt="screen shot 2016-07-21 at 7 06 20 pm" src="https://cloud.githubusercontent.com/assets/538636/17043682/4d0625fc-4f76-11e6-91cc-c3621c288eaa.png">

I'll investigate further and post most to see if I can fix it.

**Comment by zzimbler** [comment]
So i think the issue has to do with the ActivityIndicator. I'm currently on RN 0.27 but ActivityIndicator isn't introduced until 0.28. Probably need to make 0.28 a dependency/requirement for Nativebase 0.5

**Comment by zzimbler** [comment]
Works once upgraded to 0.30 React Native. Going to close this out
