### ISSUE TITLE
logo image in header not just title

### ISSUE THREAD

**Issue by adambene** [GeekyAnts/NativeBase#440]
Hi, I am about to implement the ability to add an image (logo) in the header just as text. It is not possible with the latest release.
What are your thoughts?

**Comment by sankhadeeproy007** [comment]
You can now with 2.0.x!

**Comment by adambene** [comment]
@sankhadeeproy007 I checked the docs but can not find an example for this.
Could you provide one?

**Comment by sankhadeeproy007** [comment]
![screen shot 2017-02-15 at 11 15 54 am](https://cloud.githubusercontent.com/assets/10998047/22962044/6a866df0-f370-11e6-8a8e-c915a7da23be.png)
There you go.

**Comment by adambene** [comment]
@sankhadeeproy007 almost there.
Is it now possible to place an image in the Body without a Button?

**Comment by sankhadeeproy007** [comment]
Yes, did you try?

**Comment by adambene** [comment]
Some weeks ago, but you progress really fast so we'll give it a try again. Keep up the good work! :) Thx!

**Comment by dekkofilms** [comment]
I tried doing this, but i don't know if it is working properly yet ... unless I am missing still missing something:

```
<Header>
  <Left>
    <Button transparent>
      <Icon name='menu' />
    </Button>
  </Left>
  <Body>
    <Image source={{uri: appBrandUrl}} style={{width: 200, height: 35, resizeMode: "contain"}} />
  </Body>
  <Right>
    <Button transparent>
      <Icon name='cart' />
    </Button>
  </Right>
</Header>
```

Or maybe I am misunderstanding the question above about adding an image into the body of the header.

Any suggestions appreciated! Thanks!

**Comment by adambene** [comment]
@dekkofilms The question is this but we have not yet migrated to 2.x.x. Doesn't it work?

**Comment by sankhadeeproy007** [comment]
@dekkofilms What is the output you get from the above code?

**Comment by dekkofilms** [comment]
I did get it to work ... it was an issue with an HTTP image, and not an HTTPS. I forgot Apple generally only accepts secure images only, so sorry for the confusion on thinking it was a Native Base issue. Thanks so much, guys! @adambene @sankhadeeproy007
