### ISSUE TITLE
Checkbox component makes the app crash in production

### ISSUE THREAD

**Issue by pierroo** [GeekyAnts/NativeBase#4404]
**Describe the bug**
Very simply, when using the Checkbox component from nativeBase the app completely CRASHES when in production mode.
( works fine both on emulator and device in testing mode)

**To Reproduce**
Use a CheckBox component, build with the --variant=release flag on Android, and cry.
( didn't test yet on iOS )

**Platform**

- NativeBase version3.2.2
- Device: Android, Huwaei
- OS: 11
- React Native version 0.66.0

Edit: Might as well mention here that the Checkbox performance is insanely poor: the "circle" of active button remains for a good 3 seconds, and the checkmark takes 1-2 seconds to toggle...

**Comment by pierroo** [comment]
Okay found the solution, it seems that the issue was linked to the use of SVG for your CheckBox component.
Adding the following to my proguard.pro (android/app) fixed the problem:

-keep public class com.horcrux.svg.** {*;}

Definitely something you might want to add to your documentation, and/or stop using svg for this component since we all know Android don't like them so much. :)

**Comment by mayank-96** [comment]
@pierroo Thanks for reporting this issue, we'll look into this.

**Comment by mayank-96** [comment]
Hello @pierroo, I tried reproducing the bug, but it is working fine in my case.  You can try rebuilding the app by using following command `npx react-native run-android --variant=release `.

**Comment by pors** [comment]
@mayank-96 Did you enable proguard while trying to reproduce this issue? Because that triggers it. I think it justifies a mention in the documentation.
