### ISSUE TITLE
Function in onPress causes error

### ISSUE THREAD

**Issue by haveamission** [GeekyAnts/NativeBase#4405]
**Describe the bug**
When passing a function into `<Pressable />`, there is an error. This error does not happen on baseline React Native `<Pressable />` - only in Native Base `<Pressable />`

**To Reproduce**
Minimum reproducible example (this is on web, have not tested on other platforms yet):

```
export const TestExample = ({ ...props }) => {
  return (
    <Pressable onPress={() => console.log("test")}>{props.children}</Pressable>
  );
};
```

**Expected behaviour**
Page should load (currently it just crashes), and allow you to click the `<Pressable />`, which would then run the function

**Screenshots**

<img width="1001" alt="Screen Shot 2021-12-11 at 2 32 51 PM" src="https://user-images.githubusercontent.com/10475533/145689257-db5ffa57-0c8b-47e8-8eec-830607df51c9.png">

**Platform**

- NativeBase version: 3.2.2
- Device: Macbook Pro 2017
- OS: MacOS Monterey
- Browser: Chrome
- Browser version: 96.x
- React Native version: .64? Whatever comes in Expo 43
- Expo sdk version: 43
- node: 14.18.1
- yarn or npm: 6.14.15

**Comment by ankit-tailor** [comment]
Hi @haveamission , I am not able to reproduce the issue. Can you please provide snack / code sandbox link?
