### ISSUE TITLE
Checkbok value prop

### ISSUE THREAD

**Issue by grean** [GeekyAnts/NativeBase#4407]
The checkbox value prop is not documented very well yet (3.2.2) and typescript shows this message if you don't provide it.
```
Property 'value' is missing in type '{ children: string; isChecked: boolean; onChange: () => void; colorScheme: string; }' but required in type 'ICheckboxProps'.
```
Workaround 
<Checkbox value='' ....
Could be nice if the prop would be optional at least.
Thanks for your great work.

**Comment by grean** [comment]
My bad i was reading the migration documentation part..

**Comment by MD-REHMAN** [comment]
Thanks for sharing, we have updated our docs completely, hoping the newer docs won't cause those kinds of confusion.
