### ISSUE TITLE
Icon on the right of the Header

### ISSUE THREAD

**Issue by Ciboulette** [GeekyAnts/NativeBase#441]
Hello, 

When we add one Icon in the Header, it goes on the left side. If we add two Icon, they go on each side, so that's cool. I would like to just add ONE icon but on the right side of my header. 

If someone knows how to do it, thanks in advance.. 🥇

**Comment by sankhadeeproy007** [comment]
Use prop `iconRight` with the header.

**Comment by Ciboulette** [comment]
Thank you very much. Where did you find this info ? i didn't find it on the doc

**Comment by sankhadeeproy007** [comment]
Yeah, we're working on improving our docs. We'll soon have a cleaner and more informative interface for docs. Thanks for using NativeBase!
