### ISSUE TITLE
Linear gradient is not working with NativeBase Box component in next js  

### ISSUE THREAD

**Issue by Abhineetk47** [GeekyAnts/NativeBase#4418]
<Box
      h="100%"
      shadow={4}
      flexGrow={1}
      bg={{
        linearGradient: {
          colors: ["red.100", "red.900"],
          //   colors: ["#091B30", "#FEFBF4"],
          start: [0, 0],
          end: [1, 0],
        },
      }}
    >
<Text>this text is inside the linear gradient box</Text>
</Box>

**Comment by Abhineetk47** [comment]
if you are using expo or bare flow, you can install expo-linear-gradient and configure it in the NativeBaseProvider as shown below.


import React from "react"
import { Box, Center, NativeBaseProvider } from "native-base"

export const Example = () => {
  return (
    <Box
      bg={{
        linearGradient: {
          colors: ["lightBlue.300", "violet.800"],
          start: [0, 0],
          end: [1, 0],
        },
      }}
      p={12}
      rounded="lg"
      _text={{
        fontSize: "md",
        fontWeight: "bold",
        color: "white",
      }}
    >
      This is a Box with Linear Gradient
    </Box>
  )
}

const config = {
  dependencies: {
    'linear-gradient': require('expo-linear-gradient').LinearGradient
  }
}

export default () => {
  return (
    <NativeBaseProvider config={config}>
      <Center flex={1}>
        <Example />
      </Center>
    </NativeBaseProvider>
  )
}

**Comment by steve-rodri** [comment]
@Abhineetk47 Any solution to this?
