### ISSUE TITLE
<Hidden /> with XL Screen Size

### ISSUE THREAD

**Issue by AngelLoredoAlvarez** [GeekyAnts/NativeBase#4422]
The <Hidden /> component does not work when screen size is equal to xl, a think that the component props "only", "from" and "till" ignores this breakpoint.

**Comment by ankit-tailor** [comment]
@AngelLoredoAlvarez I am unable to reproduce the issue, Can you please provide the snack?

**Comment by AngelLoredoAlvarez** [comment]
Sorry, I had an error on mi config setup, thank you all for your time.
