### ISSUE TITLE
Switch from native-base isn't working

### ISSUE THREAD

**Issue by pruge** [GeekyAnts/NativeBase#4423]
**Describe the bug**
When you put true in the value attribute
react-native switch works fine.
But, the native-base switch doesn't work.

Am I using the wrong way?

**To Reproduce**
[expo example](https://snack.expo.dev/@prugehada/example)

**Comment by erzzo** [comment]
It's because the native base switch doesn't have a value property. You need to use isChecked. Docs are here https://docs.nativebase.io/switch

**Comment by pruge** [comment]
@erzzo  Thank you. It works fine.
[expo example](https://snack.expo.dev/@prugehada/example)
