### ISSUE TITLE
Divider thickness inside Stack component is not uniform

### ISSUE THREAD

**Issue by rayan1810** [GeekyAnts/NativeBase#4425]
**Describe the bug**
If you add Divider in divider prop of Stack and pass thickness in decimal like 2.5 or 3.5 ... the rendered Dividers look different in thickness for some reason.

**To Reproduce**
Check this Expo Snack ->
https://snack.expo.dev/PEOD9UQXSS

**Expected behaviour**
All the Dividers with the same thickness should look the same.

**CodeSandBox/Snack link**
https://snack.expo.dev/PEOD9UQXSS

**Platform**

- NativeBase version - 3.2.2
- Browser version [e.g. 22]
- React Native version [e.g. 0.64]
- Expo sdk version [e.g. 41]
- node [e.g. 14.16.1]
- yarn or npm [e.g. 6.1]

**Comment by ankit-tailor** [comment]
Hi @rayan1810 , Thanks for reporting, We'll fix it soon.

**Comment by rohit0621** [comment]
Hey @rayan1810 , This is the issue of aliasing. Some browsers will antialias it nicely, others will not. You can read more about it from [here](https://twitter.com/romanshamin_en/status/1546920413908942852).
