### ISSUE TITLE
Toast provider overlaps screen content - prevents onClick events

### ISSUE THREAD

**Issue by ENT108** [GeekyAnts/NativeBase#4430]
After calling `toast.show()` Toast provider overlaps screen elements and prevents onClick events to reach buttons etc.

**Steps to reproduce the behaviour:**
1. render toast using toast.show() over a button of any kind
2. wait for the toast to disappear
3. Click on the button below the toast
4. Notice, the onClick event is not reaching the button

**Expected behaviour**

Toast provider does not cover underling screen elements.

**Screenshots**

<img width="490" alt="Screenshot 2021-12-16 at 17 32 10 (1)" src="https://user-images.githubusercontent.com/25681316/146911472-e1ad557a-eeff-4cf8-bc4c-8850b81cba19.png">

**Platform**

- NativeBase 3.2.2
- Device: iPhone 13
- OS: iOS15.1
- React Native 0.64
- node 16.11.1
- yarn 1.22.11

**Additional information**
NativeBase 3.3.0-rc.4 solves the issue, but introduces much more new issues, components props and theme incompatibility.

**Comment by Viraj-10** [comment]
Hi @ENT108, Thanks for reporting a issue. It is in progress. 😄

**Comment by Viraj-10** [comment]
Hi @ENT108, This Issue has been fixed in the latest version of NativeBase.
