### ISSUE TITLE
Alignment in the Header component.

### ISSUE THREAD

**Issue by TheMarsGuy** [GeekyAnts/NativeBase#444]
react-native: 0.40.0
react: 15.4.2
native-base: 0.5.22

I expect the title to be center aligned  on android.

It is aligned a bit towards the left.

``<Container>
          <Header>
                    <Button transparent>
                        <Icon name='ios-arrow-back' />
                    </Button>
                    <Title>Header</Title>
                    <Button transparent>
                        <Icon name='ios-menu' />
                    </Button>
             </Header>
    </Container>``

![header-android](https://cloud.githubusercontent.com/assets/10371003/22238573/383b67ae-e238-11e6-833f-e0fb8a8b7936.png)

**Comment by sankhadeeproy007** [comment]
According to android design gudelines, the Title is aligned to the left. To change it, please use your custom component inside `Header`.
