### ISSUE TITLE
Any plan for integration with reanimated

### ISSUE THREAD

**Issue by loveholly** [GeekyAnts/NativeBase#4455]
**Is your feature request related to a problem? Please describe.**
Since `Animated` from `react-native` works not so smooth on web, so do u have any plan for integration with `react-native-reanimated` to improve the animation performance?

**Additional context**
`react-native-reanimated@2.2.4` has problem with react-native-web, use `2.2.3` instead.

**Comment by loveholly** [comment]
I can help with PR if possible.

**Comment by fristyr** [comment]
+1 for reanimated 2

**Comment by sanketsahu** [comment]
You might want to check this video by Takuya: https://www.youtube.com/watch?v=k2h7usLLBhY

Here is an example of how to use it with Reanimated: https://github.com/craftzdog/react-native-animated-todo/blob/master/src/components/animated-color-box.tsx

**Comment by fristyr** [comment]
> You might want to check this video by Takuya: https://www.youtube.com/watch?v=k2h7usLLBhY
> 
> Here is an example of how to use it with Reanimated: https://github.com/craftzdog/react-native-animated-todo/blob/master/src/components/animated-color-box.tsx

I actually started to use Native Base on prod because of this video 😅
But I was talking about integrate it inside of Native Base components. In case you also find this useful

**Comment by sanketsahu** [comment]
Oh, that's great to hear! We want to keep the core light and flexible for adoption. But, your point is noted. Let us revisit this decision.
