### ISSUE TITLE
Theme toggle is not working on web

### ISSUE THREAD

**Issue by fristyr** [GeekyAnts/NativeBase#4467]
**Describe the bug**

I have a simple test component to test changing theme modes
When I toggle it on the web, for some reason this does not change the theme.
And + when I toggle it with Toggle component or buttons, all app animations are super slow,
for example opening drawer

And **setColorMode** it's not properly typed
```javascript
const setColorMode: (value: any) => void
```
```javascript
import React from 'react';
import {Text, HStack, Switch, useColorMode, Button} from 'native-base';

export const ThemeToggle = () => {
  const {colorMode, toggleColorMode, setColorMode} = useColorMode();
  return (
    <HStack space={2} alignItems="center">
      <Text>Dark</Text>
      <Switch isChecked={colorMode === 'light'} onToggle={toggleColorMode}></Switch>
      <Text>Light</Text>
      <Button
        onPress={() => {
          setColorMode('light');
        }}
      >
        Test light
      </Button>
    </HStack>
  );
};

```
**Expected behaviour**
No slow animation and toggling theme in web

**Platform**

- NativeBase version "^3.2.2",
- Device: PC
- OS: Windows 10
- Browser Google Chrome
- Browser version 96.0.4664.110
- React Native version 0.64.3
- Expo sdk version 43
- node v14.17.3
- yarn or npm 6.14.13 (npm)

**Comment by vipulbhj** [comment]
Seems like you are missing something. Here is an example you can check.

https://codesandbox.io/s/setcolormode-example-mlj2b?file=/src/components/Example.tsx

**Comment by dylan-westbury** [comment]
I think `setColorMode` must be used as child of `NativeBaseProvider`
