### ISSUE TITLE
Button borderRadius="pill" Error while updating property 'borderRadius' of a view managed by RCTView

### ISSUE THREAD

**Issue by zuhairnaqi** [GeekyAnts/NativeBase#4471]
** Before reporting this bug, please...**

1. Check the latest documentation: https://docs.nativebase.io/
2. Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
3. Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
4. Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
5. For discussion purpose make use of NativeBase discord: https://discord.gg/TSgCw2UPmb

**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

**CodeSandBox/Snack link**
It would be easier for us to debug if you can reproduce the error in a codesandbox link or a snack link. You can use the [codesandbox template](https://codesandbox.io/s/native-base-v3-template-mq6ox)/[snack template](https://snack.expo.io/@mdrehman/nativebase-template).

**Screenshots**

**Platform**

- NativeBase version [e.g. 3.2.2]
- Device: Android
- React Native version [e.g. 0.66.4]
- node [e.g. 14.18.1]
- yarn  [e.g. 1.22.5]

**Additional information**

1. Add any other context about the problem here.
2. Is the bug present in both iOS and Android or in any one of them?
3. If you want your issue to be looked at quicker, please attach a snack reproducible with your issue. Makes it easier for us!
![Screenshot_1640709847](https://user-images.githubusercontent.com/38198958/147588240-c5ac30de-eaec-4f6b-a575-2c55819c4f32.png)

**Comment by mayank-96** [comment]
Hello @zuhairnaqi, 
I am not able to reproduce this bug. Can you please provide the source code with some more insights.

**Comment by zuhairnaqi** [comment]
It was crashing with normal Button tag, however I fixed this using custom theme.
`components: {
      Button: {
        defaultProps: {
          rounded: 'full'
        },
      },`

**Comment by pLavrenov** [comment]
+1 
NativeBase version [3.4.28]
Device: Android
React Native version [0.71.8]
