### ISSUE TITLE
Skeleton with child shows "Warning: Each child in a list should have a unique "key" prop."

### ISSUE THREAD

**Issue by garrett-gottlieb** [GeekyAnts/NativeBase#4473]
** Before reporting this bug, please...**

1. Check the latest documentation: https://docs.nativebase.io/
2. Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/NativeBase/issues
3. Use the latest NativeBase release: https://github.com/GeekyAnts/NativeBase/releases
4. Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
5. For discussion purpose make use of NativeBase discord: https://discord.gg/TSgCw2UPmb

**Describe the bug**
Rendering `<Skeleton.Text>` or just `<Skeleton>` with a child shows the following warning:
```
ExceptionsManager.js:180 Warning: Each child in a list should have a unique "key" prop.

Check the render method of `ForwardRef(SkeletonText)`. See https://reactjs.org/link/warning-keys for more information.
    at Skeleton (http://127.0.0.1:19000/index.bundle?platform=ios&dev=true&hot=false&minify=false:181966:61)
    in SkeletonText
    in RCTView (created by View)
    in View
    in Unknown
```

**To Reproduce**
Steps to reproduce the behaviour:

```tsx
        <Skeleton.Text
          isLoaded={!!audioPost}
          key={`${audioPost?.id}_title`}
          mt='1'
        >
          <Text numberOfLines={2} key={`${audioPost?.id}_title`} mt='1'>
            {audioPost?.title}
          </Text>
        </Skeleton.Text>
```

**Expected behaviour**
No warning, keys are set

**CodeSandBox/Snack link**
It would be easier for us to debug if you can reproduce the error in a codesandbox link or a snack link. You can use the [codesandbox template](https://codesandbox.io/s/native-base-v3-template-mq6ox)/[snack template](https://snack.expo.io/@mdrehman/nativebase-template).

**Screenshots**

**Platform**

- NativeBase version [e.g. 3.0.1] 3.3.0-alpha.12
- Device: [e.g. iPhone6] iPhone 13 Pro Max
- OS: [e.g. iOS8.1] iOS 13
- Browser version [e.g. 22]
- React Native version [e.g. 0.64] 0.64.3
- Expo sdk version [e.g. 41] ~43.0.2
- node [e.g. 14.16.1] v12.22.7
- yarn or npm [e.g. 6.1] yarn v1.22.5

**Additional information**

1. Add any other context about the problem here.
2. Is the bug present in both iOS and Android or in any one of them?
3. If you want your issue to be looked at quicker, please attach a snack reproducible with your issue. Makes it easier for us!

**Comment by surajahmed** [comment]
@garrett-gottlieb Thanks for reporting! This issue has been resolved in version `3.3.0` or later.
