### ISSUE TITLE
DeckSwiper Undefined is not an object (evaluating 'item.image')

### ISSUE THREAD

**Issue by EyesBear** [GeekyAnts/NativeBase#448]
Hi, I tried to copy/paste the sample code for the DeckSwiper and received the error on title. Seems like the entire item object is undefined and not just item.image.
"native-base": "^0.5.22",
"react": "15.4.2",
"react-native": "0.40.0",

**Comment by sankhadeeproy007** [comment]
Can you please check #352 and see if that solution works?

**Comment by sankhadeeproy007** [comment]
Any progress here?
