### ISSUE TITLE
Rounded box prop not working for all buttons using buttons.map

### ISSUE THREAD

**Issue by creix** [GeekyAnts/NativeBase#4481]
**Describe the bug**
I'm experiencing a bug using the rounded prop in box. Right now i'm using two array and the function .map() to display the buttons.
With the first array everything is working fine and the rounded borders are displayed correctly, but with the second array only the first one button in the array have rounded borders, while the others have standard square borders.
I'm using the same style setup for the two array of buttons.
The strange behevior is that if i change the rounded prop and reload the app in Expo Go everything is working fine, but if i change everything else in my app and reload the app suddenly just the first button has rounded borders.

**To Reproduce**
This is my current setup to display two rows of button from my arrays.

```
<HStack alignItems="center" justifyContent="space-evenly" mb="1">
  {dayButtons.map((button, index) => {
    return(
      <Pressable
      onPress={() => {
          setSelectedIndexDay(index); 
        }}
        key={button.day}
      >
        {() => {
          return(
            <Box 
              padding="2" 
              rounded="lg"
              bg={ selectedIndexDay === index ? button.value : null
              }
              _text={ selectedIndexDay === index ? ({
                fontSize: 'md',
                color: 'warmGray.50',
                textAlign: 'center',
                }) 
                : ({
                  fontSize: 'md',
                  color: 'black',
                  textAlign: 'center',
                })
              }
            >
              {button.day}
            </Box>
          )
        }}
      </Pressable>
    )
  })}
  
</HStack>
<Divider bg="purple.500" thickness="2"/>
<HStack alignItems="center" justifyContent="space-evenly" mt="1" >
  {stageButtons.map((button, index) => {
    return(
      <Pressable
        onPress={() => {
          setSelectedIndexStage(index); 
        }}
        key={button.stage}
      >
        {() => {
          return(
            <Box 
              padding="2" 
              rounded="lg"
              bg={ selectedIndexStage === index ? '#ff69e1' : null
              }
              _text={ selectedIndexStage === index ? ({
                fontSize: 'md',
                color: 'warmGray.50',
                textAlign: 'center',
                }) 
                : ({
                  fontSize: 'md',
                  color: 'black',
                  textAlign: 'center',
                })
              }
            >
              {button.stage}
            </Box>
          )
        }}
      </Pressable>
    )
  })}
</HStack>
```

As you can see the code is almost identical in the two `.map()` functions, the first one is rendering everything correctly instead the second one renders correctly just the first button.

**Expected behaviour**
Every button rendered with rounded borders

**Screenshots**

https://user-images.githubusercontent.com/74594484/147891328-d3a7bd7b-3f66-4a23-804b-8ca1955c34e4.mp4

**Platform**

- NativeBase version 3.2.2
- Device: Xiaomi Mi 9T Pro
- OS: Android 11
- React Native version 0.64.3
- Expo sdk version ~43.0.2
- node 14.16.1
- yarn or npm 6.14.12

**Comment by mayank-96** [comment]
Hello @creix you can try this, it will solve the issue
`
    <Pressable
              onPress={() => {
                setSelectedIndexDay(index);
              }}
              key={button.day}
              padding="2"
              rounded="lg"
              bg={selectedIndexDay === index ? button.value : null}
              _text={
                selectedIndexDay === index
                  ? {
                      fontSize: 'md',
                      color: 'warmGray.50',
                      textAlign: 'center',
                    }
                  : {
                      fontSize: 'md',
                      color: 'black',
                      textAlign: 'center',
                    }
              }
            >
              <Text>{button.day}</Text>
   </Pressable>
`

**Comment by mayank-96** [comment]
Hello @creix,  I guess it is happening due to the return method inside `Pressable`. You can try passing the props of `Box` component inside `Pressable` directly, as shown below. It will work fine.

```
            <Pressable
              onPress={() => {
                setSelectedIndexDay(index);
              }}
              key={button.day}
              padding="2"
              rounded="lg"
              bg={selectedIndexDay === index ? button.value : null}
              _text={
                selectedIndexDay === index
                  ? {
                      fontSize: 'md',
                      color: 'warmGray.50',
                      textAlign: 'center',
                    }
                  : {
                      fontSize: 'md',
                      color: 'black',
                      textAlign: 'center',
                    }
              }
            >
              <Text>{button.day}</Text>
            </Pressable>
```

**Comment by creix** [comment]
> 

Hi, thank you for your reply.
I tried it now and while now the border are rounded in the first row of buttons linear gradient is not working anymore and when i press on the buttons conditional style of texts is not working either (The text just remains black).

Do you know how can i made them work again?

**Comment by mayank-96** [comment]
@creix I'll look into this and get back to you asap.

**Comment by creix** [comment]
I resolved this issue adding `overflow='hidden'` as property of the box.
