### ISSUE TITLE
Firefox input rendering should be optimized on focus

### ISSUE THREAD

**Issue by fabarea** [GeekyAnts/NativeBase#4486]
**Describe the bug**

The Input component rendered in Firefox is not the nicest. It is maybe a detailed, but perhaps it is not a big issue to optimize the border when "on-focus". This is a CSS optimization.

**To Reproduce**

Open the form documentation page on Chrome and Firefox and compare

https://docs.nativebase.io/form

**Screenshots**

On Firefox, we see "glitches" around the input component.

<img width="787" alt="image" src="https://user-images.githubusercontent.com/620730/147962148-1b406da6-3f4c-4728-aa4d-454008d8d2e5.png">

On Chrome it looks nice:

<img width="784" alt="image" src="https://user-images.githubusercontent.com/620730/147962072-0c78a64d-eb78-484d-ac85-71645cf26172.png">

**Platform**

Everything latest as of today (January 2022)

**Comment by Viraj-10** [comment]
Hi @fabarea, Thanks for reporting the issue. we will look into it .

**Comment by mayank-96** [comment]
Hello @fabarea, I'm closing this issue as it is fixed in latest version.
