### ISSUE TITLE
Select component doesn't render the _focus and _disabled style prop

### ISSUE THREAD

**Issue by dindustack** [GeekyAnts/NativeBase#4487]
export const Select = {
  Select: {
    baseStyle: {
      boxSizing: "border-box",
      flexShrink: 0,
      width: "100%",
      maxWidth: "250px",
      maxHeight: "32px",
      borderRadius: "8px",
      borderWidth: "1px",
      fontSize: "12px",
      placeholderTextColor: "#FFFFFF",
      backgroundColor: "#EBEBEB",
      borderColor: "#696969",
      color: "#FFFFFF",
      cursor: "pointer",
      _focus: {
        style: {
          bg: "#F2F2F2",
          borderColor: "#0099FF",
          color: "#444444",
        },
      },
      _disabled: {
        style: {
          bg: "type",
          borderColor: "#0099FF",
          color: "#444444",
          opacity: 0.6,
        },
      },
    },
    defaultProps: {
      _focus: {
        style: {
          bg: "#F2F2F2",
          borderColor: "#0099FF",
          color: "#444444",
        },
      },
      _disabled: {
        style: {
          bg: "type",
          borderColor: "#0099FF",
          color: "#444444",
          opacity: 0.6,
        },
      },
    },
  },
};

**Comment by mayank-96** [comment]
@dindustack Thanks for reporting, we'll look into this.

**Comment by mayank-96** [comment]
Hello @dindustack, you can try below syntax. Check [Customising components in NativeBase](https://md-rehman.hashnode.dev/customising-components-in-nativebase) for more details.
```
  const theme = extendTheme({
    components: {
      Select: {
        baseStyle: {
          _item: {
            _disabled: {
              bg: 'red.500',
            },
          },
        },
      },
    },
  });
```

**Comment by dindustack** [comment]
Thanks @mayank-96 for sharing
