### ISSUE TITLE
Windows compatibility - package.json compile script

### ISSUE THREAD

**Issue by Cody-G-G** [GeekyAnts/NativeBase#449]
Since 0.5.21, the compile script was added in package.json, which runs bash commands, breaking Windows compatibility. I am not able to perform "npm install" on NativeBase because of this. The error I am getting is the following:

> npm ERR! code ELIFECYCLE
> npm ERR! native-base@0.5.22 prepublish: `npm run compile`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the native-base@0.5.22 prepublish script 'npm run compile'.

Given this, what is the recommended approach for Windows users ?

**Comment by mribbons** [comment]
Hi,
I am able to consume the lib on windows. I have git installed to the path, that might help as it has some additional commands.

I am also able to run npm run-script compile ok on a cloned version of the current latest commit, https://github.com/GeekyAnts/NativeBase/commit/3f7d15ab36e2fc14e8a9f0503ad0e5b09cd913ca.

**Comment by SupriyaKalghatgi** [comment]
@Cody-G-G @mribbons Please check with the latest of NativeBase
