### ISSUE TITLE
[Colors type] theme base's derived colors without type

### ISSUE THREAD

**Issue by Youngtao1999** [GeekyAnts/NativeBase#4494]
path: `src/theme/base/colors.tsx`

1. `const theme = useTheme()`, normal colors with type, look this:
![image](https://user-images.githubusercontent.com/69896089/148324370-de993dcd-fbe1-4c91-b5a8-a0842ac39295.png)
2. but derived colors without type notice, look thes:
![image](https://user-images.githubusercontent.com/69896089/148324600-7a133b7c-c650-45dd-b806-b8e51dc3f610.png)
3. and i  use derived colors with index will error:
![image](https://user-images.githubusercontent.com/69896089/148324679-d9ef82d9-3044-45f6-82e4-006cc5764804.png)

In fact, it is have value,  because assign normal colors to derived colors:
![image](https://user-images.githubusercontent.com/69896089/148325076-11829d60-69f3-4c4e-ae7d-71c21b960d48.png)

so i resolved for this PR, only add type: https://github.com/GeekyAnts/NativeBase/pull/4493

**Comment by surajahmed** [comment]
@Youngtao1999 Thanks for reporting! We've tried merging your PR, but this caused some other type of issue with the build. We're looking into this.

**Comment by surajahmed** [comment]
This issue has been fixed in version `3.3.2` or later.
