### ISSUE TITLE
Badge Text Color No Longer Changeable

### ISSUE THREAD

**Issue by zzimbler** [GeekyAnts/NativeBase#45]
Per documentation you need to pass the color of the text into the styles property, however with the new code update you can no longer change text color to anything other than the theme colors. This is counter to the documentation http://nativebase.io/docs/v0.4.6/components#badge

Seems to be with the move to View wrapping the text when you pass the color into the style prop it will toss errors because those properties get attached to the View. To correct this you need to either create a new property that you can pass in to change the Text color or move back to wrapping a Text element only.

**Comment by sankhadeeproy007** [comment]
Thanks for pointing it out. Will fix with next release.

**Comment by sankhadeeproy007** [comment]
Fixed with [v0.5.0](https://github.com/GeekyAnts/NativeBase/blob/master/Components/Widgets/Badge.js)
