### ISSUE TITLE
Upgrade dependency to React 17.

### ISSUE THREAD

**Issue by y471n** [GeekyAnts/NativeBase#4503]
When can we expect an increase in upgrading dependencies to React 17, this is a breaking requirement to upgrade Expo.

**Comment by Viraj-10** [comment]
Hi @y471n , Thanks for reporting the issue. We are working on react and react native upgradation.

**Comment by Viraj-10** [comment]
Hi @y471n, are you facing any locking issue while upgrading expo version ?
