### ISSUE TITLE
Working with both versions (Version 2 - Version 3)

### ISSUE THREAD

**Issue by RenanNeitzel** [GeekyAnts/NativeBase#4506]
Hello everybody.

I have an app that is still using NativeBase version 2, and we are working on moving the app to version 3. But this will happen gradually.
At the moment I have an alias to be able to use both versions, that way we don't break our application with the components that are still in version 2.

But now we encounter a critical issue about this form of migration. In version 2 we also have the defaultTheme, and understand that there are a lot of customizations. And we also need to prepare customizations for what we are already migrating to the new version.

What we need to know:
Is there a way we can use components from both versions and specify customizations for each of them?

Infos about project:

- Alias to both versions

```
"native-base": "3.2.2",
"native-base-2": "npm:native-base@^2.15.2",

```

- How NativeBase is built in version 2:
```
import {Root, StyleProvider} from 'native-base';
import React from 'react';

import {App} from '../App';
import defaultTheme from '../themes/common';
import {getTheme} from '../themes/default';

export const RootComponent = () => {
  return (
    <StyleProvider style={getTheme(defaultTheme)}>
      <Root>
        <App />
      </Root>
    </StyleProvider>
  );
};

```

- defaultTheme structure in version 2:

![Screen Shot 2022-01-07 at 16 44 42](https://user-images.githubusercontent.com/41584304/148598587-2460dea0-6121-4b93-8d83-8daa38bd90e9.png)

- File theme/default/index.ts in version 2, is like:

```
import platform from '@~/themes/common';
import bodyTheme from '@~/themes/default/components/body';
import buttonTheme from '@~/themes/default/components/button';
import headerTheme from '@~/themes/default/components/header';
import leftTheme from '@~/themes/default/components/left';
import rightTheme from '@~/themes/default/components/right'

export const getTheme = (variables = platform) => {
  const theme = {
    variables,
    'NativeBase.Left': {
      ...leftTheme(),
    },
    'NativeBase.Right': {
      ...rightTheme(),
    },
    'NativeBase.Body': {
      ...bodyTheme(),
    },

    'NativeBase.Header': {
      ...headerTheme(variables),
    },

    'NativeBase.Button': {
      ...buttonTheme(variables),
    },
  };

  const cssifyTheme = (grandparent: any, parent: any, parentKey: any) => {
    _.forEach(parent, (style, styleName) => {
      if (
        styleName.startsWith('.') &&
        parentKey &&
        parentKey.indexOf('.') === 0
      ) {
        if (grandparent) {
          if (grandparent[styleName]) {
            grandparent[styleName][parentKey] = style;
          } else {
            grandparent[styleName] = {};
          }
        }
      }

      if (
        style &&
        typeof style === 'object' &&
        styleName !== 'fontVariant' &&
        styleName !== 'transform'
      ) {
        cssifyTheme(parent, style, styleName);
      }
    });
  };

  cssifyTheme(null, theme, null);

  return theme;
};

```

- How it is necessary to build NativeBase in version 3:
```
import React from 'react';
import 'react-native-gesture-handler';
import {AppRegistry} from 'react-native';
import {App} from './src/App';
import {name as appName} from './app.json';
import {NativeBaseProvider} from 'native-base';
import {defaultTheme} from './src/themes/default';

function RootComponent() {
  return (
    <NativeBaseProvider theme={defaultTheme}>
      <App />
    </NativeBaseProvider>
  );
}
```

- defaultTheme structure in version 3:
![Screen Shot 2022-01-07 at 16 53 36](https://user-images.githubusercontent.com/41584304/148599640-a0ac1593-499f-48a7-b2d0-32d9855a3086.png)

- defaultTheme file is like:

```
import {extendTheme} from 'native-base';

export const defaultTheme = extendTheme({
  config: {
    useSystemColorMode: true,
  },
  colors: {
    ...
  },
  fontConfig: {
    ...
  },
  fontWeights: {
    ...
  },
  fontSizes: {
    ...
  },
  fonts: {
    ...
  },
  components: {
    ...
  },
});

type CustomThemeType = typeof defaultTheme;

declare module 'native-base' {
  interface ICustomTheme extends CustomThemeType {}
}

```

How can I work with both versions and both defaultTheme configs ?

**Comment by MD-REHMAN** [comment]
From what I can see you have checked all the right boxes, this should work. Can you describe the exact problem you're facing if the below code doesn't be of any help?

```
import React from 'react';
import {App} from './src/App';
import {name as appName} from './app.json';
import {Root, StyleProvider} from 'native-base-2';
import {NativeBaseProvider} from 'native-base';
import {defaultTheme as defaultThemev3} from './src/themes/default';
import defaultTheme from '../themes/common';
import {getTheme} from '../themes/default';

export const RootComponent = () => {
  return (
    <NativeBaseProvider theme={defaultThemev3}>
      <StyleProvider style={getTheme(defaultTheme)}>
        <Root>
          <App />
        </Root>
      </StyleProvider>
    </NativeBaseProvider>
  );
};
```

In this case, v3 components will pick the `defaultThemev3` that have been passed and won't interfere with v2 components. I have tried something similar in an expo app without a custom v2 theme.

**Comment by RenanNeitzel** [comment]
> From what I can see you have checked all the right boxes, this should work. Can you describe the exact problem you're facing if the below code doesn't be of any help?
> 
> ```
> import React from 'react';
> import {App} from './src/App';
> import {name as appName} from './app.json';
> import {Root, StyleProvider} from 'native-base-2';
> import {NativeBaseProvider} from 'native-base';
> import {defaultTheme as defaultThemev3} from './src/themes/default';
> import defaultTheme from '../themes/common';
> import {getTheme} from '../themes/default';
> 
> export const RootComponent = () => {
>   return (
>     <NativeBaseProvider theme={defaultThemev3}>
>       <StyleProvider style={getTheme(defaultTheme)}>
>         <Root>
>           <App />
>         </Root>
>       </StyleProvider>
>     </NativeBaseProvider>
>   );
> };
> ```
> 
> In this case, v3 components will pick the `defaultThemev3` that have been passed and won't interfere with v2 components. I have tried something similar in an expo app without a custom v2 theme.

**Comment by RenanNeitzel** [comment]
Hey @MD-REHMAN,

I haven't tried this format involving the app by both themes. There was a problem naming my folders too. With these tweaks, now everything worked.

Thanks!
