### ISSUE TITLE
Expose duration on Modal/ActionSheet - Allow for custom values

### ISSUE THREAD

**Issue by thispastwinter** [GeekyAnts/NativeBase#4513]
It would be nice if the Modal and ActionSheet respectively had a openDuration/closeDuration prop. Maybe the current hardcoded values could be the defaults, and you could pass in custom values for slower or faster animations? In my case, I'd love to be able to slow them down a bit.

**Comment by thispastwinter** [comment]
See this [PR](https://github.com/GeekyAnts/NativeBase/pull/4536) as an example.

**Comment by Viraj-10** [comment]
Hi @thispastwinter, Thanks for reporting this issue. We will look into it soon 😄 .

**Comment by Viraj-10** [comment]
Hi @thispastwinter, We have introduced new internal props. `_fade, _slide, _backdropFade` lets you control animation on these components.

**Comment by thispastwinter** [comment]
@Viraj-10 awesome! This is great. Thanks!
