### ISSUE TITLE
Skeleton Missing from Native Base v3.2.2 Docs

### ISSUE THREAD

**Issue by SanchitB23** [GeekyAnts/NativeBase#4515]

**Comment by Viraj-10** [comment]
Hi @SanchitB23,  Thanks for Reporting the issue. we have added skeleton in our docs. they are in beta right now you can check them [here](https://beta-docs.nativebase.io/next/skeleton).

**Comment by Viraj-10** [comment]
Hi @SanchitB23, Docs are live you can check [Here](https://docs.nativebase.io/next/skeleton).
