### ISSUE TITLE
Input `underlined` variant wrong style

### ISSUE THREAD

**Issue by ocarreterom** [GeekyAnts/NativeBase#4517]
**Describe the bug**
The `Input` `underlined` version has wrong style in v3.3.1

**To Reproduce**
```js
<Input variant='underlined' />
```

**CodeSandBox/Snack link**
https://snack.expo.dev/b-4mryXeS

**Screenshots**
<table>
  <tr>
    <th>v3.2.1
    <th>v3.3.1
  <tr>
    <td><img width="198" alt="Captura de pantalla 2022-01-12 a las 8 56 48" src="https://user-images.githubusercontent.com/11599942/149086815-d07ee194-2587-4658-9d10-b3ea8a908707.png">
    <td><img width="183" alt="Captura de pantalla 2022-01-12 a las 8 56 10" src="https://user-images.githubusercontent.com/11599942/149086849-33a58092-1cd7-4dcb-9de0-7a0e38e0317b.png">
</table>

**Platform**
- NativeBase version v3.3.1

**Comment by Viraj-10** [comment]
Hi @ocarreterom ,
This Issue has been fixed in NativeBase V3.3.2.
