### ISSUE TITLE
Picker default value

### ISSUE THREAD

**Issue by Clowning** [GeekyAnts/NativeBase#452]
Hi NativeBase team,

First of all, thank for your collection of components it's very good !!

But i have a problem, how can i set a default text in my picker if no item is selected ? Like "Please pick one on this list" when user doesn't selected an item?

Thank by advance! :)

**Comment by sankhadeeproy007** [comment]
Hi @Clowning, thanks for your appreciation!
NativeBase picker has the same use case as RN picker. So can you tell us how it is handled by RN itself? So that we can have similar use cases.

**Comment by sankhadeeproy007** [comment]
defaultLabel prop added

**Comment by LaVielle** [comment]
I was just looking this up today, the prop is now called `placeholder` and it only works on iOS. See: http://docs.nativebase.io/Components.html#picker-placeholder-without-note-headref

**Comment by mernxl** [comment]
To archive the behavior of placeholder for android, i will suggest you do the following

```js
const items = [
  { label: 'School Type', value: '' },  // value here is double inverted commas, which is falsy
  { label: 'Primary and Secondary', value: 1 },
  { label: 'General Secondary', value: 2 },
]

... // Picker component children
  {items.map((option, i) => (
    <Picker.Item key={i} label={option.label} value={option.value} />
  ))}
...
```
