### ISSUE TITLE
couldn't pass style prop v3.3.1

### ISSUE THREAD

**Issue by mononoke-choi** [GeekyAnts/NativeBase#4520]
after upgrading 3.2.1 to 3.3.1 native-base don't pass style prop to specific child node
I used style prop to pass style pair which is only for web or to reduce strict mode warning

for instance, in v3.2.1 most of LAYOUT components are applied style property, but in v3.3.1 column and row didn't

Is it intended behavior.. ?!

please give me your advice. thanks!

**Screenshots**
<img width="1679" alt="image" src="https://user-images.githubusercontent.com/44839313/149300925-01bcc5da-7c87-4096-8d1a-d16baf817bbf.png">
ver 3.2.1

<img width="1679" alt="image" src="https://user-images.githubusercontent.com/44839313/149301676-92a2b43a-a011-4426-bce3-d6f3e033b61d.png">
ver 3.3.1

**Platform**

- NativeBase version 3.3.1
- Browser chrome
- yarn

**Comment by MD-REHMAN** [comment]
Can also share the code as well.

**Comment by truongtv22** [comment]
I have the same issue
Previously with the `Stack` I could add prop `style`, but after upgrading to v3.3.1, I couldn't use anymore
The problem as I know, prop `style` has been overwritten
https://github.com/GeekyAnts/NativeBase/blob/d0d1045ad0f40858c5c27a8485e33dc8d7918da9/src/components/primitives/Stack/Stack.tsx#L67

**Comment by mayank-96** [comment]
Hello @mononoke-choi @truongtv22 , Thanks for reporting the issue, it has been fixed in latest version v3.3.4.
