### ISSUE TITLE
Can't set button opacity on pressed state in Android

### ISSUE THREAD

**Issue by ezze** [GeekyAnts/NativeBase#4525]
**Describe the bug**

Button opacity on pressed state is broken after upgrading from Native Base 3.2.2 to 3.3.1

```jsx
<Button
  size="lg"
  _pressed={{ opacity: 0.8 }}
  onPress={() => {}}
>
  Test Opacity
</Button>
```

Now I get:

```
Error while updating property 'opacity' of a view managed by: RTCView
java.lang.String cannot be cast to java.lang.Double
```

**Expected behaviour**

Button opacity is changed on press.

**Actual behaviour**

App is crashed with exception.

**Screenshots**

![image](https://user-images.githubusercontent.com/665479/149407483-be62ed57-d664-4b40-998d-42022396566c.png)

**Platform**

- NativeBase version 3.3.1
- Device: Android Emulator, SDK 29
- OS: Ubuntu 20.04
- React Native version 0.64.2
- node 14.18.1
- yarn 1.22.17

**Comment by Viraj-10** [comment]
Hi ezze, Thanks for reporting the bug. I tried replicating the issue but it's working for me in version v3.3.2. Can you please check once at your side with latest version.

**Comment by surajahmed** [comment]
Closing this issue as this has already been fixed. Please feel free to reopen if the issue persists. Thanks.
