### ISSUE TITLE
expo demo is outdated

### ISSUE THREAD

**Issue by richard-li-next** [GeekyAnts/NativeBase#4527]
At present, the minimum SDK version supported by expo go is 41, but the demo uses 40.

![image](https://user-images.githubusercontent.com/65935211/149467388-6629256c-b7c9-480a-b53d-01e3d226398c.png)

**Comment by Viraj-10** [comment]
Hi @richard-li-next ,Thanks for reporting this issue. We are working on expo SDK upgradation.
