### ISSUE TITLE
Can't add testID to Select

### ISSUE THREAD

**Issue by OneHatRepo** [GeekyAnts/NativeBase#4537]
### Description

I should be able to add test props to component

### CodeSandBox/Snack link

none

### Steps to reproduce

2. Click on '...' 
3. Scroll down to '...' 

### NativeBase Version

3.3.1

### Platform

- [X] Android
- [ ] CRA
- [X] Expo
- [X] iOS
- [ ] Next

### Additional Information

I'm adding testID to iOS, and accessibilityLabel and accessible to Android. Adding these to the NB Select element does nothing.

**Comment by OneHatRepo** [comment]
Strangely enough, I can add these IDs to the Select.Item, but not the Select itself.

**Comment by mtaylor-evidation** [comment]
This appears to still be an issue.
