### ISSUE TITLE
How to put multiple buttons in header while using search bar

### ISSUE THREAD

**Issue by gameboyVito** [GeekyAnts/NativeBase#454]
Hi, I would like to put two buttons right beside the search bar in the header, but I cannot get it done. It always shows only one button on the right side of the search bar, do you have any solution offered to me? I am developing an IOS app.

react-native, react and native-base version：
{
"react-native": "0.40.0",
 "react": "15.4.2",
"native-base": "0.5.18",
}

Expected behaviour:
![image](https://cloud.githubusercontent.com/assets/16020361/22412343/73361ef8-e6e8-11e6-929d-82e902dc60ee.png)

Actual behaviour:
![image](https://cloud.githubusercontent.com/assets/16020361/22410932/553b2a1a-e6d9-11e6-8a43-60423f47dd77.png)

Steps to reproduce:
```
<Header searchBar rounded>
                    <InputGroup>
                        <Icon name="ios-search"/>
                        <Input placeholder="Search project"/>
                    </InputGroup>
                    <Button
                        transparent
                        title='1'
                        onPress={() => null}>
                        <Icon name='ios-options'/>
                    </Button>
                    <Button                      
                        transparent
                        title='2'
                        onPress={() => null}>
                        <Icon name='ios-people'/>
                    </Button>
</Header>
```

Is the bug present in both ios and android or in any one of them?
I only need to figure this out on IOS.

**Comment by gameboyVito** [comment]
Already fixed

**Comment by juanriglos** [comment]
Hello Vito, how you do to fix it?

**Comment by ongtzewei** [comment]
Replacing the use of InputGroup with Item was what worked for me.

**Comment by ongtzewei** [comment]
Replacing the use of InputGroup with Item was what worked for me.

**Comment by sseyha** [comment]
How to solve this issue???

**Comment by ongtzewei** [comment]
@sseyha  have you tried replacing all <InputGroup> tags with <Item>?

**Comment by ongtzewei** [comment]
@sseyha have you tried replacing all `<InputGroup>` tags with `<Item>`?

**Comment by sseyha** [comment]
@ongtzewei 
Yes i did. But it's look wired...

This on ios what i wish:
<img width="289" alt="screen shot 2017-10-04 at 2 58 42 pm" src="https://user-images.githubusercontent.com/7949290/31165274-a43f04c6-a914-11e7-846c-d55945b345db.png">

But Android won't display the same:
<img width="297" alt="screen shot 2017-10-04 at 2 58 49 pm" src="https://user-images.githubusercontent.com/7949290/31165288-af7c9c4a-a914-11e7-9533-a3bdfc25d512.png">

===> This is what i have replace with InputGroup
<Header searchBar rounded style={{paddingTop:0}}>
        <Button transparent iconLeft onPress={() => this.onPressFilter()}>
          <Icon name="md-calendar" />
        </Button>
        <InputGroup>
          <Icon name="ios-search" />
          <Input placeholder="Search Article" />
          <Icon name="ios-list" />
        </InputGroup>
        <Button transparent onPress={() => this.onSubmitSearch()}>
          <Text>Search</Text>
        </Button>
      </Header>

<img width="300" alt="screen shot 2017-10-04 at 3 01 08 pm" src="https://user-images.githubusercontent.com/7949290/31165335-eb127478-a914-11e7-8e73-c7095c4aed30.png">
<img width="292" alt="screen shot 2017-10-04 at 3 01 02 pm" src="https://user-images.githubusercontent.com/7949290/31165336-eb254ada-a914-11e7-9c42-2649fcfce65e.png">


==== Give me some advise please...

**Comment by sseyha** [comment]
@juanriglos Here is the example for you, if you would like.
@ongtzewei I found the solution now. Thank so much.

````
<View searchBar style={{flexDirection: 'row', padding:10}}>
        <Button transparent iconLeft style={{height:30}} onPress={() => null}>
          <Icon name="calendar"/>
        </Button>

        <InputGroup rounded style={{flex:1, backgroundColor:'#fff',height:30, paddingLeft:10, paddingRight:10}}>
          <Icon name="ios-search" />
          <Input style={{height:20}} placeholder="Search Article" />
          <Icon name="ios-list" />
        </InputGroup>

        <Button transparent style={{height:30}} onPress={() => null}>
          <Text>Search</Text>
        </Button>
      </View>

===== ios =====
![simulator screen shot - iphone 6 - 2017-10-04 at 16 34 35](https://user-images.githubusercontent.com/7949290/31169215-207530d0-a922-11e7-90a1-f21a0d12bb60.png)


===== Android =====
![screenshot_1507109678](https://user-images.githubusercontent.com/7949290/31169237-2ce1f90c-a922-11e7-8905-168db70dd788.png)

**Comment by blok-0** [comment]
@sseyha Can you help me?
When i tried your code the searchbar looks fine. But when i write something in input i can't see the text.
Only i tested in android
![errorseacrhbar](https://user-images.githubusercontent.com/16730291/40797126-b79331fe-64cc-11e8-9bca-5a84b3ff7178.gif)
