### ISSUE TITLE
Getting Uncaught Error: Cannot create styled-component for component: undefined after updating to latest native-base package.

### ISSUE THREAD

**Issue by Jayachandran369** [GeekyAnts/NativeBase#4540]
### Description

Getting Uncaught Error: Cannot create styled-component for component: undefined after updating to latest native-base package, updated package from 2.13.4 to 3.3.2

### CodeSandBox/Snack link

nil

### Steps to reproduce

2. Click on '...' 
3. Scroll down to '...' 

### NativeBase Version

3.3.2

### Platform

- [x] Android
- [ ] CRA
- [ ] Expo
- [x] iOS
- [ ] Next

**Comment by Viraj-10** [comment]
Hi @Jayachandran369, try deleting node_module folder and run yarn again. If this doesn't work please share your package.json. Also check upgrade docs [here](https://docs.nativebase.io/migration/migration-guide-three-point-two).
