### ISSUE TITLE
Pressable is not clickable 

### ISSUE THREAD

**Issue by kermit-sad-frog** [GeekyAnts/NativeBase#4542]
### Description

When clicking on the button inside Pressable, pressable event doesn't fire event handler, even button does not have an event on press

### CodeSandBox/Snack link

https://snack.expo.dev/@glabz/nativebase-template

### Steps to reproduce

```
   <Pressable onPress={() => alert('should works')}>
        <Button>try to click</Button>
      </Pressable>
```

### NativeBase Version

3.3.1

### Platform

- [X] Android
- [ ] CRA
- [ ] Expo
- [ ] iOS
- [ ] Next

**Comment by ankit-tailor** [comment]
Hi @kermit-sad-frog, Thanks for reporting the issue. We'll look into it.

**Comment by ankit-tailor** [comment]
Hi @kermit-sad-frog, react-native doesn't bubble Pressable onPress event to parent Pressable and `native-base` button component is made with Pressable. So it won't bubble event to parent pressable. you can refer to this [snack](https://snack.expo.dev/@ankit-tailor/bad-watermelon).
