### ISSUE TITLE
Element type is invalid ..

### ISSUE THREAD

**Issue by eebbann** [GeekyAnts/NativeBase#4546]
### Description

trying to create a search box after learning from a tutorial.. unfortunately keep getting errors

### CodeSandBox/Snack link

https://codesandbox.io/s/distracted-lamport-tnb8z

### Steps to reproduce

2. Click on '...' 
3. Scroll down to '...' 

### NativeBase Version

3.2.2

### Platform

- [ ] Android
- [ ] CRA
- [X] Expo
- [ ] iOS
- [ ] Next

### Additional Information

after noticing this error i checked the doc.. and searched header which is part of the native props and i noticed there isnt a page for header .

**Comment by ankit-tailor** [comment]
Hi @eebbann, There is no component called `Header` in native-base, it's `Heading`. You can read more about it [here](https://docs.nativebase.io/heading).

**Comment by eebbann** [comment]
thanks
