### ISSUE TITLE
How to render Sections in List?

### ISSUE THREAD

**Issue by adulhani-systango** [GeekyAnts/NativeBase#455]
Basically I have an array of names and I want to divide them into sections based on the first letter of name. Also, I would like to render list with sticky section headers. 

I went through the js code of list ( ****List**.js** ) and couldn't find renderSections prop in list. 
Does **List** provide renderSection method or is there any other way to implement sections?

react-native: 0.36.0,
react: 15.3.1,
native-base:0.5.13

**Comment by matthewyt** [comment]
I don't believe there is a simple way to do this. What I did was use the actual react native listview and use this for the styling. 

**First You will need to create a CategoryMap**

var CategoryMap = {};
if (!CategoryMap[divider]) {
  CategoryMap[divider] = [];
}
CategoryMap[divider].push(row);

**Then you will need to map these to the listview source** 

const ds = new ListView.DataSource({
  rowHasChanged: (r1, r2) => r1 !== r2,
  sectionHeaderHasChanged: (s1, s2) => s1 !== s2
});

**Then render the listview**

<ListView
  dataSource={ds.cloneWithRowsAndSections(CategoryMap)}
  renderRow={
    (detail) =>
            <ListItem listItem>
                  </ListItem>
    }
  renderSectionHeader={
    (sectionData, category) =>
            <ListItem itemDivider theme={baseTheme}>
                <Text</Text>
            </ListItem>
                }
/>

**Comment by adulhani-systango** [comment]
Ok. Thanks for the response. Just to make the situation more clear I am using redux too. Updating react-native ListView increases the complexity of the code while updating the dataArray of List ( native-base ) is pretty simple. Pretty much nothing to do. So, I was thinking of some implementation of sections using List of native-base. Can anyone on the native-base developers side share something that might be useful to me on this road?

**Comment by sankhadeeproy007** [comment]
List component will support all the props of ListView. So ideally renderSections should work as well. However we haven't tried that out yet and it'll be great if you let us know if that works.

**Comment by adulhani-systango** [comment]
Sure.

**Comment by neel132** [comment]
@sankhadeeproy007 Yes it works well using default ListView Props[tested].

**Comment by adulhani-systango** [comment]
@neel132 Can you please provide me a sample code?

**Comment by opaqe** [comment]
I'm also trying to render sections with <List> but I need to instantiate my own ListView.DataSource that supports section headers. I can't override the dataSource prop passed to ListView in List.js with my own. Would this be solved by spreading {...this.props} after all the other props? I feel like that should be a strict pattern for NativeBase components that wrap react-native components in case we want to override defaults.

**Comment by jasan-s** [comment]
does the sticky header work on android as well?

**Comment by jzhw0130** [comment]
Does the 'dataSource' property work with List?
For my test, is does not work on version  V2.3.3.

I have to use ListView as follows:
`
<ListView 
                    dataSource={data}
                    renderSectionHeader={(sectionData,sectionId) => this._renderSectionHeader(sectionData,sectionId)}
                    renderRow={(task,sectionID,rowID) => this._renderRow(task,sectionID,rowID)}
                    />
`
But render row and sectionHeader with ListItem.
