### ISSUE TITLE
@types should not be marked as peer dependencies

### ISSUE THREAD

**Issue by trajano** [GeekyAnts/NativeBase#4550]
### Description

the react types are in the package.json which locks us to React 16.

### CodeSandBox/Snack link

n/a

### Steps to reproduce

2. Click on '...' 
3. Scroll down to '...' 

### NativeBase Version

master

### Platform

- [ ] Android
- [ ] CRA
- [X] Expo
- [ ] iOS
- [ ] Next

**Comment by Viraj-10** [comment]
Hi @trajano, Thanks for reporting the issue. We will look into it.

**Comment by trajano** [comment]
Prior to your next release see if it can work with Expo 44.  Right now I don't think it works.

**Comment by Viraj-10** [comment]
- I have created app with expo SDK 44 and nativeBase. it's working.
- we have also changed our peerdep. of @types/react and currently we are testing it out.

**Comment by trajano** [comment]
Did you create in typescript?

**Comment by Viraj-10** [comment]
Hi @trajano, Issues with `PeerDependancies` are resolved in our latest release. Expo `SDK 44` works with `NativeBase` with `typeScript` and `npm`. If it is still not working for you please reopen the issue.
