### ISSUE TITLE
Actionsheet Header/Footer Typing Issue

### ISSUE THREAD

**Issue by y471n** [GeekyAnts/NativeBase#4557]
### Description

Actionsheet header and footer have typing issues

### CodeSandBox/Snack link

https://codesandbox.io/s/trusting-field-58ez2?file=/src/App.tsx

### Steps to reproduce

1. Goto https://codesandbox.io/s/trusting-field-58ez2?file=/src/App.tsx
2. Scroll Down to Actionsheet.Header or Actionsheet.footer component use
3. You can see the typing issue.

### NativeBase Version

3.2.2

### Platform

- [ ] Android
- [ ] CRA
- [X] Expo
- [ ] iOS
- [ ] Next

### Additional Information

The issue seems to be a Typescript issue for no definitions of the Header and Footer component for the Actionsheet component.

**Comment by mayank-96** [comment]
Hello @y471n, can you please re-check the codesandbox link, because I didn't find any `Actionsheet` component in example.

**Comment by ankit-tailor** [comment]
Hi @y471n, Thanks for reporting the issue. It's fixed and will be released in an upcoming version.
