### ISSUE TITLE
Missing 'MaterialCommunityIcons', 'EvilIcons' and 'SimpleLineIcons'

### ISSUE THREAD

**Issue by Landerson352** [GeekyAnts/NativeBase#456]
- react@15.4.2, react-native@0.40.0, native-base@0.5.22
- Expected behavior: Setting `theme.iconFamily` to 'MaterialCommunityIcons', 'EvilIcons' or 'SimpleLineIcons' should display icons in the matching set.
- Actual behavior: The default icon set (Ionicons) is used.

Thanks for taking a look at this. I know the icon sets are very commonly confused, as I've seen all the past issues reported by developers who haven't linked their resources and set their theme up properly. However, this issue is **specific to only 3 icon sets that are missing** from the import and switch statements: 'MaterialCommunityIcons', 'EvilIcons' and 'SimpleLineIcons'.

You can quickly [review the Icon code here](https://github.com/GeekyAnts/NativeBase/blob/master/Components/Widgets/Icon/index.js) and see that of the [10 icon sets](https://github.com/oblador/react-native-vector-icons#bundled-icon-sets) that should be available, only 7 are mapped:
https://github.com/GeekyAnts/NativeBase/blob/master/Components/Widgets/Icon/index.js

I can confirm that these icon font files are being linked properly, so it's simply the import and switch statements that need to be updated and everything works. Thank you!

**Comment by sankhadeeproy007** [comment]
Thanks for reporting this. We'll fix it in our next release.

**Comment by sankhadeeproy007** [comment]
Added with latest release.

**Comment by rags22489664** [comment]
I am facing this issue in v2.0
