### ISSUE TITLE
Input text decoration underline in rtl language

### ISSUE THREAD

**Issue by amirfrd** [GeekyAnts/NativeBase#4570]
### Description

don't show underline for text in Input

### CodeSandBox/Snack link

https://snack.expo.dev/@amirfrd/example

### NativeBase Version

3.2.2

### Platform

- [X] Android
- [ ] CRA
- [X] Expo
- [ ] iOS
- [ ] Next

**Comment by Viraj-10** [comment]
Hi @amirfrd, we have `_text` Pseudo prop which is used to style text inside a component currently, we have not added `_text` Pseudo prop support to the `Input` component. we will add support soon.

**Comment by amirfrd** [comment]
> Hi @amirfrd, we have `_text` Pseudo prop which is used to style text inside a component currently, we have not added `_text` Pseudo prop support to the `Input` component. we will add support soon. 
> Meanwhile you can add underline using style prop `style={{textDecoration:'underline'}}`

Input has underline by default in just rtl language 
But don't have in ltr

**Comment by mayank-96** [comment]
Hello @amirfrd, It is working fine in my case. Here is the [snack link](https://snack.expo.dev/@mayankp09/calm-coffee), do check it once.

**Comment by amirfrd** [comment]
@mayank-96
did you test in android?
this error exist in android

**Comment by mayank-96** [comment]
Hello @amirfrd, I guess the text typing underline which you are referring is default behaviour in android due to spell check. Check out the following [article](https://legendupdate.com/remove-the-underline-feature-on-an-android/).
