### ISSUE TITLE
Slider nib is offset when inside ListItem.

### ISSUE THREAD

**Issue by Slooowpoke** [GeekyAnts/NativeBase#458]
React-Native 0.40, React 15.4.2, Native-Base 0.5.22

## Expected behaviour
Slider should appear as it does inside a normal view when inside a list.

## Actual behaviour
Slider nib (the blue bit) appears offset when inside a list element.

## Steps to reproduce (code snippet or screenshot)
Place the slider inside a 
`<List>
<ListItem>
<Slider />
</ListItem>
</List>
`

![image](https://cloud.githubusercontent.com/assets/1674449/22546101/846008fe-e933-11e6-83a7-f89589467404.png)

## Is the bug present in both ios and android or in any one of them?
Only Android

## Any other additional info which would help us debug the issue quicker.
It's not a super pressing issue, you can get around it by taking it out of the list and applying a similar padding and using flex inside its own View. Not sure if because of that it needs fixing, but hopefully if someone else encounters it they can get around it with this.

**Comment by shivrajkumar** [comment]
v2.x solves this.
