### ISSUE TITLE
Modal vertically centers around page content, not viewport on web

### ISSUE THREAD

**Issue by IHIutch** [GeekyAnts/NativeBase#4581]
### Description

When using the modal on a page that requires scrolling, the modal tries to wrap itself around the page content, rather than the viewport itself. I seems like this may only be an issue on web

### CodeSandBox/Snack link

https://snack.expo.dev/@ihiutch/71788a

### Steps to reproduce

1. Create a page that requires to scroll
2. Include a modal component

### NativeBase Version

3.2.3

### Platform

- [ ] Android
- [ ] CRA
- [X] Expo
- [ ] iOS
- [X] Next

### Other Platform

Web

### Additional Information

Normally, I'd just add "`position:fixed, overflow: auto, height: "100%", width: "100%"` to my root elements, but using react-navigation makes this a little more complicated since it adds its own elements between the root and my pages.

My current solution is effectively a "reset" layout (`position: fixed, height: '100%', width: '100%'`) that I apply to every screen where I use a modal.

**Comment by Viraj-10** [comment]
Hi @IHIutch, Thanks for reporting this issue. We will look into it.

**Comment by IHIutch** [comment]
Bumping this as I don't think it should auto close

**Comment by ricohumme** [comment]
I have this issue as well with native-base@3.3.12

**Comment by surajahmed** [comment]
This is an issue with the Overlay component. We're still working on it. Hope to fix this in the coming release. Thanks for your patience.

**Comment by biskis** [comment]
@surajahmed Do we know when next release will be? I kind of need to go to production with a expo web app that has this problem and is kind of big. I can wait max a week, if not I will need to implement other library for the modals. I need an estimation to know how to plan my work for next week. Thanks.

**Comment by biskis** [comment]
I installed the new 3.4.6 version and the bug is still here.

**Comment by ricohumme** [comment]
Currently on 3.4.9 and issue is sadly not yet resolved

**Comment by olivermillard** [comment]
Still having this issue as well, hope it will be resolved soon

**Comment by joseito-terence** [comment]
```
<Modal 
      isOpen={isOpen}
      onClose={onClose}
      height='100vh' 
 >
```
Setting height to 100vh worked for me

**Comment by Viraj-10** [comment]
Hi @joseito-terence, @ricohumme, @biskis, @ricohumme, @IHIutch, Sorry for the delay.  We have exposed `Overlay` to the modal Component. 
to fix this issue you can write the following code using `_overlay`. 
`
 <Modal isOpen={showModal} onClose={() => setShowModal(false)} _overlay={{style:{position:'fixed'}}}>`
 
 feel free to open this issue if it still persists.

**Comment by ricohumme** [comment]
Hi, thanks for the update. Could this also be released in the 3.3 branch? 
3.4.x has (I believe to be) some unresolved issues making it hard for me to upgrade to that.

**Comment by Viraj-10** [comment]
Hi @ricohumme, Can you elaborate on the issues you are facing? we are happy to help you migrate from `v3.3` to `v3.4`.

**Comment by ricohumme** [comment]
Hi @Viraj-10 My issue lies with https://github.com/GeekyAnts/NativeBase/issues/4931
As I am not the only one mentioning this, I think something is off.
This is currently preventing me from upgrading

**Comment by Viraj-10** [comment]
@ricohumme, We are currently working on this issue and it will be resolved and released by end of this week.

**Comment by ricohumme** [comment]
Hi @Viraj-10, just coming around to this and fixed does infact keep the modal centered in the viewport whilst scrolling is still possible in the background.
It does however raise an issue with typescript is `fixed` is not one of the possible options within the definition FlexStyle:

![Scherm­afbeelding 2023-03-17 om 11 16 03](https://user-images.githubusercontent.com/11029998/225876908-95a2abec-9e36-4db6-943c-11cbc70e0182.png)

**Comment by litotechenterprise** [comment]
I'm running into this issue as well. Currently I'm using  native base version 3.4.28

**Comment by litotechenterprise** [comment]
Just as an update I found a quick work around, When opening the modal I forced the window to scroll all the way to the top of the page so the modal is centered on the screen:
`  const toggleModal = () => {
    window.scrollTo(0, 0);
    setShow((prev) => !prev);
  };`

as well as stopping scrolling from happening while the modal is open:
`show ? (document.body.style.overflow = 'hidden')
    : (document.body.style.overflow = 'auto');`
