### ISSUE TITLE
To-Do Sample is Broken

### ISSUE THREAD

**Issue by rlingineni** [GeekyAnts/NativeBase#4587]
### Description

To-Do Sample broken, checkboxes resetting

### CodeSandBox/Snack link

https://docs.nativebase.io/todo-list

### Steps to reproduce

1. Go to [Docs Site](https://docs.nativebase.io/todo-list) 
2. Click the to-do list, and check a few things
3. Clicking one checkbox will uncheck others

### NativeBase Version

3.3.1

### Platform

- [ ] Android
- [ ] CRA
- [X] Expo
- [X] iOS
- [ ] Next

### Other Platform

Web

### Additional Information

After some investigation, I found that in the `handleStatusChange` function, the `list` state variable is getting reset to the initial state.

It seems that the `onChange` handler for the checkbox isn't somehow getting binded to latest version of the `list` state. I tested this by adding a Button and the `onPress` handler, and the behavior worked as expected.

```jsx
 <HStack
  w="100%"
   justifyContent="space-between"
   alignItems="center"
   key={itemI}
 >
                <Button
                  onPress={() => {
                  // calling this in the OnPress Handler works as expected, but seems like onChange handler in the Checkbox doesn't work
                  handleStatusChange(itemI)
                  }
                  bg={"white"}
                  color={item.isCompleted ? "black" : "red"}
                >
                  {item.title}
                </Button>
                <Checkbox
                  isChecked={item.isCompleted}
                  onChange={(isChecked) => handleStatusChange(itemI)}
                  value={item.title}
                ></Checkbox>
</HStack>
```

Can you please confirm the Checkbox handler is working as expected?

**Comment by surajahmed** [comment]
@rlingineni Thanks for reporting! The To-Do sample is fixed in version `3.3.5`.
