### ISSUE TITLE
Input not respecting border colour without input element

### ISSUE THREAD

**Issue by Xmaxer** [GeekyAnts/NativeBase#4590]
### Description

I expect the border colour to always be respected

### CodeSandBox/Snack link

https://snack.expo.dev/ntznCRhvs

### Steps to reproduce

I created two input fields in the above expo project. You'll notice the first input without the right/left element doesn't respect the border colour on error when focused. But the one with the right element does.

Perhaps I am doing something wrong. Do let me know, thanks.

### NativeBase Version

3.3.4

### Platform

- [X] Android
- [ ] CRA
- [ ] Expo
- [ ] iOS
- [ ] Next

**Comment by ankit-tailor** [comment]
Hi @Xmaxer, Thanks for reporting the issue. We'll fix it.

**Comment by ankit-tailor** [comment]
Hi @Xmaxer, This issue is fixed and will be released in next version.

**Comment by surajahmed** [comment]
This issue has been fixed in version `3.3.6`. Thanks.
