### ISSUE TITLE
Utility Props docs page is crashing Chrome

### ISSUE THREAD

**Issue by hollinwakefield** [GeekyAnts/NativeBase#4593]
### Description

I can't load the utility props docs without my Chrome crashing

### CodeSandBox/Snack link

https://docs.nativebase.io/3.0.x/utility-props

### Steps to reproduce

1. Go to [the docs for Utility Props](https://docs.nativebase.io/3.0.x/utility-props)
2. Wait for my browser to crash

### NativeBase Version

3.3.1

### Platform

- [ ] Android
- [ ] CRA
- [ ] Expo
- [ ] iOS
- [ ] Next

### Other Platform

MacBook Pro, 2.3 GHz 8-Core Intel Core i9, 32 GB 2667 MHz DDR4

### Additional Information

It's also crashing on my iPhone X in Safari

**Comment by mayank-96** [comment]
Hi @hollinwakefield, Thanks for reporting the issue. We'll fix it.

**Comment by amars29** [comment]
Hey @hollinwakefield, Issue has been fixed now.

**Comment by hollinwakefield** [comment]
Thank you!
