### ISSUE TITLE
Toast is too expensive and slow

### ISSUE THREAD

**Issue by waheedakhtar694** [GeekyAnts/NativeBase#4599]
### Description

I am using toast in different areas of my app but when showing toast it completely halts the JS thread and JS thread came into minus while showing toast.

### CodeSandbox/Snack link

https://snack.expo.dev/40ddUYAHP

### Steps to reproduce

1. Open Pref monitor in the app
2. display some toast. 

### NativeBase Version

3.2.1

### Platform

- [X] Android
- [ ] CRA
- [ ] Expo
- [ ] iOS
- [ ] Next

### Other Platform

Tested only with android.

### Additional Information

You can see JS thread goes into minus while showing toast.
![ezgif com-gif-maker](https://user-images.githubusercontent.com/45425486/152134086-35770e3e-459e-47d2-8f85-c3ef668a7551.gif)

**Comment by ChrisWiles** [comment]
same issue, with my app. Works fine on v2. I think the animations are the issue. Any way to disable them?

**Comment by Viraj-10** [comment]
Hi @ChrisWiles @waheedakhtar694, Thanks for reporting the issue. we will have a look.
If you have any more information on the issue please add a comment.
PS:- Hi @ChrisWiles, currently users don't have control over the animation but in the future, we will try to provide a way to disable them if the user wants it.

**Comment by burzacoding** [comment]
It's happening to me as well, if you try to render a toast on a useEffect it will lag the app a lot

**Comment by Viraj-10** [comment]
Hi @burzacoding, We have rewritten `Toast` in the latest version of native-base `V3.4`. let us know if you still face this issue please add the following details. 

- Node Version.
- environment used to build an app ( Expo/ RCL/CRA).
- Platform (Android/IOS/Web).
- small snack example of your code.

PS:- We have deprecated some of the features of Toast in V3.4 and added them into Recipe.

**Comment by surajahmed** [comment]
Closing this issue as this has been resolved in version `3.4.9` or later. Please feel free to reopen if this issue persists. Thanks.
