### ISSUE TITLE
List in initially hidden Tabitem is only rendered after scroll interaction 

### ISSUE THREAD

**Issue by br4nnigan** [GeekyAnts/NativeBase#460]
native base 0.5.22
react native 0.39.2

    render () {
        return (
            <Container>
                <Content>
                    <Tabs>
                        <Text tabLabel="one" style={{flex: 1}}>asd</Text>
                        <List tabLabel="two"
                            dataArray={[1,2,3,4,5,7,8,9,12,12,3,34,32,32,32,25,1,2,3,4,5,7,8,9,12,12,3,34,32,32,32,25]}
                            renderRow={this.renderRow}
                        />
                    </Tabs>

                </Content>
            </Container>
        );
    }
    renderRow (data) {
        return (<ListItem><Text>data: {data}</Text></ListItem>);
    }

**Comment by br4nnigan** [comment]
same with react-native ListView

**Comment by br4nnigan** [comment]
is there a workaround?

**Comment by SupriyaKalghatgi** [comment]
@br4nnigan Haven't checked NativeBase 2.x?

**Comment by br4nnigan** [comment]
No, project is inactive...

**Comment by ivankukobko** [comment]
Bug occurs with the latest `nativebase`, when using `TabNavigator ` from `react-navigation`
