### ISSUE TITLE
extendTheme for dark mode Text color not working

### ISSUE THREAD

**Issue by Gabsys** [GeekyAnts/NativeBase#4603]
### Description

using extendTheme to cater for dark mode Text color doesn't work. 

### CodeSandbox/Snack link

N/A. Need to use real device / simulator to toogle the dark mode

### Steps to reproduce

1. extendTheme on App.js and include it in `<NativeBaseProvider>`. Example code as below:
```
const theme = extendTheme({
  components: {
    Text: {
      baseStyle: props => {
        return {
          color: themeTools.mode('black', 'white')(props),
        }
      },
    },
  },
})

return (
 <NativeBaseProvider theme={theme}>
     <ApplicationNavigator />
 </NativeBaseProvider>
 )
```
2. Put `Text` component in any screen
3. Try to switch between dark & light mode on your device
4. You will see the Text color always remain at themeTools.mode's first argument's color (In this example, it is black)

### NativeBase Version

3.2.1

### Platform

- [X] Android
- [ ] CRA
- [ ] Expo
- [X] iOS
- [ ] Next

**Comment by mayank-96** [comment]
Hello @Gabsys, I tried reproducing your issue but it is working fine in my case. You can check the [snack](https://snack.expo.dev/@mayankp09/16ecb4) link.

**Comment by Gabsys** [comment]
> Hello @Gabsys, I tried reproducing your issue but it is working fine in my case. You can check the [snack](https://snack.expo.dev/@mayankp09/16ecb4) link.

Hi, I tried using `toggleColorMode`, it does work fine. But using Dark Mode from phone settings itself doesn't have the same effect

**Comment by Gabsys** [comment]
It worked after I added:
```
config: {
    useSystemColorMode: true
}
```
to `extendTheme`
