### ISSUE TITLE
Error is thrown when using a list map to render Select.Item for Select component, if the list is undefined

### ISSUE THREAD

**Issue by himgodfreyho** [GeekyAnts/NativeBase#4604]
### Description

If I have a react state list, and the initial value of the list is undefined, if I use this list to render the Select.Item for the Select component, it will throw an error when the page is rendered.

### CodeSandbox/Snack link

https://codesandbox.io/s/objective-bush-uk769?file=/src/App.tsx

### NativeBase Version

3.3.4

### Platform

- [ ] Android
- [ ] CRA
- [ ] Expo
- [ ] iOS
- [ ] Next

### Additional Information

<img width="487" alt="image" src="https://user-images.githubusercontent.com/10152000/152325283-a1a14e42-84b0-4067-bd84-adcff559fbca.png">
<img width="1048" alt="Screenshot 2022-02-03 at 18 29 10" src="https://user-images.githubusercontent.com/10152000/152325533-7d4ccdde-9a6c-4e38-9fb6-6110bcc2829b.png">

For the same situation, some other libraries, such as MUI, won't raise an error.

<img width="524" alt="image" src="https://user-images.githubusercontent.com/10152000/152325156-b7d0a052-72f9-4727-b254-da8208e69825.png">

**Comment by mayank-96** [comment]
Hi @himgodfreyho, Thanks for reporting the issue. We'll fix it.

**Comment by surajahmed** [comment]
This issue has been fixed in version [3.3.6](https://github.com/GeekyAnts/NativeBase/releases/tag/v3.3.6).
