### ISSUE TITLE
SectionList not properly typed

### ISSUE THREAD

**Issue by codakkk** [GeekyAnts/NativeBase#4606]
### Description

SectionList's props does not infer the type from the data prop. Similar to #4469 but for SectionList.

### CodeSandbox/Snack link

/

### NativeBase Version

3.3.4

### Platform

- [X] Android
- [ ] CRA
- [ ] Expo
- [X] iOS
- [ ] Next

**Comment by surajahmed** [comment]
@codakkk Thanks for reporting! We're looking into this.

**Comment by surajahmed** [comment]
This issue has been fixed in version [3.3.6](https://github.com/GeekyAnts/NativeBase/releases/tag/v3.3.6).
