### ISSUE TITLE
Header customization

### ISSUE THREAD

**Issue by justfede** [GeekyAnts/NativeBase#461]
Hey guys! I want to customize my app but I can't find how to remove shadows from native-base elements. Por example, I want something like this:

<img width="295" alt="cap1" src="https://cloud.githubusercontent.com/assets/400900/22553418/60af228e-e93b-11e6-8c6c-16b4d4507ea2.png"> 
(this is from native base docs)

But on Android i got this:

<img width="428" alt="screen1" src="https://cloud.githubusercontent.com/assets/400900/22553435/71b8ab5e-e93b-11e6-9987-bb6973f00480.png">

I want to remove the shadow or border between header and tabs. Anybody knows how can i do it?

Thanks so much!

**Comment by justfede** [comment]
Solved with: style={{elevation:0}}

Sorry guys!

**Comment by HyperSimon** [comment]
```javascript
        <Header
          noShadow={true}
          transparent
          style={{ ...styles.header }}
        >
```
noShadow={true} should work too;

**Comment by usmansbk** [comment]
I'm unable to add elevation to native base Header component... `<Header style={{elevation: 8}}>` does not work! Any workaround please or is it a bug?

**Comment by kkrishnan90** [comment]
Doesn't work for me either ! Any fixes please ?

**Comment by CeamKrier** [comment]
In case your header has generated from the title of your **Scene** from the 'react-native-router-flux'

![image](https://user-images.githubusercontent.com/18554425/60610332-4c452580-9dcc-11e9-87f7-d6cff95083c1.png)
