### ISSUE TITLE
Require cycle native-base 3.3.5 

### ISSUE THREAD

**Issue by rodrigodiasf1984** [GeekyAnts/NativeBase#4618]
### Description

I've this require cycle warning 

### CodeSandbox/Snack link

its a privated project can link on web sorry

### Steps to reproduce

1. Just installed the lib and yarn pod install 
2. yarn ios 
3. yarn android 
4. get this warning on metro bundler
5. Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
 WARN  Require cycle: node_modules/native-base/src/components/primitives/index.ts -> node_modules/native-base/src/components/primitives/Checkbox/index.tsx -> node_modules/native-base/src/components/primitives/Checkbox/Checkbox.tsx -> node_modules/native-base/src/components/primitives/Checkbox/SizedIcon.tsx -> node_modules/native-base/src/components/primitives/index.ts

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
 WARN  Require cycle: node_modules/native-base/src/components/primitives/index.ts -> node_modules/native-base/src/components/primitives/Select/index.tsx -> node_modules/native-base/src/components/primitives/Select/SelectItem.tsx -> node_modules/native-base/src/components/composites/Actionsheet/index.tsx -> node_modules/native-base/src/components/composites/Actionsheet/Actionsheet.tsx -> node_modules/native-base/src/components/composites/Modal/index.tsx -> node_modules/native-base/src/components/composites/Modal/Modal.tsx -> node_modules/native-base/src/components/composites/Transitions/index.tsx -> node_modules/native-base/src/components/composites/Transitions/Slide.tsx -> node_modules/native-base/src/components/primitives/index.ts

### NativeBase Version

3.3.5

### Platform

- [X] Android
- [ ] CRA
- [ ] Expo
- [X] iOS
- [ ] Next

### Other Platform

"react-native": "0.67.2"

**Comment by waheedakhtar694** [comment]
Same here.

**Comment by surajahmed** [comment]
Thanks for reporting! This issue has been fixed in version [3.3.6](https://github.com/GeekyAnts/NativeBase/releases/tag/v3.3.6).
