### ISSUE TITLE
Web - Input in overlay components (alertdialog, modal)

### ISSUE THREAD

**Issue by exneval** [GeekyAnts/NativeBase#4643]
### Description

Can't lose focus by clicking outside input field

### CodeSandbox/Snack link

https://snack.expo.dev/@exneval/nativebase-x-input-x-overlay

### Steps to reproduce

1. Try to lose focus of input inside an overlay component

### NativeBase Version

3.3.6

### Platform

- [ ] Android
- [X] CRA
- [ ] Expo
- [ ] iOS
- [X] Next

### Other Platform

Web

**Comment by mayank-96** [comment]
Hello @exneval, Thanks for reporting the issue, we'll look into this.

**Comment by Youngtao1999** [comment]
Any updates here? @mayank-96

**Comment by surajahmed** [comment]
We're still working on it. Hope to fix this in the coming release. Thanks for your patience.

**Comment by Viraj-10** [comment]
Hi @exneval, This issue is fixed in the latest version of `native-base`.
