### ISSUE TITLE
Popover causes not trigger click on buttons

### ISSUE THREAD

**Issue by geoapostolidis** [GeekyAnts/NativeBase#4646]
### Description

when you have a popover and buttons in same page the buttons not clicked

### CodeSandbox/Snack link

cannot create sandbox for 3.3.6, needs react-native-svg

### Steps to reproduce

1. Add a popver
2. Add a button under the popover
3. click the button (nothing is clicked)

### NativeBase Version

3.3.6

### Platform

- [X] Android
- [ ] CRA
- [ ] Expo
- [ ] iOS
- [ ] Next

**Comment by s0rta** [comment]
You can hotfix this by setting useRNModalOnAndroid to false inside popover.tsx, I've submitted a PR that should fix this but it hasn't been merged. #4656

**Comment by surajahmed** [comment]
@geoapostolidis Thanks for reporting! We'll look into this.
@s0rta Thanks for working on this.

**Comment by ankit-tailor** [comment]
Hi @ThelmaAndrews, Which version of NativeBase are you using?

**Comment by ankit-tailor** [comment]
Hi @geoapostolidis, This issue is fixed in version `3.4.3`. let us know if it works for you.
