### ISSUE TITLE
Stack flattening is leading to these errors: Encountered two children with the same key, `.$.$.1`.

### ISSUE THREAD

**Issue by shobhitsinghal624** [GeekyAnts/NativeBase#4653]
### Description

Somehow stack flattening leads to same key in multiple children.

### CodeSandbox/Snack link

https://snack.expo.dev/Vs1NtJ-u6

### Steps to reproduce

2. Click on '...' 
3. Scroll down to '...' 

### NativeBase Version

3.3.6 onwards

### Platform

- [X] Android
- [ ] CRA
- [ ] Expo
- [X] iOS
- [ ] Next

### Additional Information

This PR seems to be the main reason the issue started: https://github.com/GeekyAnts/NativeBase/pull/4611

**Comment by shobhitsinghal624** [comment]
Hi @ankit-tailor, I created a PR ( #4776 ) that fixes this issue. Let me know if it needs any changes.

**Comment by ankit-tailor** [comment]
Hey @shobhitsinghal624, Thanks for working on the issue, I'll look into your PR.

**Comment by exneval** [comment]
@ankit-tailor any news? almost a month already, even if there's already a PR

**Comment by shobhitsinghal624** [comment]
Hi @ankit-tailor, were you able to check this out?

**Comment by g-nogueira** [comment]
I'm also waiting for this fix :/

**Comment by exneval** [comment]
does v3.4.8 solved this issue @Viraj-10 ?

**Comment by Viraj-10** [comment]
Hi, This issue has been fixed in `v3.4.8`
