### ISSUE TITLE
withDefaultColorScheme so you can declare the color once and not pass it as a prop everywhere in the app

### ISSUE THREAD

**Issue by haibert** [GeekyAnts/NativeBase#4658]
### Description

So we can apply a default color scheme to all components, instead of setting them each time we use a component

### Problem Statement

It will save a lot of time knowing that once you choose lets say "orange" as the color scheme, anywhere in the app you drop a button it will be orange, unless you change props..

### Proposed Solution or API
``` javascript
import { extendTheme, withDefaultColorScheme } from 'native-base'

const customTheme = extendTheme(
  withDefaultColorScheme({
    colorScheme: 'red',
    components: ['Button', 'Badge'],
  }),
  withDefaultColorScheme({
    colorScheme: 'blue',
    components: ['Alert', 'Table'],
  }),
)
```

**Comment by surajahmed** [comment]
@haibert Thanks for the suggestion. We've added it to our list.
