### ISSUE TITLE
wrong position of menu component in RTL layout of react-native inside of HStack

### ISSUE THREAD

**Issue by creativitycomkw** [GeekyAnts/NativeBase#4666]
### Description

wrong position of menu component in RTL layout of react-native inside of HStack

### CodeSandbox/Snack link

https://snack.expo.dev/W4HiE_uld

### Steps to reproduce

1. use RTL Layout in react-native 
2. put 3 elements in the HStack component
3. use menu component at 3rd component
4. then see menu position, it will show on the wrong position

<img src="https://user-images.githubusercontent.com/66077942/155108916-d889835e-5d0a-443e-8b02-6239a53a1b95.png" alt="alt text" width="300" height="auto">

<img src="https://user-images.githubusercontent.com/66077942/155108937-6b45d351-6a5a-4ae1-8fa8-585eb4cc7c8f.png" alt="alt text" width="300" height="auto">

### NativeBase Version

3.3.7

### Platform

- [X] Android
- [ ] CRA
- [ ] Expo
- [X] iOS
- [ ] Next

**Comment by mayank-96** [comment]
Hello @creativitycomkw, Thanks for reporting this issue, we will look into this.

**Comment by zolon4** [comment]
> Hello @creativitycomkw, Thanks for reporting this issue, we will look into this.

Any updates here?

**Comment by surajahmed** [comment]
This issue has been fixed in verison `3.3.11`. Thanks for reporting!

**Comment by creativitycomkw** [comment]
hi,

i have checked the issue in version 3.3.11 and it still there
plz check once again in react-native RTL layout

**Comment by meypod** [comment]
@surajahmed still happening
