### ISSUE TITLE
Checkbox hover animation scales disproportionately in the Y axis if children span multiple lines

### ISSUE THREAD

**Issue by Southclaws** [GeekyAnts/NativeBase#4670]
### Description

If the children nodes inside a checkbox result in multiple lines being spanned, the animation 

### CodeSandbox/Snack link

https://codesandbox.io/s/icy-sun-llo4x0?file=/src/App.tsx

### Steps to reproduce

```tsx
<Checkbox>
  <Text>lots of text that spans 2 or 3 lines</Text>
</Checkbox>
```

Hover mouse over checkbox:

One line of text, normal:
![image](https://user-images.githubusercontent.com/1636971/155358376-ce04ee10-55ee-425b-97aa-03557a3d8587.png)

Three lines, scales out of bounding box:
![image](https://user-images.githubusercontent.com/1636971/155358421-ba17b383-e879-41d7-add6-fadb9bf8c587.png)

### NativeBase Version

3.3.7

### Platform

- [ ] Android
- [ ] CRA
- [ ] Expo
- [ ] iOS
- [X] Next

### Additional Information

Disabling the animation would be a quick fix - is this possible?

**Comment by Southclaws** [comment]
Temporary fix:

```tsx
        <Checkbox
          _hover={
            {
              _interactionBox: {
                bg: "none",
              },
            } as any // necessary as types are broken somehow
          }
        >
          <Text marginX={3}>{children}</Text>
        </Checkbox>
```

**Comment by mayank-96** [comment]
Hello @Southclaws, Thanks for reporting this issue, we'll look into this.

**Comment by mayank-96** [comment]
Hello @Southclaws, This issue has been fixed, and will be released in next version.
