### ISSUE TITLE
Stable hash broken in 3.3.x 

### ISSUE THREAD

**Issue by sergioisidoro** [GeekyAnts/NativeBase#4671]
### Description

While installing native base on a clean expo project, got an error : 

```iOS Bundling failed 964ms
While trying to resolve module `stable-hash` from file `/node_modules/native-base/lib/module/hooks/useStyledSystemPropsResolver.js`, the package `.../node_modules/stable-hash/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved about
```

### CodeSandbox/Snack link

Fresh install

### Steps to reproduce

1. Create a new expo project
2. Install native base following instructions (built on a mac M1)
3. Run on iOS

**Note:, web builds ok**

### NativeBase Version

3.3.x (3.3.7)

### Platform

- [ ] Android
- [ ] CRA
- [ ] Expo
- [X] iOS
- [ ] Next

### Additional Information

If native base reverted to 3.2.x problem is fixed
Possibly related to this commit:
https://github.com/GeekyAnts/NativeBase/commit/9f4d744708397b3e524bb8e26e48aea92c7f2a3a

stable hash is a relatively new library: https://github.com/shuding/stable-hash
So it might be that the author swapped the package without a release?

**Comment by midoalone** [comment]
check this [comment](https://github.com/GeekyAnts/NativeBase/issues/4678#issuecomment-1066434275)
