### ISSUE TITLE
Flex "direction" props crash on bare react native

### ISSUE THREAD

**Issue by TVGSoft** [GeekyAnts/NativeBase#4672]
### Description

Flex "direction" props crash on bare react native

### CodeSandbox/Snack link

https://snack.expo.dev/@giaptran/nativebase-template

### Steps to reproduce

 <Flex direction="row" />

### NativeBase Version

3.3.7

### Platform

- [X] Android
- [ ] CRA
- [ ] Expo
- [X] iOS
- [ ] Next

**Comment by ankit-tailor** [comment]
Hi @TVGSoft, Thanks for reporting the issue. We'll fix it soon.

**Comment by ankit-tailor** [comment]
Hi @TVGSoft, You can use `flexDirection="row"` as well. Let us know if it works.

**Comment by youniaogu** [comment]
> Hi @TVGSoft, You can use `flexDirection="row"` as well. Let us know if it works.

same issues，it worked for me

**Comment by ankit-tailor** [comment]
Hi @TVGSoft @youniaogu, Closing this issue for now as `flexDirection` can be used instead of `direction`.
