### ISSUE TITLE
Menu Overlay "left" position not working correctly

### ISSUE THREAD

**Issue by TVGSoft** [GeekyAnts/NativeBase#4677]
### Description

Menu Overlay "left" position not working correctly

### CodeSandbox/Snack link

https://snack.expo.dev/@giaptran/nativebase-menu-overlay-bug

### Steps to reproduce

This bug doesn't happen on version 3.3.4 and below, but happens on version 3.3.5 and above.
![Screen Shot 2022-02-26 at 23 11 47](https://user-images.githubusercontent.com/20625911/155850414-a826ea60-6778-47a7-919a-48f775f2e837.png)

Expected: The Menu "left" position will be aligned with Input.
Actual: The Menu "left" position was moved at the center of Input.

### NativeBase Version

3.3.7

### Platform

- [ ] Android
- [ ] CRA
- [X] Expo
- [ ] iOS
- [ ] Next

**Comment by grumpyshiba** [comment]
Same for me

**Comment by Snotax** [comment]
I think I have the same problem. Placement only displayes correctly when I HotRefresh anything in the debugger but not initially.

**Comment by zolon4** [comment]
Same here

**Comment by mayank-96** [comment]
Hello @TVGSoft, Thanks for reporting this issue, We'll fix it soon.

**Comment by surajahmed** [comment]
This issue is fixed in version `3.3.11`. Thanks for reporting
