### ISSUE TITLE
stable hash package issue

### ISSUE THREAD

**Issue by yogesh-jgu** [GeekyAnts/NativeBase#4678]
### Description

Error: While trying to resolve module `stable-hash` from file `./node_modules/native-base/lib/module/hooks/useStyledSystemPropsResolver.js`, the package `./node_modules/stable-hash/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`./node_modules/stable-hash/dist/index.mjs`. Indeed, none of these files exist:

### CodeSandbox/Snack link

https://codesandbox.io/dashboard/home?workspace=db8bc0d5-e9ec-4173-90a7-984c82f6ab1d

### Steps to reproduce

1.  yarn add native-base styled-components styled-system 
2. Just adding the package, I am facing the issue

### NativeBase Version

3.3.7

### Platform

- [ ] Android
- [ ] CRA
- [ ] Expo
- [X] iOS
- [ ] Next

### Additional Information

![Simulator Screen Shot - iPhone 13 - 2022-02-27 at 17 11 25](https://user-images.githubusercontent.com/80828217/155881105-536ea427-59e8-44ae-8731-61210be6eca8.png)

**Comment by Viraj-10** [comment]
Hi @yogesh-jgu, Can you provide some more environment details.

1. Node Version.
2. codeSandBox link. (the provided codeSandBox link is broken).
3. workspace in which you are adding NativeBase (Expo,react-cli,etc).
4. `package.json`

**Comment by yogesh-jgu** [comment]
> Hi @yogesh-jgu, Can you provide some more environment details.
> 
> 1. Node Version.
> 2. codeSandBox link. (the provided codeSandBox link is broken).
> 3. workspace in which you are adding NativeBase (Expo,react-cli,etc).
> 4. `package.json`

[package-json.txt](https://github.com/GeekyAnts/NativeBase/files/8162723/package-json.txt)

Node : v17.5.0
Workspace: ignite-cli

**Comment by yogesh-jgu** [comment]
Any Update team on #4678?

**Comment by midoalone** [comment]
This issue because of react metro can't recognize the .mjs file, so a proper fix for this issue is to add .mjs files support to the metro.config.js 

```
sourceExts: [
        ...defaultConfig.resolver.sourceExts,
        "mjs",
],
```

For me, this is the complete metro.config.js content

```
const { makeMetroConfig } = require("@rnx-kit/metro-config")
const MetroSymlinksResolver = require("@rnx-kit/metro-resolver-symlinks")
const { getDefaultConfig } = require("metro-config")

module.exports = (async () => {
  const defaultConfig = await getDefaultConfig()
  return makeMetroConfig({
    projectRoot: __dirname,
    resolver: {
      resolveRequest: MetroSymlinksResolver(),
      assetExts: [...defaultConfig.resolver.assetExts, "bin"],
      sourceExts: [
        ...defaultConfig.resolver.sourceExts,
        "mjs",
      ],
    },
  })
})()
```

**Comment by ankit-tailor** [comment]
Hi Everyone, Thanks for your patience. This issue is fixed in latest version `3.4.11`. Closing the issue for now, feel free to re-open it if you have any doubt.

**Comment by jansenfelipe** [comment]
Same here 

```
› Using Expo Go
› Press s │ switch to development build

› Press a │ open Android
› Press w │ open web

› Press j │ open debugger
› Press r │ reload app
› Press m │ toggle menu
› Press o │ open project code in your editor

› Press ? │ show all commands

Logs for your project will appear below. Press Ctrl+C to exit.
Web Bundling failed 5089ms
Unable to resolve "stable-hash" from "node_modules\native-base\lib\module\hooks\useStyledSystemPropsResolver.js"
› Stopped server
```

**Comment by razorback21** [comment]
same issue here. I just upgraded expo 48 to 49. Expo 48 its working without issues.

`› Using Expo Go
› Press s │ switch to development build

› Press a │ open Android
› Press w │ open web

› Press j │ open debugger
› Press r │ reload app
› Press m │ toggle menu
› Press o │ open project code in your editor

› Press ? │ show all commands

Logs for your project will appear below. Press Ctrl+C to exit.
› Open in the web browser...
› Press ? │ show all commands
Web Bundling failed 13433ms
Unable to resolve "stable-hash" from "node_modules\native-base\lib\module\hooks\useStyledSystemPropsResolver.js"
`

**Comment by likeSo** [comment]
Same problem here
```
› Using Expo Go
› Press s │ switch to development build

› Press a │ open Android
› Press i │ open iOS simulator
› Press w │ open web

› Press j │ open debugger
› Press r │ reload app
› Press m │ toggle menu
› Press o │ open project code in your editor

› Press ? │ show all commands

Logs for your project will appear below. Press Ctrl+C to exit.
› Open in the web browser...
› Press ? │ show all commands
Web Bundling failed 25151ms
Unable to resolve "stable-hash" from "node_modules/native-base/lib/module/hooks/useStyledSystemPropsResolver.js"
Web Bundling failed 758ms
```

**Comment by likeSo** [comment]
New error now 
```
› Using Expo Go
› Press s │ switch to development build

› Press a │ open Android
› Press i │ open iOS simulator
› Press w │ open web

› Press j │ open debugger
› Press r │ reload app
› Press m │ toggle menu
› Press o │ open project code in your editor

› Press ? │ show all commands

Logs for your project will appear below. Press Ctrl+C to exit.
Web Bundling failed 20535ms
Unable to resolve "stable-hash" from "node_modules/native-base/lib/module/utils/useResponsiveQuery/useResponsiveQuery.web.js"
```

**Comment by jamielife** [comment]
Also getting: `Unable to resolve "stable-hash" from "node_modules\native-base\lib\module\utils\useResponsiveQuery\useResponsiveQuery.web.js"`

Node: 20.4.0
Expo SDK 49.0.3
Example (via Codespaces (using node 20.30.0)) - [https://github.com/jamielife/temp-proj](https://github.com/jamielife/temp-proj)

**Comment by jamielife** [comment]
Following up, per the suggestion above, adding .mjs files to my metro.config file resolved the issue and following [the advice here](https://github.com/GeekyAnts/NativeBase/issues/5772) resolved the remainder of my errors. 

metro.config.js:
```
// Learn more https://docs.expo.io/guides/customizing-metro
const { getDefaultConfig } = require('expo/metro-config');

/** @type {import('expo/metro-config').MetroConfig} */
const config = getDefaultConfig(__dirname, {
  // [Web-only]: Enables CSS support in Metro.
  isCSSEnabled: true,
});

config.resolver.assetExts.push(
  // Adds support for `.mjs` files
  'mjs'
);

module.exports = config;
```

**Comment by shessafridi** [comment]
Same issue

**Comment by antonyleme** [comment]
Having the same issue here using node 18.17 and expo 49

**Comment by speedhawk21** [comment]
Having the same issue:

node v16.14.1

"expo": "^49.0.0",
"native-base": "^3.4.28",
"react": "18.2.0",
"react-dom": "18.2.0",
"react-native": "0.72.3",

---------------------
› Web is waiting on http://localhost:8081

› Using Expo Go
› Press s │ switch to development build

› Press a │ open Android
› Press i │ open iOS simulator
› Press w │ open web

› Press j │ open debugger
› Press r │ reload app
› Press m │ toggle menu
› Press o │ open project code in your editor

› Press ? │ show all commands

Logs for your project will appear below. Press Ctrl+C to exit.
Web Bundling failed 3365ms
Unable to resolve "stable-hash" from "node_modules/native-base/lib/module/hooks/useStyledSystemPropsResolver.js"

**Comment by likeSo** [comment]
Customize `metro.config.js` can solve this problem; For expo users: 
Run `npx expo customize metro.config.js`
and add `config.resolver.sourceExts.push('mjs', 'cjs')`, rerun project by command `npx expo start -c`

**Comment by derlisrd** [comment]
Same issue
Web Bundling failed 1483ms
Unable to resolve "stable-hash" from "node_modules\native-base\lib\module\hooks\useStyledSystemPropsResolver.js"

**Comment by antonyleme** [comment]
> Customize `metro.config.js` can solve this problem; For expo users: Run `npx expo customize metro.config.js` and add `config.resolver.sourceExts.push('mjs', 'cjs')`, rerun project by command `npx expo start -c`

after doing this i got Unable to resolve "normalize-css-color" from "node_modules/native-base/lib/module/utils/react-native-web-fucntions/normalizeColor.js"

**Comment by likeSo** [comment]
> normalize-css-color

I got this too. And i solved this by `yarn add normalize-css-color`
It seems like Expo SDK 49 removed this package from react native web.

**Comment by derlisrd** [comment]
> > Customize `metro.config.js` can solve this problem; For expo users: Run `npx expo customize metro.config.js` and add `config.resolver.sourceExts.push('mjs', 'cjs')`, rerun project by command `npx expo start -c`
> 
> after doing this i got Unable to resolve "normalize-css-color" from "node_modules/native-base/lib/module/utils/react-native-web-fucntions/normalizeColor.js"

use: npm install normalize-css-color

**Comment by alipiopereira** [comment]
In my case I'm using Expo SDK 49, I solved it like this:

->metro.config.js
const { getDefaultConfig } = require('expo/metro-config');

const config = getDefaultConfig(__dirname);

config.resolver.assetExts.push(
  // Adds support for `.db` files for SQLite databases
  'mjs'
);

module.exports = config;

-------------

->add dependency
yarn add normalize-css-color
