### ISSUE TITLE
Set color for status bar when scrolling page

### ISSUE THREAD

**Issue by joinjoohny** [GeekyAnts/NativeBase#468]
How I can set color for status bar when page scrolled.
Now it is transparent...

<img width="379" alt="2017-02-04 22 46 49" src="https://cloud.githubusercontent.com/assets/1760643/22621406/e451f354-eb2b-11e6-8eb2-d92a44f2a85b.png">

Thx!

**Comment by sankhadeeproy007** [comment]
This is not related to NativeBase. Here's a link which might help you 
http://stackoverflow.com/questions/39297291/how-to-set-ios-status-bar-background-color-in-react-native
