### ISSUE TITLE
template failing to install

### ISSUE THREAD

**Issue by rahul-mahato** [GeekyAnts/NativeBase#4680]
### Description

Trying to install nativebase using the template with `react-native init` is failing.

### CodeSandbox/Snack link

no code sandbox link required

### Steps to reproduce

running
```npx react-native init bylo --template @native-base/react-native-template```

is throwing an error
```
npx: installed 641 in 33.854s
Unexpected token = 
```

>Screenshot
![image](https://user-images.githubusercontent.com/52028898/155931479-91704486-a9aa-4122-b0a7-d8354bc6fc02.png)

### NativeBase Version

3.3.1

### Platform

- [ ] Android
- [ ] CRA
- [ ] Expo
- [ ] iOS
- [ ] Next

**Comment by amars29** [comment]
Hi @rahul-mahato, the above command is working fine. Can you provide more context (maybe npm/node version) about the environment.

**Comment by rahul-mahato** [comment]
It had something to do with my node setup.
It works now.
Thanks @amars29

**Comment by David-C-G-G** [comment]
Hola buen dia, tarde o noche, la verdad e buscado bastante informacion sobre un problema al instalar
**npx react-native init bylo --template @native-base/react-native-template**
ya que me aparece lo siguiente (adjunto imagen):
![error](https://user-images.githubusercontent.com/70966114/160231443-963a7337-059f-4897-b06c-eeac47eed693.PNG)

**Comment by Andrew-Pynch** [comment]
> It had something to do with my node setup. It works now. Thanks @amars29

Can you share how you resolved, please?
