### ISSUE TITLE
statusBarColor has no effect

### ISSUE THREAD

**Issue by yossijacob** [GeekyAnts/NativeBase#469]
Hi,

react-native version 0.41
native-base version 0.5.22
tested on android 6 and 7

expected behavior:
I want to change the statusBar color using a theme. i change the theme variable and the color does not change.

```
get statusBarColor() {
        return Color(this.toolbarDefaultBg).darken(0.2).hexString();
    },
```

Actual behavior:
status bar color does not change.

**Comment by sankhadeeproy007** [comment]
You'll have to add the <StatusBar /> component and then import and use the variable.
Else you can also upgrade to 2.0.x and that sets the statusbar color automatically.
