### ISSUE TITLE
ActionSheet doesn't handle onClose correctly when it's closed by swiping down

### ISSUE THREAD

**Issue by taneba** [GeekyAnts/NativeBase#4692]
### Description

Let's say you have a function handleClose which will be updated after initial rendering (e.g. it refers some state inside). And you pass it to onClose prop on Actionsheet and update some state. You close Actionsheet and expectation is it fires handleClose with the latest state. It works as expected when you close by tapping overlay, but if you close it by swiping DragIndicator, handleClose get called with old state.

### CodeSandbox/Snack link

https://snack.expo.dev/@ynakamura/actionsheet-issue-reporo

### Steps to reproduce

1. Go to https://snack.expo.dev/@ynakamura/actionsheet-issue-reporo 
2. Click 'Actionsheet' button to open the Actionsheet.
3. Tap "Delete" button and close Actionsheet by tapping on Overlay. Then you should see alert with "Delete".
4. Open the Actionsheet again
5. Tap "Share" button and close Actionsheet by swiping down the Actionsheet.
6. You'll see the alert but it says "Delete" instead of "Share"

### NativeBase Version

3.3.4

### Platform

- [ ] Android
- [ ] CRA
- [X] Expo
- [X] iOS
- [ ] Next

### Additional Information

I think it is because onClose is wrapped with useRef inside of ActionContent.tsx, whereas it isn't in Modal.tsx which handles onClose when user taps overlay.

**Comment by surajahmed** [comment]
Hi @taneba, you need to call `onClose` inside `handleClose` to close the Actionsheet.
```
const handleClose = () => {
    console.log(state);
    onClose();
}
```
This will fix the issue. If you still face any problems, let us know.

**Comment by taneba** [comment]
Hi, thank you for taking a look! @surajahmed 
Yeah I need to call onClose, but it's not the problem I meant here (just forgot writing down onClose, sorry). 
The problem is that state won't be changed if user close it by swiping down. Let's say if you update state after first rendering  and close the Actionsheet afterward, it should be logged with the updated state. It works as expected when it's closed by just tapping on overlay but it doesn't if it's closed by swiping down.

And it's caused by how Actionsheet handles the function passed to onClose prop.
`<Actionsheet isOpen={isOpen} onClose={handleClose}>`

onClose will be passed to Modal component internally, and finally it's passed to Overlay. You can see how it's handled [here](https://github.com/GeekyAnts/NativeBase/blob/049822b387/src/components/composites/Modal/Modal.tsx#L79) and obviously it'll be updated when onClose is updated. Thus, tapping on overlay works fine.
But onClose also will be used in ActionsheetContent via ModalContext and eventually it's [wrapped with useRef](https://github.com/GeekyAnts/NativeBase/blob/master/src/components/composites/Actionsheet/ActionsheetContent.tsx#L29), which will be used when it's swiped down. This means it's won't be updated after first it's passed.

Sorry for unclear explanation, but I hope you can get what it is.

**Comment by surajahmed** [comment]
Hi @taneba, Can you please try the latest version `3.4.1`?
I'll try to reproduce this and let you know the status. Thanks!

**Comment by taneba** [comment]
@surajahmed 
Thanks for instruction, but the issue remains in 3.4.1 as well, and it cannot even be closed by tapping on the overlay any more after upgraded to 3.4.1.
Btw some other issues popped up in v3.4.1, but these are not relevant to this issue so I'll looking for issues and create if it's not reported yet.

**Comment by surajahmed** [comment]
@taneba We're working on this.

**Comment by surajahmed** [comment]
@taneba This issue is fixed in version `3.4.2`. Please feel free to let us know if you face any other problems. Thanks!

**Comment by taneba** [comment]
@surajahmed 
I've just tested on my device and it seems to be solved for sure!
Thank you for so quick support 💯

**Comment by najisawas** [comment]
Great to see that this was fixed! I would suggest updating the documentation at least i these few places to mention that users may need to make sure they are on 3.4.2 to get the expected behavior

https://docs.nativebase.io/action-sheet
https://docs.nativebase.io/use-disclose

I think doing a simple `yarn add` gave me 3.4.0, and it took me a day or two of trying a bunch of different fixes before i finally found this thread

**Comment by marcelino-borges** [comment]
I'm using native base `^3.4.25` and I just can't close the ActionSheet...

This is my component:
```javascript
const UserAvatar: React.FC<AvatarProps> = ({
  pictureUrl,
  userInitials,
  size,
}: AvatarProps) => {
  const { isOpen, onOpen, onClose } = useDisclose();

  const AvatarActions = useCallback(
    () => (
      <Actionsheet
        isOpen={isOpen}
        onClose={onClose}
        size="full"
      >
        <Actionsheet.Content>
          <Actionsheet.Item>
            <CustomButton
              title={'Option1 '}
              onPress={() => {}}
            />
          </Actionsheet.Item>
          <Actionsheet.Item>
            <CustomButton
              title={'Option 2'}
              onPress={() => {}}
            />
          </Actionsheet.Item>
        </Actionsheet.Content>
      </Actionsheet>
    ),
    []
  );

  return (
    <>
      <NativeBaseAvatar
        size={size ?? AVATAR_SIZE}
        source={{
          uri: pictureUrl,
        }}
        onTouchEnd={onOpen}
      >
        {userInitials}
        <NativeBaseAvatar.Badge
          size={BADGE_SIZE}
          bg={COLORS.brand[400]}
          style={styles.Badge}
          borderColor={COLORS.brand[200]}
        >
          <Icon
            as={Ionicons}
            name="add-outline"
            color="white"
            size={BADGE_ICON_SIZE}
          />
        </NativeBaseAvatar.Badge>
        <AvatarActions />
      </NativeBaseAvatar>
    </>
  );
};

export default UserAvatar;
```

And this Avatar is inside a `ZStack` component like this:
```javascript
<ScrollView style={styles.ScrollView}>
      <ZStack style={styles.ZStack}>
        {themeBar}

        <Box style={styles.ContentBG} />

        <VStack style={styles.Content}>
          <UserAvatar
            size={AVATAR_SIZE}
            userInitials={
              profile ? profile.firstName[0] + profile.lastName[0] : ''
            }
            pictureUrl={profile?.profileImageUrl}
          />
        </VStack>
      </ZStack>
    </ScrollView>
```
![image](https://user-images.githubusercontent.com/33501037/224505843-d2f3abf7-9b2b-4bbd-9556-4a8aef96e469.png)

Basically I should be able to open the ActionSheet clicking on the UserAvatar, but I also can't open the ActionSheet (even though that `onTouchEnd` event is being correctly executed - just tested with a `console.warn`). And then I shoul be able to close the ActionSheet clicking on the overlay or swipping it down.
