### ISSUE TITLE
If boolean is passed for the Radio button value, typescript is giving error.

### ISSUE THREAD

**Issue by nadun-ibits** [GeekyAnts/NativeBase#4693]
### Description

I need to use Boolean values with a Radio button. But it gives type error.

### CodeSandbox/Snack link

https://codesandbox.io/s/serene-fermat-7smg5e?file=/src/components/Example.tsx

### NativeBase Version

3.3.7

### Platform

- [X] Android
- [ ] CRA
- [ ] Expo
- [X] iOS
- [ ] Next

### Additional Information

![image](https://user-images.githubusercontent.com/97280126/156757101-a7f6369b-4bf2-4002-acbb-eee381f1a245.png)

![image](https://user-images.githubusercontent.com/97280126/156757144-67b97ced-4f08-46a6-984a-2805a53750c9.png)

**Comment by mayank-96** [comment]
Hello @nadun-ibits, `value` prop specifies the value associated with the input, as default behaviour its set type and return type needs to be `string`.

**Comment by nadun-ibits** [comment]
Thank you @mayank-96  for the reply. Is there any way that we could  define the type of the value or declare the type boolean as well? Because we have to cast string to boolean each time when we use boolean.

**Comment by ankit-tailor** [comment]
Hi @nadun-ibits , 
- React-Native [TextInput](https://reactnative.dev/docs/textinput#value) only accepts string values, but you can manipulate it using regex or some other methods. 
- Radio takes a string as a value, a boolean can not be assigned to the radio. As per MDN doc it takes value as string on web as well. [Here](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/radio#value) you can check it out.

Closing the issue for now, feel free to open it if you have any doubt.
