### ISSUE TITLE
How to add validate rules to form?

### ISSUE THREAD

**Issue by bartonhammond** [GeekyAnts/NativeBase#47]
Say for example, I'd like to require a valid email, or that the password has certain characteristics (length, special chars & numbers, etc) or password match during registration - 
1) how would that be set up 
2) where would the error message display?  

I've used this [https://github.com/gcanti/tcomb-form-native](https://github.com/gcanti/tcomb-form-native) and it includes some options for handling these issues.  I assume using that tcomb-form-native w/ NativeBase components would be doable?

**Comment by steida** [comment]
I believe it's over the scope of NativeBase. Check how I am doing universal validation https://medium.com/@steida/why-validation-libraries-suck-b63b5ff70df5#.e42o7putj

**Comment by iiitmahesh** [comment]
@sankhadeeproy007  @steida @bartonhammond  
Is there any other way to do form validation??

how to use nativebase  **Form** using these [tcomb-form-native ](https://github.com/gcanti/tcomb-form-native) ,[ redux-form](https://github.com/erikras/redux-form).
Please provide any steps or reference or code snippet.

**Comment by sanketsahusoft** [comment]
@iiitmahesh You can check this, https://github.com/jamieparkinson/redux-form-native-base

**Comment by iiitmahesh** [comment]
@sanketsahusoft I am talking about [ https://github.com/erikras/redux-form](https://github.com/erikras/redux-form).
[https://github.com/gcanti/tcomb-form-native](https://github.com/gcanti/tcomb-form-native)
How to use this native Form and Input.
(Form validation is my issue)

**Comment by thg303** [comment]
as a ui kit I think this library should provide a way for working with forms.

**Comment by MohamadKh75** [comment]
+1 need validation

**Comment by JeyKeu** [comment]
NativeBase's documentation is lacking.

**Comment by SupriyaKalghatgi** [comment]
https://docs.nativebase.io/docs/examples/ReduxFormExample.html
