### ISSUE TITLE
Typescript autocomplete not showing custom variants

### ISSUE THREAD

**Issue by jrdn91** [GeekyAnts/NativeBase#4706]
### Description

Declaring a custom type for typescript support is not showing autocomplete suggestions

### CodeSandbox/Snack link

https://snack.expo.dev/TxzqfrhF4

### Steps to reproduce

1. Setup the theme typings as described [here](https://docs.nativebase.io/typescript)
2. Attempt to use the new Button variant
3. Don't get an autocomplete suggestion for the new variants that have been added

### NativeBase Version

3.3.7

### Platform

- [ ] Android
- [ ] CRA
- [ ] Expo
- [X] iOS
- [ ] Next

### Additional Information

I don't get typescript errors when using these new variants so It would at least seem it's partially working but VSCode does not give me any suggestions when attempting to use the new variants. Are there any other steps I need to do to get VSCode to suggest these new variants as values I can pass to `variant`?

**Comment by surajahmed** [comment]
@jrdn91 Thanks for reporting! We will look into this.

**Comment by likeSo** [comment]
What is the correct way to setup the default theme for the `Button` component?
<img width="180" alt="image" src="https://user-images.githubusercontent.com/12247340/178149885-59da2d85-7fed-42b6-a7d2-379a26c0eda3.png">
The `variants` props have only `any` type, and there are no examples in the docs...
For now, i don't know how to set the default style for different variants...

**Comment by hirvesh** [comment]
+1 for this issue. Observing same.

**Comment by ankit-tailor** [comment]
Hi Everyone, This issue is fixed in `3.4.14`. Closing the issue for now, feel free to open it if you have any doubts.
