### ISSUE TITLE
Error while updating 'nativeBackgroundAndroid' 

### ISSUE THREAD

**Issue by oky1** [GeekyAnts/NativeBase#472]
Android 4.2.1 (Api 17);
![nativebackgroundandroid](https://cloud.githubusercontent.com/assets/13662700/22687576/aeb700da-ed39-11e6-902e-5286e6670d15.png)
Looks like problem with button (when replacing with TouchableOpacity error disappears);

**Comment by sankhadeeproy007** [comment]
Can you try on a newer device which supports `TouchableNativeFeedback` and check?

**Comment by oky1** [comment]
I will try. Of course  everything will be fine, but the problem persists.
Maybe
if (Platform['Version'] >= 21) {
    background = TouchableNativeFeedback.Ripple(props.backgroundColor);
  } else {
    background = TouchableNativeFeedback.SelectableBackground();
  }

**Comment by sankhadeeproy007** [comment]
Yeah sure. Will roll that out with the next update. The fact that the older API's are supported never crossed our mind. Thanks!

**Comment by Unforgiven-wanda** [comment]
Has this been implemented in the latest release?

**Comment by sankhadeeproy007** [comment]
Yes
