### ISSUE TITLE
Children of `RadioGroup` not rerendered when changed

### ISSUE THREAD

**Issue by opiation** [GeekyAnts/NativeBase#4728]
### Description

Children provided to `RadioGroup` don't get rerendered even when they're different

### CodeSandbox/Snack link

https://snack.expo.dev/@nick.alleycorpnord/c10b41

### Steps to reproduce

1. Render some `children` under `<Radio.Group>`
2. Update the children from the `Radio.Group`'s parent component
3. The children are not rerendered even though they've changed

### NativeBase Version

3.3.7

### Platform

- [ ] Android
- [ ] CRA
- [X] Expo
- [ ] iOS
- [ ] Next

### Additional Information

In the [linked Snack][0], I've provided an example of a `VStack` containing a list of card components and then the same `VStack` wrapped in a `Radio.Group`. In both examples, the props and resulting JSX of the cards change but in the example wrapping in a `Radio.Group`, the cards are not re-rendered. This caching seems too aggressive to be intentional and in either case, is not documented with [Radio][1]. If this **is** intentional, it's not intuitive for a develop to think a behavioral form component like `RadioGroup` would prevent renders of its children in this way.

[0]: https://snack.expo.dev/@nick.alleycorpnord/c10b41
[1]: https://docs.nativebase.io/radio#h3-radio-group

**Comment by enchorb** [comment]
+1 Just spend 2 hours debugging why the `Radio` elements inside `Radio.Group` where not updating their `isInvalid` property. Hope to see a patch fix for this soon as it is critical for showing users updating form error states.

**Comment by surajahmed** [comment]
This issue is fixed in latest version `3.4.6`. Please feel free to reopen if the issue persists. Thanks.

**Comment by zTaaso** [comment]
@surajahmed I'm having the same issue. I tried updating to `3.4.6` and it broke my entire application. Isn't there a workaround for it?
