### ISSUE TITLE
How to fix tabs on top?

### ISSUE THREAD

**Issue by andreyluiz** [GeekyAnts/NativeBase#473]
I am asking here because I don't know if it is a bug or something.

So, I'm setting up a very basic application with two tabs:

**App.js**
```jsx
export default () => (
  <Container>
    <Header>
      <Title>Header</Title>
    </Header>

    <Content>
      <Tabs>
        <Videos tabLabel="Vídeos" />
        <Social tabLabel="Social" />
      </Tabs>
    </Content>
  </Container>
);

const Videos = () => (
  <Container>
    <Content>
      <VideoList /> <= renders several cards, making the content scrollable
    </Content>
  </Container>
);
```

I hid the `Social` component for brevity, but it is very similar to the `Videos` component.

The `VideoList` component renders several cards based on a video list from an API. Example:

![scroll-normal](https://cloud.githubusercontent.com/assets/1965897/22688436/715a00dc-ed13-11e6-8afe-bb933ab7c086.png)

The problem is that my Tab bar is not fixed. When I scroll down the content, the Tab bar scroll together with the content. Another example:

![scrolled](https://cloud.githubusercontent.com/assets/1965897/22688464/8d5be066-ed13-11e6-9f14-04440e732872.png)

I tried to put the `Tabs` component outside `Content` component, but nothing renders.

It's very difficult for me to understand the correct behavior of the tabs. Does someone knows how do I can fix those tabs in the top?

**Comment by sankhadeeproy007** [comment]
Hi, please tell us your versions.

**Comment by andreyluiz** [comment]
Oh, sorry.

Follows:
```
"native-base": "^0.5.22"
"react": "~15.4.0-rc.4"
"react-native": "0.40.0"
```

**Comment by sankhadeeproy007** [comment]
I'd suggest you upgrade to v2.0.x.
Since you're most probably starting off with your project, that should fix it. Another fix would be to, have a <View /> inside the Container, then <Tabs/> followed by a <ScrollView />

**Comment by andreyluiz** [comment]
Nice! Indeed it is fixed. But the API changed a lot. Not a problem, but I need to refactor a little bit. A question: why the jump from 0.5.x to 2.0.0?

**Comment by sankhadeeproy007** [comment]
We done a major rewrite of components and the way they are styled in v2.0.x. Hence the jump. Check out the docs for the details. I'm closing this since it's fixed. Let me know if there's any other problem.

**Comment by andreyluiz** [comment]
No, it's okay now. Thank you.

**Comment by JiboStore** [comment]
would you mind showing how it's done? I followed @sankhadeeproy007 suggestion of using native-base 2.x, and followed his hierarchy, but I lost everything, just a blank view..

**Comment by SupriyaKalghatgi** [comment]
@JiboStore Please refer NativeBase KitchenSink, this would be helpful to you
https://github.com/GeekyAnts/NativeBase-KitchenSink

**Comment by gogulanareshkw** [comment]
same problem for also, can anyone help me please, this is my code

      <Container>
        <Header >
          <Left/>
          <Body><Title>Header</Title></Body>
          <Right/>
        </Header>

        <Content>

          <View style={{backgroundColor:"green",height:150,marginTop:50}}>
          </View>

        <Tabs transparent
         tabBarUnderlineStyle={{borderBottomWidth:2,borderColor:"green"}} >

         <Tab heading="Tab1">
            <ScrollView>
              <Text>tab1</Text>
            </ScrollView>
         </Tab>
         <Tab heading="Tab2">
         <ScrollView>
              <Text>tab2</Text>
              </ScrollView>
         </Tab>
        </Tabs>

          <View style={{backgroundColor:"green",height:150,}}>
          </View>

          <View style={{backgroundColor:"red",height:150,}}>
          </View>

          <View style={{backgroundColor:"yellow",height:150,}}>
          </View>

          <View style={{backgroundColor:"pink",height:150,}}>
          </View>

        </Content>
      </Container>


![image](https://user-images.githubusercontent.com/40063274/41159664-ee135ad6-6b4a-11e8-9460-fe5068b3fc2c.png)

after scroll down , tabs gone inside the header title, i want to fix tabs at the top 

![image](https://user-images.githubusercontent.com/40063274/41159718-1d7e8d18-6b4b-11e8-972c-36bd1bd754d5.png)


    "native-base": "2.1.4",
    "react": "16.0.0-alpha.12",
    "react-native": "0.45.1",

**Comment by SupriyaKalghatgi** [comment]
https://docs.nativebase.io/Components.html#tabs-def-headref
