### ISSUE TITLE
InputMask or add a prop mask to Input component #feature

### ISSUE THREAD

**Issue by gustavorozolin** [GeekyAnts/NativeBase#474]
A suggestion

Add to the NativeBase a component InputMask or a prop in the Input component.

Example:
`<Input mask = "99999-99" />`
Or
`<InputMask mask = "99999-99"/>`

Thank you

**Comment by sankhadeeproy007** [comment]
Hi thanks for reporting this! NativeBase being a UI library, we'd like to keep business logic separate from NativeBase. You can use [this](http://redux-form.com/6.5.0/examples/normalizing/) feature of redux form for that.

**Comment by appjitsu** [comment]
What feature are you referring to exactly? I'd also like a input mask feature.

**Comment by juliancorrea** [comment]
+1

**Comment by svlada** [comment]
@sankhadeeproy007 Could you please reconsider adding this as input-mask is really common stuff in any of the UI frameworks.

**Comment by sandropf** [comment]
@sankhadeeproy007  Could you please reconsider adding this as input-mask is really common stuff in any of the UI frameworks.²
