### ISSUE TITLE
Showcase sites and apps made with NativeBase

### ISSUE THREAD

**Issue by backtrackbaba** [GeekyAnts/NativeBase#4763]
### Description

Currently, on the main site - nativebase.io, we have a link to ["MadeWithNativeBase"](https://madewithnativebase.com/) where 3 demo projects are listed. 

Could we add more live projects which are in production made with NativeBase?

This would help in folks getting an idea of real-world implementation done with NativeBase

### Problem Statement

The problem statement here is to give new users more examples of real-world applications built by using NativeBaseThe problem

### Proposed Solution or API

No major changes as such. Adding more examples to the existing site - ["MadeWithNativeBase"](https://madewithnativebase.com/)  would be ideal

**Comment by AshwiniKumar007** [comment]
Yes, you can add your nativebase projects there. Just click on Submit project and you will be able to add your project
