### ISSUE TITLE
Cant change Text font color Inside of a button tag

### ISSUE THREAD

**Issue by CusProjects** [GeekyAnts/NativeBase#477]
Hi! Thanks for trying out NativeBase!
Due to the overwhelming requests and issues/questions we ask you to add the following details with your issue.

**Comment by sankhadeeproy007** [comment]
Can you attach a sample of the code you're trying?

**Comment by CusProjects** [comment]
sure. 
`
<Button>
<Text style={{color: '#ff0000'}}></Text>
</Button
`

**Comment by sankhadeeproy007** [comment]
![textcolor](https://cloud.githubusercontent.com/assets/10998047/22885942/a1c651b8-f221-11e6-9ae2-2338597dc517.gif)
Seems to work. Please update and check again.

**Comment by CusProjects** [comment]
Ok thank you, i'll

**Comment by simbu88** [comment]
<Button> <Text style={{color: '#ff0000'}}></Text> </Button>  Its not working
