### ISSUE TITLE
Box component doesn't read custom theme colors for borderColor

### ISSUE THREAD

**Issue by ENT108** [GeekyAnts/NativeBase#4775]
### Description

Box component doesn't read custom theme colors for borderColor

### CodeSandbox/Snack link

none

### Steps to reproduce

Just implement box with borderColor attribute using custom theme color value.

![Screenshot 2022-03-23 at 12 19 20](https://user-images.githubusercontent.com/25681316/159688523-f00b176c-db3c-43f1-ab25-ba060c507905.png)

### NativeBase Version

3.3.7

### Platform

- [X] Android
- [X] CRA
- [ ] Expo
- [X] iOS
- [ ] Next

### Additional Information

similar to: https://github.com/GeekyAnts/NativeBase/issues/4519

**Comment by surajahmed** [comment]
@ENT108 Thanks for reporting! We'll add the typing in the coming release.

**Comment by surajahmed** [comment]
@ENT108 Can you please have look at this documentation for typing custom theme https://docs.nativebase.io/typescript?

**Comment by surajahmed** [comment]
This issue is fixed in version `3.4.0` or later.
