### ISSUE TITLE
Warning: Failed prop type: Invalid props.style key from _text props ("fontWeight") supplied to `Image`

### ISSUE THREAD

**Issue by danielvindax** [GeekyAnts/NativeBase#4779]
### Description

I'm facing this warning when using component Button with _text prop and leftIcon.

### CodeSandbox/Snack link

https://codesandbox.io/s/elated-platform-i4yf5s

### Steps to reproduce

2. Click on '...' 
3. Scroll down to '...' 

### NativeBase Version

3.3.4

### Platform

- [ ] Android
- [ ] CRA
- [ ] Expo
- [ ] iOS
- [ ] Next

### Additional Information

Here is my code

`<Button
    borderRadius={4}
    p={1}
    px={1.5}
    _text={{fontSize: 14, fontWeight: 500, color: 'white'}}
    leftIcon={
      <Image
        source={Images.trashBin}
        alt={'trash-bin'}
        w={'15px'}
        h={'15px'}
      />
    }
    onPress={() => {}}>
    Remove
  </Button>`

**Comment by surajahmed** [comment]
Hi @danielvindax Can you please try the latest version `3.4.0` or later?
Let us know if you still face this issue. Thanks for reporting!

**Comment by danielvindax** [comment]
> Hi @danielvindax Can you please try the latest version `3.4.0` or later? Let us know if you still face this issue. Thanks for reporting!

Hi @surajahmed, thank you for looking into it. I see your latest release changes and fixes for the button.
