### ISSUE TITLE
needs a changelog asap

### ISSUE THREAD

**Issue by anonrig** [GeekyAnts/NativeBase#478]
Hello,
With the bump of 2.0.x, changelog is required. What are the differences thats between 0.5.x versions and 2.0.x?

**Comment by basequatro** [comment]
http://nativebase.io/docs/v2.0.0/whats-new

**Comment by gianpaj** [comment]
exactly, where are the other release notes of the previous versions? seem the changelog files gets overwritten on very release...

**Comment by shivrajkumar** [comment]
http://docs.nativebase.io/docs/release-notes/Release.html
