### ISSUE TITLE
Custom components' variants

### ISSUE THREAD

**Issue by astriskit** [GeekyAnts/NativeBase#4781]
### Description

First off, this library is nice; Thanks.

I'm unsure, if this is already built-in; Also couldn't find anything close-enough to it in the documentations so far.

It would be nice to be able to create variants of a custom-component that's based on NativeBase.io components. This might also require to support theming in custom-components as a side-effect.

### Problem Statement

A custom-component is made composed of native-base components. It seems not possible to use the name of this custom-component in the theme-config (specifically, one app-level theme) and then configure various theme-configurations for this component. 

Disclaimer: TBH haven't tried that, but judging by the way the docs go.

### Proposed Solution or API

Aligned with the current way of customising the components from the `native-base`, if name of a custom-component is `HeaderBar`, following could be one way using a custom-theme: 
`
const theme=extendTheme({
Components:{
    HeaderBar:{
        "<component_Id>": configOb
    }
}
})
`
where "<component_Id>" can be either native-base's exported or custom component's name or another individually attributable custom-component's id (some sort of viz. `key`, or some pre-decided custom-attribute `themeId`). And "configOb" is an object that's currently supported for config along with supporting "<component_Id>"/component-name attribute like it's parent object, including `variants`.

This would also need the support of the custom-attribute identifying the custom-component or native-base component in general like `themeId` in above description.

### Alternatives

For now on jsx-level of a custom-component, prop-overriding can lead to create different versions of the react-component itself. This is fine but, preferably design should be (just an opinion) handled on a thematic level or a design-system level or inside the custom-component, leaving props to just handle non-design part of the component. Although, if dev needs, there is always an option to pass on the `...restProps` inside the custom component aptly to override the "defaultProps".

### Additional Information

Happy to help, just in case.

Again thanks for making the library. 
Keep up the good work :)

**Comment by AshwiniKumar007** [comment]
@astriskit  Thanks for the valuable feedback. We will surely look into all the points raised by you.

**Comment by Viraj-10** [comment]
Hi @astriskit, you can use the `Factory` function. It takes a custom component with a theme object.
