### ISSUE TITLE
missing script npm start

### ISSUE THREAD

**Issue by GeekyGhettoKid** [GeekyAnts/NativeBase#479]
npm ERR! Linux 4.4.0-62-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2

npm ERR! missing script: start
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

I still get an error even when I add the start script to my package.json.
This never used to happen with the earlier version I had so this may be a new bug from the new update

**Comment by sankhadeeproy007** [comment]
Fixed with 2.0.3
