### ISSUE TITLE
"Check the render method of 'StaticRenderer'"  using Body or Left inside CardItem

### ISSUE THREAD

**Issue by edgaru** [GeekyAnts/NativeBase#480]
## react-native, react and native-base version
"react": "15.4.1",
"react-native": "0.39.2",
"native-base":  "0.5.18",
## Expected behaviour
Body inside CardItem work well.
## Actual behaviour
Exception: Check the render method of 'StaticRenderer'
## Steps to reproduce (code snippet or screenshot)
```javascript
render() {
    return (
      <ListView
        enableEmptySections={true}
        dataSource={this.state.dataSource}
        renderRow={(new_) => {
          return <TouchableOpacity onPress={() => this.handlePress(new_)}>
            <Card >
              <CardItem>
              <Body>
                   <Image style={{ resizeMode: 'cover' }} source={{uri: new_.image}} />
                   <Text>{new_.title}</Text>
                   <Text>{new_.lead_in}</Text>
                </Body>
              </CardItem>
            </Card>
          </TouchableOpacity>
        }}
      />
    );
  }
}
```
## Screenshot of emulator/device
With Body or Left Component:
![image](https://cloud.githubusercontent.com/assets/3507202/22720071/5856c89e-ed6e-11e6-9a1d-3f0fc78f985b.png)
Without body or left:
![image](https://cloud.githubusercontent.com/assets/3507202/22720185/f9171144-ed6e-11e6-9365-c3f5fe081283.png)

**Comment by sankhadeeproy007** [comment]
cc @shivrajkumar

**Comment by shivrajkumar** [comment]
@edgaru Did you copy paste the code from the example?
If you did, it introduces some rouge characters in the code.
We are looking into fixing it. For now you can manually write in the code.

**Comment by sankhadeeproy007** [comment]
Any progress here?
