### ISSUE TITLE
Slider in a Modal <SSRProvider>

### ISSUE THREAD

**Issue by mcatal** [GeekyAnts/NativeBase#4823]
> 

Hi, i'm upgrade to 3.3.8 and i get this error(warn) now. I'm using react-navigation, expo and native-base 3.3.8

"I am getting a bunch of errors when using a Slider in a Modal."

_Originally posted by @mcatal in https://github.com/GeekyAnts/NativeBase/issues/4273#issuecomment-1082698143_

**Comment by surajahmed** [comment]
@mcatal I'm going to roll back the changes. Thanks for reporting!

**Comment by surajahmed** [comment]
This issue is fixed in 3.4.0 or later
