### ISSUE TITLE
Unable to set a Specific color on the colorscheme

### ISSUE THREAD

**Issue by aplokultran** [GeekyAnts/NativeBase#4839]
### Description

While I was trying to use the colorScheme, I found that it take a random color value and append after the specified color. 

### CodeSandbox/Snack link

https://snack.expo.dev/4dtqE2l11

### Steps to reproduce

2. Click on '...' 
3. Scroll down to '...' 

### NativeBase Version

3.3.7

### Platform

- [X] Android
- [ ] CRA
- [ ] Expo
- [ ] iOS
- [ ] Next

**Comment by surajahmed** [comment]
Hi @youngoalchemisto, We don't have the feature to set a specific color to colorScheme. However, we can pass our default/extended theme color to colorScheme.
```
<Button colorScheme="red">Hello world</Button>
```
You can have a look at the default colors listed on https://docs.nativebase.io/default-theme#h2-colors.

We've added your request to our list for specific color to colorScheme. Thanks!

**Comment by ankit-tailor** [comment]
Hey @aplokultran, `colorScheme` whole color palette object ranges from 50 to 900. You can not use singleton color as `colorScheme` as internally we are using color palette shades. 

Closing this issue for now, feel free to re-open it if you have any doubts.
