### ISSUE TITLE
TextArea _focus props are not working

### ISSUE THREAD

**Issue by mschez** [GeekyAnts/NativeBase#4843]
### Description

TextArea _focus props are not working

### CodeSandbox/Snack link

https://snack.expo.dev/5a0244otc

### Steps to reproduce

1. Click on the Input, the borderColor will be overwritten as expected
2. Click on TextArea, the borderColor on _focus is ignored

### NativeBase Version

3.3.10

### Platform

- [X] Android
- [ ] CRA
- [ ] Expo
- [ ] iOS
- [ ] Next

**Comment by mayank-96** [comment]
Hello @mschez, Thanks for reporting this issue, we have fixed it and will be released in the upcoming version release.

**Comment by mschez** [comment]
That's amazing, thanks to you!

**Comment by ankit-tailor** [comment]
Hi @mschez , We have fixed this issue. It's released in `3.4.2`.
