### ISSUE TITLE
"Popover.CloseButton doesn't close when pressed on android"

### ISSUE THREAD

**Issue by ThelmaAndrews** [GeekyAnts/NativeBase#4857]
### Description

When you try to close the close button inside the popover it does not close. 

### CodeSandbox/Snack link

https://snack.expo.dev/?files=%7B%22App.tsx%22%3A%7B%22type%22%3A%22CODE%22%2C%22contents%22%3A%22import%20React%20from%20%27react%27%3B%5Cnimport%20%7B%20Popover%2C%20Button%2C%20Box%2C%20Center%2C%20NativeBaseProvider%20%7D%20from%20%27native-base%27%3B%5Cn%5Cnfunction%20Example()%20%7B%5Cn%20%20return%20%3CBox%20h%3D%5C%2260%25%5C%22%20w%3D%5C%22100%25%5C%22%20alignItems%3D%5C%22center%5C%22%3E%5Cn%20%20%20%20%20%20%3CPopover%20trigger%3D%7BtriggerProps%20%3D%3E%20%7B%5Cn%20%20%20%20%20%20return%20%3CButton%20%7B...triggerProps%7D%20shadow%3D%7B2%7D%20colorScheme%3D%5C%22danger%5C%22%3E%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20Delete%20Customer%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%3C%2FButton%3E%3B%5Cn%20%20%20%20%7D%7D%3E%5Cn%20%20%20%20%20%20%20%20%3CPopover.Content%20accessibilityLabel%3D%5C%22Delete%20Customerd%5C%22%20w%3D%5C%2256%5C%22%3E%5Cn%20%20%20%20%20%20%20%20%20%20%3CPopover.Arrow%20%2F%3E%5Cn%20%20%20%20%20%20%20%20%20%20%3CPopover.CloseButton%20%2F%3E%5Cn%20%20%20%20%20%20%20%20%20%20%3CPopover.Header%3EDelete%20Customer%3C%2FPopover.Header%3E%5Cn%20%20%20%20%20%20%20%20%20%20%3CPopover.Body%3E%5Cn%20%20%20%20%20%20%20%20%20%20%20%20This%20will%20remove%20all%20data%20relating%20to%20Alex.%20This%20action%20cannot%20be%5Cn%20%20%20%20%20%20%20%20%20%20%20%20reversed.%20Deleted%20data%20can%20not%20be%20recovered.%5Cn%20%20%20%20%20%20%20%20%20%20%3C%2FPopover.Body%3E%5Cn%20%20%20%20%20%20%20%20%20%20%3CPopover.Footer%20justifyContent%3D%5C%22flex-end%5C%22%3E%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%3CButton.Group%20space%3D%7B2%7D%3E%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3CButton%20colorScheme%3D%5C%22coolGray%5C%22%20variant%3D%5C%22ghost%5C%22%3E%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20Cancel%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3C%2FButton%3E%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3CButton%20colorScheme%3D%5C%22danger%5C%22%3EDelete%3C%2FButton%3E%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%3C%2FButton.Group%3E%5Cn%20%20%20%20%20%20%20%20%20%20%3C%2FPopover.Footer%3E%5Cn%20%20%20%20%20%20%20%20%3C%2FPopover.Content%3E%5Cn%20%20%20%20%20%20%3C%2FPopover%3E%5Cn%20%20%20%20%3C%2FBox%3E%3B%5Cn%7D%5Cn%5Cn%20%20%20%20export%20default%20()%20%3D%3E%20%7B%5Cn%20%20%20%20%20%20%20%20return%20(%5Cn%20%20%20%20%20%20%20%20%20%20%3CNativeBaseProvider%3E%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%3CCenter%20flex%3D%7B1%7D%20px%3D%5C%223%5C%22%3E%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3CExample%20%2F%3E%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%3C%2FCenter%3E%5Cn%20%20%20%20%20%20%20%20%20%20%3C%2FNativeBaseProvider%3E%5Cn%20%20%20%20%20%20%20%20)%3B%5Cn%20%20%20%20%7D%3B%5Cn%20%20%20%20%22%7D%7D&dependencies=react-is%2Cexpo-font%2Cnative-base%403.3.4%2Cstyled-system%2Cexpo-constants%2Creact-native-web%2Creact-native-safe-area-context%2Creact-native-svg%2Cstyled-components%2C%40expo%2Fvector-icons%2Cexpo-linear-gradient%2Cformik%2Cyup%2C%40react-navigation%2Fdrawer%2C%40react-navigation%2Fnative%2Creact-native-vector-icons%2Creact-native-gesture-handler%2Creact-native-linear-gradient%2C%40react-native-community%2Fmasked-view%2Creact-native-screens%2Creact-native-reanimated

### Steps to reproduce

1. Go to the snack expo link mentioned above.
2. Select the iOS device and click on the popover and click the close button it works perfectly. 
3. But If you change the device to Android and click the close button inside the popover it doesn't close. 

### NativeBase Version

3.3.3

### Platform

- [X] Android
- [ ] CRA
- [ ] Expo
- [ ] iOS
- [ ] Next

### Additional Information

https://github.com/GeekyAnts/NativeBase/issues/4646. This is also an issue, unable to click any button in the same page of popover.

**Comment by surajahmed** [comment]
@ThelmaAndrews Thanks for reporting this! We're working on this.

**Comment by ankit-tailor** [comment]
Hi @ThelmaAndrews, This issue is fixed in version 3.3.4`.
