### ISSUE TITLE
How to use images on Footer?

### ISSUE THREAD

**Issue by klinkov** [GeekyAnts/NativeBase#486]
Hi! 
I want use Image instead Button in Footer like here [https://github.com/GeekyAnts/NativeBase/issues/360#issue-195653323](https://github.com/GeekyAnts/NativeBase/issues/360#issue-195653323)
Can't find any information about how it should work

**Comment by sankhadeeproy007** [comment]
The link is broken. Can you please check?

**Comment by klinkov** [comment]
@sankhadeeproy007 fixed!

**Comment by klinkov** [comment]
Fixed link, not issue

**Comment by sankhadeeproy007** [comment]
Please use the issue template and fill out the details. Without the version numbers, it's hard for us to figure out.

**Comment by klinkov** [comment]
@sankhadeeproy007 

"native-base": "0.5.22",
"react": "15.4.2",
"react-native": "0.40.0",

**Comment by sankhadeeproy007** [comment]
With nativebase 0.5.x, it's not possible to add images to footer. We recommend upgrading to 2.0.x for the same.

**Comment by klinkov** [comment]
ok, is it documented for 2.0.x?

**Comment by sankhadeeproy007** [comment]
Here's the [link](http://nativebase.io/docs/v2.0.0/components#footerTab) . just replace the Text/Icon with your image.

**Comment by klinkov** [comment]
@sankhadeeproy007 thank you
