### ISSUE TITLE
Removing Native-base from a React Native project

### ISSUE THREAD

**Issue by adamgins** [GeekyAnts/NativeBase#487]
Are there any instructions to remove Native Base from a project I tried it on, please?

I tried npm uninstall native-base but the the project.pbx still has tons of references that causing the build to fail.

For example 

```
62D9CE01C81042789D08256D /* Andale Mono.ttf */ = {isa = PBXFileReference; name = "Andale Mono.ttf"; path = "../node_modules/native-base/Fonts/Andale Mono.ttf"; sourceTree = "<group>"; fileEncoding = undefined; lastKnownFileType = unknown; explicitFileType = undefined; includeInIndex = 0; };
		D73C6061F7E64AA392F2A5D4 /* Arial Black.ttf */ = {isa = PBXFileReference; name = "Arial Black.ttf"; path = "../node_modules/native-base/Fonts/Arial Black.ttf"; sourceTree = "<group>"; fileEncoding = undefined; lastKnownFileType = unknown; explicitFileType = undefined; includeInIndex = 0; };
		
```

Is there some what to clean this up, pls?

**Comment by adamgins** [comment]
OK, I think I got it worked out ... I ran `npm uninstall native-base` before `react-native unlink native-base`. You have to run the `unlink` first.

**Comment by legaciespanda** [comment]
# Unlink
npx react-native unlink native-base 
or
npm react-native unlink native-base

# ...then uninstall
npm uninstall native-base
