### ISSUE TITLE
initialColorMode does nothing

### ISSUE THREAD

**Issue by Southclaws** [GeekyAnts/NativeBase#4885]
### Description

initialColorMode does nothing

### CodeSandbox/Snack link

https://snack.expo.dev/8XbcA6ARQ

### Steps to reproduce

https://snack.expo.dev/8XbcA6ARQ

The snack template doesn't compile for some reason, but the repro is super simple, just copy from the docs https://docs.nativebase.io/next/color-mode#h2-default-color-mode3

```tsx
import { NativeBaseProvider, extendTheme, Text } from "native-base";

// Define the config
const config = {
  useSystemColorMode: false,
  initialColorMode: "dark",
};

// extend the theme
const customTheme = extendTheme({ config });
function App() {
  return (
    // pass itto NativeBaseProvider
    <NativeBaseProvider theme={customTheme}>
      // Your component
    </NativeBaseProvider>
  );
}
```

### NativeBase Version

3.3.7

### Platform

- [ ] Android
- [ ] CRA
- [ ] Expo
- [ ] iOS
- [X] Next

### Additional Information

Quick workaround for us:

```
  const cm = useColorMode();
  cm.setColorMode("dark");
```

Which works because we don't currently have a light mode but are going to implement one soon. So for now, we've just forced our app to always be dark mode by calling this in `_app.tsx` and it works.

**Comment by surajahmed** [comment]
Hi @Southclaws I've tried to reproduce the issue. It seems it works fine for me. Can you please check this https://snack.expo.dev/jWqrHqwYA?
For Nextjs project yo need to pass `isSSR` prop to `NativeBaseProvider`.
```
<NativeBaseProvider theme={customTheme} isSSR>
      // Your component
</NativeBaseProvider>`
```
Thank you ❤️

**Comment by Southclaws** [comment]
Yeah this worked for us, thanks!
