### ISSUE TITLE
FadeIn background for Select not working in android

### ISSUE THREAD

**Issue by vishnuc** [GeekyAnts/NativeBase#4886]
### Description

FadeIn background for Select not working in android

### CodeSandbox/Snack link

https://snack.expo.dev/GL2OpdsK9

### Steps to reproduce

1.Run the example in android device using expo

### NativeBase Version

3.3.x

### Platform

- [X] Android
- [ ] CRA
- [ ] Expo
- [ ] iOS
- [ ] Next

### Additional Information

HI , select box backdrop is fading in nicely in IOS , but in android its sliding up instead of fade in , its not looking good.. how to chage the animation of backdrop or make the background fully transparent. thank you.

**Comment by surajahmed** [comment]
Thanks for reporting this @vishnuc. We'll look into this.

**Comment by chadmroberts88** [comment]
This is still an issue on version 3.4.18. On Android devices, the backdrop translates from the bottom of the page to the top instead of fading in. It works fine on iOS. Is there a way to temporarily disable the backdrop, or make it transparent?

**Comment by pmtu95** [comment]
I have the same issue with Actionsheet on version 3.4.19, the backdrop transition should be fading instead of sliding

**Comment by redhorse10** [comment]
I fixed this issue by adding defaultProps to `Modal` component in my custom theme like this:

`Modal: {
      defaultProps: {
        _overlay: {
          useRNModalOnAndroid: false,
        },
        _backdrop: {
          _pressed: {
            opacity: 0.4,
          },
        },
      },
    },`

**Comment by JordanDDisch** [comment]
> I fixed this issue by adding defaultProps to `Modal` component in my custom theme like this:
> 
> `Modal: { defaultProps: { _overlay: { useRNModalOnAndroid: false, }, _backdrop: { _pressed: { opacity: 0.4, }, }, }, },`

This works, but if your using full screen modals in Android the snackbar covers the modal. Haven't explored ways around that but you can always add margin to the top of your modal to push it below the snackbar.

**Comment by namnm** [comment]
@surajahmed @Viraj-10 still having issue on 3.4.28
