### ISSUE TITLE
Icon messy code

### ISSUE THREAD

**Issue by naWang1227** [GeekyAnts/NativeBase#489]
## react-native, react and native-base version

   "native-base": "^2.0.4",
    "react": "~15.4.0",
    "react-native": "0.41.2",

##Screenshot of emulator/device

android6.0

##code

![qq 20170209140402](https://cloud.githubusercontent.com/assets/25194203/22771316/f2e811b6-eed0-11e6-9f3d-19637f745f48.png)

##error

Icon messy code：

![screenshot_2017-02-09-13-38-27](https://cloud.githubusercontent.com/assets/25194203/22771339/18a5586e-eed1-11e6-97ba-d654ba87571f.png)

**Comment by sankhadeeproy007** [comment]
Can you run `react-native-vector-icons` without native-base?

**Comment by naWang1227** [comment]
我按照https://github.com/oblador/react-native-vector-icons  步骤对android下进行了配置：

![image](https://cloud.githubusercontent.com/assets/25194203/22772488/e8e5a06e-eed7-11e6-8c47-6dbd8c3e8f2b.png)
![image](https://cloud.githubusercontent.com/assets/25194203/22772585/7a1feab2-eed8-11e6-9a46-361469016a3c.png)

下面是我的项目中的：MainApplication.java内容：

![image](https://cloud.githubusercontent.com/assets/25194203/22772990/b718089e-eeda-11e6-89f7-310b1f57ce18.png)
![image](https://cloud.githubusercontent.com/assets/25194203/22773001/c7084c82-eeda-11e6-8f38-5e57cd5fb123.png)

报错：
![image](https://cloud.githubusercontent.com/assets/25194203/22773038/f23e2890-eeda-11e6-84fb-66f3278a1844.png)

**Comment by sankhadeeproy007** [comment]
Please try `react-native link` to link the icons.

**Comment by naWang1227** [comment]
执行   _react-native link_  了。还是报错。

**Comment by naWang1227** [comment]
谢谢帮忙解答，我把修改的地方都注释掉了，icon可以正常显示了，也不知道之前是哪里出了问题。
![screenshot_2017-02-09-15-40-08](https://cloud.githubusercontent.com/assets/25194203/22773671/5717ad38-eede-11e6-8c24-ff4d05459ce8.png)

**Comment by sankhadeeproy007** [comment]
English please!
