### ISSUE TITLE
button disabled not working

### ISSUE THREAD

**Issue by victor-teles** [GeekyAnts/NativeBase#4892]
### Description

disabled prop don't change button appearence 

### CodeSandbox/Snack link

https://snack.expo.dev/@victor.teles/78717d

### NativeBase Version

3.3.10

### Platform

- [X] Android
- [ ] CRA
- [ ] Expo
- [X] iOS
- [ ] Next

**Comment by mayank-96** [comment]
Hello @victor-teles, we don't have `disabled` as a prop, instead we use `isDisabled`. You can try the following code
```
<Button key={size} size={size} isDisabled={true} _disabled={{ bg: 'black'}}>
         BUTTON
</Button>
```

**Comment by victor-teles** [comment]
@mayank-96 thank you for the answer!

But the prop "disabled" works as well, right ?
 
I'm facing some unexpected behaviors because of that
