### ISSUE TITLE
Doen not work onChangeText for input

### ISSUE THREAD

**Issue by mounlion** [GeekyAnts/NativeBase#490]
When i pass floatingLabel function onChangeText doen work

`<Item floatingLabel>
                            <Label>Password</Label>
                            <Input
                                style={{height: 40}}
                                onChangeText={(login) => AlertIOS.alert(
                                    login,
                                    'All your data are belong to us.'
                                )}
                            />
                        </Item>`

**Comment by sankhadeeproy007** [comment]
Duplicate of #483
