### ISSUE TITLE
Status Bar does not hide in modal.

### ISSUE THREAD

**Issue by pk936** [GeekyAnts/NativeBase#4905]
### Description

The status bar is hidden. But when I open modal, the status bar appears again.

### CodeSandbox/Snack link

https://snack.expo.dev/@pk936/moody-toffee

### Steps to reproduce

1. Click on button to see modal.
2. The status bar appears, although it has hidden property set

### NativeBase Version

3.3.10

### Platform

- [X] Android
- [ ] CRA
- [ ] Expo
- [ ] iOS
- [ ] Next

**Comment by surajahmed** [comment]
@pk936 Thanks for reporting this! We'll look into this.

**Comment by Viraj-10** [comment]
Hi @pk936, This Issue is fixed in the latest version on `native-base`
