### ISSUE TITLE
Swipable Tabs

### ISSUE THREAD

**Issue by peter1a** [GeekyAnts/NativeBase#491]
Where i can change tab border bottom and active color? If i change it throught variables with StyleProvider, no changes are maade at all.

**Comment by sankhadeeproy007** [comment]
cc @shivrajkumar

**Comment by peter1a** [comment]
I changed this variables but does't do anything:
# variables.js
topTabBarTextColor: (Platform.OS === 'ios') ? '#6b6b6b' : '#b3c7f9',
  topTabBarActiveTextColor: (Platform.OS === 'ios') ? '#007aff' : '#fff',
  topTabActiveBgColor: (Platform.OS === 'ios') ? '#cde1f9' : undefined,
  topTabBarBorderColor: (Platform.OS === 'ios') ? '#007aff' : '#fff',

**Comment by sankhadeeproy007** [comment]
Will be fixed with next release.

**Comment by peter1a** [comment]
Is this fixed in v2.0.5, because it still doesn't take definded values.

**Comment by sankhadeeproy007** [comment]
No, it isn't yet. We're in the process of rewriting the tabs. So might push it by tomorrow.

**Comment by sankhadeeproy007** [comment]
Fixed with v2.0.6
