### ISSUE TITLE
Set initial value for radio using setState and ref

### ISSUE THREAD

**Issue by SupriyaPKalghatgi** [GeekyAnts/NativeBase#4917]
### Description

Set the radio button with an initial value received. I am checking the received value and doing setState `defaultValue` for `Radio.Group`. Since setState will not render this change immediately, I am trying to update this change on UI with `useRef`. I found issue while defining `ref` for Radio

### CodeSandbox/Snack link

https://snack.expo.dev/@supriya_kalghatgi/radio-ref

### Steps to reproduce

2. Click on '...' 
3. Scroll down to '...' 

### NativeBase Version

3.3.4

### Platform

- [X] Android
- [ ] CRA
- [X] Expo
- [ ] iOS
- [ ] Next

### Additional Information

<img width="962" alt="image" src="https://user-images.githubusercontent.com/95462949/162863220-7ece8cb7-65ef-40bc-8150-3e15c0d38f0a.png">

**Comment by Viraj-10** [comment]
Hi @SupriyaPKalghatgi, closing this issue since a solution is provided. please feel free to re-open it.
