### ISSUE TITLE
Cannot read property 'displayName' of undefined

### ISSUE THREAD

**Issue by alexicum** [GeekyAnts/NativeBase#492]
## react-native, react and native-base version
RN = 0.41
native-base = 2.0.4
## Actual behaviour
Error: Cannot read property 'displayName' of undefined
## Steps to reproduce (code snippet or screenshot)
`<Button onPress={() => this.showFilePicker()}>Select file...</Button>`

**Comment by alexicum** [comment]
It works with native-base 0.5.13
but not with native-base 2.0.4
now button text must be wrapped with <Text></Text>:
`<Button onPress={() => this.showFilePicker()}><Text>Select file...</Text></Button>`

**Comment by sankhadeeproy007** [comment]
use <Text> inside <Button>,
