### ISSUE TITLE
Toast with status

### ISSUE THREAD

**Issue by exneval** [GeekyAnts/NativeBase#4927]
### Description

No longer work as it is used to be

### CodeSandbox/Snack link

https://snack.expo.dev/@exneval/native-base-toast-status

### Steps to reproduce

[Check docs](https://docs.nativebase.io/toast#h3-status--variant-recipes)

### NativeBase Version

3.4.1

### Platform

- [X] Android
- [X] CRA
- [X] Expo
- [X] iOS
- [X] Next

**Comment by exneval** [comment]
It seems toast with status and variants is no longer supported and needs to use a custom component (Alert) instead.
That's how it's written in the storybook.
Didn't see that in any patch notes

**Comment by ankit-tailor** [comment]
Hi @exneval, Thanks for reporting the issue. We've updated the recipe example for status and variant. Docs will be updated in the next release.

**Comment by ankit-tailor** [comment]
Hi @MoSattler, Docs are updated but the example is broken, it will be fixed in the next release.
