### ISSUE TITLE
iconFamily variable not working with StyleProvider

### ISSUE THREAD

**Issue by sedders123** [GeekyAnts/NativeBase#493]
## react-native, react and native-base version
 - React-Native:  0.40.0
 - React: 15.4.2
 - Native-Base: 2.0.4

## Expected behaviour
Changing then `iconFamily` in variables and then applying the variables with a StyleProvider, will change the Icon Set used by Native Base.

## Actual behaviour
Changing the `iconFamily` has no effect, the Icon component only accepts icon names from the IonIcons pack as if it were still default.

## Steps to reproduce (code snippet or screenshot)
```
import { Component } from 'react';
import { Container, StyleProvider, getTheme, Content, Icon } from 'native-base';

const variables={
  iconFamily: 'FontAwesome',
  iconFontSize: 28,
};

class TestPage extends Component {
  render() {
    return (
      <Container>
        <StyleProvider style={getTheme(variables)}>
          <Content>
            <Icon name="user" />
          </Content>
        </StyleProvider>
      </Container>
    );
  }
}
```

## Screenshot of emulator/device
![Screenshot of problem](https://i.imgur.com/F2nRRfl.png)
Note that the `iconFontSize` is applied correctly, it's just the font family that is the issue.

## Is the bug present in both ios and android or in any one of them?
Can only test on Android.

## Any other additional info which would help us debug the issue quicker.
If I use the Icon component from `react-native-vector-icons`, I can sucessfully use other icon sets.

**Comment by sedders123** [comment]
Just seen #b41b50f which looks like it should fix this issue

**Comment by sankhadeeproy007** [comment]
Yes, will be published in a couple of hour or so. You can use from master till then

**Comment by sedders123** [comment]
👍 Thanks
