### ISSUE TITLE
ref not available for Input component

### ISSUE THREAD

**Issue by karthik-durai** [GeekyAnts/NativeBase#4934]
### Description

can't "ref" Input component

### CodeSandbox/Snack link

https://snack.expo.dev/J-2cRbJz4

### NativeBase Version

^3.3.10

### Platform

- [X] Android
- [ ] CRA
- [ ] Expo
- [ ] iOS
- [ ] Next

### Additional Information

Used Factory function but the Input component loses focus on every input.

**Comment by ankit-tailor** [comment]
Hi @karthik-durai, I was not able to reproduce the issue and also I am not able to open your link, it would be great if you can provide some snack / codesandbox link.

**Comment by Viraj-10** [comment]
Hi @karthik-durai, it's working with latest `native-base` version.
