### ISSUE TITLE
Is there a way to pass the styles to the native-base v3 component used inside the wrapper component?

### ISSUE THREAD

**Issue by dev-pacific22** [GeekyAnts/NativeBase#4935]
### Description

I have created some basic wrapper for the native-base component, now sometimes I am using the native base components and need to pass some styles props to the wrapper and from wrapper to native base component. At this point of time I am seeing the only utility props can be passed  as style to native base component. Is there any way that I can pass the style props to native base components instead of utility props. If not I might need to write my own logic to convert css to utility props for each component. Note: The reason behind not using the native base components and utility props directly to the app(without wrapper) is  just to keep the decoupling of the UI library and there will be learning for native base to each developer in team. event if new react0-native developer comes in he need to go through this learning, to avoid this we are creating the generic wrapper components and avoiding direct use of native base components

### CodeSandbox/Snack link

https://snack.expo.dev/A5ODOwAub

### Steps to reproduce

1. Go to [snack](https://snack.expo.dev/A5ODOwAub) 
2. Run the code 
4. See error: There is no effect of style provided for custom input

### NativeBase Version

3.3.*

### Platform

- [X] Android
- [X] CRA
- [ ] Expo
- [X] iOS
- [ ] Next

**Comment by rayan1810** [comment]
Thanks for your patience, we were a bit occupied. All NativeBase components accept `style` prop which is directly mapped to React Native's style prop. You can straightaway pass your styles in this style prop. But the drawback is that theme tokens don't get resolved inside this prop.

```jsx
<Box bg="red.500" /> // This will render a Box with red.500 color picked from theme i.e. #ef4444
<Box style={{ backgroundColor: "#ef4444" }} /> // This will render the same Box.
```

**Comment by Viraj-10** [comment]
Closing this issue since a solution is provided. feel free to re-open the issue.
