### ISSUE TITLE
TouchableOpacity around an element with `shadow` looks bad on Android

### ISSUE THREAD

**Issue by srmagura** [GeekyAnts/NativeBase#4936]
### Description

If you put a `TouchableOpacity` around a `Card`, or other element with a nonzero `shadow`, the box shadow is visible through the element when pressed.

### CodeSandbox/Snack link

https://snack.expo.dev/@srmagura/nativebase-touchableopacity-card-issue

### Steps to reproduce

1. Run my Snack on an Android device. (iOS & web seem to be fine.)
2. Press the card and hold it.

**Expected behavior:** The opacity of the entire card is reduced in a way that is visually appealing.

**Actual behavior:** Something causes the shadow to be visible through the card:

![image](https://user-images.githubusercontent.com/801549/163724108-3d9025bc-d342-4f4a-aa98-8467a73ec3a1.png)

### NativeBase Version

3.4.1

### Platform

- [X] Android
- [ ] CRA
- [X] Expo
- [ ] iOS
- [ ] Next

**Comment by ankit-tailor** [comment]
Hi @srmagura , Hi [here](https://snack.expo.dev/@ankit-tailor/touchableopacity-function-component-example) is the example of `react-native` shadow. This is an open issue from `react-native`. You can follow [this](https://github.com/facebook/react-native/issues/32078) thread to get some work around.
