### ISSUE TITLE
Regression: Outline buttons now have a gray border

### ISSUE THREAD

**Issue by srmagura** [GeekyAnts/NativeBase#4937]
### Description

Buttons with `variant="outline"` now have a gray border instead of using color specified by the `colorScheme` prop.

### CodeSandbox/Snack link

https://snack.expo.dev/@srmagura/nativebase-outline-button-341

### Steps to reproduce

1. View NativeBase 3.4.1 Snack: https://snack.expo.dev/@srmagura/nativebase-outline-button-341
    ![image](https://user-images.githubusercontent.com/801549/163729236-ca074691-780d-491f-a276-80a1bd297601.png)

2. Compare to the same code in NativeBase 3.2.1: https://snack.expo.dev/@srmagura/nativebase-outline-button-321
    ![image](https://user-images.githubusercontent.com/801549/163729231-8dfa65bc-511b-4f42-b777-35005c7fdb2c.png)

### NativeBase Version

3.4.1

### Platform

- [X] Android
- [ ] CRA
- [X] Expo
- [X] iOS
- [ ] Next

### Additional Information

I reviewed the changelog and did not see anything about changing the button border color. So I am guessing this is a regression.

**Comment by srmagura** [comment]
Change was introduced [here](https://github.com/GeekyAnts/NativeBase/commit/12353876a8deeb3b0465277927e664c87872c802#diff-72aec614ddd87deb3e52c8089aa5de2454eeec568b9470a2badf25df2f69befbL93).

**Comment by mayank-96** [comment]
Hello @srmagura, this is expected behaviour according to our new design, we have intentionally kept the border color gray. We'll release the v3.4 UI Kit very soon, you can then check all the new design changes.

**Comment by dylanberry** [comment]
> Hello @srmagura, this is expected behaviour according to our new design, we have intentionally kept the border color gray. We'll release the v3.4 UI Kit very soon, you can then check all the new design changes.

I cannot override this with `extendTheme`. Definitely a bug.

**Comment by Viraj-10** [comment]
Hi @dylanberry, Please try using following code to override `borderColor`
`components: {
      Button: {
        variants: {
          outline: { _light: { borderColor: 'blue.500' } },
        },
      },
    },`

**Comment by surajahmed** [comment]
Closing this issue for now. Please feel free to reopen.

**Comment by ttdatt** [comment]
> Hi @dylanberry, Please try using following code to override `borderColor` `components: { Button: { variants: { outline: { _light: { borderColor: 'blue.500' } }, }, }, },`

Hi @Viraj-10 it works in light mode, but not dark mode
`components: { Button: { variants: { outline: { _dark: { borderColor: 'blue.500' } }, }, }, },` doesn't work
