### ISSUE TITLE
Button Text/Icon doesn't stay centered when providing width/height

### ISSUE THREAD

**Issue by omerdn1** [GeekyAnts/NativeBase#494]
## react-native, react and native-base version
**RN 0.41, native-base 2.0.5.**
## Expected behaviour
**Text/Icon inside Button stays centered after changing it's width/height.**
## Actual behaviour
**Text/Icon doesn't stay centered.**
## Steps to reproduce (code snippet or screenshot)
`<Button>
  <Text>Login</Text>
</Button`
## Is the bug present in both ios and android or in any one of them?
**Present on both iOS and Android**

**Comment by omerdn1** [comment]
Nada?

**Comment by sankhadeeproy007** [comment]
Just add `justifyContent: 'center'`, to your styles.

**Comment by nikssardana** [comment]
I am having the same problem. Here is my code:-

```
<Button transparent>
    <Icon name="ios-heart-outline" style={{color:'#000'}} />
</Button>
```

I have tested it on an android device. I even tried `justifyContent: 'center'` on the button, but that does not seem to work.
NativeBase version in my package.json is:
`"native-base": "^2.4.3",`
