### ISSUE TITLE
Radio BROKEN in latest release

### ISSUE THREAD

**Issue by pierroo** [GeekyAnts/NativeBase#4950]
### Description

Radio used to work, they no longer do in 3.3.7

### CodeSandbox/Snack link

https://docs.nativebase.io/3.3.x/radio

### Steps to reproduce

Just use template Radio.Group, it will crash with the following:
![image](https://user-images.githubusercontent.com/17619412/163996251-371abaaa-8639-408c-bf11-69186ed70a1e.png)

### NativeBase Version

3.3.7

### Platform

- [X] Android
- [ ] CRA
- [ ] Expo
- [ ] iOS
- [ ] Next

**Comment by pierroo** [comment]
After further investigation; it seems that it breaks apart only for Radios that are not checked.
If I keep only the checked one (controlled value), nothing break.
So I would guess there is an issue with the svg handling of non-checked radioBox in your latest update.

**Comment by ankit-tailor** [comment]
HI @pierroo, I wasn't able to reproduce the issue, can you please share snack / codesandbox.

**Comment by pierroo** [comment]
Sure, here it is:

  const [value, setValue] = useState('')

```
 <Radio.Group onChange={setValue} value={value} colorScheme="blue">
    <VStack space={4} alignItems="flex-start" py="3" rounded="sm" w="full">
      <Radio size="lg" value="female">Female</Radio>
      <Radio size="lg" value="male">Male</Radio>
      <Radio size="lg" value="nonbinary">Non Binary</Radio>
    </VStack>
  </Radio.Group>
```

**Comment by ankit-tailor** [comment]
Hi @pierroo, Which version are you using? I am using the latest version `3.4.3` and it's working fine for me.

**Comment by pierroo** [comment]
I am using 3.4.1
Also, I have "react-native-svg": "^12.3.0", in my package.json, maybe there is a conflict of libraries if you are also using it for your radio button?

**Comment by ankit-tailor** [comment]
Hi @pierroo, I've `react-native-svg: ^12.3.0` and `native-base: ^3.4.3` version in my package.json and it's working fine for me.

**Comment by pierroo** [comment]
Thank you.
Does that mean end of investigation on your end?
( Genuine question so I know where to stand regarding this issue, although I have no clue why rolling back to older native base would work; which does make me believe is on native base end )

**Comment by ankit-tailor** [comment]
It would be great If you can provide snack / codesandbox for the issue.

**Comment by brixbimboavengoza** [comment]
Got this bug on Version 3.4.5
![image](https://user-images.githubusercontent.com/17179577/173179215-4f3ea523-d9ff-46d0-820e-ca094fe27156.png)

**Comment by Viraj-10** [comment]
Hi @pierroo, It's working fine with the native-base latest versions. feel free to re-open the issue.
