### ISSUE TITLE
Custom Font family is ignored in Android.

### ISSUE THREAD

**Issue by JorSargsyan** [GeekyAnts/NativeBase#4954]
### Description

I've added font family in theme,and configured it like it was in your documentation.IOS worked perfectly,but in android i've had some issues.When using Text component in android,it ignores any theme provided font family,but when i'm adding font family in stylesheet styles.font family is recognized and everything works.

### CodeSandbox/Snack link

no link

### Steps to reproduce

2. Click on '...' 
3. Scroll down to '...' 

### NativeBase Version

3.4.1

### Platform

- [X] Android
- [ ] CRA
- [ ] Expo
- [ ] iOS
- [ ] Next

### Additional Information

![Screen Shot 2022-04-19 at 6 27 33 PM](https://user-images.githubusercontent.com/25637070/164027335-44b472a5-86bc-405d-95e5-9aeaf63b30aa.png)

**Comment by karyakarsa-tech** [comment]
still doesn't work on android, iOS fine.
