### ISSUE TITLE
`Card` component has no visible border on iOS

### ISSUE THREAD

**Issue by srmagura** [GeekyAnts/NativeBase#4967]
### Description

The card component should have a border of some kind. It does not on iOS.

### CodeSandbox/Snack link

https://snack.expo.dev/@srmagura/nativebase-card-ios

### Steps to reproduce

1. Run the Snack on an iOS device.

Web / Android:

![image](https://user-images.githubusercontent.com/801549/164750761-d8ae12d8-a4fe-4326-b703-df93a607f769.png)

iOS:

![NativeBase card iOS](https://user-images.githubusercontent.com/801549/164750632-fb99d91c-c772-4144-a8ae-d3e3b14107ee.jpeg)
.

### NativeBase Version

3.4.1

### Platform

- [ ] Android
- [ ] CRA
- [X] Expo
- [X] iOS
- [ ] Next

**Comment by ankit-tailor** [comment]
Hi @srmagura, Thanks for reporting the issue. We'll fix it soon.

**Comment by Viraj-10** [comment]
Hi @srmagura, We don't support the `Card` component yet. That's why we don't have documentation for it. you can use the `Box` or `Container` component.
