### ISSUE TITLE
Docs is breaking

### ISSUE THREAD

**Issue by ghost** [GeekyAnts/NativeBase#497]
The [theme variables page](http://nativebase.io/docs/v2.0.0/theme-variables) is broken.

**Comment by sankhadeeproy007** [comment]
Variables [here](https://github.com/GeekyAnts/NativeBase/blob/master/src/theme/variables/platform.js)

**Comment by jagadeshbabu** [comment]
@sankhadeeproy007 thanks for the pointing me there. However the documentation page is broken. Can you please verify and fix the page?

**Comment by sankhadeeproy007** [comment]
Sure, will do!
