### ISSUE TITLE
Regresssion: Cannot use images with Avatar

### ISSUE THREAD

**Issue by johnf** [GeekyAnts/NativeBase#4970]
### Description

Avatar no longer supports required images

### CodeSandbox/Snack link

https://snack.expo.dev/yZSTh2TeX

### Steps to reproduce

1. See snack above the first Avatar doesn't have an image

### NativeBase Version

3.4.3

### Platform

- [X] Android
- [ ] CRA
- [ ] Expo
- [X] iOS
- [ ] Next

### Additional Information

This was originally fixed in https://github.com/GeekyAnts/NativeBase/commit/bbc2ce4dc08bc92c2c2f908f8a684374e642b4ca
but then looks to have been accidentally reverted in

https://github.com/GeekyAnts/NativeBase/commit/eb99803231c2935f6966cbb98d1c580471dec728#diff-94556544ee52296429d62e0c292822e0aaee76abbf7a08f95e025c59eecc624cL34-R35

**Comment by ankit-tailor** [comment]
Hi @johnf, Thanks for reporting the issue. We'll fix it.

**Comment by Viraj-10** [comment]
Hi @johnf, This issue has been fixed in `v3.4.6`
