### ISSUE TITLE
android hardwareBackPress  conflicts with useToast

### ISSUE THREAD

**Issue by Alt-er** [GeekyAnts/NativeBase#4978]
### Description

When the toast is displayed, the return can be triggered normally

### CodeSandbox/Snack link

temporarily unavailable

### Steps to reproduce

back cannot be used when toast is displayed！

### NativeBase Version

3.3.1

### Platform

- [X] Android
- [ ] CRA
- [ ] Expo
- [ ] iOS
- [ ] Next

**Comment by ankit-tailor** [comment]
Hi @Alt-er, Thanks for reporting the issue. We'll fix it.

**Comment by Alt-er** [comment]
Is this problem hard to fix? 😭

**Comment by ankit-tailor** [comment]
Hey, This requires some architectural changes in the toast. We are working on it. Will keep you updated.

**Comment by ankit-tailor** [comment]
Hey, This issue is fixed in `v3.4.13`.
