### ISSUE TITLE
“requireNativeComponent: "RNCSafeAreaProvider" was not found in the UIManager.”

### ISSUE THREAD

**Issue by mamadfar** [GeekyAnts/NativeBase#4982]
### Description

I have this error at the begining of my app 😢

### NativeBase Version

3.4.3

### Platform

- [X] Android

### Additional Information

when I use this code in App.js, I get that error and I don't know why!
I install `react-native-safe-area-context` and nothing !
```js
import React from "react";
import {NativeBaseProvider, Box} from "native-base";

export default function App() {
  return (
    <NativeBaseProvider>
      <Box>Hello world</Box>
    </NativeBaseProvider>
  );
}

```

**Comment by Viraj-10** [comment]
Hi @mamadfar, Please provide us with the detailed steps you followed to install `native-base` with your environment details.

- Node version
- package manager (yarn / node).
- CLI used( RCL/expo etc).

**Comment by mamadfar** [comment]
> Hi @mamadfar, Please provide us with the detailed steps you followed to install `native-base` with your environment details.
> 
> * Node version
> * package manager (yarn / node).
> * CLI used( RCL/expo etc).

Hi @Viraj-10 , I use nvm for using multiple node and npm version but most the time I use node 16.
For package manager I use both (yarn and npm )
and I used native base on a existed project with react native cli

**Comment by pierrecabriere** [comment]
+1

**Comment by Viraj-10** [comment]
Hi @mamadfar @pierrecabriere, I am unable to reproduce this issue. can you push it to the repo and send me the link? So I can have a better idea.

**Comment by mamadfar** [comment]
> Hi @mamadfar @pierrecabriere, I am unable to reproduce this issue. can you push it to the repo and send me the link? So I can have a better idea.

@Viraj-10 thank you but I solved it by ./gradlew clean and yarn start --reset-cache

**Comment by maaliHasan** [comment]
I still have this issue! rest the npm cache and clean the gradlew didn't help me! Any idea please?

**Comment by mamadfar** [comment]
> I still have this issue! rest the npm cache and clean the gradlew didn't help me! Any idea please?

@maaliHasan every time you add a new package or you make a critical change, you must rebuild your app and then clean the gradlew and I assure you that it will work.

**Comment by punndcoder28** [comment]
Facing the same issue on version `3.4.17` on iOS. Tried the above mentioned steps but nothing seems to work. What I have tried till now
1. resetting metro cache
2. delete and reinstall pods
3. delete the previous version of the app install and retry
Any steps that I might have missed?

**Comment by hanamurayuki** [comment]
I also faced same issue.

`yarn add react-native-safe-area-context@4.2.4`
`npx expo run:ios` or `npx expo run:ios --no-build-cache`

solved my issue.

**Comment by mehranjavid** [comment]
I was getting the same issue when creating a new project and just following the installation steps of native base.

solved it by [cleaning build folder in xcode ](https://medium.com/@abhisheknalwaya/how-to-clear-react-native-cache-c435c258834e#:~:text=To%20clean%20the%20iOS%20build,cache%20for%20your%20current%20target.) and following your steps 

> 
> @maaliHasan every time you add a new package or you make a critical change, you must rebuild your app and then clean the gradlew and I assure you that it will work.

**Comment by ALIAHSANRST** [comment]
any solution in bare react native project ?
