### ISSUE TITLE
No Ripple Effect for Button theme "light" in android. 

### ISSUE THREAD

**Issue by georgemickael-b** [GeekyAnts/NativeBase#499]
"native-base": "2.0.5",
"react": "15.4.2",
"react-native": "0.41.1",

**Comment by sankhadeeproy007** [comment]
The ripple effect is being hidden by the background color itself. Use prop `androidRippleColor` to set a ripple color for light buttons.

**Comment by haiithust** [comment]
Can you give me an example about "Use prop androidRippleColor to set a ripple color for light buttons". I'm a beginner. thank you.

**Comment by SupriyaKalghatgi** [comment]
@haiithust Please check React Native Docs for same
