### ISSUE TITLE
Web Select switches from uncontrolled to controlled

### ISSUE THREAD

**Issue by cloudratha** [GeekyAnts/NativeBase#4996]
### Description

When using the Select in Web as controlled or uncontrolled, I expect the component to not throw internal React errors when making selections

### CodeSandbox/Snack link

https://codesandbox.io/s/zealous-mahavira-mxkh1m

### Steps to reproduce

1. View the console is error free
2. Change the select to "Category"
3. View the error in the console 

### NativeBase Version

3.3.6

### Platform

- [ ] Android
- [ ] CRA
- [ ] Expo
- [ ] iOS
- [ ] Next

### Other Platform

Web

**Comment by mayank-96** [comment]
Hello @cloudratha, thanks for reporting this issue. We'll look into it!

**Comment by Viraj-10** [comment]
Hi @cloudratha, This Issue has been fixed in `v3.4.6`.
