### ISSUE TITLE
overriding AlertDialog baseStyle (_fade, _backdropFade) is not working

### ISSUE THREAD

**Issue by hoondeveloper** [GeekyAnts/NativeBase#4997]
### Description

overriding AlertDialog baseStyle (_fade, _backdropFade) is not working.

(+) and default fade animation duration became too slow, so it seems unnatural.

### CodeSandbox/Snack link

https://snack.expo.dev/sSC9-U5FS

### Steps to reproduce

1. Go to Expo Snack link
2. Open iOS App, and click 'Open' Button
3. and watch the AlertDialog is showing and see _fade, _backdropFade baseStyle is not overriden.

### NativeBase Version

3.4.3

### Platform

- [ ] Android
- [ ] CRA
- [ ] Expo
- [X] iOS
- [ ] Next

**Comment by mayank-96** [comment]
Hello @hoondeveloper, Thanks for reporting this issue, we'll look into this!

**Comment by Viraj-10** [comment]
@surajahmed  @rayan1810 @mayank-96 Need to rethink how this can be handled on the theme level and not on the component level and should provide consistency for all the animation props.
