### ISSUE TITLE
Cant get your list examples to render properly

### ISSUE THREAD

**Issue by anthonywebb** [GeekyAnts/NativeBase#5]
I am using one of your simple list examples but it will not render properly (I am going for the look you have in your examples), actually none of the lists are.  Can you help identify what I am going wrong?

Simple code is here:
https://gist.github.com/anthonywebb/eb32f7229c860cc386080b243d1a02f5

<img width="429" alt="screen shot 2016-05-04 at 9 59 50 am" src="https://cloud.githubusercontent.com/assets/4397/15020363/fc7b401a-11de-11e6-95ab-224f9d002e7a.png">

**Comment by himanshu-sahusoft** [comment]
It worked fine when I tested your code. Maybe you can install the new version and and see if it's fixed.

**Comment by himanshu-sahusoft** [comment]
@anthonywebb I'm closing this issue. Feel free to reopen if you face this problem again.
