### ISSUE TITLE
please add a datatables / datagrid component!!

### ISSUE THREAD

**Issue by vesper8** [GeekyAnts/NativeBase#50]
This is sorely missing.. I know it must be much more complicated. But I really need one for my next project where I meant to use your boilerplate and this framework.

I need a datatable component that can handle multiple columns/rows with some kind of responsive mechanism for tables that are too large to fit on the screen. Just simple horizontal scrolling would be fine.

If it could also handle column sorting.. pagination and search/filter well omg that would be a dream.. but at this point I'll gladly take something basic. There seems to be a scarcity for this type of component.

Any hope of you adding this soon? Something that will work for both IOS and Android.

**Comment by sanketsahusoft** [comment]
@vesper8, Thanks for the input. Data-tables / data-grid isn't common for Mobile apps and so we won't be adding that to our short-term roadmap (1 to 2 months). I have added the `enhancement` label, we will have an internal discussion and update this thread. Please don't expect any development on this for next 1-2 months.

**Comment by vesper8** [comment]
ok I understand... do you have any advice on which 3rd party library I could look at? My specific app situation really requires a sturdy datatable solution.

I just bought both StrapMobile's RN apps btw :)

**Comment by sankhadeeproy007** [comment]
You can take a look at this repo. https://github.com/aksonov/react-native-tableview
Not sure how useful it will be, but that's the only option.
