### ISSUE TITLE
Customizing shadows in theme not working on the web

### ISSUE THREAD

**Issue by 404-html** [GeekyAnts/NativeBase#5008]
### Description

An attempt to customize shadows in theme results in a failure. Provided `box-shadow` css is not applied on the target element. Instead of that DOM element receives a lot of extra classes with strange names in `class` attribute.

### CodeSandbox/Snack link

https://codesandbox.io/s/admiring-chihiro-779m5c?file=/src/App.tsx

### Steps to reproduce

1. Customize `shadows` attribute in theme:

```
const theme = extendTheme({
  shadows: {
    "5":
      "box-shadow: 0px 2px 6px rgba(41, 63, 204, 0.16), 0px 4px 12px rgba(49, 75, 245, 0.36);"
  }
});
```

2. Change `shadow` attribute in some component, e.g.:

```
<NativeBaseProvider theme={theme}>
   <Button shadow="5">Hello</Button>
</NativeBaseProvider>
```

### NativeBase Version

3.3.7

### Platform

- [ ] Android
- [ ] CRA
- [ ] Expo
- [ ] iOS
- [X] Next

**Comment by rayan1810** [comment]
Hey, this is the correct way to customize your shadow. I guess this answers your query, hence I'm closing the issue. Feel free to reopen if this isn't what you were looking for.

<img width="869" alt="Screenshot 2022-05-16 at 2 06 51 PM" src="https://user-images.githubusercontent.com/36300815/168552941-383cbaec-135f-4942-9b5c-39af50312da4.png">

**Comment by Lurtroxx** [comment]
Not working still. @rayan1810
