### ISSUE TITLE
No instructions for adding icons to React Native CLI project

### ISSUE THREAD

**Issue by JeremyBradshaw7** [GeekyAnts/NativeBase#5014]
### Description

Missing installation instructions in README and docs for adding icons to React Native CLI project.

### Steps to reproduce

```
npx react-native init new_nb --template @native-base/react-native-template-typescript
cd new_nb
yarn add @native-base/icons
cd ios && pod install & cd ..
npm run ios
```

Add sample Icon code to App.tsx:

```
import {Icon} from 'native-base';
import {Entypo, FontAwesome, Ionicons, FontAwesome5} from '@native-base/icons';
```
```
            <Icon as={Entypo} name="user" size={30} color={'#ff0000'} />
            <Icon as={FontAwesome} name="user" size={30} color={'#00ff00'} />
            <Icon as={FontAwesome5} name="user" size={30} color={'#00ffff'} />
            <Icon as={Ionicons} name="user" size={30} color={'#fdf432'} />
```

<img width="140" alt="image" src="https://user-images.githubusercontent.com/36155348/168151937-63b9cc01-4e02-4619-aeb0-04b75206ab9e.png">

![image](https://user-images.githubusercontent.com/36155348/168151995-abadd2e0-24a4-4999-8096-1bcf73ff3a88.png)

### NativeBase Version

3.4.0

### Platform

- [X] Android
- [ ] CRA
- [ ] Expo
- [X] iOS
- [ ] Next

### Additional Information

I'm upgrading from NB 2 to 3 in a React Native CLI project, and understand I have to install @native-base/icons, but looking for the installation instructions [here](https://docs.nativebase.io/nb-icons) it only mentions NextJS, Expo, and React (not Native). Are there no additional steps required for React Native CLI? There must be something amiss as I'm getting "Unrecognised Font Family" errors.

Furthermore, my v2 installation has historically left font references in the `Info.plist` and `project.pbxproj` files - should these be removed?

**Comment by Viraj-10** [comment]
Hi @JeremyBradshaw7, Currently `@native-base/icons` is only supported in `Next.js`, `React App`, `Expo`. We will add support for `React Native CLI ` in future updates.

**Comment by JeremyBradshaw7** [comment]
OK thanks @Viraj-10 - perhaps that could be clearer in the docs.

**Comment by nimajnsr** [comment]
> ### Description
> Missing installation instructions in README and docs for adding icons to React Native CLI project.
> 
> ### Steps to reproduce
> ```
> npx react-native init new_nb --template @native-base/react-native-template-typescript
> cd new_nb
> yarn add @native-base/icons
> cd ios && pod install & cd ..
> npm run ios
> ```
> 
> Add sample Icon code to App.tsx:
> 
> ```
> import {Icon} from 'native-base';
> import {Entypo, FontAwesome, Ionicons, FontAwesome5} from '@native-base/icons';
> ```
> 
> ```
>             <Icon as={Entypo} name="user" size={30} color={'#ff0000'} />
>             <Icon as={FontAwesome} name="user" size={30} color={'#00ff00'} />
>             <Icon as={FontAwesome5} name="user" size={30} color={'#00ffff'} />
>             <Icon as={Ionicons} name="user" size={30} color={'#fdf432'} />
> ```
> 
> <img alt="image" width="140" src="https://user-images.githubusercontent.com/36155348/168151937-63b9cc01-4e02-4619-aeb0-04b75206ab9e.png">
> 
> ![image](https://user-images.githubusercontent.com/36155348/168151995-abadd2e0-24a4-4999-8096-1bcf73ff3a88.png)
> 
> ### NativeBase Version
> 3.4.0
> 
> ### Platform
> * [x]  Android
> * [ ]  CRA
> * [ ]  Expo
> * [x]  iOS
> * [ ]  Next
> 
> ### Additional Information
> I'm upgrading from NB 2 to 3 in a React Native CLI project, and understand I have to install @native-base/icons, but looking for the installation instructions [here](https://docs.nativebase.io/nb-icons) it only mentions NextJS, Expo, and React (not Native). Are there no additional steps required for React Native CLI? There must be something amiss as I'm getting "Unrecognised Font Family" errors.
> 
> Furthermore, my v2 installation has historically left font references in the `Info.plist` and `project.pbxproj` files - should these be removed?

hi i just figure it out if you install react-native-vector-icons and setup it properly , @native-base/icons going to work ;-) because basically it use same instructors
