### ISSUE TITLE
head style error

### ISSUE THREAD

**Issue by wuxudong** [GeekyAnts/NativeBase#503]
## react-native, react and native-base version
native-base: 2.0.5
react: 15.4.2
react-native: 0.41.2
## Expected behaviour
![simulator screen shot 12 feb 2017 10 49 59 pm](https://cloud.githubusercontent.com/assets/1391101/22863201/bfbf37a8-f176-11e6-93a2-58cffd6e6d8e.png)

## Actual behaviour

![simulator screen shot 12 feb 2017 10 55 37 pm](https://cloud.githubusercontent.com/assets/1391101/22863207/d0df2796-f176-11e6-891f-8f3f081ed0a6.png)

## Steps to reproduce (code snippet or screenshot)

   If I change native-base to 0.5.22, it works well, but in 2.0.5, the header is wrong styled.

    export default class AnatomyExample extends Component {
      render() {
        return (
          <Container>
            <Header>
              <Button transparent>
                <Icon name='ios-arrow-back' />
              </Button>

              <Title>Header</Title>

              <Button transparent>
                <Icon name='ios-menu' />
              </Button>
            </Header>
            <Content>
              <Text>Content</Text>
            </Content>

            <Footer>
              <FooterTab>
                <Button transparent>
                  <Icon name='ios-call' />
                </Button>
              </FooterTab>
            </Footer>
          </Container>
        );
      }
    }

**Comment by sanketsahusoft** [comment]
@wuxudong The use-case of Header has changed in v2.x. You need to use `<Left>`, `<Body>` and `<Right>` tags now in `<Header>`. Check [the docs here](http://nativebase.io/docs/v2.0.0/components#header1)
