### ISSUE TITLE
This project uses sdk 42.0.0.0 but this version of Expo Go only supports the following SDKs: 45.0.0, 44.0.0, 43.0.0.

### ISSUE THREAD

**Issue by franjavi06** [GeekyAnts/NativeBase#5031]
### Description

expo init my-app --template @native-base/expo-template -> This is not working on the lastest version of the android app Expo Go.

### CodeSandbox/Snack link

https://user-images.githubusercontent.com/18015702/169694027-a95c8aa1-fce0-4b16-bb72-e86b1a1facd5.jpg

### Steps to reproduce

2. Click on '...' 
3. Scroll down to '...' 

### NativeBase Version

3.4

### Platform

- [X] Android
- [ ] CRA
- [X] Expo
- [ ] iOS
- [ ] Next

### Additional Information

![Screenshot_2022-05-22-07-55-04-684](https://user-images.githubusercontent.com/18015702/169694027-a95c8aa1-fce0-4b16-bb72-e86b1a1facd5.jpg)

**Comment by Viraj-10** [comment]
Hi @franjavi06, You can just upgrade expo `expo upgrade 44`. which will upgrade the expo SDK to 44. we will upgrade `@native-base/expo-template` soon.

**Comment by franjavi06** [comment]
ok thanks

**Comment by hussamkhatib** [comment]
After upgrading this command will fix the warning of dependency issue.
`expo doctor --fix-dependencies`

**Comment by Viraj-10** [comment]
This issue is fixed now.
