### ISSUE TITLE
Styling (border bottom) is not applied when adding InputRightElement

### ISSUE THREAD

**Issue by balajsebastian** [GeekyAnts/NativeBase#5032]
### Description

When I'm adding InputRightElement as prop the styling is not applied

### CodeSandbox/Snack link

----

### Steps to reproduce

Add some styling to Input and then InputRightElement. You will see that the styling is not applied.

### NativeBase Version

3.2.2

### Platform

- [ ] Android
- [ ] CRA
- [ ] Expo
- [ ] iOS
- [ ] Next

**Comment by Viraj-10** [comment]
Hi @balajsebastian, I am unable to reproduce the bug. Can you provide a snack link with a small code snippet?

**Comment by balajsebastian** [comment]
const styles = {
    error: {
      borderBottomColor: theme.colors.red["500"]
    }
  };
 
 <Input
        style={error ? styles.error : undefined}
        InputLeftElement={InputLeftElement}
        defaultValue={defaultValue}
        isFullWidth
        type={type}
        placeholder={placeholder}
        InputRightElement={renderers.inputRightElement()}
        onChangeText={onChange}
      />
      
      in this case my red border bottom is not added

**Comment by Viraj-10** [comment]
Hi @balajsebastian, Try Using 
`  <Input _important={error ? { borderBottomColor: "#8B0000" } : {}} />`
