### ISSUE TITLE
Select text pushed to the end on Android

### ISSUE THREAD

**Issue by tavaoq** [GeekyAnts/NativeBase#5035]
### Description

When the selected item text in the Select component box is bigger than the box itself, it gets pushed to the end, cutting the left part of it.

### CodeSandbox/Snack link

https://snack.expo.dev/C5DzBi1PD

### NativeBase Version

3.3.5

### Platform

- [X] Android
- [ ] CRA
- [ ] Expo
- [ ] iOS
- [ ] Next

**Comment by Viraj-10** [comment]
Hi @tavaoq, Thanks for reporting the issue. we will look into it.
