### ISSUE TITLE
ListItem onPress

### ISSUE THREAD

**Issue by peter1a** [GeekyAnts/NativeBase#504]
Get error when use param onPress in ListItem:

## react-native, react and native-base version
react-native 0.41.2
native-base 2.0.5
## Expected behaviour
Should open other component.
## Actual behaviour
Get error: Error while updating property 'nativeBackgroundAndroid' of a view managed by: RCTView
## Is the bug present in both ios and android or in any one of them?
Present on Android (4.4.4), works on iOS and also works on Android Emulator, but doesn't work on physical device

**Comment by sankhadeeproy007** [comment]
Does [`touchableNativeFeedback`](https://facebook.github.io/react-native/docs/touchablenativefeedback.html) work on your device?

**Comment by peter1a** [comment]
Yes works

**Comment by sankhadeeproy007** [comment]
Is the `<Button />` component working fine?

**Comment by peter1a** [comment]
Yes, like it suppose to.

**Comment by sankhadeeproy007** [comment]
Fixed with 2.0.7
