### ISSUE TITLE
Toast are hidden by Keyboard

### ISSUE THREAD

**Issue by etiennelacoursiere** [GeekyAnts/NativeBase#5052]
### Description

The Toast component is appearing under the keyboard on IOS ( didn't test android yet ). It happend with the default `Toast.show({ title: 'Some title'})` as well as with a Custom component with useToast  and the render prop `toast.show({ render: () => <CustomToast title='some title' />})`

### CodeSandbox/Snack link

https://snack.expo.dev/zUHoqmQlr

### Steps to reproduce

1. Focus the input to pop the keyboard
2. Click on Spawn Toast
3. The toast is under the keyboard

### NativeBase Version

3.3.4

### Platform

- [ ] Android
- [ ] CRA
- [ ] Expo
- [X] iOS
- [ ] Next

**Comment by Viraj-10** [comment]
Hi @etiennelacoursiere, Thanks for reporting the issue. We will look into it. 
As an alternative for now. you can use `placement:'top'`. which places toast in the top position.

**Comment by Viraj-10** [comment]
This issue has been fixed in `v3.4.8`.
