### ISSUE TITLE
_pressed doesn't work with fab component

### ISSUE THREAD

**Issue by sanna231** [GeekyAnts/NativeBase#5053]
### Description

_pressed doesn't work with fab component

### CodeSandbox/Snack link

https://codesandbox.io

### NativeBase Version

3.4.5

### Platform

- [X] Android
- [X] CRA
- [X] Expo
- [X] iOS
- [X] Next

**Comment by Viraj-10** [comment]
This issue has been fixed in NativeBase `v3.4.7`
