### ISSUE TITLE
Webview in a Content doesn't scroll as expected to the end of the text

### ISSUE THREAD

**Issue by elaliwat** [GeekyAnts/NativeBase#506]
Hi all,
Webview in a Content doesn't scroll as expected to the end of the text. Especially in Android, it is more problematic and can't even reach to the end of the text in any way.

Current versions and other info
## Is the bug present in both ios and android or in any one of them? YES. But Android is more problematic.

**This is variable:**
const **SCREEN_HEIGHT** = require('Dimensions').get('window').height;

**This is the render code:**
 <Container>

            <Header theme={myTheme}>
                <Button transparent>  <Icon name='ios-arrow-back' /> </Button> 
                <Title>SOME TITLE</Title>
                <Button transparent>   <Icon name='ios-menu' />  </Button>
            </Header>

            **<Content style={{ marginHorizontal:10,  marginVertical:10 }} >            
                <WebView
                    ref={'webview'}
                    style={{ height: SCREEN_HEIGHT, }}
                    automaticallyAdjustContentInsets={false}
                    source={{html: '<html>'+this.state.content+'</html>' }} />
            </Content>**
        </Container>

**This is the state.content:**
<p>
    Poliçemiz, yurt dışına açıktır ancak, bir seyahat sağlık sigortası
    değildir. Seyahat sağlık sigortası, teminatlar bazında özel sağlık
    sigortasından farklı bir poliçedir. Konsolosluklar tarafından talep edilen
    cenaze teminatı ise en belirgin farklardan biridir. Poliçemizde, yurt
    dışına çıkışların ilk 60 gününde oluşan sağlık harcamaları, Türk tabipler
    birliği asgari ücret tarifesindeki rakamlar baz alınarak
    değerlendirilmektedir.
</p>
<p>
    Özel sağlık sigortası poliçemiz yurt dışına açık olmakla birlikte dikkat
    edilmesi gereken aşağıdaki bazı hususları hatırlatmak isteriz;
</p>
<ul>
    <li>
        Sigorta şirketinin yurt dışında herhangi bir hastane ile anlaşması
        olmadığından provizyon alınamamaktadır. Bu nedenle sağlık harcamaları
        öncelikle tarafınızca finanse edilmeli ve sonrasında aşağıdaki
        evrakların İnsan Kaynakları Sağlık bölümüne iletilmesi gerekmektedir.
    </li>
    <ul>
        <li>
            Fatura aslı
        </li>
        <li>
            Şikayet ve tanıyı belirten doktor raporu (İngilizce)
        </li>
        <li>
            Tahlil varsa, istek kağıdı ve sonuç fotokopileri
        </li>
    </ul>
</ul>
<ul>
    <li>
        Yapılan ödemelerin iadeleri, Türk Tabipler Birliğince belirlenmiş
        rakamlar dikkate alınarak, klozlarımızda belirtilen geri ödeme
        oranlarınca yapılabilmektedir. Örneğin; yurt dışında gerçekleşen bir
        muayene için ödeyeceğiniz tutar yaklaşık 200 €’dur. Türk Tabipler
        Birliğinde ise muayenenin karşılığı 155,25 TL’dir. Böyle bir durumda
        harcamanız, (teminat bakiyeniz de dikkate alınarak) TTB rakamları olan
        155,25 TL üzerinden değerlendirmeye alınacak ve %75 oranında idesi
        yapılabilecektir.
    </li>
</ul>
<p>
    Yurt dışı vize işlemlerine ilişkin bu bilgiler ışığında, ayrıca bir seyahat
    sağlık sigortası yaptırmak isterseniz, Mercek Talep Sistemi üzerindeki
    Neova Sigorta bölümünden talep girebilirsiniz.
</p>

**Comment by suvenduchhatoi** [comment]
@elaliwat use ```contentContainerStyle={{ flex: 1 }}``` for styling your ```<content> component```
```
import React, { Component } from "react";
import { WebView } from "react-native";
import { Container, Header, Content, Toast, Button, Text } from "native-base";
const SCREEN_HEIGHT = require("Dimensions").get("window").height;
export default class ToastExample extends Component {
  render() {
    return (
      <Container style={{ flex: 1 }}>
        <Header />
        <Content
          style={{ marginHorizontal: 10, marginVertical: 10 }}
          padder
          contentContainerStyle={{ flex: 1 }}
        >
          <WebView
            ref={"webview"}
            style={{ height: SCREEN_HEIGHT }}
            automaticallyAdjustContentInsets={false}
            source={{
              html:
                "<html>" +
                "<h4>Poliçemiz, yurt dışına açıktır ancak, bir seyahat sağlık sigortası değildir. Seyahat sağlık sigortası, teminatlar bazında özel sağlık sigortasından farklı bir poliçedir. Konsolosluklar tarafından talep edilen cenaze teminatı ise en belirgin farklardan biridir. Poliçemizde, yurt dışına çıkışların ilk 60 gününde oluşan sağlık harcamaları, Türk tabipler birliği asgari ücret tarifesindeki rakamlar baz alınarak değerlendirilmektedir. Özel sağlık sigortası poliçemiz yurt dışına açık olmakla birlikte dikkat edilmesi gereken aşağıdaki bazı hususları hatırlatmak isteriz; Sigorta şirketinin yurt dışında herhangi bir hastane ile anlaşması olmadığından provizyon alınamamaktadır. Bu nedenle sağlık harcamaları öncelikle tarafınızca finanse edilmeli ve sonrasında aşağıdaki evrakların İnsan Kaynakları Sağlık bölümüne iletilmesi gerekmektedir. Fatura aslı Şikayet ve tanıyı belirten doktor raporu (İngilizce) Tahlil varsa, istek kağıdı ve sonuç fotokopileri Yapılan ödemelerin iadeleri, Türk Tabipler Birliğince belirlenmiş rakamlar dikkate alınarak, klozlarımızda belirtilen geri ödeme oranlarınca yapılabilmektedir. Örneğin; yurt dışında gerçekleşen bir muayene için ödeyeceğiniz tutar yaklaşık 200 €’dur. Türk Tabipler Birliğinde ise muayenenin karşılığı 155,25 TL’dir. Böyle bir durumda harcamanız, (teminat bakiyeniz de dikkate alınarak) TTB rakamları olan 155,25 TL üzerinden değerlendirmeye alınacak ve %75 oranında idesi yapılabilecektir. Yurt dışı vize işlemlerine ilişkin bu bilgiler ışığında, ayrıca bir seyahat sağlık sigortası yaptırmak isterseniz, Mercek Talep Sistemi üzerindeki Neova Sigorta bölümünden talep girebilirsiniz.Poliçemiz, yurt dışına açıktır ancak, bir seyahat sağlık sigortası değildir. Seyahat sağlık sigortası, teminatlar bazında özel sağlık sigortasından farklı bir poliçedir. Konsolosluklar tarafından talep edilen cenaze teminatı ise en belirgin farklardan biridir. Poliçemizde, yurt dışına çıkışların ilk 60 gününde oluşan sağlık harcamaları, Türk tabipler birliği asgari ücret tarifesindeki rakamlar baz alınarak değerlendirilmektedir. Özel sağlık sigortası poliçemiz yurt dışına açık olmakla birlikte dikkat edilmesi gereken aşağıdaki bazı hususları hatırlatmak isteriz; Sigorta şirketinin yurt dışında herhangi bir hastane ile anlaşması olmadığından provizyon alınamamaktadır. Bu nedenle sağlık harcamaları öncelikle tarafınızca finanse edilmeli ve sonrasında aşağıdaki evrakların İnsan Kaynakları Sağlık bölümüne iletilmesi gerekmektedir. Fatura aslı Şikayet ve tanıyı belirten doktor raporu (İngilizce) Tahlil varsa, istek kağıdı ve sonuç fotokopileri Yapılan ödemelerin iadeleri, Türk Tabipler Birliğince belirlenmiş rakamlar dikkate alınarak, klozlarımızda belirtilen geri ödeme oranlarınca yapılabilmektedir. Örneğin; yurt dışında gerçekleşen bir muayene için ödeyeceğiniz tutar yaklaşık 200 €’dur. Türk Tabipler Birliğinde ise muayenenin karşılığı 155,25 TL’dir. Böyle bir durumda harcamanız, (teminat bakiyeniz de dikkate alınarak) TTB rakamları olan 155,25 TL üzerinden değerlendirmeye alınacak ve %75 oranında idesi yapılabilecektir. Yurt dışı vize işlemlerine ilişkin bu bilgiler ışığında, ayrıca bir seyahat sağlık sigortası yaptırmak isterseniz, Mercek Talep Sistemi üzerindeki Neova Sigorta bölümünden talep girebilirsiniz.</h4>" +
                "</html>",
            }}
          />
        </Content>
      </Container>
    );
  }
}
```
![screen shot 1440-05-08 at 12 59 46 pm](https://user-images.githubusercontent.com/44160581/51100485-519dbc00-17fc-11e9-98b5-838016aecb39.png)
