### ISSUE TITLE
Typescript: when bad prop is entered on Button component, TS doesn't complain

### ISSUE THREAD

**Issue by sanna231** [GeekyAnts/NativeBase#5061]
### Description

When I use the Button component (I'm guessing that's true for other comps), if I enter a bad prop, TS doesn't complain (e.g. loading instead of isLoading). Is that a feature or a bug?

### CodeSandbox/Snack link

https://codesandbox.io/

### NativeBase Version

3.4.5

### Platform

- [X] Android
- [X] CRA
- [X] Expo
- [X] iOS
- [X] Next

**Comment by Viraj-10** [comment]
This issue has been fixed in `v3.4.8`.
