### ISSUE TITLE
Input focusOutlineColor property doesn't work

### ISSUE THREAD

**Issue by JohnBerd** [GeekyAnts/NativeBase#5062]
### Description

focusOutlineColor property of Input component does not work, in the below example it should be black, but it is still in primary color

### CodeSandbox/Snack link

https://codesandbox.io/s/clever-bird-kx7p1x

### NativeBase Version

3.4.3

### Platform

- [ ] Android
- [ ] CRA
- [ ] Expo
- [ ] iOS
- [ ] Next

**Comment by Viraj-10** [comment]
Hi @JohnBerd, It's working for me. you can check [here](https://snack.expo.dev/@viraj_10/input-focusoutlinecolor).

**Comment by JohnBerd** [comment]
Thanks for your quick reply @Viraj-10.

In your example, it seems not working on IOS.

**Comment by otavioq** [comment]
You can try `_focused={{borderColor: 'desiredColor'}}`

**Comment by Viraj-10** [comment]
Hi @JohnBerd, sorry but currently we are finding out a solution for getting this work with IOS and Android. We know this is a difference in Design for native devices and the web. adding `borderWidth` 2px when input is in focus state and 1px when it's normal state causes a shift in layout of 1px when input is focused. react-native still has an issue with `box-shadow`. One solution was to wrap it in a `Box` with a `transparent 1px border` and then change its colour when the state is focused but it is a hack which we might go for if there is no better solution. We are open to discussion.

**Comment by JohnBerd** [comment]
Hi @Viraj-10,

Happy to know it is actually a bug and you are working on it, the @otavioq solution works so maybe it would be a good idea to implement the same behavior for the selectionColor property.

We can maybe let this issue open awaiting for a PR to fix this
