### ISSUE TITLE
Cooldown prop on pressable/button components

### ISSUE THREAD

**Issue by otavioq** [GeekyAnts/NativeBase#5065]
### Description

Add a `cooldown` prop to pressable components to prevent multiple taps

### Problem Statement

Users can tap multiple times rapdly on pressable components and do things we don't want to, e.g. submit a form multiple times, even if we add a loader or navigate to other screen.

### Proposed Solution or API

```
<Button
    cooldown={500} // after the first press, wait 500 ms before user can press again
    onPress={submitForm}
>Submit</Button>
```

### Alternatives

Currently I'm using the `disabled` prop and `setTimeout()` to prevent multiple taps.

`const [isDisabled, setIsDisabled] = useState(false)`

```
const submitForm = () => {
    setIsDisabled(true)
    setTimeout(() => {
        setIsDisabled(false)
    }, 500)  //enable back the button after 500 ms cooldown

    // do something
}
```

```
<Button
    disabled={isDisabled}
    onPress={submitForm}
>Submit</Button>
```

**Comment by Viraj-10** [comment]
Hi @otavioq, you have done this in the right way, as a component library I don't think our vision is currently aligned with adding a cooldown prop. Although we can have an open discussion on this if needed. I'm closing this issue for now feel free to reopen this issue or move this to https://github.com/GeekyAnts/NativeBase/discussions
