### ISSUE TITLE
<Grid> break

### ISSUE THREAD

**Issue by justfede** [GeekyAnts/NativeBase#507]
hey guys!

I want to make a grid with 3 rows per grid but i can't find a way to make "the jump" in the third row. I'm using map for looping in render method. 

For example, i want something like this:

            

             <Grid>
              <Col style={styles.center}>
                <Text>1</Text>
              </Col>
              <Col style={styles.center}>
                <Text>2</Text>
              </Col>
              <Col style={styles.center}>
                <Text>3</Text>
              </Col>
            </Grid>
             <Grid>
              <Col style={styles.center}>
                <Text>1</Text>
              </Col>
              <Col style={styles.center}>
                <Text>2</Text>
              </Col>
              <Col style={styles.center}>
                <Text>3</Text>
              </Col>
            </Grid>

Anyone knows any way to do this?

**Comment by sankhadeeproy007** [comment]
Use `flexWrap: 'wrap'` for `<Grid />` and give the `<Col />`s a width of `~devideWidth/3-10`

**Comment by justfede** [comment]
@sankhadeeproy007 thanks for your answer but i can't make it work. Maybe i'm missing some property for Col?

**Comment by sankhadeeproy007** [comment]
![screen shot 2017-02-14 at 1 07 32 pm](https://cloud.githubusercontent.com/assets/10998047/22919608/cb48db7e-f2b6-11e6-821e-6225a5306a17.png)
Seems to work. Please follow this example.

**Comment by cyclops24** [comment]
@sankhadeeproy007 can you please explain `devideWidth` in above code?
How you extract and use it?

**Comment by GeekRishabh** [comment]
@cyclops24 deviceWidth can be calculated using 

import {Dimensions} from 'react-native'
const deviceWidth = Dimensions.get('window').width;

**Comment by cyclops24** [comment]
Thanks @GeekRishabh,
I think it's a variable in NativeBase 😉

**Comment by GeekRishabh** [comment]
@cyclops24 it's just a variable name that hold the width of the device .
