### ISSUE TITLE
Slider does not work properly

### ISSUE THREAD

**Issue by Great-hijack** [GeekyAnts/NativeBase#5070]
### Description

Slider thumb should follow and be under my finger, but its behavior is weird.

### CodeSandbox/Snack link

https://snack.expo.dev/@zhen-zhu/nativebase-snack

### Steps to reproduce

1. Go to snack. 
2. Press the thumb and move left or right.
3. You will see the thumb is not under your finger.

### NativeBase Version

3.4.6

### Platform

- [ ] Android
- [ ] CRA
- [X] Expo
- [X] iOS
- [ ] Next

**Comment by Krithikj20** [comment]
Hi @Great-hijack, Thank you for the feedback, We will look into it and make sure that the issue is fixed at the earliest.

**Comment by Viraj-10** [comment]
This issue has been fixed in NativeBase `v3.4.7`

**Comment by mikehuebner** [comment]
I'm also having this issue, seems like I have to really try to drag the slider it doesn't stick to my finger. Can support with video if needed.

**Comment by EddyDunda** [comment]
Any updates? This is not working on the last version, too.
