### ISSUE TITLE
As a user, in a modal I should be able unset focus from input fields

### ISSUE THREAD

**Issue by shashank1010** [GeekyAnts/NativeBase#5071]
### Description

When you open the modal for this example
https://snack.expo.dev/@shashank1010/modal-checkbox-click-issue

You would notice that the first field has focus.
In this example, I simulated a vertical space with a height of 500px and then there is a checkbox.
When, the first field has focus and you scroll down to click on the checkbox, modal body scrolls up to the first field.

Also, in this case, after scrolling down, if I click on the modal body itself, even then it scrolls up to the first field.
The example in the doc works beautifully, however, only when there is no scroll.

### Problem Statement

In a modal that has input fields, scrolling and then clicking outside a field scrolls the modal to the last selected field.

### Proposed Solution or API

...
<FocusScope
              contain={visible && props.containScope}
              .
              .
              .
              .
> ... </FocusScope>

### Alternatives

I've tried all possible hacky solutions to resolve this issue, but the field just keeps retaining focus.

### Additional Information

https://snack.expo.dev/@shashank1010/modal-checkbox-click-issue

**Comment by Krithikj20** [comment]
Hi @shashank1010, Thank you for reporting this issue. We will try to fix it at the earliest.

**Comment by Viraj-10** [comment]
Hi @shashank1010, Can you specify the use case for this?
