### ISSUE TITLE
Tabs flickering and longest height issue

### ISSUE THREAD

**Issue by peter1a** [GeekyAnts/NativeBase#508]
When scrolling inside tabs, it starts flickering and all time staying on top - iOS
If changing between tabs and if one tab is longer than another, shorter tab gets also longer height - Android

## react-native, react and native-base version
react-native-0.41.2
native-base-2.0.6

**Comment by sankhadeeproy007** [comment]
Please attach screenshots.

**Comment by sankhadeeproy007** [comment]
@peter1a any updates here?

**Comment by peter1a** [comment]
Upload a video https://vid.me/RTad

**Comment by peter1a** [comment]
Any news about this bug? My app is already in production but customers already told me about this problem..

**Comment by sankhadeeproy007** [comment]
Hi, I've trying but wasn't quite able to reproduce the bug. In the example you can see that I've added two Tabs of varying heights, yet there's no flicker.
![tabs](https://cloud.githubusercontent.com/assets/10998047/23548373/396e7f86-002d-11e7-8a48-46a3b1b7e2e2.gif)

**Comment by peter1a** [comment]
It looks it is problem if i use ListItems if use View works ok.

**Comment by sankhadeeproy007** [comment]
I've tried list here as well 
https://github.com/GeekyAnts/NativeBase/issues/577#issuecomment-283928206

**Comment by peter1a** [comment]
Finnaly found what was problem, always Content component should be inside <Tab> as parent and than everythings work perfect.

**Comment by krunalp1993** [comment]
@peter1a Can you share more information? I am having same issue..

**Comment by masiamj** [comment]
+1

**Comment by rvirani1** [comment]
+1. The scroll height issue is not fixed.

**Comment by ngocdb** [comment]
+1. The scroll height issue is not fixed.

**Comment by shiundu** [comment]
I have the same issue

**Comment by 447491480** [comment]
i have the save issue too

**Comment by IslamTareq0012** [comment]
@peter1a  what do you exactly mean by  "Content component"

**Comment by milk-shake** [comment]
+1 scroll height issue when one tab requires scrolling to the end, the other tabs also can scroll even though the content fits on one screen. Even using <Content> as the tab root component doesn't help.

**Comment by akhil-geekyants** [comment]
![scrollissue](https://user-images.githubusercontent.com/27768184/33074587-b51552c0-ceec-11e7-803e-7116a3f5610a.gif)

**Comment by OogieBoogieInJSON** [comment]
@milk-shake is right. It makes sense to have the <Content> inside the <Tab> because otherwise the the longest tab will stretch the content, meaning all other tabs will have the same height.

**Comment by priyarg** [comment]
i did content inside tab but my whole page is scrolled up  when i go over the list
![image](https://user-images.githubusercontent.com/30672033/34921562-22c5ae7a-f939-11e7-939b-a5c32a6eadc5.png)

**Comment by priyarg** [comment]
i did content inside tab but my whole page is scrolled up when i go over the list
![image](https://user-images.githubusercontent.com/30672033/34921573-4a258580-f939-11e7-884e-b927a0288d9a.png)
![image](https://user-images.githubusercontent.com/30672033/34921580-5dca5818-f939-11e7-8aea-68e5985e09f5.png)

**Comment by akhil-geekyants** [comment]
@priyarg tried a code similar to this. Couldn't find any issue. Attaching a gif

Gif

![list](https://user-images.githubusercontent.com/27768184/34935604-73ee2838-fa04-11e7-8038-e372132eb47d.gif)

**Comment by priyarg** [comment]
Thanks. solved my issue.

**Comment by Zilleabbas10** [comment]
Still getting height isuue in tabs. i have two tabs and my tabs adopt height of the tab which have heighest height. please help, i have implmented almost all solutions either by placing content of tab with in <Content> tag or by passing whole data to Flatlist. your help is appreciated in advance. Thankyou

**Comment by SupriyaKalghatgi** [comment]
@Zilleabbas10 Please check above comments, snippets for help
Also check NativeBase KitchenSink and try replicating your use case there
