### ISSUE TITLE
Error After New Project Creation - Duplicate Box Import

### ISSUE THREAD

**Issue by kunle-e** [GeekyAnts/NativeBase#5082]
### Description

New Project Creation Causes Duplicate Box Import Error

### CodeSandbox/Snack link

Sandbox would be need to be able to run yarn dlx

### Steps to reproduce

- Copy installation instructions for Install in Create React App project from: https://docs.nativebase.io/install-cra
``yarn dlx  create-react-app my-app --template @native-base/typescript``

### NativeBase Version

3.4.0

### Platform

- [ ] Android
- [X] CRA
- [ ] Expo
- [ ] iOS
- [ ] Next

### Other Platform

MacOs

### Additional Information

Two Box components are being imported in App.tsx: 
``import {
  Box,
  Image,
  Text,
  Link,
  HStack,
  Heading,
  Switch,
  useColorMode,
  VStack,
  Box,
} from "native-base";``

Which causes the error below:

ERROR in src/App.tsx:12:3
TS2300: Duplicate identifier 'Box'.
    10 |   useColorMode,
    11 |   VStack,
  > 12 |   Box,
       |   ^^^
    13 | } from "native-base";
    14 |
    15 | function App() {

**Comment by Krithikj20** [comment]
Thank you @kunle-e for reporting the issue. We will look into it.

**Comment by Viraj-10** [comment]
This issue has been fixed.

**Comment by xgenem** [comment]
Issue is still persistent
