### ISSUE TITLE
Icon configuration cannot be set via NativeBaseProvider theme

### ISSUE THREAD

**Issue by chaaya** [GeekyAnts/NativeBase#5083]
### Description

DefaultProps set via theming isnt affecting the Icon.

### CodeSandbox/Snack link

https://snack.expo.dev/WlPtGP6XF

### Steps to reproduce

1. Click "Toggle"
2. The Icon color does not change between dark/light mode
3. Click "Dark/light color theming as from props"
4. Now the Icon color is applied correctly from direct props to the component.

### NativeBase Version

3.4.6

### Platform

- [X] Android
- [ ] CRA
- [ ] Expo
- [X] iOS
- [ ] Next

### Other Platform

react-native-web

**Comment by Krithikj20** [comment]
Hi @chaaya, Thank you for reporting this issue. We will look into it.

**Comment by chaaya** [comment]
@Krithikj20 it was my bad actually, had two provider in the snack I provided. Seems to work.
