### ISSUE TITLE
'props' undefined in Object.renderTab of react-native-scrollable-tab-view

### ISSUE THREAD

**Issue by opaqe** [GeekyAnts/NativeBase#509]
react-native@.0.41.2
react@15.4.2
native-base@2.0.6

Rolling back to 2.0.5 fixes this.

## Steps to reproduce (code snippet or screenshot)
This is the container that renders Tabs, which is a child of Navigator and Drawer components.

```javascript
export default class TabsScreen extends Component {
  render() {
    return (
      <Container theme={myTheme} >
        <Tabs>
          <View>
            <List>
              <ListItem>
                <Text>Item 1</Text>
              </ListItem>
            </List>
          </View>
        </Tabs>
      </Container>
    );
  }
}
```

## Is the bug present in both ios and android or in any one of them?
I'm only using android.

## Bug info
Caught exception:
> Type Error: Cannot read property 'props' of undefined

Edit: Error when turning off debugger
> undefined is not an object (evaluating 'name.props')

Call stack on caught exception: 
```
renderTab (C:\Users\Johnny…able-tab-v…:41)
(anonymous) (C:\Users\Johnny…able-tab-v…:95)
DefaultTabBar_render (C:\Users\Johnny…able-tab-v…:92)
(anonymous) (C:\Users\Johnny…hared\sta…:794)
measureLifeCyclePerf (C:\Users\Johnny…shared\sta…:73)
_renderValidatedComponentWithoutOwnerOrContext (C:\Users\Johnny…hared\sta…:793)
_renderValidatedComponent (C:\Users\Johnny…hared\sta…:820)
performInitialMount (C:\Users\Johnny…hared\sta…:360)
mountComponent (C:\Users\Johnny…hared\sta…:256)
...
```

**Comment by peter1a** [comment]
They were some changes in new version 2.0.6,
``<Tabs>
                <Tab heading="Tab1">
                    <Tab1 />
                </Tab>
                <Tab heading="Tab2">
                    <Tab2 />
                </Tab>
                <Tab heading="Tab3">
                    <Tab3 />
                </Tab>
            </Tabs>``

http://nativebase.io/docs/v2.0.0/components#tabs

**Comment by opaqe** [comment]
Interesting. Can I ask what the rationale was? Is it to customize the tab headers?

**Comment by opaqe** [comment]
Thanks it works as expected!
