### ISSUE TITLE
Button shadow doesn't work

### ISSUE THREAD

**Issue by elenitaex5** [GeekyAnts/NativeBase#5095]
### Description

I'm creating a new variant for a button. I can't find any documentation about that. But I add every single prop for shadow as react native, and nothing happened.

### CodeSandbox/Snack link

https://codesandbox.io/s/infallible-wescoff-ykg0zb

### Steps to reproduce

2. Click on '...' 
3. Scroll down to '...' 

### NativeBase Version

3.4.7

### Platform

- [X] Android
- [ ] CRA
- [ ] Expo
- [X] iOS
- [ ] Next

### Other Platform

Web

**Comment by Krithikj20** [comment]
Hi @elenitaex5, Thank you for reporting the issue. We will look into it.

**Comment by Viraj-10** [comment]
Hi, try using the following code.
```
export const theme = extendTheme({
  components: {
    Button: {
      variants: {
        login: {
          shadow: 8,
          p: 2,
          bg: "primary",
        },
      },
    },
  },
});
```

**Comment by elenitaex5** [comment]
Hi @Viraj-10 it works and shows a shadow, but where can I find how to manage it? Can I change color or where it gonna be more than only a number? or it works like `elevation` for Android?

**Comment by Viraj-10** [comment]
Hi @elenitaex5, you can check shadow prop resolution [here](https://github.com/GeekyAnts/NativeBase/blob/master/src/theme/base/shadows.ts).

**Comment by elenitaex5** [comment]
Thanks for your help @Viraj-10 ! You can remove `awaiting respnse` label too. It works for me perfectly.
