### ISSUE TITLE
Custom fonts are not working

### ISSUE THREAD

**Issue by smontlouis** [GeekyAnts/NativeBase#5097]
### Description

Custom fonts are not working.

It seems like `src/hooks/useResolvedFontFamily.ts` is used to resolve fonts, but `src/theme/styled-system.ts` is using his own fontFamily transformer by resolving  the `fonts` theme key, which returns undefined, since we don't need to transform anything so it finds nothing.

I managed to "fix it" by removing the [transformer](https://github.com/GeekyAnts/NativeBase/blob/3d19108a4c0219a2069aef97d1beafa0efa8b2a9/src/theme/styled-system.ts#L534) in `styled-system.ts`

But it's still not working on Web

### CodeSandbox/Snack link

https://snack.expo.dev/@smontlouis/expo-nativebase

### Steps to reproduce

1. Load fonts
2. Use them in Text

### NativeBase Version

3.4.7

### Platform

- [X] Android
- [X] CRA
- [X] Expo
- [X] iOS
- [ ] Next

**Comment by baselshlewett** [comment]
+1

downgrading to 3.4.6 solved the issue with fonts

**Comment by focux** [comment]
I'm also experiencing this. Downgrading fixed it for me.

**Comment by Viraj-10** [comment]
Hi, Thanks for reporting the issue. We are looking into it.

**Comment by Great-hijack** [comment]
Hi @Viraj-10, I want it to be fixed as soon as possible, it's blocking to publish to live.

**Comment by trymbill** [comment]
Also seeing this, but downgrading didn't seem to fix it.

**Comment by Viraj-10** [comment]
Hi @Great-hijack, We will release a new `rc` for `3.4.8` and by tomorrow we will release stable `3.4.8`

**Comment by teckbeng-payboy** [comment]
@Viraj-10  3.4.8 will be fixing this font issue right?

**Comment by Viraj-10** [comment]
Hi @teckbeng-payboy, Yes we have released a `v3.4.8-rc.0`. you can try it. Will be releasing stable `v3.4.8`.

**Comment by rlfrahm** [comment]
`v3.4.8-rc.0` seems to have fixed this issue for me.

**Comment by Viraj-10** [comment]
This issue has been fixed in `v3.4.8`.
