### ISSUE TITLE
StyleSheet not supported in native-base 2.0.5

### ISSUE THREAD

**Issue by pierredewilde** [GeekyAnts/NativeBase#510]
```
<Icon name="person" style={{fontSize: 30}} />
```

works as expected.

```
<Icon name="person" style={styles.icon} />
...
const styles = StyleSheet.create({
  icon: { 
    fontSize: 30 
  }
});
```
doesn't work and returns the following warning:

```
Invalid prop 'style' of type `number` supplied to `Styled(Icon)`, expected `object`.
```

**Comment by peter1a** [comment]
From docs:
If you have overwritten the styles of NativeBase components in your project using StyleSheet.create(), modify them to plain JavaScript objects. StyleSheet.create() is redundant as it's been called in the source of NativeBase components itself.

http://nativebase.io/docs/v2.0.0/migration

**Comment by pierredewilde** [comment]
Thanks for your feedback. 

The replacement of StyleSheet.create() to plain JavaScript objects works but we loose intellisense support.
