### ISSUE TITLE
Expose/export Tooltip interface

### ISSUE THREAD

**Issue by mathias-berg** [GeekyAnts/NativeBase#5106]
### Description

I would like to be able to import the type for Tooltip to make my own component fully typed.

### Problem Statement

There is not way today to get the interface or type for the Tooltip component since it doesn't seem to be exported like other types are.

### Proposed Solution or API

Export the Tooltip type like you export other types today.

**Comment by Krithikj20** [comment]
Hi @mathias-berg , Thank you for reaching out to us. We will look into it.

**Comment by Viraj-10** [comment]
We have released this in `v3.4.11`
