### ISSUE TITLE
ejectTheme message incorrect, import path no longer valid

### ISSUE THREAD

**Issue by mribbons** [GeekyAnts/NativeBase#511]
## react-native, react and native-base version
react@15.4.2
react-native@0.41.2
native-base@2.0.6

## Expected behaviour
When we run
```node node_modules\native-base\ejectTheme.js```

The message is incorrect.

https://github.com/GeekyAnts/NativeBase/blob/master/ejectTheme.js#L13

## Actual behaviour
Either there should be an index.js in src\theme, or the L13 above should be:
```    'import getTheme from \'./native-base-theme/components';',```

## Is the bug present in both ios and android or in any one of them?
Tested android, must also affect ios

**Comment by sankhadeeproy007** [comment]
The idea is to eject both the components as well as the variable folders. It seems to work fine. What exactly is the problem at your end? Are the folders not getting copied?

**Comment by mribbons** [comment]
Hi,
The folders are copied, the issue is that the eject script message is incorrect:

```import getTheme from './native-base-theme';```

There is no longer an index.js in ./native-base-theme, so the import fails. 

In order to make it work, one has to import from the components folder:

```import getTheme from './native-base-theme/components';```

**Comment by sankhadeeproy007** [comment]
Oops! Sorry. Will be fixed.

**Comment by srhise** [comment]
There is still an issue with the docs, it references the wrong path in the 2.0.0 Customize Docs. It threw me off: 

![image](https://cloud.githubusercontent.com/assets/914113/23487534/c095e41a-feb4-11e6-8c19-916abb6555af.png)

**Comment by mrezzaaa** [comment]
@srhise i think there is no `import getTheme from ` inside `native-base-theme/components` 
@sankhadeeproy007
