### ISSUE TITLE
Select Component: Option to use OS native style picker?

### ISSUE THREAD

**Issue by ongnicolas** [GeekyAnts/NativeBase#5112]
### Description

Hi, I noticed in Android the picker's style is for iOS. Is there a way to use the native android picker??

### Problem Statement

Android shows iOS style picker

![Screenshot_1656436489](https://user-images.githubusercontent.com/66074385/176244090-025bf04f-dc72-48a4-8d2b-c1326d2b91dc.png)

### Proposed Solution or API

option for OS native style picker

**Comment by Krithikj20** [comment]
Hi @madmeatballs, Thank you for reporting it. We will look into this issue.
