### ISSUE TITLE
Broken link for documentation review inside CONTRIBUTING.md

### ISSUE THREAD

**Issue by srkds** [GeekyAnts/NativeBase#5114]
### Description

Documentation review link is broken. It is giving 404. Need to update to new doc repository

### CodeSandbox/Snack link

none

### Steps to reproduce

1. Go to 'CONTRIBUTING.md' 
2. Scroll down to 'ways to contribute and 2nd point' 
3. Click on 'documentation updates'

https://github.com/GeekyAnts/NativeBase/blob/3d19108a4c0219a2069aef97d1beafa0efa8b2a9/CONTRIBUTING.md?plain=1#L27

### NativeBase Version

3.4.7

### Platform

- [ ] Android
- [ ] CRA
- [ ] Expo
- [ ] iOS
- [ ] Next

### Additional Information

Probably this is the correct or updated URL
https://github.com/GeekyAnts/nativebase-docs/pulls

**Comment by Krithikj20** [comment]
Hi @srkds , Thank you for reporting the issue. We will look into it.

**Comment by ankit-tailor** [comment]
Hey @srkds, Thanks for reporting the issue. The link will be fixed in the next release.
