### ISSUE TITLE
toggleColorMode is not working 

### ISSUE THREAD

**Issue by teckbeng-payboy** [GeekyAnts/NativeBase#5121]
### Description

toggleColorMode is not working 

### CodeSandbox/Snack link

-

### Steps to reproduce

2. Click on '...' 
3. Scroll down to '...' 

### NativeBase Version

3.4.7

### Platform

- [X] Android
- [ ] CRA
- [ ] Expo
- [X] iOS
- [ ] Next

### Additional Information

toggleColorMode is not working on the latest stable version

Sample code:
![Screenshot 2022-07-02 at 9 58 40 PM](https://user-images.githubusercontent.com/85466071/177003947-ddb680f0-7ece-479a-96e7-f13323387483.png)

**Comment by Krithikj20** [comment]
Hi @teckbeng-payboy, Thank you for reporting. We will look into it.

**Comment by ankit-tailor** [comment]
Hey @teckbeng-payboy , You've used `useColorMode` hook outside `NativeBaseProvider` and that's the reason you're not able to update the value. Try creating another component and use `useColorMode` hook there and pass that component as a children of `NativeBaseProvider`.
