### ISSUE TITLE
Invalid UIAccessibilityTrait 'alert' when using AlertDialog

### ISSUE THREAD

**Issue by sascha-kaleidoscode** [GeekyAnts/NativeBase#5123]
### Description

I'm using NativeBase in my react native project (created with CRA). Currently I'm working on a small dialog system and ran into this error message: `Invalid UIAccessbilityTrait 'alert'`. The same happens when I'm trying to use the `Switch`-component, but in this case it's not even possible to override the `accessiblityRole` value. Am I missing something or is this erroneous behavior? It is working on device when using the Expo Snack below.

### CodeSandbox/Snack link

https://snack.expo.dev/@sascha_kaleidoscode/2fd6a5

### Steps to reproduce

Use this example on a device running iOS 15.5:
https://docs.nativebase.io/alert-dialog

### NativeBase Version

3.4.6

### Platform

- [ ] Android
- [ ] CRA
- [ ] Expo
- [X] iOS
- [ ] Next

### Additional Information

Testing on iOS 15.5

**Comment by Krithikj20** [comment]
Hi @sascha-kaleidoscode, Thank you for reporting. We will look into this issue.

**Comment by sascha-kaleidoscode** [comment]
I just realized that the error occurs only in combination with another package (@viro-community/react-viro)
So it's not a NativeBase issue. Sorry for the inconvenience.
