### ISSUE TITLE
Show toast does not display styles

### ISSUE THREAD

**Issue by lcsjunior** [GeekyAnts/NativeBase#5124]
### Description

Show toast does not display styles

### CodeSandbox/Snack link

https://codesandbox.io/s/native-base-v3-template-mq6ox

### Steps to reproduce

const toast = useToast();

toast.show({
  title: 'Sign-in Failed',
  status: 'warning',
  variant: 'subtle',
  placement: 'top',
  description: error.response.data.error_description,
});

**Status, variant and more no longer work.**

### NativeBase Version

3.4.6

### Platform

- [ ] Android
- [ ] CRA
- [ ] iOS
- [ ] Next
- [X] Expo

**Comment by Krithikj20** [comment]
Hi @lcsjunior, Thank you for reporting this issue. We will look into it.

**Comment by ankit-tailor** [comment]
Hey @lcsjunior , Status and Variant props are deprecated from [v3.4.0](https://github.com/GeekyAnts/NativeBase/releases/tag/v3.4.0). Here is the [recipe](https://docs.nativebase.io/toast#h3-status--variant-recipes) for that.
