### ISSUE TITLE
Input outline onFocus has no border radius [IOS]

### ISSUE THREAD

**Issue by czerewacz** [GeekyAnts/NativeBase#5133]
### Description

When using Input component from mobile browsers like Safari or Chrome on IOS, you can see that the highlighted outline has no border radius to match Input radius

### CodeSandbox/Snack link

https://docs.nativebase.io/input

### Steps to reproduce

1. Go to https://docs.nativebase.io/input from mobile Safari or Chrome on IOS device.
2. Click on Basic Input example demo
3. You will see the outlined box with no radius.
<img width="346" alt="Screenshot 2022-07-07 at 11 22 07" src="https://user-images.githubusercontent.com/65304538/177739732-6f2e5da3-4689-465b-85ca-ed49cfc43951.png">

### NativeBase Version

3.4.7

### Platform

- [ ] Android
- [ ] CRA
- [ ] Expo
- [X] iOS
- [ ] Next

**Comment by Krithikj20** [comment]
Hi @czerewacz, Thank you for reporting this issue. We will try to fix it at the earliest.
