### ISSUE TITLE
Custom Fonts Not Working on Web

### ISSUE THREAD

**Issue by markwindsorr** [GeekyAnts/NativeBase#5136]
### Description

Custom fonts not working on web even on 3.4.8

### CodeSandbox/Snack link

Custom fonts not working on web even on 3.4.8

### Steps to reproduce

2. Click on '...' 
3. Scroll down to '...' 

### NativeBase Version

3.8.4

### Platform

- [ ] Android
- [x] CRA
- [ ] Expo
- [ ] iOS
- [ ] Next

**Comment by Viraj-10** [comment]
Hi @markwindsorr, Can you provide a snack link?

**Comment by markwindsorr** [comment]
https://snack.expo.dev/@markwindsorr/nativebase-template

**Comment by rohit0621** [comment]
Hey @markwindsorr , I've tried reproducing the issue. [Here](https://snack.expo.dev/m6WIH3PWb) is the snack link. I am using latest version `3.4.9`. It's working for me. Let me know if it works for you.

**Comment by codaDevDan** [comment]
Also having this issue for web using 3.4.7.

**Comment by Viraj-10** [comment]
Hi @codaDevDan, Please check @rohit0621 snack link and please upgrade your version. feel free to reopen this issue.
