### ISSUE TITLE
missed line of code in last version 

### ISSUE THREAD

**Issue by nimajnsr** [GeekyAnts/NativeBase#5137]
### Description

export { StyledProps } from './types';

### CodeSandbox/Snack link

/null

### Steps to reproduce

in react application

node_modules/native-base/lib/module/theme/index.js

should has this line 
export { StyledProps } from './types';

### NativeBase Version

3.4.8

### Platform

- [ ] Android
- [ ] CRA
- [ ] Expo
- [ ] iOS
- [ ] Next

### Other Platform

react js

### Additional Information

in react application

node_modules/native-base/lib/module/theme/index.js

should has this line 
export { StyledProps } from './types';

**Comment by nimajnsr** [comment]
**Failed to compile.**
./node_modules/native-base/lib/module/index.js
Attempted import error: 'StyledProps' is not exported from './theme'.

please fix that just by adding  
**export { StyledProps } from './types';**
into lib/module/theme/index.js

**Comment by nimajnsr** [comment]
just sent a pull request for fixing the issue 
[](https://github.com/GeekyAnts/NativeBase/pull/5139)

**Comment by Krithikj20** [comment]
Thank you @nimajnsr for reporting. We will look into it.

**Comment by exneval** [comment]
@Krithikj20 please merge pr #5139 to fix the compile failure

**Comment by Viraj-10** [comment]
Hi @exneval, We have fixed this issue and released new rc `v3.4.9-rc.0`
