### ISSUE TITLE
`Menu.ItemOption` does not provide access to `Box` wrapping children

### ISSUE THREAD

**Issue by Swiftwork** [GeekyAnts/NativeBase#5138]
### Description

Without access to Box there is no way to have children take up 100% of the parent space and therefore cannot right align icons.

### CodeSandbox/Snack link

https://snack.expo.dev/@swiftwork/menu-item-option-no-box-access

### Steps to reproduce

Affected line:
https://github.com/GeekyAnts/NativeBase/blob/master/src/components/composites/Menu/MenuItemOption.tsx#L49

### NativeBase Version

3.4.8

### Platform

- [X] Android
- [X] CRA
- [X] Expo
- [X] iOS
- [X] Next

**Comment by Krithikj20** [comment]
Hi @Swiftwork, Thank you for reporting the issue. We will look into it.

**Comment by ankit-tailor** [comment]
Hey @Swiftwork, This issue is fixed in `v3.4.11`.
