### ISSUE TITLE
Can't start KitchenSink using QR code shown in readme

### ISSUE THREAD

**Issue by obasille** [GeekyAnts/NativeBase#5141]
### Description

I'm getting a "EXNetwork error 403" in ExpoGo when trying to run the KitchenSink on my iPhone

### CodeSandbox/Snack link

https://github.com/GeekyAnts/nativebase#8-kitchensink-app

### Steps to reproduce

1. Go to readme's KitchnSink [section](https://github.com/GeekyAnts/nativebase#8-kitchensink-app)
2. Scan the Expo Go QR code on with the iPhone camera
3. Expo Go opens and displays a 403 error

### NativeBase Version

3.3.1

### Platform

- [ ] Android
- [ ] CRA
- [X] Expo
- [X] iOS
- [ ] Next

**Comment by Krithikj20** [comment]
Thank you @obasille, Thank you for reporting this issue. We will look into it.

**Comment by obasille** [comment]
I've also tried the "KitchenSink-app-native-base" [Expo Dev link](https://expo.dev/@geekyants/kitchensink-app-native-base) for Android. It starts an app but I only get a splash screen on my Android phone.

Got the link from the "nativebase-v3-kitchensink" [readme](https://github.com/GeekyAnts/nativebase-v3-kitchensink#running-it-on-android).

Let me know if I should create another issue.

**Comment by ankit-tailor** [comment]
Hey @obasille , Due to restrictions imposed by Apple, Expo publish link or QR does not work on IOS unless the user logged into the expo go app with the same credentials used when published.

**Comment by obasille** [comment]
Thanks @ankit-tailor, indeed I've just tried on a Android phone and got it to run on ExpoGo with the QR code :)
