### ISSUE TITLE
Button.Group throws error if Button is conditionally rendered inside

### ISSUE THREAD

**Issue by Looooong** [GeekyAnts/NativeBase#5144]
### Description

Button.Group throws error if Button is conditionally rendered inside.

### CodeSandbox/Snack link

https://snack.expo.dev/@looooooooong/button-group-null-bug

### Steps to reproduce

1. Go to Snack link.

### NativeBase Version

3.4.8

### Platform

- [ ] Android
- [ ] CRA
- [X] Expo
- [ ] iOS
- [ ] Next

### Additional Information

This happens when one of the group's children is `null`.

**Comment by Krithikj20** [comment]
Thank you @Looooong for reporting this issue. We will look into it.

**Comment by ankit-tailor** [comment]
Hey @Looooong, This issue is fixed in `v3.4.11`.
