### ISSUE TITLE
[Web] Heading font size is not specified for md breakpoint

### ISSUE THREAD

**Issue by Looooong** [GeekyAnts/NativeBase#5165]
### Description

At md breakpoint, heading uses default font size.

### CodeSandbox/Snack link

https://snack.expo.dev/@looooooooong/heading-font-size-bug

### Steps to reproduce

1. Go to Snack link 
2. Open Snack preview in a separate popup window.
3. Resize popup window's width to md breakpoint.
4. Look at the size of the heading.

### NativeBase Version

3.4.8

### Platform

- [ ] Android
- [ ] CRA
- [X] Expo
- [ ] iOS
- [ ] Next

### Additional Information

This bug seems to be introduced since version 3.3.0.

**Comment by ankit-tailor** [comment]
Hey @Looooong , Thanks for reporting the issue. We will fix it.

**Comment by ankit-tailor** [comment]
Hey @Looooong, This issue is fixed in `v3.4.11`.
