### ISSUE TITLE
Can't conditionally display children in Popover.Content

### ISSUE THREAD

**Issue by SamMcDuffie** [GeekyAnts/NativeBase#5170]
### Description

Render Error occurs if you're trying to conditionally display children inside Popover.Content if the condition is false 

### CodeSandbox/Snack link

https://codesandbox.io/s/popover-content-error-6s2o4z?file=/src/App.tsx

### Steps to reproduce

1. Go to [sandbox](https://codesandbox.io/s/popover-content-error-6s2o4z?file=/src/App.tsx)
2. Click the button in the view
3. See error. 

The error doesn't persist if `body` is provided.

### NativeBase Version

3.4.4

### Platform

- [ ] Android
- [ ] CRA
- [X] Expo
- [X] iOS
- [ ] Next

### Additional Information

The [line](https://github.com/GeekyAnts/NativeBase/blob/f6051ab60a9108917492f92f827021fd7469edf6/src/components/composites/Popover/PopoverContent.tsx#L56) causing the issue

**Comment by ankit-tailor** [comment]
Hey @SamMcDuffie , Thanks for reporting the issue. We'll fix it soon.

**Comment by ankit-tailor** [comment]
Hey @SamMcDuffie, This issue is fixed in `v3.4.11`.
