### ISSUE TITLE
[Docs] One example in the docs for the Input component results in weird behavior on iOS

### ISSUE THREAD

**Issue by ErykDarnowski** [GeekyAnts/NativeBase#5171]
### Description

The problem is with using `onPress` on the `Icon` component. This causes a dark background to appear behind the icon when it's pressed on an iOS device. In order to fix this issue the `Icon` component needs to be wrapped in a `Pressable` / `IconButton` (with this one also something along the lines of `bg: 'none'` has to be set on `_pressed`) component which than has the `onPress` prop (instead of the `Icon` component).

### CodeSandbox/Snack link

https://docs.nativebase.io/input#h3-input-elements

### Steps to reproduce

1. Go to URL
2. See error

### NativeBase Version

3.4.8

### Platform

- [ ] Android
- [ ] CRA
- [ ] Expo
- [X] iOS
- [ ] Next

**Comment by ankit-tailor** [comment]
Hey @ErykDarnowski, Thanks for your suggestions. We'll fix it soon.

**Comment by ankit-tailor** [comment]
Hey, This issue is fixed in `v3.4.11`.
