### ISSUE TITLE
Components not rendering  in react-native version 0.41.2

### ISSUE THREAD

**Issue by blaziken105** [GeekyAnts/NativeBase#521]
I am using native-base version: native-base@0.5.22
react-native version: 0.41.2
react: 15.4.2

I am trying to render tabs as shown in the given example: http://nativebase.io/docs/v2.0.0/components#tabs

My code is as follows
`
import React, { Component } from 'react';
import { Container, Header,Content, Tab, Tabs } from 'native-base';
import Profile from './Profile';
import Posts from './Posts';
export default class ProfileRoot extends Component {

render(){
 return (
     <Container>
     <Header hasTabs />
     <Tabs>
         <Tab heading="Profile">
             <Profile />
         </Tab>
         <Tab heading="Posts">
             <Posts />
         </Tab>
     </Tabs>
     </Container>
 );
 }
}`

I get the error: Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in. Check the render method of ProfileRoot.

I have export default class in both Posts and Profile and the render method contains just a button which works fine when I run it separately without the tabs.

What is really weird is that when I try any of the other examples such as the radio button(http://nativebase.io/docs/v2.0.0/components#radioButton) searchBar(http://nativebase.io/docs/v2.0.0/components#searchBar). All of these end up giving me the same error as above, Is it a breaking change in version 0.41.2?

The buttons work fine so does the spinner and thumbnail. Most other components end up giving me the above error. I get the same error on both the ios and android. What seems to be the problem here?

**Comment by sankhadeeproy007** [comment]
You're on native-base version 0.5.22. And the examples are of version 2.0.x. I'd recommend upgrading native-base
