### ISSUE TITLE
Unable to render MacOS native select using Select.

### ISSUE THREAD

**Issue by sanna231** [GeekyAnts/NativeBase#5212]
### Description

While using React Native for macOS. I am using the NativeBase library which works very good. I am using the select component however it is rendering a sliding sheet. I am hoping to use the looks from the web view as if you was on Mac.

Reference GitHub discussion: https://github.com/GeekyAnts/NativeBase/discussions/5108

### CodeSandbox/Snack link

https://codesandbox.io

### Steps to reproduce

2. Click on '...' 
3. Scroll down to '...' 

### NativeBase Version

3.4.8

### Platform

- [ ] Android
- [ ] CRA
- [ ] Expo
- [X] iOS
- [ ] Next

**Comment by ankit-tailor** [comment]
Hey @sanna231, Select renders native select component on web and on other platforms it renders actionsheet. Thanks for reporting the issue. We'll fix it.

**Comment by ankit-tailor** [comment]
Hey, This issue is fixed in `3.4.14` version.
