### ISSUE TITLE
ActionSheet's onClose handling by swiping down doesn't update with the new state

### ISSUE THREAD

**Issue by hohoaisan** [GeekyAnts/NativeBase#5216]
### Description

The same issue as https://github.com/GeekyAnts/NativeBase/issues/4692 but it's closed. 

### CodeSandbox/Snack link

https://snack.expo.dev/@hohoaisan/9eb3f4

### Steps to reproduce

1. Go to https://snack.expo.dev/@hohoaisan/9eb3f4
2. Click 'Actionsheet' button to open the Actionsheet.
3. Tap "Delete" button and close Actionsheet by tapping on Overlay. Then you should see alert with "Delete".
4. Open the Actionsheet again
5. Tap "Share" button and close Actionsheet by swiping down the Actionsheet.
6. You'll see the alert but it says "Delete" instead of "Share"

### NativeBase Version

3.4.9

### Platform

- [X] Android
- [ ] CRA
- [ ] Expo
- [X] iOS
- [ ] Next

**Comment by Krithikj20** [comment]
Thank you @hohoaisan for reporting this issue. We will look into it.

**Comment by ankit-tailor** [comment]
Hey, Thanks for reporting the issue. This issue is fixed in `v3.4.13`.
