### ISSUE TITLE
Help in understanding breakpoint measurements with mobile phones.

### ISSUE THREAD

**Issue by GollyJer** [GeekyAnts/NativeBase#5217]
### Description
_(I don't think this is a bug but it's not a feature request either)_

`windowWidth`, and thus `breakpoints`, for iPhone 7 nearly identical to Pixel 6 Pro 

### Steps to reproduce

We're working through a complete rewrite of our app with nativebase to take advantage of many of its benefits, but the main reason is the responsive breakpoints.

I'm testing on an old, small iPhone 7, a new high-density Pixel 6 Pro, and a new iPad.
I fully expected the iPhone and the Pixel to be completely different breakpoints.

- iPhone 7
750 x 1334 pixels, 16:9 ratio (~326 ppi density)
- Pixel 6 Pro
1440 x 3120 pixels, 19.5:9 ratio (~512 ppi density)

After looking at the source, I saw 
`const windowWidth = useWindowDimensions()?.width;`
is used to determine the widths.

Here are the results from each phone.
```bash
iPhone:  
NativeBase breakpoint ==> base 
windowWidth ==> 375

Android
NativeBase breakpoint ==> base 
windowWidth ==> 411
```

Both of these phones break at `base`. And more surprisingly, they are very close to one another in windowWidth.

So, it's challenging to correctly size things with the breakpoint because things show up significantly larger on the lower density iPhone 7.

How should we approach this? I realize we could make the `sm`  breakpoint between 375 and 411 to break the phones into different breakpoints, but I'm not confident that's a good solution.

Hoping someone on the NativeBase team can help us think through how to work with significantly different density phones when it seems they are actually very close together from a windowWidth perspective.

Thanks!

### NativeBase Version

3.4.1

### Platform

- [X] Android
- [ ] CRA
- [ ] Expo
- [X] iOS
- [ ] Next

**Comment by ankit-tailor** [comment]
Hey @GollyJer , NativeBase provides these default breakpoints and you can update by using extendTheme.
```
const theme = extendTheme({
    breakpoints: {
      base: 0,
      sm: 400,
      md: 700,
    },
  });
```

[Here](https://docs.nativebase.io/next/breakpoints) you can read more about it

**Comment by GollyJer** [comment]
Hi @ankit-tailor. Thanks for the help.
I've read the documentation and the source code **thoroughly**.

The real point of my question is **how these two phones can measure so closely together**?
NativeBase is using **`windowWidth`** to determine breakpoints.

    iPhone 7
    750 x 1334 pixels (326 PPI density)
    windowWidth  ==> 375 👈
    
    Pixel 6 Pro
    1440 x 3120 pixels (512 PPI density)
    windowWidth  ==> 411 👈

These phones are 7 years apart, and the Pixel is nearly twice the screen density as the iPhone but measures only ~10% larger in **`windowWidth`**.

How do you guys handle breakpoints for this situation? Is this typical?

**Comment by GollyJer** [comment]
OK, so digging into this more, I understand now that 
`const windowWidth = useWindowDimensions()?.width` is returning the DP, aka Density-Independent Pixels.
so really it's more like...
`const dp = useWindowDimensions()?.width` 

For those playing along...

- [Good summary of pixel density for ios, android, web](https://material.io/design/layout/pixel-density.html#pixel-density)
- [How do dp, dip, dpi, ppi, pixels and inches relate?](https://stackoverflow.com/questions/8478882/how-do-dp-dip-dpi-ppi-pixels-and-inches-relate)

So I'm thinking the answer is to use tighter breakpoints to scale down to smaller phones.

These are the default breakpoints...
https://github.com/GeekyAnts/NativeBase/blob/2af374e586034366dcefce9a0f23983836a7901f/src/theme/base/breakpoints.ts
```javascript 
const breakpoints = {
  'base': 0,
  'sm': 480,
  'md': 768,
  'lg': 992,
  'xl': 1280,
  '2xl': 1536,
};
```

```javascript 
breakpoints: {
    base: 0,
    sm: 376, // 👈 for small DP phones.
    md: 480,
    lg: 768,
    xl: 992,
    '2xl': 1280,
    '3xl': 1536,
  },
```

**Comment by GollyJer** [comment]
My previous idea of creating and renaming breakpoints is a BAD idea.
In testing... simply just renaming breakpoints caused weird things to happen, like the app rerendering randomly.

In the end we had to settle for just changing the sizes of the default breakpoints.
```javascript 
export const ExtendedNativeBaseTheme = extendTheme({
  breakpoints: {
    base: 0, // 0-374 dp
    sm: 376, // 375-479 dp
    md: 481, // 480-767 dp
    lg: 769, // 768-991 dp
    xl: 993, // 992-1279 dp
    '2xl': 1281, // 1280 dp and up
  },
```

**Comment by namlq93** [comment]
![Capture](https://user-images.githubusercontent.com/41458989/184219383-e3ec9297-6ecc-4039-82ad-49a32d5f0536.PNG)
I want to set styles only on the `base` screen. How can I do that? Your example applies to all 3 screens: `direction={['column', 'column', 'row']}`

**Comment by GollyJer** [comment]
> 

I think you may have posted in the wrong thread.

**Comment by usmaniqbal998** [comment]
native base measure responsiveness with respect to width . what if we want to measure it with respect to height of device ? how would that work ? what if I want to add breakpoints according to device height ?
