### ISSUE TITLE
Ref not working for Floating input

### ISSUE THREAD

**Issue by sankhadeeproy007** [GeekyAnts/NativeBase#522]

**Comment by sankhadeeproy007** [comment]
Please check #483

**Comment by carlosl** [comment]
I'm having this same issue actually, does not seem to be fixed. The onChange from #483 is working fine but if I try to ref the `<Input ref='foo' />` using `this.refs.foo._root` it return undefined when `floatingLabel` is set as a prop on `<Item />`.

Works:
```
<Item>
  <Label>Foo</Label>
  <Input ref='bar' />
</Item>

console.log(this.refs.bar._root) 
// returns Object()
```

Doesn't work:
```
<Item floatingLabel>
  <Label>Foo</Label>
  <Input ref='bar' />
</Item>

console.log(this.refs.bar._root) 
// return undefined
```

Basically I need this so I can set focus on the next Input ( ie. this.refs.foo._root.focus() )

**Comment by sankhadeeproy007** [comment]
Please check [this](https://github.com/GeekyAnts/NativeBase/issues/483#issuecomment-280073175)

**Comment by r3mariano** [comment]
I'm having the same issue as @carlosl on native-base@2.0.8.

**Comment by sankhadeeproy007** [comment]
Did you check the above link and try out the solution?

**Comment by r3mariano** [comment]
The last comments in that link was about someone having trouble with an Input in an Item without floatingLabel, and that seems to work.

The problem is that when I add floatingLabel to the item, the Input's ref stops working.

**Comment by sankhadeeproy007** [comment]
cc @shivrajkumar

**Comment by shivrajkumar** [comment]
Try `getRef` instead of `ref`

**Comment by sergio9104** [comment]
I have the same problem, fix please

**Comment by naman03malhotra** [comment]
@shivrajkumar how to use ```getRef``` can you please give an example for floatingLabel

**Comment by naman03malhotra** [comment]
It was a headache but finally found the solution.

```export default class SignUpForm extends Component {

  _focusInput(inputField) {
    this[inputField]._root.focus();
  }
  render() {
    return (
      <View>
        <Form style={styles.form}>
          <Item floatingLabel style={styles.item}>
            <Label>Mobile Number</Label>
            <Input
              keyboardType='numeric'
              returnKeyType='next'
              getRef={(input) => this.mobileInput = input}
              onSubmitEditing={() => this._focusInput('passwordInput')}
            />
          </Item>
          <Item floatingLabel style={styles.item}>
            <Label>Create Password</Label>
            <Input
              secureTextEntry={true}
              returnKeyType='next'
              getRef={(input) => this.passwordInput = input}
              onSubmitEditing={() => this._focusInput('emailInput')}
            />
          </Item>
...........

**Comment by ReyHaynes** [comment]
@naman03malhotra's solution verified working.
Was losing my mind trying to find the solution...thanks!

```
react-native-cli: 2.0.1
react-native: 0.49.5
react: 16.0.0-beta.5
```

**Comment by r3wt** [comment]
proposed solution doesn't work for android.
