### ISSUE TITLE
Custom Theme Type Warning

### ISSUE THREAD

**Issue by sanna231** [GeekyAnts/NativeBase#5224]
### Description

So I’m creating a custom theme object for NativeBase and inside of it I am adding some extra properties like “backgroundColor”. Later when accessing these properties through useTheme() the code works, but I get a type warning. Is there a way to silence them? In reality the prop is there and my code works absolutely fine.. its only a type warning.

### CodeSandbox/Snack link

NA

### Steps to reproduce

2. Click on '...' 
3. Scroll down to '...' 

### NativeBase Version

3.4.9

### Platform

- [X] Android
- [X] CRA
- [X] Expo
- [X] iOS
- [X] Next

**Comment by ankit-tailor** [comment]
Hey @sanna231, Thanks for reporting the issue. We'll look into it.

**Comment by surajahmed** [comment]
This issue is fixed in version `3.4.6` or later.
@sanna231  Can you please have look at this documentation for typing custom theme https://docs.nativebase.io/typescript?
Please feel free to reopen.
