### ISSUE TITLE
Why request only object style on component (NativeBase 2)?

### ISSUE THREAD

**Issue by alex-kakashi** [GeekyAnts/NativeBase#525]
Hi! Thanks for trying out NativeBase!
For v2, I not happy for once to change index style (StyleSheet) to object. And I cannot use array style on component NativeBase v2.

## react-native, react and native-base version
    "native-base": "2.0.7",
    "react": "15.4.2",
    "react-native": "0.41.2"
## Expected behaviour
I want set style component with StyleSheet and array style.

## Actual behaviour
Show log warning failed prop type Invalid prop 'style',  expected 'object'.
 
## Steps to reproduce (code snippet or screenshot)
```
import React, { Component } from 'react';
import { 
  Container, Header, Title, 
  Content, Text, Body
} from 'native-base';

export default class TestComponent extends Component {

    render() {
        return(
            <Container>
                <Header>
                    <Body>
                        <Title>Test</Title>
                    </Body>
                </Header>
                <Container>
                    <Text style={styles.a1}>A1</Text>
                    <Text style={StyleSheet.flatten([styles.a1])}>A2</Text>
                    <Text style={[styles.a1,styles.a2]}>A3</Text>
                </Container>
            </Container>
        );
    }
}
const styles = StyleSheet.create({
    a1: { backgroundColor: '#00ff00'},
    a2: { marginLeft: 10}
});

```

## Screenshot of emulator/device
![simulator-screen-shot-feb-16 -2560-be -4 52 06-pm](https://cloud.githubusercontent.com/assets/3070756/23016728/162e8af8-f46a-11e6-80ad-d617f4d7d3e1.png)
![simulator-screen-shot-feb-16 -2560-be -5 03 27-pm](https://cloud.githubusercontent.com/assets/3070756/23016729/17c9bf04-f46a-11e6-926a-c4c645c50f58.png)

## Is the bug present in both ios and android or in any one of them?
I tried on simulator iOS.

## Any other additional info which would help us debug the issue quicker.
If you disable protect style props on component I can use StyleSheet or array style.
Thank you.

**Comment by sankhadeeproy007** [comment]
Please check #510

**Comment by alex-kakashi** [comment]
Thanks for your feedback.
