### ISSUE TITLE
Box, Skeleton, and other components do not contain type definitions for "variant" prop

### ISSUE THREAD

**Issue by vasafix** [GeekyAnts/NativeBase#5255]
### Description

Box, Skeleton, and other components do not contain type definitions for the "variant" prop, even though if the "variant" prop is defined in "extendTheme" it is still applied.

### CodeSandbox/Snack link

https://snack.expo.dev/@krygelv/native-base-variant

### Steps to reproduce

run `tsc`

### NativeBase Version

3.4.11

### Platform

- [ ] Android
- [ ] CRA
- [ ] Expo
- [ ] iOS
- [ ] Next

**Comment by ankit-tailor** [comment]
Hey @vasafix, Thanks for reporting the issue. We'll look into it.

**Comment by hirvesh** [comment]
Hey guys! Any progress on this? 😄

**Comment by ankit-tailor** [comment]
Yes, We are working on it. It will be fixed in the next release.

**Comment by ankit-tailor** [comment]
Hi Everyone, This issue is fixed in `3.4.14`.

**Comment by SrBrahma** [comment]
Thanks!
