### ISSUE TITLE
Button.Group display is different from the demo?  

### ISSUE THREAD

**Issue by ng520tx** [GeekyAnts/NativeBase#5258]
### Description

Button.Group display is different from the demo?  

### Problem Statement

![2022-08-09 185226](https://user-images.githubusercontent.com/7404231/183630921-7ac1a4dd-d082-4c10-80b5-b73fd5e16c14.png)

![2022-08-09 185706](https://user-images.githubusercontent.com/7404231/183631671-13e327be-bd76-4b93-9c69-adfea1c71239.png)

### Proposed Solution or API

<Button.Group isAttached>
        <Button>button1</Button>
        <Button variant="outline">button2</Button>
</Button.Group>

**Comment by ankit-tailor** [comment]
Hey @ng520tx , Thanks for reporting the issue. We'll look into it.

**Comment by ankit-tailor** [comment]
Hey @ng520tx @Rutger, This issue is fixed in `3.4.12`.
