### ISSUE TITLE
connectStyle is undefined

### ISSUE THREAD

**Issue by niros001** [GeekyAnts/NativeBase#526]
Hi i used native-base v2.0.7 and when i try to import connectStyle i allways got 'undefined'
`import {connectStyle} from 'native-base'`

**Comment by sankhadeeproy007** [comment]
Why would you import connectstyle though?

**Comment by niros001** [comment]
I just follow your example.. i need to use StyleSheet theme with native base theme

**Comment by niros001** [comment]
Anyway i need to use somehow the RN StyleSheet but it ignore the styles

**Comment by sankhadeeproy007** [comment]
Okay, looking into it.

**Comment by niros001** [comment]
Thanks

**Comment by sankhadeeproy007** [comment]
@shivrajkumar The docs [here](http://nativebase.io/docs/v2.0.0/customize#themeyours) shows `connectstyle` being imported. But it isn't exported from index.js. Can you please take a look?

**Comment by niros001** [comment]
Hmm i see, so you mean i can not import the `connectsyle`?
So how can i use the StyleSheet?

**Comment by sankhadeeproy007** [comment]
Yes we can import. Will fix it in the next release.

**Comment by niros001** [comment]
Ok thanks!

**Comment by shivrajkumar** [comment]
@niros001 For now you can `import { connectStyle } from '@shoutem/theme';`

**Comment by niros001** [comment]
I check it now

**Comment by niros001** [comment]
Ok i import that `connectStyle` that get 4 parameters but iam not sure how to use it without the `StyleProvider`

**Comment by sankhadeeproy007** [comment]
Fixed with 2.0.8

**Comment by sankhadeeproy007** [comment]
![screen shot 2017-02-20 at 11 04 52 pm](https://cloud.githubusercontent.com/assets/10998047/23136687/e6fb2478-f7c3-11e6-829e-7dc081c1debe.png)
Here's how to use `connectStyle`
