### ISSUE TITLE
isHowered in pressable component doesnot work in android

### ISSUE THREAD

**Issue by codefromrvk** [GeekyAnts/NativeBase#5265]
### Description

Not able to see style changes when hovering over pressable component

### CodeSandbox/Snack link

https://snack.expo.dev/@0xrvk/f8d22b

### Steps to reproduce

1. Go to the snack link
2. Click on Android
3. Try hovering over the card
4. Hover effect does not work

### NativeBase Version

3.4.0

### Platform

- [X] Android
- [ ] CRA
- [ ] Expo
- [ ] iOS
- [ ] Next

**Comment by Viraj-10** [comment]
Hi @codefromrvk, Native Devices doesn't have a hover event. It is web-specific.
