### ISSUE TITLE
How to change `contentContainerStyle` global?

### ISSUE THREAD

**Issue by danilvalov** [GeekyAnts/NativeBase#528]
How to change `contentContainerStyle` for `Content` component for the whole of my project?
Now I need to add the prop `contentContainerStyle` to any `Content` in each screen.

**Comment by shivrajkumar** [comment]
You can create your own `CustomContent` from `Content` with the required `contentContainerStyle` and use it wherever you need in your project

**Comment by danilvalov** [comment]
@shivrajkumar 
Ok, thank you. This solution is suitable for me.
