### ISSUE TITLE
Arrow Forward Icon issue

### ISSUE THREAD

**Issue by PragyaSingla** [GeekyAnts/NativeBase#5284]
### Description

After updating native-base to 3.4.13, arrow forward icon is getting cropped.

### CodeSandbox/Snack link

https://snack.expo.dev/Rz0f7tZ9g

### Steps to reproduce

In below image, icon is getting cropped from right.

![image](https://user-images.githubusercontent.com/16425199/185564784-d8c7963b-2fbd-4950-a408-b16168255218.png)

Code Snippet:

`            
<Button
   size={'lg'}
   variant={'outline'}
    rightIcon={<ArrowForwardIcon size="5" />}
    onPress={() => onNextQuestion()}>
                Next
</Button>
`

### NativeBase Version

3.4.13

### Platform

- [X] Android
- [ ] CRA
- [ ] Expo
- [X] iOS
- [ ] Next

**Comment by Viraj-10** [comment]
Hi @PragyaSingla, Thanks for reporting this issue. We will fix it soon.

**Comment by PragyaSingla** [comment]
Thanks @Viraj-10  for consideration. Let me know once PR would be merged.

**Comment by ankit-tailor** [comment]
Hey @PragyaSingla, This issue is fixed in `3.4.14`.
