### ISSUE TITLE
System color mode doesn't react to changes

### ISSUE THREAD

**Issue by focux** [GeekyAnts/NativeBase#5286]
### Description

When you set `useSystemColorMode` to true, if you start the app, it does use the system color mode as the initial theme but once you toggle the system color mode, it doesn't react to those changes. You gotta quit and re-open the app in order for it to work.

### CodeSandbox/Snack link

N/A

### Steps to reproduce

1. Enable `useSystemColorMode` on your config
2. Start your app
3. Toggle the system appearance

### NativeBase Version

3.4.13

### Platform

- [X] Android
- [ ] CRA
- [X] Expo
- [X] iOS
- [ ] Next

**Comment by Viraj-10** [comment]
Hi @focux, can you provide a snack link?

**Comment by Viraj-10** [comment]
Hi @Rutger, Can you provide a snack link?

**Comment by Rutger** [comment]
> Hi @Rutger, Can you provide a snack link?

Sure! I've added a Snack link to my original issue: https://github.com/GeekyAnts/NativeBase/issues/5260#issuecomment-1222439062
