### ISSUE TITLE
React native CLI and native base Unable to  resolve dependency tree

### ISSUE THREAD

**Issue by mohammadbrzbrz72** [GeekyAnts/NativeBase#5298]
### Description

I can't install native base in my react-native project

### CodeSandbox/Snack link

https://codesandbox.io

### NativeBase Version

3.4.x

### Platform

- [X] Android
- [ ] CRA
- [ ] Expo
- [X] iOS
- [ ] Next

### Additional Information

```
mohammad@Mohammads-MacBook-Air begginerproject % npm i native-base
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: begginerproject@0.0.1
npm ERR! Found: react@18.0.0
npm ERR! node_modules/react
npm ERR!   react@"18.0.0" from the root project
npm ERR!   peer react@"*" from native-base@3.4.13
npm ERR!   node_modules/native-base
npm ERR!     native-base@"*" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^18.2.0" from react-dom@18.2.0
npm ERR! node_modules/react-dom
npm ERR!   peer react-dom@"*" from native-base@3.4.13
npm ERR!   node_modules/native-base
npm ERR!     native-base@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/mohammad/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mohammad/.npm/_logs/2022-08-24T06_07_58_818Z-debug-0.log
```

## package.json
```
{
  "dependencies": {
      "@react-native-async-storage/async-storage": "^1.17.9",
      "react": "18.0.0",
      "react-native": "0.69.4",
      "react-native-navigation": "^7.30.0-alpha",
      "react-native-sqlite-storage": "^6.0.1",
      "tailwindcss-react-native": "^1.7.10"
  }
```

**Comment by mohammadbrzbrz72** [comment]
The issue fix by this command:  :D

npm in --save native-base --force

**Comment by Viraj-10** [comment]
Hi @mohammadbrzbrz72, This Issue is caused after Node v16.14 and later. for now please try with node v16.13 using nvm.

**Comment by bjtu1133** [comment]
> Hi @mohammadbrzbrz72, This Issue is caused after Node v16.14 and later. for now please try with node v16.13 using nvm.

That does not work form me, I tried 16.13 and 15.14, same error.

**Comment by leighton-tidwell** [comment]
> Hi @mohammadbrzbrz72, This Issue is caused after Node v16.14 and later. for now please try with node v16.13 using nvm.

This worked for allowing me to get past the `npm i` problems.

**Comment by zanyar3** [comment]
> The issue fix by this command: :D
> 
> npm i native-base --force

Not fixed for me

**Comment by Viraj-10** [comment]
Hi All, Please refer https://github.com/GeekyAnts/NativeBase/issues/5308#issuecomment-1238033635 for this issue.
