### ISSUE TITLE
Input loses focus when updating state.

### ISSUE THREAD

**Issue by twelvearrays** [GeekyAnts/NativeBase#53]
I am using React Naive 0.27.2 with nativebase 0.4.7, I am having trouble using the input component. 

As you can see, I am trying to update the state on the input on onChangeText, but when I update the state the focus is lost from the input component.  Is there another way to use the input component to get the value from it onSubmit? 

edit: 
Also TextInput is working correctly, if I substitute it for the input component. 

-----

`import {Container, Header, Content, Button, Title, List, ListItem, InputGroup, Input, Icon} from 'native-base';
import React, {Component} from 'react';
import {TextInput, View} from 'react-native';

export default class Login extends Component {

  constructor() {
      super();
      this.state = {user: '', pw: undefined};
  }

    userNameUpdate(event){

      this.props.actions.createUser(this.state.username, '1234')
    }

    render() {
      const {login} = this.props

        return (
            <Container>
            
                <Content>

                        <InputGroup>
                               <Input
                                 placeholder="USERNAME"
                                 value={this.state.user}
                                 onChangeText={(username) => this.setState({username})}/>
                               </InputGroup>

                           <InputGroup>
                               <Icon name="ios-unlock" />
                               <Input
                                 placeholder="PASSWORD"
                                 secureTextEntry={true}
                                 value={(this.state && this.state.pw) || ''}
                                 onChangeText={(password) => this.setState({pw: password})}/>
                           </InputGroup>

                       <Button style={{margin:5}} onPress={() => this.userNameUpdate()} block> Login </Button>

                </Content>

            </Container>
        );
    }
}
`

**Comment by TimBroddin** [comment]
having the same issue

**Comment by sankhadeeproy007** [comment]
Yes it's a bug. Will be fixed my monday/tuesday.

**Comment by himanshu-sahusoft** [comment]
Fixed in v0.4.8

**Comment by TimBroddin** [comment]
Thanks!

**Comment by k2glyph** [comment]
I am still facing this issue.

**Comment by anil1712** [comment]
Yes I am also facing the same issue in **"native-base": "2.3.3"**

**Comment by anil1712** [comment]
@twelvearrays you got any solution for the same?

**Comment by SupriyaKalghatgi** [comment]
@k2glyph @anil1712 Facing this issue with 2.3.6?

**Comment by anil1712** [comment]
@SupriyaKalghatgi  Yes, its happening in 2.3.6 also.
Please check the attached gif

**Keyboard gets disappeared**

<img src="http://tinyurl.com/yaqd9ra8"/>

**Comment by anil1712** [comment]
@SupriyaKalghatgi 
FYI: I am using this for `Form` component
https://github.com/nicolaslopezj/simple-react-form

**Comment by SupriyaKalghatgi** [comment]
#1518
