### ISSUE TITLE
Component variants not applying text color from baseStyle or defaultProps

### ISSUE THREAD

**Issue by dlombardi** [GeekyAnts/NativeBase#5302]
### Description

Component variants are not applying `color` prop. If you look at the [NativeBase documentation for variants](https://docs.nativebase.io/customizing-components#h2-customizing-base-style) you can even experiment with applying a variant to the Text example with a color and it won't be applied.

### CodeSandbox/Snack link

https://docs.nativebase.io/customizing-components#h2-customizing-base-style

### Steps to reproduce

Just look at the native-base customizing-components documentation section for an example.  Emerald text color is not being applied.

### NativeBase Version

3.4.13

### Platform

- [ ] Android
- [ ] CRA
- [X] Expo
- [ ] iOS
- [ ] Next

**Comment by dlombardi** [comment]
I've also discovered the same thing applies to `padding` or `p` for input variants.  The `p` value is not being applied

**Comment by dlombardi** [comment]
Also seeing that `_filledTrack` is no longer working with the `Progress` component

**Comment by dlombardi** [comment]
This is happening with Expo SDK 46 BTW!

**Comment by Viraj-10** [comment]
This issue is fixed in `v3.4.14`.
