### ISSUE TITLE
Solito native base ts template with Link functionality broken

### ISSUE THREAD

**Issue by bidah** [GeekyAnts/NativeBase#5314]
### Description

can't navigate to user screen with default setup

### CodeSandbox/Snack link

https://snack.expo.dev/@mdrehman/nativebase-template

### Steps to reproduce

1. clone https://github.com/GeekyAnts/nativebase-templates.git  
2. cd solito-universal-app-template-nativebase-typescript
3. yarn install
4. yarn native
5. open IOS simulator
6. click on `Open User Details`

### NativeBase Version

3.3.7

### Platform

- [ ] Android
- [ ] CRA
- [ ] Expo
- [x] iOS
- [ ] Next

### Additional Information

![simulator_screenshot_590F4684-9A45-4E73-AA1D-3E7EA795D96D](https://user-images.githubusercontent.com/1574028/187489791-0ebd54e7-a657-450e-b49d-43a9c3ad45e8.png)

**Comment by ankit-tailor** [comment]
Hey @bidah, This [PR](https://github.com/GeekyAnts/nativebase-templates/pull/64) will fix this issue.
