### ISSUE TITLE
unique "key" prop warning in the Avatar.Group

### ISSUE THREAD

**Issue by nikgraf** [GeekyAnts/NativeBase#5316]
### Description

When using the Avatar.Group you get this warning: Warning: Each child in a list should have a unique "key" prop.

### CodeSandbox/Snack link

https://codesandbox.io/s/headless-night-jgqqlc?file=/src/App.tsx

### Steps to reproduce

1. Open the page
2. Open the console and see the warning.

### NativeBase Version

3.4.13

### Platform

- [ ] Android
- [ ] CRA
- [ ] Expo
- [ ] iOS
- [ ] Next

### Other Platform

web

**Comment by ankit-tailor** [comment]
Hey @nikgraf, Thanks for reporting the issue. We'll fix it.

**Comment by ankit-tailor** [comment]
Hey @nikgraf, This issue is fixed in `3.4.14`.

**Comment by nikgraf** [comment]
great thanks 👏👏👏

now just need to wait until native-base works with the latest react-native-web version :)
