### ISSUE TITLE
Change to TouchableHighlight dropped `this.props`

### ISSUE THREAD

**Issue by Vishalashah** [GeekyAnts/NativeBase#532]
## react-native, react and native-base version
react-native v0.41.2
react v15.4.2
native-base v2.0.7

## Expected behaviour
When an ListItem height and width are modified, TouchableHighlight should adhere to the same dimensions

## Actual behaviour
TouchableHighlight is not inheriting the width and height assigned to ListItem

## Steps to reproduce (code snippet or screenshot)
NA

## Screenshot of emulator/device
NA

## Is the bug present in both ios and android or in any one of them?
Only tested on iOS

## Any other additional info which would help us debug the issue quicker.
NA

**Comment by sankhadeeproy007** [comment]
Thanks for reporting! Will be looked into

**Comment by sankhadeeproy007** [comment]
![list](https://cloud.githubusercontent.com/assets/10998047/23115300/f51d837a-f769-11e6-9429-79d42c63d13e.gif)
I just tested it out and notice that it does inherit the height. Only the width is ignored. That is actually the desired effect as lisitems usually span the width of the device.
