### ISSUE TITLE
Cannot remove outline line on focus in Input component

### ISSUE THREAD

**Issue by elenitaex5** [GeekyAnts/NativeBase#5324]
### Description

I've done everything possible to change Input default props with theme. Mostly of elements have changed but input in fact have been created with a <View> around it with its same size. It <View> has an outline when input is focused (viewed in the inspector as a <div>) and nothing remove it.

### CodeSandbox/Snack link

https://codesandbox.io/s/javascript-forked-96v69s?file=/index.js

### Steps to reproduce

To reproduce this error you only needs an input in your app or storybook.

### NativeBase Version

^3.4.7

### Platform

- [ ] Android
- [ ] CRA
- [ ] Expo
- [ ] iOS
- [ ] Next

### Other Platform

Storybook web

### Additional Information

Tried in many ways of putting down outline. Last one has been:
` outlineColor: 'transparent',
   outlineStyle: 'none',
   outlineWidth: 0,`
   
   and still appearing blue outline

**Comment by ankit-tailor** [comment]
Hey @elenitaex5, You need to pass that inside the `_stack` pseudo prop as this outline is being applied on `Stack` internally. Let me know if this works for you.

```js
Input: {
  variants: {
    outline: {
      _focus: {
        borderWidth: '0',
        _stack: {
          style: {
            outlineWidth: '0',
            boxShadow: 'none',
          },
        },
      },
    },
  },
},
```

**Comment by ankit-tailor** [comment]
Closing this issue for now, let me know if this works for you. Feel free to re-open it if you have any doubts.

**Comment by elenitaex5** [comment]
Ok thanks! it finally works for me thanks!
