### ISSUE TITLE
Styling different from components page

### ISSUE THREAD

**Issue by RWOverdijk** [GeekyAnts/NativeBase#533]
Version: native-base@2.0.7

Installing nativebase and not doing anything weird besides copying code from the components page gives me something that doesn't at all look like what the examples page shows.

<img width="487" alt="screenshot 2017-02-18 21 03 14" src="https://cloud.githubusercontent.com/assets/781745/23096480/b5b9486a-f61d-11e6-8068-2da4ddc1a3e7.png">

```jsx
class App extends Component {
  render() {
    return (
      <Container>
        <Content>
          <Card>
            <CardItem header>
              <Text>NativeBase</Text>
            </CardItem>

            <CardItem>
              <Body>
              <Text>
                Something totally not offensive.
              </Text>
              </Body>
            </CardItem>
            <CardItem footer>
              <Text>GeekyAnts</Text>
            </CardItem>
          </Card>
        </Content>
      </Container>

    )
  }
}
```

**Comment by sankhadeeproy007** [comment]
I think you should add a Header. The demo was for card and the card looks fine. You're missing the header.

**Comment by RWOverdijk** [comment]
@sankhadeeproy007 I had the header before, that's not the issue.

In any case, to me, the card does **not** look fine. Compare it to the gif and you'll notice the differences in margins.

**Comment by shivrajkumar** [comment]
@RWOverdijk You need to give `padder` prop to `<Content>`

**Comment by RWOverdijk** [comment]
Thank you. That helps.

Where are the docs by the way? I found some mistakes (missing commas etc)
