### ISSUE TITLE
Unable to resolve "use-subscription" from "node_modules\native-base\src\core\color-mode\hooks.tsx"

### ISSUE THREAD

**Issue by goxr3plus** [GeekyAnts/NativeBase#5334]
### Description

Unable to resolve "use-subscription" from "node_modules\native-base\src\core\color-mode\hooks.tsx"

### CodeSandbox/Snack link

Just go from version 3.4.13 to 3.4.14

### Steps to reproduce

Just go from version 3.4.13 to 3.4.14

### NativeBase Version

3.4.14

### Platform

- [X] Android
- [ ] CRA
- [X] Expo
- [ ] iOS
- [ ] Next

### Additional Information

Already described above

![image](https://user-images.githubusercontent.com/20374208/189297118-20d30768-3657-4e8a-9dbd-cbcbd7bdf5f5.png)

**Comment by Viraj-10** [comment]
Hi @goxr3plus, Please delete and re-install node_modules. We have added some new dependencies.

**Comment by atanaskanchev** [comment]
> Hi @goxr3plus, Please delete and re-install node_modules. We have added some new dependencies.

Getting the same error even after a clean install

**Comment by NensiKasundra** [comment]
Yes getting the same issue with the react-native 0.70 project and react-native-reanimated 3.0.0-rc.2

**Comment by NensiKasundra** [comment]
@Viraj-10  in which version can you please mention here? as I'm using this with react-native 0.70 and native-base 3.4.14

**Comment by ankit-tailor** [comment]
@NensiKasundra , It's fixed in `3.4.15`.
