### ISSUE TITLE
Dynamic height of Input

### ISSUE THREAD

**Issue by amanthegreatone** [GeekyAnts/NativeBase#535]
Hi,

Is it possible to make the height of the Input dynamic. I have set multiline={true} but the height of the Input should be dynamic based on the content.

RN 0.40.0
React 0.15.2
Native-Base 2.0.7

**Comment by sankhadeeproy007** [comment]
That is not something we're supporting with NativeBase yet.

**Comment by amanthegreatone** [comment]
any hacks?

**Comment by amanthegreatone** [comment]
found the way to do it...this is there in the textinput example in RN docs
add this to the Input (declare the height in the constructor state)

```
onContentSizeChange={(event) => {
    this.setState({height: event.nativeEvent.contentSize.height});
}}
style={{height: Math.max(35, this.state.height)}}
```

**Comment by sankhadeeproy007** [comment]
Thank you!
