### ISSUE TITLE
Form Item floatingLabel option overrides child elements.

### ISSUE THREAD

**Issue by robertasg** [GeekyAnts/NativeBase#536]
This has been fixed in earlier version of NativeBase, but once again is screwed up.

Passing floatingLabel or stackedLabel option to Input component overrides the children and renders the Input element instead.

I'd say it's a bad practice to override child elements, as this might cause unexpected and hard-to-debug behavior. In my case, it replaced a redux-form Field component. Keep in mind that people may be using higher-level components that wrap your Input component. Overriding them removes the flexibility of your framework.

I can make a merge request to fix this if required.

**Comment by sankhadeeproy007** [comment]
Yes indeed. Overriding components is not the best option. However for the label floating animation. We've had to overrride the components. A fix would be greatly appreciated!
