### ISSUE TITLE
react-native-svg 13.2.0 Breaks Icon Color

### ISSUE THREAD

**Issue by enchorb** [GeekyAnts/NativeBase#5372]
### Description

See Below

### CodeSandbox/Snack link

N/A

### Steps to reproduce

The color that is passed into the Native Base <Icon /> component works fine with `react-native-svg` versions `13.1.0` and below but the latest `13.2.0` update causes all colors to be incorrect (ie. muted.400 went from being a light grey to light red)

### NativeBase Version

3.4.15

### Platform

- [X] Android
- [ ] CRA
- [ ] Expo
- [X] iOS
- [ ] Next

**Comment by Viraj-10** [comment]
Hi @enchorb, seems like an issue is from `react-native-svg` https://github.com/react-native-svg/react-native-svg/issues/1875.
Please downgrade to `13.1.0`
