### ISSUE TITLE
Pressable component is missing variant property

### ISSUE THREAD

**Issue by Jirijancik** [GeekyAnts/NativeBase#5377]
### Description

When I tried to style Pressable component for my footer, typescript gave me warning that: Property 'variant' does not exist on type 'IntrinsicAttributes & InterfacePressableProps ...

### CodeSandbox/Snack link

https://codesandbox.io/s/exciting-colden-x5prjf

### Steps to reproduce

1. Use Pressable component
2. Try to add:  variant="footer" to it
3. See error

### NativeBase Version

3.4.0

### Platform

- [ ] Android
- [ ] CRA
- [X] Expo
- [ ] iOS
- [ ] Next

### Additional Information

The only way for me to style it is to change base styles, but that is not what we would prefer. It would be sweet to be able to use this generic component to the fullest wit the theme provider.

<img width="686" alt="image" src="https://user-images.githubusercontent.com/40243099/190970058-8c8638a3-d307-4d70-a269-00e9ea786f10.png">

**Comment by Viraj-10** [comment]
Hi @Jirijancik, This issue is fixed in version `3.4.16`. Thanks for reporting this.
