### ISSUE TITLE
Upgrade NativeBase to version 2

### ISSUE THREAD

**Issue by acamenhas** [GeekyAnts/NativeBase#538]
Hi all!

I've a problem with the tab component (need to be fix on top when the user scrolls) and i read that it was fixed in version 2.

What's the best way to upgrade my NativeBase 0.5.22 to version 2?

I've changed the version in package.json but it doesnt work :(

Thanks!

**Comment by peter1a** [comment]
First check if there are new packages available with **npm outdated**, if they are use **npm update** to update all old packages with new one, also check dependencies.

**Comment by GeekRishabh** [comment]
@acamenhas before upgrading NB checkout the [compatibility](https://docs.nativebase.io/docs/Compatibility.html) and upgrade the react and RN package too .
 you can follow the step from [here]( http://nativebase.io/docs/v2.0.0/migration)
