### ISSUE TITLE
How to change text style in FormControl.ErrorMessage

### ISSUE THREAD

**Issue by luluhoc** [GeekyAnts/NativeBase#5397]
### Description

How to change text style in FormControl.ErrorMessage cause fontsize prop isn't working for me.

### Problem Statement

How to change text style in FormControl.ErrorMessage cause fontsize prop isn't working for me.

### Proposed Solution or API

.

**Comment by Viraj-10** [comment]
Hi @luluhoc, Please pass `fontSize` in `_text` like shown below.  
`<FormControl.ErrorMessage leftIcon={<WarningOutlineIcon size="xs" />} _text={{fontSize:'sm'}}>`
Closing this issue please feel free to reopen it.
