### ISSUE TITLE
How do I size cards

### ISSUE THREAD

**Issue by Jan-Jan** [GeekyAnts/NativeBase#54]
Thank you for NativeBase!

I would like to know the best way to do Card layouts. Maybe 2 cards next to each other, or even 3. At the moment it looks like a CardItem fills a row.

**Comment by Jan-Jan** [comment]
I'm using `Row` and `Col`, but if feels a bit hacky.

**Comment by sankhadeeproy007** [comment]
`Row` and `Col` uses proper flex attributes. So it's fine to use them for layouts.
