### ISSUE TITLE
The "size" props in Thumbnail is not working in v2.0.8

### ISSUE THREAD

**Issue by gameboyVito** [GeekyAnts/NativeBase#540]
After upgrading to v2.0.8, the "size" props in Thumbnail is not working. The size of Thumbnail always stays in the same size, no matter what number I set to it.

To reproduce this issue, just use the Thumbnail component like below:
```
<Container>
      <Content>
           <Text>Circular Thumbnail</Text>
           <Thumbnail size={80} source={require('./img/two.png')} />
      </Content>
</Container>
```

**Comment by sankhadeeproy007** [comment]
Hi, the size prop has been deprecated in 2.0.8. You can now pass the desired with and height with the `style` property. Will be updated in the docs.

**Comment by gameboyVito** [comment]
In my case, I need to set the shape of Thumbnail into a circle, but only setting the width and height is not enough. I guess maybe the borderRadius of the source code hasn't been handled correctly?

When the width = height = 100
![image](https://cloud.githubusercontent.com/assets/16020361/23152252/c84f02c4-f83b-11e6-922f-ab69d348c965.png)

When the width = height = 40
![image](https://cloud.githubusercontent.com/assets/16020361/23152249/b94d6ee6-f83b-11e6-8dc0-09701f42269d.png)

**Comment by sankhadeeproy007** [comment]
Yes, you'll need to specify a borderRadius of half the width/height as well. Thanks for pointing out. Will be updated in the docs.

**Comment by gameboyVito** [comment]
Thank you. It works!

**Comment by gameboyVito** [comment]
Hi, I still have one problem. How to add borderWidth to the Thumbnail? I try to set {borderWidth: 1, borderColor: 'grey', width: 50, height: 50, borderRadius: 25}, but no border show up.

**Comment by sankhadeeproy007** [comment]
With the placeholder image you have, I doubt a gray border would be visible. Try a different color please.

**Comment by gameboyVito** [comment]
![image](https://cloud.githubusercontent.com/assets/16020361/23152861/f0892964-f83f-11e6-9479-ae80cb59f9e2.png)

```
cardThumbNail: {
        width: width * 0.12,
        height: width * 0.12,
        borderRadius: width * 0.12 / 2,
        borderWidth: 5,
        borderColor: '#000'
    },
```

Still nothing happen...

**Comment by sankhadeeproy007** [comment]
Can you try it out on a regular image and check? I think this is a react-native issue

**Comment by superquest** [comment]
@sankhadeeproy007 `size` attribute is still in the docs: https://docs.nativebase.io/COMPONENTS.html#List_Thumbnail
