### ISSUE TITLE
The Tabs bar won't show up on version 2.0.8

### ISSUE THREAD

**Issue by mochamadArif** [GeekyAnts/NativeBase#541]
The tabs bar won't show up, but the content and swipe works fine.
I faced this issue after I migrate from version 2.0.6. Am I missing something on the current documentation?

**Comment by sankhadeeproy007** [comment]
Here is the updated docs for [Tabs](http://nativebase.io/docs/v2.0.0/components#tabs)!

**Comment by mochamadArif** [comment]
Thank you, I follow step by step from the docs, but I still can't figure out how to solve this issue.
![Screenshot 1](http://i.imgur.com/0PvBF9K.jpg?1)
I think there is nothing wrong on my code.
```javascript
<Drawer
	ref={(ref) => { this._drawer = ref; }}
	content={<SideMenu />}
	styles={drawerStyles}
	onClose={() => this.closeDrawer()}
	tweenHandler={(ratio) => ({
		main: { opacity:(2-ratio)/2 }
	})}>
	<StyleProvider style={getTheme(material)}>
		<Container>
			<Header hasTabs />
			<Tabs>
				<Tab heading="Heading 1">
					<Button><Text>Button 1</Text></Button>
				</Tab>
				<Tab heading="Heading 2">
					<Button><Text>Button 2</Text></Button>
				</Tab>
			</Tabs>
		</Container>
	</StyleProvider>
</Drawer>
```
But if I wrap `<Tabs>` with `<Content>`, the tab bar will showing up look like this
![Screenshot 2](http://i.imgur.com/vD1Nfy8.jpg?1)

**Comment by sankhadeeproy007** [comment]
Use from master if urgent. Has been fixed.

**Comment by mochamadArif** [comment]
Thank you very much! You really saved my day 👍

**Comment by svallen** [comment]
I grabbed the master and that worked.  Having used npm call hadn't been working earlier this morning.  

Thanks!

**Comment by weiliank** [comment]
But i am getting this error : `"Invariant Violation"` with this description below even after i using the latest master github repo. Any idea? I tried googling around but i can't find any possible solution.

"Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object. Check the render method of `ResumeHome`."

**Comment by peter1a** [comment]
What about bug with flickering and height problem? #508

**Comment by maiduchuy** [comment]
It seems that neither using master nor `2.0.9` works for me, only reverting to `2.0.6` works.

**Comment by sankhadeeproy007** [comment]
Please check #548

**Comment by maiduchuy** [comment]
@sankhadeeproy007 Thanks, re-ejecting the variables works!

**Comment by weiliank** [comment]
@maiduchuy mind share your steps on doing the ejecting? :)

**Comment by maiduchuy** [comment]
I ran `node node_modules/native-base/ejectTheme.js` as suggested in #548. If you are not sure about what it does then have a look at [this](http://nativebase.io/docs/v2.0.0/customize#themingNativeBaseApp). I keep my theme in a separate file so I only needed to look at the diffs and add them to my current theme file (which initially based on material.js)

**Comment by sankhadeeproy007** [comment]
Good to know it works!
