### ISSUE TITLE
Status bar icons are in black. Also many styles seem to be off. 

### ISSUE THREAD

**Issue by georgemickael-b** [GeekyAnts/NativeBase#543]
"native-base": "^2.0.8",
"react": "15.4.2",
"react-native": "0.41.2"

**Comment by uxman-sherwani** [comment]
Facing same issue.

**Comment by georgemickael-b** [comment]
@uxman-sherwani 
Fixed it by doing the following.

1. Run node node_modules/native-base/ejectTheme.js , you would get native-base-theme folder in root.

2. import material from './native-base-theme/variables/material'; 
    import {StyleProvider,getTheme) from 'native-base'

3. Wrap the the Container with StyleProvider like,
      <StyleProvider style={getTheme(material)}>
            <Container> .... </Container>
      </StyleProvider>
