### ISSUE TITLE
Swipe Up functionality for DeckSwiper?

### ISSUE THREAD

**Issue by blaziken105** [GeekyAnts/NativeBase#544]
Hi I am using the NativeBase DeckSwiper. The docs show two methods onSwipeLeft and onSwipeRight. Is there any support for a swipeUp method similar to what tinder has on its super like, if so how do I use the callback?

**Comment by sankhadeeproy007** [comment]
There is no vertical swiping support as of now for DeckSwiper. We might add it sometime in the future.
