### ISSUE TITLE
Checkbox text label does not update

### ISSUE THREAD

**Issue by bradencanderson** [GeekyAnts/NativeBase#5444]
### Description

`Checkbox` does not re-render when its string children update.

### CodeSandbox/Snack link

https://snack.expo.dev/pjAFSZn2x

### Steps to reproduce

1. Click "HI".
2. The label on the checkbox should increment to "Count: 1".
3. See error; the label stays as "Count: 0".

https://user-images.githubusercontent.com/5060341/194176414-ac5e4c26-2824-48a2-bb48-982988350f74.mov

### NativeBase Version

3.4.17

### Platform

- [ ] Android
- [ ] CRA
- [X] Expo
- [ ] iOS
- [ ] Next

### Other Platform

ios, android

**Comment by Viraj-10** [comment]
Hi @bradencanderson, This issue is fixed in version `v3.4.18`.
