### ISSUE TITLE
Tab headers not showing with native base

### ISSUE THREAD

**Issue by svallen** [GeekyAnts/NativeBase#546]
Native Base 2.0.8
React Native 14.0.0

Tabs are not showing properly.

![screen shot 2017-02-21 at 8 25 18 am](https://cloud.githubusercontent.com/assets/6169781/23166769/e2d93abe-f80f-11e6-9b3f-24dceb18d979.png)

**Comment by sankhadeeproy007** [comment]
Fixed in #541

**Comment by sankhadeeproy007** [comment]
Fixed with v2.0.9
