### ISSUE TITLE
When using redux within a Modal, we lose access to the Context that redux uses, causing failures.

### ISSUE THREAD

**Issue by justinmwarner** [GeekyAnts/NativeBase#5460]
### Description

In my example Snack, you can see I'm using a useSelector within a native-base Modal component. This causes a failure.

### CodeSandbox/Snack link

https://snack.expo.dev/@justinwarner/nativebase-template

### Steps to reproduce

In the Snack, click the button and notice the errors.

### NativeBase Version

^3.2.1

### Platform

- [ ] Android
- [ ] CRA
- [X] Expo
- [ ] iOS
- [ ] Next

### Additional Information

I think a Portal will help here, which could all be controlled by native-base internally.

**Comment by Viraj-10** [comment]
Hi @justinmwarner, Thanks for reporting an Issue. We will look into it.

**Comment by Viraj-10** [comment]
Hi @justinmwarner, put your provide outside `NativebaseProvider`.
Modal works like React Portal. for more understanding you can read this [blog](https://nativebase.hashnode.dev/how-the-overlay-component-works-in-nativebase)
```
 <Provider store={store}>
      <NativeBaseProvider>
        <Example />
      </NativeBaseProvider>
  </Provider>
```
