### ISSUE TITLE
Radio Button cannot be put inside a flexDirection: 'row' View

### ISSUE THREAD

**Issue by kn4rfy** [GeekyAnts/NativeBase#547]
Radio button before can be put side by side inside a flexDirection: 'row' View

Actual code:

          <View style={{flexDirection: 'row'}}>
            <ListItem selected={false}>
                <Text>Lunch Break</Text>
                <Right>
                  <Radio selected={false} />
                </Right>
            </ListItem>
            <ListItem selected={true}>
                <Text>Discussion with Client</Text>
                <Right>
                    <Radio selected={true} />
                </Right>
            </ListItem>
          </View>

## react-native@0.41.2, react@15.4.2 and native-base@2.0.6
<img width="567" alt="screen shot 2017-02-21 at 10 11 56 pm" src="https://cloud.githubusercontent.com/assets/13697282/23168940/e6a260b0-f884-11e6-8711-df246586dd34.png">

## react-native@0.41.2, react@15.4.2 and native-base@2.0.8
<img width="568" alt="screen shot 2017-02-21 at 10 14 13 pm" src="https://cloud.githubusercontent.com/assets/13697282/23168963/faa4e312-f884-11e6-8370-3a9ab663e55c.png">

**Comment by sankhadeeproy007** [comment]
![screen shot 2017-02-22 at 12 09 06 pm](https://cloud.githubusercontent.com/assets/10998047/23199989/c2cee906-f8f7-11e6-85de-6663fb5d6e7a.png)
You can try removing the `<Right />` tag and use it like the example given here.

**Comment by kn4rfy** [comment]
That's what I am doing now. Hopefully I can use it without adding more styles in the future

**Comment by sankhadeeproy007** [comment]
Yes, we'll try to fix this with future releases.
