### ISSUE TITLE
[IOS/ANDROID] - Font are not working correctly.

### ISSUE THREAD

**Issue by Kivylius** [GeekyAnts/NativeBase#5475]
### Description

The fonts dont seem to work on android or ios, copied the example from the docs

### CodeSandbox/Snack link

https://snack.expo.dev/@nh104263/font-broken?platform=web

### Steps to reproduce

1. Go to '[ling](https://snack.expo.dev/@nh104263/font-broken?platform=web)' 
2. Click on 'ios/android' 
3. Scroll down to 'see fonts not working as execpted' 

### NativeBase Version

3.4.17

### Platform

- [X] Android
- [ ] CRA
- [ ] Expo
- [X] iOS
- [ ] Next

### Additional Information

Web:

<img width="301" alt="Screen Shot 2022-10-14 at 15 08 13" src="https://user-images.githubusercontent.com/1041335/195867420-11b14c34-b738-4879-94d4-158ae126a9f9.png">

IOS/ANDROID

<img width="491" alt="Screen Shot 2022-10-14 at 14 59 21" src="https://user-images.githubusercontent.com/1041335/195867213-f1ff40ee-ea9a-4c87-881f-fcea8c893dd5.png">

**Comment by Viraj-10** [comment]
Hi @Kivylius, I made a few corrections to yours.  you can see them [here](https://snack.expo.dev/@viraj_10/loading-font-example?platform=web). closing this issue. feel free re-open it.

**Comment by Kivylius** [comment]
Thank you.  We need the `NativeBaseProvider` not be conditionals rendered.

**Comment by Viraj-10** [comment]
> Thank you. We need the `NativeBaseProvider` not be conditionals rendered.

Hi @Kivylius, even if you remove that it will work.

**Comment by Kivylius** [comment]
It seems on first load, the font are still not displaying correctly, after a refresh it works ok.

<img width="327" alt="Screen Shot 2022-10-18 at 10 42 06" src="https://user-images.githubusercontent.com/1041335/196396516-32e96338-6c8f-4a1e-9f56-4312443422ae.png">
