### ISSUE TITLE
DeckSwiper swipe on button press not working

### ISSUE THREAD

**Issue by blaziken105** [GeekyAnts/NativeBase#549]
My problem is  in reference to the issue here https://github.com/GeekyAnts/NativeBase/issues/416 
I want to click a button and the action of it would cause the deck swiper move to the next item in the deck. I have followed the instructions in the above link, it doesn't seem to work
    
      `<DeckSwiper`
                  ref={(ds) => {this.deckSwiper = ds;}}
                  dataSource={cards}
                  onSwipeLeft={this.callLeftSwipe}
                  onSwipeRight={this.callRightSwipe}
                  renderItem={item =>

                        <Card style={{ elevation: 3 }}>
                            <CardItem>
                                <Left>
                                    <Thumbnail source={item.image} />
                                </Left>
                                <Body>
                                    <Text>{item.text}</Text>
                                    <Text note>NativeBase</Text>
                                </Body>
                            </CardItem>
                            <CardItem cardBody>
                                    <Text style={{ width: screenWidth, height: screenheight }}>Cool</Text>
                                    <TouchableOpacity  onPress={() => {
                                      this.setCurrentItem(item);
                                      this.setModalVisible(true,item)
                                      }} >
                                     <Image style={{ resizeMode: 'cover', width: screenWidth, height: screenheight }} source={item.image} />
                                    </TouchableOpacity>

                                    </CardItem>
                            <CardItem>
                                <Icon onPress={() => this.deckSwiper.swipeRight()} name="md-thumbs-up" style={{ color: '#ED4A6A' }} />
                                <Text>{item.name}</Text>
                            </CardItem>
                        </Card>
                      }
                />` 

P.S I have noticed that I can access the props of the deckSwiper and call the custom methods I have written for handling a swipe such as onPress={() => this.deckSwiper.props.onSwipeRight()}  it ends up calling the callRightSwipe method. However this doesn't solve the problem wherein the card would change to the next one in the deck. Any idea what the problem could be?

**Comment by sullof** [comment]
I have the same issue.

**Comment by shivrajkumar** [comment]
try `onPress={() => this.deckSwiper._root. swipeRight()}`

**Comment by sullof** [comment]
Thanks but that command crashes the app because `this.deckSwiper._root` is undefined.

**Comment by sankhadeeproy007** [comment]
Can you check with v2.0.12 if it works?
![deckswiper](https://cloud.githubusercontent.com/assets/10998047/23555380/b7ba0664-004e-11e7-8b65-4cfba6b0d73d.gif)
Should be fixed.

**Comment by ryannewton** [comment]
This isn't working for me either. Is there something else I need to do to access _root.

When I `console.log(this.deckSwiper)` it has these properties:
`_reactInternalInstance: ReactCompositeComponentWrapper`
`context: Object`
`isMounted: (...)`
`props: Object`
`refs: Object`
`replaceState: (...)`
`resolveConnectedComponentStyle: ()`
`setWrappedInstance : ()`
`state: Object`
`updater: Object`
`wrappedInstance: DeckSwiper`
`__proto__: ReactComponent`

**Comment by shivrajkumar** [comment]
@ryannewton native-base version?

**Comment by ryannewton** [comment]
@shivrajkumar I was on 2.0.9. Just upgraded and that solved it.
Thanks!

**Comment by ryannewton** [comment]
This seems to have broken in 2.1.4.
Any idea what the new API is?

**Comment by BrianJVarley** [comment]
I'm on v 2.1.3 and same issue. `this._deckSwiper._root.swipeRight()` gives an undefined.

**Comment by BrianJVarley** [comment]
> This isn't working for me either. Is there something else I need to do to access _root.
> 
> When I `console.log(this.deckSwiper)` it has these properties:
> `_reactInternalInstance: ReactCompositeComponentWrapper`
> `context: Object`
> `isMounted: (...)`
> `props: Object`
> `refs: Object`
> `replaceState: (...)`
> `resolveConnectedComponentStyle: ()`
> `setWrappedInstance : ()`
> `state: Object`
> `updater: Object`
> `wrappedInstance: DeckSwiper`
> `__proto__: ReactComponent`

Did you find a solution for this swiper not working? Or did a specific version upgrade work for you?

**Comment by BrianJVarley** [comment]
> This seems to have broken in 2.1.4.
> Any idea what the new API is?

@ryannewton  did you find a version that worked for the deck swiper?
MIne is giving undefined for v.2.1.3.
