### ISSUE TITLE
Custom theme text color ignored by Text component

### ISSUE THREAD

**Issue by obasille** [GeekyAnts/NativeBase#5497]
### Description

Using a theme with a custom text color doesn't change the color the Text component

### CodeSandbox/Snack link

https://snack.expo.dev/@zilhk/native-base-theme-custom-text-color

### Steps to reproduce

See snack example.

If I understand correctly this is a limitation of how the theme system works (as the default color of the Text component is statically in its default theme) but that seems to defeat the purpose of being able to customize the theme text colors.

### NativeBase Version

3.4.18

### Platform

- [ ] Android
- [ ] CRA
- [X] Expo
- [ ] iOS
- [ ] Next

**Comment by Viraj-10** [comment]
Hi @obasille, please refer following code for Changing the Text component default color with a theme.
```
const theme = extendTheme({
  components: {
    Text: {
      baseStyle: {
        color: 'red.100',
      },
    },
  },
});

```

for better understanding please refer [this](https://docs.nativebase.io/next/customizing-components) doc.

**Comment by Viraj-10** [comment]
Also, use the latest version of `native-base`. In the snack, you provided you have added color palette named text. refer to [ this](https://docs.nativebase.io/next/customizing-theme) doc to know more.
