### ISSUE TITLE
Spinner failsl

### ISSUE THREAD

**Issue by Jan-Jan** [GeekyAnts/NativeBase#55]
Please help.

The example http://nativebase.io/docs/v0.4.6/components#spinner fails with `Element type is invalid`.
I'm using native-base 0.4.7

**Comment by sankhadeeproy007** [comment]
The spinner component is not working  for Android atm. However if you want it only for iOS. You can uncomment lines `28, 29, 61 & 62` from index.js.

**Comment by sankhadeeproy007** [comment]
Fixed with [v0.5.0](https://github.com/GeekyAnts/NativeBase/blob/master/Components/Widgets/Spinner.js)
