### ISSUE TITLE
Migration and theming docs are a little bit confusing

### ISSUE THREAD

**Issue by designorant** [GeekyAnts/NativeBase#552]
I have been playing with NativeBase `2.0.x` a little and noticed a number of issues with the docs. There's a few similar issues here (#451, #497, #538) but this is about the specific issues I've stumbled upon.

The migration guide is outdated when it comes to porting over themes. It mentions `variables.js` that doesn't exist anymore. [Docs on theming](http://nativebase.io/docs/v2.0.0/customize#themingNativeBaseApp) seem to be better, but are a quite confusing anyway, for example:

- Running `node node_modules/native-base/ejectTheme.js` results in output that says:
  
  > Head over to the docs(http://docs.nativebase.io/docs/customize/) for detailed information on customization

  That link leads to some old (?) docs for `v0.5.22`

- Docs fail to explain what `commonColor.js`, `material.js` and `platform.js` are. I assume these are themes themselves. It would be good to explain that the `platform.js` is the equivalent of what `variables.js` used to be (assuming by [this comment](https://github.com/GeekyAnts/NativeBase/issues/497#issuecomment-278862789) by @sanketsahusoft).

- Docs seem to be using a reference to `variable.js`, i.e.:
  > Go to Themes/variable.js and modify color code for textColor.
  
  This, again, is a tad confusing, particularly when the themes folder is called `native-base-theme` and themes sit in a `/variables/` subfolder of it.

- Related to the previous point, docs says: `import material from './native-base-theme/material';` which I believe should be `import material from './native-base-theme/variables/material';`.

- Docs doesn't explain what a variable really is, what a theme is, what the structure of the generated `native-base-theme` folder should look like, etc.

The latest (`2.0.8`) approach on theming seems to be a little different form how it worked with `2.0.0` so I understand this is still a work in progress but I hope the above helps nevertheless.

**Comment by sankhadeeproy007** [comment]
Hi, thanks for pointing out. We're woking to make the docs better. Your PR definitely helps!

**Comment by sanketsahusoft** [comment]
@designorant Thanks a lot for pointing out the number of issues with the docs.

We are going to work thoroughly on the docs. The success of any Open Source project lies in good documentation.

**Comment by andreyluiz** [comment]
I have issues with theming too. I tried to set the theme pointing to a copy of `material.js`, but this does not seems to work. Which file do I use to properly set the theme in 2.0.x?

**Comment by 3h13m** [comment]
@andreyluiz nice keyword "ejectTheme.js". U saved my life. Many thks

**Comment by shivrajkumar** [comment]
The new docs which is now in GitBook is much improved and resolves most of these issue and confusion. If not all. http://docs.nativebase.io/
