### ISSUE TITLE
ListView api can't be accessed through List ref

### ISSUE THREAD

**Issue by kjng** [GeekyAnts/NativeBase#555]
I currently am assigning a ref from native-base's List component but can't access the ListView api, specifically the scrollToEnd method. Am I doing something wrong?

```javascript
<List
     ref={(chatList) => { this._chatList = chatList }}
     dataArray={this.state.messages}
     renderRow={(message) =>
       <ListItem>
          <Text>{message}</Text>
       </ListItem>
     }
/>
```

this._chatList is the native-base component but there is no scrollToEnd method.

**Comment by sankhadeeproy007** [comment]
Replace `ref={(chatList) => { this._chatList = chatList }}` by `ref={(chatList) => { this._chatList._root = chatList }}` and try please.

**Comment by juslintek** [comment]
I've added this pull request, which should fix the issue:
https://github.com/GeekyAnts/NativeBase/pull/561

**Comment by daniel-van-niekerk** [comment]
Using this.refs.myList._root.root.scrollTo({x: 0, x: 0, animated: true}) worked for me. Note the extra root.

**Comment by toby1991** [comment]
this.refs.xxx.scrolltoEnd  Not Work for me either.
