### ISSUE TITLE
[Expo v47] [RN 0.70.5] [NativeBase ^3.4.21] Unable to resolve "native-base" from "App.tsx"

### ISSUE THREAD

**Issue by garrettg123** [GeekyAnts/NativeBase#5550]
### Description

App never loads, iOS Bundling failed

### CodeSandbox/Snack link

https://snack.expo.dev/@garrettg/nativebase-template

### Steps to reproduce

Run app from XCode using version provided in Snack.

### NativeBase Version

^3.4.21

### Platform

- [ ] Android
- [ ] CRA
- [X] Expo
- [X] iOS
- [ ] Next

### Additional Information

Same with NativeBase `^3.4.16`

![Simulator Screen Shot - iPhone 13 Pro Max - 2022-11-14 at 02 52 51](https://user-images.githubusercontent.com/1219054/201608431-4fbc9218-e030-4e45-a20c-d0e93785cf71.png)

**Comment by surajahmed** [comment]
@garrettg123 Thanks for reporting this. We'll have a look at this.

**Comment by ruchik02** [comment]
Hey @garrettg123, right now the version of native-base is ^3.4.25. You can update this version, and then it's working fine.
