### ISSUE TITLE
No autocomplete suggestions for extendedTheme when using WebStorm

### ISSUE THREAD

**Issue by MarianLudwig** [GeekyAnts/NativeBase#5569]
### Description

I recently switched to WebStorm from VSCode and am facing the issue that the autocompletion for colors does not respect the colors I added in my own theme. However, this is working just fine in VSCode and I couldn't track the error to WebStorm which is why I'm wondering if it's a native-base bug, somehow?

### Steps to reproduce

1. Create a default Expo project with native-base
2. Extend the theme colors using `extendTheme`
3. Add a native-base component, such as a `<Box>` in app.tsx and check autocomplete suggestions for `bg` prop

### NativeBase Version

3.4.19

### Platform

- [X] Android
- [ ] CRA
- [X] Expo
- [X] iOS
- [ ] Next

**Comment by surajahmed** [comment]
@MarianLudwig Please re-declare `native-base` typing again with extended theme typing. You can have a look at it [here](https://docs.nativebase.io/typescript)

**Comment by yamaha3680** [comment]
@MarianLudwig I had this problem. I repeated the steps from the tutorial, but it didn't help. The types only got better after I updated the library from 3.2.2 to 3.4.25.
