### ISSUE TITLE
Failed prop type: Invalid prop `style` of type `number` supplied to `Styled(List)`, expected `object`

### ISSUE THREAD

**Issue by br4nnigan** [GeekyAnts/NativeBase#557]
can't assign Stylesheet.create() styles to nativeBase component. I use current master and yesterday it worked.

**Comment by Maftalion** [comment]
Figured it out, apparently in v2 you have to pass plain objects as styles instead properties defined in your Stylesheet.create object - http://nativebase.io/docs/v2.0.0/migration

**Comment by br4nnigan** [comment]
So now i need to create a seperate style object for nativeBase components? What in improvement... anyway, thanks for the hint!

**Comment by bitsal** [comment]
It's weird you close issues without any comments "why".

I wonder why it is closed and what is a reason not using StyleSheet styles. To migrate my project to a new version of NativeBase we have to spend a lot of time to split all our styles to "for NativeBase" and "others" and convert the first one to simple JS object.

@shivrajkumar any comments?

**Comment by sankhadeeproy007** [comment]
Hi @bitsal we've mentioned it in our docs that it isn't supported at the moment with NativeBase. 

We are however working on a fix which should make it possible to add StyleSheet.create() objects.

There are various duplicates of this issue, #510, #525, #527, #599. It's hard to keep track of multiple issues referring to the same problem.

Re-opening this for now.

**Comment by bitsal** [comment]
@sankhadeeproy007 Thank you for the explanation! 
Leave at least one ticket/issue open to let us track the status via a subscribtion.

**Comment by StephenStrickland** [comment]
@sanketsahusoft I am assuming this is an issue in native base due to shoutem/theme not allowing styles from StyleSheet.create(). See https://github.com/shoutem/ui/issues/51

**Comment by sanketsahusoft** [comment]
I think @sankhadeeproy007 was to be tagged but anyway I can take this.

@StephenStrickland Yes, that's true but we have modified shoutem/ui a lot and we will be supporting Stylesheet.create() method in the next release.

**Comment by SupriyaKalghatgi** [comment]
#884

**Comment by uchilaka** [comment]
I made the following comment with notes on how I resolved this issue (hint: backward compatibility issues between native-base 1.x.x and 2.x.x): https://github.com/GeekyAnts/NativeBase/issues/884?_pjax=%23js-repo-pjax-container#issuecomment-306006075. Hope this helps!

**Comment by finian** [comment]
@sanketsahusoft Any plan to support StyleSheet.create()?

**Comment by sanketsahusoft** [comment]
@finian Yes, we are working towards that.

**Comment by ozexpert** [comment]
@sanketsahusoft is there a way to convert StyleSheet.create() to plain javascript object?
https://github.com/apentle/react-native-theme using this, seems it returns StyleSheet.create() object. thus, using NativeBase won't work.

**Comment by sanketsahusoft** [comment]
@ozexpert Yes, there are ways to convert it. You can use `StyleSheet.flatten()` function as explained in the [docs](https://facebook.github.io/react-native/docs/stylesheet.html)

**Comment by ozexpert** [comment]
That works @sankhadeeproy007 many thanks!

**Comment by sankhadeeproy007** [comment]
You mean @sanketsahusoft :)
