### ISSUE TITLE
Error when using Select on MacOS

### ISSUE THREAD

**Issue by josh-thompson13** [GeekyAnts/NativeBase#5574]
### Description

When using the select component on MacOS a render error is thrown

### CodeSandbox/Snack link

https://snack.expo.dev/J8g7pVAuA

### Steps to reproduce

The below code works on all devices except macos. The error thrown is, "Text strings must be rendered within a <Text> component. 

`<Select minWidth="200" accessibilityLabel="Choose Service" placeholder="Choose Service" _selectedItem={{
        bg: "teal.600",
        endIcon: <CheckIcon size={5} />
      }} mt="1">
          <Select.Item label="UX Research" value="ux" />
          <Select.Item label="Web Development" value="web" />
          <Select.Item label="Cross Platform Development" value="cross" />
          <Select.Item label="UI Designing" value="ui" />
          <Select.Item label="Backend Development" value="backend" />
        </Select>`

### NativeBase Version

3.4.22

### Platform

- [ ] Android
- [ ] CRA
- [ ] Expo
- [ ] iOS
- [ ] Next

### Other Platform

MacOS

### Additional Information

Please note this is code taken directly from the native base select example

**Comment by josh-thompson13** [comment]
Think this was my mistake so I will close.

**Comment by AshwiniKumar007** [comment]
Thanks for reporting @josh-thompson13.
We will check this
