### ISSUE TITLE
The "as" properties for "icon" do not work. It gives an error.

### ISSUE THREAD

**Issue by mhy-beta** [GeekyAnts/NativeBase#5608]
### Description

The "as" prop for the icon does not work, any icon cannot be displayed.

### CodeSandbox/Snack link

https://github.com/mhy-beta/atlas4/tree/master

### Steps to reproduce

1 - expo init my-app --template @native-base/expo-template
2 - command: cd my-app, and run "expo start", open web. No problem it is work.
3 - create new folder in root "screens" add new page name "header.js"
4 - import native-base components
import {StatusBar, Box, HStack, IconButton, Text, Icon, Center} from "native-base";
5 - goto nativebase docs, and copy design->AppBar, paste "header.js"
change function to "export default function HeaderScreen()"
this point ->
<Icon as={MaterialIcons} ...
show WebStorm warning this page "Unresolved variable or type MaterialIcons"
6 - open App.js and add <HeaderScreen/> in <NativeBaseProvider> bottom line.
7 - Run "expo start" command
8 - Open web and look console
-> Uncaught ReferenceError: MaterialIcons is not defined
    at HeaderScreen (header.js:8:1)
...
9 - delete all as={}..., and reload app.
![del_as_prop](https://user-images.githubusercontent.com/76412344/206727707-584c8b6c-f99e-4246-9e00-5b2a60c18d01.png)
10 - Thinking that the package "expo-vector-icons" is the default, I changed their name. "back" "down" but not showing any icons.
11 - I try the iphone 7 but ı see this message
"There was a problem running the requested app.
This project uses SDK 44.0.0 but this version of expo Go only supportts the following SDKs:
45.0.0, 46.0.0, 47.0.0..."
12 - yarn add expo@45.0.0
 expo doctor --fix-dependencies
expo start
13 - open app and icons not visible, not "?" or somethink. empty

Note: i try another project expo upgrade command, install last version(47) but not working app. Crashed.
project files: https://github.com/mhy-beta/atlas4/tree/master

### NativeBase Version

3.4.0

### Platform

- [ ] Android
- [ ] CRA
- [X] Expo
- [X] iOS
- [ ] Next

**Comment by sahilvasuja** [comment]
Hello,I see your code and you hadn’t passed as= {MaterialIcons}

**Comment by sahilvasuja** [comment]
Hello, I see your code and you hadn’t passed as= {MaterialIcons}
here is the reference👇
```
import React from "react";
import { VStack, HStack, Button, IconButton, Icon, Text, NativeBaseProvider, Center, Box, StatusBar } from "native-base";
import { MaterialIcons } from "@expo/vector-icons";

function AppBar() {
  return <>
      <StatusBar bg="#3700B3" barStyle="light-content" />
      <Box safeAreaTop bg="violet.600" />
      <HStack bg="violet.600" px="1" py="3" justifyContent="space-between" alignItems="center" w="100%" maxW="350">
        <HStack alignItems="center">
          <IconButton icon={<Icon size="sm" as={MaterialIcons} name="menu" color="white" />} />
          <Text color="white" fontSize="20" fontWeight="bold">
            Home
          </Text>
        </HStack>
        <HStack>
          <IconButton icon={<Icon as={MaterialIcons} name="favorite" size="sm" color="white" />} />
          <IconButton icon={<Icon as={MaterialIcons} name="search" size="sm" color="white" />} />
          <IconButton icon={<Icon as={MaterialIcons} name="more-vert" size="sm" color="white" />} />
        </HStack>
      </HStack>
    </>;
}

function Example() {
  return <Center>
      <AppBar />
    </Center>;
}

    export default () => {
        return (
          <NativeBaseProvider>
            <Center flex={1} px="3">
                <Example />
            </Center>
          </NativeBaseProvider>
        );
    };
```

**Comment by mhy-beta** [comment]
@sahilvasuja thank you for answer.

@expo-vector-icon does not exist among nativebase dependencies.

To use it in Nativebase, I need to install it externally.

However, in the project I created with "expo init my-app --template @native-base/expo-template" this should already be done automatically.
Because components such as <Icon> <IconButton> ... have this feature. However, in order to add an icon to the icon, the user has to install the dependency from the outside nativebase.

And no information about add package vector-icon is given either.

If the props given with "as" will belong to the iconspack that I need to add externally, why bother with "as" instead of using "MaterialIcon" or "Entrypo" directly? Which one do you think makes sense?


let's think like this. I have now created a new project.
I went to "https://docs.nativebase.io/icon-button"
I copied the code there and ran it to see how. result is show error!

I look at the page where I copied the sample code and nowhere does it say "expo-vector-icons" is required or should be to use this feature.

It's stated on the "https://docs.nativebase.io/icon" page, but no other page has this information and examples are constantly added using the expo-vector-icon package.

If you do not make this warning consciously, this information should be added to the pages containing examples.
Otherwise, instead of using "expo-vector-icons", it is necessary to replace the samples with their own nativebase-icons.
