### ISSUE TITLE
How to remove bottom border of ListItem?

### ISSUE THREAD

**Issue by weeravit** [GeekyAnts/NativeBase#563]
I try to set 'noBorder' prop but nothing happened.

React Native v0.41
NativeBase v2.0.3

**Comment by sankhadeeproy007** [comment]
`style={{borderBottomWidth: 0}}`

**Comment by weeravit** [comment]
Thank @sankhadeeproy007  It work for me.

**Comment by RWOverdijk** [comment]
This doesn't work if the avatar prop is set to true.

**Comment by svdwyer** [comment]
@RWOverdijk 
in that case you need to set the style property to the Body (and Right) element

**Comment by RWOverdijk** [comment]
I noticed. I think that's a bit of an ugly solution, so I didn't mention it here.

**Comment by SupriyaKalghatgi** [comment]
`<ListItem noBorder>`
This removes bottom border from ListItem

**Comment by kristinadarroch** [comment]
How do you set the avatar prop to false?
