### ISSUE TITLE
Question: Asking about Tab Bar example

### ISSUE THREAD

**Issue by puzpuz** [GeekyAnts/NativeBase#565]
RN 0.41 Native Base 2.09

This is not an issue, It's a question and request.

Native Base have a very nice set of interface to be use. Since Native Base has its own FooterTab (Navigation Tab). I wonder if there is an example to use this component. Just a simple changing from one page to another, and changing its active status (which highlighting the active tab). I'm quite confuse on how to integrate it with React Native Router Flux since they have their own Navigation Tab. 

Any answer or pointer would be appreciated, thank you

**Comment by sankhadeeproy007** [comment]
You can set the active to mirror the current state. On click of a button you can set the route to a new page and set the active state of the current tab as well. 
Let me know if all this info together is overwhelming for you and you need me to break it up for you.

**Comment by puzpuz** [comment]
Very quick response :)
Actually I just started learning React Native 3 weeks ago, so yes it's quite confusing for me. Here some question:
1. If the active status mirror the current state, then if I have 3 tabs, I need 3 state (for each tab), so whenever I click on a tab, I set its own state to true, and set the others to false? Am I correct on this one?

2. If you say that I can set the route to a new page then if I have 3 tabs, it means that I have 3 page ( all three have the same footer) ?

My background is an Android Native developer, so I'm quite familiar with Fragment. I thought if you change the tab, you only change the inside of <Content> tag.

Thank you

**Comment by sankhadeeproy007** [comment]
Answer to 1, yes that's what you need to do. 
Answer to 2, you can set a common FooterTab and nest the routing inside the component containing the footerTab.

**Comment by sankhadeeproy007** [comment]
Here's something which you might relate to. #542

**Comment by puzpuz** [comment]
If you say it's related to that question, are you suggesting me to make a tab at the top, hide the tab, and control the tab changing from the footer tab?

Sorry I don't get it

**Comment by sankhadeeproy007** [comment]
No, that is another way of doing it. It's okay if your case is totally different.

**Comment by puzpuz** [comment]
I'm using router flux, so for every page I create, I will declare a `<Scene>` tag and in order to change page I will call Actions.someScreenName(). But the problem is whenever I call Actions method. The screen will change completely (not partially) That is why I'm confuse on how to combine Native Base Footer interface with router flux's navigation ability

**Comment by sankhadeeproy007** [comment]
Okay, I understand your question. Did you try putting the router inside the Component which has the FooterTabs? Like declare all your scenes inside that component, which has the FooterTbs component?
