### ISSUE TITLE
Header. How to show a long Title?

### ISSUE THREAD

**Issue by danilvalov** [GeekyAnts/NativeBase#567]
In the Native Base documentation we can see the following image:

<img src="http://nativebase.io/docs/v2.0.0/assets/img/ios/new/head&FootCard.png" alt="" width="300" />

We see that `<Title>` can use more space but it is cut off.
How to show a long `<Title>`?

**Comment by quangrau** [comment]
Same question. Any configuration for that? or I have to restyle the Header component?

**Comment by sankhadeeproy007** [comment]
You'll have to `eject` and change the header component. Just set the flex value [here](https://github.com/GeekyAnts/NativeBase/blob/master/src/theme/components/Header.js#L199) to higher value. Please feel free to ask if you have any problems with ejecting.

**Comment by klvs** [comment]
For anyone coming from Google, as mentioned in #605 `<Body style={{flex: 3}}>` fixes this issue for me.

**Comment by cdimitroulas** [comment]
@klvs your solution works but then the title is no longer centered. Is there a way to easily center it after applying `flex: 3` on the styles?

**Comment by agungjk** [comment]
Just wrap it to <Text></Text>
Dont use <Title></Title>

**Comment by stpch** [comment]
Setting 'flex: 1` for `<Body>` and `flex: 0` for `<Left>` and `<Right>` also seems to do the trick and you'll get a `<Body>` that takes up all remaining width. You might have to play around with margins/paddings, though, to get the desired look.

**Comment by BobsonTheFirst** [comment]
I have two icons in my header (one left in the header, one right in the header). When setting <body> flex: 1 and Left & Rihgt: 0, the header title will cover the left icon. My solution: setting <body> flex: 4 and setting <Left> & <Right> flex:1.

**Comment by mohemos** [comment]
> @klvs your solution works but then the title is no longer centered. Is there a way to easily center it after applying `flex: 3` on the styles?
This should centralize the title 
`<Body style={{flex: 3, flexDirection:'row', justifyContent:'center'}}>`

**Comment by littlefinger42** [comment]
> xDirection:'row'

Or `{ flex: 3, alignItems: "center" }`
