### ISSUE TITLE
how to define global font?

### ISSUE THREAD

**Issue by PierBover** [GeekyAnts/NativeBase#57]
There is nothing about fonts in the `light.js`.

Is it possible to do that?

**Comment by sankhadeeproy007** [comment]
Just setting the font as a variable won't be of much help. We'll have to include the .ttf file separately for each custom fonts. So that is not something we're looking to support in the near future. However if you do need a different font, this article might be of some help.
https://medium.com/@dabit3/adding-custom-fonts-to-react-native-b266b41bff7f#.mzhtf14we

**Comment by PierBover** [comment]
Thanks I know how to include and use custom fonts.

What I'd like to know is how to apply that font to all NativeBase widgets.

**Comment by sankhadeeproy007** [comment]
Provided you use all the `<Text>` components from native-base for your app. You can define the font-family in Components/Widgets/Text.js.

**Comment by PierBover** [comment]
Oh ok, I was hoping there was a way to do that from the theme.

Maybe you could mark this as a feature request?

**Comment by sankhadeeproy007** [comment]
There is already a custom font request. Since we want native-base to work out of the box, we can have a font variable, but how do you suggest we deal with the problem of manually adding font files?

**Comment by sankhadeeproy007** [comment]
Same as #23

**Comment by PierBover** [comment]
Including custom font is easy.

1) Create a `fonts` folder in the project root.

2) Add this to `package.json`

```
  "rnpm": {
    "assets": [
      "fonts"
    ]
  }
```

3) `rnpm link`

You already have a similar procedure when installing the `react-native-vector-icons` dependency without the need of modifying `package.json` so something cleaner could be achieved.

**Comment by sankhadeeproy007** [comment]
Sounds cool. Will try it out and hopefully publish it with our next release. Appreciate the help. Thanks!

**Comment by benjick** [comment]
@PierBover Doesn't seem to link the fonts in iOS (0.41), got another solution you're aware off?

**Comment by PierBover** [comment]
@benjick no, sorry.
