### ISSUE TITLE
Tabs in 2.0.10

### ISSUE THREAD

**Issue by Clowning** [GeekyAnts/NativeBase#573]
Hi NativeBase,

First of all, thank for your components, it's very cool ! 

But i have an issue with Tabs components ! In your documentations you said there are some custom style we can add : 

tabStyle
activeTabStyle
textStyle
activeTextStyle

But no one working ! 

Here, there is my code : 

```
headingFree() {
    return (
      <TabHeading
        tabStyle ={{ backgroundColor: '#6298FC' }}
        activeTabStyle={{ backgroundColor: 'white' }}
        >
        <Text style={{ color: 'white', fontWeight: 'bold' }}>{'Top ' + I18n.t('common.free')}</Text>
      </TabHeading>
    );
  }

  render() {
    return (
      <View
        style={{
          flex: 1,
          marginTop: 60,
          marginBottom: 45,
        }}>
         <Container>
        <Tabs>
          <Tab heading={this.headingFree()}>
            <TopPaid />
          </Tab>
          <Tab heading={this.headingFree()}>
            <TopFree />
          </Tab>
          <Tab heading={this.headingFree()}>
            <TopNews />
          </Tab>
        </Tabs>
      </Container>
      </View>
    );
  }
```

So, if you have a solution? :) !

Thank by advance!

**Comment by sankhadeeproy007** [comment]
activeTabStyle and tabStyle are only to be used when you pass a string to the `heading` prop.
In your case, you can directly use `style={{backgrounColor: (this.state.active) ? '#6298FC' : 'white'}}` Make sure you keep track of the active tab in your local state.

**Comment by sankhadeeproy007** [comment]
@Clowning Does it work?
