### ISSUE TITLE
Button is always on top even with overlay View with big zIndex

### ISSUE THREAD

**Issue by LeoAref** [GeekyAnts/NativeBase#576]
## react-native, react and native-base version
- react-native: `0.41.2`
- native-base": `^2.0.10`

## Expected behaviour
Have the `absolute` positioned `View` covering the `Button`

## Actual behaviour
The `Button` is always on top, even with giving the `View` big `zIndex`

## Steps to reproduce (code snippet or screenshot)
<img width="269" alt="screen shot 2017-02-27 at 09 24 10" src="https://cloud.githubusercontent.com/assets/6577222/23353793/898541ba-fcce-11e6-8f6d-6f4ec938444e.png">

## Screenshot of emulator/device
Nexus 6 

## Is the bug present in both ios and android or in any one of them?
Tried only on Android

## Any other additional info which would help us debug the issue quicker.
Styles:
```js
const styles = {
  container: {
    flex: 0,
    width: 300,
    position: 'relative'
  },
  spinner: {
    height: 36
  },
  overlay: {
    position: 'absolute',
    zIndex: 10,
    backgroundColor: 'rgba(255, 0, 0, .75)',
    left: 0,
    right: 0,
    bottom: 0,
    top: 0,
    flex: 1,
    justifyContent: 'center'
  }
};
```

Jsx:
```js
<Card style={this.props.style.container}>
  <Form>
    <Item>
      <Input placeholder="Username"/>
    </Item>
    <Item last>
      <Input placeholder="Password"/>
    </Item>
  </Form>
  <Button full style={{zIndex: 10}}>
    <Text>Login</Text>
  </Button>
  <View style={this.props.style.overlay}>
    <Spinner style={this.props.style.spinner} color='green'/>
  </View>
</Card>
```

**Comment by sankhadeeproy007** [comment]
Give the View a higher elevation, anything above 4.
