### ISSUE TITLE
Native Base Roadmap

### ISSUE THREAD

**Issue by nicolascavallin** [GeekyAnts/NativeBase#5769]
### Description

Understanding that all efforts are on `gluestack` now, I would like to ask about the roadmap for Native Base, to get clear our roadmap using it.

### Problem Statement

Considering that gluestack is the future, is scheduled any update or something for Native Base?

For example, is known the "In React 18, SSRProvider is not necessary and is a noop..." warning with React Native 72. And is possible that in future there will be another like that.

### Proposed Solution or API

Knowing the roadmap for Native Base and for gluestack will help us with our roadmap.

Thanks in advance.

**Comment by bennyszantar** [comment]
That would be very helpful, up !

**Comment by Jarvie789** [comment]
It is estimated that Native Base will no longer be maintained gradually, and will turn to gluestack-ui wholeheartedly.
