### ISSUE TITLE
npm install failure 

### ISSUE THREAD

**Issue by leonidster** [GeekyAnts/NativeBase#578]
Hello,

When trying to install NativeBase using the command:
npm install native-base --save

I'm getting the following error:

m ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "native-base" "--save"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! code E404

npm ERR! 404 no such package available : @shoutem/animation
npm ERR! 404 
npm ERR! 404  '@shoutem/animation' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'native-base'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

My versions:
react-native-cli: 2.0.1
react-native: 0.40.0
npm version: 3.10.10

Thanks.

**Comment by sankhadeeproy007** [comment]
Seems to be a temporary glitch. Can you try again and check? I just did a fresh install and it worked fine.

**Comment by leonidster** [comment]
nope, still same errors..

**Comment by sankhadeeproy007** [comment]
Can you install @shoutem/animation independently?

**Comment by leonidster** [comment]
I tried, an also getting the same error..

**Comment by Gordyus** [comment]
Hi,

Same problem here :
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\
node_modules\npm\bin\npm-cli.js" "install" "--save" "@shoutem/animation"
npm ERR! node v7.6.0
npm ERR! npm v4.1.2

npm ERR! Invalid name: "@shoutem/animation"

Version react :
react-native-cli: 2.0.1
react-native: 0.41.2

Version npm : 4.1.2

I posted an issue [here](https://github.com/shoutem/animation/issues/12) just in case.

Thanks.

**Comment by juanpgaviria** [comment]
+1

**Comment by juanpgaviria** [comment]
i mange to pass this issue.. i was running npm@3.10.3... i just updated to 3.10.10 and problem fixed.. weird because @leonidster its using that version. But that solve it.. im been playing with "n" few days ago, may be i did something wrong. So try reinstalling npm.

**Comment by winterbang** [comment]
sorry, i still have the same problem. 
version npm : 4.4.1
version node v7.3.0
how to solve it.
thanks

**Comment by juanpgaviria** [comment]
@winterbang mate, i just reinstall npm and it worked.. try that while some adult solve the real problem(which is unknow! :P), if reinstall does not work sorry i cant help!

**Comment by winterbang** [comment]
@juanpgaviria thanks. there is also problems. 

> no such package available : @shoutem/animation

version npm v4.1.2
version node v7.6.0

so disappointed

**Comment by shivrajkumar** [comment]
Closing the issue as it works fine with the newer versions
