### ISSUE TITLE
Unable to find modules after install and yarn start the react-native cli

### ISSUE THREAD

**Issue by michaelroevievictoria** [GeekyAnts/NativeBase#5780]
### Description

not sure but the error is from the other library but after i use yarn why native-base is using that library 

### CodeSandbox/Snack link

//

### Steps to reproduce

after I close the app and run though again

I try to bump up the native-base
native-base": "3.2.2-rc.3", from 3.0

error says
![image](https://github.com/GeekyAnts/NativeBase/assets/6307916/a6ad53d1-6f9e-4252-8808-6e412812e292)

![image](https://github.com/GeekyAnts/NativeBase/assets/6307916/4203f842-f51b-49e5-8bde-b5d6256318fd)
![image](https://github.com/GeekyAnts/NativeBase/assets/6307916/c714dfe2-5966-4c78-aedf-c62bcbbeca1d)

### NativeBase Version

3.2.2-rc.3

### Platform

- [X] Android
- [X] CRA
- [ ] Expo
- [X] iOS
- [ ] Next

**Comment by Manikanta-GEP** [comment]
It's happening with older versions of native base as well

**Comment by adityatagline** [comment]
I have version 3.4.28 also tried with ^3.4.28 facing same error.

**Comment by michaelroevievictoria** [comment]
this [snippet code](https://github.com/adobe/react-spectrum/issues/4894#issuecomment-1674054618) save my day

**Comment by karthikeyancontus** [comment]
https://github.com/adobe/react-spectrum/issues/4894
