### ISSUE TITLE
Text inside Button isn't capitalized

### ISSUE THREAD

**Issue by yustnip** [GeekyAnts/NativeBase#579]
On Android a text inside Button isn't capitalized. Example:

```js
import { Button, Text } from 'native-base'
...
<Button>
    <Text>Button text</Text>
</Button>
...
```

![screen shot 2017-02-27 at 18 35 31](https://cloud.githubusercontent.com/assets/9950871/23367593/d463f1d4-fd1b-11e6-8784-b17114c59976.png)

*react-native, react and native-base version*
0.41.2, 15.4.2, 2.0.10

**Comment by sankhadeeproy007** [comment]
`Capitalize` prop has been discontinued because that involved cloning of elements which is not a good practice. Will be updated in docs soon.

**Comment by sanketsahusoft** [comment]
@sankhadeeproy007 Can't we do it without cloning? I think there must be some good way of doing it.

May be detect the context of <Text> and if it's within a <Button> then capitalize the children[0] of <Text> by default.

Just thinking out loud.

**Comment by sankhadeeproy007** [comment]
@sanketsahusoft  Since there's no CSS way of doing this yet, we'll have to check the type and if it's `string` we'll have to do a `toUpperCase` to it. So we'll have to render the text part again.

**Comment by 337240552** [comment]
`<Text uppercase={false}>some text</Text`
