### ISSUE TITLE
Header icons are not aligned in the middle and different background?

### ISSUE THREAD

**Issue by kenma9123** [GeekyAnts/NativeBase#58]
Got the latest release from npm `0.4.9`. But as soon as I try it out. The header icons are not center aligned. The background of the header is blue green and the foreground is black., I was expecting a dark gray background and a white foreground just like what's on the [docs](http://nativebase.io/docs/v0.4.6/components#header). Look the image below. Maybe it's not compatible with the latest react-native or am I doing something wrong?

dependencies:
```
    "native-base": "^0.4.9",
    "react": "15.2.1",
    "react-native": "0.29.0",
    "react-native-vector-icons": "^2.0.3"
```

![image](https://cloud.githubusercontent.com/assets/1641990/16757581/9cad7f8a-483f-11e6-927a-ffc8843e79f7.png)

**Comment by sankhadeeproy007** [comment]
Can you replace line no. 24 in `NativeBase/Components/Widgets/Header.js` with the following code `paddingTop: (Platform.OS === 'ios' ) ? 15 : 0,`. That should do the trick. Also the header color is a variable and can be changed from `NativeBase/Components/Themes/light.js` line no. 52. Let me know if that works.

**Comment by kenma9123** [comment]
Okay it worked. I cloned the master branch instead, it seems the latest update `0.4.9` doesn't have the changes 4 days ago. I suggest to release a new version very soon :) Thanks :+1:

**Comment by sankhadeeproy007** [comment]
Good to know it worked. We're trying our best to release latest stable versions. We'll release a new version with more features very soon.

**Comment by blaziken105** [comment]
I have similar issues with the header body, the left and right tags align the icons properly to the corners. However the body text doesn't centre align.

I have the following dependencies
    "native-base": "^2.1.1",
    "react": "16.0.0-alpha.6",
    "react-native": "0.43.1",

The code is as follows:

  ```
<Header >
            <Left>
              <Icon name="arrow-back" style={{backgroundColor:'blue',color:"#fff"}} onPress={this.back.bind(this)}/>
            </Left>
            <Body>
                <Title style={{backgroundColor:'red'}}>ABC</Title>
            </Body>
            <Right>
              <Icon name="brush" style={{backgroundColor:'green',color:"#fff"}} onPress={this.edit.bind(this)}/>
            </Right>
 </Header>

```
I have put background colours to see the space taken up by each component, apparently the body doesn't take up enough space to centre align. What seems to be the problem here? What is the best fix for such an issue?

![view](https://cloud.githubusercontent.com/assets/19424452/25982550/11e189cc-36fb-11e7-83bd-48ab1819eab0.png)

**Comment by pavex** [comment]
I have same problem on Android. Left component is very wide (flex: 1). Try to remove Left wrapper component.
