### ISSUE TITLE
Why is this package 2.x.x when React Native itself is 0.x.x ?

### ISSUE THREAD

**Issue by adityasaxena** [GeekyAnts/NativeBase#581]
Sorry team. I think naming it as version 2 would mean the package is stable and breaking changes only happen in major releases. I believe that is not the case here. Could you guys stick to updating major versions everytime you introduce breaking changes ?

**Comment by sanketsahusoft** [comment]
@adityasaxena We named it 2.x because we had many breaking changes and RN stays at 0.x because they didn't have breaking changes. Also, to add the most famous dependency of RN i.e. Vector Icons is at 4.x.

React jumped from 0.x to 15.x! It's okay -- Let's talk about real issues!
