### ISSUE TITLE
Toast not working

### ISSUE THREAD

**Issue by sardormajano** [GeekyAnts/NativeBase#584]
Hello! I am trying to use native-base Toast component, but it won't work. Even though I import it by native-base docs (http://nativebase.io/docs/v2.0.0/components#toast). 

`import {Toast, Text} from 'native-base';`

When I use it, it is throwing error: 'Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined.'

`<Toast ><Text>{context.state.toastText}</Text><Toast>`

Tried consoleLogging the component (remoteJS debugging)

`console.log(Toast);`, 

but I am getting 'undefined' while when consoleLogging any other imported component (native-base component) returns something like

`function StyledComponent(props,context){_cl...`.

I am new to react-native, and have been having this problem for a couple of hours. Could you, please, help me with that? My native-base version is 2.0.9

**Comment by fhad-getmaple** [comment]
+1

**Comment by sankhadeeproy007** [comment]
Toast has been added v2.0.10 onwards. Please upgrade your version and check.

**Comment by iiitmahesh** [comment]
Not working in 2.0.12

```
import {Text, Toast } from 'native-base';
login = () => {
        this.setState({ loading_status: true });
        let credentials = { "email": this.state.email, "password": this.state.password }
        this.props.getDevices(credentials, false).then((responseJson) => {
            this.setState({
                resultMsg: { success: 'Awesome, you\'re now logged in!' },
                loading_status: false
            });          
            Actions.app();
        }).catch((err) => {
            console.log('Failing in login page')
            Toast.show({
                text: 'Wrong password!',
                position: 'bottom',
                buttonText: 'Okay'
              });
            this.setState({ resultMsg: { error: 'Please check your credentialss' }, loading_status: false });
             
        });
    }

```

**Comment by GeekRishabh** [comment]
@iiitmahesh  what version of RN you are using ?

**Comment by iiitmahesh** [comment]
@GeekRishabh 

```
"react": "15.4.2",
"react-native": "0.40.0",
"native-base": "2.0.12",
```

**Comment by jan4984** [comment]
@iiitmahesh as documented, 

> Note: For Toast to work, it has to be called inside Container.

now we have another issue https://github.com/GeekyAnts/NativeBase/issues/432

**Comment by akashanand708** [comment]
For toast to work, wherever you want, even after ajax response,
The topmost component should be wrapped between <Root>.... </Root>
According to nativeBase docs.
https://docs.nativebase.io/Components.html#Thumbnail
It worked for me

**Comment by SupriyaKalghatgi** [comment]
https://docs.nativebase.io/Components.html#toast-def-headref
