### ISSUE TITLE
Style props not being applied

### ISSUE THREAD

**Issue by srhise** [GeekyAnts/NativeBase#585]
I am trying to apply basic style properties per the docs to input elements and groups, and it is rendering the default layout each time, and not applying props correctly. 

## react-native, react and native-base version
NB -> 2.0.11 RN->0.41
## Expected behaviour
Input style properties render properly
## Actual behaviour
Input style properties do not render properly
## Steps to reproduce (code snippet or screenshot)
Try to add an InputGroup or Item with rounded corners or icon right alignment
## Screenshot of emulator/device
![image](https://cloud.githubusercontent.com/assets/914113/23485724/bd9157ae-feaa-11e6-98fe-35acb131ed61.png)

## Is the bug present in both ios and android or in any one of them?
only tested on iOS
## Any other additional info which would help us debug the issue quicker.
I tried applying the 'light' theme to the component, this did not change anything. I am copy and pasting examples from docs.

**Comment by sankhadeeproy007** [comment]
cc @shivrajkumar

**Comment by shivrajkumar** [comment]
@srhise In v2.0.x `InputGroup` has been replaced by `Item`.
Refer http://nativebase.io/docs/v2.0.0/components#roundedTextbox

**Comment by srhise** [comment]
Using item doesn't help me in this situation. The only style I have applied is to set the text color to white: 

![image](https://cloud.githubusercontent.com/assets/914113/23510030/fb15d50c-ff25-11e6-8656-1c32cce56e64.png)

**Comment by morgan-adoche** [comment]
+1

**Comment by shivrajkumar** [comment]
Fixed in v2.1.3
Have a look
