### ISSUE TITLE
cannot vertically center Form component

### ISSUE THREAD

**Issue by mmckinley8** [GeekyAnts/NativeBase#586]
Hi! Thanks for trying out NativeBase!
Due to the overwhelming requests and issues/questions we ask you to add the following details with your issue.

## react-native, react and native-base version
react-native: 0.41.2, react: 15.4.0, native-base: 2.0.11
## Expected behaviour
vertically centered textInput (Form Item)
## Actual behaviour
Form completely disappears when trying to add vertically centering styles to it or its parents
## Steps to reproduce (code snippet or screenshot)
 ```
 render() {
    return (
      <Container>
        <Content contentContainerStyle={{alignItems: 'center', flex: 1, justifyContent: 'center'}}>
          <Form>
            <Item>
              <Input placeholder="Username" />
            </Item>
            <Item last>
              <Input placeholder="Password" />
            </Item>
          </Form>
        </Content>
      </Container>
    )
  }
```
## Screenshot of emulator/device
It's just a blank screen.
## Is the bug present in both ios and android or in any one of them?
Both
## Any other additional info which would help us debug the issue quicker.
If I add no styles, it appears at the top of the page as expected and in the docs, I can also add padding to it - but cannot vertically center. I was able to vertically center a button using the approach above.

**Comment by shivrajkumar** [comment]
Just using `justifyContent: 'center'` should do it.

**Comment by Ajay-Jadhao** [comment]
Same here

**Comment by akhil-geekyants** [comment]
@Ajay-Jadhao I just tried with the above code and modified it and was getting the form content centered vertically. can you try something like this

```
 <Container>
          <Content contentContainerStyle={{flex:1,justifyContent: 'center'}}>
            <Form>
              <Item>
                <Input placeholder="Username" />
              </Item>
              <Item last>
                <Input placeholder="Password" />
              </Item>
            </Form>
          </Content>
     </Container>
```

**Comment by Ajay-Jadhao** [comment]
@akhil-geekyants 

Below is my code 

`  render() {
    return (
      <Container>
        <Header backgroundColor='#207ee1'>
            <Left>
              <Image
                style={styles.imageStyle}
                source={logo}
              />
            </Left>
          <Right />
        </Header>

        <Content style={styles.contentStyle} contentContainerStyle={{ flex:1, justifyContent: 'center' }}>
          <Card>
            <CardItem>
              <Body>
                <Item >
                  <Text style={styles.titleStyle}>
                    Invoice & Revenue
                  </Text>
                </Item>
                <Item>
                  <Icon name='face' />
                  <Input placeholder='Username' />
                </Item>

                <Item>
                  <Icon name='lock-open' />
                  <Input placeholder='Password' />
                </Item>
              </Body>
            </CardItem>
          </Card>
        </Content>

      </Container>
    );`

**Comment by akhil-geekyants** [comment]
just add this style for Card  `<Card style={{justifyContent:'center'}}>`

**Comment by Ajay-Jadhao** [comment]
Still not working No effect on Card.

Here is the screenshot.
![screenshot_1506070307](https://user-images.githubusercontent.com/8046991/30736787-cc50ed84-9fa1-11e7-99a0-d4df5d46e69f.png)

**Comment by akhil-geekyants** [comment]
@Ajay-Jadhao 
you can eject the theme by following this [docs](https://docs.nativebase.io/Customize.html#Customize) and remove `flex:1` from cardTheme object in `native-base-theme/components/Card.js` or you can override the card style by putting `flex:0` (not sure whether it is a good practice)

**Comment by rubanraj54** [comment]
Still I couldn't vertically center card component inside **Content**
