### ISSUE TITLE
ListItem background color gets black while pressed in iOS

### ISSUE THREAD

**Issue by Cotel** [GeekyAnts/NativeBase#587]
I've just Native Base in my project from 2.0.5 to 2.0.11. My React-Native version is 0.40 and React is 15.4.2.

After the update, when I click on a ListItem it's background gets totally black.

![image](https://cloud.githubusercontent.com/assets/9035239/23504195/ba40523c-ff3e-11e6-875b-72726e9858fb.png)

I have not touched any style related with ListItem or TouchableOpacity.

Is there any way to solve this without returning to 2.0.5?

**Comment by sankhadeeproy007** [comment]
Did you `eject` your variables?

**Comment by Cotel** [comment]
I used `node node_modules/native-base/ejectTheme.js` but I did not touch anything in `variables`.

**Comment by Cotel** [comment]
I found the solution. I missed one line in my theme file while I was migrating it: `listBtnUnderlayColor: '#DDD'`.

Thank you!
