### ISSUE TITLE
Ionic "arrow-dropright" not working

### ISSUE THREAD

**Issue by amelzer** [GeekyAnts/NativeBase#588]
## native-base version
navite-base version 2.0.9

## Expected behaviour
Icon is shown.

## Actual behaviour
"?" is shown

## Steps to reproduce (code snippet or screenshot)
`<Icon name="arrow-dropright"/>`

## Screenshot of emulator/device
![simulator screen shot 2 mar 2017 13 44 23](https://cloud.githubusercontent.com/assets/1628866/23507838/2228fa06-ff4f-11e6-9507-92d60cf3c947.png)

## Is the bug present in both ios and android or in any one of them?
Both

## Any other additional info which would help us debug the issue quicker.
"ios-arrow-dropright" and "md-arrow-dropright" work fine.
"arrow-dropright" is an icon from the Ionicons set http://ionicframework.com/docs/v2/ionicons/

**Comment by sankhadeeproy007** [comment]
Fixed with v2.0.12
