### ISSUE TITLE
undefined is not an object (item.type.displayName)

### ISSUE THREAD

**Issue by tanmynguyen** [GeekyAnts/NativeBase#589]
Hi! Thanks for trying out NativeBase!
Due to the overwhelming requests and issues/questions we ask you to add the following details with your issue.

## react-native, react and native-base version
- RN: 0.42.0
- React: 15.4.2
- NB: 2.0.11
## Expected behaviour
Add Header 
## Steps to reproduce (code snippet or screenshot)
<img width="1035" alt="screen shot 2017-03-02 at 23 41 32" src="https://cloud.githubusercontent.com/assets/11315567/23517169/30b6ae26-ffa2-11e6-931d-8efe00f47a4d.png">

## Screenshot of emulator/device
<img width="377" alt="screen shot 2017-03-02 at 23 41 46" src="https://cloud.githubusercontent.com/assets/11315567/23517148/1e864ec8-ffa2-11e6-9395-8b7c6ee76258.png">

**Comment by sankhadeeproy007** [comment]
I don't think `<Left/>` and `<Right />` are supported in `native-base/backward`

**Comment by tanmynguyen** [comment]
Thanks you. Left, Right and Body only supported `native-base`
