### ISSUE TITLE
Input can't be accessed through ref

### ISSUE THREAD

**Issue by yeknava** [GeekyAnts/NativeBase#591]
## react-native, react and native-base version
RN 42 & NB 2.0.11
## Expected behaviour
Input should accept ref as a prop but it wont.

we need input ref to focus next input on onSubmitEditing event. 

[https://facebook.github.io/react-native/docs/textinput.html](url) -> BlurOnSubmitExample

**Comment by sankhadeeproy007** [comment]
The docs here have explained how to use refs. Also please upgrade to v2.0.12 and check.

**Comment by ryanwilliams** [comment]
I also cannot get refs to work on `<Input />` components. I'm using 2.0.12. 

In this version the ref function is never called:

    <Input ref={input => console.log("HUH?", input) } />

And in this version `this.refs` never gets populated with a ref to the input

    <Input ref="something" />

However if I change the `Input` to a `Label` then it works fine.

**Comment by ryanwilliams** [comment]
After further investigation it's only when the input is inside a `<Item floatingLabel>` I guess it doesn't have a control in the view when it's initially mounted, so there's nothing to reference.

**Comment by bfreis** [comment]
Same issue: a `ref` defined on an `<Input>` component inside an `<Item floatingLabel>` doesn't work. But if I remove the `floatingLabel`, it does work.

Here's an example that doesn't work. The message logged to the console displays `[]`.

      <View>
        <View padder>
          <Form>
            <Item floatingLabel>
              <Label>Login</Label>
              <Input ref="loginInput"/>
            </Item>
            <Item floatingLabel last>
              <Label>Password</Label>
              <Input secureTextEntry ref={'passwordInput'}/>
            </Item>
          </Form>
        </View>
        <View padder>
          <Button block onPress={() => console.log('pressed', JSON.stringify(Object.keys(this.refs)))}>
            <Text>Login</Text>
          </Button>
        </View>
      </View>

If I remove the `floatingLabel`, then the message on the console logs correctly, `["loginInput", "passwordInput"]`.

**Comment by fbacker** [comment]
Also notice this.
Also if I try to pre set a value to the Input the floating label is in "empty" mode (down) above my prefilled value.

**Comment by pierre-H** [comment]
I have the same problem with `<Item floatingLabel>`
@yeknava could you re-open this issue ?

**Comment by shivrajkumar** [comment]
For `floatingLabel` try gerRef

**Comment by pierre-H** [comment]
@shivrajkumar thank you but what's gerRef ?

**Comment by AbhishekBiswal** [comment]
@pierre-H Use getRef instead of Ref
Here's a working example:

```js
<Item floatingLabel>
                  <Label>Title</Label>
                  <Input
                  returnKeyType = {"next"}
                  autoFocus = {true}
                  onSubmitEditing={(event) => {
                      this._textInput._root.focus(); 
                  }}
                  />
              </Item>
              <Item floatingLabel>
                  <Label>Description</Label>
                  <Input
                  getRef={(c) => this._inputDesc = c}
                  multiline={true} style={{height: 100}} />
                  onSubmitEditing={(event) => { this._inputLink._root.focus(); }}
              </Item>
```

**Comment by AbhishekBiswal** [comment]
@pierre-H 
Use getRef instead of ref

Here's a working example:
```jsx
<Item floatingLabel>
                  <Label>Title</Label>
                  <Input
                  returnKeyType = {"next"}
                  autoFocus = {true}
                  onSubmitEditing={(event) => {
                      this._inputDesc._root.focus(); 
                  }}
                  />
              </Item>
              <Item floatingLabel>
                  <Label>Description</Label>
                  <Input
                  getRef={(c) => this._inputDesc = c}
                  multiline={true} style={{height: 100}} />
                  onSubmitEditing={(event) => { this._inputLink._root.focus(); }}
              </Item>
```

**Comment by fbacker** [comment]
Running 2.1.3 on iOS

    getRef={(c) => console.log("hello",c)}

c returns undefined

**Comment by fryck** [comment]
If you add an Icon, ref become undefined...

`<Item floatingLabel>
                  <Label>Description</Label>
                  <Input
                  getRef={(c) => this._inputDesc = c}
                  multiline={true} style={{height: 100}} />
                  onSubmitEditing={(event) => { this._inputLink._root.focus(); }}
                  <Icon />
              </Item>`

**Comment by Nahueleti** [comment]
Solution proposed by @AbhishekBiswal 
```
...
<Input
                  getRef={(c) => this._inputDesc = c}
...
```

works.

> native-base@2.2.1
> react-native@0.46.2
> react@16.0.0-alpha.12

**Comment by boringer** [comment]
I use `getRef` but get no help.

**Comment by Roconda** [comment]
This is a really weird issue which is inconsistent with RN. Any permanent fix on the roadmap?

**Comment by fmoessle** [comment]
Please fix this. I love using native base, that is the first really annoying thing I encountered :(

**Comment by hardcodet** [comment]
This is most definitely broken. I also don't get a reference through `getref`. The `pw` field I'm trying to set here stays `undefined`:

                    <Item error={!loginStore.isValidPassword}>
                        <Icon active name="unlock"/>
                        <Input
                            getRef={i => this.pw = i}
                            placeholder="Password"
                            value={loginStore.password}
                            returnKeyType={"done"}
                            onChangeText={p => loginStore.setPassword(p)}
                            secureTextEntry={true}
                        />
                    </Item>

**Comment by mindfocus** [comment]
Also can't be accessed through ref 
`
loginBtnPress = () => {
		console.log(this);
		console.log(this.emailInput);
		console.log(this.passwordInput);
		console.log(this.refs);
	};
<Item floatingLabel>
								<Icon active name="person"/>
								<Label>邮箱</Label>
								<Input
									ref='emailInput'
									returnKeyType='next'
									onSubmitEditing={() => this._focusInput('passwordInput')}
								/>
							</Item>
							<Item floatingLabel>
								<Icon active name="lock"/>
								<Label>密码</Label>
								<Input
									getRef={c => {
										this.passwordInput = c;
									}}
									secureTextEntry={true}
								/>
							</Item>
							<Button full info onPress={() => this.loginBtnPress()}>
								<Text>登录</Text>
							</Button>
`
React-Native:0.50.0
React-Native:16.0.0
Native-Base:2.3.5

**Comment by pennyandsean** [comment]
Why is this closed? Its still a problem.

**Comment by pennyandsean** [comment]
Why is this closed?  I didn't see a fix in any of the referenced issues.

**Comment by akhil-geekyants** [comment]
@pennyandsean just checked this. It is working fine. Attaching a gif.

Gif

![inputref](https://user-images.githubusercontent.com/27768184/35609379-11f6b4a2-0683-11e8-8ba4-61d4b7b43274.gif)

**Comment by pennyandsean** [comment]
Thanks for replying @akhil-geekyants, that just doesn't work for me, I have to use `getRef`.  I'm on 2.3.7.  All good anyway, it must be me.

**Comment by eedsilva** [comment]
I am on 2.3.8 and **getRef** also works for me.

**Comment by Amonith** [comment]
@akhil-geekyants That's because you didn't add the `floatingLabel` prop on `Item`. With this prop I'm also experiencing this issue. I'm on 2.3.10.

**Comment by blackdynamo** [comment]
This is silly that this has been open for over a year. There are other issues relating to the same problem. @akhil-geekyants your solution in the gif doesn't include `floatingLabel`. You have:

```<Item></Item>```

it fails with:

```<Item floatingLabel></Item>```

I don't know how much more clear we can get with the problem. I can't use the NativeBase Inputs because of this, I have to roll my own floating label solution.

This still exists in 2.4.1

**Comment by SupriyaKalghatgi** [comment]
@Amonith @blackdynamo The example by @akhil-geekyants includes `<Item floatingLabel>`
