### ISSUE TITLE
Toast.show is not a function

### ISSUE THREAD

**Issue by aklarfeld** [GeekyAnts/NativeBase#592]
I'm testing out the Toast functionality in iOS. I tried my own use function and the example function found in the docs (http://nativebase.io/docs/v2.0.0/components#toast) and I keep seeing the same error. I also made sure to call Toast inside of a Container.

I noticed in the docs, the component name is also "Toast" - is this intentional?

    "native-base": "^2.0.10",
    "react": "15.4.2",

Anyone else experiencing similar problems with Toast + NativeBase?

Thanks

**Comment by sankhadeeproy007** [comment]
Toast.show() will work from 2.0.12 onwards!

**Comment by aklarfeld** [comment]
Thanks :)

**Comment by LeoAref** [comment]
@sankhadeeproy007 This info should be in the docs 😉
