### ISSUE TITLE
"md-arro-down" instead of "md-arrow-down" on android

### ISSUE THREAD

**Issue by JanErikFoss** [GeekyAnts/NativeBase#594]
Using Icon with name "arrow-down", expecting to get an icon with a downwards arrow,
but on android I get this warning:

    Warning: Failed prop type: Invalid prop `name` of value `md-arro-down` supplied to `IconNB`, expected one of ["ios-add","ios-add-circle" .......
    ..... "md-wine","md-woman"].
    in IconNB (created by Styled(IconNB))
    in Styled(IconNB) (created by Icon)
    in Icon (created by Styled(Icon))
    in Styled(Icon) (created by Map)
    in RCTView (created by View)
    in View (created by Button)
    in TouchableNativeFeedback (created by Button)
    in Button (created by Styled(Button))
    in Styled(Button) (created by Map)
    in RCTView (created by View)

It seems there's an "r" missing in there.

Works fine on iOS.

React native 0.41.2
Native Base 2.0.12

**Comment by deneuv34** [comment]
hmmm... seems need fix here..... 
I just give PR for this...

**Comment by shivrajkumar** [comment]
Fixed.
