### ISSUE TITLE
The Keyboard won't show up after upgrading to RN 0.42.0

### ISSUE THREAD

**Issue by janzenz** [GeekyAnts/NativeBase#596]
## react-native
RN: 0.42.0
React: 15.4.2
NativeBase: 2.0.12
## Expected behaviour
Keyboard should come out after clicking the `<TextInput>` or `<Input>` in NativeBase
## Actual behaviour
No Keyboard will come out after clicking the `<Input>`
## Steps to reproduce (code snippet or screenshot)
Here's my code snippet:
```
     <StyleProvider style={getTheme(custom)}>
        <Container>
          <Header>
            <Left>
              <Button transparent onPress={() => this.popRoute()}>
                <Icon name="ios-arrow-back" />
              </Button>
            </Left>

            <Body>
              <Title>Login</Title>
            </Body>
            <Right></Right>
          </Header>
          <Content padder>
            <Form>
              <Item >
                <Input
                  placeholder="Email"
                  onChangeText={(text) => this.email = text} />
              </Item>
              <Item>
                <Input
                  secureTextEntry
                  placeholder="Password"
                  onChangeText={(text) => this.password = text} />
              </Item>
            </Form>

            <Button
              block
              success
              verticalSpacing
              onPress={this._login}>
              <Text>Login</Text>
            </Button>
          </Content>
        </Container>
      </StyleProvider>
```
## Screenshot of emulator/device
![screen capture on 2017-03-05 at 14-44-11](https://cloud.githubusercontent.com/assets/1410147/23585185/64e31128-01b2-11e7-8ce0-a67b0dbc79ed.gif)

## Is the bug present in both ios and android or in any one of them?
Testing only in iOS
## Any other additional info which would help us debug the issue quicker.
I've just upgraded RN from `0.41.2` to `0.42.0` and NativeBase at `2.0.12`

**Comment by sankhadeeproy007** [comment]
Can you try to figure out which component exactly is breaking it? Is it because of the `<Input />` or `<Content />`?

**Comment by janzenz** [comment]
@sankhadeeproy007 I just updated my issue report, I realized I didn't enclosed the `<Components>` in back ticks. Anyway, I tried adding `<Input/>` and `<TextInput/>` inside `<Content/>` and the result is the same. Of course when I remove `<Content/>` the Keyboard won't come out since it's the wrapper for `<KeyboardAwareScrollView/>`. Does that help?

**Comment by janzenz** [comment]
@sankhadeeproy007 sorry my bad! for some reason I disabled the keyboard on the iOS hardware. It's easy to miss because the hokey is `cmd+k`. Noob problems! Sorry for the bother.
