### ISSUE TITLE
Segment display issue

### ISSUE THREAD

**Issue by bluedusk** [GeekyAnts/NativeBase#598]
Hi, I got this issue on segment component, please have a look. Many thanks.

## react-native, react and native-base version
    "react-native": "0.41.2",
    "react": "15.4.2",
    "native-base": "^2.0.10",

## Expected behaviour
Segment Component display in the center of Header, as shown in document: http://nativebase.io/docs/v2.0.0/components#segment
## Actual behaviour
Segment button not showing in Header/Body.
## Steps to reproduce (code snippet or screenshot)

    <Container>
        <Header>
            <Left style={{borderWidth:1,borderColor:'green'}}>
              <Button transparent onPress={() => Actions.pop()}>
                <Icon name="arrow-back" />
              </Button>
            </Left>
            <Body style={{borderWidth:3,borderColor:'black'}}>
              <Segment style={{borderWidth:1,borderColor:'red'}}>
                <Button first active><Text>button</Text></Button>
              </Segment>
            </Body>
            <Right style={{borderWidth:1,borderColor:'blue'}}>
              {/* <Button transparent onPress={()=>{Actions['newItem']()}}><Icon name="search" /></Button> */}
              <Button transparent onPress={()=>{Actions['newItem']()}}><Text>Add</Text></Button>
            </Right>
        </Header>
        <Content padder>
          {/* { this.renderList() } */}
        </Content>
      </Container>

## Screenshot of emulator/device
![screenshot](http://7xkckh.com1.z0.glb.clouddn.com/screenshot1.png)
## Is the bug present in both ios and android or in any one of them?
Tested only on IOS emulator

**Comment by sankhadeeproy007** [comment]
If you want just one button in the segment, why not just add a Button instead of segment?

**Comment by bluedusk** [comment]
@sankhadeeproy007 Its the same issue for multiple buttons.

**Comment by sankhadeeproy007** [comment]
![screen shot 2017-03-09 at 6 43 40 pm](https://cloud.githubusercontent.com/assets/10998047/23751666/5726db7a-04f8-11e7-9e2c-195d129b14f6.png)
Seems to work pretty fine. Are you ejecting the variables?

**Comment by Norfeldt** [comment]
@sankhadeeproy007 I'm having the same issue and yes I have ejected the variables.

**Comment by shivrajkumar** [comment]
@Norfeldt @bluedusk If you had ejected the theme with your previous version and have upgraded the latest of NativeBase, you need to merge the old theme with the new theme.
That will resolve your issue.
Let me know if it works.

**Comment by Norfeldt** [comment]
I have deleted the ejected theme and it's still an issue

![screen shot 2017-04-18 at 19 03 27](https://cloud.githubusercontent.com/assets/678806/25143172/c6c61b68-2469-11e7-8475-c0a8967937ed.png)
```

export default class ScreenTabsDetails extends Component {
  render() {
    return (
      <Container>

        <Header>
          <Left>
            <Button transparent onPress={ () => this.props.navigator.pop() }>
              <Icon name='ios-backspace' />
            </Button>
          </Left>

          <Body>
            <Segment>
              <Button first><Text>1</Text></Button>
              <Button last><Text>2</Text></Button>
            </Segment>
          </Body>
 
         <Right />

        </Header>

        <Content padder>
          <Text>Hello NativeBase</Text>
        </Content>
...
```

**Comment by jrempel1** [comment]
This is still an issue in 2.1.5

```        <Header hasSegment>
          <Left>
            <Button onPress={() => goBack()} transparent>
              <Icon name="arrow-back" />
            </Button>
          </Left>
          <Body>
            <Segment>
              <Button
                first
                active={this.state.currentView == "detail"}
                onPress={() => this.setState({ currentView: "detail" })}
              >
                <Text>Detail</Text>
              </Button>
              <Button
                active={this.state.currentView == "map"}
                onPress={() => this.setState({ currentView: "map" })}
              >
                <Text>Map</Text>
              </Button>
            </Segment>
          </Body>
          <Right>
            <Button
              transparent
              onPress={() =>
                Share.share({
                  message: event.title,
                  dialogTitle: event.title,
                  url: event.website
                })}
            >
              <Icon ios="ios-share-outline" android="md-share" />
            </Button>
          </Right>
        </Header>
```

![misaligned-header](https://user-images.githubusercontent.com/1776510/28148176-1895342a-6753-11e7-8f33-6c046efcc95a.png)

**Comment by shivrajkumar** [comment]
@jrempel1 You can just pass flex properties to Segment component and Body to fix.
Say 
```
<Body style={{ flex: 1.5 }}>
 <Segment style={{ alignSelf: "flex-start" }}>
  ......
```
