### ISSUE TITLE
Content Scroll View

### ISSUE THREAD

**Issue by jreziga** [GeekyAnts/NativeBase#60]
Hello,

When I'm using InputGroup without a Content node, the height become a mess http://puu.sh/q06Qf/eb54690a3e.png I can't fix it whatever I do with styles.

The 2nd issue is a question : Is it possible to use a Content without Scrollable effect ?

Thanks !

**Comment by sankhadeeproy007** [comment]
Hi, can you try the latest updates pulling from master and check if that works for you. We'll publish once we're sure it works great.

**Comment by sankhadeeproy007** [comment]
Fixed with v0.5.0
