### ISSUE TITLE
modify header explanation in the docs

### ISSUE THREAD

**Issue by gijsbotje** [GeekyAnts/NativeBase#600]
i took me a week to realize this...

I wanted to change the color of the text in the statusbar.
Tried multiple times to add an StatusBar component in my components with no success.
finally it hit me, maybe it has to be defined inside the header...
And that turned out to be the fix.

This was not explained in the documentation of native base, so...
Maybe it should be explained in the docs that the StatusBar has to be inside the Header

**Comment by sankhadeeproy007** [comment]
We have added the `iosBarStyle` prop to the docs. thanks for reporting!
