### ISSUE TITLE
Current implementation of List is wrong.

### ISSUE THREAD

**Issue by ericvan76** [GeekyAnts/NativeBase#601]
https://github.com/GeekyAnts/NativeBase/blob/master/src/basic/List.js#L18-L19

This implementation looses tracking to the previous data, and `ListViewDataSource` will mark all records as `dirty`, and gonna re-render everything. Consider moving `new ListView.DataSource({ rowHasChanged: (r1, r2) => r1 !== r2 });` to constructor(), and call `ds.cloneWithRows(this.props.dataArray);` when new data arrives.

See ListViewSource:
https://github.com/facebook/react-native/blob/master/Libraries/CustomComponents/ListView/ListViewDataSource.js#L235-L240

**Comment by sankhadeeproy007** [comment]
Thanks for reporting! Will be fixed.

**Comment by sankhadeeproy007** [comment]
Reopening this till the new update is released.

**Comment by ericvan76** [comment]
The commit looks okay to me, thanks!

**Comment by stefan0s** [comment]
![listerror](https://cloud.githubusercontent.com/assets/13720159/23873498/ea5c1bea-083a-11e7-9ae7-cb641edbabbb.png)

After updating we receive the following error. Any help appreciated

Thank you

**Comment by ericvan76** [comment]
@stefan0s , I can see a problem in that commit, and in the mean time, can you try to pass-in dataArray=[] to see if it works?

**Comment by stefan0s** [comment]
Sure that works! I was wondering if we should replace our static List Items and use dataArray

**Comment by ericvan76** [comment]
@stefan0s, nothing is different if you use dataArray or not, native-base's List is just a wrapper to ListView, and dataArray is an easier way to create/manage DataSource for you. It's completely up to your. But unfortunately there is a bug at the moment, so keep the hack for now, and you should be able to remove it as long as my PR gets approved.
