### ISSUE TITLE
Customize styling issue

### ISSUE THREAD

**Issue by puzpuz** [GeekyAnts/NativeBase#602]
RN: 0.41.2
React: 15.4.2
Native base: 2.0.11

I was trying to customizing style using the following [documentation](http://nativebase.io/docs/v2.0.0/customize#themingNativeBaseApp).

I have eject my theme and using StyleProvider to do it.

```
...
import getTheme from './native-base-theme/components';
import platform from './native-base-theme/variables/platform';
...
<StyleProvider style={getTheme(platform)}>
  <Container>
    <Tabs>
      <Tab heading={<TabHeading style={{ backgroundColor: platform.tabActiveBgColor }}><Text>{I18n.t('activity_news_tab')}</Text></TabHeading>}>
        <NewsActivityTab />
      </Tab>
      <Tab heading={<TabHeading style={{ backgroundColor: platform.tabActiveBgColor }}><Text>{I18n.t('maintenance_news_tab')}</Text></TabHeading>}>
        <NewsMaintenanceTab />        
      </Tab>
    </Tabs>
  </Container>
</StyleProvider>


```
But I got this error
![screenshot_1488783901](https://cloud.githubusercontent.com/assets/3850502/23599843/6316976c-027e-11e7-9c4c-1d35c6f3c0da.png)

platform.js line:173
```
get statusBarColor() {
    return color(this.toolbarDefaultBg).darken(0.2).hexString();
},
```

tested on android emulator

**Comment by nqhung139** [comment]
.hexString() -> hex() to fixed issue :)

**Comment by puzpuz** [comment]
Thank you, it solve the problem
For those who have the same problem you need to modify it on Line:173, 246, and 283 in platform.js

**Comment by davidsneal** [comment]
Oddly for me (using 2.1.5) I had to change all instances of `hex()` to `hexString()`

**Comment by nonameolsson** [comment]
I had to do the same in `v.2.3.0`.

**Comment by imwr** [comment]
I had to do the same in v.2.3.2 and v.2.3.3.
