### ISSUE TITLE
StyleProvider

### ISSUE THREAD

**Issue by stefan0s** [GeekyAnts/NativeBase#603]
Hi! 

We have started our project from native-starter-kit and we have upgraded RN 0.41 and NB 2.0.12

Application works fine, but style is not rendering. We have just add StyleProvider on the App.js (root component) like this <StyleProvider style={getTheme(material)}>

http://nativebase.io/docs/v2.0.0/customize#themingNativeBaseApp

Default theming is rendering on both ios/android. Should we do anything else?

**Comment by sankhadeeproy007** [comment]
Can I see some code snippets? The directory structure?

**Comment by stefan0s** [comment]
This is our base starter-kit
https://github.com/start-react/native-starter-kit

on js/App.js we wrap component with StyleProvider

**Comment by sankhadeeproy007** [comment]
We have used the `StyleProvider` [here](https://github.com/GeekyAnts/NativeBase-KitchenSink/blob/master/js/AppNavigator.js). This pattern should work.

**Comment by stefan0s** [comment]
we are still getting error!

components/index.js
on const cssifyTheme


undefined is not a function (Evaluating styleName.indexOf('.'))

**Comment by sankhadeeproy007** [comment]
Please post a link to the code you're trying because it seems to work pretty fine with other apps.

**Comment by surikat** [comment]
In native-starter-kit this is how I handled it:
in src/containers/ui/DrawerContainer.js

...
    
    import { StyleProvider, Container } from 'native-base';
    import getTheme from '../../../native-base-theme/components';
    import platform from '../../../native-base-theme/variables/platform';
    
...

    <View style={{ backgroundColor: '#000', flex: 1 }}>
        <Container>
            <StyleProvider style={getTheme(platform)}>
                  <DefaultRenderer navigationState={children[0]} onNavigate={this.props.onNavigate} />
            </StyleProvider>
        </Container>
    </View>
    
...

**Comment by lil5** [comment]
I get the error when I create an object in one file(e.g. `../../palette.js`) import it into the `variables/theme.js` file and use vars from the external (`palette.primaryColor`) file

```js
// theme.js (copy of platform)
import color from 'color'
import { Platform, Dimensions, PixelRatio } from 'react-native'

import palette from './../../palette'

const deviceHeight = Dimensions.get('window').height
const deviceWidth = Dimensions.get('window').width
const platform = Platform.OS
const platformStyle = undefined
const isIphoneX =
  platform === 'ios' && deviceHeight === 812 && deviceWidth === 375

export default {
  platformStyle,
  platform,

  // Android
  androidRipple: false,
  androidRippleColor: color(palette.primaryColor).alpha(0.3),
  androidRippleColorDark: 'rgba(0, 0, 0, 0.15)',
  btnUppercaseAndroidText: true,

  // Badge
  badgeBg: palette.primaryTextColor,
  badgeColor: palette.alternateTextColor,
  badgePadding: platform === 'ios' ? 3 : 0,
...etc
```
