### ISSUE TITLE
How to remove ellipsis in the Title

### ISSUE THREAD

**Issue by freshnewegg** [GeekyAnts/NativeBase#605]
How do you remove the ellipsis in the Body component of the header?

When I have a longer title, it seems to always show ellipsis. How can I display the full title?

<img width="378" alt="screen shot 2017-03-06 at 3 47 22 pm" src="https://cloud.githubusercontent.com/assets/5714313/23628998/3bc902e8-0284-11e7-93b3-5620e9b32f42.png">

I've gone through the documentation a few times and haven't seen anything. It's not my styles, I've removed those and the ellipsis still show. Could someone point me in the right direction?

## react-native, react and native-base version
react-native 0.40.0, react 15.4.1, "native-base":  "2.0.x",
## Steps to reproduce (code snippet or screenshot)
`			<Header style={styles.header}>
				<Left></Left>
				<Body>
					<Title style={styles.text_white}>{'Purchase Completed!'}</Title>
            	</Body>
            	<Right></Right>
            </Header>`

**Comment by sankhadeeproy007** [comment]
Related to #567. Please check the solution there. Alternatively, you can try `<Body style={{flex: 3}}>` to fix it.

**Comment by thien-thach** [comment]
@sankhadeeproy007 thanks so much, it worked

**Comment by hardcodet** [comment]
@sankhadeeproy007 This feels like a hack to a probably simple issue. Any chance we get proper layout options for headers and titles?

**Comment by sfm2222** [comment]
@sankhadeeproy007  Im unable to resolve using  <Body style={{flex: 3}}> as it is not on center on every device.

**Comment by harikrishnanp** [comment]
Use `<Body style={{flex: 2}}>` If you don't need longer title.

**Comment by sfm2222** [comment]
I'm using a very long title "TEST XXX XXXXX XXXXX" 17 characters long with 3 blank spaces. Any suggestions?

**Comment by programadornatal** [comment]
Thanks, this  style={{flex: 2}} work for me
