### ISSUE TITLE
Button not clickable in header

### ISSUE THREAD

**Issue by natashache** [GeekyAnts/NativeBase#608]
Button is unresponsive when clicked on, but only when it's placed in the Header. In the Content block it works fine.

Here's the code:
```
    <LinearGradient colors={['#F0CB35', '#C02425']} style={styles.linearGradient}>
      <Container>
        <Header style={{backgroundColor: 'transparent', borderWidth: 0}}>
          <Left>
            <Button transparent
              onPress={ () => this.props.navigation.goBack(null) }>
              <Icon name='ios-arrow-back' />
            </Button>
          </Left>
          <Body />
          <Right />
        </Header>
         <Content style={styles.container}>
            <Button transparent
              onPress={ () => this.props.navigation.goBack(null) }>
              <Icon name='ios-arrow-back' />
            </Button>
          </Content>
      </Container>
    </LinearGradient>       
```
The first button (in header) doesn't work and the second button (in content) works.
## react-native, react and native-base version
react native 0.41. native base 2.0.12.
## Is the bug present in both ios and android or in any one of them?
Only tried on ios emulator.

Also, I want to get rid of the bottom border line for the header. Tried setting borderColor to 'transparent' and borderWidth to 0. Neither works.

**Comment by sankhadeeproy007** [comment]
![button](https://cloud.githubusercontent.com/assets/10998047/23646725/265cd81c-0338-11e7-90ee-0f4d705a87c2.gif)
The button seems to work pretty well. Also just add the `hasTabs` prop to header for no border.
Can you just try doing a regular alert and check if the button responds?

**Comment by natashache** [comment]
@sankhadeeproy007 Thanks! I figured out what the problem was. I set the style of the Content block with `{position: 'absolute', flex: 1}`. It lay over the Header block and covered the button in header. But I didn't know it because the background is transparent. I deleted that style setting and it's now working. Sorry about the false alarm.

**Comment by sankhadeeproy007** [comment]
Glad it worked!
