### ISSUE TITLE
Nested text in CardItem has different font

### ISSUE THREAD

**Issue by amelzer** [GeekyAnts/NativeBase#609]
## react-native, react and native-base version
navite-base version 2.0.9

## Expected behaviour
Font size stays the same

## Actual behaviour
Inner text has slightly bigger font size

## Steps to reproduce (code snippet or screenshot)
       <Card>
         <CardItem>
          <Body>
            <Text>A<Text>A</Text>A</Text>
          </Body>
         </CardItem>
      </Card>
## Screenshot of emulator/device
![simulator screen shot 7 mar 2017 12 05 17](https://cloud.githubusercontent.com/assets/1628866/23653862/5eaac8c8-032e-11e7-9e50-2d1772d52ebb.png)

## Is the bug present in both ios and android or in any one of them?
both 

## Any other additional info which would help us debug the issue quicker.
Is not present when CardItem is ommited.

**Comment by shivrajkumar** [comment]
#610
