### ISSUE TITLE
NativeBase's Text component does't support nested styling

### ISSUE THREAD

**Issue by jeanniton-mnr** [GeekyAnts/NativeBase#610]
Hi!
Thank you for providing NativeBase UI.

I just want to mention, while I don't if it something that can be fixed,  that the Text component of native-base doesn't support nested styling.

I spent a great amount of time trying to figure out why I was having the issue making inherited style until I have tried to use the Text component from "pure" React Native. Then now, I understand nested styling it was not supported by react-base.

Thanks!

Version: 
"react-native": "0.38.0",
"native-base": "^2.0.8",

**Comment by devmnrj** [comment]
Although, there is no Text Component documented on native-base website. But I saw you were always using the Text component from native-base instead of react-native.

Like : import { Container, Content, Button, Text } from 'native-base'; found at http://nativebase.io/docs/v2.0.0/components#button

So I thought it was a good practice.

**Comment by sankhadeeproy007** [comment]
Please tell us what you are trying to do and what is the error you are getting. Any screenshots, code snippets would be helpful.

**Comment by devmnrj** [comment]
![react-native-text-demo](https://cloud.githubusercontent.com/assets/11714176/23821655/8375c866-0607-11e7-868d-ab1ccec46493.gif)

**Comment by devmnrj** [comment]
Normal behaviour sample: https://facebook.github.io/react-native/docs/text.html

**Comment by bitsal** [comment]
+1
I have a lot of warnings with Styled(Text).

**Comment by rohanBagchi** [comment]
<img width="325" alt="screen shot 2018-02-08 at 11 29 52 am" src="https://user-images.githubusercontent.com/5557094/35957786-6bd0b914-0cc3-11e8-8b5d-4172ed9ccd25.png">

**Comment by SupriyaKalghatgi** [comment]
@rohanBagchi Thats something wrong that you are doing

**Comment by suvenduchhatoi** [comment]
@jeanniton-mnr 
<Text> component of native-base perfectly supports nested styling.
Check for current versions of "native-base" and "react-native"
See the docs of NativeBase:-https://docs.nativebase.io/docs/Compatibility.html

An example code for you-
```

import React, { Component } from "react";
import { View } from "react-native";
import { Text } from "native-base";
export default class BoldAndBeautiful extends Component {
  render() {
    return (
      <View style={{ marginTop: 30 }}>
        <Text style={{ fontWeight: "bold" }}>
          I am bold
          <Text style={{ color: "red" }}>and red</Text>
        </Text>
      </View>
    );
  }
}
```

**Comment by suvenduchhatoi** [comment]
@rohanBagchi 
You are not importing StyleSheet styles properly to the Text component...
Try this way:
```
import React, { Component } from "react";
import { View, StyleSheet } from "react-native";
import { Text } from "native-base";
const styles = StyleSheet.create({
  labelStyle: {
    fontSize: 20,
    color: "#000",
    lineHeight: 20,
  },
});
export default class BoldAndBeautiful extends Component {
  render() {
    return (
      <View style={{ marginTop: 30 }}>
        <Text style={styles.labelStyle}>
          I am bold
          <Text style={{ color: "red" }}>and red</Text>
        </Text>
      </View>
    );
  }
}
```

**Comment by suvenduchhatoi** [comment]
Closing the issue due to no response for a while...Hope your issue has been resolved.You can reopen the issue if you still feel the issue is exclusive to "native-base"...

**Comment by suvenduchhatoi** [comment]
Closing the issue due to no response for a while...Hope your issue has been resolved.You can reopen the issue if you still feel the issue is exclusive to "native-base"...

**Comment by hugobarragon** [comment]
Does not work as expexted:  
native base
![image](https://user-images.githubusercontent.com/35630927/133773909-bfc6bebd-bf8e-4473-a20f-2eb0c22b8783.png)
should work as this:  
![image](https://user-images.githubusercontent.com/35630927/133774014-3859d12d-e1ff-4bc0-834f-561dd6179962.png)
