### ISSUE TITLE
Cannot Override Text Color

### ISSUE THREAD

**Issue by gavinkilbride** [GeekyAnts/NativeBase#613]
## react-native, react and native-base version
2.0.9
## Expected behaviour
I should be able to override the image color of the <Text> tag with the following:
[Override commonColor](http://www.tiikoni.com/tis/view/?id=cac68c3)
I am using the theme like this:
`import theme from "../../../../themes/base-theme";`
and applying the theme like this
`<StyleProvider style={getTheme(theme)}>`
## Actual behaviour
the `<Title>` color in the image above is overridden correctly but the `<Text>` color is not.
have tried to debug as far as I can and the styles are being overridden in cssifyTheme method and are returned in the correct format but the `<Text>` is not being rendered in the correct color.
## Steps to reproduce (code snippet or screenshot)
[NativeBase.Text Color](http://www.tiikoni.com/tis/view/?id=188690a)
## Screenshot of emulator/device
[Incorrect text of subtitle text under large orange title](http://www.tiikoni.com/tis/view/?id=efb14ff)
## Is the bug present in both ios and android or in any one of them?
Only tested in iOS emulator.
## Any other additional info which would help us debug the issue quicker.
Not really. I have tried without the spread operator but that doesn't make any difference.

**Comment by sankhadeeproy007** [comment]
Been fixed with [this](https://github.com/GeekyAnts/NativeBase/commit/8d58e661a3023fe300646fe42aac58db3473bc5e). Please upgrade for this fix.
