### ISSUE TITLE
Button text color doesn't change

### ISSUE THREAD

**Issue by gsteyn** [GeekyAnts/NativeBase#615]
## react-native, react and native-base version
"react": "15.4.1",
"react-native": "^0.41.2",
"native-base": "2.0.10",

## Expected behaviour
Text color of button to change according to the `color` value given in `textStyle`.

## Actual behaviour
The color does not change and stays the default color.

## Steps to reproduce (code snippet or screenshot)
`<Button transparent textStyle={{color: '#595DB'}}>
                            <Text>Send</Text>
                        </Button>`

## Is the bug present in both ios and android or in any one of them?
It's present on Android. I'm not able to test on iOS.

**Comment by gsteyn** [comment]
Not sure if this is related to #613? If it is, feel free to close this issue.

**Comment by gsteyn** [comment]
This was a mistake by me. I imported Text from react-native, instead of nativebase. Once I used the Text component from nativebase, the text styling took affect.

**Comment by sankhadeeproy007** [comment]
There is no need to use `textStyle`, you can directly use style with the `<Text>` component.

**Comment by thg303** [comment]
looks like `textStyle` is removed from Button component. docs need to be updated accordingly.
