### ISSUE TITLE
Listener for Tabs

### ISSUE THREAD

**Issue by justfede** [GeekyAnts/NativeBase#616]
Hi guys! There's any way to fire an event when a tab is selected? 

I tried with componentDidMount but it only fires once.. (I need to handle several tab changes)

Thanks!

**Comment by sankhadeeproy007** [comment]
`<Tabs onChangeTab={(i, ref)=> console.log(i)}>`
You can use the onChangeTab callback.

**Comment by naman03malhotra** [comment]
Please add this to docs as well.

**Comment by ikhsanalatsary** [comment]
the right is `<Tabs onChangeTab={({ i, ref, from })=> console.log(i)}>`

**Comment by n-sviridenko** [comment]
@rubinjohny same issue. https://github.com/GeekyAnts/NativeBase/issues/2359
