### ISSUE TITLE
Can't use <Text> in TouchableHighlight

### ISSUE THREAD

**Issue by FlowerGeoji** [GeekyAnts/NativeBase#619]
Hi! Thanks for trying out NativeBase!
Due to the overwhelming requests and issues/questions we ask you to add the following details with your issue.

react-native version : 0.41.2
native-base version : 2.0.12

![screenshot_2017-03-09-20-20-12](https://cloud.githubusercontent.com/assets/18716984/23748234/146a2842-0506-11e7-93ae-452fb305a013.png)

`<Text>` Component in native-base can not use in `<TouchableHighlight>` Component in react-native
like this
`<TouchableHighlight`
`         underlayColor='#009D52'`
`         activeOpacity={1.0}`
`         onPress={()=>{this.props.onClickCoinExchange()}}>`
`         <Text style={styles.coinButtonText}>(Text)</Text>`
`</TouchableHighlight>`

https://facebook.github.io/react-native/docs/direct-manipulation.html#composite-components-and-setnativeprops

**Comment by shivrajkumar** [comment]
![text issue](https://cloud.githubusercontent.com/assets/17001305/23943192/9d1dead8-0994-11e7-9c0a-82c18586b80f.gif)

**Comment by SupriyaKalghatgi** [comment]
#574
