### ISSUE TITLE
Card style type definition issue.

### ISSUE THREAD

**Issue by asdacap** [GeekyAnts/NativeBase#620]
Hi there, I may have found an issue, on https://github.com/GeekyAnts/NativeBase/blob/master/index.d.ts#L384,

```
interface Card extends React.ViewProperties, ReactListViewProperties {
     dataArray?: Array<any>,
     style?: React.Ref<React.ViewProperties | React.ListViewProperties>
     ref?: React.Ref<React.ViewProperties | ReactListViewProperties>,
}
```
Why is the `style` a `React.Ref`?

**Comment by SupriyaKalghatgi** [comment]
@asdacap Could you check with [2.1.4](https://github.com/GeekyAnts/NativeBase/releases/tag/v2.1.4)?

**Comment by asdacap** [comment]
@SupriyaKalghatgi it seems to have been fixed on the latest release. Thanks.

**Comment by SupriyaKalghatgi** [comment]
@asdacap Good to know that you got it working
