### ISSUE TITLE
Undefined is not an object using Toast component.

### ISSUE THREAD

**Issue by iicdii** [GeekyAnts/NativeBase#621]
## react-native, react and native-base version
    "native-base": "^2.0.12",
    "react": "15.4.2",
    "react-native": "^0.42.0"
## Expected behaviour
Toast component must be shown.
## Actual behaviour
Error occurred.
## Steps to reproduce (code snippet or screenshot)
in render code, it implements "onValueChange" function when item is picked.
```javascript
<Container>
    ...
	  <Picker
	        selectedValue={tempStartYear}
	        style={{width: 80, alignSelf: 'flex-end'}}
	        onValueChange={this.onValueChange.bind(this, 'tempStartYear')}>
	        {years.map((year, index) =>
	          <Picker.Item key={index} label={year} value={year} />
	        )}
	  </Picker>
    ...
</Container>
```

in onValueChange function, It delivers data to "isDateValidate" function
```javascript
onValueChange(key, value) {
	const newState = {};
	newState[key] = value;

	if (this.isDateValidate(key, value))
	  this.setState(newState);
};
```

in isDateValidate function, I called Toast.show when data is invalid.
I tested with invalid data and it shows me an error.
```javascript
isDateValidate(key, value) {
  const {
    tempStartYear, tempStartMonth, tempEndYear, tempEndMonth
  } = this.state;

  console.log(key + ': ' + value);
  console.log('tempStartYear: ' + tempStartYear);

  if (key === 'tempEndYear' && value > tempStartYear) {
    Toast.show({
      text: 'error test',
      position: 'bottom',
      buttonText: 'Okay'
    });
    return false;
  }

  return true;
}
```
## Screenshot of emulator/device
![image](https://cloud.githubusercontent.com/assets/4951716/23758614/aa26438a-052d-11e7-9946-ca3fbb5331dd.png)
## Is the bug present in both ios and android or in any one of them?
I only tested in Android.

**Comment by deneuv34** [comment]
@iicdii I think I got this bug too in android and iOS

**Comment by sankhadeeproy007** [comment]
Can you get the toast to render simply with Toast.show({config})? Or does the toast not render at all?

**Comment by iicdii** [comment]
@sankhadeeproy007 Okay, I closed Genymotion and try to reinstall npm, rebuild (react-native run-android) and run it works fine now.

**Comment by sankhadeeproy007** [comment]
So can you close this issue?

**Comment by amirmatin** [comment]
I have done the steps above but still getting this error..

**Comment by galcivar** [comment]
Error here aswell
