### ISSUE TITLE
Using headerComponent in Picker causes exception V2.0.12 - iOS only

### ISSUE THREAD

**Issue by brainbow91** [GeekyAnts/NativeBase#623]
I tried to use the Picker component with a custom headerComponent on iOS. But using this headerComponent attribute in picker causes an exception "RawText " " must be wrapped in an explicit <Text> component". I definitely don't have any " " in my headerComponent-Definition. This exception also pops up when using the example from NativeBase website.

![ios_picker_headercomponent](https://cloud.githubusercontent.com/assets/26322808/23789929/468c63e0-057d-11e7-82c7-fdd99c5f05c0.jpg)
![source_code_picker_headercompontent](https://cloud.githubusercontent.com/assets/26322808/23789933/4a450fb4-057d-11e7-9011-ecd9040aade4.jpg)

**Comment by pikitgb** [comment]
i had same issue today, it was a space that for some reason was returning that error.

**Comment by wjnxiang** [comment]
when I had used the <Text>Demo</Text> , It happened.
