### ISSUE TITLE
Adding Sticky list section for ios and android?(question)

### ISSUE THREAD

**Issue by jasan-s** [GeekyAnts/NativeBase#625]

**Comment by sankhadeeproy007** [comment]
Not yet, but maybe with RN's new flat list implementation, we'll have that as well.

**Comment by omerdn1** [comment]
@sankhadeeproy007  When are you going to implement FlatList to your code?

**Comment by Jasbir23** [comment]
@here Example for FlatList with sticky headers => http://docs.nativebase.io/docs/FlatListExample.html

**Comment by Ernoff** [comment]
Above link returns 404.. Page not Found!!

**Comment by Jasbir23** [comment]
@Ernoff updated link 
[Flatlist Example](http://docs.nativebase.io/docs/examples/FlatListExample.html)
