### ISSUE TITLE
Deck Swiper - Goto Index (wish/feature)

### ISSUE THREAD

**Issue by fbacker** [GeekyAnts/NativeBase#626]
"native-base": "2.0.7",
    "react": "15.4.2",
    "react-native": "^0.41.2",

Is it possible to choose 'selected index' for the Deck Swiper?

For e.g. Having a Deck Swiper showing images. Below a have a grid of thumbnails (ListView). When I press the thumbnail I would like the Deck Swiper to select the correct view.

    this.refs.deckswiper.selectedIndex(2)

Also having the Deck Swiper event trigger when a deck is selected would be kickass

    onSwipe={(index) => console.log('new card is selected',index)}

**Comment by sankhadeeproy007** [comment]
We'll see if that can be done :)

**Comment by ll0406** [comment]
YES!! please implement this feature!

**Comment by philohelp** [comment]
Yes onSwipe={(index) => console.log('new card is selected',index)} would be a huge gain !

**Comment by cinder92** [comment]
is there any update on this? :)

**Comment by dienast** [comment]
This would be a huge improvement. +1

**Comment by miukki** [comment]
![image](https://user-images.githubusercontent.com/132497/38022711-d5eea418-32b2-11e8-8731-d8de4b3306b3.png)
8(

**Comment by gupta-ji6** [comment]
Kindly add this as early as possible. This is a very useful feature

**Comment by SupriyaKalghatgi** [comment]
#38

**Comment by arjun-bhatt** [comment]
Any update?
