### ISSUE TITLE
Picker not working when debugging

### ISSUE THREAD

**Issue by craigcoles** [GeekyAnts/NativeBase#628]
## Versions

```
"react": "15.4.2",
"react-native": "0.42.0",
"native-base": "^2.0.12",
```

## Expected behaviour

Whilst debugging on iOS, when clicking on the picker, picker items should be displayed.

## Actual behaviour

Whilst debugging on iOS, clicking on the picker causes it to do nothing, and clicking it again causes the app to crash.

## Screenshot of emulator/device

![ezgif-2-39f7c22455](https://cloud.githubusercontent.com/assets/996430/23805514/12bf27da-05b6-11e7-8bbc-34c90f3b9ccf.gif)

**Comment by janzenz** [comment]
@craigcoles same issue.

**Comment by sankhadeeproy007** [comment]
It's an issue with react-native itself.
https://github.com/facebook/react-native/issues/12777

**Comment by sankhadeeproy007** [comment]
Upgrade to RN 0.42.2 for the fix.

**Comment by craigcoles** [comment]
Cheers @sankhadeeproy007 👍

**Comment by n-sviridenko** [comment]
Still having this issue. Using expo `v30.0.1`
