### ISSUE TITLE
icon color not working Form item floating labels

### ISSUE THREAD

**Issue by iiitmahesh** [GeekyAnts/NativeBase#629]
**icon color not working Form item floating labels**

I have checked in mobile inspector, it is (icon) showing color #000  

```
`import {Container, Badge,Text, Button, Content, Form, Item, Input , Label,Icon} from 'native-base';`
```
```
<View style={[ styles.bg]}>
    <Form>
        <Item floatingLabel>
            <Icon style={{color: '#fff'}} name='ios-person-outline' />
            <Label>Username</Label>
            <Input />
        </Item>
        <Item floatingLabel>
            <Icon style={{color: '#fff'}} name='ios-lock-outline' />
            <Label>Password</Label>
            <Input />
        </Item>
    </Form>
</View>

```

**Comment by iiitmahesh** [comment]
**non floating form item  working fine,** only floating variable not working 

```
<Form>
    <Item>
        <Icon style={{color: '#fff'}} name='ios-person-outline' />
        <Input placeholder='Username' />
    </Item>
    <Item>
        <Icon style={{color: '#fff'}} name='ios-lock-outline' />
        <Input placeholder='Password' />
        <Input />
    </Item>
</Form>

```

**Comment by sankhadeeproy007** [comment]
Thanks, for reporting. Will be looked into.
cc @shivrajkumar

**Comment by iambanh2** [comment]
I get this error. :)

**Comment by GeekRishabh** [comment]
@iambanh2 @iiitmahesh what you guys can do is to add 

```
  '.floatingLabel': {
        'NativeBase.Input': {
          height: 60,
          top: 8,
        },
        'NativeBase.Icon': {
          color:'blue',
        },

        'NativeBase.Label': {
          top: 8,
        },
      },
```
in the native-base-theme/components/Item.js 
It worked for me .Give it a try .

**Comment by AggarwalAnkit** [comment]
@shivrajkumar I am still getting this issue. Icon not appearing when using floating label. my configuration is as follows:

    "native-base": "2.2.0",
    "react": "16.0.0-alpha.12",
    "react-native": "0.45.1",

**Comment by AggarwalAnkit** [comment]
@GeekRishabh your solution also didn't work for me. I am new to react-native. Can someone please help me with this issue. @shivrajkumar can you reopen this issue?

**Comment by crazydev71** [comment]
Same issue for me. color prop is not working in floating label. Is there any solution?

**Comment by AggarwalAnkit** [comment]
@crazydev71 for now I am writing Icon component outside the Item component and that is working fine.
