### ISSUE TITLE
Controlled InputGroup dismisses keyboard after each character press

### ISSUE THREAD

**Issue by sodik82** [GeekyAnts/NativeBase#63]
After each character the keyboard is dismissed (seems like input looses the focus) however I would expect the keyboard to be opened while typing.

Not working example can be found e.g. here https://github.com/sodik82/mhd-simple/blob/2a59975e003a39ab5427fbc430c4c1c0f8b8dec4/js/components/home/index.js#L27

Notes: 
1. Classic RN `TextInput` works fine (see example)
2. When I remove `InputGroup` and leave only `Input` - keyboard works normally - but I loose icon etc. (but it is expected in such case). 

My environment: IOS simulator

**Comment by sankhadeeproy007** [comment]
Can you try upgrading to RN 0.29 and see if the error persists?

**Comment by sodik82** [comment]
I started with latest start-react/native-starter-kit which contained `native-base@0.4.7`. The problem seems to be resolved with upgrading to version `0.5`
