### ISSUE TITLE
[Form] Component has a slight padding on the left.

### ISSUE THREAD

**Issue by janzenz** [GeekyAnts/NativeBase#630]
react-native: 0.42.0
react: 15.4.2
native-base: 2.0.12

## Expected behaviour
The spacing of the form inputs should be consistent on the left and right.
## Actual behaviour
There is a slightly larger spacing on the left side of the form inputs. Notice the alignment of the button and the form inputs on the left side.

## Steps to reproduce (code snippet or screenshot)
![screen shot 2017-03-11 at 19 38 48](https://cloud.githubusercontent.com/assets/1410147/23822978/f53d9e7a-0692-11e7-9f54-a680156f2444.png)

## Is the bug present in both ios and android or in any one of them?
Tested only on iOS
## Any other additional info which would help us debug the issue quicker.

The bug only happens when the input items are enclosed within the `<Form/>` tag.
I'm using this structure: 

```
           <Form>
              <Item>
                <Input
                  placeholder="First Name"
                  onChangeText={(text) => this.firstName = text} />
              </Item>
              <Item>
                <Input
                  placeholder="Last Name"
                  onChangeText={(text) => this.lastName = text} />
              </Item>
              <Item>
                <Input
                  placeholder="Email"
                  onChangeText={(text) => this.email = text} />
              </Item>
              <Item {...(email === confirmEmail && { success: true })}>
                <Input
                  placeholder="Confirm Email"
                  onChangeText={(text) => this.setState({email: text})} />
                  <Icon name='checkmark-circle' />
              </Item>
              <Item>
                <Input
                  placeholder="Mobile No."
                  onChangeText={(text) => this.setState({mobile: text})} />
              </Item>
              <Item>
                <Input
                  placeholder="Password"
                  secureTextEntry
                  onChangeText={(text) => this.password = text} />
              </Item>
              <Item success>
                <Input
                  placeholder="Confirm Password"
                  secureTextEntry
                  onChangeText={(text) => this.confirmPassword = text} />
                  <Icon name='checkmark-circle' />
              </Item>
            </Form>
```

**Comment by mhaagens** [comment]
Experiencing the same.

**Comment by janzenz** [comment]
@mhaagens I've resolved it by removing the `<Form>` tag. But I'm not sure what the side-effects will be. Nonetheless, it works for now.

**Comment by sankhadeeproy007** [comment]
It's not a bug. That is how the design guidelines specify the Forms and Lists to be.

**Comment by janzenz** [comment]
@sankhadeeproy007 Thanks for clarifying, I just followed the documentation example for this one. If that's the case then which should be followed? Keeping everything inside <Form> or keeping the <Item> component and just remove the <Form> tag?

**Comment by sankhadeeproy007** [comment]
The tag is just for adding the paddings and making it look better. It has no effect on how you handlw your data. So whatever makes your inputs work well, go with that.

**Comment by janzenz** [comment]
I agree. Do you think the Documentation can be updated to clarify this? If so I'll be happy to add.

**Comment by gsdias** [comment]
@sankhadeeproy007 its a default style, so how can we override that style in the List and ListItem. I tried to put margin: 0 and padding: 0 in both elements but still getting the left padding while the right padding is gone.

**Comment by ashkonhakimi** [comment]
I got it to work as follows. I added these styles to my ListItem. The black on either side of the image below is just the simulator. There's no space. 

`  width: '100%',
    marginLeft: 0,
    paddingLeft: 0,
    paddingRight: 0,
    marginRight: 0`

<img width="334" alt="screen shot 2017-10-31 at 3 34 33 am" src="https://user-images.githubusercontent.com/5055808/32214520-210965ea-bded-11e7-91ff-eba212fd329f.png">

**Comment by Bai-Jie** [comment]
This design guidelines can be customize through https://docs.nativebase.io/Customize.html#Customize
