### ISSUE TITLE
App runs slow on IOS device

### ISSUE THREAD

**Issue by bluedusk** [GeekyAnts/NativeBase#631]
App runs slow on IOS device (IPAD4, IOS10) while woks fine on simulator.  Release mode also tried, still pretty slow. Any idea why?  Thanks a lot.

update:
It seems that when remote js debugging in on, it works fine on device.

## react-native, react and native-base version
"react-native": "0.41.2",
"react": "15.4.2",
"native-base": "^2.0.10",

**Comment by sankhadeeproy007** [comment]
You need to remove all your console log statements. As they tend to create some lag.

**Comment by bluedusk** [comment]
@sankhadeeproy007 Thanks for your reply. I comment all `console.log` but still slow with debugger off. And does release mode affected by console.log ? 
performance comparison after comment all console.log: 
>    Dev mode with debugger on > Dev mode with debugger off ≈ Release mode

**Comment by sankhadeeproy007** [comment]
If you are running on xcode, can you check the logger there if anything is getting logged?

**Comment by shivrajkumar** [comment]
Performance improved with v2.1.0
