### ISSUE TITLE
Footer Tab Active Color

### ISSUE THREAD

**Issue by ahsanazwar** [GeekyAnts/NativeBase#632]
How can I change the selected tab background color in footer tab on select
This is my code:

`
'use strict';
import React,{Component} from 'react';

import {StyleProvider,Footer,Header,Container,Icon,Title,Content,Button,FooterTab,Body} from 'native-base';
import {Text} from 'react-native';
import Selling from './selling';
import ManageStore from './manage_store'; // your first screen
import ManageOrder from './manage_order';
import UserProfile from './userProfile';
import getTheme from '../theme/components';
import material from '../theme/variables/material';

class SellerDashboard extends Component {
   
  renderSelectedTab () {
    switch (this.state.selectedTab) {
      case 'selling':
       return (<Selling{...this.props}/>);
        break;
      case 'manage_store':
       return (<ManageStore{...this.props}/>);
        break;
      case 'manage_order':
        return (<ManageOrder{...this.props}/>);
        break;
      case 'userProfile':
        return (<UserProfile/>);
        break;   
    }
  }
   
   constructor(props) {
     super(props);
   
     this.state = {
      selectedTab: "selling"
     };
   }

      render() {
    return (
        <Container style={{backgroundColor:'white'}}>
          
          <Content>
            {this.renderSelectedTab()}
          </Content>
       <StyleProvider style={getTheme(material)}>        
        <Footer>
          <FooterTab>
            <Button style={{backgroundColor:'#99004d'}} 
                    active={this.setState.selectedTab==='selling'} 
               onPress={() => this.setState({selectedTab: 'selling'})}>
                 <Icon ios='ios-map-outline' android="md-map" style={{color: 'black'}}/>
               <Text>Selling</Text>
            </Button>

            <Button 
               onPress={() => this.setState({selectedTab: 'manage_store'})}>
               <Icon ios='ios-cart-outline' android="md-cart" style={{color: 'black'}}/>
               <Text>Store</Text>
            </Button>

            <Button style={{backgroundColor:'#99004d'}} onPress={() => this.setState({selectedTab: 'manage_order'})}>
               <Icon ios='ios-pricetag-outline' android="md-pricetag" style={{color: 'black'}}/>
               <Text>MyOrder</Text>
            </Button>

            <Button style={{backgroundColor:'#99004d'}} onPress={() => this.setState({selectedTab: 'userProfile'})}>
               <Icon ios='ios-person-outline' android="md-person" style={{color: 'black'}}/>
               <Text>Profile</Text>
            </Button>
           
           </FooterTab>
        </Footer>
        </StyleProvider>
        </Container>
     );
  }
}

export default SellerDashboard;`

**Comment by sankhadeeproy007** [comment]
By changing the values [here](https://github.com/GeekyAnts/NativeBase/blob/master/src/theme/components/FooterTab.js#L24) and/or [here](https://github.com/GeekyAnts/NativeBase/blob/master/src/theme/variables/material.js#L149).
Please ask customization related questions on stack-overflow. Let's just track issues hare.
