### ISSUE TITLE
Left , Right , Body Tag causing "Element type is invalid error"

### ISSUE THREAD

**Issue by manukn** [GeekyAnts/NativeBase#634]
> "Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. Check the render method of `StaticRenderer`"

Left, Right, Body tag from native-base causing this issue.

```javascript
import React, { Component } from 'react';
import { Image, Platform } from 'react-native';
import { connect } from 'react-redux';
import { Content, Text, List, ListItem, Icon, Container, Left, Right, Badge, Button, View, StyleProvider, getTheme, variables } from 'native-base';
`

**Comment by sankhadeeproy007** [comment]
How are you using left, right and body? Any other details? Like the versions or the screenshots?
Which were mentioned in the issue template.

**Comment by ghjer** [comment]
I have the same issue. When I use the exact same example, as given in the docs, the error occurs.

**Comment by GeekRishabh** [comment]
@ghjer @manukn  you guys  might have got the error as you may have copied down the code and then running it .
try it writing instead of copy.

**Comment by vvavepacket** [comment]
@ghjer  @manukn  im encountering the same issue. I did try writing the code but still saying undefined...  Were you able to fix it?

**Comment by GeekRishabh** [comment]
@vvavepacket can you share the code snippet .

**Comment by ghjer** [comment]
@vvavepacket: I haven't fixed this issue, but is is an issue caused by versioning. It depence on the version of react, react-native and of course the native-base version. I'm currenly on v0.5.13 while left- right attributes are available on 2.0 or up. I need to upgrade soon because quite some packages get deprecated by swift 3 on ios

**Comment by vvavepacket** [comment]
Yup I confirmed this is issue with version. It turns out in the versions
I'm using, the class is located in different package.

**Comment by GeekRishabh** [comment]
Left , Right , Body Tag  are added in NB > v2.0

**Comment by mickeyren** [comment]
this issue still persist, could not use CardItem at all because of this error. The samples themselves are broken.

From the example:

```
<Container>
      <Content>
      <Card style={{flex: 0}} >
        <CardItem>
            <CardItem>
              <Left>
                <Button transparent textStyle={{color: '#87838B'}}>
                  <Icon name="logo-github" />
                  <Text>1,926 stars</Text>
                </Button>
              </Left>
            </CardItem>
        </CardItem>
      </Card>
      </Content>
</Container>
```

results in
```
Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
```
