### ISSUE TITLE
Which files to put .gitignore after install?

### ISSUE THREAD

**Issue by VilleMiekkoja** [GeekyAnts/NativeBase#637]
Hello,

Could someone tell me which files should I put into .gitignore after installing this native base library?
I see it has changed some files in the native folders(ios, android), which are not gitignored even using the standard .gitignore for react-native projects. http://stackoverflow.com/questions/42754258/react-native-which-files-to-include-in-version-control-after-installing-native

## react-native, react and native-base version
    "react-native": "0.40.0",
    "react": "15.4.2",
    "native-base": "^2.0.8",
## Expected behaviour
After install, there should be nothing to commit to version control, except the package.json changes
## Actual behaviour
After install, files in the native folders changes:
ios/AppName.xcodeproj/project.pbxproj (fonts)
ios/AppName/Info.plist (fonts)

android:
some android assets (fonts)

**Comment by sankhadeeproy007** [comment]
This is due to the icons that are linked in ios and android. You can ignore them and commit.

**Comment by VilleMiekkoja** [comment]
What do you mean by ignoring them? You mean put those to .gitignore, and then commiting? Or ignoring them by not doing anything for them, and commiting them to version control?

**Comment by sankhadeeproy007** [comment]
Any team member of yours who installs native-base will eventually end up with the same changes once they link the native modules.

So you can add the files before committing or both you can have these in your `.gitignore` file.

**Comment by VilleMiekkoja** [comment]
Ok. I think I will commit them. As I believe the project.pbsproj file is a file that should not be .gitignored. (at least it's not ignored by the standard .gitignore). Thanks for your help!
