### ISSUE TITLE
Floating Action Button overlays Footer

### ISSUE THREAD

**Issue by abettadapur** [GeekyAnts/NativeBase#638]
Hi! Thanks for trying out NativeBase!
Due to the overwhelming requests and issues/questions we ask you to add the following details with your issue.

## react-native, react and native-base version
React-Native: 0.41
Native-Base: 2.0.12
## Expected behaviour
When using a Floating Action Button with a Footer tag, I expect the FAB to be positioned above the Footer
## Actual behaviour
The FAB overlays the Footer
## Steps to reproduce (code snippet or screenshot)
```
<Container>
    <Content>
    </Content>
    <Footer>
         {this.props.renderTabs()}
     </Footer>
     <Fab
                direction="up"
                position="bottomRight"
            >
                <Icon
                    name="md-add"
                />
     </Fab>
</Container >
```
![image](https://cloud.githubusercontent.com/assets/2415669/23837549/7f01d022-0747-11e7-96d8-4551150966d1.png)

## Is the bug present in both ios and android or in any one of them?
Android, haven't tested on IOS

**Comment by sankhadeeproy007** [comment]
Have you tried giving it a marginBottom?

**Comment by abettadapur** [comment]
Yes that is the workaround I have used for now, but I still found this to be unexpected.

Feel free to close this if it's by design.

**Comment by sankhadeeproy007** [comment]
The FAB is independent of any other components in the screen. So if we add a footer, it isn't `smart` enough to move up. Hence the margins.

**Comment by luisgagocasas** [comment]
containerStyle={{bottom: 60}}
