### ISSUE TITLE
Scrollable Tabs

### ISSUE THREAD

**Issue by patrickalbani** [GeekyAnts/NativeBase#639]
Have a page with 6, 7 tabs, in version 0.5 i use this import:
import { ScrollableTabBar } from 'react-native-scrollable-tab-view';

in tabs use this form:
 <Tabs edgeHitWidth={1000} renderTabBar={() => <ScrollableTabBar
                                                                        activeTextColor="white"
                                                                        backgroundColor="#3F51B5"
                                                                        inactiveTextColor="white"
                                                                        underlineStyle={{backgroundColor: 'orange'}}/>}>

![image](https://cloud.githubusercontent.com/assets/20818198/23858633/d7bcf8c0-07df-11e7-9dba-4a48dcb18f51.png)

but in version 2.0.x this not work. How to make this?

![image](https://cloud.githubusercontent.com/assets/20818198/23858740/391a3966-07e0-11e7-82c8-6cfd0a3b7765.png)

**Comment by sankhadeeproy007** [comment]
Hi, we'll look into this and get back to you with a solution in a couple of days.

**Comment by sankhadeeproy007** [comment]
@patrickalbani Tabs has been added to master. 
![screen shot 2017-03-16 at 8 29 30 pm](https://cloud.githubusercontent.com/assets/10998047/24002653/4efd5cbe-0a87-11e7-8af2-d64a2a8dd1bc.png)

Here's how to use it. Please note that `heading` as of now only takes a string.
Use from master if it's urgent. Let me know if you face any problems.

**Comment by patrickalbani** [comment]
Great @sankhadeeproy007 
Work perfectly
Thanks

**Comment by ngocdb** [comment]
> Please note that heading as of now only takes a string.
=>
With that way, how can we style the heading ?
For example how can I set the fontSize of the heading text ?

**Comment by sankhadeeproy007** [comment]
![screen shot 2017-05-09 at 10 49 38 am](https://cloud.githubusercontent.com/assets/10998047/25836529/3e4aaff0-34a5-11e7-8eda-0d1eb99f2896.png)
From the docs.

**Comment by ngocdb** [comment]
OK,
Great!, Thanks @sankhadeeproy007, it works!
I have another issue with ScrollableTab.
Everything is fine in the normal case, but if I rotate the phone (horizontal dimension), with ScrollableTab, tabs are not auto (full) expand.
![rotatephone](https://cloud.githubusercontent.com/assets/3035559/25837565/a714a58c-34b8-11e7-8cce-85ef01ad7918.png)
How can I deal with that?
