### ISSUE TITLE
Toast callback

### ISSUE THREAD

**Issue by justfede** [GeekyAnts/NativeBase#640]
Hey guys! I wan't to perform some action when the toast closes. It's posible?

Thanks!

**Comment by shivrajkumar** [comment]
@justfede It is not possible do that yet.

**Comment by alexrussell** [comment]
FWIW this is now available, see https://github.com/GeekyAnts/NativeBase/blob/master/src/basic/ToastContainer.js#L79

However, the toast closing code is implemented somewhat non-DRYly, and as such this only actually fires when the toast is *manually* closed. If the original config specified a duration, the toast would still be closed but the callback wouldn't be called as a different code path is run in this case (specifically https://github.com/GeekyAnts/NativeBase/blob/master/src/basic/ToastContainer.js#L59).

**Comment by SupriyaKalghatgi** [comment]
@alexrussell Good one!
@justfede did you take a look?

**Comment by SupriyaKalghatgi** [comment]
Merged #1191
