### ISSUE TITLE
Include documentation and test against create-react-native-app

### ISSUE THREAD

**Issue by brentvatne** [GeekyAnts/NativeBase#645]
Hello! You are going to have lots of people try to use NativeBase with [create-react-native-app](https://github.com/react-community/create-react-native-app), so you might want to include some documentation on how to do it. Additionally, you may want to work it into your testing workflow to make sure that NativeBase works as expected in CRNA.

The process for using it with CRNA is the same as with Expo: https://blog.expo.io/using-react-native-ui-toolkits-with-exponent-3993434caf66#.zhsqwy51v

**Comment by gautamkishore** [comment]
+1

**Comment by sutani** [comment]
hello, i will create documentation about how to use Native Base. can i assigned my self in issue?

**Comment by gautamkishore** [comment]
That'll be great Sutani

**Comment by sutani** [comment]
ok @gautamkishore

**Comment by shivrajkumar** [comment]
http://docs.nativebase.io/docs/GetStarted.html#Quick_Setup

**Comment by brentvatne** [comment]
🚀
