### ISSUE TITLE
getTheme index doesn't exist

### ISSUE THREAD

**Issue by shuffgy** [GeekyAnts/NativeBase#646]
## react-native, react and native-base version
    "native-base": "^2.0.12",
    "react": "15.4.2",
    "react-native": "0.42.0"

## Expected behaviour
Wanted to try NativeBase and customize the theme as it is described here: http://nativebase.io/docs/v2.0.0/customize

## Actual behaviour
After adding the row `import getTheme from './native-base-theme/components';` my emulator throws a 500 Error with 

> -path to root-/native-base-theme/components/index not found

but i see the index.js in that folder.

## Steps to reproduce (code snippet or screenshot)
Just run `node node_modules/native-base/ejectTheme.js`

## Any other additional info which would help us debug the issue quicker.
tried installing via Terminal in VS Code and the powershell from microsoft with and without admin-rights.

**Comment by geekyants-github** [comment]
You need to import it from the path it is there in your project code.

**Comment by shuffgy** [comment]
@geekyants-github  I am very sorry but I use the following line `import getTheme from './native-base-theme/components';` because it is in my root folder (like my index.android.js..). 
"AwesomeNativeBase" (root) -> "native-base-theme" -> "components".
`import material from './native-base-theme/variables/material';` throws no error...

**Comment by jaapster** [comment]
I have the same issue as @shuffgy, using the correct path.

**Comment by jaapster** [comment]
@shuffgy Ok, I got it working by stopping the dev-server and running `react-native link` and `react-native run-ios`.
