### ISSUE TITLE
SegmentTheme 'segmentActiveTextColor' not updating

### ISSUE THREAD

**Issue by chapeljuice** [GeekyAnts/NativeBase#648]
I'm trying to customize the theme of the Segment element, but running into issues with the `segmentActiveTextColor` configuration. I'm trying to update it both in `variables/platform.js` and in `components/Segment.js`, but having no luck.

### UI view
I want the active state text (in this case, the word 'Current') to be white...so I need to update the active text color.
<img width="284" alt="screen shot 2017-03-15 at 10 30 02 am" src="https://cloud.githubusercontent.com/assets/862642/23962186/85041c80-096a-11e7-9349-0e75bee0a59b.png">

### Component code:
```
import { Segment, Button, StyleProvider } from 'native-base';
import getTheme from './../../../native-base-theme/components';
import platform from './../../../native-base-theme/variables/platform.js';

class Toggle extends React.Component {

  render () {
    return (
      <StyleProvider style={getTheme(platform)}>
        <Segment>
          <Button first active><Text>Current</Text></Button>
          <Button last><Text>Previous</Text></Button>
        </Segment>
      </StyleProvider>
    )
  }
};
```
### Segment.js
I've tried to update `color: 'variables.segmentActiveTextColor'` to be `color: '#fff'` with no luck. 
<img width="469" alt="screen shot 2017-03-15 at 10 29 07 am" src="https://cloud.githubusercontent.com/assets/862642/23962110/46752248-096a-11e7-8521-5fb200604bad.png">

### platform.js
Trying to update the variable doesn't seem to work either:
<img width="483" alt="screen shot 2017-03-15 at 10 27 30 am" src="https://cloud.githubusercontent.com/assets/862642/23962040/154f5d8c-096a-11e7-9449-1b646b302655.png">

Info: 
native-base@2.0.12 
react-native-cli: 2.0.1
react-native: 0.42.0

**Comment by shivrajkumar** [comment]
@chapeljuice You need to use `Text` from NativeBase for that to work.
Seems you are using RN `Text`

**Comment by chapeljuice** [comment]
Bah, that was it. Apologies. Thanks so much for the response!
