### ISSUE TITLE
Can you put an image in the Body of a Header?

### ISSUE THREAD

**Issue by dekkofilms** [GeekyAnts/NativeBase#649]
I tried doing this, but i don't know if it is working properly yet ... unless I am missing still missing something:

```
<Header>
  <Left>
    <Button transparent>
      <Icon name='menu' />
    </Button>
  </Left>
  <Body>
    <Image source={{uri: appBrandUrl}} style={{width: 200, height: 35, resizeMode: "contain"}} />
  </Body>
  <Right>
    <Button transparent>
      <Icon name='cart' />
    </Button>
  </Right>
</Header>
```

I have also tried wrapping the `<Image>` around `<Title></Title>` tags, as well as, `<Button></Button>` tags.

Any suggestions appreciated! Thanks!

**Comment by shivrajkumar** [comment]
![screen shot 2017-03-16 at 1 11 16 pm](https://cloud.githubusercontent.com/assets/17001305/23986436/1ee8d72a-0a4a-11e7-88e9-21dbbc07b0ee.png)
it seems to be working fine

**Comment by dekkofilms** [comment]
okay, cool @shivrajkumar I just noticed on my android build the image was there, so I don't think this is necessarily a NativeBase issue, it might be something with iOS ... I know they don't like HTTP images, so I need to double check that URL when I get to my project. Thanks for verifying that it does work!
