### ISSUE TITLE
Warning YellowBox

### ISSUE THREAD

**Issue by jreziga** [GeekyAnts/NativeBase#65]
It seems you're applying invalid style to View jsx node http://puu.sh/q4PXU/195d40dad0.jpg Is it possible to do something about it ?

**Comment by sankhadeeproy007** [comment]
Hi, can you tell me, using which component is causing this error?

**Comment by jreziga** [comment]
InputGroup/Input and Button. I didn't tried others

**Comment by sankhadeeproy007** [comment]
I just did a fresh install and it seemed to work without any workings. Are you sure you aren't applying any external styles to your components?

**Comment by jreziga** [comment]
Yes you're right.
I tried to set fontSize on Button element and color to Input element. How can I set my own fontSize for Button node ?

**Comment by sankhadeeproy007** [comment]
Use `textStyle` prop. 
http://nativebase.io/docs/v0.5.0/components#button
