### ISSUE TITLE
How to navigate in NativeBase

### ISSUE THREAD

**Issue by li-zhenyu** [GeekyAnts/NativeBase#650]
I looked the NativeBase API.
The question is I didn't find out how to navigate scenes. (using React Navigation ?)
please somebody help me. thanks a lot.

**Comment by deneuv34** [comment]
@li-zhenyu you can use react-native-router-flux too for navigation

**Comment by zohaibr** [comment]
@deneuv34 any guidance or Docs that you can link to? 
Thanks

**Comment by li-zhenyu** [comment]
@deneuv34 react-native-router-flux is great, thanks

**Comment by deneuv34** [comment]
@zohaibr you can go [here](https://github.com/aksonov/react-native-router-flux) for complete information

**Comment by deneuv34** [comment]
@li-zhenyu your welcome :+1:

**Comment by andidev** [comment]
@deneuv34 
There is nothing there about configuring with Native Base, or have I missed something?

**Comment by sankhadeeproy007** [comment]
I don't think you need docs separately for react-native-router-flux. Here's how we've used it with NativeBase in our KitchenSink App. https://github.com/GeekyAnts/NativeBase-KitchenSink

**Comment by uxman-sherwani** [comment]
Nativebase is only a library for UI components and has nothing to do with navigation at the moment. You can use any navigation library **(react-navigation, react-native-router-flux etc)** available for react-native.

**Comment by andidev** [comment]
@sankhadeeproy007 great! That works just fine for at least me!
@uxman-sherwani yes I know Native Base is just a library for UI components though for new react native users like me it the whole navigation part of react native is a bit confusing.

The confusing part with combining **react-native-router-flux** with **Native Base** for me is that react-native-router-flux has a build-in navbar support which is not the Native Base `Header`-tag. Therefore it's also a bit confusing how to setup and use the Native Base anatomy tags `Container`, `Header`, `Content` and `Footer`.

**Comment by sankhadeeproy007** [comment]
@andidev We can just have `hideNavBar` set at our initial route. That will hide the RNRF navbar and we can use NativeBase navbar with it.

**Comment by andidev** [comment]
Thanks! Works like a charm and its really easy to configure.

**Comment by vijaychouhan-rails** [comment]
Simple application at https://github.com/vijaychouhan-rails/AllInOne
