### ISSUE TITLE
Does Button have a default minimum width?

### ISSUE THREAD

**Issue by HyperSimon** [GeekyAnts/NativeBase#651]
Does Button have a default minimum width?
I want to get a round button, So I set the following style

```javascript
<NativeButton style={StyleSheet.flatten( styles.deleteButton)}>
</NativeButton>
```

for StyleSheet

```javascript
  deleteButton: {
    width: 18,
    height: 18,
    borderRadius: 9,
    borderColor: '#AEB2D7',
    borderWidth: 0.5,
    backgroundColor: '#C7C7C7',
    marginLeft: 10,
    marginTop: 15
  },
```

It looks like this
<img width="140" alt="2017-03-16 3 24 55" src="https://cloud.githubusercontent.com/assets/9377192/23986023/09aba28a-0a5d-11e7-9831-15722bb94c5d.png">

These are wide and high for 60 buttons, rounded to 30, working well
<img width="153" alt="2017-03-16 3 27 26" src="https://cloud.githubusercontent.com/assets/9377192/23986033/157ff552-0a5d-11e7-9c68-886c30450c84.png">

**Comment by sankhadeeproy007** [comment]
That probably is due to the horizontalPadding. Set it to 0 and try.

**Comment by HyperSimon** [comment]
It's working, thanks @sankhadeeproy007
