### ISSUE TITLE
Badge too large, positioned wrong and pushing down FooterTab Icon

### ISSUE THREAD

**Issue by znafets** [GeekyAnts/NativeBase#652]
react-native-cli: 2.0.1
react-native: 0.42.0

using the code example from the ReactBase 2.0 website like so:

``` html
         <Footer >
            <FooterTab>
              <Button>
                <Icon name="apps" />
                <Text>Apps</Text>
              </Button>
              <Button>
                <Badge style={{ backgroundColor: 'blue' }}><Text>51</Text></Badge>
                <Icon name="person" />
                 <Text>Contact</Text>
              </Button>
              <Button>
                <Icon name="camera" />
                 <Text>Camera</Text>
              </Button>
              <Button active>
                <Icon name="share" />
                 <Text>Share</Text>
              </Button>
            </FooterTab>
          </Footer>
```

gives me:

<img width="372" alt="screen shot 2017-03-16 at 14 04 30" src="https://cloud.githubusercontent.com/assets/1311944/23997576/1ac72130-0a52-11e7-8ef0-8b78912ed395.png">

**Comment by znafets** [comment]
<img width="375" alt="screen shot 2017-03-16 at 14 16 17" src="https://cloud.githubusercontent.com/assets/1311944/23997804/33cb6e7e-0a53-11e7-9584-d7313040f2de.png">

**Comment by andidev** [comment]
I can confirm this, I had to style it myself.

**Comment by znafets** [comment]
where, how did you style it ? Any pointers ?

**Comment by HyperSimon** [comment]
Same here

**Comment by andidev** [comment]
I did something like this (absolute positioning), though its not to tested. I think it looks a bit strange on android for example.

```xml
...
<Badge style={{ position: 'absolute', right: 12, top: 3, paddingTop: 0, paddingBottom: 0, borderRadius: 100, height: 18 }}>
    <Text style={{ height: 16, fontSize: 12 }}>{this.props.numberOfOrders}</Text>
</Badge>
...
```

**Comment by znafets** [comment]
Hmm thanks, it seems the best way to overwrite the standards from NativeBase (as you can customise it this way) ... I just wonder if that could not be fixed in the guts of NativeBase defaults in order to have it correctly displayed in the first place, without being forced to customise in order to provide valid props

**Comment by andidev** [comment]
According to the docs it looks like it should be styled by default. So styling it is just a workaround.

**Comment by sankhadeeproy007** [comment]
Yes, that looks like a bug. We'll look into it.

**Comment by geekyants-github** [comment]
You need to pass badge prop in the Button
Something like this
`<Button badge>
     <Badge style={{ backgroundColor: 'blue' }}><Text>51</Text></Badge>
      <Icon name="person" />
       <Text>Contact</Text>
  </Button>`

**Comment by shivrajkumar** [comment]
You need to pass badge prop in the Button
Something like this
`<Button badge>
    <Badge style={{ backgroundColor: 'blue' }}><Text>51</Text></Badge>
     <Icon name="person" />
      <Text>Contact</Text>
 </Button>`

**Comment by andidev** [comment]
Cool then this issue is about updating the documentation since it does not include the badge attribute.

**Comment by znafets** [comment]
This is still pushing the Tab Icon and Text down

**Comment by andidev** [comment]
So the example seems to be updated and it seems to work!

**Comment by znafets** [comment]
This is what I still see when I copy&paste the example code from the website:

<img width="373" alt="screen shot 2017-03-17 at 23 46 08" src="https://cloud.githubusercontent.com/assets/1311944/24065533/1d0411c2-0b6c-11e7-93fe-a66f7c2ad966.png">

As you can see the first and third tab (those with the badge) are pushed out of position.

I ran node node_modules/native-base/ejectTheme.js before which copies the styles in local folders ... is it possible that there went something wrong?

**Comment by znafets** [comment]
Yes, that was it ... the creation of the local copy of native-base components seems to cause this if those components are used in the app.
here is what I did:

1. I removed the local copy of the native-base components which were created by to above command
2. deleted the nodes_modules folder
3. npm install
4. react-native link
5. changed the imports to the default native-base

and voila, positioning is correct, here is what I see now:
<img width="376" alt="screen shot 2017-03-18 at 00 13 25" src="https://cloud.githubusercontent.com/assets/1311944/24066146/5d09ef68-0b70-11e7-9c41-8fa8998cf71b.png">

**Comment by znafets** [comment]
@shivrajkumar : is this fixed, or why would this issue be closed ?
The problem seems to be in the recommended comment `node node_modules/native-base/ejectTheme.js`for customising themes and styles ... if you do as described and use the generated files you end up with the described problem
