### ISSUE TITLE
ActionSheet

### ISSUE THREAD

**Issue by acamenhas** [GeekyAnts/NativeBase#658]
Hi! First of all, thank you for this amazing lib of React UI Components!!

I've upgrade NB to version 2.0.12 but i can't put ActionSheet working :(

I've copy paste the example but it gives me the error: "undefined is not an object (evaluating '_nativeBase.ActionSheet.show')

Can you help me?

Best of all
![actionsheet](https://cloud.githubusercontent.com/assets/14015712/24072540/a53da494-0be0-11e7-9a87-49af5232c0f7.png)

**Comment by sankhadeeproy007** [comment]
ActionSheet has been added from v2.0.13.
Please upgrade and check.

**Comment by acamenhas** [comment]
That's it!
Thank you!
