### ISSUE TITLE
Tabs: setting initial page fails to move underlining bar

### ISSUE THREAD

**Issue by alfie-ab** [GeekyAnts/NativeBase#665]
When I set the initialPage prop in tabs to a non-default option, it renders on the correct tab but it fails to move the underlining bar to that tab:

![screen shot 2017-03-21 at 14 18 44](https://cloud.githubusercontent.com/assets/20194492/24151736/84eecd0e-0e41-11e7-9b36-5b90c0b80845.png)

This is my code:

`<Tabs initialPage={1}>`
                `<Tab heading="History">`
                  `<HistoryDetailTab/>`
                `</Tab>`
                `<Tab heading="Examination">`
                  `<ExaminationDetailTab/>`
                `</Tab>`
                `<Tab heading="Investigation">`
                  `<InvestigationDetailTab/>`
               ` </Tab>`
 `</Tabs>`

It worked on version 2.0.0 but not on anything higher than 2.0.6.

React native: 0.40.0
Native-base: 2.0.9

Any help would be much appreciated, thank you!

**Comment by ercekal** [comment]
Have the same issue! Any luck??

**Comment by tishad770** [comment]
Facing the same issue. No support found?

**Comment by alfie-ab** [comment]
No, no support found unfortunately. I ended up changing the theme of my tabs (using StyleProvider) to make the underlining bar transparent. So now they look like this: 

![screen shot 2017-04-11 at 11 53 34](https://cloud.githubusercontent.com/assets/20194492/24905911/8ed3c01e-1ead-11e7-8b84-984bf505cba9.png)
 
Which obviously isn't ideal but at least the logic works and they render on the right tab.

**Comment by shivrajkumar** [comment]
This seem to work in the newer releases v2.1.x.
Let me know if it works.

**Comment by AnthonyAltieri** [comment]
Still not working on v2.1.4

**Comment by ikhsanalatsary** [comment]
Still not working on v2.3.2

**Comment by SupriyaKalghatgi** [comment]
#1010

**Comment by rodrigoreis22** [comment]
Not working on v2.3.3

**Comment by jaychoumylove** [comment]
I have encountered this problem with version 2.8.1. Is there any maintenance?
