### ISSUE TITLE
Toast not work on IOS

### ISSUE THREAD

**Issue by huang475** [GeekyAnts/NativeBase#666]
Hi! Thanks for trying out NativeBase!
Due to the overwhelming requests and issues/questions we ask you to add the following details with your issue.

## react-native, react and native-base version
react-native 0.42
react 15.4.1
native-base 2.0.13
## Expected behaviour
toast will show up
## Actual behaviour
toast didn't show up. And an exception about `shadowView not found` was thrown afterward.
## Steps to reproduce (code snippet or screenshot)
```#javascript
if (error) {
          Toast.show({
            text: error,
            position: 'bottom',
            duration: 2000,
            type: 'danger',
          });
}
```
## Screenshot of emulator/device
<img width="368" alt="screen shot 2017-03-22 at 9 29 20 am" src="https://cloud.githubusercontent.com/assets/5912803/24178135/24c8e102-0ee2-11e7-8299-7af4d6f15841.png">

## Is the bug present in both ios and android or in any one of them?
only ios, android is okay.

**Comment by sankhadeeproy007** [comment]
Upgrade to RN 42.2. It's a react-native issue.
