### ISSUE TITLE
Card footer not visible (BUG)

### ISSUE THREAD

**Issue by cyclops24** [GeekyAnts/NativeBase#668]
Hi,
First thanks for this awesome package. I try using `Card` component like below:
```
<Card>
                    <CardItem header>
                        <Text>NativeBase</Text>
                    </CardItem>
                    <CardItem>
                        <Body>
                        <Text>
                            NativeBase is a free and open source framework that enables developers to build
                            high-quality mobile apps using React Native iOS and Android apps
                            with a fusion of ES6.
                        </Text>
                        </Body>
                    </CardItem>
                    <CardItem>
                        <Body>
                        <Text>
                            NativeBase builds a layer on top of React Native that provides you with
                            basic set of components for mobile application development.
                        </Text>
                        </Body>
                    </CardItem>
                    <CardItem>
                        <Body>
                        <Text>
                            Get on the mobile fast track with NativeBase, the fastest-growing platform
                            and tool set for iOS and Android development.
                        </Text>
                        </Body>
                    </CardItem>
                    <CardItem footer>
                        <Text>GeekyAnts</Text>
                    </CardItem>
                </Card>
```
But in my device `Nexus 7 Tab with android 5` footer not visible.
Do you have any suggestion for find the issue?
I'm using NativeBase `2.0.12` and React-Native `0.42.0`.

![screenshot_2017-03-22-11-18-42](https://cloud.githubusercontent.com/assets/8266479/24185621/c0b9464c-0ef1-11e7-83ba-6eb0ce3775e0.png)

**Comment by dekkofilms** [comment]
@cyclops24 have you found any resolve for this ... i have noticed that on my app as well. It works fine on iOS actually, but for android devices it is missing. 

Would love to know if you have found a fix to this!

**Comment by cyclops24** [comment]
Hi @dekkofilms,
Unfortunately I can't find any way to fix this. 😢

**Comment by dekkofilms** [comment]
@cyclops24 womp. hopefully this will get some attention soon

**Comment by cyclops24** [comment]
@dekkofilms until bug fix for this issue you can use [react native elements card component](https://github.com/react-native-community/react-native-elements#card) as a temporary solution. It's OK and not break on large screen or android device.

**Comment by acomito** [comment]
I'm having a similar issue where my final CardItem in a card is always pushed off screen. Im testing on an iphone 7+

**Comment by palmsey** [comment]
I noticed this too, the last CardItem is missing on plus devices (testing with a 6s+). I can get around it by adding sufficient paddingBottom to the card or an extra CardItem to the end, but neither of those options look great.

**Comment by cyclops24** [comment]
@sankhadeeproy007 Are you any plan to fix this?
I really need NativeBase style Card component but it's very buggy now on big screen (Tablet 7 inch for example)

**Comment by sankhadeeproy007** [comment]
cc @GeekRishabh

**Comment by cyclops24** [comment]
@sankhadeeproy007, @GeekRishabh  I think issue somewhere in this file:
https://github.com/GeekyAnts/NativeBase/blob/master/src/theme/components/CardItem.js

**Comment by cyclops24** [comment]
@SupriyaKalghatgi This issue still exists and not fixed.
I checked it again today with 2.1.5 version.
Please reopen it.

**/CC:** @sankhadeeproy007 , @dekkofilms , @acomito guys are you still have problem?

**Comment by SupriyaKalghatgi** [comment]
@acomito Check this
![card-iphone7](https://user-images.githubusercontent.com/13464885/27169587-18b44770-51c8-11e7-81cc-fac4373b94e4.gif)

**Comment by SupriyaKalghatgi** [comment]
@palmsey Check this
![card-iphone6s](https://user-images.githubusercontent.com/13464885/27169795-0510f6d6-51c9-11e7-836d-f6991c7d1c51.gif)

**Comment by SupriyaKalghatgi** [comment]
@cyclops24 I have tried your snippet for Card in Android Tab, with
```
"dependencies": {
    "native-base": "^2.1.5",
    "react": "16.0.0-alpha.12",
    "react-native": "0.45.1"
  },
```
![screenshot_20170615-173120](https://user-images.githubusercontent.com/13464885/27180363-c18076e4-51f0-11e7-83eb-ea7eaaee1768.png)

**Comment by cyclops24** [comment]
@SupriyaKalghatgi  It's not working well in Android 5.1.1 maybe it's related to #669

**Comment by akhil-geekyants** [comment]
Fixed in the latest version

![screen shot 2017-11-06 at 7 04 36 pm](https://user-images.githubusercontent.com/27768184/32443582-8040bdb4-c325-11e7-966b-c41037f38be6.png)

![card](https://user-images.githubusercontent.com/27768184/32443677-dd712686-c325-11e7-8f9e-f3ad639d5aac.gif)
