### ISSUE TITLE
Form in card body not visible in Nexus 7 Tab (BUG)

### ISSUE THREAD

**Issue by cyclops24** [GeekyAnts/NativeBase#669]
Hi, I try using below code (a `Form` inside a `Card` component)
```
<Card>
                    <CardItem header style={{ backgroundColor: 'lightgray' }}>
                        <Right>
                            <Text>This is Right align text </Text>
                        </Right>
                        <Badge primary>
                            <Text>step 1</Text>
                        </Badge>
                    </CardItem>
                    <CardItem>
                        <Body>
                        <Text style={{color: 'red'}}>{this.state.error}</Text>
                        <Form style={{alignSelf: 'stretch'}}>
                            <Item>
                                <Label>number:</Label>
                                <Input keyboardType="numeric"/>

                            </Item>
                            <Item>
                                <Label>date:</Label>
                                <Input />

                            </Item>
                            <Item>
                                <Label>number 2:</Label>
                                <Input keyboardType="numeric"/>

                            </Item>
                            <Item>
                                <Label>date 2:</Label>
                                <Input />

                            </Item>

                            <Button success block
                            >
                                <Text>submit</Text>
                                <Icon name='check' size={20} color="#FFFFFF"/>
                            </Button>
                        </Form>
                        </Body>
                    </CardItem>
                </Card>
```

But in my device Nexus 7 Tab with android 5 footer not visible.
Do you have any suggestion for find the issue and fix it?
I'm using NativeBase `2.0.12` and React-Native `0.42.0`.

![screenshot_2017-03-22-12-00-35](https://cloud.githubusercontent.com/assets/8266479/24186772/798b6baa-0ef7-11e7-838f-0ab2decdb7e5.png)

I think it's maybe related to this issue: https://github.com/GeekyAnts/NativeBase/issues/668

**Comment by cyclops24** [comment]
I change my code a little and add `style={{backgroundColor: 'red'}}` for `CardItem` that not appear and find it on the outer card component. This is my new code:
```
<Card>
                    <CardItem header style={{ backgroundColor: 'lightgray' }}>
                        <Right>
                            <Text>This is Right align text </Text>
                        </Right>
                        <Badge primary>
                            <Text>step 1</Text>
                        </Badge>
                    </CardItem>
                    <CardItem style={{backgroundColor: 'red'}}>
                        <Body>
                        <Text style={{color: 'red'}}>{this.state.error}</Text>
                        <Form style={{alignSelf: 'stretch'}}>
                            <Item>
                                <Label>number:</Label>
                                <Input keyboardType="numeric"/>

                            </Item>
                            <Item>
                                <Label>date:</Label>
                                <Input />

                            </Item>
                            <Item>
                                <Label>number 2:</Label>
                                <Input keyboardType="numeric"/>

                            </Item>
                            <Item>
                                <Label>date 2:</Label>
                                <Input />

                            </Item>

                            <Button success block
                            >
                                <Text>submit</Text>
                                <Icon name='check' size={20} color="#FFFFFF"/>
                            </Button>
                        </Form>
                        </Body>
                    </CardItem>
                </Card>
```

And this is new screenshot:
![screenshot_2017-03-22-18-27-22](https://cloud.githubusercontent.com/assets/8266479/24201471/bb46b82a-0f2d-11e7-9acc-d23043a3a779.png)

When I remove `Form` component from `CardItem` it's render successfully like below:
```
<Card>
                    <CardItem header style={{ backgroundColor: 'lightgray' }}>
                        <Right>
                            <Text>This is Right align text </Text>
                        </Right>
                        <Badge primary>
                            <Text>step 1</Text>
                        </Badge>
                    </CardItem>
                    <CardItem style={{backgroundColor: 'red'}}>
                        <Body>
                        <Text style={{color: 'red'}}>{this.state.error}</Text>
                        </Body>
                    </CardItem>
                </Card>
```
![screenshot_2017-03-22-18-32-42](https://cloud.githubusercontent.com/assets/8266479/24201581/187745b4-0f2e-11e7-8777-88fae95577a6.png)

**Comment by cyclops24** [comment]
@sankhadeeproy007 is it a bug or I miss something? :thinking:

**Comment by Anima-t3d** [comment]
Similar to https://github.com/GeekyAnts/NativeBase/issues/612

**Comment by cyclops24** [comment]
Thanks @Anima-t3d ,
So based on that issue what's your suggestion as a quick fix?

**Comment by cyclops24** [comment]
@Anima-t3d , @sankhadeeproy007 ,
Based on @Anima-t3d guide and #612 I add `paddingTop: 30` to my `CardItem` and my form now is visible.
This is my code:
```
<Card>
                    <CardItem header style={{ backgroundColor: 'lightgray', paddingTop: 30 }}>
                        <Right>
                            <Text>This is Right align text </Text>
                        </Right>
                        <Badge primary>
                            <Text>step 1</Text>
                        </Badge>
                    </CardItem>
                    <CardItem style={{backgroundColor: 'red'}}>
                        <Body>
                        <Text style={{color: 'red'}}>{this.state.error}</Text>
                        <Form style={{alignSelf: 'stretch'}}>
                            <Item>
                                <Label>number:</Label>
                                <Input keyboardType="numeric"/>

                            </Item>
                            <Item>
                                <Label>date:</Label>
                                <Input />

                            </Item>
                            <Item>
                                <Label>number 2:</Label>
                                <Input keyboardType="numeric"/>

                            </Item>
                            <Item>
                                <Label>date 2:</Label>
                                <Input />

                            </Item>

                            <Button success block
                            >
                                <Text>submit</Text>
                                <Icon name='check' size={20} color="#FFFFFF"/>
                            </Button>
                        </Form>
                        </Body>
                    </CardItem>
                </Card>
```

And this is new screenshot:
![screenshot_2017-03-23-20-33-31](https://cloud.githubusercontent.com/assets/8266479/24257515/b8253cbc-1008-11e7-9ef3-5d1762e39ba8.png)

@sankhadeeproy007 are you any plan to fix this? Why this happens on 7 inch Nexus 7 with android 5?

**Comment by cyclops24** [comment]
I don't want to add extra `paddingTop: 30` to fix this 😢

**Comment by Anima-t3d** [comment]
@cyclops24 It's because of the header. If you move the "body" above it, it should show. There are a few ways to try: padding/margins or set fixed height. But in the end I use `View` as a container.

**Comment by cyclops24** [comment]
@Anima-t3d,
Unfortunatly move body to above of the header didn't work for me. The only solution for my code is to add extra padding with `paddingTop: 30` and I don't want use this approach because it's very ugly and I'm in production now.

Yes I think simple `View` is better because NativeBase `card` component seems very buggy now. I switch to use [react native elements card component](https://github.com/react-native-community/react-native-elements#card) as a temporary solution.
Maybe useful for too.
I can switch back to NativeBase when this bug fix.
Thanks for your attention ✋

**Comment by Iliyass** [comment]
this bug still persist in version 2.1.4

**Comment by cyclops24** [comment]
@SupriyaKalghatgi Like #668 this issue is still exist on 2.1.5.
Please reopen issue until fix.

**Comment by cyclops24** [comment]
I create a reproduce repo for this issue:
Please check it here: https://github.com/cyclops24/NBIssue669

**Comment by SupriyaKalghatgi** [comment]
@cyclops24 I tried your snippet for `Form` within `Card` (1st snippet) in Android Tab and iPhone 7, with
```
"dependencies": {
    "native-base": "^2.1.5",
    "react": "16.0.0-alpha.12",
    "react-native": "0.45.1"
  },
```
![screenshot_20170615-173945](https://user-images.githubusercontent.com/13464885/27180604-dc67f828-51f1-11e7-8933-d3f02493d368.png)
![simulator screen shot jun 15 2017 5 41 31 pm](https://user-images.githubusercontent.com/13464885/27180616-e472897a-51f1-11e7-929c-76895e57f54c.png)

**Comment by SupriyaKalghatgi** [comment]
@cyclops24 Tried your [second snippet](https://github.com/GeekyAnts/NativeBase/issues/669#issuecomment-288407877), card with form and backgroundColor

![screen shot 2017-06-15 at 5 51 35 pm](https://user-images.githubusercontent.com/13464885/27181049-7bc878b0-51f3-11e7-8d96-8aba6121fa52.png)

![screenshot_20170615-175317](https://user-images.githubusercontent.com/13464885/27181096-b105b970-51f3-11e7-9474-294f5ba5fa80.png)

**Comment by cyclops24** [comment]
I checked it again on Nexus 7 tab in portrait mode and it's still break. Please check and if need screen shot tell me @SupriyaKalghatgi .
Thanks

**Comment by sankhadeeproy007** [comment]
@cyclops24 What is the version of android on your nexus? It's breaking on android 5 and works on android 6.

**Comment by mnlbox** [comment]
My Nexus android version is: 5.1.1.
It's breaking only on portrait mode.

**Comment by cyclops24** [comment]
My Nexus android version is: 5.1.1.
It's breaking only on portrait mode.

**Comment by cyclops24** [comment]
@sankhadeeproy007 are you have any good news about this issue?

**Comment by dhdo** [comment]
A quick fix for me was to wrap the `<Form>` around a `<View>` component with `flex: 1`. After that the form showed properly.

**Comment by akhil-geekyants** [comment]
Fixed in the latest version (2.3.3)

![screen shot 2017-11-06 at 7 27 17 pm](https://user-images.githubusercontent.com/27768184/32444436-a6d5aa0e-c328-11e7-95f8-7fa9f42a0c32.png)

![card](https://user-images.githubusercontent.com/27768184/32444442-ab704b46-c328-11e7-83e1-f2102e6d6f50.gif)

**Comment by vlkalashnikov91** [comment]
You need to set <Form> after <Card> and before <CardItem>.
 {
<Card>
     <Form>
        <CardItem>
           <Body> ...

**Comment by vlkalashnikov91** [comment]
You need to set `<Form>` after `<Card>` and before `<CardItem>`

`<Card>`
    `  <Form>`
        `   <CardItem>`
            `    <Body>`...
