### ISSUE TITLE
ListItem layout broken having badge on right

### ISSUE THREAD

**Issue by zash80** [GeekyAnts/NativeBase#672]
Layout of list item is broken having a badge on right side and list items of type avatar or thumnail. It works for type icon:

```
<ListItem avatar>
  <Left>
    <Button style={{ backgroundColor: '#8F8E93' }}>
      <Icon active name="cog" />
    </Button>
  </Left>
  <Body>
    <Text>Software Update</Text>
  </Body>
  <Right>
    <Badge style={{ backgroundColor: '#FD3C2D' }}><Text>2</Text></Badge>
  </Right>
</ListItem>
```

**Comment by GeekRishabh** [comment]
@zash80  we will  fix this. For time being you can do  ```  <Right style={{ top: -3}}> ```.

**Comment by nathvarun** [comment]
@zash80  just put the ListItem inside a Content and it should work 
 
`<Content>
<ListItem avatar>
...
</ListItem>
</Content>`

**Comment by rsmelo92** [comment]
Sorry to revive this issue but is still happening
![image](https://user-images.githubusercontent.com/16295402/46960515-1a8d0280-d075-11e8-907e-d4d5edaafcb1.png)

**Comment by thomGeenen** [comment]
would have to reopen the issue because there's always the same problem. I have an offset of 10 that causes my <Text note>new Date()</Text> to be completely offset
