### ISSUE TITLE
Subtitle text color is not black when it should be white (Android)

### ISSUE THREAD

**Issue by andidev** [GeekyAnts/NativeBase#675]
The color of the subtitle is black when it should be white (at least according the documentation) on Android devices.

Actual:
![skarmavbild 2017-03-22 kl 22 07 56](https://cloud.githubusercontent.com/assets/571389/24220998/d6ec553e-0f4c-11e7-8497-611bae34e1e9.png)

Expected according to documentation:
![skarmavbild 2017-03-22 kl 22 08 35](https://cloud.githubusercontent.com/assets/571389/24221005/de8a098a-0f4c-11e7-8a1e-59182727c4b8.png)

```
"native-base": "2.0.13",
"react": "15.4.2",
"react-native": "0.42.3",
```

**Comment by shivrajkumar** [comment]
Fixed in newer versions.

**Comment by HermantoTang** [comment]
Still happen in the newest version

```
    "native-base": "2.1.3",
    "react": "16.0.0-alpha.6",
    "react-native": "0.43.4",
```
