### ISSUE TITLE
Content   disableKBDismissScroll = {true}

### ISSUE THREAD

**Issue by flyjennyetn** [GeekyAnts/NativeBase#676]
Content   Settings  disableKBDismissScroll = {true}  No reaction at all

**Comment by GeekRishabh** [comment]
@flyjennyetn seems to work fine . For more look [here](https://github.com/APSL/react-native-keyboard-aware-scroll-view/issues/82). Internally NB use [react-native-keyboard-aware-scroll-view](https://github.com/APSL/react-native-keyboard-aware-scroll-view) . So you can use the props of Keyboard-aware-scroll-view .

**Comment by karimmortabit** [comment]
Same for me here, nothing happens when I use `disableKBDismissScroll = {true}` on `Content` tag :/. So I have this issue : https://github.com/GeekyAnts/NativeBase/issues/339

**Comment by aozisik** [comment]
Same here. Can't get disableKBDismissScroll to work.

I've got:

	"react-native": "0.46.4",
	"native-base": "^2.3.0",

**Comment by karimmortabit** [comment]
@GeekRishabh @shivrajkumar any help please ?

**Comment by leoskyrocker** [comment]
well. disableKBDismissScroll is not actually doing what it is suggested to do in the docs.
Specifically, it doesn't do this:
> Disables automatic scroll on focus.

If we look [here](https://github.com/GeekyAnts/NativeBase/blob/e3f07aed7944e16d0c9d7a71b0dbf8cd1b4d22b4/src/basic/Content.js#L12), it is simply setting resetScrollToCoords, and according to the docs [here](https://github.com/GeekyAnts/react-native-keyboard-aware-scroll-view#f4805f254d6cc8e3329f5fb224944401f66655db) it is only setting the "Coordinates that will be used to reset the scroll when the keyboard hides" to null.

enableAutoAutomaticScroll should be the correct props to use instead, however, it is a prop used in an internal lib of NativeBase and it is error prone in the future. Especially the [original lib](https://github.com/APSL/react-native-keyboard-aware-scroll-view/tree/069b2ad9bba3205f683c9a488b97ec1494de456b) has already renamed the prop to enableAutomaticScroll in a newer version not used by NativeBase.

Anyhow, I couldn't get it working even if I passed enableAutoAutomaticScroll={false} to <Content>. Still investigating why.

**Comment by leoskyrocker** [comment]
oh, I see. There's no Android Support with the version NativeBase is using.

**Comment by SupriyaKalghatgi** [comment]
@leoskyrocker What is the version of NativeBase you are on?

**Comment by leoskyrocker** [comment]
@SupriyaKalghatgi I was on 2.3.6, which I just noticed is the last version that uses the old version of react-native-keyboard-aware-scroll-view.
Uses react-native-keyboard-aware-scroll-view v0.4.2 since NativeBase 2.3.7, which now should have android support.

However, my point above still holds since [this line](https://github.com/GeekyAnts/NativeBase/blob/bfa725ecbc95ec2738c24f067d81501715a87f6e/src/basic/Content.js#L12) is not changed.

> disableKBDismissScroll is not actually doing what it is suggested to do in the docs.
> Specifically, it doesn't do this:
>
> > Disables automatic scroll on focus.
>
> If we look here, it is simply setting resetScrollToCoords, and according to the docs here it is only setting the "Coordinates that will be used to reset the scroll when the keyboard hides" to null.

**Comment by averypfeiffer** [comment]
+1 would love a solution
