### ISSUE TITLE
NativeBase Text can't be used directly inside TouchableHighlight

### ISSUE THREAD

**Issue by sodik82** [GeekyAnts/NativeBase#68]
I am getting error `Touchable child must either be native or forward setNativeProps to a native component`

That's unfortunate as it prevent "direct" mixture of native base and RN.

I believe you could use https://github.com/facebook/react/blob/master/src/renderers/native/NativeMethodsMixin.js to solve this together with other "incompabilities" like measuring etc.

**Comment by SupriyaKalghatgi** [comment]
@sodik82 Can you check for this against the latest of NativeBase?

**Comment by sodik82** [comment]
still there. have you fixed something regarding this issue?

**Comment by sankhadeeproy007** [comment]
Added [here](https://github.com/GeekyAnts/NativeBase/blob/master/Components/Widgets/Text.js#L34)
