### ISSUE TITLE
ActionSheet 'show' method says undefined is not an object

### ISSUE THREAD

**Issue by syardumi** [GeekyAnts/NativeBase#680]
## react-native, react and native-base version
RN 0.42, R 15.4.2, NB 2.0.13

## Expected behaviour
ActionSheet should show just like it does in the docs: http://nativebase.io/docs/v2.0.0/components#actionsheet

## Actual behaviour
Error. **undefined is not an object (evaluating '_nativeBase.ActionSheet.show')**

## Steps to reproduce (code snippet or screenshot)
```
import React, { Component } from 'react';
import { Image } from 'react-native';
import { Button, ActionSheet } from 'native-base';

const placeholder = require('../images/placeholder_person.png');

var BUTTONS = [
  'Option 0',
  'Option 1',
  'Option 2',
  'Delete',
  'Cancel',
];
var DESTRUCTIVE_INDEX = 3;
var CANCEL_INDEX = 4;

export default class ProfileImage extends React.Component {

  render() {
    return (
      <Button transparent onPress={() => ActionSheet.show(
            {
              options: BUTTONS,
              cancelButtonIndex: CANCEL_INDEX,
              destructiveButtonIndex: DESTRUCTIVE_INDEX,
              title: 'Testing ActionSheet'
            },
            (buttonIndex) => {
              this.setState({ clicked: BUTTONS[buttonIndex] });
            }
            )}>
            <Image source={placeholder}  />
      </Button>
    );
  }
}
```

## Screenshot of emulator/device
<img width="487" alt="screen shot 2017-03-23 at 4 24 42 pm" src="https://cloud.githubusercontent.com/assets/2123996/24268765/4730d1b0-0fe5-11e7-9fd5-32d01c47cb48.png">

## Is the bug present in both ios and android or in any one of them?
Both

**Comment by sankhadeeproy007** [comment]
This got skipped in the docs, but you need to add actionSheet inside a `<Container />` for it to show properly.

**Comment by syardumi** [comment]
OK - thanks for the info, Sankha. Does the Container need to be the root element on the page? I'm having trouble using ActionSheet inside a Container where it is a sub-element of the root.

**Comment by sankhadeeproy007** [comment]
Okay, we haven't tested in a nested container scenario. Can you test with Container as the root element? This will help us narrow down the possibilities.

**Comment by syardumi** [comment]
I just tried:
```
<Container>
  <Content>
    <Button transparent onPress={() => ActionSheet.show(......
```
as the root level element, but I'm still getting the same error.

**Comment by sankhadeeproy007** [comment]
Upgrade to RN 0.42.2 and check please.

**Comment by syardumi** [comment]
I've tried upgrading to the latest release (0.42.3), but still no change.

**Comment by compusam** [comment]
The error is same to me, i have to change the functionality to Fab component.

Thanks.

**Comment by syardumi** [comment]
Unfortunately, I can't use Fab for my case. Sankha, is there any progress on this bug?

**Comment by predescu** [comment]
I had the same issue and after I checked the node_modules/native-base/src/basic folder I saw that the file Actionsheet.js is not there.

`rm -rf node_modules`
`npm install`

solved the problem.

**Comment by syardumi** [comment]
Thanks @predescu. That worked too!

**Comment by shikya** [comment]
The error is still persisting.
<img width="382" alt="screen shot 2017-07-17 at 6 00 53 pm" src="https://user-images.githubusercontent.com/8678847/28267985-17eeac52-6b1a-11e7-9cc6-62310dbcba49.png">
<img width="382" alt="screen shot 2017-07-17 at 6 01 00 pm" src="https://user-images.githubusercontent.com/8678847/28267984-17ebcef6-6b1a-11e7-9e81-ab1b796d0e7f.png">

I created a sample app to reproduce. 
https://github.com/shikya/NativeBaseTest

Install dependencies and run `react-native run-ios` to start the app.

**Comment by jraack** [comment]
@shikya Yes, i have got still the same issue, RN 0.44.0

**Comment by luiskhernandez** [comment]
I am getting the same error, anyone has found a solution?

**Comment by marcusvbp** [comment]
I am getting this error too. RN 0.48.1

I have created a component that invokes the AS component and then insert the new component in my scene. Look this gist: https://gist.github.com/marcusvbp/67cf22925cb5fc38aa11f85efc7c7e83

**Comment by luiskhernandez** [comment]
Hi @marcusvbp , you should import 

    import {Root} from 'native-base'

and then 


    render() {
        return (
          <Root>
          <View style={styles.container}>
            <Button transparent style={styles.btn} onPress={ () => this.showAS() }>
              <Icon name="person" style={{ color: '#666', fontSize: 50 }} />
            </Button>
          </View>
          </Root>
        );
      }

**Comment by marcusvbp** [comment]
@luiskhernandez Thanks it worked!

**Comment by gustavoadt** [comment]
The solutions from @luiskhernandez  and @predescu didn't work for me.
The ActionSheet file exists and the <Root> didn't change anything.

In my case I have 2 scenes with the AS component.
The crash occurs when I render the AS in the scene 1 and then go to scene 2 and try to access it.
If I do the opposite, scence 2 first then go to scene 1, it doesn't happen.

The codes are slightly different:

On scene 1 it's used like the docs, but on scene 2 I choose between two sets of BUTTON that I render, with different cancelButtonIndex. The scene one uses a const, but on scence 2 both set a different number. Both scenes use the AS on a <Header> with a <Button>.

It crashes before showing the menu or anything. The first output of the red screen says the issue is on the show() method of AS.

Any other solutions? The code is pretty straight forward, but if you need to see it, just let me know.

Thanks in advance.

**Comment by darula-hpp** [comment]
Adding the root tag worked for me also thanks
