### ISSUE TITLE
Tabs automatic scrolling

### ISSUE THREAD

**Issue by patrickalbani** [GeekyAnts/NativeBase#683]
I have a screen with 2 tabs and some input. When i click inside a input of first page, automatic scroll to the second screen.

![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/20818198/24297316/19aecd0e-1081-11e7-9197-e84409b75ed2.gif)

**Comment by GeekRishabh** [comment]
@patrickalbani seems to work fine .
![issuetab](https://cloud.githubusercontent.com/assets/23093075/25042941/b4d89512-2139-11e7-88a0-670d8d871a14.gif)

**Comment by shivrajkumar** [comment]
Closing the issue as this seem to be resolved in the newer versions.
Let me know if you are still stuck with the issue.

**Comment by patrickalbani** [comment]
The problem persist, but only when the Input style={{textAlign: 'right'}}

**Comment by Deevent** [comment]
@patrickalbani Thank you so much ! I got crazy with that and just removing the textAlign in my input solved the issue.
