### ISSUE TITLE
Text in Header not Clickable

### ISSUE THREAD

**Issue by obykoo** [GeekyAnts/NativeBase#684]
I have Header defined like this and right text is not clickable.

```
<Header>
      <Left>
          <Button transparent onPress={this.onBack}>
              <Icon color={color} name='ios-arrow-back' />
          </Button>
       </Left>
        <Body style={{flex:2}}>
             <Title>{text}</Title>
          </Body>
          <Right>
                 <Text onPress={this.onEdit} style={{color:'#fff'}}>{isEdit ? translate.t('editCancel') : translate.t('edit')}</Text>
           </Right>
   </Header>
```

Result:
![image](https://cloud.githubusercontent.com/assets/25873477/24327122/a02989ba-11c0-11e7-9b5c-94f353bfa6c4.png)

If I add text to button , then size of text is too big for button.

**Comment by iiitmahesh** [comment]
:+1:

**Comment by oximer** [comment]
https://facebook.github.io/react-native/docs/text.html

Text doesn't have a property onPress. You should wrap it on something clickable, like a TouchableHighlight or a Button.

**Comment by shivrajkumar** [comment]
Seem to work fine for `onPress` of `<Text>` 
![header](https://cloud.githubusercontent.com/assets/17001305/25082891/2a5f4f36-2371-11e7-9ca4-ee3d6ebe9192.gif)
