### ISSUE TITLE
Switch - Wrong Documentation

### ISSUE THREAD

**Issue by jaseemabbas** [GeekyAnts/NativeBase#685]
The documentation for `Switch` under `List Icon` state

`<Switch valur={false} />`

instead of 

`<Switch value={false} />`

**Comment by shivrajkumar** [comment]
Documentation moved to GitBook http://docs.nativebase.io/

**Comment by iiitmahesh** [comment]
@shivrajkumar  Can please share ref link for Switch ??  how to use and different props and styling ....

**Comment by iiitmahesh** [comment]
@shivrajkumar I think  @jaseemabbas talking about typo in GitBook.

**Comment by shivrajkumar** [comment]
@iiitmahesh NativeBase Switch internally uses RN Switch https://facebook.github.io/react-native/docs/switch.html
You can use it the same way as RN Switch

**Comment by iiitmahesh** [comment]
Oh got this. https://facebook.github.io/react-native/docs/switch.html.
I understood why swtich documentation explict  not in native base.
