### ISSUE TITLE
FAB expanded button icons are not shown.

### ISSUE THREAD

**Issue by kidnapkin** [GeekyAnts/NativeBase#687]
Hi! Thanks for trying out NativeBase!
Due to the overwhelming requests and issues/questions we ask you to add the following details with your issue.

Please check the existing open/closed issues for a possible duplicate before creating a new issue :)

Also **DO** fill out the below form to give us a better idea about your environment and help us debug it quicker. Issues without the required details will mostly be unattended to.

## react-native, react and native-base version
react-native 0.42.3, native-base 2.1.0
## Expected behaviour
Expand buttons with icons 
## Actual behaviour
Buttons are expanded without icons
## Steps to reproduce (code snippet or screenshot)

```Javascript
<Fab
  active={this.state.active}
  direction="up"
  containerStyle={{ bottom: 65 }}
  style={{ backgroundColor: '#3498db' }}
  position="bottomRight"
  onPress={() => this.setState({ active: !this.state.active })}
>
  <Icon name="add" />
  <Button>
    <Icon name="person" style={{ color: '#fff' }} />
  </Button>
</Fab>
```

## Screenshot of emulator/device

![screenshot_2017-03-27-15-45-08-377_com twadlockapp](https://cloud.githubusercontent.com/assets/9214135/24358887/452e2a38-130b-11e7-9855-7b4af6600630.png)

## Is the bug present in both ios and android or in any one of them?
Not tested on ios

## Any other additional info which would help us debug the issue quicker.
When active prop hardcoded with true the icon is shown.

Downgrade to 2.0.8 works for me.

**Comment by LeoAref** [comment]
I have the same issue

**Comment by LeoAref** [comment]
I tried to solve the issue, but it seems that the Fab component has many issues, and I'm using now **https://github.com/mastermoo/react-native-action-button** and it's working so well so far

**Comment by GeekRishabh** [comment]
@LeoAref @kidnapkin seems to work fine. Do check again and let know for which conditions are you facing the issue.

**Comment by LeoAref** [comment]
@GeekRishabh I'll try to check it next week and get back to you.

**Comment by shivrajkumar** [comment]
Should work fine with latest version 2.1.3
