### ISSUE TITLE
Any way to make bottom tabs ? 

### ISSUE THREAD

**Issue by Kris4an7** [GeekyAnts/NativeBase#688]
Hello, I want to make bottom tabs, but I can't seem to figure out how. Could someone help me ? 

Thank you !

**Comment by Kris4an7** [comment]
?

**Comment by davidhenley** [comment]
+1

**Comment by sankhadeeproy007** [comment]
Bottom tabs as in? Have you checked FooterTabs?

**Comment by davidhenley** [comment]
FooterTabs do not use horizontal scrollview

**Comment by westonganger** [comment]
The documentation under the tabs section should tell us about the existence of Footer Tabs.

**Comment by davidhenley** [comment]
Footer tabs are different. Also, how hard is it to read the doc sections.
Footer Tabs are in big letters on the side.

**Comment by shivrajkumar** [comment]
@davidhenley try applying the prop `tabBarPosition="bottom"`.
`<Tabs tabBarPosition="bottom">`
Let me know if it works

**Comment by geek-ibrar** [comment]
Yeah it works :)
