### ISSUE TITLE
Form: Stackedlabel on top of text in ios

### ISSUE THREAD

**Issue by elinlindberg** [GeekyAnts/NativeBase#692]
react-native 0.42.3
react 15.4.2
native-base 2.0.11

When using a stacked label in a form the behavior is wrong on both Android and iOS. In android the input box is in the center and very small. On iOS the label is on top of the input box.

Code:
```
<Form>
                  <Item stackedLabel>
                    <Label>{this.props.qrCodeTextInput}</Label>
                    <Input 
                      onChangeText={(text) => this.props.setText(text)}
                      value={this.props.text}
                      maxLength={15}
                      placeholder={this.props.qrCodeTextInputPlaceholder}/>
                  </Item>
                </Form>
```

![screen shot 2017-03-29 at 08 14 53](https://cloud.githubusercontent.com/assets/26759812/24441160/9bd63706-1458-11e7-90fe-159fd21bb83c.png)

**Comment by parkerproject** [comment]
same issue here, I might just build my own form

**Comment by GeekRishabh** [comment]
@elinlindberg @parkerproject seems to work fine . Try again and let know if issue exist .

**Comment by parkerproject** [comment]
Did you make an update that we need to pull or something? What version are you using?

**Comment by GeekRishabh** [comment]
@parkerproject I am using the below dependencies 
`
 "native-base": "2.1.0",
    "react": "~15.4.2",
    "react-native": "0.42.3",
`

**Comment by shivrajkumar** [comment]
Do eject the new theme and merge if you are still facing the issue.
