### ISSUE TITLE
missing typescript definitions in 2.1

### ISSUE THREAD

**Issue by stsrki** [GeekyAnts/NativeBase#693]
Hi, just want to inform you that the following are missing from typescript definitions:
`getTheme, StyleProvider`

For now I have manually changed my local index.d.ts for native-base, but you should definitely include these in the future releases. tnx

**Comment by jmc420** [comment]
I think Form and Label are also missing.

**Comment by Oize** [comment]
Could not find Fab also.

**Comment by stsrki** [comment]
These components are also missing from tsd
`ActionSheet, Form, Segment, Toast`

and Tabs component is missing function
`onChangeTab()`

**Comment by vkalinichev** [comment]
Also missing:
  * `noShadow` property of `Header`
  * `noBorder` property of `ListItem`

Anyone have workaround for manual extending type definitions to prevent `tsc` build failing?

**Comment by stsrki** [comment]
There aro two ways that I can think of.

First is to use spread operator like

`<Tabs {...{ onChangeTab: this.handleActiveTab } }>`

And the second way is to just change _index.d.ts_ inside _node_modules\native-base_ and just add what is missing. Bad thing with this it will be overwritten when you upgrade native base, unless you add this file to your source control.

**Comment by bherila** [comment]
Also missing `NativeBaseComponent`

**Comment by AleksandarDev** [comment]
@SupriyaKalghatgi No new reports since Apr 18

Here is compiled list:

- [ ] `StyleProvider` PR https://github.com/GeekyAnts/NativeBase/pull/955
- [ ] `getTheme`
- [ ] `Form`
- [ ] `Label`
- [ ] `Fab`
- [ ] `ActionSheet`
- [ ] `Segment`
- [ ] `Toast`
- [ ] `Tab.onChangeTab`
- [ ] `Header.noShadow`
- [ ] `ListItem.noBorder`
- [ ] `NativeBaseComponent`

I can check definitions are still missing and can make PR for all if you approve it.

**Comment by lukecwilliams** [comment]
We see missing, for `Content`:
`disableKBDismissScroll`
`enableResetScrollToCoords`

Thanks!

**Comment by Offtree** [comment]
Button interface is at least missing the following:
```
badge?: boolean; 
vertical?: boolean;
```

I believe `Subtitle` interface should be renamed from `SubTitle` to `Subtitle`

**Comment by PaitoAnderson** [comment]
`Root` is also missing

**Comment by mcd-php** [comment]
Absence of `Root` is complete show-stopper and forces me to move my project from rock-solid TypeScript back to the Great Grimpen Mire of plain JavaScript

**Comment by bherila** [comment]
@AleksandarDev any update on PR? Need help?

**Comment by AleksandarDev** [comment]
@bherila I didn't yet get approval for a PR from collab user so I didn't even try to include missing definitions.

**Comment by AleksandarDev** [comment]
@mcd-php @PaitoAnderson `Root` is now in d.ts (added 8 days ago by shivrajkumar) you can take it from master or wait for next build

**Comment by bherila** [comment]
@shivrajkumar do you support @AleksandarDev making a PR for additional typescript definitions?

**Comment by SupriyaKalghatgi** [comment]
@AleksandarDev Please share the PR link here

**Comment by SupriyaKalghatgi** [comment]
This has been merged
