### ISSUE TITLE
Documentation problem for List Element

### ISSUE THREAD

**Issue by zenware** [GeekyAnts/NativeBase#694]
[Nativebase.io -> Docs -> v2.0.0 -> Components -> List](http://nativebase.io/docs/v2.0.0/components#list) suggests the property is `thumnail` when it should definitely be `thumbnail`
![Image of the issue](https://www.dropbox.com/s/1nn8v8a6opx65jc/Screenshot%202017-03-29%2018.12.49.png?dl=1)

Sorry about the issue for this, I wish there was a publicly obvious way to contribute to the documentation because I would have done that.

**Comment by sankhadeeproy007** [comment]
Hi @zenware. We're going to launch our open sourced documentation today. It is in gitbook, so hopefully it'll be easier for people to contribute.
