### ISSUE TITLE
View under Header

### ISSUE THREAD

**Issue by DannyAziz** [GeekyAnts/NativeBase#696]
react-native: 0.42, react: 15.4.1 and native-base: 2.0.12
Expected behaviour
I was expecting to get the header to be transparent, above the blue square. Instead the blue square goes on top of the header

Actual behaviour
![image](https://cloud.githubusercontent.com/assets/3679064/24503137/b425d2bc-1548-11e7-90c7-ab5e5233ff60.png)

Steps to reproduce (code snippet or screenshot)
```
<Container>
    <Header transparent style={{zIndex: 4}}>
        <Body>
            <Title>Fuck a duck</Title>
        </Body>
    </Header>
    <View style={{height: 200, backgroundColor: 'blue', position: 'absolute', width: 
     Dimensions.get('window').width,  zIndex: 1, opacity: 1}}></View>
</Container>
```

Played around with zIndex to no avail, would love some help

**Comment by GeekRishabh** [comment]
@DannyAziz 
![issueheader](https://cloud.githubusercontent.com/assets/23093075/25039843/87ab400a-2123-11e7-820a-64d0cb207a33.gif)

```
 <Container>
    <Header iosStatusbar= 'light-content' >
        <Body>
            <Title>Fuck a duck</Title>
        </Body>
    </Header>
    <View style={{ height:200, backgroundColor: 'blue', width: 
     Dimensions.get('window').width,  zIndex: 1, opacity: 1}}>
     </View>
</Container>

```
Try the above will work for you .

**Comment by SupriyaKalghatgi** [comment]
The `noShadow` prop of Header removes shadow from iOS Header and elevation from Android Header.

https://docs.nativebase.io/Components.html#header-no-shadow-headref
