### ISSUE TITLE
Focus capability for the Input component

### ISSUE THREAD

**Issue by LeoAref** [GeekyAnts/NativeBase#697]
This is a feature request to support the focusing capability to the Input component, something like:

```js
<Input
  focus={this.state.isSearchActive}
  value={this.props.search}
  onChangeText={this.props.setSearchText}
  placeholder="Search"
/>
```

**Comment by chrise86** [comment]
@LeoAref how did you resolve this?

**Comment by tharungeorgebabu** [comment]
how was this resolved

im on "native-base": "^2.3.0",

when i use Input and do a search--> at the point when there is no results returned--> focus goes away from the Input component

how to force the input to stay on the Input component?
