### ISSUE TITLE
Changelog is outdated.

### ISSUE THREAD

**Issue by yeknava** [GeekyAnts/NativeBase#699]
Changelog section in nativebase's site and Changelog file in repo both are outdated.
Please keep update it with each release. Thanks ;)

**Comment by SupriyaKalghatgi** [comment]
@yeknava Yes the ChangeLog with the repo is outdated.
But the Release Notes with the tags published are always up-to-date.
You can take a look at [Releases](https://github.com/GeekyAnts/NativeBase/releases).
