### ISSUE TITLE
Can't style <Footer>

### ISSUE THREAD

**Issue by Wu4D** [GeekyAnts/NativeBase#701]
Hello there, I've been strugling with this bug for like 4h

`import getTheme from './../native-base-theme/components';`
`import platform from './../native-base-theme/variables/platform';`

The render method:

`<StyleProvider style={getTheme(platform)}>

                <Container style={{marginTop: 53}}>

                    <Content>
                   
                    </Content>

                    <Footer>
                        <Col style={{justifyContent: 'center'}}>
                            <Text>Text</Text>
                            <Text>Lorem ipsum</Text>
                        </Col>
                        <Col style={{justifyContent: 'center', alignItems: 'flex-end', marginRight: 4}}>
                            <TouchableOpacity onPress={() => Actions.results()}>
                                <Text>Search</Text>
                            </TouchableOpacity>
                        </Col>
                    </Footer>

                </Container>
</StyleProvider>`

`And the <Container> is wraped inside <StyleProvider style={getTheme(platform)} ></ StyleProvider >`

And inside platform.js I have     

// Footer
`
  footerHeight: 55,
  footerDefaultBg: '#CCFF00',
`

But the style is not being applied

**Comment by GeekRishabh** [comment]
@Wu4D  All you need to do is to reload the app .seems to work fine. Do check again .

**Comment by shivrajkumar** [comment]
Closing the issue as the above solution should work.
Let me know if it doesn't.
