### ISSUE TITLE
FooterTab text color not change.

### ISSUE THREAD

**Issue by vkyii** [GeekyAnts/NativeBase#702]
Hi,
I have updated NB from 2.0.7 to 2.1.0 with react(15.4.1) and react-native(0.42.0),
It seems that the color of Button's Text in FooterTab not changed when switch active buttons.
PS: sorry can't upload picture, i tryed several times.

**Comment by vkyii** [comment]
I need add a 'active' property to Text component, which is not required in previous versions:
```
const isActive = this.state.activeTab;
<Footer>
    <FooterTab>
        <Button active={isActive}>
            <Text  active={isActive}>Apps</Text>
        </Button>
        <Button active={isActive}>
            <Text active={isActive}>Camera</Text>
        </Button>
        <Button  active={isActive}>
            <Text active={isActive}>Navigate</Text>
        </Button>
        <Button active={isActive}>
            <Text active={isActive}>Contact</Text>
        </Button>
    </FooterTab>
</Footer>
```

**Comment by christianguevara** [comment]
Yes, is not working in your theme if you set 'tabActiveBgColor' with a color you will see tabs are always active, even if states changes.
Maybe a workaround.

`let cycleStyle = {
            ...styles.footerTabDisabled
        };
        let amountsStyle = {
            ...styles.footerTabDisabled
        };
        if (this.isCycleActive()) {
            cycleStyle = {
                ...styles.footerTabEnabled
            };
        }
        if (this.isAmountsActive()) {
            amountsStyle = {
                ...styles.footerTabEnabled
            };
        }
        return (
            <Footer>
                <FooterTab>
                    <Button full onPress={() => this.props.setGroupCycleSection('cycle')}>
                        <Icon name="paper" style={cycleStyle}/>
                        <Text style={cycleStyle}>Ciclo</Text>
                    </Button>
                    <Button full onPress={() => this.props.setGroupCycleSection('amounts')}>
                        <Icon name="cash" style={amountsStyle}/>
                        <Text style={amountsStyle}>Montos</Text>
                    </Button>
                </FooterTab>
            </Footer>
        );`

**Comment by christianguevara** [comment]
+1

**Comment by andidev** [comment]
Same here

**Comment by shivrajkumar** [comment]
This seem to work fine.
The issue is may be due to ejected theme.
 If you had ejected the theme with v2.0.7, you need merge the new theme of v2.1.0 with it.
We are looking into ways to merge new themes with the old ones in a easier way. But for now you will have to do it manually.
Let me know if it works.

**Comment by vkyii** [comment]
1. change `"@shoutem/theme": "git+https://github.com/GeekyAnts/theme.git#caching"` to `"@shoutem/theme": "git+https://github.com/GeekyAnts/theme.git"` in file `node_modules/native-base/package.json`
2. `npm i`
Then everything is OK.
