### ISSUE TITLE
Shoutem Documentation

### ISSUE THREAD

**Issue by smooJitter** [GeekyAnts/NativeBase#704]
I notice you are now introducing shoutem.  Where can I learn about how shoutem and native-base work together

**Comment by himanshu-satija** [comment]
Shoutem is used as a theming engine in `native-base`. We have [forked](https://github.com/GeekyAnts/theme) it and customized according to our needs but usage mostly remains same.

For usage with native-base, following the [docs](https://docs.nativebase.io/CUSTOMIZE.html#Theming_NativeBase_Apps) should be enough.

To get more info, you can check shoutem theme documentation [here](http://shoutem.github.io/docs/ui-toolkit/theme/introduction)
