### ISSUE TITLE
Touchable Cards?

### ISSUE THREAD

**Issue by arnthorsnaer** [GeekyAnts/NativeBase#706]
Hi there 

I'm using react-native via Exponent ( expo 15.0.2 - native-base 2.1.0 - react 15.4.0 ). Can you point me in the right direction on how I can add "touchable" effect to a (native-base) card?

Looking at the source code it looks like I can add a "button" boolean to the CardItem component. This wraps it with TouchableOpacity. However since a Card can contain multiple CardItems, this does not really work. The semantics of a Card is that users interact with the card more than they would interact with parts of the card. 

Therefore I am interested in the style of the entire card changing when touched. Wrapping the whole card with TouchableOpacity does not work. 

Any ideas?

**Comment by aeonphyxius** [comment]
Any hints on this? I am actually looking to solve the same "problem" 

Thanks !!!

**Comment by arnthors** [comment]
This may have been fixed in https://github.com/GeekyAnts/NativeBase/commit/5374e8bf44117e0d143be1cddf32cd97519a9cab

Have not tested this though
