### ISSUE TITLE
problem with scoped npm packages... @expo/vector-icons

### ISSUE THREAD

**Issue by clayboyd** [GeekyAnts/NativeBase#707]
I'm having trouble reading the scoped npm packages.  This fails:

npm install @expo/vector-icons --save

npm ERR! unpack Could not read data for @expo/vector-icons@4.0.0
npm ERR! Darwin 16.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "@expo/vector-icons" "--save"
npm ERR! node v7.8.0
npm ERR! npm  v4.2.0

npm ERR! Invalid name: "@expo/vector-icons"
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/clboyd/.npm/_logs/2017-04-02T20_02_08_050Z-debug.log

It fails with various versions of node and npm...

I get similar scoped errors when trying to install the AwesomeNativeBase application following your instructions.

thanks,
clay

**Comment by GeekRishabh** [comment]
@clayboyd npm install @expo/vector-icons --save seems to work fine. Do check again and let know for which conditions are you facing the issue.share the NB, react & RN version you are using.

**Comment by sr1234** [comment]
Running into a similar problem when trying to install react-native-elements library:

`tests-MacBook-Pro:swipe samrazi$ npm install react-native-elements --save
npm ERR! Darwin 16.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "react-native-elements" "--save"
npm ERR! node v7.0.0
npm ERR! npm  v3.10.8

npm ERR! Invalid name: "@expo/vector-icons"
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/samrazi/Documents/dev-sandbox/udemyadvancedreactnative/swipe/npm-debug.log`

Any help appreciated.
