### ISSUE TITLE
an issue when upgrade RN43 

### ISSUE THREAD

**Issue by tonylinyy** [GeekyAnts/NativeBase#711]
hi,when upgrade native-base to RN43
there is an issue about:
react-native/Libraries/Components/StaticContainer   in SceneComponent.js
it should be: 
react-native/Libraries/Components/StaticContainer.react

**Comment by iambanh2** [comment]
I got problems.

**Comment by sanketsahusoft** [comment]
@tonylinyy @iambanh2 

We are fixing this.

**Comment by sanketsahusoft** [comment]
Guys, looks like RN43 requires React 16 and vector-icons doesn't have support for React 16. So, we will have to wait for third party libraries to be updated and then we can upgrade NativeBase. Until then use RN42.

**Comment by HilSny** [comment]
I got RN 43 working fine with NativeBase when I fixed this line in SceneComponents from:

```
var StaticContainer=require('react-native/Libraries/Components/StaticContainer');
```
to

```
var StaticContainer=require('react-native/Libraries/Components/StaticContainer.react');
```
Doesn't look like an issue with vector icons at least in the way that we use that package.

**Comment by HilSny** [comment]
For what its worth fixing the SceneComponent file allowed me to use NativeBase without issue (including the Icon component).

Not sure this is an issue with vector-icons and their compatibility with React 16.

**Comment by nouh** [comment]
https://github.com/oblador/react-native-vector-icons/issues/435 seems vector-icons works fine with react 16. The problem may still lie in native-base

**Comment by tonylinyy** [comment]
I edit the path to:react-native/Libraries/Components/StaticContainer.react
and everything is ok in my project,including vector-icons

**Comment by shivrajkumar** [comment]
Fixed in latest version v2.1.1

**Comment by DemisBand** [comment]
Sorry but I currently RN43/ Native Base 2.1.1 and the good way is :
**var StaticContainer=require('react-native/Libraries/Components/StaticContainer.js');**
not 
var StaticContainer=require('react-native/Libraries/Components/StaticContainer.react');

I test on ios..

**Comment by oximer** [comment]
You should update the react native on the package.json. It actually, now getting the 0.43, but default. Thus, the node_module continues with ".js" and it causes a error for compiling.
