### ISSUE TITLE
Unexpected token import in Shoutem dependency

### ISSUE THREAD

**Issue by mikestone14** [GeekyAnts/NativeBase#713]
## react-native, react and native-base version

`react` - 15.4.2
`react-native` - 0.42.3
`native-base` - 2.1.0
`jest` - 19.0.2

## Expected behaviour

The Jest test suite is expected to run & tests pass

## Actual behaviour

`SyntaxError: Unexpected token import` when importing `connectStyle` in the `@shoutem` dependency.

<img width="1096" alt="screen shot 2017-04-04 at 8 55 21 am" src="https://cloud.githubusercontent.com/assets/2905145/24657584/cdd60838-1914-11e7-9932-7aa88f5bccff.png">

## Is the bug present in both ios and android or in any one of them?

This has only been tested in iOS.

**Comment by kidnapkin** [comment]
just modify jest config package.json

Works for me. Seems like it's a common problem
```
  "jest": {
    "preset": "react-native",
    "transformIgnorePatterns": [
      "node_modules/(?!react-native|@shoutem/theme|@shoutem/animation|@shoutem/ui|tcomb-form-native)"
    ],
    "setupFiles": [
      "./test/setup.js"
    ]
  }
```

**Comment by matejstrasek** [comment]
I am still getting same error even after modifying jest config in package.json. Any ideas?

**Comment by sidd607** [comment]
@matejstrasek can you explain what you did ?

**Comment by matejstrasek** [comment]
@sidd607 sorry for late response. If you still haven't solve it: I was putting additional elements into `transformIgnorePatterns` for each library and didn't work. Using all in one element and with `|` as @kidnapkin did, worked.

**Comment by SupriyaKalghatgi** [comment]
Please check this with NativeBase 2.3.3

**Comment by srinuch1981** [comment]
It is not solved . Tried 2.3.3 and transformIgnorePatterns as well. 

"native-base": "2.3.3",
"react": "16.0.0-beta.5",
"react-native": "0.49.3",


"jest": {
		"preset": "react-native",
		"transformIgnorePatterns": [
			"node_modules/(?!(jest-)?react-native|react-navigation|react-clone-referenced-element|react-native-localization|native-base-shoutem-theme|@shoutem/theme|@shoutem/animation|@shoutem/ui|tcomb-form-native)"
		],
		"setupFiles": [
			"./jest-setup.js"
		]
	},

**Comment by benallfree** [comment]
```json
  "jest": {
    "preset": "react-native",
    "transformIgnorePatterns": [
      "node_modules/native-base-shoutem-theme"
    ]
  }
```
Works for me! 2.3.2

**Comment by SupriyaKalghatgi** [comment]
Updating the dependencies is the fix for this
There is a PR open for this #1391

**Comment by theohdv** [comment]
Still have the problem, 2.3.2 with:

```json
"jest": {
  "preset": "react-native",
  "setupFiles": [
    "<rootDir>/__tests__/jest/setup.js"
  ],
  "testPathIgnorePatterns": [
    "<rootDir>/__tests__/jest/",
    "<rootDir>/node_modules/"
  ],
  "transformIgnorePatterns": [
    "node_modules/(?!react-native|native-base-shoutem-theme|react-navigation)"
  ]
}
```

**Comment by SupriyaKalghatgi** [comment]
Check out fixes for jest with [2.5.0](https://github.com/GeekyAnts/NativeBase/releases/tag/v2.5.0)
This issue will be closed next week in case of no response

**Comment by alexfqc** [comment]
All options for `transformIgnorePatterns` are not working for me on react-native 0.56

**Comment by uc-asa** [comment]
My config for jest and it resolve my problem for **suthem lib** .

"jest": {
    "preset": "react-native",
    "transformIgnorePatterns": [
      "node_modules/(?!native-base-shoutem-theme|react-native)"
    ]
  },
