### ISSUE TITLE
Toast okay Button Not Displaying

### ISSUE THREAD

**Issue by muthuraman007** [GeekyAnts/NativeBase#715]
When i display more text in toast it gets stuck and need  to close app every time. 
To reproduce make the toast to display two line of text message this error will be produced.
The problem causing is when i display more text, toast button is not  displaying. if it displayed i can close the toast by clicking on it. Not displaying causes  toast to never be closed.

**Comment by danilvalov** [comment]
@muthuraman007 

I confirm.
I already sent a pull request, which fix this problem: https://github.com/GeekyAnts/NativeBase/pull/710
You can add this fix to your code or use my repository as a temporary solution.

**Comment by shivrajkumar** [comment]
Fixed in v2.1.3
