### ISSUE TITLE
Searchbar input not clicable on iOS

### ISSUE THREAD

**Issue by obykoo** [GeekyAnts/NativeBase#718]
I am using this with:
"react-native-router-flux"

Using "native-base": "^2.0.13", and "react": "15.4.2", "react-native": "0.42.0",

```
<Container>
       <Header searchBar rounded >
       <Button transparent onPress={()=>{Actions.pop()}}>
           <Icon name="arrow-back" />
       </Button>
         <Item>
               <Input keyboardType={'default'}  placeholder={translate.t('profile.searchIllness')} onChangeText={this.onTextChanged}   />
             </Item>
        </Header>

                {body}
                {spinner}

</Container>
```
Input looks like this and is not responsive at all:

![2017-04-05_15h49_13](https://cloud.githubusercontent.com/assets/25873477/24714260/4953a5ec-1a28-11e7-843a-0f79509c7e6b.png)

However this is working on Andorid and not working on iOS

**Comment by obykoo** [comment]
You have to set width of input othervise it wont work

**Comment by GeekRishabh** [comment]
@obykoo seems to work fine.even without width .

**Comment by HyperSimon** [comment]
input not clicable on iOS but work on Android too here

```javascript
         <Item inlineLabel>
            <Label style={{ color: '#979797' }}>姓名:</Label>
            <Input
              style={styles.input_name}
              onChangeText={this.props.onNameChange}
            />
          </Item>
```

**Comment by GeekRishabh** [comment]
@HyperSimon 
![issue](https://cloud.githubusercontent.com/assets/23093075/25039576/ce3e94ce-2121-11e7-8484-e5145d246131.gif)
it seem to work fine . Try out again .

**Comment by HyperSimon** [comment]
@GeekRishabh Thanks.In my case is that the following layout covers the input box, causing the input box to be clickable.
