### ISSUE TITLE
Unrecognized font family 'Ionicons'

### ISSUE THREAD

**Issue by charlieroth** [GeekyAnts/NativeBase#72]
Here I have a simple component: 
```
import React, { Component } from 'react';
import {
  Container,
  Header,
  Title,
  Content,
  Button,
  Icon,
} from 'native-base';

export default class App extends Component {
  render() {
    return(
      <Container>
        <Header>
          <Button transparent>
              <Icon name="ios-arrow-back" />
          </Button>

          <Title>Header</Title>

          <Button transparent>
              <Icon name="ios-menu" />
          </Button>
        </Header>

        <Content>

        </Content>
      </Container>
    );
  }
}
```
I ran `rnpm link` like I was told to do in the Getting Started section of the docs. I am getting this error: 
![screen shot 2016-07-21 at 11 43 59 am](https://cloud.githubusercontent.com/assets/13981427/17029309/c48ee584-4f38-11e6-8e01-0df6f7dabc8f.png)

Any suggestions? Should I try to link native-base manually following the instructions in the docs?

**Comment by advany** [comment]
Same problems... also checked xcode. The fonts are already in the build phase

**Comment by sankhadeeproy007** [comment]
You have restart packager after adding fonts. Close the packager terminal and restart from xcode. Should fix your problem.

**Comment by olivergeorge** [comment]
Try `rnpm link react-native-vector-icons`

**Comment by kumarryogeshh** [comment]
<projectDir>/node_modules/native-base/node_modules/react-native-vector-icons/RNVectorIconsManager/RNVectorIconsManager.h:9:9: 'RCTBridgeModule.h' file not found

**Comment by himanshu-sahusoft** [comment]
Try running `rm -rf node_modules && npm install`
If RN < 0.29, run `rnpm link react-native-vector-icons` 
If RN >= 0.29, run `react-native link react-native-vector-icons`

**Comment by RobbyRob81** [comment]
Same problem here even after following the above suggestions.

**Comment by tranquang7979** [comment]
I solved and I think this is one of cause. 
http://image.prntscr.com/image/837ddc4fea2d427e8466671c2515b3b1.png
I tried to re-run this command "react-native link react-native-vector-icons" because my RN >= 0.29.

**Comment by clucasalcantara** [comment]
react-native link react-native-vector-icons solved my problem.

**Comment by farruxx** [comment]
Only declaring in Info.plist helped
http://stackoverflow.com/a/30540901

**Comment by sravindravmd** [comment]
Hi All,
I was having same problem and resolved  by doing this.

1) close running packager 
2) run react-native link react-native-vector-icons
3 and run react-native  start --reset-cache
4) Finally  use react-native run-ios

**Comment by zhulinpinyu** [comment]
@sravindravmd thank you so much.

**Comment by clucasalcantara** [comment]
@charlieroth You can try to recreate the iOS Scheme on XCode, and run `react-native link` or `rnpm link` after.

**Comment by nicnilov** [comment]
What worked for me was uninstalling the `@expo/vector-icons` package recommended by [Native-base Getting Started guide](http://docs.nativebase.io/docs/GetStarted.html#Quick_Setup), and installing the `react-native-vector-icons` as a dependency. 

    npm install react-native-vector-icons --save
    react-native link react-native-vector-icons

**Comment by Lalit-Joshi** [comment]
react-native link react-native-vector-icons is working for me thanks.

**Comment by AbhayVarshney** [comment]
Hi, I am getting this same issue. So for some reason, my app is working perfectly fine when I run it through the emulator. But when I run it on my device, the same error is shown. I have no clue why it works on the emulator but not on the device.

**Comment by GeekRishabh** [comment]
@AbhayVarshney If you are using expo/CRNA then you need to import then Ionicons .
somewhat like 
```
  async componentWillMount() {
      await Expo.Font.loadAsync({
        'Roboto': require('native-base/Fonts/Roboto.ttf'),
        'Roboto_medium': require('native-base/Fonts/Roboto_medium.ttf'),
        'Ionicons': require('native-base/Fonts/Ionicons.ttf'),
      });
  }
```
you can have a look [here](https://github.com/GeekyAnts/NativeBase-KitchenSink/blob/updated/CRNA/js/setup.js) this will work for you .

**Comment by AbhayVarshney** [comment]
@GeekRishabh I don't use expo/CRNA. Will I need it in order to run it on the device? Is there another option?

**Comment by kadharmfn** [comment]
I had the same issue.

Solved by running first Link

    react-native link

Then restart,

    react-native run-ios

**Comment by ckim16** [comment]
I specifically want to use `Entypo` from `react-native-vector-icons`. I have copied over the `Fonts` folder to the Xcode, checked all the icon types are there in `info.plist` and `copy bundle resources`, `rm -rf node_modules && npm install`, clean up last build, `react-native link react-native-vector-icons` and then `npm start` but it still does not work.

```
import Entypo from 'react-native-vector-icons/Entypo';

<Entypo name={icon} size={25}/>
```
and nothing shows up (Iconwise..) :(

**Comment by wung-s** [comment]
I faced the issue with both `v2.1.4` and `v2.1.5`
So I fixed the version in `package.json` to `"native-base": "2.1.3"`
Then ran the following: 
`rm -rf node_modules`
`npm i`
`react-native link`

**Comment by zhangqiangoffice** [comment]
react-native link react-native-vector-icons solved my problem.

**Comment by cristianPerez** [comment]
# Solved with 

```bash
react-native link react-native-vector-icons
```

**Comment by tuanluu-agilityio** [comment]
These command resolved my issue:

```sh
react-native link react-native-vector-icons
react-native start --reset-cache
react-native run-ios
```

**Comment by Arshiamidos** [comment]
just do manual as @RobbyRob81  said 
![screen shot - - at](https://user-images.githubusercontent.com/6451804/37234422-dc6e51bc-240c-11e8-8a31-85c18912e9dd.png)

**Comment by Arshiamidos** [comment]
just adding manual as @RobbyRob81  said 
![screen shot - - at](https://user-images.githubusercontent.com/6451804/37234436-fad0575e-240c-11e8-966d-5231709d0c77.png)

**Comment by jerodgers1** [comment]
If you have tried everything and its still not working I suggest rechecking the spelling of the fonts you declare in Info.plist 
"typos are evil"

**Comment by SupriyaKalghatgi** [comment]
@vemundeldegard try the above mentioned solutions

**Comment by maniyarpayal** [comment]
@sravindravmd  Thanks. Your solution works for me.

**Comment by stepheljobs** [comment]
This works for me adding the fonts manually on the Build Phase tab of the xcode then run the it on xcode manually.

![screen shot 2018-09-14 at 2 59 24 am](https://user-images.githubusercontent.com/8773383/45509476-3f6a2d80-b7ca-11e8-91c9-e967c631099c.png)

**Comment by pinchez254** [comment]
The problem is with native-base Title, nativ- base uses custom fonts , import Text from react-native and style it to be a title instead if you are having trouble especially if you are are using expo

**Comment by shaynos** [comment]
I had this problem on a new react native project. I ran the project on the simulator through Xcode and it ran properly after that

**Comment by mahdi4187** [comment]
react-native link

**Comment by arhmnsh** [comment]
I'd tried all the steps mentioned in above comments like:

> close running packager
> run react-native link react-native-vector-icons
> and run react-native start --reset-cache
> Finally use react-native run-ios

Was still facing the issue.
I then restarted terminal, Xcode, simulator. It worked!

**Comment by ReactDevBeginner** [comment]
Hello Guys

Still facing this error more than 3 months i have tried all things, Please can someone help me to fix this please, I'm so confused.

the most screens of my application are using native-base :/

Also - Im using Visual Studio Code & windows device.

Please Advice !!

**Comment by forbesgillikin** [comment]
I was having this problem today on a fresh React Native install. I solved this issue by using the Legacy Build System in xCode instead of the default New Build System. You can change your build system settings by navigating to File > Project Settings > Shared Project Settings > Build System.

**Comment by pinchez254** [comment]
This mainly happens due to use of Icons from native base ... try to use
react-native vector icons or @expo vector icons.

**Comment by pinsoneatra** [comment]
try to delete ios/build, and rebuild by react-native run-ios.
that solved my problem.

**Comment by seunex** [comment]
If your iOS project is using CocoaPods (contains Podfile) and linked library has podspec file, then react-native link will link the library using Podfile. 

Add the comment below to the bottom of your podfile.

 # Add new pods below this line

Then run "react-native link [package_name]"

This works for me.

**Comment by LucasHelal** [comment]
easy solution

run

''' expo install expo-font '''

**Comment by codler** [comment]
Run `react-native link` then `react-native run-ios`

**Comment by eddyfrank** [comment]
For RN 0.60+ **don't** use `react-native link ...`! (see [Autolinking](https://github.com/react-native-community/cli/blob/master/docs/autolinking.md))

Instead add this in your `Podfile`:

```
pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
```

and run `pod update` (or `pod install`).

Furthermore add this in your `Info.plist`:

```
<key>UIAppFonts</key>
<array>
  <string>AntDesign.ttf</string>
  <string>Entypo.ttf</string>
  <string>EvilIcons.ttf</string>
  <string>Feather.ttf</string>
  <string>FontAwesome.ttf</string>
  <string>FontAwesome5_Brands.ttf</string>
  <string>FontAwesome5_Regular.ttf</string>
  <string>FontAwesome5_Solid.ttf</string>
  <string>Foundation.ttf</string>
  <string>Ionicons.ttf</string>
  <string>MaterialIcons.ttf</string>
  <string>MaterialCommunityIcons.ttf</string>
  <string>SimpleLineIcons.ttf</string>
  <string>Octicons.ttf</string>
  <string>Zocial.ttf</string>
</array>
```

(took from https://github.com/oblador/react-native-vector-icons#option-with-cocoapods)

Works fine in my project with:
```
"react": "16.9.0",
"react-native": "0.61.1",
"native-base": "2.13.8" (react-native-vector-icons@6.6.0),
```

**Comment by Bioinformatics-Surgeon** [comment]
Screen shot for adding Ionicons.ttf to `Info.plist`
<img width="1439" alt="Screen Shot 2020-01-17 at 9 02 55 PM" src="https://user-images.githubusercontent.com/31856466/72656932-e174c980-396c-11ea-9c24-29e3a52869b4.png">

**Comment by alexandermckay** [comment]
Simply add the missing font to your `ios/project_name/Info.plist` file.

Don't worry about using `react-native link` this is automatically taken care of in newer versions (from `0.60`) and messing around with linking can create annoying bugs.

I only use Material Community Icons so I can ignore the other icon fonts.

```
<key>UIAppFonts</key>
<array>
  <string>MaterialCommunityIcons.ttf</string>
</array>
```

One thing to be aware of is `react-native unlink react-native-vector-icons` clears the `UIAppFonts` array so unlink first, then edit `Info.plist`.

**Comment by kigh143** [comment]
I had the same problem, I fixed buy running run `react-native link react-native-vector-icons`

**Comment by thangpq** [comment]
> 2\. react-native link react-native-vector-icons



> Hi All,
> I was having same problem and resolved by doing this.
> 
> 1. close running packager
> 2. run react-native link react-native-vector-icons
> 3. and run react-native  start --reset-cache
> 4. Finally  use react-native run-ios

Perfect answer ! You helped me much !!!! Thanks you

**Comment by ugurcanalyuz** [comment]
> I solved and I think this is one of cause.
> http://image.prntscr.com/image/837ddc4fea2d427e8466671c2515b3b1.png
> I tried to re-run this command `react-native link react-native-vector-icons` because my RN >= 0.29.

Thanks, now working my project!

**Comment by gabrielmicko** [comment]
> <key>UIAppFonts</key>
> <array>
>   <string>AntDesign.ttf</string>
>   <string>Entypo.ttf</string>
>   <string>EvilIcons.ttf</string>
>   <string>Feather.ttf</string>
>   <string>FontAwesome.ttf</string>
>   <string>FontAwesome5_Brands.ttf</string>
>   <string>FontAwesome5_Regular.ttf</string>
>   <string>FontAwesome5_Solid.ttf</string>
>   <string>Foundation.ttf</string>
>   <string>Ionicons.ttf</string>
>   <string>MaterialIcons.ttf</string>
>   <string>MaterialCommunityIcons.ttf</string>
>   <string>SimpleLineIcons.ttf</string>
>   <string>Octicons.ttf</string>
>   <string>Zocial.ttf</string>
> </array>

Thanks for this!

**Comment by leonzuendel** [comment]
this is still an issue and i tried EVERY step from EVERY issue i found on several plattforms (not only git and even for only expo or react native) - it is still relevant and the documentation is literally useless and has so many errors that it's not even fun anymore... 

icons are not showing due to the font family being unrecognized and loading them 1:1 like in the docs and i also tried several other ways - there not working alone and not in the (also so terribly bad documented) tab navigation

i never write issues myself but THIS drives me crazy. even a simple thing like that can't be documented right? seems like i'm giving up vue native at this point

**Comment by anmolagarwal17** [comment]
> Screen shot for adding Ionicons.ttf to `Info.plist`
> 
> xcode version 11.3
> 
> `"native-base": "^2.13.8", "react": "16.9.0", "react-native": "0.61.5"`
> 
> <img alt="Screen Shot 2020-01-17 at 9 02 55 PM" width="1439" src="https://user-images.githubusercontent.com/31856466/72656932-e174c980-396c-11ea-9c24-29e3a52869b4.png">
> 
> I read through link provided by eddyfrank. (https://github.com/oblador/react-native-vector-icons#option-with-cocoapods)
> Followed the iOS portion shown below:
> ![image](https://user-images.githubusercontent.com/31856466/72657040-94ddbe00-396d-11ea-84dd-6f7eb73c1af9.png)

Thanks a lot man 🔥

Also, everyone else, you need to add fonts manually in the `./ios/{yourAppName}/Info.plist` file.
To add it manually paste below code in that file (to add all fonts):
`
<key>UIAppFonts</key>
<array>
  <string>AntDesign.ttf</string>
  <string>Entypo.ttf</string>
  <string>EvilIcons.ttf</string>
  <string>Feather.ttf</string>
  <string>FontAwesome.ttf</string>
  <string>FontAwesome5_Brands.ttf</string>
  <string>FontAwesome5_Regular.ttf</string>
  <string>FontAwesome5_Solid.ttf</string>
  <string>Foundation.ttf</string>
  <string>Ionicons.ttf</string>
  <string>MaterialIcons.ttf</string>
  <string>MaterialCommunityIcons.ttf</string>
  <string>SimpleLineIcons.ttf</string>
  <string>Octicons.ttf</string>
  <string>Zocial.ttf</string>
  <string>Fontisto.ttf</string>
</array>
`

More on it: [here](https://github.com/oblador/react-native-vector-icons#option-manually)

**Comment by Ayzekberk** [comment]
my react version is over 0.6

1) i successfully install vector icons first `npm install react-native-vector-icons`
2) i did `npx pod-install` successfully (I don't use react-native link because it gives error and also when i check react-native > 0.6 there is autolinking usage so react-native link not preferable in react-native > 0.6)
3) Than i ran my app with this command
`npx react-native run-ios --simulator="iPhone 8"`
4) in my App.js file there is import like this. Also library shows no error !
`import Ionicons from "react-native-vector-icons/Ionicons";`

5)But when i want to use ionicons in JSX like this

I got this error Unrecognized font family 'Ionicons'

than i ran react-native link react-native-vector-icons

also when i build like this situation o my build was failed. But when i unlink my build successfull.

I don't understand where i make a mistake

**Comment by Ayzekberk** [comment]
Most important think is if you face with this error if react-native version > 0.6;

1) ***** MOST IMPORTANT IS THIS : 
Don't use `reack-native link` and unlink your dependecy if you link before `react-native unlink react-native-vector-icons` 

2) you have to link manually. So in update `ios` folder update your `Podfile` with your dependency
`pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'`

3) than update inside of your`info.plist` file inside `ios` folder. Add those fonts under `<key>UIAppFonts</key>`
                 ```
                 <string>AntDesign.ttf</string>
		<string>Entypo.ttf</string>
		<string>EvilIcons.ttf</string>
		<string>Feather.ttf</string>
		<string>FontAwesome.ttf</string>
		<string>FontAwesome5_Brands.ttf</string>
		<string>FontAwesome5_Regular.ttf</string>
		<string>FontAwesome5_Solid.ttf</string>
		<string>Fontisto.ttf</string>
		<string>Foundation.ttf</string>
		<string>Ionicons.ttf</string>
		<string>MaterialCommunityIcons.ttf</string>
		<string>MaterialIcons.ttf</string>
		<string>Octicons.ttf</string>
		<string>SimpleLineIcons.ttf</string>
		<string>Zocial.ttf</string>
```
4) dont forget to run `pod update` inside `ios` directory on terminal
5) run your app by `npx react-native run-ios --simulator="iPhone 8" `
