### ISSUE TITLE
How to programmatically "cascade" theme styles?

### ISSUE THREAD

**Issue by AshCoolman** [GeekyAnts/NativeBase#721]
I'm a bit confused on the best way to pull in theme variables and use them within a Custom component.

## Packages

* react-native:0.42.3 
* native-base: 2.1.0

## Expected behaviour

`myThemeColors.js` (rough snippet):

    "btnPrimaryBg": 'lightblue',
    "btnPrimaryColor": 'blue',

`App.js` (rough snippet):

     import getTheme from 'native-base/src/theme/components';
     import myColors from './myColors';

    export default class App extends React.Component {
      render() {
        <StyleProvider style={getTheme(styleConstants)}>
          <MyComponent>
              Is this blue?
          </MyComponent>
        </StyleProvider>
      }
    }

`MyComponent.js` (rough snippet):

      import { Button, Text } from 'native-base';

      export default const MyComponent = props => (
      <Button primary={true} >
        <Text>
          {props.children}
        </Text>
      </Button>
      )

Currently this displays `MyComponent`:

 * background lightblue
 * text white

I want `MyComponent` displayed:

* background: lightblue
* text: **blue**

I'd like the color of `<Text />` to grab the **blue** from the `<Button />`. Put another way, I'd like to _programmatically cascade_ **native-base** _Button theme_ ([_primary_, _success_, _info_, _danger_ etc](http://nativebase.io/docs/v2.0.0/components#button)) into `<Text />`. 

One option might be to create a _new_ theme, just for the button via shoutem somehow - but I feel this is overly complex.

What would be a nice way of doing this?

http://stackoverflow.com/questions/43236508/how-to-cascade-native-base-theme-values-into-children

**Comment by shivrajkumar** [comment]
@AshCoolman You can eject nativebase theme and customize it as per your requirements.
You can just edit and use your own style in the ejected theme or add new props with new set of style rules to a component.
