### ISSUE TITLE
Android Back button in ActionSheet

### ISSUE THREAD

**Issue by pselibas** [GeekyAnts/NativeBase#722]
When an ActionSheet is displayed and the user presses the Android back button an alert is shown instead of closing the ActionSheet.

## react-native, react and native-base version
2.1.0
## Expected behavior 
ActionSheet should be closed.
## Actual behavior
An alert is shown saying "Modal has been closed."
## Is the bug present in both ios and android or in any one of them?
Only exists in Android

**Comment by sankhadeeproy007** [comment]
@shivrajkumar Can you take a look at this? Should be very straight forward.
