### ISSUE TITLE
[Help Wanted] How to hide the gray split line of header on IOS ?

### ISSUE THREAD

**Issue by HyperSimon** [GeekyAnts/NativeBase#724]
<img width="464" alt="2017-04-07 5 40 37" src="https://cloud.githubusercontent.com/assets/9377192/24794876/e030bdd2-1bb9-11e7-9cfe-bb2bed3c179d.png">

Now I want to hide the gray split line, I read the entire document, but did not find the relevant settings. 

This is my code

```javascript
        <Header
          noShadow={true}
          transparent
          style={{ ...styles.header }}
        >
          <Left style={{ ...styles.header_left }} />

          <Body style={{ ...styles.header_body }}>
              ...
          </Body>

          <Right style={{ ...styles.header_right }} />
        </Header>

```

**Comment by shivrajkumar** [comment]
@HyperSimon `noShadow`/`hasTabs` prop to the header should do the trick.
Let me know if it doesn't work. And do specify the version of NativeBase.
