### ISSUE TITLE
SceneComponent.js: module does not exist in the module map

### ISSUE THREAD

**Issue by cyaxares** [GeekyAnts/NativeBase#725]
I used native base & It works properly, today i updated npm, now a problem appears and i get this error:
![nativebase](https://cloud.githubusercontent.com/assets/9538639/24797604/373d879e-1ba7-11e7-964b-6065684194c7.png)

**Comment by flaviojunior** [comment]
I'm getting same error.
I trying to compile project using native base and typescript. But I getting some errors.

What's the native-base version are you using?

**Comment by shivrajkumar** [comment]
@flaviojunior @cyaxares latest version of NativeBase (v2.1.1) works for RN 43 and React 16.
For versions below that you need to use NativeBase v2.1.0

**Comment by cyaxares** [comment]
I downgrade native-base fixed

Thanks @shivrajkumar

**Comment by gwilymhumphreys** [comment]
Hey, if a release has breaking changes could you please release a new major version rather than a patch - this should be v3.0.0 to be in line with semantic versioning (and not break everyones builds, hah). Cheers 👍
