### ISSUE TITLE
Unable to import 'native-base/ui'.

### ISSUE THREAD

**Issue by smilewithsiddharth** [GeekyAnts/NativeBase#727]
I have installed native-base 2.1.1 through npm install native-base --save. 
but whenever i am trying to use 'native-base/ui' its throwing this error : 
error: bundling: UnableToResolveError: Unable to resolve module `native-base/ui` from `E:\ReactNativeApps\srmezy\src\components\LoginFormAdvance.js`: Module does not exist in the module map or in these directories:
  E:\ReactNativeApps\srmezy\node_modules\native-base
![whatsapp image 2017-04-08 at 16 06 07](https://cloud.githubusercontent.com/assets/17086526/24828175/68aa7bf6-1c75-11e7-91e1-7f967db777e7.jpeg)

**Comment by sankhadeeproy007** [comment]
Hi, please use `native-base` instead of `native-base/ui`
