### ISSUE TITLE
How can I listen to onPress events for InputGroup Icon?

### ISSUE THREAD

**Issue by sodik82** [GeekyAnts/NativeBase#73]
I would like to respond to `Icon` clicks inside of InputGroup - e.g. I want to cancel users input when he clicks "cross" icon inside of text input. 

I have tried following
```
      <InputGroup>
          <TouchableHighlight onPress={() => console.log("ahoj")}>
            <Icon name="ios-home" />
          </TouchableHighlight>
          <Input  {...props}/>
      </InputGroup>
```
but that just end up with "undefined exception" in `getIconProps` of `InputGroup.js@99:0`

I am using version `0.5.0`

**Comment by sankhadeeproy007** [comment]
Hi @sodik82! Thanks for pointing it out. It goes straight into our roadmap for the next release.

**Comment by sankhadeeproy007** [comment]
@sodik82 You can add a `<Button>` inside `<InputGroup />` for the desired effect. 
```
<InputGroup>
   <Icon name="ios-home" />
   <Input  {...props}/>
   <Button transparent onPress={} >
      <Icon name="ios-home" />
   </Button>
</InputGroup>
```
Please note that the  Icon will be aligned to the right. We're working on making it more configurable.

**Comment by sodik82** [comment]
thanks. it is working now in `0.5.1`.

just small note - I have to use `small` button, since normal button size gets cut by overflow.

**Comment by SupriyaKalghatgi** [comment]
@sodik82 Did you go through [Button-Size](http://nativebase.io/docs/v0.5.0/components#buttonSize)

**Comment by sodik82** [comment]
yes.... when I "just" use your example the button icon is cut off like here
![image](https://cloud.githubusercontent.com/assets/6132259/17130051/dc9bfce8-5316-11e6-92db-c682e42bcabf.png)

when I use small button, it is okey (just the icon is smaller :))
```
            <Button transparent small onPress={props.onReset}>
              <Icon name="ios-close" />
            </Button>
```

**Comment by sankhadeeproy007** [comment]
Good to know it's working. You can increase/decrease the Icon size though.
