### ISSUE TITLE
Form Item Showing Empty on Inner Input

### ISSUE THREAD

**Issue by leyuan** [GeekyAnts/NativeBase#730]
## react-native, react and native-base version
I upgraded to 2.1.1 today.
Before it was working fine in 2.0.12

## Expected behaviour
Worked as documentation

## Actual behaviour
Placeholder not showing, content not editable

## Steps to reproduce (code snippet or screenshot)
Same code from http://nativebase.io/docs/v2.0.0/components#form

```
                <Content>
                    <Form>
                        <Item>
                            <Input placeholder="Username" />
                        </Item>
                        <Item last>
                            <Input placeholder="Password" />
                        </Item>
                    </Form>
                </Content>
```

## Screenshot of emulator/device
It's empty

![image](https://cloud.githubusercontent.com/assets/1417993/24847431/274ba892-1d7e-11e7-9a3e-68a84e6dc431.png)

But if you remove `<Item>` the input fields show up

## Is the bug present in both ios and android or in any one of them?
Only tested in IOS, but since this is pretty basic components, I guess it's breaking for both.

## Any other additional info which would help us debug the issue quicker.

package.json
```
  "dependencies": {
    "color": "^0.11.3",
    "firebase": "^3.7.0",
    "lodash": "^4.13.1",
    "moment": "^2.13.0",
    "native-base": "2.1.1",
    "react": "16.0.0-alpha.3",
    "react-native": "0.43.1",
    "react-native-easy-grid": "0.1.8",
    "react-native-facebook-login": "^1.4.0",
    "react-native-modalbox": "^1.3.4",
    "react-native-router-flux": "^3.38.0",
    "react-redux": "^5.0.2",
    "redux": "^3.6.0",
    "redux-persist": "^4.0.0",
    "redux-thunk": "^2.2.0",
    "remote-redux-devtools": "^0.5.0",
    "whatwg-fetch": "^1.0.0"
  },
  "devDependencies": {
    "babel-eslint": "^6.1.2",
    "babel-jest": "17.0.0",
    "babel-preset-react-native": "1.9.0",
    "chai": "^3.5.0",
    "eslint": "^3.5.0",
    "eslint-config-airbnb": "^11.1.0",
    "eslint-plugin-import": "^1.14.0",
    "eslint-plugin-jsx-a11y": "^2.2.1",
    "eslint-plugin-react": "^6.2.0",
    "eslint-plugin-react-native": "^2.0.0",
    "jest": "17.0.0",
    "jest-react-native": "17.0.0",
    "mocha": "^2.5.3",
    "react-test-renderer": "15.3.2",
    "remote-redux-devtools-on-debugger": "^0.7.0",
    "remotedev-server": "^0.1.2"
  },
  "jest": {
    "preset": "react-native"
  }
```

**Comment by kitsune7** [comment]
I've been having the same issue. I managed to get the input fields working again after tinkering with them for a few hours, but it was a pain and I'm still having the same issue with other types of input.

They're still there if we are, in fact, having the same problem. Try adding a style to it like `style={{ borderWidth: 1, borderColor: '#2ac' }}` to make it show up so you can at least see it.

**Comment by leyuan** [comment]
@kitsune7 yeah man, I am expecting this to get fixed soon!

**Comment by shivrajkumar** [comment]
@leyuan @kitsune7 You need to add input.js https://github.com/GeekyAnts/NativeBase/blob/master/src/theme/components/Input.js in your theme and include that in index.js.
Let me know if it works

**Comment by kitsune7** [comment]
Customizing the theme didn't do too much to fix the problem (although I was glad to get some more control over things...), but I managed to get everything working again.

There was a parent component with an `alignItem: 'center'` property that was screwing things up. I'd suggest playing around with some styles on the parent components.

**Comment by leyuan** [comment]
hey @kitsune7 
@shivrajkumar 's solution does fix for me.
Thanks!
