### ISSUE TITLE
Need documentation with examples in 2.1.1 Tabs.

### ISSUE THREAD

**Issue by tishad770** [GeekyAnts/NativeBase#731]
I read the documentation on nativebase.io and want to use tabs. Here's what I am planning to do-

In each tab, i call the same component with different props and will make an api call to fetch some data in the tab. But i am facing problems with the navigation and page transitions. Is there any full documentation where I can get idea about the tab navigation?

My code is like this: 

`<Tabs>`
`    <Tab heading="First">`
`        <TabList data = "first" />`
 `   </Tab>`
`    <Tab heading="Second">`
`        <TabList data = "Second" />`
`    </Tab>`
`    <Tab heading="Third">`
`       <TabList data = "Third" />`
`    </Tab>`
`    <Tab heading="Fourth">`
`        <TabList data = "Fourth" />`
`    </Tab>`
`</Tabs>`

What am I missing here?

**Comment by GeekRishabh** [comment]
@tishad770 have a look [here](https://github.com/GeekyAnts/NativeBase-KitchenSink) .you can get an idea how to deal with tab .
