### ISSUE TITLE
URGENT! Docs are Broken - Merge Conflict

### ISSUE THREAD

**Issue by masiamj** [GeekyAnts/NativeBase#732]
This is not an issue with your component library.

The NativeBase docs on GitBook are broken; someone incorrectly pushed up code with a merge conflict, and it is causing the page not to load.

Expected Behavior: Page load with correct documentation.

Actual Behavior: Old version of documentation trying to load with incorrect assets and params.

Steps To Reproduce: Visit: https://docs.nativebase.io/

Screenshot: 
<img width="763" alt="screen shot 2017-04-10 at 11 36 40 am" src="https://cloud.githubusercontent.com/assets/7084914/24869680/02e632d8-1de2-11e7-892a-4d6dca979e2e.png">

**Comment by sankhadeeproy007** [comment]
@masiamj Thanks for reporting. Has been fixed!
