### ISSUE TITLE
Can't specify "iconStyles" on <Fab />

### ISSUE THREAD

**Issue by superquest** [GeekyAnts/NativeBase#733]
## Expected behaviour
I would expect the following to make a fab with a red "create" icon in it.

```
<Fab iconStyles={{ color: 'red' }}>
  <Icon name='create' />
</Fab>
```

## Actual behaviour
Icon remains the default color, the hex value `#fff`

## More information

[These are the default values](https://github.com/GeekyAnts/NativeBase/blob/30b90f09d0af85cd318e700c93917e11ca27c34d/src/basic/Fab.js#L119) I would like the ability to override

**Comment by shivrajkumar** [comment]
Fixed in v2.1.3
