### ISSUE TITLE
Picker inside Item on android not working, running well on ios

### ISSUE THREAD

**Issue by yovierayz** [GeekyAnts/NativeBase#734]
I've issue to use Picker inside Item
<img width="559" alt="screen shot 2017-04-11 at 12 09 32" src="https://cloud.githubusercontent.com/assets/2038089/24893736/c843128a-1eaf-11e7-99a6-5ef27ea54b11.png">

Running well on IOS
<img width="684" alt="screen shot 2017-04-11 at 12 03 04" src="https://cloud.githubusercontent.com/assets/2038089/24893615/de4d29fe-1eae-11e7-8fc6-51f679e3a58d.png">

But picker not working on Android
<img width="578" alt="screen shot 2017-04-11 at 12 02 58" src="https://cloud.githubusercontent.com/assets/2038089/24893628/fae98e68-1eae-11e7-8931-713f0db6b99c.png">

When i moves Picker to outside Item, works on IOS and Android. Thanks.

**Comment by shivrajkumar** [comment]
@yovierayz You will need to apply some width to the picker.

**Comment by dylannlaw** [comment]
It works after adding width to the picker.

**Comment by yovierayz** [comment]
@shivrajkumar ok it's works, tq :)

**Comment by sujayjaju** [comment]
This needs to be in the docs, right?

**Comment by isaachinman** [comment]
This should be in the docs, 100%. @shivrajkumar Would you accept a PR?

**Comment by stefmabo** [comment]
I think that would be better:  `... <Picker style={{flex: 1}} ...`
