### ISSUE TITLE
How can I center a View in <Content> vertically?

### ISSUE THREAD

**Issue by Symous** [GeekyAnts/NativeBase#735]

**Comment by shivrajkumar** [comment]
You can do `<Content  contentContainerStyle={{ justifyContent: 'center', flex: 1  }}>`

**Comment by Symous** [comment]
yes,friend,it truly worked,but imagine this kind of situation,I have a List in Content to display some items and there should have a  picture in the center of the screen to remind the user when there is no item in List.
If we user <Content contentContainerStyle={{ justifyContent: 'center', flex: 1 }}>,the List will display in the center. Is there any elegant way to do this?such as add a property  to the List to make it fill in the screen.

**Comment by sankhadeeproy007** [comment]
`<Content contentContainerStyle={{ justifyContent: (condition for showing picture) ? 'center' : undefined, flex: (condition for showing picture) ? 1 : undefined }}>`

**Comment by sulthanmamusa** [comment]
Great things, its working fine.

**Comment by rubanraj54** [comment]
If I do this, then scroll bar is not appearing in my case.
