### ISSUE TITLE
Checkbox component ---checkboxSize attribute not working

### ISSUE THREAD

**Issue by arunkumarrmrj** [GeekyAnts/NativeBase#737]
Hi 

"native-base": "^0.5.13",
"react": "15.4.2",
"react-native": "0.42.3",

`<CheckBox checked={true}  checkboxSize={20}/>`

But not change the checkbox size

I'm using checkboxSize values in number,string,... but not working

Let me know how to change checkboxsize

**Comment by shivrajkumar** [comment]
@arunkumarrmrj You can change the size in  your theme https://github.com/GeekyAnts/NativeBase/blob/v0.5.13/Components/Themes/light.js#L77

**Comment by GeekRishabh** [comment]
@arunkumarrmrj  checkout the [compatibility](https://docs.nativebase.io/docs/Compatibility.html ) of NB too with react and RN

**Comment by waltermvp** [comment]
is the checkbox prop no longer supported?

**Comment by SupriyaKalghatgi** [comment]
@waltermvp Please check docs
Also stay tuned for new update of docs

**Comment by waltermvp** [comment]
Do you have a link to the docs? I've seen with both checkbox as a prop and another that says to use theming.

**Comment by waltermvp** [comment]
@supriyakalghatgi

**Comment by SupriyaKalghatgi** [comment]
@waltermvp you could Google it !

**Comment by SupriyaKalghatgi** [comment]
https://docs.nativebase.io/

**Comment by waltermvp** [comment]
I have seen that documentation and conflicting documentation as well. 'checkboxSize' seems broken to me despite the documentation. However in some docs within the repo it suggests to only use a theme.  @supriyakalghatgi

**Comment by SupriyaKalghatgi** [comment]
@waltermvp 
> seen that documentation and conflicting documentation as well

Please elaborate on this

**Comment by SupriyaKalghatgi** [comment]
`checkboxSize` works fine from theme
https://github.com/GeekyAnts/NativeBase/blob/master/src/theme/variables/commonColor.js#L94

**Comment by impactcolor** [comment]
@SupriyaKalghatgi you got a horrible attitude.  Why are you even on here if you don't want to help anyone?
