### ISSUE TITLE
<Item> theme overrides <Form> theme

### ISSUE THREAD

**Issue by lashae** [GeekyAnts/NativeBase#738]
I'm using `<StyleProvider>` at my `<App>` component level, which means my all App is styled with NB theme. 

I have the following `Login` component:

```
            <Container>
                <Content>
                    <Form>
                        <Item stackedLabel label="Username">
                            <Label>Username</Label>
                            <Input style={{backgroundColor: 'red'}} />
                        </Item>
                        <Item stackedLabel last label="Password">
                            <Label>Password</Label>
                            <Input />
                        </Item>
                    </Form>
                </Content>
            </Container>
```

And the `Input`s are rendered very tiny at the center of their respective rows. Please see: http://pasteboard.co/jccYzby1.png 

If I remove, 

```
'NativeBase.Item': {
                ...itemTheme( variables ),
            },
```

part from `native-base-theme/components/index.js`the `Input`s are rendered as expected *in terms of width*. Please see: http://pasteboard.co/35YXLqfXJ.png

It seems, somehow, `Form` and `Item` themes are overlapping for width definition.

## react-native, react and native-base version
React-Native: 0.43.2, React: 16.0.0-alpha.6, NB: 2.1.1
## Expected behaviour
Full-width Input
## Actual behaviour
Very narrow, centered Input
## Steps to reproduce (code snippet or screenshot)
Please see above
## Screenshot of emulator/device
Please see above
## Is the bug present in both ios and android or in any one of them?
Both.

---

# Edit
Further debugging yield me to the problematic style rule for `.stackedLabel`.

It is here: https://github.com/GeekyAnts/NativeBase/blob/master/src/theme/components/Item.js#L202

Changing `alignItems: 'center'` to `alignItems: 'stretch'` seems to resolve the issue for `.stackedLabel`.

So as a workaround I added `alignItems: 'stretch'` right under this line: https://github.com/GeekyAnts/NativeBase/blob/master/src/theme/components/Item.js#L47 

However problem is there for all other `<Item>` variants: `.fixedLabel`, `.inlineLabel`, and `.floatingLabel` and perhaps there is another central main cause.

Do you have any comment/idea on this?

**Comment by lashae** [comment]
Further debugging yield me to the problematic style rule! 

It is here: https://github.com/GeekyAnts/NativeBase/blob/master/src/theme/components/Item.js#L202

Changing `alignItems: 'center'` to `alignItems: 'stretch'` seems to resolve the issue.

Do you have any comment/idea on this?

**Comment by shivrajkumar** [comment]
@lashae You need to add `input.js` https://github.com/GeekyAnts/NativeBase/blob/master/src/theme/components/Input.js in your theme and include that in `index.js`.

**Comment by lashae** [comment]
@shivrajkumar My ejected NB theme/components folder doesn't have this `Input.js` file. Is it normal?

**Comment by shivrajkumar** [comment]
@lashae It seem to work fine for me.
Do you have `input.js` https://github.com/GeekyAnts/NativeBase/blob/master/src/theme/components/Input.js in your ejected theme and is it included in theme `index.js` this way https://github.com/GeekyAnts/NativeBase/blob/master/src/theme/components/index.js#L77

**Comment by lashae** [comment]
@ahivrajkumar Strangely I hadn't but I added after your emphasis. However it didn't make any difference.  I also tested on a real device however it didn't make sense. 

Do we both have the exact version of React, RN and NB? If so, how can we proceed to debug?

**Comment by shivrajkumar** [comment]
Can you check if the issue still exist if you do not wrap your app with `StyleProvider`. In that case the app will use theme from `native-base` module.

**Comment by lashae** [comment]
@shivrajkumar I cannot reproduce the error now. Perhaps somehow 5374e8b has resolved it. You can close the issue, thank you for your assistance!
