### ISSUE TITLE
Floating Action Button don't show ripple effect on Android

### ISSUE THREAD

**Issue by JonatanSalas** [GeekyAnts/NativeBase#740]
Hi guys! Thanks for this amazing library! 

I'm facing an issue with Floating Action Button not showing Ripple Effect in version >= Lollipop.

## react-native, react and native-base version
RN 0.43.0, R 16.0.0-alpha.3, NB 2.1.1
## Expected behaviour
In Android version >= Lollipop, every touchable view should show a ripple effect when performing a click
## Actual behaviour
When using the Floating Action Button on Android it doesn't show the ripple effect
## Is the bug present in both ios and android or in any one of them?
Android devices only, applying to version >= Lollipop. 
## Any other additional info which would help us debug the issue quicker.
**The bug seems to be because of the usage of [TouchableOpacity](http://facebook.github.io/react-native/releases/0.43/docs/touchableopacity.html)**. To render a Touchable view that supports ripple effect, you should use the component [**TouchableNativeFeedback**](http://facebook.github.io/react-native/releases/0.43/docs/touchablenativefeedback.html)

You could apply a check for Platform, and return a different kind of TouchableView when rendering for Android/IOS.

If you give me the ok, I would like to make a PR to help you with this issue, Let me know!

**Comment by shivrajkumar** [comment]
@JonatanSalas Check the latest of NativeBase version 2.2 for the fix

**Comment by JonatanSalas** [comment]
@shivrajkumar Okay! I will check it today! Thanks!
