### ISSUE TITLE
'shoutem/animation' is not in the npm registry.

### ISSUE THREAD

**Issue by zuojianjian** [GeekyAnts/NativeBase#741]
and i am try npm install --save @shoutem/ui but fail
error log: 
npm ERR! addLocal Could not install shoutem/ui
npm ERR! Error: ENOENT: no such file or directory, stat 'D:\workdir\reactdir\PracticeRN\shoutem\ui'

**Comment by shivrajkumar** [comment]
@zuojianjian `npm install --save @shoutem/ui` and `npm install --save @shoutem/animation` seems to work fine. Do check again and let know on which condition are you facing the issue
