### ISSUE TITLE
Is there anyway to have a global style.js, and not one for each screen ?

### ISSUE THREAD

**Issue by pkassonss** [GeekyAnts/NativeBase#742]
Been trying out the starter kit and the kitchen sink examples and they are great.

However, each screen 'folder' has an included style ... I would expect there is an easy way to have a global style for all, much like in web dev ... and that if desired, the folder style could override?

**Comment by GeekRishabh** [comment]
@pkassonss what you an do is eject out theme using ```node node_modules/native-base/ejectTheme.js ``` and make changes in the component style as per your need . if you want to customize it in only few component then you have to include different style file .

**Comment by pkassonss** [comment]
Sorry, not following.  Are you saying there to use a base style sheet in this base folder and somehow it will be 'global' ?

**Comment by GeekRishabh** [comment]
@pkassonss if you want to provide style to NB components then what you can do is eject out theme using ```node node_modules/native-base/ejectTheme.js ```and make changes in the component style as per your need .and if you want to provide style to RN component then what you can do is create another folder in the main directory of your app or anywhere in your app (as per you) and import the style from there in components that you want to pass style to.

**Comment by himanshu-satija** [comment]
@pkassonss In [KitchenSink app](https://github.com/GeekyAnts/NativeBase-KitchenSink), `native-base-theme` folder contains the ejected theme which will be applied globally if you wrap your root component with `StyleProvider` from native-base.

See how StyleProvider is used [here](https://github.com/GeekyAnts/NativeBase-KitchenSink/blob/master/js/AppNavigator.js)

Get more info [here](https://docs.nativebase.io/CUSTOMIZE.html#Theming_NativeBase_Apps)

`styles.js` in screen folders is applied as inline style which overrides the global style coming from theme.
