### ISSUE TITLE
Some things not working with NativeBase

### ISSUE THREAD

**Issue by pkassonss** [GeekyAnts/NativeBase#744]
Using:

    "native-base": "^2.1.0",
    "react": "^16.0.0-alpha.6",
    "react-native": "^0.43.3",

But, things like Toast.show not working -

Unhandled JS Exception: undefined is not an object (evaluating '_nativeBase.Toast.show')

Using following code (source example, copied from the website)

                <Button onPress={()=> Toast.show({
                    text: 'Wrong password!',
                    position: 'bottom',
                    buttonText: 'Okay',
                    duration: 3000
                   })}>
                   Toast
                </Button>

Thanks.

**Comment by GeekRishabh** [comment]
@pkassonss seems to work fine make sure that you are following the [Compatibility Modes](https://docs.nativebase.io/docs/Compatibility.html) . 
![toast](https://cloud.githubusercontent.com/assets/23093075/25080012/05b3a5fe-235f-11e7-9ac0-95f58eba3e7a.gif)

**Comment by GeekRishabh** [comment]
@pkassonss  If you are on RN < 43, you need to go for Nativebase v2.1.0
The latest of Nativebase supports RN > 43.
https://github.com/GeekyAnts/NativeBase/releases/tag/v2.1.1

**Comment by pkassonss** [comment]
From what I can tell, I am on the correct version of all things:

    "native-base": "^2.1.0",
    "react": "^16.0.0-alpha.6",
    "react-native": "^0.43.3",

I just applied the proper code as you suggested, but it still did not work.

**Comment by himanshu-satija** [comment]
@pkassonss Are you using `Toast` inside `Container`.

From [docs](https://docs.nativebase.io/COMPONENTS.html#Toast)
`Note: For Toast to work, it has to be called inside Container.`

One more thing, use native-base>=2.1.1 with RN >= 0.43

**Comment by pkassonss** [comment]
I have put Toast inside a Container:

...

     
                <Button onPress={()=> Toast.show({
                    text: 'Wrong password!',
                    position: 'bottom',
                    buttonText: 'Okay',
                    duration: 3000
                   })}>
                   Toast
                </Button>
      
                <Text style={styles.italicBold}>
                   {this.state.messageLabel}
                </Text>

      
          </Content>
      </Container>

...

I am using the starter kit project and building upon it.  I did notice, though, that the kitchen sink toast works, but there is significant differences in the native-base folder.  

For starter kit there is no \src\basic under native base, but there is under kitchen sink.

Here is the package.json for both ... and a bit confused on the differences, since they were obtained about the same time (only pasting top most portion):

kitchen sink:
----------
{
  "_args": [
    [
      {
        "raw": "native-base@git+https://github.com/GeekyAnts/NativeBase.git#master",
        "scope": null,
        "escapedName": "native-base",
        "name": "native-base",
        "rawSpec": "git+https://github.com/GeekyAnts/NativeBase.git#master",
        "spec": "git+https://github.com/GeekyAnts/NativeBase.git#master",
        "type": "hosted",
        "hosted": {
          "type": "github",
          "ssh": "git@github.com:GeekyAnts/NativeBase.git#master",
          "sshUrl": "git+ssh://git@github.com/GeekyAnts/NativeBase.git#master",
          "httpsUrl": "git+https://github.com/GeekyAnts/NativeBase.git#master",
          "gitUrl": "git://github.com/GeekyAnts/NativeBase.git#master",
          "shortcut": "github:GeekyAnts/NativeBase#master",
          "directUrl": "https://raw.githubusercontent.com/GeekyAnts/NativeBase/master/package.json"
        }
      },
      "/Users/pkasson/dev/ios/React/r_and_d/native-starter-kitchensink/NativeBase-KitchenSink"
    ]
  ],
  "_from": "git+https://github.com/GeekyAnts/NativeBase.git#master",
  "_id": "native-base@2.0.13",
  "_inCache": true,
  "_location": "/native-base",
  "_phantomChildren": {
    "react-timer-mixin": "0.13.3"
  },


starter kit:
------------

{
  "_args": [
    [
      {
        "raw": "native-base@0.5.22",
        "scope": null,
        "escapedName": "native-base",
        "name": "native-base",
        "rawSpec": "0.5.22",
        "spec": "0.5.22",
        "type": "version"
      },
      "/Users/pkasson/dev/ios/React/r_and_d/native-starter-kit/native-starter-kit"
    ]
  ],
  "_from": "native-base@0.5.22",
  "_id": "native-base@0.5.22",
  "_inCache": true,
  "_location": "/native-base",
  "_nodeVersion": "6.2.2",
  "_npmOperationalInternal": {
    "host": "packages-18-east.internal.npmjs.com",
    "tmp": "tmp/native-base-0.5.22.tgz_1484578507733_0.23451081290841103"
  },

**Comment by shivrajkumar** [comment]
@pkassonss The starter kit seem to use native-base version v0.5.22
Do check again with the latest version of native-base

**Comment by pkassonss** [comment]
Latest version causes this error:

This error is caused by a @providesModule declaration with the same name across two different files.
Error: @providesModule naming collision:
  Duplicate module name: react-native-vector-icons
  Paths: /Users/pkasson/dev/ios/React/r_and_d/native-starter-kit/EveryMan/node_modules/react-native/local-cli/core/__fixtures__/files/package.json collides with 
         /Users/pkasson/dev/ios/React/r_and_d/native-starter-kit/EveryMan/node_modules/react-native-router-flux/node_modules/react-native/local-cli/core/__fixtures__/files/package.json

**Comment by shivrajkumar** [comment]
The issue is with latest version of `react-native-router-flux`. Not with `native-base`.
Use v3.38.0 of RNRF

**Comment by pkassonss** [comment]
I am currently using 3.38

**Comment by cosydney** [comment]
+1, My toast is not showing and I'm using:
  ```"native-base": "^2.1.2",
    "react": "16.0.0-alpha.6",
    "react-native": "^0.43.3",
    "react-native-router-flux": "^3.38.0"```
Error I'm getting: 
`ExceptionsManager.js:63 Cannot read property '_root' of undefined`

**Comment by shivrajkumar** [comment]
#819
