### ISSUE TITLE
Adding native-base crashes expo projects?

### ISSUE THREAD

**Issue by acomito** [GeekyAnts/NativeBase#746]
## react-native, react and native-base version

List prior to adding native-base (when app was working as expected):

```
"dependencies": {
    "expo": "^15.0.2",
    "lodash": "^4.17.4",
    "react": "~15.4.0",
    "react-native": "https://github.com/exponent/react-native/archive/sdk-15.0.0.tar.gz",
    "react-native-elements": "^0.11.0",
    "react-native-meteor": "^1.0.3",
    "react-navigation": "^1.0.0-beta.7",
    "react-redux": "^5.0.4",
    "redux": "^3.6.0",
    "redux-thunk": "^2.2.0"
  }

```

## Steps to reproduce issue with fresh expo project

- create new expo project from expo XDE
- send link to iphone via email
- click link via email, open app on iphone
- app works
- npm i -S native-base
- app works
- `import { Button } from 'native-base';` in main.js
- app crashes and can't find Components folder (maybe just need a clean cache)
- npm install @expo/vector-icons --save
- click restart from expo XDE
- app restarts
- expo XDE notification comes up about missing `ls` package from npm
- packager restarts, refresh app on phone, error still there about unable to resolve components from native-base
- add font snippet to App component in main.js

```
async componentWillMount() {
      await Expo.Font.loadAsync({
        'Roboto': require('native-base/Fonts/Roboto.ttf'),
        'Roboto_medium': require('native-base/Fonts/Roboto_medium.ttf'),
      });
  }
```
- restart packager from expo XDE again
- app reboots and does it's transforming modules X% thing
- same error
- try to follow direction from [this issue](https://github.com/expo/expo/issues/32)
- change main.js to the following:
```

import Expo from 'expo';
import React from 'react';
import { StyleSheet, Text, View } from 'react-native';
import { Button} from 'native-base';

class App extends React.Component {

  state = { fontsAreLoaded: false };

  async componentWillMount() {
      await Expo.Font.loadAsync({
        'Roboto': require('native-base/Fonts/Roboto.ttf'),
        'Roboto_medium': require('native-base/Fonts/Roboto_medium.ttf'),
      });
      this.setState({fontsAreLoaded: true});
  }
  render() {
    if (this.state.fontsAreLoaded) {
      return <Exponent.Components.AppLoading/>;
    }
    return (
      <View style={styles.container}>
        <Text>Open up main.js to start working on your app!</Text>
        <Button buttonText="Click Me!" />
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});

Expo.registerRootComponent(App);

```
and package.json of this:

```
{
  "name": "native-base-test",
  "version": "0.0.0",
  "description": "Hello Expo!",
  "author": null,
  "private": true,
  "main": "main.js",
  "dependencies": {
    "@expo/vector-icons": "^4.0.0",
    "expo": "^15.0.2",
    "ls": "^0.2.1",
    "native-base": "^2.1.1",
    "react": "~15.4.0",
    "react-native": "https://github.com/exponent/react-native/archive/sdk-15.0.0.tar.gz"
  }
}

```

- still the same error
- still seeing notification about missing ls package, so `npm i -S ls`
- restart packager again via expo XDE and go through transforming modules X%
- app still have same error
- begin to feel tears welling up in eyes
- close expo XDE and re-open and then re-open project
- same error and notification about ls is still there
- run` npm install` as I begin to sweat and feel head getting hot
- reload app, prior error is gone but now getting "Tunnel packager error" similar to this guy:

http://stackoverflow.com/questions/42884096/expo-xde-cannot-run-application-throws-tunnel-packager-not-found

- gives up and hopes somebody can point out a simple step he missed

**Comment by KidkArolis** [comment]
I get this error:
```
Unable to resolve module `react-native/Libraries/Components/StaticContainer.react`
from `node_modules/native-base/dist/src/basic/Tabs/SceneComponent.js`
```

**Comment by shivrajkumar** [comment]
@acomito @KidkArolis If you are on RN < 43, you need to go for Nativebase v2.1.0
The latest of Nativebase supports RN > 43.
https://github.com/GeekyAnts/NativeBase/releases/tag/v2.1.1

**Comment by GeekRishabh** [comment]
@acomito in render function you are trying to call <Exponent.Components.AppLoading/> instead use <Expo.Components.AppLoading/>; . we suggest you to use [CRNA](https://github.com/react-community/create-react-native-app)
you can have a quick look [here](https://github.com/GeekyAnts/NativeBase-KitchenSink)

**Comment by acomito** [comment]
Thanks @GeekRishabh. Looks like it's a version thing as cited by @shivrajkumar. I'll try using 2.1 for now.

**Comment by saiprasad1996** [comment]
Is the issue solved? I'm getting a weird error after npm installing native-base. I'm quite not able to understand the root cause . Please help me solving this issue.. My project highly relies on native-base and I'm using the latest native-base package .
The following is the log from XDE console.  

```  Restarting project and clearing packager cache (Hold shift while clicking restart to avoid clearing cache).
9:44:55 PM
Starting React Native packager...
9:44:58 PM
Scanning 566 folders for symlinks in G:\Projects\ReactNativeProjects\expo4ever\node_modules (38ms)
9:45:00 PM
Loading dependency graph.
9:45:00 PM
Running packager on port 19001.
9:45:00 PM
9:45:06 PM
Project opened! You can now use the "Send Link" or "Device" buttons to view your project.
9:45:26 PM
Dependency graph loaded.
9:45:37 PM
Opening on Android device
9:45:46 PM
Building JavaScript bundle: finished in 99799ms.
9:45:47 PM
Your JavaScript transform cache is empty, rebuilding (this may take a minute).
9:47:47 PM
Building JavaScript bundle: finished in 1455ms.
9:47:49 PM
SyntaxError: Unexpected end of JSON input
    at parse (<anonymous>)
    at process._tickCallback (internal/process/next_tick.js:103:7)
9:47:49 PM
SyntaxError: Unexpected end of JSON input
    at parse (<anonymous>)
    at process._tickCallback (internal/process/next_tick.js:103:7)`

**Comment by SupriyaKalghatgi** [comment]
@saiprasad1996 Share your `package.json`

**Comment by saiprasad1996** [comment]
@SupriyaKalghatgi Below is my package.json file please take a look at it .

```
{
  "name": "Expo4ever",
  "version": "0.0.1",
  "description": "React Native Expo experimentation!",
  "author": "Sai Prasad",
  "private": true,
  "main": "main.js",
  "dependencies": {
    "@expo/vector-icons": "^5.0.0",
    "expo": "16.0.0",
    "native-base": "^2.1.5",
    "react": "16.0.0-alpha.6",
    "react-native": "https://github.com/expo/react-native/archive/sdk-16.0.0.tar.gz"
  }
}

```
**This is the content of main.js file in case you want to check**
```
import Expo from 'expo';
import React from 'react';
import { StyleSheet, View } from 'react-native';
import {
  Header,
  Body,
  Left,
  Icon,
  Text,
  Container,
  Content,
  Title,
} from 'native-base'

class App extends React.Component {
  async componentWillMount() {
        await Expo.Font.loadAsync({
          'Roboto': require('native-base/Fonts/Roboto.ttf'),
          'Roboto_medium': require('native-base/Fonts/Roboto_medium.ttf'),
        });
    }

  render() {
    return (
      <Container>
        <Header>
          <Left><Icon name="ios-navigate" /></Left>
          <Body><Title>Home</Title></Body>
        </Header>
        <Content>
          <Body>
            <Text>Main Screen</Text>
          </Body>
        </Content>
      </Container>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});

Expo.registerRootComponent(App);

```

Thank you for your quick reply! :-)

**Comment by dajimene** [comment]
Hello everyone, someone to help me solve the following error.
![image](https://user-images.githubusercontent.com/27232120/28221060-7b3f508a-6887-11e7-8bbc-2cbb6845fbf8.png)

![image](https://user-images.githubusercontent.com/27232120/28221108-a66cf1f4-6887-11e7-8dda-6e1a527d4e13.png)

**Comment by escalepion** [comment]
hello i have same problem.I created app via create-react-native-app.. I installed exactly 2.1.0 version of native-base. I will share my package.json... Everything is ok. But when i import nativebase, the app crashes. The error is: "UnableToResolveError undefined". It is enough just calling native-base for crashing.

here is my package.json: 
```
`{
  "name": "movies",
  "version": "0.1.0",
  "private": true,
  "devDependencies": {
    "jest-expo": "~18.0.0",
    "react-native-scripts": "0.0.50",
    "react-test-renderer": "16.0.0-alpha.12"
  },
  "main": "./node_modules/react-native-scripts/build/bin/crna-entry.js",
  "scripts": {
    "start": "react-native-scripts start",
    "eject": "react-native-scripts eject",
    "android": "react-native-scripts android",
    "ios": "react-native-scripts ios",
    "test": "node node_modules/jest/bin/jest.js --watch"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "@exponent/vector-icons": "^4.0.0",
    "expo": "^18.0.3",
    "native-base": "2.1.0",
    "react": "16.0.0-alpha.12",
    "react-native": "^0.45.1"
  }
}`
```

here is my app.js: 
```
`import React from 'react';
import { StyleSheet, Text, View } from 'react-native';
import {
  Button,
  Icon,
} from 'native-base';

export default class App extends React.Component {
  async componentWillMount() {
        await Expo.Font.loadAsync({
          'Roboto': require('native-base/Fonts/Roboto.ttf'),
          'Roboto_medium': require('native-base/Fonts/Roboto_medium.ttf'),
        });
    }
  render() {
    return (
      <View style={styles.container}>
        <Text>Opennasdas up App.js to start working on your app!</Text>
        <Text>Changes you make will automatically reload.</Text>
        <Text>Shake your phone to open the developer menu.</Text>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});`

```
and screenshot of error:

![expo](https://user-images.githubusercontent.com/26687352/28242568-f6077c30-69b7-11e7-9825-d2b03595b0c7.jpg)

**Comment by ewein** [comment]
@dajimene I'm having the same issue, is there a fix for this?

**Comment by HamadaFMahdi** [comment]
in case anyone else is wondering...
try running npm install again. worked for me.

(note: I used CRNA to set up my app)
