### ISSUE TITLE
Dynamic add theme attribute to component

### ISSUE THREAD

**Issue by redwind** [GeekyAnts/NativeBase#747]
## react-native, react and native-base version
`"native-base": "^2.0.13",
    "react": "15.4.2",
    "react-native": "^0.42.2",`
## Expected behaviour
Sory for this issue request, but i don't know how to dynamic component theme attribute base on value. For example
`<Button small
 onPress={() => onPressButton()}
      >
        <Text >{onText}</Text>
      </Button>`
and i want to dynamic add "light" attribute to Button base on value on Button click.

Thanks !

**Comment by shivrajkumar** [comment]
@redwind applying boolean conditions on the prop should do the trick for you.
Something like this
<Button light={(condition) ? true : false}>
Let me know if that works for you.

**Comment by redwind** [comment]
@shivrajkumar it's work. 

Thank so much !
