### ISSUE TITLE
InputGroup does not support dynamic styling

### ISSUE THREAD

**Issue by pkassonss** [GeekyAnts/NativeBase#748]
Per the FB spec, component styling can support styling like this:

{[styles.input, this.state.userNameInvalid && styles.inputError]}

where, if the second block (userNameInvalid) is true, the component will use the 2nd style.  I can no get this to work with InputGroup, but, perhaps there is a better way to do what I am trying:

1.  perform simple text field validation and highlight the field and optionally show an icon for error conditions, to provide great user error feedback.

**Comment by shivrajkumar** [comment]
@pkassonss #575

**Comment by shivrajkumar** [comment]
Fixed with latest version 2.3.0
