### ISSUE TITLE
Multiple Arrays in Dynamic List

### ISSUE THREAD

**Issue by rostyys** [GeekyAnts/NativeBase#750]
Hello, I'm wondering if there is a way to iterate through more than one array when creating a dynamic list?

e.g. 

```
<Container>
  <Content>
     <List dataArray={items, items2} renderRow={(data,data2) =>
        <ListItem>
             <Text>{data}</Text>
             <Text note>{data2}</Text>
        </ListItem>
     } />
  </Content>
</Container>
```

Could this be done? What's the correct syntax because the above doesn't work! Any help would be much appreciated.

**Comment by SupriyaKalghatgi** [comment]
+1 [SO](https://stackoverflow.com/questions/43643820/multiple-arrays-in-dynamic-list)

**Comment by SupriyaKalghatgi** [comment]
@rostyys Did you try implementing this with React Native?

**Comment by rostyys** [comment]
@SupriyaKalghatgi Yes, in a react native project.

**Comment by SupriyaKalghatgi** [comment]
@rostyys I meant, did you try running with React Native component, without NativeBase?

**Comment by SupriyaKalghatgi** [comment]
@rostyys Any updates on this?

**Comment by rostyys** [comment]
@SupriyaKalghatgi I have no tried with React Native component. Could you possible specify what I should try?

**Comment by SupriyaKalghatgi** [comment]
Did you try the above implementation with React Native pure components?
I mean without using NativeBase

**Comment by shivrajkumar** [comment]
dataArray of NativeBase List accepts a single array just like dataSource of ReactNative ListView which accepts a single object

**Comment by HaloBeginner** [comment]
render(){
        var product = [];
        for(var i = 0; i < 15; i++){
            product.push({'name': 'Apple', 'price' : '$6'}); 
        }

        return(
            <List dataArray={product}
            renderRow={(product) =>
              <ListItem>
                <Text>{product.name}</Text>
                 <Text note>{product.price}</Text>
              </ListItem>
            }>
          </List>
        );
    }

It's worked for me.

**Comment by sixmoraltales** [comment]
+1 I'm also encountering this problem. Is there a particular reason the dataSource shouldn't be able to accept an array of Objects? It would be much more convenient to be able to read the multiple parameters of an Object into each listItem render.

**Comment by sixmoraltales** [comment]
Would be great to reopen this issue since reading from multiple arrays, or at least a multidimensional array (of objects ideally) is a basic requirement for most real world use cases.
