### ISSUE TITLE
undefined is not an object (evaluating 'variables.platformStyle')

### ISSUE THREAD

**Issue by kheide** [GeekyAnts/NativeBase#752]
On the following; 

`    "native-base": "^2.1.2",
    "react": "16.0.0-alpha.6",
    "react-native": "^0.43.3",`

Getting this error every time I use the `<StyleProvider>` tag. Thus not being able to style anything.

**Comment by GeekRishabh** [comment]
@kheide can you share the code snippet .It will be easy to debug .and help you

**Comment by l3lackcurtains** [comment]
Got the same problem for white I try to use Icon
"native-base": "^2.1.2", "react": "16.0.0-alpha.6", "react-native": "^0.43.4",

**Comment by l3lackcurtains** [comment]
It worked after adding style into StyleProvider Tag:

```
import getTheme from '../native-base-theme/components'
import material from '../native-base-theme/variables/material'
...
<StyleProvider style={getTheme(material)}>
...
</StyleProvider>
```

**Comment by shivrajkumar** [comment]
@kheide @l3lackcurtains Yes, if you are using `<StyleProvider>`, you do need to pass theme to it through `style` prop

**Comment by anatoliibatiuk** [comment]
Have the same issue specifically on <Header/> component (other components works fine) 

  import headerTheme from '../Themes/Header';
  ...
  <StyleProvider style={headerTheme()}>
  ...

**Comment by anatoliibatiuk** [comment]
Have the same issue specifically on "Header" component (other components works fine) 

  import headerTheme from '../Themes/Header';
  ...
  <StyleProvider style={headerTheme()}>
  ...

**Comment by anatoliibatiuk** [comment]
Have the same issue specifically on <Header/> component (other components works fine) 

```
  import headerTheme from '../Themes/Header';
  ...
  <StyleProvider style={headerTheme()}>
  ...
```

**Comment by anatoliibatiuk** [comment]
Have the same issue specifically on "Header" component (other components works fine) 

```
  import headerTheme from '../Themes/Header';
  ...
  <StyleProvider style={headerTheme()}>
  ...
```

**Comment by namrata-mego** [comment]
I am doing theme change task using toggle . Problem with me for styleprovider only parents componants style is rendering while toggle button means relading and not all compoants color change.
