### ISSUE TITLE
Can't Use SimpleLineIcons

### ISSUE THREAD

**Issue by OmriAharon** [GeekyAnts/NativeBase#755]
I've gone over all issues, and nothing worked for me.
I'm trying to use the `like` icon from SimpleLineIcons but I keep getting a question mark.

## react-native, react and native-base version
RN: 0.43.3
NB: 2.1.2

## Expected behaviour
I see the Like Icon when using this:
```
import {Icon} from "native-base";
...
<Icon name="like" style={{fontSize: 12, color: 'red'}} />
```
## Actual behaviour
I see a question mark.

## Steps to reproduce (code snippet or screenshot)
![image](https://cloud.githubusercontent.com/assets/12033595/25196755/49e426da-254a-11e7-8fe0-085e3ca412a6.png)

## Screenshot of emulator/device
Also seeing an invalid value for name attribute:
![image](https://cloud.githubusercontent.com/assets/12033595/25196787/64b5a164-254a-11e7-90e6-860ee42ae008.png)

## Is the bug present in both ios and android or in any one of them?
I'm just trying the android emulator.

## Any other additional info which would help us debug the issue quicker.
I tried `react-native link react-native-vector-icons`.
I tried manually copying the fonts from `react-native-vector-icons` to `android/app/src/main/assets/fonts`. 
I tried installation with gradle as requested in the [react-native-vector-icons](https://github.com/oblador/react-native-vector-icons) repo.
I managed to get some icons to work, such as `md-menu`.
Also - if there is the same name for an icon in two different icon fonts, how do we tell it which font we want it to draw the icon from?

**Comment by shivrajkumar** [comment]
@OmriAharon Check the latest v2.1.3
Fixed
