### ISSUE TITLE
Unable to change Tabs border bottom color

### ISSUE THREAD

**Issue by feelinc** [GeekyAnts/NativeBase#757]
## react-native, react and native-base version
"native-base": "^2.1.2",
"react": "16.0.0-alpha.6",
"react-native": "0.43.3",

## Expected behaviour
Able to change the bottom border color.

## Actual behaviour
The bottom border color always appear in white color.

## Steps to reproduce (code snippet or screenshot)
```
const tabProps = {
  underlineStyle: {borderColor: '#f65857'}
};

return (
  <Tabs>
    <Tab heading="Tab 1" {...tabProps}>
      <Tab1 />
    </Tab>
    <Tab heading="Tab 2" {...tabProps}>
      <Tab2 />
    </Tab>
    <Tab heading="Tab 3" {...tabProps}>
      <Tab3 />
    </Tab>
  </Tabs>
);
```

## Screenshot of emulator/device
![selection_296](https://cloud.githubusercontent.com/assets/345562/25216977/598fe03a-25cf-11e7-95fd-c22945ec9c08.jpg)

## Is the bug present in both ios and android or in any one of them?
Only tested in Android.

## Any other additional info which would help us debug the issue quicker.
None.

**Comment by shivrajkumar** [comment]
@feelinc it should be `tabBarUnderlineStyle: { backgroundColor: '#f65857' }`

**Comment by feelinc** [comment]
@shivrajkumar still not working. re-compiled and restart the npm, but still not working.

**Comment by shivrajkumar** [comment]
@feelinc `tabBarUnderlineStyle` needs to be applied to <Tabs> not <Tab>

**Comment by feelinc** [comment]
applied to not?

**Comment by shivrajkumar** [comment]
Ah! my bad.
Applied to `<Tabs>` not to `<Tab>`

**Comment by feelinc** [comment]
Thanks a lot, it's working :)

**Comment by JayKurniawan** [comment]
@shivrajkumar how do I implemented the `tabBarUnderlineStyle` ?
`<Tabs 
    ................                      
  >`

**Comment by prasanthlrb** [comment]
![screenshot 1](https://user-images.githubusercontent.com/23078792/36038824-c12b62dc-0de6-11e8-9f1a-5f15d7cdffd6.png)

**Comment by skraloupak** [comment]
@prasanthlrb Hi, you have to paste it to braces `{ }` and use `=` after tabBarUnderlineStyle
example:
` <Tabs tabBarUnderlineStyle={{ backgroundColor: '#f65857' }}>`

**Comment by impradeepsaini** [comment]
hi, can anyone tell how to change border color for other tabs (tabs other than current selected one)? 

tabBarUnderlineStyle works for the active tab but for the rest of tabs, how to change their body color?

**Comment by SupriyaKalghatgi** [comment]
Check NativeBase Docs https://docs.nativebase.io/
