### ISSUE TITLE
StyleProvider not updating brandPrimary on Picker component

### ISSUE THREAD

**Issue by mini-eggs** [GeekyAnts/NativeBase#761]
## react-native, react and native-base version
You can find my package.json [here](https://raw.githubusercontent.com/mini-eggs/Flippour/master/package.json)

## Expected behaviour
StyleProvider is not update brandPrimary on the Picker component.

## Actual behaviour
StyleProvider will update brandPrimary on the Picker component just as it does every other component.

## Steps to reproduce (code snippet or screenshot)
Feel free to download my project here [here](https://github.com/mini-eggs/Flippour).
To run on iOS:
```
git clone https://github.com/mini-eggs/Flippour.git
cd Flippour
yarn
yarn ios
```

## Screenshot of emulator/device
Screenshots can be found [here](http://imgur.com/a/1X4tD).

## Is the bug present in both ios and android or in any one of them?
I've only tested this on iOS.

## Any other additional info which would help us debug the issue quicker.
You'll notice in the screenshots provided there is a console.warn of using refs. I do not use refs in this project. But that could also be a different dependency. Best of luck! If I have the time I'll look into the code myself and update here. No promises, though. 😜

**Comment by SupriyaKalghatgi** [comment]
The screenshot does not tell us the primary color, due to insufficient information we are closing this for now.
Also please check with latest of NativeBase 2.1.4 and React Native 0.44.0
