### ISSUE TITLE
can not read property of ‘checkboxBgColor’ undefined

### ISSUE THREAD

**Issue by amitbravo** [GeekyAnts/NativeBase#765]
react": "16.0.0-alpha.6"
native-base": "^2.1.2"
react-native": "0.43.3"

![screen shot 2017-04-21 at 5 05 34 pm](https://cloud.githubusercontent.com/assets/16644357/25275802/bd54028c-26b4-11e7-8ba1-71cde99391e7.png)

Code : <CheckBox checked={true} /> 

This issue was not exists before I upgraded react-native from .39 to .43.3

**Comment by Schwusch** [comment]
react": "16.0.0-alpha.6"
native-base": "^2.1.2"
react-native": "0.43.1"

I'm having the same issue with CheckBox

**Comment by ohtangza** [comment]
We are still getting this issue.
I cannot understand why this was closed without enough testing...

**Comment by shivrajkumar** [comment]
Fixed in v2.1.3
