### ISSUE TITLE
Encountered error while trying to customize theme

### ISSUE THREAD

**Issue by CliveTeow** [GeekyAnts/NativeBase#768]
react": "15.4.2"
native-base": "^2.0.5"
react-native": "0.41.2"

## Expected behaviour
Able to customize the theme.

## Actual behaviour
Shows error undefined is not a function (evaluating '(0,_color2.default)(this.radioColor).darken(0.2).hexString()')

## Steps to reproduce (code snippet or screenshot)
Follow the steps in the documentation: http://docs.nativebase.io/CUSTOMIZE.html#Theming_NativeBase_Apps
E.g.
`import {Container, Content, Text} from 'native-base';
import React, {Component} from 'react-native';
import getTheme from './native-base-theme/components';
import material from './native-base-theme/variables/material';
​export default class ThemeExample extends Component {
    render() {
        return (
        <StyleProvider style={getTheme(material)}>
            <Container>
                    <Content>
                        <Text>
                            I have changed the text color.
                        </Text>
                    </Content>
            </Container>
          </StyleProvider>
        );
    }
}`

## Screenshot of emulator/device
![screen shot 2017-04-22 at 10 15 25 pm](https://cloud.githubusercontent.com/assets/19527543/25305178/35e1fcbe-27a9-11e7-9e09-a330071cdf19.png)

## Is the bug present in both ios and android or in any one of them?
Both

**Comment by RichardLindhout** [comment]
You need to change hexString() to string()

**Comment by RichardLindhout** [comment]
And install npm install color -S

**Comment by CliveTeow** [comment]
@RichardLindhout It works. Thanks.

**Comment by eivindvr** [comment]
Works for me as well. thanks!
