### ISSUE TITLE
Very minor issue regarding documentation of Card List

### ISSUE THREAD

**Issue by maxtonsc** [GeekyAnts/NativeBase#770]
Hi,
First time submitting an issue so apologies if this isn't the place/correct format.

Noticed that in the documentation of card list on https://docs.nativebase.io/COMPONENTS.html#Card_List the code doesn't ask to import 'Right'. Thus, throwing an issue when the code uses <Right>. I know its an minor issue but figured it may help out.

Love the code base and it's really helping me out with my project. Apologies again if this is incorrect of me submitting an issue for this.

Cheers,

**Comment by Jasbir23** [comment]
Hi @maxtonsc , Glad that you brought the issue to our notice. We will fix this asap. In the meanwhile you can import 'Right' from 'native-base'.
Thanks again

**Comment by wcandillon** [comment]
@Jasbir23 @sanketsahusoft Is there a place where we can contribute to the documentation pages? I found some inconsistencies and typos but I am not sure where is the documentation hosted on github?

**Comment by GeekRishabh** [comment]
@wcandillon  you can edit it and send PR . The docs are hosted [here](https://github.com/GeekyAnts/native-base-docs)

**Comment by wcandillon** [comment]
Thks a lot!
