### ISSUE TITLE
Card Image dooesn't showing properly.

### ISSUE THREAD

**Issue by tishad770** [GeekyAnts/NativeBase#771]
Here is my code: 

         <Card key={item['id']} >
                
              <CardItem cardBody>
                    <Image
                        source={{uri: item['image']}}
                        style={{
                            alignSelf: 'stretch',
                            resizeMode: 'contain',
                            width: Dimensions.get('window').width,
                            marginRight: 10,
                            }}
                    />
                </CardItem>

                <CardItem footer>
                    <Text>Title</Text>

                </CardItem>
            </Card>

Its not working properly i.e: no image is being shown. 
Any idea what am I missing?

**Comment by rithvikvibhu** [comment]
Same issue

**Comment by GeekRishabh** [comment]
```
 <View style={{padding: 20}}>
                           <Card>
                                    <CardItem cardBody>
                                        <Image source={require('../images/test.jpg')} style={{  resizeMode: 'cover', height: 200, width: null, flex: 1 }} />
                                    </CardItem>
                                </Card>
                            </View>
```
@rithvikvibhu @tishad770  the above should work for you guys .try it out

**Comment by rithvikvibhu** [comment]
@GeekRishabh thanks for that. What about external images?
`source={{uri: food.pic}}` used to work with any url for an image.

**Comment by ferdingler** [comment]
I had a similar issue just now. The image, when placed inside a Card with a height of 180, will render on the simulator, but not on the device. 

`<Card>
    <CardItem cardBody>
        <Image
            source={item.thumbnail}
            style={styles.thumbnail}
        />
    </CardItem>
    <CardItem note>
        <Grid>
            <Row>
                <Text>{item.name}</Text>
            </Row>
            <Row>
                <Text>{item.description}</Text>
            </Row>
        </Grid>
    </CardItem>
</Card>`

`const styles = StyleSheet.create({
    thumbnail: {
        flex: 1,
        height: 180 // Changed this to >200
    }
});`

Changing the height to anything larger than 200 fixed the issue. 😕

**Comment by ishsingh** [comment]
I also had several rendering issues with Card on devices, and I just ended up replacing all of them with custom styled view.

**Comment by Anima-t3d** [comment]
There are many issues with the card item. For example: https://github.com/GeekyAnts/NativeBase/issues/612 

I also changed to use custom styled views.

**Comment by SupriyaKalghatgi** [comment]
![screen shot 2017-05-31 at 5 11 35 pm](https://cloud.githubusercontent.com/assets/13464885/26630452/5a2f18b0-4624-11e7-9dcd-be085c0e1db6.png)

@tishad770 @rithvikvibhu @ferdingler @ishsingh @Anima-t3d 
Works fine. Tried with device as well, all good
If both width and height is included for the Image.

You need to check the note mentioned in the docs of React Native for [Image](https://facebook.github.io/react-native/docs/images.html#network-images)

@rithvikvibhu Yes ` external images` still works with Image
