### ISSUE TITLE
Flex direction on content not working

### ISSUE THREAD

**Issue by tishad770** [GeekyAnts/NativeBase#773]
I want to display two images side by side instead of on in the bottom of another. Here is my code : 

     <Content style={{flexDirection: 'row', flexWrap: 'wrap'}}>
         <Image
              key={data[0]['id']}
                 source={{ uri: data[0]['image']['url']}}
                 style={{
                      width: Dimensions.get('window').width * 0.2,
                       height: 120,
                        }}
                    />
         <Image
              key={data[1]['id']}
                 source={{ uri: data[1]['image']['url']}}
                 style={{
                      width: Dimensions.get('window').width * 0.2,
                       height: 120,
                        }}
                    />

                
       </Content>

But it is not working as it should. What am I missing here?

**Comment by GeekRishabh** [comment]
![screen shot 2017-04-24 at 11 31 37 am](https://cloud.githubusercontent.com/assets/23093075/25324138/abb6d98a-28e1-11e7-902f-2f536118f356.png)
@tishad770 if you are trying for something like the above you can use the library from [here](https://github.com/GeekyAnts/react-native-easy-grid)

**Comment by tishad770** [comment]
Temporary Solved. Used **View** instead of **Content**. But the issue remains with Content.
