### ISSUE TITLE
[Input] success + floating = label empty

### ISSUE THREAD

**Issue by pierre-H** [GeekyAnts/NativeBase#774]
## react-native, react and native-base version
React-Native : 0.43.4
React : 15.4.0
Native Base : 2.1.2
## Expected behaviour
```jsx
<Item floatingLabel={true}>
    <InputGroup success={this.state.isValid}>
        <Label>{this.props.label}</Label>
        <Input onChangeText={this.handleChange} />
        {this.state.isValid ? icon : ''}
    </InputGroup>
</Item>
```
Should print a correct floating and success input with the label.
## Actual behaviour
The label is missing/empty : I have to invert Item and InputGroup but then the input is not successful (green).
## Steps to reproduce (code snippet or screenshot)
See the example?
## Is the bug present in both ios and android or in any one of them?
Android : Yes
iOS : can't reproduce because I don't have a Mac.

**Comment by SupriyaKalghatgi** [comment]
@pierre-H Did you check the syntax of from Docs?
Move `<Label>` before `<InputGroup>`

**Comment by SupriyaKalghatgi** [comment]
NativeBase will be deprecating InputGroup from its next versions

**Comment by pierre-H** [comment]
@SupriyaKalghatgi I can't test since I am traveling on business for few weeks. I will come back to you when I will be able. If InputGroup will be deprecating, so there is no problem anymore.

**Comment by SupriyaKalghatgi** [comment]
@pierre-H Good to hear that, closing the issue
Also I tried running your code snippet, and suggested you solution in a [comment](https://github.com/GeekyAnts/NativeBase/issues/774#issuecomment-303351729)
