### ISSUE TITLE
a bug of InputGroup in version 2.1.2

### ISSUE THREAD

**Issue by Symous** [GeekyAnts/NativeBase#775]
Hi,I update native-base 2.1.2 and I found all of my Input only  display 2-3 characters which is display normally in last version.
this is the code of the input in my program:
```js
<InputGroup>
                  <Icon name='ios-home' style={{color:'gray'}}/>
                  <Input placeholder='Input name' value = {this.state.name == undefined ? '' : this.state.name} onChangeText={(text)=>this.setState({ name:text })}/>
</InputGroup>
```

the Item perfermance is same as InputGroup:
```js
<Item>
       <Label>First Name<Label>
        <Input value='6666666666666'/>
 <Item>
```

and if I remove the InputGroup or Item like this :
```js
<Input placeholder='Input name' value = {this.state.name == undefined ? '' : this.state.name} onChangeText={(text)=>this.setState({ name:text })}/>
```
it will display all characters as excepted. 

Please fix this soon , Thanks. :D

**Comment by shivrajkumar** [comment]
@Symous If you had ejected the theme with previous version, you need to merge the latest theme with that. With v2.1.1, theme for Input was added separately.

**Comment by Symous** [comment]
@shivrajkumar Thank you my friend,I have run 'node node_modules/native-base/ejectTheme.js' again and it can display normally both with Item and InputGroup.But if I add property editable = {false} to Input,now the color of the content  is black which is gray in the last version.

**Comment by shivrajkumar** [comment]
@Symous You can just wrap your app with `StyleProvider` like this http://docs.nativebase.io/CUSTOMIZE.html#Theming_NativeBase_Apps
and do the changes in the theme as you require.

**Comment by Symous** [comment]
@shivrajkumar Yes I know that I can them the not-allow-editable Input of myself,what I mean is the color in the new version (black) is different from the old version (gray) .And I guess the gray color is more obviously for us to understand that the Input is not editable.

**Comment by SupriyaKalghatgi** [comment]
@Symous You said `Input only display 2-3 characters`
Do you still face this?

**Comment by Symous** [comment]
@SupriyaKalghatgi I have solved this by run 'node node_modules/native-base/ejectTheme.js' again. :-)

**Comment by SupriyaKalghatgi** [comment]
@Symous What about `property editable = {false} to Input`?

**Comment by SupriyaKalghatgi** [comment]
- If you have a `value` for `<Input>` with `editable = {false}`, the value will be rendered in Black

- If the `value` is null for `<Input>` with `editable = {false}`, the placeholder(if included) will be rendered in Grey

- If you have a `value` for `<Input>` with `editable = {true}`, the value will be rendered in Black

**Comment by Symous** [comment]
@SupriyaKalghatgi you can just style prop to custom it yourself!
