### ISSUE TITLE
[Bug] Not fully display on tablets

### ISSUE THREAD

**Issue by ithieund** [GeekyAnts/NativeBase#776]
Hi,
Anyone try this on tablets?
It is not fully displayed in large device such as tablet (both Android and iOS), the black padding around is too large.

Can you please fix this in next release?
Thanks.

**Comment by shivrajkumar** [comment]
@ithieund Can you please specify, with what component are you facing the issue and also the versions.

**Comment by ithieund** [comment]
@shivrajkumar ,
First is the footer component, it does not fully display the width while switching from portrait to landscape (both Android and iOS)
![android landscape](https://cloud.githubusercontent.com/assets/4217195/25379877/85fb7a14-29d8-11e7-97dc-6b2055ceb57b.png)

![ipad landscape](https://cloud.githubusercontent.com/assets/4217195/25379892/90943a6a-29d8-11e7-825d-0dde90a7b982.png)

Second is the content component (i thought it was), it does not fully display in iOS tablet, the black padding is too much.
![ipad 2](https://cloud.githubusercontent.com/assets/4217195/25379944/b9bf3dae-29d8-11e7-9582-3e490e87d046.png)

The final issue is the font size, it's too large while displaying iOS tablet, it break the original design, which displays well in iPhone or Android phone.
![ipad 2](https://cloud.githubusercontent.com/assets/4217195/25380020/f99c7ac2-29d8-11e7-89c4-6573a765b7c9.png)

It's display normal in iPhone
![image](https://cloud.githubusercontent.com/assets/4217195/25380089/3f5c5942-29d9-11e7-808e-440a479c9571.png)

I'm using native-base v0.5.22
Thanks.

**Comment by ithieund** [comment]
@sankhadeeproy007 ,
Can you please check this bug?

Thanks.

**Comment by ithieund** [comment]
@shivrajkumar , @sankhadeeproy007 ,
Can you please give me your feedback?

Thanks.

**Comment by SupriyaKalghatgi** [comment]
Please check the latest of NativeBase

**Comment by Fox-3394** [comment]
Hi everyone, I have the same problem. I tried use version Nativebase(^2.1.5) and Reat-native(^0.45.1) latest, some issues have been improved. The footer show normal,  but content and padding still not improved. Please help me, Thanks.

**Comment by ithieund** [comment]
@SupriyaKalghatgi ,
It's not fixed yet.
Please check.

Thanks.

**Comment by BjoernScheurich** [comment]
I faced the same issues with padding, font and content size when running on iPads. On android tablets the layout was rendered correctly. Turned out that the deployment information in Xcode was set to "iPhone". After setting it to "Universal" the issue was solved and the additional padding was gone.

See: https://github.com/facebook/react-native/issues/11102#issuecomment-262660951

**Comment by ithieund** [comment]
@BjoernScheurich ,
Thank you very much, changing from iPhone to Universal worked for me.

**Comment by akhil-geekyants** [comment]
Fixed in the latest version (native-base:2.3.3)

![display](https://user-images.githubusercontent.com/27768184/32495558-251b0f9e-c3ec-11e7-8808-e76eb7af33da.gif)
![display2](https://user-images.githubusercontent.com/27768184/32495559-2547d416-c3ec-11e7-909f-1b4d8f924431.gif)
