### ISSUE TITLE
Toast blocks whole screen and prevents interaction without dismissing

### ISSUE THREAD

**Issue by lashae** [GeekyAnts/NativeBase#777]
## react-native, react and native-base version
React 16.0.0-alpha.6, React Native 0.43.2, Native Base 2.1.2

## Expected behaviour
Toast shouldn't prevent UI items to be interacted, it shouldn't mask the whole screen. Material design toasts are just small boxes and doesn't require to be dismissed to interact with the UI. Assume you have a login form and you displayed "Incorrect username or password" message on a Native-Base toast component, user have to explicitly dismiss toast to interact with the login form or you have to set a timeout to hide the toast.

## Actual behaviour
When a toast is displayed (say at the bottom), although the toast message is displayed within a small rectangle box behind the curtains a transparent modal is used which prevents user to interact with the UI while the toast is still visible. User have to dismiss toast to interact with any UI item.

## Steps to reproduce (code snippet or screenshot)
Create any `Toast` to reproduce.

## Screenshot of emulator/device
N/A

## Is the bug present in both ios and android or in any one of them?
Both

**Comment by ohtangza** [comment]
I think this is very important to deliver the same experience as Android-native Toast.

**Comment by adamwan92** [comment]
+1

**Comment by ohtangza** [comment]
Any updates?

**Comment by SupriyaKalghatgi** [comment]
You can get updates after a couple of days

**Comment by ohtangza** [comment]
@SupriyaKalghatgi Thank you very much!

**Comment by shivrajkumar** [comment]
Check the latest of NativeBase (v2.2) for this. Do check the docs as the use case for toast and actionsheet has changed a bit. http://rawgit.com/GeekyAnts/native-base-docs/master/_book/Components.html#Toast

**Comment by lashae** [comment]
@shivrajkumar I can confirm that version 2.2 fixes the issue. So I'm closing the issue, thanks!

**Comment by palindrom228** [comment]
if you'll met it in next time, make sure that you not using useCallBack, if you are using it, so add toast to your dependency
