### ISSUE TITLE
[Form] navigation and submit with keyboard

### ISSUE THREAD

**Issue by pierre-H** [GeekyAnts/NativeBase#779]
Hello,
I'd like to create a form where it's possible to go to the next field directly from the keyboard and send it directly when we are on the last field.
Is it possible ?
It's very common. Now with Native Base, we have to click on every field and then in order to click on the button two times : one for the keyboard dismissing and another one for the submit.

Thank you in advance !

**Comment by shivrajkumar** [comment]
@pierre-H https://github.com/facebook/react-native/commit/ab12189f87d8e7fd84a4f1b92fa97e8894e984c7#diff-35d03ce527379518aef0aa3aad098cfa
http://stackoverflow.com/questions/32748718/react-native-how-to-select-the-next-textinput-after-pressing-the-next-keyboar
This should do.
