### ISSUE TITLE
[Drawer] use of root or _root ?

### ISSUE THREAD

**Issue by pierre-H** [GeekyAnts/NativeBase#780]
## react-native, react and native-base version
React : 16.0.0-alpha.6 - React Native : 0.43.4 - Native Base : 2.1.2
## Expected behaviour
Access to the drawer root like this  `this.drawer.root` ([from the example](https://docs.nativebase.io/COMPONENTS.html#Drawer))
## Actual behaviour
I can't access to the drawer root like this : `this.drawer.root`. I have to use this code `this.drawer._root`.
## Steps to reproduce (code snippet or screenshot)
Use the code of the example : https://docs.nativebase.io/COMPONENTS.html#Drawer
## Is the bug present in both ios and android or in any one of them?
Both of them
## Any other additional info which would help us debug the issue quicker.
The error is that root is undefined. _root is not.

**Comment by shivrajkumar** [comment]
@pierre-H Yes, the drawer can be accessed with `_root`. The docs seem to have the older code.We will fix this asap. For the time being you can refer this https://github.com/GeekyAnts/NativeBase-KitchenSink/blob/master/js/AppNavigator.js#L143

**Comment by pierre-H** [comment]
Thank you !
