### ISSUE TITLE
Picker doesn't work in landscape mode

### ISSUE THREAD

**Issue by sampsasaarela** [GeekyAnts/NativeBase#782]
Picker module doesn't work in landscape mode. 

![simulator screen shot 24 apr 2017 20 37 36](https://cloud.githubusercontent.com/assets/1910651/25350459/e680c96c-292d-11e7-8ce4-355ebb3ab6ba.png)

My solution is to add `supportedOrientations` property to the picker and set it to the `Modal`.

Propery is documented [here](https://facebook.github.io/react-native/docs/modal.html#supportedorientations) in react native docs.

```javascript
        <Picker
          supportedOrientations={['portrait', 'landscape']}
          defaultLabel="Select category"
          iosHeader="Select category"
          mode="dropdown"
          selectedValue={this.props.category}
          onValueChange={this.onCategoryChange}
        >
          {this.state.categories.map(category =>
            <Item label={category.value} value={category.key} key={category.key} />,
          )}
        </Picker>
```

Pull request is here:  #783. Fixes also #785.

**Comment by shivrajkumar** [comment]
Fixed in v2.1.3
Take a look

**Comment by corpsemxq** [comment]
Still see this in the 2.8.0

**Comment by corpsemxq** [comment]
DatePicker doesn't work in landscape mode

Sample issue.
