### ISSUE TITLE
Toast doesn't work in landscape mode

### ISSUE THREAD

**Issue by sampsasaarela** [GeekyAnts/NativeBase#785]
Toast module doesn't work in landscape mode. 

My solution is to add `supportedOrientations` property to the toast and set it to the `Modal`.

Propery is documented [here](https://facebook.github.io/react-native/docs/modal.html#supportedorientations) in react native docs.

```javascript
      Toast.show({
        supportedOrientations: ['portrait', 'landscape'],
        text: 'File uploaded succesfully',
        position: 'center',
        buttonText: 'X',
        type: 'success',
        duration: 2000,
      });
```

Pull request is here:  #783. Fixes also #782.

**Comment by shivrajkumar** [comment]
Fixed in v2.1.3
