### ISSUE TITLE
Icons not working on iOS

### ISSUE THREAD

**Issue by tishad770** [GeekyAnts/NativeBase#786]
It states that NativeBase uses https://oblador.github.io/react-native-vector-icons/ for icons. I am trying to use : 

`<Icon name ="location">`
But it doesn't work. 

What am I missing?

**Comment by shivrajkumar** [comment]
@tishad770 `location` comes under EvilIcons. To use that either you can import EvilIcons from `react-native-vector-icons` and use it as `<EvilIcons name="location" />`
Or you can change `iconFamily` in ejected theme variable of native-base and use as `<Icons name="location" />`
Let me know how it goes.
