### ISSUE TITLE
The focus of the input component within the content components lead to double-click the operation button component

### ISSUE THREAD

**Issue by tranren** [GeekyAnts/NativeBase#789]
Content components contained within the login components, if the focus in the input component, click on the button component to complete the login twice

**Comment by SupriyaKalghatgi** [comment]
![input](https://cloud.githubusercontent.com/assets/13464885/26583297/4d346c2c-4562-11e7-8514-de632a1e5a31.gif)

This is not an issue with NativeBase
The GIF includes Button and TextInput of React Native

**Comment by ProteanDev** [comment]
Any progress on this, guys?

**Comment by akhil-geekyants** [comment]
@ProteanDev can you check this with the latest version 2.3.9

**Comment by ProteanDev** [comment]
@akhil-geekyants I tried, yeah this may Not be an issue with native-base but with react native's TextInput props.
