### ISSUE TITLE
Input box hidden by keyboard

### ISSUE THREAD

**Issue by amirfl** [GeekyAnts/NativeBase#79]
When I have a lot of content on screen with an Input box at the bottom, the keyboard hides that Input after it gets focus.
In my previous React-Native apps, I solved this with a  compoent named [react-native-keyboard-aware-scroll-view](https://github.com/APSL/react-native-keyboard-aware-scroll-view)
Is there a way to solve this in NativeBase?

Thanks for creating this great library

**Comment by sankhadeeproy007** [comment]
Updated with v0.5.2
