### ISSUE TITLE
Scroll issue with container and content

### ISSUE THREAD

**Issue by rithvikvibhu** [GeekyAnts/NativeBase#790]
react-native-cli: 2.0.1
react-native: 0.42.0
native-base: 2.0.13

## Expected behaviour
Scroll with all cards (at least 4)

## Actual behaviour
Cannot scroll completely. Only first 1.5 cards visible

## Steps to reproduce (code snippet or screenshot)
Note: Container has backgroundColor `red` and content has `black`. Helps with identifying in screen capture below.
```js
render() {
    if (this.state.dataLoaded) {

      return (
        <Container style={{backgroundColor: 'red'}}>
          <Content padder style={{marginBottom: 100, height: 2000, backgroundColor: 'black'}}>
            {
              this.remoteFoodData.map( (food, index) => {
                return(
                  <Card style={foodListStyles.card} key={index}>
                    <CardItem>
                      <Left>
                        <Body>
                          <Text style={foodListStyles.foodName}>{food.name}</Text>
                          <Text note>By {food.sellerName}</Text>
                        </Body>
                      </Left>
                      <Right>
                        <Body>
                          <Text style={[foodListStyles.foodVen, food.ven === 'Veg' ? foodListStyles.green : foodListStyles.red]}>{food.ven}</Text>
                        </Body>
                      </Right>
                    </CardItem>

                    <CardItem cardBody>
                      <Image style={foodListStyles.foodPic} source={{uri: food.pic}} />
                    </CardItem>

                    <CardItem style={{ justifyContent: 'space-around' }}>
                      <Button transparent>
                        <Icon active name="md-heart" />
                        <Text>{food.likes}</Text>
                      </Button>
                      <Text>₹{food.cost} per {food.unit}</Text>
                      <Text>Order in 2 hours</Text>
                    </CardItem>

                  </Card>
                )
              })
            }
          </Content>
      </Container>
      )

    } else {

      return(
        <Container>
          <Content padder>
            <Spinner color='blue' />
          </Content>
        </Container>
      )
    }

  }
```
## Screenshot of emulator/device
![scroll](https://cloud.githubusercontent.com/assets/5113343/25423613/fb49be98-2a82-11e7-94b4-9202fcc6201f.gif)

## Is the bug present in both ios and android or in any one of them?
Yes, in android. Haven't tested iOS

**Comment by irekrog** [comment]
I have the same problem. Any idea?

**Comment by rithvikvibhu** [comment]
So I figured its because of the container height. Setting it to something greater than the height of the content shows everything. Since content is dynamically loaded, setting a static height for container isn't a fix. Any ideas?

**Comment by gabrielpjordao** [comment]
Experiencing the same issue here. Ideas?

**Comment by rithvikvibhu** [comment]
Try removing Container or Content. I wasn't working for me because both are scrollable.

**Comment by SupriyaKalghatgi** [comment]
```
    "native-base": "2.1.4",
    "react": "16.0.0-alpha.6",
    "react-native": "0.44.0",
```
![container](https://cloud.githubusercontent.com/assets/13464885/26350609/709381b2-3fd1-11e7-84ff-e0eb3cdac306.gif)

**Comment by gabrielpjordao** [comment]
Thank you for your help. It was an expo bug. After deleting and reinstalling the client, it began to work..

**Comment by rithvikvibhu** [comment]
@SupriyaKalghatgi Try removing all `height` styles applied to Content and Container.

**Comment by dsp1589** [comment]
am facing the same issue in android but working fine in iOS.
