### ISSUE TITLE
Container flex: to flexGrow error

### ISSUE THREAD

**Issue by smooJitter** [GeekyAnts/NativeBase#791]
I'm using react-native-navigation.

The Container component yields the following error.
`
View was rendered with explicitly set width/height but with a 0 flexBasis.  (This might be fixed by changing flex: to flexGrow:) View:<RCTShadowView: ...>
`
I was able to fixed the problem by using StyleProvider and changing the flex attribute accordingly.  Apparently this was a breaking change to RN .36.  

My question, consider I made the change on the customized version of Container, should I expect any errors?

**Comment by shivrajkumar** [comment]
@smooJitter Customizing the theme won't throw any error. Using StyleProvider you pass your local customized theme to the NativeBase components, which overwrites the default theme of NativeBase components.
