### ISSUE TITLE
Styles for disabled checkbox and disabled text input 

### ISSUE THREAD

**Issue by Darex1991** [GeekyAnts/NativeBase#794]
Hi guys,
I wanted to style checkbox with attribute disabled and text input. How can I do this?
I trying using "Theme" files but is not working (maybe my bad). 
For these I tried adding new styles into "InputGroup.js" and "CheckBox.js" files:

```
'.disabled': {
        'NativeBase.Input': {
          color: 'red',
        },
```

"native-base": "2.0.12",
"react": "15.4.1",
"react-native": "0.42.3",

Thanks for any help.
Darek

**Comment by SupriyaKalghatgi** [comment]
You should go through [Theme Your Custom Component](https://docs.nativebase.io/Customize.html#custom-component-headref) completely to implement your requirement
