### ISSUE TITLE
Big space between <Left> and <Body> in Header component (NativeBase ^2.1.3)

### ISSUE THREAD

**Issue by gustavorozolin** [GeekyAnts/NativeBase#795]
I have used this code:
`<Header>
          <Left>
            <Button transparent onPress={() => this.voltar()}>
              <Icon name="arrow-back"/>
            </Button>
          </Left>
          <Body>
            <Title>Title</Title>
          </Body>
        </Header>`

Result:
![screenshot_2017-04-27-16-07-14](https://cloud.githubusercontent.com/assets/1047333/25500106/149e525a-2b64-11e7-9860-d1fd9aa41c52.png)

**Comment by shivrajkumar** [comment]
You also need to include `<Right />` inside the Header

**Comment by gustavorozolin** [comment]
Thanks for reply @shivrajkumar,

I've made 3 new tests and I got this result:
![screenshot_2017-04-28-14-24-43](https://cloud.githubusercontent.com/assets/1047333/25539843/639398f0-2c1f-11e7-88a2-d79b5d4cbde9.png)
![screenshot_2017-04-28-14-24-32](https://cloud.githubusercontent.com/assets/1047333/25539845/63976778-2c1f-11e7-9ff2-4c9bd282254b.png)
![screenshot_2017-04-28-14-23-34](https://cloud.githubusercontent.com/assets/1047333/25539844/63954c22-2c1f-11e7-8853-670f0c211b82.png)

**Comment by RakhmatovR** [comment]
@shivrajkumar and so NativeBase Header doesn't follow Material UI guidelines, yep?
https://material.io/guidelines/layout/structure.html#structure-app-bar
It will be all the same if you write Header correctly with Left, Body and Right components. Title will be far from Left icon.

**Comment by samosaara** [comment]
Sorry for necro-posting this issue, but it is the first one on google. You can fix that property applying flex items properties, to the `<Left>` `<Body>`  and `<Right>` like flex, flex-grow, flex-shrink etc.
