### ISSUE TITLE
Extracted theme scripts fail to be imported when "color" 1.x package is used in app.

### ISSUE THREAD

**Issue by ivankashtanov** [GeekyAnts/NativeBase#797]
My project uses [color](https://www.npmjs.com/package/color) package as a dependency, the version is 1.0.3.
When I extract NB theme to customize it and then import into my app scripts, it fails.
The reason is that NB uses old version of color package which uses methods removed in 1.x, so when I extract theme and it starts using color module from my dependencies, it calls undefined functions.
Example [here](https://github.com/GeekyAnts/NativeBase/blob/master/src/theme/variables/material.js#L173): `hexString` exists in 0.11 but it's renamed to `hex` in 1.x.

The solution would be updating your dependency or adding some info about this situation to docs.

- react-native 0.42, react 15.4.1 and native-base 2.0.11
- expected behaviour: no errors after importing e.g. `variables\material.js` from extracted theme
- actual behaviour: error `undefined is not a function (evaluating '(0, _color2.default)(this.toolbarDefaultBg).darken(0.2).hexString()')` on [this](https://github.com/GeekyAnts/NativeBase/blob/master/src/theme/variables/material.js#L173) line
- Steps to reproduce (code snippet or screenshot):
    - extract theme
    - install npm package `color` as dependency for app
    - import `%theme_location%/variables/material.js`

**Comment by sankhadeeproy007** [comment]
cc @GeekRishabh

**Comment by GeekRishabh** [comment]
@ivankashtanov Thanks for pointing this out . We will fix this in our next release .If you don't need latest color module you can use the older version as of now (V0.11.1) . which will be already in node_module all you need to do is to import that .

**Comment by ivankashtanov** [comment]
@GeekRishabh Thanks for the workaround. But the app already uses new color package, so I just replaced `hexString` calls with `hex` in extracted theme. Haven't had other problems with the theme yet.

**Comment by sankhadeeproy007** [comment]
Fixed with 2.1.5
