### ISSUE TITLE
Can't find variable: Header

### ISSUE THREAD

**Issue by GiacomoK** [GeekyAnts/NativeBase#798]
Hi,
I tried to add an Header to my view, but I get this error:

Can't find variable: Header

This is my code:

    ...
    import { Container, Content, List, ListItem } from 'native-base';

    class RootContainer extends Component {

        componentDidMount () {
            // if redux persist is not active fire startup action
            if (!ReduxPersist.active) {
                this.props.startup()
            }
        }

      render () {
        return (
            <Container>
                <Header>
                    <Left>
                        <Button transparent>
                            <Icon name='arrow-back' />
                        </Button>
                    </Left>
                    <Body>
                        <Title>Header</Title>
                    </Body>
                    <Right>
                        <Button transparent>
                            <Icon name='menu' />
                        </Button>
                    </Right>
                </Header>
                <ScrollableTabView
                    style={{marginTop: 20, }}
                    initialPage={1}
                    renderTabBar={() => <AmalarteBar />}>
                    <ScrollView tabLabel="ios-film" style={styles.tabView}>
                        <View>
                            <Container>
                                <Content>
                                    <List>
                                        <ListItem >
                                            <Text>Simon Mignolet</Text>
                                        </ListItem>
                                        <ListItem>
                                            <Text>Nathaniel Clyne</Text>
                                        </ListItem>
                                        <ListItem>
                                            <Text>Dejan Lovren</Text>
                                        </ListItem>
                                    </List>
                                </Content>
                            </Container>
                        </View>
                    </ScrollView>
                    <ScrollView tabLabel="ios-musical-notes" style={styles.tabView}>
                        <View style={styles.card}>
                            <Text>Concerti musicali</Text>
                        </View>
                    </ScrollView>
                </ScrollableTabView>
            </Container>
        )
      }
    }

Any help?

Thanks

**Comment by himanshu-satija** [comment]
You have to import all the Native Base components that you are using.

`import { Container, Content, List, ListItem, Header, Button, Icon, View, /* All native-base components used in this file */ } from 'native-base';

**Comment by GiacomoK** [comment]
Why did you close the ticket? The docs are wrong, change them pls.

**Comment by sankhadeeproy007** [comment]
@GiacomoK Did the above solution work for you?

**Comment by GiacomoK** [comment]
Yes but the docs are wrong. Can you fix it pls?

**Comment by sankhadeeproy007** [comment]
Yes, we're working on the docs. Will be updated on monday.
cc @Jasbir23
