### ISSUE TITLE
Include <Footer> component in Component Anatomy Documentation

### ISSUE THREAD

**Issue by s2t2** [GeekyAnts/NativeBase#80]
The [Documentation about Component Anatomy](http://nativebase.io/docs/v0.5.0/components#anatomy) says: "Container takes mainly three components: `<Header>` and `<Content>`" and goes on to give examples about those two components. 

Should `<Footer>` be the third component referenced by name and included in the examples below?

**Comment by SupriyaKalghatgi** [comment]
@s2t2 Sorry for this.
`Footer` is under development and be released soon

**Comment by s2t2** [comment]
This is less of a confusion/blocker and more of an attempt to improve the
docs. FYI - for me, footer is working fine on Android.

Thanks again for this library!

**Comment by sankhadeeproy007** [comment]
Good to know you find it useful 👍

**Comment by adambene** [comment]
Footer is really useful, looking forward to the release.

**Comment by parkerproject** [comment]
looking forward to Footer:) Nice work guys!

**Comment by SupriyaKalghatgi** [comment]
Footer included with 0.5.8

**Comment by s2t2** [comment]
Footer is not in the documentation ([cheat sheet](http://nativebase.io/docs/v0.5.5/cheatsheet)).
