### ISSUE TITLE
DeckSwiper - How to know which card was swiped?

### ISSUE THREAD

**Issue by OmriAharon** [GeekyAnts/NativeBase#802]
## react-native, react and native-base version
NB - 2.1.2
RN - 0.43.3
React - 16.0.0-alpha.6

This is not really a bug, but it's unclear from the documentation and there are no parameters for `onSwipeLeft`/`onSwipeRight`.

Let's say I want to do something to the card getting swiped - how do I know which got swiped? Is there a way to get a reference to the element?

**Comment by ppoliani** [comment]
It looks like currently, both functions don't pass any parameters. However, there is already a `selectedItem` property in the `state` so I assume it would be a very [quick fix](https://github.com/GeekyAnts/NativeBase/pull/807).

**Comment by OmriAharon** [comment]
Let it merge! 😄

**Comment by lsps9150414** [comment]
Let it merge!

**Comment by sankhadeeproy007** [comment]
cc @shivrajkumar

**Comment by sankhadeeproy007** [comment]
Fixed with 2.1.5
