### ISSUE TITLE
Please avoid json.stringify

### ISSUE THREAD

**Issue by smmoosavi** [GeekyAnts/NativeBase#803]
in `ScrollableTabBar.componentWillReceiveProps` method `JSON.stringify` used which cause slow rendering and some times error thrown from this line.

## react-native, react and native-base version
react-native@0.43.2
react@16.0.0-alpha.6
native-base@2.1.2
## Steps to reproduce (code snippet or screenshot)
you can't run [advanced tab example](https://docs.nativebase.io/COMPONENTS.html#Advanced_Tabs) and you will see `TypeError: Converting circular structure to JSON`

```
                <Tab heading={ <TabHeading><Icon name="camera" /><Text>Camera</Text></TabHeading>}>
                    <Tab1 />
                </Tab>
```

## Is the bug present in both ios and android or in any one of them?
I checked android

## Any other additional info which would help us debug the issue quicker.

bad code:
```
    if (JSON.stringify(this.props.tabs) !== JSON.stringify(nextProps.tabs) && this.state._containerWidth) {
      this.setState({ _containerWidth: null, });
    }
```
https://github.com/GeekyAnts/NativeBase/blob/031cd958b51a043480f3cc4b665a05640654545d/src/basic/Tabs/ScrollableTabBar.js#L214

**Comment by ishsingh** [comment]
I have the same problem with following versions:

react-native@0.44.0
react@16.0.0-alpha.6
native-base@2.1.3
