### ISSUE TITLE
The Components section of your website isn't resolving

### ISSUE THREAD

**Issue by chapeljuice** [GeekyAnts/NativeBase#810]
https://docs.nativebase.io/Components.html#Components produces a 404:
```
Not Found

The requested URL /Components.html was not found on this server.

Additionally, a 404 Not Found error was encountered while trying to use an ErrorDocument to handle the request.
```

**Comment by aleinnocenzi** [comment]
Same problem also for the "customize" section
https://docs.nativebase.io/Customize.html#Customize

**Comment by GeekRishabh** [comment]
@chapeljuice @aleinnocenzi  Thanks for bringing this in notice . Few changes were made so you can try the below url as of now
https://docs.nativebase.io/COMPONENTS.html#Components
https://docs.nativebase.io/CUSTOMIZE.html#Customize

**Comment by ElliottJRo** [comment]
^ Above links still giving 404
