### ISSUE TITLE
Input onChangeText (undefined is not a function)

### ISSUE THREAD

**Issue by pukeanddie** [GeekyAnts/NativeBase#811]
react-native 0.44.0
react: 16.0.0
native-base: 2.1.3
android (ios untested)

```
class SomeFormComponent extends Component {
render() {
     return (
         // ....omitted....
          <Input 
                onChangeText={value => this.props.myTextAction({ prop: 'value', value })}
                value={this.props.value}
          />
     );
}
//... omitted...
}

//...omitted
export default connect(mapStateToProps, { myTextAction })(SomeFormComponent);
```

Red screen of death throws error: 'undefined is not a function (evaluating 'this2.props.myTextAction({prop:'value', value: value})')

**Comment by pukeanddie** [comment]
My issue has been resolved and is entirely unrelated to native-base.

**Comment by princenaman** [comment]
@pukeanddie 
I am also having the same issue.
How did you solve?

**Comment by omair115** [comment]
How did you solve?
