### ISSUE TITLE
Deprecation Warning on React Native 44

### ISSUE THREAD

**Issue by stefensuhat** [GeekyAnts/NativeBase#813]
```
Warning: View.AccessibilityTraits has been deprecated and will be removed in a future version of ReactNative. Use ViewAccessibility.AccessibilityTraits instead.

Warning: View.AccessibilityComponentType has been deprecated and will be removed in a future version of ReactNative. Use ViewAccessibility.AccessibilityComponentTypes instead.

Warning: View.forceTouchAvailable has been deprecated and will be removed in a future version of ReactNative. Use NativeModules.PlatformConstants.forceTouchAvailable instead.

Warning: View.propTypes has been deprecated and will be removed in a future version of ReactNative. Use ViewPropTypes instead.
```

Here is what I import:
```
import { Container, Content, Footer, FooterTab } from 'native-base';
```

Latest NativeBase
React Native 44

**Comment by fhad-getmaple** [comment]
+1

**Comment by haythemOUE** [comment]
+1

**Comment by zerokid** [comment]
+1

**Comment by BroshkovD** [comment]
+1

**Comment by AJDowds** [comment]
+1

**Comment by ZevenFang** [comment]
+1

**Comment by tonylinyy** [comment]
+1

**Comment by jjsaguit** [comment]
+1

**Comment by zerokid** [comment]
just run react-native uninstall native-base. the warning gone

**Comment by hanpanpan200** [comment]
+1

**Comment by pohodnya** [comment]
+1

**Comment by azulkipli** [comment]
+1

**Comment by jamesphe** [comment]
+1

**Comment by BenBenz** [comment]
+1

**Comment by leonardollobato** [comment]
+1

**Comment by fhad-getmaple** [comment]
@zerokid's solution works: run `react-native uninstall native-base`

This issue should be closed

**Comment by agersoncgps** [comment]
Sorry if I am being dense here, but how does uninstalling native-base constitute a solution? I would like to use native-base.

**Comment by thilook** [comment]
Any news if this will be fix in future releases?

**Comment by Tiendq** [comment]
`react-native uninstall native-base` isn't a solution, I ran it and get following error:

`rnpm-install WARN ERRINVALIDPROJ Project native-base is not a react-native library`
`Cannot find module '/Users/<project path>/node_modules/native-base/package.json'`

**Comment by sanketsahusoft** [comment]
We are trying to fix this ASAP.

**Comment by sanketsahusoft** [comment]
@agersoncgps That's true, it's been unsolved. We are fixing this. You can continue using it and rely on us that this warning will be fixed in the next fix bump of NativeBase.

@zerokid @fhad-getmaple Thanks for putting our morale down. I still hope NativeBase helped you somewhere.

**Comment by agersoncgps** [comment]
@stefensuhat Native Base helps me a lot! Thank you for your hard work.

**Comment by SupriyaKalghatgi** [comment]
Fixed with [2.1.4](https://github.com/GeekyAnts/NativeBase/releases/tag/v2.1.4)

**Comment by nikhilcoolstuff** [comment]
I'm still getting this warning with version 2.1.4

**Comment by lashae** [comment]
I'm getting the same warning even with version 2.2.0
