### ISSUE TITLE
Subtitle fontSize in Header not working

### ISSUE THREAD

**Issue by fhad-getmaple** [GeekyAnts/NativeBase#817]
Seems like the fontSize set in native-base-theme/components/Header.js isn't being passed down to the Subtitle component in Headers. I also tried ejecting the Theme files again.

React-Native v0.44
Native-Base v2.1.3

<img width="263" alt="screen shot 2017-05-05 at 2 34 48 pm" src="https://cloud.githubusercontent.com/assets/22453066/25759341/0389a04a-31a0-11e7-80d8-a5b67e590507.png">

**Comment by HermantoTang** [comment]
Seems like the whole subtitle style is not working in my case,
same issue as #675 

```
    "native-base": "2.1.3",
    "react": "16.0.0-alpha.6",
    "react-native": "0.43.4",
```

**Comment by GeekRishabh** [comment]
@fhad-getmaple 
```
 <Header hasSubtitle>
    <Left>
                    <Button transparent>
                        <Icon name='arrow-back' />
                    </Button>
                </Left>
                <Body>
                    <Title>Title</Title>
                    <Subtitle style={{fontSize: 20, color: 'red'}}>Subtitle</Subtitle>
                </Body>
                <Right />
            </Header>
```
try the above code will work for you.

**Comment by fhad-getmaple** [comment]
Hi @GeekRishabh, 

Thanks for the work around. Do you have any word if the bug itself will be fixed in an update?

Thanks.

**Comment by SupriyaKalghatgi** [comment]
package.json
```
    "native-base": "^2.1.4",
    "react": "16.0.0-alpha.6",
    "react-native": "^0.44.0",
```

This works fine, with default components, without inline style

![screen shot 2017-06-01 at 4 52 04 pm](https://cloud.githubusercontent.com/assets/13464885/26677704/bc7678f8-46ea-11e7-9853-72ace7032ec9.png)

**Comment by aswinramakrish** [comment]
`Subtitle` doesn't seem to work. Here is my `package.json`

    "react": "16.2.0",
    "react-native": "0.52.2",
    "native-base": "^2.3.7"

I see a definition for `Title`, but not for `Subtitle` (`t` with a lower case). But I see `SubTitle`, but if I use that I get the following error.

    Invariant Violation: Element type is invalid: expected a string (for built-in components) or a 
    class/function (for composite components) but got: undefined. You likely forgot to export your 
    component from the file it's defined in, or you might have mixed up default and named imports.

Here is what I see in the definition -

![screen shot 2018-03-18 at 5 42 02 pm](https://user-images.githubusercontent.com/1799620/37572648-cb6aec9a-2ad3-11e8-964f-f4854637fae4.png)

![screen shot 2018-03-18 at 5 43 17 pm](https://user-images.githubusercontent.com/1799620/37572657-e49a8a2c-2ad3-11e8-9a68-640f94a1dcec.png)

I'm using it exactly the way it says in the example in the docs. Something like this -

    <Container>
      <Header>
        <Left>
          <Button transparent>
            <Icon name='arrow-back' />
          </Button>
        </Left>
        <Body>
          <Title>Title</Title>
          <Subtitle>Subtitle</Subtitle>
        </Body>
        <Right />
      </Header>
    </Container>

**Comment by akhil-geekyants** [comment]
@aswinramakrish are you still facing this issue. Checked this. It is working fine (with 2.3.10). Attaching a gif

Gif

![subtitle](https://user-images.githubusercontent.com/27768184/37585901-a99f0562-2b80-11e8-8cf0-78c68af09fcb.gif)

**Comment by aswinramakrish** [comment]
Ok. Found the issue. The default color of `Subtitle` is `#ffffff` and guess what my header background was? 😂
