### ISSUE TITLE
SimpleLineIcons.ttf: No such file or directory

### ISSUE THREAD

**Issue by sheprdinc** [GeekyAnts/NativeBase#820]
This happens even after running:  react-native link

Can i just delete it?

**Comment by sheprdinc** [comment]
So on further digging, react-native link forces that font 2 appear twice info.pList, plus the file does not exist in node_modules/native-base/Fonts ... so if anyone runs into this, just grab the font from here:
https://github.com/oblador/react-native-vector-icons/blob/master/Fonts/SimpleLineIcons.ttf
Then manually add it to your RN project.
Resolved!

**Comment by shivrajkumar** [comment]
@sheprdinc May i know the version of native-base you are using?

**Comment by kernelgonnapanic** [comment]
I also encountered this issue. I'm using `native-base@2.1.0`.

**Comment by GeekRishabh** [comment]
@sheprdinc @kernelgonnapanic what is the RN version you guys are using  ?
Rather mention the step to reproduce so that we can look into it .

**Comment by kernelgonnapanic** [comment]
I just installed native-base in my project. I've run link and started the project build. 
I got such error:
`project-name/node_modules/native-base/Fonts/SimpleLineIcons.ttf: No such file or directory`

My dependencies:
```
   "babel-plugin-flow-react-proptypes": "^2.2.1",
    "eslint": "^3.15.0",
    "eslint-config-airbnb": "^14.1.0",
    "eslint-config-react-native": "^1.6.0",
    "eslint-plugin-import": "^2.2.0",
    "eslint-plugin-jsx-a11y": "^3.0.2 || ^4.0.0",
    "eslint-plugin-react": "^6.9.0",
    "graphql-tag": "^2.0.0",
    "jest-transform-graphql": "^2.0.0",
    "lodash": "^4.17.4",
    "native-base": "2.1.0",
    "react": "~15.4.0",
    "react-apollo": "^1.1.2",
    "react-native": "0.42.3",
    "react-native-config": "^0.3.1",
    "react-navigation": "^1.0.0-beta.7",
    "react-redux": "^5.0.4",
    "redux": "^3.6.0",
    "redux-logger": "^3.0.1",
    "redux-thunk": "^2.2.0",
    "reselect": "^3.0.0"
```
Let me know if you need more info.

**Comment by SupriyaKalghatgi** [comment]
@sheprdinc @kernelgonnapanic Please check [2.1.4](https://github.com/GeekyAnts/NativeBase/releases/tag/v2.1.4)

**Comment by SupriyaKalghatgi** [comment]
Works with NativeBase [2.1.4](https://github.com/GeekyAnts/NativeBase/releases/tag/v2.1.4) by ejecting the Theme

**Comment by quadsurf** [comment]
@GeekRishabh sorry for late response (it's me @sheprdinc) ... in answer to your request:
"native-base": "^2.0.7"
"react-native": "0.42.0"

**Comment by quadsurf** [comment]
this issue is still happening by the way, and every time i remove node_modules and re-install, i have to perform my workaround all over again
