### ISSUE TITLE
Flatlist instead of ListView in List Component

### ISSUE THREAD

**Issue by Nygma297** [GeekyAnts/NativeBase#822]
## Version Info
* react-native:0.42.0
* react: 15.4.2
* native-base: ^2.0.11
## Issue Type: 
- [x] Feature
- [ ] Bug
## Performance Issue:
Android 
iOS.

If You could do this it would make the rendering of the lists faster and would also help to handle large or bad data in the list's dataSource

**Comment by SupriyaKalghatgi** [comment]
#625

**Comment by tmaly1980** [comment]
@SupriyaKalghatgi , so how would we use FlatList with the swipeable rows? I've looked in List.js (v2.3.0) and it's still using ListView.

**Comment by levani** [comment]
Any update on this? Can find any usage of `FlatList` anywhere in this repo...

**Comment by njt1982** [comment]
Example seems to be here: http://docs.nativebase.io/docs/examples/FlatListExample.html
