### ISSUE TITLE
Deck Swiper Flashing Content

### ISSUE THREAD

**Issue by brodus13** [GeekyAnts/NativeBase#826]
Hi there! I checked around and didn't notice any existing issues open for this.

I'm having an issue where I have quite a bit of content inside of my deck swiper cards, and random parts of the content seem to flash from invisible to visible at random intervals when the cards are being swiped, or moved around.

Is this something I'm doing wrong? It seems like a bug to me. I'd opened a question about it in the forms to ask if it was an issue with something on my end, but I had no replies, and one person comment saying the same thing was happening to them. I'll link this below...
http://discuss.nativebase.io/t/deck-swiper-content-flashing/407

I don't have an example of it on hand, but I could probably create one if there isn't an easy answer for this.

Thanks so much for your time!

**Comment by SupriyaKalghatgi** [comment]
@brodus13 What version of React Native and NativeBase are you on?
It would be good if you could post the snippet with output here

**Comment by SupriyaKalghatgi** [comment]
#866

**Comment by SupriyaKalghatgi** [comment]
#334

**Comment by brodus13** [comment]
Hi there @SupriyaKalghatgi , sorry for the delayed response, here's the versions I'm working on.
"native-base": "2.1.0-rc.2",
"react": "~15.4.0",
"react-native": "0.42.3",

**Comment by mdebo** [comment]
Hi!
I'm facing the same issue using react-native 0.44.3 and native-base 2.1.4
Any news about it?

Thanks!

**Comment by flieks** [comment]
i'm having the same issue. Please look at my video in referenced issue

**Comment by pallavbakshi** [comment]
Hey! I haven't checked out the code of GeekyAnts Nativebase package but generally my images flash when I re-render a component from <View> tag to <Animated.View> tag. So basically, you should use <Animated.View> even for the cards that are not at the top of the stack.

**Comment by CliveTeow** [comment]
Yes. I followed a deck swiper component creation online tutorial. After use <Animated.View> for the cards that are not at the top of the stack, the image flashing is gone.

**Comment by carocad** [comment]
Hey guys, I am having this same issue.

The Animated.View approach didnt work for me though :(

However I was able to find something out. The content flickers because it is being re-rendered several times. By putting a simple log statement in the renderItems function you can see everytime that the card is swipe the item is re-rendered between 5 to 8 times.

I would expect a single re-render since it is basically switching from one item to the next.

Hope it helps

**Comment by ojathelonius** [comment]
@carocad How did you fix the re-rendering issue then ? Did you have to override the shouldComponentUpdate method ?

**Comment by carocad** [comment]
@ojathelonius I couldnt find a solution for it. I just stopped using using after I found what the problem was and switched to a more basic approach :/

**Comment by ojathelonius** [comment]
@carocad I'll give it a try, there may be a way to prevent rendering the component (let alone the thumbnail inside) while swiping.

Out of curiosity, did you try the other swipe cards libraries out there ? I need the same look and feel and would then seek another solution to retain the same behavior.

**Comment by carocad** [comment]
@ojathelonius no I didnt try the other libraries. I simply created a View which I re-render whenever the user request the next item.

**Comment by ojathelonius** [comment]
@carocad 
Alright, thanks !

**Comment by e11i0t** [comment]
I got the issue that local images were loading properly, but external images were flickering. Using FastImage from https://github.com/DylanVann/react-native-fast-image fixed the issue for me

**Comment by aravi365** [comment]
i am having a serious performance issue while using the deckswiper of nativebase. When the data increases the deckswiper seems to be responding very poor and is also flashing.

**Comment by voold** [comment]
Same for me
