### ISSUE TITLE
ActionSheet cannot show TWICE

### ISSUE THREAD

**Issue by zywj** [GeekyAnts/NativeBase#827]
react-native: **0.44**
native-base: **2.1.3**
react-navigation: **1.0.0-beta.9**

Expected behaviour:  **Using ReactNavigation from one screen back to this parent and can show ActionSheet or Toast again successfully**

Actual behaviour: **I cannot show ActionSheet or Toast again, when I back**

Steps to reproduce:  

## First Step
<img width="329" alt="cb5f7485-78a8-4443-814a-4561bc86a1fb" src="https://cloud.githubusercontent.com/assets/5554211/26023363/621280b2-37ec-11e7-8eb4-afd13f431e69.png">

## Second Step
<img width="263" alt="35e9d428-80db-49d5-882c-cdf750d48ae1" src="https://cloud.githubusercontent.com/assets/5554211/26023365/65c69cc0-37ec-11e7-9444-e6bb9c6d850f.png">

## Third Step
<img width="384" alt="8aaec2a8-03f6-474e-85a1-19ac91b632b8" src="https://cloud.githubusercontent.com/assets/5554211/26023366/683e7e28-37ec-11e7-8411-68259e16ef73.png">

## ERROR
![image](https://cloud.githubusercontent.com/assets/5554211/26023367/6bf28596-37ec-11e7-96e9-f2259e9c68b6.png)

**Comment by zywj** [comment]
Here is the error line
https://github.com/GeekyAnts/NativeBase/blob/master/src/basic/Actionsheet.js#L29

And the instance is here:
https://github.com/GeekyAnts/NativeBase/blob/master/src/basic/Container.js#L16

It can't found the '_root' (**Container** element), after navigation backed to the ActionSheet screen.

**Comment by lndj** [comment]
Give up and nobody can help you!

**Comment by zywj** [comment]
@lndj  I am  confused

**Comment by yeknava** [comment]
Same in android with react-native-router-flux navigator.

**Comment by zywj** [comment]
@lndj @yeknava  I gave up and now using https://www.npmjs.com/package/react-native-actionsheet

**Comment by SupriyaKalghatgi** [comment]
We will look into this very soon

**Comment by shivrajkumar** [comment]
#739
