### ISSUE TITLE
can't find variable StyleProvider

### ISSUE THREAD

**Issue by payamka** [GeekyAnts/NativeBase#828]
Hi
I wnt to using NativeBase in my app but I get this error:
can't find variable StyleProvider

And this my code in android.index:

`/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 * @flow
 */

import React, { Component } from 'react';
import {
  AppRegistry,
  StyleSheet,
  Text,
  View
} from 'react-native';
import getTheme from './native-base-theme/components';

export default class AwesomeNativeBase extends Component {
  render() {
    return (
      <StyleProvider style={getTheme()}>
		<Container>
			<Content>
				<Button>
					<Text>Click Me! </Text>
				</Button>
			</Content>
		</Container>
	  </StyleProvider>
	  
    );
  }
}

AppRegistry.registerComponent('AwesomeNativeBase', () => AwesomeNativeBase);
`

Can you help me about this problem?
Thanks

**Comment by SupriyaKalghatgi** [comment]
@payamka What versions of React Native and NativeBase are you on?

**Comment by shivrajkumar** [comment]
Check the latest of NativeBase
