### ISSUE TITLE
[Feature Request] Centering content should be easier

### ISSUE THREAD

**Issue by warent** [GeekyAnts/NativeBase#829]
In this page, https://docs.nativebase.io/Components.html#Components in the very first example that shows a logo with "Build Something Amazing" you align content in a way that isn't obvious at all. It took me longer than it probably could have have to find out I had to do this (and I'm still not sure if this is best practice)

```jsx
      <Container>
        <Body>
          <Content contentContainerStyle={{ height: '100%', justifyContent: 'center' }}>
          </Content>
        </Body>
      </Container>
```

**Comment by SupriyaKalghatgi** [comment]
Check with [NativeBase KitchenSink](https://github.com/GeekyAnts/NativeBase-KitchenSink)
Similar example [here](https://github.com/GeekyAnts/NativeBase-KitchenSink/blob/master/js/components/home/index.js)

**Comment by chrischen-melb** [comment]
```jsx
<Container>
  <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}>
    // ...
  </View>
</Container>

```
this will do. But you will loose some of the perks of `<Content>`?
