### ISSUE TITLE
Title not stylable?

### ISSUE THREAD

**Issue by s2t2** [GeekyAnts/NativeBase#83]
Can you please provide guidance on how to properly style the `<Title>` component?

Given this style definition:

```` js
var styles = StyleSheet.create({
  title: {
    color:"#ffffff",
    fontSize:20,
    fontFamily:"sans-serif-medium"
  }
}
````

... when used to style a react-native `<Text>` component, it works:

```` js
<Header style={styles.header}>
   <Text style={styles.title}>My Title</Text>
</Header>
````

![screenshot 2016-07-26 16 53 29](https://cloud.githubusercontent.com/assets/1328807/17142756/97796e08-5351-11e6-9680-69b0053218f7.png)

... but when used to style a `<Title>` component, it does not work:

```` js
<Header style={styles.header}>
  <Title style={styles.title}>My Title</Title>
</Header>  
````

![screenshot 2016-07-26 16 53 43](https://cloud.githubusercontent.com/assets/1328807/17142775/a5e7360a-5351-11e6-89a7-ea65952a3304.png)

<hr>

I would just stick to using `<Text>` in the header, but in conjunction with a `<Button>`, the text does not show up, whereas the `<Title>` does. 

```` js
<Header style={styles.header}>
  <Button transparent onPress={this.goBack}>
    <Icon name="md-arrow-back" style={styles.backIcon}/>
  </Button>
   <Text style={styles.title}>My Title</Text>
</Header>
````
![screenshot 2016-07-26 16 58 27](https://cloud.githubusercontent.com/assets/1328807/17142974/3ae225f8-5352-11e6-94c0-b021c4874b5a.png)

```` js
<Header style={styles.header}>
  <Button transparent onPress={this.goBack}>
    <Icon name="md-arrow-back" style={styles.backIcon}/>
  </Button>
   <Title style={styles.title}>My Title</Title>
</Header>
````

![screenshot 2016-07-26 16 56 41](https://cloud.githubusercontent.com/assets/1328807/17142979/3f2d232e-5352-11e6-83cf-6a73c662777f.png)

Please advise on how to properly style `<Title>` or how to display `<Text>` in the header in conjunction with a button.

**Comment by zzimbler** [comment]
@s2t2 I think you can control this by creating a separate "theme file." if you look at the source of the Title component it's pulling the fontSize and fontWeight from the theme file.

Check out http://nativebase.io/docs/v0.5.0/customize

**Comment by sankhadeeproy007** [comment]
@s2t2 I've fixed that it's available [here](https://github.com/GeekyAnts/NativeBase/blob/master/Components/Widgets/Title.js) on `master`. You can either pull from master or just copy the contents over to your project. We'll publish with the updates sometime later this week.

**Comment by SupriyaKalghatgi** [comment]
@s2t2 Check out [latest documentation](http://nativebase.io/docs/v0.5.2/customize) for customizing NativeBase components
