### ISSUE TITLE
Why eject theme?

### ISSUE THREAD

**Issue by warent** [GeekyAnts/NativeBase#830]
Hi there,

First I'd like to say that the method of StyleProvider is a really good one I think. It's super nice to have a general style provider abstracted out for us. Also thanks for your work on this project in general.

To the main point, I just think it's a little bizarre that we have to do this process of ejectTheme in order to start applying new global styles. Is it worth considering keeping the internal theme and allowing StyleProvider to overwrite those internal styles as needed? Then we could leave ejectTheme as a last resort.

One reason why I think ejectTheme might become a problem is if NativeBase updates the main theme, then users who have already ejected might find it rather difficult to merge in the updates.

**Comment by sanketsahusoft** [comment]
@warent Thanks for appreciation!

I understand your concern about ejectTheme. There is something interesting about ejectedTheme is that, you can safely delete everything which you don't touch from the ejected folder and pass only the properties which you want to change. NativeBase internally merges the theme with the default one.

**Comment by andidev** [comment]
@sanketsahusoft 
Sounds great though it does not seem to work. I tried to pass only footer background color and I got lots of errors
```xml
<StyleProvider style={getTheme({ footerDefaultBg: 'red' })}>
  ...
</StyleProvider>
```
though this seems to work
```xml
<StyleProvider style={getTheme({ ...platform, footerDefaultBg: 'red' })}>
  ...
</StyleProvider>
```

**Comment by sanketsahusoft** [comment]
@andidev It used to work fine but I will check it and provide you a working solution once I get deep into this one.

**Comment by sanketsahusoft** [comment]
@andidev And for now, I hope you can manage with the ejected theme.

**Comment by andidev** [comment]
```xml
<StyleProvider style={getTheme({ ...platform, ...myCustomTheme })}>
  ...
</StyleProvider>
```

works fine for me without ejecting the theme since I import the base theme I want to extend with 
```javascript
import platform from 'native-base/dist/src/theme/variables/platform';
```

**Comment by kodayashi** [comment]
This approach doesn't seem to work anymore @sanketsahusoft - What's the best practice for ejecting to apply custom styles while also having the ability to update native-base? I like the idea of merging a custom theme with the default one (so that if I upgrade native-base I get new styles/components, etc.).

Is explicit merging not needed? Does it now work automatically like you mentioned it should in your comment on May 16, 2017?
