### ISSUE TITLE
There is no gap between checkbox and text.

### ISSUE THREAD

**Issue by pedrogarciyalopez** [GeekyAnts/NativeBase#831]
## react-native, react and native-base version
native-base: 2.1.3,
react-native: 0.44.0
react: 16.0.0-alpha.6

## Steps to reproduce (code snippet or screenshot)
```javascript
import React, { Component } from 'react';
import { Container, Content, ListItem, Text, CheckBox } from 'native-base';
export default class CheckBoxExample extends Component {
    render() {
        return (
            <Container>
                <Content>
                    <ListItem>
                        <CheckBox checked={true} />
                        <Text>Daily Stand Up</Text>
                    </ListItem>
                    <ListItem>
                        <CheckBox checked={false} />
                        <Text>Discussion with Client</Text>
                    </ListItem>
                </Content>
            </Container>
        );
    }
}
```

## Screenshot of emulator/device
<img width="818" alt="screenshot" src="https://cloud.githubusercontent.com/assets/14232660/26106653/3331d774-3a4f-11e7-8be1-5f79acea508c.png">

## Is the bug present in both ios and android or in any one of them?
Android and iOS.

**Comment by GeekRishabh** [comment]
@pedrogarciyalopez  what you can do is pass style and add margin left to the Text.

**Comment by pedrogarciyalopez** [comment]
@GeekRishabh Of course I can do this. But I thought that it was already done for me. Nothing is said about it in the docs.

**Comment by GeekRishabh** [comment]
@pedrogarciyalopez  will try to get this fix in next  version

**Comment by pedrogarciyalopez** [comment]
@GeekRishabh Would be nice! i'll be waiting, thank you.

**Comment by GeekRishabh** [comment]
@pedrogarciyalopez  sorry I didn't go through your code .
NB have this resolved already . Please have a look at docs [here](https://docs.nativebase.io/Components.html#list-icon-headref).

**Comment by pedrogarciyalopez** [comment]
Yes,
```javascript
<ListItem icon>
  <Left>
    <CheckBox checked={true} />
  </Left>
  <Body>
    <Text>Daily Stand Up</Text>
  </Body>
</ListItem>
```
this markup works well!

@GeekRishabh thank you!
