### ISSUE TITLE
TouchableOpacity inside CardItem

### ISSUE THREAD

**Issue by kiranraj2k** [GeekyAnts/NativeBase#832]
```
       <CardItem button onPress={() => this.outside()}>
            <TouchableOpacity onPress={() => this.inside()}> 
            </TouchableOpacity>
        </CardItem>
```
When I click on TouchableOpacity it calls `this.outside()`. Basically instead of calling the `onPress`
event of the inner `Touchable` it calls the same of it's parent `Touchable`

But the following works:

```
 <TouchableOpacity onPress={() => this.outside()}> 
   <TouchableOpacity onPress={() => this.inside()}> 
   </TouchableOpacity>
  </TouchableOpacity>
```
In the above case clicking on the inner TouchableOpacity calls `this.inside()` only.

I would like to have the `CardItem` follow the same behaviour as well.

**Comment by Sky891028** [comment]
happend to me
