### ISSUE TITLE
How to set Header opacity

### ISSUE THREAD

**Issue by Symous** [GeekyAnts/NativeBase#833]
Hi, I try to change the opacity of the Header.
`<Header style={{backgroundColor:'gray',opacity:0.5}}/>`
But that doesn't work.

**Comment by SupriyaKalghatgi** [comment]
![screen shot 2017-05-24 at 12 56 02 pm](https://cloud.githubusercontent.com/assets/13464885/26391436/6e794588-4080-11e7-8f94-73035a09fb5a.png)

What is the issue you are facing
Please share your output

**Comment by Symous** [comment]
Yes. I have no idea why it didn't work last time, but is OK now.Thanks a lot. :-)

**Comment by ydv0121** [comment]
set
Header style={{elevation:0}}
its works
thank you @ChetanGodiya4
