### ISSUE TITLE
Native base shoutem theme - Unable to resolve module

### ISSUE THREAD

**Issue by alex-dotdev** [GeekyAnts/NativeBase#834]
Error:
Unable to resolve module `./examples/Shapes` from `../node_modules/native-base-shoutem-theme/index.js` - examples/Shapes doesn't exist.

Package versions:
```
"native-base": "^2.1.3",
"react": "16.0.0-alpha.6",
"react-native": "0.44.0"
```

It appears that the example folder has been removed from your fork of the module. Adding the missing files from **Shoutem's repo** directly fixed the problem until other modules are added. Then yarn clears the unknown files out.

**Comment by SupriyaKalghatgi** [comment]
@alex-dotdev Please check with [2.1.4](https://github.com/GeekyAnts/NativeBase/releases/tag/v2.1.4)

**Comment by alex-dotdev** [comment]
Looks good thanks
