### ISSUE TITLE
Conditional Style?

### ISSUE THREAD

**Issue by ChiWuSage** [GeekyAnts/NativeBase#835]
How can we do conditional style with Nativebase component?

Here is my code.
`<ListItem onPress={} style={[nativeBaseStyle.notSelected, this.isSelected() && nativeBaseStyle.isSelected]}>
<Text>{rowData.firstName}</Text></ListItem>`

NativeBaseStyle looks like this.
`export default{
    isSelected:{
      backgroundColor: 'blue',
    },
    notSelected:{
      backgroundColor: 'transparent',
    },
}`

It works with React Native component but not NativeBase component.

## react-native, react and native-base version
react-native 0.41.2
native-base 2.0.12
## Expected behaviour
Different style should be loaded base on the condition
## Actual behaviour
Gave me the warnings. 

> Warning: Failed prop type: Invalid prop 'style' of type 'array' supplied to 'Styled(ListItem)', expected 'object'.
## Is the bug present in both ios and android or in any one of them?
Only Tested on Android

**Comment by remo-sk** [comment]
It doen't work for me neither. Looks like NativeBase doesn't support array style format.

**Comment by Jasbir23** [comment]
Hey @ChiWuSage , We are planning to incorporate array style format in newer versions of NativeBase, for now you can use the ES6 as pointed by @remo-sk above.
Thanks :)

**Comment by SupriyaKalghatgi** [comment]
#575

**Comment by shivrajkumar** [comment]
With the latest of NativeBase version 2.3.0. Now all components accepts the styling same way as any other Rn components which include conditional styling

**Comment by msqar** [comment]
@shivrajkumar i'm trying to do ternary condition on ListItem and still throwing me a warning and not working. This is weird.

```
<ListItem
       style={ this.state.locationService ? scopedStyles.disabledProperty : ''}>
       ...
```

Shows warning: Failed prop type: Invalid prop `style` supplied to `Styled(ListItem)`
