### ISSUE TITLE
iPhone 7 Font Scaling

### ISSUE THREAD

**Issue by MoutonJB** [GeekyAnts/NativeBase#839]
Hi guys,

I am using native-base 2.1.3 on react-native 0.44.

When using native-base on an iPhone 6/7 simulator, or on an iPhone 6 device everything is fine and we have no issues with regards to layouts, but once we deploy this to an iPhone 7 device all fonts are almost double in size.

I have used the Kitchen Sink app as a starting point and kept everything as close to the default theme as possible, with a separate style sheet for styling components not related to native-base.  The screenshot is of the List component containing ListItems which uses the default styling provided by native-base.  This renders perfectly on iPhone  6/7 simulators and iPhone 6 device, but on iPhone 7 device all fonts are enlarged.

![img_6759 002](https://cloud.githubusercontent.com/assets/13761634/26225211/5b828092-3c26-11e7-910f-aadb2529dd82.png)

Any guidance as to what the origin of this problem might be would be appreciated.  Most articles I have found regarding font scaling problems, have been mentioning the PixelRatio.get() implementation in react-native, suggesting that that might be the source of the problem.

Thanks in advance

**Comment by SupriyaKalghatgi** [comment]
@MoutonJB We will look into this

**Comment by MoutonJB** [comment]
Hi guys,  we managed to figure this problem out.  The scaling issues was cause why the accessibility settings on the device it self and when turning that off, everything renders as per normal.
