### ISSUE TITLE
Feature Suggestion: Badge Width

### ISSUE THREAD

**Issue by zzimbler** [GeekyAnts/NativeBase#84]
Curious if there was a reason to make the Badge component forced as a 27x27 circle? If not, perhaps it makes sense to change the width from 'width' to 'minWidth' of 27. This would allow longer strings and would be in line with how Bootstrap on the web handles it. My use case is that I have potentially more than single digits that I need show to a user and thus a forced width of 27 is no bueno. I can send a pull request if you'd like!

**Comment by sankhadeeproy007** [comment]
There is no `minHeight` for react-native. Although I've figured out a workaround by putting some horizontal padding around the text. I've pushed the update on `master`. You can use it if you need it urgently.

**Comment by zzimbler** [comment]
I'm not sure I was totally clear on the use case here. I'm aiming to the do the following:

1. Ideal Scenario:

<img width="377" alt="screen shot 2016-07-28 at 1 57 27 am" src="https://cloud.githubusercontent.com/assets/538636/17205129/a8745540-5466-11e6-93f4-b8e9775c1449.png">
or
<img width="367" alt="screen shot 2016-07-28 at 1 56 58 am" src="https://cloud.githubusercontent.com/assets/538636/17205117/97413770-5466-11e6-9598-303d4857a86a.png">

2. How it currently handles long text:

<img width="376" alt="screen shot 2016-07-28 at 1 58 22 am" src="https://cloud.githubusercontent.com/assets/538636/17205161/c93ba544-5466-11e6-8166-5ab9856e1f11.png">
or
<img width="374" alt="screen shot 2016-07-28 at 1 59 07 am" src="https://cloud.githubusercontent.com/assets/538636/17205187/e6140044-5466-11e6-950d-42d5130305b4.png">

I was able to solve 2 by changing the width to minWidth of 27

**Comment by sankhadeeproy007** [comment]
@zzimbler Did you try the code above? It seems to be working fine over here.

**Comment by zzimbler** [comment]
@sankhadddproy007 I didn't see a commit attached to the issue, can you point me to the new commit you did and I'll check it out tomorrow? (It's rather late here in the US and I'm headed to bed)

**Comment by sankhadeeproy007** [comment]
[Here](https://github.com/GeekyAnts/NativeBase/commit/c87a7726ebe10035ce3538f701c4df10e05e7e4f)

**Comment by zzimbler** [comment]
Looks like your solution works well too :thumbsup:
