### ISSUE TITLE
Can't change the value if a default value is entered into the Input component

### ISSUE THREAD

**Issue by pratomchaip** [GeekyAnts/NativeBase#842]
## react-native, react and native-base version
react-native : 0.43.1 
react : 16.0.0-alpha.3
native-base : 2.1.1
... forked from the NativeBase Starter Kit

## Expected behaviour
Should be able to delete/edit the value in the text `Input` component if a default value is given.

## Actual behaviour
Can't delete/edit the value in the `Input` component.
After every keystroke, the value in the Input text box always jumps back to the default value.

## Steps to reproduce (code snippet or screenshot)
```
<Form>
  <Item>
    <Label>Test label</Label>
    <Input
      placeholder="test placeholder"
      value="test"
    />
  </Item>
</Form>
```
## Screenshot of emulator/device
n/a
## Is the bug present in both ios and android or in any one of them?
Tested on Android emulator.

**Comment by SupriyaKalghatgi** [comment]
Not related to NativeBase
Check controlled components and uncontrolled components

**Comment by nikoootine** [comment]
Im having the same problem. Input should still be editable even when there is a default value

**Comment by soleilgl** [comment]
I use TextInput to wrap it, and it works for me.

**Comment by appjitsu** [comment]
@soleilgl can you share your code for this? I have the same issue with not being able to change the text.

**Comment by hafbau** [comment]
@pratomchaip what you want is `defaultValue` not `value`.

As @SupriyaKalghatgi suggested checking up on controlled / uncontrolled components might be helpful.

**Comment by appjitsu** [comment]
Yeah, I eventually figured that out. ;)

**Comment by JeyKeu** [comment]
`nativebase: 2.4.5`
`react: ^16.3.1`
`react-native: ^0.55.3`
````jsx
<Input defaultValue="{defaultValue}"/>
````

shows an emty textbox, whereas it should display the numeric value.
