### ISSUE TITLE
Unresponsive Button in Header

### ISSUE THREAD

**Issue by EgaSetya** [GeekyAnts/NativeBase#847]
So, I'm using side menu or drawer on my current project and I'm using **NativeBase+react-native-router-flux**. Everything works fine, the menu will open at swipe but I just found out that the menu won't open when I tap button that I put on header. I think there is something wrong with my function but After further investigation the button is not responding to tap/press. 

Here is the code for header:
```
<Header style={{backgroundColor: '#f4c542', borderBottomColor: 'transparent'}} hasTabs>
  <Left>
    <Button transparent onPress={()=>Alert.alert("hamburger tapped")}>
      <Icon name='menu' />
    </Button>
  </Left>
  <Body>
    <Title style={{color: '#5b5b5b'}}>HOME</Title>
  </Body>
  <Right />
</Header>
```

and below is my AppNavigation.js structure:
```
<RouterWithRedux>
  <Scene key="modal" component={Modal}>
    <Scene key="root">
      //another scene
    </Scene>
  <Scene key="statusModal" component={StatusModal} />
  </Scene>
            
  <Router key="draw" component={SideMenu} open={false} hideNavBar={true}>
  <Scene key='main' component={Home} hideNavBar={true} />
   </Router>
</RouterWithRedux>
```

How can I make my button work?

**Comment by SupriyaKalghatgi** [comment]
Please check [NativeBase-KitchenSink](https://github.com/GeekyAnts/NativeBase-KitchenSink/blob/master/js/AppNavigator.js) for working example

**Comment by mnlbox** [comment]
@EgaSetya Can you explain how fix your issue?

**Comment by SupriyaKalghatgi** [comment]
@EgaSetya Did you get your app running, referencing NativeBase KitchenSink?

**Comment by EgaSetya** [comment]
@SupriyaKalghatgi Yeah after referencing on NativeBase KitchenSink and some searching, I actually got my app running. Thanks for the help
