### ISSUE TITLE
Unable to style the tabs

### ISSUE THREAD

**Issue by pranay414** [GeekyAnts/NativeBase#848]
![screen shot 2017-05-23 at 1 38 46 pm](https://cloud.githubusercontent.com/assets/16045021/26344418/2dec5910-3fbd-11e7-933d-6becd455f5eb.png)

How do I bring the tabs down like the one shown below?

<img width="297" alt="screen shot 2017-05-23 at 1 39 43 pm" src="https://cloud.githubusercontent.com/assets/16045021/26344460/4fab6050-3fbd-11e7-9cc6-f5b95b169446.png">

**Comment by shivrajkumar** [comment]
@pranay414 http://docs.nativebase.io/Components.html#tabs-def-headref

**Comment by pranay414** [comment]
@shivrajkumar I tried it. The result is the 1st pic.

**Comment by shivrajkumar** [comment]
@pranay414 Can you share code snippet of your use case.

**Comment by pranay414** [comment]
`import React, { Component } from 'react'
import { Container, Header, Title, Button, Left, Right, Body, Icon, Tab, Tabs, Bottom } from 'native-base'
class DashboardNew extends Component {
    render() {
        return (
            <Container>
                <Header hasTabs>
                    <Left>
                        <Button transparent>
                            <Icon name='menu' />
                        </Button>
                    </Left>
                    <Right>
                    <Body>
                        <Title>MY LOADS</Title>
                    </Body>
                    </Right>
                    
                     <Tabs>
                        <Tab heading="Tab1">
                            {/*TODO*/}
                        </Tab>
                        <Tab heading="Tab2">
                            {/*TODO*/}
                        </Tab>
                        <Tab heading="Tab3">
                            {/*TODO*/}
                        </Tab>
                    </Tabs>
                </Header>
            </Container>
        );
    }
}

export default DashboardNew;`

**Comment by pranay414** [comment]
import React, { Component } from 'react'
import { Container, Header, Title, Button, Left, Right, Body, Icon, Tab, Tabs, Bottom } from 'native-base'
class DashboardNew extends Component {
    render() {
        return (
            <Container>
                <Header hasTabs>
                    <Left>
                        <Button transparent>
                            <Icon name='menu' />
                        </Button>
                    </Left>
                    <Right>
                    <Body>
                        <Title>MY LOADS</Title>
                    </Body>
                    </Right>
                    
                     <Tabs>
                        <Tab heading="Tab1">
                            {/*TODO*/}
                        </Tab>
                        <Tab heading="Tab2">
                            {/*TODO*/}
                        </Tab>
                        <Tab heading="Tab3">
                            {/*TODO*/}
                        </Tab>
                    </Tabs>
                </Header>
            </Container>
        );
    }
}

export default DashboardNew;

**Comment by pranay414** [comment]
<img width="1003" alt="screen shot 2017-05-23 at 2 21 23 pm" src="https://cloud.githubusercontent.com/assets/16045021/26346217/2148db24-3fc3-11e7-954c-a6086fd8365b.png">

**Comment by RakhmatovR** [comment]
@pranay414 I guess you should replace your `Tabs` outside of `Header`, e.g to `Content`

**Comment by pranay414** [comment]
@RakhmatovR It worked, one more thing, can we multiple **Content** inside Container component?

**Comment by RakhmatovR** [comment]
@pranay414 I think no, read this [NativeBase Anatomy](http://docs.nativebase.io/Components.html#anatomy-headref)
try to replace `Tabs` between `Header` and `Content`, because `Content` only for content. Your `Tabs` is part of `Header`, I guess

**Comment by pranay414** [comment]
@RakhmatovR Yes tabs are a part of header
