### ISSUE TITLE
Can't create rounded ripple effect for Button in Header

### ISSUE THREAD

**Issue by RakhmatovR** [GeekyAnts/NativeBase#849]
## react-native, react and native-base version
**react-native**: 0.44.0
**react**: 16.0.0-alpha.6
**native-base**: 2.1.4
## Expected behaviour
Button shouldn't resize by adding `rounded` property and should correctly show ripple effect
## Actual behaviour
Button resizes and ripple effect is "square"
## Steps to reproduce
```
<Header>
  <Left style={{ marginLeft: 4, marginRight: -20 }}>
	<Button rounded transparent>
	  <Icon name='menu' />
	</Button>
  </Left>
  <Body>
	<Title>Imports List</Title>
  </Body>
  <Right />
</Header>
```
## Screenshot
![image](https://cloud.githubusercontent.com/assets/12181701/26344630/86f5bf76-3fca-11e7-9bf3-2c2be9576a32.png)
## Expected example
![image](https://cloud.githubusercontent.com/assets/12181701/26344550/408b12c0-3fca-11e7-85fc-967c9d62df50.png)
## Is the bug present in both ios and android or in any one of them?
Tested on Android device.

**Comment by RakhmatovR** [comment]
Similar issue - [[Android] TouchableNativeFeedback's ripples aren't affected by borderRadius](https://github.com/facebook/react-native/issues/6480)

**Comment by rockmacaca** [comment]
I have an incoming fix for this FYI. I'll hopefully be opening a PR later today with some Android-specific button enhancements and theme cleanup.

**Comment by roziy** [comment]
<Header>
                        <Left>                            
                            <View style={{ borderRadius: 50, width: 42, height: 42 }}>
                                <TouchableNativeFeedback 
                                    onPress={() => { this.props.navigation.navigate('DrawerOpen') }}
                                    background={TouchableNativeFeedback.Ripple('#fff', true)}>
                                    <View style={{ width: 42, height: 42, backgroundColor: 'transparent', justifyContent:'center', alignItems:'center',alignSelf:'center'}} >
                                    <Icon name='menu' style={{color:'#fff'}} />
                                    </View>
                                </TouchableNativeFeedback>
                            </View>                            
                        </Left>
                        <Body>
                            <Title>MY APP</Title>
                        </Body>
                        <Right>
                            <Button transparent rounded  >
                                <Icon name='ios-chatbubbles-outline' />
                            </Button>
                        </Right>
                    </Header>

**Comment by SupriyaKalghatgi** [comment]
#1206
