### ISSUE TITLE
State of NativeBase

### ISSUE THREAD

**Issue by cia48621793** [GeekyAnts/NativeBase#850]
It's crystal clear the activity of NativeBase is quickly diminishing, so far there's only one maintainer actively maintaining NativeBase judging from the commit history, what happened to the dev team? Are you guys or us uninterested in NativeBase anymore?

**Comment by sanketsahusoft** [comment]
@cia48621793 We are maintaining it! We are looking into all the issues one-by-one.

Expect many bugs to be resolved this week. And we will be adding more components in the coming weeks for sure.

**Comment by sanketsahusoft** [comment]
Also @cia48621793 to add to it, we have been working on a "new tool" and we hope it will "change the way we develop UI". It's the outcome of several feedback which we received on NativeBase.

But, again, we will also continue to support NativeBase in the long-term.

**Comment by andidev** [comment]
"new tool" a NatovBase replacement? Similar library?

**Comment by lukecwilliams** [comment]
Whoa - would like to see more info here too, until reading this I didn't realize there was some kind of NativeBase 2.0 in the works and in the long term NativeBase will not be the primary product.

@sanketsahusoft Are you able to provide any updated information here?

**Comment by sanketsahusoft** [comment]
@lukecwilliams It is something like this: https://builder.nativebase.io/ but it's in it's early phase.

We were also mentioned in the [Facebook blog](https://facebook.github.io/react-native/blog/2017/06/21/react-native-monthly-1.html) about the same.

**Comment by lukecwilliams** [comment]
@sanketsahusoft That's very interesting - thank you and we'll follow the progress.
