### ISSUE TITLE
Undefined is not an object (evaluating '_reactNative.ViewPropTypes.style')

### ISSUE THREAD

**Issue by Tsouef** [GeekyAnts/NativeBase#851]
Hi, I have an issue with the latest version of nativeBase. 

I'm trying just to add an example in my Application. 

```javascript
import { AppRegistry } from 'react-native'
import React, { Component } from 'react';
import { Container, Header, Title, Content, Footer, FooterTab, Button, Left, Right, Body, Icon } from 'native-base';
​export default class AnatomyExample extends Component {
    render() {
        return (
            <Container>
                <Header>
                    <Left>
                        <Button transparent>
                            <Icon name='menu' />
                        </Button>
                    </Left>
                    <Body>
                        <Title>Header</Title>
                    </Body>
                    <Right />
                </Header>
                <Content>
                    // Your main content goes here
                </Content>
                <Footer>
                    <FooterTab>
                        <Button full>
                            <Text>Footer</Text>
                        </Button>
                    </FooterTab>
                </Footer>
            </Container>
        );
    }
}


AppRegistry.registerComponent('myApp', () => AnatomyExample)
```

My package.json:

```javascript
{
  "name": "myApp",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "lodash": "^4.17.4",
    "native-base": "^2.1.4",
    "react": "16.0.0-alpha.6",
    "react-native": "0.43.4",
    "react-native-camera": "git+https://github.com/lwansbrough/react-native-camera.git",
    "react-native-vector-icons": "^4.1.1",
    "react-navigation": "^1.0.0-beta.9"
  },
  "devDependencies": {
    "babel-jest": "19.0.0",
    "babel-preset-react-native": "1.9.1",
    "jest": "19.0.2",
    "react-test-renderer": "16.0.0-alpha.6"
  },
  "jest": {
    "preset": "react-native"
  }
}
```

![image](https://cloud.githubusercontent.com/assets/18745759/26348625/91d40302-3fad-11e7-9eff-636a2c446334.png)

I'v tried to delete node_modules, cache clean, npm install, not working.

Thanks,

**Comment by Dani93380** [comment]
same

**Comment by RakhmatovR** [comment]
@Tsouef @Dani93380 works perfect for me, try to update `react-native` package to 0.44.0

**Comment by shivrajkumar** [comment]
@Tsouef @Dani93380 View.propTypes is deprecated and instead ViewPropTypes is used from RN44, which is introduced in the latest version of NativeBase as well. So For RN44 got for NativeBase v2.1.4 and anything below RN44, you can use NB v2.1.3

**Comment by Tsouef** [comment]
Thanks, It's working !

**Comment by brascene** [comment]
I'm using RN38 and NB 2.1.3 and still facing this issue, so frustrating... what should I do?

**Comment by SupriyaKalghatgi** [comment]
```
"native-base": "2.1.4",
"react": "16.0.0-alpha.6",
"react-native": "0.44.0",
```
works for me
Also tried this with `RNRF 3.39.2`, got it running

**Comment by matthiasprieth** [comment]
@shivrajkumar i can't upgrade to 0.44.0 because of other dependencies and I'm on 
```
    "native-base": "2.1.0",
    "react": "15.4.1",
    "react-native": "0.42.3",
```
but nothing working so far even with older native-base versions

**Comment by wellmonge** [comment]
I upgrade react-native-router-flux 3.39.0 and get this error, with a simple roll back to version 3.37.0 it works. Could be some related with -v3.39.0 .

**Comment by imcbv** [comment]
@wellmonge thank you! My problem was that in my package.json I was doing:

`"react-native-router-flux": "^3.37.0"`

But that actually fetches the most recent 3.x.x version. Setting the package version explicitly with:

`"react-native-router-flux": "3.37.0"`

Solved my problem.

**Comment by lancebailey79** [comment]
native-base@2.1.0
"react-native": "^0.42.3"
"react": "^15.4.1"
"react-native-router-flux": "3.37.0"

Solved It For ME

**Comment by SupriyaKalghatgi** [comment]
@matthiasprieth In that case, try using older version of RNRF
May be you can check the compatibility versions pf React Native and RNRF

**Comment by SupriyaKalghatgi** [comment]
@wellmonge I got my app running with the latest version of React Native, NativeBase and RNRF
Check my [comment](https://github.com/GeekyAnts/NativeBase/issues/851#issuecomment-304849087)

**Comment by SupriyaKalghatgi** [comment]
@matthiasprieth With the versions specified by you, try installing 3.37.0 of RNRF

**Comment by matthiasprieth** [comment]
@SupriyaKalghatgi thx i got it working by switching to version
```
    "react": "~15.4.1",
    "react-native": "0.42.0",
```
and putting
```
    configurations.all {
        resolutionStrategy {
         eachDependency { DependencyResolveDetails details ->
           if (details.requested.group == 'com.facebook.react' && details.requested.name == 'react-native') {
             details.useVersion "0.42.0" // Your React Native version here
           }
         }
        }
    }
``` 
in `build.gradle`. So i think for me it had nothing to do with RNRF. And for the code in `build.gradle` there is also a dynamic approach on the web, where you don't have to put your react version in it, but i couldn't find it anymore.

**Comment by SupriyaKalghatgi** [comment]
Good to know that you got it working.

**Comment by Talor-A** [comment]
I'm using nativebase 2.1.4 and react-native 44.2.0 and still get this issue. any fix?

**Comment by scotthollandjr** [comment]
For the life of me, I can't solve this issue. I've tried countless different variations of versions for React, RN, RNRF, as well as clearing caches.

Is there anything else that has been effective that I could be missing?

**Comment by shivrajkumar** [comment]
@scotthollandjr Can you post your package.json here

**Comment by scotthollandjr** [comment]
```
"firebase": "3.6.8",
"lodash": "^4.17.4",
"react": "15.4.2",
"react-native": "0.41.1",
"react-native-maps": "git+https://github.com/airbnb/react-native-maps.git",
"react-native-router-flux": "^3.37.0",
"react-native-vector-icons": "4.0.0",
"react-redux": "5.0.2",
"redux": "3.6.0",
"redux-thunk": "2.2.0"
```

This was the most recent setup before the error occurred

**Comment by shivrajkumar** [comment]
@scotthollandjr And the version of `native-base`?

**Comment by scotthollandjr** [comment]
@shivrajkumar I didn't have `native-base`, but when attempting different package versions I added it at `2.1.0`

**Comment by shivrajkumar** [comment]
@scotthollandjr `native-base` v2.1.0 should work fine with the above mention versions of react and react-native.

**Comment by shivrajkumar** [comment]
And as for your issue, that is of `react-native-router-flux`, the latest of RNRF i.e, v3.39.1 is for RN44 and you are using RN41. Remove `^` from 3.37.0 of RNRF. That will resolve your issue.

**Comment by scotthollandjr** [comment]
@shivrajkumar 
These are my current versions and I'm still having the issue:
```
"react": "15.4.2",
"native-base": "2.1.0",
"react-native": "0.41.1",
"react-native-router-flux": "3.37.0",
```

I deleted node_modules and reinstalled, deleted the app from the simulator, cleared DerivedData from xcode, and `npm start -- --reset-cache`. I don't know what I'm missing

**Comment by shivrajkumar** [comment]
@scotthollandjr Did upgrade the app after changing RN version?

**Comment by scotthollandjr** [comment]
@shivrajkumar upgrade how?

**Comment by shivrajkumar** [comment]
`react-native upgrade` https://facebook.github.io/react-native/docs/upgrading.html

**Comment by scotthollandjr** [comment]
@shivrajkumar Yes, same result

**Comment by shivrajkumar** [comment]
@scotthollandjr This issue arises when you are using any package compatible for RN44 and you are using RN<44.
So do check other packages that you are using. May be `react-native-maps`.

**Comment by jiteshwadia** [comment]
Package.json contains:
    "prop-types": "^15.5.8",
    "react": "16.0.0-alpha.6",
    "native-base": "2.1.4",
    "react-native": "^0.44.0",
    "react-native-router-flux": "^3.37.0",


Did, 
watchman watch-del-all
rm -rf node_modules && npm install
rm -fr $TMPDIR/react-*
npm start -- --reset-cache

But still getting error.

**Comment by scotthollandjr** [comment]
@jiteshwadia Remove `^` from RNRF and upgrade to latest version, this in combination with the cache clearing solved the problem for me

**Comment by brascene** [comment]
@jiteshwadia make sure that you also have installed that react version globally:
npm install react@16.0.0-alpha.6 -g

**Comment by SorooshPardazCompany** [comment]
use clear cash and upgrade your RN version 

[برنامه نویسی اندروید و ios](https://sorooshpardaz.com/mobile-app-android-ios-programming)

**Comment by ArtixZ** [comment]
It's **react-native-router-flux** issue. I did npm install, and I got the newer version for that. 
And then I rolled it back to the version specified in package.json, that is v3.35.0, and it's working fine now.

**Comment by haifaGh** [comment]
guys i'm having the same problem and i can't upgrade since i have other dependencies .. so what should i do ? thanks 
<img width="399" alt="screen shot 2017-07-02 at 21 12 32" src="https://user-images.githubusercontent.com/15948361/27773153-48d8de4c-5f6b-11e7-8d51-58d48d6e2e93.png">

**Comment by rhomnickcoloma** [comment]
Hello! Guys I've Been reading this thread because i also encountered the same issue. Here's what i did,

Current XCode Version = 8.3.3

i removed the /node_modules folder and installed new with these versions

"react": "16.0.0-alpha.6"
"react-native": "0.44.0"
"babel-jest": "20.0.3"
"babel-preset-react-native": "2.0.0"

(Note: This is step is very important)
and don't forget to restart the server like so 
`node node_modules/react-native/local-cli/cli.js start -- --reset-cache`
then rebuild. for instance
`react-native run-<platform>`

Hope this helps.

**Comment by adriaanvanrossum** [comment]
For me the issue was a typo, I typed this

```js
View.PropTypes.style
```

instead of (what is needs to be):

```js
View.propTypes.style
```

**Comment by jeremyfrancis** [comment]
ViewStylePropTypes must be used now. I changed them all manually and that worked but it gives me a lot of warnings.

**Comment by andersondecarvalho** [comment]
Install version:   npm i --save lottie-react-native@1.1.1

**Comment by parthgandhi7** [comment]
Just make a search for `View.propTypes.style` in your node_modules folder and you would come to know which module has the issue. You would then have to use the updated version of that module if they have fixed it or you would need to find an alternative. In my case , [rn-viewpager](https://github.com/zbtang/React-Native-ViewPager) was creating this issue. So, i used [the workaround suggested here](https://github.com/zbtang/React-Native-ViewPager/issues/92) for solving the issue , as the fix for this issue hasn't been merged yet (as of this writing).

**Comment by ngoducduy** [comment]
I use nativebase on "react-native": "0.50.4" and have same issue, Somebody help me !
thanks

**Comment by shubhanshusingh** [comment]
- check for packages having this!
grep -R "View.propTypes" node_modules 
 

- then, go to https://github.com/reactjs/react-codemod#reactnative-view-proptypes 
- install package and upgrade that package by providing path to those node-modules by running the script provided

for ex. jscodeshift -t react-codemod/transforms/ReactNative-View-propTypes.js node_modules/rn-viewpager/

@ngoducduy

**Comment by sangdesigner** [comment]
App is Crashing on open checking updates then crash

{
  "name": "poc1",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
  
    "react": "16.3.1",
    "react-native": "0.55.4",
    "react-native-auto-updater": "^0.2.5",
    "react-native-exception-handler": "^2.7.5",
    "react-navigation": "^2.0.1"
  
  },
  "devDependencies": {
    "babel-jest": "22.4.3",
    "babel-preset-react-native": "4.0.0",
    "jest": "22.4.3",
    "react-test-renderer": "16.3.1"
  },
  "jest": {
    "preset": "react-native"
  }
}
