### ISSUE TITLE
<Text> not rendering on iphone 6+ when wrapped in <Body>

### ISSUE THREAD

**Issue by pukeanddie** [GeekyAnts/NativeBase#854]
react-native 0.44 & native-base 2.1.3

The following code works as expected when running on an iphone 6, but not on an iphone 6+. On the 6+ the text does not render. In the layout inspector within xCode it appears that the RCText view has a rect of 0,0,0,0. 

As a row in a `<ListView />` with each row as
```
<Card>
     <CardItem>
          <Body>
               <Text>Does Not Render on Iphone 6+, Rect is 0,0,0,0</Text>
          </Body>
     </CardItem>
</Card>
```
All components are imported from native-base. If I remove the `<Body>` tag from the JSX example above the `<Text>` component renders properly on a 6+.

**Comment by sankhadeeproy007** [comment]
Fixed with 2.1.5
