### ISSUE TITLE
Adjust drawer opacity 

### ISSUE THREAD

**Issue by pranay414** [GeekyAnts/NativeBase#855]
Hi,
How do I set the drawer opacity?
I am having something like this.
<img width="252" alt="screen shot 2017-05-24 at 11 16 43 am" src="https://cloud.githubusercontent.com/assets/16045021/26388536/82aeab00-4072-11e7-9b85-749c9f0a7220.png">

I want something like this.
<img width="279" alt="screen shot 2017-05-24 at 11 17 18 am" src="https://cloud.githubusercontent.com/assets/16045021/26388551/9626c12c-4072-11e7-9e2c-36927db2dc65.png">

**Comment by SupriyaKalghatgi** [comment]
@pranay414 You can check [NativeBase-KitchenSink](https://github.com/GeekyAnts/NativeBase-KitchenSink) for same
Here's the code for [Drawer](https://github.com/GeekyAnts/NativeBase-KitchenSink/blob/master/js/components/sidebar/index.js) used

**Comment by pranay414** [comment]
@SupriyaKalghatgi Thanks, this will do my job 👍
