### ISSUE TITLE
Rendering multiple card button inside a list

### ISSUE THREAD

**Issue by pranay414** [GeekyAnts/NativeBase#856]
Hi, I am trying to Render multiple card button inside ListItem. I am not sure with my implementation. Can someone help me what I am doing wrong?

<img width="244" alt="screen shot 2017-05-24 at 5 50 07 pm" src="https://cloud.githubusercontent.com/assets/16045021/26402832/7396f370-40a9-11e7-90ef-714f465b4c44.png">

`import React, { Component } from 'react'
import { Actions } from 'react-native-router-flux'
import { Container, Header, Title, Button, Left, Right, Body, Tab, Tabs, Bottom, Content, Card, CardItem, Text, Drawer, List, ListItem } from 'native-base'
import SideBar from '../components/Sidebar'
import View from 'react-native'
import Accordion from 'react-native-collapsible/Accordion'
import Icon from 'react-native-vector-icons/MaterialCommunityIcons'

class DashboardNew extends Component {

    render() {
        var items = ['Delhi','Mumbai','Kolkata','Chennai'];

        return (
            <Drawer
              ref={(ref) => { this.drawer = ref; }}
              opacity={1}
              content={<SideBar navigator={this.navigator} />}
              onClose={() => this.drawer._root.close()} >
            <Container>
                <Header>
                    <Left>
                        <Button transparent onPress={() => {this.drawer._root.open()}}>
                            <Icon name='menu' size={24} color='#ffffff' />
                        </Button>
                    </Left>
                    <Body>
                        <Title>My Loads</Title>
                    </Body>
                    <Right/>
                </Header>
                <Tabs intialPage={0}>
                        <Tab heading="Current">
                            {/*TODO--> Rendering multiple Card buttons*/}
                            <Container>
                            <Content>
                            <List dataArray={items}
                                renderRow={(item) =>
                                <ListItem>
                                   <Container>
                <Content>
                    <Card>
                    <CardItem button>
                       <Text style={{fontSize:16,fontWeight:'bold'}}>{item}</Text>
                       <Right>
                           <Icon name="truck-fast" size={24} />
                          <Text note style={{fontSize:16}}>2</Text>
                       </Right>
                     </CardItem>
                   </Card>
                </Content>
            </Container>
                                </ListItem>
                                }>
                                </List>
                             </Content>
                         </Container>
                        </Tab>
                        <Tab heading="Delivered">
                            {/*TODO*/}
                            <Container>
                            <Content>
                            <List dataArray={items}
                                renderRow={(item) =>
                                <ListItem>
                                    <Text style={{fontWeight:'bold'}}>Order #</Text>
                                    <Text style={{paddingLeft:5,fontStyle:'italic'}}>23445</Text>
                                    <Body>
                                        <Text style={{fontWeight:'bold',fontSize:16}}>{item}</Text>
                                    </Body>
                                    <Text note>12/05/17{"\n"}3:43pm</Text>
                                </ListItem>
                                }>
                                </List>
                             </Content>
                         </Container>
                        </Tab>
                </Tabs>
            </Container>
            </Drawer>
        );
    }
}

export default DashboardNew;`

**Comment by pranay414** [comment]
I figured a way to do it, just remove the **Container** tags inside the tabs and then we're done.

**Comment by SupriyaKalghatgi** [comment]
@pranay414 Good to know that you got it working
