### ISSUE TITLE
Warning: Accessing PropTypes on React Native 44

### ISSUE THREAD

**Issue by ZevenFang** [GeekyAnts/NativeBase#861]
`Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.`

Here is what I import:

`import {View, Text} from 'native-base'`

NativeBase 2.1.4
React Native 0.44.0
I guess it is caused by [this](https://github.com/GeekyAnts/NativeBase/blob/master/src/basic/Text.js#L22-L24).

**Comment by SupriyaKalghatgi** [comment]
@ZevenFang What is the version of React you are on?

**Comment by ZevenFang** [comment]
16.0.0-alpha.6

**Comment by shivrajkumar** [comment]
@ZevenFang Can you share your package.json

**Comment by ZevenFang** [comment]
```
{
  "name": "my-app",
  "version": "0.1.0",
  "devDependencies": {
    "jest-expo": "^1.0.0",
    "react-native-scripts": "0.0.29",
    "react-test-renderer": "16.0.0-alpha.6"
  },
  "main": "./node_modules/react-native-scripts/build/bin/crna-entry.js",
  "scripts": {
    "start": "react-native-scripts start",
    "eject": "react-native-scripts eject",
    "android": "react-native-scripts android",
    "ios": "react-native-scripts ios",
    "test": "node node_modules/jest/bin/jest.js"
  },
  "jest": {
    "preset": "jest-expo",
    "transformIgnorePatterns": [
      "/node_modules/(?!native-base)/"
    ]
  },
  "dependencies": {
    "@expo/ex-navigation": "^3.0.0",
    "@expo/vector-icons": "^4.1.1",
    "dva": "^1.2.1",
    "expo": "^17.0.0",
    "native-base": "^2.1.4",
    "react": "16.0.0-alpha.6",
    "react-dom": "^15.0.0",
    "react-native": "^0.44.0"
  }
}
```

**Comment by ZevenFang** [comment]
Here is my [repo](https://github.com/ZevenFang/react-native-starterkit).

**Comment by SupriyaKalghatgi** [comment]
@ZevenFang Can you got to your `node_modules` and check for React Native's version?

**Comment by ZevenFang** [comment]
Yes, it's 0.44.0.
![image](https://cloud.githubusercontent.com/assets/11134329/26482194/957be8fe-4218-11e7-98a8-2ff0fc27adf3.png)

**Comment by SupriyaKalghatgi** [comment]
@ZevenFang Just a try,
Re-install `node_modules`

**Comment by ZevenFang** [comment]
I try to install with npm, and it works. But it doesn't work with yarn.

**Comment by narup** [comment]
I am running into this same issue! Tried everything, still broken

**Comment by SupriyaKalghatgi** [comment]
@ZevenFang You can check your `yarn.lock` file for this, in case you have older versions of dependencies

**Comment by ZevenFang** [comment]
My [yarn.lock](https://github.com/ZevenFang/react-native-starterkit/blob/master/yarn.lock#L3833-L3850)

**Comment by SupriyaKalghatgi** [comment]
@ZevenFang I tried installing using the `package.json` provided by you, by `yarn`
It works fine

**Comment by ZevenFang** [comment]
It prints error when I run [test](https://travis-ci.org/ZevenFang/react-native-starterkit/builds/238171291#L288-L292) on travis.

**Comment by ZevenFang** [comment]
I find a solution [here](https://stackoverflow.com/questions/43302963/how-to-fix-react-15-5-3-proptypes-deprecated-warning-when-using-create-react-app).

**Comment by SupriyaKalghatgi** [comment]
@ZevenFang Seems that its not because of NativeBase

**Comment by ZevenFang** [comment]
It may caused by NativeBase.
![image](https://cloud.githubusercontent.com/assets/11134329/26679862/7417f626-4709-11e7-8392-03e60a8929fe.png)

**Comment by ZevenFang** [comment]
Accessing PropTypes here directly.
![image](https://cloud.githubusercontent.com/assets/11134329/26679954/e679de8c-4709-11e7-8b8b-dccba184d00b.png)

**Comment by sankhadeeproy007** [comment]
Yes, looks like an issue with NativeBase cc @shivrajkumar

**Comment by sankhadeeproy007** [comment]
Fixed with 2.1.5

**Comment by ZevenFang** [comment]
Thank you very much.

**Comment by tokland** [comment]
I was seeing the warning on the JS console (origin: node_modules/native-base-shoutem-theme/src/StyleProvider.js), so I made a quick and dirty search to see other occurrences. That's what I got:

```
$ grep -r "import.*\<PropTypes\>.*react" node_modules/**/src/** 
node_modules/native-base-shoutem-theme/src/connectStyle.js:import React, { PropTypes } from 'react';
node_modules/native-base-shoutem-theme/src/StyleProvider.js:import React, { Children, PropTypes } from 'react';
node_modules/native-base/src/basic/SwipeRow.js:import React, { Component, PropTypes } from 'react';
node_modules/native-base/src/basic/Swipe/index.js:import React, { Component, PropTypes } from "react";
node_modules/native-base/src/basic/Swipe/NativeButton.js:import React, { PropTypes } from "react";
```
[yarn.lock.txt](https://github.com/GeekyAnts/NativeBase/files/1117332/yarn.lock.txt)

[package.json.txt](https://github.com/GeekyAnts/NativeBase/files/1117336/package.json.txt)


[package.json.txt](https://github.com/GeekyAnts/NativeBase/files/1117335/package.json.txt)
