### ISSUE TITLE
What is best practice for using ScrollView with Deckswiper? What is best practice for card navigation (back) with Deckswiper

### ISSUE THREAD

**Issue by SupriyaKalghatgi** [GeekyAnts/NativeBase#867]
When use ScrollView with deckswiper, swipe gesture override Scroll gesture so it is very hard to Scroll. 
Also not clear with new version of DeckSwiper what is best method for implementing previous card on swipeleft?

Ref: [NativeBase Forum](http://discuss.nativebase.io/t/what-is-best-practice-for-using-scrollview-with-deckswiper-what-is-best-practice-for-card-navigation-back-with-deckswiper/223)

**Comment by SupriyaKalghatgi** [comment]
ScrollView scrolls the screen content vertically, whereas Deck Swiper scrolls it horizontally
So ScrollView shouldn't be used with Deck Swiper

**Comment by SupriyaKalghatgi** [comment]
If you want to do so, you can put up both the things in two different layers

**Comment by deepakdroidgeek23** [comment]
@SupriyaKalghatgi  how it can be done with different layers?
