### ISSUE TITLE
Captcha or reCaptcha for react-native

### ISSUE THREAD

**Issue by SupriyaKalghatgi** [GeekyAnts/NativeBase#868]
Ref: [NativeBase Forum](http://discuss.nativebase.io/t/captcha-or-recaptcha-for-react-native/400/1)

**Comment by DavitVosk** [comment]
is there any update re this?

**Comment by sanketsahusoft** [comment]
I don't think we are going to include this. NativeBase would only focus on UI and presentational components with no business logic.

**Comment by sanketsahusoft** [comment]
If we get a chance, we might publish it as a separate package though.

**Comment by DavitVosk** [comment]
is there any hope to be done these days? I need to use captcha in my RN app and as I see there is no any choise to do it as of today..

**Comment by karsens** [comment]
I need this....
