### ISSUE TITLE
If i need add a custom icon that i designed, ¿How i can add in the tab <Icon>?

### ISSUE THREAD

**Issue by SupriyaKalghatgi** [GeekyAnts/NativeBase#870]
Ref: [NativeBase Forum](http://discuss.nativebase.io/t/hi-if-i-need-add-a-custom-icon-that-i-designed-how-i-can-add-in-the-tab-icon/345)

**Comment by cristiankmb** [comment]
i have the same question... For now my app work with the default icon from **ionicons** on android, but  in iOS i using footer tabs, this allow me add custom icons for tab.

**Comment by Jasbir23** [comment]
Tried using custom Icons from [react-native-vector-icons](https://github.com/oblador/react-native-vector-icons). I placed these icons in the [NativeBase TabHeading](http://docs.nativebase.io/Components.html#advanced-tabs-headref). Everything seems to be working fine.

**Comment by ptaking** [comment]
@Jasbir23 I think OP means custom icon in a custom `.ttf` file. I'm having the same question.

**Comment by egeniegithub** [comment]
I need to use my .png icon in Tabheading

**Comment by akhil-geekyants** [comment]
@egeniegithub tried a sample code

Code
```
import React, { Component } from 'react';
import { Image } from "react-native";
import { Container, Header, Tab, Tabs, TabHeading, Icon, Text } from 'native-base';
export default class App extends Component {
  render() {
    return (
      <Container>
        <Header hasTabs />
        <Tabs>
          <Tab heading={<TabHeading><Image resizeMode="contain" style={{ flex: 1 }}
            source={require('./icon.png')}
          /></TabHeading>}>
            <Text>Tab one</Text>
          </Tab>
          <Tab heading={<TabHeading><Text>No Icon</Text></TabHeading>}>
            <Text>Tab two</Text>
          </Tab>
          <Tab heading={<TabHeading><Icon name="apps" /></TabHeading>}>
            <Text>Tab three</Text>
          </Tab>
        </Tabs>
      </Container>
    );
  }
}
```
![simulator screen shot - iphone 6 - 2018-05-16 at 11 39 26](https://user-images.githubusercontent.com/27768184/40099520-0154d75a-58fe-11e8-8116-fbaa89b23c3a.png)

**Comment by JakinTayo** [comment]
How do you change the color of the tab

**Comment by cristiankmb** [comment]
> How do you change the color of the tab

@JakinTayo  User the TabStyle Property you can see more from: https://docs.nativebase.io/Components.html#tabs-def-headref
