### ISSUE TITLE
Need Searchbar along with Header's Title and Icons

### ISSUE THREAD

**Issue by SupriyaKalghatgi** [GeekyAnts/NativeBase#876]
![screen shot 2017-05-25 at 4 33 57 pm](https://cloud.githubusercontent.com/assets/13464885/26447881/38e5ea64-4168-11e7-8790-d2f0f06b36ac.png)

Something like this

Ref: [NativeBase Slack](https://nativebase.slack.com/files/justinjoyn/F5HLN13UK/room-services.png)

**Comment by shivrajkumar** [comment]
https://nativebase.slack.com/files/justinjoyn/F5HLN13UK/room-services.png
