### ISSUE TITLE
FAB - Transparent - Opacity - Move

### ISSUE THREAD

**Issue by gustavoadt** [GeekyAnts/NativeBase#879]
## react-native, react and native-base version
**0.43**
## Expected behaviour
**See text through FAB and Move FAB**
## Actual behaviour
**Can't change opacity/transparency with ease. Can't move the FAB**
## Is the bug present in both ios and android or in any one of them?
**Android tested**
## Any other additional info which would help us debug the issue quicker.

Hello there,

I want to change the _opacity_ of my _FAB_ but I have to repeat for each button it contains and still the colors appear wrong, because of the necessary icon (props[0]) and positioning. Also, I would like to _move it around_, is it possible?

The FAB is blue, let's say I want it to be green but almost invisible, so the user can read what it is behind it. Also, move it would be a nice option.

Thanks in advance.

**Comment by SupriyaKalghatgi** [comment]
#881

**Comment by shivrajkumar** [comment]
Check the latest version 2.2
