### ISSUE TITLE
Scrolling with active keyboard can leave status-bar sized gap

### ISSUE THREAD

**Issue by ronaldheft** [GeekyAnts/NativeBase#88]
1. Open up the keyboard in an `Input` component
2. Scroll the view down
3. Notice the stuck gap at the top
4. Close keyboard
5. Gap remains until scrolling again, and it's possible to get the scrollview stuck again without opening the keyboard

<img width="487" alt="screen_shot_2016-07-29_at_5_57_47_pm" src="https://cloud.githubusercontent.com/assets/1143112/17264682/a58872f2-55b6-11e6-8c8f-976ba902fd9c.png">

**Comment by sankhadeeproy007** [comment]
Could you just try out the solution given [here](https://github.com/APSL/react-native-keyboard-aware-scroll-view/issues/45)?

**Comment by ronaldheft** [comment]
Yes, that resolves the issue if I place `contentInset={{bottom: 0}}` on `<Content>`. Is there a particular reason this is happening, or do I need to remember to place that on any view containing a keyboard?

**Comment by sankhadeeproy007** [comment]
It seems to be an issue with [react-native-keyboard-aware-scroll-view](https://github.com/APSL/react-native-keyboard-aware-scroll-view). Looks like it'll have to be used in all the pages with Input.
