### ISSUE TITLE
Animation Fixes & FAB

### ISSUE THREAD

**Issue by SupriyaKalghatgi** [GeekyAnts/NativeBase#881]

**Comment by shivrajkumar** [comment]
Fixed in latest version 2.2

**Comment by shuffgy** [comment]
What do I have to do, to make it work? The is no animation with 2.2.0 after i updated from 2.1.5.

I was looking for something like here in the material design guidelines:

https://storage.googleapis.com/material-design/publish/material_v_11/assets/0B8v7jImPsDi-ZmQ0UnFPZmtiSU0/components-buttons-fab-transition_speeddial_02.mp4

**Comment by cyclops24** [comment]
I think it's need more doc about FAB.
