### ISSUE TITLE
ListView Swipe

### ISSUE THREAD

**Issue by SupriyaKalghatgi** [GeekyAnts/NativeBase#883]

**Comment by shivrajkumar** [comment]
Added in version 2.2.0

**Comment by namnv16** [comment]
@shishircc @SupriyaKalghatgi 
I get error when using Swipeable List in https://docs.nativebase.io/Components.html#Spinner
Error messsage: Json.stringify cannot serialize cylic structures.
Below is my source code:
lass Cart extends Component {
    static navigationOptions = {
        header: null
    };

    constructor(props) {
        super(props);
        this.ds = new ListView.DataSource({ rowHasChanged: (r1, r2) => r1 !== r2 });
        this.state = {
            basic: true,
            listViewData: this.ds.cloneWithRows(['row 1', 'row 2']),
        };
    }

    deleteRow(secId, rowId, rowMap) {
        rowMap[`${secId}${rowId}`].props.closeRow();
        const newData = [...this.state.listViewData];
        newData.splice(rowId, 1);
        this.setState({ listViewData: newData });
    }

    render() {
        return (
            <Container>
                <Header>
                    <Body>
                        <Title>Giỏ hàng</Title>
                    </Body>
                </Header>
                <Content>
                    <List
                        dataSource={this.state.listViewData}
                        leftOpenValue={75}
                        rightOpenValue={-75}
                        renderRow={data =>
                            <ListItem>
                                <Text>{data}</Text>
                            </ListItem>
                        }
                        renderLeftHiddenRow={data =>
                            <Button info onPress={() => alert(data)}>
                                <Icon active name="information-circle" />
                            </Button>
                        }
                        right={
                            <Button danger onPress={_ => this.deleteRow(secId, rowId, rowMap)}>
                                <Icon active name="trash" />
                            </Button>
                        }
                    />
                </Content>
                <Footer4VGO {...this.props} />
            </Container>
        );
    }
}

**Comment by shivrajkumar** [comment]
@namnv16 Check #1096 for this
