### ISSUE TITLE
stackedLabel/inlineLabel support for Picker

### ISSUE THREAD

**Issue by Trenrod** [GeekyAnts/NativeBase#89]
Currently Picker can be used as ListItem but cannot add a label.

**Comment by sankhadeeproy007** [comment]
@Trenrod can tell me what exactly your use case is and how you want it to look?

**Comment by ericvan76** [comment]
I'm not sure whether my one is the same issue, try to make a form with following fields: 

- Name (A TextInput with a Icon and Label)
- Gender (A ListItem with a Icon and Label, and click it will show Picker)
- Other Switches or CheckBoxes with Icon and Label

It is very difficult to make them in a same list with same styles. 

To simplify the question, how can I use a picker with a form? the picked value should be displayed as the same style of the TextInput.

**Comment by SupriyaKalghatgi** [comment]
@ericvan76 You can check the demonstration of [Form](https://github.com/GeekyAnts/NativeBase-KitchenSink/blob/master/js/components/form/index.js) in [NativeBase-KitchenSink](https://github.com/GeekyAnts/NativeBase-KitchenSink)
