### ISSUE TITLE
Can I use <View> tag inside the <Container> tag or vice versa ? 

### ISSUE THREAD

**Issue by harrybhadana** [GeekyAnts/NativeBase#90]

**Comment by sankhadeeproy007** [comment]
Yes.

**Comment by harrybhadana** [comment]
http://strapmobile.com/docs/react-native-ecommerce-starter/v4.0.0/components#picker 
I am using the first picker . ie. 
 <Picker
                        mode="dropdown"
                        selectedValue={this.state.selected_value}
                        onValueChange={function_call()}>
                        <Item label="Net Banking" value="pay1" />
                        <Item label="Debit/Credit Card" value="pay2" />
                        <Item label="Cash on Delivery" value="pay3" />
                    </Picker>

LandingPage.js 

'use strict'
var React= require('react');
var ReactNative = require('react-native');
var {
	View,
	Text,
	Image,
	StyleSheet,
	TouchableHighlight,
	Dimensions,Picker
}= ReactNative;

 var deviceWidth = Dimensions.get('window').width; //full width
 var width=deviceWidth-50;
 import { Container, Content } from 'native-base';
const Item = Picker.Item;

class LandingPage extends React.Component{

constructor(props) {
			 		super(props);
			 		this.state = { selected_value:'pay2'};

			 	}


press(){
		console.log("hiii");
	}
	render(){

	return(

<View style={styles.imageContainer}>
	<Image style={styles.backgroundImage} source={require('./images/Dobble.png')}/>
		<View style={styles.container}>

		<Picker
                        mode="dropdown"
                        selectedValue={this.state.selected_value}
                        onValueChange={this.press}>
                        <Item label="Net Banking" value="pay1" />
                        <Item label="Debit/Credit Card" value="pay2" />
                        <Item label="Cash on Delivery" value="pay3" />
                    </Picker>

			<TouchableHighlight
			style={ [styles.button ,styles.googleColor]}>
			<Text style={styles.font }> Log in with Google</Text>
			</TouchableHighlight>

			<TouchableHighlight
			style={ [styles.button ,styles.fbColor]}>
			<Text style={styles.font}>Log in with Facebook</Text>
			</TouchableHighlight>

			<TouchableHighlight
			style={ [styles.button ,styles.registerColor]}>
			<Text style={styles.font}> Register Now</Text>
			</TouchableHighlight>

			<TouchableHighlight 
			underlayColor="gray"
			onPress={this.press}>
			<Text style={[styles.underlineText,styles.font]}> Sign in here </Text>
			</TouchableHighlight>

		</View>

		</View>

	//


	);


	}
};

Picker should appear at the top of "Login with google" button , but it is not appearing in simulator. 
![simulator screen shot 01-aug-2016 7 25 29 pm](https://cloud.githubusercontent.com/assets/14834863/17296234/c0df5e26-581d-11e6-96cd-0beb34f8e63a.png)

**Comment by sankhadeeproy007** [comment]
You're checking the wrong documentation. Please see [here](http://nativebase.io/docs/v0.5.2/components#picker) for `native-base` Picker.

**Comment by harrybhadana** [comment]
yeah , I was checking the wrong the documentation . 
But the problem here is if I make the independent picker file , and include it in index.ios.js it works fine but when i try to include it in my page as you can see in the screenshot (i put the picker above the first button , it is not showing )

so the previous document was showing the "react-native picker" and the one you suggested is showing "Native-base"  picker . 
but please tell me how can i make sure that it shows on my screen above the "Login with Google" button .

**Comment by sankhadeeproy007** [comment]
You can try styling your Picker element, giving it some width/height. That might help. This is not a native-base issue, so stack-overflow might be a better place for this question.
