### ISSUE TITLE
How to optimize the app bundle size?

### ISSUE THREAD

**Issue by SupriyaKalghatgi** [GeekyAnts/NativeBase#900]
What's the best way of optimizing the app bundle size when using NativeBase?

The biggest issue is the fonts, I'm not (at least explicitly) using any of them, aside from Ionicons, so there's potentially 9 megabytes of fonts being included that I don't use in my app.

Oh, and including the San Francisco font in the Android build is explicitly against the terms of the font license (and including it with the iOS build is unnecessary at best, and possible against the terms of the license too).

```
IMPORTANT NOTE: THE APPLE SAN FRANCISCO FONT IS TO BE USED SOLELY FOR CREATING MOCK-UPS OF USER INTERFACES TO BE USED IN SOFTWARE PRODUCTS RUNNING ON APPLE’S iOS, OS X OR tvOS OPERATING SYSTEMS, AS APPLICABLE.
```

Ref: [NativeBase Forum](http://discuss.nativebase.io/t/how-to-optimise-the-app-bundle-size/442)

**Comment by sankhadeeproy007** [comment]
Fixed with [this commit](https://github.com/GeekyAnts/NativeBase/commit/5cddf34ac541dd51beaf7ce0c0669ecf9fda8a66)
