### ISSUE TITLE
Cannot style CheckBox component in TSX files, attribute not present.

### ISSUE THREAD

**Issue by darkyelox** [GeekyAnts/NativeBase#901]
Hi, i'm using native-base for learning to use react-native and typescript together but i notice some problem using the CheckBox component because i can't style it using the `style` attribute in my tsx files, so i go to the index.d.ts and i notice that the CheckBox interface is not extending `ReactNative.TouchableOpacityProperties` so  i cannot style this component using TypeScript.

- react 16.0.0-alpha.6
- react-native 0.44.0
- native-base ^2.1.4
- Expected behavior:  styling the CheckBox component in TSX files
- Actual Behavior: CheckBox component not extends ReactNative.TouchableOpacityProperties in the index.d.ts file so cannot be styled in TSX files.
- Reproduce: create a react-native project and configure it using typescript, create a root component using TSX extension and try to use style attribute in a CheckBox component.
- Screenshots:
![image](https://cloud.githubusercontent.com/assets/8183191/26586322/750a430a-4514-11e7-8162-ee8bbde7c24f.png)
![image](https://cloud.githubusercontent.com/assets/8183191/26586485/e8aeba98-4514-11e7-96f4-b5fdf02cec3f.png)
![image](https://cloud.githubusercontent.com/assets/8183191/26586642/6aafb178-4515-11e7-848a-126efa2d72a0.png)

**Comment by SupriyaKalghatgi** [comment]
#667
