### ISSUE TITLE
Dark Theme

### ISSUE THREAD

**Issue by jennykortina** [GeekyAnts/NativeBase#902]
I have seen a "dark theme" mentioned in issues but cannot find it.  I want my app to have a dark background and light font.  What is the best way to achieve this?

**Comment by SupriyaKalghatgi** [comment]
@jennykortina You can check the docs for [Customizing theme](https://docs.nativebase.io/Customize.html#theaming-nb-headref) and set your color context accordingly

**Comment by jennykortina** [comment]
@SupriyaKalghatgi thanks I had already read all of that.  How do you change the background of the whole app from white to black?  Thanks!

**Comment by SupriyaKalghatgi** [comment]
@jennykortina Thats not possible in one step
We may consider it in future
But now, you need to change the color context component wise for your theme

**Comment by chaitanya0bhagvan** [comment]
@jennykortina @SupriyaKalghatgi Switching theme at runtime is quite simple. Here are the steps

1. Create two themes, Light and Dark, you can modify one of the files in native-base/variables/*.
2. Switch the theme passed to StyleProvider getTheme in runtime.
3. This above is dependent on a fix that I have proposed in this bug [Changing theme is not propagated to connectedComponents](https://github.com/GeekyAnts/NativeBase/issues/910).

Take a look at this repo to see it in action [repo](https://github.com/chaitanya0bhagvan/issue-theme-not-propagated.git)

**Comment by SupriyaKalghatgi** [comment]
@chaitanya0bhagvan Yes i know that
@jennykortina question was about changing the theme of app with NativeBase's theme, i.e., 
as you said `Create two themes, Light and Dark, you can modify one of the files in native-base/variables/*`, if this was readily available

**Comment by chaitanya0bhagvan** [comment]
@SupriyaKalghatgi did you mean creating those two files will take some effort?

**Comment by chaitanya0bhagvan** [comment]
@SupriyaKalghatgi could you also take a look at this [bug](https://github.com/GeekyAnts/NativeBase/issues/910). I am not able to find the source for native-base-shoutem-theme otherwise I could have sent a pull request.

**Comment by SupriyaKalghatgi** [comment]
@chaitanya0bhagvan Creating copy of those theme files is not just that
If you want a dark theme for your app, then the color context of all the components should match accordingly

**Comment by chaitanya0bhagvan** [comment]
@SupriyaKalghatgi any theme is a function of few variables. With android as an example these would be the variables (it can be adapted for ios also)

>   primaryColorDark:   '#1976D2',
>   primaryColor:        '#2196F3',
>   primaryColorLight:  '#BBDEFB',
>   accentColor:         '#FF4081',
> 
>   primaryTextColor:   '#212121',
>   secondaryTextColor: '#757575',
>   iconTextColor:   '#FFFFFF',
>   dividerColor:        '#BDBDBD',

We can wrap the variables object inside a function that accepts an object with the above variables. Take a look at this [gist](https://gist.github.com/chaitanya0bhagvan/76b6f869378647b9cf2b9e18cf51a037). 

I do understand your point relating to color context. For an application that wants to support a Light and a Dark theme, the colors must be chosen so that the colors match the context for that use case. For general use cases I would be worried such as bright colors on bright images etc.

**Comment by jennykortina** [comment]
@chaitanya0bhagvan @SupriyaKalghatgi what is the name of the variable to change the background of the app from white to black?  I still can't find that.

**Comment by chaitanya0bhagvan** [comment]
@jennykortina You would have to create a new variable for backgroundColor and create a Wrapper, decorated with connectStyle, around Container. This wrapped Container will have a style property to change the backgroundColor. You will also have to create a style in native-base-theme/components/index.js. I have updated the above [gist](https://gist.github.com/chaitanya0bhagvan/76b6f869378647b9cf2b9e18cf51a037) to reflect this
