### ISSUE TITLE
Proposing changing Separator text on iOS to conform to guidelines

### ISSUE THREAD

**Issue by vtsatskin** [GeekyAnts/NativeBase#903]
I noticed that the current list separator on iOS has a non-default styling for the text. Here is a screenshot from the kitchen sink application.

![img_1470](https://cloud.githubusercontent.com/assets/1301625/26605584/9ff88926-455c-11e7-82f2-8b4fad429983.PNG)

However, looking at the UI guidelines supplied by Apple, text for a separator would look like so:

<img width="373" alt="screen shot 2017-05-30 at 5 24 19 pm" src="https://cloud.githubusercontent.com/assets/1301625/26605676/ebd94664-455c-11e7-98db-0eea6670b1fd.png">

I'm thinking of creating a pull request to make the changes necessary to update the font size, colour, and padding from the side. Would these changes be welcomed?

Currently I use two Separators to get similar spacing between list items as used by Apple in multiple grouped TableViews (see screenshot below). What does the team think about having increased padding between the text and the top of the separator?

![img_1471](https://cloud.githubusercontent.com/assets/1301625/26605973/0b9c30b4-455e-11e7-8d7c-fc77f68d1a9d.PNG)

## react-native, react and native-base version

* react-native@0.44.2
* react@16.0.0-alpha.6
* native-base@2.1.4

**Comment by sankhadeeproy007** [comment]
@vtsatskin A pull request would be very welcome!

**Comment by vtsatskin** [comment]
@sankhadeeproy007 I'm just waiting for a resolution to my issues with running the KitchenSink app with the latest version of native-base so I can start testing my changes: https://github.com/GeekyAnts/NativeBase-KitchenSink/issues/53

**Comment by shivrajkumar** [comment]
Update to latest version 2.2.0 and use `group` prop with Separator component.
