### ISSUE TITLE
Active text on tab heading not working

### ISSUE THREAD

**Issue by sabbyt** [GeekyAnts/NativeBase#904]
**react-native, react and native-base version:**
rn: 0.42.3
react: 15.4.2
nb: 2.1.0
**Expected behaviour:**
active text should change colour, matching with tab heading bottom border colour
**Actual behaviour:**
active text not changing colour but tab heading bottom border colour is changing

**Steps to reproduce (code snippet or screenshot)**
```
    <Container>
        <Header hasTabs={hasTabs}>
           <Title style={style}>{title}</Title>
        </Header>
        <Tabs>
          <Tab heading="To mobile">
            <Tab2 />
          </Tab>
          <Tab heading="To card">
            <Tab1 />
          </Tab>
        </Tabs>
    </Container>
```
![screen shot 2017-05-31 at 11 03 35 2](https://cloud.githubusercontent.com/assets/10805641/26614116/f7689234-45f0-11e7-848f-ab574ac855cd.png)
![screen shot 2017-05-31 at 11 03 38 2](https://cloud.githubusercontent.com/assets/10805641/26614120/fa385a30-45f0-11e7-82ee-c3f7f63b2506.png)

**Is the bug present in both ios and android or in any one of them?**
only tested on android

**Comment by SupriyaKalghatgi** [comment]
Check with the latest of NativeBase
