### ISSUE TITLE
TouchableHighlight on press doesnt work

### ISSUE THREAD

**Issue by jeromelebleu26** [GeekyAnts/NativeBase#906]
Hi, 

I'm trying to create an action on TouchableHighlith on Press, but i'have an error `undefined is not an object`

This is my code : 

`
import React, {Component} from 'react';
import {Image, Platform, StatusBar, ListView, TouchableHighlight} from 'react-native';
import {connect} from 'react-redux';
import {Actions} from 'react-native-router-flux';
import {
    Container,
    Content,
    Text,
    Icon,
    View,
    Left,
    Right,
    Header,
    Body,
    Title,
    Animated

} from 'native-base';

import styles from './styles';

class Championnat extends Component {

    constructor(props) {
        super(props);
        const ds = new ListView.DataSource({rowHasChanged: (r1, r2) => r1 !== r2});
        this.state = {
            dataSource: ds.cloneWithRows([
                {slug : 'team', name : 'Liqgue1'},
                {slug : 'worldcup', name : 'Coupe du monde'},
            ]),
        };
    }

    pressRow(data) {

        console.log(data);

    }

    renderRow(data){
        return (
            <TouchableHighlight onPress={()=> this.pressRow(data)}>
                <View style={styles.lstView}>
                    <Image style={styles.lstPicto} />
                    <Text style={styles.lstText}>{data.name}</Text>
                    <Icon name="angle-right" right style={styles.lstIcon} />
                </View>
            </TouchableHighlight>

        )
    }

    render() {
        return (
            <Container style={styles.container}>

                <Header style={styles.header}>
                    <Left>
                        <Button transparent onPress={() => Actions.pop()}>
                            <Icon active name="angle-left"/>
                        </Button>
                    </Left>
                    <Body>
                        <Title>Choisir un championnat</Title>
                    </Body>
                    <Right></Right>
                </Header>

                <View style={{flex: 1}}>
                    <ListView

                        dataSource={this.state.dataSource}
                        renderRow = {this.renderRow.bind(this)}

                    ></ListView>
                </View>

            </Container>

        )
    }
}

export default connect()(Championnat);

`

I've seen an another post, so i publish my packadge (from expo) : 

`
{
  "name": "Oh-my-foot",
  "version": "0.0.0",
  "description": "Hello Expo!",
  "author": "Whatson web",
  "private": true,
  "main": "main.js",
  "dependencies": {
    "@expo/react-native-fade-in-image": "^1.1.1",
    "es6-promise": "^4.1.0",
    "expo": "17.0.0",
    "fetchival": "^0.3.2",
    "react": "16.0.0-alpha.6",
    "react-native": "https://github.com/expo/react-native/archive/sdk-17.0.0.tar.gz",
    "react-native-cached-image": "^1.3.3",
    "react-redux": "^5.0.5",
    "whatwg-fetch": "^2.0.3"
  },
  "devDependencies": {
    "remote-redux-devtools": "^0.5.11"
  }
}

`

**Comment by sankhadeeproy007** [comment]
Not related to native-base.
