### ISSUE TITLE
Creating Lists with Sections

### ISSUE THREAD

**Issue by njt1982** [GeekyAnts/NativeBase#909]
RE: https://github.com/GeekyAnts/NativeBase/blob/master/src/basic/List.js#L15

## react-native, react and native-base version

RN 0.43, NB 2.1.2

## Expected behaviour

To be able to pass in a hash of sections and rows, with section data for labels (like you can with ListView).

## Actual behaviour

Can only pass in a "flat" single section list, as we assume `dataArray` coded that way, using `cloneWithRows`. See: http://richardkho.com/section-headers-in-react-native-listview-components/

**Comment by shivrajkumar** [comment]
@njt1982 List through dataArray accepts only single section list. For more complex data list you can use RN ListView.
