### ISSUE TITLE
what are the possible modes for native-base picker apart from "dropdown"? 

### ISSUE THREAD

**Issue by harrybhadana** [GeekyAnts/NativeBase#91]

**Comment by sankhadeeproy007** [comment]
For android it's same as [react-native](https://facebook.github.io/react-native/docs/picker.html) and for iOS there's just modal.

**Comment by safweb89** [comment]
there is 'popup' i just have tried it and it works pretty good

**Comment by mali3days** [comment]
![picker_modes](https://user-images.githubusercontent.com/13189724/32485117-e4558278-c3aa-11e7-8777-52003bcebf1d.png)
