### ISSUE TITLE
Typo in toast component tutorial code(docs code from website) causes a crash

### ISSUE THREAD

**Issue by neelindap** [GeekyAnts/NativeBase#911]
Hi Team,

A typo in the toast component doc on the website(https://docs.nativebase.io/Components.html#Toast) causes a crash when using toast in applications.
```
<Button onPress={()=> Toast.show({
              supportedOrientations: ['potrait','landscape'],
              text: 'Wrong password!',
              position: 'bottom',
              buttonText: 'Okay'
            })}>
```
It should be portrait.
Same is present in the configuration table as well.

Regards,
Neel Indap

**Comment by shivrajkumar** [comment]
Fixed
