### ISSUE TITLE
[Android] react-native-dropdownalert is underneath Header component

### ISSUE THREAD

**Issue by testshallpass** [GeekyAnts/NativeBase#912]
### react-native, react and native-base version
- native-base: ^2.1.3,
- react: ^16.0.0-alpha.6,
- react-native: ^0.43.4,
- react-native-dropdownalert: ^2.8.0
### Expected behaviour
DropdownAlert to overlap `<Header />` component on Android.
### Actual behaviour
DropdownAlert is seen underneath `<Header />` component on Android
### Steps to reproduce (code snippet or screenshot)
1. Download: react-native-dropdownalert/example
2. Use terminal and navigate to the example directory: cd /Example
3. Install the npm modules: npm install
4. Link: react-native link
5. Check that the folder node_modules was installed.
6. Use a NavBar on main.js (I used native-base components)
7. Run project: react-native run-android
8. Show alert: Press some button to show alert
### Is the bug present in both ios and android or in any one of them?
- Android
### Any other additional info which would help us debug the issue quicker.
- [Duplicate issue reported on DropdownAlert github](https://github.com/testshallpass/react-native-dropdownalert/issues/53)
![screenshot_20170610-221732](https://user-images.githubusercontent.com/7293079/27007741-b6389d20-4e2b-11e7-9e17-5be5951a099c.png)

**Comment by sankhadeeproy007** [comment]
Try giving a higher elevation to `containerStyle` prop of the dropdownAlert.

**Comment by testshallpass** [comment]
I will try that. What is the elevation on `<Header />`?  If any?

**Comment by sankhadeeproy007** [comment]
I think that's 3

**Comment by testshallpass** [comment]
Unfortunately, change to elevation did not work. I did added the Dropdownalert to the last position in the header document tree and that allowed it to overlap. However, limited to header's height.

![screenshot_20170610-220426](https://user-images.githubusercontent.com/7293079/27007736-610a100e-4e2b-11e7-8014-48fd7b85ade1.png)

**Comment by mahendra13** [comment]
I am also facing the same issue, is there any solution.

**Comment by ssac** [comment]
For 
"react-native-dropdownalert": "^2.10.0",
"react-native": "^0.46.4",

Below code work:
<Header noShadow>

My android versions are 4.1.2 and 4.4.4

**Comment by RamyarIran** [comment]
I had the exact same problem! easily solved with on <DropdownAlert elevation={4} />!
Thanks Geeky Ants

**Comment by akhil-geekyants** [comment]
Setting the `<DropdownAlert/>` elevation greater than or equal to `<Header/>`'s elevation solves the issue.

![dropdownalert](https://user-images.githubusercontent.com/27768184/33123291-ccc4869e-cf9f-11e7-9f4e-4390c15756c8.gif)

**Comment by akhil-geekyants** [comment]
Closing this issue.

**Comment by husnainafzal86** [comment]
Thanks! worked perfectly with elevation={3} or {4}

**Comment by Gretchin** [comment]
set elevation to DropdownAlert  repair tapToClose for me, ty

**Comment by dalmarcogd** [comment]
> Setting the `<DropdownAlert/>` elevation greater than or equal to `<Header/>`'s elevation solves the issue.
> 
> ![dropdownalert](https://user-images.githubusercontent.com/27768184/33123291-ccc4869e-cf9f-11e7-9f4e-4390c15756c8.gif)

Its works for me.
