### ISSUE TITLE
Customizing style using style provider

### ISSUE THREAD

**Issue by vinujan59** [GeekyAnts/NativeBase#914]
## react-native, react and native-base version
react-native - 0.44.0
react - 16.0.0-alpha.6
## Expected behaviour
Custom Style should be propagated when applying through styleProvider
## Actual behaviour
Getting error variables.platFormStyle undefined
## Steps to reproduce (code snippet or screenshot)
Component

`<StyleProvider style={headerThemeCus}>
                    <Header searchBar rounded>
                        <Left>
                            <Button transparent onPress={Actions.calendar}>
                                <Icon name='calendar'/>
                            </Button>
                        </Left>
                        <Item>
                            <Input placeholder="Search Customers, Rooms ..."/>
                            <Icon name="search"/>
                        </Item>
                        <Right>
                            <Button transparent>
                                <Icon name='menu'/>
                            </Button>
                        </Right>
                    </Header>
                </StyleProvider>`

style

import variable from './../native-base-theme/variables/platform';
const platform = Platform.OS;
const platformStyle = undefined;
const headerThemeCus = {
    'NativeBase.Header':{
        '.span': {
            height: 128,
            'NativeBase.Left': {
                alignSelf: 'flex-start',
            },
            'NativeBase.Body': {
                alignSelf: 'flex-end',
                alignItems: 'flex-start',
                justifyContent: 'center',
                paddingBottom: 26,
            },
            'NativeBase.Right': {
                alignSelf: 'flex-start',
            },
        },
        '.hasSubtitle': {
            'NativeBase.Body': {
                'NativeBase.Title': {
                    fontSize: variable.titleFontSize - 2,
                    fontFamily: variable.titleFontfamily,
                    textAlign: 'center',
                },
                'NativeBase.Subtitle': {
                    fontSize: variable.subTitleFontSize,
                    fontFamily: variable.titleFontfamily,
                    color: variable.subtitleColor,
                    textAlign: 'center',
                },
            },
        },
        '.noShadow': {
            elevation: 0,
            shadowColor: null,
            shadowOffset: null,
            shadowRadius: null,
            shadowOpacity: null,
        },
        '.hasTabs': {
            elevation: 0,
            shadowColor: null,
            shadowOffset: null,
            shadowRadius: null,
            shadowOpacity: null,
            borderBottomWidth: null,
        },
        '.hasSegment': {
            elevation: 0,
            shadowColor: null,
            shadowOffset: null,
            shadowRadius: null,
            shadowOpacity: null,
            borderBottomWidth: null,
        },
        'NativeBase.Button': {
            justifyContent: 'center',
            alignSelf: 'center',
            alignItems: 'center',
            '.transparent': {
                'NativeBase.Text': {
                    color: variable.toolbarBtnColor,
                    fontWeight: '600',
                },
                'NativeBase.Icon': {
                    color: variable.toolbarBtnColor,
                },
                'NativeBase.IconNB': {
                    color: variable.toolbarBtnColor,
                },
                paddingHorizontal: variable.buttonPadding,
            },
            paddingHorizontal: 15,
        },
        '.searchBar': {
            'NativeBase.Item': {
                'NativeBase.Icon': {
                    backgroundColor: 'transparent',
                    color: variable.dropdownLinkColor,
                    fontSize: variable.toolbarSearchIconSize,
                    alignItems: 'center',
                    marginTop: 2,
                    paddingRight: 10,
                    paddingLeft: 10,
                },
                'NativeBase.IconNB': {
                    backgroundColor: 'transparent',
                    color: null,
                    alignSelf: 'center',
                },
                'NativeBase.Input': {
                    alignSelf: 'center',
                    lineHeight: 24,
                    height: variable.searchBarHeight,
                },
                alignSelf: 'center',
                alignItems: 'center',
                flex:1,
                justifyContent: 'center',
                height: variable.searchBarHeight,
                borderColor: 'transparent',
                backgroundColor: variable.toolbarInputColor,
            },
            'NativeBase.Button': {
                '.transparent': {
                    'NativeBase.Text': {
                        fontWeight: '500',
                    },
                    paddingHorizontal: null,
                    paddingLeft: (platform === 'ios') ? 10 : 10,
                    paddingRight: (platform === 'ios') ? 10 : 10,
                },
                paddingHorizontal: (platform === 'ios') ? undefined : null,
                width: (platform === 'ios') ? undefined : undefined,
                height: (platform === 'ios') ? undefined : undefined,
                flex : 0
            },
            'NativeBase.Right':{
                'NativeBase.Button': {
                    '.transparent': {
                        'NativeBase.Text': {
                            fontWeight: '500',
                        },
                        paddingHorizontal: null,
                        paddingRight: (platform === 'ios') ? 10 : 10,
                        paddingLeft: (platform === 'ios') ? 10 : 10,
                    },
                    paddingHorizontal: (platform === 'ios') ? undefined : null,
                    width: (platform === 'ios') ? undefined : undefined,
                    height: (platform === 'ios') ? undefined : undefined,
                },
                flex:0
            },
            'NativeBase.Left':{
                'NativeBase.Button': {
                    '.transparent': {
                        'NativeBase.Text': {
                            fontWeight: '500',
                        },
                        paddingHorizontal: null,
                        paddingLeft: (platform === 'ios') ? 10 : 10,
                        paddingRight: (platform === 'ios') ? 10 : 10,
                    },
                    paddingHorizontal: (platform === 'ios') ? undefined : null,
                    width: (platform === 'ios') ? undefined : undefined,
                    height: (platform === 'ios') ? undefined : undefined,
                },
                flex:0
            }
        },
        '.rounded': {
            'NativeBase.Item': {
                borderRadius: ((platform === 'ios') && (platformStyle !== 'material')) ? 25 : 3,
            },
        },
        'NativeBase.Left': {
            'NativeBase.Button': {
                '.hasText': {
                    marginLeft: -10,
                    height: 30,
                    'NativeBase.Icon': {
                        color: variable.toolbarBtnColor,
                        fontSize: variable.iconHeaderSize,
                        marginTop: 2,
                        marginRight: 5,
                        marginLeft: 2
                    },
                    'NativeBase.Text': {
                        color: variable.toolbarBtnColor,
                        fontSize: 17,
                        marginLeft: 2,
                        lineHeight: 21
                    },
                    'NativeBase.IconNB': {
                        color: variable.toolbarBtnColor,
                        fontSize: variable.iconHeaderSize,
                        marginTop: 2,
                        marginRight: 5,
                        marginLeft: 2
                    },
                },
                '.transparent': {
                    marginLeft: -3,
                    'NativeBase.Icon': {
                        color: variable.toolbarBtnColor,
                        fontSize: variable.iconHeaderSize,
                        marginTop: 2,
                        marginRight: 2,
                        marginLeft: 2
                    },
                    'NativeBase.IconNB': {
                        color: variable.toolbarBtnColor,
                        fontSize: variable.iconHeaderSize,
                        marginTop: 2,
                        marginRight: 2,
                        marginLeft: 2
                    },
                    'NativeBase.Text': {
                        color: variable.toolbarBtnColor,
                        fontSize: 17,
                        top: (platform === 'ios') ? undefined : -1.5,
                    },
                    backgroundColor: 'transparent',
                    borderColor: null,
                    elevation: 0,
                    shadowColor: null,
                    shadowOffset: null,
                    shadowRadius: null,
                    shadowOpacity: null,
                },
                'NativeBase.Icon': {
                    color: variable.toolbarBtnColor,
                },
                'NativeBase.IconNB': {
                    color: variable.toolbarBtnColor,
                },
                alignSelf: null,
                paddingHorizontal: variable.buttonPadding,
            },
            flex: ((platform === 'ios') && (platformStyle !== 'material')) ? 1 : 0.5,
            alignSelf: 'center',
            alignItems: 'flex-start',
        },
        'NativeBase.Body': {
            flex: 1,
            alignItems: ((platform === 'ios') && (platformStyle !== 'material')) ? 'center' : 'flex-start',
            alignSelf: 'center',
            'NativeBase.Segment': {
                borderWidth: 0,
                alignSelf: 'flex-end',
                marginRight: (platform === 'ios') ? -40 : -55
            },
            'NativeBase.Button': {
                alignSelf: 'center',
                '.transparent': {
                    backgroundColor: 'transparent',
                },
                'NativeBase.Icon': {
                    color: variable.toolbarBtnColor,
                },
                'NativeBase.IconNB': {
                    color: variable.toolbarBtnColor,
                },
                'NativeBase.Text': {
                    color: variable.inverseTextColor,
                },
            },
        },
        'NativeBase.Right': {
            'NativeBase.Button': {
                '.hasText': {
                    height: 30,
                    'NativeBase.Icon': {
                        color: variable.toolbarBtnColor,
                        fontSize: variable.iconHeaderSize - 2,
                        marginTop: 2,
                        marginRight: 2,
                        marginLeft: 5
                    },
                    'NativeBase.Text': {
                        color: variable.toolbarBtnColor,
                        fontSize: 17,
                        lineHeight: 21
                    },
                    'NativeBase.IconNB': {
                        color: variable.toolbarBtnColor,
                        fontSize: variable.iconHeaderSize - 2,
                        marginTop: 2,
                        marginRight: 2,
                        marginLeft: 5
                    },
                },
                '.transparent': {
                    marginRight: -8,
                    paddingHorizontal: 15,
                    borderRadius: 50,
                    'NativeBase.Icon': {
                        color: variable.toolbarBtnColor,
                        fontSize: (platform === 'ios') ? variable.iconHeaderSize - 6 : variable.iconHeaderSize - 2,
                        marginTop: 2,
                        marginLeft: 2,
                        marginRight: 2
                    },
                    'NativeBase.IconNB': {
                        color: variable.toolbarBtnColor,
                        fontSize: (platform === 'ios') ? variable.iconHeaderSize - 6 : variable.iconHeaderSize - 2,
                        marginTop: 2,
                        marginLeft: 2,
                        marginRight: 2
                    },
                    'NativeBase.Text': {
                        color: variable.toolbarBtnColor,
                        fontSize: 17,
                        top: (platform === 'ios') ? undefined : -1.5,
                    },
                    backgroundColor: 'transparent',
                    borderColor: null,
                    elevation: 0,
                    shadowColor: null,
                    shadowOffset: null,
                    shadowRadius: null,
                    shadowOpacity: null,
                },
                'NativeBase.Icon': {
                    color: variable.toolbarBtnColor,
                },
                'NativeBase.IconNB': {
                    color: variable.toolbarBtnColor,
                },
                alignSelf: null,
                paddingHorizontal: variable.buttonPadding,
            },
            flex: 1,
            alignSelf: 'center',
            alignItems: 'flex-end',
            flexDirection: 'row',
            justifyContent: 'flex-end',
        },
        backgroundColor: variable.toolbarDefaultBg,
        flexDirection: 'row',
        paddingHorizontal: 10,
        justifyContent: 'center',
        paddingTop: (platform === 'ios') ? 15 : 0,
        borderBottomWidth: (platform === 'ios') ? (1 / PixelRatio.getPixelSizeForLayoutSize(1)) : 0,
        borderBottomColor: variable.toolbarDefaultBorder,
        height: variable.toolbarHeight,
        elevation: 3,
        shadowColor: (platformStyle === 'material') ? '#000' : undefined,
        shadowOffset: (platformStyle === 'material') ? {width: 0, height: 2} : undefined,
        shadowOpacity: (platformStyle === 'material') ? 0.2 : undefined,
        shadowRadius: (platformStyle === 'material') ? 1.2 : undefined,
        top: 0,
        left: 0,
        right: 0,
    }
};

## Is the bug present in both ios and android or in any one of them?
Just checking on android
## Any other additional info which would help us debug the issue quicker.
I have ejected the theme. In order to customize theme to component level this approach is handled

**Comment by kaylabranson** [comment]
Also getting this error

**Comment by SupriyaKalghatgi** [comment]
You need to pass the variable file name here
Please check the [Docs](https://docs.nativebase.io/Customize.html#Theming_NativeBase_Apps) for this

**Comment by vinujan59** [comment]
yeah, I did not get error by passing variables, but styles was fully applied as earlier

<StyleProvider style={headerStyle} >

headerStyle ={// neeeded to import variable from variables/platform 
      variables,
     'NativeBaseHeader':{ styles for header}}
} 

But below worked as intended

const headerStyle = (variables = variable) => {
    const platformStyle = variables.platformStyle;
    const platform = variables.platform;
    let style = headerTheme();
    style['NativeBase.Header'] =  {
       //style specified
    };
    return style;
};

**Comment by SupriyaKalghatgi** [comment]
@vinujan59 Please post screenshot of actual and expected output

**Comment by vinujan59** [comment]
![image](https://user-images.githubusercontent.com/11666269/26918492-e4dfe65c-4c4f-11e7-9ef7-9d18adf8efa1.png)
 vs
![image](https://user-images.githubusercontent.com/11666269/26918509-f56f093a-4c4f-11e7-94b9-efdda22ef1bb.png)

these are the screenshots for the above code. You can see styles of component such as Icon and Input is not applied.

**Comment by SupriyaKalghatgi** [comment]
@vinujan59 The theme you pass should be a function
So the use case should be 
```
<StyleProvider style={headerStyle()}>
```

**Comment by vinujan59** [comment]
yeah exactly

**Comment by SupriyaKalghatgi** [comment]
@vinujan59 Can you close this issue, if your issue is fixed?
