### ISSUE TITLE
Creating a picker component 

### ISSUE THREAD

**Issue by openqubit** [GeekyAnts/NativeBase#916]
I have some card items and i would like to add a picker component that i can use to have select box

```
<CardItem>
<Item  floatingLabel>
<Label>Airtime Amount</Label>
<Picker selectedValue={this.state.language} onValueChange={(lang) => this.setState({language: lang})}> <Picker.Item label="Java" value="java" /> <Picker.Item label="JavaScript" value="js" /></Picker>
</Item>
</CardItem>
```
I have this is in the constructor

```
constructor(props) {
  super();
  this.state = {
    language: 'Qt',
  }
}
```
The code does not display the picker but instead displays a text input box.

How can i have the picker working?.

**Comment by shivrajkumar** [comment]
@openqubit adding prop `floatingLabel` gives you a input component of floating type.
Using the Picker outside `<Item>` or removing `floatingLabel` prop should resolve this.
