### ISSUE TITLE
Thumbnail props for size not working

### ISSUE THREAD

**Issue by SupriyaKalghatgi** [GeekyAnts/NativeBase#917]
Thumbnail `small`, `large` prop when used with shape type `sqaure`, it changes the image to shape  `circle`

![pasted image at 2017_06_05 04_20 pm](https://cloud.githubusercontent.com/assets/13464885/26820122/57a3d690-4abf-11e7-9c9f-be8f17c3e855.png)

**Comment by sankhadeeproy007** [comment]
Fixed with 2.1.5
