### ISSUE TITLE
Header background Image and Tabar

### ISSUE THREAD

**Issue by googl3r** [GeekyAnts/NativeBase#919]
Hi,
I want to add a background for header and increase its size, but the Image doesnt fit the header background. Also is it possible to customize header tabs ? Juste like the Image belloW
![img_1379](https://user-images.githubusercontent.com/2989553/26847155-52121b6e-4afc-11e7-9570-35e36bd25f77.PNG)

**Comment by sankhadeeproy007** [comment]
![screen shot 2017-06-07 at 4 11 54 pm](https://user-images.githubusercontent.com/10998047/26874661-0de29432-4b9c-11e7-864a-a81645cd5d91.png)
You can add the background image by using the above code. 
About the 2nd part of your question, you can customize the Segment to achieve the desired result.

**Comment by HusseinElGanzory** [comment]
> ![screen shot 2017-06-07 at 4 11 54 pm](https://user-images.githubusercontent.com/10998047/26874661-0de29432-4b9c-11e7-864a-a81645cd5d91.png)
> You can add the background image by using the above code.
> About the 2nd part of your question, you can customize the Segment to achieve the desired result.

i have icons at header on left and right when write fixed width icon not displayed

**Comment by HusseinElGanzory** [comment]
i have icons at header on left and right when write fixed width icon not displayed
