### ISSUE TITLE
How can I add styling to picker? 

### ISSUE THREAD

**Issue by harrybhadana** [GeekyAnts/NativeBase#92]
I want to change the width of drop-down menu to 100% . and also want to add a bottom border in each item .

**Comment by sankhadeeproy007** [comment]
Native base picker is just a wrapper around react-native's picker. It's only in iOS that we've implemented the modal view. You can style the android dropdown the same way you style the react-native dropdown. If you want full width, you might want to use `flex: 1`. This is not an issue with native-base, so I'm closing it.
