### ISSUE TITLE
Picker will not render in ios

### ISSUE THREAD

**Issue by tamagokun** [GeekyAnts/NativeBase#921]
## react-native, react and native-base version

```
"native-base": "^2.1.4",
"react": "16.0.0-alpha.6",
"react-native": "0.44.3",
```

## Expected behaviour

Picker gets rendered

## Actual behaviour

App throws error.

## Steps to reproduce (code snippet or screenshot)

```jsx
<Picker>
  <Picker.Item label='Test' value='test' />
</Picker>
```

## Screenshot of emulator/device

![screen shot 2017-06-07 at 6 43 23 am](https://user-images.githubusercontent.com/487333/26874780-df454916-4b4c-11e7-9bc3-cb9afec9c99f.png)

## Is the bug present in both ios and android or in any one of them?

Judging by the source, this probably works fine on Android, though I did not test.

**Comment by sankhadeeproy007** [comment]
The example works pretty fine for me. Try rendering multiple values of Item instead of just one.

**Comment by tamagokun** [comment]
Whoa, okay, yeah, that worked. I know no one would typically have just *one* item in a picker, but it seems like it should be able to work with that. Maybe using `React.children` instead of accessing `this.props.children` directly would be better?

Anyways, thanks for the help, i'll close.
