### ISSUE TITLE
[Android] this.props.children.toUpperCase is not a function

### ISSUE THREAD

**Issue by renehauck** [GeekyAnts/NativeBase#925]
Similar to this issue: #285, my app (after a update) throw the error 

```
TypeError: this.props.children.toUpperCase is not a function
    at Text.render (Text.js:15)
    ....
```

in this case in Text.js.
Removing the function "toUpperCase()" seems to work, but i don't know, if this the correct way?

**Comment by sankhadeeproy007** [comment]
What version of native-base are you using? What is the use case?

**Comment by sankhadeeproy007** [comment]
And **PLEASE** make use of the issue template.

**Comment by renehauck** [comment]
## react-native, react and native-base version
"react": "16.0.0-alpha.6",
    "react-native": "0.44.0",
"native-base": "^2.1.4"

## Expected behaviour
my text
## Actual behaviour
```
TypeError: this.props.children.toUpperCase is not a function
    at Text.render (Text.js:15)
    ....
```
## Steps to reproduce (code snippet or screenshot)
This code produce the error:
 ```
<CardItem>
    <Left>
        <Thumbnail source={element.imageUrl ? { uri: ServiceManager.getImageUrlByName(element.store.icon) } : noImage} />
        <Body>
            <Text>{element.store.name}</Text>
            <Text note>{element.store.street}{element.store.streetNumber}</Text>
            <Text note>{element.store.zipcode} {element.store.city}</Text>
        </Body>
    </Left>
</CardItem>
```
## Screenshot of emulator/device
## Is the bug present in both ios and android or in any one of them?
i have only a android device
## Any other additional info which would help us debug the issue `quicker.```
Removing the function "toUpperCase()" seems to work, but i don't know, if this the correct way?

**Comment by sankhadeeproy007** [comment]
Seems to work pretty well for me in RN 44.2, can you upgrade and check?

**Comment by phpnil** [comment]
A still same issue I found in upgrade version.
here is my package.json
`{
  "name": "MyProject",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "native-base": "^2.1.5",
    "react": "16.0.0-alpha.12",
    "react-native": "0.45.1",
    "react-native-fit-image": "^1.4.8",
    "react-native-htmlview": "^0.9.0",
    "react-native-router-flux": "^3.40.1",
    "react-native-timeago": "^0.3.0"
  },
  "devDependencies": {
    "babel-jest": "20.0.3",
    "babel-preset-react-native": "2.0.0",
    "jest": "20.0.4",
    "react-test-renderer": "16.0.0-alpha.12"
  },
  "jest": {
    "preset": "react-native"
  }
}`

![screenshot_1498225635](https://user-images.githubusercontent.com/6614063/27484977-aeb8e600-5848-11e7-8598-2e5c339c9131.png)

**Comment by nazrdogan** [comment]
Same issue

**Comment by jamesphe** [comment]
+1

**Comment by nazrdogan** [comment]
use RN Text . I solved with that.

**Comment by phpnil** [comment]
@nazrdogan what next step to solve this issue. Do i need to update anything?

**Comment by nazrdogan** [comment]
no , I just used RN Text Component instead of Nativebase
