### ISSUE TITLE
Update to 2.1.5 breaks my project.

### ISSUE THREAD

**Issue by sankhadeeproy007** [GeekyAnts/NativeBase#928]
When we upgrade to **2.1.5 and above** from an older version of native-base, there are multiple build errors. 
This is happening because we have removed the unused fonts from the package #900. 

**If you've not many any changes to native code:**
Deleting the android/ios directories and running `react-native upgrade` fixes it.

Otherwise 

**Unlinking vector-icons and cleaning the build should fix it.**
Steps 
![screen shot 2017-06-10 at 2 38 40 pm](https://user-images.githubusercontent.com/10998047/27001565-a5de4b00-4dea-11e7-9825-db9f10046d76.png)

![screen shot 2017-06-10 at 2 38 27 pm](https://user-images.githubusercontent.com/10998047/27001563-9582a0ee-4dea-11e7-9d2b-47ba5ab55655.png)

`react-native link`

**Comment by yaronlevi** [comment]
Seems like I haveing this issue. Do you think it's related?
<img width="674" alt="screen shot 2017-06-10 at 2 07 06" src="https://user-images.githubusercontent.com/5398977/26997532-4124716a-4d83-11e7-9268-6364e7b021d3.png">

**Comment by flyandi** [comment]
I just removed the references from the project but now I have a different issue .. seems like everytime I upgrade there is a problem in native-base :\

**Comment by stadiumbeejm** [comment]
I am having issues as well.

<img width="1437" alt="screen shot 2017-06-10 at 3 56 30 am" src="https://user-images.githubusercontent.com/24426002/27001166-f7d09076-4d90-11e7-8753-18118ec6c1a7.png">

**Comment by sankhadeeproy007** [comment]
Did you follow the steps mentioned?

**Comment by stadiumbeejm** [comment]
I ran your first piece of code with no effect. I dont know what you mean by deleting my ios/android directories

**Comment by sankhadeeproy007** [comment]
did you create your app with CRNA?

**Comment by stadiumbeejm** [comment]
no it is an old project. I just pulled it down from git ran, npm install and it freaked out with all these errors

**Comment by sankhadeeproy007** [comment]
ios/android directory means folders named `ios` and `android` inside your project.

**Comment by sankhadeeproy007** [comment]
@yaronlevi Yes, that's because of the breaking change. Let me know if that fixes it.

**Comment by stadiumbeejm** [comment]
i guess I am lost...and i guess more new that what i actually considered. Why do i need to delete these with all my custom java and custom ios code. What value does that give me?

**Comment by sankhadeeproy007** [comment]
@stadiumbeejm okay hold on, I'll just get back with an alternative.

**Comment by sankhadeeproy007** [comment]
@stadiumbeejm The steps have been updated in the initial comment. can you try that out and let me know.

**Comment by stadiumbeejm** [comment]
I pulled fresh from git
npm install
npm link
react-native run-ios

I got the below

<img width="854" alt="screen shot 2017-06-10 at 9 44 17 am" src="https://user-images.githubusercontent.com/24426002/27003294-e504f01e-4dc1-11e7-8c51-2eb27c2e4196.png">
<img width="1391" alt="screen shot 2017-06-10 at 9 46 50 am" src="https://user-images.githubusercontent.com/24426002/27003298-ea3058b2-4dc1-11e7-9067-d652bcd8293b.png">

**Comment by HenryZl** [comment]
你好，
我在执行过 
`react-native upgrade `
`npm install`
`react-native link`
之后，在模拟器上运行app时，
我得到了这样一个错误，
`Bundling `index.android.js`  100.0% (989/989), done.
`
`
Opening /xxxxxxx/node_modules/native-base/dist/src/index.js with code
spawn code ENOENT
`
有什么解决思路吗？

**Comment by voquockhanh** [comment]
Hi guys,

- After remove fonts from "Copy Bundle Resource" step of IOS. I meet same problems like @yaronlevi @flyandi @stadiumbeejm 

- I think problems came from we didn't delete 100% old font from "project.pbxproj" file. So, we need manual delete them. In my case, here I did:
1. Open "project.pbxproj" with your text Editor
2. Find "PBXGroup", scroll down a bit until you see some lines like this:
`ECCBAFC717104E399E34097D /* EvilIcons.ttf */,`
3. You may see some duplicate .tff here. In my case:
`FC3471B0670F40EBA73BB0AF /* EvilIcons.ttf */,
ECCBAFC717104E399E34097D /* EvilIcons.ttf */,`
4. left value is ID, use it to search in file. if you see which ID is less occurrence, mean it is missed deleted by our steps in first post. You need delete those lines using that ID

- In case you already deleted those .tff files preference in "Resources" in Xcode like @flyandi , you will not see duplicate "xxxx.ttf" in "PBXGroup". you should find "xxxx.ttf" manually in "project.pbxproj" and find wrong ID.

Hope it help : D

**Comment by shivrajkumar** [comment]
Closing this as the above solution works. Let us know if you still face this

**Comment by fabriziobertoglio1987** [comment]
I tried the [following solution](https://github.com/oblador/react-native-vector-icons/issues/851#issuecomment-457997515) and solved the problem, without having to manually delete the entries.
