### ISSUE TITLE
Logo, landscape and focus fields

### ISSUE THREAD

**Issue by basequatro** [GeekyAnts/NativeBase#93]
Hi there. i have 2 questions about nativebase.io, mainly about responsive design.

1 - Is the logo alignment already working?
2 - Does this UI works in landscape mode? Login screen seems cropped

**Comment by sankhadeeproy007** [comment]
I'm not sure which logo you're referring to.
And no, we are focussing mainly on portrait mode as of now. However with a few changes here and there, it should work fine for landscape too.
