### ISSUE TITLE
StyleProvider does not recognize children.

### ISSUE THREAD

**Issue by flyandi** [GeekyAnts/NativeBase#932]
![image](https://user-images.githubusercontent.com/329973/27000280-26e1e910-4d63-11e7-8678-cec72796e8fb.png)
Looks like the latest version does not recognize the children of an StyleProvider.

Code
```
<StyleProvider style={getTheme(common)}>
                <Container>
                   ...
                </Container>
            </StyleProvider>
```

**Comment by flyandi** [comment]
That's with 

```
 "native-base": "^2.1.5",
    "react": "^16.0.0-alpha.12",
    "react-native": "^0.45.1",```

**Comment by edude03** [comment]
I'm having the same issue

**Comment by bullantt** [comment]
Im having the same issue anyone find a fix??

**Comment by edude03** [comment]
Yes actually, it's surprisingly easy, change `"react": "^16.0.0-alpha.12",` to `"react": "16.0.0-alpha.12",` (note the lack of `^` in the latter). It turns out that FB released alpha 16.0.0-13 which is broken.

**Comment by SupriyaKalghatgi** [comment]
@flyandi @bullantt Did you try with he above solution?

**Comment by smooJitter** [comment]
While I'm not getting an error, StyleProvider still does not recognize children.  Because I don't get an error, I have nothing to show.   The material theme should change change the background of the Header to blue, but it doesn't

**Comment by shivrajkumar** [comment]
@flyandi @edude03 This issue arrises with `react: 16.0.0-alpha.13`. For now you can use 16.0.0-alpha.12. This will be fixed in the next patch i.e, 2.3.1

**Comment by akhil-geekyants** [comment]
Please let us know if you still face any issue.
