### ISSUE TITLE
Duplicate module name: StaticContainer.react

### ISSUE THREAD

**Issue by openqubit** [GeekyAnts/NativeBase#933]
I am trying to run an android app and i am getting this error

```
Loading dependency graph...
Bundling `index.android.js`
  Analysing...Failed to build DependencyGraph: @providesModule naming collision:
  Duplicate module name: StaticContainer.react
  Paths: C:/Users/user/mt\node_modules/react-static-container/lib/StaticContainer.react.js collides with C:/Users/user/mt\node_modules/react-native/Libraries/Components/StaticContainer.js

This error is caused by a @providesModule declaration with the same name across two different files.
Error: @providesModule naming collision:
  Duplicate module name: StaticContainer.react
  Paths: C:/Users/user/mt\node_modules/react-static-container/lib/StaticContainer.react.js collides with C:/Users/user/mt\node_modules/react-native/Libraries/Components/StaticContainer.js

This error is caused by a @providesModule declaration with the same name across two different files.
    at HasteMap._updateHasteMap (C:/Users/user/mt/node_modules/react-native/packager/src/node-haste/DependencyGraph/HasteMap.js:158:13)
    at module.getName.then.name (C:/Users/user/mt/node_modules/react-native/packager/src/node-haste/DependencyGraph/HasteMap.js:119:31)
Press any key to continue . . .
```

**Comment by kabala** [comment]
I got the same error today. Checking how can I resolve it.

**Comment by kabala** [comment]
+1

**Comment by openqubit** [comment]
@kabala Unfortunately I wasn't able to solve the issue so I just closed the issue and moved away from native base.

**Comment by shivrajkumar** [comment]
@kabala Could you please specify the version of native-base.
And also, are you using `react-native-router-flux`. If yes, which version?

**Comment by kabala** [comment]
Hi, I'm using "native-base": "2.1.1",, no react-native-flux. I've cloned this repo that's giving me the error https://github.com/start-react/native-starter-kit/

**Comment by SupriyaKalghatgi** [comment]
Native Starter Kit [#110](https://github.com/start-react/native-starter-kit/issues/110)

**Comment by sankhadeeproy007** [comment]
@kabala It's a version conflict. `react-static-container` has been removed in react 16.0.0 onwards. Upgrading native-base to latest should fix this issue.

**Comment by kabala** [comment]
Hi, the problem was related with watchman installed globally. I uninstalled it and now it's working! Thx very much guys!
