### ISSUE TITLE
PBXCp Error No Such File or Directory Error for Certain Fonts

### ISSUE THREAD

**Issue by MaxwellGover** [GeekyAnts/NativeBase#936]
I'm trying to build my react native project onto my actual device but these errors are causing the build to fail.

<img width="881" alt="screen shot 2017-06-11 at 9 31 43 pm" src="https://user-images.githubusercontent.com/11525891/27016610-e68f4f5e-4eef-11e7-9854-cdefc44be76b.png">

```
CpResource /Users/maxwellgover/Desktop/nimbus/node_modules/native-base/Fonts/Arial\ Black.ttf /Users/maxwellgover/Library/Developer/Xcode/DerivedData/nimbus-dwhroufdxzvgkcajekmlbluemoyy/Build/Products/Debug-iphoneos/nimbus.app/Arial\ Black.ttf
    cd /Users/maxwellgover/Desktop/nimbus/ios
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    builtin-copy -exclude .DS_Store -exclude CVS -exclude .svn -exclude .git -exclude .hg -resolve-src-symlinks /Users/maxwellgover/Desktop/nimbus/node_modules/native-base/Fonts/Arial\ Black.ttf /Users/maxwellgover/Library/Developer/Xcode/DerivedData/nimbus-dwhroufdxzvgkcajekmlbluemoyy/Build/Products/Debug-iphoneos/nimbus.app
```

## react-native, react and native-base version
react-native-cli: 2.0.1
react-native: 0.44.0
nativebase: 0.2.0

## Expected behaviour
Not cause the xcode build to fail.

## Actual behaviour
Causes xcode build to fail.

## Steps to reproduce (code snippet or screenshot)
Try building onto actual device.

## Is the bug present in both ios and android or in any one of them?
ios

**Comment by MaxwellGover** [comment]
Going to resources folder in xcode and deleting all the fonts highlighted in red solved the issue.

**Comment by ohtangza** [comment]
Any guess why it happened?
