### ISSUE TITLE
input ref cant be accessed from this.ref, What is the whole point of input if I cant get its value

### ISSUE THREAD

**Issue by engramyosama6** [GeekyAnts/NativeBase#94]
< Input placeholder="FOO" ref="FOO" />

FOO.boo = this.refs.FOO.value; //undefined

**Comment by pwoltman** [comment]
This is related to how InputGroup works by cloning the child Input (inadvertently removing refs) - same cause as issue #70 

I haven't found a workaround yet.

**Comment by pwoltman** [comment]
Update: see https://github.com/GeekyAnts/NativeBase/issues/70#issuecomment-239933501

**Comment by sankhadeeproy007** [comment]
Fixed in 0.5.5. Thanks @pwoltman !
