### ISSUE TITLE
Floating label inputs overlapping

### ISSUE THREAD

**Issue by charloh** [GeekyAnts/NativeBase#941]
Hi! Thanks for trying out NativeBase!
Due to the overwhelming requests and issues/questions we ask you to add the following details with your issue.

Please check the existing open/closed issues for a possible duplicate before creating a new issue :)

Also **DO** fill out the below form to give us a better idea about your environment and help us debug it quicker. Issues without the required details will mostly be unattended to.

**Comment by SupriyaKalghatgi** [comment]
Fixed with NativeBase 2.1.5
#627

**Comment by pinchez254** [comment]
here is the fix https://github.com/GeekyAnts/NativeBase/issues/627#issuecomment-427930681
