### ISSUE TITLE
PBXCp Error Missing Fonts in Xcode

### ISSUE THREAD

**Issue by pukeanddie** [GeekyAnts/NativeBase#945]
upgrading existing RN 0.44 project with native-base 2.1.5

npm install --save native-base
react-native link native-base

open Xcode (after clean and restart) build fails with several PBXCp errors for missing font files:

> error: /Users/random.person/ReactNative/RandomProject/node_modules/native-base/Fonts/Andale Mono.ttf: No such file or directory

or in terminal with react-native run-ios

> CpResource /Users/random.person/ReactNative/RandomProject/node_modules/native-base/Fonts/Andale\ Mono.ttf build/Build/Products/Debug-iphonesimulator/SaveAs.app/Andale\ Mono.ttf

**Comment by pukeanddie** [comment]
I was able to resolve this issue with the following steps. (perhaps steps 1 & 3 aren't even necessary)
1) react-native unlink native-base
2) removing font files in Resources folder within xcode
3) react-native link native-base

**Comment by AshokICreate** [comment]
Make sure you have native-base installed.

npm install  native-base --save

**Comment by cmmartin** [comment]
For whatever reason, using yarn instead of npm resolves this for me

**Comment by JGuiraud** [comment]
I had the same problem with react-native-vector-icons. I did what @natwales suggested (changing native-base by react-native-vector-icons, obviously). It did work!
