### ISSUE TITLE
[Question] Why many unresolved issue closed ??

### ISSUE THREAD

**Issue by cyclops24** [GeekyAnts/NativeBase#951]
Hi guys,
Recently I seen that a large number of issues closed but it's unresolved. If GeekyAnts don't need contributing with report issue please tell me. Users like me want to help open source community by report issue to reach a bug free and stable product.
Most of issues close by @SupriyaKalghatgi 👎 
These are issue list that I followed and closed without any result:
1. #668 
2. #669 
3. #612 
4. #776 
5. #941 
6. #662 
7. #739 
and more and more and more. 😢 

**/CC:** @SupriyaKalghatgi, @sankhadeeproy007

**Comment by openqubit** [comment]
@cyclops24  I am also wondering the same. In my opinion, making the toolkit compatible with  CRNA and Expo only works in the narrow world of make believe but having this work on plain react native is a very tall order indeed.

CRNA in itself has no place in the react native ecosystem and it seems to me like a predatory system  to get people to install the Expo IDE.  Divest your efforts from CRNA and things are going to turn around.

**Comment by sankhadeeproy007** [comment]
Hi @cyclops24 thanks for pointing it out. We try our best to emulate the use cases and reproduce the errors. It might happen in some cases that we are unable to reproduce the issues on our side. Hence we assume them to be fixed and close them.
We'll definitely take another look and make sure the issues are resolved. 
I'm reopening the issues for further analysis/development.

**Comment by sankhadeeproy007** [comment]
@openqubit The development for components are done in plain react-native itself and not CRNA.
We are in no way affiliated to Expo, there's no reason for us to make native-base compatible only for CRNA.
By the way did you see any difference in the behaviour of components in plain react-native and CRNA?

**Comment by openqubit** [comment]
" By the way did you see any difference in the behaviour of components in plain react-native and CRNA?"

Plenty.

**Comment by sankhadeeproy007** [comment]
"Plenty."

Examples? Screenshots? Code snippets?

**Comment by openqubit** [comment]
@sankhadeeproy007  I will put together screenshots and examples later.

**Comment by cyclops24** [comment]
@sankhadeeproy007 Thanks for your attention. I try reproduce issues for your team so you can check real issue simply.
I start with #669

**Comment by mnlbox** [comment]
And also this: #847

**Comment by cyclops24** [comment]
#881

**Comment by cyclops24** [comment]
#457

**Comment by mnlbox** [comment]
#176
