### ISSUE TITLE
Icons in footertab

### ISSUE THREAD

**Issue by nooralahzadeh** [GeekyAnts/NativeBase#954]
Hi, I am using footertab + icons in my application based on expo, means that I open simulator from expo!
In first step, when app is loaded, the icons do not appear in footer, but when I click over tab they can be seen!
Do i need to do some pre-load of cash the icons?
Any suggestion!
Thanks

**Comment by shivrajkumar** [comment]
@nooralahzadeh The issue seems to be with expo.
If you try just the @expo/vector-icons in a similar way, it you will see the same behaviour.

**Comment by nooralahzadeh** [comment]
So any suggestion!
Thanks.
