### ISSUE TITLE
DeckSwiper feels clunky

### ISSUE THREAD

**Issue by jarnell** [GeekyAnts/NativeBase#957]
I'm trying out DeckSwiper but the animation feels a bit clunky. If I don't swipe the card fast enough, it "jumps" to the next card: http://imgur.com/a/L4DwQ (slow-mo)

This is just a fixed-size grey View inside a DeckSwiper.

Is this how the component is intended to work, or is it a bug?

**Comment by dasveloper** [comment]
Especially when it hangs for the last few frames with just the corner in, or if you're swiping too fast you may pull a card back that was already well on its way the other way, even the buttons on the "advanced deckswiper" have a very long delay before activating the swipe.

**Comment by lulul62** [comment]
Same for me, tested on different device (Galaxy tab s2, Iphone 7, galaxy S7)

**Comment by hoekma** [comment]
Ditto for me.  Interestingly it works fine in the kitchen sink app.  I wonder if this is a debug-mode problem?  perhaps someone else can try that?  I'm having problems with Redux dispatch() right now running outside of debug mode locking up my app that I'm working through so I'm unable to test it right now.

**Comment by akhil-geekyants** [comment]
Performance Issue. Marking as duplicate. See issue #826
