### ISSUE TITLE
DeckSwiper doesn't have any function swipeLeft / right?

### ISSUE THREAD

**Issue by jacob-cross99** [GeekyAnts/NativeBase#958]
```
 <DeckSwiper
             activeOpacity={1}
             dataSource={ listings }
             ref={(deckSwiper) => console.log(deckSwiper)}
             renderItem={(listing) => getListingCard(listing)}
             onSwipeLeft={(listing) => this.onSwipe(true, listing)}
             onSwipeRight={(listing) => this.onSwipe(false, listing)}
           ></DeckSwiper>
```
When I console.log(deckSwiper) there is no function swipeLeft, or swipeRight on _root or any other properties. In other versions I had those functions but now I don't.

I'm developing using NativeBase ^2.1.5, and React Native 0.45.1.

**Comment by lsps9150414** [comment]
@shivrajkumar which version can we get the fix? https://github.com/GeekyAnts/NativeBase/commit/f7f6829e4a3ada2a616a00e37aaccafe4cd27294

**Comment by shivrajkumar** [comment]
@lsps9150414 This will be released with the next version today.

**Comment by lsps9150414** [comment]
@shivrajkumar Nice!!!

**Comment by shivrajkumar** [comment]
Check the latest version 2.2

**Comment by lsps9150414** [comment]
@shivrajkumar Tried v.2.2 still can't find `swipeLeft ` or `swipeRight` method. Where should I look for them?

```javascript
<Swiper
    ref={(swiper) => { this.Swiper = swiper; }}
/>
```

```javascript
handleNoOnPress() {
    console.log(this.Swiper);  // can't find them
    this.Swiper.swipeLeft();  // gives `this.Swiper.swipeLeft is not a function`
}
```

**Comment by jarnell** [comment]
@lsps9150414 try `this.Swiper._root.swipeLeft()`

**Comment by shivrajkumar** [comment]
@lsps9150414 Check https://github.com/GeekyAnts/NativeBase-KitchenSink/blob/master/js/components/deckswiper/advanced.js for this implementation

**Comment by lsps9150414** [comment]
@jarnell @shivrajkumar Thanks!
