### ISSUE TITLE
Support more <InputGroup> properties

### ISSUE THREAD

**Issue by mrphu3074** [GeekyAnts/NativeBase#96]
Hi, 

I think we should support 2 properties to `InputGroup` are : `disabled` <bool>   and `errorText` <string>. It make easier when you work with form.

Thanks,
I really love `native-base`

**Comment by sankhadeeproy007** [comment]
`disabled`, `error` & `success` props added to inputgroup.

**Comment by mrphu3074** [comment]
👍
