### ISSUE TITLE
Using Icon's ios and android attributes within ReactNative-Typescript project

### ISSUE THREAD

**Issue by haythem-ouederni** [GeekyAnts/NativeBase#960]
Hi the team,

I have been facing a problem using the `Icon` element within a `ReactNative` project that uses `Typescript`. And here are the different details.

Thank you for your help :)

## Librairies versions : 
react-native: 0.44.0
react : 16.0.0-alpha.6
native-base : 2.1.5
typescript : 2.4.0

## Expected behaviour
No Typescript validation error when using the ios and android attributes on the Icon tag. In addition to the fact to be able to use Icon without a `name` attribute as we can see in the [documentation example](https://docs.nativebase.io/Components.html#icon-def-headref).

Example : 
```` jsx
<Icon ios="ios-trash-outline" android="md-trash"/>
````
## Actual behaviour
Typescript throws an error telling me that `ios` and `android` attributes are not supported for the Icon tag: 
````
error TS2322: Type '{ ios: "ios-trash-outline"; android: "md-trash"; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<Icon> & Readonly<{ children?: ReactNode; }> & Read...'.
  Type '{ ios: "ios-trash-outline"; android: "md-trash"; }' is not assignable to type 'Readonly<Icon>'.
    Property 'name' is missing in type '{ ios: "ios-trash-outline"; android: "md-trash"; }'.
````
## Suggested fix
I have fixed this problem locally by editing the `index.d.ts`file at the root of the NativeBase node module. I have changed the declaration of the Icon interface as follows : 
```` typescript
    /**
         * see Widget Icon.js
         */
    interface Icon {
      name?: string;
      style?: ReactNative.TextStyle;
      active?: boolean;
      ios?: string;
      android?: string;
      color?: string;
      fontSize?: number;
    }
```` 

Is it possible to have this fix in a coming release ?

Thank you :)

**Comment by shivrajkumar** [comment]
Added in the latest release v2.2

**Comment by haythem-ouederni** [comment]
thanks @shivrajkumar :)

**Comment by wardjk87** [comment]
This fix has been removed in current version of index.d.ts for native base 2.12.1. 
lines 642-653
`interface Icon extends Testable {
			name: string;
			type?: "AntDesign" | "Entypo" | "EvilIcons" | "Feather" | "FontAwesome" | "FontAwesome5" | "Foundation" | "Ionicons" | "MaterialCommunityIcons" | "MaterialIcons" | "Octicons" | "SimpleLineIcons" | "Zocial";
			// TODO position attribute of ReactNative.FlexStyle hasn't another position values without "absolute" and "relative"
			style?: any;
			onPress?: (e?: any) => any;
			active?: boolean;
			ios?: string;
			android?: string;
			color?: string;
			fontSize?: number;
		}`
