### ISSUE TITLE
this.inputProps is undefined

### ISSUE THREAD

**Issue by ifalldev** [GeekyAnts/NativeBase#967]
Hi!

I'm facing this error: `this.inputProps is undefined`, that refers to `node_modules/native-base/src/basic/Item.js 23:19` which is this:

```
componentDidMount() {
    if (this.inputProps.value) {
      this.setState({ isFocused: true });
      this.floatUp(-16);
    }
    if (this.inputProps && this.inputProps.getRef)
      this.inputProps.getRef(this._inputRef);
  }
```

My workaround is as simple as it can be, I forced the first validation as the second resulting this:
`if (this.inputProps && this.inputProps.value)`.

Just documenting to contributors and users that may have this issue.

**Comment by mativs** [comment]
Hi @shivrajkumar  do you know when this fix will be released?

**Comment by shivrajkumar** [comment]
@mativs The fix will be released with the next version by end of this week.

**Comment by mativs** [comment]
Awesome, thanks!!

**Comment by flyandi** [comment]
Running into the same issue.. Has this been resolved? It's a really annoying issue. 

Is this in dev-master already?

**Comment by shivrajkumar** [comment]
@flyandi Did you try the latest version 2.2.0. This has been fixed

**Comment by ignivaashwani** [comment]
kl

**Comment by ignivaashwani** [comment]
@shivrajkumar In the latest version  2.2.0 action sheet is no working

**Comment by shivrajkumar** [comment]
@ignivaashwani What is the error that you are getting.
And also make sure to check the docs for the use case as with the latest version, the use case has slightly changed
