### ISSUE TITLE
I have problem with floating label input

### ISSUE THREAD

**Issue by boyinfotronics** [GeekyAnts/NativeBase#968]
I have problem with floating label input 

    "native-base": "2.1.0",
    "react": "15.4.2",
    "react-native": "0.42.0",

![image](https://user-images.githubusercontent.com/25657869/27297133-dd5ff4f6-554d-11e7-8f6f-e8dc61c7f510.png)

**Comment by shivrajkumar** [comment]
#627

**Comment by slorber** [comment]
@shivrajkumar for me this issue is not resolved in 2.2.1, and is the same as https://github.com/GeekyAnts/NativeBase/issues/1073
