### ISSUE TITLE
<Content> tag is  not working. 

### ISSUE THREAD

**Issue by wethil** [GeekyAnts/NativeBase#97]
I check the docs and according to docs when we use <Content> tag, there suppose to be padding on left and right for body view. But still my content is adjacent with sides.  

Thanks..

**Comment by sankhadeeproy007** [comment]
use `padder` with content.

**Comment by wethil** [comment]
That is the solution. Thanks a lot!

**Comment by ar-nit** [comment]
![screenshot 66](https://cloud.githubusercontent.com/assets/11644819/19012225/9517ef38-87d9-11e6-9578-65b8e0921a4f.png)
Hi! guy, How to fix padding between Home button and another ? (I try v0.5.8 and v0.5.9 latest).

**Comment by SupriyaKalghatgi** [comment]
@ar-nit Check [NativeBase-KitchenSink](https://github.com/GeekyAnts/NativeBase-KitchenSink)

This demonstrates usage of all NativeBase components.

![button](https://cloud.githubusercontent.com/assets/13464885/20344276/1d7d3dee-ac18-11e6-8986-3381dda2987c.png)
