### ISSUE TITLE
Native base update issue [Urgent]

### ISSUE THREAD

**Issue by CliveTeow** [GeekyAnts/NativeBase#971]
## react-native, react and native-base version
react-native: 0.44.3
react: 16.0.0-alpha.13
native-base: 2.1.5
## Expected behaviour
After updated native base, the app able to run as usual
## Actual behaviour
Have error after updated native base
## Screenshot of emulator/device
![screen shot 2017-06-21 at 3 26 49 pm](https://user-images.githubusercontent.com/19527543/27372135-1914bcd6-5696-11e7-9f5e-5f31c8858c77.png)

## Is the bug present in both ios and android or in any one of them?
Both

**Comment by shivrajkumar** [comment]
@CliveTeow Seems to work for the above versions.
Try deleting node_modules and installing again.

**Comment by CliveTeow** [comment]
@shivrajkumar You mean the node_modules folder in the project?

**Comment by shivrajkumar** [comment]
Yes

**Comment by CliveTeow** [comment]
Still not working

**Comment by CliveTeow** [comment]
I changed back the react version to react: 16.0.0-alpha.6, then seems no more issue.
react-native: 0.44.3
react: 16.0.0-alpha.6
native-base: 2.1.5

**Comment by CliveTeow** [comment]
But why all the inputs height seem shrunk? Can't see the placeholder of the input.
![screen shot 2017-06-21 at 4 19 48 pm](https://user-images.githubusercontent.com/19527543/27374179-7d7eea6e-569d-11e7-9a60-4e56f108ef6a.png)

**Comment by shivrajkumar** [comment]
@CliveTeow Have you ejected the theme?

**Comment by CliveTeow** [comment]
@shivrajkumar I ejected last time. After upgraded native base, do I need to eject it again?

**Comment by CliveTeow** [comment]
@shivrajkumar It is now working. Thanks. :)
