### ISSUE TITLE
iconFamily not working in the header?

### ISSUE THREAD

**Issue by njt1982** [GeekyAnts/NativeBase#973]
## react-native, react and native-base version

```
react-native@0.44.3
react@16.0.0-alpha.6
native-base@2.1.5
```

## Expected / Actual behaviour
`<Icon name="pencil" />` works everywhere else (using `FontAwesome` as my `iconFamily` in my theme). But in the header, I get an error which indicates the family has reverted to the default Ionicons. Which has no pencil or edit icon ;)

## Steps to reproduce (code snippet or screenshot)

<Icon name="pencil" />`

![pasted_image_21_06_2017__16_33](https://user-images.githubusercontent.com/384976/27392858-aed584c2-569f-11e7-8c32-2a0606ae48c4.jpg)

Any ideas?

**Comment by shivrajkumar** [comment]
![screen shot 2017-06-28 at 1 20 19 pm](https://user-images.githubusercontent.com/17001305/27626147-99e1c82c-5c04-11e7-8acd-e4e5cc159d99.png)
@njt1982 This seems to be working.
Make sure that the Header component is also wrapped inside StyleProvider.

**Comment by njt1982** [comment]
Thanks @shivrajkumar - I did eventually get it working with that, but the icon ended up being rejected during QA as it didn't look right.

Ended up with this:

```
<Button transparent onPress={() => params.showAddComment() } ><Icon style={styles.headerButton} name="ios-chatbubbles-outline" /></Button>
```

But StyleProvider is the working approach for this. TBH not sure why it doesn't use the default theme setting?!

**Comment by shivrajkumar** [comment]
@njt1982 The default theme of native-base has Ionicons as the default Icons.
To override that, new/modified theme has to be passed to the components, which is Icon in this case. And theme passed through StyleProvider merges/overrides the default theme.
