### ISSUE TITLE
<Right> does not work in List

### ISSUE THREAD

**Issue by pkassonss** [GeekyAnts/NativeBase#974]
I am copying examples from KitchenSink into a NativeBase GitHub base project, and when I add either the <Left> or <Right> it cause the error (below)

Here is my config:

    "native-base": "https://github.com/GeekyAnts/NativeBase#master",
    "react": "^15.5.4",
    "react-native": "^0.42.3",

....

Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in. Check the render method of `StaticRenderer`.

Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. Check the render method of `StaticRenderer`.

Unhandled JS Exception: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. Check the render method of `StaticRenderer`.

**Comment by shivrajkumar** [comment]
@pkassonss Check the compatibility
http://docs.nativebase.io/docs/Compatibility.html
