### ISSUE TITLE
TypeError: Cannot read property 'value' of undefined 

### ISSUE THREAD

**Issue by CliveTeow** [GeekyAnts/NativeBase#976]
# react-native, react and native-base version
react-native: 0.45.1
react: react@16.0.0-alpha.12
native-base: 2.1.5
## Expected behaviour
Everything working fine.
## Actual behaviour
There are some errors from native base.
## Steps to reproduce (code snippet or screenshot)
After clicked a button/ radio, will show the error
## Screenshot of emulator/device
![screen shot 2017-06-22 at 7 05 52 pm](https://user-images.githubusercontent.com/19527543/27431139-fcb07682-577d-11e7-9ecb-f47e906e9a5f.png)

TypeError: Cannot read property 'value' of undefined
    at Item.componentDidMount (Item.js:23)
    at ReactCompositeComponent.js:377
    at measureLifeCyclePerf (ReactCompositeComponent.js:63)
    at ReactCompositeComponent.js:376
    at CallbackQueue.notifyAll (CallbackQueue.js:75)
    at ReactNativeReconcileTransaction.close (ReactNativeReconcileTransaction.js:36)
    at ReactNativeReconcileTransaction.closeAll (Transaction.js:223)
    at ReactNativeReconcileTransaction.perform (Transaction.js:165)
    at ReactUpdatesFlushTransaction.perform (Transaction.js:152)
    at ReactUpdatesFlushTransaction.perform (ReactUpdates.js:77)

Also trigger this error after the above error happened:
![screen shot 2017-06-22 at 7 12 21 pm](https://user-images.githubusercontent.com/19527543/27431368-ebc303a2-577e-11e7-9d32-430124bd0d44.png)

In Android, have this error as well(while showing TypeError: Cannot read property 'value' of undefined):
![screen shot 2017-06-22 at 7 38 33 pm](https://user-images.githubusercontent.com/19527543/27432447-b9ef7320-5782-11e7-873a-0e398416ffac.png)
#
## Is the bug present in both ios and android or in any one of them?
Both

**Comment by dylannlaw** [comment]
I am having exactly same error with the same package version for react, react native and native base.

@CliveTeow have you found any solutions for this?

**Comment by dylannlaw** [comment]
@buzzswarbrick there is actually a pull request that fixed this issue. Let's wait for a new release.
https://github.com/GeekyAnts/NativeBase/pull/938

**Comment by kitsune7** [comment]
I have the same issue with the same versions, but it happens even after I downgrade nativebase to 2.1.4. I also can't get the temporary fix in `Items.js` to actually get used in the bundle.

**Comment by shivrajkumar** [comment]
Fixed in the latest version 2.2.0
