### ISSUE TITLE
[Suggestion] Hamburger component

### ISSUE THREAD

**Issue by mnlbox** [GeekyAnts/NativeBase#981]
Hi guys,
Today I found [this other repo from GeekyAnts](https://github.com/GeekyAnts/react-native-hamburger) accidentally and It's very beautiful. I suggest to merge this as a new component to NativeBase or make a working example about "how integrate Hamburger with NativeBase Drawer?"

Thanks for your attention. 😉

**Comment by mnlbox** [comment]
@SupriyaKalghatgi any news about this?

**Comment by SupriyaKalghatgi** [comment]
Closing this, as NativeBase wont be adding this
