### ISSUE TITLE
[Bug] Content typings lacking contentContainerStyle definition

### ISSUE THREAD

**Issue by luchillo17** [GeekyAnts/NativeBase#984]
## react-native, react and native-base version
react@16.0.0-alpha.6
react-native@0.44.3
native-base@2.1.5

## Expected behaviour
To actually allow me to use `contentContainerStyle` in my `Content` component with typescript.

## Actual behaviour
VSCode end's up yelling at me for the tipings, i would end up taking hours thinking i wasn't doing it right until i tried the actual code and it worked on the emulator.

## Steps to reproduce (code snippet or screenshot)
![image](https://user-images.githubusercontent.com/9698639/27524226-cbffb35e-59f8-11e7-83ec-344ae20e9a6b.png)

## Is the bug present in both ios and android or in any one of them?
The error is about typings lacking the correct definition, the code works as expected.
## Any other additional info which would help us debug the issue quicker.
Here's the actual NativeBase definition, it lacks `contentContainerStyle`, thus the editor and compilator complains and doesn't allow me to start, i have to comment out, start compilator, and then uncomment:
![image](https://user-images.githubusercontent.com/9698639/27525514-1d5591c8-5a04-11e7-84de-3dc0017b63a3.png)

## Temporal workaround by merging custom typings
The following settle down the errors from `tsc` and `VSCode`:
```ts
import { ViewStyle } from 'react-native'
import { Content } from 'native-base'

declare module 'native-base' {
  namespace NativeBase {

    interface Content {
      contentContainerStyle?: ViewStyle
    }
  }
}
```

**Comment by shivrajkumar** [comment]
Added in v2.2.0
