### ISSUE TITLE
'shoutem/animation' is not in the npm registry.

### ISSUE THREAD

**Issue by samsiu2014** [GeekyAnts/NativeBase#986]
I'm new to react native and github.
I need to say sorry first if i didn't follow the rules or did anything incorrect.
I searched a few hours but i cannot find out the way to solve this problem.
When I used npm i native-base --save command.
The error "'shoutem/animation' is not in the npm registry." is popped out.
![image](https://user-images.githubusercontent.com/26761164/27532103-b1221c9a-5a91-11e7-80d6-7ffa0d417bd1.png)

I tried to browser the https://registry.npmjs.org/shoutem/animation
and i just saw an empty {}.
![image](https://user-images.githubusercontent.com/26761164/27532118-befe6346-5a91-11e7-86cc-53d255ae5ade.png)

Meanwhile, comparing to other links like https://registry.npmjs.org/print-message
there should be some codes or words inside.
![image](https://user-images.githubusercontent.com/26761164/27532136-d402ab80-5a91-11e7-864d-28b2062fac43.png)

I'm not sure if I missed something. Please let me know what can I do.
Thank you!

**Comment by horiuchie** [comment]
Your npm might be too old.

_System Requirements_ ( [From docs](https://docs.nativebase.io/docs/GetStarted.html) )
_・Globally installed node >= 6.0
・Globally installed npm >= 4.0_

**Comment by samsiu2014** [comment]
Thanks dude!
My problem solved after I deleted the npm installed by chocolatey.
