### ISSUE TITLE
Switch component does support touch events

### ISSUE THREAD

**Issue by jrempel1** [GeekyAnts/NativeBase#988]
Expected Usage:
`<Switch onPress={toggleSwitch()} />`

The switch component does not appear to implement touchable opacity or support any touch events

**Comment by shivrajkumar** [comment]
@jrempel1 Switch doesn't take the prop `onPress`.
Use `onValueChange` for callback function and `value` for boolean true or false

**Comment by jrempel1** [comment]
@shivrajkumar thanks. onValueChange works. I think documentation for this component should be updated. If want I can create a pull request

**Comment by sankhadeeproy007** [comment]
Please, that would be awesome!

**Comment by SupriyaKalghatgi** [comment]
Updated docs with `Switch` details

Check [here](https://docs.nativebase.io/Components.html#list-icon-headref)
