### ISSUE TITLE
CheckBoxes not responding in List

### ISSUE THREAD

**Issue by hszeto** [GeekyAnts/NativeBase#989]
What's the proper way to handle a list of checkboxes? I've the following code, but the checkboxes just don't respond to my clicks on both iOS and Android emulators.

I have:
```
"native-base": "2.1.3",
"react": "16.0.0-alpha.3",
"react-native": "0.43.2", 
```

Here is the code:
```
import React, { Component } from 'react';
import { Container, Content, Item, List,
         CheckBox, Body, ListItem, Text } from 'native-base';

class SelectFriends extends Component {
  constructor(props) {
    super(props);

    this.state = {
      friends: [{ id: 10, name:"Gundam" },
                { id: 20, name:"Rambo" },
                { id: 30, name:"Mickey Mouse" } ],
      checkBoxChecked: false
    };
  }


  onCheckBoxPress(id) {
    console.log( "Checked!" );
    console.log( id );
    this.setState({
      checkBoxChecked: !this.state.checkBoxChecked
    });
  }

  render() {
    return(
      <Container>
        <Content>
          <Item>
            <List dataArray={this.state.friends}
              renderRow={(friend) =>
                <ListItem>
                  <CheckBox
                    checked={this.state.checkBoxChecked}
                    onPress={()=>this.onCheckBoxPress(friend.id)}
                  />
                  <Body>
                    <Text>{friend.name}</Text>
                  </Body>
                </ListItem>
              }
            >
            </List>
          </Item>
        </Content>
      </Container>
    );
  }
};

export default SelectFriends;
```

The console.log works on clicks... so it's somewhat working... 

I've tried nativebase version 2.1.4 and 2.1.5. Got tons of build errors, so I went back to 2.1.3....

**Comment by shivrajkumar** [comment]
@hszeto The issue seems to be with List. Will be fixed in next release.
Use ListView of React Native for now. Something like this
![screen shot 2017-06-27 at 7 26 18 pm](https://user-images.githubusercontent.com/17001305/27591309-e58406fa-5b6e-11e7-9b0e-21d31fd95dce.png)

**Comment by hszeto** [comment]
@shivrajkumar Thanks for the help! it works... however, only 1 user can be checked. Sort of behaving like a radio button now....

**Comment by hszeto** [comment]
Thanks @shivrajkumar . I made some tweaking to your code... the checkboxes work now.

```
import React, { Component } from 'react';
import { ListView } from 'react-native';
import { Container, Content, Item, List,
         CheckBox, Body, ListItem, Text } from 'native-base';

class SelectFriends extends Component {
  constructor(props) {
    super(props);

    this.state = {
      friends: [{ id: 10, name:"Gundam" },
                { id: 20, name:"Rambo" },
                { id: 30, name:"Mickey Mouse" } ],
      selectedFriendId: []
    };
  }


  onCheckBoxPress(id) {
    let tmp = this.state.selectedFriendId;

    if ( tmp.includes( id ) ) {
      tmp.splice( tmp.indexOf(id), 1 );
    } else {
      tmp.push( id );
    }

    this.setState({
      selectedFriendId: tmp
    });
  }

  render() {
    return(
      <Container>
        <Content>
          <Item>
            <ListView
              enableEmptySections={true} 
              dataSource={ds.cloneWithRows(this.state.friends)}
              renderRow={(friend) =>
                <ListItem>
                  <CheckBox
                    checked={this.state.selectedFriendId.includes(friend.id) ? true : false}
                    onPress={()=>this.onCheckBoxPress(friend.id)}
                  />
                  <Body>
                    <Text>{friend.name}</Text>
                  </Body>
                </ListItem>
              }
            />
          </Item>
        </Content>
      </Container>
    );
  }
};

export default SelectFriends;
```

**Comment by Nandez89** [comment]
Was this fixed on the new version like it was said? I'm on 2.3.1 and still have the same issue. The workaround doesn't work for me either :(

**Comment by maartenvandillen** [comment]
Same here. Using it in a FlatList and it's not updating after toggling the checked state.

**Comment by jayeshjain24** [comment]
Same issue. Checkbox not getting ticked.

**Comment by akhil-geekyants** [comment]
@jayeshjain24 tried hszeto's code with ReactNative FlatList.

Gif

![checkbox](https://user-images.githubusercontent.com/27768184/34405970-72acb3bc-ebdc-11e7-8f18-17292023c3aa.gif)

Code
```
import React, { Component } from 'react';
import { Container, Content, Item, CheckBox, Body, ListItem, Text } from 'native-base';
import { FlatList } from 'react-native'

export default class SelectFriends extends Component {
  constructor(props) {
    super(props);
    this.state = {
      friends: [{ id: 10, name: "Gundam" },
      { id: 20, name: "Rambo" },
      { id: 30, name: "Mickey Mouse" }],
      selectedId: 10
    };
  }

  onCheckBoxPress(value) {
    this.setState({
      selectedId: value
    });
  }

  render() {
    return (
      <Container>
        <Content>
          <Item>
            <FlatList
              extraData={this.state}
              keyExtractor={(item, index) => item.id}
              data={this.state.friends}
              renderItem={({ item }) => {
                return <ListItem>
                  <CheckBox
                    checked={this.state.selectedId == item.id}
                    onPress={() => this.onCheckBoxPress(item.id)}
                  />
                  <Body>
                    <Text>{item.name}</Text>
                  </Body>
                </ListItem>
              }}
            />
          </Item>
        </Content>
      </Container>
    );
  }
};

```

**Comment by teddyteh** [comment]
For those who have an issue with Flatlists, add this as a prop to Flatlist itself:
extraData={this.state}

**Comment by tk26** [comment]
This is a combination of FlatList with multiple selection.

import React, { Component } from 'react';
import { Container, Content, View, Text, Button, List, ListItem, CheckBox, Body, Item } from 'native-base';
import { FlatList } from 'react-native';

var Contacts = require('react-native-contacts')

const initialState = {
    contacts: [],
    selectedChecklist: []
}

export default class InviteUsers extends Component {
    constructor(props) {
        super(props);
        this.state = initialState;
    }

    componentDidMount() {
        Contacts.getAll((err, contacts) => {
            if(err === 'denied'){
                // error
            } else {
                // contacts returned in []
                this.setState({
                    contacts: contacts.map(contact => { return {
                        id: contact.recordID,
                        name: contact.givenName + " " + contact.familyName,
                        phoneNumber: contact.phoneNumbers[0].number,
                    }})
                });
            }
        });
    }

    onCheckBoxPress(id) {
        let tmp = this.state.selectedChecklist;

        if ( tmp.includes( id ) ) {
            tmp.splice( tmp.indexOf(id), 1 );
        } else {
            tmp.push( id );
        }

        this.setState({
            selectedChecklist: tmp
        });
    }

    sendInvites() {
        alert(JSON.stringify(this.state.selectedChecklist));
    }

    render() {
        return (
            <Container>
                <Content>
                    <View>
                        <Text>
                            Select one or more contacts and hit "Send"
                        </Text>
                         <Item>
                            <FlatList
                                extraData={this.state}
                                keyExtractor={(item, index) => item.id}
                                data={this.state.contacts}
                                renderItem={({ item }) => {
                                    return <ListItem>
                                    <CheckBox
                                        checked={this.state.selectedChecklist.includes(item.id) ? true : false}
                                        onPress={() => this.onCheckBoxPress(item.id)}
                                    />
                                    <Body>
                                        <Text>{item.name}</Text>
                                    </Body>
                                    </ListItem>
                                }}
                            />
                        </Item>
                        <Button rounded info onPress = { () => this.sendInvites() }>
                            <Text>
                                Send
                            </Text>
                        </Button>
                    </View>
                </Content>
            </Container>
        );
    }
}

**Comment by tk26** [comment]
This is a working example of FlatList with multiple select:

<img width="941" alt="screen shot 2018-02-12 at 12 23 15 am" src="https://user-images.githubusercontent.com/6154318/36085383-08b29620-0f8b-11e8-9962-2c535e34d31d.png">
<img width="877" alt="screen shot 2018-02-12 at 12 23 39 am" src="https://user-images.githubusercontent.com/6154318/36085384-08bd7bb2-0f8b-11e8-8619-008347c88fae.png">

**Comment by gid30n** [comment]
@tk26 thx man you save my day! hope good things will always come up to your life dude

**Comment by ritzblogs** [comment]
This solution worked for me
https://abodeofmystories.blogspot.com/2021/07/ReactNative-Checkbox-cant-be-pressed-more-than-1-time-Android.html
