### ISSUE TITLE
Header buttons

### ISSUE THREAD

**Issue by ErkanSen14** [GeekyAnts/NativeBase#99]
Hello, 
I have some content laid out like this:

```
<Header>

<Button>
</Button>

<Title>
</Title>

<Button>
</Button>

</Header>
```

but it seems that the left button is not clickable; in fact it seems that the left button isn't even being detected as a button. 
<img width="377" alt="screen shot 2016-08-04 at 4 42 38 pm" src="https://cloud.githubusercontent.com/assets/17013914/17419374/bef96650-5a62-11e6-88eb-ed31636f2da4.png">
<img width="374" alt="screen shot 2016-08-04 at 4 42 49 pm" src="https://cloud.githubusercontent.com/assets/17013914/17419375/bf072d6c-5a62-11e6-896b-bd8831e455fb.png">
<img width="373" alt="screen shot 2016-08-04 at 4 42 56 pm" src="https://cloud.githubusercontent.com/assets/17013914/17419376/bf0b94f6-5a62-11e6-93c8-23fe527b5d1a.png">

**Comment by sankhadeeproy007** [comment]
I've fixed it. You can use from master till we release our next update.

**Comment by ErkanSen14** [comment]
Thanks, it's working now!
