### ISSUE TITLE
Blank cards inside list

### ISSUE THREAD

**Issue by pranay414** [GeekyAnts/NativeBase#991]
Hi, 
I am trying to add two cards as a list item in List, but I am getting a blank card with nothing inside it. Where am I going wrong?

![screen shot 2017-06-27 at 7 13 16 pm](https://user-images.githubusercontent.com/16045021/27590557-b52dcb3c-5b6c-11e7-9b72-778b0da47334.png)

**Comment by shivrajkumar** [comment]
@pranay414 Please share your code snippet to reproduce the issue

**Comment by pranay414** [comment]
<Content>
                    <Grid>
                        <Row style={{ paddingTop: 14 }}>
                            <Left style={{ alignItems: 'center' }}><Text style={{ fontWeight: 'bold', color: 'green' }}>Running:  10</Text></Left>
                            <Right style={{ alignItems: 'center' }}><Text style={{ fontWeight: 'bold', color: 'red' }}>Stationary:  5</Text></Right>
                        </Row>
                        <List>
                         <ListItem>
                            <Card>
                                <CardItem>
                                    <Text style={{ fontWeight: 'bold' }}>Distance</Text>
                                    <Right>
                                        <Text>{totalDistanceToday}</Text>
                                    </Right>
                                </CardItem>
                            </Card>
                        </ListItem>
                        <ListItem>
                            <Card>
                                <CardItem>
                                    <Text style={{ fontWeight: 'bold' }}>Trips</Text>
                                    <Right>
                                        <Text>{tripsToday}</Text>
                                    </Right>
                                </CardItem>
                            </Card>
                        </ListItem>
                        </List>
                    </Grid>
                </Content>

**Comment by shivrajkumar** [comment]
![screen shot 2017-06-29 at 12 38 56 pm](https://user-images.githubusercontent.com/17001305/27675506-f9263e8a-5cc7-11e7-86b0-8ebd2ccb5fb4.png)
@pranay414 Your code seems to work fine

**Comment by pranay414** [comment]
It fails in android!

**Comment by shivrajkumar** [comment]
@pranay414 Seems to work in android too.
![screenshot_20170630-194223](https://user-images.githubusercontent.com/17001305/27739545-9bfa063c-5dcc-11e7-8073-c51acc464b9d.jpg)

**Comment by pranay414** [comment]
Android 6.0

**Comment by shivrajkumar** [comment]
@pranay414 The above is a screenshot of Android 6.0 only.
Can you check this again.

**Comment by pranay414** [comment]
Sure!

**Comment by shivrajkumar** [comment]
@pranay414 Any updates here

**Comment by pranay414** [comment]
Yeah got it, thanks 👍

**Comment by wootwoot1234** [comment]
I'm having this same issue.  The list is blank when I load the screen but when I "pull" down on the list the screen refreshes and I see the content as I should see it.  Here are some screenshots:

![simulator screen shot - iphone 6 - 2017-10-24 at 15 10 43](https://user-images.githubusercontent.com/419609/31970819-4480ccbc-b8ce-11e7-923a-38fa0f49994b.png)

![simulator screen shot - iphone 6 - 2017-10-24 at 15 10 45](https://user-images.githubusercontent.com/419609/31970818-44557756-b8ce-11e7-893a-4eb71196c940.png)

Here's my code:

    import React, {Component} from "react";
    import {ListView} from "react-native";
    import {
        Container,
        Content,
        Button,
        Icon,
        List,
        ListItem,
        Text,
        Card,
        StyleProvider,
        Body,
        Header,
        Title,
        Left,
        Right
    } from "native-base";
    import getTheme from "../../native-base-theme/components";
    import commonColor from "../../native-base-theme/variables/commonColor";
    const datas = [
        "Simon Mignolet",
        "Nathaniel Clyne",
        "Dejan Lovren",
        "Mama Sakho",
        "Alberto Moreno",
        "Emre Can",
        "Joe Allen",
        "Phil Coutinho"
    ];
    export default class Shopping extends Component {
        constructor(props) {
            super(props);
            this.ds = new ListView.DataSource({rowHasChanged: (r1, r2) => r1 !== r2});
            this.state = {
                basic: true,
                listViewData: datas
            };
        }
        deleteRow(secId, rowId, rowMap) {
            rowMap[`${secId}${rowId}`].props.closeRow();
            const newData = [...this.state.listViewData];
            newData.splice(rowId, 1);
            this.setState({listViewData: newData});
        }
        render() {
            return (
                <StyleProvider style={getTheme(commonColor)}>
                    <Container>
                        <Header hasTabs>
                            <Left>
                                <Button transparent onPress={() => this.props.navigation.goBack()}>
                                    <Icon name="arrow-back" />
                                </Button>
                            </Left>
                            <Body>
                                <Title>Shopping</Title>
                            </Body>
                            <Right>
                                <Button transparent onPress={() => this.props.navigation.goBack()}>
                                    <Icon name="add" />
                                </Button>
                            </Right>
                        </Header>
                        <Content padder>
                            <Card>
                                <List
                                    dataSource={this.ds.cloneWithRows(this.state.listViewData)}
                                    onRowOpen={(secId, rowId, rowMap) => {
                                        rowMap[`${secId}${rowId}`].props.closeRow();
                                        console.log("asdfasdf");
                                    }}
                                    renderRow={data => (
                                        <ListItem>
                                            <Text> {data} </Text>
                                        </ListItem>
                                    )}
                                    renderLeftHiddenRow={data => (
                                        <Button full onPress={() => alert(data)}>
                                            <Icon active name="information-circle" />
                                        </Button>
                                    )}
                                    renderRightHiddenRow={(data, secId, rowId, rowMap) => (
                                        <Button full danger onPress={() => this.deleteRow(secId, rowId, rowMap)}>
                                            <Icon active name="trash" />
                                        </Button>
                                    )}
                                    leftOpenValue={75}
                                    rightOpenValue={-75}
                                />
                            </Card>
                            <Text style={{padding: 10}}>Note: Swipe to delete</Text>
                        </Content>
                    </Container>
                </StyleProvider>
            );
        }
    }


and

    import {StackNavigator} from "react-navigation";
    import List from "./list.js";
    import Shopping from "./shopping.js";
    export default (MainScreenNavigator = StackNavigator(
        {
            List: {screen: List},
            Shopping: {screen: Shopping}
        },
        {
            initialRouteName: "List",
            headerMode: "none"
        }
    ));

**Comment by luck2011** [comment]
@wootwoot1234 Same here! The swipe list is blank sometimes after a router changed for a little while! Do you have any solutions?

**Comment by jdnichollsc** [comment]
Same here

**Comment by luck2011** [comment]
@jdnichollsc Adding `renderScrollComponent={() => <ScrollView style={styles.list} />}` to `<List />` worked for me. Even this is `<List />`'s default value.
