### ISSUE TITLE
Styled components + Native Base incompatibility

### ISSUE THREAD

**Issue by Charlynux** [GeekyAnts/NativeBase#993]
Hello,

When I use styled-components with NativeBase components, I got this warning message :

> Warning: Failed prop type: Invalid prop `style` of type `array` supplied to `Styled(Button)`, expected `object`.

I find an issue on styled-components, with my exact error.
https://github.com/styled-components/styled-components/issues/645

So I give some additional informations and it seems to be a NativeBase problem.
https://github.com/styled-components/styled-components/issues/645#issuecomment-311354099

## Dependencies versions
"native-base": "2.1.5"
"react": "16.0.0-alpha.12"
"react-native": "0.45.1"
"styled-components": "2.1.0"

## Expected behaviour
Applying style to NativeBase components.

## Actual behaviour
Warning message.

## Steps to reproduce (code snippet or screenshot)
Run this project : https://github.com/Charlynux/StyledNativeBase

## Screenshot of emulator/device
![simulator_screenshot](https://user-images.githubusercontent.com/6061550/27597169-e826169e-5b61-11e7-85e3-64268735611d.png)

## Is the bug present in both ios and android or in any one of them?
Both iOS and Android

**Comment by JDansercoer** [comment]
+1

**Comment by shivrajkumar** [comment]
#575

**Comment by shivrajkumar** [comment]
@Charlynux @JDansercoer The latest of NativeBase 2.3.0 now accepts both array styles and StyleSheet.create.
